#!/bin/bash

CURR_DIR=$(pwd)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "GENERATING js_scodes using "${BASH_SOURCE[0]}

cd $SCRIPT_DIR

DIR_IN="../scod_tabs/"

node print_json_scodes.js ${DIR_IN}/BYZ_ref_scodes.tab BYZ
node print_json_scodes.js ${DIR_IN}/NES_ref_scodes.tab NES
node print_json_scodes.js ${DIR_IN}/WH_ref_scodes.tab WH
node print_json_scodes.js ${DIR_IN}/TR_ref_scodes.tab TR

node print_json_scodes.js ${DIR_IN}/WLC_ref_scodes.tab WLC
node print_json_scodes.js ${DIR_IN}/LXX_ref_scodes.tab LXX
node print_json_scodes.js ${DIR_IN}/TKH_ref_scodes.tab TKH
node print_json_scodes.js ${DIR_IN}/ALE_ref_scodes.tab ALE

cd ${CURR_DIR}

