#!/bin/bash

CURR_DIR=$(pwd)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "GENERATING js_bibs using "${BASH_SOURCE[0]}

cd $SCRIPT_DIR

bash gen_js_bib_sh BYZ
bash gen_js_bib_sh NES
bash gen_js_bib_sh TR
bash gen_js_bib_sh WH

bash gen_js_bib_sh WLC
bash gen_js_bib_sh LXX
bash gen_js_bib_sh TKH
bash gen_js_bib_sh ALE

cd ${CURR_DIR}

