
	
export const bib_verses = {
  "job": {
    "27": {
      "1": "Job retomó su parábola y dijo ",
      "2": "  “Vive Dios, que me ha quitado el derecho,   el Todopoderoso, que ha amargado mi alma ",
      "3": "  (por la duración de mi vida aún está en mí,   y el espíritu de Dios está en mis narices); ",
      "4": "  ciertamente mis labios no hablarán injusticia,   ni mi lengua proferirá engaños. ",
      "5": "  Lejos de mí el justificaros.   Hasta que no muera no apartaré mi integridad de mí. ",
      "6": "  Me aferro a mi justicia y no la abandono.   Mi corazón no me reprochará mientras viva. ",
      "7": "  “Que mi enemigo sea como el malvado.   Que el que se levante contra mí sea como los injustos. ",
      "8": "  Porque ¿cuál es la esperanza del impío, cuando es cortado?   cuando Dios le quita la vida? ",
      "9": "  ¿Oirá Dios su clamor cuando le sobrevengan problemas? ",
      "10": "  Se deleitará en el Todopoderoso,   e invocar a Dios en todo momento? ",
      "11": "  Te enseñaré sobre la mano de Dios.   No ocultaré lo que está con el Todopoderoso. ",
      "12": "  Mirad, todos vosotros lo habéis visto;   ¿por qué entonces te has vuelto totalmente vanidoso? ",
      "13": "  “Esta es la porción de un hombre malvado con Dios,   la herencia de los opresores, que reciben del Todopoderoso. ",
      "14": "  Si sus hijos se multiplican, es por la espada.   Su descendencia no se conformará con el pan. ",
      "15": "  Los que queden de él serán enterrados en la muerte.   Sus viudas no se lamentarán. ",
      "16": "  Aunque amontone plata como el polvo,   y preparar la ropa como la arcilla; ",
      "17": "  puede prepararlo, pero el justo se lo pondrá,   y los inocentes se repartirán la plata. ",
      "18": "  Construye su casa como la polilla,   como una caseta que hace el vigilante. ",
      "19": "  Se acuesta rico, pero no volverá a hacerlo.   Abre los ojos y no está. ",
      "20": "  Los terrores lo alcanzan como las aguas.   Una tormenta se lo lleva en la noche. ",
      "21": "  El viento del este lo arrastra y se va.   Lo barre de su lugar. ",
      "22": "  Porque se lanza contra él y no perdona,   mientras huye de su mano. ",
      "23": "  Los hombresle aplaudirán,   y lo sacará de su lugar con un silbido.  "
    },
    "28": {
      "1": "  “Seguramente hay una mina de plata,   y un lugar para el oro que refinan. ",
      "2": "  El hierro se extrae de la tierra,   y el cobre se funde a partir del mineral. ",
      "3": "  El hombre pone fin a la oscuridad,   y busca, hasta el límite más lejano,   las piedras de la oscuridad y de la espesa oscuridad. ",
      "4": "  Abre un pozo lejos de donde vive la gente.   Se olvidan por el pie.   Cuelgan lejos de los hombres, se balancean de un lado a otro. ",
      "5": "  En cuanto a la tierra, de ella sale el pan.   Por debajo, está volteado como si fuera por el fuego. ",
      "6": "  Los zafiros proceden de sus rocas.   Tiene polvo de oro. ",
      "7": "  Ese camino no lo conoce ningún ave de rapiña,   tampoco lo ha visto el ojo del halcón. ",
      "8": "  Los animales orgullosos no la han pisado,   ni el león feroz ha pasado por allí. ",
      "9": "  Pone la mano en la roca de pedernal,   y derriba los montes de raíz. ",
      "10": "  Él corta canales entre las rocas.   Su ojo ve cada cosa preciosa. ",
      "11": "  Él ata los arroyos para que no se rieguen.   Lo que está oculto lo saca a la luz. ",
      "12": "  “Pero, ¿dónde se encontrará la sabiduría?   ¿Dónde está el lugar del entendimiento? ",
      "13": "  El hombre no conoce su precio,   y no se encuentra en la tierra de los vivos. ",
      "14": "  Lo profundo dice: “No está en mí”.   El mar dice: “No está conmigo”. ",
      "15": "  No se puede conseguir por oro,   tampoco se pesará la plata por su precio. ",
      "16": "  No se puede valorar con el oro de Ofir,   con el precioso ónix, o el zafiro.   ",
      "17": "  El oro y el cristal no pueden igualarlo,   ni se cambiará por joyas de oro fino. ",
      "18": "  No se mencionará el coral ni el cristal.   Sí, el precio de la sabiduría está por encima de los rubíes. ",
      "19": "  El topacio de Etiopía no lo igualará.   No se valorará con oro puro. ",
      "20": "  ¿De dónde viene entonces la sabiduría?   ¿Dónde está el lugar del entendimiento? ",
      "21": "  Verlo está oculto a los ojos de todos los vivos,   y se mantuvo cerca de las aves del cielo. ",
      "22": "  La destrucción y la muerte dicen,   ‘Hemos oído el rumor con nuestros oídos’. ",
      "23": "  “Dios entiende su camino,   y conoce su lugar. ",
      "24": "  Porque mira hasta los confines de la tierra,   y ve bajo todo el cielo. ",
      "25": "  Él establece la fuerza del viento.   Sí, mide las aguas por medida. ",
      "26": "  Cuando hizo un decreto para la lluvia,   y un camino para el relámpago del trueno, ",
      "27": "  entonces lo vio y lo declaró.   Lo estableció, sí, y lo buscó. ",
      "28": "  Al hombre le dijo,   He aquí el temor del Señor,  que es la sabiduría.   Apartarse del mal es la comprensión’”.  "
    },
    "29": {
      "1": "Job retomó su parábola y dijo ",
      "2": "  “Oh, si yo fuera como en los meses de antaño,   como en los días en que Dios velaba por mí; ",
      "3": "  cuando su lámpara brilló sobre mi cabeza,   y con su luz atravesé las tinieblas, ",
      "4": "  como estaba en mi mejor momento,   cuando la amistad de Dios estaba en mi tienda, ",
      "5": "  cuando el Todopoderoso aún estaba conmigo,   y mis hijos estaban a mi alrededor, ",
      "6": "  cuando mis pasos fueron lavados con mantequilla,   y la roca derramó chorros de aceite para mí, ",
      "7": "  cuando salí a la puerta de la ciudad,   cuando preparé mi asiento en la calle. ",
      "8": "  Los jóvenes me vieron y se escondieron.   Los ancianos se levantaron y se pusieron de pie. ",
      "9": "  Los príncipes se abstuvieron de hablar,   y se puso la mano en la boca. ",
      "10": "  La voz de los nobles se acalló,   y su lengua se pegó al paladar. ",
      "11": "  Porque cuando el oído me escuchó, entonces me bendijo,   y cuando el ojo me vio, me elogió, ",
      "12": "  porque liberé a los pobres que lloraban,   y también al huérfano, que no tenía quien le ayudara, ",
      "13": "  la bendición del que estaba dispuesto a perecer vino sobre mí,   y he hecho que el corazón de la viuda cante de alegría. ",
      "14": "  Me vestí de justicia, y me vistió.   Mi justicia era como un manto y una diadema. ",
      "15": "  Yo era los ojos de los ciegos,   y los pies a los cojos. ",
      "16": "  Fui padre de los necesitados.   Investigué la causa de él que no conocía. ",
      "17": "  Rompí las mandíbulas de los injustos   y arrancó la presa de sus dientes. ",
      "18": "  Entonces dije: “Moriré en mi propia casa,   Contaré mis días como la arena. ",
      "19": "  Mi raíz se extiende hasta las aguas.   El rocío reposa toda la noche en mi rama. ",
      "20": "  Mi gloria está fresca en mí.   Mi arco se renueva en mi mano’. ",
      "21": "  “Los hombres me escucharon, esperaron,   y guardé silencio por mi consejo. ",
      "22": "  Después de mis palabras no volvieron a hablar.   Mi discurso cayó sobre ellos. ",
      "23": "  Me esperaron como a la lluvia.   Sus bocas bebieron como con la lluvia de primavera. ",
      "24": "  Les sonreí cuando no tenían confianza.   No rechazaron la luz de mi rostro. ",
      "25": "  elegí fuera de su camino, y me senté como jefe.   Viví como un rey en el ejército,   como quien consuela a los dolientes.  "
    },
    "30": {
      "1": "  “Pero ahora los que son más jóvenes que yo se burlan de mí,   cuyos padres consideré indignos de poner con mis perros pastores. ",
      "2": "  ¿De qué me sirve la fuerza de sus manos?   hombres en los que la edad madura ha perecido? ",
      "3": "  Están demacrados por la carencia y el hambre.   Roen la tierra seca, en la penumbra del desperdicio y la desolación. ",
      "4": "  Arrancan hierbas saladas junto a los arbustos.   Las raíces del árbol de la retama son su alimento. ",
      "5": "  Son expulsados de entre los hombres.   Lloran tras ellos como tras un ladrón, ",
      "6": "  para que vivan en valles espantosos,   y en agujeros de la tierra y de las rocas. ",
      "7": "  Rebuznan entre los arbustos.   Están reunidos bajo las ortigas. ",
      "8": "  Son hijos de locos, sí, hijos de malvados.   Fueron expulsados a latigazos de la tierra. ",
      "9": "  “Ahora me he convertido en su canción.   Sí, soy un sinónimo para ellos. ",
      "10": "  Me aborrecen, se alejan de mí,   y no duden en escupirme a la cara. ",
      "11": "  Porque ha desatado su cuerda y me ha afligido;   y se han desprendido de la restricción ante mí. ",
      "12": "  A mi derecha se levanta la chusma.   Me apartan los pies.   Ellos lanzan sus caminos de destrucción contra mí. ",
      "13": "  Marcan mi camino.   Promueven mi destrucción   sin la ayuda de nadie. ",
      "14": "  Como a través de una amplia brecha llegan.   Se enrollan en medio de la ruina. ",
      "15": "  Los terrores se han vuelto contra mí.   Persiguen mi honor como el viento.   Mi bienestar ha pasado como una nube. ",
      "16": "  “Ahora mi alma se derrama dentro de mí.   Los días de aflicción se han apoderado de mí. ",
      "17": "  En la estación nocturna mis huesos están calados en mí,   y los dolores que me roen no tienen descanso. ",
      "18": "  Mi vestimenta está desfigurada por una gran fuerza.   Me ata como el cuello de mi túnica. ",
      "19": "  Me ha arrojado al fango.   Me he convertido en polvo y cenizas. ",
      "20": "  Clamo a ti, y no me respondes.   Me pongo de pie, y tú me miras. ",
      "21": "  Te has vuelto cruel conmigo.   Con la fuerza de tu mano me persigues. ",
      "22": "  Me alzas al viento y me conduces con él.   Me disuelves en la tormenta. ",
      "23": "  Porque sé que me llevarás a la muerte,   a la casa designada para toda la vida. ",
      "24": "  “Sin embargo, ¿no se tiende la mano en su caída?   ¿O en su calamidad, por tanto, clamar por ayuda? ",
      "25": "  ¿No lloré por el que estaba en apuros?   ¿No se afligió mi alma por los necesitados? ",
      "26": "  Cuando buscaba el bien, vino el mal.   Cuando esperaba la luz, llegó la oscuridad. ",
      "27": "  Mi corazón está turbado y no descansa.   Me han llegado días de aflicción. ",
      "28": "  Voy de luto sin el sol.   Me pongo de pie en la asamblea y pido ayuda. ",
      "29": "  Soy hermano de los chacales,   y compañera de los avestruces. ",
      "30": "  Mi piel se ennegrece y se desprende de mí.   Mis huesos están quemados por el calor. ",
      "31": "  Por eso mi arpa se ha convertido en luto,   y mi pipa en la voz de los que lloran.  "
    },
    "31": {
      "1": "  “Hice un pacto con mis ojos;   ¿cómo debería entonces mirar con lujuria a una mujer joven? ",
      "2": "  Porque lo que es la porción de Dios en lo alto,   y la herencia del Todopoderoso en las alturas? ",
      "3": "  ¿No es una calamidad para los injustos,   y el desastre a los obreros de la iniquidad? ",
      "4": "  No ve mis caminos,   y contar todos mis pasos? ",
      "5": "  “Si he andado con falsedad,   y mi pie se ha apresurado a engañar ",
      "6": "  (que me pesen en una balanza uniforme,   para que Dios conozca mi integridad); ",
      "7": "  si mi paso se ha desviado del camino,   si mi corazón caminara tras mis ojos,   si alguna mancha se ha pegado a mis manos, ",
      "8": "  entonces déjame sembrar, y que otro coma.   Sí, que el producto de mi campo sea desarraigado. ",
      "9": "  “Si mi corazón ha sido seducido por una mujer,   y he esperado en la puerta de mi vecino, ",
      "10": "  y luego dejar que mi esposa muela por otra,   y dejar que otros duerman con ella. ",
      "11": "  Porque eso sería un crimen atroz.   Sí, sería una iniquidad ser castigado por los jueces, ",
      "12": "  porque es un fuego que consume hasta la destrucción,   y que me arrancaría de raíz todo mi aumento. ",
      "13": "  “Si he despreciado la causa de mi siervo   o de mi sirvienta,   cuando contendían conmigo, ",
      "14": "  ¿Qué haré entonces cuando Dios se levante?   Cuando me visite, ¿qué le responderé? ",
      "15": "  ¿Acaso no lo hizo el que me hizo en el vientre?   ¿No se nos formó en el vientre materno? ",
      "16": "  “Si he retenido a los pobres de su deseo,   o han hecho fallar los ojos de la viuda, ",
      "17": "  o haber comido mi bocado solo,   y el huérfano no ha comido de ella ",
      "18": "  (no, desde mi juventud creció conmigo como con un padre,   La he guiado desde el vientre de mi madre); ",
      "19": "  si he visto a alguno perecer por falta de ropa,   o que los necesitados no tenían cobertura; ",
      "20": "  si su corazón no me ha bendecido,   si no se ha calentado con el vellón de mi oveja; ",
      "21": "  si he levantado mi mano contra los huérfanos,   porque vi mi ayuda en la puerta; ",
      "22": "  entonces dejé caer mi hombro desde el omóplato,   y que mi brazo se rompa desde el hueso. ",
      "23": "  Porque la calamidad de Dios es un terror para mí.   Por su majestad, no puedo hacer nada. ",
      "24": "  “Si he hecho del oro mi esperanza,   y han dicho al oro fino: “Tú eres mi confianza”. ",
      "25": "  Si me he alegrado porque mi riqueza era grande,   y porque mi mano se había vuelto mucho; ",
      "26": "  si he visto el sol cuando brillaba,   o la luna moviéndose con esplendor, ",
      "27": "  y mi corazón ha sido seducido en secreto,   y mi mano lanzó un beso de mi boca; ",
      "28": "  esto también sería una iniquidad que sería castigada por los jueces,   porque habría negado al Dios que está arriba. ",
      "29": "  “Si me he alegrado de la destrucción del que me odiaba,   o me levanté cuando el mal lo encontró ",
      "30": "  (Ciertamente no he permitido que mi boca peque   pidiendo su vida con una maldición); ",
      "31": "  si los hombres de mi tienda no han dicho,   ¿Quién puede encontrar a alguien que no se haya saciado con su carne? ",
      "32": "  (el extranjero no ha acampado en la calle,   pero he abierto mis puertas al viajero); ",
      "33": "  si como Adán he cubierto mis transgresiones,   ocultando mi iniquidad en mi corazón, ",
      "34": "  porque temía a la gran multitud,   y el desprecio de las familias me aterrorizó,   así que guardé silencio, y no salí de la puerta... ",
      "35": "  ¡ojalá tuviera uno que me escuchara!   ¡He aquí mi firma! ¡Que el Todopoderoso me responda!   ¡Que el acusador escriba mi acusación! ",
      "36": "  Seguramente lo llevaría al hombro,   y lo ataría a mí como una corona. ",
      "37": "  Yo le declararía el número de mis pasos.   Me acercaría a él como un príncipe. ",
      "38": "  Si mi tierra grita contra mí,   y sus surcos lloran juntos; ",
      "39": "  si he comido sus frutos sin dinero,   o han hecho que sus propietarios pierdan la vida, ",
      "40": "  deja que los cardoscrezcan en lugar del trigo,   y stinkweed en lugar de cebada”. Las palabras de Job han terminado."
    },
    "32": {
      "1": "Así que estos tres hombres dejaron de responder a Job, porque era justo a sus ojos.",
      "2": "Entonces se encendió la ira de Elihú, hijo de Baraquel, buzita, de la familia de Ram, contra Job. Su ira se encendió porque él se justificaba a sí mismo antes que a Dios.",
      "3": "También se encendió su ira contra sus tres amigos, porque no habían encontrado respuesta, y sin embargo habían condenado a Job.",
      "4": "Ahora bien, Elihú había esperado para hablar con Job, porque ellos eran mayores que él.",
      "5": "Cuando Elihú vio que no había respuesta en la boca de estos tres hombres, se encendió su ira. ",
      "6": "Eliú, hijo de Baraquel, el buzita, respondió,   “Yo soy joven, y tú eres muy viejo.   Por eso me contuve y no me atreví a mostrarte mi opinión. ",
      "7": "  Dije: “Los días deben hablar,   y la multitud de años debe enseñar la sabiduría”. ",
      "8": "  Pero hay un espíritu en el hombre,   y el Espíritu  del Todopoderoso les da entendimiento. ",
      "9": "  No son los grandes los que son sabios,   ni a los ancianos que entienden de justicia. ",
      "10": "  Por eso le dije: “Escúchame;   Yo también mostraré mi opinión”. ",
      "11": "  “He aquí que he esperado tus palabras,   y escuché su razonamiento,   mientras buscabas qué decir. ",
      "12": "  Sí, te he prestado toda mi atención,   pero no hubo nadie que convenciera a Job,   o que respondió a sus palabras, entre vosotros. ",
      "13": "  Tened cuidado, no sea que digáis: “Hemos encontrado la sabiduría”.   Dios puede refutarlo, no el hombre;’ ",
      "14": "  pues no ha dirigido sus palabras contra mí;   tampoco le responderé con sus discursos. ",
      "15": "  “Están asombrados. No responden más.   No tienen nada que decir. ",
      "16": "  ¿Debo esperar, porque ellos no hablan,   porque se quedan quietos y no responden más? ",
      "17": "  Yo también responderé a mi parte,   y también mostraré mi opinión. ",
      "18": "  Porque estoy lleno de palabras.   El espíritu dentro de mí me constriñe. ",
      "19": "  He aquí que mi pecho es como el vino que no tiene salida;   como los odres nuevos, está a punto de reventar. ",
      "20": "  Voy a hablar para que me refresquen.   Abriré mis labios y responderé. ",
      "21": "  Por favor, no permitas que respete la persona de ningún hombre,   ni daré títulos lisonjeros a ningún hombre. ",
      "22": "  Porque no sé dar títulos halagadores,   o si no, mi Hacedor me llevaría pronto.  "
    },
    "33": {
      "1": "  “Sin embargo, Job, escucha mi discurso,   y escucha todas mis palabras. ",
      "2": "  Mira ahora, he abierto mi boca.   Mi lengua ha hablado en mi boca. ",
      "3": "  Mis palabras expresarán la rectitud de mi corazón.   Lo que mis labios saben que hablarán con sinceridad. ",
      "4": "  El Espíritu de Dios me ha hecho,   y el aliento del Todopoderoso me da la vida. ",
      "5": "  Si puedes, respóndeme.   Pon en orden tus palabras ante mí, y levántate. ",
      "6": "  He aquí que yo soy para con Dios lo mismo que vosotros.   Yo también estoy formado de la arcilla. ",
      "7": "  He aquí que mi terror no te hará temer,   ni mi presión será pesada para ti. ",
      "8": "  “Ciertamente, has hablado a mi oído,   He escuchado la voz de tus palabras, diciendo, ",
      "9": "  ‘Estoy limpio, sin desobediencia.   Soy inocente y no hay iniquidad en mí. ",
      "10": "  He aquí que encuentra ocasiones contra mí.   Me cuenta como su enemigo. ",
      "11": "  Pone mis pies en el cepo.   Él marca todos mis caminos”. ",
      "12": "  “He aquí que yo te responderé. En esto no eres justo,   porque Dios es más grande que el hombre. ",
      "13": "  ¿Por qué os esforzáis contra él?   porque no da cuenta de ninguno de sus asuntos? ",
      "14": "  Porque Dios habla una vez,   sí dos veces, aunque el hombre no presta atención. ",
      "15": "  En un sueño, en una visión nocturna,   cuando el sueño profundo cae sobre los hombres,   en el sueño en la cama, ",
      "16": "  entonces abre los oídos de los hombres,   y sella su instrucción, ",
      "17": "  para que retire al hombre de su propósito,   y ocultar el orgullo del hombre. ",
      "18": "  Aleja su alma de la fosa,   y su vida de perecer por la espada. ",
      "19": "  “También es castigado con dolor en su cama,   con una lucha continua en sus huesos, ",
      "20": "  para que su vida aborrezca el pan,   y su alma un alimento delicado. ",
      "21": "  Su carne está tan consumida que no se puede ver.   Sus huesos que no se vieron sobresalen. ",
      "22": "  Sí, su alma se acerca a la fosa,   y su vida a los destructores. ",
      "23": "  “Si hay junto a él un ángel,   un intérprete, uno entre mil,   para mostrar al hombre lo que es correcto para él, ",
      "24": "  entonces Dios se apiada de él y le dice,   Líbralo de bajar a la fosa,   He encontrado un rescate”. ",
      "25": "  Su carne será más fresca que la de un niño.   Vuelve a los días de su juventud. ",
      "26": "  Reza a Dios, y éste le es favorable,   para que vea su rostro con alegría.   Él devuelve al hombre su justicia. ",
      "27": "  Canta ante los hombres y dice,   He pecado y he pervertido lo que era justo,   y no me benefició. ",
      "28": "  Él ha redimido mi alma de ir a la fosa.   Mi vida verá la luz”. ",
      "29": "  “He aquí que Dios hace todas estas cosas,   dos veces, sí tres veces, con un hombre, ",
      "30": "  para sacar su alma de la fosa,   para que sea iluminado con la luz de los vivos. ",
      "31": "  Fíjate bien, Job, y escúchame.   Guarda silencio, y yo hablaré. ",
      "32": "  Si tienes algo que decir, respóndeme.   Habla, pues deseo justificarte. ",
      "33": "  Si no, escúchame.   Guarda la paz, y yo te enseñaré la sabiduría”.  "
    },
    "34": {
      "1": "Además, Eliú respondió, ",
      "2": "  “Escuchad mis palabras, sabios.   Escúchame, tú que tienes conocimiento. ",
      "3": "  Porque el oído prueba las palabras,   como el paladar prueba la comida. ",
      "4": "  Escojamos para nosotros lo que es correcto.   Conozcamos entre nosotros lo que es bueno. ",
      "5": "  Porque Job ha dicho: “Soy justo”,   Dios me ha quitado el derecho. ",
      "6": "  A pesar de mi derecho se me considera un mentiroso.   Mi herida es incurable, aunque estoy sin desobediencia’. ",
      "7": "  Qué hombre es como Job,   que bebe el desprecio como el agua, ",
      "8": "  que va en compañía de los obreros de la iniquidad,   y camina con los hombres malvados? ",
      "9": "  Porque él ha dicho: “De nada le sirve al hombre   para que se deleite con Dios”. ",
      "10": "  “Por tanto, escuchadme, hombres de entendimiento:   lejos de Dios, que haga la maldad,   del Todopoderoso, para que cometa iniquidad. ",
      "11": "  Porque el trabajo de un hombre se lo devolverá,   y haz que cada uno encuentre según sus caminos. ",
      "12": "  Sí, ciertamente, Dios no hará maldad,   ni el Todopoderoso pervertirá la justicia. ",
      "13": "  ¿Quién lo puso a cargo de la tierra?   ¿O quién lo ha designado sobre el mundo entero? ",
      "14": "  Si pone su corazón en sí mismo,   si reuniera para sí su espíritu y su aliento, ",
      "15": "  toda la carne perecería junta,   y el hombre volvería a convertirse en polvo. ",
      "16": "  “Si ahora tienes entendimiento, escucha esto.   Escucha la voz de mis palabras. ",
      "17": "  ¿Debe gobernar incluso quien odia la justicia?   ¿Condenarás al que es justo y poderoso, ",
      "18": "  que dice a un rey: “¡Vil!   o a los nobles, “¡malvados!”? ",
      "19": "  No respeta las personas de los príncipes,   ni respetar a los ricos más que a los pobres,   porque todos son obra de sus manos. ",
      "20": "  En un momento mueren, incluso a medianoche.   El pueblo se estremece y fallece.   A los poderosos se les quita la mano. ",
      "21": "  “Porque sus ojos están en los caminos del hombre.   Él ve todas sus salidas. ",
      "22": "  No hay oscuridad, ni tinieblas espesas,   donde los obreros de la iniquidad pueden esconderse. ",
      "23": "  Porque no necesita considerar más a un hombre,   que debe ir ante Dios en el juicio. ",
      "24": "  El rompe en pedazos a los hombres poderosos de una manera que no se puede descubrir,   y pone a otros en su lugar. ",
      "25": "  Por eso toma conocimiento de sus obras.   Él los derriba en la noche, para que sean destruidos. ",
      "26": "  Los golpea como hombres malvados   a la vista de los demás; ",
      "27": "  porque se apartaron de seguirlo,   y no prestaba atención a ninguna de sus formas, ",
      "28": "  de modo que hicieron llegar a él el clamor de los pobres.   Oyó el clamor de los afligidos. ",
      "29": "  Cuando da tranquilidad, ¿quién puede entonces condenar?   Cuando esconde su rostro, ¿quién puede verlo entonces?   Está sobre una nación o un hombre por igual, ",
      "30": "  para que no reine el hombre impío,   para que no haya nadie que engañe al pueblo. ",
      "31": "  “Porque ¿ha dicho alguno a Dios,   ‘Soy culpable, pero no ofenderé más. ",
      "32": "  Enséñame lo que no veo.   Si he hecho iniquidad, no la haré más’? ",
      "33": "  ¿Será su recompensa como deseas, que la rechaces?   Porque tú debes elegir, y no yo.   Por lo tanto, habla de lo que sabes. ",
      "34": "  Los hombres de entendimiento me dirán,   sí, todo sabio que me escuche: ",
      "35": "  “Job habla sin conocimiento.   Sus palabras carecen de sabiduría”. ",
      "36": "  Deseo que Job sea juzgado hasta el final,   a causa de su respuesta como hombres malvados. ",
      "37": "  Porque añade la rebelión a su pecado.   Aplaude entre nosotros,   y multiplica sus palabras contra Dios”.  "
    },
    "35": {
      "1": "Además, Eliú respondió, ",
      "2": "  “¿Consideras que es tu derecho,   o dices, ‘Mi justicia es más que la de Dios,’ ",
      "3": "  que te preguntes: “¿Qué ventaja tendrá para ti?   ¿Qué beneficio tendré, más que si hubiera pecado?’ ",
      "4": "  Yo te responderé,   y tus compañeros contigo. ",
      "5": "  Miren al cielo y vean.   Mira los cielos, que están más altos que tú. ",
      "6": "  Si has pecado, ¿qué efecto tienes contra él?   Si tus transgresiones se multiplican, ¿qué le haces? ",
      "7": "  Si eres justo, ¿qué le das?   ¿O qué recibe de su mano? ",
      "8": "  Tu maldad puede herir a un hombre como tú,   y tu justicia puede beneficiar a un hijo de hombre. ",
      "9": "  “A causa de la multitud de opresiones gritan.   Piden ayuda por el brazo del poderoso. ",
      "10": "  Pero nadie dice: “¿Dónde está Dios, mi Hacedor?   que da canciones en la noche, ",
      "11": "  que nos enseña más que los animales de la tierra,   y nos hace más sabios que los pájaros del cielo”. ",
      "12": "  Allí gritan, pero nadie responde,   por el orgullo de los hombres malos. ",
      "13": "  Ciertamente, Dios no escuchará un grito vacío,   ni el Todopoderoso lo considerará. ",
      "14": "  Cuánto menos cuando dices que no lo ves.   La causa está delante de él, ¡y tú lo esperas! ",
      "15": "  Pero ahora, porque no ha visitado en su ira,   tampoco considera mucho la arrogancia, ",
      "16": "  por lo tantoJob abre su boca con palabras vacías,   y multiplica las palabras sin conocimiento”.  "
    },
    "36": {
      "1": "Eliú también continuó, y dijo, ",
      "2": "  “Tened un poco de paciencia conmigo y os lo mostraré;   porque todavía tengo algo que decir en nombre de Dios. ",
      "3": "  Obtendré mis conocimientos desde lejos,   y atribuiré la justicia a mi Hacedor. ",
      "4": "  Porque en verdad mis palabras no son falsas.   Uno que es perfecto en conocimiento está contigo. ",
      "5": "  “He aquí que Dios es poderoso y no desprecia a nadie.   Es poderoso en la fuerza del entendimiento. ",
      "6": "  No preserva la vida de los malvados,   sino que hace justicia a los afligidos. ",
      "7": "  No aparta sus ojos de los justos,   pero con reyes en el trono,   los pone para siempre, y son exaltados. ",
      "8": "  Si están atados con grilletes,   y son tomados en las cuerdas de las aflicciones, ",
      "9": "  luego les muestra su trabajo,   y sus transgresiones, que se han comportado con orgullo. ",
      "10": "  También les abre los oídos a la instrucción,   y ordena que vuelvan de la iniquidad. ",
      "11": "  Si le escuchan y le sirven,   pasarán sus días en la prosperidad,   y sus años en los placeres. ",
      "12": "  Pero si no escuchan, perecerán a espada;   morirán sin conocimiento. ",
      "13": "  “Pero los impíos de corazón acumulan ira.   No gritan pidiendo ayuda cuando los ata. ",
      "14": "  Mueren en la juventud.   Su vida perece entre los impuros. ",
      "15": "  Él libera a los afligidos por su aflicción,   y abre su oído en la opresión. ",
      "16": "  Sí, él te habría seducido por la angustia,   en un lugar amplio, donde no hay restricciones.   Lo que se pone en su mesa estaría lleno de grasa. ",
      "17": "  “Pero tú estás lleno del juicio de los malvados.   El juicio y la justicia se apoderan de ti. ",
      "18": "  No dejes que las riquezas te inciten a la ira,   ni dejes que el gran tamaño de un soborno te desvíe. ",
      "19": "  Tu riqueza te sostendría en la angustia,   o todo el poder de tu fuerza? ",
      "20": "  No desees la noche,   cuando la gente es cortada en su lugar. ",
      "21": "  Tened cuidado, no miréis la iniquidad;   porque has elegido esto antes que la aflicción. ",
      "22": "  He aquí que Dios es exaltado en su poder.   ¿Quién es un profesor como él? ",
      "23": "  ¿Quién le ha prescrito su camino?   ¿O quién puede decir: “Has cometido una injusticia”? ",
      "24": "  “Acuérdate de que engrandeces su obra,   sobre la que los hombres han cantado. ",
      "25": "  Todos los hombres lo han mirado.   El hombre lo ve de lejos. ",
      "26": "  He aquí que Dios es grande y no lo conocemos.   El número de sus años es inabarcable. ",
      "27": "  Porque él extrae las gotas de agua,   que destilan en lluvia de su vapor, ",
      "28": "  que los cielos derraman   y que caen sobre el hombre en abundancia. ",
      "29": "  En efecto, ¿puede alguien entender la propagación de las nubes   y los truenos de su pabellón? ",
      "30": "  He aquí que difunde su luz a su alrededor.   Cubre el fondo del mar. ",
      "31": "  Porque por ellos juzga al pueblo.   Da comida en abundancia. ",
      "32": "  Cubre sus manos con el rayo,   y le ordena que golpee la marca. ",
      "33": "  Su ruido habla de él,   y el ganado también, en lo que respecta a la tormenta que se avecina.  "
    },
    "37": {
      "1": "  “Sí, ante esto mi corazón tiembla,   y es desplazado de su lugar. ",
      "2": "  Escucha, oh, escucha el ruido de su voz,   el sonido que sale de su boca. ",
      "3": "  Lo envía bajo todo el cielo,   y sus rayos hasta los confines de la tierra. ",
      "4": "  Tras ella ruge una voz.   Truena con la voz de su majestad.   No se guarda nada cuando se escucha su voz. ",
      "5": "  Dios truena maravillosamente con su voz.   Él hace grandes cosas, que no podemos comprender. ",
      "6": "  Porque dice a la nieve: “Cae sobre la tierra”.   también a la lluvia,   y a los chubascos de su poderosa lluvia. ",
      "7": "  Él sella la mano de cada hombre,   para que todos los hombres a los que ha hecho lo conozcan. ",
      "8": "  Entonces los animales se ponen a cubierto,   y permanecen en sus guaridas. ",
      "9": "  De su habitación sale la tormenta,   y el frío del norte. ",
      "10": "  Por el soplo de Dios se da el hielo,   y la anchura de las aguas está congelada. ",
      "11": "  Sí, carga la espesa nube con humedad.   Extiende la nube de su rayo. ",
      "12": "  Se ha dado la vuelta gracias a su guía,   para que hagan todo lo que él les mande   en la superficie del mundo habitable, ",
      "13": "  ya sea por la corrección, o por su tierra,   o por la bondad amorosa, que la hace venir. ",
      "14": "  “Escucha esto, Job.   Quédate quieto y considera las obras maravillosas de Dios. ",
      "15": "  ¿Sabes cómo los controla Dios?   y hace brillar el rayo de su nube? ",
      "16": "  ¿Conoces el funcionamiento de las nubes,   las obras maravillosas de aquel que es perfecto en el conocimiento? ",
      "17": "  Tú, cuya ropa es cálida   cuando la tierra está quieta a causa del viento del sur? ",
      "18": "  ¿Puedes, con él, extender el cielo,   que es fuerte como un espejo de metal fundido? ",
      "19": "  Enséñanos lo que le vamos a decir,   porque no podemos hacer nuestro caso a causa de la oscuridad. ",
      "20": "  ¿Se le dirá que voy a hablar?   ¿O debería un hombre desear ser tragado? ",
      "21": "  Los hombres no ven la luz que brilla en los cielos,   pero el viento pasa y los despeja. ",
      "22": "  Del norte viene el esplendor dorado.   Con Dios hay una majestuosidad impresionante. ",
      "23": "  No podemos llegar al Todopoderoso.   Está exaltado en el poder.   Con justicia y gran rectitud, no oprimirá. ",
      "24": "  Por eso los hombres lo veneran.   No tiene en cuenta a los sabios de corazón”.  "
    },
    "38": {
      "1": "Entonces Yahvé respondió a Job desde el torbellino, ",
      "2": "  “¿Quién es el que oscurece el consejo   por palabras sin conocimiento? ",
      "3": "  Prepárate como un hombre,   porque yo te interrogaré y tú me responderás. ",
      "4": "  “¿Dónde estabas cuando puse los cimientos de la tierra?   Declara, si tienes entendimiento. ",
      "5": "  ¿Quién determinó sus medidas, si lo sabe?   ¿O quién estiró la línea en él? ",
      "6": "  ¿Sobre qué estaban fijados sus cimientos?   O quién puso su piedra angular, ",
      "7": "  cuando las estrellas de la mañana cantaban juntas,   y todos los hijos de Dios gritaron de alegría? ",
      "8": "  “O que cierra el mar con puertas,   cuando salió del vientre materno, ",
      "9": "  cuando hice de las nubes su vestimenta,   y lo envolvió en una espesa oscuridad, ",
      "10": "  marcadas para ello mi límite,   poner barras y puertas, ",
      "11": "  y dijo: “Puedes venir aquí, pero no más allá.   ¿Tus orgullosas olas serán detenidas aquí? ",
      "12": "  “¿Has ordenado la mañana en tus días,   y ha hecho que el amanecer conozca su lugar, ",
      "13": "  para que se apodere de los confines de la tierra,   y sacudir a los malvados fuera de ella? ",
      "14": "  Se cambia como la arcilla bajo el sello,   y presentado como una prenda de vestir. ",
      "15": "  A los malvados se les oculta la luz.   El brazo alto está roto. ",
      "16": "  “¿Has entrado en los manantiales del mar?   ¿O has caminado por los recovecos de las profundidades? ",
      "17": "  ¿Se te han revelado las puertas de la muerte?   ¿O has visto las puertas de la sombra de la muerte? ",
      "18": "  ¿Has comprendido la tierra en su anchura?   Declara, si lo sabes todo. ",
      "19": "  “¿Cuál es el camino hacia la morada de la luz?   En cuanto a la oscuridad, cuál es su lugar, ",
      "20": "  que lo lleves a su límite,   para que discierna los caminos de su casa? ",
      "21": "  Seguramente lo sabes, pues naciste entonces,   ¡y el número de sus días es genial! ",
      "22": "  ¿Has entrado en los almacenes de la nieve,   o has visto los almacenes del granizo, ",
      "23": "  que he reservado para el tiempo de la angustia,   contra el día de la batalla y la guerra? ",
      "24": "  De qué manera se distribuye el rayo,   o el viento del este disperso en la tierra? ",
      "25": "  Que ha cortado un canal para el agua de la inundación,   o la trayectoria de la tormenta, ",
      "26": "  para hacer llover en una tierra donde no hay hombre,   en el desierto, en el que no hay hombre, ",
      "27": "  para saciar el terreno baldío y desolado,   para hacer crecer la hierba tierna? ",
      "28": "  ¿La lluvia tiene padre?   ¿O quién recoge las gotas de rocío? ",
      "29": "  ¿De qué vientre salió el hielo?   ¿Quién ha dado a luz a la escarcha gris del cielo? ",
      "30": "  Las aguas se vuelven duras como la piedra,   cuando la superficie de las profundidades está congelada. ",
      "31": "  “¿Puedes atar el cúmulo de las Pléyades,   o aflojar las cuerdas de Orión? ",
      "32": "  ¿Puedes guiar a las constelaciones en su estación?   ¿O puedes guiar a la Osa con sus cachorros? ",
      "33": "  ¿Conoces las leyes de los cielos?   ¿Puede establecer su dominio sobre la tierra? ",
      "34": "  “¿Puedes elevar tu voz a las nubes,   para que la abundancia de aguas te cubra? ",
      "35": "  ¿Puedes enviar relámpagos para que se vayan?   ¿Te informan de que “aquí estamos”? ",
      "36": "  ¿Quién ha puesto la sabiduría en las partes interiores?   ¿O quién ha dado entendimiento a la mente? ",
      "37": "  ¿Quién puede contar las nubes con sabiduría?   O que puede verter los contenedores del cielo, ",
      "38": "  cuando el polvo se convierte en una masa,   y los terrones se pegan? ",
      "39": "  “¿Puedes cazar la presa para la leona,   o satisfacer el apetito de los jóvenes leones, ",
      "40": "  cuando se agazapan en sus guaridas,   y acechar en la espesura? ",
      "41": "  Que proporciona al cuervo su presa,   cuando sus jóvenes claman a Dios,   y vagan por falta de comida?  "
    },
    "39": {
      "1": "  “¿Sabéis en qué momento paren las cabras montesas?   ¿Observas cuando la cierva tiene cervatillo? ",
      "2": "  ¿Puedes contar los meses que cumplen?   ¿O sabes la hora en que dan a luz? ",
      "3": "  Se inclinan. Llevan a sus crías.   Terminan sus dolores de parto. ",
      "4": "  Sus crías se hacen fuertes.   Crecen en el campo abierto.   Salen y no vuelven. ",
      "5": "  “¿Quién ha liberado al burro salvaje?   O que ha soltado las amarras del asno veloz, ",
      "6": "  cuyo hogar he convertido en el desierto,   y la tierra salada su morada? ",
      "7": "  Desprecia el tumulto de la ciudad,   tampoco oye los gritos del conductor. ",
      "8": "  La cordillera es su pasto.   Busca cada cosa verde. ",
      "9": "  “¿Se contentará el buey salvaje con servirte?   ¿O se quedará junto a tu comedero? ",
      "10": "  ¿Puedes sujetar al buey salvaje en el surco con su arnés?   ¿O va a labrar los valles después de ti? ",
      "11": "  ¿Confiarás en él, porque su fuerza es grande?   ¿O le dejarás tu trabajo? ",
      "12": "  ¿Confiarás en él para que traiga a casa tu semilla?   y recoger el grano de tu era? ",
      "13": "  “Las alas del avestruz se agitan con orgullo,   ¿pero son las plumas y el plumaje del amor? ",
      "14": "  Porque deja sus huevos en la tierra,   los calienta en el polvo, ",
      "15": "  y olvida que el pie puede aplastarlos,   o que el animal salvaje los pisotee. ",
      "16": "  Trata con dureza a sus crías, como si no fueran suyas.   Aunque su trabajo es en vano, no tiene miedo, ",
      "17": "  porque Dios la ha privado de sabiduría,   tampoco le ha impartido entendimiento. ",
      "18": "  Cuando se eleva a lo alto,   desprecia al caballo y a su jinete. ",
      "19": "  “¿Le has dado fuerza al caballo?   ¿Has vestido su cuello con una melena temblorosa? ",
      "20": "  ¿Le has hecho saltar como una langosta?   La gloria de su resoplido es impresionante. ",
      "21": "  Pisa el valle y se regocija en su fuerza.   Sale al encuentro de los hombres armados. ",
      "22": "  Se burla del miedo y no se amilana,   ni se aparta de la espada. ",
      "23": "  El carcaj se sacude contra él,   la lanza y la jabalina. ",
      "24": "  Come la tierra con fiereza y rabia,   ni se queda quieto al sonido de la trompeta. ",
      "25": "  Cada vez que suena la trompeta, resopla: “¡Ah!   Huele la batalla a lo lejos,   el estruendo de los capitanes, y los gritos. ",
      "26": "  “¿Es por tu sabiduría que el halcón vuela,   y extiende sus alas hacia el sur? ",
      "27": "  ¿Es por tu orden que el águila se levanta,   y hace su nido en las alturas? ",
      "28": "  En el acantilado habita y hace su hogar,   en la punta del acantilado y la fortaleza. ",
      "29": "  Desde allí espía la presa.   Sus ojos lo ven de lejos. ",
      "30": "  Sus crías también chupan sangre.   Donde están los muertos, allí está él”.  "
    },
    "40": {
      "1": "Además, Yahvé respondió a Job, ",
      "2": "  “¿Acaso el que discute puede contender con el Todopoderoso?   El que discute con Dios, que responda”. ",
      "3": "Entonces Job respondió a Yahvé, ",
      "4": "  “He aquí que soy de poca monta. ¿Qué te voy a responder?   Me pongo la mano en la boca. ",
      "5": "  He hablado una vez y no voy a responder;   Sí, dos veces, pero no seguiré adelante”. ",
      "6": "Entonces Yahvé respondió a Job desde el torbellino: ",
      "7": "  “Ahora prepárate como un hombre.   Te interrogaré, y tú me responderás. ",
      "8": "  ¿Acaso anularás mi juicio?   ¿Me condenas para justificarte? ",
      "9": "  ¿O es que tienes un brazo como Dios?   ¿Se puede tronar con una voz como la suya? ",
      "10": "  “Ahora adórnate con excelencia y dignidad.   Arréglate con honor y majestuosidad. ",
      "11": "  Derrama la furia de tu ira.   Mira a todos los que son orgullosos, y bájalos. ",
      "12": "  Mira a todo el que es orgulloso, y humíllalo.   Aplasta a los malvados en su lugar. ",
      "13": "  Escóndelos juntos en el polvo.   Ata sus rostros en el lugar oculto. ",
      "14": "  Entonces también te admitiré   que tu propia mano derecha puede salvarte. ",
      "15": "  “Mira ahora el behemoth, que yo he hecho igual que tú.   Come hierba como un buey. ",
      "16": "  Mira ahora, su fuerza está en sus muslos.   Su fuerza está en los músculos de su vientre. ",
      "17": "  Mueve su cola como un cedro.   Los tendones de sus muslos están unidos. ",
      "18": "  Sus huesos son como tubos de bronce.   Sus miembros son como barras de hierro. ",
      "19": "  Él es el principal de los caminos de Dios.   El que lo hizo le da su espada. ",
      "20": "  Ciertamente, las montañas producen alimento para él,   donde juegan todos los animales del campo. ",
      "21": "  Se acuesta bajo los árboles de loto,   en la cobertura del carrizo, y el pantano. ",
      "22": "  Los lotos lo cubren con su sombra.   Los sauces del arroyo lo rodean. ",
      "23": "  He aquí que si un río se desborda, no tiembla.   Se muestra confiado, aunque el Jordán se hincha hasta la boca. ",
      "24": "  Lo tomará cualquiercuando esté de guardia,   o atravesar su nariz con un lazo?  "
    },
    "41": {
      "1": "  “¿Puedes sacar al Leviatán  con un anzuelo?   o presionar su lengua con una cuerda? ",
      "2": "  ¿Puedes poner una cuerda en su nariz,   o atravesar su mandíbula con un gancho? ",
      "3": "  Te hará muchas peticiones,   ¿o te hablará con palabras suaves? ",
      "4": "  Hará un pacto con vosotros,   para que lo tomes por siervo para siempre? ",
      "5": "  ¿Jugarás con él como con un pájaro?   ¿O lo atarás para tus chicas? ",
      "6": "  ¿Los comerciantes harán un trueque por él?   ¿Lo repartirán entre los comerciantes? ",
      "7": "  Puede llenar su piel con hierros de púas,   o su cabeza con lanzas de pescado? ",
      "8": "  Pon tu mano sobre él.   Recuerda la batalla, y no lo hagas más. ",
      "9": "  He aquí que la esperanza de él es vana.   ¿No se abatirá uno incluso al verlo? ",
      "10": "  Nadie es tan feroz que se atreva a agitarlo.   ¿Quién es, pues, el que puede presentarse ante mí? ",
      "11": "  ¿Quién me ha dado primero, para que yo le pague?   Todo bajo el cielo es mío. ",
      "12": "  “No guardaré silencio sobre sus miembros,   ni su poderosa fuerza, ni su buena contextura. ",
      "13": "  ¿Quién puede despojarse de su prenda exterior?   ¿Quién se acercará a sus fauces? ",
      "14": "  ¿Quién puede abrir las puertas de su rostro?   Alrededor de sus dientes está el terror. ",
      "15": "  Las fuertes escamas son su orgullo,   encerrados juntos con un cierre hermético. ",
      "16": "  Uno está tan cerca de otro,   que ningún aire pueda interponerse entre ellos. ",
      "17": "  Están unidos entre sí.   Se pegan entre sí, de modo que no se pueden separar. ",
      "18": "  Su estornudo hace brillar la luz.   Sus ojos son como los párpados de la mañana. ",
      "19": "  De su boca salen antorchas ardientes.   Saltan chispas de fuego. ",
      "20": "  De sus fosas nasales sale un humo,   como de una olla hirviendo sobre un fuego de cañas. ",
      "21": "  Su aliento enciende las brasas.   Una llama sale de su boca. ",
      "22": "  Hay fuerza en su cuello.   El terror baila ante él. ",
      "23": "  Las escamas de su carne están unidas.   Son firmes con él.   No se pueden mover. ",
      "24": "  Su corazón es firme como una piedra,   sí, firme como la piedra de molino inferior. ",
      "25": "  Cuando se levanta, los poderosos tienen miedo.   Se retiran ante su paliza. ",
      "26": "  Si uno lo ataca con la espada, no puede prevalecer;   ni la lanza, ni el dardo, ni el asta puntiaguda. ",
      "27": "  Cuenta el hierro como paja,   y el bronce como la madera podrida. ",
      "28": "  La flecha no puede hacerle huir.   Las piedras de la honda son como la paja para él. ",
      "29": "  Los palos se cuentan como rastrojos.   Se ríe de las prisas de la jabalina. ",
      "30": "  Sus partes inferiores son como alfareros afilados,   dejando un rastro en el barro como un trineo. ",
      "31": "  Hace que lo profundo hierva como una olla.   Hace que el mar sea como un bote de pomada. ",
      "32": "  Hace brillar un camino tras él.   Se diría que el profundo tiene el pelo blanco. ",
      "33": "  En la tierra no hay nada igual,   que se hace sin miedo. ",
      "34": "  Él ve todo lo que es alto.   Es el rey de todos los hijos de la soberbia”.  "
    },
    "42": {
      "1": "Entonces Job respondió a Yahvé: ",
      "2": "  “Sé que todo lo puedes hacer,   y que ningún propósito tuyo puede ser frenado. ",
      "3": "  Preguntasteis: “¿Quién es ese que esconde el consejo sin conocimiento?”.   por lo que he pronunciado lo que no entendía,   cosas demasiado maravillosas para mí, que no conocía. ",
      "4": "  Dijiste: “Escucha, ahora, y yo hablaré;   Te interrogaré y tú me responderás’. ",
      "5": "  Había oído hablar de ti por el oído,   pero ahora mi ojo te ve. ",
      "6": "  Por eso me aborrezco,   y arrepentirse en polvo y ceniza”. ",
      "7": "Fue así que, después de que Yahvé hubo pronunciado estas palabras a Job, Yahvé dijo a Elifaz el temanita: “Mi ira se ha encendido contra ti y contra tus dos amigos, porque no habéis hablado de mí lo que es justo, como lo ha hecho mi siervo Job.",
      "8": "Ahora, pues, tomad para vosotros siete toros y siete carneros, e id a mi siervo Job, y ofreced para vosotros un holocausto; y mi siervo Job rogará por vosotros, pues yo lo aceptaré, para que no os trate según vuestra insensatez. Porque no habéis hablado de mí lo que es justo, como mi siervo Job”. ",
      "9": "Entonces Elifaz, el temanita, Bildad, el suhita, y Zofar, el naamatita, fueron e hicieron lo que Yahvé les ordenó, y Yahvé aceptó a Job. ",
      "10": "Yahvé restauró la prosperidad de Job cuando éste oró por sus amigos. El Señor le dio a Job el doble de lo que tenía antes.",
      "11": "Entonces todos sus hermanos, todas sus hermanas y todos los que antes lo conocían, vinieron a él y comieron con él en su casa. Lo consolaron, y lo consolaron por todo el mal que el Señor le había hecho pasar. Todos le dieron también una pieza de dinero,  y todos un anillo de oro. ",
      "12": "Así, el Señor bendijo el final de Job más que su principio. Tenía catorce mil ovejas, seis mil camellos, mil yuntas de bueyes y mil burras.",
      "13": "Tenía también siete hijos y tres hijas.",
      "14": "A la primera la llamó Jemimah, a la segunda Keziah y a la tercera Keren Happuch.",
      "15": "En toda la tierra no se encontraron mujeres tan hermosas como las hijas de Job. Su padre les dio una herencia entre sus hermanos.",
      "16": "Después de esto, Job vivió ciento cuarenta años, y vio a sus hijos, y a los hijos de sus hijos, hasta cuatro generaciones.",
      "17": "Así murió Job, siendo viejo y lleno de días."
    }
  },
  "psalms": {
    "1": {
      "1": "   Dichoso el hombre que no sigue el consejo de los malvados,   ni se pare en el camino de los pecadores,   ni sentarse en el asiento de los burlones; ",
      "2": "  pero su deleite está en la ley de Yahvé.     En su ley medita día y noche. ",
      "3": "  Será como un árbol plantado junto a las corrientes de agua,   que produce su fruto en su temporada,   cuya hoja tampoco se marchita.   Todo lo que haga prosperará. ",
      "4": "  Los malvados no son así,   sino que son como la paja que el viento se lleva. ",
      "5": "  Por lo tanto, los impíos no estarán en el juicio,   ni los pecadores en la congregación de los justos. ",
      "6": "  Porque Yahvé conoce el camino de los justos,   pero el camino de los impíos perecerá."
    },
    "2": {
      "1": "  Por qué se enfurecen las naciones,   ¿y los pueblos traman una cosa vana? ",
      "2": "  Los reyes de la tierra toman posición,   y los gobernantes se aconsejan entre sí,   contra Yahvé y contra su Ungido,  diciendo, ",
      "3": "  “Rompamos sus vínculos,   y arrojar sus cuerdas de nosotros”. ",
      "4": "  El que está sentado en los cielos se reirá.   El Señor  se burlará de ellos. ",
      "5": "  Entonces les hablará en su ira,   y aterrorizarlos en su ira: ",
      "6": "  “Pero he puesto a mi Rey en mi santo monte de Sión”. ",
      "7": "  Voy a contar el decreto:   Yahvé me dijo: “Tú eres mi hijo.   Hoy me he convertido en tu padre. ",
      "8": "  Pídeme y te daré las naciones como herencia,   los confines de la tierra para su posesión. ",
      "9": "  Los romperás con una vara de hierro.   Los harás pedazos como una vasija de alfarero”. ",
      "10": "  Ahora, pues, sed sabios, reyes.   Instrúyanse, jueces de la tierra. ",
      "11": "  Sirve a Yahvé con temor,   y se regocija con el temblor. ",
      "12": "  Dad un homenaje sincero al Hijo,  no sea que se enfade y perezcáis en el camino,   porque su ira pronto se encenderá.   Dichosos los que se refugian en él."
    },
    "3": {
      "1": "   ¡Yahvé, cómo han aumentado mis adversarios!   Muchos son los que se levantan contra mí. ",
      "2": "  Son muchos los que dicen de mi alma,   “No hay ayuda para él en Dios”.  Selah. ",
      "3": "  Pero tú, Yahvé, eres un escudo a mi alrededor,   mi gloria, y el que levanta mi cabeza. ",
      "4": "  Clamo a Yahvé con mi voz,   y me responde desde su santo monte. Selah. ",
      "5": "  Me acosté y dormí.   Me he despertado, porque Yahvé me sostiene. ",
      "6": "  No tendré miedo de decenas de miles de personas   que se han puesto en mi contra por todos lados. ",
      "7": "  ¡Levántate, Yahvé!   ¡Sálvame, Dios mío!   Porque has golpeado a todos mis enemigos en el pómulo.   Has roto los dientes de los malvados. ",
      "8": "  La salvación pertenece a Yahvé.   Que tu bendición sea para tu pueblo. Selah."
    },
    "4": {
      "1": "   Respóndeme cuando te llamo, Dios de mi justicia.   Alíviame de mi angustia.   Ten piedad de mí y escucha mi oración. ",
      "2": "  Hijos de los hombres, ¿hasta cuándo se convertirá mi gloria en deshonra?   ¿Amarás la vanidad y buscarás la falsedad? Selah. ",
      "3": "  Pero sabed que Yahvé ha reservado para sí al que es piadoso;   Yahvé escuchará cuando le llame. ",
      "4": "  Permanece en el temor y no peques.   Busca tu propio corazón en tu cama, y quédate quieto. Selah. ",
      "5": "  Ofrece los sacrificios de la justicia.   Pon tu confianza en Yahvé. ",
      "6": "  Muchos dicen: “¿Quién nos mostrará algo bueno?”   Yahvé, haz que la luz de tu rostro brille sobre nosotros. ",
      "7": "  Has puesto alegría en mi corazón,   más que cuando su grano y su vino nuevo se incrementan. ",
      "8": "  En paz me acostaré y dormiré,   porque sólo tú, Yahvé, me haces vivir con seguridad."
    },
    "5": {
      "1": "   Presta atención a mis palabras, Yahvé.   Considera mi meditación. ",
      "2": "  Escucha la voz de mi clamor, mi Rey y mi Dios,   porque te ruego. ",
      "3": "  Yahvé, por la mañana escucharás mi voz.   Por la mañana te expondré mis peticiones, y velaré expectante. ",
      "4": "  Porque no eres un Dios que se complace en la maldad.   El mal no puede vivir contigo. ",
      "5": "  El arrogante no se mantendrá ante tus ojos.   Odias a todos los obreros de la iniquidad. ",
      "6": "  Destruirás a los que dicen mentiras.   Yahvé aborrece al hombre sanguinario y engañoso. ",
      "7": "  Pero en cuanto a mí, en la abundancia de tu bondad amorosa entraré en tu casa.   Me inclinaré hacia tu santo templo en reverencia a ti. ",
      "8": "  Guíame, Yahvé, en tu justicia a causa de mis enemigos.   Haz tu camino directo ante mi cara. ",
      "9": "  Porque no hay fidelidad en su boca.   Su corazón es la destrucción.   Su garganta es una tumba abierta.   Halagan con su lengua. ",
      "10": "  Hazlos culpables, Dios.   Que caigan por sus propios consejos.   Échalos en la multitud de sus transgresiones,   porque se han rebelado contra ti. ",
      "11": "  Pero que se alegren todos los que se refugian en ti.   Que siempre griten de alegría, porque tú los defiendes.   Que también los que aman tu nombre se alegren en ti. ",
      "12": "  Porque bendecirás a los justos.   Yahvé, lo rodearás de favor como de un escudo."
    }
  }
};

