
	
export const bib_verses = {
  "psalms": {
    "38": {
      "1": "   Yahvé, no me reprendas en tu ira,   ni me castigues en tu caliente descontento. ",
      "2": "  Porque tus flechas me han atravesado,   tu mano me presiona con fuerza. ",
      "3": "  No hay solidez en mi carne a causa de tu indignación,   ni hay salud en mis huesos a causa de mi pecado. ",
      "4": "  Porque mis iniquidades han pasado por encima de mi cabeza.   Como carga pesada, son demasiado pesados para mí. ",
      "5": "  Mis heridas son repugnantes y corruptas   a causa de mi estupidez. ",
      "6": "  Me duele y me inclino mucho.   Voy de luto todo el día. ",
      "7": "  Porque mi cintura está llena de ardor.   No hay solidez en mi carne. ",
      "8": "  Me siento débil y gravemente herido.   He gemido por la angustia de mi corazón. ",
      "9": "  Señor, todo mi deseo está ante ti.   Mi gemido no se te oculta. ",
      "10": "  Mi corazón palpita.   Me fallan las fuerzas.   En cuanto a la luz de mis ojos, también me ha dejado. ",
      "11": "  Mis amantes y mis amigos se mantienen alejados de mi plaga.   Mis parientes están lejos. ",
      "12": "  También los que buscan mi vida ponen trampas.   Los que buscan mi daño hablan cosas maliciosas,   y meditar engaños todo el día. ",
      "13": "  Pero yo, como un sordo, no oigo.   Soy como un hombre mudo que no abre la boca. ",
      "14": "  Sí, soy como un hombre que no oye,   en cuya boca no hay reproches. ",
      "15": "  Porque espero en ti, Yahvé.   Tú responderás, Señor mi Dios. ",
      "16": "  Porque dije: “No dejes que se regodeen en mí,   o se exaltan sobre mí cuando mi pie resbala”. ",
      "17": "  Porque estoy dispuesto a caer.   Mi dolor está continuamente ante mí. ",
      "18": "  Porque declararé mi iniquidad.   Me arrepentiré de mi pecado. ",
      "19": "  Pero mis enemigos son vigorosos y numerosos.   Los que me odian sin razón son numerosos. ",
      "20": "  Los que dan el mal por el bien son también adversarios míos,   porque sigo lo que es bueno. ",
      "21": "  No me abandones, Yahvé.   Dios mío, no te alejes de mí. ",
      "22": "  Date prisapara ayudarme,   Señor, mi salvación."
    },
    "39": {
      "1": "   Dije: “Vigilaré mis caminos, para no pecar con mi lengua.   Guardaré mi boca con una brida mientras el malvado esté ante mí”. ",
      "2": "  Me quedé mudo de silencio.   Me callé, incluso de buenas.   Mi pena se agitó. ",
      "3": "  Mi corazón estaba caliente dentro de mí.   Mientras meditaba, el fuego ardía.   Hablé con la lengua: ",
      "4": "  “Yahvé, muéstrame mi fin,   cuál es la medida de mis días.   Hazme saber lo frágil que soy. ",
      "5": "  He aquí que has hecho que mis días sean anchos de mano.   Mi vida es como nada ante ti.   Ciertamente cada hombre es como un aliento”. Selah. ",
      "6": "  “Ciertamente, todo hombre camina como una sombra.   Seguramente se ocupan en vano.   Amontona, y no sabe quién recogerá. ",
      "7": "  Ahora, Señor, ¿qué espero?   Mi esperanza está en ti. ",
      "8": "  Líbrame de todas mis transgresiones.   No me hagas el reproche de los tontos. ",
      "9": "  Me quedé mudo.   No abrí la boca,   porque tú lo hiciste. ",
      "10": "  Aleja de mí tu azote.   Estoy vencido por el golpe de tu mano. ",
      "11": "  Cuando reprendes y corriges al hombre por su iniquidad,   consumes su riqueza como una polilla.   Ciertamente, todo hombre no es más que un soplo”. Selah. ",
      "12": "  “Escucha mi oración, Yahvé, y presta atención a mi clamor.   No te calles ante mis lágrimas.   Porque soy un extraño con vosotros,   un extranjero, como lo fueron todos mis padres. ",
      "13": "  Oh, perdóname, para que recupere las fuerzas,   antes de que me vaya y no exista más”."
    },
    "40": {
      "1": "   Esperé pacientemente a Yahvé.   Se volvió hacia mí y escuchó mi grito. ",
      "2": "  También a mí me sacó de un pozo horrible,   de la arcilla cenagosa.   Puso mis pies en una roca,   y me dio un lugar firme para pararme. ",
      "3": "  Ha puesto en mi boca un cántico nuevo, la alabanza a nuestro Dios.   Muchos lo verán, y temerán, y confiarán en Yahvé. ",
      "4": "  Dichoso el hombre que hace de Yahvé su confianza,   y no respeta a los soberbios, ni a los que se apartan a la mentira. ",
      "5": "  Muchas son, Yahvé, mi Dios, las obras maravillosas que has hecho,   y sus pensamientos que son hacia nosotros.   No pueden ser declarados de nuevo a usted.   Si quisiera declarar y hablar de ellos, son más de los que se pueden contar. ",
      "6": "  Sacrificio y ofrenda que no deseabas.   Me has abierto los oídos.   No has exigido holocausto ni ofrenda por el pecado. ",
      "7": "  Entonces dije: “He aquí que he venido.   Está escrito sobre mí en el libro del pergamino. ",
      "8": "  Me encanta hacer tu voluntad, Dios mío.   Sí, tu ley está en mi corazón”. ",
      "9": "  He proclamado la buena noticia de la justicia en la gran asamblea.   He aquí que no sellaré mis labios, Yahvé, tú lo sabes. ",
      "10": "  No he ocultado tu justicia en mi corazón.   He declarado tu fidelidad y tu salvación.   No he ocultado tu amorosa bondad y tu verdad a la gran asamblea. ",
      "11": "  No me niegues tus tiernas misericordias, Yahvé.   Que tu amorosa bondad y tu verdad me preserven continuamente. ",
      "12": "  Porque me han rodeado innumerables males.   Mis iniquidades me han alcanzado, de modo que no soy capaz de levantar la vista.   Son más que los pelos de mi cabeza.   Mi corazón me ha fallado. ",
      "13": "  Complácete, Yahvé, en librarme.   Apresúrate a ayudarme, Yahvé. ",
      "14": "  Que se decepcionen y se confundan juntos los que buscan mi alma para destruirla.   Que retrocedan y sean deshonrados los que se deleitan en mi daño. ",
      "15": "  Que queden desolados por su vergüenza los que me dicen: “¡Ah! ¡Ah!” ",
      "16": "  Que todos los que te buscan se regocijen y se alegren en ti.   Que los que aman tu salvación digan continuamente: “¡Sea exaltado Yahvé!” ",
      "17": "  Pero soy pobre y estoy necesitado.   Que el Señor piense en mí.   Tú eres mi ayuda y mi libertador.   No te demores, Dios mío."
    },
    "41": {
      "1": "   Dichoso el que considera a los pobres.   Yahvé lo librará en el día del mal. ",
      "2": "  Yahvé lo preservará y lo mantendrá con vida.   Será bendecido en la tierra,   y no lo entregará a la voluntad de sus enemigos. ",
      "3": "  Yahvé lo sostendrá en su lecho de enfermo,   y restaurarlo de su lecho de enfermedad. ",
      "4": "  Dije: “¡Yahvé, ten piedad de mí!   Cúrame, porque he pecado contra ti”. ",
      "5": "  Mis enemigos hablan mal de mí:   “¿Cuándo morirá y perecerá su nombre?” ",
      "6": "  Si viene a verme, habla con falsedad.   Su corazón recoge la iniquidad para sí mismo.   Cuando va al extranjero, lo cuenta. ",
      "7": "  Todos los que me odian susurran juntos contra mí.   Se imaginan lo peor para mí. ",
      "8": "  “Una mala enfermedad”, dicen, “lo ha afligido.   Ahora que yace no se levantará más”. ",
      "9": "  Sí, mi propio amigo familiar, en quien confié,   que comió el pan conmigo,   ha levantado su talón contra mí. ",
      "10": "  Pero tú, Yahvé, ten piedad de mí y levántame,   para que yo les pague. ",
      "11": "  Por esto sé que te deleitas en mí,   porque mi enemigo no triunfa sobre mí. ",
      "12": "  En cuanto a mí, me sostienes en mi integridad,   y ponme en tu presencia para siempre. ",
      "13": "  Benditosea Yahvé, el Dios de Israel,   ¡desde la eternidad y hasta la eternidad!   Amén y amén."
    },
    "42": {
      "1": "  Como el ciervo que busca los arroyos de agua,   por lo que mi alma suspira por ti, Dios.   ",
      "2": "  Mi alma tiene sed de Dios, del Dios vivo.   ¿Cuándo vendré a comparecer ante Dios? ",
      "3": "  Mis lágrimas han sido mi alimento día y noche,   mientras me preguntan continuamente: “¿Dónde está tu Dios?” ",
      "4": "  De esto me acuerdo, y derramo mi alma dentro de mí,   cómo solía ir con la multitud, y los llevaba a la casa de Dios,   con voz de alegría y alabanza, una multitud que celebra un día santo. ",
      "5": "  ¿Por qué te desesperas, alma mía?   ¿Por qué te perturbas dentro de mí?   ¡Espera en Dios!   Porque aún le alabaré por la ayuda salvadora de su presencia. ",
      "6": "  Dios mío, mi alma está desesperada dentro de mí.   Por eso me acuerdo de ti desde la tierra del Jordán,   las alturas del Hermón, desde la colina Mizar. ",
      "7": "  Llamadas profundas al ruido de sus cascadas.   Todas tus olas y tus olas me han barrido. ",
      "8": "  Yahvé  ordenará su bondad amorosa durante el día.   En la noche su canción estará conmigo:   una oración al Dios de mi vida. ",
      "9": "  Preguntaré a Dios, mi roca: “¿Por qué me has olvidado?   ¿Por qué voy de luto por la opresión del enemigo?” ",
      "10": "  Como con una espada en los huesos, mis adversarios me reprochan,   mientras me preguntan continuamente: “¿Dónde está tu Dios?” ",
      "11": "  ¿Por quéestás desesperada, alma mía?   ¿Por qué te perturbas dentro de mí?   ¡Espera en Dios! Porque todavía lo alabaré,   la ayuda salvadora de mi rostro, y mi Dios."
    },
    "43": {
      "1": "  Vindícame, Dios, y defiende mi causa contra una nación impía.   Oh, líbrame de los hombres engañosos y malvados. ",
      "2": "  Porque tú eres el Dios de mi fuerza. ¿Por qué me has rechazado?   ¿Por qué estoy de luto por la opresión del enemigo? ",
      "3": "  Oh, envía tu luz y tu verdad.   Deja que me guíen.   Deja que me lleven a tu santa colina,   a sus tiendas. ",
      "4": "  Entonces iré al altar de Dios,   a Dios, mi mayor alegría.   Te alabaré con el arpa, Dios, mi Dios. ",
      "5": "  ¿Por qué te desesperas, alma mía?   ¿Por qué te perturbas dentro de mí?   ¡Esperen en Dios!   Porque todavía lo alabaré:   mi Salvador, mi ayudante y mi Dios."
    },
    "44": {
      "1": "   Hemos escuchado con nuestros oídos, Dios;   nuestros padres nos han contado el trabajo que hicisteis en sus días,   en los días de antaño. ",
      "2": "  Has expulsado a las naciones con tu mano,   pero tú los plantaste.   Has afligido a los pueblos,   pero los difundes en el extranjero. ",
      "3": "  Porque no obtuvieron la tierra en posesión por su propia espada,   ni su propio brazo los salvó;   sino tu mano derecha, tu brazo y la luz de tu rostro,   porque les fuiste favorable. ",
      "4": "  Dios, tú eres mi Rey.   ¡Comando victorias para Jacob! ",
      "5": "  A través de ti, derrotaremos a nuestros adversarios.   Por tu nombre, aplastaremos a los que se levantan contra nosotros. ",
      "6": "  Porque no confiaré en mi arco,   ni mi espada me salvará. ",
      "7": "  Pero tú nos has salvado de nuestros adversarios,   y han avergonzado a los que nos odian. ",
      "8": "  En Dios nos hemos jactado todo el día.   Daremos gracias a tu nombre por siempre. Selah. ",
      "9": "  Pero ahora nos has rechazado y nos has deshonrado,   y no salgan con nuestros ejércitos. ",
      "10": "  Nos haces retroceder ante el adversario.   Los que nos odian se apropian del botín. ",
      "11": "  Nos has hecho como ovejas para comer,   y nos han dispersado entre las naciones. ",
      "12": "  Vendes a tu pueblo por nada,   y no han ganado nada con su venta. ",
      "13": "  Nos conviertes en un reproche para nuestros vecinos,   una burla y un escarnio a los que nos rodean. ",
      "14": "  Nos has convertido en un sinónimo entre las naciones,   una sacudida de cabeza entre los pueblos. ",
      "15": "  Todo el día mi deshonra está ante mí,   y la vergüenza cubre mi cara, ",
      "16": "  ante la burla de quien reprocha y abusa verbalmente,   por el enemigo y el vengador. ",
      "17": "  Todo esto se nos ha venido encima,   pero no te hemos olvidado.   No hemos sido falsos a su pacto. ",
      "18": "  Nuestro corazón no ha retrocedido,   ni nuestros pasos se han desviado de tu camino, ",
      "19": "  aunque nos hayas aplastado en la guarida de los chacales,   y nos cubrió con la sombra de la muerte. ",
      "20": "  Si hemos olvidado el nombre de nuestro Dios,   o extender nuestras manos a un dios extraño, ",
      "21": "  ¿No buscará Dios esto?   Porque él conoce los secretos del corazón. ",
      "22": "  Sí, por tu causa nos matan todo el día.   Se nos considera como ovejas para el matadero. ",
      "23": "  ¡Despierta!   ¿Por qué duermes, Señor?     ¡Levántate!   No nos rechaces para siempre. ",
      "24": "  ¿Por qué ocultas tu rostro?   ¿y olvidar nuestra aflicción y nuestra opresión? ",
      "25": "  Porque nuestra alma se inclina hacia el polvo.   Nuestro cuerpo se aferra a la tierra. ",
      "26": "  Levántatepara ayudarnos.   Redímenos por tu amorosa bondad."
    },
    "45": {
      "1": "   Mi corazón rebosa de un tema noble.   Recito mis versos para el rey.   Mi lengua es como la pluma de un hábil escritor. ",
      "2": "  Tú eres el más excelente de los hijos de los hombres.   La gracia ha ungido tus labios,   por eso Dios te ha bendecido para siempre. ",
      "3": "  Pon tu espada en el muslo, oh poderoso,   en tu esplendor y tu majestad. ",
      "4": "  En tu majestuosidad cabalga victorioso en nombre de la verdad, la humildad y la rectitud.   Deja que tu mano derecha muestre acciones asombrosas. ",
      "5": "  Tus flechas son afiladas.   Las naciones caen bajo ti, con flechas en el corazón de los enemigos del rey. ",
      "6": "  Tu trono, Dios, es eterno y para siempre.   Un cetro de equidad es el cetro de tu reino. ",
      "7": "  Has amado la justicia y odiado la maldad.   Por eso Dios, tu Dios, te ha ungido con el aceite de la alegría por encima de tus compañeros. ",
      "8": "  Todos tus vestidos huelen a mirra, áloe y casia.   De los palacios de marfil los instrumentos de cuerda te han alegrado. ",
      "9": "  Las hijas de los reyes están entre tus mujeres honorables.   A su derecha la reina se encuentra en oro de Ophir. ",
      "10": "  Escucha, hija, considera y vuelve tu oído.   Olvídate de tu propia gente, y también de la casa de tu padre. ",
      "11": "  Así el rey deseará tu belleza,   honradlo, pues es vuestro señor. ",
      "12": "  La hija de Tiro viene con un regalo.   Los ricos del pueblo suplican su favor. ",
      "13": "  La princesa en su interior es toda una gloria.   Su ropa está entretejida con oro. ",
      "14": "  Será llevada al rey en una obra bordada.   Las vírgenes, sus compañeras que la siguen, serán traídas a ti. ",
      "15": "  Con alegría y regocijo serán conducidos.   Entrarán en el palacio del rey. ",
      "16": "  Sus hijos ocuparán el lugar de sus padres.   Los harás príncipes en toda la tierra. ",
      "17": "  haré que tu nombre sea recordado en todas las generaciones.   Por eso los pueblos te darán gracias por los siglos de los siglos."
    },
    "46": {
      "1": "   Dios es nuestro refugio y nuestra fuerza,   una ayuda muy presente en los problemas. ",
      "2": "  Por eso no tendremos miedo, aunque la tierra cambie,   aunque las montañas se agiten en el corazón de los mares; ",
      "3": "  aunque sus aguas rugen y se agitan,   aunque las montañas tiemblen con su hinchazón. Selah. ",
      "4": "  Hay un río cuyas corrientes alegran la ciudad de Dios,   el lugar santo de las tiendas del Altísimo. ",
      "5": "  Dios está dentro de ella. Ella no será movida.   Dios la ayudará al amanecer. ",
      "6": "  Las naciones se enfurecieron. Los reinos se conmovieron.   Levantó la voz y la tierra se derritió. ",
      "7": "  El Señor de los Ejércitos está con nosotros.   El Dios de Jacob es nuestro refugio. Selah. ",
      "8": "  Vengan, vean las obras de Yahvé,   qué desolaciones ha hecho en la tierra. ",
      "9": "  Hace cesar las guerras hasta el fin de la tierra.   Rompe el arco y destroza la lanza.   Quema los carros en el fuego. ",
      "10": "  “Estad tranquilos y sabed que yo soy Dios.   Seré exaltado entre las naciones.   Seré exaltado en la tierra”. ",
      "11": "  Yahvéde los Ejércitos está con nosotros.   El Dios de Jacob es nuestro refugio. Selah.  "
    },
    "47": {
      "1": "   Oh, aplaudid todas las naciones.   ¡Grita a Dios con voz de triunfo! ",
      "2": "  Porque Yahvé el Altísimo es imponente.   Es un gran Rey sobre toda la tierra. ",
      "3": "  Él somete a las naciones bajo nosotros,   y pueblos bajo nuestros pies. ",
      "4": "  Él elige nuestra herencia por nosotros,   la gloria de Jacob a quien amó. Selah. ",
      "5": "  Dios ha subido con un grito,   Yahvé con el sonido de una trompeta. ",
      "6": "  ¡Cantad alabanzas a Dios! ¡Canten alabanzas!   ¡Cantad alabanzas a nuestro Rey! ¡Cantad alabanzas! ",
      "7": "  Porque Dios es el Rey de toda la tierra.   Canta alabanzas con comprensión. ",
      "8": "  Dios reina sobre las naciones.   Dios se sienta en su santo trono. ",
      "9": "  Los príncipes de los pueblos están reunidos,   el pueblo del Dios de Abraham.   Porque los escudos de la tierra pertenecen a Dios.   Es muy exaltado."
    },
    "48": {
      "1": "   Grande es Yahvé, y digno de gran alabanza,   en la ciudad de nuestro Dios, en su santo monte. ",
      "2": "  Hermoso en elevación, la alegría de toda la tierra,   es el Monte Zion, en los lados norte,   la ciudad del gran Rey. ",
      "3": "  Dios se ha mostrado en sus ciudadelas como un refugio. ",
      "4": "  Pues he aquí que los reyes se han reunido,   pasaron juntos. ",
      "5": "  Lo vieron y se asombraron.   Estaban consternados.   Se apresuraron a marcharse. ",
      "6": "  El temblor se apoderó de ellos allí,   dolor, como el de una mujer de parto. ",
      "7": "  Con el viento del este, rompes las naves de Tarsis. ",
      "8": "  Como hemos oído, hemos visto,   en la ciudad de Yahvé de los Ejércitos, en la ciudad de nuestro Dios.   Dios lo establecerá para siempre. Selah. ",
      "9": "  Hemos pensado en tu amorosa bondad, Dios,   en el centro de su templo. ",
      "10": "  Como tu nombre, Dios,   así es tu alabanza hasta los confines de la tierra.   Tu mano derecha está llena de justicia. ",
      "11": "  ¡Que se alegre el monte Sión!   Que las hijas de Judá se alegren por tus juicios. ",
      "12": "  Camina alrededor de Sión y rodéala.   Numerar sus torres. ",
      "13": "  Fíjate en sus baluartes.   Considera sus palacios,   para que lo cuentes a la siguiente generación. ",
      "14": "  Porque este Dios es nuestro Dios por los siglos de los siglos.   Él será nuestro guía incluso hasta la muerte."
    },
    "49": {
      "1": "   Oíd esto, todos los pueblos.   Escuchad, todos los habitantes del mundo, ",
      "2": "  tanto de baja como de alta,   ricos y pobres juntos. ",
      "3": "  Mi boca dirá palabras de sabiduría.   Mi corazón pronunciará la comprensión. ",
      "4": "  Inclinaré mi oído a un proverbio.   Resolveré mi acertijo en el arpa. ",
      "5": "  ¿Por qué he de temer en los días de maldad?   cuando me rodea la iniquidad en los talones? ",
      "6": "  Los que confían en su riqueza,   y se jactan de la multitud de sus riquezas... ",
      "7": "  ninguno de ellos puede redimir a su hermano,   ni dar a Dios un rescate por él. ",
      "8": "  Porque la redención de su vida es costosa,   ningún pago es suficiente, ",
      "9": "  para que viva eternamente,   para que no vea la corrupción. ",
      "10": "  Porque ve que los sabios mueren;   así mismo el necio y el insensato perecen,   y dejar su riqueza a otros. ",
      "11": "  Su pensamiento interior es que sus casas serán eternas,   y sus moradas para todas las generaciones.   Dan su nombre a sus tierras. ",
      "12": "  Pero el hombre, a pesar de sus riquezas, no perdura.   Es como los animales que perecen. ",
      "13": "  Este es el destino de los insensatos,   y de los que aprueban sus dichos. Selah. ",
      "14": "  Están designados como un rebaño para el Seol.     La muerte será su pastor.   Los rectos se enseñorearán de ellos por la mañana.   Su belleza se descompondrá en el Seol,     lejos de su mansión. ",
      "15": "  Pero Dios redimirá mi alma del poder del Seol,     porque él me recibirá. Selah. ",
      "16": "  No tengas miedo cuando un hombre se hace rico,   cuando la gloria de su casa se incremente; ",
      "17": "  porque cuando muera no se llevará nada.   Su gloria no descenderá tras él. ",
      "18": "  Aunque mientras vivió bendijo su alma —   y los hombres te alaban cuando te va bien... ",
      "19": "  irá a la generación de sus padres.   Nunca verán la luz. ",
      "20": "  Un hombre que tiene riquezas sin entendimiento,   es como los animales que perecen."
    },
    "50": {
      "1": "   El Poderoso, Dios, Yahvé, habla,   y llama a la tierra desde el amanecer hasta el atardecer. ",
      "2": "  De Sión, la perfección de la belleza,   Dios brilla. ",
      "3": "  Nuestro Dios viene y no calla.   Un fuego devora ante él.   Es muy tormentoso a su alrededor. ",
      "4": "  Llama a los cielos,   a la tierra, para juzgar a su pueblo: ",
      "5": "  “Reúne a mis santos conmigo,   los que han hecho un pacto conmigo mediante el sacrificio”. ",
      "6": "  Los cielos declararán su justicia,   porque Dios mismo es juez. Selah. ",
      "7": "  “Oíd, pueblo mío, y yo hablaré.   Israel, testificaré contra ti.   Yo soy Dios, tu Dios. ",
      "8": "  No te reprendo por tus sacrificios.   Tus holocaustos están continuamente ante mí. ",
      "9": "  No tengo necesidad de un toro de tu plaza,   ni los machos cabríos de sus corrales. ",
      "10": "  Porque todo animal del bosque es mío,   y el ganado en mil colinas. ",
      "11": "  Conozco todas las aves de las montañas.   Los animales salvajes del campo son míos. ",
      "12": "  Si tuviera hambre, no te lo diría,   porque el mundo es mío, y todo lo que hay en él. ",
      "13": "  Comeré carne de toro,   o beber la sangre de las cabras? ",
      "14": "  Ofrece a Dios el sacrificio de acción de gracias.   Pagad vuestros votos al Altísimo. ",
      "15": "  Invócame en el día de la angustia.   Yo te libraré y tú me honrarás”. ",
      "16": "  Pero al malvado Dios le dice,   “¿Qué derecho tienes a declarar mis estatutos,   que has tomado mi pacto en tus labios, ",
      "17": "  ya que odias la instrucción,   y lanzar mis palabras detrás de ti? ",
      "18": "  Cuando viste a un ladrón, consentiste con él,   y han participado con adúlteros. ",
      "19": "  “Das tu boca al mal.   Tu lengua enmarca el engaño. ",
      "20": "  Te sientas y hablas contra tu hermano.   Calumnias al hijo de tu propia madre. ",
      "21": "  Tú has hecho estas cosas y yo he guardado silencio.   Pensaste que yo era igual que tú.   Te reprenderé y te acusaré delante de tus ojos. ",
      "22": "  “Ahora consideren esto, ustedes que se olvidan de Dios,   para que no te haga pedazos y no haya quien te libere. ",
      "23": "  Quienofrece el sacrificio de acción de gracias me glorifica,   y prepara su camino para que le muestre la salvación de Dios”."
    },
    "51": {
      "1": "   Ten piedad de mí, Dios, según tu amorosa bondad.   Según la multitud de tus misericordias, borra mis transgresiones. ",
      "2": "  Lávame completamente de mi iniquidad.   Límpiame de mi pecado. ",
      "3": "  Porque conozco mis transgresiones.   Mi pecado está constantemente ante mí. ",
      "4": "  Contra ti, y sólo contra ti, he pecado,   y he hecho lo que es malo a tus ojos,   por lo que se puede demostrar que tiene razón cuando habla,   y se justifica cuando se juzga. ",
      "5": "  He aquí que he nacido en la iniquidad.   Mi madre me concibió en pecado. ",
      "6": "  He aquí que deseas la verdad en las partes internas.   Me enseñas la sabiduría en lo más íntimo. ",
      "7": "  Purifícame con el hisopo y quedaré limpio.   Lávame y quedaré más blanco que la nieve. ",
      "8": "  Déjame oír la alegría y el gozo,   para que los huesos que has roto se alegren. ",
      "9": "  Esconde tu rostro de mis pecados,   y borra todas mis iniquidades. ",
      "10": "  Crea en mí un corazón limpio, oh Dios.   Renueva un espíritu correcto dentro de mí. ",
      "11": "  No me eches de tu presencia,   y no me quites tu Espíritu Santo. ",
      "12": "  Devuélveme la alegría de tu salvación.   Sosténgame con un espíritu dispuesto. ",
      "13": "  Entonces enseñaré a los transgresores tus caminos.   Los pecadores se convertirán a ti. ",
      "14": "  Líbrame de la culpa del derramamiento de sangre, oh Dios, el Dios de mi salvación.   Mi lengua cantará en voz alta tu justicia. ",
      "15": "  Señor, abre mis labios.   Mi boca declarará tu alabanza. ",
      "16": "  Porque no te complace el sacrificio, si no, lo daría.   No te gusta el holocausto. ",
      "17": "  Los sacrificios de Dios son un espíritu quebrantado.   Oh Dios, no despreciarás un corazón roto y contrito. ",
      "18": "  Hazle el bien a Sión.   Construye los muros de Jerusalén. ",
      "19": "  Entonces te deleitarás con los sacrificios de la justicia,   en los holocaustos y en los holocaustos completos.   Entonces ofrecerán toros en tu altar."
    },
    "52": {
      "1": "   ¿Por qué te jactas de hacer travesuras, hombre poderoso?   La bondad amorosa de Dios perdura continuamente. ",
      "2": "  Tu lengua trama la destrucción,   como una navaja afilada, trabajando con engaño. ",
      "3": "  Amas el mal más que el bien,   mintiendo en lugar de decir la verdad. Selah. ",
      "4": "  Amas todas las palabras devoradoras,   tu lengua engañosa. ",
      "5": "  Dios también te destruirá para siempre.   Él te tomará y te sacará de tu tienda,   y te arrancaré de la tierra de los vivos. Selah. ",
      "6": "  También los justos lo verán y temerán,   y se ríen de él, diciendo, ",
      "7": "  “He aquí el hombre que no hizo de Dios su fuerza,   sino que confió en la abundancia de sus riquezas,   y se fortaleció en su maldad”. ",
      "8": "  Pero en cuanto a mí, soy como un olivo verde en la casa de Dios.   Confío en la bondad amorosa de Dios por siempre y para siempre. ",
      "9": "  Te daré gracias por siempre, porque lo has hecho.   Esperaré en tu nombre, porque es bueno,   en presencia de tus santos."
    },
    "53": {
      "1": "   El necio ha dicho en su corazón: “No hay Dios”.   Son corruptos y han hecho una iniquidad abominable.   No hay nadie que haga el bien. ",
      "2": "  Dios mira desde el cielo a los hijos de los hombres,   para ver si hay alguno que lo haya entendido,   que buscan a Dios. ",
      "3": "  Cada uno de ellos ha vuelto.   Se han ensuciado juntos.   No hay nadie que haga el bien, no, ninguno. ",
      "4": "  No tienen conocimiento los obreros de la iniquidad,   que se comen a mi pueblo como si fuera pan,   y no invocan a Dios? ",
      "5": "  Allí estaban con gran temor, donde no había temor,   porque Dios ha dispersado los huesos del que acampa contra ti.   Los has puesto en evidencia,   porque Dios los ha rechazado. ",
      "6": "  ¡Ohque la salvación de Israel salga de Sión!   Cuando Dios trae de vuelta a su pueblo del cautiverio,   entonces Jacob se alegrará,   e Israel se alegrará."
    },
    "54": {
      "1": "   Sálvame, Dios, por tu nombre.   Reivindícame con tu poder. ",
      "2": "  Escucha mi oración, Dios.   Escucha las palabras de mi boca. ",
      "3": "  Porque los extraños se han levantado contra mí.   Hombres violentos han buscado mi alma.   No han puesto a Dios delante de ellos. Selah. ",
      "4": "  He aquí que Dios es mi ayudante.   El Señor es quien sostiene mi alma. ",
      "5": "  Él pagará el mal a mis enemigos.   Destrúyelos con tu verdad. ",
      "6": "  Con una ofrenda voluntaria, te sacrificaré.   Daré gracias a tu nombre, Yahvé, porque es bueno. ",
      "7": "  Porque me ha librado de toda angustia.   Mi ojo ha visto el triunfo sobre mis enemigos."
    },
    "55": {
      "1": "   Escucha mi oración, Dios.   No te escondas de mi súplica. ",
      "2": "  Atiéndeme y respóndeme.   Estoy inquieto en mi queja,   y gime",
      "3": "por la voz del enemigo,   a causa de la opresión de los malvados.   Porque me hacen sufrir.   Con rabia me guardan rencor. ",
      "4": "  Mi corazón está gravemente dolorido en mi interior.   Los terrores de la muerte han caído sobre mí. ",
      "5": "  El temor y el temblor se han apoderado de mí.   El horror me ha abrumado. ",
      "6": "  Dije: “¡Oh, si tuviera alas como una paloma!   Entonces volaría y descansaría. ",
      "7": "  He aquí que entonces me alejaría.   Me alojaría en el desierto”. Selah. ",
      "8": "  “Me apresuraría a refugiarme del viento tempestuoso y de la tormenta”. ",
      "9": "  Confúndelos, Señor, y confunde su lenguaje,   porque he visto violencia y lucha en la ciudad. ",
      "10": "  Día y noche merodean por sus muros.   La malicia y el abuso también están en ella. ",
      "11": "  Las fuerzas destructivas están dentro de ella.   Las amenazas y las mentiras no salen de sus calles. ",
      "12": "  Porque no fue un enemigo quien me insultó,   entonces podría haberlo soportado.   Tampoco el que me odiaba se levantó contra mí,   entonces me habría escondido de él. ",
      "13": "  Pero fuiste tú, un hombre como yo,   mi compañero, y mi amigo familiar. ",
      "14": "  Tomamos juntos una dulce comunión.   Caminamos en la casa de Dios con compañía. ",
      "15": "  Que la muerte les llegue de repente.   Que bajen vivos al Seol.     Porque la maldad está entre ellos, en su morada. ",
      "16": "  En cuanto a mí, invocaré a Dios.   Yahvé me salvará. ",
      "17": "  Por la tarde, por la mañana y al mediodía, gritaré de angustia.   Escuchará mi voz. ",
      "18": "  Él ha redimido mi alma en paz de la batalla que había contra mí,   aunque hay muchos que se oponen a mí. ",
      "19": "  Dios, que está entronizado para siempre,   los escuchará y responderá. Selah.   Nunca cambian   y no teman a Dios. ",
      "20": "  Levanta las manos contra sus amigos.   Ha violado su pacto. ",
      "21": "  Su boca era suave como la mantequilla,   pero su corazón estaba en guerra.   Sus palabras eran más suaves que el aceite,   sin embargo, eran espadas desenvainadas. ",
      "22": "  Echa tu carga sobre Yahvé y él te sostendrá.   Él nunca permitirá que los justos sean conmovidos. ",
      "23": "  Pero tú, Dios, los harás descender al pozo de la destrucción.   Los hombres sanguinarios y engañosos no vivirán ni la mitad de sus días,   pero confiaré en ti."
    },
    "56": {
      "1": "   Ten piedad de mí, Dios, porque el hombre quiere engullirme.   Todo el día me ataca y me oprime. ",
      "2": "  Mis enemigos quieren engullirme todo el día,   porque son muchos los que luchan orgullosamente contra mí. ",
      "3": "  Cuando tengo miedo,   Pondré mi confianza en ti. ",
      "4": "  En Dios, alabo su palabra.   En Dios, pongo mi confianza.   No tendré miedo.   ¿Qué puede hacerme la carne? ",
      "5": "  Todo el día tergiversan mis palabras.   Todos sus pensamientos son contra mí para mal. ",
      "6": "  Conspiran y acechan,   vigilando mis pasos.   Están ansiosos por quitarme la vida. ",
      "7": "  ¿Escaparán por la iniquidad?   En la cólera, Dios arroja a los pueblos. ",
      "8": "  Tú cuentas mis andanzas.   Pusiste mis lágrimas en tu contenedor.   ¿No están en tu libro? ",
      "9": "  Entonces mis enemigos se volverán el día que yo llame.   Sé esto: que Dios es para mí. ",
      "10": "  En Dios, alabaré su palabra.   En Yahvé, alabaré su palabra. ",
      "11": "  He puesto mi confianza en Dios.   No tendré miedo.   ¿Qué puede hacerme el hombre? ",
      "12": "  Tus votos están sobre mí, Dios.   Te daré las gracias por las ofrendas. ",
      "13": "  Porque has librado mi alma de la muerte,   y evitó que se me cayeran los pies,   para que pueda caminar ante Dios a la luz de los vivos."
    },
    "57": {
      "1": "   Ten piedad de mí, Dios, ten piedad de mí,   porque mi alma se refugia en ti.   Sí, a la sombra de tus alas me refugiaré,   hasta que el desastre haya pasado. ",
      "2": "  Clamo al Dios Altísimo,   a Dios que cumple mis peticiones por mí. ",
      "3": "  Él enviará desde el cielo y me salvará,   reprende al que me persigue. Selah.   Dios enviará su amorosa bondad y su verdad. ",
      "4": "  Mi alma está entre leones.   Me encuentro entre los que se prenden fuego,   incluso los hijos de los hombres, cuyos dientes son lanzas y flechas,   y su lengua una espada afilada. ",
      "5": "  ¡Sé exaltado, Dios, por encima de los cielos!   ¡Que tu gloria esté por encima de toda la tierra! ",
      "6": "  Han preparado una red para mis pasos.   Mi alma se inclina.   Cavan una fosa antes que yo.   Ellos mismos caen en el medio. Selah. ",
      "7": "  Mi corazón está firme, Dios.   Mi corazón es firme.   Cantaré, sí, cantaré alabanzas. ",
      "8": "  ¡Despierta, mi gloria! ¡Despierta, laúd y arpa!   Despertaré al amanecer. ",
      "9": "  Te daré gracias, Señor, entre los pueblos.   Te cantaré alabanzas entre las naciones. ",
      "10": "  Porque tu gran bondad llega hasta los cielos,   y tu verdad a los cielos. ",
      "11": "  Sé exaltado, Dios, por encima de los cielos.   Que tu gloria sea sobre toda la tierra."
    },
    "58": {
      "1": "   ¿Acaso habláis con justicia, los silenciosos?   ¿Juzgáis sin culpa, hijos de los hombres? ",
      "2": "  No, en tu corazón traman la injusticia.   Mide la violencia de tus manos en la tierra. ",
      "3": "  Los malvados se extravían desde el vientre.   Son díscolos desde que nacen, hablando mentiras. ",
      "4": "  Su veneno es como el de una serpiente,   como una cobra sorda que tapa su oreja, ",
      "5": "  que no escucha la voz de los encantadores,   por muy hábil que sea el encantador. ",
      "6": "  Rompe sus dientes, Dios, en su boca.   Saca los grandes dientes de los leones jóvenes, Yahvé. ",
      "7": "  Que se desvanezcan como el agua que fluye.   Cuando tensen el arco, que sus flechas sean desafiladas. ",
      "8": "  Que sean como un caracol que se derrite y pasa,   como el niño que nace muerto, que no ha visto el sol. ",
      "9": "  Antes de que sus macetas puedan sentir el calor de las espinas,   barrerá lo verde y lo ardiente por igual. ",
      "10": "  El justo se alegrará cuando vea la venganza.   Lavará sus pies en la sangre de los impíos, ",
      "11": "  para que los hombres digan: “Ciertamente hay una recompensa para los justos.   Ciertamente hay un Dios que juzga la tierra”."
    },
    "59": {
      "1": "   Líbrame de mis enemigos, Dios mío.   Ponme en alto de los que se levantan contra mí. ",
      "2": "  Líbrame de los obreros de la iniquidad.   Sálvame de los hombres sedientos de sangre. ",
      "3": "  Porque, he aquí, ellos acechan mi alma.   Los poderosos se reúnen contra mí,   no por mi desobediencia, ni por mi pecado, Yahvé. ",
      "4": "  No he hecho nada malo, pero están dispuestos a atacarme.   ¡Levántate, mira, y ayúdame! ",
      "5": "  Tú, Yahvé Dios de los Ejércitos, el Dios de Israel,   despierta para castigar a las naciones.   No tengas piedad de los malvados traidores. Selah. ",
      "6": "  Regresan al atardecer, aullando como perros,   y merodean por la ciudad. ",
      "7": "  He aquí que vomitan con la boca.   Las espadas están en sus labios,   “Porque”, dicen, “¿quién nos escucha?” ",
      "8": "  Pero tú, Yahvé, te ríes de ellos.   Te burlas de todas las naciones. ",
      "9": "  Oh, mi Fuerza, yo velo por ti,   porque Dios es mi alta torre. ",
      "10": "  Mi Dios irá delante de mí con su amorosa bondad.   Dios me permitirá mirar a mis enemigos con triunfo. ",
      "11": "  No los mates, o mi pueblo se olvidará.   Dispérsalos con tu poder y derríbalos, Señor, nuestro escudo. ",
      "12": "  Por el pecado de su boca y las palabras de sus labios,   que se dejen atrapar por su orgullo,   por las maldiciones y mentiras que pronuncian. ",
      "13": "  Consúmelos con ira.   Consúmelos y ya no existirán.   Hazles saber que Dios gobierna en Jacob,   hasta los confines de la tierra. Selah. ",
      "14": "  Al anochecer, que vuelvan.   Que aúllen como un perro y recorran la ciudad. ",
      "15": "  Andarán de un lado a otro en busca de comida,   y esperar toda la noche si no están satisfechos. ",
      "16": "  Pero yo cantaré tu fuerza.   Sí, cantaré en voz alta tu amorosa bondad por la mañana.   Porque tú has sido mi alta torre,   un refugio en el día de mi angustia. ",
      "17": "  A ti, mi fuerza, te cantaré alabanzas.   Porque Dios es mi alta torre, el Dios de mi misericordia."
    },
    "60": {
      "1": "   Dios, nos has rechazado.   Nos has destrozado.   Te has enfadado.   Restablézcanos, de nuevo. ",
      "2": "  Has hecho temblar la tierra.   Lo has roto.   Arreglar sus fracturas,   porque tiembla. ",
      "3": "  Has mostrado a tu pueblo cosas difíciles.   Nos has hecho beber el vino que nos hace tambalear. ",
      "4": "  Has dado un estandarte a los que te temen,   para que se muestre por la verdad. Selah. ",
      "5": "  Para que tu amado sea liberado,   salva con tu mano derecha, y respóndenos. ",
      "6": "  Dios ha hablado desde su santuario:   “Voy a triunfar.   Dividiré Siquem,   y medir el valle de Succoth. ",
      "7": "  Mío es Galaad y mío es Manasés.   Efraín también es la defensa de mi cabeza.   Judá es mi cetro. ",
      "8": "  Moab es mi lavabo.   Lanzaré mi sandalia sobre Edom.   Grito de triunfo sobre Filistea”. ",
      "9": "  ¿Quién me llevará a la ciudad fuerte?   ¿Quién me ha llevado a Edom? ",
      "10": "  ¿No nos has rechazado, Dios, a nosotros?   No sales con nuestros ejércitos, Dios. ",
      "11": "  Danos ayuda contra el adversario,   porque la ayuda del hombre es vana. ",
      "12": "  Por medio de Dios lo haremos con valentía,   ya que es él quien va a pisotear a nuestros adversarios."
    },
    "61": {
      "1": "   Escucha mi clamor, Dios.   Escucha mi oración. ",
      "2": "  Desde el fin de la tierra, te llamaré cuando mi corazón esté abrumado.   Condúceme a la roca que es más alta que yo. ",
      "3": "  Porque tú has sido un refugio para mí,   una torre fuerte del enemigo. ",
      "4": "  Yo habitaré en tu tienda para siempre.   Me refugiaré al abrigo de tus alas. Selah. ",
      "5": "  Porque tú, Dios, has escuchado mis votos.   Me has dado la herencia de los que temen tu nombre. ",
      "6": "  Prolongarás la vida del rey.   Sus años serán para generaciones. ",
      "7": "  Será entronizado en la presencia de Dios para siempre.   Designa tu amorosa bondad y la verdad, para que lo preserven. ",
      "8": "  Así cantaré alabanzas a tu nombre para siempre,   para que pueda cumplir mis votos diariamente."
    },
    "62": {
      "1": "   Mi alma descansa sólo en Dios.   Mi salvación viene de él. ",
      "2": "  Sólo él es mi roca, mi salvación y mi fortaleza.   Nunca seré muy agitado. ",
      "3": "  ¿Cuánto tiempo agredirás a un hombre?   ¿Podrían todos ustedes tirarlo al suelo?   como un muro inclinado, como una valla tambaleante? ",
      "4": "  Tienen toda la intención de derribarlo de su elevado lugar.   Se deleitan con las mentiras.   Bendicen con la boca, pero maldicen por dentro. Selah. ",
      "5": "  Alma mía, espera en silencio sólo a Dios,   porque mi expectativa es de él. ",
      "6": "  Sólo él es mi roca y mi salvación, mi fortaleza.   No voy a ser sacudido. ",
      "7": "  Mi salvación y mi honor están con Dios.   La roca de mi fuerza, y mi refugio, está en Dios. ",
      "8": "  Confiad en él en todo momento, vosotros.   Derrama tu corazón ante él.   Dios es un refugio para nosotros. Selah. ",
      "9": "  Seguramente los hombres de bajo grado son sólo un soplo,   y los hombres de alto grado son una mentira.   En los saldos subirán.   Juntos son más ligeros que un soplo. ",
      "10": "  No confíes en la opresión.   No te envanezcas en el robo.   Si la riqueza aumenta,   no pongas tu corazón en ellos. ",
      "11": "  Dios ha hablado una vez;   Dos veces he escuchado esto,   ese poder pertenece a Dios. ",
      "12": "  También a ti, Señor, te corresponde la bondad,   pues recompensas a cada uno según su trabajo."
    },
    "63": {
      "1": "   Dios, tú eres mi Dios.   Te buscaré con ahínco.   Mi alma tiene sed de ti.   Mi carne te anhela,   en una tierra seca y cansada, donde no hay agua. ",
      "2": "  Así te he visto en el santuario,   viendo tu poder y tu gloria. ",
      "3": "  Porque tu bondad amorosa es mejor que la vida,   mis labios te alabarán. ",
      "4": "  Así te bendeciré mientras viva.   Levantaré mis manos en tu nombre. ",
      "5": "  Mi alma se saciará como del más rico alimento.   Mi boca te alabará con labios alegres, ",
      "6": "  cuando te recuerdo en mi cama,   y pensar en ti en las guardias nocturnas. ",
      "7": "  Porque tú has sido mi ayuda.   Me alegraré a la sombra de tus alas. ",
      "8": "  Mi alma permanece cerca de ti.   Tu mano derecha me sostiene. ",
      "9": "  Pero los que buscan mi alma para destruirla   irán a las partes bajas de la tierra. ",
      "10": "  Serán entregados al poder de la espada.   Serán comida para chacales. ",
      "11": "  Pero el rey se alegrará en Dios.   Todos los que juran por él lo alabarán,   porque la boca de los que hablan mentiras será silenciada."
    },
    "64": {
      "1": "   Escucha mi voz, Dios, en mi queja.   Preserva mi vida del miedo al enemigo. ",
      "2": "  Escóndeme de la conspiración de los malvados,   de la ruidosa multitud de los que hacen el mal; ",
      "3": "  que afilan su lengua como una espada,   y apuntan sus flechas, palabras mortales, ",
      "4": "  para disparar a hombres inocentes desde emboscadas.   Le disparan de repente y sin miedo. ",
      "5": "  Se alientan a sí mismos en planes malvados.   Hablan de poner trampas en secreto.   Dicen: “¿Quién los verá?” ",
      "6": "  Conspiran la injusticia, diciendo: “¡Hemos hecho un plan perfecto!”   Seguramente la mente y el corazón del hombre son astutos. ",
      "7": "  Pero Dios les disparará.   Serán abatidos repentinamente con una flecha. ",
      "8": "  Sus propias lenguas los arruinarán.   Todos los que los vean sacudirán la cabeza. ",
      "9": "  Toda la humanidad tendrá miedo.   Declararán la obra de Dios,   y reflexionará sabiamente sobre lo que ha hecho. ",
      "10": "  Los justos se alegrarán en Yahvé,   y se refugiarán en él.   Todos los rectos de corazón lo alabarán."
    },
    "65": {
      "1": "   La alabanza te espera, Dios, en Sión.   Los votos serán realizados a usted. ",
      "2": "  Tú que escuchas la oración,   todos los hombres vendrán a ti. ",
      "3": "  Pecados me abrumó,   pero tú expiaste nuestras transgresiones. ",
      "4": "  Dichoso el que eliges y haces que se acerque,   para que viva en tus tribunales.   Nos llenaremos de la bondad de tu casa,   tu templo sagrado. ",
      "5": "  Con impresionantes obras de justicia, nos respondes,   Dios de nuestra salvación.   Tú que eres la esperanza de todos los confines de la tierra,   de los que están lejos en el mar. ",
      "6": "  Con tu poder, formas las montañas,   habiéndote armado de fuerza. ",
      "7": "  Tú calmas el rugido de los mares,   el rugido de sus olas,   y la agitación de las naciones. ",
      "8": "  También los que habitan en lugares lejanos se asustan ante tus maravillas.   Llamas al alba de la mañana y a la tarde con cantos de alegría. ",
      "9": "  Tú visitas la tierra y la riegas.   Lo enriqueces enormemente.   El río de Dios está lleno de agua.   Tú les proporcionas el grano, pues así lo has ordenado. ",
      "10": "  Empapas sus surcos.   Nivela sus crestas.   Lo suavizas con duchas.   Lo bendices con un cultivo. ",
      "11": "  Coronas el año con tu generosidad.   Sus carros rebosan de abundancia. ",
      "12": "  Las praderas salvajes se desbordan.   Las colinas se visten de alegría. ",
      "13": "  Los pastos deestán cubiertos de rebaños.   Los valles también están revestidos de grano.   ¡Gritan de alegría!   También cantan."
    },
    "66": {
      "1": "   ¡Aclamad a Dios con alegría, toda la tierra! ",
      "2": "  ¡Cantad a la gloria de su nombre!   ¡Ofrezcan gloria y alabanza! ",
      "3": "  Dile a Dios: “¡Cuán asombrosas son tus obras!   Por la grandeza de tu poder, tus enemigos se someten a ti. ",
      "4": "  Toda la tierra te adorará,   y te cantará;   cantarán a tu nombre”. Selah. ",
      "5": "  Venid y ved las hazañas de Dios.   una obra impresionante en favor de los hijos de los hombres. ",
      "6": "  Convirtió el mar en tierra seca.   Atravesaron el río a pie.   Allí, nos regocijamos en él. ",
      "7": "  Él gobierna con su poderío para siempre.   Sus ojos vigilan a las naciones.   No dejes que los rebeldes se levanten contra él. Selah. ",
      "8": "  ¡Alabad a nuestro Dios, pueblos!   Haz que se escuche el sonido de su alabanza, ",
      "9": "  que preserva nuestra vida entre los vivos,   y no permite que nuestros pies se muevan. ",
      "10": "  Porque tú, Dios, nos has puesto a prueba.   Nos has refinado, como se refina la plata. ",
      "11": "  Nos has llevado a la cárcel.   Has puesto una carga sobre nuestras espaldas. ",
      "12": "  Permitiste que los hombres pasaran por encima de nuestras cabezas.   Pasamos por el fuego y por el agua,   pero nos has traído al lugar de la abundancia. ",
      "13": "  Entraré en tu templo con holocaustos.   Te pagaré mis votos,",
      "14": "que mis labios prometieron,   y mi boca hablaba, cuando estaba angustiado. ",
      "15": "  Te ofreceré holocaustos de animales gordos,   con la ofrenda de carneros,   Ofreceré toros con cabras. Selah. ",
      "16": "  Venid a escuchar, todos los que teméis a Dios.   Declararé lo que ha hecho por mi alma. ",
      "17": "  Le grité con la boca.   Fue ensalzado con mi lengua. ",
      "18": "  Si yo acariciara el pecado en mi corazón,   el Señor no habría escuchado. ",
      "19": "  Pero, ciertamente, Dios ha escuchado.   Él ha escuchado la voz de mi oración. ",
      "20": "  Bendito sea Dios, que no ha rechazado mi oración,   ni su amorosa bondad de mi parte."
    },
    "67": {
      "1": "   Que Dios se apiade de nosotros, que nos bendiga,   y haz que su rostro brille sobre nosotros. Selah. ",
      "2": "  Para que tu camino sea conocido en la tierra,   y tu salvación entre todas las naciones, ",
      "3": "  que los pueblos te alaben, Dios.   Que todos los pueblos te alaben. ",
      "4": "  Que las naciones se alegren y canten de alegría,   porque juzgarás a los pueblos con equidad,   y gobernar las naciones de la tierra. Selah. ",
      "5": "  Que los pueblos te alaben, Dios.   Que todos los pueblos te alaben. ",
      "6": "  La tierra ha dado sus frutos.   Dios, incluso nuestro propio Dios, nos bendecirá. ",
      "7": "  Dios nos bendecirá.   Todos los confines de la tierra le temerán."
    },
    "68": {
      "1": "   ¡Que se levante Dios!   ¡Que se dispersen sus enemigos!   Que los que lo odian también huyan ante él. ",
      "2": "  Como el humo se aleja,   así que ahuyéntalos.   Como la cera se derrite ante el fuego,   que los malvados perezcan ante la presencia de Dios. ",
      "3": "  Pero que los justos se alegren.   Que se alegren ante Dios.   Sí, que se regocijen con alegría. ",
      "4": "  ¡Cantad a Dios! ¡Cantad alabanzas a su nombre!   Exalta al que cabalga sobre las nubes:   ¡a Yah, su nombre!   Alégrate ante él. ",
      "5": "  Padre de los huérfanos y defensor de las viudas,   es Dios en su santa morada. ",
      "6": "  Dios pone a los solitarios en las familias.   Saca a los prisioneros con el canto,   pero los rebeldes habitan en una tierra quemada por el sol. ",
      "7": "  Dios, cuando saliste ante tu pueblo,   cuando marchaste por el desierto... Selah. ",
      "8": "  La tierra tembló.   El cielo también derramó lluvia ante la presencia del Dios del Sinaí —   ante la presencia de Dios, el Dios de Israel. ",
      "9": "  Tú, Dios, enviaste una lluvia abundante.   Has confirmado tu herencia cuando estaba agotada. ",
      "10": "  Su congregación vivía en ella.   Tú, Dios, preparaste tu bondad para los pobres. ",
      "11": "  El Señor anunció la palabra.   Los que lo proclaman son una gran empresa. ",
      "12": "  “¡Reyes de los ejércitos huyen! Huyen!”   La que espera en casa reparte el botín, ",
      "13": "  mientras duermes entre las hogueras,   las alas de una paloma enfundadas en plata,   sus plumas con oro brillante. ",
      "14": "  Cuando el Todopoderoso dispersó a los reyes en ella,   nevó en Zalmon. ",
      "15": "  Las montañas de Basán son montañas majestuosas.   Las montañas de Basán son escarpadas. ",
      "16": "  ¿Por qué miráis con envidia, montañas escarpadas,   en la montaña donde Dios decide reinar?   Sí, Yahvé morará allí para siempre. ",
      "17": "  Los carros de Dios son decenas de miles y miles de miles.   El Señor está entre ellos, desde el Sinaí, en el santuario. ",
      "18": "  Has subido a lo alto.   Has llevado a los cautivos.   Has recibido regalos entre la gente,   sí, también entre los rebeldes, para que Yah Dios habite allí. ",
      "19": "  Bendito sea el Señor, que cada día soporta nuestras cargas,   el Dios que es nuestra salvación. Selah. ",
      "20": "  Dios es para nosotros un Dios de liberación.   A Yahvé, el Señor, le corresponde escapar de la muerte. ",
      "21": "  Pero Dios atravesará la cabeza de sus enemigos,   el cuero cabelludo de aquel que aún continúa en su culpabilidad. ",
      "22": "  El Señor dijo: “Te traeré de nuevo desde Basán,   Te traeré de nuevo desde las profundidades del mar, ",
      "23": "  para que los aplastes, mojando tu pie en la sangre,   para que las lenguas de tus perros tengan su parte de tus enemigos”. ",
      "24": "  Han visto tus procesiones, Dios,   hasta las procesiones de mi Dios, mi Rey, en el santuario. ",
      "25": "  Los cantantes iban delante, los juglares les seguían,   entre las damas tocando con panderetas, ",
      "26": "  “Bendecid a Dios en las congregaciones,   el Señor en la asamblea de Israel”. ",
      "27": "  Allí está el pequeño Benjamín, su gobernante,   los príncipes de Judá, su consejo,   los príncipes de Zabulón y los príncipes de Neftalí. ",
      "28": "  Tu Dios ha ordenado tu fuerza.   Fortalece, Dios, lo que has hecho por nosotros. ",
      "29": "  Por tu templo en Jerusalén,   los reyes te traerán regalos. ",
      "30": "  Reprende al animal salvaje de las cañas,   la multitud de los toros con los becerros de los pueblos.   Pisotea las barras de plata.   Dispersa a las naciones que se deleitan en la guerra. ",
      "31": "  Los príncipes saldrán de Egipto.   Etiopía se apresurará a extender sus manos a Dios. ",
      "32": "  ¡Cantad a Dios, reinos de la tierra!   Canten alabanzas al Señor — Selah — ",
      "33": "  al que cabalga sobre el cielo de los cielos, que son de la antigüedad;   He aquí que él emite su voz, una voz poderosa. ",
      "34": "  ¡Asume la fuerza de Dios!   Su excelencia está sobre Israel,   su fuerza está en los cielos. ",
      "35": "  Eres impresionante, Dios, en tus santuarios.   El Dios de Israel da fuerza y poder a su pueblo.   Alabado sea Dios."
    },
    "69": {
      "1": "   Sálvame, Dios,   ¡porque las aguas me han llegado al cuello! ",
      "2": "  Me hundo en el fango profundo, donde no hay punto de apoyo.   He llegado a aguas profundas, donde las inundaciones me desbordan. ",
      "3": "  Estoy cansado de mi llanto.   Tengo la garganta seca.   Mis ojos fallan buscando a mi Dios. ",
      "4": "  Los que me odian sin causa son más que los cabellos de mi cabeza.   Los que quieren cortarme, siendo mis enemigos injustamente, son poderosos.   Tengo que restaurar lo que no me he llevado. ",
      "5": "  Dios, tú conoces mi insensatez.   Mis pecados no están ocultos para ti. ",
      "6": "  No permitas que se avergüencen por mí los que te esperan, Señor Yahvé de los Ejércitos.   No permitas que los que te buscan sean deshonrados por mí, Dios de Israel. ",
      "7": "  Porque por tu causa, he soportado el reproche.   La vergüenza ha cubierto mi cara. ",
      "8": "  Me he convertido en un extraño para mis hermanos,   un extranjero para los hijos de mi madre. ",
      "9": "  Porque el celo de tu casa me consume.   Los reproches de los que te reprochan han caído sobre mí. ",
      "10": "  Cuando lloré y ayuné,   que fue a mi reproche. ",
      "11": "  Cuando hice de la arpillera mi vestimenta,   Me convertí en un sinónimo para ellos. ",
      "12": "  Los que se sientan en la puerta hablan de mí.   Soy la canción de los borrachos. ",
      "13": "  Pero en cuanto a mí, mi oración es para ti, Yahvé, en un tiempo aceptable.   Dios, en la abundancia de tu amorosa bondad, respóndeme en la verdad de tu salvación. ",
      "14": "  Sácame del fango y no dejes que me hunda.   Libérame de los que me odian, y de las aguas profundas. ",
      "15": "  No dejes que las aguas de la inundación me arrollen,   ni dejar que las profundidades me traguen.   No dejes que la fosa me cierre la boca. ",
      "16": "  Respóndeme, Yahvé, porque tu bondad es buena.   Según la multitud de tus tiernas misericordias, vuélvete hacia mí. ",
      "17": "  No ocultes tu rostro a tu siervo,   porque estoy en apuros.   ¡Respóndeme rápido! ",
      "18": "  Acércate a mi alma y redímela.   Rescátame por mis enemigos. ",
      "19": "  Tú conoces mi oprobio, mi vergüenza y mi deshonra.   Mis adversarios están todos ante ti. ",
      "20": "  Los reproches han quebrantado mi corazón, y estoy lleno de tristeza.   Busqué a alguien que se apiadara, pero no había ninguno;   para los consoladores, pero no encontré ninguno. ",
      "21": "  También me dieron veneno para mi comida.   En mi sed, me dieron a beber vinagre. ",
      "22": "  Que su mesa ante ellos se convierta en una trampa.   Que se convierta en una retribución y una trampa. ",
      "23": "  Que se les oscurezcan los ojos para que no puedan ver.   Que sus espaldas estén continuamente dobladas. ",
      "24": "  Derrama tu indignación sobre ellos.   Deja que la ferocidad de tu ira los alcance. ",
      "25": "  Que su morada quede desolada.   Que nadie habite en sus tiendas. ",
      "26": "  Porque persiguen al que tú has herido.   Cuentan el dolor de aquellos a los que has herido. ",
      "27": "  Acusarles de un crimen tras otro.   No permitas que entren en tu justicia. ",
      "28": "  Que sean borrados del libro de la vida,   y no ser escrito con los justos. ",
      "29": "  Pero tengo dolor y angustia.   Que tu salvación, Dios, me proteja. ",
      "30": "  Alabaré el nombre de Dios con un canto,   y lo engrandecerá con acción de gracias. ",
      "31": "  Esto complacerá más a Yahvé que un buey,   o un toro que tiene cuernos y pezuñas. ",
      "32": "  Los humildes lo han visto y se alegran.   Tú que buscas a Dios, deja que tu corazón viva. ",
      "33": "  Porque Yahvé escucha a los necesitados,   y no desprecia a su pueblo cautivo. ",
      "34": "  Que el cielo y la tierra lo alaben;   ¡los mares, y todo lo que se mueve en ellos! ",
      "35": "  Porque Dios salvará a Sión y construirá las ciudades de Judá.   Se establecerán allí y serán los dueños. ",
      "36": "  También los hijos de sus siervos la heredarán.   Los que aman su nombre habitarán en él."
    },
    "70": {
      "1": "   Apresúrate, Dios, a liberarme.   Ven pronto a ayudarme, Yahvé. ",
      "2": "  Que se decepcionen y confundan los que buscan mi alma.   Que los que desean mi ruina sean devueltos en desgracia. ",
      "3": "  Que se conviertan a causa de su vergüenza   que dicen: “¡Ajá! ¡Ajá!” ",
      "4": "  Que todos los que te buscan se regocijen y se alegren en ti.   Que los que aman tu salvación digan continuamente,   “¡Que Dios sea exaltado!” ",
      "5": "  Pero soy pobre y estoy necesitado.   Ven a mí rápidamente, Dios.   Tú eres mi ayuda y mi libertador.   Yahvé, no te demores.  "
    },
    "71": {
      "1": "  En ti, Yahvé, me refugio.   Nunca dejes que me decepcione. ",
      "2": "  Líbrame con tu justicia y rescátame.   Vuelve tu oído hacia mí, y sálvame. ",
      "3": "  Sé para mí una roca de refugio a la que pueda acudir siempre.   Da la orden de salvarme,   porque tú eres mi roca y mi fortaleza. ",
      "4": "  Rescátame, Dios mío, de la mano de los malvados,   de la mano del hombre injusto y cruel. ",
      "5": "  Porque tú eres mi esperanza, Señor Yahvé,   mi confianza desde mi juventud. ",
      "6": "  He confiado en ti desde el vientre materno.   Tú eres el que me sacó del vientre de mi madre.   Siempre te alabaré. ",
      "7": "  Soy una maravilla para muchos,   pero tú eres mi fuerte refugio. ",
      "8": "  Mi boca se llenará de tus alabanzas,   con su honor durante todo el día. ",
      "9": "  No me rechaces en mi vejez.   No me abandones cuando me fallen las fuerzas. ",
      "10": "  Porque mis enemigos hablan de mí.   Los que velan por mi alma conspiran juntos, ",
      "11": "  diciendo: “Dios lo ha abandonado.   Perseguidlo y cogedlo, porque nadie lo rescatará”. ",
      "12": "  Dios, no te alejes de mí.   Dios mío, date prisa en ayudarme. ",
      "13": "  Que mis acusadores queden decepcionados y consumidos.   Que se cubran de ignominia y escarnio los que quieran perjudicarme. ",
      "14": "  Pero siempre tendré esperanza,   y se sumará a todos sus elogios. ",
      "15": "  Mi boca hablará de tu justicia,   y de tu salvación todo el día,   aunque no conozco su medida completa. ",
      "16": "  Vendré con los actos poderosos del Señor Yahvé.   Haré mención de tu justicia, incluso de la tuya solamente. ",
      "17": "  Dios, me has enseñado desde mi juventud.   Hasta ahora, he declarado tus obras maravillosas. ",
      "18": "  Sí, aunque sea viejo y canoso, Dios, no me abandones,   hasta que haya declarado tu fuerza a la siguiente generación,   tu poderío a todos los que han de venir. ",
      "19": "  Dios, tu justicia también llega a los cielos.   Has hecho grandes cosas.   Dios, ¿quién es como tú? ",
      "20": "  Tú, que nos has mostrado muchos y amargos problemas,   me dejarás vivir.   Nos harás salir de las profundidades de la tierra. ",
      "21": "  Aumenta mi honor   y reconfortarme de nuevo. ",
      "22": "  También te alabaré con el arpa por tu fidelidad, Dios mío.   Te canto alabanzas con la lira, Santo de Israel. ",
      "23": "  ¡Mis labios gritarán de alegría!   Mi alma, que has redimido, te canta alabanzas. ",
      "24": "  Mi lengua también hablará de tu justicia todo el día,   porque están decepcionados y confundidos,   que quieren hacerme daño."
    }
  }
};

