
	
export const bib_verses = {
  "2_thessalonians": {
    "2": {
      "1": "Ahora bien, hermanos, en cuanto a la venida de nuestro Señor Jesucristo y a nuestra reunión con él, os pedimos",
      "2": "que no os dejéis sacudir rápidamente el ánimo ni os turbéis, ni por espíritu, ni por palabra, ni por carta, como si fuera de nuestra parte, diciendo que el día de Cristo ya ha llegado.",
      "3": "Que nadie os engañe en modo alguno. Porque no será si no viene primero la rebelión, y se revela el hombre de pecado, el hijo de la destrucción.",
      "4": "Se opone y se levanta contra todo lo que se llama Dios o se adora, de modo que se sienta como Dios en el templo de Dios, erigiéndose en Dios.",
      "5": "¿No os acordáis de que, cuando aún estaba con vosotros, os dije estas cosas?",
      "6": "Ahora sabéis lo que le detiene, para que se manifieste a su tiempo.",
      "7": "Porque el misterio de la iniquidad ya funciona. Sólo que ahora hay uno que lo detiene, hasta que sea quitado del camino.",
      "8": "Entonces se manifestará el inicuo, a quien el Señor matará con el soplo de su boca y destruirá con la manifestación de su venida;",
      "9": "aquel cuya venida es según la obra de Satanás con todo poder y señales y prodigios mentirosos,",
      "10": "y con todo engaño de iniquidad para los que se están perdiendo, por no haber recibido el amor de la verdad, para que se salven.",
      "11": "A causa de esto, Dios les envía un poderoso engaño, para que crean la mentira,",
      "12": "a fin de que sean juzgados todos los que no creyeron la verdad, sino que se complacieron en la injusticia. ",
      "13": "Pero estamos obligados a dar siempre gracias a Dios por vosotros, hermanos amados por el Señor, porque Dios os eligió desde el principio para la salvación mediante la santificación del Espíritu y la creencia en la verdad,",
      "14": "a la que os llamó por medio de nuestra Buena Noticia, para obtener la gloria de nuestro Señor Jesucristo.",
      "15": "Así que, hermanos, manteneos firmes y conservad las tradiciones que os hemos enseñado, ya sea de palabra o por carta. ",
      "16": "Ahora bien, nuestro Señor Jesucristo en persona, y Dios, nuestro Padre, que nos amó y nos dio el consuelo eterno y la buena esperanza por medio de la gracia,",
      "17": "confortan vuestros corazones y os confirman en toda obra y palabra buena."
    },
    "3": {
      "1": "Por último, hermanos, rogad por nosotros, para que la palabra del Señor se extienda rápidamente y sea glorificada, así como con vosotros,",
      "2": "y para que seamos librados de los hombres irracionales y malvados; porque no todos tienen fe.",
      "3": "Pero fiel es el Señor, que os afirmará y os protegerá del maligno.",
      "4": "Tenemos confianza en el Señor respecto a vosotros, en que hacéis y haréis lo que os mandamos.",
      "5": "Que el Señor dirija vuestros corazones al amor de Dios y a la perseverancia de Cristo. ",
      "6": "Ahora os ordenamos, hermanos, en nombre de nuestro Señor Jesucristo, que os apartéis de todo hermano que ande en rebeldía y no según la tradición que recibieron de nosotros.",
      "7": "Porque sabéis cómo debéis imitarnos. Porque no nos comportamos con rebeldía entre vosotros,",
      "8": "ni comimos el pan de la mano de nadie sin pagarlo, sino que con trabajo y fatiga trabajamos de noche y de día, para no ser una carga para ninguno de vosotros.",
      "9": "Esto no fue porque no tuviéramos derecho, sino para daros ejemplo, para que nos imitarais.",
      "10": "Pues incluso cuando estábamos con vosotros, os ordenamos esto: “Si alguno no está dispuesto a trabajar, que no coma”.",
      "11": "Porque nos enteramos de que hay algunos que andan entre ustedes con rebeldía, que no trabajan en absoluto, sino que son unos entrometidos.",
      "12": "A los que son así, les ordenamos y exhortamos en el Señor Jesucristo, que trabajen con tranquilidad y coman su propio pan. ",
      "13": "Pero vosotros, hermanos, no os canséis de hacer lo que es justo.",
      "14": "Si alguno no obedece a nuestra palabra en esta carta, anoten a ese hombre y no tengan compañía con él, para que se avergüence.",
      "15": "No lo tengáis por enemigo, sino amonestadlo como a un hermano. ",
      "16": "Que el mismo Señor de la paz os dé la paz en todo momento y en todos los sentidos. El Señor esté con todos vosotros. ",
      "17": "Yo, Pablo, escribo este saludo con mi propia mano, que es el signo de toda carta. Así es como escribo.",
      "18": "La gracia de nuestro Señor Jesucristo esté con todos vosotros. Amén."
    }
  },
  "1_timothy": {
    "1": {
      "1": "Pablo, apóstol de Jesucristo según el mandato de Dios nuestro Salvador y del Señor Jesucristo nuestra esperanza,",
      "2": "a Timoteo, mi verdadero hijo en la fe: Gracia, misericordia y paz de parte de Dios nuestro Padre y de Cristo Jesús nuestro Señor. ",
      "3": "Como os insté cuando iba a Macedonia, quedaos en Éfeso para que ordenéis a algunos hombres que no enseñen una doctrina diferente,",
      "4": "y que no presten atención a mitos y genealogías interminables, que provocan disputas en lugar de la administración de Dios, que está en la fe.",
      "5": "Pero el objetivo de este mandamiento es el amor de corazón puro, la buena conciencia y la fe sincera,",
      "6": "de lo cual algunos, habiendo errado el camino, se han desviado hacia la palabrería vana,",
      "7": "deseando ser maestros de la ley, aunque no entienden ni lo que dicen ni lo que afirman con rotundidad. ",
      "8": "Pero sabemos que la ley es buena si una persona la usa legalmente,",
      "9": "como sabiendo esto, esa ley no está hecha para una persona justa, sino para los inicuos e insubordinados, para los impíos y pecadores, para los impíos y profanos, para los asesinos de padres y asesinos de madres para los homicidas,",
      "10": "para los inmorales sexuales, para los homosexuales, para los traficantes de esclavos, para los mentirosos, para los perjuros, y para cualquier otra cosa contraria a la sana doctrina,",
      "11": "según la Buena Noticia de la gloria de la bendito Dios, que fue encomendado a mi confianza. ",
      "12": "Doy gracias al que me capacitó, Cristo Jesús, nuestro Señor, porque me tuvo por fiel, nombrándome para el servicio,",
      "13": "aunque solía ser blasfemo, perseguidor e insolente. Sin embargo, obtuve misericordia porque lo hice ignorantemente en la incredulidad.",
      "14": "La gracia de nuestro Señor abundó sobremanera con la fe y el amor que hay en Cristo Jesús.",
      "15": "El dicho es fiel y digno de toda aceptación: que Cristo Jesús vino al mundo para salvar a los pecadores, de los cuales yo soy el primero.",
      "16": "Sin embargo, por esta causa obtuve misericordia, para que en mí primero, Jesucristo desplegara toda su paciencia para ejemplo de los que iban a creer en él para la vida eterna.",
      "17": "Ahora bien, al Rey eterno, inmortal, invisible, a Dios que es el único sabio, sea el honor y la gloria por los siglos de los siglos. Amén. ",
      "18": "Te encomiendo esta instrucción, hijo mío Timoteo, según las profecías que te fueron dadas antes, para que por medio de ellas libres la buena batalla,",
      "19": "conservando la fe y la buena conciencia, de la que algunos han naufragado respecto a la fe,",
      "20": "de los cuales son Himeneo y Alejandro, a quienes entregué a Satanás para que les enseñara a no blasfemar."
    },
    "2": {
      "1": "Exhorto, pues, ante todo, a que se hagan peticiones, oraciones, súplicas y acciones de gracias por todos los hombres,",
      "2": "por los reyes y por todos los que están en las alturas, para que llevemos una vida tranquila y sosegada en toda piedad y reverencia.",
      "3": "Porque esto es bueno y agradable a los ojos de Dios, nuestro Salvador,",
      "4": "que desea que todos los hombres se salven y lleguen al pleno conocimiento de la verdad.",
      "5": "Porque hay un solo Dios y un solo mediador entre Dios y los hombres, el hombre Cristo Jesús,",
      "6": "que se entregó a sí mismo en rescate por todos, el testimonio a su debido tiempo,",
      "7": "para el cual fui designado predicador y apóstol — digo la verdad en Cristo, no miento —, maestro de los gentiles en la fe y la verdad. ",
      "8": "Deseo, pues, que los hombres oren en todo lugar, levantando las manos santas, sin ira ni duda.",
      "9": "De la misma manera, que también las mujeres se adornen con ropa decente, con modestia y propiedad, no con cabellos trenzados, oro, perlas o ropa costosa,",
      "10": "sino con buenas obras, lo cual es apropiado para las mujeres que profesan la piedad.",
      "11": "Que la mujer aprenda en tranquilidad con plena sumisión.",
      "12": "Pero no permito que la mujer enseñe, ni que ejerza autoridad sobre el hombre, sino que esté en quietud.",
      "13": "Porque primero fue formado Adán y luego Eva.",
      "14": "Adán no fue engañado, pero la mujer, siendo engañada, ha caído en la desobediencia;",
      "15": "pero se salvará por medio de sus hijos, si continúan en la fe, el amor y la santidad con sobriedad."
    },
    "3": {
      "1": "Este es un dicho fiel: el que busca ser supervisor desea una buena obra.",
      "2": "Por lo tanto, el supervisor debe ser irreprochable, marido de una sola mujer, moderado, sensato, modesto, hospitalario, bueno para enseñar;",
      "3": "no bebedor, no violento, no codicioso de dinero, sino amable, no pendenciero, no avaro;",
      "4": "que gobierne bien su propia casa, teniendo a los hijos en sujeción con toda reverencia;",
      "5": "(porque ¿cómo podría cuidar de la asamblea de Dios alguien que no sabe gobernar su propia casa?)",
      "6": "no un recién convertido, no sea que envaneciéndose caiga en la misma condenación que el diablo.",
      "7": "Además, debe tener un buen testimonio de los que están fuera, para no caer en el oprobio y en la trampa del diablo. ",
      "8": "Los siervos, de la misma manera, deben ser reverentes, no de doble lengua, no adictos a mucho vino, no codiciosos de dinero,",
      "9": "manteniendo el misterio de la fe en una conciencia pura.",
      "10": "Que también sean probados primero; entonces que sirvan si son irreprochables.",
      "11": "Sus esposas, del mismo modo, deben ser reverentes, no calumniadoras, templadas y fieles en todo.",
      "12": "Que los siervos sean maridos de una sola mujer, gobernando bien a sus hijos y a su propia casa.",
      "13": "Porque los que han servido bien ganan para sí una buena posición y una gran audacia en la fe que es en Cristo Jesús. ",
      "14": "Estas cosas os escribo, esperando ir pronto a vosotros,",
      "15": "pero si espero mucho, para que sepáis cómo deben comportarse los hombres en la casa de Dios, que es la asamblea del Dios vivo, columna y fundamento de la verdad.",
      "16": "Sin embargo, el misterio de la piedad es grande:   Dios se reveló en la carne,   justificado en el espíritu,   visto por los ángeles,   predicado entre las naciones,   creía en el mundo,   y recibido en la gloria."
    },
    "4": {
      "1": "Pero el Espíritu dice expresamente que en los últimos tiempos algunos se apartarán de la fe, prestando atención a los espíritus seductores y a las doctrinas de los demonios,",
      "2": "mediante la hipocresía de hombres que hablan mentiras, marcadas en su propia conciencia como con un hierro candente,",
      "3": "prohibiendo el matrimonio y mandando abstenerse de los alimentos que Dios creó para ser recibidos con acción de gracias por los que creen y conocen la verdad.",
      "4": "Porque toda criatura de Dios es buena, y nada debe rechazarse si se recibe con acción de gracias.",
      "5": "Pues se santifica mediante la palabra de Dios y la oración. ",
      "6": "Si instruyes a los hermanos en estas cosas, serás un buen servidor de Cristo Jesús, alimentado con las palabras de la fe y de la buena doctrina que has seguido.",
      "7": "Pero rechaza las fábulas profanas y de viejas. Ejercítate en la piedad.",
      "8": "Porque el ejercicio corporal tiene algún valor, pero la piedad tiene valor en todas las cosas, teniendo la promesa de la vida actual y de la venidera.",
      "9": "Esta frase es fiel y digna de toda aceptación.",
      "10": "Porque para ello nos esforzamos y sufrimos reproches, porque hemos puesto nuestra confianza en el Dios vivo, que es el Salvador de todos los hombres, especialmente de los que creen.",
      "11": "Ordena y enseña estas cosas. ",
      "12": "Que nadie desprecie tu juventud, sino que seas un ejemplo para los creyentes, en palabra, en tu forma de vida, en amor, en espíritu, en fe y en pureza.",
      "13": "Hasta que yo venga, prestad atención a la lectura, a la exhortación y a la enseñanza.",
      "14": "No descuidéis el don que hay en vosotros, que os fue dado por profecía con la imposición de las manos de los ancianos.",
      "15": "Sé diligente en estas cosas. Dedícate por completo a ellas, para que tu progreso sea revelado a todos.",
      "16": "Presta atención a ti mismo y a tu enseñanza. Continúa en estas cosas, porque haciendo esto te salvarás a ti mismo y a los que te escuchan."
    },
    "5": {
      "1": "No reprendas al anciano, sino exhórtale como a un padre; a los jóvenes, como a hermanos;",
      "2": "a las mujeres mayores, como a madres; a las jóvenes, como a hermanas, con toda pureza. ",
      "3": "Honra a las viudas que son realmente viudas.",
      "4": "Pero si alguna viuda tiene hijos o nietos, que aprenda primero a mostrar piedad hacia su propia familia y a retribuir a sus padres, porque esto es aceptable a los ojos de Dios.",
      "5": "La que es realmente viuda y está desolada, tiene su esperanza puesta en Dios y continúa con sus peticiones y oraciones de noche y de día.",
      "6": "Pero la que se entrega al placer está muerta mientras vive.",
      "7": "Ordena también estas cosas, para que sean sin reproche.",
      "8": "Pero si alguno no provee para los suyos, y especialmente para su casa, ha negado la fe y es peor que un incrédulo. ",
      "9": "Que no se inscriba ninguna viuda menor de sesenta años, que haya sido esposa de un solo hombre,",
      "10": "que haya sido aprobada por sus buenas obras, si ha criado hijos, si ha sido hospitalaria con los extranjeros, si ha lavado los pies de los santos, si ha aliviado a los afligidos y si ha seguido diligentemente toda buena obra. ",
      "11": "Pero rechaza a las viudas más jóvenes, porque cuando se han vuelto indeseables contra Cristo, desean casarse,",
      "12": "teniendo la condena, porque han rechazado su primera promesa.",
      "13": "Además, también aprenden a ser ociosas, yendo de casa en casa. No sólo ociosos, sino también chismosos y entrometidos, diciendo cosas que no deben.",
      "14": "Deseo, pues, que las viudas más jóvenes se casen, tengan hijos, gobiernen la casa y no den ocasión al adversario para que las insulte.",
      "15": "Porque ya algunos se han apartado en pos de Satanás.",
      "16": "Si algún hombre o mujer creyente tiene viudas, que las socorra, y que no se agobie la asamblea, para que socorra a las que sí son viudas. ",
      "17": "Los ancianos que gobiernan bien sean tenidos por dignos de doble honor, especialmente los que trabajan en la palabra y en la enseñanza.",
      "18": "Porque la Escritura dice: “No pondrás bozal al buey cuando triture el grano”. Y: “ El obrero es digno de su salario”.   ",
      "19": "No recibas una acusación contra un anciano si no es por la palabra de dos o tres testigos.",
      "20": "A los que pecan, repréndelos a la vista de todos, para que también los demás tengan temor.",
      "21": "Os ordeno, en presencia de Dios, del Señor Jesucristo y de los ángeles elegidos, que observéis estas cosas sin prejuicios, sin hacer nada por parcialidad.",
      "22": "No pongas las manos apresuradamente sobre nadie. No seas partícipe de los pecados de los demás. Mantente puro. ",
      "23": "Ya no bebas sólo agua, sino usa un poco de vino por el bien de tu estómago y tus frecuentes enfermedades. ",
      "24": "Algunos pecados de los hombres son evidentes y los preceden al juicio, y otros también los siguen después.",
      "25": "Así también hay obras buenas que son evidentes, y las que no lo son no pueden ocultarse."
    },
    "6": {
      "1": "Todos los que son siervos bajo el yugo consideren a sus propios amos dignos de toda honra, para que el nombre de Dios y la doctrina no sean blasfemados.",
      "2": "Los que tienen amos creyentes, que no los desprecien por ser hermanos, sino que los sirvan, porque los que participan del beneficio son creyentes y amados. Enseña y exhorta estas cosas. ",
      "3": "Si alguno enseña una doctrina diferente y no se aviene a las sanas palabras, a las palabras de nuestro Señor Jesucristo y a la doctrina que es conforme a la piedad,",
      "4": "es un engreído, que no sabe nada, sino que está obsesionado con discusiones, disputas y batallas de palabras, de las que surgen envidias, contiendas, injurias, malas sospechas,",
      "5": "roces constantes de personas de mente corrompida y destituidas de la verdad, que suponen que la piedad es un medio de ganancia. Apártate de los tales. ",
      "6": "Pero la piedad con satisfacción es una gran ganancia.",
      "7": "Porque nada hemos traído al mundo, y ciertamente nada podemos llevar a cabo.",
      "8": "Pero teniendo alimento y vestido, nos contentaremos con eso.",
      "9": "Pero los que se empeñan en ser ricos caen en una tentación, en un lazo y en muchas codicias necias y perjudiciales, que ahogan a los hombres en la ruina y la destrucción.",
      "10": "Porque el amor al dinero es raíz de toda clase de males. Algunos se han desviado de la fe por su avaricia, y se han atravesado con muchos dolores. ",
      "11": "Pero tú, hombre de Dios, huye de estas cosas y sigue la justicia, la piedad, la fe, el amor, la perseverancia y la mansedumbre.",
      "12": "Pelea la buena batalla de la fe. Aférrate a la vida eterna a la que has sido llamado, y has confesado la buena confesión a la vista de muchos testigos.",
      "13": "Os ordeno ante Dios, que da vida a todas las cosas, y ante Cristo Jesús, que ante Poncio Pilato dio testimonio de la buena confesión,",
      "14": "que guardéis el mandamiento sin mancha, irreprochables hasta la aparición de nuestro Señor Jesucristo,",
      "15": "que en el momento oportuno mostrará, que es el bendito y único Gobernante, el Rey de reyes y Señor de señores.",
      "16": "Sólo él tiene la inmortalidad, que habita en una luz inaccesible, a quien nadie ha visto ni puede ver, a quien corresponde el honor y el poder eterno. Amén. ",
      "17": "Pide a los que son ricos en este tiempo que no sean arrogantes, ni tengan su esperanza puesta en la incertidumbre de las riquezas, sino en el Dios vivo, que nos provee ricamente de todo para que lo disfrutemos;",
      "18": "que hagan el bien, que sean ricos en buenas obras, que estén dispuestos a repartir, deseosos de compartir;",
      "19": "acumulando para sí un buen fundamento para el tiempo venidero, para que puedan echar mano de la vida eterna. ",
      "20": "Timoteo, guarda lo que se te ha encomendado, apartándote de la palabrería vacía y de las oposiciones de lo que se llama falsamente conocimiento,",
      "21": "que algunos profesan, y así se han desviado de la fe. Que la gracia sea contigo. Amén."
    }
  },
  "2_timothy": {
    "1": {
      "1": "Pablo, apóstol de Jesucristo por la voluntad de Dios, según la promesa de la vida que es en Cristo Jesús,",
      "2": "a Timoteo, mi hijo amado: Gracia, misericordia y paz, de parte de Dios Padre y de Cristo Jesús, nuestro Señor. ",
      "3": "Doy gracias a Dios, a quien sirvo como mis antepasados, con una conciencia pura. Cuán incesante es mi recuerdo de ti en mis súplicas, noche y día",
      "4": "anhelando verte, recordando tus lágrimas, para llenarme de alegría;",
      "5": "habiendo recordado la fe sincera que hay en ti, que vivió primero en tu abuela Loida y en tu madre Eunice y, estoy persuadido, también en ti. ",
      "6": "Por eso os recuerdo que debéis avivar el don de Dios que hay en vosotros por la imposición de mis manos.",
      "7": "Porque Dios no nos dio un espíritu de temor, sino de poder, amor y dominio propio.",
      "8": "Por tanto, no os avergoncéis del testimonio de nuestro Señor, ni de mí, su prisionero, sino que soportad las penalidades por la Buena Nueva según el poder de Dios,",
      "9": "que nos salvó y nos llamó con una vocación santa, no según nuestras obras, sino según su propio propósito y gracia, que nos fue dada en Cristo Jesús antes de los tiempos eternos,",
      "10": "pero que ahora se ha revelado por la aparición de nuestro Salvador, Cristo Jesús, que abolió la muerte y sacó a la luz la vida y la inmortalidad por medio de la Buena Nueva.",
      "11": "Para esto fui nombrado predicador, apóstol y maestro de los gentiles.",
      "12": "Por esta causa también sufro estas cosas. Sin embargo, no me avergüenzo, porque conozco a aquel en quien he creído, y estoy convencido de que es capaz de guardar lo que le he confiado para ese día. ",
      "13": "Mantened el modelo de las sanas palabras que habéis oído de mí, en la fe y el amor que hay en Cristo Jesús.",
      "14": "Ese bien que se os ha encomendado, guardadlo por medio del Espíritu Santo que mora en nosotros. ",
      "15": "Esto sabes, que todos los que están en Asia se apartaron de mí, de los cuales son Filgelio y Hermógenes.",
      "16": "Que el Señor conceda misericordia a la casa de Onesíforo, pues muchas veces me refrescó y no se avergonzó de mi cadena,",
      "17": "sino que, estando en Roma, me buscó diligentemente y me encontró",
      "18": "(el Señor le conceda encontrar la misericordia del Señor en aquel día); y en cuántas cosas sirvió en Éfeso, lo sabéis muy bien."
    },
    "2": {
      "1": "Tú, pues, hijo mío, fortalécete en la gracia que es en Cristo Jesús.",
      "2": "Lo que has oído de mí entre muchos testigos, encomiéndalo a hombres fieles que puedan enseñar también a otros.",
      "3": "Por lo tanto, debes soportar las dificultades como un buen soldado de Cristo Jesús.",
      "4": "Ningún soldado en servicio se enreda en los asuntos de la vida, para agradar al que lo alistó como soldado.",
      "5": "Asimismo, si alguien compite en atletismo, no es coronado si no ha competido según las reglas.",
      "6": "El agricultor que trabaja debe ser el primero en recibir una parte de la cosecha.",
      "7": "Considera lo que te digo, y que el Señor te dé entendimiento en todas las cosas. ",
      "8": "Acuérdate de Jesucristo, resucitado de entre los muertos, de la estirpe de David, según mi Buena Noticia,",
      "9": "en la que sufro penurias hasta el punto de ser encadenado como un criminal. Pero la palabra de Dios no está encadenada.",
      "10": "Por eso lo soporto todo por los elegidos, para que también ellos obtengan la salvación que hay en Cristo Jesús con gloria eterna.",
      "11": "Este dicho es digno de confianza:   “Porque si morimos con él,   también viviremos con él. ",
      "12": "  Si soportamos,   también reinaremos con él.   Si lo negamos,   también nos negará. ",
      "13": "  Si somos infieles,   permanece fiel;   porque no puede negarse a sí mismo”. ",
      "14": "Recuérdales estas cosas, encargándoles ante el Señor que no discutan sobre las palabras sin provecho, para subvertir a los que escuchan. ",
      "15": "Procura presentarte a Dios aprobado, como obrero que no tiene de qué avergonzarse, manejando debidamente la palabra de verdad.",
      "16": "Pero evita la palabrería vacía, porque irá más allá en la impiedad,",
      "17": "y esas palabras consumirán como gangrena, de los cuales son Himeneo y Fileto:",
      "18": "hombres que han errado respecto a la verdad, diciendo que la resurrección ya pasó, y derribando la fe de algunos.",
      "19": "Sin embargo, el firme fundamento de Dios se mantiene, teniendo este sello: “El Señor conoce a los que son suyos”, y “Todo el que nombre el nombre del Señor se aparte de la injusticia”. ",
      "20": "En una casa grande no sólo hay vasos de oro y de plata, sino también de madera y de barro. Unos son para la honra y otros para la deshonra.",
      "21": "Por lo tanto, si alguno se purifica de éstos, será un vaso para la honra, santificado y apto para el uso del amo, preparado para toda buena obra. ",
      "22": "Huyan de los deseos juveniles, sino persigan la justicia, la fe, el amor y la paz con los que invocan al Señor de corazón puro.",
      "23": "Pero rechazad las preguntas necias e ignorantes, sabiendo que generan disputas.",
      "24": "El siervo del Señor no debe reñir, sino ser amable con todos, capaz de enseñar, paciente,",
      "25": "corrigiendo con mansedumbre a los que se oponen. Tal vez Dios les dé el arrepentimiento que lleve al pleno conocimiento de la verdad,",
      "26": "y se recuperen de la trampa del diablo, habiendo sido cautivos de él para hacer su voluntad."
    },
    "3": {
      "1": "Pero sabed esto: que en los últimos días vendrán tiempos difíciles.",
      "2": "Porque los hombres serán amantes de sí mismos, amantes del dinero, jactanciosos, arrogantes, blasfemos, desobedientes a los padres, ingratos, impíos,",
      "3": "sin afecto natural, implacables, calumniadores, sin autocontrol, feroces, no amantes del bien,",
      "4": "traidores, testarudos, engreídos, amantes de los placeres más que de Dios,",
      "5": "teniendo una forma de piedad pero habiendo negado su poder. Apartaos también de éstos.",
      "6": "Porque algunos de ellos son personas que se introducen en las casas y llevan cautivas a mujeres crédulas cargadas de pecados, llevadas por diversas concupiscencias,",
      "7": "siempre aprendiendo y nunca pudiendo llegar al conocimiento de la verdad.",
      "8": "Así como Janés y Jambres se opusieron a Moisés, también éstos se oponen a la verdad, hombres de mente corrompida, que en lo que respecta a la fe son rechazados.",
      "9": "Pero no seguirán adelante. Porque su insensatez será evidente para todos los hombres, como también lo fue la de ellos. ",
      "10": "Pero ustedes siguieron mi enseñanza, mi conducta, mi propósito, mi fe, mi paciencia, mi amor, mi constancia,",
      "11": "mis persecuciones y mis sufrimientos, que me sucedieron en Antioquía, Iconio y Listra. Soporté esas persecuciones. El Señor me libró de todas ellas.",
      "12": "Sí, y todos los que desean vivir piadosamente en Cristo Jesús sufrirán persecución.",
      "13": "Pero los hombres malvados y los impostores irán de mal en peor, engañando y siendo engañados.",
      "14": "Pero vosotros permanecéis en lo que habéis aprendido y os habéis asegurado, sabiendo de quién lo habéis aprendido.",
      "15": "Desde la infancia, habéis conocido las Sagradas Escrituras, que pueden haceros sabios para la salvación mediante la fe que es en Cristo Jesús.",
      "16": "Toda la Escritura es inspirada por Dios y es útil para enseñar, para reprender, para corregir y para instruir en la justicia,",
      "17": "a fin de que cada persona que pertenece a Dios sea completa, completamente equipada para toda buena obra."
    },
    "4": {
      "1": "Os ordeno, pues, delante de Dios y del Señor Jesucristo, que juzgará a los vivos y a los muertos en su aparición y en su Reino:",
      "2": "predicad la palabra; urgid a tiempo y a destiempo; reprended, reprended y exhortad con toda paciencia y enseñanza.",
      "3": "Porque vendrá el tiempo en que no escucharán la sana doctrina, sino que, teniendo comezón de oír, se amontonarán maestros según sus propias concupiscencias,",
      "4": "y apartarán sus oídos de la verdad y se volverán a las fábulas.",
      "5": "Pero tú sé sobrio en todo, sufre penalidades, haz la obra de un evangelista y cumple tu ministerio. ",
      "6": "Porque ya me han ofrecido, y ha llegado el momento de mi partida.",
      "7": "He librado el buen combate. He terminado el curso. He mantenido la fe.",
      "8": "Desde ahora me está reservada la corona de la justicia, que el Señor, el juez justo, me dará en aquel día; y no sólo a mí, sino también a todos los que han amado su aparición. ",
      "9": "Procura venir pronto a verme,",
      "10": "porque Demas me ha dejado, amando este mundo presente, y se ha ido a Tesalónica; Crescens, a Galacia; y Tito, a Dalmacia.",
      "11": "Sólo Lucas está conmigo. Toma a Marcos y tráelo contigo, porque me es útil para el servicio.",
      "12": "Pero he enviado a Tíquico a Éfeso.",
      "13": "Trae cuando vengas el manto que dejé en Troas con Carpo, y los libros, especialmente los pergaminos.",
      "14": "Alejandro el calderero me hizo mucho mal. El Señor le pagará según sus actos.",
      "15": "Tengan cuidado con él, porque se opuso mucho a nuestras palabras. ",
      "16": "En mi primera defensa, nadie vino a ayudarme, sino que todos me abandonaron. Que no se les eche en cara.",
      "17": "Pero el Señor se mantuvo a mi lado y me fortaleció, para que por medio de mí se proclamara plenamente el mensaje y lo escucharan todos los gentiles. Así fui librado de la boca del león.",
      "18": "Y el Señor me librará de toda obra mala y me preservará para su Reino celestial. A él sea la gloria por los siglos de los siglos. Amén. ",
      "19": "Saludad a Prisca y a Aquila, y a la casa de Onesíforo.",
      "20": "Erasto se quedó en Corinto, pero dejé a Trófimo en Mileto enfermo.",
      "21": "Procura venir antes del invierno. Te saluda Eubulo, así como Pudente, Lino, Claudia y todos los hermanos. ",
      "22": "El Señor Jesucristo esté con tu espíritu. La gracia sea contigo. Amén."
    }
  },
  "titus": {
    "1": {
      "1": "Pablo, siervo de Dios y apóstol de Jesucristo, según la fe de los elegidos de Dios y el conocimiento de la verdad que es conforme a la piedad,",
      "2": "con la esperanza de la vida eterna, que Dios, que no puede mentir, prometió antes de los tiempos;",
      "3": "pero que a su tiempo reveló su palabra en el mensaje que se me confió según el mandamiento de Dios nuestro Salvador,",
      "4": "a Tito, mi verdadero hijo según una fe común: Gracia, misericordia y paz de parte de Dios Padre y del Señor Jesucristo, nuestro Salvador. ",
      "5": "Os dejé en Creta por esta razón, para que pusierais en orden lo que faltaba y nombrarais ancianos en cada ciudad, tal como osordené:",
      "6": "si alguno es irreprochable, marido de una sola mujer, que tenga hijos creyentes, que no esté acusado de conducta desordenada o indisciplinada.",
      "7": "Porque el supervisor debe ser irreprochable, como administrador de Dios, no complaciente, no fácilmente enojado, no dado al vino, no violento, no codicioso de ganancias deshonestas;",
      "8": "sino dado a la hospitalidad, amante del bien, de mente sobria, justo, santo, autocontrolado,",
      "9": "que mantenga la palabra fiel que es según la enseñanza, para que pueda exhortar en la sana doctrina, y convencer a los que lo contradicen. ",
      "10": "Porque también hay muchos hombres revoltosos, habladores vanos y engañadores, especialmente los de la circuncisión,",
      "11": "a quienes hay que tapar la boca; hombres que trastornan casas enteras, enseñando cosas que no deben, por un afán de lucro deshonesto.",
      "12": "Uno de ellos, profeta de los suyos, dijo: “Los cretenses son siempre mentirosos, malas bestias y glotones ociosos.”",
      "13": "Este testimonio es verdadero. Por eso, repréndelos duramente, para que sean sanos en la fe,",
      "14": "sin prestar atención a las fábulas judías y a los mandatos de los hombres que se apartan de la verdad.",
      "15": "Para los puros, todas las cosas son puras, pero para los contaminados e incrédulos, nada es puro, sino que tanto su mente como su conciencia están contaminadas.",
      "16": "Profesan que conocen a Dios, pero con sus obras lo niegan, siendo abominables, desobedientes e incapaces de toda buena obra."
    },
    "2": {
      "1": "sino que digan lo que conviene a la sana doctrina,",
      "2": "que los hombres mayores sean templados, sensatos, de mente sobria, sanos en la fe, en el amor y en la perseverancia,",
      "3": "y que las mujeres mayores sean igualmente reverentes en su conducta, no calumniadoras ni esclavas del mucho vino",
      "4": "que instruyan a las mujeres jóvenes en el amor a sus maridos, en el amor a sus hijos,",
      "5": "que sean sobrias, castas, trabajadoras en el hogar, bondadosas, sometidas a sus propios maridos, para que la palabra de Dios no sea blasfemada. ",
      "6": "Asimismo, exhorta a los más jóvenes a ser sobrios.",
      "7": "En todo, muéstrate como ejemplo de buenas obras. En tu enseñanza, muestra integridad, seriedad, incorruptibilidad,",
      "8": "y solidez de palabra que no pueda ser condenada, para que el que se oponga a ti se avergüence, sin tener nada malo que decir de nosotros. ",
      "9": "Exhorta a los siervos a que estén sujetos a sus propios amos y sean agradables en todo, sin contradecir,",
      "10": "sin robar, sino mostrando toda buena fidelidad, para que adornen en todo la doctrina de Dios, nuestro Salvador.",
      "11": "Porque la gracia de Dios se ha manifestado, trayendo la salvación a todos los hombres,",
      "12": "instruyéndonos para que, renunciando a la impiedad y a los deseos mundanos, vivamos en este tiempo sobria, justa y piadosamente;",
      "13": "aguardando la esperanza bienaventurada y la manifestación de la gloria de nuestro gran Dios y Salvador Jesucristo,",
      "14": "que se entregó a sí mismo por nosotros, para redimirnos de toda iniquidad y purificar para sí un pueblo que le pertenezca, celoso de buenas obras. ",
      "15": "Decid estas cosas y exhortad y reprended con toda autoridad. Que nadie os desprecie."
    },
    "3": {
      "1": "Recuérdales que se sometan a los gobernantes y a las autoridades, que sean obedientes, que estén dispuestos a toda buena obra,",
      "2": "que no hablen mal de nadie, que no sean contenciosos, que sean amables, mostrando toda la humildad hacia todos los hombres.",
      "3": "Porque también nosotros fuimos en otro tiempo insensatos, desobedientes, engañados, sirviendo a diversos deseos y placeres, viviendo en la malicia y la envidia, odiosos y odiándose unos a otros.",
      "4": "Pero cuando se manifestó la bondad de Dios, nuestro Salvador, y su amor hacia los hombres,",
      "5": "no por obras de justicia que nosotros mismos hubiéramos hecho, sino según su misericordia, nos salvó mediante el lavado de la regeneración y la renovación por el Espíritu Santo,",
      "6": "que derramó sobre nosotros abundantemente por medio de Jesucristo, nuestro Salvador;",
      "7": "para que, justificados por su gracia, fuésemos hechos herederos según la esperanza de la vida eterna.",
      "8": "Esta afirmación es fiel, y sobre estas cosas deseo que insistáis con confianza, para que los que han creído a Dios se preocupen por mantener las buenas obras. Estas cosas son buenas y provechosas para los hombres;",
      "9": "pero evitad las discusiones necias, las genealogías, las contiendas y las disputas sobre la ley, porque son inútiles y vanas.",
      "10": "Evitad a un hombre faccioso después de una primera y segunda amonestación,",
      "11": "sabiendo que el tal es pervertido y pecador, estando autocondenado. ",
      "12": "Cuando te envíe a Artemas, o a Tíquico, procura venir conmigo a Nicópolis, pues he decidido invernar allí.",
      "13": "Enviad prontamente al abogado Zenas y a Apolos, para que no les falte nada.",
      "14": "Que nuestro pueblo aprenda también a mantener las buenas obras para satisfacer las necesidades necesarias, para que no sea infructuoso. ",
      "15": "Os saludan todos los que están conmigo. Saluden a los que nos aman en la fe. Que la gracia esté con todos vosotros. Amén."
    }
  },
  "philemon": {
    "1": {
      "1": "Pablo, prisionero de Cristo Jesús, y Timoteo, nuestro hermano, a Filemón, nuestro amado colaborador,",
      "2": "a la amada Apia, a Arquipo, nuestro compañero de armas, y a la asamblea en vuestra casa:",
      "3": "Gracia a vosotros y paz de parte de Dios nuestro Padre y del Señor Jesucristo. ",
      "4": "Doy gracias a mi Dios siempre, haciendo mención de ti en mis oraciones,",
      "5": "oyendo hablar de tu amor y de la fe que tienes para con el Señor Jesús y para con todos los santos,",
      "6": "para que la comunión de tu fe se haga efectiva en el conocimiento de todo lo bueno que hay en nosotros en Cristo Jesús.",
      "7": "Porque tenemos mucha alegría y consuelo en tu amor, porque los corazones de los santos han sido refrescados por medio de ti, hermano. ",
      "8": "Por lo tanto, aunque tengo toda la audacia en Cristo para ordenaros lo que conviene,",
      "9": "sin embargo, por amor, más bien apelo a vosotros, siendo uno como Pablo, anciano, pero también prisionero de Jesucristo.",
      "10": "Apelo a vosotros por mi hijo Onésimo, del que me he convertido en padre en mis cadenas,",
      "11": "que antes os era inútil, pero que ahora nos es útil a vosotros y a mí.",
      "12": "Te lo devuelvo. Recibid, pues, a éste, es decir, a mi propio corazón,",
      "13": "a quien deseaba retener conmigo, para que en vuestro nombre me sirviera en mis cadenas para la Buena Nueva.",
      "14": "Pero no quise hacer nada sin tu consentimiento, para que tu bondad no fuera como por necesidad, sino por libre voluntad.",
      "15": "Por lo tanto, tal vez se separó de ti por un tiempo para que lo tuvieras para siempre,",
      "16": "no ya como un esclavo, sino más que un esclavo, un hermano amado, especialmente para mí, pero cuánto más para ti, tanto en la carne como en el Señor. ",
      "17": "Si, pues, me consideras un socio, recíbelo como a mí.",
      "18": "Pero si os ha perjudicado o os debe algo, ponedlo en mi cuenta.",
      "19": "Yo, Pablo, escribo esto con mi propia mano: Te lo devolveré (sin mencionar que me debes incluso a ti mismo además).",
      "20": "Sí, hermano, permíteme que me alegre de ti en el Señor. Refresca mi corazón en el Señor. ",
      "21": "Confiando en tu obediencia, te escribo, sabiendo que harás incluso más allá de lo que te digo. ",
      "22": "Prepara también una habitación de huéspedes para mí, pues espero que, gracias a tus oraciones, se me restituya. ",
      "23": "Os saluda Epafras, mi compañero de prisión en Cristo Jesús,",
      "24": "así como Marcos, Aristarco, Demas y Lucas, mis compañeros de trabajo. ",
      "25": "La gracia de nuestro Señor Jesucristo esté con tu espíritu. Amén."
    }
  },
  "hebrews": {
    "1": {
      "1": "Dios, habiendo hablado en el pasado a los padres por medio de los profetas en muchas ocasiones y de diversas maneras,",
      "2": "al final de estos días nos ha hablado por medio de su Hijo, a quien nombró heredero de todas las cosas, por quien también hizo los mundos.",
      "3": "Su Hijo es el resplandor de su gloria, la imagen misma de su sustancia, y sostiene todas las cosas con la palabra de su poder, el cual, después de habernos purificado por sí mismo de nuestros pecados, se sentó a la derecha de la Majestad en las alturas,",
      "4": "habiendo llegado a ser tan mejor que los ángeles como el nombre más excelente que ha heredado es mejor que el de ellos.",
      "5": "Porque ¿a cuál de los ángeles dijo en algún momento,   “Tú eres mi Hijo.   ¿Hoy me he convertido en tu padre?”  y otra vez,   “Seré para él un Padre,   y será para mí un Hijo?” ",
      "6": "Cuando vuelve a traer al primogénito al mundo dice: “Que todos los ángeles de Dios lo adoren”.",
      "7": "De los ángeles dice,   “Hace vientos a sus ángeles,   y sus siervos una llama de fuego”. ",
      "8": "Pero del Hijo dice,   “Tu trono, oh Dios, es por los siglos de los siglos.   El cetro de la rectitud es el cetro de tu Reino. ",
      "9": "  Has amado la justicia y odiado la iniquidad;   por eso Dios, tu Dios, te ha ungido con el aceite de la alegría por encima de tus compañeros”. ",
      "10": "Y,   “Tú, Señor, en el principio, pusiste los cimientos de la tierra.   Los cielos son obra de tus manos. ",
      "11": "  Ellos perecerán, pero tú continúas.   Todos ellos envejecerán como lo hace una prenda de vestir. ",
      "12": "  Los enrollarás como un manto,   y serán cambiados;   pero tú eres el mismo.   Tus años no fallarán”. ",
      "13": "Pero a cuál de los ángeles le ha dicho en algún momento,   “Siéntate a mi derecha,   hasta que haga de tus enemigos el escabel de tus pies?” ",
      "14": "¿No son todos ellos espíritus servidores, enviados a hacer un servicio por el bien de los que heredarán la salvación?"
    },
    "2": {
      "1": "Por lo tanto, debemos prestar más atención a las cosas que se escucharon, para que no nos desviemos.",
      "2": "Porque si la palabra hablada por medio de los ángeles resultó firme, y toda transgresión y desobediencia recibió un justo castigo,",
      "3": "¿cómo escaparemos nosotros si descuidamos una salvación tan grande, la cual, habiendo sido hablada al principio por medio del Señor, nos fue confirmada por los que oyeron,",
      "4": "testificando Dios también con ellos, tanto por señales como por prodigios, por diversas obras de poder y por dones del Espíritu Santo, según su propia voluntad? ",
      "5": "Porque no sometió a los ángeles el mundo venidero, del que hablamos.",
      "6": "Pero uno ha testificado en alguna parte, diciendo,   “¿Qué es el hombre, para que pienses en él?   ¿O el hijo del hombre, que se preocupa por él? ",
      "7": "  Lo hiciste un poco más bajo que los ángeles.   Lo coronaste de gloria y honor. ",
      "8": "  Has sometido todas las cosas bajo sus pies”. Porque al someter todas las cosas a él, no dejó nada que no le estuviera sometido. Pero ahora todavía no vemos todas las cosas sometidas a él.",
      "9": "Pero vemos al que ha sido hecho un poco más bajo que los ángeles, Jesús, a causa del sufrimiento de la muerte, coronado de gloria y honor, para que por la gracia de Dios probara la muerte por todos. ",
      "10": "Porque a él, por quien son todas las cosas y por quien son todas las cosas, le convenía, al llevar a muchos hijos a la gloria, perfeccionar por medio de los sufrimientos al autor de su salvación.",
      "11": "Porque tanto el que santifica como los santificados proceden todos de uno, por lo que no se avergüenza de llamarlos hermanos,",
      "12": "diciendo,   “Declararé tu nombre a mis hermanos.   Entre la congregación cantaré tu alabanza”. ",
      "13": "De nuevo: “Pondré mi confianza en él”. De nuevo: “He aquí que estoy con los hijos que Dios me ha dado”.",
      "14": "Puesto que los hijos participaron de la carne y de la sangre, también él participó de lo mismo, para anular por medio de la muerte al que tenía el poder de la muerte, es decir, al diablo,",
      "15": "y liberar a todos los que, por temor a la muerte, estaban durante toda su vida sujetos a esclavitud.",
      "16": "Porque ciertamente, no da ayuda a los ángeles, sino que da ayuda a la descendencia de Abraham.",
      "17": "Por eso estaba obligado en todo a hacerse semejante a sus hermanos, para llegar a ser un sumo sacerdote misericordioso y fiel en las cosas de Dios, para expiar los pecados del pueblo.",
      "18": "Porque habiendo sufrido él mismo la tentación, puede ayudar a los que son tentados."
    },
    "3": {
      "1": "Por tanto, santos hermanos, partícipes de una vocación celestial, considerad al Apóstol y Sumo Sacerdote de nuestra confesión: Jesús,",
      "2": "que fue fiel al que lo designó, como también lo fue Moisés en toda su casa.",
      "3": "Pues ha sido considerado digno de más gloria que Moisés, porque el que construyó la casa tiene más honor que la casa.",
      "4": "Porque toda casa es construida por alguien; pero el que construyó todas las cosas es Dios.",
      "5": "Moisés, en efecto, fue fiel en toda su casa como siervo, para dar testimonio de lo que después se iba a decir,",
      "6": "pero Cristo es fiel como Hijo sobre su casa. Nosotros somos su casa, si mantenemos firme nuestra confianza y la gloria de nuestra esperanza hasta el fin.",
      "7": "Por tanto, como dice el Espíritu Santo,   “Hoy, si escuchas su voz, ",
      "8": "  no endurezcáis vuestros corazones como en la rebelión,   en el día de la prueba en el desierto, ",
      "9": "  donde tus padres me pusieron a prueba y me probaron,   y vio mis actos durante cuarenta años. ",
      "10": "  Por eso me disgusté con esa generación,   y dijo: “Siempre se equivocan en su corazón,   pero no conocían mis costumbres’. ",
      "11": "  Como juré en mi ira,   ‘No entrarán en mi descanso’”. ",
      "12": "Cuidado, hermanos, no sea que haya en alguno de vosotros un mal corazón de incredulidad, apartándose del Dios vivo;",
      "13": "sino que os exhortéis unos a otros de día en día, mientras se llame “hoy”, no sea que alguno de vosotros se endurezca por el engaño del pecado.",
      "14": "Porque hemos llegado a ser partícipes de Cristo, si mantenemos firme el principio de nuestra confianza hasta el fin,",
      "15": "mientras se dice,   “Hoy, si escuchas su voz,   no endurezcáis vuestros corazones, como en la rebelión”. ",
      "16": "Porque ¿quiénes, al oírlo, se rebelaron? ¿No fueron todos los que salieron de Egipto guiados por Moisés?",
      "17": "¿Con quiénes se disgustó durante cuarenta años? ¿No fue con los que pecaron, cuyos cuerpos cayeron en el desierto?",
      "18": "¿A quiénes juró que no entrarían en su reposo, sino a los desobedientes?",
      "19": "Vemos que no pudieron entrar a causa de la incredulidad."
    },
    "4": {
      "1": "Temamos, pues, que no parezca que alguno de vosotros se ha quedado sin la promesa de entrar en su descanso.",
      "2": "Porque ciertamente se nos ha anunciado la buena noticia, como a ellos también, pero la palabra que oyeron no les aprovechó, porque no se mezcló con la fe de los que oyeron.",
      "3": "Pues nosotros, los que hemos creído, entramos en ese reposo, como él ha dicho: “Como juré en mi ira, no entrarán en mi reposo”, aunque las obras estaban acabadas desde la fundación del mundo.",
      "4": "Porque él ha dicho esto en algún lugar acerca del séptimo día: “Dios descansó en el séptimo día de todas sus obras”;",
      "5": "y en este lugar otra vez: “No entrarán en mi reposo”. ",
      "6": "Viendo, pues, que falta que algunos entren en ella, y que aquellos a los que antes se les había predicado la buena nueva no entraron por desobediencia,",
      "7": "vuelve a definir un día determinado, “hoy”, diciendo por medio de David tanto tiempo después (tal como se ha dicho),   “Hoy, si escuchas su voz,   no endurezcáis vuestros corazones”. ",
      "8": "Porque si Josué les hubiera dado descanso, no habría hablado después de otro día.",
      "9": "Queda, pues, un descanso sabático para el pueblo de Dios.",
      "10": "Porque el que ha entrado en su reposo ha descansado también de sus obras, como Dios lo hizo de las suyas.",
      "11": "Procuremos, pues, entrar en ese reposo, para que nadie caiga en el mismo ejemplo de desobediencia.",
      "12": "Porque la palabra de Dios es viva y eficaz, y más cortante que toda espada de dos filos, pues penetra hasta la división del alma y del espíritu, de las articulaciones y de los tuétanos, y es capaz de discernir los pensamientos y las intenciones del corazón.",
      "13": "No hay criatura que se oculte a su vista, sino que todas las cosas están desnudas y expuestas ante los ojos de aquel a quien debemos rendir cuentas. ",
      "14": "Teniendo, pues, un gran sumo sacerdote que ha atravesado los cielos, Jesús, el Hijo de Dios, aferrémonos a nuestra confesión.",
      "15": "Porque no tenemos un sumo sacerdote que no pueda compadecerse de nuestras debilidades, sino uno que ha sido tentado en todo como nosotros, pero sin pecado.",
      "16": "Acerquémonos, pues, con confianza al trono de la gracia, para recibir misericordia y hallar gracia para el auxilio en el momento de necesidad."
    },
    "5": {
      "1": "Porque todo sumo sacerdote, tomado de entre los hombres, es designado para los hombres en lo que respecta a Dios, para que ofrezca tanto dones como sacrificios por los pecados.",
      "2": "El sumo sacerdote puede tratar con dulzura a los que son ignorantes y se extravían, porque él mismo está también rodeado de debilidad.",
      "3": "Por eso debe ofrecer sacrificios por los pecados, tanto por el pueblo como por él mismo.",
      "4": "Nadie se arroga este honor, sino que es llamado por Dios, como lo fue Aarón.",
      "5": "Así también Cristo no se glorificó para ser hecho sumo sacerdote, sino que fue él quien le dijo,   “Tú eres mi Hijo.   Hoy me he convertido en tu padre”. ",
      "6": "Como dice también en otro lugar,   “Eres un sacerdote para siempre,   según el orden de Melquisedec”. ",
      "7": "Él, en los días de su carne, habiendo ofrecido oraciones y peticiones con fuerte clamor y lágrimas al que podía salvarlo de la muerte, y habiendo sido escuchado por su temor piadoso,",
      "8": "aunque era un Hijo, aprendió la obediencia por las cosas que sufrió.",
      "9": "Habiendo sido perfeccionado, llegó a ser para todos los que le obedecen el autor de la salvación eterna,",
      "10": "nombrado por Dios sumo sacerdote según el orden de Melquisedec. ",
      "11": "Acerca de él tenemos muchas palabras que decir, y difíciles de interpretar, ya que os habéis vuelto torpes de oído.",
      "12": "Pues aunque ya deberíais ser maestros, necesitáis de nuevo que alguien os enseñe los rudimentos de los primeros principios de las revelaciones de Dios. Habéis llegado a necesitar leche, y no alimento sólido.",
      "13": "Porque todo el que vive de leche no tiene experiencia en la palabra de justicia, pues es un bebé.",
      "14": "Pero el alimento sólido es para los que ya han crecido, que por el uso tienen sus sentidos ejercitados para discernir el bien y el mal."
    },
    "6": {
      "1": "Por lo tanto, dejando la enseñanza de los primeros principios de Cristo, prosigamos hacia la perfección, volviendo a poner el fundamento del arrepentimiento de las obras muertas, de la fe hacia Dios,",
      "2": "de la enseñanza de los bautismos, de la imposición de manos, de la resurrección de los muertos y del juicio eterno.",
      "3": "Esto haremos, si Dios lo permite.",
      "4": "Porque en cuanto a los que una vez fueron iluminados y gustaron del don celestial, y fueron hechos partícipes del Espíritu Santo,",
      "5": "y gustaron de la buena palabra de Dios y de los poderes del siglo venidero,",
      "6": "y luego recayeron, es imposible renovarlos de nuevo al arrepentimiento, ya que crucifican de nuevo al Hijo de Dios para sí mismos, y lo exponen a la vergüenza.",
      "7": "Porque la tierra que ha bebido la lluvia que viene a menudo sobre ella y produce una cosecha adecuada para los que la cultivan, recibe la bendición de Dios;",
      "8": "pero si produce espinas y cardos, es rechazada y está a punto de ser maldecida, cuyo fin es ser quemada. ",
      "9": "Pero, amados, estamos persuadidos de cosas mejores para vosotros, y de cosas que acompañan a la salvación, aunque hablemos así.",
      "10": "Porque Dios no es injusto, como para olvidar vuestra obra y el trabajo de amor que habéis mostrado hacia su nombre, al servir a los santos, y al servirlos todavía.",
      "11": "Deseamos que cada uno de vosotros muestre la misma diligencia en la plenitud de la esperanza hasta el final,",
      "12": "para que no seáis perezosos, sino imitadores de los que por la fe y la perseverancia heredaron las promesas. ",
      "13": "Porque cuando Dios hizo una promesa a Abraham, como no podía jurar por nadie más grande, juró por sí mismo,",
      "14": "diciendo: “Ciertamente te bendeciré y te multiplicaré”.",
      "15": "Así, habiendo soportado pacientemente, obtuvo la promesa.",
      "16": "Porque los hombres ciertamente juran por uno mayor, y en toda disputa suya el juramento es definitivo para la confirmación.",
      "17": "De este modo, Dios, decidido a mostrar más abundantemente a los herederos de la promesa la inmutabilidad de su consejo, se interpuso con un juramento,",
      "18": "para que por dos cosas inmutables, en las que es imposible que Dios mienta, tengamos un fuerte estímulo, los que hemos huido para refugiarnos en la esperanza puesta ante nosotros.",
      "19": "Esta esperanza la tenemos como ancla del alma, una esperanza segura y firme que entra en lo que está dentro del velo,",
      "20": "donde como precursor entró Jesús por nosotros, convertido en sumo sacerdote para siempre según el orden de Melquisedec."
    },
    "7": {
      "1": "Porque este Melquisedec, rey de Salem, sacerdote del Dios Altísimo, que salió al encuentro de Abraham al volver de la matanza de los reyes y lo bendijo,",
      "2": "a quien también Abraham repartió la décima parte de todo (siendo primero, por interpretación, “rey de la justicia”, y luego también “rey de Salem”, que significa “rey de la paz”,",
      "3": "sin padre, sin madre, sin genealogía, no teniendo principio de días ni fin de vida, sino hecho como el Hijo de Dios), permanece sacerdote continuamente. ",
      "4": "Ahora bien, considera cuán grande era este hombre, a quien incluso Abraham el patriarca dio un décimo del mejor botín.",
      "5": "Ciertamente, los hijos de Leví que reciben el oficio de sacerdote tienen el mandato de tomar los diezmos del pueblo según la ley, es decir, de sus hermanos, aunque éstos hayan salido del cuerpo de Abraham,",
      "6": "pero aquel cuya genealogía no se cuenta a partir de ellos ha aceptado los diezmos de Abraham, y ha bendecido al que tiene las promesas.",
      "7": "Pero sin ninguna disputa el menor es bendecido por el mayor.",
      "8": "Aquí reciben los diezmos los que mueren, pero allí recibe los diezmos aquel de quien se da testimonio de que vive.",
      "9": "Podemos decir que, por medio de Abraham, incluso Leví, que recibe los diezmos, ha pagado los diezmos,",
      "10": "pues todavía estaba en el cuerpo de su padre cuando Melquisedec lo conoció. ",
      "11": "Ahora bien, si la perfección fue por medio del sacerdocio levítico (porque bajo él el pueblo ha recibido la ley), ¿qué necesidad había de que se levantara otro sacerdote según el orden de Melquisedec, y no fuera llamado según el orden de Aarón?",
      "12": "Porque siendo cambiado el sacerdocio, es necesario que se haga también un cambio en la ley.",
      "13": "Porque aquel de quien se dicen estas cosas pertenece a otra tribu, de la cual nadie ha oficiado en el altar.",
      "14": "Porque es evidente que nuestro Señor ha salido de Judá, de cuya tribu Moisés no habló nada respecto al sacerdocio.",
      "15": "Esto es aún más abundantemente evidente, si a semejanza de Melquisedec se levanta otro sacerdote,",
      "16": "que ha sido hecho, no según la ley de un mandamiento carnal, sino según el poder de una vida sin fin;",
      "17": "porque está atestiguado,   “Eres un sacerdote para siempre,   según el orden de Melquisedec”. ",
      "18": "Porque hay una anulación de un mandamiento anterior a causa de su debilidad e inutilidad",
      "19": "(porque la ley no hizo nada perfecto), y una introducción de una esperanza mejor, por la cual nos acercamos a Dios.",
      "20": "Ya que no fue hecho sacerdote sin prestar juramento",
      "21": "(pues ciertamente fueron hechos sacerdotes sin juramento), sino con juramento por el que dice de él,   “El Señor juró y no cambiará de opinión,   ‘Eres un sacerdote para siempre,   según el orden de Melquisedec”. ",
      "22": "Por tanto, Jesús se ha convertido en la garantía de un pacto mejor. ",
      "23": "Muchos, en efecto, han sido hechos sacerdotes, porque la muerte les impide continuar.",
      "24": "Pero él, por vivir eternamente, tiene su sacerdocio inmutable.",
      "25": "Por eso también puede salvar hasta el extremo a los que se acercan a Dios por medio de él, ya que vive eternamente para interceder por ellos. ",
      "26": "Porque tal sumo sacerdote nos convenía: santo, sin culpa, sin mancha, apartado de los pecadores y hecho más alto que los cielos;",
      "27": "que no tiene necesidad, como aquellos sumos sacerdotes, de ofrecer sacrificios cada día, primero por sus propios pecados y luego por los del pueblo. Porque esto lo hizo una vez para siempre, al ofrecerse a sí mismo.",
      "28": "Porque la ley nombra como sumos sacerdotes a hombres que tienen debilidad, pero la palabra del juramento, que vino después de la ley, nombra para siempre a un Hijo que ha sido perfeccionado."
    },
    "8": {
      "1": "Ahora bien, en las cosas que estamos diciendo, el punto principal es éste: tenemos tal sumo sacerdote, que se sentó a la derecha del trono de la Majestad en los cielos,",
      "2": "un servidor del santuario y del verdadero tabernáculo que el Señor levantó, no el hombre.",
      "3": "Porque todo sumo sacerdote está destinado a ofrecer tanto ofrendas como sacrificios. Por lo tanto, es necesario que este sumo sacerdote también tenga algo que ofrecer.",
      "4": "Porque si estuviera en la tierra, no sería sacerdote en absoluto, ya que hay sacerdotes que ofrecen las ofrendas según la ley,",
      "5": "que sirven de copia y sombra de las cosas celestiales, tal como Moisés fue advertido por Dios cuando iba a hacer el tabernáculo, pues le dijo: “Mira, todo lo harás según el modelo que se te mostró en la montaña.”",
      "6": "Pero ahora ha obtenido un ministerio más excelente, por cuanto es también el mediador de un pacto mejor, que sobre mejores promesas ha sido dado como ley. ",
      "7": "Porque si aquel primer pacto hubiera sido impecable, no se habría buscado lugar para un segundo.",
      "8": "Porque encontrando faltas en ellos, dijo,   “He aquí que vienen los días”, dice el Señor,   “que haré un nuevo pacto con la casa de Israel y con la casa de Judá; ",
      "9": "  no según el pacto que hice con sus padres   el día en que los tomé de la mano para sacarlos de la tierra de Egipto;   porque no continuaron en mi pacto,   y no les hice caso”, dice el Señor. ",
      "10": "  “Porque éste es el pacto que haré con la casa de Israel   después de esos días”, dice el Señor:   “Pondré mis leyes en su mente;   También los escribiré en su corazón.   Yo seré su Dios,   y serán mi pueblo. ",
      "11": "  No enseñarán a cada hombre a su conciudadano   y cada uno a su hermano, diciendo: “Conoce al Señor”.   porque todos me conocerán,   desde lo más pequeño hasta lo más grande. ",
      "12": "  Porque seré misericordioso con su injusticia.   No me acordaré más de sus pecados y de sus actos ilícitos”. ",
      "13": "Al decir: “Un nuevo pacto”, ha dejado obsoleto el primero. Pero lo que se vuelve obsoleto y envejece está a punto de desaparecer."
    },
    "9": {
      "1": "Ciertamente, incluso el primer pacto tenía ordenanzas de servicio divino y un santuario terrenal.",
      "2": "Se preparó un tabernáculo. En la primera parte estaban el candelabro, la mesa y el pan de muestra, que se llama el Lugar Santo.",
      "3": "Después del segundo velo estaba el tabernáculo que se llama el Santo de los Santos,",
      "4": "que tenía un altar de oro para el incienso y el arca de la alianza recubierta de oro por todos lados, en la que había una vasija de oro que contenía el maná, la vara de Aarón que brotaba y las tablas de la alianza;",
      "5": "y encima querubines de gloria que cubrían el propiciatorio, de lo cual no podemos hablar ahora en detalle. ",
      "6": "Así preparadas estas cosas, los sacerdotes entraban continuamente en el primer tabernáculo, cumpliendo los servicios,",
      "7": "pero en el segundo sólo entraba el sumo sacerdote, una vez al año, no sin sangre, que ofrecía por sí mismo y por los errores del pueblo.",
      "8": "El Espíritu Santo está indicando esto, que el camino hacia el Lugar Santo no fue revelado todavía mientras el primer tabernáculo estaba en pie.",
      "9": "Esto es un símbolo de la época actual, en la que se ofrecen dones y sacrificios que son incapaces, en lo que respecta a la conciencia, de hacer perfecto al adorador,",
      "10": "siendo sólo (con comidas y bebidas y lavados diversos) ordenanzas carnales, impuestas hasta un tiempo de reforma. ",
      "11": "Pero Cristo, habiendo venido como sumo sacerdote de los bienes venideros, a través del mayor y más perfecto tabernáculo, no hecho de manos, es decir, no de esta creación,",
      "12": "ni por la sangre de machos cabríos y terneros, sino por su propia sangre, entró una vez por todas en el Lugar Santo, habiendo obtenido la redención eterna.",
      "13": "Porque si la sangre de los machos cabríos y de los toros, y la ceniza de una vaquilla que rocía a los contaminados, santifican para la limpieza de la carne,",
      "14": "¿cuánto más la sangre de Cristo, que por el Espíritu eterno se ofreció a sí mismo sin defecto a Dios, limpiará vuestra conciencia de las obras muertas para servir al Dios vivo?",
      "15": "Por eso es mediador de una nueva alianza, ya que se ha producido una muerte para la redención de las transgresiones que había bajo la primera alianza, a fin de que los llamados reciban la promesa de la herencia eterna.",
      "16": "Porque donde hay un testamento, necesariamente tiene que haber la muerte del que lo hizo.",
      "17": "Porque el testamento está en vigor donde ha habido muerte, pues nunca está en vigor mientras vive el que lo hizo.",
      "18": "Por lo tanto, ni siquiera el primer pacto ha sido dedicado sin sangre.",
      "19": "Pues cuando Moisés pronunció todos los mandamientos para todo el pueblo según la ley, tomó la sangre de los terneros y de los machos cabríos, con agua, lana escarlata e hisopo, y roció tanto el libro como a todo el pueblo,",
      "20": "diciendo: “Esta es la sangre de la alianza que Dios os ha ordenado.” ",
      "21": "De la misma manera roció con sangre el tabernáculo y todos los utensilios del ministerio.",
      "22": "Según la ley, casi todo se limpia con sangre, y sin derramamiento de sangre no hay remisión. ",
      "23": "Era, pues, necesario que las copias de las cosas celestiales fueran purificadas con éstas, pero las cosas celestiales mismas con mejores sacrificios que éstos.",
      "24": "Porque Cristo no ha entrado en los lugares santos hechos de mano, que son representaciones de los verdaderos, sino en el cielo mismo, para presentarse ahora en la presencia de Dios por nosotros;",
      "25": "ni tampoco que se ofrezca a sí mismo con frecuencia, como el sumo sacerdote entra en el lugar santo año tras año con sangre que no es suya,",
      "26": "pues de lo contrario tendría que haber sufrido con frecuencia desde la fundación del mundo. Pero ahora, al final de los tiempos, se ha manifestado para quitar el pecado con el sacrificio de sí mismo.",
      "27": "Así como está establecido que los hombres mueran una vez, y después de esto, el juicio,",
      "28": "así también Cristo, habiendo sido ofrecido una vez para llevar los pecados de muchos, aparecerá por segunda vez, no para ocuparse del pecado, sino para salvar a los que lo esperan ansiosamente."
    },
    "10": {
      "1": "Porque la ley, teniendo una sombra del bien que ha de venir, y no la imagen misma de las cosas, no puede con los mismos sacrificios de año en año, que ofrecen continuamente, hacer perfectos a los que se acercan.",
      "2": "De lo contrario, ¿no habrían dejado de ofrecerse, porque los adoradores, una vez purificados, ya no tendrían conciencia de los pecados?",
      "3": "Pero en esos sacrificios hay un recuerdo anual de los pecados.",
      "4": "Porque es imposible que la sangre de los toros y de los machos cabríos quite los pecados.",
      "5": "Por eso, cuando viene al mundo, dice,   “No deseabas sacrificios ni ofrendas,   pero preparaste un cuerpo para mí. ",
      "6": "  No te agradaron los holocaustos completos ni los sacrificios por el pecado. ",
      "7": "  Entonces dije: “He aquí que he venido (en el rollo del libro está escrito de mí)   para hacer tu voluntad, oh Dios”. ",
      "8": "Antes de decir: “Sacrificios y ofrendas y holocaustos completos y sacrificios por el pecado no quisiste, ni te agradaron” (los que se ofrecen según la ley),",
      "9": "entonces ha dicho: “He venido a hacer tu voluntad”. Quita lo primero para establecer lo segundo,",
      "10": "por cuya voluntad hemos sido santificados mediante la ofrenda del cuerpo de Jesucristo hecha una vez para siempre. ",
      "11": "En efecto, todos los sacerdotes están de pie día tras día, sirviendo y ofreciendo a menudo los mismos sacrificios, que nunca pueden quitar los pecados,",
      "12": "pero él, después de haber ofrecido un solo sacrificio por los pecados para siempre, se sentó a la derecha de Dios,",
      "13": "esperando desde entonces hasta que sus enemigos sean puestos como escabel de sus pies.",
      "14": "Porque con una sola ofrenda ha perfeccionado para siempre a los santificados.",
      "15": "El Espíritu Santo también nos da testimonio, pues después de decir, ",
      "16": "  “Este es el pacto que haré con ellos   después de esos días”, dice el Señor,   “Pondré mis leyes en su corazón,   También los escribiré en su mente”. entonces dice, ",
      "17": "  “No me acordaré más de sus pecados e iniquidades”. ",
      "18": "Ahora bien, donde está la remisión de éstos, no hay más ofrenda por el pecado. ",
      "19": "Teniendo, pues, hermanos, la seguridad de entrar en el lugar santo por la sangre de Jesús,",
      "20": "por el camino que él nos dedicó, un camino nuevo y vivo, a través del velo, es decir, de su carne,",
      "21": "y teniendo un gran sacerdote sobre la casa de Dios,",
      "22": "acerquémonos con un corazón verdadero en la plenitud de la fe, teniendo nuestros corazones rociados de una mala conciencia y teniendo nuestro cuerpo lavado con agua pura,",
      "23": "mantengamos firme la confesión de nuestra esperanza sin vacilar, porque el que prometió es fiel. ",
      "24": "Consideremos cómo provocarnos unos a otros al amor y a las buenas obras,",
      "25": "no dejando de reunirnos, como acostumbran algunos, sino exhortándonos unos a otros, y tanto más cuanto veis que el Día se acerca. ",
      "26": "Porque si pecamos voluntariamente después de haber recibido el conocimiento de la verdad, ya no queda un sacrificio por los pecados,",
      "27": "sino una temible expectativa de juicio y una ferocidad de fuego que devorará a los adversarios.",
      "28": "El hombre que hace caso omiso de la ley de Moisés muere sin compasión por la palabra de dos o tres testigos.",
      "29": "¿De qué peor castigo creéis que será juzgado el que ha pisoteado al Hijo de Dios, y ha considerado impía la sangre de la alianza con la que fue santificado, y ha insultado al Espíritu de gracia?",
      "30": "Porque conocemos al que dijo: “La venganza me pertenece. Yo pagaré”, dice el Señor. Otra vez: “El Señor juzgará a su pueblo”.",
      "31": "Es una cosa temible caer en las manos del Dios vivo. ",
      "32": "Pero recordad los días anteriores, en los que, después de ser iluminados, soportasteis una gran lucha con sufrimientos:",
      "33": "en parte, estando expuestos tanto a los reproches como a las opresiones, y en parte, haciéndoos partícipes de los que eran tratados así.",
      "34": "Pues ambos os compadecisteis de mí en mis cadenas y aceptasteis con alegría el despojo de vuestros bienes, sabiendo que tenéis para vosotros una posesión mejor y duradera en los cielos.",
      "35": "Por lo tanto, no desperdiciéis vuestra audacia, que tiene una gran recompensa.",
      "36": "Porque necesitáis la resistencia para que, habiendo hecho la voluntad de Dios, recibáis la promesa. ",
      "37": "  “Dentro de muy poco,   el que venga, vendrá y no esperará. ",
      "38": "  Pero el justo vivirá por la fe.   Si se encoge, mi alma no se complace en él”. ",
      "39": "Pero no somos de los que retroceden a la destrucción, sino de los que tienen fe para la salvación del alma."
    }
  }
};

