
	
export const bib_verses = {
  "galatians": {
    "5": {
      "1": "Manténganse, pues, firmes en la libertad con que Cristo nos hizo libres, y no vuelvan a enredarse con el yugo de la esclavitud. ",
      "2": "He aquí, yo, Pablo, os digo que si recibís la circuncisión, de nada os servirá Cristo.",
      "3": "Sí, vuelvo a testificar a todo hombre que recibe la circuncisión que es deudor de cumplir toda la ley.",
      "4": "Estáis alejados de Cristo, los que queréis ser justificados por la ley. Os habéis apartado de la gracia.",
      "5": "Porque nosotros, por medio del Espíritu, aguardamos por fe la esperanza de la justicia.",
      "6": "Porque en Cristo Jesús ni la circuncisión ni la incircuncisión valen nada, sino la fe que obra por el amor. ",
      "7": "¡Corríais bien! ¿Quién se entrometió en ti para que no obedecieras la verdad?",
      "8": "Esta persuasión no proviene del que os llama.",
      "9": "Un poco de levadura crece en toda la masa.",
      "10": "Tengo confianza para con vosotros en el Señor, que no pensaréis de otra manera. Pero el que os molesta llevará su juicio, sea quien sea. ",
      "11": "Pero yo, hermanos, si todavía predico la circuncisión, ¿por qué sigo siendo perseguido? Entonces se ha quitado el escollo de la cruz.",
      "12": "Quisiera que los que os molestan se cortaran a sí mismos. ",
      "13": "Porque vosotros, hermanos, habéis sido llamados a la libertad. Sólo que no usen su libertad como una oportunidad para la carne, sino que por amor sean servidores de los demás.",
      "14": "Porque toda la ley se cumple en una sola palabra, en esta: “Amarás a tu prójimo como a ti mismo”.",
      "15": "Pero si os mordéis y os devoráis unos a otros, tened cuidado de no consumiros unos a otros. ",
      "16": "Pero yo digo: andad por el Espíritu, y no cumpliréis los deseos de la carne.",
      "17": "Porque la carne desea contra el Espíritu, y el Espíritu contra la carne; y éstos se oponen entre sí, para que no hagáis lo que deseáis.",
      "18": "Pero si sois guiados por el Espíritu, no estáis bajo la ley.",
      "19": "Ahora bien, son evidentes las obras de la carne, que son: adulterio, inmoralidad sexual, impureza, lujuria,",
      "20": "idolatría, hechicería, odios, contiendas, celos, arrebatos de cólera, rivalidades, divisiones, herejías,",
      "21": "envidias, asesinatos, borracheras, orgías, y cosas semejantes a éstas; de las cuales os advierto, como también os he advertido, que los que practican tales cosas no heredarán el Reino de Dios. ",
      "22": "Pero el fruto del Espíritu es amor, alegría, paz, paciencia, amabilidad, bondad, fe,",
      "23": "mansedumbre y dominio propio. Contra tales cosas no hay ley.",
      "24": "Los que son de Cristo han crucificado la carne con sus pasiones y deseos. ",
      "25": "Si vivimos por el Espíritu, andemos también por el Espíritu.",
      "26": "No nos ensoberbezcamos, ni nos provoquemos unos a otros, ni nos envidiemos."
    },
    "6": {
      "1": "Hermanos, aunque un hombre sea sorprendido en alguna falta, vosotros, que sois espirituales, restauradlo con espíritu de mansedumbre, mirándoos a vosotros mismos para que tampoco seáis tentados.",
      "2": "Sobrellevad los unos las cargas de los otros, y cumplid así la ley de Cristo.",
      "3": "Porque si uno se cree algo cuando no es nada, se engaña a sí mismo.",
      "4": "Pero que cada uno examine su propia obra, y entonces tendrá razón para gloriarse en sí mismo, y no en otro.",
      "5": "Porque cada uno llevará su propia carga. ",
      "6": "Pero el que es enseñado en la palabra, comparta todo lo bueno con el que enseña. ",
      "7": "No te engañes. Dios no se burla, porque todo lo que el hombre siembra, eso también cosechará.",
      "8": "Porque el que siembra para su propia carne, de la carne cosechará corrupción. Pero el que siembra para el Espíritu, del Espíritu cosechará vida eterna.",
      "9": "No nos cansemos de hacer el bien, porque cosecharemos a su tiempo si no nos damos por vencidos.",
      "10": "Así que, según tengamos oportunidad, hagamos el bien a todos los hombres, y especialmente a los de la familia de la fe. ",
      "11": "Mirad con qué letras tan grandes os escribo de mi propia mano.",
      "12": "Todos los que desean causar una buena impresión en la carne os obligan a circuncidaros, para no ser perseguidos por la cruz de Cristo.",
      "13": "Pues incluso los que reciben la circuncisión no guardan ellos mismos la ley, sino que desean que os circuncidéis para presumir en vuestra carne.",
      "14": "Pero lejos está de mí el gloriarme sino en la cruz de nuestro Señor Jesucristo, por quien el mundo ha sido crucificado para mí, y yo para el mundo.",
      "15": "Porque en Cristo Jesús ni la circuncisión es nada, ni la incircuncisión, sino una nueva creación.",
      "16": "Todos los que andan por esta regla, la paz y la misericordia sean con ellos, y con el Israel de Dios. ",
      "17": "A partir de ahora, que nadie me cause problemas, porque llevo las marcas del Señor Jesús marcadas en mi cuerpo. ",
      "18": "La gracia de nuestro Señor Jesucristo esté con vuestro espíritu, hermanos. Amén."
    }
  },
  "ephesians": {
    "1": {
      "1": "Pablo, apóstol de Cristo Jesús por la voluntad de Dios, a los santos que están en Éfeso y a los fieles en Cristo Jesús:",
      "2": "Gracia a vosotros y paz de parte de Dios nuestro Padre y del Señor Jesucristo. ",
      "3": "Bendito sea el Dios y Padre de nuestro Señor Jesucristo, que nos ha bendecido con toda bendición espiritual en los lugares celestiales en Cristo,",
      "4": "así como nos eligió en él antes de la fundación del mundo, para que fuéramos santos y sin defecto ante él en el amor,",
      "5": "habiéndonos predestinado para ser adoptados como hijos por medio de Jesucristo para sí mismo, según el beneplácito de su deseo,",
      "6": "para alabanza de la gloria de su gracia, por la cual nos favoreció gratuitamente en el Amado.",
      "7": "En él tenemos nuestra redención por medio de su sangre, el perdón de nuestros delitos, según las riquezas de su gracia",
      "8": "que hizo abundar para con nosotros en toda sabiduría y prudencia,",
      "9": "dándonos a conocer el misterio de su voluntad, según su beneplácito que se propuso en él",
      "10": "para una administración de la plenitud de los tiempos, para resumir en Cristo todas las cosas, las que están en los cielos y las que están en la tierra.",
      "11": "También a nosotros se nos asignó una herencia en él, habiendo sido preordenados según el propósito de aquel que hace todas las cosas según el consejo de su voluntad,",
      "12": "a fin de que seamos para alabanza de su gloria, nosotros que antes esperábamos en Cristo.",
      "13": "En él también vosotros, habiendo oído la palabra de la verdad, la Buena Nueva de vuestra salvación, en quien, habiendo creído también, fuisteis sellados con el Espíritu Santo prometido,",
      "14": "que es prenda de nuestra herencia, para la redención de la posesión de Dios, para alabanza de su gloria. ",
      "15": "Por eso yo también, habiendo oído de la fe en el Señor Jesús que hay entre vosotros y del amor que tenéis hacia todos los santos,",
      "16": "no ceso de dar gracias por vosotros, haciendo mención de vosotros en mis oraciones,",
      "17": "para que el Dios de nuestro Señor Jesucristo, el Padre de la gloria, os dé un espíritu de sabiduría y de revelación en el conocimiento de él,",
      "18": "teniendo los ojos de vuestros corazones iluminados, para que sepáis cuál es la esperanza de su llamamiento y cuáles son las riquezas de la gloria de su herencia en los santos,",
      "19": "y cuál es la supereminente grandeza de su poder para con nosotros los que creemos, según la operación de la fuerza de su poder",
      "20": "que obró en Cristo cuando lo resucitó de entre los muertos y lo hizo sentar a su derecha en los lugares celestiales,",
      "21": "muy por encima de todo gobierno, autoridad, poder, dominio y todo nombre que se nombra, no sólo en este siglo, sino también en el venidero.",
      "22": "Sometió todas las cosas a sus pies y le dio como cabeza de todas las cosas a la asamblea,",
      "23": "que es su cuerpo, la plenitud de aquel que lo llena todo en todos."
    },
    "2": {
      "1": "Fuisteis vivificados cuando estabais muertos en transgresiones y pecados,",
      "2": "en los cuales anduvisteis en otro tiempo según la corriente de este mundo, conforme al príncipe de la potestad del aire, el espíritu que ahora obra en los hijos de la desobediencia.",
      "3": "También todos nosotros vivimos en otro tiempo en los deseos de nuestra carne, haciendo los deseos de la carne y de la mente, y éramos por naturaleza hijos de la ira, como los demás.",
      "4": "Pero Dios, rico en misericordia, por su gran amor con que nos amó,",
      "5": "aun cuando estábamos muertos por nuestros delitos, nos dio vida juntamente con Cristo — por gracia habéis sido salvados —",
      "6": "y nos resucitó con él, haciéndonos sentar con él en los lugares celestiales en Cristo Jesús,",
      "7": "para mostrar en los siglos venideros las abundantes riquezas de su gracia en su bondad para con nosotros en Cristo Jesús;",
      "8": "porque por gracia habéis sido salvados por medio de la fe, y esto no de vosotros mismos; es don de Dios,",
      "9": "no por obras, para que nadie se gloríe.",
      "10": "Porque somos hechura suya, creados en Cristo Jesús para buenas obras, las cuales Dios preparó de antemano para que anduviéramos en ellas. ",
      "11": "Recordad, pues, que en otro tiempo vosotros, los gentiles en la carne, que sois llamados “incircuncisión” por lo que se llama “circuncisión” (en la carne, hecha por las manos),",
      "12": "que en aquel tiempo estabais separados de Cristo, alejados de la comunidad de Israel y extraños a los pactos de la promesa, sin esperanza y sin Dios en el mundo.",
      "13": "Pero ahora, en Cristo Jesús, vosotros, que en otro tiempo estabais alejados, habéis sido hechos cercanos por la sangre de Cristo.",
      "14": "Porque él es nuestra paz, que de ambos hizo uno, derribando la pared intermedia de separación,",
      "15": "habiendo abolido en su carne la enemistad, la ley de los mandamientos contenidos en las ordenanzas, para crear en sí mismo un solo hombre nuevo de los dos, haciendo la paz,",
      "16": "y reconciliar a ambos en un solo cuerpo con Dios por medio de la cruz, matando por ella la enemistad.",
      "17": "Vino a predicar la paz a los que estaban lejos y a los que estaban cerca.",
      "18": "Porque por medio de él ambos tenemos acceso al Padre en un solo Espíritu.",
      "19": "Así pues, ya no sois extranjeros ni forasteros, sino conciudadanos de los santos y de la familia de Dios,",
      "20": "edificados sobre el fundamento de los apóstoles y profetas, siendo Cristo Jesús mismo la principal piedra del ángulo;",
      "21": "en el cual todo el edificio, unido entre sí, va creciendo hasta convertirse en un templo santo en el Señor;",
      "22": "en el cual también vosotros sois edificados juntos para morada de Dios en el Espíritu."
    },
    "3": {
      "1": "Por esta razón yo, Pablo, soy el prisionero de Cristo Jesús en favor de vosotros los gentiles,",
      "2": "si es que habéis oído hablar de la administración de aquella gracia de Dios que me fue dada para con vosotros,",
      "3": "cómo por revelación me fue dado a conocer el misterio, como antes escribí en pocas palabras,",
      "4": "por el cual, cuando leéis, podéis percibir mi entendimiento en el misterio de Cristo",
      "5": "que en otras generaciones no fue dado a conocer a los hijos de los hombres, como ahora ha sido revelado a sus santos apóstoles y profetas en el Espíritu,",
      "6": "que los gentiles son coherederos y miembros del cuerpo, y copartícipes de su promesa en Cristo Jesús por medio de la Buena Nueva,",
      "7": "de la cual fui hecho siervo según el don de aquella gracia de Dios que me fue dada según la operación de su poder.",
      "8": "A mí, el más insignificante de todos los santos, me fue dada esta gracia de predicar a los gentiles las inescrutables riquezas de Cristo,",
      "9": "y de hacer ver a todos los hombres cuál es la administración del misterio que por siglos ha estado oculto en Dios, quien creó todas las cosas por medio de Jesucristo,",
      "10": "con el fin de que ahora, por medio de la asamblea, se dé a conocer la multiplicidad de la sabiduría de Dios a los principados y a las potestades en los lugares celestiales,",
      "11": "según el propósito eterno que realizó en Cristo Jesús, nuestro Señor.",
      "12": "En él tenemos confianza y acceso en confianza por nuestra fe en él.",
      "13": "Por lo tanto, les pido que no se desanimen ante mis problemas por ustedes, que son su gloria. ",
      "14": "Por esta razón, doblo mis rodillas ante el Padre de nuestro Señor Jesucristo,",
      "15": "de quien procede toda familia en el cielo y en la tierra,",
      "16": "para que os conceda, según las riquezas de su gloria, que seáis fortalecidos con poder por su Espíritu en la persona interior",
      "17": "para que Cristo habite en vuestros corazones por medio de la fe, a fin de que, arraigados y cimentados en el amor,",
      "18": "seáis fortalecidos para comprender con todos los santos cuál es la anchura, la longitud, la altura y la profundidad,",
      "19": "y conocer el amor de Cristo, que sobrepasa todo conocimiento, para que seáis llenos de toda la plenitud de Dios. ",
      "20": "A aquel que es capaz de hacer muchísimo más de lo que pedimos o pensamos, según el poder que obra en nosotros,",
      "21": "a él sea la gloria en la asamblea y en Cristo Jesús por todas las generaciones, por los siglos de los siglos. Amén."
    },
    "4": {
      "1": "Por lo tanto, yo, prisionero en el Señor, os ruego que os comportéis como corresponde a la vocación con la que habéis sido llamados,",
      "2": "con toda humildad, paciencia, soportándoos unos a otros en el amor,",
      "3": "procurando guardar la unidad del Espíritu en el vínculo de la paz.",
      "4": "Hay un solo cuerpo y un solo Espíritu, así como vosotros también fuisteis llamados en una sola esperanza de vuestra vocación,",
      "5": "un solo Señor, una sola fe, un solo bautismo,",
      "6": "un solo Dios y Padre de todos, que está sobre todos y por todos y en todos nosotros.",
      "7": "Pero a cada uno de nosotros se le dio la gracia según la medida del don de Cristo.",
      "8": "Por eso dice,   “Cuando ascendió a lo alto,   llevó cautiva la cautividad,   y daba regalos a la gente”.",
      "9": "  Ahora bien, esto de “ascendió”, ¿qué es sino que también descendió primero a las partes bajas de la tierra?",
      "10": "El que descendió es el que también ascendió muy por encima de todos los cielos, para llenarlo todo. ",
      "11": "A unos les dio ser apóstoles, a otros profetas, a otros evangelistas, a otros pastores y maestros",
      "12": "para el perfeccionamiento de los santos, para la obra de servir, para la edificación del cuerpo de Cristo,",
      "13": "hasta que todos lleguemos a la unidad de la fe y del conocimiento del Hijo de Dios, a un varón hecho y derecho, a la medida de la estatura de la plenitud de Cristo,",
      "14": "para que ya no seamos niños, zarandeados y llevados por todo viento de doctrina, por estratagema de hombres, con astucia, según las artimañas del error;",
      "15": "sino que, hablando la verdad con amor, crezcamos en todo en aquel que es la cabeza, Cristo,",
      "16": "de quien todo el cuerpo, bien concertado y unido entre sí por la acción de cada una de las coyunturas, según la medida de cada una de las partes, contribuye a la edificación del cuerpo en el amor. ",
      "17": "Esto digo, pues, y testifico en el Señor, que ya no andáis como los demás gentiles, en la inutilidad de su mente,",
      "18": "entenebrecidos en su entendimiento, alejados de la vida de Dios por la ignorancia que hay en ellos, por el endurecimiento de sus corazones.",
      "19": "Ellos, habiéndose vuelto insensibles, se entregaron a la lujuria, para obrar toda impureza con avidez.",
      "20": "Pero vosotros no aprendisteis a Cristo de esa manera,",
      "21": "si es que le oísteis y fuisteis enseñados en él, así como la verdad está en Jesús:",
      "22": "que os despojéis, en cuanto a vuestra antigua manera de vivir, del viejo hombre que se corrompe según los deseos del engaño,",
      "23": "y que os renovéis en el espíritu de vuestra mente,",
      "24": "y os revistáis del nuevo hombre, que a semejanza de Dios ha sido creado en justicia y santidad de la verdad. ",
      "25": "Por lo tanto, desechando la mentira, hablad con la verdad cada uno con su prójimo, pues somos miembros los unos de los otros.",
      "26": "“Enfádate y no peques”. No dejes que se ponga el sol sobre tu ira,",
      "27": "y no des lugar al diablo.",
      "28": "El que roba no robe más, sino que trabaje, produciendo con sus manos algo bueno, para tener algo que dar al que tiene necesidad.",
      "29": "No salga de vuestra boca ninguna palabra corrompida, sino sólo lo que es bueno para edificar a los demás según la necesidad, a fin de dar gracia a los que escuchan.",
      "30": "No entristezcáis al Espíritu Santo de Dios, en quien fuisteis sellados para el día de la redención.",
      "31": "Aparta de ti toda amargura, ira, enojo, gritería y calumnia, con toda malicia.",
      "32": "Y sed bondadosos unos con otros, tiernos de corazón, perdonándoos mutuamente, como también Dios os perdonó a vosotros en Cristo."
    },
    "5": {
      "1": "Sed, pues, imitadores de Dios, como hijos amados.",
      "2": "Caminad en el amor, como también Cristo nos amó y se entregó a sí mismo por nosotros, ofrenda y sacrificio a Dios en olor fragante. ",
      "3": "Pero la inmoralidad sexual, y toda inmundicia o codicia, ni siquiera se mencione entre vosotros, como conviene a los santos;",
      "4": "ni la inmundicia, ni las conversaciones necias, ni las bromas, que no son apropiadas, sino más bien la acción de gracias. ",
      "5": "Sabed con certeza que ningún inmoral sexual, ni impuro, ni codicioso (que es idólatra), tiene herencia en el Reino de Cristo y de Dios. ",
      "6": "Que nadie os engañe con palabras vacías, porque a causa de estas cosas la ira de Dios viene sobre los hijos de la desobediencia.",
      "7": "Por tanto, no seáis partícipes de ellos.",
      "8": "Porque antes erais tinieblas, pero ahora sois luz en el Señor. Caminad como hijos de la luz,",
      "9": "porque el fruto del Espíritu es en toda bondad, justicia y verdad,",
      "10": "demostrando lo que es agradable al Señor.",
      "11": "No tengáis comunión con las obras infructuosas de las tinieblas, sino más bien reprendedlas.",
      "12": "Porque es una vergüenza incluso hablar de las cosas que hacen en secreto.",
      "13": "Pero todas las cosas, cuando son reprendidas, son reveladas por la luz, porque todo lo que revela es luz.",
      "14": "Por eso dice: “Despierta, tú que duermes, y levántate de entre los muertos, y Cristo brillará sobre ti.” ",
      "15": "Por lo tanto, mirad bien cómo andáis, no como imprudentes, sino como sabios,",
      "16": "aprovechando el tiempo, porque los días son malos.",
      "17": "No seáis, pues, insensatos, sino comprended cuál es la voluntad del Señor.",
      "18": "No os embriaguéis con vino, en lo cual hay disipación, sino sed llenos del Espíritu,",
      "19": "hablando entre vosotros con salmos, himnos y cánticos espirituales; cantando y entonando melodías en vuestro corazón al Señor;",
      "20": "dando siempre gracias por todo en nombre de nuestro Señor Jesucristo a Dios, el Padre;",
      "21": "sometiéndoos unos a otros en el temor de Cristo. ",
      "22": "Esposas, estad sujetas a vuestros maridos, como al Señor.",
      "23": "Porque el marido es la cabeza de la mujer, como también Cristo es la cabeza de la asamblea, siendo él mismo el salvador del cuerpo.",
      "24": "Pero como la asamblea está sujeta a Cristo, así también las esposas estén sujetas a sus propios maridos en todo. ",
      "25": "Maridos, amad a vuestras mujeres, así como Cristo amó a la asamblea y se entregó a sí mismo por ella,",
      "26": "para santificarla, habiéndola purificado mediante el lavado del agua con la palabra,",
      "27": "a fin de presentársela a sí mismo gloriosa, sin mancha ni arruga ni cosa semejante, sino santa y sin defecto.",
      "28": "Así también los maridos deben amar a sus propias esposas como a sus propios cuerpos. El que ama a su propia mujer se ama a sí mismo.",
      "29": "Porque nadie ha odiado jamás su propia carne, sino que la alimenta y la cuida, como también el Señor lo hace con la asamblea,",
      "30": "porque somos miembros de su cuerpo, de su carne y de sus huesos.",
      "31": "“Por eso el hombre dejará a su padre y a su madre y se unirá a su mujer. Entonces los dos se convertirán en una sola carne”.",
      "32": "Este misterio es grande, pero yo hablo de Cristo y de la asamblea.",
      "33": "Sin embargo, cada uno de vosotros debe amar también a su propia mujer como a sí mismo; y que la mujer respete a su marido."
    },
    "6": {
      "1": "Hijos, obedeced a vuestros padres en el Señor, porque esto es justo.",
      "2": "“Honra a tu padre y a tu madre”, que es el primer mandamiento con una promesa:",
      "3": "“para que te vaya bien y vivas mucho tiempo en la tierra.” ",
      "4": "Vosotros, padres, no provoquéis a vuestros hijos a la ira, sino educadlos en la disciplina y la instrucción del Señor. ",
      "5": "Siervos, obedeced a los que según la carne son vuestros amos, con temor y temblor, con sencillez de corazón, como a Cristo,",
      "6": "no sirviendo sólo cuando los ojos están puestos en vosotros, como los que complacen a los hombres, sino como siervos de Cristo, haciendo de corazón la voluntad de Dios,",
      "7": "con buena voluntad haciendo el servicio como al Señor y no a los hombres,",
      "8": "sabiendo que cualquier cosa buena que cada uno haga, la volverá a recibir del Señor, esté atado o libre. ",
      "9": "Vosotros, amos, haced lo mismo con ellos y dejad de amenazar, sabiendo que el que es a la vez su amo y el vuestro está en el cielo, y no hay parcialidad con él. ",
      "10": "Por último, fortaleceos en el Señor y en la fuerza de su poder.",
      "11": "Vestíos de toda la armadura de Dios, para que podáis resistir las asechanzas del diablo.",
      "12": "Porque nuestra lucha no es contra la carne y la sangre, sino contra los principados, contra las potestades, contra los gobernantes del mundo de las tinieblas de este siglo y contra las fuerzas espirituales de la maldad en los lugares celestiales.",
      "13": "Vestíos, pues, de toda la armadura de Dios, para que podáis resistir en el día malo, y habiendo hecho todo, estar firmes.",
      "14": "Estad, pues, de pie, teniendo abrochado a la cintura el cinturón de la verdad, y habiéndoos puesto la coraza de la justicia,",
      "15": "y calzando vuestros pies con la preparación de la Buena Nueva de la paz,",
      "16": "sobre todo, tomando el escudo de la fe, con el cual podréis apagar todos los dardos de fuego del maligno.",
      "17": "Y tomad el yelmo de la salvación, y la espada del Espíritu, que es la palabra de Dios;",
      "18": "con toda oración y solicitud, orando en todo tiempo en el Espíritu, y velando para ello con toda perseverancia y solicitud por todos los santos.",
      "19": "Orad por mí, para que me sea dada la palabra al abrir mi boca, para dar a conocer con denuedo el misterio de la Buena Nueva,",
      "20": "de la cual soy embajador encadenado; para que en ella hable con denuedo, como debo hablar. ",
      "21": "Pero para que también vosotros conozcáis mis asuntos, cómo estoy, Tíquico, el hermano amado y siervo fiel en el Señor, os lo hará saber todo.",
      "22": "Lo he enviado a vosotros con este mismo fin, para que conozcáis nuestra situación y para que consuele vuestros corazones. ",
      "23": "La paz sea con los hermanos, y el amor con la fe, de parte de Dios Padre y del Señor Jesucristo.",
      "24": "La gracia sea con todos los que aman a nuestro Señor Jesucristo con amor incorruptible. Amén."
    }
  },
  "philippians": {
    "1": {
      "1": "Pablo y Timoteo, siervos de Jesucristo, a todos los santos en Cristo Jesús que están en Filipos, con los capataces y los servidores:",
      "2": "Gracia y paz de parte de Dios nuestro Padre y del Señor Jesucristo. ",
      "3": "Doy gracias a mi Dios cada vez que me acuerdo de vosotros,",
      "4": "siempre en todas mis peticiones en favor de todos vosotros, haciendo mis peticiones con alegría,",
      "5": "por vuestra colaboración en la promoción de la Buena Nueva desde el primer día hasta ahora;",
      "6": "estando seguro de esto mismo, de que el que comenzó una buena obra en vosotros la completará hasta el día de Jesucristo.",
      "7": "Incluso es justo que piense así en nombre de todos vosotros, porque os tengo en mi corazón, ya que tanto en mis obligaciones como en la defensa y confirmación de la Buena Nueva, todos sois partícipes conmigo de la gracia.",
      "8": "Porque Dios es mi testigo de cómo anhelo a todos ustedes en la tierna misericordia de Cristo Jesús. ",
      "9": "Esto ruego: que vuestro amor abunde aún más en conocimiento y en todo discernimiento,",
      "10": "para que aprobéis las cosas excelentes, a fin de que seáis sinceros y sin ofensa para el día de Cristo,",
      "11": "llenos de los frutos de la justicia que son por medio de Jesucristo, para gloria y alabanza de Dios. ",
      "12": "Quiero que sepáis, hermanos, que lo que me ha sucedido ha resultado más bien para el progreso de la Buena Nueva,",
      "13": "de modo que se ha hecho evidente a toda la guardia del palacio y a todos los demás que mis ataduras son en Cristo,",
      "14": "y que la mayoría de los hermanos en el Señor, confiados por mis ataduras, se atreven más a hablar la palabra de Dios sin temor.",
      "15": "En efecto, algunos predican a Cristo incluso por envidia y contienda, y otros también por buena voluntad.",
      "16": "Los primeros predican insinceramente a Cristo por ambición egoísta, pensando que añaden aflicción a mis cadenas;",
      "17": "pero los segundos por amor, sabiendo que estoy destinado a la defensa de la Buena Nueva. ",
      "18": "¿Qué importa? Sólo que de todas las maneras, ya sea en apariencia o en verdad, se anuncie a Cristo. Me alegro de esto, sí, y me alegraré.",
      "19": "Porque sé que esto resultará para mi salvación por medio de vuestras oraciones y de la provisión del Espíritu de Jesucristo,",
      "20": "según mi ferviente expectativa y esperanza, que de ninguna manera seré defraudado, sino que con toda valentía, como siempre, ahora también Cristo será magnificado en mi cuerpo, ya sea por la vida o por la muerte.",
      "21": "Porque para mí vivir es Cristo, y morir es una ganancia.",
      "22": "Pero si sigo viviendo en la carne, esto dará fruto de mi trabajo; sin embargo, no sé qué elegiré.",
      "23": "Pero estoy en apuros entre los dos, teniendo el deseo de partir y estar con Cristo, lo cual es mucho mejor.",
      "24": "Sin embargo, permanecer en la carne es más necesario por tu bien.",
      "25": "Teniendo esta confianza, sé que me quedaré, sí, y permaneceré con todos vosotros para vuestro progreso y gozo en la fe,",
      "26": "para que vuestra jactancia abunde en Cristo Jesús en mí por mi presencia de nuevo con vosotros. ",
      "27": "Solamente que vuestra manera de vivir sea digna de la Buena Nueva de Cristo, para que, tanto si voy a veros como si estoy ausente, me entere de vuestro estado, de que os mantenéis firmes en un solo espíritu, con una sola alma que lucha por la fe de la Buena Nueva;",
      "28": "y en nada os asustan los adversarios, lo cual es para ellos una prueba de destrucción, pero para vosotros de salvación, y eso de parte de Dios.",
      "29": "Porque se os ha concedido, en nombre de Cristo, no sólo creer en él, sino también sufrir en su nombre,",
      "30": "teniendo el mismo conflicto que visteis en mí y que ahora oís que está en mí."
    },
    "2": {
      "1": "Por lo tanto, si hay alguna exhortación en Cristo, si hay algún consuelo de amor, si hay alguna comunión del Espíritu, si hay alguna misericordia y compasión,",
      "2": "haced que mi alegría sea plena, teniendo los mismos sentimientos, teniendo el mismo amor, siendo unánimes, de un mismo parecer;",
      "3": "no haciendo nada por rivalidad o por presunción, sino con humildad, considerando cada uno a los demás como mejores que él mismo;",
      "4": "no mirando cada uno sólo lo suyo, sino también lo de los demás. ",
      "5": "Tened presente esto, que también hubo en Cristo Jesús,",
      "6": "el cual, existiendo en forma de Dios, no consideró el ser igual a Dios como cosa a que aferrarse,",
      "7": "sino que se despojó a sí mismo, tomando la forma de siervo, hecho semejante a los hombres.",
      "8": "Y hallándose en forma humana, se humilló a sí mismo, haciéndose obediente hasta la muerte, sí, la muerte de cruz.",
      "9": "Por eso Dios también lo exaltó en alto grado y le dio el nombre que está por encima de todo nombre,",
      "10": "para que ante el nombre de Jesús se doble toda rodilla de los que están en el cielo, en la tierra y debajo de la tierra,",
      "11": "y toda lengua confiese que Jesucristo es el Señor, para gloria de Dios Padre. ",
      "12": "Así que, amados míos, como siempre habéis obedecido, no sólo en mi presencia, sino ahora mucho más en mi ausencia, ocupaos en vuestra salvación con temor y temblor.",
      "13": "Porque Dios es el que obra en vosotros tanto el querer como el hacer por su buena voluntad. ",
      "14": "Haced todo sin quejaros ni discutir,",
      "15": "para que lleguéis a ser irreprochables e inofensivos, hijos de Dios sin defecto en medio de una generación torcida y perversa, en medio de la cual sois vistos como luces en el mundo,",
      "16": "sosteniendo la palabra de vida, para que tenga algo de que jactarse en el día de Cristo de que no corrí en vano ni trabajé en vano.",
      "17": "Sí, y si me derramo en el sacrificio y servicio de vuestra fe, me alegro y me regocijo con todos vosotros.",
      "18": "De la misma manera, ustedes también deben alegrarse y regocijarse conmigo. ",
      "19": "Pero espero en el Señor Jesús que te envíe pronto a Timoteo, para que yo también me alegre al saber cómo te va.",
      "20": "Porque no tengo a nadie más afín, que se preocupe de verdad por ti.",
      "21": "Porque todos buscan lo suyo, no las cosas de Jesucristo.",
      "22": "Pero tú sabes que él se ha probado a sí mismo. Como un hijo sirve a un padre, así ha servido conmigo en la promoción de la Buena Nueva.",
      "23": "Por eso espero enviarlo enseguida, en cuanto vea cómo me va a ir.",
      "24": "Pero confío en el Señor que yo mismo también vendré pronto. ",
      "25": "Pero consideré necesario enviaros a Epafrodito, mi hermano, compañero de trabajo, compañero de milicia, y vuestro apóstol y servidor de mi necesidad,",
      "26": "ya que anhelaba a todos vosotros, y estaba muy preocupado porque habíais oído que estaba enfermo.",
      "27": "Porque, en efecto, estuvo enfermo casi hasta la muerte, pero Dios tuvo misericordia de él, y no sólo de él, sino también de mí, para que no tuviera pena sobre pena.",
      "28": "Por eso lo he enviado con mayor diligencia, para que cuando lo veáis de nuevo, os alegréis, y yo me entristezca menos.",
      "29": "Recibidlo, pues, en el Señor con toda alegría, y tened a estas personas en honor,",
      "30": "porque por la obra de Cristo se acercó a la muerte, arriesgando su vida para suplir lo que faltaba en vuestro servicio hacia mí."
    },
    "3": {
      "1": "Por último, hermanos míos, ¡alégrense en el Señor! Escribiros las mismas cosas, a mí en verdad no me cansa, pero para vosotros es seguro. ",
      "2": "Guardaos de los perros; guardaos de los malos obreros; guardaos de la falsa circuncisión.",
      "3": "Porque nosotros somos la circuncisión, que adoramos a Dios en el Espíritu, y nos regocijamos en Cristo Jesús, y no tenemos confianza en la carne;",
      "4": "aunque yo mismo tenga confianza incluso en la carne. Si algún otro hombre piensa que tiene confianza en la carne, yo aún más:",
      "5": "circuncidado al octavo día, del linaje de Israel, de la tribu de Benjamín, hebreo de los hebreos; en cuanto a la ley, fariseo;",
      "6": "en cuanto al celo, perseguidor de la asamblea; en cuanto a la justicia que está en la ley, hallado irreprochable. ",
      "7": "Sin embargo, considero las cosas que fueron para mí ganancia como pérdida por Cristo.",
      "8": "Sí, ciertamente, y estimo todas las cosas como pérdida por la excelencia del conocimiento de Cristo Jesús, mi Señor, por quien he sufrido la pérdida de todas las cosas, y las tengo por basura, para ganar a Cristo",
      "9": "y ser hallado en él, no teniendo una justicia propia, la que es de la ley sino la que es por la fe en Cristo, la justicia que proviene de Dios por la fe,",
      "10": "para conocerlo a él y el poder de su resurrección, y la participación en sus padecimientos, haciéndome semejante a su muerte,",
      "11": "si es que de alguna manera llego a la resurrección de entre los muertos.",
      "12": "No es que ya lo haya obtenido, o que ya esté perfeccionado, sino que prosigo, para apoderarme de aquello para lo cual también fui apresado por Cristo Jesús. ",
      "13": "Hermanos, no me considero todavía como asido, pero una cosa hago: olvidando lo que queda atrás y extendiéndome a lo que está delante,",
      "14": "prosigo hacia la meta por el premio de la alta vocación de Dios en Cristo Jesús.",
      "15": "Pensemos, pues, así todos los que somos perfectos. Si en algo pensáis de otra manera, Dios también os lo revelará.",
      "16": "Sin embargo, en la medida en que ya hemos alcanzado, caminemos según la misma regla. Seamos de la misma mente. ",
      "17": "Hermanos, sed imitadores juntos de mí, y fijaos en los que andan por este camino, así como nos tenéis por ejemplo.",
      "18": "Porque muchos andan, de los cuales os he hablado muchas veces, y ahora os lo digo incluso llorando, como los enemigos de la cruz de Cristo,",
      "19": "cuyo fin es la destrucción, cuyo dios es el vientre, y cuya gloria está en su vergüenza, que piensan en las cosas terrenales.",
      "20": "Porque nuestra ciudadanía está en los cielos, desde donde también esperamos a un Salvador, el Señor Jesucristo,",
      "21": "que transformará el cuerpo de nuestra humillación para que sea conforme al cuerpo de su gloria, según la acción por la cual puede incluso someter todas las cosas a sí mismo."
    },
    "4": {
      "1": "Por tanto, hermanos míos, amados y anhelados, mi alegría y mi corona, manteneos firmes en el Señor de esta manera, amados míos. ",
      "2": "Exhorto a Euodia, y exhorto a Syntyche, a que piensen de la misma manera en el Señor.",
      "3": "Sí, te ruego también a ti, compañero verdadero, que ayudes a estas mujeres, pues ellas trabajaron conmigo en la Buena Nueva, con Clemente también, y con los demás colaboradores míos, cuyos nombres están en el libro de la vida. ",
      "4": "¡Alégrense siempre en el Señor! De nuevo diré: “¡Alégrense!”",
      "5": "Que tu mansedumbre sea conocida por todos los hombres. El Señor está cerca.",
      "6": "En nada os afanéis, sino que en todo, mediante la oración y la petición con acción de gracias, presentad vuestras peticiones a Dios.",
      "7": "Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús. ",
      "8": "Por último, hermanos, todo lo que es verdadero, todo lo que es honorable, todo lo que es justo, todo lo que es puro, todo lo que es hermoso, todo lo que es de buena reputación: si hay alguna virtud y si hay algo digno de alabanza, pensad en estas cosas.",
      "9": "Haced lo que habéis aprendido, recibido, oído y visto en mí, y el Dios de la paz estará con vosotros. ",
      "10": "Pero me regocijo mucho en el Señor de que ahora, por fin, hayas revivido tu pensamiento por mí, en el que sí pensabas, pero te faltaba la oportunidad.",
      "11": "No es que hable por falta, pues he aprendido a contentarme en cualquier estado en que me encuentre.",
      "12": "Sé cómo ser humilde, y también sé cómo abundar. En todas y cada una de las circunstancias he aprendido el secreto tanto de estar saciado como de tener hambre, tanto de abundar como de estar necesitado.",
      "13": "Todo lo puedo en Cristo, que me fortalece.",
      "14": "Sin embargo, habéis hecho bien en participar en mi aflicción.",
      "15": "Vosotros mismos sabéis también, filipenses, que al principio de la Buena Nueva, cuando partí de Macedonia, ninguna asamblea compartía conmigo el dar y el recibir, sino sólo vosotros.",
      "16": "Pues incluso en Tesalónica enviasteis una y otra vez a mi necesidad.",
      "17": "No es que busque el don, sino que busco el fruto que aumenta a vuestra cuenta.",
      "18": "Pero yo lo tengo todo y me sobra. Estoy lleno, habiendo recibido de Epafrodito las cosas que vinieron de ti, una fragancia agradable, un sacrificio aceptable y agradable a Dios.",
      "19": "Mi Dios suplirá toda necesidad tuya según sus riquezas de gloria en Cristo Jesús.",
      "20": "Al Dios y Padre nuestro sea la gloria por los siglos de los siglos. Amén. ",
      "21": "Saludad a todos los santos en Cristo Jesús. Los hermanos que están conmigo os saludan.",
      "22": "Os saludan todos los santos, especialmente los de la casa del César. ",
      "23": "La gracia del Señor Jesucristo esté con todos vosotros. Amén."
    }
  },
  "colossians": {
    "1": {
      "1": "Pablo, apóstol de Cristo Jesús por la voluntad de Dios, y Timoteo nuestro hermano,",
      "2": "a los santos y fieles hermanos en Cristo de Colosas: Gracia a vosotros y paz de parte de Dios nuestro Padre y del Señor Jesucristo. ",
      "3": "Damos gracias a Dios Padre de nuestro Señor Jesucristo, orando siempre por vosotros,",
      "4": "habiendo oído de vuestra fe en Cristo Jesús y del amor que tenéis hacia todos los santos,",
      "5": "a causa de la esperanza que os está reservada en los cielos, de la cual habéis oído antes en la palabra de la verdad de la Buena Nueva",
      "6": "que os ha llegado, así como está en todo el mundo y da fruto y crece, como lo hace también en vosotros, desde el día en que oísteis y conocisteis la gracia de Dios en la verdad,",
      "7": "así como lo aprendisteis de Epafras, nuestro amado consiervo, que es un fiel servidor de Cristo en favor vuestro,",
      "8": "que también nos declaró vuestro amor en el Espíritu. ",
      "9": "Por esta razón, nosotros también, desde el día en que oímos esto, no cesamos de orar y de pedir por vosotros, para que seáis llenos del conocimiento de su voluntad en toda sabiduría e inteligencia espirituales,",
      "10": "a fin de que andéis dignamente del Señor, para agradarle en todo, llevando fruto en toda buena obra y creciendo en el conocimiento de Dios,",
      "11": "fortalecidos con todo poder según el poder de su gloria, para toda resistencia y perseverancia con alegría,",
      "12": "dando gracias al Padre, que nos hizo aptos para ser partícipes de la herencia de los santos en la luz,",
      "13": "que nos libró del poder de las tinieblas y nos trasladó al Reino del Hijo de su amor,",
      "14": "en quien tenemos nuestra redención, el perdón de nuestros pecados. ",
      "15": "Él es la imagen del Dios invisible, el primogénito de toda la creación.",
      "16": "Porque por él fueron creadas todas las cosas en los cielos y en la tierra, las visibles y las invisibles, sean tronos, sean dominios, sean principados, sean potestades. Todo ha sido creado por medio de él y para él.",
      "17": "Él es antes de todas las cosas, y en él se mantienen todas las cosas.",
      "18": "Él es la cabeza del cuerpo, la asamblea, que es el principio, el primogénito de entre los muertos, para que en todo tenga la preeminencia.",
      "19": "Porque toda la plenitud se complació en habitar en él,",
      "20": "y por medio de él reconciliar consigo todas las cosas, tanto las que están en la tierra como las que están en los cielos, haciendo la paz mediante la sangre de su cruz. ",
      "21": "Vosotros, que en tiempos pasados estabais enajenados y erais enemigos en vuestra mente por vuestras malas acciones,",
      "22": "sin embargo, ahora os ha reconciliado en el cuerpo de su carne por medio de la muerte, para presentaros santos y sin defecto e irreprochables ante él,",
      "23": "si es que permanecéis en la fe, cimentados y firmes, y no os apartáis de la esperanza de la Buena Nueva que habéis oído, que se proclama en toda la creación bajo el cielo, de la cual yo, Pablo, fui hecho servidor. ",
      "24": "Ahora me regocijo en mis padecimientos por causa de ustedes, y lleno por mi parte lo que falta de las aflicciones de Cristo en mi carne por causa de su cuerpo, que es la asamblea,",
      "25": "de la cual fui hecho siervo según la administración de Dios que me fue dada para con ustedes para cumplir la palabra de Dios,",
      "26": "el misterio que ha estado oculto por siglos y generaciones. Pero ahora ha sido revelado a sus santos,",
      "27": "a quienes Dios quiso dar a conocer cuáles son las riquezas de la gloria de este misterio entre los gentiles, que es Cristo en vosotros, la esperanza de la gloria.",
      "28": "Nosotros lo anunciamos, amonestando a todo hombre y enseñando a todo hombre con toda sabiduría, a fin de presentar a todo hombre perfecto en Cristo Jesús;",
      "29": "para lo cual también trabajo, esforzándome según su obra, que actúa poderosamente en mí."
    },
    "2": {
      "1": "Porque quiero que sepáis lo mucho que lucho por vosotros y por los de Laodicea, y por todos los que no han visto mi rostro en la carne;",
      "2": "para que sus corazones sean consolados, estando unidos en el amor, y obteniendo todas las riquezas de la plena seguridad del entendimiento, a fin de que conozcan el misterio de Dios, tanto del Padre como de Cristo,",
      "3": "en quien están escondidos todos los tesoros de la sabiduría y del conocimiento.",
      "4": "Ahora bien, digo esto para que nadie os engañe con la persuasión de las palabras.",
      "5": "Porque aunque estoy ausente en la carne, estoy con vosotros en el espíritu, alegrándome y viendo vuestro orden y la firmeza de vuestra fe en Cristo. ",
      "6": "Así pues, de la misma manera que recibisteis a Cristo Jesús, el Señor, andad en él,",
      "7": "arraigados y edificados en él, y confirmados en la fe, tal como habéis sido enseñados, abundando en ella con acción de gracias. ",
      "8": "Tened cuidado de no dejar que nadie os robe con su filosofía y vano engaño, según la tradición de los hombres, según los espíritus elementales del mundo, y no según Cristo.",
      "9": "Porque en él habita corporalmente toda la plenitud de la Deidad,",
      "10": "y en él sois hechos plenos, que es la cabeza de todo principado y potestad.",
      "11": "En él también fuisteis circuncidados con una circuncisión no hecha de mano, despojándoos del cuerpo de los pecados de la carne, en la circuncisión de Cristo,",
      "12": "habiendo sido sepultados con él en el bautismo, en el cual también fuisteis resucitados con él mediante la fe en la acción de Dios, que lo resucitó de entre los muertos.",
      "13": "Vosotros estabais muertos por vuestros delitos y por la incircuncisión de vuestra carne. Él os dio vida junto con él, habiéndonos perdonado todos nuestros delitos,",
      "14": "borrando la letra de las ordenanzas que había contra nosotros. La ha quitado de en medio, clavándola en la cruz.",
      "15": "Habiendo despojado a los principados y a las potestades, los exhibió abiertamente, triunfando sobre ellos en ella. ",
      "16": "Nadie, pues, os juzgue en el comer o en el beber, o en cuanto a la fiesta, la luna nueva o el día de reposo,",
      "17": "que son sombra de lo que ha de venir; pero el cuerpo es de Cristo.",
      "18": "Que nadie os despoje de vuestro premio humillándose a sí mismo y adorando a los ángeles, deteniéndose en lo que no ha visto, envanecido por su mente carnal,",
      "19": "y sin aferrarse firmemente a la Cabeza, de la cual todo el cuerpo, abastecido y unido por las coyunturas y ligamentos, crece con el crecimiento de Dios. ",
      "20": "Si habéis muerto con Cristo de los espíritus elementales del mundo, ¿por qué, como si vivierais en el mundo, os sometéis a las ordenanzas,",
      "21": "“No manéeis, ni gustéis, ni toquéis”",
      "22": "(todo lo cual perece con el uso), según los preceptos y doctrinas de los hombres?",
      "23": "Estas cosas, en efecto, parecen sabiduría en el culto autoimpuesto, en la humildad y en la severidad hacia el cuerpo, pero no tienen ningún valor contra la complacencia de la carne."
    },
    "3": {
      "1": "Si, pues, habéis resucitado con Cristo, buscad las cosas de arriba, donde está Cristo sentado a la derecha de Dios.",
      "2": "Poned la mira en las cosas de arriba, no en las de la tierra.",
      "3": "Porque habéis muerto, y vuestra vida está escondida con Cristo en Dios.",
      "4": "Cuando Cristo, nuestra vida, se manifieste, entonces también vosotros os manifestaréis con él en la gloria. ",
      "5": "Haced morir, pues, vuestros miembros que están en la tierra: la inmoralidad sexual, la impureza, la pasión depravada, el mal deseo y la codicia, que es idolatría.",
      "6": "Por estas cosas viene la ira de Dios sobre los hijos de la desobediencia.",
      "7": "En otro tiempo también anduvisteis en ellas, cuando vivíais en ellas,",
      "8": "pero ahora debéis desecharlas todas: la ira, el enojo, la malicia, la calumnia y el hablar vergonzoso de vuestra boca.",
      "9": "No os mintáis los unos a los otros, ya que os habéis despojado del viejo hombre con sus obras,",
      "10": "y os habéis revestido del nuevo hombre, que se renueva en el conocimiento según la imagen de su Creador,",
      "11": "donde no puede haber griego y judío, circuncisión e incircuncisión, bárbaro, escita, siervo o libre, sino que Cristo es todo y en todos. ",
      "12": "Revístanse, pues, como elegidos de Dios, santos y amados, de un corazón compasivo, bondadoso, humilde y perseverante;",
      "13": "soportándose los unos a los otros y perdonándose mutuamente, si alguno tiene queja contra alguno; como Cristo os perdonó, así también hacedlo vosotros. ",
      "14": "Sobre todas estas cosas, andad en amor, que es el vínculo de la perfección.",
      "15": "Y que la paz de Dios reine en vuestros corazones, a la que también fuisteis llamados en un solo cuerpo, y sed agradecidos.",
      "16": "Que la palabra de Cristo habite abundantemente en vosotros, enseñándoos y amonestándoos unos a otros con sabiduría, con salmos, himnos y cánticos espirituales, cantando con gracia en vuestro corazón al Señor. ",
      "17": "Todo lo que hagáis, de palabra o de obra, hacedlo en nombre del Señor Jesús, dando gracias a Dios Padre por medio de él. ",
      "18": "Esposas, estad sujetas a vuestros maridos, como conviene en el Señor. ",
      "19": "Maridos, amad a vuestras mujeres y no os amargueis con ellas. ",
      "20": "Hijos, obedezcan a sus padres en todo, porque esto agrada al Señor. ",
      "21": "Padres, no provoquéis a vuestros hijos, para que no se desanimen. ",
      "22": "Siervos, obedeced en todo a los que son vuestros amos según la carne, no sólo cuando miran, como los que agradan a los hombres, sino con sencillez de corazón, temiendo a Dios.",
      "23": "Y todo lo que hagáis, trabajad de corazón, como para el Señor y no para los hombres,",
      "24": "sabiendo que del Señor recibiréis la recompensa de la herencia, pues servís al Señor Cristo.",
      "25": "Pero el que hace el mal, recibirá de nuevo el mal que ha hecho, y no hay parcialidad."
    },
    "4": {
      "1": "Amos, dad a vuestros siervos lo que es justo y equitativo, sabiendo que también vosotros tenéis un amo en el cielo. ",
      "2": "Perseverad en la oración, velando en ella con acción de gracias,",
      "3": "orando juntos también por nosotros, para que Dios nos abra una puerta para la palabra, para hablar del misterio de Cristo, por el que yo también estoy preso,",
      "4": "a fin de revelarlo como debo hablar. ",
      "5": "Camina con sabiduría hacia los que están fuera, redimiendo el tiempo.",
      "6": "Hablad siempre con gracia, sazonados con sal, para que sepáis cómo debéis responder a cada uno. ",
      "7": "Todos mis asuntos os serán dados a conocer por Tíquico, el hermano amado, siervo fiel y compañero de fatigas en el Señor.",
      "8": "Lo envío a vosotros con este mismo propósito, para que conozca vuestras circunstancias y consuele vuestros corazones,",
      "9": "junto con Onésimo, el hermano fiel y amado, que es uno de vosotros. Ellos os darán a conocer todo lo que ocurre aquí. ",
      "10": "Os saludan Aristarco, mi compañero de prisión, y Marcos, el primo de Bernabé (sobre el que recibisteis instrucciones: “si viene a vosotros, recibidlo”),",
      "11": "y Jesús, que se llama Justo. Estos son mis únicos compañeros de trabajo por el Reino de Dios que son de la circuncisión, hombres que han sido un consuelo para mí. ",
      "12": "Os saluda Epafras, que es uno de vosotros, siervo de Cristo, procurando siempre por vosotros en sus oraciones, para que estéis perfectos y completos en toda la voluntad de Dios.",
      "13": "Porque doy testimonio de él de que tiene gran celo por vosotros, por los de Laodicea y por los de Hierápolis.",
      "14": "Os saludan Lucas, el médico amado, y Demas.",
      "15": "Saludad a los hermanos que están en Laodicea, con Ninfas y la asamblea que está en su casa.",
      "16": "Cuando se haya leído esta carta entre vosotros, haced que se lea también en la asamblea de los laodicenses, y que leáis también la carta de Laodicea.",
      "17": "Dile a Arquipo: “Cuida el ministerio que has recibido en el Señor, para que lo cumplas”. ",
      "18": "Yo, Pablo, escribo este saludo con mi propia mano. Recordad mis cadenas. Que la gracia esté con vosotros. Amén."
    }
  },
  "1_thessalonians": {
    "1": {
      "1": "Pablo, Silvano y Timoteo, a la asamblea de los tesalonicenses en Dios Padre y en el Señor Jesucristo: Gracia a vosotros y paz de parte de Dios nuestro Padre y del Señor Jesucristo. ",
      "2": "Damos siempre gracias a Dios por todos vosotros, mencionándoos en nuestras oraciones,",
      "3": "recordando sin cesar vuestra obra de fe y trabajo de amor y perseverancia de esperanza en nuestro Señor Jesucristo, ante nuestro Dios y Padre.",
      "4": "Sabemos, hermanos amados por Dios, que sois unos elegidos,",
      "5": "y que nuestra Buena Noticia os llegó no sólo de palabra, sino también con poder, y con el Espíritu Santo y con mucha seguridad. Sabéis qué clase de hombres nos mostramos entre vosotros por vuestro bien.",
      "6": "Os convertisteis en imitadores de nosotros y del Señor, habiendo recibido la palabra en medio de mucha aflicción, con alegría del Espíritu Santo,",
      "7": "de modo que llegasteis a ser un ejemplo para todos los que creen en Macedonia y en Acaya.",
      "8": "Porque de vosotros se ha proclamado la palabra del Señor, no sólo en Macedonia y Acaya, sino también en todos los lugares donde ha salido vuestra fe hacia Dios, de modo que no tenemos necesidad de decir nada.",
      "9": "Porque ellos mismos informan acerca de nosotros de la acogida que hemos tenido por parte de vosotros, y de cómo os habéis convertido de los ídolos a Dios para servir a un Dios vivo y verdadero,",
      "10": "y para esperar a su Hijo del cielo, al que ha resucitado de entre los muertos: Jesús, que nos libra de la ira venidera."
    },
    "2": {
      "1": "Porque vosotros mismos sabéis, hermanos, que nuestra visita a vosotros no fue en vano,",
      "2": "sino que, habiendo sufrido antes y siendo tratados vergonzosamente, como sabéis, en Filipos, nos envalentonamos en nuestro Dios para anunciaros la Buena Nueva de Dios en medio de muchos conflictos.",
      "3": "Porque nuestra exhortación no es por error, ni por inmundicia, ni por engaño.",
      "4": "Sino que, como hemos sido aprobados por Dios para que se nos confíe la Buena Nueva, así hablamos, no como para complacer a los hombres, sino a Dios, que prueba nuestros corazones.",
      "5": "Porque en ningún momento se nos encontró usando palabras de adulación, como sabéis, ni un manto de codicia (Dios es testigo),",
      "6": "ni buscando la gloria de los hombres (ni de vosotros ni de otros), cuando podríamos haber reclamado la autoridad como apóstoles de Cristo.",
      "7": "Pero fuimos amables con vosotros, como una madre que amamanta a sus hijos. ",
      "8": "Así, pues, anhelando afectuosamente de vosotros, nos agradó comunicaros no sólo la Buena Nueva de Dios, sino también nuestras propias almas, porque os habías hecho muy queridos para nosotros.",
      "9": "Porque os acordáis, hermanos, de nuestros trabajos y fatigas; pues trabajando de noche y de día, para no ser una carga para ninguno de vosotros, os hemos predicado la Buena Nueva de Dios.",
      "10": "Vosotros sois testigos ante Dios de lo santa, justa e irreprochablemente que nos comportamos con vosotros los creyentes.",
      "11": "Como sabéis, os exhortamos, consolamos e imploramos a cada uno de vosotros, como lo hace un padre con sus propios hijos,",
      "12": "con el fin de que caminéis dignamente de Dios, que os llama a su Reino y a su gloria. ",
      "13": "Por eso también damos gracias a Dios sin cesar, porque cuando recibisteis de nosotros la palabra del mensaje de Dios, la aceptasteis no como palabra de hombres, sino como es en verdad, la palabra de Dios, que también obra en vosotros los que creéis.",
      "14": "Porque vosotros, hermanos, os hicisteis imitadores de las asambleas de Dios que están en Judea en Cristo Jesús; pues también sufristeis de vuestros propios compatriotas lo mismo que ellos de los judíos",
      "15": "que mataron tanto al Señor Jesús como a sus propios profetas, y nos expulsaron, y no agradan a Dios, y son contrarios a todos los hombres,",
      "16": "prohibiéndonos hablar a los gentiles para que se salven, para colmar siempre sus pecados. Pero la ira ha venido sobre ellos hasta el extremo. ",
      "17": "Pero nosotros, hermanos, estando despojados de ti por un corto tiempo en presencia, no en corazón, nos esforzamos aún más por ver tu rostro con gran deseo,",
      "18": "porque queríamos ir a ti — de hecho, yo, Pablo, una y otra vez —, pero Satanás nos lo impidió.",
      "19": "Pues, ¿cuál es nuestra esperanza, o alegría, o corona de regocijo? ¿No eres tú, ante nuestro Señor Jesús en su venida?",
      "20": "Porque tú eres nuestra gloria y nuestra alegría."
    },
    "3": {
      "1": "Por eso, cuando ya no pudimos aguantar más, nos pareció bien quedarnos solos en Atenas,",
      "2": "y enviamos a Timoteo, nuestro hermano y siervo de Dios en la Buena Nueva de Cristo, para que os afirmara y os consolara en cuanto a vuestra fe,",
      "3": "a fin de que nadie se conmoviera por estas aflicciones. Porque sabéis que hemos sido designados para esta tarea.",
      "4": "Porque ciertamente, cuando estábamos con vosotros, os dijimos de antemano que íbamos a sufrir aflicción, tal como sucedió, y lo sabéis.",
      "5": "Por esta razón, yo también, cuando ya no podía soportar más, envié para conocer vuestra fe, por temor a que por cualquier medio el tentador os hubiera tentado, y nuestro trabajo hubiera sido en vano. ",
      "6": "Pero Timoteo acaba de llegar a nosotros de parte de ustedes, y nos ha traído la alegre noticia de su fe y de su amor, y de que tienen siempre un buen recuerdo de nosotros, anhelando vernos, así como nosotros también anhelamos verlos.",
      "7": "Por esta razón, hermanos, fuimos consolados por vosotros en toda nuestra angustia y aflicción por vuestra fe.",
      "8": "Porque ahora vivimos, si permanecéis firmes en el Señor.",
      "9": "¿Qué acción de gracias podemos volver a dar a Dios por vosotros, por todo el gozo con que nos alegramos por vosotros delante de nuestro Dios,",
      "10": "orando de noche y de día con exceso para poder ver vuestro rostro y perfeccionar lo que falta a vuestra fe? ",
      "11": "Que nuestro Dios y Padre mismo, y nuestro Señor Jesucristo, dirijan nuestro camino hacia vosotros.",
      "12": "Que el Señor os haga crecer y abundar en el amor entre vosotros y con todos los hombres, como también nosotros lo hacemos con vosotros,",
      "13": "para que establezca vuestros corazones irreprochables en santidad ante nuestro Dios y Padre en la venida de nuestro Señor Jesús con todos sus santos."
    },
    "4": {
      "1": "Por último, hermanos, os rogamos y exhortamos en el Señor Jesús, que así como habéis recibido de nosotros cómo debéis andar y agradar a Dios, abundéis más y más.",
      "2": "Porque ya sabéis qué instrucciones os hemos dado por medio del Señor Jesús.",
      "3": "Porque esta es la voluntad de Dios: vuestra santificación, que os abstengáis de la inmoralidad sexual,",
      "4": "que cada uno de vosotros sepa dominar su propio cuerpo en santificación y honor,",
      "5": "no en la pasión de la lujuria, como los gentiles que no conocen a Dios,",
      "6": "que nadie se aproveche ni agravie a un hermano o hermana en este asunto; porque el Señor es vengador en todas estas cosas, como también os lo advertimos y testificamos.",
      "7": "Porque Dios no nos llamó para la impureza, sino para la santificación.",
      "8": "Por tanto, el que rechaza esto no rechaza al hombre, sino a Dios, que también os ha dado su Espíritu Santo. ",
      "9": "Pero en cuanto al amor fraternal, no tenéis necesidad de que se os escriba. Porque vosotros mismos habéis sido enseñados por Dios a amaros los unos a los otros,",
      "10": "pues de hecho lo hacéis con todos los hermanos que hay en toda Macedonia. Pero os exhortamos, hermanos, a que abundéis cada vez más;",
      "11": "y a que os propongáis llevar una vida tranquila, ocupándoos de vuestros propios asuntos y trabajando con vuestras propias manos, tal como os hemos instruido,",
      "12": "para que os conduzcáis debidamente con los que están fuera y no tengáis necesidad de nada. ",
      "13": "Pero no queremos que ignoréis, hermanos, lo de los que han dormido, para que no os entristezcáis como los demás, que no tienen esperanza.",
      "14": "Porque si creemos que Jesús murió y resucitó, también Dios traerá consigo a los que durmieron en Jesús.",
      "15": "Porque esto os decimos por la palabra del Señor: que nosotros, los que vivimos, los que quedamos hasta la venida del Señor, no precederemos en modo alguno a los que han dormido.",
      "16": "Porque el Señor mismo descenderá del cielo con un grito, con la voz del arcángel y con la trompeta de Dios. Los muertos en Cristo resucitarán primero,",
      "17": "y luego nosotros, los que quedemos vivos, seremos arrebatados con ellos en las nubes para recibir al Señor en el aire. Así estaremos con el Señor para siempre.",
      "18": "Por eso, consuélense unos a otros con estas palabras."
    },
    "5": {
      "1": "Pero en cuanto a los tiempos y las estaciones, hermanos, no tenéis necesidad de que se os escriba nada.",
      "2": "Porque vosotros mismos sabéis bien que el día del Señor viene como un ladrón en la noche.",
      "3": "Porque cuando digan: “Paz y seguridad”, entonces vendrá sobre ellos una destrucción repentina, como los dolores de parto de una mujer embarazada. Entonces no podrán escapar de ninguna manera.",
      "4": "Pero vosotros, hermanos, no estáis en las tinieblas, para que el día os sorprenda como un ladrón.",
      "5": "Todos vosotros sois hijos de la luz e hijos del día. No pertenecemos a la noche ni a las tinieblas,",
      "6": "así que no durmamos, como los demás, sino velemos y seamos sobrios.",
      "7": "Porque los que duermen, duermen de noche; y los que se emborrachan, se emborrachan de noche.",
      "8": "Pero ya que pertenecemos al día, seamos sobrios, poniéndonos la coraza de la fe y del amor, y por yelmo, la esperanza de la salvación.",
      "9": "Porque Dios no nos destinó a la ira, sino a la obtención de la salvación por medio de nuestro Señor Jesucristo,",
      "10": "quien murió por nosotros, para que, ya sea que estemos despiertos o durmiendo, vivamos junto con él.",
      "11": "Exhortaos, pues, unos a otros, y edificaos mutuamente, como también vosotros. ",
      "12": "Pero os rogamos, hermanos, que conozcáis a los que trabajan entre vosotros y os presiden en el Señor y os amonestan,",
      "13": "y que los respetéis y honréis con amor por su trabajo. Estad en paz entre vosotros.",
      "14": "Os exhortamos, hermanos: Amonestad a los desordenados; animad a los pusilánimes; apoyad a los débiles; sed pacientes con todos.",
      "15": "Procurad que nadie devuelva a nadie mal por mal, sino que sigáis siempre lo que es bueno para los unos y para los otros. ",
      "16": "Alégrate siempre.",
      "17": "Orad sin cesar.",
      "18": "Dad gracias en todo, porque ésta es la voluntad de Dios para con vosotros en Cristo Jesús.",
      "19": "No apaguen el Espíritu.",
      "20": "No despreciéis las profecías.",
      "21": "Probad todas las cosas y retened firmemente lo que es bueno.",
      "22": "Absteneos de toda forma de maldad. ",
      "23": "Que el mismo Dios de la paz te santifique por completo. Que todo tu espíritu, tu alma y tu cuerpo se conserven irreprochables en la venida de nuestro Señor Jesucristo. ",
      "24": "Es fiel el que os llama, que también lo hará. ",
      "25": "Hermanos, rezad por nosotros. ",
      "26": "Saluda a todos los hermanos con un beso santo.",
      "27": "Te ordeno solemnemente por el Señor que esta carta sea leída a todos los santos hermanos. ",
      "28": "La gracia de nuestro Señor Jesucristo esté con vosotros. Amén."
    }
  },
  "2_thessalonians": {
    "1": {
      "1": "Pablo, Silvano y Timoteo, a la asamblea de los tesalonicenses en Dios nuestro Padre y en el Señor Jesucristo:",
      "2": "Gracia a vosotros y paz de parte de Dios nuestro Padre y del Señor Jesucristo. ",
      "3": "Estamos obligados a dar siempre gracias a Dios por vosotros, hermanos, como corresponde, porque vuestra fe crece en extremo, y el amor de todos y cada uno de vosotros entre sí abunda,",
      "4": "de modo que nosotros mismos nos gloriamos de vosotros en las asambleas de Dios por vuestra perseverancia y fe en todas vuestras persecuciones y en las aflicciones que soportáis.",
      "5": "Esto es una señal evidente del justo juicio de Dios, a fin de que seáis tenidos por dignos del Reino de Dios, por el cual también sufrís.",
      "6": "Porque es cosa justa para Dios devolver la aflicción a los que os afligen,",
      "7": "y daros alivio a vosotros, que estáis afligidos con nosotros, cuando el Señor Jesús se manifieste desde el cielo con sus poderosos ángeles en fuego ardiente,",
      "8": "castigando a los que no conocen a Dios, y a los que no obedecen la Buena Nueva de nuestro Señor Jesús,",
      "9": "que pagará la la destrucción eterna de la faz del Señor y de la gloria de su poderío,",
      "10": "cuando venga en aquel día para ser glorificado en sus santos y para ser admirado entre todos los que han creído, porque nuestro testimonio de vosotros fue creído. ",
      "11": "Con este fin también rogamos siempre por vosotros, para que nuestro Dios os tenga por dignos de vuestra vocación, y cumpla con fuerza todo deseo de bondad y toda obra de fe,",
      "12": "para que el nombre de nuestro Señor Jesús sea glorificado en vosotros, y vosotros en él, según la gracia de nuestro Dios y del Señor Jesucristo."
    }
  }
};

