
	
export const bib_verses = {
  "genesis": {
    "34": {
      "1": "Dina, la hija de Lea, que dio a luz a Jacob, salió a ver a las hijas de la tierra.",
      "2": "La vio Siquem, hijo de Hamor el heveo, príncipe de la tierra. La tomó, se acostó con ella y la humilló.",
      "3": "Su alma se unió a Dina, la hija de Jacob, y amó a la joven, y le habló con cariño.",
      "4": "Siquem habló con su padre, Hamor, diciendo: “Consígueme a esta joven como esposa”. ",
      "5": "Jacob se enteró de que había mancillado a su hija Dina, y sus hijos estaban con su ganado en el campo. Jacob calló hasta que llegaron.",
      "6": "Hamor, el padre de Siquem, salió a buscar a Jacob para hablar con él.",
      "7": "Los hijos de Jacob vinieron del campo cuando lo oyeron. Los hombres se entristecieron y se enojaron mucho, porque él había hecho una locura en Israel al acostarse con la hija de Jacob, cosa que no debía hacerse.",
      "8": "Hamor habló con ellos, diciendo: “El alma de mi hijo Siquem anhela a su hija. Por favor, dénsela como esposa.",
      "9": "Hagan matrimonios con nosotros. Dennos sus hijas y tomen las nuestras para ustedes.",
      "10": "Viviréis con nosotros, y la tierra estará ante vosotros. Vivan y comercien en ella, y obtengan posesiones en ella”. ",
      "11": "Siquem dijo a su padre y a sus hermanos: “Dejadme encontrar el favor de vuestros ojos, y todo lo que me digáis os lo daré.",
      "12": "Pedidme una gran cantidad como dote, y os daré lo que me pidáis, pero dadme a la joven como esposa”. ",
      "13": "Los hijos de Jacob respondieron a Siquem y a su padre Hamor con engaño cuando hablaron, porque había mancillado a Dina, su hermana,",
      "14": "y les dijeron: “No podemos hacer esto, entregar a nuestra hermana a un incircunciso; porque eso es un reproche para nosotros.",
      "15": "Sólo con esta condición os consentiremos. Si sois como nosotros, que todo varón de vosotros sea circuncidado,",
      "16": "entonces os daremos nuestras hijas; y tomaremos vuestras hijas para nosotros, y moraremos con vosotros, y seremos un solo pueblo.",
      "17": "Pero si no nos escucháis y os circuncidáis, entonces tomaremos a nuestra hermana,  y nos iremos”. ",
      "18": "Sus palabras agradaron a Hamor y a Siquem, hijo de Hamor.",
      "19": "El joven no esperó para hacer esto, porque se había deleitado en la hija de Jacob, y fue honrado sobre toda la casa de su padre.",
      "20": "Hamor y Siquem, su hijo, llegaron a la puerta de su ciudad, y hablaron con los hombres de su ciudad, diciendo:",
      "21": "“Estos hombres son pacíficos con nosotros. Por lo tanto, déjenlos vivir en la tierra y comerciar en ella. Porque he aquí que la tierra es suficientemente grande para ellos. Tomemos a sus hijas para nosotros como esposas, y démosles nuestras hijas.",
      "22": "Sólo con esta condición los hombres consentirán en vivir con nosotros, para ser un solo pueblo, si todo varón de entre nosotros se circuncida, como ellos se circuncidan.",
      "23": "¿No será nuestro su ganado y sus posesiones y todos sus animales? Sólo démosles nuestro consentimiento, y ellos habitarán con nosotros”. ",
      "24": "Todos los que salían de la puerta de su ciudad escuchaban a Jamor y a su hijo Siquem, y todo varón era circuncidado, todos los que salían de la puerta de su ciudad.",
      "25": "Al tercer día, cuando ya estaban adoloridos, dos de los hijos de Jacob, Simeón y Leví, hermanos de Dina, tomaron cada uno su espada, vinieron a la ciudad desprevenida y mataron a todos los varones.",
      "26": "Mataron a Hamor y a Siquem, su hijo, a filo de espada, y sacaron a Dina de la casa de Siquem y se fueron.",
      "27": "Los hijos de Jacob vinieron sobre los muertos y saquearon la ciudad, porque habían profanado a su hermana.",
      "28": "Tomaron sus rebaños, sus vacas, sus asnos, lo que había en la ciudad, lo que había en el campo,",
      "29": "y toda su riqueza. Llevaron cautivos a todos sus pequeños y a sus mujeres, y tomaron como botín todo lo que había en la casa.",
      "30": "Jacob dijo a Simeón y a Leví: “Me habéis turbado para hacerme odioso a los habitantes del país, entre los cananeos y los ferezeos. Soy poco numeroso. Se reunirán contra mí y me golpearán, y seré destruido, yo y mi casa”. ",
      "31": "Dijeron: “¿Debe tratar a nuestra hermana como a una prostituta?”"
    },
    "35": {
      "1": "Dios dijo a Jacob: “Levántate, sube a Betel y vive allí. Haz allí un altar a Dios, que se te apareció cuando huías de la cara de tu hermano Esaú”. ",
      "2": "Entonces Jacob dijo a su familia y a todos los que estaban con él: “Quitad los dioses extranjeros que hay entre vosotros, purificaos y cambiad vuestros vestidos.",
      "3": "Levantémonos y subamos a Betel. Haré allí un altar a Dios, que me respondió en el día de mi angustia y estuvo conmigo en el camino que recorrí.” ",
      "4": "Entregaron a Jacob todos los dioses extranjeros que tenían en sus manos, y los anillos que tenían en sus orejas; y Jacob los escondió bajo la encina que estaba junto a Siquem.",
      "5": "Viajaron, y un terror de Dios estaba sobre las ciudades que estaban alrededor, y no persiguieron a los hijos de Jacob.",
      "6": "Entonces Jacob llegó a Luz (es decir, Betel), que está en la tierra de Canaán, él y todo el pueblo que estaba con él.",
      "7": "Edificó allí un altar y llamó al lugar El Betel, porque allí se le reveló Dios, cuando huía de la cara de su hermano.",
      "8": "Murió Débora, la nodriza de Rebeca, y fue enterrada debajo de Betel, bajo la encina; y su nombre fue llamado Allon Bacuth. ",
      "9": "Dios se le apareció de nuevo a Jacob, cuando venía de Paddán Aram, y lo bendijo.",
      "10": "Dios le dijo: “Tu nombre es Jacob. Ya no te llamarás Jacob, sino que te llamarás Israel”. Le puso el nombre de Israel.",
      "11": "Dios le dijo: “Yo soy el Dios Todopoderoso. Sé fecundo y multiplícate. De ti saldrá una nación y una compañía de naciones, y de tu cuerpo saldrán reyes.",
      "12": "La tierra que di a Abraham y a Isaac, te la daré a ti, y a tu descendencia después de ti le daré la tierra”. ",
      "13": "Dios se alejó de él en el lugar donde habló con él.",
      "14": "Jacob levantó una columna en el lugar donde habló con él, una columna de piedra. Derramó sobre ella una libación y derramó sobre ella aceite.",
      "15": "Jacob llamó “Betel” al lugar donde Dios habló con él. ",
      "16": "Viajaron desde Betel. Todavía faltaba una distancia para llegar a Efraín, y Raquel estaba de parto. Tuvo un duro parto.",
      "17": "Cuando estaba de parto, la partera le dijo: “No temas, porque ahora tendrás otro hijo.” ",
      "18": "Cuando su alma partió (pues murió), le puso el nombre de Benoni,  pero su padre le puso el nombre de Benjamín.  ",
      "19": "Raquel murió y fue enterrada en el camino de Efrata (también llamada Belén).",
      "20": "Jacob levantó una columna sobre su tumba. El mismo es el pilar de la tumba de Raquel hasta el día de hoy.",
      "21": "Israel viajó y extendió su tienda más allá de la torre de Eder.",
      "22": "Mientras Israel vivía en esa tierra, Rubén fue y se acostó con Bilhá, la concubina de su padre, e Israel se enteró. Los hijos de Jacob eran doce.",
      "23": "Los hijos de Lea: Rubén (primogénito de Jacob), Simeón, Leví, Judá, Isacar y Zabulón.",
      "24": "Los hijos de Raquel: José y Benjamín.",
      "25": "Los hijos de Bilhah (sierva de Raquel): Dan y Neftalí.",
      "26": "Los hijos de Zilpa (sierva de Lea): Gad y Aser. Estos son los hijos de Jacob, que le nacieron en Padan Aram.",
      "27": "Jacob vino a Isaac, su padre, a Mamre, a Quiriat Arba (que es Hebrón), donde Abraham e Isaac vivían como extranjeros. ",
      "28": "Los días de Isaac fueron ciento ochenta años.",
      "29": "Isaac entregó el espíritu y murió, y fue reunido con su pueblo, viejo y lleno de días. Esaú y Jacob, sus hijos, lo enterraron."
    },
    "36": {
      "1": "Esta es la historia de las generaciones de Esaú (es decir, Edom).",
      "2": "Esaú tomó sus esposas de las hijas de Canaán: Ada, hija de Elón, el hitita; y Oholibama, hija de Aná, hija de Zibeón, el heveo;",
      "3": "y Basemat, hija de Ismael, hermana de Nebaiot.",
      "4": "Ada dio a luz a Esaú, Elifaz. Basemat dio a luz a Reuel.",
      "5": "Oholibama dio a luz a Jeús, Jalam y Coré. Estos son los hijos de Esaú, que le nacieron en la tierra de Canaán.",
      "6": "Esaú tomó a sus esposas, a sus hijos, a sus hijas y a todos los miembros de su familia, con su ganado, todos sus animales y todas sus posesiones, que había reunido en la tierra de Canaán, y se fue a una tierra alejada de su hermano Jacob.",
      "7": "Porque su riqueza era demasiado grande para que pudieran habitar juntos, y la tierra de sus viajes no podía soportarlos a causa de su ganado.",
      "8": "Esaú vivió en la región montañosa de Seir. Esaú es Edom. ",
      "9": "Esta es la historia de las generaciones de Esaú, padre de los edomitas, en la región montañosa de Seír:",
      "10": "Estos son los nombres de los hijos de Esaú Elifaz, hijo de Ada, esposa de Esaú; y Reuel, hijo de Basemat, esposa de Esaú.",
      "11": "Los hijos de Elifaz fueron Temán, Omar, Zefo, Gatam y Cenaz.",
      "12": "Timna fue concubina de Elifaz, hijo de Esaú, y dio a luz a Amalec. Estos son los descendientes de Ada, esposa de Esaú.",
      "13": "Estos son los hijos de Reuel: Nahath, Zerah, Shammah y Mizzah. Estos fueron los descendientes de Basemat, esposa de Esaú.",
      "14": "Estos fueron los hijos de Oholibama, hija de Aná, hija de Zibeón, mujer de Esaú; ella dio a luz a Esaú: Jeús, Jalam y Coré. ",
      "15": "Estos son los jefes de los hijos de Esaú: los hijos de Elifaz, primogénito de Esaú: el jefe Temán, el jefe Omar, el jefe Zefo, el jefe Cenaz,",
      "16": "el jefe Coré, el jefe Gatam, el jefe Amalec. Estos son los jefes que vinieron de Elifaz en la tierra de Edom. Estos son los hijos de Ada.",
      "17": "Estos son los hijos de Reuel, hijo de Esaú: el jefe Nahat, el jefe Zerah, el jefe Shammah, el jefe Mizzah. Estos son los jefes que vinieron de Reuel en la tierra de Edom. Estos son los hijos de Basemat, mujer de Esaú.",
      "18": "Estos son los hijos de Oholibama, mujer de Esaú: el jefe Jeús, el jefe Jalam y el jefe Coré. Estos son los jefes que vinieron de Oholibama, hija de Aná, mujer de Esaú.",
      "19": "Estos son los hijos de Esaú (es decir, Edom), y estos son sus jefes. ",
      "20": "Estos son los hijos de Seir el horeo, los habitantes de la tierra: Lotán, Sobal, Zibeón, Aná,",
      "21": "Disón, Ezer y Disán. Estos son los jefes que vinieron de los horeos, los hijos de Seír en la tierra de Edom.",
      "22": "Los hijos de Lotán fueron Hori y Hemán. La hermana de Lotán fue Timna.",
      "23": "Estos son los hijos de Sobal: Alván, Manahat, Ebal, Safo y Onam.",
      "24": "Estos son los hijos de Zibeón Aiah y Anah. Este es Aná, que encontró las aguas termales en el desierto, mientras alimentaba a los asnos de Zibeón, su padre.",
      "25": "Estos son los hijos de Aná: Disón y Oholibama, hija de Aná.",
      "26": "Estos son los hijos de Disón: Hemdán, Eshbán, Itrán y Querán.",
      "27": "Estos son los hijos de Ezer Bilhán, Zaaván y Acán.",
      "28": "Estos son los hijos de Disán: Uz y Arán.",
      "29": "Estos son los jefes que vinieron de los horeos: el jefe Lotán, el jefe Sobal, el jefe Zibeón, el jefe Aná,",
      "30": "el jefe Disón, el jefe Ezer y el jefe Disán. Estos son los jefes que vinieron de los horeos, según sus jefes en la tierra de Seir. ",
      "31": "Estos son los reyes que reinaron en la tierra de Edom, antes de que ningún rey reinara sobre los hijos de Israel.",
      "32": "Bela, hijo de Beor, reinó en Edom. El nombre de su ciudad fue Dinhabah.",
      "33": "Bela murió, y en su lugar reinó Jobab, hijo de Zera de Bosra.",
      "34": "Murió Jobab, y en su lugar reinó Husam, del país de los temanitas.",
      "35": "Murió Husam, y reinó en su lugar Hadad, hijo de Bedad, que hirió a Madián en el campo de Moab. El nombre de su ciudad fue Avit.",
      "36": "Murió Hadad, y en su lugar reinó Samá de Masreca.",
      "37": "Murió Samá, y en su lugar reinó Saúl, de Rehobot, junto al río.",
      "38": "Murió Saúl, y en su lugar reinó Baal Hanán, hijo de Acbor.",
      "39": "Murió Baal Hanán, hijo de Acbor, y en su lugar reinó Hadar. El nombre de su ciudad fue Pau. Su esposa se llamaba Mehetabel, hija de Matred, hija de Mezahab. ",
      "40": "Estos son los nombres de los jefes que vinieron de Esaú, según sus familias, por sus lugares y por sus nombres: el jefe Timna, el jefe Alvah, el jefe Jetheth,",
      "41": "el jefe Oholibamah, el jefe Elah, el jefe Pinon,",
      "42": "el jefe Kenaz, el jefe Teman, el jefe Mibzar,",
      "43": "el jefe Magdiel y el jefe Iram. Estos son los jefes de Edom, según sus domicilios en la tierra de su posesión. Este es Esaú, el padre de los edomitas."
    },
    "37": {
      "1": "Jacob vivía en la tierra de los viajes de su padre, en la tierra de Canaán.",
      "2": "Esta es la historia de las generaciones de Jacob. José, teniendo diecisiete años, apacentaba el rebaño con sus hermanos. Era un muchacho con los hijos de Bilha y Zilpa, las esposas de su padre. José informó a su padre sobre su maldad.",
      "3": "Israel amaba a José más que a todos sus hijos, porque era el hijo de su vejez, y le hizo una túnica de muchos colores.",
      "4": "Sus hermanos vieron que su padre lo amaba más que a todos sus hermanos, y lo odiaron y no pudieron hablarle en paz. ",
      "5": "José soñó un sueño, y se lo contó a sus hermanos, y éstos lo odiaron aún más.",
      "6": "Les dijo: “Escuchad este sueño que he soñado:",
      "7": "porque he aquí que estábamos atando gavillas en el campo, y he aquí que mi gavilla se levantó y también se puso de pie; y he aquí que vuestras gavillas se acercaron y se inclinaron hacia mi gavilla.” ",
      "8": "Sus hermanos le preguntaron: “¿De verdad vas a reinar sobre nosotros? ¿Realmente tendrás dominio sobre nosotros?” Lo odiaban aún más por sus sueños y por sus palabras.",
      "9": "Soñó aún otro sueño y lo contó a sus hermanos, diciendo: “He aquí que he soñado otro sueño, y he aquí que el sol, la luna y once estrellas se inclinaban ante mí.”",
      "10": "Se lo contó a su padre y a sus hermanos. Su padre lo reprendió y le dijo: “¿Qué es este sueño que has soñado? ¿Acaso yo y tu madre y tus hermanos vendremos a postrarnos en la tierra ante ti?”",
      "11": "Sus hermanos le envidiaban, pero su padre tenía presente esta frase. ",
      "12": "Sus hermanos fueron a apacentar el rebaño de su padre en Siquem.",
      "13": "Israel dijo a José: “¿No están tus hermanos apacentando el rebaño en Siquem? Ven, y te enviaré con ellos”. Él le respondió: “Aquí estoy”. ",
      "14": "Le dijo: “Ve ahora a ver si les va bien a tus hermanos y al rebaño, y tráeme otra vez la noticia”. Y lo envió fuera del valle de Hebrón, y llegó a Siquem.",
      "15": "Cierto hombre lo encontró, y he aquí que estaba vagando por el campo. El hombre le preguntó: “¿Qué buscas?” ",
      "16": "Dijo: “Busco a mis hermanos. Dime, por favor, dónde están apacentando el rebaño”. ",
      "17": "El hombre dijo: “Se han ido de aquí, porque les he oído decir: “Vamos a Dotán””. José fue tras sus hermanos y los encontró en Dotán.",
      "18": "Lo vieron de lejos, y antes de que se acercara a ellos, conspiraron contra él para matarlo.",
      "19": "Se decían unos a otros: “He aquí que viene este soñador.",
      "20": "Venid, pues, y matémosle, y echémosle en uno de los pozos, y diremos: ‘Un animal malvado le ha devorado’. Veremos qué será de sus sueños”. ",
      "21": "Rubén lo oyó y lo libró de sus manos y dijo: “No le quitemos la vida”.",
      "22": "Rubén les dijo: “No derramen sangre. Arrojadlo a este pozo que está en el desierto, pero no le pongáis la mano encima”, para librarlo de sus manos y devolverlo a su padre.",
      "23": "Cuando José llegó a manos de sus hermanos, éstos le quitaron la túnica de muchos colores que llevaba puesta;",
      "24": "lo tomaron y lo arrojaron a la fosa. La fosa estaba vacía. No había agua en ella. ",
      "25": "Se sentaron a comer el pan, y levantaron los ojos y miraron, y vieron que una caravana de ismaelitas venía de Galaad, con sus camellos cargados de especias, bálsamo y mirra, que iban a llevar a Egipto.",
      "26": "Judá dijo a sus hermanos: “¿De qué nos sirve matar a nuestro hermano y ocultar su sangre?",
      "27": "Vengan y vendámoslo a los ismaelitas, y que nuestra mano no lo toque, porque es nuestro hermano, nuestra carne.” Sus hermanos le hicieron caso.",
      "28": "Pasaron unos madianitas que eran mercaderes, y sacaron y levantaron a José de la fosa, y vendieron a José a los ismaelitas por veinte monedas de plata. Los mercaderes llevaron a José a Egipto. ",
      "29": "Rubén volvió a la fosa y vio que José no estaba en ella, y se rasgó las vestiduras.",
      "30": "Volvió a sus hermanos y dijo: “El niño ya no está; y yo, ¿a dónde iré?”",
      "31": "Tomaron la túnica de José, mataron un macho cabrío y mojaron la túnica en la sangre.",
      "32": "Tomaron la túnica de muchos colores, la llevaron a su padre y le dijeron: “Hemos encontrado esto. Examínala ahora y comprueba si es la túnica de tu hijo o no”. ",
      "33": "Lo reconoció y dijo: “Es la túnica de mi hijo. Un animal malvado lo ha devorado. Sin duda, José está despedazado”.",
      "34": "Jacob se rasgó las vestiduras, se puso tela de saco en la cintura y lloró a su hijo durante muchos días.",
      "35": "Todos sus hijos y todas sus hijas se levantaron para consolarlo, pero él se negó a ser consolado. Dijo: “Porque bajaré al Seol  a mi hijo, de luto”. Su padre lloró por él.",
      "36": "Los madianitas lo vendieron a Egipto a Potifar, un oficial del Faraón, el capitán de la guardia."
    },
    "38": {
      "1": "En aquel tiempo, Judá bajó de entre sus hermanos y visitó a un adulamita que se llamaba Hira.",
      "2": "Allí, Judá vio a la hija de un cananeo llamado Súa. La tomó y se acercó a ella.",
      "3": "Ella concibió y dio a luz un hijo, al que llamó Er.",
      "4": "Concibió de nuevo y dio a luz un hijo, al que llamó Onán.",
      "5": "Concibió de nuevo y dio a luz un hijo, al que llamó Sela. Estaba en Chezib cuando lo dio a luz.",
      "6": "Judá tomó una esposa para Er, su primogénito, y su nombre fue Tamar.",
      "7": "Er, el primogénito de Judá, era malvado a los ojos de Yavé. Así que Yahvé lo mató.",
      "8": "Judá le dijo a Onán: “Acércate a la mujer de tu hermano y cumple con ella el deber de un marido hermano, y cría descendencia para tu hermano.”",
      "9": "Onán sabía que la descendencia no sería suya; y cuando entró a la mujer de su hermano, derramó su semen en el suelo, para no dar descendencia a su hermano.",
      "10": "Lo que hizo fue malo a los ojos de Yavé, y también lo mató.",
      "11": "Entonces Judá le dijo a Tamar, su nuera: “Quédate viuda en la casa de tu padre hasta que crezca Sela, mi hijo”, pues dijo: “No sea que él también muera como sus hermanos”. Tamar se fue a vivir a la casa de su padre. ",
      "12": "Después de muchos días, murió la hija de Súa, esposa de Judá. Judá se consoló y subió con sus esquiladores de ovejas a Timná, él y su amigo Hira, el adulamita.",
      "13": "Le dijeron a Tamar: “Mira, tu suegro sube a Timná a esquilar sus ovejas”.",
      "14": "Ella se quitó las prendas de su viudez, se cubrió con su velo y se envolvió, y se sentó en la puerta de Enaim, que está en el camino de Timná, porque vio que Selá era mayor, y que ella no le había sido dada como esposa.",
      "15": "Cuando Judá la vio, pensó que era una prostituta, pues se había cubierto el rostro.",
      "16": "Se dirigió a ella por el camino y le dijo: “Por favor, ven, déjame entrar contigo”, pues no sabía que era su nuera. Ella dijo: “¿Qué me darás, para que puedas entrar en mí?” ",
      "17": "Dijo: “Te enviaré un cabrito del rebaño”. Ella dijo: “¿Me darás una prenda, hasta que la envíes?” ",
      "18": "Él dijo: “¿Qué prenda te daré?” Ella dijo: “Tu sello y tu cordón, y tu bastón que está en tu mano”. Se los dio, y entró en ella, y ella concibió por él.",
      "19": "Ella se levantó y se fue, y se quitó el velo de encima y se puso las ropas de su viudez.",
      "20": "Judá envió al cabrito de la mano de su amigo, el adulamita, a recibir la prenda de la mano de la mujer, pero no la encontró.",
      "21": "Entonces preguntó a los hombres de su lugar, diciendo: “¿Dónde está la prostituta que estaba en Enaim, junto al camino?” Dijeron: “Aquí no ha habido ninguna prostituta”. ",
      "22": "Volvió a Judá y le dijo: “No la he encontrado; y también los hombres del lugar dijeron: “Aquí no ha habido ninguna prostituta””.",
      "23": "Judá dijo: “Que se quede con ella, no sea que nos avergoncemos. He aquí que he enviado esta cabrita, y no la has encontrado”. ",
      "24": "Unos tres meses después, se le dijo a Judá: “Tamar, tu nuera, se ha prostituido. Además, he aquí que está embarazada por prostitución”. Judá dijo: “Sácala y que la quemen”.",
      "25": "Cuando la sacaron, envió a decir a su suegro: “Estoy embarazada del hombre que tiene esto”. También le dijo: “Por favor, discierne de quién son estos: el sello, los cordones y el bastón”. ",
      "26": "Judá los reconoció y dijo: “Ella es más justa que yo, porque no se la di a Sela, mi hijo”. No volvió a conocerla.",
      "27": "En el tiempo de su parto, he aquí que había gemelos en su seno.",
      "28": "Cuando dio a luz, uno de ellos sacó una mano, y la partera tomó y ató un hilo de grana en su mano, diciendo: “Este salió primero.”",
      "29": "Al retirar la mano, he aquí que su hermano salió, y ella le dijo: “¿Por qué te has hecho una brecha?” Por eso se llamó Pérez.  ",
      "30": "Después salió su hermano, que tenía el hilo escarlata en la mano, y se llamó Zerah.  "
    },
    "39": {
      "1": "José fue llevado a Egipto. Potifar, un oficial del Faraón, el capitán de la guardia, un egipcio, lo compró de la mano de los ismaelitas que lo habían hecho descender.",
      "2": "El Señor estaba con José, y éste era un hombre próspero. Estaba en la casa de su amo el egipcio.",
      "3": "Su amo vio que Yavé estaba con él, y que Yavé hacía prosperar en su mano todo lo que hacía.",
      "4": "José halló gracia ante sus ojos. Le sirvió, y Potifar lo nombró supervisor de su casa, y todo lo que tenía lo puso en sus manos.",
      "5": "Desde el momento en que lo nombró supervisor de su casa y de todo lo que tenía, Yavé bendijo la casa del egipcio por causa de José. La bendición del Señor recayó sobre todo lo que tenía, en la casa y en el campo.",
      "6": "Dejó todo lo que tenía en manos de José. No se preocupó por nada, excepto por la comida que comía. José era bien parecido y guapo.",
      "7": "Después de esto, la mujer de su amo puso sus ojos en José y le dijo: “Acuéstate conmigo”. ",
      "8": "Pero él se negó y dijo a la mujer de su amo: “He aquí que mi amo no sabe lo que hay conmigo en la casa, y ha puesto en mi mano todo lo que tiene.",
      "9": "Nadie es mayor que yo en esta casa, y no me ha ocultado nada más que a ti, porque eres su mujer. ¿Cómo, pues, puedo hacer esta gran maldad, y pecar contra Dios?” ",
      "10": "Mientras ella le hablaba a José cada día, él no la escuchaba, ni se acostaba junto a ella, ni estaba con ella.",
      "11": "Por aquel entonces, él entró en la casa para hacer su trabajo, y no había ninguno de los hombres de la casa dentro.",
      "12": "Ella lo agarró por el manto, diciendo: “Acuéstate conmigo”. Él dejó su manto en la mano de ella y salió corriendo.",
      "13": "Cuando ella vio que él había dejado su manto en la mano de ella, y había corrido afuera,",
      "14": "llamó a los hombres de su casa, y les habló diciendo: “He aquí, él ha traído a un hebreo para burlarse de nosotros. Entró en mi casa para acostarse conmigo, y yo grité con fuerza.",
      "15": "Cuando oyó que yo levantaba la voz y gritaba, dejó su manto junto a mí y salió corriendo.”",
      "16": "Ella dejó su ropa junto a ella, hasta que su amo volvió a casa.",
      "17": "Ella le habló según estas palabras, diciendo: “El siervo hebreo que nos has traído, entró a burlarse de mí,",
      "18": "y al levantar mi voz y gritar, dejó su ropa junto a mí y salió corriendo.” ",
      "19": "Cuando su amo oyó las palabras de su mujer, que le dijo: “Esto es lo que me hizo tu siervo”, se encendió su ira.",
      "20": "El amo de José lo apresó y lo metió en la cárcel, el lugar donde estaban atados los prisioneros del rey, y allí estuvo detenido.",
      "21": "Pero el Señor estaba con José, y se mostró bondadoso con él, y le dio favor a los ojos del guardián de la prisión.",
      "22": "El guardián de la cárcel puso en manos de José a todos los presos que estaban en la cárcel. Todo lo que hicieran allí, él era responsable de ello.",
      "23": "El guardián de la cárcel no se ocupaba de nada de lo que estaba bajo su mano, porque el Señor estaba con él; y lo que él hacía, el Señor lo hacía prosperar."
    },
    "40": {
      "1": "Después de estas cosas, el copero del rey de Egipto y su panadero ofendieron a su señor, el rey de Egipto.",
      "2": "El faraón se enojó con sus dos oficiales, el jefe de los coperos y el jefe de los panaderos.",
      "3": "Los puso en custodia en la casa del capitán de la guardia, en la cárcel, el lugar donde estaba atado José.",
      "4": "El capitán de la guardia se los asignó a José, y él se ocupó de ellos. Permanecieron en la cárcel muchos días.",
      "5": "Ambos soñaron un sueño, cada uno su sueño, en una noche, cada uno según la interpretación de su sueño, el copero y el panadero del rey de Egipto, que estaban atados en la cárcel.",
      "6": "José entró a ellos por la mañana, los vio y vio que estaban tristes.",
      "7": "Preguntó a los oficiales del faraón que estaban con él detenidos en la casa de su amo, diciendo: “¿Por qué parecen tan tristes hoy?” ",
      "8": "Le dijeron: “Hemos soñado un sueño y no hay nadie que pueda interpretarlo”. José les dijo: “¿Las interpretaciones no son de Dios? Por favor, díganmelo a mí”. ",
      "9": "El jefe de los coperos contó su sueño a José y le dijo: “En mi sueño, he aquí que una vid estaba delante de mí,",
      "10": "y en la vid había tres sarmientos. Era como si hubiera brotado, florecido, y sus racimos producían uvas maduras.",
      "11": "La copa del faraón estaba en mi mano; tomé las uvas, las exprimí en la copa del faraón y entregué la copa en la mano del faraón.” ",
      "12": "José le dijo: “Esta es su interpretación: las tres ramas son tres días.",
      "13": "Dentro de tres días más, el faraón levantará tu cabeza y te devolverá tu cargo. Entregarás la copa del Faraón en su mano, como lo hacías cuando eras su copero.",
      "14": "Pero acuérdate de mí cuando te vaya bien. Por favor, muéstrate bondadoso conmigo, y mencióname ante el Faraón, y sácame de esta casa.",
      "15": "Porque ciertamente fui robado de la tierra de los hebreos, y aquí tampoco he hecho nada para que me metan en el calabozo.” ",
      "16": "Cuando el jefe de los panaderos vio que la interpretación era buena, dijo a José: “Yo también estaba en mi sueño, y he aquí que tres cestas de pan blanco estaban sobre mi cabeza.",
      "17": "En el cesto de arriba había toda clase de alimentos horneados para el Faraón, y las aves los comían del cesto sobre mi cabeza.” ",
      "18": "José respondió: “Esta es su interpretación. Los tres cestos son tres días.",
      "19": "Dentro de tres días más, el Faraón levantará tu cabeza de encima, te colgará en un árbol y las aves comerán tu carne de encima.”",
      "20": "Al tercer día, que era el cumpleaños del Faraón, éste hizo un banquete para todos sus servidores, y levantó la cabeza del jefe de los coperos y la del jefe de los panaderos entre sus servidores.",
      "21": "Restituyó al jefe de los coperos a su puesto, y entregó la copa a la mano del Faraón;",
      "22": "pero colgó al jefe de los panaderos, como José les había interpretado.",
      "23": "Sin embargo, el jefe de los coperos no se acordó de José, sino que lo olvidó."
    },
    "41": {
      "1": "Al cabo de dos años completos, Faraón soñó, y he aquí que estaba junto al río.",
      "2": "He aquí que siete reses subían del río. Estaban lisos y gordos, y se alimentaban en la hierba del pantano.",
      "3": "He aquí que otras siete reses subían tras ellas del río, feas y flacas, y se quedaban junto a las otras reses al borde del río.",
      "4": "Las reses feas y flacas se comieron a las siete reses lisas y gordas. Entonces el faraón se despertó.",
      "5": "Se durmió y soñó por segunda vez; y he aquí que siete cabezas de grano surgían en un solo tallo, sanas y buenas.",
      "6": "He aquí que siete cabezas de grano, delgadas y arruinadas por el viento del este, brotaban tras ellas.",
      "7": "Las cabezas de grano delgadas se tragaron las siete espigas sanas y llenas. El faraón se despertó, y he aquí que era un sueño.",
      "8": "Por la mañana, su espíritu se turbó y mandó llamar a todos los magos y sabios de Egipto. El Faraón les contó sus sueños, pero no había nadie que pudiera interpretárselos. ",
      "9": "Entonces el jefe de los coperos habló al Faraón, diciendo: “Hoy me acuerdo de mis faltas.",
      "10": "El faraón se enojó con sus servidores y me puso en custodia en la casa del capitán de la guardia, con el jefe de los panaderos.",
      "11": "En una noche soñamos un sueño, él y yo. Cada uno soñó según la interpretación de su sueño.",
      "12": "Estaba allí con nosotros un joven hebreo, sirviente del capitán de la guardia, y se lo contamos, y él nos interpretó nuestros sueños. Él interpretó a cada uno según su sueño.",
      "13": "Tal como nos lo interpretó, así fue. Me restituyó en mi cargo, y lo colgó”. ",
      "14": "Entonces el Faraón envió a llamar a José, y lo sacaron apresuradamente del calabozo. Se afeitó, se cambió de ropa y entró a ver al Faraón.",
      "15": "El faraón dijo a José: “He soñado un sueño, y no hay nadie que pueda interpretarlo. He oído decir de ti que cuando oyes un sueño puedes interpretarlo”. ",
      "16": "José respondió al Faraón diciendo: “No está en mí. Dios le dará al Faraón una respuesta de paz”. ",
      "17": "El faraón habló a José: “En mi sueño, he aquí que yo estaba al borde del río;",
      "18": "y he aquí que siete reses gordas y lisas subían del río. Se alimentaban en la hierba del pantano;",
      "19": "y he aquí que otras siete reses subían tras ellas, pobres y muy feas y flacas, como nunca vi en toda la tierra de Egipto por su fealdad.",
      "20": "Las reses flacas y feas se comieron a las primeras siete reses gordas;",
      "21": "y cuando se las comieron, no se podía saber que se las habían comido, sino que seguían siendo feas, como al principio. Entonces me desperté.",
      "22": "Vi en mi sueño, y he aquí que siete cabezas de grano salían de un solo tallo, llenas y buenas;",
      "23": "y he aquí que siete cabezas de grano, marchitas, flacas y arrasadas por el viento del este, salían detrás de ellas.",
      "24": "Las cabezas de grano flacas se tragaron a las siete cabezas de grano buenas. Se lo conté a los magos, pero no hubo nadie que pudiera explicármelo”. ",
      "25": "José dijo al Faraón: “El sueño del Faraón es uno. Lo que Dios va a hacer se lo ha declarado al Faraón.",
      "26": "Las siete reses buenas son siete años, y las siete cabezas de grano buenas son siete años. El sueño es uno.",
      "27": "Las siete reses flacas y feas que subieron después de ellas son siete años, y también las siete cabezas de grano vacías que fueron destruidas por el viento del este; serán siete años de hambre.",
      "28": "Esto es lo que le he dicho al Faraón. Dios ha mostrado al Faraón lo que va a hacer.",
      "29": "He aquí que vienen siete años de gran abundancia en toda la tierra de Egipto.",
      "30": "Después de ellos vendrán siete años de hambre, y toda la abundancia será olvidada en la tierra de Egipto. El hambre consumirá la tierra,",
      "31": "y la abundancia no se conocerá en la tierra a causa de esa hambruna que sigue, pues será muy grave.",
      "32": "El sueño se duplicó para el Faraón, porque la cosa está establecida por Dios, y Dios la llevará a cabo en breve. ",
      "33": "“Ahora, pues, busque el Faraón un hombre discreto y sabio, y póngalo sobre la tierra de Egipto.",
      "34": "Que el Faraón haga esto, y que designe capataces sobre la tierra, y que recoja la quinta parte de los productos de la tierra de Egipto en los siete años de abundancia.",
      "35": "Que recojan todo el alimento de estos años buenos que vienen, y que almacenen el grano bajo la mano del Faraón para la alimentación en las ciudades, y que lo guarden.",
      "36": "El alimento será para abastecer la tierra contra los siete años de hambre que habrá en la tierra de Egipto, para que la tierra no perezca por el hambre.” ",
      "37": "La cosa fue buena a los ojos del Faraón y de todos sus siervos.",
      "38": "El faraón dijo a sus siervos: “¿Acaso podemos encontrar a alguien como éste, un hombre en quien esté el Espíritu de Dios?”",
      "39": "El faraón dijo a José: “Porque Dios te ha mostrado todo esto, no hay nadie tan discreto y sabio como tú.",
      "40": "Tú estarás al frente de mi casa. Todo mi pueblo será gobernado según tu palabra. Sólo en el trono seré más grande que tú”.",
      "41": "El faraón dijo a José: “He aquí que te he puesto sobre toda la tierra de Egipto”.",
      "42": "El faraón se quitó el anillo de sello de su mano y lo puso en la de José; lo vistió con ropas de lino fino y le puso una cadena de oro al cuello.",
      "43": "Lo hizo montar en el segundo carro que tenía. Gritaron ante él: “¡Inclina la rodilla!” Lo puso sobre toda la tierra de Egipto.",
      "44": "El faraón dijo a José: “Yo soy el faraón. Sin ti, nadie levantará la mano ni el pie en toda la tierra de Egipto”.",
      "45": "El faraón llamó a José Zafnat-Panea. Le dio por esposa a Asenat, hija de Potifera, sacerdote de On. José salió a recorrer la tierra de Egipto. ",
      "46": "José tenía treinta años cuando se presentó ante el Faraón, rey de Egipto. José salió de la presencia del Faraón y recorrió toda la tierra de Egipto.",
      "47": "En los siete años de abundancia, la tierra produjo en abundancia.",
      "48": "Recogió toda la comida de los siete años que había en la tierra de Egipto, y guardó la comida en las ciudades. En cada ciudad almacenó alimentos de los campos que rodeaban la ciudad.",
      "49": "José acumuló grano como la arena del mar, mucho, hasta que dejó de contarlo, porque no tenía número.",
      "50": "A José le nacieron dos hijos antes de que llegara el año del hambre, que le dio a luz Asenat, hija de Potifera, sacerdote de On.",
      "51": "José llamó al primogénito Manasés,  “Porque”, dijo, “Dios me ha hecho olvidar todo mi trabajo y toda la casa de mi padre.”",
      "52": "El nombre del segundo, lo llamó Efraín:  “Porque Dios me ha hecho fructificar en la tierra de mi aflicción.” ",
      "53": "Los siete años de abundancia que hubo en la tierra de Egipto llegaron a su fin.",
      "54": "Comenzaron a llegar los siete años de hambre, tal como había dicho José. Hubo hambre en todas las tierras, pero en toda la tierra de Egipto hubo pan.",
      "55": "Cuando toda la tierra de Egipto estaba hambrienta, el pueblo clamó al Faraón por pan, y el Faraón dijo a todos los egipcios: “Vayan a José. Haced lo que él os diga”.",
      "56": "El hambre se extendía por toda la superficie de la tierra. José abrió todos los almacenes y vendió a los egipcios. El hambre era grave en la tierra de Egipto.",
      "57": "Todos los países vinieron a Egipto, a José, para comprar grano, porque el hambre era grave en toda la tierra."
    },
    "42": {
      "1": "Vio Jacob que había grano en Egipto, y dijo a sus hijos: “¿Por qué os miráis unos a otros?”.",
      "2": "Dijo: “He aquí, he oído que hay grano en Egipto. Bajad allí y comprad para nosotros de allí, para que vivamos y no muramos”.",
      "3": "Los diez hermanos de José bajaron a comprar grano a Egipto.",
      "4": "Pero Jacob no envió a Benjamín, el hermano de José, con sus hermanos, porque dijo: “No sea que le pase algo malo.”",
      "5": "Los hijos de Israel fueron a comprar entre los que venían, porque había hambre en la tierra de Canaán.",
      "6": "José era el gobernador de la tierra. Era él quien vendía a todo el pueblo de la tierra. Vinieron los hermanos de José y se inclinaron ante él con el rostro hacia la tierra.",
      "7": "José vio a sus hermanos y los reconoció, pero se comportó con ellos como un extraño y les habló con rudeza. Les dijo: “¿De dónde venís?”. Dijeron: “De la tierra de Canaán, para comprar comida”. ",
      "8": "José reconoció a sus hermanos, pero ellos no lo reconocieron a él.",
      "9": "José se acordó de los sueños que había soñado con ellos y les dijo: “¡Sois espías! Habéis venido a ver la desnudez de la tierra”. ",
      "10": "Le dijeron: “No, mi señor, pero tus siervos han venido a comprar comida.",
      "11": "Todos somos hijos de un hombre; somos hombres honrados. Tus siervos no son espías”. ",
      "12": "Les dijo: “¡No, pero habéis venido a ver la desnudez de la tierra!” ",
      "13": "Ellos dijeron: “Nosotros, tus siervos, somos doce hermanos, hijos de un solo hombre en la tierra de Canaán; y he aquí que el menor está hoy con nuestro padre, y uno ya no está.” ",
      "14": "José les dijo: “Es como les dije, diciendo: ‘Ustedes son espías’.",
      "15": "Por esto seréis probados. Por la vida del Faraón, no saldréis de aquí, a menos que venga vuestro hermano menor.",
      "16": "Enviad a uno de vosotros y que traiga a vuestro hermano, y seréis atados, para que se compruebe si vuestras palabras son verdaderas, o si por la vida del faraón ciertamente sois espías.”",
      "17": "Los puso a todos juntos en custodia durante tres días. ",
      "18": "Al tercer día, José les dijo: “Haced esto y vivid, porque temo a Dios.",
      "19": "Si sois hombres honrados, dejad que uno de vuestros hermanos sea atado en vuestra prisión; pero vosotros id, llevad grano para el hambre de vuestras casas.",
      "20": "Traedme a vuestro hermano menor; así se verificarán vuestras palabras y no moriréis.” Así lo hicieron.",
      "21": "Se dijeron unos a otros: “Ciertamente somos culpables respecto a nuestro hermano, ya que vimos la angustia de su alma, cuando nos suplicó, y no quisimos escucharlo. Por eso nos ha sobrevenido esta angustia”.",
      "22": "Rubén les respondió: “¿No os dije que no pecarais contra el niño, y no quisisteis escuchar? Por eso también, he aquí que se requiere su sangre”.",
      "23": "Ellos no sabían que José los entendía, pues había un intérprete entre ellos.",
      "24": "Se apartó de ellos y lloró. Luego volvió a ellos y les habló, y tomó a Simeón de entre ellos y lo ató ante sus ojos.",
      "25": "Entonces José dio la orden de llenar sus sacos de grano, y de devolver a cada uno su dinero en su saco, y de darles comida para el camino. Así se hizo con ellos. ",
      "26": "Cargaron sus asnos con el grano y se fueron de allí.",
      "27": "Cuando uno de ellos abrió su saco para dar de comer a su asno en el lugar de alojamiento, vio su dinero. Estaba en la boca de su saco.",
      "28": "Dijo a sus hermanos: “¡Mi dinero se ha recuperado! He aquí que está en mi saco”. Les falló el corazón, y se volvieron temblando unos a otros, diciendo: “¿Qué es esto que Dios ha hecho con nosotros?”",
      "29": "Vinieron a Jacob, su padre, a la tierra de Canaán, y le contaron todo lo que les había sucedido, diciendo:",
      "30": "“El hombre, el señor de la tierra, habló con nosotros con aspereza y nos tomó por espías del país.",
      "31": "Nosotros le dijimos: ‘Somos hombres honestos. No somos espías.",
      "32": "Somos doce hermanos, hijos de nuestro padre; uno ya no existe, y el más joven está hoy con nuestro padre en la tierra de Canaán.’",
      "33": "El hombre, el señor de la tierra, nos dijo: ‘Por esto sabré que sois hombres honrados: dejad conmigo a uno de vuestros hermanos, tomad grano para el hambre de vuestras casas y seguid vuestro camino.",
      "34": "Traedme a vuestro hermano menor. Entonces sabré que no sois espías, sino que sois hombres honrados. Así te entregaré a tu hermano, y comerciarás en la tierra”. ",
      "35": "Cuando vaciaron sus sacos, he aquí que el fajo de dinero de cada uno estaba en su saco. Cuando ellos y su padre vieron sus fajos de dinero, se asustaron.",
      "36": "Jacob, su padre, les dijo: “¡Me habéis privado de mis hijos! Ya no está José, ya no está Simeón, y queréis llevaros a Benjamín. Todo esto es contra mí”. ",
      "37": "Rubén habló a su padre diciendo: “Mata a mis dos hijos si no te lo traigo. Confíalo a mi cuidado, y te lo traeré de nuevo”. ",
      "38": "Dijo: “Mi hijo no bajará con vosotros, pues su hermano ha muerto y sólo queda él. Si le ocurre algún daño en el camino por el que vas, entonces harás descender mis canas con dolor al Seol”.  "
    },
    "43": {
      "1": "El hambre era severa en la tierra.",
      "2": "Cuando se consumió el grano que habían sacado de Egipto, su padre les dijo: “Volved a comprarnos un poco más de comida”. ",
      "3": "Judá le habló diciendo: “El hombre nos advirtió solemnemente, diciendo: ‘No veréis mi rostro, a menos que vuestro hermano esté con vosotros’.",
      "4": "Si envías a nuestro hermano con nosotros, bajaremos a comprarte comida;",
      "5": "pero si no lo envías, no bajaremos, porque el hombre nos dijo: ‘No veréis mi rostro, a menos que vuestro hermano esté con vosotros’”. ",
      "6": "Israel dijo: “¿Por qué me trataste tan mal, diciéndole al hombre que tenías otro hermano?” ",
      "7": "Dijeron: “El hombre preguntó directamente por nosotros y por nuestros parientes, diciendo: ‘¿Vive aún tu padre? ¿Tenéis otro hermano? Nos limitamos a responder a sus preguntas. ¿Acaso podíamos saber que iba a decir: ‘Bajad a vuestro hermano’?” ",
      "8": "Judá dijo a Israel, su padre: “Envía al muchacho conmigo, y nos levantaremos y nos iremos, para que vivamos y no muramos, tanto nosotros como tú, y también nuestros pequeños.",
      "9": "Yo seré la garantía para él. De mi mano lo requerirás. Si no te lo traigo, y lo pongo delante de ti, entonces déjame cargar con la culpa para siempre;",
      "10": "porque si no nos hubiéramos demorado, seguramente ya habríamos regresado por segunda vez.” ",
      "11": "Su padre, Israel, les dijo: “Si ha de ser así, haced esto: Tomad de los frutos selectos de la tierra en vuestros sacos, y bajad un regalo para el hombre, un poco de bálsamo, un poco de miel, especias y mirra, nueces y almendras;",
      "12": "y tomad el doble de dinero en vuestra mano, y llevad el dinero que se os devolvió en la boca de vuestros sacos. Tal vez fue un descuido.",
      "13": "Toma también a tu hermano, levántate y vuelve con él.",
      "14": "Que el Dios Todopoderoso te dé misericordia ante el hombre, para que te libere a tu otro hermano y a Benjamín. Si estoy desprovisto de mis hijos, estoy desprovisto”. ",
      "15": "Los hombres aceptaron ese regalo, y tomaron el doble de dinero en su mano, y a Benjamín; se levantaron, bajaron a Egipto y se presentaron ante José.",
      "16": "Cuando José vio a Benjamín con ellos, le dijo al mayordomo de su casa: “Lleva a los hombres a la casa, descuartiza un animal y prepárate, porque los hombres cenarán conmigo al mediodía.” ",
      "17": "El hombre hizo lo que José le ordenó, y llevó a los hombres a la casa de José.",
      "18": "Los hombres tuvieron miedo de que los llevaran a la casa de José, y dijeron: “Por el dinero que se devolvió en nuestros sacos la primera vez, nos han traído, para que busque ocasión contra nosotros, nos ataque y nos tome como esclavos, junto con nuestros asnos.”",
      "19": "Se acercaron al mayordomo de la casa de José, y le hablaron a la puerta de la casa,",
      "20": "y le dijeron: “Oh, señor mío, la primera vez bajamos a comprar comida.",
      "21": "Cuando llegamos al lugar de alojamiento, abrimos nuestros sacos, y he aquí que el dinero de cada uno estaba en la boca de su saco, nuestro dinero en su totalidad. Lo hemos traído en nuestra mano.",
      "22": "Hemos bajado otro dinero en nuestra mano para comprar comida. No sabemos quién puso nuestro dinero en nuestros sacos”. ",
      "23": "Dijo: “La paz sea con vosotros. No tengáis miedo. Tu Dios, y el Dios de tu padre, te ha dado un tesoro en tus sacos. He recibido vuestro dinero”. Hizo salir a Simeón hacia ellos.",
      "24": "El hombre llevó a los hombres a la casa de José, les dio agua y les lavó los pies. Les dio forraje a sus burros.",
      "25": "Prepararon el regalo para la llegada de José al mediodía, pues se enteraron de que debían comer pan allí. ",
      "26": "Cuando José volvió a casa, le llevaron el regalo que tenían en la mano a la casa, y se postraron en tierra ante él.",
      "27": "Él les preguntó por su bienestar y les dijo: “¿Está bien vuestro padre, el anciano del que habéis hablado? ¿Aún vive?” ",
      "28": "Ellos dijeron: “Tu siervo, nuestro padre, está bien. Todavía está vivo”. Se inclinaron humildemente.",
      "29": "Él levantó los ojos y vio a Benjamín, su hermano, hijo de su madre, y dijo: “¿Es éste tu hermano menor, del que me hablaste?” Y él respondió: “Que Dios se apiade de ti, hijo mío”.",
      "30": "José se apresuró, pues su corazón anhelaba a su hermano, y buscó un lugar para llorar. Entró en su habitación y lloró allí.",
      "31": "Se lavó la cara y salió. Se controló y dijo: “Sirve la comida”. ",
      "32": "Le servían a él solo, y a ellos solos, y a los egipcios que comían con él solos, porque los egipcios no comen con los hebreos, pues eso es una abominación para los egipcios.",
      "33": "Se sentaron delante de él, el primogénito según su primogenitura y el menor según su juventud, y los hombres se maravillaron entre sí.",
      "34": "Les mandó porciones de delante, pero la porción de Benjamín fue cinco veces mayor que la de cualquiera de ellos. Bebieron y se alegraron con él."
    },
    "44": {
      "1": "Mandó al administrador de su casa, diciendo: “Llena los sacos de los hombres con comida, toda la que puedan llevar, y pon el dinero de cada uno en la boca de su saco.",
      "2": "Pon mi copa, la copa de plata, en la boca del saco del más joven, con su dinero del grano”. Él hizo conforme a la palabra que José había dicho.",
      "3": "Tan pronto como amaneció, los hombres fueron despedidos, ellos y sus asnos.",
      "4": "Cuando salieron de la ciudad y aún no estaban lejos, José dijo a su mayordomo: “Arriba, sigue a los hombres. Cuando los alcances, pregúntales: ‘¿Por qué habéis premiado el mal con el bien?",
      "5": "¿No es esto de lo que bebe mi señor, y por lo que en verdad adivina? Habéis hecho el mal al hacerlo’”.",
      "6": "Los alcanzó y les dijo estas palabras. ",
      "7": "Le dijeron: “¿Por qué habla mi señor tales palabras? ¡Lejos están tus siervos de hacer tal cosa!",
      "8": "He aquí, el dinero que encontramos en la boca de nuestros sacos, te lo trajimos de la tierra de Canaán. ¿Cómo, pues, habríamos de robar plata u oro de la casa de tu señor?",
      "9": "Con cualquiera de tus siervos que se encuentre, que muera, y nosotros también seremos esclavos de mi señor”. ",
      "10": "Dijo: “Ahora también sea según tus palabras. Aquel con quien se encuentre será mi esclavo; y tú serás irreprochable”. ",
      "11": "Entonces se apresuraron, y cada uno bajó su saco al suelo, y cada uno abrió su saco.",
      "12": "Buscó, comenzando por el más viejo y terminando por el más joven. La copa se encontró en el saco de Benjamín.",
      "13": "Luego se rasgaron las vestiduras, y cada uno cargó su asno, y regresaron a la ciudad. ",
      "14": "Judá y sus hermanos llegaron a la casa de José, y éste todavía estaba allí. Se postraron en el suelo ante él.",
      "15": "José les dijo: “¿Qué obra es ésta que habéis hecho? ¿No sabéis que un hombre como yo sí puede hacer adivinación?” ",
      "16": "Judá dijo: “¿Qué le diremos a mi señor? ¿Qué vamos a decir? ¿Cómo nos exculparemos? Dios ha descubierto la iniquidad de tus siervos. He aquí que somos esclavos de mi señor, tanto nosotros como aquel en cuya mano se encuentra la copa”. ",
      "17": "Él dijo: “Lejos de mí el hacerlo. El hombre en cuya mano se encuentre la copa, será mi esclavo; pero en cuanto a ti, sube en paz a tu padre.” ",
      "18": "Entonces Judá se acercó a él y le dijo: “Oh, señor mío, por favor, deja que tu siervo hable una palabra en los oídos de mi señor, y no dejes que tu ira arda contra tu siervo, porque eres como Faraón.",
      "19": "Mi señor preguntó a sus siervos, diciendo: “¿Tenéis padre o hermano?”",
      "20": "Dijimos a mi señor: “Tenemos un padre, un anciano, y un hijo de su edad, un pequeño; y su hermano ha muerto, y sólo queda él de su madre; y su padre lo quiere.",
      "21": "Dijiste a tus siervos: ‘Tráiganlo a mí, para que ponga mis ojos en él’.",
      "22": "Dijimos a mi señor: ‘El muchacho no puede dejar a su padre, pues si lo dejara, su padre moriría’.",
      "23": "Dijiste a tus siervos: Si tu hermano menor no baja contigo, no verás más mi rostro’.",
      "24": "Cuando subimos donde tu siervo mi padre, le contamos las palabras de mi señor.",
      "25": "Nuestro padre dijo: ‘Vuelve a comprarnos un poco de comida’.",
      "26": "Nosotros dijimos: ‘No podemos bajar. Si nuestro hermano menor está con nosotros, entonces bajaremos; porque no podremos ver el rostro del hombre, a menos que nuestro hermano menor esté con nosotros.’",
      "27": "Tu siervo, mi padre, nos dijo: ‘Ustedes saben que mi esposa me dio dos hijos.",
      "28": "Uno salió de mí, y dije: “Seguramente está despedazado”; y no lo he vuelto a ver.",
      "29": "Si me quitan a éste también, y le sucede algún daño, harán descender mis canas con dolor al Seol.’  ",
      "30": "Ahora, pues, cuando vaya a ver a tu siervo mi padre, y el muchacho no esté con nosotros, ya que su vida está ligada a la del muchacho,",
      "31": "sucederá que cuando vea que el muchacho ya no está, morirá. Tus siervos harán descender las canas de tu siervo, nuestro padre, con dolor al Seol.  ",
      "32": "Porque tu siervo se hizo garante del muchacho ante mi padre, diciendo: ‘Si no te lo traigo, entonces cargaré con la culpa ante mi padre para siempre’.",
      "33": "Ahora, pues, por favor, deja que tu siervo se quede en lugar del muchacho, el esclavo de mi señor; y deja que el muchacho suba con sus hermanos.",
      "34": "Porque ¿cómo voy a subir a mi padre si el muchacho no está conmigo? para que no vea el mal que le sobrevendrá a mi padre”."
    },
    "45": {
      "1": "Entonces José no pudo controlarse ante todos los que estaban frente a él, y gritó: “¡Que todos salgan de mí!”. Nadie más estaba con él, mientras José se daba a conocer a sus hermanos.",
      "2": "Lloró en voz alta. Los egipcios lo oyeron, y la casa del faraón también.",
      "3": "José dijo a sus hermanos: “¡Yo soy José! ¿Vive aún mi padre?” Sus hermanos no pudieron responderle, pues estaban aterrados ante su presencia.",
      "4": "José dijo a sus hermanos: “Acérquense a mí, por favor”. Se acercaron. Él les dijo: “Yo soy José, vuestro hermano, a quien vendisteis a Egipto.",
      "5": "No os entristezcáis ni os enfadéis por haberme vendido aquí, pues Dios me ha enviado delante de vosotros para preservar la vida.",
      "6": "Durante estos dos años el hambre ha estado en la tierra, y aún quedan cinco años, en los que no habrá arado ni cosecha.",
      "7": "Dios me envió delante de ti para preservar para ti un remanente en la tierra, y para salvarte con vida mediante una gran liberación.",
      "8": "Así que ahora no fuiste tú quien me envió aquí, sino Dios, y él me ha hecho padre del Faraón, señor de toda su casa y gobernante de toda la tierra de Egipto.",
      "9": "Date prisa, sube a ver a mi padre y dile: “Esto es lo que dice tu hijo José: “Dios me ha hecho señor de todo Egipto. Baja a verme. No esperes.",
      "10": "Habitarás en la tierra de Gosén, y estarás cerca de mí, tú, tus hijos, los hijos de tus hijos, tus rebaños, tus manadas y todo lo que tengas.",
      "11": "Allí te proveeré, porque todavía hay cinco años de hambre; para que no llegues a la pobreza, tú y tu familia, y todo lo que tienes”’.",
      "12": "He aquí que tus ojos ven, y los ojos de mi hermano Benjamín, que es mi boca la que te habla.",
      "13": "Contarás a mi padre toda mi gloria en Egipto y todo lo que has visto. Te apresurarás a traer a mi padre aquí”.",
      "14": "Se echó al cuello de su hermano Benjamín y lloró, y Benjamín lloró sobre su cuello.",
      "15": "Besó a todos sus hermanos y lloró sobre ellos. Después sus hermanos hablaron con él. ",
      "16": "La noticia se oyó en la casa del faraón, diciendo: “Han venido los hermanos de José”. Esto agradó al Faraón y a sus siervos.",
      "17": "El faraón le dijo a José: “Dile a tus hermanos que hagan esto: Carguen sus animales y vayan, viajen a la tierra de Canaán.",
      "18": "Tomad a vuestro padre y a vuestras familias, y venid a mí, y os daré el bien de la tierra de Egipto, y comeréis la grasa de la tierra.’",
      "19": "Ahora se os ordena hacer esto: Tomad carros de la tierra de Egipto para vuestros pequeños y para vuestras mujeres, y traed a vuestro padre, y venid.",
      "20": "Además, no os preocupéis por vuestras pertenencias, porque el bien de toda la tierra de Egipto es vuestro.” ",
      "21": "Así lo hicieron los hijos de Israel. José les dio carros, según el mandato del faraón, y les dio provisiones para el camino.",
      "22": "A cada uno de ellos le dio mudas de ropa, pero a Benjamín le dio trescientas piezas de plata y cinco mudas de ropa.",
      "23": "Envió a su padre lo siguiente: diez burros cargados con los bienes de Egipto, y diez burras cargadas de grano y pan y provisiones para su padre en el camino.",
      "24": "Entonces despidió a sus hermanos y se fueron. Les dijo: “Mirad que no os peleéis por el camino”. ",
      "25": "Subieron de Egipto y llegaron a la tierra de Canaán, donde su padre Jacob.",
      "26": "Le contaron, diciendo: “José aún vive, y es soberano de toda la tierra de Egipto”. Su corazón se desmayó, pues no les creyó.",
      "27": "Le contaron todas las palabras de José que él les había dicho. Cuando vio los carros que José había enviado para llevarlo, el espíritu de Jacob, su padre, revivió.",
      "28": "Israel dijo: “Es suficiente. José, mi hijo, sigue vivo. Iré a verlo antes de morir”."
    },
    "46": {
      "1": "Israel viajó con todo lo que tenía, llegó a Beerseba y ofreció sacrificios al Dios de su padre, Isaac.",
      "2": "Dios habló a Israel en las visiones de la noche, y dijo: “¡Jacob, Jacob!” Dijo: “Aquí estoy”. ",
      "3": "Dijo: “Yo soy Dios, el Dios de tu padre. No tengas miedo de bajar a Egipto, porque allí haré de ti una gran nación.",
      "4": "Yo bajaré contigo a Egipto. También te haré subir con toda seguridad. La mano de José cerrará tus ojos”. ",
      "5": "Jacob se levantó de Beerseba, y los hijos de Israel llevaron a Jacob, a su padre, a sus hijos y a sus mujeres, en los carros que el faraón había enviado para transportarlo.",
      "6": "Tomaron su ganado y sus bienes, que habían adquirido en la tierra de Canaán, y entraron en Egipto: Jacob, y toda su descendencia con él,",
      "7": "sus hijos, y los hijos de sus hijos con él, sus hijas y las hijas de sus hijos, y llevó toda su descendencia con él a Egipto. ",
      "8": "Estos son los nombres de los hijos de Israel que entraron en Egipto, Jacob y sus hijos: Rubén, primogénito de Jacob.",
      "9": "Los hijos de Rubén: Hanoc, Palú, Hezrón y Carmi.",
      "10": "Los hijos de Simeón: Jemuel, Jamín, Ohad, Jacín, Zohar y Shaúl, hijo de una cananea.",
      "11": "Los hijos de Leví: Gersón, Coat y Merari.",
      "12": "Los hijos de Judá: Er, Onán, Sela, Pérez y Zéraj; pero Er y Onán murieron en la tierra de Canaán. Los hijos de Pérez fueron Hezrón y Hamul.",
      "13": "Los hijos de Isacar: Tola, Puvah, Iob y Shimron.",
      "14": "Los hijos de Zabulón: Sered, Elón y Jahleel.",
      "15": "Estos son los hijos de Lea, que dio a luz a Jacob en Padan Aram, con su hija Dina. Todas las almas de sus hijos e hijas fueron treinta y tres.",
      "16": "Los hijos de Gad: Zifón, Haggi, Shuni, Ezbón, Eri, Arodi y Areli.",
      "17": "Los hijos de Aser: Imna, Ishva, Ishvi, Beriá y su hermana Sera. Los hijos de Beriá: Heber y Malquiel.",
      "18": "Estos son los hijos de Zilpá, que Labán dio a su hija Lea, y que ella dio a luz a Jacob, dieciséis almas.",
      "19": "Los hijos de Raquel, mujer de Jacob José y Benjamín.",
      "20": "A José le nacieron en la tierra de Egipto Manasés y Efraín, que le dio a luz Asenat, hija de Potifera, sacerdote de On.",
      "21": "Los hijos de Benjamín: Bela, Becher, Ashbel, Gera, Naamán, Ehi, Rosh, Muppim, Huppim y Ard.",
      "22": "Estos son los hijos de Raquel que le nacieron a Jacob: todos fueron catorce.",
      "23": "El hijo de Dan: Hushim.",
      "24": "Los hijos de Neftalí: Jahzeel, Guni, Jezer y Silim.",
      "25": "Estos son los hijos de Bilhá, que Labán dio a su hija Raquel, y éstos fueron los que ella dio a luz a Jacob: todas las almas fueron siete.",
      "26": "Todas las almas que vinieron con Jacob a Egipto, que fueron su descendencia directa, además de las mujeres de los hijos de Jacob, todas las almas fueron sesenta y seis.",
      "27": "Los hijos de José, que le nacieron en Egipto, fueron dos almas. Todas las almas de la casa de Jacob, que llegaron a Egipto, fueron setenta. ",
      "28": "Jacob envió a Judá delante de José para que le mostrara el camino a Gosén, y llegaron a la tierra de Gosén.",
      "29": "José preparó su carro y subió a recibir a Israel, su padre, en Gosén. Se presentó ante él, y se echó sobre su cuello, y lloró sobre su cuello un buen rato.",
      "30": "Israel dijo a José: “Ahora déjame morir, ya que he visto tu rostro, que aún estás vivo”. ",
      "31": "José dijo a sus hermanos y a la casa de su padre: “Subiré y hablaré con el Faraón y le diré: ‘Mis hermanos y la casa de mi padre, que estaban en la tierra de Canaán, han venido a mí.",
      "32": "Estos hombres son pastores, pues han sido cuidadores de ganado, y han traído sus rebaños, sus manadas y todo lo que tienen.’",
      "33": "Sucederá que cuando el Faraón os llame y os diga: “¿A qué os dedicáis?",
      "34": "que diréis: ‘Tus siervos han sido cuidadores de ganado desde nuestra juventud hasta ahora, tanto nosotros como nuestros padres’, para que podáis habitar en la tierra de Gosén; porque todo pastor es una abominación para los egipcios.”"
    },
    "47": {
      "1": "Entonces José entró y dio cuenta al Faraón, diciendo: “Mi padre y mis hermanos, con sus rebaños, sus manadas y todo lo que poseen, han salido de la tierra de Canaán; y he aquí que están en la tierra de Gosén.”",
      "2": "De entre sus hermanos tomó cinco hombres y los presentó al Faraón.",
      "3": "El faraón dijo a sus hermanos: “¿A qué os dedicáis?” Dijeron al Faraón: “Tus siervos son pastores, tanto nosotros como nuestros padres”.",
      "4": "También dijeron al Faraón: “Hemos venido a vivir como extranjeros en la tierra, porque no hay pastos para los rebaños de tus siervos. Porque el hambre es grave en la tierra de Canaán. Ahora, pues, por favor, deja que tus siervos habiten en la tierra de Gosén”. ",
      "5": "El faraón habló a José, diciendo: “Tu padre y tus hermanos han venido a ti.",
      "6": "La tierra de Egipto está ante ti. Haz que tu padre y tus hermanos habiten en lo mejor de la tierra. Que habiten en la tierra de Gosén. Si conoces a algún hombre capaz entre ellos, ponlo a cargo de mi ganado”. ",
      "7": "José hizo entrar a Jacob, su padre, y lo presentó ante el Faraón; y Jacob bendijo al Faraón.",
      "8": "El faraón dijo a Jacob: “¿Cuántos años tienes?” ",
      "9": "Jacob dijo al Faraón: “Los años de mi peregrinación son ciento treinta años. Los días de los años de mi vida han sido pocos y malos. No han llegado a los días de los años de la vida de mis padres en los días de su peregrinación”.",
      "10": "Jacob bendijo al faraón y salió de la presencia del faraón. ",
      "11": "José colocó a su padre y a sus hermanos, y les dio una posesión en la tierra de Egipto, en lo mejor de la tierra, en la tierra de Ramsés, como lo había ordenado el Faraón.",
      "12": "José proveyó de pan a su padre, a sus hermanos y a toda la familia de su padre, según el tamaño de sus familias. ",
      "13": "No había pan en toda la tierra, pues el hambre era muy severa, de modo que la tierra de Egipto y la tierra de Canaán desfallecían a causa del hambre.",
      "14": "José reunió todo el dinero que se encontró en la tierra de Egipto y en la tierra de Canaán, por el grano que compraron; y José llevó el dinero a la casa del Faraón.",
      "15": "Cuando se gastó todo el dinero en la tierra de Egipto y en la tierra de Canaán, todos los egipcios se acercaron a José y le dijeron: “Danos pan, pues ¿para qué vamos a morir en tu presencia? Porque nuestro dinero se agota”. ",
      "16": "José dijo: “Dame tu ganado, y yo te daré comida para tu ganado, si se acaba tu dinero”. ",
      "17": "Trajeron sus ganados a José, y éste les dio pan a cambio de los caballos, de los rebaños y de los asnos, y los alimentó con pan a cambio de todos sus ganados de aquel año.",
      "18": "Terminado aquel año, vinieron a él el segundo año y le dijeron: “No vamos a ocultar a mi señor que todo nuestro dinero se ha gastado, y que los rebaños son de mi señor. No queda nada a la vista de mi señor, sino nuestros cuerpos y nuestras tierras.",
      "19": "¿Por qué hemos de morir ante sus ojos, nosotros y nuestras tierras? Cómpranos a nosotros y a nuestra tierra a cambio de pan, y nosotros y nuestra tierra seremos siervos del faraón. Danos semilla, para que vivamos y no muramos, y para que la tierra no quede desolada”. ",
      "20": "Así que José compró toda la tierra de Egipto para el Faraón, pues cada hombre de los egipcios vendió su campo, porque la hambruna se cebó con ellos, y la tierra pasó a ser del Faraón.",
      "21": "En cuanto al pueblo, lo trasladó a las ciudades desde un extremo de la frontera de Egipto hasta el otro.",
      "22": "Sólo que no compró la tierra de los sacerdotes, porque los sacerdotes tenían una porción del Faraón y comían su porción que el Faraón les daba. Por eso no vendieron sus tierras.",
      "23": "Entonces José dijo al pueblo: “Miren, hoy les he comprado a ustedes y a sus tierras para el Faraón. He aquí que hay semilla para ustedes, y ustedes sembrarán la tierra.",
      "24": "Sucederá que en las cosechas daréis una quinta parte al Faraón, y cuatro partes serán vuestras, para semilla del campo, para vuestro alimento, para los de vuestras casas y para el alimento de vuestros hijos.” ",
      "25": "Dijeron: “¡Nos has salvado la vida! Hallemos el favor a los ojos de mi señor, y seremos siervos del Faraón”. ",
      "26": "José hizo un estatuto sobre la tierra de Egipto hasta el día de hoy, para que el Faraón tuviera el quinto. Sólo la tierra de los sacerdotes no pasó a ser del Faraón. ",
      "27": "Israel vivió en la tierra de Egipto, en la tierra de Gosén, y se apropió de ella, y fructificó y se multiplicó en gran manera.",
      "28": "Jacob vivió en la tierra de Egipto diecisiete años. Así que los días de Jacob, los años de su vida, fueron ciento cuarenta y siete años.",
      "29": "Se acercó el momento en que Israel debía morir, y llamó a su hijo José, y le dijo: “Si ahora he hallado gracia ante tus ojos, por favor, pon tu mano debajo de mi muslo y trátame con bondad y sinceridad. Por favor, no me entierres en Egipto,",
      "30": "sino que cuando duerma con mis padres, me sacarás de Egipto y me enterrarás en su sepultura.” José dijo: “Haré lo que has dicho”. ",
      "31": "Israel dijo: “Júrame”, y él le juró. Entonces Israel se inclinó sobre la cabecera de la cama."
    },
    "48": {
      "1": "Después de estas cosas, alguien dijo a José: “He aquí que tu padre está enfermo”. Tomó consigo a sus dos hijos, Manasés y Efraín.",
      "2": "Alguien avisó a Jacob y le dijo: “He aquí que tu hijo José viene a ti”, e Israel se fortaleció y se sentó en la cama.",
      "3": "Jacob dijo a José: “El Dios Todopoderoso se me apareció en Luz, en la tierra de Canaán, y me bendijo,",
      "4": "y me dijo: ‘He aquí que te haré fructificar y te multiplicaré, y haré de ti una compañía de pueblos, y daré esta tierra a tu descendencia después de ti como posesión eterna’.",
      "5": "Tus dos hijos, que te nacieron en la tierra de Egipto antes de que yo viniera a ti a Egipto, son míos; Efraín y Manasés, como Rubén y Simeón, serán míos.",
      "6": "Tu descendencia, de la que seas padre después de ellos, será tuya. Se llamarán con el nombre de sus hermanos en su herencia.",
      "7": "En cuanto a mí, cuando vine de Paddán, Raquel murió a mi lado en la tierra de Canaán, en el camino, cuando aún faltaba para llegar a Efrat, y la enterré allí en el camino a Efrat (también llamada Belén).” ",
      "8": "Israel vio a los hijos de José y dijo: “¿Quiénes son estos?” ",
      "9": "José dijo a su padre: “Son mis hijos, que Dios me ha dado aquí”. Dijo: “Por favor, tráemelos, y los bendeciré”.",
      "10": "Ahora bien, los ojos de Israel estaban apagados por la edad, de modo que no podía ver bien. José los acercó, los besó y los abrazó.",
      "11": "Israel dijo a José: “No creía que fuera a ver tu rostro, y he aquí que Dios me ha permitido ver también tu descendencia.”",
      "12": "José los sacó de entre sus rodillas y se inclinó con el rostro hacia la tierra.",
      "13": "José tomó a ambos, a Efraín con su mano derecha hacia la mano izquierda de Israel, y a Manasés con su mano izquierda hacia la mano derecha de Israel, y los acercó a él.",
      "14": "Israel extendió su mano derecha y la puso sobre la cabeza de Efraín, que era el menor, y su mano izquierda sobre la cabeza de Manasés, guiando sus manos a sabiendas, pues Manasés era el primogénito.",
      "15": "Bendijo a José y dijo,   “El Dios ante el que caminaron mis padres Abraham e Isaac,   el Dios que me ha alimentado durante toda mi vida hasta el día de hoy, ",
      "16": "  el ángel que me ha redimido de todo mal, bendice a los muchachos,   y que mi nombre sea nombrado en ellos,   y el nombre de mis padres Abraham e Isaac.   Que crezcan en multitud sobre la tierra”. ",
      "17": "Cuando José vio que su padre ponía su mano derecha sobre la cabeza de Efraín, le disgustó. Levantó la mano de su padre para quitarla de la cabeza de Efraín a la de Manasés.",
      "18": "José dijo a su padre: “No es así, padre mío, porque éste es el primogénito. Pon tu mano derecha sobre su cabeza”. ",
      "19": "Su padre se negó y dijo: “Lo sé, hijo mío, lo sé. Él también llegará a ser un pueblo, y también será grande. Sin embargo, su hermano menor será más grande que él, y su descendencia llegará a ser una multitud de naciones”.",
      "20": "Aquel día los bendijo diciendo: “Israel bendecirá en vosotros, diciendo: “Dios os haga como Efraín y como Manasés”” Puso a Efraín por delante de Manasés.",
      "21": "Israel dijo a José: “He aquí que yo muero, pero Dios estará contigo y te hará volver a la tierra de tus padres.",
      "22": "Además, te he dado una porción por encima de tus hermanos, que tomé de la mano del amorreo con mi espada y con mi arco.”"
    }
  }
};

