
	
export const bib_verses = {
  "proverbs": {
    "7": {
      "1": "  Hijo mío, guarda mis palabras.   Guarda mis mandamientos dentro de ti. ",
      "2": "  ¡Guarda mis mandamientos y vive!   Guarda mi enseñanza como la niña de tus ojos. ",
      "3": "  Átalos en los dedos.   Escríbelos en la tabla de tu corazón. ",
      "4": "  Dile a la sabiduría: “Eres mi hermana”.   Llama a la comprensión de tu pariente, ",
      "5": "  para que te alejen de la mujer extraña,   de la extranjera que halaga con sus palabras. ",
      "6": "  Pues en la ventana de mi casa,   Miré a través de mi celosía. ",
      "7": "  Vi entre los simples.   Distinguí entre los jóvenes a un joven vacío de entendimiento, ",
      "8": "  pasando por la calle cerca de su esquina,   se dirigió a su casa, ",
      "9": "  en el crepúsculo, en la tarde del día,   en medio de la noche y en la oscuridad. ",
      "10": "  He aquí que le salió al encuentro una mujer con atuendo de prostituta,   y con astucia. ",
      "11": "  Es ruidosa y desafiante.   Sus pies no se quedan en su casa. ",
      "12": "  Ahora está en las calles, ahora en las plazas,   y acechando en cada esquina. ",
      "13": "  Entonces ella lo agarró y lo besó.   Con una cara impúdica le dijo: ",
      "14": "  “Los sacrificios de ofrendas de paz están conmigo.   Hoy he pagado mis votos. ",
      "15": "  Por eso salí a tu encuentro,   para buscar diligentemente tu rostro,   y te he encontrado. ",
      "16": "  He extendido mi sofá con alfombras de tapiz,   con telas rayadas del hilo de Egipto. ",
      "17": "  He perfumado mi cama con mirra, áloe y canela. ",
      "18": "  Ven, vamos a saciarnos de amor hasta la mañana.   Consolémonos con el amor. ",
      "19": "  Porque mi marido no está en casa.   Ha hecho un largo viaje. ",
      "20": "  Se ha llevado una bolsa de dinero.   Volverá a casa con la luna llena”. ",
      "21": "  Con palabras persuasivas, ella lo desvió.   Con el halago de sus labios, lo sedujo. ",
      "22": "  La siguió inmediatamente,   como un buey va al matadero,   como un tonto que se mete en un lazo. ",
      "23": "  Hasta que una flecha le atraviese el hígado,   como un pájaro se apresura a la trampa,   y no sabe que le costará la vida. ",
      "24": "  Ahora, pues, hijos, escuchadme.   Presta atención a las palabras de mi boca. ",
      "25": "  No dejes que tu corazón se vuelva hacia sus caminos.   No te desvíes de sus caminos, ",
      "26": "  porque ha arrojado muchos heridos.   Sí, todos sus muertos son un poderoso ejército. ",
      "27": "  Su casa es el camino al Seol,     bajando a las habitaciones de la muerte."
    },
    "8": {
      "1": "  ¿No grita la sabiduría?   ¿La comprensión no levanta la voz? ",
      "2": "  En la cima de los lugares altos por cierto,   donde los caminos se encuentran, ella se para. ",
      "3": "  Junto a las puertas, a la entrada de la ciudad,   en las puertas de entrada, llora en voz alta: ",
      "4": "  “¡Os llamo a vosotros, hombres!   Envío mi voz a los hijos de la humanidad. ",
      "5": "  ¡Tú, simple, entiende la prudencia!   ¡Necios, tened un corazón comprensivo! ",
      "6": "  Escuchad, porque voy a hablar de cosas excelentes.   La apertura de mis labios es para las cosas correctas. ",
      "7": "  Porque mi boca dice la verdad.   La maldad es una abominación para mis labios. ",
      "8": "  Todas las palabras de mi boca son en justicia.   No hay nada torcido ni perverso en ellos. ",
      "9": "  Todo está claro para el que entiende,   derecho a los que encuentran el conocimiento. ",
      "10": "  Recibe mi instrucción antes que la plata,   conocimiento más que el oro de la elección. ",
      "11": "  Porque la sabiduría es mejor que los rubíes.   Todas las cosas que se puedan desear no se pueden comparar con ella. ",
      "12": "  “Yo, la sabiduría, he hecho de la prudencia mi morada.   Descubra el conocimiento y la discreción. ",
      "13": "  El temor a Yahvé es odiar el mal.   Odio el orgullo, la arrogancia, el mal camino y la boca perversa. ",
      "14": "  El consejo y el buen conocimiento son míos.   Tengo comprensión y poder. ",
      "15": "  Por mí reinan los reyes,   y los príncipes decretan la justicia. ",
      "16": "  Por mí gobiernan los príncipes,   nobles, y todos los gobernantes justos de la tierra. ",
      "17": "  Yo amo a los que me aman.   Los que me buscan con diligencia me encontrarán. ",
      "18": "  Conmigo están las riquezas, el honor,   riqueza duradera y prosperidad. ",
      "19": "  Mi fruto es mejor que el oro, sí, que el oro fino,   mi rendimiento que la plata de elección. ",
      "20": "  Yo ando en el camino de la justicia,   en medio de los caminos de la justicia, ",
      "21": "  para dar riqueza a los que me aman.   Lleno sus tesoros. ",
      "22": "  “Yahvé me poseyó en el comienzo de su obra,   ante sus hazañas de antaño. ",
      "23": "  Fui establecido desde siempre, desde el principio,   antes de que la tierra existiera. ",
      "24": "  Cuando no había profundidades, nací yo,   cuando no había manantiales que abundaran en agua. ",
      "25": "  Antes de que las montañas se asentaran en su lugar,   antes de las colinas, nací yo; ",
      "26": "  cuando aún no había hecho la tierra ni los campos,   ni el principio del polvo del mundo. ",
      "27": "  Cuando estableció los cielos, yo estaba allí.   Cuando estableció un círculo en la superficie de las profundidades, ",
      "28": "  cuando estableció las nubes de arriba,   cuando los manantiales de las profundidades se hicieron fuertes, ",
      "29": "  cuando le dio al mar su límite,   para que las aguas no violen su mandamiento,   cuando marcó los cimientos de la tierra, ",
      "30": "  entonces yo era el artesano a su lado.   Era una delicia día a día,   siempre regocijándose ante él, ",
      "31": "  regocijo en todo su mundo.   Mi deleite fue con los hijos de los hombres. ",
      "32": "  “Ahora, pues, hijos míos, escuchadme,   porque son dichosos los que guardan mis caminos. ",
      "33": "  Escucha la instrucción y sé sabio.   No lo rechaces. ",
      "34": "  Dichoso el hombre que me escucha,   vigilando diariamente a mis puertas,   esperando en los puestos de mi puerta. ",
      "35": "  Porque quien me encuentra, encuentra la vida,   y obtendrá el favor de Yahvé. ",
      "36": "  Pero el que peca contra mí hace daño a su propia alma.   Todos los que me odian aman la muerte”."
    },
    "9": {
      "1": "  La sabiduría ha construido su casa.   Ella ha esculpido sus siete pilares. ",
      "2": "  Ella ha preparado su carne.   Ha mezclado su vino.   También ha puesto su mesa. ",
      "3": "  Ha enviado a sus doncellas.   Llora desde los lugares más altos de la ciudad: ",
      "4": "  “¡El que sea sencillo, que se meta aquí!”   En cuanto al que está vacío de entendimiento, le dice, ",
      "5": "  “Ven, come un poco de mi pan,   ¡Bebe un poco del vino que he mezclado! ",
      "6": "  Deja tus costumbres sencillas y vive.   Camina por el camino del entendimiento”. ",
      "7": "  El que corrige a un burlón invita al insulto.   Quien reprende a un malvado invita al abuso. ",
      "8": "  No reprendas al burlón, para que no te odie.   Reprende a una persona sabia, y te amará. ",
      "9": "  Instruye a una persona sabia, y será aún más sabia.   Enseña a una persona justa, y aumentará su aprendizaje. ",
      "10": "  El temor de Yahvé es el principio de la sabiduría.   El conocimiento del Santo es la comprensión. ",
      "11": "  Porque por mí se multiplicarán tus días.   Los años de tu vida se incrementarán. ",
      "12": "  Si eres sabio, eres sabio por ti mismo.   Si te burlas, sólo tú lo soportarás. ",
      "13": "  La mujer tonta es ruidosa,   indisciplinado, y no sabe nada. ",
      "14": "  Se sienta a la puerta de su casa,   en un asiento en los lugares altos de la ciudad, ",
      "15": "  para llamar a los que pasan,   que siguen su camino, ",
      "16": "  “El que sea sencillo, que se meta aquí”.   En cuanto a aquel que está vacío de entendimiento, ella le dice, ",
      "17": "  “El agua robada es dulce.   La comida que se come en secreto es agradable”. ",
      "18": "  Pero no sabe que los espíritus difuntos están allí,   que sus invitados están en las profundidades del Seol.  "
    },
    "10": {
      "1": "Los proverbios de Salomón.   Un hijo sabio hace un padre feliz;   pero un hijo insensato trae dolor a su madre. ",
      "2": "  Los tesoros de la maldad no aprovechan nada,   pero la justicia libra de la muerte. ",
      "3": "  Yahvé no permitirá que el alma del justo pase hambre,   pero aleja el deseo de los malvados. ",
      "4": "  Se hace pobre el que trabaja con mano perezosa,   pero la mano del diligente trae riqueza. ",
      "5": "  El que recoge en verano es un hijo sabio,   pero el que duerme durante la cosecha es un hijo que causa vergüenza. ",
      "6": "  Las bendiciones están en la cabeza de los justos,   pero la violencia cubre la boca de los malvados. ",
      "7": "  La memoria de los justos es bendita,   pero el nombre de los malvados se pudrirá. ",
      "8": "  Los sabios de corazón aceptan los mandamientos,   pero un tonto parlanchín caerá. ",
      "9": "  El que camina sin culpa, camina con seguridad,   pero el que pervierte sus caminos será descubierto. ",
      "10": "  El que guiña el ojo causa dolor,   pero un tonto parlanchín caerá. ",
      "11": "  La boca del justo es un manantial de vida,   pero la violencia cubre la boca de los malvados. ",
      "12": "  El odio suscita conflictos,   pero el amor cubre todos los males. ",
      "13": "  La sabiduría se encuentra en los labios del que tiene discernimiento,   pero la vara es para la espalda del que no tiene entendimiento. ",
      "14": "  Los sabios acumulan conocimientos,   pero la boca del necio está cerca de la ruina. ",
      "15": "  La riqueza del rico es su ciudad fuerte.   La destrucción de los pobres es su pobreza. ",
      "16": "  El trabajo de los justos conduce a la vida.   El aumento de los malvados lleva al pecado. ",
      "17": "  Está en el camino de la vida quien hace caso a la corrección,   pero el que abandona la reprensión extravía a los demás. ",
      "18": "  El que oculta el odio tiene labios mentirosos.   El que profiere una calumnia es un necio. ",
      "19": "  En la multitud de palabras no falta la desobediencia,   pero el que refrena sus labios lo hace con sabiduría. ",
      "20": "  La lengua del justo es como la plata selecta.   El corazón de los malvados es de poco valor. ",
      "21": "  Los labios de los justos alimentan a muchos,   pero los necios mueren por falta de entendimiento. ",
      "22": "  La bendición de Yahvé trae riqueza,   y no le añade ningún problema. ",
      "23": "  El placer del necio es hacer la maldad,   pero la sabiduría es un hombre de placer del entendimiento. ",
      "24": "  Lo que los malvados temen los alcanzará,   pero el deseo de los justos será concedido. ",
      "25": "  Cuando el torbellino pasa, el malvado ya no existe;   pero los justos se mantienen firmes para siempre. ",
      "26": "  Como vinagre a los dientes y como humo a los ojos,   así es el perezoso para los que lo envían. ",
      "27": "  El temor a Yahvé prolonga los días,   pero los años de los impíos serán acortados. ",
      "28": "  La perspectiva de los justos es la alegría,   pero la esperanza de los malvados perecerá. ",
      "29": "  El camino de Yahvé es una fortaleza para los rectos,   sino que es una destrucción para los obreros de la iniquidad. ",
      "30": "  Los justos nunca serán eliminados,   pero los malvados no habitarán la tierra. ",
      "31": "  La boca del justo produce sabiduría,   pero la lengua perversa será cortada. ",
      "32": "  Los labios de los justos saben lo que es aceptable,   pero la boca de los malvados es perversa."
    },
    "11": {
      "1": "  Un balance falso es una abominación para Yahvé,   pero las pesas precisas son su deleite. ",
      "2": "  Cuando llega el orgullo, llega la vergüenza,   pero con la humildad viene la sabiduría. ",
      "3": "  La integridad de los rectos los guiará,   pero la perversidad de los traidores los destruirá. ",
      "4": "  Las riquezas no aprovechan en el día de la ira,   pero la justicia libra de la muerte. ",
      "5": "  La justicia del intachable dirigirá su camino,   pero el impío caerá por su propia maldad. ",
      "6": "  La justicia de los rectos los librará,   pero los infieles quedarán atrapados por los malos deseos. ",
      "7": "  Cuando un malvado muere, la esperanza perece,   y la expectativa de poder se queda en nada. ",
      "8": "  El justo es liberado de la angustia,   y el malvado ocupa su lugar. ",
      "9": "  Con su boca el impío destruye a su prójimo,   pero los justos serán liberados a través del conocimiento. ",
      "10": "  Cuando le va bien al justo, la ciudad se alegra.   Cuando los malvados perecen, hay gritos. ",
      "11": "  Por la bendición de los rectos, la ciudad es exaltada,   pero es derribado por la boca de los malvados. ",
      "12": "  El que desprecia a su prójimo está vacío de sabiduría,   pero un hombre comprensivo mantiene su paz. ",
      "13": "  El que trae chismes traiciona una confianza,   pero el que tiene un espíritu de confianza es el que guarda un secreto. ",
      "14": "  Donde no hay una guía sabia, la nación cae,   pero en la multitud de consejeros está la victoria. ",
      "15": "  El que es garante de un extraño sufrirá por ello,   pero el que rechaza las prendas de garantía está seguro. ",
      "16": "  Una mujer con gracia obtiene honor,   pero los hombres violentos obtienen riquezas. ",
      "17": "  El hombre misericordioso hace el bien a su propia alma,   pero el que es cruel molesta a su propia carne. ",
      "18": "  Los malvados ganan sueldos engañosos,   pero el que siembra justicia cosecha una recompensa segura. ",
      "19": "  El que es verdaderamente justo obtiene la vida.   El que persigue el mal obtiene la muerte. ",
      "20": "  Los perversos de corazón son una abominación para Yahvé,   pero aquellos cuyos caminos son intachables son su deleite. ",
      "21": "  Ciertamente, el hombre malo no quedará impune,   pero la descendencia  de los justos será liberada. ",
      "22": "  Como un anillo de oro en el hocico de un cerdo,   es una hermosa mujer que carece de discreción. ",
      "23": "  El deseo de los justos es sólo bueno.   La expectativa de los malvados es la ira. ",
      "24": "  Hay uno que dispersa y aumenta aún más.   Hay uno que retiene más de lo debido, pero gana la pobreza. ",
      "25": "  El alma liberal será engordada.   El que riega será también regado. ",
      "26": "  La gente maldice a quien retiene el grano,   pero la bendición caerá sobre la cabeza de quien lo venda. ",
      "27": "  El que busca diligentemente el bien, busca el favor,   pero el que busca el mal, éste vendrá a él. ",
      "28": "  El que confía en sus riquezas caerá,   pero el justo florecerá como la hoja verde. ",
      "29": "  El que molesta a su propia casa heredará el viento.   El necio servirá al sabio de corazón. ",
      "30": "  El fruto del justo es un árbol de vida.   El que es sabio gana almas. ",
      "31": "  He aquí que los justos serán recompensados en la tierra,   ¡cuanto más el malvado y el pecador!"
    },
    "12": {
      "1": "  Quien ama la corrección ama el conocimiento,   pero el que odia la reprensión es un estúpido. ",
      "2": "  El hombre bueno obtendrá el favor de Yahvé,   pero condenará a un hombre de planes malvados. ",
      "3": "  El hombre no será establecido por la maldad,   pero la raíz de los justos no se moverá. ",
      "4": "  Una mujer digna es la corona de su marido,   pero una esposa desgraciada es como la podredumbre en sus huesos. ",
      "5": "  Los pensamientos del justo son justos,   pero el consejo de los malvados es engañoso. ",
      "6": "  Las palabras de los malvados consisten en acechar la sangre,   pero el discurso de los rectos los rescata. ",
      "7": "  Los malvados son derribados y ya no existen,   pero la casa de los justos permanecerá. ",
      "8": "  El hombre será alabado según su sabiduría,   pero el que tiene una mente torcida será despreciado. ",
      "9": "  Mejor es el que es poco conocido, y tiene un servidor,   que el que se honra y carece de pan. ",
      "10": "  El hombre justo respeta la vida de su animal,   pero la misericordia de los malvados es cruel. ",
      "11": "  El que cultiva su tierra tendrá pan en abundancia,   pero el que persigue fantasías está vacío de entendimiento. ",
      "12": "  El malvado desea el botín de los hombres malos,   pero la raíz de los justos florece. ",
      "13": "  Un hombre malvado está atrapado por el pecado de los labios,   pero los justos saldrán de las dificultades. ",
      "14": "  El hombre será satisfecho con el bien por el fruto de su boca.   El trabajo de las manos del hombre le será recompensado. ",
      "15": "  El camino del necio es correcto a sus propios ojos,   pero el que es sabio escucha el consejo. ",
      "16": "  Un tonto muestra su fastidio el mismo día,   pero quien pasa por alto un insulto es prudente. ",
      "17": "  El que es veraz testifica con honestidad,   pero un testigo falso miente. ",
      "18": "  Hay uno que habla con imprudencia, como el que atraviesa una espada,   pero la lengua del sabio sana. ",
      "19": "  Los labios de la verdad se establecerán para siempre,   pero una lengua mentirosa es sólo momentánea. ",
      "20": "  El engaño está en el corazón de los que traman el mal,   pero la alegría llega a los promotores de la paz. ",
      "21": "  Al justo no le sucederá ningún mal,   pero los malvados se llenarán de maldad. ",
      "22": "  Los labios mentirosos son una abominación para Yahvé,   pero los que hacen la verdad son su deleite. ",
      "23": "  El hombre prudente guarda sus conocimientos,   pero el corazón de los necios proclama la necedad. ",
      "24": "  Las manos de los diligentes gobernarán,   pero la pereza termina en trabajo esclavo. ",
      "25": "  La ansiedad en el corazón del hombre lo agobia,   pero una palabra amable lo alegra. ",
      "26": "  Una persona justa es prudente en la amistad,   pero el camino de los malvados los extravía. ",
      "27": "  El perezoso no asa su juego,   pero las posesiones de los hombres diligentes son apreciadas. ",
      "28": "  En el camino de la justicia está la vida;   en su camino no hay muerte."
    },
    "13": {
      "1": "  Un hijo sabio escucha la instrucción de su padre,   pero un burlón no escucha la reprimenda. ",
      "2": "  Por el fruto de sus labios, el hombre disfruta de las cosas buenas,   pero los infieles ansían la violencia. ",
      "3": "  El que guarda su boca guarda su alma.   El que abre mucho los labios se arruina. ",
      "4": "  El alma del perezoso desea y no tiene nada,   pero el deseo de los diligentes será plenamente satisfecho. ",
      "5": "  El hombre justo odia la mentira,   pero un hombre malvado trae vergüenza y desgracia. ",
      "6": "  La justicia guarda el camino de la integridad,   pero la maldad derriba al pecador. ",
      "7": "  Hay quienes pretenden ser ricos, pero no tienen nada.   Hay algunos que fingen ser pobres, pero tienen grandes riquezas. ",
      "8": "  El rescate de la vida de un hombre es su riqueza,   pero los pobres no escuchan las amenazas. ",
      "9": "  La luz de los justos brilla con fuerza,   pero la lámpara de los malvados se apaga. ",
      "10": "  La soberbia sólo genera peleas,   pero la sabiduría está en las personas que aceptan los consejos. ",
      "11": "  La riqueza obtenida de forma deshonesta se desvanece,   pero el que recoge a mano lo hace crecer. ",
      "12": "  La esperanza postergada enferma el corazón,   pero cuando el anhelo se cumple, es un árbol de la vida. ",
      "13": "  Quien desprecia la instrucción lo pagará,   pero el que respeta una orden será recompensado. ",
      "14": "  La enseñanza de los sabios es un manantial de vida,   para alejarse de las trampas de la muerte. ",
      "15": "  El buen entendimiento gana el favor,   pero el camino de los infieles es duro. ",
      "16": "  Todo hombre prudente actúa desde el conocimiento,   pero un tonto expone la locura. ",
      "17": "  Un mensajero malvado cae en problemas,   pero un enviado de confianza consigue la curación. ",
      "18": "  La pobreza y la vergüenza llegan al que rechaza la disciplina,   pero el que hace caso a la corrección será honrado. ",
      "19": "  El anhelo cumplido es dulce para el alma,   pero los tontos detestan apartarse del mal. ",
      "20": "  El que camina con los sabios se hace sabio,   pero el compañero de los tontos sufre daños. ",
      "21": "  La desgracia persigue a los pecadores,   pero la prosperidad recompensa a los justos. ",
      "22": "  Un buen hombre deja una herencia a los hijos de sus hijos,   pero la riqueza del pecador se almacena para el justo. ",
      "23": "  En los campos de los pobres hay abundancia de alimentos,   pero la injusticia la barre. ",
      "24": "  El que ahorra la vara odia a su hijo,   pero quien lo ama tiene cuidado de disciplinarlo. ",
      "25": "  El justo come para satisfacer su alma,   pero el vientre de los malvados pasa hambre."
    },
    "14": {
      "1": "  Toda mujer sabia construye su casa,   pero la insensata lo derriba con sus propias manos. ",
      "2": "  El que camina en su rectitud teme a Yahvé,   pero el que es perverso en sus caminos lo desprecia. ",
      "3": "  La palabrería del necio trae una vara a su espalda,   pero los labios de los sabios los protegen. ",
      "4": "  Donde no hay bueyes, el pesebre está limpio,   pero mucho aumento es por la fuerza del buey. ",
      "5": "  Un testigo veraz no miente,   pero un testigo falso vierte mentiras. ",
      "6": "  El burlón busca la sabiduría y no la encuentra,   pero el conocimiento llega fácilmente a una persona con criterio. ",
      "7": "  Aléjate de un hombre necio,   porque no encontrarás conocimiento en sus labios. ",
      "8": "  La sabiduría del prudente es pensar en su camino,   pero la locura de los tontos es el engaño. ",
      "9": "  Los tontos se burlan de la expiación de los pecados,   pero entre los rectos hay buena voluntad. ",
      "10": "  El corazón conoce su propia amargura y alegría;   no los compartirá con un extraño. ",
      "11": "  La casa de los malvados será derribada,   pero la tienda de los rectos florecerá. ",
      "12": "  Hay un camino que le parece correcto al hombre,   pero al final lleva a la muerte. ",
      "13": "  Incluso en la risa el corazón puede estar triste,   y la alegría puede acabar en pesadez. ",
      "14": "  El infiel será pagado por sus propios caminos;   De la misma manera, un buen hombre será recompensado por sus caminos. ",
      "15": "  Un hombre sencillo se lo cree todo,   pero el hombre prudente considera cuidadosamente sus caminos. ",
      "16": "  El hombre sabio teme y evita el mal,   pero el tonto es un calentón y un imprudente. ",
      "17": "  El que se enoja rápidamente comete una locura,   y un hombre astuto es odiado. ",
      "18": "  Los simples heredan la locura,   pero los prudentes están coronados por el conocimiento. ",
      "19": "  Los malos se inclinan ante los buenos,   y los malvados a las puertas de los justos. ",
      "20": "  El pobre es rechazado incluso por su propio vecino,   pero el rico tiene muchos amigos. ",
      "21": "  El que desprecia a su prójimo peca,   pero el que se apiada de los pobres es bienaventurado. ",
      "22": "  ¿No se extravían los que traman el mal?   Pero el amor y la fidelidad pertenecen a los que planean el bien. ",
      "23": "  En todo trabajo duro hay un beneficio,   pero la palabrería de los labios sólo conduce a la pobreza. ",
      "24": "  La corona de los sabios es su riqueza,   pero la necedad de los necios los corona de necedad. ",
      "25": "  Un testigo veraz salva almas,   pero un testigo falso es engañoso. ",
      "26": "  En el temor de Yahvé hay una fortaleza segura,   y será un refugio para sus hijos. ",
      "27": "  El temor de Yahvé es una fuente de vida,   apartando a la gente de las trampas de la muerte. ",
      "28": "  En la multitud del pueblo está la gloria del rey,   pero en la falta de gente está la destrucción del príncipe. ",
      "29": "  El que es lento para la ira tiene un gran entendimiento,   pero el que tiene un temperamento rápido muestra la locura. ",
      "30": "  La vida del cuerpo es un corazón en paz,   pero la envidia pudre los huesos. ",
      "31": "  El que oprime a los pobres desprecia a su Hacedor,   pero el que es bondadoso con el necesitado lo honra. ",
      "32": "  El impío es abatido en su calamidad,   pero en la muerte, el justo tiene un refugio. ",
      "33": "  La sabiduría descansa en el corazón de quien tiene entendimiento,   y se da a conocer incluso en el interior de los tontos. ",
      "34": "  La justicia enaltece a una nación,   pero el pecado es una desgracia para cualquier pueblo. ",
      "35": "  El favor del rey es para el siervo que trata con sabiduría,   pero su ira es hacia el que causa vergüenza."
    },
    "15": {
      "1": "  Una respuesta amable aleja la ira,   pero una palabra dura despierta la ira. ",
      "2": "  La lengua de los sabios alaba el conocimiento,   pero las bocas de los necios destilan necedad. ",
      "3": "  Los ojos de Yahvé están en todas partes,   vigilando a los malos y a los buenos. ",
      "4": "  La lengua amable es un árbol de vida,   pero el engaño en ella aplasta el espíritu. ",
      "5": "  Un tonto desprecia la corrección de su padre,   pero el que hace caso a la reprensión demuestra prudencia. ",
      "6": "  En la casa del justo hay muchos tesoros,   pero los ingresos de los malvados traen problemas. ",
      "7": "  Los labios de los sabios difunden el conocimiento;   no así con el corazón de los tontos. ",
      "8": "  El sacrificio que hacen los impíos es una abominación para Yahvé,   pero la oración de los rectos es su delicia. ",
      "9": "  El camino de los impíos es una abominación para Yahvé,   pero ama al que sigue la justicia. ",
      "10": "  Hay una disciplina severa para quien abandona el camino.   Quien odia la reprensión morirá. ",
      "11": "  El Seol  y Abadón están delante de Yahvé —   ¡cuánto más el corazón de los hijos de los hombres! ",
      "12": "  Al burlón no le gusta ser reprendido;   no acudirá a los sabios. ",
      "13": "  Un corazón alegre hace una cara alegre,   pero un corazón dolorido rompe el espíritu. ",
      "14": "  El corazón de quien tiene entendimiento busca el conocimiento,   pero la boca de los necios se alimenta de la necedad. ",
      "15": "  Todos los días de los afligidos son miserables,   pero el que tiene un corazón alegre disfruta de una fiesta continua. ",
      "16": "  Mejor es lo pequeño, con el temor de Yahvé,   que un gran tesoro con problemas. ",
      "17": "  Mejor es una cena de hierbas, donde está el amor,   que un ternero engordado con odio. ",
      "18": "  El hombre iracundo suscita la discordia,   pero el que es lento para la ira apacigua los conflictos. ",
      "19": "  El camino del perezoso es como un terreno de espinas,   pero el camino de los rectos es una carretera. ",
      "20": "  El hijo sabio alegra al padre,   pero un necio desprecia a su madre. ",
      "21": "  La insensatez es la alegría para quien está vacío de sabiduría,   pero un hombre de entendimiento mantiene su camino recto. ",
      "22": "  Donde no hay consejo, los planes fracasan;   pero en una multitud de consejeros se establecen. ",
      "23": "  La alegría llega al hombre con la respuesta de su boca.   ¡Qué buena es una palabra en el momento adecuado! ",
      "24": "  El camino de la vida lleva a los sabios hacia arriba,   para evitar que baje al Seol.   ",
      "25": "  El Señor desarraigará la casa de los soberbios,   pero mantendrá intactos los límites de la viuda. ",
      "26": "  Yahvé detesta los pensamientos de los malvados,   pero los pensamientos de los puros son agradables. ",
      "27": "  El que está ávido de ganancia, perturba su propia casa,   pero el que odia los sobornos vivirá. ",
      "28": "  El corazón de los justos pesa las respuestas,   pero la boca de los malvados brota el mal. ",
      "29": "  Yahvé está lejos de los malvados,   pero él escucha la oración de los justos. ",
      "30": "  La luz de los ojos alegra el corazón.   Las buenas noticias dan salud a los huesos. ",
      "31": "  El oído que escucha la reprensión vive,   y estará en casa entre los sabios. ",
      "32": "  El que rechaza la corrección desprecia su propia alma,   pero el que escucha la reprensión obtiene la comprensión. ",
      "33": "  El temor de Yahvé enseña la sabiduría.   Antes del honor está la humildad."
    },
    "16": {
      "1": "  Los planes del corazón pertenecen al hombre,   pero la respuesta de la lengua es de Yahvé. ",
      "2": "  Todos los caminos del hombre son limpios ante sus propios ojos,   pero Yahvé sopesa los motivos. ",
      "3": "  Encomienda tus obras a Yahvé,   y tus planes tendrán éxito. ",
      "4": "  Yahvé ha hecho todo para su propio fin.   sí, incluso los malvados para el día del mal. ",
      "5": "  Todo el que es orgulloso de corazón es una abominación para Yahvé;   ciertamente no quedarán impunes. ",
      "6": "  Por la misericordia y la verdad se expía la iniquidad.   Por el temor a Yahvé los hombres se apartan del mal. ",
      "7": "  Cuando los caminos del hombre agradan a Yahvé,   hace que hasta sus enemigos estén en paz con él. ",
      "8": "  Mejor es un poco con la justicia,   que los grandes ingresos con la injusticia. ",
      "9": "  El corazón del hombre planea su curso,   pero Yahvé dirige sus pasos. ",
      "10": "  Los juicios inspirados están en los labios del rey.   No traicionará su boca. ",
      "11": "  Las balanzas y los platillos honestos son de Yahvé;   todos los pesos de la bolsa son obra suya. ",
      "12": "  Es una abominación que los reyes hagan el mal,   porque el trono se establece por la justicia. ",
      "13": "  Los labios justos son la delicia de los reyes.   Valoran a quien dice la verdad. ",
      "14": "  La ira del rey es un mensajero de la muerte,   pero un hombre sabio lo apaciguará. ",
      "15": "  En la luz del rostro del rey está la vida.   Su favor es como una nube de la lluvia de primavera. ",
      "16": "  ¡Cuánto mejor es conseguir sabiduría que oro!   Sí, conseguir la comprensión es ser elegido más que la plata. ",
      "17": "  El camino de los rectos es apartarse del mal.   El que guarda su camino preserva su alma. ",
      "18": "  La soberbia precede a la destrucción,   y un espíritu arrogante antes de una caída. ",
      "19": "  Es mejor tener un espíritu humilde con los pobres,   que repartir el botín con los orgullosos. ",
      "20": "  El que presta atención a la Palabra encuentra la prosperidad.   Quien confía en Yahvé es bendecido. ",
      "21": "  Los sabios de corazón serán llamados prudentes.   El placer de los labios favorece la instrucción. ",
      "22": "  La comprensión es una fuente de vida para quien la tiene,   pero el castigo de los tontos es su locura. ",
      "23": "  El corazón del sabio instruye a su boca,   y añade el aprendizaje a sus labios. ",
      "24": "  Las palabras agradables son un panal,   dulce para el alma, y salud para los huesos. ",
      "25": "  Hay un camino que le parece correcto al hombre,   pero al final lleva a la muerte. ",
      "26": "  El apetito del trabajador trabaja para él,   porque su boca le urge. ",
      "27": "  Un hombre sin valor trama una travesura.   Su discurso es como un fuego abrasador. ",
      "28": "  El hombre perverso suscita conflictos.   Un susurrador separa a los amigos cercanos. ",
      "29": "  El hombre violento seduce a su prójimo,   y lo lleva por un camino que no es bueno. ",
      "30": "  El que guiña los ojos para tramar perversidades,   el que comprime sus labios, está empeñado en el mal. ",
      "31": "  Las canas son una corona de gloria.   Se consigue con una vida de rectitud. ",
      "32": "  El que es lento para la ira es mejor que el poderoso;   el que gobierna su espíritu, que el que toma una ciudad. ",
      "33": "  La suerte está echada,   pero todas sus decisiones provienen de Yahvé."
    },
    "17": {
      "1": "  Mejor es un bocado seco con tranquilidad,   que una casa llena de fiestas con disputas. ",
      "2": "  El siervo que trata con sabiduría gobernará sobre el hijo que causa vergüenza,   y tendrá parte en la herencia entre los hermanos. ",
      "3": "  El crisol es para la plata y el horno para el oro,   pero Yahvé pone a prueba los corazones. ",
      "4": "  El malhechor hace caso a los labios perversos.   Un mentiroso da oídos a una lengua traviesa. ",
      "5": "  Quien se burla de los pobres reprocha a su Hacedor.   El que se alegra de la calamidad no quedará impune. ",
      "6": "  Los hijos de los niños son la corona de los ancianos;   la gloria de los niños son sus padres. ",
      "7": "  Un discurso excelente no es propio de un tonto,   y mucho menos los labios mentirosos se ajustan a un príncipe. ",
      "8": "  El soborno es una piedra preciosa a los ojos de quien lo da;   a donde quiera que vaya, prospera. ",
      "9": "  El que cubre una ofensa promueve el amor;   pero quien repite un asunto separa a los mejores amigos. ",
      "10": "  Una reprimenda entra más profundamente en quien tiene entendimiento   que cien latigazos a un tonto. ",
      "11": "  Un hombre malvado sólo busca la rebelión;   por lo que se enviará un cruel mensajero contra él. ",
      "12": "  Que una osa despojada de sus cachorros se encuentre con un hombre,   más que un tonto en su locura. ",
      "13": "  Quien recompensa el mal por el bien,   el mal no saldrá de su casa. ",
      "14": "  El comienzo de la contienda es como romper una presa,   Por lo tanto, hay que detener la contienda antes de que se produzca una pelea. ",
      "15": "  El que justifica al impío y el que condena al justo,   ambos por igual son una abominación para Yahvé. ",
      "16": "  ¿Por qué hay dinero en la mano de un tonto para comprar sabiduría,   ya que no tiene entendimiento? ",
      "17": "  Un amigo ama en todo momento;   y un hermano ha nacido para la adversidad. ",
      "18": "  Un hombre sin entendimiento golpea las manos,   y se convierte en una garantía en presencia de su vecino. ",
      "19": "  El que ama la desobediencia ama la contienda.   El que construye una puerta alta busca la destrucción. ",
      "20": "  El que tiene un corazón perverso no encuentra la prosperidad,   y el que tiene una lengua engañosa cae en problemas. ",
      "21": "  El que se convierte en padre de un tonto se apena.   El padre de un tonto no tiene alegría. ",
      "22": "  Un corazón alegre es una buena medicina,   pero un espíritu aplastado seca los huesos. ",
      "23": "  Un malvado recibe un soborno en secreto,   para pervertir los caminos de la justicia. ",
      "24": "  La sabiduría está ante el rostro del que tiene entendimiento,   pero los ojos de un necio vagan hasta los confines de la tierra. ",
      "25": "  El hijo insensato causa dolor a su padre,   y la amargura a la que lo parió. ",
      "26": "  También castigar al justo no es bueno,   ni para azotar a los funcionarios por su integridad. ",
      "27": "  El que ahorra sus palabras tiene conocimiento.   El que es ecuánime es un hombre comprensivo. ",
      "28": "  Incluso el necio, cuando guarda silencio, es considerado sabio.   Cuando cierra los labios, se cree que tiene criterio."
    },
    "18": {
      "1": "  El hombre que se aísla persigue el egoísmo,   y desafía todo buen juicio. ",
      "2": "  El necio no se deleita en el entendimiento,   pero sólo para revelar su propia opinión. ",
      "3": "  Cuando llega la maldad, llega también el desprecio,   y con la vergüenza viene la desgracia. ",
      "4": "  Las palabras de la boca del hombre son como aguas profundas.   La fuente de la sabiduría es como un arroyo que fluye. ",
      "5": "  Ser parcial con las caras de los malvados no es bueno,   ni para privar a los inocentes de la justicia. ",
      "6": "  Los labios de un necio entran en disputa,   y su boca invita a los golpes. ",
      "7": "  La boca del necio es su perdición,   y sus labios son una trampa para su alma. ",
      "8": "  Las palabras de un chismoso son como bocados delicados:   bajan a lo más íntimo de la persona. ",
      "9": "  El que es flojo en su trabajo   es hermano de aquel que es maestro de la destrucción. ",
      "10": "  El nombre de Yahvé es una torre fuerte:   los justos corren hacia él, y están a salvo. ",
      "11": "  La riqueza del rico es su ciudad fuerte,   como un muro inescalable en su propia imaginación. ",
      "12": "  Antes de la destrucción, el corazón del hombre es orgulloso,   pero antes del honor está la humildad. ",
      "13": "  El que responde antes de escuchar,   que es una locura y una vergüenza para él. ",
      "14": "  El espíritu del hombre lo sostendrá en la enfermedad,   pero un espíritu aplastado, ¿quién puede soportarlo? ",
      "15": "  El corazón del que discierne obtiene conocimiento.   El oído del sabio busca el conocimiento. ",
      "16": "  El regalo de un hombre le da cabida,   y lo lleva ante los grandes hombres. ",
      "17": "  El que defiende su causa primero parece tener razón.   hasta que llega otro y lo interroga. ",
      "18": "  El lote resuelve las disputas,   y mantiene separados a los fuertes. ",
      "19": "  Un hermano ofendido es más difícil que una ciudad fortificada.   Las disputas son como los barrotes de una fortaleza. ",
      "20": "  El estómago del hombre se llena con el fruto de su boca.   Con la cosecha de sus labios está satisfecho. ",
      "21": "  La muerte y la vida están en poder de la lengua;   los que la aman comerán su fruto. ",
      "22": "  Quien encuentra una esposa, encuentra algo bueno,   y obtiene el favor de Yahvé. ",
      "23": "  Los pobres piden clemencia,   pero los ricos responden con dureza. ",
      "24": "  Un hombre con muchos compañeros puede arruinarse,   pero hay un amigo que está más cerca que un hermano."
    },
    "19": {
      "1": "  Mejor es el pobre que camina en su integridad   que el que es perverso de labios y es necio. ",
      "2": "  No es bueno tener celo sin conocimiento,   ni precipitarse con los pies y perder el camino. ",
      "3": "  La necedad del hombre subvierte su camino;   su corazón se enfurece contra Yahvé. ",
      "4": "  La riqueza añade muchos amigos,   pero el pobre está separado de su amigo. ",
      "5": "  El testigo falso no quedará impune.   El que vierte mentiras no quedará libre. ",
      "6": "  Muchos pedirán el favor de un gobernante,   y todo el mundo es amigo de un hombre que da regalos. ",
      "7": "  Todos los parientes de los pobres le rehúyen;   ¡cuánto más le evitan sus amigos!   Los persigue con súplicas, pero se han ido. ",
      "8": "  El que obtiene la sabiduría ama su propia alma.   El que guarda el entendimiento encontrará el bien. ",
      "9": "  El testigo falso no quedará impune.   El que dice mentiras perecerá. ",
      "10": "  La vida delicada no es apropiada para un tonto,   y mucho menos que un siervo se enseñoree de los príncipes. ",
      "11": "  La discreción del hombre lo hace lento para la ira.   Es su gloria pasar por alto una ofensa. ",
      "12": "  La ira del rey es como el rugido de un león,   pero su favor es como el rocío en la hierba. ",
      "13": "  El hijo necio es la calamidad de su padre.   Las peleas de una esposa son un goteo continuo. ",
      "14": "  La casa y las riquezas son una herencia de los padres,   pero una esposa prudente es de Yahvé. ",
      "15": "  La pereza hace caer en un profundo sueño.   El alma ociosa sufrirá hambre. ",
      "16": "  El que guarda el mandamiento guarda su alma,   pero el que es despectivo en sus caminos, morirá. ",
      "17": "  El que se apiada de los pobres presta a Yahvé;   lo recompensará. ",
      "18": "  Disciplina a tu hijo, porque hay esperanza;   no seas partícipe de su muerte. ",
      "19": "  El hombre de mal genio debe pagar la pena,   porque si lo rescatas, debes hacerlo de nuevo. ",
      "20": "  Escucha el consejo y recibe la instrucción,   para que seas sabio en tu fin último. ",
      "21": "  Hay muchos planes en el corazón del hombre,   pero el consejo de Yahvé prevalecerá. ",
      "22": "  Lo que hace que un hombre sea deseado es su bondad.   Un pobre es mejor que un mentiroso. ",
      "23": "  El temor a Yahvé conduce a la vida, y luego a la satisfacción;   descansa y no será tocado por los problemas. ",
      "24": "  El perezoso entierra su mano en el plato;   no volverá a llevárselo a la boca. ",
      "25": "  Azotad a un burlón, y el simple aprenderá la prudencia;   Reprende al que tiene entendimiento, y obtendrá conocimiento. ",
      "26": "  El que roba a su padre y aleja a su madre   es un hijo que causa vergüenza y trae reproche. ",
      "27": "  Si dejas de escuchar la instrucción, hijo mío,   te alejarás de las palabras del conocimiento. ",
      "28": "  Un testigo corrupto se burla de la justicia,   y la boca de los malvados engulle iniquidad. ",
      "29": "  Las penasestán preparadas para los burlones,   y golpes para las espaldas de los tontos.  "
    },
    "20": {
      "1": "  El vino es un burlador y la cerveza es un pendenciero.   Quien se deja llevar por ellos no es sabio. ",
      "2": "  El terror de un rey es como el rugido de un león.   Quien lo provoque a la ira perderá su propia vida. ",
      "3": "  Es un honor para un hombre mantenerse alejado de las disputas,   pero todos los tontos se pelearán. ",
      "4": "  El perezoso no arará a causa del invierno;   por lo que mendigará en la cosecha, y no tendrá nada. ",
      "5": "  El consejo en el corazón del hombre es como las aguas profundas,   pero un hombre comprensivo lo sacará. ",
      "6": "  Muchos hombres pretenden ser hombres de amor indefectible,   pero ¿quién puede encontrar un hombre fiel? ",
      "7": "  El hombre justo camina con integridad.   Benditos sean sus hijos después de él. ",
      "8": "  Un rey que se sienta en el trono del juicio   dispersa todo el mal con sus ojos. ",
      "9": "  ¿Quién puede decir: “He purificado mi corazón”?   Estoy limpio y sin pecado”. ",
      "10": "  Pesos y medidas diferentes,   ambos por igual son una abominación para Yahvé. ",
      "11": "  Hasta un niño se da a conocer por sus actos,   si su trabajo es puro, y si es correcto. ",
      "12": "  El oído que oye y el ojo que ve,   Yahvé ha hecho incluso a los dos. ",
      "13": "  No ames el sueño, no sea que llegues a la pobreza.   Abre los ojos y te saciarás de pan. ",
      "14": "  “No es bueno, no es bueno”, dice el comprador;   pero cuando se va por su camino, entonces se jacta. ",
      "15": "  Hay oro y abundancia de rubíes,   pero los labios del conocimiento son una joya rara. ",
      "16": "  Toma la prenda de quien pone una garantía para un extranjero;   y lo tienen en prenda por una mujer descarriada. ",
      "17": "  La comida fraudulenta es dulce para el hombre,   pero después se le llena la boca de grava. ",
      "18": "  Los planes se establecen mediante asesoramiento;   ¡con una guía sabia haces la guerra! ",
      "19": "  El que va de un lado a otro como portador de cuentos revela secretos;   por tanto, no te hagas compañía de quien abre mucho los labios. ",
      "20": "  El que maldiga a su padre o a su madre,   su lámpara se apagará en la oscuridad de las tinieblas. ",
      "21": "  Una herencia ganada rápidamente al principio   no será bendecido al final. ",
      "22": "  No digas: “Pagaré el mal”.   Espera a Yahvé, y él te salvará. ",
      "23": "  Yahvé detesta las diferencias de peso,   y las balanzas deshonestas no son agradables. ",
      "24": "  Los pasos del hombre son de Yahvé;   ¿cómo puede entonces el hombre entender su camino? ",
      "25": "  Es una trampa para el hombre hacer una entrega precipitada,   para luego considerar sus votos. ",
      "26": "  Un rey sabio selecciona a los malvados,   y conduce el trillo sobre ellos. ",
      "27": "  El espíritu del hombre es la lámpara de Yahvé,   buscando en todas sus partes más íntimas. ",
      "28": "  El amor y la fidelidad mantienen al rey a salvo.   Su trono se sustenta en el amor. ",
      "29": "  La gloria de los jóvenes es su fuerza.   El esplendor de los ancianos son sus canas. ",
      "30": "  Los golpes que hieren limpian el mal,   y los golpes purgan las partes más íntimas.  "
    },
    "21": {
      "1": "  El corazón del rey está en la mano de Yahvé como las corrientes de agua.   Lo convierte en lo que desea. ",
      "2": "  Todo camino del hombre es correcto a sus propios ojos,   pero Yahvé pesa los corazones. ",
      "3": "  Hacer rectitud y justicia   es más aceptable para Yahvé que el sacrificio. ",
      "4": "  Una mirada elevada y un corazón orgulloso,   la lámpara de los malvados, es el pecado. ",
      "5": "  Los planes de los diligentes seguramente conducen a la ganancia;   y todo el que se precipita seguramente se precipita a la pobreza. ",
      "6": "  Conseguir tesoros por una lengua mentirosa   es un vapor fugaz para los que buscan la muerte. ",
      "7": "  La violencia de los malvados los ahuyentará,   porque se niegan a hacer lo que es correcto. ",
      "8": "  El camino del culpable es tortuoso,   pero la conducta del inocente es recta. ",
      "9": "  Es mejor habitar en el rincón de la azotea   que compartir una casa con una mujer contenciosa. ",
      "10": "  El alma del malvado desea el mal;   su prójimo no encuentra misericordia en sus ojos. ",
      "11": "  Cuando el burlador es castigado, el simple adquiere sabiduría.   Cuando el sabio se instruye, recibe conocimiento. ",
      "12": "  El Justo considera la casa de los malvados,   y lleva a los malvados a la ruina. ",
      "13": "  El que detenga sus oídos ante el clamor de los pobres,   también gritará, pero no será escuchado. ",
      "14": "  Un regalo en secreto apacigua la ira,   y un soborno en el manto, una fuerte ira. ",
      "15": "  El justo se alegra de hacer justicia;   sino que es una destrucción para los obreros de la iniquidad. ",
      "16": "  El hombre que se aleja del camino del entendimiento   descansará en la asamblea de los espíritus difuntos. ",
      "17": "  El que ama el placer será un hombre pobre.   El que ama el vino y el aceite no será rico. ",
      "18": "  El impío es un rescate para el justo,   los traidores por los rectos. ",
      "19": "  Es mejor habitar en una tierra desierta,   que con una mujer contenciosa e inquieta. ",
      "20": "  Hay un tesoro precioso y aceite en la morada de los sabios,   pero el necio se lo traga. ",
      "21": "  El que sigue la justicia y la bondad   encuentra la vida, la justicia y el honor. ",
      "22": "  Un hombre sabio escala la ciudad de los poderosos,   y hace bajar la fuerza de su confianza. ",
      "23": "  El que cuida su boca y su lengua   guarda su alma de los problemas. ",
      "24": "  El hombre orgulloso y arrogante — “burlador” es su nombre —   trabaja en la arrogancia del orgullo. ",
      "25": "  El deseo del perezoso lo mata,   porque sus manos se niegan a trabajar. ",
      "26": "  Hay quienes codician con avidez todo el día;   pero los justos dan y no retienen. ",
      "27": "  El sacrificio de los malvados es una abominación —   ¡cuánto más, cuando lo trae con una mente perversa! ",
      "28": "  El testigo falso perecerá.   Un hombre que escucha habla con la eternidad. ",
      "29": "  El malvado endurece su rostro;   pero en cuanto a los rectos, él establece sus caminos. ",
      "30": "  No hay sabiduría ni entendimiento   ni consejo contra Yahvé. ",
      "31": "  El caballo está preparado para el día de la batalla;   pero la victoria es de Yahvé.  "
    },
    "22": {
      "1": "  El buen nombre es más deseable que las grandes riquezas,   y el favor amoroso es mejor que la plata y el oro. ",
      "2": "  Los ricos y los pobres tienen esto en común:   Yahvé es el creador de todos ellos. ",
      "3": "  Un hombre prudente ve el peligro y se esconde;   pero los simples pasan, y sufren por ello. ",
      "4": "  El resultado de la humildad y el temor a Yahvé   es la riqueza, el honor y la vida. ",
      "5": "  Espinas y trampas hay en el camino de los malvados;   quien guarda su alma se aleja de ellos. ",
      "6": "  Educa al niño en el camino que debe seguir,   y cuando sea viejo no se apartará de él. ",
      "7": "  Los ricos dominan a los pobres.   El prestatario está al servicio del prestamista. ",
      "8": "  El que siembra maldad cosecha problemas,   y la vara de su furia será destruida. ",
      "9": "  El que tiene un ojo generoso será bendecido,   porque comparte su comida con los pobres. ",
      "10": "  Expulsa al burlón, y se acabará la contienda;   sí, se acabarán las peleas y los insultos. ",
      "11": "  El que ama la pureza de corazón y habla con gracia   es el amigo del rey. ",
      "12": "  Los ojos de Yahvé vigilan el conocimiento,   pero frustra las palabras de los infieles. ",
      "13": "  El perezoso dice: “¡Hay un león afuera!   Me matarán en las calles”. ",
      "14": "  La boca de una adúltera es un pozo profundo.   El que está bajo la ira de Yahvé caerá en ella. ",
      "15": "  La locura está ligada al corazón de un niño;   la vara de la disciplina lo aleja de él. ",
      "16": "  El que oprime al pobre para su propio aumento y el que da al rico,   ambos llegan a la pobreza. ",
      "17": "  Vuelve tu oído y escucha las palabras de los sabios.   Aplica tu corazón a mis enseñanzas. ",
      "18": "  Porque es una cosa agradable si las guardas dentro de ti,   si todos ellos están listos en sus labios. ",
      "19": "  Hoy te enseño, incluso a ti,   para que tu confianza esté en Yahvé. ",
      "20": "  ¿No te he escrito treinta cosas excelentes   de consejo y conocimiento, ",
      "21": "  Para enseñarte la verdad, palabras fiables,   para dar respuestas sólidas a los que te enviaron? ",
      "22": "  No exploten al pobre porque es pobre;   y no aplastar a los necesitados en los tribunales; ",
      "23": "  porque Yahvé defenderá su caso,   y saquean la vida de los que los saquean. ",
      "24": "  No te hagas amigo de un hombre de mal genio.   No te asocies con quien alberga ira, ",
      "25": "  para que no aprendas sus caminos   y atrapar tu alma. ",
      "26": "  No seas de los que golpean las manos,   de los que son garantía de las deudas. ",
      "27": "  Si no tienes medios para pagar,   ¿por qué debería quitarte la cama de debajo de ti? ",
      "28": "  No muevas el antiguo mojón   que sus padres han establecido. ",
      "29": "  ¿Ves ena un hombre hábil en su trabajo?   Servirá a los reyes.   No servirá a los hombres oscuros.  "
    },
    "23": {
      "1": "  Cuando te sientas a comer con una regla,   considera con diligencia lo que tienes delante; ",
      "2": "  poner un cuchillo en la garganta   si eres un hombre dado al apetito. ",
      "3": "  No estés deseoso de sus delicias,   ya que son alimentos engañosos. ",
      "4": "  No te canses de ser rico.   En tu sabiduría, muestra moderación. ",
      "5": "  ¿Por qué pones tus ojos en lo que no es?   Porque ciertamente le salen alas como a un águila y vuela en el cielo. ",
      "6": "  No comas la comida de quien tiene un ojo tacaño,   y no anhelan sus delicias, ",
      "7": "  pues mientras piensa en el costo, así es.   “¡Come y bebe!”, te dice,   pero su corazón no está contigo. ",
      "8": "  Vomitarás el bocado que has comido   y desperdiciar tus agradables palabras. ",
      "9": "  No hables al oído de un tonto,   porque despreciará la sabiduría de tus palabras. ",
      "10": "  No muevas el antiguo mojón.   No invadan los campos de los huérfanos, ",
      "11": "  para su Defensor es fuerte.   Él defenderá su caso contra ti. ",
      "12": "  Aplica tu corazón a la instrucción,   y tus oídos a las palabras del conocimiento. ",
      "13": "  No retengas la corrección de un niño.   Si lo castigas con la vara, no morirá. ",
      "14": "  Castígalo con la vara,   y salvar su alma del Seol.   ",
      "15": "  Hijo mío, si tu corazón es sabio,   entonces mi corazón se alegrará, incluso el mío. ",
      "16": "  Sí, mi corazón se alegrará   cuando tus labios dicen lo que es correcto. ",
      "17": "  Que tu corazón no envidie a los pecadores,   sino que teman a Yahvé todo el día. ",
      "18": "  Ciertamente, hay una esperanza futura,   y tu esperanza no será cortada. ",
      "19": "  Escucha, hijo mío, y sé sabio,   ¡y mantener tu corazón en el camino correcto! ",
      "20": "  No te encuentres entre los que beben demasiado vino,   o los que se atiborran de carne; ",
      "21": "  porque el borracho y el glotón se volverán pobres;   y la somnolencia los viste de harapos. ",
      "22": "  Escucha a tu padre que te dio la vida,   y no desprecies a tu madre cuando sea vieja. ",
      "23": "  Compra la verdad y no la vendas.   Consigue sabiduría, disciplina y comprensión. ",
      "24": "  El padre de los justos tiene una gran alegría.   Quien engendra un hijo sabio se deleita en él. ",
      "25": "  ¡Que se alegren tu padre y tu madre!   ¡Que se alegre la que te parió! ",
      "26": "  Hijo mío, dame tu corazón;   y que tus ojos se mantengan en mis caminos. ",
      "27": "  Para una prostituta es un pozo profundo;   y una esposa caprichosa es un pozo estrecho. ",
      "28": "  Sí, está al acecho como un ladrón,   y aumenta los infieles entre los hombres. ",
      "29": "  ¿Quién se lamenta?   ¿Quién tiene pena?   ¿Quién tiene conflictos?   ¿Quién tiene quejas?   ¿Quién tiene moretones innecesarios?   ¿Quién tiene los ojos inyectados en sangre? ",
      "30": "  Los que se quedan mucho tiempo en el vino;   los que van a buscar vino mezclado. ",
      "31": "  No mires el vino cuando está rojo,   cuando brilla en la taza,   cuando baja sin problemas. ",
      "32": "  Al final, muerde como una serpiente,   y envenena como una víbora. ",
      "33": "  Tus ojos verán cosas extrañas,   y tu mente imaginará cosas confusas. ",
      "34": "  Sí, serás como el que se acuesta en medio del mar,   o como el que se acuesta encima de los aparejos: ",
      "35": "  “¡Me golpearon, y no me hirieron!   ¡Me golpean y no lo siento!   ¿Cuándo me despertaré? Puedo hacerlo de nuevo.   Buscaré más”.  "
    }
  }
};

