
	
export const bib_verses = {
  "leviticus": {
    "10": {
      "1": "Nadab y Abiú, hijos de Aarón, tomaron cada uno su incensario, pusieron fuego en él y colocaron incienso, y ofrecieron delante de Yavé un fuego extraño que él no les había mandado.",
      "2": "Salió fuego de delante de Yavé y los devoró, y murieron delante de Yavé. ",
      "3": "Entonces Moisés le dijo a Aarón: “Esto es lo que habló Yahvé, diciendo,   Me mostraré santo a los que se acerquen a mí,   y ante todo el pueblo seré glorificado”. Aarón calló.",
      "4": "Moisés llamó a Misael y a Elzafán, hijos de Uziel, tío de Aarón, y les dijo: “Acérquense y saquen a sus hermanos de delante del santuario fuera del campamento.”",
      "5": "Se acercaron, pues, y los llevaron en sus túnicas fuera del campamento, como Moisés había dicho. ",
      "6": "Moisés dijo a Aarón, a Eleazar y a Itamar, sus hijos: “No os soltéis el pelo de la cabeza, ni os rasguéis las vestiduras, para que no muráis, y para que no se enoje con toda la congregación; pero que vuestros hermanos, toda la casa de Israel, se lamenten por el fuego que Yahvé ha encendido.",
      "7": "No saldrás de la puerta de la Tienda del Encuentro, para que no mueras, porque el aceite de la unción de Yavé está sobre ti.” Ellos hicieron lo que dijo Moisés.",
      "8": "Entonces Yahvé le dijo a Aarón:",
      "9": "“Tú y tus hijos no deben beber vino ni bebida fuerte cada vez que entren en la Tienda del Encuentro, o morirán. Esto será un estatuto para siempre a lo largo de vuestras generaciones.",
      "10": "Debes distinguir entre lo santo y lo común, y entre lo inmundo y lo limpio.",
      "11": "Enseñarás a los hijos de Israel todos los estatutos que Yahvé les ha dicho por medio de Moisés.” ",
      "12": "Moisés dijo a Aarón, a Eleazar y a Itamar, sus hijos que habían quedado: “Tomad la ofrenda que queda de las ofrendas encendidas a Yahvé, y comedla sin levadura junto al altar, porque es santísima;",
      "13": "y la comeréis en lugar santo, porque es vuestra porción y la de vuestros hijos, de las ofrendas encendidas a Yahvé; porque así me ha sido ordenado.",
      "14": "El pecho agitado y el muslo cargado los comeréis en un lugar limpio, tú, tus hijos y tus hijas contigo, porque son dados como tu porción y la de tus hijos, de los sacrificios de las ofrendas de paz de los hijos de Israel.",
      "15": "Traerán el muslo cargado y el pecho ondulado con las ofrendas encendidas de la grasa, para mecerlo como ofrenda mecida ante Yahvé. Será de ustedes, y de sus hijos con ustedes, como porción para siempre, como lo ha ordenado Yahvé”. ",
      "16": "Moisés indagó diligentemente sobre el macho cabrío de la ofrenda por el pecado, y, he aquí, fue quemado. Se enojó con Eleazar y con Itamar, los hijos de Aarón que habían quedado, diciendo:",
      "17": "“¿Por qué no habéis comido la ofrenda por el pecado en el lugar del santuario, ya que es santísima, y él os la ha dado para que carguéis con la iniquidad de la congregación, para hacer expiación por ellos ante Yahvé?",
      "18": "He aquí que su sangre no fue llevada al interior del santuario. Ciertamente debisteis comerlo en el santuario, como yo lo ordené”. ",
      "19": "Aarón habló a Moisés: “He aquí que hoy han ofrecido su ofrenda por el pecado y su holocausto ante Yahvé, y me han sucedido cosas como éstas. Si yo hubiera comido hoy la ofrenda por el pecado, ¿habría sido agradable a los ojos de Yahvé?” ",
      "20": "Cuando Moisés lo oyó, le pareció bien."
    },
    "11": {
      "1": "Yahvé habló a Moisés y a Aarón, diciéndoles:",
      "2": "“Hablad a los hijos de Israel, diciendo: “Estos son los seres vivos que podéis comer de entre todos los animales que hay en la tierra.",
      "3": "Todo lo que tiene pezuña hendida y rumia entre los animales, eso podéis comer. ",
      "4": "“‘Sin embargo, no comeréis de los que rumian, ni de los que parten la pezuña: el camello, porque rumia pero no tiene la pezuña partida, es inmundo para vosotros.",
      "5": "El huracán,  porque mastica el bolo alimenticio, pero no tiene la pezuña partida, es impuro para ti.",
      "6": "La liebre, por masticar el bolo alimenticio, pero sin tener la pezuña abierta, es impura para ustedes.",
      "7": "El cerdo, porque tiene la pezuña hendida y es de pezuña hendida, pero no rumia, es inmundo para ti.",
      "8": "No comerás su carne. No tocarás sus cadáveres. Son impuros para ti. ",
      "9": "“‘Puedes comer de todo lo que está en las aguas: todo lo que tiene aletas y escamas en las aguas, en los mares y en los ríos, eso puedes comer.",
      "10": "Todo lo que no tiene aletas y escamas en los mares y ríos, todo lo que se mueve en las aguas, y todos los seres vivos que están en las aguas, son una abominación para ti,",
      "11": "y los detestarás. No comerás su carne, y aborrecerás sus cadáveres.",
      "12": "Todo lo que no tenga aletas ni escamas en las aguas es una abominación para ti. ",
      "13": "“‘Aborrecerás éstas entre las aves; no se comerán porque son una abominación: el águila, el buitre, el buitre negro,",
      "14": "el milano real, cualquier tipo de milano negro,",
      "15": "cualquier tipo de cuervo,",
      "16": "el búho cornudo, el búho chillón, la gaviota, cualquier tipo de halcón,",
      "17": "el búho pequeño, el cormorán, el búho grande,",
      "18": "el búho blanco, el búho del desierto, el águila pescadora,",
      "19": "la cigüeña, cualquier tipo de garza, la abubilla y el murciélago. ",
      "20": "“‘Todos los insectos voladores que andan a cuatro patas son una abominación para ti.",
      "21": "Sin embargo, puedes comer estos: de todos los reptiles alados que andan a cuatro patas, que tienen patas largas y articuladas para saltar sobre la tierra.",
      "22": "Incluso de estos podréis comer: cualquier tipo de langosta, cualquier tipo de cateta, cualquier tipo de grillo y cualquier tipo de saltamontes.",
      "23": "Pero todos los reptiles alados que tienen cuatro patas son una abominación para ustedes. ",
      "24": "“‘Por ellos quedarás impuro: el que toque sus cadáveres quedará impuro hasta la noche.",
      "25": "El que lleve alguna parte de sus cadáveres se lavará la ropa y quedará impuro hasta la noche. ",
      "26": "“‘Todo animal que tenga una pezuña partida que no esté completamente dividida, o que no rumie, es impuro para ti. Todo el que los toque será impuro.",
      "27": "Todo lo que vaya sobre sus patas, entre todos los animales que van a cuatro patas, son inmundos para ti. El que toque sus cadáveres quedará impuro hasta la noche.",
      "28": "El que lleve su cadáver se lavará la ropa y quedará impuro hasta la noche. Son inmundos para ti. ",
      "29": "“‘Estos son los inmundos para vosotros entre los reptiles que se arrastran por la tierra: la comadreja, la rata, cualquier clase de lagarto grande,",
      "30": "la salamanquesa, y el lagarto monitor, el lagarto de pared, el eslizón y el camaleón.",
      "31": "Estos son los impuros para vosotros entre todos los que se arrastran. El que los toque cuando estén muertos será impuro hasta la noche.",
      "32": "Todo lo que caiga sobre ellos cuando estén muertos será impuro; ya sea un recipiente de madera, ropa, piel o saco, cualquiera que sea el recipiente con el que se haga cualquier trabajo, deberá ser puesto en agua, y quedará impuro hasta la noche. Entonces quedará limpio.",
      "33": "Toda vasija de barro en la que caiga cualquiera de ellas y todo lo que haya en ella será impuro. Lo romperás.",
      "34": "Todo alimento que se pueda comer y que esté empapado en agua será impuro. Toda la bebida que se beba en cualquiera de esos recipientes será inmunda.",
      "35": "Todo aquello sobre lo que caiga una parte de su cuerpo será inmundo; ya sea el horno o la cocina para las ollas, se romperá en pedazos. Son inmundos, y serán inmundos para vosotros.",
      "36": "Sin embargo, el manantial o la cisterna donde se recoja el agua serán limpios, pero lo que toque su cadáver será impuro.",
      "37": "Si parte de su cadáver cae sobre cualquier semilla que se vaya a sembrar, será limpia.",
      "38": "Pero si se pone agua sobre la semilla, y parte de su cadáver cae sobre ella, será impuro para ti. ",
      "39": "“‘Si algún animal de los que puedes comer muere, el que toque su cadáver quedará impuro hasta la noche.",
      "40": "El que coma de su cadáver lavará sus vestidos y quedará impuro hasta la noche. El que lleve su cadáver lavará su ropa y quedará impuro hasta la noche. ",
      "41": "“‘Todo lo que se arrastra por la tierra es una abominación. No se comerá.",
      "42": "Todo lo que ande sobre su vientre, y todo lo que ande a cuatro patas, o todo lo que tenga muchas patas, todo lo que se arrastra sobre la tierra, no lo comeréis, porque es una abominación.",
      "43": "No os haréis abominables con ningún reptil que se arrastre. No os haréis inmundos con ellos, para que os contaminéis con ellos.",
      "44": "Porque yo soy Yahvé, vuestro Dios. Santificaos, pues, y sed santos, porque yo soy santo. No os contaminaréis con ningún animal que se mueva sobre la tierra.",
      "45": "Porque yo soy Yahvé, que os he sacado de la tierra de Egipto para ser vuestro Dios. Seréis, pues, santos, porque yo soy santo. ",
      "46": "“‘Esta es la ley del animal, del ave y de todo ser viviente que se mueve en las aguas, y de todo ser que se arrastra por la tierra,",
      "47": "para distinguir entre lo inmundo y lo limpio, y entre lo que se puede comer y lo que no se puede comer’”."
    },
    "12": {
      "1": "Yahvé habló a Moisés, diciendo:",
      "2": "“Habla a los hijos de Israel, diciendo: Si una mujer concibe y da a luz un hijo varón, será impura siete días; como en los días de su menstruación será impura.",
      "3": "Al octavo día se circuncidará la carne de su prepucio.",
      "4": "Ella permanecerá en la sangre de purificación treinta y tres días. No tocará ninguna cosa sagrada, ni entrará en el santuario, hasta que se completen los días de su purificación.",
      "5": "Pero si da a luz a una niña, será impura dos semanas, como en su período; y permanecerá en la sangre de purificación sesenta y seis días. ",
      "6": "“‘Cuando se completen los días de su purificación por un hijo o por una hija, ella traerá al sacerdote, a la puerta de la Tienda de Reunión, un cordero de un año para el holocausto, y un pichón o una tórtola, para el sacrificio por el pecado.",
      "7": "Él la ofrecerá ante Yahvé y hará expiación por ella; entonces quedará limpia de la fuente de su sangre. “‘Esta es la ley para la que da a luz, sea macho o hembra.",
      "8": "Si no puede comprar un cordero, tomará dos tórtolas o dos pichones: uno para el holocausto y el otro para el sacrificio por el pecado. El sacerdote hará expiación por ella, y quedará limpia”."
    },
    "13": {
      "1": "Yahvé habló a Moisés y a Aarón, diciendo:",
      "2": "“Cuando un hombre tenga una hinchazón en la piel de su cuerpo, o una costra, o una mancha brillante, y se convierta en la piel de su cuerpo en la plaga de la lepra, entonces será llevado al sacerdote Aarón o a uno de sus hijos, los sacerdotes.",
      "3": "El sacerdote examinará la plaga en la piel del cuerpo. Si el pelo de la plaga se ha vuelto blanco, y el aspecto de la plaga es más profundo que la piel del cuerpo, se trata de una plaga de lepra; entonces el sacerdote lo examinará y lo declarará impuro.",
      "4": "Si la mancha es blanca en la piel de su cuerpo, y su apariencia no es más profunda que la piel, y su pelo no se ha vuelto blanco, entonces el sacerdote aislará a la persona infectada durante siete días.",
      "5": "El sacerdote lo examinará al séptimo día. Si en sus ojos la plaga está detenida y la plaga no se ha extendido en la piel, entonces el sacerdote lo aislará por siete días más.",
      "6": "El sacerdote lo examinará de nuevo al séptimo día. Si la peste ha desaparecido y no se ha extendido por la piel, el sacerdote lo declarará limpio. Se trata de una costra. Se lavará la ropa y quedará limpio.",
      "7": "Pero si la costra se extiende en la piel después de haberse presentado al sacerdote para su purificación, se presentará de nuevo al sacerdote.",
      "8": "El sacerdote lo examinará, y si la costra se ha extendido por la piel, el sacerdote lo declarará impuro. Es lepra. ",
      "9": "“Cuando la plaga de la lepra esté en un hombre, será llevado al sacerdote;",
      "10": "y el sacerdote lo examinará. Si hay una hinchazón blanca en la piel, que ha vuelto blanco el cabello, y hay carne viva en la hinchazón,",
      "11": "se trata de una lepra crónica en la piel de su cuerpo, y el sacerdote lo declarará impuro. No lo aislará, porque ya está impuro. ",
      "12": "“Si la lepra brota por toda la piel, y la lepra cubre toda la piel del infectado, desde la cabeza hasta los pies, según lo que le parezca al sacerdote,",
      "13": "entonces el sacerdote lo examinará. Si la lepra ha cubierto toda su carne, lo declarará limpio de la plaga. Todo se ha vuelto blanco: está limpio.",
      "14": "Pero cuando la carne viva aparezca en él, será impuro.",
      "15": "El sacerdote examinará la carne viva y lo declarará impuro: la carne viva es impura. Es lepra.",
      "16": "O si la carne viva se vuelve y se convierte en blanca, entonces vendrá al sacerdote.",
      "17": "El sacerdote lo examinará. Si la llaga se ha vuelto blanca, el sacerdote lo declarará limpio de la llaga. Está limpio. ",
      "18": "“Cuando el cuerpo tenga un forúnculo en la piel, y se haya curado,",
      "19": "y en el lugar del forúnculo haya una hinchazón blanca, o una mancha brillante, de color blanco rojizo, entonces se mostrará al sacerdote.",
      "20": "El sacerdote lo examinará. Si su aspecto es más profundo que la piel, y su pelo se ha vuelto blanco, el sacerdote lo declarará impuro. Es la plaga de la lepra. Ha brotado en el forúnculo.",
      "21": "Pero si el sacerdote lo examina, y he aquí que no hay pelos blancos en él, y no está más profundo que la piel, sino que es tenue, entonces el sacerdote lo aislará siete días.",
      "22": "Si se extiende en la piel, el sacerdote lo declarará impuro. Es una plaga.",
      "23": "Pero si la mancha brillante permanece en su lugar y no se ha extendido, es la cicatriz del forúnculo; y el sacerdote lo declarará limpio. ",
      "24": "“O cuando el cuerpo tenga una quemadura de fuego en su piel, y la carne viva de la quemadura se convierta en una mancha brillante, de color blanco rojizo o blanco,",
      "25": "entonces el sacerdote lo examinará; y he aquí que si el pelo de la mancha brillante se ha vuelto blanco, y su aspecto es más profundo que la piel, es lepra. Ha brotado en el quemado, y el sacerdote lo declarará impuro. Es la plaga de la lepra.",
      "26": "Pero si el sacerdote lo examina y ve que no hay pelo blanco en la mancha, y que no es más profunda que la piel, sino que se ha desvanecido, entonces el sacerdote lo aislará siete días.",
      "27": "El sacerdote lo examinará al séptimo día. Si se ha extendido en la piel, el sacerdote lo declarará impuro. Es la plaga de la lepra.",
      "28": "Si la mancha brillante permanece en su lugar y no se ha extendido en la piel, sino que se ha desvanecido, es la hinchazón de la quemadura, y el sacerdote lo declarará limpio, porque es la cicatriz de la quemadura. ",
      "29": "“Cuando un hombre o una mujer tenga una plaga en la cabeza o en la barba,",
      "30": "entonces el sacerdote examinará la plaga; y si su aspecto es más profundo que la piel, y el pelo en ella es amarillo y fino, entonces el sacerdote lo declarará impuro. Se trata de una picazón. Es lepra de la cabeza o de la barba.",
      "31": "Si el sacerdote examina la plaga de prurito, y he aquí que su aspecto no es más profundo que la piel, y no hay pelo negro en ella, entonces el sacerdote aislará a la persona infectada de prurito durante siete días.",
      "32": "Al séptimo día el sacerdote examinará la plaga; y he aquí que si la picazón no se ha extendido, y no hay pelo amarillo en ella, y la apariencia de la picazón no es más profunda que la piel,",
      "33": "entonces será afeitado, pero no afeitará la picazón. Entonces el sacerdote aislará al que tiene la picazón siete días más.",
      "34": "Al séptimo día, el sacerdote examinará el prurito; y si el prurito no se ha extendido en la piel, y su apariencia no es más profunda que la piel, entonces el sacerdote lo declarará limpio. Se lavará la ropa y quedará limpio.",
      "35": "Pero si la picazón se extiende en la piel después de su limpieza,",
      "36": "entonces el sacerdote lo examinará; y si la picazón se ha extendido en la piel, el sacerdote no buscará el pelo amarillo; es impuro.",
      "37": "Pero si en sus ojos se ha detenido la picazón y le ha crecido pelo negro, entonces la picazón está curada. Está limpio. El sacerdote lo declarará limpio. ",
      "38": "“Cuando un hombre o una mujer tenga manchas brillantes en la piel del cuerpo, incluso manchas blancas brillantes,",
      "39": "entonces el sacerdote los examinará. He aquí, si las manchas brillantes en la piel de su cuerpo son de color blanco opaco, es una erupción inofensiva. Ha brotado en la piel. Está limpio. ",
      "40": "“Si a un hombre se le cae el pelo de la cabeza, es calvo. Está limpio.",
      "41": "Si se le ha caído el pelo de la parte delantera de la cabeza, es calvo de frente. Está limpio.",
      "42": "Pero si en la cabeza calva o en la frente calva hay una plaga de color blanco rojizo, es lepra que brota en su cabeza calva o en su frente calva.",
      "43": "Entonces el sacerdote lo examinará. He aquí, si la hinchazón de la plaga es de color blanco rojizo en su cabeza calva o en su frente calva, como la apariencia de la lepra en la piel del cuerpo,",
      "44": "es un hombre leproso. Es impuro. El sacerdote lo declarará impuro. Su plaga está en su cabeza. ",
      "45": "“El leproso en el que se encuentre la plaga se vestirá con ropas rasgadas, y el cabello de su cabeza colgará suelto. Se cubrirá el labio superior y gritará: “¡Inmundo! Impuro!",
      "46": "Todo el tiempo que la plaga esté en él, será impuro. Es impuro. Vivirá solo. Su morada estará fuera del campamento. ",
      "47": "“También el vestido en el que esté la plaga de la lepra, sea de lana o de lino;",
      "48": "sea de urdimbre o de trama; de lino o de lana; sea de cuero o de cualquier cosa de cuero;",
      "49": "si la plaga es verdosa o rojiza en el vestido, o en el cuero, o en la urdimbre, o en la trama, o en cualquier cosa de cuero, es la plaga de la lepra, y será mostrada al sacerdote.",
      "50": "El sacerdote examinará la plaga y la aislará durante siete días.",
      "51": "Al séptimo día examinará la plaga. Si la plaga se ha extendido en el vestido, ya sea en la urdimbre o en la trama, o en la piel, cualquiera que sea el uso que se le dé a la piel, la plaga es un moho destructor. Es impuro.",
      "52": "Se quemará el vestido, ya sea en la urdimbre o en la trama, en la lana o en el lino, o en cualquier cosa de cuero, en el que esté la plaga, porque es un moho destructor. Se quemará en el fuego. ",
      "53": "“Si el sacerdote lo examina, y he aquí que la peste no se ha propagado en el vestido, ni en la urdimbre, ni en la trama, ni en nada de piel;",
      "54": "entonces el sacerdote ordenará que laven el objeto en que está la peste, y lo aislará siete días más.",
      "55": "Entonces el sacerdote lo examinará, después de lavar la plaga; y he aquí que si la plaga no ha cambiado de color, y la plaga no se ha propagado, es impuro; lo quemarás en el fuego. Es una mancha enmohecida, ya sea que la desnudez esté por dentro o por fuera.",
      "56": "Si el sacerdote mira, y he aquí que la plaga se ha desvanecido después de haberla lavado, entonces la arrancará del vestido, o de la piel, o de la urdimbre, o de la trama;",
      "57": "y si aparece de nuevo en el vestido, ya sea en la urdimbre, en la trama o en cualquier cosa de la piel, se está extendiendo. Quemarás con fuego lo que contenga la plaga.",
      "58": "El vestido, ya sea en la urdimbre o en la trama, o en cualquier cosa de piel que sea, que lavarás, si la peste se ha ido de ellos, se lavará por segunda vez, y quedará limpio.” ",
      "59": "Esta es la ley de la plaga del moho en una prenda de lana o de lino, ya sea en la urdimbre o en la trama, o en cualquier cosa de piel, para declararla limpia o para declararla impura."
    },
    "14": {
      "1": "Yahvé habló a Moisés, diciendo, ",
      "2": "“Esta será la ley del leproso el día de su purificación: Será llevado al sacerdote,",
      "3": "y el sacerdote saldrá del campamento. El sacerdote lo examinará. Si la plaga de la lepra se ha curado en el leproso,",
      "4": "entonces el sacerdote mandará que tomen para el que va a ser purificado dos aves vivas y limpias, madera de cedro, grana e hisopo.",
      "5": "El sacerdote les ordenará que maten una de las aves en una vasija de barro sobre agua corriente.",
      "6": "En cuanto a la ave viva, la tomará, así como la madera de cedro, la grana y el hisopo, y los mojará, junto con la ave viva, en la sangre de la ave matada sobre el agua corriente.",
      "7": "Rociará siete veces sobre el que ha de quedar limpio de la lepra, y lo declarará limpio, y dejará que el ave viva salga al campo. ",
      "8": "“El que vaya a ser purificado lavará su ropa, se afeitará todo el pelo y se bañará en agua, y quedará limpio. Después entrará en el campamento, pero permanecerá siete días fuera de su tienda.",
      "9": "Al séptimo día se afeitará todo el cabello de la cabeza, la barba y las cejas. Se afeitará todo el cabello. Lavará sus ropas y bañará su cuerpo con agua. Entonces quedará limpio. ",
      "10": "“Al octavo día tomará dos corderos machos sin defecto, una oveja de un año sin defecto, tres décimas de efa de harina fina para la ofrenda de harina, mezclada con aceite, y un tronco  de aceite.",
      "11": "El sacerdote que lo purifique pondrá al hombre que va a ser purificado, y esas cosas, delante de Yahvé, a la puerta de la Tienda del Encuentro. ",
      "12": "“El sacerdote tomará uno de los corderos machos y lo ofrecerá como ofrenda por el pecado, con el tronco de aceite, y los agitará como ofrenda mecida ante Yahvé.",
      "13": "Matará el cordero macho en el lugar donde se mata el sacrificio por el pecado y el holocausto, en el lugar del santuario; porque así como el sacrificio por el pecado es del sacerdote, también lo es el sacrificio por la culpa. Es algo muy sagrado.",
      "14": "El sacerdote tomará un poco de la sangre de la ofrenda por el pecado y la pondrá en la punta de la oreja derecha del que va a ser purificado, en el pulgar de su mano derecha y en el dedo gordo de su pie derecho.",
      "15": "El sacerdote tomará un poco del tronco de aceite y lo echará en la palma de su mano izquierda.",
      "16": "El sacerdote mojará su dedo derecho en el aceite que tiene en su mano izquierda, y rociará un poco del aceite con su dedo siete veces delante de Yahvé.",
      "17": "El sacerdote pondrá un poco del resto del aceite que tiene en su mano sobre la punta de la oreja derecha del que va a ser purificado, y sobre el pulgar de su mano derecha, y sobre el dedo gordo de su pie derecho, sobre la sangre de la ofrenda por la culpa.",
      "18": "El resto del aceite que tiene el sacerdote en su mano lo pondrá sobre la cabeza del que va a ser purificado, y el sacerdote hará expiación por él ante Yahvé. ",
      "19": "“El sacerdote ofrecerá la ofrenda por el pecado y hará la expiación por el que ha de ser purificado a causa de su impureza. Después matará el holocausto;",
      "20": "entonces el sacerdote ofrecerá el holocausto y la ofrenda sobre el altar. El sacerdote hará expiación por él, y quedará limpio. ",
      "21": "“Si es pobre y no puede pagar tanto, tomará un cordero macho como ofrenda por la culpa, para hacer expiación por él, y la décima parte de un efa  de harina fina mezclada con aceite para una ofrenda de harina, y un tronco  de aceite;",
      "22": "y dos tórtolas, o dos pichones de paloma, como pueda pagar; y una será una ofrenda por el pecado, y la otra un holocausto. ",
      "23": "“Al octavo día los traerá para su purificación al sacerdote, a la puerta de la Tienda del Encuentro, ante Yahvé.",
      "24": "El sacerdote tomará el cordero de la ofrenda por la culpa y el tronco de aceite, y el sacerdote los agitará como ofrenda mecida ante Yahvé.",
      "25": "Matará el cordero de la ofrenda por la culpa. El sacerdote tomará un poco de la sangre de la ofrenda por la culpa y la pondrá en la punta de la oreja derecha del que va a ser purificado, en el pulgar de su mano derecha y en el dedo gordo de su pie derecho.",
      "26": "El sacerdote verterá un poco del aceite en la palma de su mano izquierda;",
      "27": "y el sacerdote rociará con su dedo derecho un poco del aceite que tiene en su mano izquierda siete veces ante Yahvé.",
      "28": "Luego el sacerdote pondrá un poco del aceite que tiene en su mano sobre la punta de la oreja derecha del que va a ser purificado, y sobre el pulgar de su mano derecha, y sobre el dedo gordo de su pie derecho, en el lugar de la sangre de la ofrenda por la culpa.",
      "29": "El resto del aceite que está en la mano del sacerdote lo pondrá sobre la cabeza del que va a ser purificado, para hacer expiación por él ante Yahvé.",
      "30": "Ofrecerá una de las tórtolas o de los pichones de paloma, lo que pueda pagar,",
      "31": "de la clase que pueda pagar, la una para la ofrenda por el pecado y la otra para el holocausto, con la ofrenda. El sacerdote hará la expiación por el que ha de ser purificado ante Yahvé”. ",
      "32": "Esta es la ley para el que tiene la plaga de la lepra y no puede pagar el sacrificio para su purificación. ",
      "33": "Yahvé habló a Moisés y a Aarón, diciendo:",
      "34": "“Cuando hayáis entrado en la tierra de Canaán, que yo os doy en posesión, y pongo un moho que se extiende en una casa de la tierra de vuestra posesión,",
      "35": "entonces el dueño de la casa vendrá y avisará al sacerdote, diciendo: “Me parece que hay una especie de plaga en la casa.",
      "36": "El sacerdote ordenará que se vacíe la casa, antes de que el sacerdote entre a examinar la plaga, para que todo lo que haya en la casa no quede impuro. Después el sacerdote entrará a inspeccionar la casa.",
      "37": "Examinará la plaga; y si la plaga está en las paredes de la casa con vetas huecas, verdosas o rojizas, y parece ser más profunda que la pared,",
      "38": "entonces el sacerdote saldrá de la casa a la puerta de la misma, y cerrará la casa por siete días.",
      "39": "El sacerdote volverá al séptimo día y mirará. Si la peste se ha extendido por las paredes de la casa,",
      "40": "entonces el sacerdote mandará que saquen las piedras en las que está la peste, y las arrojen a un lugar inmundo fuera de la ciudad.",
      "41": "Hará que se raspe todo el interior de la casa. Echarán la argamasa que rasparon fuera de la ciudad en un lugar inmundo.",
      "42": "Tomarán otras piedras y las pondrán en el lugar de esas piedras; y tomará otra argamasa y enlucirá la casa. ",
      "43": "“Si la peste vuelve a brotar en la casa después de haber sacado las piedras, y después de haber raspado la casa, y después de haberla enlucido,",
      "44": "entonces el sacerdote entrará y mirará; y he aquí que si la peste se ha extendido en la casa, es un moho destructor en la casa. Es impura.",
      "45": "Derribará la casa, sus piedras y su madera, y toda la argamasa de la casa. Los sacará de la ciudad a un lugar inmundo. ",
      "46": "“Además, el que entre en la casa mientras está cerrada será impuro hasta la noche.",
      "47": "El que se acueste en la casa lavará su ropa, y el que coma en la casa lavará su ropa. ",
      "48": "“Si el sacerdote entra y la examina, y he aquí que la peste no se ha propagado en la casa, después de haberla enlucido, entonces el sacerdote declarará limpia la casa, porque la peste está curada.",
      "49": "Para limpiar la casa tomará dos aves, madera de cedro, grana e hisopo.",
      "50": "Matará una de las aves en una vasija de barro sobre agua corriente.",
      "51": "Tomará la madera de cedro, el hisopo, la grana y el ave viva, y los mojará en la sangre del ave sacrificada y en el agua corriente, y rociará la casa siete veces.",
      "52": "Limpiará la casa con la sangre del ave y con el agua corriente, con el ave viva, con la madera de cedro, con el hisopo y con la grana;",
      "53": "pero dejará que el ave viva salga de la ciudad al campo abierto. Así expiará la casa, y quedará limpia”. ",
      "54": "Esta es la ley para cualquier plaga de lepra, y para una picazón,",
      "55": "y para el moho destructor de un vestido, y para una casa,",
      "56": "y para una hinchazón, y para una costra, y para una mancha brillante;",
      "57": "para enseñar cuándo es impuro, y cuándo es limpio. Esta es la ley de la lepra."
    },
    "15": {
      "1": "Yahvé habló a Moisés y a Aarón, diciendo:",
      "2": "“Hablad a los hijos de Israel y decidles: ‘Cuando un hombre tenga flujo de su cuerpo, a causa de su flujo será impuro.",
      "3": "Esta será su impureza en su flujo: ya sea que su cuerpo corra con su flujo, o que su cuerpo se haya detenido por su flujo, es su impureza. ",
      "4": "“‘Todo lecho sobre el que se acueste el que tiene el flujo será impuro; y todo aquello sobre lo que se siente será impuro.",
      "5": "El que toque su lecho lavará su ropa y se bañará con agua, y quedará impuro hasta la noche.",
      "6": "El que se siente sobre cualquier cosa en la que se haya sentado el hombre que tiene el flujo, lavará su ropa, se bañará con agua y quedará impuro hasta la noche. ",
      "7": "“‘El que toque el cuerpo del que tiene el flujo se lavará la ropa y se bañará con agua, y quedará impuro hasta la noche. ",
      "8": "“‘Si el que tiene el flujo escupe sobre el que está limpio, entonces lavará su ropa y se bañará con agua, y quedará impuro hasta la noche. ",
      "9": "“‘Cualquier silla de montar que lleve el enfermo será impura.",
      "10": "El que toque cualquier cosa que haya estado debajo de él quedará impuro hasta la noche. El que lleve esas cosas se lavará la ropa y se bañará con agua, y quedará impuro hasta la noche. ",
      "11": "“‘Cualquiera que toque el que tiene el flujo, sin haberse lavado las manos con agua, lavará su ropa y se bañará con agua, y quedará impuro hasta la noche. ",
      "12": "“‘La vasija de barro que toque el que tiene la descarga, será rota; y toda vasija de madera será enjuagada en agua. ",
      "13": "“‘Cuando el que tiene flujo se limpie de su flujo, contará para sí siete días para su purificación, y lavará sus vestidos; y bañará su carne en agua corriente, y quedará limpio. ",
      "14": "“‘Al octavo día tomará dos tórtolas o dos pichones de paloma, y se presentará ante Yahvé a la puerta de la Tienda del Encuentro, y los entregará al sacerdote.",
      "15": "El sacerdote los ofrecerá, uno como ofrenda por el pecado y el otro como holocausto. El sacerdote hará la expiación por él ante Yavé por su liberación. ",
      "16": "“‘Si un hombre tiene una emisión de semen, se lavará con agua toda su carne y quedará impuro hasta la noche.",
      "17": "Toda la ropa y toda la piel sobre la que haya semen se lavará con agua, y quedará impura hasta la noche.",
      "18": "Si un hombre se acuesta con una mujer y hay emisión de semen, ambos se bañarán con agua y quedarán impuros hasta la noche. ",
      "19": "“‘Si una mujer tiene flujo, y su flujo en su carne es de sangre, estará en su impureza siete días. Quien la toque será impuro hasta la noche. ",
      "20": "“‘Todo lo que ella se acueste en su impureza será impuro. Todo lo que ella se siente será impuro.",
      "21": "El que toque su lecho lavará su ropa y se bañará en agua, y quedará impuro hasta la noche.",
      "22": "El que toque algo sobre lo que ella se siente, lavará su ropa, se bañará con agua y quedará impuro hasta la noche.",
      "23": "Si está en la cama o en cualquier cosa sobre la que ella se siente, cuando la toque será impuro hasta la noche. ",
      "24": "“‘Si alguno se acuesta con ella, y su flujo menstrual está sobre él, será impuro siete días; y toda cama en la que se acueste será impura. ",
      "25": "“‘Si una mujer tiene una descarga de su sangre muchos días fuera del tiempo de su período, o si tiene una descarga más allá del tiempo de su período, todos los días de la descarga de su impureza serán como en los días de su período. Será impura.",
      "26": "Toda cama en la que se acueste durante todos los días de su flujo será para ella como la cama de su período. Todo aquello sobre lo que se siente será impuro, como la impureza de su menstruación.",
      "27": "Quien toque estas cosas quedará impuro, lavará su ropa y se bañará con agua, y quedará impuro hasta la noche. ",
      "28": "“‘Pero si se limpia de su flujo, contará para sí siete días, y después de eso quedará limpia.",
      "29": "Al octavo día tomará dos tórtolas o dos pichones y los llevará al sacerdote, a la puerta de la Tienda de reunión.",
      "30": "El sacerdote ofrecerá una como ofrenda por el pecado, y la otra como holocausto; y el sacerdote hará expiación por ella ante Yahvé por la impureza de su flujo. ",
      "31": "“‘Así separarás a los hijos de Israel de su impureza, para que no mueran en su impureza cuando contaminen mi tabernáculo que está en medio de ellos’”. ",
      "32": "Esta es la ley del que tiene flujo, y del que tiene emisión de semen, de modo que es impuro por ello;",
      "33": "y de la que tiene la regla, y del hombre o la mujer que tiene flujo, y del que se acuesta con ella que es impuro."
    },
    "16": {
      "1": "Yahvé habló a Moisés después de la muerte de los dos hijos de Aarón, cuando se acercaron ante Yahvé y murieron;",
      "2": "y Yahvé dijo a Moisés: “Dile a Aarón, tu hermano, que no entre en ningún momento en el Lugar Santísimo, dentro del velo, delante del propiciatorio que está sobre el arca, para que no muera, porque me apareceré en la nube sobre el propiciatorio. ",
      "3": "“Aarón entrará en el santuario con un novillo para el sacrificio por el pecado y un carnero para el holocausto.",
      "4": "Se pondrá la túnica de lino sagrada. Tendrá los pantalones de lino sobre su cuerpo, y se pondrá la faja de lino, y se vestirá con el turbante de lino. Son las vestimentas sagradas. Bañará su cuerpo con agua y se las pondrá.",
      "5": "Tomará de la congregación de los hijos de Israel dos machos cabríos para el sacrificio por el pecado y un carnero para el holocausto. ",
      "6": "“Aarón ofrecerá el toro de la ofrenda por el pecado, que es para él, y hará expiación por él y por su casa.",
      "7": "Tomará los dos machos cabríos y los pondrá delante de Yavé, a la puerta de la Tienda del Encuentro.",
      "8": "Aarón echará suertes sobre los dos machos cabríos: una suerte para Yavé, y la otra suerte para el chivo expiatorio.",
      "9": "Aarón presentará el macho cabrío sobre el que haya caído la suerte para Yahvé, y lo ofrecerá como ofrenda por el pecado.",
      "10": "Pero el macho cabrío sobre el que cayó la suerte para el chivo expiatorio será presentado vivo ante Yavé, para hacer expiación por él, para enviarlo como chivo expiatorio al desierto. ",
      "11": "“Aarón presentará el toro del sacrificio por el pecado, que es para él, y hará la expiación por sí mismo y por su casa, y matará el toro del sacrificio por el pecado que es para él.",
      "12": "Tomará un incensario lleno de carbones encendidos del altar, delante de Yavé, y dos puñados de incienso aromático machacado, y lo llevará al interior del velo.",
      "13": "Pondrá el incienso sobre el fuego delante de Yavé, para que la nube del incienso cubra el propiciatorio que está sobre el pacto, a fin de que no muera.",
      "14": "Tomará parte de la sangre del toro y la rociará con su dedo sobre el propiciatorio que está al oriente; y delante del propiciatorio rociará parte de la sangre con su dedo siete veces. ",
      "15": "“Entonces matará el macho cabrío de la ofrenda por el pecado que es para el pueblo, y llevará su sangre al interior del velo, y hará con su sangre lo mismo que hizo con la sangre del toro, y la rociará sobre el propiciatorio y delante del propiciatorio.",
      "16": "Hará la expiación por el Lugar Santo, a causa de la impureza de los hijos de Israel y de sus transgresiones, de todos sus pecados; y lo mismo hará por la Tienda de Reunión que habita con ellos en medio de su impureza.",
      "17": "Nadie estará en la Tienda de reunión cuando entre a hacer expiación en el Lugar Santo, hasta que salga y haya hecho expiación por él y por su familia, y por toda la asamblea de Israel. ",
      "18": "“Saldrá al altar que está delante de Yahvé y hará expiación por él, y tomará parte de la sangre del toro y parte de la sangre del macho cabrío, y la pondrá alrededor de los cuernos del altar.",
      "19": "Con su dedo rociará parte de la sangre sobre el altar siete veces, y lo purificará y lo santificará de la impureza de los hijos de Israel. ",
      "20": "“Cuando haya terminado de expiar el Lugar Santo, la Tienda de Reunión y el altar, presentará el macho cabrío vivo.",
      "21": "Aarón pondrá sus dos manos sobre la cabeza del macho cabrío vivo y confesará sobre él todas las iniquidades de los hijos de Israel y todas sus transgresiones, todos sus pecados, y los pondrá sobre la cabeza del macho cabrío, y lo enviará al desierto de la mano de un hombre preparado.",
      "22": "El macho cabrío llevará sobre sí todas sus iniquidades a una tierra solitaria, y soltará al macho cabrío en el desierto. ",
      "23": "“Aarón entrará en la Tienda del Encuentro y se quitará las vestiduras de lino que se puso al entrar en el Lugar Santo, y las dejará allí.",
      "24": "Luego se bañará en agua en un lugar santo, se pondrá sus vestiduras y saldrá a ofrecer su holocausto y el holocausto del pueblo, y hará expiación por él y por el pueblo.",
      "25": "La grasa de la ofrenda por el pecado la quemará sobre el altar. ",
      "26": "“El que suelte el macho cabrío como chivo expiatorio lavará su ropa y bañará su carne con agua, y después entrará en el campamento.",
      "27": "El toro para la ofrenda por el pecado y el macho cabrío para la ofrenda por el pecado, cuya sangre fue traída para hacer expiación en el Lugar Santo, serán llevados fuera del campamento; y quemarán sus pieles, su carne y su estiércol con fuego.",
      "28": "El que los queme lavará su ropa y bañará su carne con agua, y después entrará en el campamento. ",
      "29": "“Será un estatuto para vosotros: en el séptimo mes, a los diez días del mes, afligiréis vuestras almas y no haréis ningún tipo de trabajo, ya sea nativo o extranjero que viva como forastero entre vosotros;",
      "30": "porque en este día se hará expiación por vosotros, para limpiaros. Quedarás limpio de todos tus pecados ante el Señor.",
      "31": "Es un día de descanso solemne para ustedes, y afligirán sus almas. Es un estatuto para siempre.",
      "32": "El sacerdote ungido y consagrado para ser sacerdote en lugar de su padre, hará la expiación y se pondrá las vestiduras de lino, las vestiduras sagradas.",
      "33": "Luego hará la expiación por el Santuario Sagrado; y hará la expiación por la Tienda de Reunión y por el altar; y hará la expiación por los sacerdotes y por todo el pueblo de la asamblea. ",
      "34": "“Esto será un estatuto eterno para ti, para hacer expiación por los hijos de Israel una vez al año por todos sus pecados”. Se hizo como Yahvé le ordenó a Moisés."
    },
    "17": {
      "1": "Yahvé habló a Moisés, diciendo:",
      "2": "“Habla a Aarón y a sus hijos, y a todos los hijos de Israel, y diles: ‘Esto es lo que Yahvé ha ordenado:",
      "3": "Todo hombre de la casa de Israel que mate un toro, un cordero o una cabra en el campamento, o que lo mate fuera del campamento,",
      "4": "y no lo haya traído a la puerta de la Tienda de Reunión para ofrecerlo como ofrenda a Yavé ante el tabernáculo de Yavé: la sangre se le imputará a ese hombre. Ha derramado sangre. Ese hombre será cortado de entre su pueblo.",
      "5": "Esto es para que los hijos de Israel traigan sus sacrificios, que sacrifican en el campo abierto, para que los traigan a Yahvé, a la puerta de la Tienda del Encuentro, al sacerdote, y los sacrifiquen como ofrendas de paz a Yahvé.",
      "6": "El sacerdote rociará la sangre sobre el altar de Yavé, a la puerta de la Tienda del Encuentro, y quemará la grasa como aroma agradable para Yavé.",
      "7": "No volverán a sacrificar sus productos a los ídolos caprinos, después de los cuales se prostituyen. Esto les servirá de estatuto para siempre a lo largo de sus generaciones”. ",
      "8": "“Les dirás: ‘Cualquier hombre que haya de la casa de Israel, o de los extranjeros que viven como forasteros entre ellos, que ofrezca un holocausto o un sacrificio,",
      "9": "y no lo traiga a la puerta de la Tienda del Encuentro para sacrificarlo a Yahvé, ese hombre será cortado de su pueblo. ",
      "10": "“‘Cualquier hombre de la casa de Israel, o de los extranjeros que viven como forasteros entre ellos, que coma cualquier clase de sangre, yo pondré mi rostro contra esa alma que come sangre, y la cortaré de entre su pueblo.",
      "11": "Porque la vida de la carne está en la sangre. Os la he dado sobre el altar para hacer expiación por vuestras almas; porque es la sangre la que hace expiación en razón de la vida.",
      "12": "Por eso he dicho a los hijos de Israel: “Ninguna persona entre vosotros puede comer sangre, ni ningún extranjero que viva como tal entre vosotros puede comer sangre.” ",
      "13": "“‘Todo hombre de los hijos de Israel, o de los extranjeros que vivan como forasteros entre ellos, que cace algún animal o ave que se pueda comer, derramará su sangre y lo cubrirá con polvo.",
      "14": "Porque en cuanto a la vida de toda carne, su sangre es con su vida. Por eso dije a los hijos de Israel: “No comeréis la sangre de ninguna clase de carne, porque la vida de toda carne es su sangre. El que la coma será cortado”. ",
      "15": "“‘Toda persona que coma lo que muere por sí mismo, o lo que desgarran los animales, sea nativo o extranjero, lavará sus ropas y se bañará con agua, y quedará impuro hasta la noche. Entonces quedará limpio.",
      "16": "Pero si no los lava, ni se baña con agua, entonces cargará con su iniquidad”."
    },
    "18": {
      "1": "Yahvé dijo a Moisés:",
      "2": "“Habla a los hijos de Israel y diles: “Yo soy Yahvé, vuestro Dios.",
      "3": "No harás lo que hacen en la tierra de Egipto, donde vivías. No haréis como ellos en la tierra de Canaán, adonde os llevo. No seguirás sus estatutos.",
      "4": "Harás mis ordenanzas. Guardarán mis estatutos y caminarán en ellos. Yo soy el Señor, tu Dios.",
      "5": "Por lo tanto, guardarás mis estatutos y mis ordenanzas, los cuales, si el hombre los cumple, vivirá en ellos. Yo soy Yahvé. ",
      "6": "“‘Ninguno de ustedes se acercará a ningún pariente cercano para descubrir su desnudez: Yo soy Yahvé. ",
      "7": "“‘No descubrirás la desnudez de tu padre, ni la desnudez de tu madre: ella es tu madre. No descubrirás su desnudez. ",
      "8": "“‘No descubrirás la desnudez de la mujer de tu padre. Es la desnudez de tu padre. ",
      "9": "“‘No descubrirás la desnudez de tu hermana, de la hija de tu padre o de la hija de tu madre, tanto si ha nacido en casa como si ha nacido fuera. ",
      "10": "“‘No descubrirás la desnudez de la hija de tu hijo o de la hija de tu hija, su desnudez, porque la de ellos es tu propia desnudez. ",
      "11": "“‘No descubrirás la desnudez de la hija de la mujer de tu padre, concebida por éste, pues es tu hermana. ",
      "12": "“‘No descubrirás la desnudez de la hermana de tu padre. Ella es la pariente cercana de tu padre. ",
      "13": "“‘No descubrirás la desnudez de la hermana de tu madre, porque es pariente cercana de tu madre. ",
      "14": "“‘No descubrirás la desnudez del hermano de tu padre. No te acercarás a su mujer. Ella es tu tía. ",
      "15": "“‘No descubrirás la desnudez de tu nuera. Es la mujer de tu hijo. No descubrirás su desnudez. ",
      "16": "“‘No descubrirás la desnudez de la mujer de tu hermano. Es la desnudez de tu hermano. ",
      "17": "“‘No descubrirás la desnudez de una mujer y de su hija. No tomarás a la hija de su hijo, ni a la hija de su hija, para descubrir su desnudez. Son parientes cercanos. Es una maldad. ",
      "18": "“‘No tomarás una esposa además de su hermana, para ser rival, para descubrir su desnudez, mientras su hermana esté viva. ",
      "19": "“‘No te acercarás a una mujer para descubrir su desnudez, mientras esté impura por su impureza. ",
      "20": "“‘No te acostarás carnalmente con la mujer de tu prójimo, ni te contaminarás con ella. ",
      "21": "“‘No darás a ninguno de tus hijos como sacrificio a Moloc. No profanarás el nombre de tu Dios. Yo soy Yahvé. ",
      "22": "“‘No te acostarás con un hombre como con una mujer. Eso es detestable. ",
      "23": "“‘No te acostarás con ningún animal para contaminarte con él. Ninguna mujer puede entregarse a un animal para acostarse con él: es una perversión. ",
      "24": "“‘No os contaminéis en ninguna de estas cosas; porque en todas ellas se contaminaron las naciones que estoy echando delante de vosotros.",
      "25": "La tierra se contaminó. Por eso castigué su iniquidad, y la tierra vomitó a sus habitantes.",
      "26": "Guardad, pues, mis estatutos y mis ordenanzas, y no hagáis ninguna de estas abominaciones; ni el nativo, ni el extranjero que vive como forastero entre vosotros",
      "27": "(porque los hombres de la tierra que estaban antes de vosotros habían hecho todas estas abominaciones, y la tierra se contaminó),",
      "28": "para que la tierra no os vomite también a vosotros, cuando la contaminéis, como vomitó a la nación que estaba antes de vosotros. ",
      "29": "“‘Porque cualquiera que haga alguna de estas abominaciones, las almas que las hagan serán cortadas de entre su pueblo.",
      "30": "Por lo tanto, guardarán mis requisitos, para que no practiquen ninguna de estas costumbres abominables que se practicaban antes de ustedes, y para que no se contaminen con ellas. Yo soy Yahvé, vuestro Dios”."
    },
    "19": {
      "1": "Yahvé habló a Moisés diciendo:",
      "2": "“Habla a toda la congregación de los hijos de Israel y diles: “Seréis santos, porque yo, Yahvé, vuestro Dios, soy santo. ",
      "3": "“‘Cada uno de vosotros respetará a su madre y a su padre. Guardarán mis sábados. Yo soy Yahvé, vuestro Dios. ",
      "4": "“‘No se vuelvan a los ídolos, ni se hagan dioses de fundición. Yo soy Yahvé, vuestro Dios. ",
      "5": "“‘Cuando ofrezcas un sacrificio de paz a Yahvé, lo ofrecerás para que seas aceptado.",
      "6": "Se comerá el mismo día que lo ofrezcas, y al día siguiente. Si queda algo hasta el tercer día, se quemará con fuego.",
      "7": "Si se come al tercer día, es una abominación. No se aceptará;",
      "8": "sino que todo el que lo coma cargará con su iniquidad, porque ha profanado la cosa santa de Yahvé, y esa alma será cortada de su pueblo. ",
      "9": "“‘Cuando recojas la cosecha de tu tierra, no segarás del todo los rincones de tu campo, ni recogerás las espigas de tu cosecha.",
      "10": "No espigarás tu viña, ni recogerás las uvas caídas de tu viña. Las dejarás para el pobre y para el extranjero. Yo soy el Señor, tu Dios. ",
      "11": "“‘No robarás’. “‘No mentirás’. “‘No os engañaréis unos a otros’. ",
      "12": "“‘No jurarás por mi nombre en falso ni profanarás el nombre de tu Dios. Yo soy Yahvé. ",
      "13": "“‘No oprimirás a tu prójimo ni le robarás. “‘El salario de un jornalero no permanecerá con vosotros toda la noche hasta la mañana. ",
      "14": "“‘No maldecirás al sordo, ni pondrás tropiezo al ciego, sino que temerás a tu Dios. Yo soy Yahvé. ",
      "15": "“‘No cometerás injusticia en el juicio. No serás parcial con el pobre, ni mostrarás favoritismo con el grande; sino que juzgarás a tu prójimo con justicia. ",
      "16": "“‘No irás por ahí como calumniador entre tu pueblo. “‘No pondrás en peligro la vida  de tu prójimo. Yo soy Yahvé. ",
      "17": "“‘No odiarás a tu hermano en tu corazón. Reprenderás a tu prójimo y no cargarás con el pecado por su culpa. ",
      "18": "“‘No te vengarás ni guardarás rencor a los hijos de tu pueblo, sino que amarás a tu prójimo como a ti mismo. Yo soy Yahvé. ",
      "19": "“‘Deberás cumplir mis estatutos. “‘No cruzarás diferentes tipos de animales. “‘No sembrarás tu campo con dos tipos de semilla; “‘No lleves una prenda hecha de dos tipos de material. ",
      "20": "“‘Si un hombre se acuesta carnalmente con una mujer que es una chica esclava, comprometida para casarse con otro hombre, y no se rescata o se le da la libertad; serán castigados. No serán condenados a muerte, porque ella no era libre.",
      "21": "Traerá su ofrenda por la culpa a Yahvé, a la puerta de la Tienda del Encuentro, un carnero como ofrenda por la culpa.",
      "22": "El sacerdote hará expiación por él con el carnero de la ofrenda por la culpa ante Yahvé, por el pecado que haya cometido; y el pecado que haya cometido le será perdonado. ",
      "23": "“‘Cuando llegues a la tierra y hayas plantado toda clase de árboles para comer, entonces contarás sus frutos como prohibidos.  Durante tres años te estará prohibido. No se podrá comer.",
      "24": "Pero al cuarto año todo su fruto será sagrado, para alabar al Señor.",
      "25": "En el quinto año comerás su fruto, para que te dé sus frutos. Yo soy el Señor, tu Dios. ",
      "26": "“‘No comerás ninguna carne con la sangre todavía en ella. No usarás encantamientos, ni practicarás la hechicería. ",
      "27": "“‘No te cortarás el pelo a los lados de la cabeza ni te recortarás el borde de la barba. ",
      "28": "“‘No harás ningún corte en tu carne por los muertos, ni te tatuarás ninguna marca. Yo soy Yahvé. ",
      "29": "“‘No profanes a tu hija, para hacerla prostituta; no sea que la tierra caiga en la prostitución, y la tierra se llene de maldad. ",
      "30": "“‘Guardarán mis sábados y reverenciarán mi santuario; yo soy Yahvé. ",
      "31": "“‘No te dirijas a los que son médiums, ni a los magos. No los busques para ser contaminado por ellos. Yo soy Yahvé, tu Dios. ",
      "32": "“‘Te levantarás ante la cabeza gris y honrarás el rostro de los ancianos; y temerás a tu Dios. Yo soy Yahvé. ",
      "33": "“‘Si un extranjero vive como forastero con vosotros en vuestra tierra, no le haréis mal.",
      "34": "El extranjero que viva como forastero con ustedes será para ustedes como el nativo entre ustedes, y lo amarán como a ustedes mismos; porque ustedes vivieron como extranjeros en la tierra de Egipto. Yo soy Yahvé, tu Dios. ",
      "35": "“‘No harás injusticia en el juicio, en las medidas de longitud, de peso o de cantidad.",
      "36": "Tendrás balanzas justas, pesas justas, un efa justo,  y un hin justo.  Yo soy el Señor, tu Dios, que te sacó de la tierra de Egipto. ",
      "37": "“‘Observarás todos mis estatutos y todas mis ordenanzas, y los pondrás en práctica. Yo soy Yahvé’”."
    },
    "20": {
      "1": "Yahvé habló a Moisés, diciendo:",
      "2": "“Además, dirás a los hijos de Israel: ‘Cualquiera de los hijos de Israel, o de los extranjeros que vivan como forasteros en Israel, que entregue alguno de sus vástagos  a Moloc, morirá. El pueblo del país apedreará a esa persona con piedras.",
      "3": "Yo también pondré mi rostro contra esa persona, y la cortaré de entre su pueblo, porque ha dado de su descendencia a Moloc, para profanar mi santuario, y para profanar mi santo nombre.",
      "4": "Si todos los pueblos de la tierra esconden sus ojos de esa persona cuando da de su descendencia a Moloc, y no le dan muerte,",
      "5": "entonces yo pondré mi rostro contra ese hombre y contra su familia, y lo cortaré de entre su pueblo, y a todos los que se prostituyen después de él para prostituirse con Moloc. ",
      "6": "“‘La persona que se vuelve a los que son médiums y magos, para jugar a la prostitución después de ellos, incluso pondré mi cara contra esa persona, y la cortaré de entre su pueblo. ",
      "7": "“‘Santificaos, pues, y sed santos, porque yo soy Yahvé, vuestro Dios.",
      "8": "Guardarán mis estatutos y los pondrán en práctica. Yo soy Yahvé, que os santifico. ",
      "9": "“‘Porque todo el que maldiga a su padre o a su madre será condenado a muerte. Ha maldecido a su padre o a su madre. Su sangre caerá sobre él. ",
      "10": "“‘El hombre que comete adulterio con la mujer de otro hombre, incluso el que comete adulterio con la mujer de su prójimo, el adúltero y la adúltera serán condenados a muerte. ",
      "11": "“‘El hombre que se acuesta con la mujer de su padre ha descubierto la desnudez de su padre. Ambos serán condenados a muerte. Su sangre será sobre ellos. ",
      "12": "“‘Si un hombre se acuesta con su nuera, ambos serán condenados a muerte. Han cometido una perversión. Su sangre caerá sobre ellos. ",
      "13": "“‘Si un hombre se acuesta con un varón como con una mujer, ambos han cometido una abominación. Serán condenados a muerte. Su sangre será sobre ellos mismos. ",
      "14": "“‘Si un hombre toma una esposa y a su madre, es una maldad. Serán quemados con fuego, tanto él como ellas, para que no haya maldad entre vosotros. ",
      "15": "“‘Si un hombre se acuesta con un animal, será condenado a muerte; y matarás al animal. ",
      "16": "“‘Si una mujer se acerca a un animal y se acuesta con él, matarás a la mujer y al animal. Serán condenados a muerte. Su sangre caerá sobre ellos. ",
      "17": "“‘Si un hombre toma a su hermana — la hija de su padre o de su madre — y ve su desnudez, y ella ve la suya, es cosa vergonzosa. Serán cortados a la vista de los hijos de su pueblo. Él ha descubierto la desnudez de su hermana. Llevará su iniquidad. ",
      "18": "“‘Si un hombre se acuesta con una mujer que tiene su menstruación y descubre su desnudez, él ha desnudado su fuente, y ella ha descubierto la fuente de su sangre. Ambos serán cortados de entre su pueblo. ",
      "19": "“‘No descubrirás la desnudez de la hermana de tu madre, ni la de la hermana de tu padre, porque ha desnudado a su pariente cercano. Ellos cargarán con su iniquidad.",
      "20": "Si un hombre se acuesta con la mujer de su tío, ha descubierto la desnudez de su tío. Ellos cargarán con su pecado. Morirán sin hijos. ",
      "21": "“‘Si un hombre toma la mujer de su hermano, es una impureza. Ha descubierto la desnudez de su hermano. No tendrán hijos. ",
      "22": "“‘Por lo tanto, guardaréis todos mis estatutos y todas mis ordenanzas, y los pondréis en práctica, para que la tierra donde os traigo a vivir no os vomite.",
      "23": "No andarás en las costumbres de la nación que estoy echando delante de ti; porque ellos hicieron todas estas cosas, y por eso los aborrecí.",
      "24": "Pero a vosotros os he dicho: “Heredaréis su tierra, y os la daré para que la poseáis, una tierra que mana leche y miel”. Yo soy Yahvé, tu Dios, que te ha separado de los pueblos. ",
      "25": "“‘Por tanto, distinguiréis entre el animal limpio y el impuro, y entre las aves impuras y las limpias. No os haréis abominables con ningún animal, ni con ninguna ave, ni con nada de lo que abunda en la tierra, que yo he separado de vosotros como impuro para vosotros.",
      "26": "Seréis santos para mí, porque yo, Yahvé, soy santo, y os he apartado de los pueblos para que seáis míos. ",
      "27": "“‘El hombre o la mujer que sea un médium o un mago serán condenados a muerte. Serán apedreados. Su sangre será sobre ellos”."
    },
    "21": {
      "1": "Yahvé dijo a Moisés: “Habla a los sacerdotes, hijos de Aarón, y diles: ‘El sacerdote no se profanará por los muertos de su pueblo,",
      "2": "excepto por sus parientes que están cerca de él: por su madre, por su padre, por su hijo, por su hija, por su hermano,",
      "3": "y por su hermana virgen que está cerca de él, que no ha tenido marido; por ella puede profanarse.",
      "4": "No se contaminará, siendo jefe de su pueblo, para profanarse. ",
      "5": "“‘No se afeitarán la cabeza ni se afeitarán las comisuras de la barba, ni se harán cortes en la carne.",
      "6": "Serán santos para su Dios, y no profanarán el nombre de su Dios, porque ofrecen las ofrendas quemadas de Yahvé, el pan de su Dios. Por lo tanto, serán santos. ",
      "7": "“‘No se casarán con una mujer prostituta o profana. El sacerdote no se casará con una mujer divorciada de su marido, porque él es santo para su Dios.",
      "8": "Por eso lo santificarás, porque él ofrece el pan de tu Dios. Será santo para ti, porque yo, Yahvé, que te santifico, soy santo. ",
      "9": "“‘La hija de cualquier sacerdote, si se profana haciendo de prostituta, profana a su padre. Será quemada con fuego. ",
      "10": "“‘El que es sumo sacerdote entre sus hermanos, sobre cuya cabeza se derrama el aceite de la unción, y que es consagrado para vestir las vestiduras, no dejará suelto el cabello de su cabeza, ni rasgará sus vestidos.",
      "11": "No debe entrar a ningún cadáver, ni contaminarse por su padre o por su madre.",
      "12": "No saldrá del santuario ni profanará el santuario de su Dios, porque la corona del aceite de la unción de su Dios está sobre él. Yo soy Yahvé. ",
      "13": "“‘Tomará una esposa en su virginidad.",
      "14": "No se casará con una viuda, ni con una divorciada, ni con una mujer impura, ni con una prostituta. Tomará como esposa a una virgen de su propio pueblo.",
      "15": "No profanará su descendencia entre su pueblo, porque yo soy Yahvé, que lo santifico”. ",
      "16": "Yahvé habló a Moisés, diciendo:",
      "17": "“Di a Aarón: “Ninguno de tus descendientes, a lo largo de sus generaciones, que tenga un defecto podrá acercarse a ofrecer el pan de su Dios.",
      "18": "Porque todo hombre que tenga un defecto, no se acercará: un ciego, o un cojo, o el que tenga la nariz chata, o cualquier deformidad,",
      "19": "o un hombre que tenga un pie lesionado, o una mano lesionada,",
      "20": "o un jorobado, o un enano, o el que tenga un defecto en el ojo, o una enfermedad que pique, o costras, o que tenga los testículos dañados.",
      "21": "Ningún hombre de la descendencia del sacerdote Aarón que tenga un defecto se acercará a ofrecer las ofrendas de Yahvé hechas por fuego. Como tiene un defecto, no se acercará a ofrecer el pan de su Dios.",
      "22": "Comerá el pan de su Dios, tanto del más sagrado como del santo.",
      "23": "No se acercará al velo, ni se acercará al altar, porque tiene un defecto; para que no profane mis santuarios, porque yo soy Yavé que los santifico”. ",
      "24": "Entonces Moisés habló a Aarón, a sus hijos y a todos los hijos de Israel."
    },
    "22": {
      "1": "Yahvé habló a Moisés, diciendo:",
      "2": "“Di a Aarón y a sus hijos que se separen de las cosas sagradas de los hijos de Israel, que ellos hacen sagradas para mí, y que no profanen mi santo nombre. Yo soy Yahvé. ",
      "3": "“Diles: ‘Si alguno de todos tus descendientes, a lo largo de tus generaciones, se acerca a las cosas sagradas que los hijos de Israel santifican a Yahvé, teniendo su impureza encima, esa alma será cortada de delante de mí. Yo soy Yahvé. ",
      "4": "“‘Quien de los descendientes de Aarón sea leproso o tenga flujo, no comerá de las cosas sagradas hasta que esté limpio. El que toque algo inmundo por los muertos, o un hombre que tenga una emisión seminal,",
      "5": "o el que toque cualquier cosa que se arrastre por la que pueda quedar impuro, o un hombre del que pueda quedar impuro, sea cual sea la impureza que tenga—",
      "6": "la persona que toque a cualquiera de ellos quedará impura hasta la tarde, y no comerá de las cosas sagradas a menos que se bañe en agua.",
      "7": "Cuando se ponga el sol, quedará limpio, y después comerá de las cosas sagradas, porque es su pan.",
      "8": "No comerá lo que muera por sí mismo o sea desgarrado por los animales, contaminándose con ello. Yo soy Yahvé. ",
      "9": "“‘Por tanto, seguirán mi mandamiento, para que no carguen con el pecado y mueran en él, si lo profanan. Yo soy Yahvé, que los santifico. ",
      "10": "“‘Ningún extranjero comerá de la cosa sagrada; el extranjero que viva con los sacerdotes, o un siervo contratado, no comerá de la cosa sagrada.",
      "11": "Pero si un sacerdote compra un esclavo, adquirido con su dinero, comerá de él; y los nacidos en su casa comerán de su pan.",
      "12": "Si la hija de un sacerdote se casa con un extranjero, no comerá de la ofrenda de las cosas santas.",
      "13": "Pero si la hija de un sacerdote es viuda o divorciada y no tiene hijos, y ha vuelto a la casa de su padre como en su juventud, podrá comer del pan de su padre; pero ningún extraño comerá de él. ",
      "14": "“‘Si un hombre come algo sagrado sin saberlo, entonces le añadirá la quinta parte de su valor, y le dará la cosa sagrada al sacerdote.",
      "15": "Los sacerdotes no profanarán las cosas santas de los hijos de Israel, que ofrecen a Yahvé,",
      "16": "y así les harán cargar con la iniquidad que trae la culpa cuando comen sus cosas santas; porque yo soy Yahvé que los santifico.’” ",
      "17": "Yahvé habló a Moisés, diciendo:",
      "18": "“Habla a Aarón y a sus hijos, y a todos los hijos de Israel, y diles: “Todo el que sea de la casa de Israel, o de los extranjeros en Israel, que ofrezca su ofrenda, ya sea alguno de sus votos o alguna de sus ofrendas voluntarias, que ofrezcan a Yahvé como holocausto:",
      "19": "para que seas aceptado, ofrecerás un macho sin defecto, de los toros, de las ovejas o de las cabras.",
      "20": "Pero no ofrecerás lo que tenga algún defecto, porque no te será aceptable.",
      "21": "El que ofrezca un sacrificio de paz a Yahvé para cumplir un voto, o para una ofrenda voluntaria de la manada o del rebaño, será perfecto para ser aceptado. No deberá tener ningún defecto.",
      "22": "No ofrecerás a Yahvé lo que esté ciego, herido, mutilado, con verrugas, supurante o con llagas, ni harás de ellos una ofrenda encendida sobre el altar de Yahvé.",
      "23": "O un toro o un cordero que tenga alguna deformidad o falta en sus partes, que podrás ofrecer como ofrenda voluntaria; pero para un voto no se aceptará.",
      "24": "No debes ofrecer a Yahvé lo que tenga los testículos magullados, aplastados, rotos o cortados. No debes hacer esto en tu tierra.",
      "25": "No debes ofrecer nada de esto como pan de tu Dios de la mano de un extranjero, porque su corrupción está en ellos. Hay un defecto en ellos. No te serán aceptados”. ",
      "26": "Yahvé habló a Moisés diciendo:",
      "27": "“Cuando nazca un toro, una oveja o una cabra, permanecerá siete días con su madre. A partir del octavo día será aceptado como ofrenda quemada a Yahvé.",
      "28": "Ya sea que se trate de una vaca o de una oveja, no la matarás a ella y a su cría en un solo día. ",
      "29": "“Cuando sacrifiques un sacrificio de acción de gracias a Yahvé, lo sacrificarás para que seas aceptado.",
      "30": "Se comerá en el mismo día; no dejarás nada de él para la mañana. Yo soy Yahvé. ",
      "31": "“Por lo tanto, guardarán mis mandamientos y los pondrán en práctica. Yo soy Yahvé.",
      "32": "No profanarás mi santo nombre, sino que seré santificado entre los hijos de Israel. Yo soy Yahvé que te santifica,",
      "33": "que te sacó de la tierra de Egipto, para ser tu Dios. Yo soy Yahvé”."
    },
    "23": {
      "1": "Yahvé habló a Moisés, diciendo:",
      "2": "“Habla a los hijos de Israel y diles: ‘Las fiestas fijas de Yahvé, que proclamarás como convocatorias sagradas, son mis fiestas fijas. ",
      "3": "“‘Seis días se trabajará, pero el séptimo día es un día de descanso solemne, una santa convocación; no harás ninguna clase de trabajo. Es un día de reposo para Yahvé en todas vuestras moradas. ",
      "4": "“‘Estas son las fiestas fijas de Yahvé, las convocatorias sagradas, que proclamarás a su tiempo.",
      "5": "En el primer mes, el día catorce del mes, por la tarde, es la Pascua de Yahvé.",
      "6": "El decimoquinto día del mismo mes es la fiesta de los panes sin levadura para Yahvé. Durante siete días comerás panes sin levadura.",
      "7": "El primer día tendrás una santa convocación. No harás ningún trabajo regular.",
      "8": "Pero durante los siete días ofrecerás a Yahvé una ofrenda encendida. El séptimo día es una santa convocación. No harás ningún trabajo regular”. ",
      "9": "Yahvé habló a Moisés, diciendo:",
      "10": "“Habla a los hijos de Israel y diles: ‘Cuando hayáis entrado en la tierra que os doy y hayáis recogido su cosecha, traeréis al sacerdote la gavilla de las primicias de vuestra cosecha.",
      "11": "Él agitará la gavilla ante el Señor, para que sea aceptada por ustedes. Al día siguiente del sábado, el sacerdote la mecerá.",
      "12": "El día en que agites la gavilla, ofrecerás un cordero macho sin defecto de un año como holocausto a Yahvé.",
      "13": "La ofrenda con él será de dos décimas de efa  de harina fina mezclada con aceite, ofrenda encendida a Yahvé en olor agradable; y la libación con él será de vino, la cuarta parte de un hin.  ",
      "14": "No debes comer pan, ni grano tostado, ni grano fresco, hasta este mismo día, hasta que hayas traído la ofrenda de tu Dios. Este es un estatuto para siempre a través de vuestras generaciones en todas vuestras moradas. ",
      "15": "“‘Contarás desde el día siguiente al sábado, desde el día en que trajiste la gavilla de la ofrenda mecida: se completarán siete sábados.",
      "16": "Al día siguiente del séptimo sábado contarás cincuenta días, y ofrecerás una nueva ofrenda a Yahvé.",
      "17": "Sacaréis de vuestras moradas dos panes para la ofrenda mecida, hechos de dos décimas de efa  de harina fina. Serán cocidos con levadura, como primicias para Yahvé.",
      "18": "Con el pan presentarás siete corderos de un año sin defecto, un novillo y dos carneros. Serán un holocausto para Yahvé, con su ofrenda y sus libaciones, una ofrenda encendida, de dulce aroma para Yahvé.",
      "19": "Ofrecerás un macho cabrío como ofrenda por el pecado, y dos corderos de un año como sacrificio de paz.",
      "20": "El sacerdote los agitará con el pan de las primicias como ofrenda mecida ante Yavé, junto con los dos corderos. Serán sagrados para Yavé para el sacerdote.",
      "21": "Ese mismo día proclamarás que habrá una convocatoria sagrada para ti. No harás ningún trabajo regular. Este es un estatuto para siempre en todas vuestras moradas a lo largo de vuestras generaciones. ",
      "22": "“‘Cuando recojas la cosecha de tu tierra, no debes segar totalmente en los rincones de tu campo. No debes recoger los restos de tu cosecha. Debes dejarlos para el pobre y para el extranjero. Yo soy Yahvé, tu Dios”. ",
      "23": "Yahvé habló a Moisés, diciendo:",
      "24": "“Habla a los hijos de Israel, diciendo: ‘En el séptimo mes, el primer día del mes, habrá un descanso solemne para ustedes, un memorial de toque de trompetas, una convocatoria santa.",
      "25": "No haréis ningún trabajo regular. Ofreceréis una ofrenda encendida a Yahvé’”. ",
      "26": "Yahvé habló a Moisés diciendo:",
      "27": "“Sin embargo, el décimo día de este séptimo mes es el día de la expiación. Será para ustedes una convocatoria sagrada. Os afligiréis y ofreceréis una ofrenda encendida a Yahvé.",
      "28": "No haréis ninguna clase de trabajo en ese mismo día, porque es un día de expiación, para expiaros ante Yahvé vuestro Dios.",
      "29": "Porque el que no se niegue a sí mismo en ese mismo día, será cortado de su pueblo.",
      "30": "El que haga cualquier tipo de trabajo en ese mismo día, yo destruiré a esa persona de entre su pueblo.",
      "31": "No harás ninguna clase de trabajo: es un estatuto para siempre a través de tus generaciones en todas tus moradas.",
      "32": "Será para vosotros un sábado de descanso solemne, y os negaréis a vosotros mismos. En el noveno día del mes, al atardecer, de tarde en tarde, guardaréis vuestro sábado”. ",
      "33": "Yahvé habló a Moisés, diciendo:",
      "34": "“Habla a los hijos de Israel y diles: ‘El día quince de este mes séptimo es la fiesta de las cabañas  durante siete días a Yahvé.",
      "35": "El primer día será una convocatoria sagrada. No harás ningún trabajo regular.",
      "36": "Durante los siete días ofrecerás a Yahvé una ofrenda encendida. El octavo día será una convocatoria sagrada para ustedes. Ofreceréis a Yahvé una ofrenda encendida. Es una asamblea solemne; no harás ningún trabajo regular. ",
      "37": "“‘Estas son las fiestas señaladas por Yahvé, que proclamarás como convocatorias sagradas, para ofrecer una ofrenda encendida a Yahvé, un holocausto, una ofrenda de comida, un sacrificio y ofrendas de bebida, cada una en su día —",
      "38": "además de los sábados de Yahvé, y además de tus dones, y además de todos tus votos, y además de todas tus ofrendas voluntarias, que das a Yahvé. ",
      "39": "“‘Así pues, el día quince del mes séptimo, cuando hayáis recogido los frutos de la tierra, celebraréis la fiesta de Yahvé durante siete días. El primer día será un descanso solemne, y el octavo día será un descanso solemne.",
      "40": "El primer día tomarás los frutos de los árboles majestuosos, las ramas de las palmeras, las ramas de los árboles frondosos y los sauces del arroyo; y te alegrarás ante Yavé, tu Dios, durante siete días.",
      "41": "Lo celebrarás como fiesta para Yahvé durante siete días al año. Es un estatuto para siempre a lo largo de vuestras generaciones. La celebrarás en el séptimo mes.",
      "42": "Viviréis en refugios temporales  durante siete días. Todos los nativos de Israel habitarán en refugios temporales,  ",
      "43": "para que vuestras generaciones sepan que yo hice habitar a los hijos de Israel en refugios temporales  cuando los saqué de la tierra de Egipto. Yo soy Yahvé, vuestro Dios”. ",
      "44": "Así pues, Moisés declaró a los hijos de Israel las fiestas señaladas por Yahvé."
    },
    "24": {
      "1": "Yahvé habló a Moisés, diciendo:",
      "2": "“Ordena a los hijos de Israel que te traigan aceite de oliva puro batido para la luz, para hacer arder continuamente una lámpara.",
      "3": "Fuera del velo del Testimonio, en la Tienda del Encuentro, Aarón la mantendrá en orden desde la tarde hasta la mañana ante Yahvé continuamente. Será un estatuto para siempre a lo largo de vuestras generaciones.",
      "4": "El mantendrá en orden las lámparas en el candelabro de oro puro ante el Señor continuamente. ",
      "5": "“Tomarás harina fina y cocerás con ella doce tortas; dos décimas de efa  irán en una torta.",
      "6": "Las pondrás en dos hileras, seis en cada hilera, sobre la mesa de oro puro delante de Yahvé.",
      "7": "Pondrás incienso puro en cada hilera, para que sea para el pan un memorial, una ofrenda encendida a Yahvé.",
      "8": "Cada día de reposo lo pondrá en orden delante de Yavé continuamente. Es un pacto eterno a favor de los hijos de Israel.",
      "9": "Será para Aarón y sus hijos. Lo comerán en un lugar sagrado, porque es lo más sagrado para él de las ofrendas de Yahvé hechas por fuego por un estatuto perpetuo.” ",
      "10": "El hijo de una mujer israelita, cuyo padre era egipcio, salió entre los hijos de Israel; y el hijo de la mujer israelita y un hombre de Israel se pelearon en el campamento.",
      "11": "El hijo de la mujer israelita blasfemó el Nombre y maldijo, y lo llevaron a Moisés. Su madre se llamaba Shelomith, hija de Dibri, de la tribu de Dan.",
      "12": "Lo pusieron en custodia hasta que se les declarara la voluntad de Yavé.",
      "13": "Yahvé habló a Moisés, diciendo:",
      "14": "“Saca del campamento al que ha maldecido, y que todos los que lo hayan oído pongan sus manos sobre su cabeza, y que toda la congregación lo apedree.",
      "15": "Hablarás a los hijos de Israel diciendo: “El que maldiga a su Dios cargará con su pecado.",
      "16": "El que blasfeme el nombre de Yavé, ciertamente morirá. Toda la congregación lo apedreará ciertamente. Tanto el extranjero como el nativo serán condenados a muerte cuando blasfemen el Nombre. ",
      "17": "“‘El que hiera mortalmente a un hombre, morirá.",
      "18": "El que hiera mortalmente a un animal, lo compensará, vida por vida.",
      "19": "Si alguien hiere a su prójimo, se hará con él lo mismo que él ha hecho:",
      "20": "fractura por fractura, ojo por ojo, diente por diente. Se hará con él lo mismo que haya hecho con alguien.",
      "21": "El que mate a un animal lo compensará, y el que mate a un hombre será condenado a muerte.",
      "22": "Tendrás un mismo tipo de ley tanto para el extranjero como para el nativo, porque yo soy Yahvé, tu Dios”. ",
      "23": "Moisés habló a los hijos de Israel, y sacaron del campamento al que había maldecido y lo apedrearon. Los hijos de Israel hicieron lo que Yahvé les ordenó a Moisés."
    }
  }
};

