
	
export const bib_verses = {
  "nehemiah": {
    "8": {
      "1": "Todo el pueblo se reunió como un solo hombre en el lugar amplio que estaba frente a la puerta de las aguas, y hablaron a Esdras el escriba para que trajera el libro de la ley de Moisés, que Yahvé había ordenado a Israel.",
      "2": "El sacerdote Esdras trajo la ley ante la asamblea, tanto de hombres como de mujeres, y de todos los que podían oír con entendimiento, el primer día del mes séptimo.",
      "3": "Leyó de ella ante el lugar amplio que estaba frente a la puerta de las aguas, desde la mañana hasta el mediodía, en presencia de los hombres y de las mujeres, y de los que podían entender. Los oídos de todo el pueblo estaban atentos al libro de la ley.",
      "4": "Esdras, el escriba, estaba de pie sobre un púlpito de madera que habían hecho al efecto; y junto a él estaban Matatías, Sema, Anáías, Urías, Hilcías y Maasías, a su derecha; y a su izquierda, Pedaías, Misael, Malquías, Hasum, Hasbaddana, Zacarías y Mesulam.",
      "5": "Esdras abrió el libro a la vista de todo el pueblo (porque él estaba por encima de todo el pueblo), y cuando lo abrió, todo el pueblo se puso de pie.",
      "6": "Entonces Esdras bendijo a Yavé, el gran Dios. Todo el pueblo respondió: “Amén, Amén”, levantando las manos. Inclinaron la cabeza y adoraron a Yavé con el rostro en tierra.",
      "7": "También Jesúa, Baní, Serebías, Jamín, Acub, Sabetai, Hodías, Maasías, Kelita, Azarías, Jozabad, Hanán, Pelaías y los levitas, hicieron que el pueblo entendiera la ley; y el pueblo permaneció en su lugar.",
      "8": "Leían en el libro, en la ley de Dios, claramente; y daban el sentido, de modo que entendían la lectura. ",
      "9": "Nehemías, que era el gobernador, el sacerdote y escriba Esdras, y los levitas que enseñaban al pueblo, dijeron a todo el pueblo: “Hoy es un día santo para Yahvé, vuestro Dios. No os lamentéis ni lloréis”. Porque todo el pueblo lloró al oír las palabras de la ley.",
      "10": "Luego les dijo: “Vayan. Coman la grasa, beban lo dulce y envíen porciones a quien no tiene nada preparado, porque hoy es santo para nuestro Señor. No os entristezcáis, porque la alegría de Yahvé es vuestra fuerza”. ",
      "11": "Entonces los levitas calmaron a todo el pueblo, diciendo: “Callad, porque el día es sagrado. No se aflijan”. ",
      "12": "Todo el pueblo siguió su camino para comer, beber, enviar porciones y celebrar, porque habían entendido las palabras que se les habían declarado. ",
      "13": "Al segundo día, los jefes de familia de todo el pueblo, los sacerdotes y los levitas se reunieron con Esdras, el escriba, para estudiar las palabras de la ley.",
      "14": "Encontraron escrito en la ley cómo Yahvé había ordenado por medio de Moisés que los hijos de Israel debían habitar en cabañas en la fiesta del séptimo mes;",
      "15": "y que debían publicar y proclamar en todas sus ciudades y en Jerusalén, diciendo: “Salgan al monte y traigan ramas de olivo, ramas de olivo silvestre, ramas de mirto, ramas de palmeras y ramas de árboles frondosos, para hacer refugios temporales, como está escrito.” ",
      "16": "Así que el pueblo salió y los trajo, y se hicieron refugios temporales, cada uno en el techo de su casa, en sus patios, en los patios de la casa de Dios, en el lugar ancho de la puerta de las aguas y en el lugar ancho de la puerta de Efraín.",
      "17": "Toda la asamblea de los que habían regresado del cautiverio hizo refugios temporales y vivió en los refugios temporales, pues desde los días de Josué hijo de Nun hasta ese día los hijos de Israel no lo habían hecho. Hubo una alegría muy grande.",
      "18": "Además, cada día, desde el primero hasta el último, se leía en el libro de la ley de Dios. Celebraron la fiesta durante siete días; y el octavo día hubo una asamblea solemne, según la ordenanza."
    },
    "9": {
      "1": "El día veinticuatro de este mes se reunieron los hijos de Israel con ayuno, con cilicio y con tierra sobre ellos.",
      "2": "Los descendientes de Israel se separaron de todos los extranjeros y se pusieron de pie y confesaron sus pecados y las iniquidades de sus padres.",
      "3": "Se pusieron de pie en su lugar y leyeron en el libro de la ley de Yavé su Dios la cuarta parte del día; y la cuarta parte la confesaron y adoraron a Yavé su Dios.",
      "4": "Entonces Jesúa, Baní, Cadmiel, Sebanías, Buní, Serebías, Baní y Quenaní, de los levitas, se pusieron de pie en la escalera y clamaron en voz alta a Yavé su Dios. ",
      "5": "Entonces los levitas, Jesúa y Cadmiel, Baní, Hasabneías, Serebías, Hodías, Sebanías y Petaías, dijeron: “¡Ponte de pie y bendice a Yahvé, tu Dios, desde la eternidad hasta la eternidad! ¡Bendito sea tu nombre glorioso, que es exaltado sobre toda bendición y alabanza!",
      "6": "Tú eres Yahvé, tú solo. Tú has hecho el cielo, el cielo de los cielos, con todo su ejército, la tierra y todo lo que hay en ella, los mares y todo lo que hay en ellos, y tú lo conservas todo. El ejército de los cielos te adora.",
      "7": "Tú eres Yahvé, el Dios que eligió a Abram, lo sacó de Ur de los Caldeos, le dio el nombre de Abraham,",
      "8": "encontró su corazón fiel ante ti, e hizo un pacto con él para darle la tierra del cananeo, del hitita, del amorreo, del ferezeo, del jebuseo y del gergeseo, para dársela a su descendencia, y has cumplido tus palabras, porque eres justo. ",
      "9": "“Viste la aflicción de nuestros padres en Egipto, y oíste su clamor junto al Mar Rojo,",
      "10": "y mostraste señales y prodigios contra el Faraón, contra todos sus siervos y contra todo el pueblo de su tierra, porque sabías que se burlaban de ellos, y te hiciste un nombre, como lo es hoy.",
      "11": "Dividiste el mar delante de ellos, de modo que pasaron por el medio del mar en seco; y arrojaste a sus perseguidores a las profundidades, como una piedra a las aguas impetuosas.",
      "12": "Además, en una columna de nube los guiaste de día, y en una columna de fuego de noche, para alumbrarles el camino que debían seguir. ",
      "13": "“También bajaste al monte Sinaí, y hablaste con ellos desde el cielo, y les diste ordenanzas rectas y leyes verdaderas, buenos estatutos y mandamientos,",
      "14": "y les diste a conocer tu santo sábado, y les ordenaste mandamientos, estatutos y una ley, por medio de Moisés, tu siervo,",
      "15": "y les diste pan del cielo para su hambre, y les sacaste agua de la roca para su sed, y les ordenaste que entraran a poseer la tierra que habías jurado darles. ",
      "16": "“Pero ellos y nuestros padres se comportaron con soberbia, endurecieron su cerviz, no escucharon tus mandamientos,",
      "17": "y se negaron a obedecer. No tuvieron en cuenta tus maravillas que hiciste entre ellos, sino que endurecieron su cerviz, y en su rebeldía nombraron un capitán para volver a su esclavitud. Pero tú eres un Dios dispuesto a perdonar, clemente y misericordioso, lento para la ira y abundante en bondades, y no los abandonaste.",
      "18": "Sí, cuando se hicieron un becerro moldeado y dijeron: “Este es vuestro Dios, que os hizo subir de Egipto”, y cometieron horribles blasfemias,",
      "19": "pero tú, en tus múltiples misericordias, no los abandonaste en el desierto. La columna de nube no se apartó de ellos durante el día para guiarlos por el camino, ni la columna de fuego durante la noche para mostrarles la luz y el camino que debían seguir.",
      "20": "También diste tu buen Espíritu para instruirlos, y no retuviste tu maná de su boca, y les diste agua para su sed. ",
      "21": "“Sí, cuarenta años los sostuviste en el desierto. Nada les faltó. Sus vestidos no envejecieron y sus pies no se hincharon.",
      "22": "Además, les diste reinos y pueblos, que asignaste según sus porciones. Así poseyeron la tierra de Sehón, la tierra del rey de Hesbón y la tierra de Og, rey de Basán.",
      "23": "También multiplicaste sus hijos como las estrellas del cielo, y los introdujiste en la tierra sobre la que habías dicho a sus padres que entrarían a poseerla. ",
      "24": "“Así que los hijos entraron y poseyeron la tierra; y tú sometiste ante ellos a los habitantes de la tierra, los cananeos, y los entregaste en sus manos, con sus reyes y los pueblos de la tierra, para que hicieran con ellos lo que quisieran.",
      "25": "Tomaron ciudades fortificadas y una tierra rica, y poseyeron casas llenas de todos los bienes, cisternas excavadas, viñas, olivares y árboles frutales en abundancia. Así comieron, se saciaron, engordaron y se deleitaron en tu gran bondad. ",
      "26": "“Sin embargo, fueron desobedientes y se rebelaron contra ti, echaron tu ley a sus espaldas, mataron a tus profetas que testificaban contra ellos para que se volvieran a ti, y cometieron horribles blasfemias.",
      "27": "Por eso los entregaste en manos de sus adversarios, que los angustiaron. En el tiempo de su angustia, cuando clamaron a ti, tú oíste desde el cielo; y según tus múltiples misericordias les diste salvadores que los salvaron de las manos de sus adversarios.",
      "28": "Pero después de haber descansado, volvieron a hacer el mal ante ti; por eso los dejaste en manos de sus enemigos, para que se enseñorearan de ellos; sin embargo, cuando volvieron y clamaron a ti, tú oíste desde el cielo; y muchas veces los libraste según tus misericordias,",
      "29": "y diste testimonio contra ellos, para que volvieran a tu ley. Sin embargo, fueron arrogantes y no escucharon tus mandamientos, sino que pecaron contra tus ordenanzas (que si el hombre hace, vivirá en ellas), volvieron la espalda, endurecieron su cerviz y no quisieron escuchar.",
      "30": "Sin embargo, durante muchos años los aguantaste y les diste testimonio con tu Espíritu por medio de tus profetas. Sin embargo, no quisieron escuchar. Por eso los entregaste en manos de los pueblos de las tierras. ",
      "31": "“Sin embargo, en tus múltiples misericordias, no les pusiste fin ni los abandonaste, porque eres un Dios clemente y misericordioso. ",
      "32": "Ahora, pues, Dios nuestro, el grande, el poderoso y el imponente, que guarda el pacto y la bondad amorosa, no dejes que te parezcan pequeños todos los trabajos que nos han sobrevenido, a nuestros reyes, a nuestros príncipes, a nuestros sacerdotes, a nuestros profetas, a nuestros padres y a todo tu pueblo, desde el tiempo de los reyes de Asiria hasta hoy.",
      "33": "Sin embargo, tú eres justo en todo lo que ha recaído sobre nosotros; porque tú has actuado con verdad, pero nosotros hemos hecho maldad.",
      "34": "También nuestros reyes, nuestros príncipes, nuestros sacerdotes y nuestros padres no han guardado tu ley, ni han escuchado tus mandamientos y tus testimonios con los que testificaste contra ellos.",
      "35": "Porque no te han servido en su reino y en tu gran bondad que les diste, y en la tierra grande y rica que les diste. No se convirtieron de sus obras malvadas. ",
      "36": "“He aquí que hoy somos siervos, y en cuanto a la tierra que diste a nuestros padres para comer su fruto y su bien, he aquí que somos siervos en ella.",
      "37": "La tierra da muchos frutos a los reyes que has puesto sobre nosotros a causa de nuestros pecados. También tienen poder sobre nuestros cuerpos y sobre nuestro ganado, a su antojo, y estamos en gran aflicción.",
      "38": "Sin embargo, por todo esto, hacemos un pacto seguro y lo escribimos; y nuestros príncipes, nuestros levitas y nuestros sacerdotes lo sellan.”"
    },
    "10": {
      "1": "Los que sellaron fueron: Nehemías, el gobernador, hijo de Hacalías, y Sedequías,",
      "2": "Seraías, Azarías, Jeremías,",
      "3": "Pashur, Amarías, Malquías,",
      "4": "Hattush, Sebanías, Malluch,",
      "5": "Harim, Meremot, Abdías,",
      "6": "Daniel, Ginetón, Baruc,",
      "7": "Mesulam, Abías, Mijamín,",
      "8": "Maazías, Bilgai y Semaías. Estos eran los sacerdotes.",
      "9": "Los levitas: Jesúa hijo de Azanías, Binúi de los hijos de Henadad, Cadmiel;",
      "10": "y sus hermanos, Sebanías, Hodías, Kelita, Pelaías, Hanán,",
      "11": "Mica, Rehob, Hasabías,",
      "12": "Zaccur, Serebías, Sebanías,",
      "13": "Hodías, Baní y Beninú.",
      "14": "Los jefes del pueblo: Parosh, Pahathmoab, Elam, Zattu, Bani,",
      "15": "Bunni, Azgad, Bebai,",
      "16": "Adonías, Bigvai, Adin,",
      "17": "Ater, Ezequías, Azzur,",
      "18": "Hodías, Hashum, Bezai,",
      "19": "Hariph, Anathoth, Nobai,",
      "20": "Magpiash, Meshullam, Hezir,",
      "21": "Meshezabel, Zadok, Jaddua,",
      "22": "Pelatiah, Hanan, Anaiah,",
      "23": "Hoshea, Hananiah, Hasshub,",
      "24": "Hallohesh, Pilha, Shobek,",
      "25": "Rehum, Hashabnah, Maaseiah,",
      "26": "Ahiah, Hanan, Anan,",
      "27": "Malluch, Harim y Baanah. ",
      "28": "El resto del pueblo, los sacerdotes, los levitas, los porteros, los cantores, los servidores del templo, y todos los que se habían apartado de los pueblos de las tierras a la ley de Dios, sus esposas, sus hijos y sus hijas — todos los que tenían conocimiento y entendimiento —",
      "29": "se unieron a sus hermanos sus nobles, y entraron en una maldición y en un juramento, para andar en la ley de Dios, que fue dada por Moisés el siervo de Dios, y para observar y hacer todos los mandamientos de Yahvé nuestro Señor, y sus ordenanzas y sus estatutos;",
      "30": "y que no daríamos nuestras hijas a los pueblos de la tierra, ni tomaríamos sus hijas para nuestros hijos;",
      "31": "y que si los pueblos de la tierra trajeran mercancías o algún grano en el día de reposo para vender, no les compraríamos en el día de reposo, ni en un día santo; y que renunciaríamos a las cosechas del séptimo año y a la exacción de toda deuda. ",
      "32": "Además, nos hemos impuesto la obligación de cobrar anualmente la tercera parte de un siclo para el servicio de la casa de nuestro Dios:",
      "33": "para el pan de la proposición, para la ofrenda continua, para el holocausto continuo, para los sábados, para las lunas nuevas, para las fiestas, para las cosas santas, para las ofrendas por el pecado para hacer expiación por Israel, y para toda la obra de la casa de nuestro Dios.",
      "34": "Nosotros, los sacerdotes, los levitas y el pueblo, echamos suertes sobre la ofrenda de leña, para traerla a la casa de nuestro Dios, según las casas de nuestros padres, en los tiempos señalados de año en año, para quemarla en el altar de Yahvé nuestro Dios, como está escrito en la ley;",
      "35": "y para traer las primicias de nuestra tierra y las primicias de todos los frutos de toda clase de árboles, de año en año, a la casa de Yahvé;",
      "36": "también los primogénitos de nuestros hijos y de nuestros ganados, como está escrito en la ley, y los primogénitos de nuestras vacas y de nuestros rebaños, para llevarlos a la casa de nuestro Dios, a los sacerdotes que sirven en la casa de nuestro Dios",
      "37": "y que traigamos las primicias de nuestra masa, nuestras ofrendas de ondas, el fruto de toda clase de árboles, el vino nuevo y el aceite, a los sacerdotes, a las salas de la casa de nuestro Dios; y los diezmos de nuestra tierra a los levitas; porque ellos, los levitas, toman los diezmos en todas nuestras aldeas agrícolas.",
      "38": "El sacerdote, descendiente de Aarón, estará con los levitas cuando éstos tomen los diezmos. Los levitas llevarán el diezmo de los diezmos a la casa de nuestro Dios, a las habitaciones, a la casa del tesoro.",
      "39": "Porque los hijos de Israel y los hijos de Leví llevarán la ofrenda mecida del grano, del vino nuevo y del aceite, a las habitaciones donde están los utensilios del santuario y los sacerdotes que ministran, con los porteros y los cantores. No abandonaremos la casa de nuestro Dios."
    },
    "11": {
      "1": "Los príncipes del pueblo vivían en Jerusalén. El resto del pueblo también echó suertes para que uno de los diez habitara en Jerusalén, la ciudad santa, y nueve partes en las demás ciudades.",
      "2": "El pueblo bendijo a todos los hombres que se ofrecieron voluntariamente para habitar en Jerusalén. ",
      "3": "Estos son los jefes de la provincia que vivían en Jerusalén; pero en las ciudades de Judá, cada uno vivía en su posesión en sus ciudades: los sacerdotes, los levitas, los servidores del templo y los hijos de los servidores de Salomón.",
      "4": "Algunos de los hijos de Judá y de los hijos de Benjamín vivían en Jerusalén. De los hijos de Judá Ataías hijo de Uzías, hijo de Zacarías, hijo de Amarías, hijo de Sefatías, hijo de Mahalalel, de los hijos de Pérez;",
      "5": "y Maasías hijo de Baruc, hijo de Colhoze, hijo de Hazaías, hijo de Adaías, hijo de Joiarib, hijo de Zacarías, hijo del silonita.",
      "6": "Todos los hijos de Pérez que vivían en Jerusalén eran cuatrocientos sesenta y ocho hombres valientes. ",
      "7": "Estos son los hijos de Benjamín: Salú, hijo de Mesulam, hijo de Joed, hijo de Pedaías, hijo de Colaías, hijo de Maasías, hijo de Itiel, hijo de Jesaías.",
      "8": "Después de él, Gabbai y Sallai, novecientos veintiocho.",
      "9": "Joel hijo de Zicri era su supervisor; y Judá hijo de Hasenúa era el segundo sobre la ciudad. ",
      "10": "De los sacerdotes: Jedaías hijo de Joiarib, Jacín,",
      "11": "Seraías hijo de Hilcías, hijo de Mesulam, hijo de Sadoc, hijo de Meraiot, hijo de Ahitub, jefe de la casa de Dios,",
      "12": "y sus hermanos que hacían la obra de la casa, ochocientos veintidós; y Adaías hijo de Jeroham, hijo de Pelalías, hijo de Amzi, hijo de Zacarías, hijo de Pashur, hijo de Malquías,",
      "13": "y sus hermanos, jefes de las casas paternas, doscientos cuarenta y dos y Amashsai hijo de Azarel, hijo de Ahzai, hijo de Meshillemoth, hijo de Immer,",
      "14": "y sus hermanos, hombres valientes, ciento veintiocho; y su jefe era Zabdiel, hijo de Haggedolim. ",
      "15": "De los levitas Semaías hijo de Hasub, hijo de Azricam, hijo de Hasabías, hijo de Bunni;",
      "16": "y Sabetai y Jozabad, de los jefes de los levitas, que tenían a su cargo los asuntos externos de la casa de Dios;",
      "17": "y Matanías hijo de Mica, hijo de Zabdi, hijo de Asaf, que era el jefe que iniciaba la acción de gracias en la oración, y Bacbuquías, el segundo entre sus hermanos; y Abda hijo de Sammúa, hijo de Galal, hijo de Jedutún.",
      "18": "Todos los levitas de la ciudad santa eran doscientos ochenta y cuatro. ",
      "19": "Además, los guardianes de las puertas, Acub, Talmón y sus hermanos, que vigilaban las puertas, eran ciento setenta y dos.",
      "20": "El resto de Israel, de los sacerdotes y de los levitas, estaban en todas las ciudades de Judá, cada uno en su heredad.",
      "21": "Pero los servidores del templo vivían en Ofel, y Ziha y Gishpa estaban al frente de los servidores del templo. ",
      "22": "El supervisor de los levitas en Jerusalén era Uzi hijo de Bani, hijo de Hasabías, hijo de Matanías, hijo de Mica, de los hijos de Asaf, los cantores, estaba a cargo de los asuntos de la casa de Dios.",
      "23": "Porque había un mandamiento del rey acerca de ellos, y una provisión establecida para los cantores, como cada día lo requería.",
      "24": "Petaías, hijo de Meshezabel, de los hijos de Zera, hijo de Judá, estaba al lado del rey en todos los asuntos del pueblo. ",
      "25": "En cuanto a las aldeas con sus campos, algunos de los hijos de Judá vivían en Quiriat Arba y sus pueblos, en Dibón y sus pueblos, en Jekabzeel y sus aldeas,",
      "26": "en Jesúa, en Moladah, Bet Pelet,",
      "27": "en Hazar Shual en Beersheba y sus aldeas,",
      "28": "en Ziklag, en Meconah y sus aldeas,",
      "29": "en En Rimmon, en Zorah, en Jarmuth,",
      "30": "Zanoah, Adullam y sus aldeas, Lachish y sus campos, y Azekah y sus aldeas. Y acamparon desde Beerseba hasta el valle de Hinom.",
      "31": "Los hijos de Benjamín también vivían desde Geba, en Micmas y Aija, y en Betel y sus pueblos,",
      "32": "en Anatot, Nob, Ananías,",
      "33": "Hazor, Ramá, Gittaim,",
      "34": "Hadid, Zeboim, Neballat,",
      "35": "Lod y Ono, el valle de los artesanos.",
      "36": "De los levitas, ciertas divisiones de Judá se establecieron en el territorio de Benjamín."
    },
    "12": {
      "1": "Estos son los sacerdotes y levitas que subieron con Zorobabel, hijo de Salatiel, y con Jesúa: Seraías, Jeremías, Esdras,",
      "2": "Amarías, Malluch, Hattush,",
      "3": "Secanías, Rehum, Meremot,",
      "4": "Iddo, Ginnethoi, Abías,",
      "5": "Mijamín, Maadia, Bilgah,",
      "6": "Semaías, Joiarib, Jedaías,",
      "7": "Sallu, Amok, Hilkiah y Jedaías. Estos eran los jefes de los sacerdotes y de sus hermanos en los días de Jesúa. ",
      "8": "Además, los levitas eran Jesúa, Binúi, Cadmiel, Serebías, Judá y Matanías, que estaba a cargo de los cantos de acción de gracias, él y sus hermanos.",
      "9": "También Bakbucías y Unno, sus hermanos, estaban cerca de ellos según sus cargos.",
      "10": "Jesúa fue padre de Joiaquim, y Joiaquim fue padre de Eliasib, y Eliasib fue padre de Joiada,",
      "11": "y Joiada fue padre de Jonatán, y Jonatán fue padre de Jaddua. ",
      "12": "En los días de Joiakim había sacerdotes, jefes de familia de los padres: de Seraías, Meraías; de Jeremías, Hananías;",
      "13": "de Esdras, Mesulam; de Amarías, Johanán;",
      "14": "de Malluchi, Jonatán; de Sebanías, José;",
      "15": "de Harim, Adna; de Meraiot, Helkai;",
      "16": "de Iddo, Zacarías; de Ginetón, Mesulam;",
      "17": "de Abías, Zicri; de Miniamin, de Moadías, Piltai;",
      "18": "de Bilgah, Sammua; de Semaías, Jonatán;",
      "19": "de Joiarib, Mattenai; de Jedaías, Uzzi;",
      "20": "de Sallai, Kallai; de Amok, Eber;",
      "21": "de Hilcías, Hasabías; de Jedaías, Netanel. ",
      "22": "En cuanto a los levitas, en los días de Eliasib, Joiada, Johanán y Jaddua, se registraron los jefes de familia; también los sacerdotes, en el reinado de Darío el Persa.",
      "23": "Los hijos de Leví, jefes de familia, fueron inscritos en el libro de las crónicas, hasta los días de Johanán hijo de Eliasib.",
      "24": "Los jefes de los levitas: Hasabías, Serebías y Jesúa hijo de Cadmiel, con sus hermanos cerca de ellos, para alabar y dar gracias según el mandato de David, el hombre de Dios, sección tras sección.",
      "25": "Matanías, Bacbuquías, Abdías, Mesulam, Talmón y Acub eran guardianes de las puertas, que vigilaban los almacenes de las puertas.",
      "26": "Estos eran en los días de Joiaquim hijo de Jesúa, hijo de Josadac, y en los días del gobernador Nehemías y del sacerdote y escriba Esdras. ",
      "27": "En la dedicación del muro de Jerusalén, buscaron a los levitas de todos sus lugares para traerlos a Jerusalén a celebrar la dedicación con alegría, dando gracias y cantando, con címbalos, instrumentos de cuerda y arpas.",
      "28": "Los hijos de los cantores se reunieron, tanto de la llanura que rodea a Jerusalén como de las aldeas de los netofatitas;",
      "29": "también de Bet Gilgal y de los campos de Geba y Azmavet, porque los cantores se habían construido aldeas alrededor de Jerusalén.",
      "30": "Los sacerdotes y los levitas se purificaron, y purificaron el pueblo, las puertas y el muro. ",
      "31": "Entonces hice subir a los príncipes de Judá al muro, y designé dos grandes compañías que dieron gracias y fueron en procesión. Una iba a la derecha en el muro, hacia la puerta del estiércol;",
      "32": "y tras ellos iban Oseas, con la mitad de los príncipes de Judá,",
      "33": "y Azarías, Esdras y Mesulam,",
      "34": "Judá, Benjamín, Semaías, Jeremías,",
      "35": "y algunos de los hijos de los sacerdotes con trompetas: Zacarías hijo de Jonatán, hijo de Semaías, hijo de Matanías, hijo de Micaías, hijo de Zacur, hijo de Asaf;",
      "36": "y sus hermanos, Semaías, Azarel, Milalai, Gilalai, Maai, Netanel, Judá y Hanani, con los instrumentos musicales de David, el hombre de Dios; y el escriba Esdras estaba delante de ellos.",
      "37": "Por la puerta del manantial, y en línea recta delante de ellos, subieron por las escaleras de la ciudad de David, en la subida del muro, por encima de la casa de David, hasta la puerta de las aguas, hacia el este. ",
      "38": "La otra compañía de los que daban gracias salió a su encuentro, y yo tras ellos, con la mitad del pueblo en el muro, por encima de la torre de los hornos, hasta el muro ancho,",
      "39": "y por encima de la puerta de Efraín, y por la puerta vieja, y por la puerta del pescado, la torre de Hananel, y la torre de Hammea, hasta la puerta de las ovejas; y se detuvieron en la puerta de la guardia.",
      "40": "Las dos compañías de los que daban gracias en la casa de Dios estaban en pie, y yo y la mitad de los jefes conmigo;",
      "41": "y los sacerdotes, Eliaquim, Maasías, Miniamin, Micaías, Elioenai, Zacarías y Hananías, con trompetas;",
      "42": "y Maasías, Semaías, Eleazar, Uzi, Johanán, Malquías, Elam y Ezer. Los cantores cantaban en voz alta, con Jezrahías, su supervisor.",
      "43": "Aquel día ofrecieron grandes sacrificios y se regocijaron, porque Dios los había hecho gozar con gran alegría; y también se regocijaron las mujeres y los niños, de modo que la alegría de Jerusalén se oyó hasta muy lejos. ",
      "44": "Aquel día se designaron hombres sobre las salas para los tesoros, para las ofrendas de las olas, para las primicias y para los diezmos, a fin de recoger en ellas, según los campos de las ciudades, las porciones señaladas por la ley para los sacerdotes y los levitas; porque Judá se alegró por los sacerdotes y por los levitas que servían.",
      "45": "Ellos cumplían el deber de su Dios y el deber de la purificación, y lo mismo hacían los cantores y los porteros, según el mandato de David y de Salomón su hijo.",
      "46": "Porque en los días de David y de Asaf de antaño había un jefe de los cantores, y cantos de alabanza y de acción de gracias a Dios.",
      "47": "Todo Israel, en los días de Zorobabel y en los días de Nehemías, dio las porciones de los cantores y de los porteros, según cada día; y apartaron lo que era para los levitas; y los levitas apartaron lo que era para los hijos de Aarón."
    },
    "13": {
      "1": "Aquel día leyeron en el libro de Moisés a oídos del pueblo, y se encontró escrito en él que un amonita y un moabita no debían entrar en la asamblea de Dios para siempre,",
      "2": "porque no salieron al encuentro de los hijos de Israel con pan y agua, sino que contrataron a Balaam contra ellos para maldecirlos; sin embargo, nuestro Dios convirtió la maldición en bendición.",
      "3": "Sucedió que cuando escucharon la ley, separaron de Israel a toda la multitud mixta. ",
      "4": "Antes de esto, el sacerdote Eliasib, que había sido designado como encargado de las habitaciones de la casa de nuestro Dios, siendo aliado de Tobías,",
      "5": "había preparado para él una gran sala, en la que antes se depositaban las ofrendas de comida, el incienso, los vasos y los diezmos del grano, el vino nuevo y el aceite, que se daban por mandato a los levitas, a los cantores y a los porteros; y las ofrendas onduladas para los sacerdotes.",
      "6": "Pero en todo esto no estuve en Jerusalén, porque en el año treinta y dos de Artajerjes, rey de Babilonia, fui al rey; y después de algunos días pedí permiso al rey,",
      "7": "y llegué a Jerusalén, y comprendí el mal que Eliasib había hecho a Tobías, al prepararle una habitación en los atrios de la casa de Dios.",
      "8": "Esto me afligió mucho. Por eso eché de la habitación todos los enseres de Tobías.",
      "9": "Luego ordené, y ellos limpiaron las habitaciones. Llevé a ellas los utensilios de la casa de Dios, con las ofrendas de comida y el incienso de nuevo. ",
      "10": "Me di cuenta de que las porciones de los levitas no se les habían dado, de modo que los levitas y los cantores, que hacían el trabajo, habían huido cada uno a su campo.",
      "11": "Entonces discutí con los jefes y dije: “¿Por qué está abandonada la casa de Dios?” Los reuní y los puse en su lugar.",
      "12": "Entonces todo Judá trajo el diezmo del grano, del vino nuevo y del aceite a las arcas.",
      "13": "Puse como tesoreros sobre los tesoros al sacerdote Selemías y al escriba Sadoc, y de los levitas a Pedaías; y junto a ellos a Hanán hijo de Zaccur, hijo de Matanías; porque eran tenidos por fieles, y su oficio era repartir a sus hermanos. ",
      "14": "Acuérdate de mí, Dios mío, en cuanto a esto, y no borres mis buenas obras que he hecho por la casa de mi Dios y por sus celebraciones. ",
      "15": "En aquellos días vi a algunos hombres que pisaban lagares en sábado en Judá, que traían gavillas y cargaban asnos con vino, uvas, higos y toda clase de cargas que llevaban a Jerusalén en día de reposo; y testifiqué contra ellos en el día en que vendían alimentos.",
      "16": "También vivían allí algunos hombres de Tiro, que traían pescado y toda clase de mercancías, y vendían en sábado a los hijos de Judá y en Jerusalén.",
      "17": "Entonces discutí con los nobles de Judá y les dije: “¿Qué maldad es ésta que hacéis, profanando el día de reposo?",
      "18": "¿No hicieron esto vuestros padres, y no trajo nuestro Dios todo este mal sobre nosotros y sobre esta ciudad? Sin embargo, vosotros traéis más ira sobre Israel al profanar el sábado”. ",
      "19": "Sucedió que cuando las puertas de Jerusalén comenzaron a oscurecerse antes del sábado, mandé cerrar las puertas y ordené que no se abrieran hasta después del sábado. Puse a algunos de mis siervos a cargo de las puertas, para que no se introdujera ninguna carga en el día de reposo.",
      "20": "Entonces los mercaderes y vendedores de toda clase de mercancías acamparon fuera de Jerusalén una o dos veces.",
      "21": "Entonces yo testifiqué contra ellos y les dije: “¿Por qué os quedáis alrededor del muro? Si volvéis a hacerlo, os echaré mano”. Desde entonces, no vinieron en sábado.",
      "22": "Mandé a los levitas que se purificaran, y que vinieran a guardar las puertas, para santificar el día de reposo. Acuérdate de mí también por esto, Dios mío, y perdóname según la grandeza de tu amorosa bondad. ",
      "23": "En aquellos días vi también a los judíos que se habían casado con mujeres de Asdod, de Amón y de Moab;",
      "24": "y sus hijos hablaban la mitad en el idioma de Asdod, y no podían hablar en la lengua de los judíos, sino según la lengua de cada pueblo.",
      "25": "Yo discutí con ellos, los maldije, golpeé a algunos de ellos, les arranqué el cabello y les hice jurar por Dios: “No daréis vuestras hijas a sus hijos, ni tomaréis sus hijas para vuestros hijos, ni para vosotros.",
      "26": "¿No pecó Salomón, rey de Israel, con estas cosas? Sin embargo, entre muchas naciones no hubo un rey como él, y fue amado por su Dios, y Dios lo hizo rey de todo Israel. Sin embargo, las mujeres extranjeras lo hicieron pecar.",
      "27": "¿Debemos, pues, escucharte para hacer todo este gran mal, para transgredir a nuestro Dios casándonos con mujeres extranjeras?” ",
      "28": "Uno de los hijos de Joiada, hijo del sumo sacerdote Eliasib, era yerno de Sanbalat el horonita; por eso lo eché de mí.",
      "29": "Acuérdate de ellos, Dios mío, porque han profanado el sacerdocio y la alianza del sacerdocio y de los levitas. ",
      "30": "Así los limpié de todos los extranjeros y señalé los deberes para los sacerdotes y para los levitas, cada uno en su trabajo;",
      "31": "y para la ofrenda de leña, en los tiempos señalados, y para las primicias. Acuérdate de mí, Dios mío, para bien."
    }
  },
  "esther": {
    "1": {
      "1": "En los días de Asuero (éste es Asuero, que reinó desde la India hasta Etiopía, sobre ciento veintisiete provincias),",
      "2": "en aquellos días, cuando el rey Asuero se sentó en el trono de su reino, que estaba en el palacio de Susa,",
      "3": "en el tercer año de su reinado, hizo una fiesta para todos sus príncipes y sus servidores; el ejército de Persia y de Media, los nobles y los príncipes de las provincias estaban delante de él.",
      "4": "Exhibió las riquezas de su glorioso reino y el honor de su excelente majestad muchos días, hasta ciento ochenta días. ",
      "5": "Cuando se cumplieron estos días, el rey hizo una fiesta de siete días para todo el pueblo presente en el palacio de Susa, tanto el grande como el pequeño, en el patio del jardín del palacio real.",
      "6": "Había colgaduras de material blanco y azul, sujetas con cordones de lino fino y púrpura a anillos de plata y a columnas de mármol. Los divanes eran de oro y plata, sobre un pavimento de mármol rojo, blanco, amarillo y negro.",
      "7": "Les daban de beber en vasos de oro de diversas clases, incluso vino real en abundancia, según la generosidad del rey.",
      "8": "De acuerdo con la ley, la bebida no era obligatoria, pues así lo había ordenado el rey a todos los funcionarios de su casa, para que hicieran lo que cada uno quisiera. ",
      "9": "También la reina Vasti hizo un banquete para las mujeres de la casa real que pertenecía al rey Asuero. ",
      "10": "El séptimo día, cuando el corazón del rey estaba alegre por el vino, ordenó a Mehumán, Biztha, Harbona, Bigtha y Abagtha, Zethar y Carcass, los siete eunucos que servían en presencia del rey Asuero,",
      "11": "que trajeran a la reina Vasti ante el rey con la corona real, para mostrar al pueblo y a los príncipes su belleza, pues era hermosa.",
      "12": "Pero la reina Vasti se negó a presentarse a la orden del rey por medio de los eunucos. Por eso el rey se enojó mucho, y su ira ardía en él. ",
      "13": "Entonces el rey dijo a los sabios, que conocían los tiempos (pues era costumbre del rey consultar a los que conocían la ley y el juicio;",
      "14": "y junto a él estaban Carshena, Shethar, Admatha, Tarshish, Meres, Marsena y Memucan, los siete príncipes de Persia y de Media, que veían la cara del rey y se sentaban los primeros en el reino),",
      "15": "“¿Qué haremos con la reina Vasti según la ley, porque no ha cumplido la orden del rey Asuero por los eunucos?” ",
      "16": "Memucán respondió ante el rey y los príncipes: “La reina Vasti no ha hecho mal sólo al rey, sino también a todos los príncipes y a todo el pueblo que está en todas las provincias del rey Asuero.",
      "17": "Porque esta acción de la reina será conocida por todas las mujeres, haciéndolas despreciar a sus maridos cuando se diga: ‘El rey Asuero mandó traer a la reina Vasti ante él, pero ella no vino’.",
      "18": "Hoy, las princesas de Persia y de Media que se han enterado de la acción de la reina lo contarán a todos los príncipes del rey. Esto causará mucho desprecio e ira. ",
      "19": "“Si al rey le parece bien, que salga de él un mandamiento real y que se escriba entre las leyes de los persas y de los medos, para que no pueda ser alterado, a fin de que Vasti no vuelva a presentarse ante el rey Asuero; y que el rey dé su patrimonio real a otra que sea mejor que ella.",
      "20": "Cuando se publique en todo el reino el decreto del rey que él hará (porque es grande), todas las mujeres darán honor a sus maridos, tanto a los grandes como a los pequeños.” ",
      "21": "Este consejo agradó al rey y a los príncipes, y el rey hizo conforme a la palabra de Memucán:",
      "22": "pues envió cartas a todas las provincias del rey, a cada provincia según su escritura, y a cada pueblo en su lengua, para que cada uno gobernara su casa, hablando en la lengua de su pueblo."
    },
    "2": {
      "1": "Después de estas cosas, cuando la ira del rey Asuero se apaciguó, se acordó de Vasti, de lo que había hecho y de lo que se había decretado contra ella.",
      "2": "Entonces los servidores del rey que le servían dijeron: “Que se busquen jóvenes vírgenes hermosas para el rey.",
      "3": "Que el rey designe oficiales en todas las provincias de su reino, para que reúnan a todas las jóvenes vírgenes hermosas en la ciudadela de Susa, en la casa de las mujeres, bajo la custodia de Hegai, el eunuco del rey, guardián de las mujeres. Que se les den cosméticos;",
      "4": "y que la doncella que agrade al rey sea reina en lugar de Vasti”. El asunto agradó al rey, y así lo hizo. ",
      "5": "Había en la ciudadela de Susa un judío que se llamaba Mardoqueo, hijo de Jair, hijo de Simei, hijo de Cis, benjamita,",
      "6": "que había sido llevado de Jerusalén con los cautivos que habían sido llevados con Jeconías, rey de Judá, a quienes Nabucodonosor, rey de Babilonia, había llevado.",
      "7": "Crió a Hadasa, es decir, a Ester, la hija de su tío, pues no tenía padre ni madre. La doncella era hermosa y bella; y cuando su padre y su madre murieron, Mardoqueo la tomó como hija propia. ",
      "8": "Así que, cuando se oyó la orden del rey y su decreto, y cuando se reunieron muchas doncellas en la ciudadela de Susa, para la custodia de Hegai, Ester fue llevada a la casa del rey, a la custodia de Hegai, guardián de las mujeres.",
      "9": "La doncella le agradó y obtuvo de él su benevolencia. Se apresuró a darle cosméticos y sus raciones de comida, así como las siete doncellas selectas que debían entregársele fuera de la casa del rey. La trasladó a ella y a sus doncellas al mejor lugar de la casa de las mujeres.",
      "10": "Ester no había dado a conocer su pueblo ni sus parientes, porque Mardoqueo le había ordenado que no lo hiciera.",
      "11": "Mardoqueo se paseaba todos los días frente al patio de la casa de las mujeres, para saber cómo estaba Ester y qué sería de ella. ",
      "12": "A cada joven le llegaba el turno de entrar ante el rey Asuero después de su purificación durante doce meses (pues así se cumplían los días de su purificación, seis meses con aceite de mirra y seis meses con fragancias dulces y con preparaciones para embellecer a las mujeres).",
      "13": "La joven se presentó entonces ante el rey de esta manera: se le dio todo lo que deseaba para que fuera con ella de la casa de las mujeres a la casa del rey.",
      "14": "Al anochecer se fue, y al día siguiente volvió a la segunda casa de las mujeres, a la custodia de Shaashgaz, el eunuco del rey, que guardaba las concubinas. No volvió a entrar en la casa del rey, a no ser que el rey se complaciera en ella, y la llamara por su nombre. ",
      "15": "Cuando llegó el turno de Ester, hija de Abihail, tío de Mardoqueo, que la había tomado por hija, para entrar al rey, no exigió nada más que lo que le aconsejaba Hegai, el eunuco del rey, guardián de las mujeres. Ester obtuvo el favor de todos los que la miraban. ",
      "16": "Ester fue llevada a la casa real del rey Asuero en el mes décimo, que es el mes de Tebet, en el séptimo año de su reinado.",
      "17": "El rey amó a Ester más que a todas las mujeres, y ella obtuvo el favor y la bondad ante sus ojos más que todas las vírgenes, de modo que puso la corona real sobre su cabeza y la nombró reina en lugar de Vasti. ",
      "18": "Entonces el rey hizo una gran fiesta para todos sus príncipes y sus siervos, la fiesta de Ester; y proclamó un día de fiesta en las provincias, y dio regalos según la generosidad del rey. ",
      "19": "Cuando las vírgenes se reunieron por segunda vez, Mardoqueo estaba sentado en la puerta del rey.",
      "20": "Ester aún no había dado a conocer a sus parientes ni a su pueblo, como le había ordenado Mardoqueo; porque Ester obedecía a Mardoqueo, como lo hacía cuando era educada por él.",
      "21": "En aquellos días, mientras Mardoqueo estaba sentado en la puerta del rey, dos de los eunucos del rey, Bigtán y Teres, que eran porteros, se enojaron y trataron de poner las manos sobre el rey Asuero.",
      "22": "Este asunto llegó a conocimiento de Mardoqueo, quien informó a la reina Ester; y Ester informó al rey en nombre de Mardoqueo.",
      "23": "Cuando se investigó este asunto, y se comprobó que era así, ambos fueron colgados en una horca; y se escribió en el libro de las crónicas en presencia del rey."
    },
    "3": {
      "1": "Después de estas cosas, el rey Asuero ascendió a Amán, hijo de Hamedata el Agagita, y lo hizo avanzar, y puso su asiento por encima de todos los príncipes que estaban con él.",
      "2": "Todos los siervos del rey que estaban en la puerta del rey se inclinaron y rindieron homenaje a Amán, porque el rey así lo había ordenado con respecto a él. Pero Mardoqueo no se inclinó ni le rindió homenaje.",
      "3": "Entonces los servidores del rey que estaban en la puerta del rey dijeron a Mardoqueo: “¿Por qué desobedeces el mandato del rey?”",
      "4": "Como le hablaban todos los días y él no los escuchaba, se lo comunicaron a Amán para ver si la razón de Mardoqueo se mantenía, pues él les había dicho que era judío.",
      "5": "Cuando Amán vio que Mardoqueo no se inclinaba ni le rendía homenaje, se llenó de ira.",
      "6": "Pero despreció la idea de poner las manos sobre Mardoqueo solo, porque le habían dado a conocer el pueblo de Mardoqueo. Por lo tanto, Amán trató de destruir a todos los judíos que había en todo el reino de Asuero, incluso al pueblo de Mardoqueo. ",
      "7": "En el mes primero, que es el mes de Nisán, en el año duodécimo del rey Asuero, echaron Pur, es decir, la suerte, delante de Amán de día en día y de mes en mes, y eligieron el mes duodécimo, que es el mes de Adar.",
      "8": "Amán dijo al rey Asuero: “Hay un pueblo disperso y diseminado entre los pueblos de todas las provincias de tu reino, y sus leyes son diferentes a las de los demás pueblos. No cumplen las leyes del rey. Por lo tanto, al rey no le conviene permitir que se queden.",
      "9": "Si al rey le parece bien, que se escriba que sean destruidos; y yo pagaré diez mil talentos de plata en manos de los encargados de los negocios del rey, para que los ingresen en las arcas del rey.” ",
      "10": "El rey se quitó el anillo de la mano y se lo dio a Amán, hijo de Hamedata el Agagita, enemigo de los judíos.",
      "11": "El rey dijo a Amán: “La plata se te da a ti, también el pueblo, para que hagas con él lo que te parezca”. ",
      "12": "Entonces los escribas del rey fueron convocados el primer mes, a los trece días del mes; y todo lo que Amán mandó fue escrito a los gobernadores locales del rey, y a los gobernadores que estaban sobre cada provincia, y a los príncipes de cada pueblo, a cada provincia según su escritura, y a cada pueblo en su idioma. Estaba escrito en nombre del rey Asuero, y estaba sellado con el anillo del rey.",
      "13": "Se enviaron cartas por medio de correos a todas las provincias del rey, para destruir, matar y hacer perecer a todos los judíos, jóvenes y ancianos, niños y mujeres, en un solo día, el día trece del mes duodécimo, que es el mes de Adar, y para saquear sus bienes.",
      "14": "Se publicó una copia de la carta para que el decreto se distribuyera en todas las provincias, a fin de que todos los pueblos estuvieran preparados para ese día.",
      "15": "Los mensajeros salieron a toda prisa por orden del rey, y el decreto se repartió en la ciudadela de Susa. El rey y Amán se sentaron a beber; pero la ciudad de Susa estaba perpleja."
    },
    "4": {
      "1": "Cuando Mardoqueo se enteró de todo lo que se había hecho, rasgó sus ropas y se vistió de saco con cenizas, y salió al centro de la ciudad, y se lamentó fuerte y amargamente.",
      "2": "Llegó hasta la puerta del rey, pues a nadie se le permite entrar en la puerta del rey vestido de cilicio.",
      "3": "En todas las provincias, dondequiera que llegaba la orden del rey y su decreto, había gran luto entre los judíos, y ayuno, llanto y lamentos; y muchos se acostaban en cilicio y ceniza. ",
      "4": "Vinieron las doncellas de Ester y sus eunucos y le contaron esto, y la reina se entristeció mucho. Envió ropa a Mardoqueo, para reemplazar su cilicio, pero él no la recibió.",
      "5": "Entonces Ester llamó a Hatac, uno de los eunucos del rey, a quien había designado para que la atendiera, y le ordenó que fuera a ver a Mardoqueo, para averiguar qué era esto y por qué era.",
      "6": "Salió, pues, Hatac a ver a Mardoqueo, a la plaza de la ciudad que estaba delante de la puerta del rey.",
      "7": "Mardoqueo le contó todo lo que le había sucedido y la suma exacta del dinero que Amán había prometido pagar a las arcas del rey por la destrucción de los judíos.",
      "8": "También le dio la copia del escrito del decreto que se había dado en Susa para destruirlos, para que se lo mostrara a Ester y se lo declarara, y para que la instara a entrar al rey para suplicarle y pedirle por su pueblo. ",
      "9": "Hathach vino y le contó a Ester las palabras de Mardoqueo.",
      "10": "Entonces Ester habló con Hatac y le dio un mensaje para Mardoqueo",
      "11": "“Todos los siervos del rey y el pueblo de las provincias del rey saben que cualquiera, sea hombre o mujer, que se presente al rey en el patio interior sin ser llamado, hay una ley para él: que sea condenado a muerte, excepto aquellos a quienes el rey les extienda el cetro de oro, para que vivan. No he sido llamado a entrar al rey en estos treinta días”. ",
      "12": "Le contaron a Mardoqueo las palabras de Ester.",
      "13": "Entonces Mardoqueo les pidió que le devolvieran a Ester esta respuesta “No pienses para ti que vas a escapar en la casa del rey más que todos los judíos.",
      "14": "Porque si ahora callas, el alivio y la liberación vendrán a los judíos desde otro lugar, pero tú y la casa de tu padre pereceréis. ¿Quién sabe si no has venido al reino para un momento como éste?” ",
      "15": "Entonces Ester les pidió que respondieran a Mardoqueo,",
      "16": "“Ve, reúne a todos los judíos que están presentes en Susa, y ayunen por mí, y no coman ni beban durante tres días, ni de noche ni de día. Yo y mis doncellas también ayunaremos de la misma manera. Entonces entraré a ver al rey, lo cual es contrario a la ley; y si perezco, perezco”.",
      "17": "Así pues, Mardoqueo se puso en camino e hizo todo lo que Ester le había ordenado."
    },
    "5": {
      "1": "Al tercer día, Ester se vistió con sus ropas reales y se puso en el patio interior de la casa real, junto a la casa del rey. El rey estaba sentado en su trono real en la casa real, junto a la entrada de la casa.",
      "2": "Cuando el rey vio a la reina Ester de pie en el patio, ella obtuvo el favor de sus ojos; y el rey le tendió a Ester el cetro de oro que tenía en la mano. Entonces Ester se acercó y tocó la punta del cetro. ",
      "3": "Entonces el rey le preguntó: “¿Qué quieres, reina Ester? ¿Cuál es tu petición? Se te dará hasta la mitad del reino”. ",
      "4": "Ester dijo: “Si al rey le parece bien, que el rey y Amán vengan hoy al banquete que le he preparado”. ",
      "5": "Entonces el rey dijo: “Trae pronto a Amán, para que se haga lo que ha dicho Ester”. Así que el rey y Amán llegaron al banquete que Ester había preparado. ",
      "6": "El rey dijo a Ester en el banquete del vino: “¿Cuál es tu petición? Se te concederá. ¿Cuál es tu petición? Hasta la mitad del reino se cumplirá”. ",
      "7": "Entonces Ester respondió y dijo: “Mi petición y mi solicitud es ésta.",
      "8": "Si he hallado gracia ante los ojos del rey, y si al rey le agrada conceder mi petición y cumplir mi solicitud, que el rey y Amán vengan al banquete que les prepararé, y yo haré mañana lo que el rey ha dicho.” ",
      "9": "Entonces Amán salió aquel día alegre y contento de corazón, pero cuando vio a Mardoqueo en la puerta del rey, que no se levantaba ni se movía por él, se llenó de ira contra Mardoqueo.",
      "10": "Sin embargo, Amán se contuvo y se fue a su casa. Allí mandó llamar a sus amigos y a Zeresh, su esposa.",
      "11": "Amán les contó la gloria de sus riquezas, la multitud de sus hijos, todas las cosas en que el rey lo había promovido, y cómo lo había aventajado por encima de los príncipes y servidores del rey. ",
      "12": "También dijo Amán: “Sí, la reina Ester no dejó entrar a nadie con el rey al banquete que ella había preparado, sino a mí; y mañana también estoy invitado por ella junto con el rey.",
      "13": "Pero todo esto no me sirve de nada, mientras vea al judío Mardoqueo sentado a la puerta del rey.” ",
      "14": "Entonces Zeresh, su mujer, y todos sus amigos le dijeron: “Que se haga una horca de cincuenta codos de altura, y por la mañana habla con el rey de colgar a Mardoqueo en ella. Entonces entra alegremente con el rey al banquete”. Esto le gustó a Amán, así que mandó hacer la horca."
    },
    "6": {
      "1": "Aquella noche, el rey no podía dormir. Mandó traer el libro de los registros de las crónicas, y se los leyeron al rey.",
      "2": "Se encontró escrito que Mardoqueo había hablado de Bigtana y Teresh, dos eunucos del rey, que eran porteros, y que habían tratado de ponerle las manos encima al rey Asuero.",
      "3": "El rey dijo: “¿Qué honor y dignidad se le ha dado a Mardoqueo por esto?” Entonces los sirvientes del rey que lo atendían dijeron: “No se ha hecho nada por él”. ",
      "4": "El rey dijo: “¿Quién está en el patio?” Ahora bien, Amán había entrado en el atrio exterior de la casa real, para hablar con el rey acerca de colgar a Mardoqueo en la horca que había preparado para él. ",
      "5": "Los servidores del rey le dijeron: “Mira, Amán está en el patio”. El rey dijo: “Que entre”.",
      "6": "Así que Amán entró. El rey le dijo: “¿Qué se hará con el hombre a quien el rey se complace en honrar?” Y dijo Amán en su corazón: “¿A quién se deleita el rey en honrar más que a mí mismo?”",
      "7": "Amán dijo al rey: “Para el hombre a quien el rey se deleita en honrar,",
      "8": "que se traigan las ropas reales que el rey acostumbra a usar, y el caballo en que el rey monta, y en cuya cabeza está puesta una corona real.",
      "9": "Que la ropa y el caballo sean entregados a la mano de uno de los príncipes más nobles del rey, para que se vista con ellos al hombre a quien el rey se complace en honrar, y se le haga cabalgar por la plaza de la ciudad, y se proclame ante él: “¡Así se hará con el hombre a quien el rey se complace en honrar!” ",
      "10": "Entonces el rey dijo a Amán: “Apresúrate a tomar la ropa y el caballo, como has dicho, y hazlo por el judío Mardoqueo, que se sienta a la puerta del rey. Que no falte nada de todo lo que has dicho”. ",
      "11": "Entonces Amán tomó la ropa y el caballo y vistió a Mardoqueo, lo hizo cabalgar por la plaza de la ciudad y proclamó ante él: “¡Así se hará con el hombre al que el rey se complace en honrar!” ",
      "12": "Mardoqueo regresó a la puerta del rey, pero Amán se apresuró a ir a su casa, de luto y con la cabeza cubierta.",
      "13": "Amán contó a Zeres su mujer y a todos sus amigos todo lo que le había sucedido. Entonces sus sabios y Zeresh su mujer le dijeron: “Si Mardoqueo, ante quien has empezado a caer, es de ascendencia judía, no prevalecerás contra él, sino que seguramente caerás ante él.”",
      "14": "Mientras aún hablaban con él, llegaron los eunucos del rey y se apresuraron a llevar a Amán al banquete que había preparado Ester."
    },
    "7": {
      "1": "El rey y Amán vinieron a banquete con la reina Ester.",
      "2": "El rey volvió a decir a Ester el segundo día en el banquete de vino: “¿Cuál es tu petición, reina Ester? Se te concederá. ¿Cuál es tu petición? Hasta la mitad del reino se cumplirá”. ",
      "3": "La reina Ester respondió: “Si he hallado gracia ante tus ojos, oh rey, y si al rey le parece bien, que se me dé la vida a petición mía, y a mi pueblo a petición mía.",
      "4": "Porque hemos sido vendidos, yo y mi pueblo, para ser destruidos, para ser asesinados y para perecer. Pero si hubiéramos sido vendidos por esclavos y esclavas, habría callado, aunque el adversario no hubiera podido compensar la pérdida del rey.” ",
      "5": "Entonces el rey Asuero dijo a la reina Ester: “¿Quién es y dónde está el que se atrevió a hacer eso en su corazón?” ",
      "6": "Ester dijo: “¡Un adversario y un enemigo, este malvado Amán!” Entonces Amán tuvo miedo ante el rey y la reina.",
      "7": "El rey se levantó furioso del banquete de vino y se dirigió al jardín del palacio. Amán se levantó para pedir su vida a la reina Ester, pues veía que había un mal determinado contra él por parte del rey.",
      "8": "Entonces el rey volvió a salir del jardín del palacio al lugar del banquete del vino, y Amán había caído en el diván donde estaba Ester. Entonces el rey dijo: “¿Acaso va a agredir a la reina delante de mí en la casa?” Al salir la palabra de la boca del rey, cubrieron el rostro de Amán. ",
      "9": "Entonces Harbonah, uno de los eunucos que estaban con el rey, dijo: “He aquí, la horca de cincuenta codos de altura, que Amán ha hecho para Mardoqueo, que habló bien para el rey, está de pie en la casa de Amán.” El rey dijo: “¡Cuélguenlo!” ",
      "10": "Así que colgaron a Amán en la horca que había preparado para Mardoqueo. Entonces se aplacó la ira del rey."
    },
    "8": {
      "1": "Aquel día, el rey Asuero entregó la casa de Amán, el enemigo de los judíos, a la reina Ester. Mardoqueo se presentó ante el rey, pues Ester le había contado lo que era.",
      "2": "El rey se quitó el anillo que le había quitado a Amán y se lo dio a Mardoqueo. Ester puso a Mardoqueo al frente de la casa de Amán. ",
      "3": "Ester volvió a hablar ante el rey, se postró a sus pies y le rogó con lágrimas que acabara con la maldad de Amán el agagita y con el plan que había planeado contra los judíos.",
      "4": "Entonces el rey le tendió a Ester el cetro de oro. Entonces Ester se levantó y se presentó ante el rey.",
      "5": "Ella dijo: “Si al rey le agrada, y si he hallado gracia ante sus ojos, y la cosa le parece bien al rey, y soy agradable a sus ojos, que se escriba para anular las cartas ideadas por Amán, hijo de Hamedata el agagueo, que él escribió para destruir a los judíos que están en todas las provincias del rey.",
      "6": "Porque, ¿cómo podré soportar ver el mal que le espera a mi pueblo? ¿Cómo podré soportar ver la destrucción de mis parientes?” ",
      "7": "Entonces el rey Asuero dijo a la reina Ester y al judío Mardoqueo: “Mira, he entregado a Ester a la casa de Amán, y lo han colgado en la horca porque puso su mano sobre los judíos.",
      "8": "Escribe también a los judíos lo que te plazca, en nombre del rey, y séllalo con el anillo del rey; porque lo que se escribe en nombre del rey, y se sella con el anillo del rey, no puede ser revocado por nadie.” ",
      "9": "Entonces fueron llamados los escribas del rey en aquel tiempo, en el mes tercero, que es el mes de Siván, a los veintitrés días del mes; y se escribió según todo lo que Mardoqueo mandó a los judíos, y a los gobernadores locales, y a los gobernadores y príncipes de las provincias que están desde la India hasta Etiopía, ciento veintisiete provincias, a cada provincia según su escritura, y a cada pueblo en su lengua, y a los judíos en su escritura y en su lengua.",
      "10": "Escribió en nombre del rey Asuero, y lo selló con el anillo del rey, y envió las cartas por correo a caballo, montando en caballos reales criados de corceles veloces.",
      "11": "En esas cartas, el rey concedía a los judíos que estaban en cada ciudad que se reunieran y defendieran sus vidas, para destruir, matar y hacer perecer a todo el poder del pueblo y de la provincia que los asaltara, a sus pequeños y a sus mujeres, y para saquear sus posesiones,",
      "12": "en un solo día en todas las provincias del rey Asuero, el día trece del duodécimo mes, que es el mes de Adar.",
      "13": "Se publicó en todos los pueblos una copia de la carta para que el decreto se repartiera en todas las provincias, a fin de que los judíos estuvieran preparados para ese día para vengarse de sus enemigos.",
      "14": "Salieron, pues, los mensajeros que montaban en caballos reales, se apresuraron y se pusieron en marcha por orden del rey. El decreto se dio en la ciudadela de Susa. ",
      "15": "Mardoqueo salió de la presencia del rey con ropas reales de azul y blanco, y con una gran corona de oro, y con un manto de lino fino y púrpura; y la ciudad de Susa gritó y se alegró.",
      "16": "Los judíos tuvieron luz, alegría, gozo y honor.",
      "17": "En todas las provincias y en todas las ciudades, dondequiera que llegaba el mandamiento del rey y su decreto, los judíos tenían alegría, gozo, fiesta y festividad. Muchos de entre los pueblos de la tierra se hicieron judíos, porque el temor de los judíos había caído sobre ellos."
    },
    "9": {
      "1": "En el mes duodécimo, que es el mes de Adar, a los trece días del mes, cuando el mandamiento del rey y su decreto estaban a punto de ser ejecutados, el día en que los enemigos de los judíos esperaban conquistarlos, (pero resultó lo contrario, que los judíos conquistaron a los que los odiaban),",
      "2": "los judíos se reunieron en sus ciudades por todas las provincias del rey Asuero, para echar mano a los que querían hacerles daño. Nadie pudo resistirlos, porque el temor a ellos había caído sobre todo el pueblo.",
      "3": "Todos los príncipes de las provincias, los gobernadores locales, los intendentes y los que se ocupaban de los asuntos del rey ayudaban a los judíos, porque el temor a Mardoqueo había caído sobre ellos.",
      "4": "Porque Mardoqueo era grande en la casa del rey, y su fama se extendía por todas las provincias, pues el hombre Mardoqueo se hacía cada vez más grande.",
      "5": "Los judíos golpeaban a todos sus enemigos a golpe de espada, con matanza y destrucción, y hacían lo que querían con los que los odiaban.",
      "6": "En la ciudadela de Susa, los judíos mataron y destruyeron a quinientos hombres.",
      "7": "Mataron a Parshandatha, Dalphon, Aspatha,",
      "8": "Poratha, Adalia, Aridatha,",
      "9": "Parmashta, Arisai, Aridai, y Vaizatha,",
      "10": "los diez hijos de Haman hijo de Hammedatha, el enemigo de los judíos, pero no pusieron su mano en el botín. ",
      "11": "Aquel día se presentó ante el rey el número de los muertos en la ciudadela de Susa.",
      "12": "El rey dijo a la reina Ester: “Los judíos han matado y destruido a quinientos hombres en la ciudadela de Susa, incluidos los diez hijos de Amán; ¡qué han hecho entonces en el resto de las provincias del rey! ¿Cuál es tu petición? Se te concederá. ¿Cuál es tu otra petición? Se hará”. ",
      "13": "Entonces Ester dijo: “Si al rey le parece bien, que se conceda a los judíos que están en Susa que hagan también mañana lo que se ha decretado hoy, y que los diez hijos de Amán sean colgados en la horca.” ",
      "14": "El rey ordenó que se hiciera esto. Se dio un decreto en Susa, y colgaron a los diez hijos de Amán.",
      "15": "Los judíos que estaban en Susa se reunieron también el día catorce del mes de Adar y mataron a trescientos hombres en Susa, pero no pusieron la mano en el botín. ",
      "16": "Los demás judíos que estaban en las provincias del rey se reunieron, defendieron sus vidas, descansaron de sus enemigos y mataron a setenta y cinco mil de los que los odiaban; pero no pusieron su mano en el botín.",
      "17": "Esto lo hicieron el día trece del mes de Adar, y el día catorce de ese mes descansaron y lo convirtieron en un día de fiesta y alegría. ",
      "18": "Pero los judíos que estaban en Susa se reunieron los días trece y catorce del mes; y el día quince de ese mes descansaron, y lo convirtieron en un día de fiesta y alegría.",
      "19": "Por lo tanto, los judíos de las aldeas que viven en las ciudades no amuralladas, hacen del decimocuarto día del mes de Adar un día de alegría y de fiesta, un día festivo, y un día para enviarse regalos de comida unos a otros. ",
      "20": "Mardoqueo escribió estas cosas y envió cartas a todos los judíos que se encontraban en todas las provincias del rey Asuero, tanto de cerca como de lejos,",
      "21": "para ordenarles que celebraran anualmente los días catorce y quince del mes de Adar,",
      "22": "como los días en que los judíos descansaban de sus enemigos, y el mes que se convertía para ellos de tristeza en alegría, y de luto en fiesta; para que los hicieran días de fiesta y de alegría, y para que se enviaran regalos de comida unos a otros, y regalos a los necesitados.",
      "23": "Los judíos aceptaron la costumbre que habían iniciado, como les había escrito Mardoqueo,",
      "24": "porque Amán, hijo de Hamedata, el agagita, enemigo de todos los judíos, había tramado contra los judíos para destruirlos, y había echado a “Pur”, es decir, a la suerte, para consumirlos y destruirlos;",
      "25": "pero cuando esto fue conocido por el rey, éste ordenó por cartas que su malvado plan, que había planeado contra los judíos, volviera sobre su propia cabeza, y que él y sus hijos fueran colgados en la horca. ",
      "26": "Por eso llamaron a estos días “Purim”, de la palabra “Pur”. Por lo tanto, a causa de todas las palabras de esta carta, y de lo que habían visto sobre este asunto, y de lo que les había llegado,",
      "27": "los judíos establecieron y se impusieron a sí mismos, a sus descendientes y a todos los que se unieron a ellos, para que no dejasen de guardar estos dos días según lo que estaba escrito y según su tiempo señalado cada año;",
      "28": "y que estos días fueran recordados y guardados a través de cada generación, cada familia, cada provincia y cada ciudad; y que estos días de Purim no desaparecieran de entre los judíos, ni su memoria pereciera de su descendencia. ",
      "29": "Entonces la reina Ester, hija de Abihail, y el judío Mardoqueo escribieron con toda autoridad para confirmar esta segunda carta de Purim.",
      "30": "Envió cartas a todos los judíos de las ciento veintisiete provincias del reino de Asuero con palabras de paz y de verdad,",
      "31": "para confirmar estos días de Purim en sus tiempos señalados, como habían decretado Mardoqueo el judío y la reina Ester, y como se habían impuesto a sí mismos y a sus descendientes en materia de ayunos y de luto.",
      "32": "El mandamiento de Ester confirmó estos asuntos de Purim; y fue escrito en el libro."
    },
    "10": {
      "1": "El rey Asuero impuso un tributo en la tierra y en las islas del mar.",
      "2": "¿No están escritos en el libro de las crónicas de los reyes de Media y de Persia todos los actos de su poder y de su fuerza, y la relación completa de la grandeza de Mardoqueo, a la que el rey le hizo avanzar?",
      "3": "Porque Mardoqueo, el judío, estaba junto al rey Asuero, y era grande entre los judíos y aceptado por la multitud de sus hermanos, buscando el bien de su pueblo y hablando de paz a todos sus descendientes."
    }
  },
  "job": {
    "1": {
      "1": "Había un hombre en la tierra de Uz, cuyo nombre era Job. Aquel hombre era intachable y recto, y temía a Dios, y se apartaba del mal.",
      "2": "Le nacieron siete hijos y tres hijas.",
      "3": "Sus posesiones eran también siete mil ovejas, tres mil camellos, quinientas yuntas de bueyes, quinientas asnas y una casa muy grande; de modo que este hombre era el más grande de todos los hijos del oriente.",
      "4": "Sus hijos fueron y celebraron una fiesta en la casa de cada uno en su cumpleaños; y enviaron a llamar a sus tres hermanas para que comieran y bebieran con ellos.",
      "5": "Y cuando los días de su fiesta se acabaron, Job envió a santificarlas, y se levantó de madrugada y ofreció holocaustos según el número de todas ellas. Porque Job decía: “Puede ser que mis hijos hayan pecado y renunciado a Dios en su corazón”. Job lo hacía continuamente. ",
      "6": "El día en que los hijos de Dios vinieron a presentarse ante Yahvé, Satanás también vino entre ellos.",
      "7": "Yahvé dijo a Satanás: “¿De dónde vienes?” Entonces Satanás respondió a Yahvé, y dijo: “De ir y venir por la tierra, y de andar arriba y abajo en ella”. ",
      "8": "Yahvé dijo a Satanás: “¿Has considerado a mi siervo Job? Porque no hay nadie como él en la tierra, un hombre intachable y recto, que teme a Dios y se aparta del mal.” ",
      "9": "Entonces Satanás respondió a Yahvé y dijo: “¿Acaso Job teme a Dios por nada?",
      "10": "¿No has hecho un cerco alrededor de él, de su casa y de todo lo que tiene, por todos lados? Has bendecido la obra de sus manos, y su hacienda ha aumentado en la tierra.",
      "11": "Pero extiende ahora tu mano y toca todo lo que tiene, y te denunciará en tu cara”. ",
      "12": "Yahvé dijo a Satanás: “Mira, todo lo que tiene está en tu poder. Sólo que sobre él no extiendas tu mano”. Entonces Satanás salió de la presencia de Yahvé.",
      "13": "Cayó un día en que sus hijos y sus hijas estaban comiendo y bebiendo vino en la casa de su hermano mayor,",
      "14": "que un mensajero vino a Job y le dijo: “Los bueyes estaban arando y los asnos apacentando junto a ellos,",
      "15": "y los sabeos atacaron y se los llevaron. Sí, han matado a los siervos a filo de espada, y sólo yo he escapado para contártelo”. ",
      "16": "Mientras él seguía hablando, vino también otro y dijo: “El fuego de Dios ha caído del cielo y ha quemado a las ovejas y a los siervos y los ha consumido, y sólo yo he escapado para contarlo.” ",
      "17": "Mientras él seguía hablando, llegó otro y dijo: “Los caldeos han formado tres bandas y han arrasado con los camellos, y los han llevado, sí, y han matado a los siervos a filo de espada; y sólo yo he escapado para contártelo.” ",
      "18": "Mientras él seguía hablando, vino también otro y dijo: “Tus hijos y tus hijas estaban comiendo y bebiendo vino en casa de su hermano mayor,",
      "19": "y he aquí que vino un gran viento del desierto y golpeó las cuatro esquinas de la casa, y cayó sobre los jóvenes, y están muertos. Sólo yo he escapado para contarlo”. ",
      "20": "Entonces Job se levantó, rasgó su túnica, se afeitó la cabeza, se postró en el suelo y adoró.",
      "21": "Dijo: “Desnudo salí del vientre de mi madre, y desnudo volveré a él. Yahvé dio, y Yahvé ha quitado. Bendito sea el nombre de Yahvé”.",
      "22": "En todo esto, Job no pecó ni acusó a Dios de haber obrado mal."
    },
    "2": {
      "1": "También el día en que los hijos de Dios vinieron a presentarse ante Yahvé, Satanás vino también entre ellos para presentarse ante Yahvé.",
      "2": "Yahvé dijo a Satanás: “¿De dónde vienes?” Satanás respondió a Yahvé, y dijo: “De ir y venir por la tierra, y de andar arriba y abajo en ella”. ",
      "3": "Yahvé dijo a Satanás: “¿Has considerado a mi siervo Job? Porque no hay nadie como él en la tierra, un hombre intachable y recto, que teme a Dios y se aparta del mal. Todavía mantiene su integridad, aunque tú me incitaste contra él, para arruinarlo sin causa”. ",
      "4": "Satanás respondió a Yahvé y dijo: “Piel por piel. Sí, todo lo que el hombre tiene lo dará por su vida.",
      "5": "Pero extiende ahora tu mano y toca su hueso y su carne, y te denunciará en tu cara.” ",
      "6": "Yahvé dijo a Satanás: “Mira, está en tu mano. Sólo perdona su vida”. ",
      "7": "Entonces Satanás salió de la presencia de Yavé, e hirió a Job con llagas dolorosas desde la planta del pie hasta la cabeza.",
      "8": "Tomó para sí un tiesto para rasparse, y se sentó entre las cenizas.",
      "9": "Entonces su mujer le dijo: “¿Aún mantienes tu integridad? Renuncia a Dios y muere”. ",
      "10": "Pero él le dijo: “Hablas como una de las mujeres necias. ¿Qué? ¿Recibiremos el bien de la mano de Dios, y no recibiremos el mal?” En todo esto Job no pecó con sus labios.",
      "11": "Cuando los tres amigos de Job se enteraron de todo este mal que le había sobrevenido, vinieron cada uno de su lugar: Elifaz el temanita, Bildad el suhita y Zofar el naamatita; y se citaron juntos para venir a compadecerse de él y a consolarlo.",
      "12": "Cuando alzaron los ojos desde lejos y no lo reconocieron, alzaron la voz y lloraron; cada uno de ellos rasgó su manto y esparció polvo sobre sus cabezas hacia el cielo.",
      "13": "Y se sentaron con él en el suelo durante siete días y siete noches, sin que nadie le dirigiera la palabra, porque veían que su dolor era muy grande."
    },
    "3": {
      "1": "Después de esto, Job abrió la boca y maldijo el día de su nacimiento.",
      "2": "Job respondió: ",
      "3": "  “Que perezca el día en que nací,   la noche que dijo: “Hay un niño concebido”. ",
      "4": "  Que ese día sea la oscuridad.   No dejes que Dios desde arriba lo busque,   ni dejar que la luz lo ilumine. ",
      "5": "  Que las tinieblas y la sombra de la muerte la reclamen para sí.   Deja que una nube se detenga en ella.   Que todo lo que hace el día negro lo aterrorice. ",
      "6": "  En cuanto a esa noche, que la oscuridad espesa se apodere de ella.   Que no se regocije entre los días del año.   Que no entre en el número de los meses. ",
      "7": "  He aquí, que esa noche sea estéril.   Que no venga ninguna voz alegre. ",
      "8": "  Que lo maldigan los que maldicen el día,   que están listos para despertar al Leviatán. ",
      "9": "  Que las estrellas de su crepúsculo sean oscuras.   Que busque la luz, pero no la tenga,   ni dejar que vea los párpados de la mañana, ",
      "10": "  porque no cerró las puertas del vientre de mi madre,   ni ocultó los problemas a mis ojos. ",
      "11": "  “¿Por qué no he muerto desde el vientre?   ¿Por qué no renuncié al espíritu cuando mi madre me dio a luz? ",
      "12": "  ¿Por qué me recibieron las rodillas?   ¿O por qué el pecho, que debo amamantar? ",
      "13": "  Por ahora debería haberme acostado y callado.   Debería haber dormido, así habría descansado, ",
      "14": "  con reyes y consejeros de la tierra,   que construyeron lugares de desecho para sí mismos; ",
      "15": "  o con príncipes que tenían oro,   que llenaron sus casas de plata; ",
      "16": "  o como un nacimiento intempestivo oculto no había sido,   como niños que nunca vieron la luz. ",
      "17": "  Allí los malvados dejan de molestar.   Allí descansan los cansados. ",
      "18": "  Allí los prisioneros están a gusto juntos.   No oyen la voz del capataz. ",
      "19": "  Los pequeños y los grandes están allí.   El siervo es libre de su amo. ",
      "20": "  “¿Por qué se da luz al que está en la miseria?   vida a los amargados del alma, ",
      "21": "  que anhelan la muerte, pero no llega;   y cavar para ello más que para los tesoros ocultos, ",
      "22": "  que se regocijan en exceso,   y se alegran, cuando pueden encontrar la tumba? ",
      "23": "  Por qué se da luz a un hombre cuyo camino está oculto,   a los que Dios ha cobijado? ",
      "24": "  Porque mis suspiros llegan antes de comer.   Mis gemidos se derraman como agua. ",
      "25": "  Porque lo que temo viene sobre mí,   lo que me da miedo viene a mí. ",
      "26": "  No estoy tranquilo, ni tengo descanso;   pero los problemas vienen”."
    },
    "4": {
      "1": "Entonces Elifaz, el temanita, respondió, ",
      "2": "  “Si alguien se aventura a hablar contigo, ¿te apenarás?   Pero, ¿quién puede abstenerse de hablar? ",
      "3": "  He aquí que has instruido a muchos,   has fortalecido las manos débiles. ",
      "4": "  Tus palabras han sostenido al que estaba cayendo,   has hecho firmes las rodillas débiles. ",
      "5": "  Pero ahora ha llegado a ti, y te desmayas.   Te toca, y te sientes perturbado. ",
      "6": "  ¿No es tu piedad tu confianza?   ¿No es la integridad de tus caminos tu esperanza? ",
      "7": "  “¿Recuerdas, ahora, a quien pereció siendo inocente?   ¿O dónde se cortó el montante? ",
      "8": "  Según lo que he visto, los que aran la iniquidad   y sembrar problemas, cosechar lo mismo. ",
      "9": "  Por el soplo de Dios perecen.   Por la explosión de su ira son consumidos. ",
      "10": "  El rugido del león,   y la voz del león feroz,   los dientes de los jóvenes leones, están rotos. ",
      "11": "  El viejo león perece por falta de presa.   Los cachorros de la leona están dispersos por el mundo. ",
      "12": "  “Ahora bien, una cosa me fue traída en secreto.   Mi oído recibió un susurro de ella. ",
      "13": "  En los pensamientos de las visiones de la noche,   cuando el sueño profundo cae sobre los hombres, ",
      "14": "  me invadió el miedo y el temblor,   que hizo temblar todos mis huesos. ",
      "15": "  Entonces un espíritu pasó ante mi rostro.   El vello de mi carne se erizó. ",
      "16": "  Se quedó quieto, pero no pude discernir su aspecto.   Una forma estaba ante mis ojos.   Silencio, luego escuché una voz que decía, ",
      "17": "  “¿Será el hombre mortal más justo que Dios?   ¿Puede un hombre ser más puro que su Creador? ",
      "18": "  He aquí que no se fía de sus siervos.   Acusa a sus ángeles de error. ",
      "19": "  Cuánto más los que habitan en casas de barro,   cuyos cimientos están en el polvo,   ¡que son aplastados ante la polilla! ",
      "20": "  Entre la mañana y la noche son destruidos.   Perecen para siempre sin tener en cuenta nada. ",
      "21": "  ¿No está la cuerda de su tienda arrancada dentro de ellos?   Mueren, y eso sin sabiduría”."
    },
    "5": {
      "1": "  “Llama ahora; ¿hay alguien que te responda?   ¿A cuál de los santos te dirigirás? ",
      "2": "  Porque el resentimiento mata al necio,   y los celos matan a los simples. ",
      "3": "  He visto a los insensatos echar raíces,   pero de repente maldije su morada. ",
      "4": "  Sus hijos están lejos de la seguridad.   Son aplastados en la puerta.   Tampoco hay ninguno que los entregue, ",
      "5": "  cuya cosecha devoran los hambrientos,   y sacarlo incluso de las espinas.   La trampa se abre para su sustancia. ",
      "6": "  Porque la aflicción no sale del polvo,   tampoco los problemas surgen de la tierra; ",
      "7": "  pero el hombre ha nacido para el problema,   mientras las chispas vuelan hacia arriba. ",
      "8": "  “Pero en cuanto a mí, buscaría a Dios.   Yo encomendaría mi causa a Dios, ",
      "9": "  que hace grandes cosas que no se pueden comprender,   cosas maravillosas sin número; ",
      "10": "  que hace llover sobre la tierra,   y envía aguas sobre los campos; ",
      "11": "  para que ponga en alto a los de abajo,   los que lloran son exaltados a la seguridad. ",
      "12": "  Él frustra los planes de los astutos,   para que sus manos no puedan realizar su empresa. ",
      "13": "  El toma a los sabios en su propia astucia;   el consejo de los astutos se lleva de cabeza. ",
      "14": "  Se encuentran con la oscuridad durante el día,   y tantear al mediodía como en la noche. ",
      "15": "  Pero él salva de la espada de su boca,   incluso a los necesitados de la mano de los poderosos. ",
      "16": "  Así que el pobre tiene esperanza,   y la injusticia le cierra la boca. ",
      "17": "  “He aquí que es feliz el hombre a quien Dios corrige.   Por lo tanto, no desprecies el castigo del Todopoderoso. ",
      "18": "  Porque él hiere y venda.   Se hiere y sus manos se recomponen. ",
      "19": "  Él te librará en seis problemas;   sí, en siete ningún mal te tocará. ",
      "20": "  En el hambre te reducirá de la muerte;   en la guerra, del poder de la espada. ",
      "21": "  Estarás oculto del azote de la lengua,   ni tendrás miedo de la destrucción cuando llegue. ",
      "22": "  Te reirás de la destrucción y del hambre,   ni tendrás miedo de los animales de la tierra. ",
      "23": "  Porque serás aliado de las piedras del campo.   Los animales del campo estarán en paz contigo. ",
      "24": "  Sabrás que tu tienda está en paz.   Visitarás tu redil y no echarás nada en falta. ",
      "25": "  También sabrás que tu descendencia será grande,   tu descendencia como la hierba de la tierra. ",
      "26": "  Llegarás a la tumba en plena edad,   como una descarga de grano viene en su temporada. ",
      "27": "  He aquí que lo hemos investigado. Así es.   Escúchalo y conócelo para tu bien”.  "
    }
  }
};

