
	
export const bib_verses = {
  "2_kings": {
    "17": {
      "1": "En el duodécimo año de Acaz, rey de Judá, Oseas, hijo de Ela, comenzó a reinar en Samaria sobre Israel durante nueve años.",
      "2": "Hizo lo que era malo a los ojos de Yavé, pero no como los reyes de Israel que lo precedieron.",
      "3": "Salmanasar, rey de Asiria, subió contra él, y Oseas se convirtió en su siervo y le trajo tributo.",
      "4": "El rey de Asiria descubrió una conspiración en Oseas, pues éste había enviado mensajeros a So, rey de Egipto, y no ofrecía tributo al rey de Asiria, como lo había hecho año tras año. Por lo tanto, el rey de Asiria lo apresó y lo encarceló.",
      "5": "Entonces el rey de Asiria recorrió todo el país, subió a Samaria y la sitió durante tres años.",
      "6": "En el noveno año de Oseas, el rey de Asiria tomó Samaria y se llevó a Israel a Asiria, y los puso en Halah y en el Habor, el río de Gozán, y en las ciudades de los medos. ",
      "7": "Fue así porque los hijos de Israel habían pecado contra Yahvé su Dios, que los sacó de la tierra de Egipto de la mano del faraón, rey de Egipto, y habían temido a otros dioses,",
      "8": "y anduvieron en los estatutos de las naciones que Yahvé echó de delante de los hijos de Israel, y de los reyes de Israel, que ellos hicieron.",
      "9": "Los hijos de Israel hicieron en secreto cosas que no eran rectas contra Yahvé su Dios; y se construyeron lugares altos en todas sus ciudades, desde la torre de los vigías hasta la ciudad fortificada;",
      "10": "y se erigieron columnas y postes de Asera en todo cerro alto y debajo de todo árbol verde",
      "11": "y quemaron incienso en todos los lugares altos, como lo hicieron las naciones que Yahvé transportó antes de ellos; e hicieron cosas perversas para provocar la ira de Yahvé;",
      "12": "y sirvieron a ídolos, de los cuales Yahvé les había dicho: “No harás esto.”",
      "13": "Sin embargo, Yahvé dio testimonio a Israel y a Judá, por medio de todo profeta y todo vidente, diciendo: “Convertíos de vuestros malos caminos, y guardad mis mandamientos y mis estatutos, conforme a toda la ley que ordené a vuestros padres, y que os envié por medio de mis siervos los profetas.”",
      "14": "Sin embargo, no quisieron escuchar, sino que endurecieron su cuello como el de sus padres, que no creyeron en Yavé, su Dios.",
      "15": "Rechazaron sus estatutos y su pacto que había hecho con sus padres, y sus testimonios que les había atestiguado; siguieron la vanidad y se envanecieron, y siguieron a las naciones que estaban a su alrededor, acerca de las cuales Yahvé les había ordenado que no hicieran como ellas.",
      "16": "Abandonaron todos los mandatos de Yahvé, su Dios, y se hicieron imágenes fundidas, dos becerros, e hicieron una Asera, y adoraron a todo el ejército del cielo, y sirvieron a Baal.",
      "17": "Hicieron pasar por el fuego a sus hijos y a sus hijas, usaron la adivinación y los encantamientos, y se vendieron para hacer lo que era malo a los ojos de Yahvé, para provocarlo a la ira.",
      "18": "Por eso Yahvé se enojó mucho con Israel y los quitó de su vista. No quedó más que la tribu de Judá. ",
      "19": "También Judá no guardó los mandamientos de Yavé, su Dios, sino que anduvo en los estatutos de Israel que ellos hicieron.",
      "20": "Yahvé rechazó a toda la descendencia de Israel, la afligió y la entregó en manos de salteadores, hasta echarla de su vista.",
      "21": "Porque arrancó a Israel de la casa de David, e hicieron rey a Jeroboam hijo de Nabat; y Jeroboam apartó a Israel de seguir a Yavé y les hizo cometer un gran pecado.",
      "22": "Los hijos de Israel anduvieron en todos los pecados de Jeroboam que él cometió; no se apartaron de ellos",
      "23": "hasta que Yahvé quitó a Israel de su vista, como lo dijo por medio de todos sus siervos los profetas. Así que Israel fue llevado de su propia tierra a Asiria hasta el día de hoy. ",
      "24": "El rey de Asiria trajo gente de Babilonia, de Cuta, de Avva, de Hamat y de Sefarvaim, y los colocó en las ciudades de Samaria en lugar de los hijos de Israel; y se apoderaron de Samaria y vivieron en sus ciudades.",
      "25": "Así fue que, al principio de su permanencia allí, no temieron a Yavé. Por eso Yahvé envió leones entre ellos, que mataron a algunos de ellos.",
      "26": "Por eso hablaron con el rey de Asiria, diciendo: “Las naciones que has transportado y colocado en las ciudades de Samaria no conocen la ley del dios de la tierra. Por eso ha enviado leones entre ellos; y he aquí que los matan, porque no conocen la ley del dios de la tierra.” ",
      "27": "Entonces el rey de Asiria ordenó: “Lleva allí a uno de los sacerdotes que trajiste de allí, y que  vaya y habite allí, y que les enseñe la ley del dios de la tierra.” ",
      "28": "Entonces uno de los sacerdotes que habían llevado de Samaria vino y vivió en Betel, y les enseñó cómo debían temer a Yavé. ",
      "29": "Sin embargo, cada nación hizo sus propios dioses y los puso en las casas de los lugares altos que los samaritanos habían hecho, cada nación en sus ciudades en las que vivían.",
      "30": "Los hombres de Babilonia hicieron a Succoth Benot, y los hombres de Cut hicieron a Nergal, y los hombres de Hamat hicieron a Ashima,",
      "31": "y los avvitas hicieron a Nibhaz y a Tartak; y los sefarvitas quemaron a sus hijos en el fuego a Adrammelech y a Anammelech, los dioses de Sefarvaim.",
      "32": "Temían, pues, a Yavé, y también hacían de entre ellos sacerdotes de los lugares altos, que sacrificaban para ellos en las casas de los lugares altos.",
      "33": "Temían a Yahvé, y también servían a sus propios dioses, según los caminos de las naciones de las que habían sido transportados.",
      "34": "Hasta el día de hoy hacen lo mismo que antes. No temen a Yahvé, y no siguen los estatutos, ni las ordenanzas, ni la ley, ni el mandamiento que Yahvé ordenó a los hijos de Jacob, a quienes llamó Israel;",
      "35": "con quienes Yahvé había hecho un pacto y les había ordenado, diciendo: “No temeréis a otros dioses, ni os inclinaréis ante ellos, ni les serviréis, ni les sacrificaréis",
      "36": "sino que temeréis a Yahvé, que os sacó de la tierra de Egipto con gran poder y con brazo extendido, y a él os inclinaréis y a él sacrificaréis.",
      "37": "Los estatutos y las ordenanzas, la ley y el mandamiento que él escribió para vosotros, los cumpliréis para siempre. No temeréis a otros dioses.",
      "38": "No olvidarás el pacto que he hecho contigo. No temerán a otros dioses.",
      "39": "Sino que temerás a Yahvé, tu Dios, y él te librará de la mano de todos tus enemigos.” ",
      "40": "Sin embargo, no escucharon, sino que hicieron lo mismo que antes.",
      "41": "Así que estas naciones temieron a Yavé, y también sirvieron a sus imágenes grabadas. Sus hijos hicieron lo mismo, y también los hijos de sus hijos. Hacen lo mismo que hicieron sus padres hasta el día de hoy."
    },
    "18": {
      "1": "En el tercer año de Oseas hijo de Ela, rey de Israel, comenzó a reinar Ezequías hijo de Acaz, rey de Judá.",
      "2": "Tenía veinticinco años cuando comenzó a reinar, y reinó veintinueve años en Jerusalén. Su madre se llamaba Abi, hija de Zacarías.",
      "3": "Hizo lo que era justo a los ojos del Señor, conforme a todo lo que había hecho su padre David.",
      "4": "Quitó los lugares altos, rompió las columnas y derribó la Asera. También hizo pedazos la serpiente de bronce que había hecho Moisés, porque en aquellos días los hijos de Israel le quemaban incienso; y la llamó Nehustán.",
      "5": "Confió en Yahvé, el Dios de Israel, de modo que después de él no hubo nadie como él entre todos los reyes de Judá, ni entre los que le precedieron.",
      "6": "Porque se unió a Yavé. No se apartó de seguirlo, sino que guardó sus mandamientos, que Yahvé le ordenó a Moisés.",
      "7": "El Señor estaba con él. Dondequiera que iba, prosperaba. Se rebeló contra el rey de Asiria y no le sirvió.",
      "8": "Golpeó a los filisteos hasta Gaza y sus fronteras, desde la torre de los vigías hasta la ciudad fortificada. ",
      "9": "En el cuarto año del rey Ezequías, que era el séptimo año de Oseas hijo de Ela, rey de Israel, Salmanasar, rey de Asiria, subió contra Samaria y la sitió.",
      "10": "Al cabo de tres años la tomaron. En el sexto año de Ezequías, que era el noveno año de Oseas, rey de Israel, Samaria fue tomada.",
      "11": "El rey de Asiria se llevó a Israel a Asiria, y los puso en Halah y en el Habor, el río de Gozán, y en las ciudades de los medos,",
      "12": "porque no obedecieron la voz de Yavé, su Dios, sino que transgredieron su pacto, todo lo que mandó Moisés, siervo de Yavé, y no quisieron oírlo ni hacerlo. ",
      "13": "En el año catorce del rey Ezequías, Senaquerib, rey de Asiria, subió contra todas las ciudades fortificadas de Judá y las tomó.",
      "14": "Ezequías, rey de Judá, envió al rey de Asiria a Laquis, diciendo: “Te he ofendido. Retírate de mí. Lo que me impongas, lo soportaré”. El rey de Asiria asignó a Ezequías, rey de Judá, trescientos talentos de plata y treinta talentos  de oro.",
      "15": "Ezequías le dio toda la plata que se encontraba en la casa de Yavé y en los tesoros de la casa real.",
      "16": "En aquel tiempo, Ezequías cortó el oro de las puertas del templo de Yavé y de las columnas que Ezequías, rey de Judá, había recubierto, y se lo dio al rey de Asiria. ",
      "17": "El rey de Asiria envió a Tartán, a Rabsaris y a Rabsaces desde Laquis al rey Ezequías con un gran ejército a Jerusalén. Subieron y llegaron a Jerusalén. Cuando subieron, vinieron y se pararon junto al conducto del estanque superior, que está en el camino del campo del batán.",
      "18": "Cuando llamaron al rey, salieron hacia ellos Eliaquim, hijo de Hilcías, que estaba al frente de la casa, y Sebnah, el escriba, y Joah, hijo de Asaf, el registrador.",
      "19": "Rabsaces les dijo: “Di ahora a Ezequías: “El gran rey, el rey de Asiria, dice: “¿Qué confianza es ésta en la que confías?",
      "20": "Ustedes dicen (pero no son más que palabras vanas): ‘Hay consejo y fuerza para la guerra’. Ahora bien, ¿en quién confían ustedes, que se han rebelado contra mí?",
      "21": "Ahora bien, he aquí que confiáis en el bastón de esta caña magullada, incluso en Egipto. Si un hombre se apoya en ella, se le meterá en la mano y la atravesará. Así es el Faraón, rey de Egipto, para todos los que confían en él.",
      "22": "Pero si me decís: “Confiamos en el Señor, nuestro Dios”, ¿no es aquel cuyos lugares altos y cuyos altares ha quitado Ezequías, y ha dicho a Judá y a Jerusalén: “Adoraréis ante este altar en Jerusalén”?",
      "23": "Ahora, pues, por favor, dad prendas a mi amo el rey de Asiria, y yo os daré dos mil caballos si sois capaces de poner jinetes en ellos.",
      "24": "¿Cómo, pues, puedes rechazar el rostro de un capitán del más pequeño de los siervos de mi amo, y poner tu confianza en Egipto para carros y jinetes?",
      "25": "¿Acaso he subido sin Yahvé contra este lugar para destruirlo? Yahvé me dijo: “Sube contra esta tierra y destrúyela””. ",
      "26": "Entonces Eliaquim, hijo de Jilquías, Sebna y Joá, dijeron a Rabsaces: “Por favor, habla a tus siervos en lengua siria, porque nosotros la entendemos. No hables con nosotros en la lengua de los judíos, a oídos del pueblo que está en el muro”. ",
      "27": "Pero Rabsaces les dijo: “¿Acaso mi amo me ha enviado a su amo y a ustedes para decirles estas palabras? ¿No me ha enviado a los hombres que se sientan en el muro, para que coman su propio estiércol y beban su propia orina con ustedes?” ",
      "28": "Entonces Rabsaces se puso de pie y gritó con gran voz en el idioma de los judíos, y habló diciendo: “Oigan la palabra del gran rey, el rey de Asiria.",
      "29": "El rey dice: ‘No dejes que Ezequías te engañe, porque no podrá librarte de su mano.",
      "30": "No dejen que Ezequías los haga confiar en Yavé, diciendo: “Seguramente Yavé nos librará, y esta ciudad no será entregada en manos del rey de Asiria.”",
      "31": "No escuchen a Ezequías’. Porque el rey de Asiria dice: ‘Hagan las paces conmigo y salgan a mi encuentro; y cada uno de ustedes coma de su propia vid, y cada uno de su propia higuera, y cada uno beba agua de su propia cisterna;",
      "32": "hasta que yo venga y los lleve a una tierra como la suya, una tierra de grano y de vino nuevo, una tierra de pan y de viñas, una tierra de olivos y de miel, para que vivan y no mueran. No escuchen a Ezequías cuando los convenza diciendo: “El Señor nos librará”.",
      "33": "¿Acaso alguno de los dioses de las naciones ha librado su tierra de la mano del rey de Asiria?",
      "34": "¿Dónde están los dioses de Hamat y de Arpad? ¿Dónde están los dioses de Sefarvaim, de Hena y de Ivva? ¿Han librado a Samaria de mi mano?",
      "35": "¿Quiénes son, entre todos los dioses de los países, los que han librado a su país de mi mano, para que Yahvé libere a Jerusalén de mi mano?” ",
      "36": "Pero el pueblo se quedó callado y no le respondió ni una sola palabra, porque la orden del rey era: “No le respondan”.",
      "37": "Entonces Eliaquim, hijo de Hilcías, que estaba al frente de la casa, vino con Sebna, el escriba, y con Joah, hijo de Asaf, el registrador, a Ezequías con las ropas rasgadas, y le contaron las palabras de Rabsaces."
    },
    "19": {
      "1": "Cuando el rey Ezequías lo oyó, se rasgó las vestiduras, se cubrió de cilicio y entró en la casa de Yahvé.",
      "2": "Envió a Eliaquim, que estaba al frente de la casa, a Sebna, el escriba, y a los ancianos de los sacerdotes, cubiertos de cilicio, a ver al profeta Isaías, hijo de Amoz.",
      "3": "Le dijeron: “Ezequías dice: ‘Hoy es un día de angustia, de reprimenda y de rechazo; porque los niños han llegado al punto de nacer, y no hay fuerza para librarlos.",
      "4": "Puede ser que Yavé tu Dios escuche todas las palabras de Rabsaces, a quien el rey de Asiria, su amo, ha enviado para desafiar al Dios vivo, y reprenda las palabras que Yavé tu Dios ha escuchado. Por lo tanto, levanta tu oración por el remanente que queda’”. ",
      "5": "Los siervos del rey Ezequías acudieron a Isaías.",
      "6": "Isaías les dijo: “Díganle esto a su amo: El Señor dice: “No temas las palabras que has oído, con las que los servidores del rey de Asiria me han blasfemado.",
      "7": "He aquí que yo pondré un espíritu en él, y oirá noticias, y volverá a su tierra. Haré que caiga a espada en su propia tierra”. ",
      "8": "Volvió, pues, Rabsaces y encontró al rey de Asiria guerreando contra Libna, pues había oído que había salido de Laquis.",
      "9": "Cuando oyó decir de Tirhakah, rey de Etiopía: “He aquí que ha salido a pelear contra ti”, volvió a enviar mensajeros a Ezequías, diciendo:",
      "10": "“Dile a Ezequías, rey de Judá, lo siguiente: ‘No permitas que tu Dios, en quien confías, te engañe diciendo que Jerusalén no será entregada en manos del rey de Asiria.",
      "11": "He aquí, tú has oído lo que los reyes de Asiria han hecho a todas las tierras, destruyéndolas por completo. ¿Serás liberado?",
      "12": "¿Los dioses de las naciones los han librado, a los que mis padres han destruido: Gozán, Harán, Rezef y los hijos de Edén que estaban en Telasar?",
      "13": "¿Dónde está el rey de Hamat, el rey de Arpad y el rey de la ciudad de Sefarvaim, de Hena y de Ivva?” ",
      "14": "Ezequías recibió la carta de manos de los mensajeros y la leyó. Entonces Ezequías subió a la casa de Yavé y la extendió ante Yavé.",
      "15": "Ezequías oró ante Yavé y dijo: “Yavé, Dios de Israel, que estás entronizado sobre los querubines, tú eres el Dios, sólo tú, de todos los reinos de la tierra. Tú has hecho el cielo y la tierra.",
      "16": "Inclina tu oído, Yahvé, y escucha. Abre tus ojos, Yahvé, y mira. Escucha las palabras de Senaquerib, que ha enviado para desafiar al Dios vivo.",
      "17": "En verdad, Yahvé, los reyes de Asiria han asolado a las naciones y a sus tierras,",
      "18": "y han echado al fuego a sus dioses, pues no eran dioses, sino obra de manos de hombres, madera y piedra. Por eso los han destruido.",
      "19": "Ahora, pues, Yahvé, nuestro Dios, sálvanos, te lo ruego, de su mano, para que todos los reinos de la tierra sepan que tú, Yahvé, eres el único Dios.” ",
      "20": "Entonces Isaías, hijo de Amoz, envió a decir a Ezequías: “Yahvé, el Dios de Israel, dice: ‘Me has orado contra Senaquerib, rey de Asiria, y te he escuchado.",
      "21": "Esta es la palabra que Yahvé ha pronunciado sobre él: ‘La virgen hija de Sión te ha despreciado y se ha burlado de ti. La hija de Jerusalén ha sacudido la cabeza ante ti.",
      "22": "¿A quién has desafiado y blasfemado? ¿Contra quién has alzado tu voz y levantado tus ojos en alto? ¡Contra el Santo de Israel!",
      "23": "Por medio de tus mensajeros, has desafiado al Señor y has dicho: “Con la multitud de mis carros, he subido a la altura de los montes, a lo más recóndito del Líbano, y cortaré sus altos cedros y sus selectos cipreses; y entraré en su más lejana morada, en el bosque de su campo fructífero.",
      "24": "He cavado y bebido aguas extrañas, y secaré todos los ríos de Egipto con la planta de mis pies”.",
      "25": "¿No has oído cómo lo he hecho hace mucho tiempo, y lo he formado de antiguo? Ahora he hecho que sea tuyo el arrasar las ciudades fortificadas hasta convertirlas en montones ruinosos.",
      "26": "Por eso sus habitantes tenían poco poder. Estaban consternados y confundidos. Eran como la hierba del campo y como la hierba verde, como la hierba de los tejados y como el grano desgastado antes de crecer.",
      "27": "Pero yo sé que te sientas, que sales, que entras y que te enfureces contra mí.",
      "28": "A causa de tu furia contra mí, y porque tu arrogancia ha subido a mis oídos, pondré mi garfio en tu nariz y mi freno en tus labios, y te haré volver por el camino por el que viniste. ",
      "29": "“Esta será la señal para vosotros: Este año comeréis lo que crezca por sí mismo, y el segundo año lo que brote de él; y el tercer año sembraréis y segaréis, y plantaréis viñas y comeréis su fruto.",
      "30": "El remanente que ha escapado de la casa de Judá volverá a echar raíces hacia abajo y a dar fruto hacia arriba.",
      "31": "Porque de Jerusalén saldrá un remanente, y del monte Sión los que escapen. El celo de Yahvé lo realizará. ",
      "32": "“Por eso dice el Señor sobre el rey de Asiria: ‘No vendrá a esta ciudad, ni lanzará una flecha contra ella. No vendrá ante ella con escudo, ni levantará un montículo contra ella.",
      "33": "Volverá por el mismo camino por el que vino, y no vendrá a esta ciudad’, dice el Señor.",
      "34": "‘Porque yo defenderé esta ciudad para salvarla, por mí y por mi siervo David’”. ",
      "35": "Aquella noche, el ángel de Yavé salió e hirió a ciento ochenta y cinco mil en el campamento de los asirios. Cuando los hombres se levantaron de madrugada, he aquí que todos ellos eran cadáveres.",
      "36": "Entonces Senaquerib, rey de Asiria, partió, se fue a su casa y vivió en Nínive.",
      "37": "Mientras adoraba en la casa de Nisroc, su dios, Adramelec y Sharezer lo hirieron con la espada, y escaparon a la tierra de Ararat. Su hijo Esar Haddón reinó en su lugar."
    },
    "20": {
      "1": "En aquellos días Ezequías estaba enfermo y moribundo. El profeta Isaías, hijo de Amoz, se acercó a él y le dijo: “Yahvé dice: ‘Pon en orden tu casa, porque morirás y no vivirás’”. ",
      "2": "Entonces volvió su rostro hacia la pared y oró a Yavé, diciendo:",
      "3": "“Acuérdate ahora, Yavé, te lo ruego, de cómo he andado delante de ti con verdad y con un corazón perfecto, y he hecho lo que es bueno ante tus ojos.” Y Ezequías lloró amargamente. ",
      "4": "Antes de que Isaías saliera a la parte central de la ciudad, le llegó la palabra de Yavé, que decía:",
      "5": "“Vuelve y dile a Ezequías, príncipe de mi pueblo: ‘Yavé, el Dios de David, tu padre, dice: “He oído tu oración. He visto tus lágrimas. He aquí que yo te curaré. Al tercer día subirás a la casa de Yavé.",
      "6": "Añadiré a tus días quince años. Te libraré a ti y a esta ciudad de la mano del rey de Asiria. Defenderé esta ciudad por mí y por mi siervo David”. ",
      "7": "Isaías dijo: “Toma una torta de higos”. Lo cogieron y lo pusieron a hervir, y se recuperó. ",
      "8": "Ezequías dijo a Isaías: “¿Cuál será la señal de que Yahvé me sanará y de que subiré a la casa de Yahvé al tercer día?” ",
      "9": "Isaías dijo: “Esta será la señal para ustedes de parte de Yahvé, de que Yahvé hará lo que ha dicho: ¿debe la sombra avanzar diez pasos, o retroceder diez pasos?” ",
      "10": "Ezequías respondió: “Es cosa ligera que la sombra avance diez pasos. No, sino que la sombra vuelva atrás diez pasos”. ",
      "11": "El profeta Isaías clamó a Yahvé, y éste hizo retroceder diez pasos la sombra que había descendido en el reloj de sol de Acaz. ",
      "12": "En aquel tiempo Berodac Baladán, hijo de Baladán, rey de Babilonia, envió cartas y un regalo a Ezequías, pues había oído que Ezequías había estado enfermo.",
      "13": "Ezequías los escuchó y les mostró todo el depósito de sus cosas preciosas: la plata, el oro, las especias y el aceite precioso, y la casa de su armadura, y todo lo que se encontraba en sus tesoros. No había nada en su casa, ni en todo su dominio, que Ezequías no les mostrara. ",
      "14": "Entonces el profeta Isaías se acercó al rey Ezequías y le dijo: “¿Qué han dicho estos hombres? ¿De dónde han venido a ti?” Ezequías dijo: “Han venido de un país lejano, incluso de Babilonia”. ",
      "15": "Él dijo: “¿Qué han visto en tu casa?” Ezequías respondió: “Han visto todo lo que hay en mi casa. No hay nada entre mis tesoros que no les haya mostrado”. ",
      "16": "Isaías dijo a Ezequías: “Escucha la palabra de Yahvé.",
      "17": "‘He aquí que vienen días en que todo lo que hay en tu casa, y lo que tus padres han almacenado hasta hoy, será llevado a Babilonia. No quedará nada’, dice el Señor.",
      "18": "‘Se llevarán a algunos de tus hijos que saldrán de ti, a los que engendrarás, y serán eunucos en el palacio del rey de Babilonia’”. ",
      "19": "Entonces Ezequías dijo a Isaías: “La palabra de Yahvé que has pronunciado es buena”. Dijo además: “¿No es así, si la paz y la verdad estarán en mis días?” ",
      "20": "El resto de los hechos de Ezequías, y toda su fuerza, y cómo hizo el estanque y el conducto, y cómo introdujo el agua en la ciudad, ¿no están escritos en el libro de las crónicas de los reyes de Judá?",
      "21": "Ezequías durmió con sus padres, y su hijo Manasés reinó en su lugar."
    },
    "21": {
      "1": "Manasés tenía doce años cuando comenzó a reinar, y reinó cincuenta y cinco años en Jerusalén. El nombre de su madre era Hefzibá.",
      "2": "Hizo lo que era malo a los ojos de Yavé, según las abominaciones de las naciones que Yavé arrojó delante de los hijos de Israel.",
      "3": "Porque volvió a edificar los lugares altos que Ezequías, su padre, había destruido; levantó altares para Baal e hizo una Asera, como hizo Ajab, rey de Israel, y adoró a todo el ejército del cielo, y les sirvió.",
      "4": "Edificó altares en la casa de Yahvé, de la cual Yahvé dijo: “Pondré mi nombre en Jerusalén”.",
      "5": "Construyó altares para todo el ejército del cielo en los dos atrios de la casa de Yavé.",
      "6": "Hizo pasar a su hijo por el fuego, practicó la hechicería, usó encantamientos y trató con los que tenían espíritus familiares y con los magos. Hizo mucho mal a los ojos de Yahvé, para provocarlo a la ira.",
      "7": "Puso la imagen grabada de Asera que había hecho en la casa de la que Yahvé dijo a David y a Salomón su hijo: “En esta casa y en Jerusalén, que he elegido de entre todas las tribus de Israel, pondré mi nombre para siempre;",
      "8": "no haré que los pies de Israel vuelvan a errar fuera de la tierra que di a sus padres, con tal de que observen hacer todo lo que les he mandado, y toda la ley que mi siervo Moisés les mandó.”",
      "9": "Pero ellos no escucharon, y Manasés los sedujo para que hicieran lo que es malo, más de lo que hicieron las naciones que Yahvé destruyó antes de los hijos de Israel. ",
      "10": "Yahvé habló por medio de sus siervos los profetas, diciendo:",
      "11": "“Por cuanto Manasés, rey de Judá, ha hecho estas abominaciones, y ha hecho maldades mayores que las que hicieron los amorreos que fueron antes de él, y también ha hecho pecar a Judá con sus ídolos;",
      "12": "por tanto, Yahvé, el Dios de Israel, dice: He aquí que yo traigo tal mal sobre Jerusalén y sobre Judá, que al que lo oiga le hormiguearán ambos oídos.",
      "13": "Extenderé sobre Jerusalén la línea de Samaria y la plomada de la casa de Acab; y limpiaré a Jerusalén como se limpia un plato, limpiándolo y poniéndolo boca abajo.",
      "14": "Desecharé el remanente de mi herencia y lo entregaré en manos de sus enemigos. Se convertirán en presa y botín de todos sus enemigos,",
      "15": "porque han hecho lo que es malo ante mis ojos, y me han provocado a la ira desde el día en que sus padres salieron de Egipto, hasta hoy.’” ",
      "16": "Además, Manasés derramó mucha sangre inocente, hasta llenar Jerusalén de un extremo a otro; además de su pecado con el que hizo pecar a Judá, al hacer lo que era malo a los ojos de Yahvé. ",
      "17": "El resto de los hechos de Manasés, y todo lo que hizo, y su pecado que cometió, ¿no están escritos en el libro de las crónicas de los reyes de Judá?",
      "18": "Manasés durmió con sus padres y fue enterrado en el jardín de su casa, en el jardín de Uza; y su hijo Amón reinó en su lugar. ",
      "19": "Amón tenía veintidós años cuando comenzó a reinar, y reinó dos años en Jerusalén. Su madre se llamaba Mesulmet, hija de Haruz de Jotba.",
      "20": "Hizo lo que era malo a los ojos de Yahvé, como lo hizo su padre Manasés.",
      "21": "Anduvo en todos los caminos en que anduvo su padre, y sirvió a los ídolos que su padre servía, y los adoró;",
      "22": "y abandonó a Yavé, el Dios de sus padres, y no anduvo en el camino de Yavé.",
      "23": "Los servidores de Amón conspiraron contra él y mataron al rey en su propia casa.",
      "24": "Pero el pueblo del país mató a todos los que habían conspirado contra el rey Amón, y el pueblo del país hizo rey a su hijo Josías en su lugar.",
      "25": "Los demás hechos de Amón, ¿no están escritos en el libro de las crónicas de los reyes de Judá?",
      "26": "Fue enterrado en su tumba en el jardín de Uza, y su hijo Josías reinó en su lugar."
    },
    "22": {
      "1": "Josías tenía ocho años cuando comenzó a reinar, y reinó treinta y un años en Jerusalén. Su madre se llamaba Yedida, hija de Adaías de Bozcat.",
      "2": "Hizo lo que era justo a los ojos de Yavé, y siguió todo el camino de David, su padre, sin apartarse ni a la derecha ni a la izquierda. ",
      "3": "En el año dieciocho del rey Josías, el rey envió a Safán, hijo de Azalías, hijo de Mesulam, el escriba, a la casa de Yavé, diciendo:",
      "4": "“Sube al sumo sacerdote Hilcías, para que cuente el dinero que se trae a la casa de Yavé, que los guardianes del umbral han reunido del pueblo.",
      "5": "Que lo entreguen en mano de los obreros que tienen la vigilancia de la casa de Yavé; y que lo den a los obreros que están en la casa de Yavé, para reparar los daños de la casa,",
      "6": "a los carpinteros, a los constructores y a los albañiles, y para comprar madera y piedra cortada para reparar la casa.",
      "7": "Sin embargo, no se les pedirá cuenta del dinero entregado en sus manos, porque ellos actúan con fidelidad.” ",
      "8": "El sumo sacerdote Hilcías dijo al escriba Safán: “He encontrado el libro de la ley en la casa de Yahvé”. Hilcías entregó el libro a Safán, y éste lo leyó.",
      "9": "El escriba Safán fue a ver al rey y le trajo de nuevo la noticia, diciendo: “Tus servidores han vaciado el dinero que se encontró en la casa y lo han entregado en manos de los obreros que tienen la supervisión de la casa de Yavé.”",
      "10": "El escriba Safán informó al rey diciendo: “El sacerdote Hilcías me ha entregado un libro”. Entonces Safán lo leyó ante el rey. ",
      "11": "Cuando el rey escuchó las palabras del libro de la ley, se rasgó las vestiduras.",
      "12": "El rey ordenó al sacerdote Hilcías, a Ajicam hijo de Safán, a Acbor hijo de Micaías, al escriba Safán y a Asaías, siervo del rey, diciendo:",
      "13": "“Vayan a consultar a Yavé por mí, por el pueblo y por todo Judá, sobre las palabras de este libro que se ha encontrado pues es grande la ira del Señor que se ha encendido contra nosotros, porque nuestros padres no han escuchado las palabras de este libro, para hacer conforme a todo lo que está escrito acerca de nosotros.” ",
      "14": "Entonces el sacerdote Hilcías, Ajicam, Acbor, Safán y Asaías fueron a ver a la profetisa Hulda, esposa de Salum hijo de Ticva, hijo de Harhas, guardián del armario (que vivía en Jerusalén en el segundo barrio), y hablaron con ella.",
      "15": "Ella les dijo: “Yahvé, el Dios de Israel, dice: ‘Díganle al hombre que los ha enviado a mí:",
      "16": "“Yahvé dice: ‘He aquí que yo traigo el mal sobre este lugar y sobre sus habitantes, incluso todas las palabras del libro que ha leído el rey de Judá.",
      "17": "Porque me han abandonado y han quemado incienso a otros dioses, para provocarme a la ira con toda la obra de sus manos, por eso mi ira se encenderá contra este lugar, y no se apagará.’”",
      "18": "Pero al rey de Judá, que te envió a consultar a Yavé, dile: “Dice Yavé, el Dios de Israel: ‘En cuanto a las palabras que has oído,",
      "19": "porque tu corazón se enterneció y te humillaste ante Yavé cuando oíste lo que hablé contra este lugar y contra sus habitantes, para que se convirtieran en desolación y maldición, y has rasgado tus vestiduras y llorado ante mí, yo también te he oído’, dice Yavé.",
      "20": "‘Por lo tanto, he aquí que te reuniré con tus padres, y serás reunido a tu tumba en paz. Tus ojos no verán todo el mal que traeré a este lugar’”’. Así que llevaron este mensaje al rey."
    },
    "23": {
      "1": "El rey envió, y se reunieron con él todos los ancianos de Judá y de Jerusalén.",
      "2": "El rey subió a la casa de Yavé, y con él todos los hombres de Judá y todos los habitantes de Jerusalén, con los sacerdotes, los profetas y todo el pueblo, tanto el pequeño como el grande; y leyó en su presencia todas las palabras del libro de la alianza que se encontraba en la casa de Yavé.",
      "3": "El rey se puso de pie junto a la columna e hizo un pacto ante Yavé de caminar en pos de Yavé y de guardar sus mandamientos, sus testimonios y sus estatutos con todo su corazón y toda su alma, para confirmar las palabras de este pacto que estaban escritas en este libro; y todo el pueblo estuvo de acuerdo con el pacto. ",
      "4": "El rey ordenó al sumo sacerdote Jilquías, a los sacerdotes del segundo orden y a los guardianes del umbral, que sacaran del templo de Yavé todos los recipientes que habían sido fabricados para Baal, para Asera y para todo el ejército del cielo; y los quemó fuera de Jerusalén, en los campos del Cedrón, y llevó sus cenizas a Betel.",
      "5": "Se deshizo de los sacerdotes idólatras que los reyes de Judá habían ordenado que quemaran incienso en los lugares altos de las ciudades de Judá y en los lugares de los alrededores de Jerusalén; los que también quemaban incienso a Baal, al sol, a la luna, a los planetas y a todo el ejército del cielo.",
      "6": "Sacó la Asera de la casa de Yavé, fuera de Jerusalén, hasta el arroyo Cedrón, y la quemó en el arroyo Cedrón, la redujo a polvo y arrojó su polvo sobre las tumbas de la gente común.",
      "7": "Derribó las casas de las prostitutas masculinas que estaban en la casa de Yavé, donde las mujeres tejían colgaduras para el Ashera.",
      "8": "Sacó a todos los sacerdotes de las ciudades de Judá, y profanó los lugares altos donde los sacerdotes habían quemado incienso, desde Geba hasta Beerseba; y derribó los lugares altos de las puertas que estaban a la entrada de la puerta de Josué, el gobernador de la ciudad, que estaban a la mano izquierda del hombre en la puerta de la ciudad.",
      "9": "Sin embargo, los sacerdotes de los lugares altos no subían al altar de Yavé en Jerusalén, sino que comían panes sin levadura entre sus hermanos.",
      "10": "Profanó a Tofet, que está en el valle de los hijos de Hinom, para que nadie hiciera pasar a su hijo o a su hija por el fuego a Moloc.",
      "11": "Quitó los caballos que los reyes de Judá habían dedicado al sol, a la entrada de la casa de Yavé, junto a la habitación de Natán Melec, el oficial que estaba en el atrio, y quemó con fuego los carros del sol.",
      "12": "El rey derribó los altares que estaban en el techo de la habitación superior de Acaz, que habían hecho los reyes de Judá, y los altares que había hecho Manasés en los dos atrios de la Casa de Yavé, y los derribó de allí, y arrojó su polvo al arroyo Cedrón.",
      "13": "El rey profanó los lugares altos que estaban delante de Jerusalén, a la derecha del monte de la corrupción, que Salomón, rey de Israel, había edificado para Astoret, abominación de los sidonios, para Quemos, abominación de Moab, y para Milcom, abominación de los hijos de Amón.",
      "14": "Rompió las columnas, cortó los postes de Asera y llenó sus lugares con huesos de hombres. ",
      "15": "Además, el altar que estaba en Betel y el lugar alto que había hecho Jeroboam hijo de Nabat, el que hizo pecar a Israel, ese altar y el lugar alto los derribó; y quemó el lugar alto y lo redujo a polvo, y quemó la Asera.",
      "16": "Al volverse Josías, divisó los sepulcros que estaban allí en el monte; y mandó sacar los huesos de los sepulcros, y los quemó sobre el altar, y lo profanó, conforme a la palabra de Yahvé que proclamaba el hombre de Dios que anunciaba estas cosas.",
      "17": "Entonces dijo: “¿Qué monumento es el que veo?” Los hombres de la ciudad le dijeron: “Es la tumba del hombre de Dios que vino de Judá y proclamó estas cosas que has hecho contra el altar de Betel”. ",
      "18": "Dijo: “¡Dejadle! Que nadie mueva sus huesos”. Así que dejaron en paz sus huesos, con los del profeta que salió de Samaria.",
      "19": "También tomó Josías todas las casas de los lugares altos que había en las ciudades de Samaria, que los reyes de Israel habían hecho para provocar la ira de Yavé, e hizo con ellas lo mismo que había hecho en Betel.",
      "20": "Mató a todos los sacerdotes de los lugares altos que estaban allí, sobre los altares, y quemó huesos de hombres sobre ellos; y volvió a Jerusalén. ",
      "21": "El rey ordenó a todo el pueblo diciendo: “Celebrad la Pascua a Yahvé, vuestro Dios, como está escrito en este libro de la Alianza.”",
      "22": "Ciertamente no se celebró una Pascua así desde los días de los jueces que juzgaban a Israel, ni en todos los días de los reyes de Israel, ni de los reyes de Judá;",
      "23": "pero en el año dieciocho del rey Josías, se celebró esta Pascua a Yavé en Jerusalén. ",
      "24": "Además, Josías eliminó a los que tenían espíritus familiares, a los magos y a los terafines,  y a los ídolos, y todas las abominaciones que se veían en la tierra de Judá y en Jerusalén, para confirmar las palabras de la ley que estaban escritas en el libro que el sacerdote Hilcías encontró en la casa de Yavé.",
      "25": "No hubo antes de él ningún rey que se convirtiera a Yavé con todo su corazón, con toda su alma y con todas sus fuerzas, según toda la ley de Moisés; y no hubo ninguno como él que se levantara después de él.",
      "26": "Sin embargo, Yahvé no se apartó del ardor de su gran ira, con la que ardía su enojo contra Judá, a causa de toda la provocación con que Manasés lo había provocado.",
      "27": "Yahvé dijo: “También quitaré a Judá de mi vista, como he quitado a Israel; y desecharé esta ciudad que he elegido, Jerusalén, y la casa de la que dije: ‘Mi nombre estará allí’.” ",
      "28": "Los demás hechos de Josías, y todo lo que hizo, ¿no están escritos en el libro de las crónicas de los reyes de Judá?",
      "29": "En sus días el faraón Necoh, rey de Egipto, subió contra el rey de Asiria hasta el río Éufrates; y el rey Josías fue contra él, pero el faraón Necoh lo mató en Meguido cuando lo vio.",
      "30": "Sus servidores lo llevaron muerto en un carro desde Meguido, lo trajeron a Jerusalén y lo enterraron en su propia tumba. El pueblo del país tomó a Joacaz, hijo de Josías, lo ungió y lo hizo rey en lugar de su padre. ",
      "31": "Joacaz tenía veintitrés años cuando comenzó a reinar, y reinó tres meses en Jerusalén. Su madre se llamaba Hamutal, hija de Jeremías de Libna.",
      "32": "Hizo lo que era malo a los ojos de Yavé, según todo lo que habían hecho sus padres.",
      "33": "El faraón Necoh lo puso en prisión en Ribla, en la tierra de Hamat, para que no reinara en Jerusalén, y le impuso un tributo de cien talentos de plata y un talento  de oro.",
      "34": "El faraón Necoh hizo rey a Eliaquim, hijo de Josías, en lugar de Josías, su padre, y le cambió el nombre por el de Joacim; pero se llevó a Joacaz, que vino a Egipto y murió allí.",
      "35": "Joacim entregó la plata y el oro al faraón, pero gravó la tierra para dar el dinero según el mandato del faraón. Exigió la plata y el oro del pueblo de la tierra, a cada uno según su valoración, para dárselo al faraón Necó.",
      "36": "Joacim tenía veinticinco años cuando comenzó a reinar, y reinó once años en Jerusalén. Su madre se llamaba Zebida, hija de Pedaías de Rumah.",
      "37": "Hizo lo que era malo a los ojos de Yahvé, según todo lo que habían hecho sus padres."
    },
    "24": {
      "1": "En sus días subió Nabucodonosor, rey de Babilonia, y Joacim fue su siervo durante tres años. Luego se volvió y se rebeló contra él.",
      "2": "Yahvé envió contra él grupos de caldeos, grupos de sirios, grupos de moabitas y grupos de hijos de Amón, y los envió contra Judá para destruirla, según la palabra de Yahvé que habló por medio de sus siervos los profetas.",
      "3": "Ciertamente por mandato de Yahvé esto vino sobre Judá, para quitarlos de su vista por los pecados de Manasés, según todo lo que hizo,",
      "4": "y también por la sangre inocente que derramó; porque llenó a Jerusalén de sangre inocente, y Yahvé no quiso perdonar.",
      "5": "Los demás hechos de Joacim y todo lo que hizo, ¿no están escritos en el libro de las crónicas de los reyes de Judá?",
      "6": "Y Joacim durmió con sus padres, y su hijo Joaquín reinó en su lugar. ",
      "7": "El rey de Egipto no salió más de su tierra, porque el rey de Babilonia había tomado, desde el arroyo de Egipto hasta el río Éufrates, todo lo que pertenecía al rey de Egipto. ",
      "8": "Joaquín tenía dieciocho años cuando comenzó a reinar, y reinó en Jerusalén tres meses. Su madre se llamaba Nehushta, hija de Elnatán de Jerusalén.",
      "9": "Hizo lo que era malo a los ojos de Yavé, según todo lo que había hecho su padre.",
      "10": "En aquel tiempo los servidores de Nabucodonosor, rey de Babilonia, subieron a Jerusalén, y la ciudad fue sitiada.",
      "11": "Nabucodonosor, rey de Babilonia, llegó a la ciudad mientras sus siervos la sitiaban,",
      "12": "y Joaquín, rey de Judá, salió hacia el rey de Babilonia: él, su madre, sus siervos, sus príncipes y sus oficiales; y el rey de Babilonia lo capturó en el octavo año de su reinado.",
      "13": "Sacó de allí todos los tesoros de la casa de Yavé y los tesoros de la casa real, y cortó en pedazos todos los objetos de oro que Salomón, rey de Israel, había hecho en el templo de Yavé, como había dicho Yavé.",
      "14": "Se llevó a toda Jerusalén, a todos los príncipes y a todos los hombres valientes, hasta diez mil cautivos, y a todos los artesanos y herreros. No quedó nadie más que los más pobres del país.",
      "15": "Llevó a Joaquín a Babilonia, con la madre del rey, las mujeres del rey, sus oficiales y los principales hombres del país. Los llevó en cautiverio desde Jerusalén hasta Babilonia.",
      "16": "El rey de Babilonia llevó cautivos a Babilonia a todos los hombres poderosos, siete mil, y a los artesanos y herreros, mil, todos ellos fuertes y aptos para la guerra.",
      "17": "El rey de Babilonia hizo rey en su lugar a Matanías, hermano del padre de Joaquín, y le cambió el nombre por el de Sedequías. ",
      "18": "Sedequías tenía veintiún años cuando comenzó a reinar, y reinó once años en Jerusalén. Su madre se llamaba Hamutal, hija de Jeremías de Libna.",
      "19": "Hizo lo que era malo a los ojos de Yavé, según todo lo que había hecho Joacim.",
      "20": "Porque por la ira de Yavé, esto sucedió en Jerusalén y en Judá, hasta que los expulsó de su presencia. Entonces Sedequías se rebeló contra el rey de Babilonia."
    },
    "25": {
      "1": "En el noveno año de su reinado, en el décimo mes, a los diez días del mes, vino Nabucodonosor, rey de Babilonia, él y todo su ejército, contra Jerusalén, y acampó contra ella; y construyeron contra ella fortalezas alrededor.",
      "2": "Así estuvo sitiada la ciudad hasta el undécimo año del rey Sedequías.",
      "3": "En el noveno día del cuarto mes, la hambruna fue severa en la ciudad, de modo que no hubo pan para el pueblo de la tierra.",
      "4": "Entonces se abrió una brecha en la ciudad, y todos los hombres de guerra huyeron de noche por el camino de la puerta entre las dos murallas, que estaba junto al jardín del rey (ahora los caldeos estaban contra la ciudad alrededor); y el rey se fue por el camino del Arabá.",
      "5": "Pero el ejército caldeo persiguió al rey y lo alcanzó en las llanuras de Jericó, y todo su ejército se dispersó de él.",
      "6": "Entonces capturaron al rey y lo llevaron al rey de Babilonia, a Ribla, y lo juzgaron.",
      "7": "Mataron a los hijos de Sedequías ante sus ojos, luego le sacaron los ojos, lo ataron con grilletes y lo llevaron a Babilonia. ",
      "8": "En el mes quinto, a los siete días del mes, que era el año decimonoveno del rey Nabucodonosor, rey de Babilonia, llegó a Jerusalén Nabuzaradán, capitán de la guardia, siervo del rey de Babilonia.",
      "9": "Quemó la casa de Yahvé, la casa del rey y todas las casas de Jerusalén. Quemó con fuego todas las casas grandes.",
      "10": "Todo el ejército de los caldeos, que estaba con el capitán de la guardia, derribó los muros alrededor de Jerusalén.",
      "11": "Nabuzaradán, el capitán de la guardia, se llevó cautivo al resto del pueblo que había quedado en la ciudad y a los que habían desertado al rey de Babilonia; todo el resto de la multitud.",
      "12": "Pero el capitán de la guardia dejó a algunos de los más pobres de la tierra para que trabajaran las viñas y los campos. ",
      "13": "Los caldeos rompieron las columnas de bronce que había en la casa de Yavé, así como las bases y el mar de bronce que había en la casa de Yavé, y llevaron los pedazos de bronce a Babilonia.",
      "14": "Se llevaron las ollas, las palas, los apagadores, las cucharas y todos los recipientes de bronce con los que servían.",
      "15": "El capitán de la guardia se llevó las sartenes para el fuego, las palanganas, lo que era de oro, por oro, y lo que era de plata, por plata.",
      "16": "Los dos pilares, el único mar y las bases, que Salomón había hecho para la casa de Yavé, el bronce de todos estos recipientes no se pesaba.",
      "17": "La altura de la única columna era de dieciocho codos,  y sobre ella había un capitel de bronce. La altura del capitel era de tres codos, con red y granadas en el capitel alrededor, todo de bronce; y la segunda columna con su red era como éstas. ",
      "18": "El capitán de la guardia tomó a Seraías, el sumo sacerdote, a Sofonías, el segundo sacerdote, y a los tres guardianes del umbral;",
      "19": "y de la ciudad tomó a un oficial que estaba al frente de los hombres de guerra, y a cinco hombres de los que habían visto la cara del rey, que se encontraban en la ciudad, y al escriba, al capitán del ejército que reunía al pueblo del país, y a sesenta hombres del pueblo del país que se encontraban en la ciudad.",
      "20": "Nabuzaradán, capitán de la guardia, los tomó y los llevó al rey de Babilonia, a Ribla.",
      "21": "El rey de Babilonia los atacó y los mató en Ribla, en la tierra de Hamat. Y Judá fue llevado cautivo fuera de su tierra. ",
      "22": "En cuanto al pueblo que había quedado en la tierra de Judá y que Nabucodonosor, rey de Babilonia, había dejado como gobernador a Gedalías, hijo de Ajicam, hijo de Safán.",
      "23": "Cuando todos los capitanes de las fuerzas, ellos y sus hombres, oyeron que el rey de Babilonia había nombrado gobernador a Gedalías, vinieron a Gedalías a Mizpa, Ismael hijo de Netanías, Johanán hijo de Carea, Seraías hijo de Tanhumet el netofita, y Jaazanías hijo del maacateo, ellos y sus hombres.",
      "24": "Gedalías les juró a ellos y a sus hombres, y les dijo: “No teman por los siervos de los caldeos. Moren en la tierra y sirvan al rey de Babilonia, y les irá bien”. ",
      "25": "Pero en el séptimo mes vino Ismael, hijo de Netanías, hijo de Elisama, de la estirpe real, y diez hombres con él, e hirieron a Gedalías de tal manera que murió, con los judíos y los caldeos que estaban con él en Mizpa.",
      "26": "Todo el pueblo, tanto el pequeño como el grande, y los capitanes de las fuerzas se levantaron y fueron a Egipto, porque tenían miedo de los caldeos.",
      "27": "En el año treinta y siete del cautiverio de Joaquín, rey de Judá, en el mes duodécimo, a los veintisiete días del mes, Evilmerodac, rey de Babilonia, en el año en que comenzó a reinar, liberó a Joaquín, rey de Judá, de la prisión,",
      "28": "y le habló amablemente y puso su trono por encima del trono de los reyes que estaban con él en Babilonia,",
      "29": "y le cambió sus ropas de prisión. Joaquín comió pan delante de él continuamente todos los días de su vida;",
      "30": "y para su manutención, se le dio continuamente una ración de parte del rey, cada día una porción, todos los días de su vida.  "
    }
  },
  "1_chronicles": {
    "1": {
      "1": "Adán, Seth, Enosh,",
      "2": "Kenan, Mahalalel, Jared,",
      "3": "Enoc, Matusalén, Lamec,",
      "4": "Noé, Sem, Cam y Jafet. ",
      "5": "Los hijos de Jafet: Gomer, Magog, Madai, Javan, Tubal, Meshech y Tiras.",
      "6": "Los hijos de Gomer: Ashkenaz, Diphath y Togarmah.",
      "7": "Los hijos de Javán: Elishah, Tarsis, Kittim y Rodanim. ",
      "8": "Los hijos de Cam: Cus, Mizraim, Put y Canaán.",
      "9": "Los hijos de Cus: Seba, Havilah, Sabta, Raama y Sabteca. Los hijos de Raamah: Sabá y Dedán.",
      "10": "Cus se convirtió en el padre de Nimrod. Él comenzó a ser un poderoso en la tierra.",
      "11": "Mizraim se convirtió en el padre de Ludim, Anamim, Lehabim, Naphtuhim,",
      "12": "Pathrusim, Casluhim (de donde vinieron los filisteos) y Caphtorim.",
      "13": "Canaán se convirtió en el padre de Sidón, su primogénito, Het,",
      "14": "el jebuseo, el amorreo, el gergeseo,",
      "15": "el heveo, el arquita, el sinita,",
      "16": "el arvadita, el zemarita y el hamateo. ",
      "17": "Los hijos de Sem: Elam, Asur, Arpachshad, Lud, Aram, Uz, Hul, Gether y Meshech.",
      "18": "Arpachshad fue padre de Shelah, y Shelah fue padre de Eber.",
      "19": "A Eber le nacieron dos hijos: el nombre del uno fue Peleg, porque en sus días la tierra fue dividida; y el nombre de su hermano fue Joktán.",
      "20": "Joktán fue padre de Almodad, Shelef, Hazarmaveth, Jerah,",
      "21": "Hadoram, Uzal, Diklah,",
      "22": "Ebal, Abimael, Sheba,",
      "23": "Ophir, Havilah y Jobab. Todos estos fueron hijos de Joktán.",
      "24": "Sem, Arpachshad, Shelah,",
      "25": "Eber, Peleg, Reu,",
      "26": "Serug, Nahor, Terah,",
      "27": "Abram (también llamado Abraham). ",
      "28": "Los hijos de Abraham: Isaac e Ismael.",
      "29": "Estas son sus generaciones: el primogénito de Ismael, Nebaiot; luego Cedar, Adbeel, Mibsam,",
      "30": "Mishma, Dumah, Massa, Hadad, Tema,",
      "31": "Jetur, Nafis y Cedemah. Estos son los hijos de Ismael. ",
      "32": "Los hijos de Cetura, concubina de Abraham: dio a luz a Zimran, Jokshan, Medan, Midian, Ishbak y Shuah. Los hijos de Joksán: Seba y Dedán.",
      "33": "Los hijos de Madián: Efá, Efer, Hanoc, Abida y Eldaá. Todos estos fueron hijos de Cetura. ",
      "34": "Abraham se convirtió en el padre de Isaac. Los hijos de Isaac: Esaú e Israel.",
      "35": "Los hijos de Esaú: Elifaz, Reuel, Jeús, Jalam y Coré.",
      "36": "Los hijos de Elifaz: Temán, Omar, Zefi, Gatam, Kenaz, Timna y Amalec.",
      "37": "Los hijos de Reuel: Nahat, Zerah, Shammah y Mizzah. ",
      "38": "Los hijos de Seir: Lotán, Sobal, Zibeón, Aná, Disón, Ezer y Disán.",
      "39": "Los hijos de Lotán: Hori y Homam; y Timna era hermana de Lotán.",
      "40": "Los hijos de Sobal: Alian, Manahath, Ebal, Shephi y Onam. Los hijos de Zibeón: Aiah y Anah.",
      "41": "El hijo de Aná: Disón. Los hijos de Disón: Hamrán, Eshbán, Itrán y Querán.",
      "42": "Los hijos de Ezer: Bilhan, Zaavan y Jaakan. Los hijos de Disán: Uz y Arán. ",
      "43": "Estos son los reyes que reinaron en la tierra de Edom, antes de que ningún rey reinara sobre los hijos de Israel Bela hijo de Beor, y el nombre de su ciudad fue Dinhabah.",
      "44": "Murió Bela, y en su lugar reinó Jobab, hijo de Zera, de Bosra.",
      "45": "Murió Jobab, y reinó en su lugar Husam, de la tierra de los temanitas.",
      "46": "Murió Husam, y reinó en su lugar Hadad, hijo de Bedad, que hirió a Madián en el campo de Moab, y el nombre de su ciudad fue Avit.",
      "47": "Murió Hadad, y en su lugar reinó Samá de Masreca.",
      "48": "Murió Samá, y reinó en su lugar Saúl, de Rehobot, junto al río.",
      "49": "Murió Saúl, y en su lugar reinó Baal Hanán, hijo de Acbor.",
      "50": "Murió Baal Hanán, y en su lugar reinó Hadad; el nombre de su ciudad fue Pai. Su esposa se llamaba Mehetabel, hija de Matred, hija de Mezahab.",
      "51": "Luego murió Hadad. Los jefes de Edom fueron: el jefe Timna, el jefe Aliah, el jefe Jetheth,",
      "52": "el jefe Oholibamah, el jefe Elah, el jefe Pinon,",
      "53": "el jefe Kenaz, el jefe Teman, el jefe Mibzar,",
      "54": "el jefe Magdiel y el jefe Iram. Estos son los jefes de Edom."
    },
    "2": {
      "1": "Estos son los hijos de Israel: Rubén, Simeón, Leví, Judá, Isacar, Zabulón,",
      "2": "Dan, José, Benjamín, Neftalí, Gad y Aser. ",
      "3": "Los hijos de Judá: Er, Onán y Sela, los tres que le nacieron de la hija de Súa, la cananea. Er, el primogénito de Judá, fue malvado a los ojos de Yahvé ; y lo mató.",
      "4": "Tamar, su nuera, le dio a luz a Pérez y a Zéraj. Todos los hijos de Judá fueron cinco. ",
      "5": "Los hijos de Pérez: Hezrón y Hamul.",
      "6": "Los hijos de Zera: Zimri, Etán, Hemán, Calcol y Dara: cinco en total.",
      "7": "Los hijos de Carmi: Acar, el perturbador de Israel, que cometió una infracción en la cosa consagrada.",
      "8": "El hijo de Etán: Azarías. ",
      "9": "También los hijos de Hezrón, que le nacieron: Jerajmeel, Ram y Quelubai.",
      "10": "Ram fue padre de Aminadab, y Aminadab fue padre de Nahsón, príncipe de los hijos de Judá;",
      "11": "y Nahsón fue padre de Salma, y Salma fue padre de Booz,",
      "12": "y Booz fue padre de Obed, y Obed fue padre de Isaí",
      "13": "e Isaí fue padre de su primogénito Eliab, Abinadab el segundo, Simea el tercero,",
      "14": "Netanel el cuarto, Raddai el quinto,",
      "15": "Ozem el sexto y David el séptimo;",
      "16": "y sus hermanas fueron Zeruiah y Abigail. Los hijos de Sarvia: Abisai, Joab y Asael, tres.",
      "17": "Abigail dio a luz a Amasa, y el padre de Amasa fue Jeter, el ismaelita. ",
      "18": "Caleb, hijo de Hezrón, fue padre de hijos de Azubá, su mujer, y de Jeriot; y estos fueron sus hijos Jesher, Shobab y Ardón.",
      "19": "Murió Azubá, y Caleb se casó con Efrat, que le dio a luz a Hur.",
      "20": "Hur fue el padre de Uri, y Uri fue el padre de Bezalel. ",
      "21": "Después, Hezrón se acercó a la hija de Maquir, padre de Galaad, a la que tomó como esposa cuando tenía sesenta años, y ella le dio a luz a Segub.",
      "22": "Segub fue el padre de Jair, quien tuvo veintitrés ciudades en la tierra de Galaad.",
      "23": "Gesur y Aram les arrebataron las ciudades de Jair, con Kenat y sus aldeas, hasta sesenta ciudades. Todos estos fueron los hijos de Maquir, padre de Galaad.",
      "24": "Después de la muerte de Hezrón en Caleb Efrata, Abías, mujer de Hezrón, le dio a luz a Ashur, padre de Tecoa. ",
      "25": "Los hijos de Jerajmeel, primogénito de Hezrón, fueron Rama el primogénito, Buna, Orén, Ozem y Ahías.",
      "26": "Jerajmeel tuvo otra esposa que se llamaba Atará. Ella fue la madre de Onam.",
      "27": "Los hijos de Ram, primogénito de Jerajmeel, fueron Maaz, Jamín y Eker.",
      "28": "Los hijos de Onam fueron Shammai y Jada. Los hijos de Shammai: Nadab y Abisur.",
      "29": "La mujer de Abisur se llamaba Abihail, y dio a luz a Ahban y a Molid.",
      "30": "Los hijos de Nadab: Seled y Appaim; pero Seled murió sin hijos.",
      "31": "El hijo de Appaim: Ishi. El hijo de Ishi: Sesán. El hijo de Sesán: Ahlai.",
      "32": "Los hijos de Jada, hermano de Shammai: Jeter y Jonatán; pero Jeter murió sin hijos.",
      "33": "Los hijos de Jonatán: Pelet y Zaza. Estos fueron los hijos de Jerajmeel.",
      "34": "Sesán no tuvo hijos, sino sólo hijas. Sesán tenía un sirviente, un egipcio, que se llamaba Jarha.",
      "35": "Sesán dio su hija a Jarha, su siervo, como esposa, y ella le dio a luz a Atai.",
      "36": "Atai fue padre de Natán, y Natán fue padre de Zabad,",
      "37": "y Zabad fue padre de Eflal, y Eflal fue padre de Obed,",
      "38": "y Obed fue padre de Jehú, y Jehú fue padre de Azarías",
      "39": "y Azarías fue padre de Helez, y Helez fue padre de Eleasah,",
      "40": "y Eleasah fue padre de Sismai, y Sismai fue padre de Sallum,",
      "41": "y Sallum fue padre de Jekamiah, y Jekamiah fue padre de Elishama. ",
      "42": "Los hijos de Caleb, hermano de Jerajmeel, fueron Mesá, su primogénito, que fue padre de Zif, y los hijos de Maresá, padre de Hebrón.",
      "43": "Los hijos de Hebrón: Coré, Tapú, Recem y Sema.",
      "44": "Sema fue el padre de Raham, el padre de Jorkeam; y Rekem fue el padre de Shammai.",
      "45": "El hijo de Samai fue Maón; y Maón fue el padre de Bet Zur.",
      "46": "Efá, concubina de Caleb, dio a luz a Harán, Moza y Gazez; y Harán fue padre de Gazez.",
      "47": "Los hijos de Jahdai: Regem, Jotán, Gesán, Pelet, Efá y Shaaf.",
      "48": "Maaca, concubina de Caleb, dio a luz a Seber y a Tirana.",
      "49": "También dio a luz a Shaaf, padre de Madmaná, a Sheva, padre de Macbena, y al padre de Gbea; y la hija de Caleb fue Acsa. ",
      "50": "Estos fueron los hijos de Caleb, hijo de Hur, primogénito de Efrata: Sobal, padre de Quiriat Jearim,",
      "51": "Salma, padre de Belén, y Haref, padre de Bet Gader.",
      "52": "Sobal, padre de Quiriat Jearim, tuvo hijos: Haroeh, la mitad de los Menuhoth.",
      "53": "Las familias de Quiriat Jearim: los itritas, los putitas, los shumatitas y los misraítas; de ellos salieron los zoratitas y los eshtaolitas.",
      "54": "Los hijos de Salma: Belén, los netofatitas, Atrot Bet Joab, y la mitad de los manaítas, los zoritas.",
      "55": "Las familias de escribas que vivían en Jabes: los tiratitas, los simeatitas y los sucatitas. Estos son los ceneos que vinieron de Hamat, el padre de la casa de Recab."
    },
    "3": {
      "1": "Estos fueron los hijos de David que le nacieron en Hebrón: el primogénito, Amnón, de Ahinoam jezreelita; el segundo, Daniel, de Abigail carmelita;",
      "2": "el tercero, Absalón, hijo de Maaca, hija de Talmai, rey de Gesur; el cuarto, Adonías, hijo de Haggit;",
      "3": "el quinto, Sefatías, de Abital; el sexto, Itream, de Egla, su mujer:",
      "4": "seis le nacieron en Hebrón; y reinó allí siete años y seis meses. Reinó treinta y tres años en Jerusalén;",
      "5": "y estos le nacieron en Jerusalén: Simea, Sobab, Natán y Salomón, cuatro, de Betsúa, hija de Amiel;",
      "6": "e Ibhar, Elisama, Elifelet,",
      "7": "Nogah, Nefeg, Jafía,",
      "8": "Elisama, Eliada y Elifelet, nueve.",
      "9": "Todos estos eran hijos de David, además de los hijos de las concubinas; y Tamar era su hermana. ",
      "10": "El hijo de Salomón fue Roboam, su hijo Abías, su hijo Asa, su hijo Josafat,",
      "11": "Su hijo Joram, su hijo Ocozías, su hijo Joás,",
      "12": "Su hijo Amasías, su hijo Azarías, su hijo Jotam,",
      "13": "Su hijo Acaz, su hijo Ezequías, su hijo Manasés,",
      "14": "Su hijo Amón, su hijo Josías.",
      "15": "Los hijos de Josías: el primogénito Johanán, el segundo Joaquím, el tercero Sedequías y el cuarto Salum.",
      "16": "Los hijos de Joacim Jeconías, su hijo, y Sedequías, su hijo.",
      "17": "Los hijos de Jeconías, el cautivo: Saltiel su hijo,",
      "18": "Malquiram, Pedaías, Senazar, Jecamías, Hosama y Nedabías.",
      "19": "Los hijos de Pedaías: Zorobabel y Simei. Los hijos de Zorobabel: Mesulam y Hananías; y Selomit fue su hermana;",
      "20": "y Hasubá, Ohel, Berequías, Hasadías y Jushab Hesed, cinco.",
      "21": "Los hijos de Ananías: Pelatías y Jesaías; los hijos de Refaías, los hijos de Arnán, los hijos de Abdías, los hijos de Secanías.",
      "22": "El hijo de Secanías: Semaías. Los hijos de Semaías: Hatús, Igal, Barías, Nearías y Safat, seis.",
      "23": "Los hijos de Nearías: Elioenai, Hizkiah y Azrikam, tres.",
      "24": "Los hijos de Elioenai: Hodaviah, Eliashib, Pelaiah, Akkub, Johanan, Delaiah, y Anani, siete."
    },
    "4": {
      "1": "Los hijos de Judá: Pérez, Hezrón, Carmi, Hur y Sobal.",
      "2": "Reaías, hijo de Sobal, fue padre de Jahat, y Jahat fue padre de Ahumai y Lahad. Estas son las familias de los zoratíes.",
      "3": "Estos fueron los hijos del padre de Etam Jezreel, Isma e Idbash. El nombre de su hermana era Hazzelelponi.",
      "4": "Penuel fue el padre de Gedor y Ezer el padre de Hushah. Estos son los hijos de Hur, primogénito de Efrata, padre de Belén.",
      "5": "Ashur, padre de Tecoa, tuvo dos esposas, Helá y Naara.",
      "6": "Naara le dio a luz a Ahuzzam, Hefer, Temeni y Haahashtari. Estos fueron los hijos de Naara.",
      "7": "Los hijos de Hela fueron Zeret, Izhar y Etnán.",
      "8": "Hakkoz fue el padre de Anub, Zobebah y las familias de Aharhel, hijo de Harum. ",
      "9": "Jabes era más honorable que sus hermanos. Su madre le puso el nombre de Jabes,  diciendo: “Porque lo parí con dolor”. ",
      "10": "Jabes invocó al Dios  de Israel, diciendo: “¡Oh, que me bendigas de verdad y amplíes mi frontera! Que tu mano esté conmigo, y que me guardes del mal, para que no cause dolor”. Dios le concedió lo que pidió. ",
      "11": "Quelub, hermano de Shuhah, se convirtió en el padre de Mehir, quien fue el padre de Eshton.",
      "12": "Eshton llegó a ser el padre de Beth Rapha, Paseah, y Tehinnah el padre de Ir Nahash. Estos son los hombres de Recah.",
      "13": "Los hijos de Kenaz: Othniel y Seraiah. Los hijos de Othniel: Hathath.  ",
      "14": "Meonothai fue el padre de Ofra; y Seraiah fue el padre de Joab, el padre de Ge Harashim, porque eran artesanos.",
      "15": "Los hijos de Caleb, hijo de Jefone: Iru, Ela y Naam. El hijo de Ela: Kenaz.",
      "16": "Los hijos de Jehallelel: Zif, Zifa, Tiria y Asarel.",
      "17": "Los hijos de Esdras: Jeter, Mered, Efer y Jalón; y la mujer de Mered dio a luz a Miriam, a Shammai y a Ishbah, padre de Eshtemoa.",
      "18": "Su mujer, la judía, dio a luz a Jered, padre de Gedor, a Heber, padre de Soco, y a Jekutiel, padre de Zanoa. Estos son los hijos de Bitías, hija del faraón, que tomó Mered.",
      "19": "Los hijos de la mujer de Hodías, hermana de Naham, fueron los padres de Keilá el garmita y de Estemoa el maacateo.",
      "20": "Los hijos de Simón: Amnón, Rinna, Ben Hanán y Tilón. Los hijos de Ishi: Zohet y Ben Zohet.",
      "21": "Los hijos de Sela, hijo de Judá: Er padre de Leca, Laada padre de Maresa, y las familias de la casa de los que trabajaban el lino fino, de la casa de Asbea;",
      "22": "y Jokim, y los hombres de Cozeba, y Joás, y Saraf, que tenían dominio en Moab, y Jasubilehem. Estos registros son antiguos.",
      "23": "Estos eran los alfareros y los habitantes de Netaim y Gedera; vivían allí con el rey para su trabajo. ",
      "24": "Los hijos de Simeón: Nemuel, Jamín, Jarib, Zera, Shaúl;",
      "25": "Su hijo Salum, su hijo Mibsam y su hijo Misma.",
      "26": "Los hijos de Misma: Hamuel su hijo, Zaccur su hijo, Simei su hijo.",
      "27": "Simei tuvo dieciséis hijos y seis hijas; pero sus hermanos no tuvieron muchos hijos, y toda su familia no se multiplicó como los hijos de Judá.",
      "28": "Vivían en Beerseba, Molada, Hazarshual,",
      "29": "en Bilhá, en Ezem, en Tolad,",
      "30": "en Betuel, en Horma, en Siclag,",
      "31": "en Bet Marcabot, Hazar Susim, en Bet Biri y en Shaaraim. Estas fueron sus ciudades hasta el reinado de David.",
      "32": "Sus aldeas eran Etam, Ain, Rimmon, Tochen y Ashan, cinco ciudades;",
      "33": "y todas sus aldeas que estaban alrededor de las mismas ciudades, hasta Baal. Estos fueron sus asentamientos, y conservaron su genealogía.",
      "34": "Meshobab, Jamlec, Josá hijo de Amasías,",
      "35": "Joel, Jehú hijo de Joshibías, hijo de Seraías, hijo de Asiel,",
      "36": "Elioenai, Jaakobah, Jeshohaiah, Asaiah, Adiel, Jesimiel, Benaía,",
      "37": "y Ziza hijo de Sifí, hijo de Allón, hijo de Jedaías, hijo de Simri, hijo de Semaías —",
      "38": "estos mencionados por su nombre eran príncipes en sus familias. Las casas de sus padres aumentaron mucho. ",
      "39": "Fueron a la entrada de Gedor, al lado oriental del valle, para buscar pastos para sus rebaños.",
      "40": "Encontraron ricos y buenos pastos, y la tierra era amplia, tranquila y apacible, porque los que vivían allí antes eran descendientes de Cam.",
      "41": "Estos escritos por su nombre vinieron en los días de Ezequías, rey de Judá, y atacaron sus tiendas y a los meuníes que allí se encontraban, y los destruyeron por completo hasta el día de hoy, y vivieron en su lugar, porque allí había pastos para sus rebaños.",
      "42": "Algunos de ellos, de los hijos de Simeón, quinientos hombres, fueron al monte de Seir, teniendo por capitanes a Pelatías, Nearías, Refaías y Uziel, hijos de Ishi.",
      "43": "Hirieron al resto de los amalecitas que escaparon, y han vivido allí hasta el día de hoy."
    },
    "5": {
      "1": "Los hijos de Rubén, primogénito de Israel (pues él era el primogénito, pero por haber profanado el lecho de su padre, su primogenitura fue entregada a los hijos de José, hijo de Israel; y la genealogía no debe enumerarse según la primogenitura.",
      "2": "Porque Judá prevaleció sobre sus hermanos, y de él salió el príncipe; pero la primogenitura fue de José) —",
      "3": "los hijos de Rubén, primogénito de Israel: Hanoch, Pallu, Hezron y Carmi.",
      "4": "Los hijos de Joel: Semaías su hijo, Gog su hijo, Simei su hijo,",
      "5": "Miqueas su hijo, Reaías su hijo, Baal su hijo,",
      "6": "y Beera su hijo, a quien Tilgath Pilneser, rey de Asiria, llevó cautivo. Era príncipe de los rubenitas.",
      "7": "Sus hermanos por sus familias, cuando se enumeró la genealogía de sus generaciones: el jefe, Jeiel, y Zacarías,",
      "8": "y Bela hijo de Azaz, hijo de Sema, hijo de Joel, que vivía en Aroer, hasta Nebo y Baal Meón;",
      "9": "y vivía hacia el este hasta la entrada del desierto desde el río Éufrates, porque sus ganados se multiplicaban en la tierra de Galaad. ",
      "10": "En los días de Saúl, hicieron la guerra a los hagritas, que cayeron por su mano, y vivieron en sus tiendas por toda la tierra al este de Galaad. ",
      "11": "Los hijos de Gad vivieron junto a ellos en la tierra de Basán hasta Salecá:",
      "12": "Joel el principal, Safam el segundo, Janai y Safat en Basán.",
      "13": "Sus hermanos de las casas paternas: Miguel, Mesulam, Seba, Jorai, Jacan, Zia y Eber, siete.",
      "14": "Estos fueron los hijos de Abihail, hijo de Huri, hijo de Jaroa, hijo de Galaad, hijo de Micael, hijo de Jeshishai, hijo de Jahdo, hijo de Buz;",
      "15": "Ahi hijo de Abdiel, hijo de Guni, jefe de las casas de sus padres.",
      "16": "Vivían en Galaad, en Basán, y en sus ciudades, y en todas las tierras de pastoreo de Sarón hasta sus fronteras.",
      "17": "Todos estos fueron enumerados por genealogías en los días de Jotam, rey de Judá, y en los días de Jeroboam, rey de Israel. ",
      "18": "Los hijos de Rubén, los gaditas y la media tribu de Manasés, de hombres valientes, capaces de llevar broquel y espada, de disparar con arco y hábiles en la guerra, eran cuarenta y cuatro mil setecientos sesenta que podían salir a la guerra.",
      "19": "Hicieron la guerra a los hagritas, a Jetur, a Nafis y a Nodab.",
      "20": "Fueron ayudados contra ellos, y los hagritas fueron entregados en su mano, y todos los que estaban con ellos; porque clamaron a Dios en la batalla, y él les respondió porque pusieron su confianza en él.",
      "21": "Les quitaron el ganado: de sus camellos cincuenta mil, de las ovejas doscientas cincuenta mil, de los asnos dos mil y de los hombres cien mil.",
      "22": "Porque muchos cayeron muertos, porque la guerra era de Dios. Vivieron en su lugar hasta el cautiverio. ",
      "23": "Los hijos de la media tribu de Manasés vivían en la tierra. Se multiplicaron desde Basán hasta Baal Hermón, Senir y el monte Hermón.",
      "24": "Estos eran los jefes de las casas de sus padres: Efer, Ishi, Eliel, Azriel, Jeremías, Hodavías y Jahdiel: hombres valientes y famosos, jefes de sus casas paternas.",
      "25": "Se rebelaron contra el Dios de sus padres y se prostituyeron en pos de los dioses de los pueblos de la tierra que Dios había destruido antes que ellos.",
      "26": "Entonces el Dios de Israel despertó el espíritu de Pul, rey de Asiria, y el espíritu de Tilgat Pilneser, rey de Asiria, y se llevó a los rubenitas, a los gaditas y a la media tribu de Manasés, y los llevó a Halah, Habor, Hara y al río de Gozán, hasta el día de hoy."
    }
  }
};

