
	
export const bib_verses = {
  "numbers": {
    "25": {
      "1": "Israel se quedó en Sitim, y el pueblo comenzó a prostituirse con las hijas de Moab;",
      "2": "pues llamaron al pueblo a los sacrificios de sus dioses. El pueblo comía y se inclinaba ante sus dioses.",
      "3": "Israel se unió a Baal Peor, y la ira de Yavé ardió contra Israel.",
      "4": "Yahvé dijo a Moisés: “Toma a todos los jefes del pueblo y cuélgalos a Yahvé ante el sol, para que el furor de Yahvé se aparte de Israel.” ",
      "5": "Moisés dijo a los jueces de Israel: “Maten todos a sus hombres que se han unido a Baal Peor”. ",
      "6": "He aquí que uno de los hijos de Israel vino y trajo a sus hermanos una mujer madianita a la vista de Moisés y de toda la congregación de los hijos de Israel, mientras lloraban a la puerta de la Tienda de Reunión.",
      "7": "Cuando Finees, hijo de Eleazar, hijo del sacerdote Aarón, lo vio, se levantó de en medio de la congregación y tomó una lanza en su mano.",
      "8": "Fue tras el hombre de Israel al pabellón, y los atravesó a ambos, al hombre de Israel y a la mujer por el cuerpo. Así se detuvo la plaga entre los hijos de Israel.",
      "9": "Los que murieron por la plaga fueron veinticuatro mil. ",
      "10": "Yahvé habló a Moisés y le dijo:",
      "11": "“Finees, hijo de Eleazar, hijo del sacerdote Aarón, ha alejado mi ira de los hijos de Israel, ya que se puso celoso con mis celos entre ellos, para que yo no consumiera a los hijos de Israel en mis celos.",
      "12": "Por tanto, di: “He aquí que yo le doy mi pacto de paz.",
      "13": "Será para él, y para su descendencia después de él, el pacto de un sacerdocio eterno, porque fue celoso por su Dios e hizo expiación por los hijos de Israel.’” ",
      "14": "El nombre del hombre de Israel que fue asesinado con la mujer madianita era Zimri, hijo de Salu, príncipe de una casa paterna entre los simeonitas.",
      "15": "El nombre de la mujer madianita que fue asesinada era Cozbi, hija de Zur. Era jefe de la gente de una casa paterna en Madián. ",
      "16": "Yahvé habló a Moisés, diciendo:",
      "17": "“Acosa a los madianitas y golpéalos;",
      "18": "porque te han acosado con sus artimañas, en las que te han engañado en el asunto de Peor, y en el incidente relativo a Cozbi, la hija del príncipe de Madián, su hermana, que fue asesinada el día de la plaga en el asunto de Peor.”"
    },
    "26": {
      "1": "Después de la plaga, Yahvé habló a Moisés y al sacerdote Eleazar hijo de Aarón, diciendo:",
      "2": "“Hagan un censo de toda la congregación de los hijos de Israel, de veinte años en adelante, por las casas de sus padres, todos los que puedan salir a la guerra en Israel.”",
      "3": "Moisés y el sacerdote Eleazar hablaron con ellos en las llanuras de Moab, junto al Jordán, en Jericó, diciendo:",
      "4": "“Hagan un censo, de veinte años en adelante, como Yahvé les ordenó a Moisés y a los hijos de Israel.” Estos son los que salieron de la tierra de Egipto.",
      "5": "Rubén, el primogénito de Israel; los hijos de Rubén: de Hanoc, la familia de los Hanocitas; de Palú, la familia de los Palúitas;",
      "6": "de Hezrón, la familia de los Hezronitas; de Carmi, la familia de los Carmitas.",
      "7": "Estas son las familias de los rubenitas; y los contados de ellas fueron cuarenta y tres mil setecientos treinta.",
      "8": "El hijo de Pallu: Eliab.",
      "9": "Los hijos de Eliab: Nemuel, Datán y Abiram. Estos son aquellos Datán y Abiram que fueron llamados por la congregación, que se rebelaron contra Moisés y contra Aarón en la compañía de Coré cuando se rebelaron contra Yahvé;",
      "10": "y la tierra abrió su boca y los tragó junto con Coré cuando esa compañía murió; en ese momento el fuego devoró a doscientos cincuenta hombres, y se convirtieron en una señal.",
      "11": "Sin embargo, los hijos de Coré no murieron.",
      "12": "Los hijos de Simeón por sus familias: de Nemuel, la familia de los nemuelitas; de Jamín, la familia de los jaminitas; de Jacín, la familia de los jacinitas;",
      "13": "de Zera, la familia de los zeraítas; de Shaúl, la familia de los shaúlitas.",
      "14": "Estas son las familias de los simeonitas, veintidós mil doscientos.",
      "15": "Los hijos de Gad por sus familias: de Zefón, la familia de los zefonitas; de Haggi, la familia de los haggitas; de Shuni, la familia de los shunitas;",
      "16": "de Ozni, la familia de los oznitas; de Eri, la familia de los eritas;",
      "17": "de Arod, la familia de los aroditas; de Areli, la familia de los arelitas.",
      "18": "Estas son las familias de los hijos de Gad según los contados de ellos, cuarenta mil quinientos.",
      "19": "Los hijos de Judá: Er y Onán. Er y Onán murieron en la tierra de Canaán.",
      "20": "Los hijos de Judá por sus familias fueron: de Selá, la familia de los selanitas; de Pérez, la familia de los pérezicos; de Zera, la familia de los zeraitas.",
      "21": "Los hijos de Pérez fueron: de Hezrón, la familia de los hezronitas; de Hamul, la familia de los hamulitas.",
      "22": "Estas son las familias de Judá según los contados de ellas, setenta y seis mil quinientos.",
      "23": "Los hijos de Isacar por sus familias: de Tola, la familia de los tolaítas; de Puva, la familia de los punítas;",
      "24": "de Jasub, la familia de los jasubitas; de Simrón, la familia de los simronitas.",
      "25": "Estas son las familias de Isacar según los contados de ellas, sesenta y cuatro mil trescientos.",
      "26": "Los hijos de Zabulón por sus familias: de Sered, la familia de los sereditas; de Elón, la familia de los elonitas; de Jahleel, la familia de los jahleelitas.",
      "27": "Estas son las familias de los zabulonitas según los contados de ellos, sesenta mil quinientos.",
      "28": "Los hijos de José según sus familias: Manasés y Efraín.",
      "29": "Los hijos de Manasés: de Maquir, la familia de los maquiritas; y Maquir fue el padre de Galaad; de Galaad, la familia de los galaaditas.",
      "30": "Estos son los hijos de Galaad: de Iezer, la familia de los Iezeritas; de Helek, la familia de los Helekitas;",
      "31": "y de Asriel, la familia de los Asrielitas; y de Siquem, la familia de los Siquemitas;",
      "32": "y de Semida, la familia de los Semidaitas; y de Hefer, la familia de los Heferitas.",
      "33": "Zelofehad, hijo de Hefer, no tuvo hijos, sino hijas; y los nombres de las hijas de Zelofehad fueron Mahá, Noé, Hogá, Milca y Tirsa.",
      "34": "Estas son las familias de Manasés. Los contados de ellos fueron cincuenta y dos mil setecientos.",
      "35": "Estos son los hijos de Efraín por sus familias: de Sutela, la familia de los Sutelitas; de Becher, la familia de los Becheritas; de Tahan, la familia de los Tahanitas.",
      "36": "Estos son los hijos de Sutela: de Erán, la familia de los eranitas.",
      "37": "Estas son las familias de los hijos de Efraín, según los contados de ellos, treinta y dos mil quinientos. Estos son los hijos de José por sus familias.",
      "38": "Los hijos de Benjamín por sus familias: de Bela, la familia de los belaítas; de Asbel, la familia de los asbelitas; de Ahiram, la familia de los ahiramitas;",
      "39": "de Sefufam, la familia de los shufamitas; de Hufam, la familia de los hufamitas.",
      "40": "Los hijos de Bela fueron Ard y Naamán: la familia de los arditas; y de Naamán, la familia de los naamitas.",
      "41": "Estos son los hijos de Benjamín por sus familias; y los contados de ellos fueron cuarenta y cinco mil seiscientos.",
      "42": "Estos son los hijos de Dan por sus familias: de Shuham, la familia de los shuhamitas. Estas son las familias de Dan por sus familias.",
      "43": "Todas las familias de los suhamitas, según los contados de ellos, fueron sesenta y cuatro mil cuatrocientos.",
      "44": "Los hijos de Aser por sus familias: de Imna, la familia de los imnitas; de Ishvi, la familia de los ishvitas; de Beriá, la familia de los beritas.",
      "45": "De los hijos de Beriá: de Heber, la familia de los heberitas; de Malquiel, la familia de los malquielitas.",
      "46": "El nombre de la hija de Aser fue Sera.",
      "47": "Estas son las familias de los hijos de Aser según los contados de ellos, cincuenta y tres mil cuatrocientos.",
      "48": "Los hijos de Neftalí por sus familias: de Jahzeel, la familia de los jahzeelitas; de Guni, la familia de los gunitas;",
      "49": "de Jezer, la familia de los jezeritas; de Silim, la familia de los sillemitas.",
      "50": "Estas son las familias de Neftalí según sus familias; y los contados de ellas fueron cuarenta y cinco mil cuatrocientos.",
      "51": "Estos son los contados de los hijos de Israel, seiscientos un mil setecientos treinta. ",
      "52": "Yahvé habló a Moisés diciendo:",
      "53": "“A éstos se les repartirá la tierra en herencia según el número de nombres.",
      "54": "A los más les darás más herencia, y a los menos les darás menos herencia. A cada uno se le dará su herencia según los contados de él.",
      "55": "Sin embargo, la tierra se dividirá por sorteo. Según los nombres de las tribus de sus padres heredarán.",
      "56": "Según la suerte se repartirá su herencia entre los más y los menos”. ",
      "57": "Estos son los contados de los levitas según sus familias: de Gersón, la familia de los gersonitas; de Coat, la familia de los coatitas; de Merari, la familia de los meraritas.",
      "58": "Estas son las familias de Leví: la familia de los libnitas, la familia de los hebronitas, la familia de los mahlitas, la familia de los musitas y la familia de los corasitas. Coat fue el padre de Amram.",
      "59": "El nombre de la esposa de Amram era Jocabed, hija de Leví, que había nacido de Leví en Egipto. Ella dio a luz a Amram, a Aarón y a Moisés, y a su hermana Miriam.",
      "60": "De Aarón nacieron Nadab y Abiú, Eleazar e Itamar.",
      "61": "Nadab y Abiú murieron cuando ofrecieron fuego extraño ante Yahvé.",
      "62": "Los que fueron contados de ellos fueron veintitrés mil, todos los varones de un mes para arriba; pues no fueron contados entre los hijos de Israel, porque no se les dio herencia entre los hijos de Israel.",
      "63": "Estos son los que fueron contados por Moisés y el sacerdote Eleazar, quienes contaron a los hijos de Israel en los llanos de Moab, junto al Jordán de Jericó.",
      "64": "Pero entre éstos no hubo ninguno de los que fueron contados por Moisés y el sacerdote Aarón, que contaron a los hijos de Israel en el desierto de Sinaí.",
      "65": "Porque Yahvé había dicho de ellos: “Ciertamente morirán en el desierto”. No quedó ningún hombre de ellos, excepto Caleb, hijo de Jefone, y Josué, hijo de Nun."
    },
    "27": {
      "1": "Entonces se acercaron las hijas de Zelofehad, hijo de Hefer, hijo de Galaad, hijo de Maquir, hijo de Manasés, de las familias de Manasés hijo de José. Estos son los nombres de sus hijas: Mahá, Noé, Hogá, Milca y Tirsa.",
      "2": "Se presentaron ante Moisés, ante el sacerdote Eleazar y ante los príncipes y toda la congregación, a la puerta de la Tienda del Encuentro, diciendo:",
      "3": "“Nuestro padre murió en el desierto. No estaba entre la compañía de los que se agruparon contra Yavé en compañía de Coré, sino que murió en su propio pecado. No tuvo hijos.",
      "4": "¿Por qué se ha de quitar el nombre de nuestro padre de entre su familia, porque no tuvo hijo? Danos una posesión entre los hermanos de nuestro padre”. ",
      "5": "Moisés llevó su causa ante el Señor.",
      "6": "Yahvé habló a Moisés, diciendo:",
      "7": "“Las hijas de Zelofehad hablan con razón. Ciertamente les darás posesión de una herencia entre los hermanos de su padre. Harás que la herencia de su padre pase a ellas.",
      "8": "Hablarás a los hijos de Israel diciendo: “Si un hombre muere y no tiene hijo, harás que su herencia pase a su hija.",
      "9": "Si no tiene hija, darás su herencia a sus hermanos.",
      "10": "Si no tiene hermanos, darás su herencia a los hermanos de su padre.",
      "11": "Si su padre no tiene hermanos, entonces darás su herencia a su pariente más cercano de su familia, y él la poseerá. Esto será un estatuto y una ordenanza para los hijos de Israel, como Yahvé le ordenó a Moisés”. ",
      "12": "Yahvé dijo a Moisés: “Sube a este monte de Abarim y ve la tierra que he dado a los hijos de Israel.",
      "13": "Cuando la hayas visto, tú también serás reunido con tu pueblo, como fue reunido tu hermano Aarón;",
      "14": "porque en la contienda de la congregación, te rebelaste contra mi palabra en el desierto de Zin, para honrarme como santo en las aguas ante sus ojos.” (Estas son las aguas de Meribah de Cades en el desierto de Zin). ",
      "15": "Moisés habló a Yahvé, diciendo:",
      "16": "“Que Yahvé, el Dios de los espíritus de toda carne, designe a un hombre sobre la congregación,",
      "17": "que salga delante de ellos, y que entre delante de ellos, y que los conduzca fuera, y que los haga entrar, para que la congregación de Yahvé no sea como ovejas que no tienen pastor.” ",
      "18": "El Señor dijo a Moisés: “Toma a Josué, hijo de Nun, un hombre en el que está el Espíritu, y pon tu mano sobre él.",
      "19": "Ponlo delante del sacerdote Eleazar y de toda la congregación, y encárgalo ante ellos.",
      "20": "Le darás autoridad, para que toda la congregación de los hijos de Israel obedezca.",
      "21": "Se presentará ante el sacerdote Eleazar, quien preguntará por él con el juicio del Urim ante Yahvé. A su palabra saldrán, y a su palabra entrarán, él y todos los hijos de Israel con él, toda la congregación.” ",
      "22": "Moisés hizo lo que el Señor le había ordenado. Tomó a Josué y lo presentó ante el sacerdote Eleazar y ante toda la congregación.",
      "23": "Le impuso las manos y lo comisionó, tal como Yahvé habló por medio de Moisés."
    },
    "28": {
      "1": "Yahvé habló a Moisés, diciendo:",
      "2": "“Ordena a los hijos de Israel y diles: ‘Procuren presentar mi ofrenda, mi alimento para mis ofrendas encendidas, como aroma agradable para mí, a su debido tiempo’.",
      "3": "Les dirás: ‘Esta es la ofrenda encendida que ofrecerás a Yavé: corderos machos de un año sin defecto, dos al día, para un holocausto continuo.",
      "4": "Ofrecerás un cordero por la mañana, y ofrecerás el otro cordero al atardecer,",
      "5": "con la décima parte de un efa  de harina fina como ofrenda, mezclada con la cuarta parte de un hin  de aceite batido.",
      "6": "Es un holocausto continuo que fue ordenado en el monte Sinaí como aroma agradable, una ofrenda hecha por fuego a Yahvé.",
      "7": "Su libación será la cuarta parte de un hin por cada cordero. Derramarás una libación de bebida fuerte a Yahvé en el lugar santo.",
      "8": "El otro cordero lo ofrecerás al atardecer. Como la ofrenda de la mañana, y como su libación, lo ofrecerás, ofrenda encendida, como aroma agradable a Yahvé. ",
      "9": "“‘En el día de reposo, ofrecerás dos corderos machos de un año sin defecto, y dos décimas de efa  de harina fina como ofrenda mezclada con aceite, y su libación:",
      "10": "Este es el holocausto de cada sábado, además del holocausto continuo y su libación. ",
      "11": "“‘En los comienzos de tus meses, ofrecerás un holocausto a Yahvé dos novillos, un carnero, siete corderos machos de un año sin defecto,",
      "12": "y tres décimas de un efa  de harina fina para un holocausto mezclado con aceite, para cada toro; y dos décimas de harina fina para un holocausto mezclado con aceite, para el único carnero;",
      "13": "y una décima de harina fina mezclada con aceite para un holocausto a cada cordero, como ofrenda quemada de aroma agradable, ofrenda hecha por fuego a Yahvé.",
      "14": "Sus libaciones serán la mitad de un hin de vino para el toro, la tercera parte de un hin para el carnero y la cuarta parte de un hin para el cordero. Este es el holocausto de cada mes durante todos los meses del año.",
      "15": "También se ofrecerá un macho cabrío como ofrenda por el pecado a Yahvé, además del holocausto continuo y su libación. ",
      "16": "“‘En el primer mes, el día catorce del mes, es la Pascua de Yahvé.",
      "17": "El decimoquinto día de este mes habrá una fiesta. Se comerá pan sin levadura durante siete días.",
      "18": "En el primer día habrá una santa convocación. No harás ningún trabajo regular,",
      "19": "sino que ofrecerás una ofrenda encendida, un holocausto a Yahvé: dos novillos, un carnero y siete corderos de un año. Serán sin defecto,",
      "20": "con su ofrenda de harina, harina fina mezclada con aceite. Ofrecerás tres décimas por el toro, y dos décimas por el carnero.",
      "21": "Ofrecerás una décima por cada cordero de los siete corderos;",
      "22": "y un macho cabrío como ofrenda por el pecado, para hacer expiación por ti.",
      "23": "Los ofrecerás además del holocausto de la mañana, que es un holocausto continuo.",
      "24": "Así ofrecerás cada día, durante siete días, el alimento de la ofrenda encendida, de aroma agradable para Yahvé. Se ofrecerá además del holocausto continuo y su libación.",
      "25": "El séptimo día tendréis una santa convocación. No harás ningún trabajo regular. ",
      "26": "“‘También en el día de las primicias, cuando ofrezcas una nueva ofrenda a Yahvé en tu fiesta de las semanas, tendrás una santa convocación. No harás ningún trabajo regular;",
      "27": "sino que ofrecerás un holocausto como aroma agradable a Yahvé: dos novillos, un carnero, siete corderos macho de un año;",
      "28": "y su ofrenda de harina fina mezclada con aceite, tres décimas por cada toro, dos décimas por el único carnero,",
      "29": "una décima por cada cordero de los siete corderos;",
      "30": "y un macho cabrío, para hacer expiación por ti.",
      "31": "Además del holocausto continuo y su ofrenda de comida, los ofrecerás junto con sus libaciones. Procura que sean sin defecto."
    },
    "29": {
      "1": "“‘En el séptimo mes, el primer día del mes, tendréis una santa convocación; no haréis ningún trabajo regular. Es un día de toque de trompetas para ti.",
      "2": "Ofrecerás un holocausto como aroma agradable a Yahvé: un novillo, un carnero, siete corderos machos de un año sin defecto;",
      "3": "y su ofrenda de harina fina mezclada con aceite: tres décimas por el toro, dos décimas por el carnero,",
      "4": "y una décima por cada cordero de los siete corderos;",
      "5": "y un macho cabrío como ofrenda por el pecado, para hacer expiación por vosotros;",
      "6": "además del holocausto de la luna nueva con su ofrenda, y el holocausto continuo con su ofrenda, y sus libaciones, según su ordenanza, como aroma agradable, ofrenda encendida a Yahvé. ",
      "7": "“‘En el décimo día de este séptimo mes tendréis una santa convocación. Afligiréis vuestras almas. No haréis ninguna clase de trabajo;",
      "8": "sino que ofreceréis a Yahvé un holocausto como aroma agradable: un novillo, un carnero, siete corderos macho de un año, todos sin defecto;",
      "9": "y su ofrenda de harina fina mezclada con aceite: tres décimas por el toro, dos décimas por el único carnero,",
      "10": "una décima por cada cordero de los siete corderos;",
      "11": "un macho cabrío como ofrenda por el pecado, además de la ofrenda por el pecado de la expiación, y el holocausto continuo, y su ofrenda de comida, y sus libaciones. ",
      "12": "“‘El decimoquinto día del séptimo mes tendrás una santa convocación. No harás ningún trabajo regular. Celebrarás una fiesta a Yahvé durante siete días.",
      "13": "Ofrecerás un holocausto, una ofrenda encendida, de aroma agradable a Yahvé: trece novillos, dos carneros, catorce corderos machos de un año, todos sin defecto;",
      "14": "y su ofrenda de harina fina mezclada con aceite: tres décimas por cada toro de los trece toros, dos décimas por cada carnero de los dos carneros,",
      "15": "y una décima por cada cordero de los catorce corderos;",
      "16": "y un macho cabrío para la ofrenda por el pecado, además del holocausto continuo, su ofrenda y su libación. ",
      "17": "“‘El segundo día ofrecerás doce novillos, dos carneros y catorce corderos machos de un año sin defecto;",
      "18": "y su ofrenda y su libación por los toros, por los carneros y por los corderos, según su número, conforme a la ordenanza;",
      "19": "y un macho cabrío como ofrenda por el pecado, además del holocausto continuo, con su ofrenda y su libación. ",
      "20": "“‘Al tercer día: once toros, dos carneros, catorce corderos machos de un año sin defecto;",
      "21": "y su ofrenda y su libación por los toros, por los carneros y por los corderos, según su número, conforme a la ordenanza;",
      "22": "y un macho cabrío como ofrenda por el pecado, además del holocausto continuo, y su ofrenda y su libación. ",
      "23": "“‘Al cuarto día diez toros, dos carneros, catorce corderos machos de un año sin defecto;",
      "24": "su ofrenda y su libación por los toros, por los carneros y por los corderos, según su número, conforme a la ordenanza;",
      "25": "y un macho cabrío como ofrenda por el pecado; además del holocausto continuo, su ofrenda y su libación. ",
      "26": "“‘Al quinto día: nueve toros, dos carneros, catorce corderos machos de un año sin defecto;",
      "27": "y su ofrenda y su libación por los toros, por los carneros y por los corderos, según su número, conforme a la ordenanza,",
      "28": "y un macho cabrío como ofrenda por el pecado, además del holocausto continuo, y su ofrenda y su libación. ",
      "29": "“‘En el sexto día: ocho toros, dos carneros, catorce corderos machos de un año sin defecto;",
      "30": "y su ofrenda y su libación por los toros, por los carneros y por los corderos, según su número, conforme a la ordenanza,",
      "31": "y un macho cabrío como ofrenda por el pecado; además del holocausto continuo, su ofrenda y su libación. ",
      "32": "“‘En el séptimo día: siete toros, dos carneros, catorce corderos machos de un año sin defecto;",
      "33": "y su ofrenda y su libación por los toros, por los carneros y por los corderos, según su número, conforme a la ordenanza,",
      "34": "y un macho cabrío como ofrenda por el pecado; además del holocausto continuo, su ofrenda y su libación. ",
      "35": "“‘El octavo día tendrás una asamblea solemne. No harás ningún trabajo regular;",
      "36": "sino que ofrecerás un holocausto, una ofrenda encendida, un aroma agradable a Yahvé: un toro, un carnero, siete corderos machos de un año sin defecto;",
      "37": "su ofrenda y su libación por el toro, por el carnero y por los corderos, serán según su número, conforme a la ordenanza,",
      "38": "y un macho cabrío como ofrenda por el pecado, además del holocausto continuo, con su ofrenda y su libación. ",
      "39": "“‘Ofrecerás esto a Yahvé en tus fiestas establecidas — además de tus votos y tus ofrendas voluntarias — para tus holocaustos, tus ofrendas de comida, tus ofrendas de bebida y tus ofrendas de paz’”. ",
      "40": "Moisés dijo a los hijos de Israel todo lo que Yahvé le había ordenado a Moisés."
    },
    "30": {
      "1": "Moisés habló a los jefes de las tribus de los hijos de Israel, diciendo: “Esto es lo que Yahvé ha ordenado.",
      "2": "Cuando un hombre haga un voto a Yavé, o haga un juramento para atar su alma con un vínculo, no deberá faltar a su palabra. Hará conforme a todo lo que salga de su boca. ",
      "3": "“Además, cuando una mujer hace un voto a Yahvé y se compromete con una promesa, estando en la casa de su padre, en su juventud,",
      "4": "y su padre oye su voto y su promesa con la que ha vinculado su alma, y su padre no le dice nada, entonces todos sus votos serán válidos, y toda promesa con la que haya vinculado su alma será válida.",
      "5": "Pero si su padre se lo prohíbe el día que se entere, ninguno de sus votos ni de sus promesas con los que haya ligado su alma subsistirán. El Señor la perdonará, porque su padre se lo ha prohibido. ",
      "6": "“Si tiene marido, mientras sus votos están sobre ella, o la imprudente expresión de sus labios con la que ha ligado su alma,",
      "7": "y su marido lo oye, y no le dice nada el día que lo oye, entonces sus votos serán firmes, y sus promesas con las que ha ligado su alma serán firmes.",
      "8": "Pero si su marido se lo prohíbe el día que lo oiga, entonces anulará su voto que está sobre ella y las palabras imprudentes de sus labios, con las que ha ligado su alma. El Señor la perdonará. ",
      "9": "“Pero el voto de la viuda o de la divorciada, todo aquello con lo que haya ligado su alma quedará en su contra. ",
      "10": "“Si ella hizo un voto en casa de su marido o vinculó su alma con un juramento,",
      "11": "y su marido lo oyó, y calló ante ella y no la desautorizó, entonces todos sus votos serán válidos, y toda prenda con la que vinculó su alma será válida.",
      "12": "Pero si su marido los anuló el día que los oyó, entonces todo lo que haya salido de sus labios en cuanto a sus votos, o en cuanto al vínculo de su alma, no subsistirá. Su marido los ha anulado. El Señor la perdonará.",
      "13": "Todo voto, y todo juramento vinculante para afligir el alma, su marido puede establecerlo, o su marido puede anularlo.",
      "14": "Pero si su esposo no le dice nada de un día para otro, entonces él establece todos sus votos o todos sus juramentos que están sobre ella. Los ha establecido, porque no le dijo nada el día que los escuchó.",
      "15": "Pero si los anula después de haberlos escuchado, entonces él cargará con su iniquidad.” ",
      "16": "Estosson los estatutos que Yahvé ordenó a Moisés, entre un hombre y su esposa, entre un padre y su hija, estando en su juventud, en la casa de su padre."
    },
    "31": {
      "1": "Yahvé habló a Moisés, diciendo:",
      "2": "“Véngate de los hijos de Israel contra los madianitas. Después te reunirás con tu pueblo”. ",
      "3": "Moisés habló al pueblo diciendo: “Arma a los hombres de entre ustedes para la guerra, para que vayan contra Madián, para ejecutar la venganza de Yavé contra Madián.",
      "4": "Enviaréis mil de cada tribu, de todas las tribus de Israel, a la guerra.”",
      "5": "Así que fueron entregados, de los miles de Israel, mil de cada tribu, doce mil armados para la guerra.",
      "6": "Moisés los envió, mil de cada tribu, a la guerra con Finees, hijo del sacerdote Eleazar, a la guerra, con los utensilios del santuario y las trompetas de alarma en su mano.",
      "7": "Lucharon contra Madián, como Yahvé le ordenó a Moisés. Mataron a todos los varones.",
      "8": "Mataron a los reyes de Madián con el resto de sus muertos: Evi, Rekem, Zur, Hur y Reba, los cinco reyes de Madián. También mataron a espada a Balaam, hijo de Beor.",
      "9": "Los hijos de Israel tomaron cautivas a las mujeres de Madián con sus hijos, y tomaron como botín todo su ganado, todos sus rebaños y todos sus bienes.",
      "10": "Quemaron todas sus ciudades en los lugares donde vivían y todos sus campamentos.",
      "11": "Tomaron todos los cautivos y todo el botín, tanto de hombres como de animales.",
      "12": "Llevaron a los cautivos, con la presa y el botín, a Moisés, al sacerdote Eleazar y a la congregación de los hijos de Israel, al campamento de los llanos de Moab, que están junto al Jordán, en Jericó.",
      "13": "Moisés y el sacerdote Eleazar, con todos los jefes de la congregación, salieron a recibirlos fuera del campamento.",
      "14": "Moisés se enojó con los oficiales del ejército, los capitanes de mil y los de cien, que venían del servicio de guerra.",
      "15": "Moisés les dijo: “¿Habéis salvado a todas las mujeres con vida?",
      "16": "He aquí que éstas hicieron que los hijos de Israel, por consejo de Balaam, cometieran transgresión contra Yavé en el asunto de Peor, y así fue la plaga en la congregación de Yavé.",
      "17": "Maten, pues, a todo varón entre los pequeños, y maten a toda mujer que haya conocido al hombre acostándose con él.",
      "18": "Pero todas las muchachas que no hayan conocido al hombre acostándose con él, manténganse vivas. ",
      "19": "“Acampad fuera del campamento durante siete días. El que haya matado a alguna persona, y el que haya tocado a algún muerto, purificaos al tercer día y al séptimo, vosotros y vuestros cautivos.",
      "20": "Purificaréis todos los vestidos, todo lo que sea de piel, todo lo que sea de pelo de cabra y todo lo que sea de madera.” ",
      "21": "El sacerdote Eleazar dijo a los hombres de guerra que iban a la batalla: “Este es el estatuto de la ley que Yahvé ha ordenado a Moisés.",
      "22": "Sin embargo, el oro, la plata, el bronce, el hierro, el estaño y el plomo,",
      "23": "todo lo que pueda resistir el fuego, lo haréis pasar por el fuego, y quedará limpio; no obstante, será purificado con el agua para la impureza. Todo lo que no resista el fuego lo harás pasar por el agua.",
      "24": "El séptimo día lavarás tus ropas, y quedarás limpio. Después entrarás en el campamento”. ",
      "25": "Yahvé habló a Moisés, diciendo:",
      "26": "“Cuenta el botín que fue tomado, tanto de personas como de animales, tú, y el sacerdote Eleazar, y los jefes de familia de la congregación;",
      "27": "y divide el botín en dos partes: entre los hombres hábiles en la guerra, que salieron a la batalla, y toda la congregación.",
      "28": "Levanten un tributo a Yahvé de los hombres de guerra que salieron a la batalla: un alma de cada quinientos; de las personas, del ganado, de los asnos y de los rebaños.",
      "29": "Tómalo de la mitad de ellos y dáselo al sacerdote Eleazar, para la ofrenda mecida de Yavé.",
      "30": "De la mitad de los hijos de Israel, tomarás un alma de cada cincuenta, de las personas, del ganado, de los asnos y de los rebaños, de todo el ganado, y se los darás a los levitas, que cumplen con el deber del tabernáculo de Yavé.” ",
      "31": "Moisés y el sacerdote Eleazar hicieron lo que Yahvé les ordenó. ",
      "32": "El botín, además del botín que tomaron los hombres de guerra, fue de seiscientas setenta y cinco mil ovejas,",
      "33": "setenta y dos mil cabezas de ganado,",
      "34": "sesenta y un mil asnos,",
      "35": "y treinta y dos mil personas en total, de las mujeres que no habían conocido al hombre acostándose con él.",
      "36": "La mitad, que era la porción de los que salían a la guerra, era en número de trescientas treinta y siete mil quinientas ovejas;",
      "37": "y el tributo de las ovejas era de seiscientas setenta y cinco.",
      "38": "El ganado vacuno era de treinta y seis mil, de los cuales el tributo de Yahvé era de setenta y dos.",
      "39": "Los asnos eran treinta mil quinientos, de los cuales el tributo del Señor era sesenta y uno.",
      "40": "Las personas eran dieciséis mil, de las cuales el tributo de Yahvé era de treinta y dos personas.",
      "41": "Moisés entregó el tributo, que era la ofrenda mecida de Yavé, al sacerdote Eleazar, como Yavé se lo había ordenado a Moisés.",
      "42": "De la mitad de los hijos de Israel, que Moisés repartió entre los hombres que combatieron",
      "43": "(la mitad de la congregación era de trescientas treinta y siete mil quinientas ovejas,",
      "44": "treinta y seis mil cabezas de ganado,",
      "45": "treinta mil quinientos asnos",
      "46": "y dieciséis mil personas),",
      "47": "de la mitad de los hijos de Israel, Moisés tomó un animal de cada cincuenta, tanto de hombres como de animales, y se los dio a los levitas, que cumplían con el deber del tabernáculo de Yahvé, como Yahvé le ordenó a Moisés. ",
      "48": "Se acercaron a Moisés los oficiales que estaban al frente de los miles del ejército, los capitanes de miles y los de cientos.",
      "49": "Le dijeron a Moisés: “Tus siervos han tomado la suma de los hombres de guerra que están bajo nuestro mando, y no falta ni uno de nosotros.",
      "50": "Hemos traído la ofrenda de Yavé, lo que cada uno encontró: adornos de oro, brazaletes, pulseras, anillos de sello, pendientes y collares, para expiar nuestras almas ante Yavé.” ",
      "51": "Moisés y el sacerdote Eleazar tomaron su oro, todas las joyas trabajadas.",
      "52": "Todo el oro de la ofrenda de ola que ofrecieron a Yavé, de los capitanes de millares y de los capitanes de centenas, fue de dieciséis mil setecientos cincuenta siclos.  ",
      "53": "Los hombres de guerra habían tomado un botín, cada uno para sí mismo.",
      "54": "Moisés y el sacerdote Eleazar tomaron el oro de los capitanes de millares y de centenas, y lo llevaron a la Tienda del Encuentro como memorial para los hijos de Israel ante Yavé."
    },
    "32": {
      "1": "Los hijos de Rubén y los hijos de Gad tenían una gran cantidad de ganado. Vieron la tierra de Jazer y la tierra de Galaad. He aquí que el lugar era un sitio para el ganado.",
      "2": "Entonces los hijos de Gad y los hijos de Rubén vinieron y hablaron a Moisés, al sacerdote Eleazar y a los jefes de la congregación, diciendo:",
      "3": "“Atarot, Dibón, Jazer, Nimra, Hesbón, Eleale, Sebam, Nebo y Beón,",
      "4": "la tierra que Yahvé hirió ante la congregación de Israel, es tierra de ganado; y vuestros siervos tienen ganado.”",
      "5": "Ellos dijeron: “Si hemos hallado gracia ante tus ojos, que esta tierra sea dada a tus siervos como posesión. No nos hagas pasar el Jordán”. ",
      "6": "Moisés dijo a los hijos de Gad y a los hijos de Rubén: “¿Van a ir sus hermanos a la guerra mientras ustedes están sentados aquí?",
      "7": "¿Por qué desaniman el corazón de los hijos de Israel para que no vayan a la tierra que el Señor les ha dado?",
      "8": "Así lo hicieron sus padres cuando los envié desde Cades Barnea a ver la tierra.",
      "9": "Pues cuando subieron al valle de Escol y vieron la tierra, desanimaron el corazón de los hijos de Israel para que no entraran en la tierra que Yahvé les había dado.",
      "10": "Aquel día ardió la ira de Yavé, y juró diciendo:",
      "11": "‘Ciertamente ninguno de los hombres que subieron de Egipto, de veinte años en adelante, verá la tierra que juré a Abraham, a Isaac y a Jacob; porque no me han seguido del todo,",
      "12": "excepto Caleb hijo de Jefone cenezeo, y Josué hijo de Nun, porque han seguido a Yavé del todo.’",
      "13": "La ira del Señor se encendió contra Israel, y lo hizo vagar de un lado a otro del desierto durante cuarenta años, hasta que se consumió toda la generación que había hecho el mal a los ojos del Señor. ",
      "14": "“He aquí que ustedes se han levantado en el lugar de sus padres, un aumento de hombres pecadores, para aumentar el furor de Yahvé contra Israel.",
      "15": "Porque si os apartáis de él, volverá a dejarlos en el desierto, y destruiréis a todo este pueblo.” ",
      "16": "Se acercaron a él y le dijeron: “Construiremos aquí apriscos para nuestros ganados y ciudades para nuestros pequeños;",
      "17": "pero nosotros mismos estaremos listos armados para ir delante de los hijos de Israel, hasta que los hayamos llevado a su lugar. Nuestros pequeños vivirán en las ciudades fortificadas a causa de los habitantes de la tierra.",
      "18": "No volveremos a nuestras casas hasta que todos los hijos de Israel hayan recibido su herencia.",
      "19": "Porque no heredaremos con ellos al otro lado del Jordán y más allá, porque nuestra herencia nos ha llegado a este lado del Jordán hacia el este.” ",
      "20": "Moisés les dijo: “Si hacéis esto, si os armáis para ir delante de Yavé a la guerra,",
      "21": "y cada uno de vuestros hombres armados pasará el Jordán delante de Yavé hasta que haya expulsado a sus enemigos de delante de él,",
      "22": "y la tierra esté sometida delante de Yavé; entonces después volveréis, y estaréis libres de obligaciones para con Yavé y para con Israel. Entonces esta tierra será tu posesión ante el Señor. ",
      "23": "“Pero si no lo haces, he aquí que has pecado contra Yahvé; y ten por seguro que tu pecado te descubrirá.",
      "24": "Construye ciudades para tus pequeños, y rediles para tus ovejas; y haz lo que ha salido de tu boca.” ",
      "25": "Los hijos de Gad y los hijos de Rubén hablaron con Moisés y le dijeron: “Tus siervos harán lo que ordena mi señor.",
      "26": "Nuestros pequeños, nuestras mujeres, nuestros rebaños y todo nuestro ganado quedarán allí en las ciudades de Galaad;",
      "27": "pero tus siervos pasarán, cada uno de ellos armado para la guerra, delante de Yavé para combatir, como dice mi señor.” ",
      "28": "Entonces Moisés ordenó acerca de ellos al sacerdote Eleazar y a Josué hijo de Nun, y a los jefes de familia de las tribus de los hijos de Israel.",
      "29": "Moisés les dijo: “Si los hijos de Gad y los hijos de Rubén pasan con vosotros el Jordán, cada uno armado para la batalla delante de Yahvé, y la tierra es sometida delante de vosotros, les daréis la tierra de Galaad en posesión;",
      "30": "pero si no pasan con vosotros armados, tendrán posesión entre vosotros en la tierra de Canaán.” ",
      "31": "Los hijos de Gad y los hijos de Rubén respondieron diciendo: “Como Yahvé ha dicho a tus siervos, así haremos.",
      "32": "Pasaremos armados delante de Yavé a la tierra de Canaán, y la posesión de nuestra herencia quedará con nosotros al otro lado del Jordán.” ",
      "33": "Moisés les dio a los hijos de Gad, a los hijos de Rubén y a la media tribu de Manasés hijo de José, el reino de Sehón, rey de los amorreos, y el reino de Og, rey de Basán; la tierra, según sus ciudades y sus límites, las ciudades de los alrededores.",
      "34": "Los hijos de Gad edificaron Dibón, Atarot, Aroer,",
      "35": "Atrot-sofán, Jazer, Jogbehá,",
      "36": "Bet Nimra y Bet Harán: ciudades fortificadas y rediles para las ovejas.",
      "37": "Los hijos de Rubén edificaron Hesbón, Elealeh, Quiriatá,",
      "38": "Nebo y Baal Meón (sus nombres fueron cambiados) y Sibma. Dieron otros nombres a las ciudades que construyeron.",
      "39": "Los hijos de Maquir, hijo de Manasés, fueron a Galaad, la tomaron y despojaron a los amorreos que estaban en ella.",
      "40": "Moisés dio Galaad a Maquir hijo de Manasés, y éste vivió en ella.",
      "41": "Jair hijo de Manasés fue y tomó sus aldeas, y las llamó Havvoth Jair.",
      "42": "Nobah fue y tomó Kenath y sus aldeas, y la llamó Nobah, según su propio nombre."
    },
    "33": {
      "1": "Estos son los viajes de los hijos de Israel, cuando salieron de la tierra de Egipto con sus ejércitos bajo la mano de Moisés y Aarón.",
      "2": "Moisés escribió los puntos de partida de sus viajes por mandato de Yahvé. Estos son sus viajes según sus puntos de partida.",
      "3": "Partieron de Ramsés en el primer mes, el día quince del primer mes; al día siguiente de la Pascua, los hijos de Israel salieron con la mano en alto a la vista de todos los egipcios,",
      "4": "mientras los egipcios enterraban a todos sus primogénitos, a los que Yahvé había herido entre ellos. Yahvé también ejecutó juicios sobre sus dioses.",
      "5": "Los hijos de Israel partieron de Ramsés y acamparon en Sucot.",
      "6": "Partieron de Sucot y acamparon en Etam, que está en el límite del desierto.",
      "7": "Partieron de Etham y volvieron a Pihahiroth, que está frente a Baal Zephon, y acamparon frente a Migdol.",
      "8": "Partieron de delante de Hahirot y cruzaron por el medio del mar hacia el desierto. Recorrieron tres días de camino en el desierto de Etham, y acamparon en Mara.",
      "9": "Partieron de Mara y llegaron a Elim. En Elim había doce fuentes de agua y setenta palmeras, y acamparon allí.",
      "10": "Partieron de Elim y acamparon junto al Mar Rojo.",
      "11": "Partieron del Mar Rojo y acamparon en el desierto de Sin.",
      "12": "Partieron del desierto de Sin y acamparon en Dofka.",
      "13": "Partieron de Dofka y acamparon en Alush.",
      "14": "Partieron de Alush y acamparon en Refidim, donde no había agua para que el pueblo bebiera.",
      "15": "Partieron de Refidim y acamparon en el desierto de Sinaí.",
      "16": "Partieron del desierto de Sinaí y acamparon en Kibroth Hattaavah.",
      "17": "Partieron de Kibroth Hattaavah y acamparon en Hazeroth.",
      "18": "Partieron de Hazeroth y acamparon en Rithmah.",
      "19": "Partieron de Ritma y acamparon en Rimón Pérez.",
      "20": "Partieron de Rimón Pérez y acamparon en Libná.",
      "21": "Partieron de Libná y acamparon en Risá.",
      "22": "Partieron de Risá y acamparon en Kehelatá.",
      "23": "Partieron de Kehelatá y acamparon en el monte Ovejero.",
      "24": "Partieron del monte Ovejero y acamparon en Harada.",
      "25": "Partieron de Harada y acamparon en Majelot.",
      "26": "Partieron de Majelot y acamparon en Tahat.",
      "27": "Partieron de Tahat y acamparon en Taré.",
      "28": "Partieron de Taré y acamparon en Mitcá.",
      "29": "Partieron de Mitca y acamparon en Hasmona.",
      "30": "Partieron de Hasmona y acamparon en Moserot.",
      "31": "Partieron de Moserot y acamparon en Bene Jaakán.",
      "32": "Partieron de Bene Jaakan y acamparon en Hor Haggidgad.",
      "33": "Partieron de Hor Haggidgad y acamparon en Jotbatha.",
      "34": "Partieron de Jotbata y acamparon en Abrona.",
      "35": "Partieron de Abrona y acamparon en Ezión Geber.",
      "36": "Partieron de Ezión Geber y acamparon en Cades, en el desierto de Zin.",
      "37": "Partieron de Cades y acamparon en el monte Hor, en el límite de la tierra de Edom.",
      "38": "El sacerdote Aarón subió al monte Hor por orden de Yavé y murió allí, en el cuadragésimo año después de que los hijos de Israel salieron de la tierra de Egipto, en el quinto mes, el primer día del mes.",
      "39": "Aarón tenía ciento veintitrés años cuando murió en el monte Hor.",
      "40": "El rey cananeo de Arad, que vivía en el sur, en la tierra de Canaán, se enteró de la llegada de los hijos de Israel.",
      "41": "Partieron del monte Hor y acamparon en Salmoná.",
      "42": "Partieron de Salmoná y acamparon en Punón.",
      "43": "Partieron de Punón y acamparon en Obot.",
      "44": "Partieron de Oboth y acamparon en Iye Abarim, en la frontera de Moab.",
      "45": "Partieron de Iyim y acamparon en Dibón Gad.",
      "46": "Partieron de Dibón Gad y acamparon en Almon Diblathaim.",
      "47": "Partieron de Almon Diblathaim y acamparon en los montes de Abarim, frente a Nebo.",
      "48": "Partieron de los montes de Abarim y acamparon en las llanuras de Moab, junto al Jordán, en Jericó.",
      "49": "Acamparon junto al Jordán, desde Bet Jeshimot hasta Abel Shittim, en las llanuras de Moab.",
      "50": "Yahvé habló a Moisés en las llanuras de Moab, junto al Jordán de Jericó, diciendo:",
      "51": "Habla a los hijos de Israel y diles: “Cuando paséis el Jordán a la tierra de Canaán,",
      "52": "entonces expulsaréis a todos los habitantes de la tierra de delante de vosotros, destruiréis todos sus ídolos de piedra, destruiréis todas sus imágenes fundidas y derribaréis todos sus lugares altos.",
      "53": "Tomarás posesión de la tierra y habitarás en ella, porque yo te he dado la tierra para que la poseas.",
      "54": "Heredaréis la tierra por sorteo según vuestras familias; a los grupos más numerosos les darás una herencia mayor, y a los más pequeños les darás una herencia menor. Dondequiera que le toque la suerte a un hombre, eso será suyo. Heredaréis según las tribus de vuestros padres. ",
      "55": "“Pero si no expulsas a los habitantes de la tierra de delante de ti, los que dejes que queden de ellos serán como aguijones en tus ojos y espinas en tus costados. Te acosarán en la tierra en la que habitas.",
      "56": "Sucederá que, como pensaba hacerles a ellos, así os haré a vosotros”."
    },
    "34": {
      "1": "Yahvé habló a Moisés, diciendo:",
      "2": "“Manda a los hijos de Israel y diles: ‘Cuando lleguéis a la tierra de Canaán (ésta es la tierra que os corresponderá en herencia, la tierra de Canaán según sus límites),",
      "3": "vuestro límite sur será desde el desierto de Zin a lo largo del lado de Edom, y vuestro límite sur será desde el extremo del Mar Salado hacia el este.",
      "4": "Tu frontera girará hacia el sur de la subida de Akrabbim, y pasará por Zin; y pasará por el sur de Cades Barnea; y de allí irá a Hazar Addar, y pasará por Azmón.",
      "5": "La frontera girará desde Azmón hasta el arroyo de Egipto, y terminará en el mar. ",
      "6": "“‘Para la frontera occidental, tendrás el gran mar y su frontera. Esta será tu frontera occidental. ",
      "7": "“‘Esta será vuestra frontera del norte: desde el gran mar os marcaréis el monte Hor.",
      "8": "Desde el monte Hor marcaréis hasta la entrada de Hamat, y la frontera pasará por Zedad.",
      "9": "Luego la frontera irá hasta Zifrón, y terminará en Hazar Enán. Esta será vuestra frontera norte. ",
      "10": "“‘Marcarás tu frontera oriental desde Hazar Enán hasta Sefam.",
      "11": "La frontera bajará desde Sefam hasta Ribla, al lado oriental de Ain. La frontera descenderá y llegará hasta el lado del mar de Cinneret, hacia el este.",
      "12": "La frontera bajará hasta el Jordán y terminará en el Mar Salado. Esta será tu tierra según sus límites alrededor”. ",
      "13": "Moisés ordenó a los hijos de Israel diciendo: “Esta es la tierra que heredaréis por sorteo, que Yahvé ha ordenado dar a las nueve tribus y a la media tribu;",
      "14": "porque la tribu de los hijos de Rubén según las casas de sus padres, la tribu de los hijos de Gad según las casas de sus padres y la media tribu de Manasés han recibido su herencia.",
      "15": "Las dos tribus y la media tribu han recibido su herencia al otro lado del Jordán, en Jericó, hacia el este, hacia la salida del sol.” ",
      "16": "Yahvé habló a Moisés diciendo:",
      "17": "“Estos son los nombres de los hombres que te repartirán la tierra en herencia El sacerdote Eleazar y Josué, hijo de Nun.",
      "18": "Tomarás un príncipe de cada tribu para repartir la tierra en herencia.",
      "19": "Estos son los nombres de los hombres: De la tribu de Judá, Caleb hijo de Jefone.",
      "20": "De la tribu de los hijos de Simeón, Shemuel hijo de Ammihud.",
      "21": "De la tribu de Benjamín, Elidad hijo de Chislón.",
      "22": "De la tribu de los hijos de Dan, un príncipe, Bukki hijo de Jogli.",
      "23": "De los hijos de José: de la tribu de los hijos de Manasés, un príncipe, Hanniel hijo de Efod.",
      "24": "De la tribu de los hijos de Efraín, un príncipe, Kemuel hijo de Siftán.",
      "25": "De la tribu de los hijos de Zabulón, un príncipe: Elizafán, hijo de Parnac.",
      "26": "De la tribu de los hijos de Isacar, un príncipe: Paltiel, hijo de Azzán.",
      "27": "De la tribu de los hijos de Aser, un príncipe: Ahihud, hijo de Selomi.",
      "28": "De la tribu de los hijos de Neftalí un príncipe, Pedahel hijo de Ammihud”.",
      "29": "Estos son los que Yahvé mandó a repartir la herencia a los hijos de Israel en la tierra de Canaán."
    },
    "35": {
      "1": "Yahvé habló a Moisés en las llanuras de Moab, junto al Jordán, en Jericó, diciendo:",
      "2": "“Ordena a los hijos de Israel que den a los levitas ciudades para que las habiten de su herencia. Darán a los levitas tierras de pastoreo para las ciudades de los alrededores.",
      "3": "Ellos tendrán las ciudades para habitarlas. Sus tierras de pastoreo serán para su ganado, para sus posesiones y para todos sus animales. ",
      "4": "“Las tierras de pastoreo de las ciudades, que darás a los levitas, serán desde el muro de la ciudad y hacia afuera mil codos  alrededor de ella.",
      "5": "Medirás fuera de la ciudad dos mil codos por el lado este, dos mil codos por el lado sur, dos mil codos por el lado oeste y dos mil codos por el lado norte, quedando la ciudad en medio. Estas serán las tierras de pastoreo de sus ciudades. ",
      "6": "“Las ciudades que darás a los levitas serán las seis ciudades de refugio que darás para que huya el homicida. Además de ellas, darás cuarenta y dos ciudades.",
      "7": "Todas las ciudades que darás a los levitas serán cuarenta y ocho ciudades junto con sus tierras de pastoreo.",
      "8": "En cuanto a las ciudades que darás de la posesión de los hijos de Israel, de los muchos tomarás muchos, y de los pocos tomarás pocos. Cada uno, según su herencia, dará parte de sus ciudades a los levitas”.",
      "9": "Yahvé habló a Moisés, diciendo:",
      "10": "“Habla a los hijos de Israel y diles: ‘Cuando paséis el Jordán a la tierra de Canaán,",
      "11": "entonces os designaréis ciudades para que os sirvan de refugio, para que huya allí el homicida que mate a cualquier persona sin saberlo.",
      "12": "Las ciudades os servirán de refugio contra el vengador, para que el homicida no muera hasta que se presente ante la congregación para ser juzgado.",
      "13": "Las ciudades que darás serán para ti seis ciudades de refugio.",
      "14": "Darás tres ciudades al otro lado del Jordán, y darás tres ciudades en la tierra de Canaán. Serán ciudades de refugio.",
      "15": "Estas seis ciudades serán refugio para los hijos de Israel, para el extranjero y para el forastero que viva entre ellos, para que todo el que mate a alguien sin querer huya allí. ",
      "16": "“‘Pero si lo golpeó con un instrumento de hierro, de modo que murió, es un asesino. El asesino será condenado a muerte.",
      "17": "Si lo golpeó con una piedra en la mano, con la que un hombre puede morir, y murió, es un asesino. El homicida será condenado a muerte.",
      "18": "O si lo golpea con un arma de madera en la mano, con la que pueda morir un hombre, y muere, es un asesino. El asesino morirá.",
      "19": "El vengador de la sangre dará muerte al asesino. Cuando lo encuentre, lo matará.",
      "20": "Si lo empujó por odio, o le arrojó algo mientras estaba al acecho, de modo que murió,",
      "21": "o en hostilidad lo golpeó con su mano, de modo que murió, el que lo golpeó ciertamente morirá. Es un asesino. El vengador de la sangre dará muerte al asesino cuando lo encuentre. ",
      "22": "“‘Pero si lo empuja repentinamente sin hostilidad, o arroja sobre él cualquier cosa sin estar al acecho,",
      "23": "o con cualquier piedra, con la que pueda morir un hombre, sin verlo, y la arroja sobre él de modo que muera, y no era su enemigo ni buscaba su daño,",
      "24": "entonces la congregación juzgará entre el agresor y el vengador de la sangre de acuerdo con estas ordenanzas.",
      "25": "La congregación librará al homicida de la mano del vengador de la sangre, y la congregación lo devolverá a su ciudad de refugio, donde había huido. Allí habitará hasta la muerte del sumo sacerdote, que fue ungido con el óleo santo. ",
      "26": "“‘Pero si el homicida sale en algún momento de la frontera de su ciudad de refugio donde huye,",
      "27": "y el vengador de la sangre lo encuentra fuera de la frontera de su ciudad de refugio, y el vengador de la sangre mata al homicida, éste no será culpable de sangre,",
      "28": "porque debería haber permanecido en su ciudad de refugio hasta la muerte del sumo sacerdote. Pero después de la muerte del sumo sacerdote, el homicida regresará a la tierra de su posesión. ",
      "29": "“‘Estas cosas serán para vosotros un estatuto y una ordenanza a lo largo de vuestras generaciones en todas vuestras moradas. ",
      "30": "“‘Cualquiera que mate a una persona, el asesino será asesinado con base en el testimonio de los testigos; pero un solo testigo no declarará contra una persona para que muera. ",
      "31": "“‘Además, no aceptarás ningún rescate por la vida de un asesino que sea culpable de muerte. Será condenado a muerte. ",
      "32": "“‘No tomarás rescate por el que haya huido a su ciudad de refugio, para que vuelva a habitar en la tierra antes de la muerte del sacerdote. ",
      "33": "“‘Así no contaminarás la tierra donde vives; porque la sangre contamina la tierra. No se puede hacer expiación de la tierra por la sangre que se derrama en ella, sino por la sangre del que la derramó.",
      "34": "No contaminarás la tierra que habitas, donde yo habito; porque yo, Yahvé, habito en medio de los hijos de Israel.’”"
    },
    "36": {
      "1": "Los jefes de familia de los hijos de Galaad, hijo de Maquir, hijo de Manasés, de las familias de los hijos de José, se acercaron y hablaron ante Moisés y ante los príncipes, los jefes de familia de los hijos de Israel.",
      "2": "Ellos dijeron: “Yahvé ordenó a mi señor que diera la tierra en herencia por sorteo a los hijos de Israel. Mi señor recibió la orden de Yahvé de dar la herencia de nuestro hermano Zelofehad a sus hijas.",
      "3": "Si ellas se casan con alguno de los hijos de las otras tribus de los hijos de Israel, su herencia se quitará de la herencia de nuestros padres y se añadirá a la herencia de la tribu a la que pertenezcan. Así será quitada de la suerte de nuestra herencia.",
      "4": "Cuando llegue el jubileo de los hijos de Israel, su herencia se añadirá a la de la tribu a la que pertenezcan. Así que su herencia será quitada de la herencia de la tribu de nuestros padres”. ",
      "5": "Moisés ordenó a los hijos de Israel según la palabra de Yahvé, diciendo: “La tribu de los hijos de José dice lo que es justo.",
      "6": "Esto es lo que Yahvé manda con respecto a las hijas de Zelofehad, diciendo: “Que se casen con quien mejor les parezca, sólo que se casarán en la familia de la tribu de su padre.",
      "7": "Así, ninguna herencia de los hijos de Israel pasará de una tribu a otra, pues todos los hijos de Israel conservarán la herencia de la tribu de sus padres.",
      "8": "Toda hija que posea una herencia en cualquier tribu de los hijos de Israel será esposa de uno de la familia de la tribu de su padre, para que los hijos de Israel posean cada uno la herencia de sus padres.",
      "9": "Así, ninguna herencia pasará de una tribu a otra, pues las tribus de los hijos de Israel conservarán cada una su propia herencia”. ",
      "10": "Las hijas de Zelofehad hicieron lo que Yahvé mandó a Moisés:",
      "11": "porque Mahá, Tirsa, Hogá, Milca y Noé, las hijas de Zelofehad, se casaron con los hijos de los hermanos de su padre.",
      "12": "Se casaron con las familias de los hijos de Manasés, hijo de José. Su herencia permaneció en la tribu de la familia de su padre. ",
      "13": "Estos son los mandamientos y las ordenanzas que Yahvé ordenó por medio de Moisés a los hijos de Israel en las llanuras de Moab, junto al Jordán, en Jericó."
    }
  },
  "deuteronomy": {
    "1": {
      "1": "Estas son las palabras que Moisés dirigió a todo Israel al otro lado del Jordán, en el desierto, en el Arabá frente a Suf, entre Parán, Tofel, Labán, Hazerot y Dizahab.",
      "2": "Hay once días de viaje desde Horeb, por el camino del monte Seir, hasta Cades Barnea.",
      "3": "En el año cuarenta, en el mes undécimo, el primer día del mes, Moisés habló a los hijos de Israel según todo lo que Yahvé  le había ordenado,",
      "4": "después de haber herido en Edrei a Sehón, rey de los amorreos que vivía en Hesbón, y a Og, rey de Basán que vivía en Astarot.",
      "5": "Al otro lado del Jordán, en la tierra de Moab, Moisés comenzó a declarar esta ley, diciendo:",
      "6": "“El Señor, nuestro Dios,  nos habló en Horeb, diciendo: ‘Ya habéis vivido bastante en este monte.",
      "7": "Volveos y emprended vuestro viaje, e id a la región montañosa de los amorreos y a todos los lugares cercanos a ella: en el Arabá, en la región montañosa, en la llanura, en el sur, a la orilla del mar, en la tierra de los cananeos y en el Líbano hasta el gran río, el río Éufrates.",
      "8": "He aquí que  he puesto la tierra delante de ti. Entrad y poseed la tierra que Yahvé juró a vuestros padres — a Abraham, a Isaac y a Jacob — para dársela a ellos y a su descendencia  después de ellos”. ",
      "9": "En aquel tiempo te hablé diciendo: “No puedo soportarte yo solo.",
      "10": "Yahvé, vuestro Dios, os ha multiplicado, y he aquí que sois hoy como las estrellas del cielo por la multitud.",
      "11": "¡Que Yavé, el Dios de tus padres, te haga mil veces más numerosa y te bendiga, como te ha prometido!",
      "12": "¿Cómo podré soportar yo solo vuestros problemas, vuestras cargas y vuestras luchas?",
      "13": "Toma a hombres sabios y entendidos que sean respetados entre tus tribus, y los haré jefes sobre ti”. ",
      "14": "Tú me respondiste y dijiste: “Lo que has dicho es bueno hacerlo”.",
      "15": "Así que tomé a los jefes de vuestras tribus, hombres sabios y respetados, y los nombré jefes sobre vosotros, capitanes de millares, capitanes de centenas, capitanes de cincuenta, capitanes de decenas y oficiales, según vuestras tribus.",
      "16": "En aquel tiempo ordené a vuestros jueces, diciendo: “Oíd los casos entre vuestros hermanos y juzgad con justicia entre un hombre y su hermano, y el extranjero que vive con él.",
      "17": "No mostrarás parcialidad en el juicio; escucharás por igual al pequeño y al grande. No temerás el rostro del hombre, porque el juicio es de Dios. El caso que sea demasiado duro para ti, lo traerás a mí, y yo lo escucharé”.",
      "18": "En aquel momento os ordené todo lo que debíais hacer.",
      "19": "Salimos de Horeb y atravesamos todo ese desierto grande y terrible que ustedes vieron, por el camino de la región montañosa de los amorreos, como nos lo ordenó el Señor, nuestro Dios, y llegamos a Cades Barnea.",
      "20": "Os dije: “Habéis llegado a la región montañosa de los amorreos, que el Señor nuestro Dios nos da.",
      "21": "He aquí que el Señor, vuestro Dios, ha puesto la tierra delante de vosotros. Subid y tomad posesión, como os ha dicho el Señor, el Dios de vuestros padres. No tengas miedo ni te acobardes”. ",
      "22": "Os acercasteis a mí, todos vosotros, y dijisteis: “Enviemos hombres delante de nosotros, para que nos busquen por la tierra y nos traigan la noticia del camino por el que debemos subir y de las ciudades a las que debemos llegar.” ",
      "23": "El asunto me agradó. Tomé doce de tus hombres, un hombre por cada tribu.",
      "24": "Se volvieron y subieron a la región montañosa, y llegaron al valle de Escol y lo exploraron.",
      "25": "Tomaron en sus manos parte del fruto de la tierra y nos lo trajeron, y nos volvieron a avisar diciendo: “Es una buena tierra la que nos da el Señor, nuestro Dios.” ",
      "26": "Pero no quisisteis subir, sino que os rebelasteis contra el mandamiento del Señor, vuestro Dios.",
      "27": "Murmurabais en vuestras tiendas y decíais: “Porque Yahvé nos odiaba, nos ha sacado de la tierra de Egipto para entregarnos en manos de los amorreos para que nos destruyan.",
      "28": "¿Adónde vamos a subir? Nuestros hermanos han hecho que nuestro corazón se derrita, diciendo: ‘Los pueblos son más grandes y más altos que nosotros. Las ciudades son grandes y están fortificadas hasta el cielo. Además, hemos visto allí a los hijos de los anakim’”. ",
      "29": "Entonces les dije: “No se asusten. No les tengas miedo.",
      "30": "Yahvé tu Dios, que va delante de ti, luchará por ti, según todo lo que hizo por ti en Egipto ante tus ojos,",
      "31": "y en el desierto, donde has visto cómo Yahvé tu Dios te llevaba, como un hombre lleva a su hijo, en todo el camino que recorriste, hasta que llegaste a este lugar.” ",
      "32": "Pero en esto no creísteis a Yahvé, vuestro Dios,",
      "33": "que iba delante de vosotros en el camino, para buscaros un lugar donde acampar: en el fuego de noche, para mostraros por qué camino debíais ir, y en la nube de día.",
      "34": "Yahvé oyó la voz de vuestras palabras y se enojó, y juró diciendo:",
      "35": "“Ciertamente ninguno de estos hombres de esta mala generación verá la buena tierra que juré dar a vuestros padres,",
      "36": "excepto Caleb hijo de Jefone. Él la verá. Le daré la tierra que ha pisado a él y a sus hijos, porque ha seguido enteramente a Yahvé”. ",
      "37": "También el Señor se enojó conmigo por causa de ustedes, diciendo: “Tú tampoco entrarás allí.",
      "38": "Josué, hijo de Nun, que está delante de ti, entrará allí. Anímalo, porque él hará que Israel la herede.",
      "39": "Además, tus pequeños, que dijiste que serían capturados o asesinados, tus hijos, que hoy no tienen conocimiento del bien ni del mal, entrarán allí. Yo se la daré, y ellos la poseerán.",
      "40": "Pero en cuanto a ti, vuélvete y emprende tu viaje al desierto por el camino del Mar Rojo”. ",
      "41": "Entonces respondisteis y me dijisteis: “Hemos pecado contra Yahvé. Subiremos a pelear, conforme a todo lo que nos ordenó el Señor, nuestro Dios”. Cada uno de ustedes se vistió con sus armas de guerra y se dispuso a subir a la región montañosa. ",
      "42": "El Señor me dijo: “Diles que no suban y que no peleen, porque yo no estoy en medio de ustedes, para que no sean golpeados ante sus enemigos”. ",
      "43": "Así que os hablé, y no me escuchasteis, sino que os rebelasteis contra el mandamiento del Señor, y fuisteis presuntuosos, y subisteis a la región montañosa.",
      "44": "Los amorreos, que vivían en esa región montañosa, salieron contra ti y te persiguieron como lo hacen las abejas, y te derribaron en Seir, hasta Horma.",
      "45": "Volvisteis y llorasteis delante de Yavé, pero Yavé no escuchó vuestra voz, ni volvió su oído hacia vosotros.",
      "46": "Así que permaneciste en Cades muchos días, según los días que permaneciste."
    },
    "2": {
      "1": "Luego nos volvimos y emprendimos la marcha hacia el desierto por el camino del Mar Rojo, como me había dicho Yahvé; y rodeamos el monte Seir durante muchos días. ",
      "2": "Yahvé me habló diciendo:",
      "3": "“Ya has rodeado bastante este monte. Vuélvete hacia el norte.",
      "4": "Ordena al pueblo que diga: ‘Vas a pasar por la frontera de tus hermanos, los hijos de Esaú, que habitan en Seír; y ellos tendrán miedo de ti. Tened, pues, cuidado.",
      "5": "No contendáis con ellos, porque no os daré nada de su tierra, ni siquiera para que la pise la planta del pie, porque he dado el monte Seir a Esaú como posesión.",
      "6": "Les comprarás alimentos por dinero, para que puedas comer. También les comprarás agua por dinero, para que puedas beber’”. ",
      "7": "Porque el Señor, tu Dios, te ha bendecido en toda la obra de tus manos. Él ha conocido tu caminar por este gran desierto. Estos cuarenta años, el Señor tu Dios ha estado contigo. Nada te ha faltado. ",
      "8": "Así pasamos de nuestros hermanos, los hijos de Esaú, que habitan en Seir, por el camino del Arabá, desde Elat y desde Ezión Geber. Nos volvimos y pasamos por el camino del desierto de Moab. ",
      "9": "El Señor me dijo: “No molestes a Moab, ni te enfrentes a ellos en la batalla, porque no te daré nada de su tierra en posesión, ya que he dado Ar a los hijos de Lot en posesión.” ",
      "10": "(Los Emim vivían allí antes, un pueblo grande y numeroso, y alto como los Anakim.",
      "11": "Estos también se consideran refaítas, como los anakim; pero los moabitas los llaman emim.",
      "12": "Los horeos también vivieron en Seir en el pasado, pero los hijos de Esaú los sucedieron. Los destruyeron de delante de ellos y vivieron en su lugar, como hizo Israel con la tierra de su posesión, que Yahvé les dio). ",
      "13": "“Ahora levántate y cruza el arroyo Zered”. Pasamos por el arroyo Zered. ",
      "14": "Los días en que salimos de Cades Barnea hasta que pasamos el arroyo de Zered fueron treinta y ocho años, hasta que toda la generación de los hombres de guerra fue consumida desde la mitad del campamento, como se lo había jurado el Señor.",
      "15": "Además, la mano de Yahvé estaba contra ellos, para destruirlos desde la mitad del campamento, hasta que fueran consumidos.",
      "16": "Entonces, cuando todos los hombres de guerra fueron consumidos y muertos de entre el pueblo,",
      "17": "el Señor me habló diciendo:",
      "18": "“Hoy debes pasar por Ar, la frontera de Moab.",
      "19": "Cuando te acerques a la frontera de los hijos de Amón, no los molestes ni contiendas con ellos, porque no te daré nada de la tierra de los hijos de Amón en posesión, porque se la he dado a los hijos de Lot en posesión.” ",
      "20": "(Eso también se considera tierra de refaítas. Los refaim vivían allí en el pasado, pero los amonitas los llaman zamzummim,",
      "21": "un pueblo grande, numeroso y alto, como los anakim; pero Yahvé los destruyó de delante de Israel, y los sucedieron y vivieron en su lugar,",
      "22": "como hizo con los hijos de Esaú que habitan en Seir, cuando destruyó a los horeos de delante de ellos; y los sucedieron y vivieron en su lugar hasta el día de hoy.",
      "23": "Luego los avvim, que vivían en aldeas hasta Gaza: los caphtorim, que salieron de Caphtor, los destruyeron y vivieron en su lugar). ",
      "24": "“Levántate, emprende tu viaje y pasa por el valle de Arnón. He aquí que he entregado en tu mano a Sehón el amorreo, rey de Hesbón, y a su tierra; comienza a poseerla, y enfréntate a él en la batalla.",
      "25": "Hoy comenzaré a infundir tu temor y tu miedo a los pueblos que están bajo todo el cielo, que oirán la noticia de ti y temblarán y se angustiarán por tu causa.” ",
      "26": "Envié mensajeros desde el desierto de Cedemot a Sehón, rey de Hesbón, con palabras de paz, diciendo:",
      "27": "“Déjame pasar por tu tierra. Iré por el camino. No me desviaré ni a la derecha ni a la izquierda.",
      "28": "Me venderás comida por dinero, para que coma; y me darás agua por dinero, para que beba. Sólo déjenme pasar sobre mis pies,",
      "29": "como lo hicieron conmigo los hijos de Esaú que habitan en Seír, y los moabitas que habitan en Ar, hasta que pase el Jordán a la tierra que el Señor, nuestro Dios, nos da.”",
      "30": "Pero Sehón, rey de Hesbón, no nos dejó pasar, porque el Señor, tu Dios, endureció su espíritu e hizo que su corazón se obstinara, para entregarlo en tu mano, como sucede hoy. ",
      "31": "El Señor me dijo: “He aquí que he comenzado a entregar a Sehón y su tierra delante de ti. Comienza a poseer, para que heredes su tierra”.",
      "32": "Entonces Sijón salió contra nosotros, él y todo su pueblo, para combatir en Jahaz.",
      "33": "El Señor, nuestro Dios, lo entregó ante nosotros, y lo golpeamos a él, a sus hijos y a todo su pueblo.",
      "34": "En ese momento tomamos todas sus ciudades, y destruimos por completo todas las ciudades habitadas, con las mujeres y los niños. No dejamos a nadie en pie.",
      "35": "Sólo tomamos el ganado como botín para nosotros, con el saqueo de las ciudades que habíamos tomado.",
      "36": "Desde Aroer, que está al borde del valle de Arnón, y la ciudad que está en el valle, hasta Galaad, no hubo ciudad demasiado alta para nosotros. El Señor, nuestro Dios, lo entregó todo ante nosotros.",
      "37": "Sólo a la tierra de los hijos de Amón no os acercasteis: a todas las riberas del río Jaboc y a las ciudades de la región montañosa, y a todo lo que el Señor, nuestro Dios, nos prohibió."
    }
  }
};

