#!/bin/bash

IN_DIR="../txt_tabs"
OUT_DIR="."
SLQ_FILE="./get_BIB_tab.sql3"

fin=${IN_DIR}/${1}_txt.tab
fout=${OUT_DIR}/${1}_bib.tab

echo "Generating "${fout}" from "${fin}

cp ${fin} in.tab
sed -i 's/:/|/g' in.tab

rm ${fout}
rm out.tab
sqlite3 < ${SLQ_FILE}
mv out.tab ${fout}
rm in.tab

