#!/bin/bash

CURR_DIR=$(pwd)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "UPDATING FROM MAKE "${BASH_SOURCE[0]}

cd $SCRIPT_DIR

cp ../../doc/web/nav3_todacarne.mustache ./nav_todacarne.mustache
cp ../../doc/web/text3_todacarne.mustache ./text_todacarne.mustache

cd ${CURR_DIR}
