#!/bin/bash

CURR_DIR=$(pwd)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "GENERATING nav_js "${BASH_SOURCE[0]}

cd $SCRIPT_DIR

SRC_DIR=${1}
BOOK_NAM=${2}
LANG=${3}

echo "GENERATING "${SRC_DIR}/text2_${BOOK_NAM}.mustache

node rm_top_info.js ${LANG} ${SRC_DIR}/text1_${BOOK_NAM}.mustache ${SRC_DIR}/text2_${BOOK_NAM}.mustache

cd ${CURR_DIR}
