
	
export const bib_verses = {
  "songs": {
    "4": {
      "1": "Behold, you are beautiful, my love.   Behold, you are beautiful.   Your eyes are like doves behind your veil.   Your hair is as a flock of goats,   that descend from Mount Gilead. ",
      "2": "  Your teeth are like a newly shorn flock,   which have come up from the washing,   where every one of them has twins.   None is bereaved among them. ",
      "3": "  Your lips are like scarlet thread.   Your mouth is lovely.   Your temples are like a piece of a pomegranate behind your veil. ",
      "4": "  Your neck is like David’s tower built for an armory,   on which a thousand shields hang,   all the shields of the mighty men. ",
      "5": "  Your two breasts are like two fawns   that are twins of a roe,   which feed among the lilies. ",
      "6": "  Until the day is cool, and the shadows flee away,   I will go to the mountain of myrrh,   to the hill of frankincense. ",
      "7": "  You are all beautiful, my love.   There is no spot in you. ",
      "8": "  Come with me from Lebanon, my bride,   with me from Lebanon.   Look from the top of Amana,   from the top of Senir and Hermon,   from the lions’ dens,   from the mountains of the leopards. ",
      "9": "  You have ravished my heart, my sister, my bride.   You have ravished my heart with one of your eyes,   with one chain of your neck. ",
      "10": "  How beautiful is your love, my sister, my bride!   How much better is your love than wine,   the fragrance of your perfumes than all kinds of spices! ",
      "11": "  Your lips, my bride, drip like the honeycomb.   Honey and milk are under your tongue.   The smell of your garments is like the smell of Lebanon. ",
      "12": "  My sister, my bride, is a locked up garden;   a locked up spring,   a sealed fountain. ",
      "13": "  Your shoots are an orchard of pomegranates, with precious fruits,   henna with spikenard plants, ",
      "14": "  spikenard and saffron,   calamus and cinnamon, with every kind of incense tree;   myrrh and aloes, with all the best spices, ",
      "15": "  a fountain of gardens,   a well of living waters,   flowing streams from Lebanon. ",
      "16": "   Awake, north wind, and come, you south!   Blow on my garden, that its spices may flow out.   Let my beloved come into his garden,   and taste his precious fruits."
    },
    "5": {
      "1": "  I have come into my garden, my sister, my bride.   I have gathered my myrrh with my spice;   I have eaten my honeycomb with my honey;   I have drunk my wine with my milk.     Eat, friends!   Drink, yes, drink abundantly, beloved. ",
      "2": "   I was asleep, but my heart was awake.   It is the voice of my beloved who knocks:   “Open to me, my sister, my love, my dove, my undefiled;   for my head is filled with dew,   and my hair with the dampness of the night.” ",
      "3": "  I have taken off my robe. Indeed, must I put it on?   I have washed my feet. Indeed, must I soil them? ",
      "4": "  My beloved thrust his hand in through the latch opening.   My heart pounded for him. ",
      "5": "  I rose up to open for my beloved.   My hands dripped with myrrh,   my fingers with liquid myrrh,   on the handles of the lock. ",
      "6": "  I opened to my beloved;   but my beloved left, and had gone away.   My heart went out when he spoke.   I looked for him, but I didn’t find him.   I called him, but he didn’t answer. ",
      "7": "  The watchmen who go about the city found me.   They beat me.   They bruised me.   The keepers of the walls took my cloak away from me. ",
      "8": "  I adjure you, daughters of Jerusalem,   If you find my beloved,   that you tell him that I am faint with love. ",
      "9": "   How is your beloved better than another beloved,   you fairest among women?   How is your beloved better than another beloved,   that you do so adjure us? ",
      "10": "   My beloved is white and ruddy.   The best among ten thousand. ",
      "11": "  His head is like the purest gold.   His hair is bushy, black as a raven. ",
      "12": "  His eyes are like doves beside the water brooks,   washed with milk, mounted like jewels. ",
      "13": "  His cheeks are like a bed of spices with towers of perfumes.   His lips are like lilies, dropping liquid myrrh. ",
      "14": "  His hands are like rings of gold set with beryl.   His body is like ivory work overlaid with sapphires. ",
      "15": "  His legs are like pillars of marble set on sockets of fine gold.   His appearance is like Lebanon, excellent as the cedars. ",
      "16": "  His mouth is sweetness;   yes, he is altogether lovely.   This is my beloved, and this is my friend,   daughters of Jerusalem."
    },
    "6": {
      "1": "  Where has your beloved gone, you fairest among women?   Where has your beloved turned, that we may seek him with you? ",
      "2": "   My beloved has gone down to his garden,   to the beds of spices,   to pasture his flock in the gardens, and to gather lilies. ",
      "3": "  I am my beloved’s, and my beloved is mine.   He browses among the lilies. ",
      "4": "   You are beautiful, my love, as Tirzah,   lovely as Jerusalem,   awesome as an army with banners. ",
      "5": "  Turn away your eyes from me,   for they have overcome me.   Your hair is like a flock of goats,   that lie along the side of Gilead. ",
      "6": "  Your teeth are like a flock of ewes,   which have come up from the washing,   of which every one has twins;   not one is bereaved among them. ",
      "7": "  Your temples are like a piece of a pomegranate behind your veil. ",
      "8": "  There are sixty queens, eighty concubines,   and virgins without number. ",
      "9": "  My dove, my perfect one, is unique.   She is her mother’s only daughter.   She is the favorite one of her who bore her.   The daughters saw her, and called her blessed.   The queens and the concubines saw her, and they praised her. ",
      "10": "  Who is she who looks out as the morning,   beautiful as the moon,   clear as the sun,   and awesome as an army with banners? ",
      "11": "  I went down into the nut tree grove,   to see the green plants of the valley,   to see whether the vine budded,   and the pomegranates were in flower. ",
      "12": "  Without realizing it,   my desire set me with my royal people’s chariots. ",
      "13": "   Return, return, Shulammite!   Return, return, that we may gaze at you.     Why do you desire to gaze at the Shulammite,   as at the dance of Mahanaim?"
    },
    "7": {
      "1": "How beautiful are your feet in sandals, prince’s daughter!   Your rounded thighs are like jewels,   the work of the hands of a skillful workman. ",
      "2": "  Your body is like a round goblet,   no mixed wine is wanting.   Your waist is like a heap of wheat,   set about with lilies. ",
      "3": "  Your two breasts are like two fawns,   that are twins of a roe. ",
      "4": "  Your neck is like an ivory tower.   Your eyes are like the pools in Heshbon by the gate of Bathrabbim.   Your nose is like the tower of Lebanon which looks toward Damascus. ",
      "5": "  Your head on you is like Carmel.   The hair of your head like purple.   The king is held captive in its tresses. ",
      "6": "  How beautiful and how pleasant you are,   love, for delights! ",
      "7": "  This, your stature, is like a palm tree,   your breasts like its fruit. ",
      "8": "  I said, “I will climb up into the palm tree.   I will take hold of its fruit.”   Let your breasts be like clusters of the vine,   the smell of your breath like apples. ",
      "9": "  Your mouth is like the best wine,   that goes down smoothly for my beloved,   gliding through the lips of those who are asleep. ",
      "10": "   I am my beloved’s.   His desire is toward me. ",
      "11": "  Come, my beloved! Let’s go out into the field.   Let’s lodge in the villages. ",
      "12": "  Let’s go early up to the vineyards.   Let’s see whether the vine has budded,   its blossom is open,   and the pomegranates are in flower.   There I will give you my love. ",
      "13": "  The mandrakes produce fragrance.   At our doors are all kinds of precious fruits, new and old,   which I have stored up for you, my beloved."
    },
    "8": {
      "1": "Oh that you were like my brother,   who nursed from the breasts of my mother!   If I found you outside, I would kiss you;   yes, and no one would despise me. ",
      "2": "  I would lead you, bringing you into the house of my mother,   who would instruct me.   I would have you drink spiced wine,   of the juice of my pomegranate. ",
      "3": "  His left hand would be under my head.   His right hand would embrace me. ",
      "4": "  I adjure you, daughters of Jerusalem,   that you not stir up, nor awaken love,   until it so desires. ",
      "5": "   Who is this who comes up from the wilderness,   leaning on her beloved?      Under the apple tree I awakened you.   There your mother conceived you.   There she was in labor and bore you. ",
      "6": "  Set me as a seal on your heart,   as a seal on your arm;   for love is strong as death.   Jealousy is as cruel as Sheol.    Its flashes are flashes of fire,   a very flame of Yah.  ",
      "7": "  Many waters can’t quench love,   neither can floods drown it.   If a man would give all the wealth of his house for love,   he would be utterly scorned. ",
      "8": "   We have a little sister.   She has no breasts.   What shall we do for our sister   in the day when she is to be spoken for? ",
      "9": "  If she is a wall,   we will build on her a turret of silver.   If she is a door,   we will enclose her with boards of cedar. ",
      "10": "   I am a wall, and my breasts like towers,   then I was in his eyes like one who found peace. ",
      "11": "  Solomon had a vineyard at Baal Hamon.   He leased out the vineyard to keepers.   Each was to bring a thousand shekels  of silver for its fruit. ",
      "12": "  My own vineyard is before me.   The thousand are for you, Solomon,   two hundred for those who tend its fruit. ",
      "13": "   You who dwell in the gardens, with friends in attendance,   let me hear your voice! ",
      "14": "   Come away, my beloved!   Be like a gazelle or a young stag on the mountains of spices!"
    }
  },
  "isaiah": {
    "1": {
      "1": "The vision of Isaiah the son of Amoz, which he saw concerning Judah and Jerusalem, in the days of Uzziah, Jotham, Ahaz, and Hezekiah, kings of Judah. ",
      "2": "  Hear, heavens,   and listen, earth; for Yahweh  has spoken:   “I have nourished and brought up children   and they have rebelled against me. ",
      "3": "  The ox knows his owner,   and the donkey his master’s crib;   but Israel doesn’t know.   My people don’t consider.” ",
      "4": "  Ah sinful nation,   a people loaded with iniquity,   offspring  of evildoers,   children who deal corruptly!   They have forsaken Yahweh.   They have despised the Holy One of Israel.   They are estranged and backward. ",
      "5": "  Why should you be beaten more,   that you revolt more and more?   The whole head is sick,   and the whole heart faint. ",
      "6": "  From the sole of the foot even to the head there is no soundness in it,   but wounds, welts, and open sores.   They haven’t been closed, bandaged, or soothed with oil. ",
      "7": "  Your country is desolate.   Your cities are burned with fire.   Strangers devour your land in your presence   and it is desolate,   as overthrown by strangers. ",
      "8": "  The daughter of Zion is left like a shelter in a vineyard,   like a hut in a field of melons,   like a besieged city. ",
      "9": "  Unless Yahweh of Armies had left to us a very small remnant,   we would have been as Sodom.   We would have been like Gomorrah. ",
      "10": "  Hear Yahweh’s word, you rulers of Sodom!   Listen to the law of our God,  you people of Gomorrah! ",
      "11": "  “What are the multitude of your sacrifices to me?”, says Yahweh.   “I have had enough of the burnt offerings of rams   and the fat of fed animals.   I don’t delight in the blood of bulls,   or of lambs,   or of male goats. ",
      "12": "  When you come to appear before me,   who has required this at your hand, to trample my courts? ",
      "13": "  Bring no more vain offerings.   Incense is an abomination to me.   New moons, Sabbaths, and convocations—   I can’t stand evil assemblies. ",
      "14": "  My soul hates your New Moons and your appointed feasts.   They are a burden to me.   I am weary of bearing them. ",
      "15": "  When you spread out your hands, I will hide my eyes from you.   Yes, when you make many prayers, I will not hear.   Your hands are full of blood. ",
      "16": "  Wash yourselves. Make yourself clean.   Put away the evil of your doings from before my eyes.   Cease to do evil. ",
      "17": "  Learn to do well.   Seek justice.   Relieve the oppressed.   Defend the fatherless.   Plead for the widow.” ",
      "18": "  “Come now, and let’s reason together,” says Yahweh:   “Though your sins are as scarlet, they shall be as white as snow.   Though they are red like crimson, they shall be as wool. ",
      "19": "  If you are willing and obedient,   you will eat the good of the land; ",
      "20": "  but if you refuse and rebel, you will be devoured with the sword;   for Yahweh’s mouth has spoken it.” ",
      "21": "  How the faithful city has become a prostitute!   She was full of justice.   Righteousness lodged in her,   but now there are murderers. ",
      "22": "  Your silver has become dross,   your wine mixed with water. ",
      "23": "  Your princes are rebellious and companions of thieves.   Everyone loves bribes and follows after rewards.   They don’t defend the fatherless,   neither does the cause of the widow come to them. ",
      "24": "  Therefore the Lord,  Yahweh of Armies,   the Mighty One of Israel, says:   “Ah, I will get relief from my adversaries,   and avenge myself on my enemies. ",
      "25": "  I will turn my hand on you,   thoroughly purge away your dross,   and will take away all your tin.  ",
      "26": "  I will restore your judges as at the first,   and your counselors as at the beginning.   Afterward you shall be called ‘The city of righteousness,   a faithful town.’ ",
      "27": "  Zion shall be redeemed with justice,   and her converts with righteousness. ",
      "28": "  But the destruction of transgressors and sinners shall be together,   and those who forsake Yahweh shall be consumed. ",
      "29": "  For they shall be ashamed of the oaks which you have desired,   and you shall be confounded for the gardens that you have chosen. ",
      "30": "  For you shall be as an oak whose leaf fades,   and as a garden that has no water. ",
      "31": "  The strong will be like tinder,   and his work like a spark.   They will both burn together,   and no one will quench them.”"
    },
    "2": {
      "1": "This is what Isaiah the son of Amoz saw concerning Judah and Jerusalem. ",
      "2": "  It shall happen in the latter days, that the mountain of Yahweh’s house shall be established on the top of the mountains,   and shall be raised above the hills;   and all nations shall flow to it. ",
      "3": "  Many peoples shall go and say,   “Come, let’s go up to the mountain of Yahweh,   to the house of the God of Jacob;   and he will teach us of his ways,   and we will walk in his paths.”   For the law shall go out of Zion,   and Yahweh’s word from Jerusalem. ",
      "4": "  He will judge between the nations,   and will decide concerning many peoples.   They shall beat their swords into plowshares,   and their spears into pruning hooks.   Nation shall not lift up sword against nation,   neither shall they learn war any more. ",
      "5": "  House of Jacob, come, and let’s walk in the light of Yahweh. ",
      "6": "  For you have forsaken your people, the house of Jacob,   because they are filled from the east,   with those who practice divination like the Philistines,   and they clasp hands with the children of foreigners. ",
      "7": "  Their land is full of silver and gold,   neither is there any end of their treasures.   Their land also is full of horses,   neither is there any end of their chariots. ",
      "8": "  Their land also is full of idols.   They worship the work of their own hands,   that which their own fingers have made. ",
      "9": "  Man is brought low,   and mankind is humbled;   therefore don’t forgive them. ",
      "10": "  Enter into the rock,   and hide in the dust,   from before the terror of Yahweh,   and from the glory of his majesty. ",
      "11": "  The lofty looks of man will be brought low,   the arrogance of men will be bowed down,   and Yahweh alone will be exalted in that day. ",
      "12": "  For there will be a day of Yahweh of Armies for all that is proud and arrogant,   and for all that is lifted up,   and it shall be brought low— ",
      "13": "  for all the cedars of Lebanon, that are high and lifted up,   for all the oaks of Bashan, ",
      "14": "  for all the high mountains,   for all the hills that are lifted up, ",
      "15": "  for every lofty tower,   for every fortified wall, ",
      "16": "  for all the ships of Tarshish,   and for all pleasant imagery. ",
      "17": "  The loftiness of man shall be bowed down,   and the arrogance of men shall be brought low;   and Yahweh alone shall be exalted in that day. ",
      "18": "  The idols shall utterly pass away. ",
      "19": "  Men shall go into the caves of the rocks,   and into the holes of the earth,   from before the terror of Yahweh,   and from the glory of his majesty,   when he arises to shake the earth mightily. ",
      "20": "  In that day, men shall cast away their idols of silver   and their idols of gold,   which have been made for themselves to worship,   to the moles and to the bats, ",
      "21": "  to go into the caverns of the rocks,   and into the clefts of the ragged rocks,   from before the terror of Yahweh,   and from the glory of his majesty,   when he arises to shake the earth mightily. ",
      "22": "  Stop trusting in man, whose breath is in his nostrils;   for of what account is he?"
    },
    "3": {
      "1": "  For, behold,  the Lord, Yahweh of Armies, takes away from Jerusalem and from Judah supply and support,   the whole supply of bread,   and the whole supply of water; ",
      "2": "  the mighty man,   the man of war,   the judge,   the prophet,   the diviner,   the elder, ",
      "3": "  the captain of fifty,   the honorable man,   the counselor,   the skilled craftsman,   and the clever enchanter. ",
      "4": "  I will give boys to be their princes,   and children shall rule over them. ",
      "5": "  The people will be oppressed,   everyone by another,   and everyone by his neighbor.   The child will behave himself proudly against the old man,   and the wicked against the honorable. ",
      "6": "  Indeed a man shall take hold of his brother in the house of his father, saying,   “You have clothing, you be our ruler,   and let this ruin be under your hand.” ",
      "7": "  In that day he will cry out, saying, “I will not be a healer;   for in my house is neither bread nor clothing.   You shall not make me ruler of the people.” ",
      "8": "  For Jerusalem is ruined, and Judah is fallen;   because their tongue and their doings are against Yahweh,   to provoke the eyes of his glory. ",
      "9": "  The look of their faces testify against them.   They parade their sin like Sodom.   They don’t hide it.   Woe to their soul!   For they have brought disaster upon themselves. ",
      "10": "  Tell the righteous that it will be well with them,   for they will eat the fruit of their deeds. ",
      "11": "  Woe to the wicked!   Disaster is upon them,   for the deeds of their hands will be paid back to them. ",
      "12": "  As for my people, children are their oppressors,   and women rule over them.   My people, those who lead you cause you to err,   and destroy the way of your paths. ",
      "13": "  Yahweh stands up to contend,   and stands to judge the peoples. ",
      "14": "  Yahweh will enter into judgment with the elders of his people   and their leaders:   “It is you who have eaten up the vineyard.   The plunder of the poor is in your houses. ",
      "15": "  What do you mean that you crush my people,   and grind the face of the poor?” says the Lord, Yahweh of Armies. ",
      "16": "  Moreover Yahweh said, “Because the daughters of Zion are arrogant,   and walk with outstretched necks and flirting eyes,   walking daintily as they go,   jingling ornaments on their feet; ",
      "17": "  therefore the Lord brings sores on the crown of the head of the women of Zion,   and Yahweh will make their scalps bald.” ",
      "18": "In that day the Lord will take away the beauty of their anklets, the headbands, the crescent necklaces,",
      "19": "the earrings, the bracelets, the veils,",
      "20": "the headdresses, the ankle chains, the sashes, the perfume containers, the charms,",
      "21": "the signet rings, the nose rings,",
      "22": "the fine robes, the capes, the cloaks, the purses,",
      "23": "the hand mirrors, the fine linen garments, the tiaras, and the shawls. ",
      "24": "  It shall happen that instead of sweet spices, there shall be rottenness;   instead of a belt, a rope;   instead of well set hair, baldness;   instead of a robe, a wearing of sackcloth;   and branding instead of beauty. ",
      "25": "  Your men shall fall by the sword,   and your mighty in the war. ",
      "26": "  Her gates shall lament and mourn.   She shall be desolate and sit on the ground."
    },
    "4": {
      "1": "Seven women shall take hold of one man in that day, saying, “We will eat our own bread, and wear our own clothing. Just let us be called by your name. Take away our reproach.” ",
      "2": "In that day, Yahweh’s branch will be beautiful and glorious, and the fruit of the land will be the beauty and glory of the survivors of Israel.",
      "3": "It will happen that he who is left in Zion and he who remains in Jerusalem shall be called holy, even everyone who is written among the living in Jerusalem,",
      "4": "when the Lord shall have washed away the filth of the daughters of Zion, and shall have purged the blood of Jerusalem from within it, by the spirit of justice and by the spirit of burning.",
      "5": "Yahweh will create over the whole habitation of Mount Zion and over her assemblies, a cloud and smoke by day, and the shining of a flaming fire by night, for over all the glory will be a canopy.",
      "6": "There will be a pavilion for a shade in the daytime from the heat, and for a refuge and for a shelter from storm and from rain."
    },
    "5": {
      "1": "  Let me sing for my well beloved a song of my beloved about his vineyard.   My beloved had a vineyard on a very fruitful hill. ",
      "2": "  He dug it up,   gathered out its stones,   planted it with the choicest vine,   built a tower in the middle of it,   and also cut out a wine press in it.   He looked for it to yield grapes,   but it yielded wild grapes. ",
      "3": "  “Now, inhabitants of Jerusalem and men of Judah,   please judge between me and my vineyard. ",
      "4": "  What could have been done more to my vineyard, that I have not done in it?   Why, when I looked for it to yield grapes, did it yield wild grapes? ",
      "5": "  Now I will tell you what I will do to my vineyard.   I will take away its hedge, and it will be eaten up.   I will break down its wall, and it will be trampled down. ",
      "6": "  I will lay it a wasteland.   It won’t be pruned or hoed,   but it will grow briers and thorns.   I will also command the clouds that they rain no rain on it.” ",
      "7": "  For the vineyard of Yahweh of Armies is the house of Israel,   and the men of Judah his pleasant plant.   He looked for justice, but behold, oppression,   for righteousness, but behold, a cry of distress. ",
      "8": "  Woe to those who join house to house,   who lay field to field, until there is no room,   and you are made to dwell alone in the middle of the land! ",
      "9": "  In my ears, Yahweh of Armies says: “Surely many houses will be desolate,   even great and beautiful, unoccupied. ",
      "10": "  For ten acres  of vineyard shall yield one bath,    and a homer  of seed shall yield an ephah.”  ",
      "11": "  Woe to those who rise up early in the morning, that they may follow strong drink,   who stay late into the night, until wine inflames them! ",
      "12": "  The harp, lyre, tambourine, and flute, with wine, are at their feasts;   but they don’t respect the work of Yahweh,   neither have they considered the operation of his hands. ",
      "13": "  Therefore my people go into captivity for lack of knowledge.   Their honorable men are famished,   and their multitudes are parched with thirst. ",
      "14": "  Therefore Sheol  has enlarged its desire,   and opened its mouth without measure;   and their glory, their multitude, their pomp, and he who rejoices among them, descend into it. ",
      "15": "  So man is brought low,   mankind is humbled,   and the eyes of the arrogant ones are humbled; ",
      "16": "  but Yahweh of Armies is exalted in justice,   and God the Holy One is sanctified in righteousness. ",
      "17": "  Then the lambs will graze as in their pasture,   and strangers will eat the ruins of the rich. ",
      "18": "  Woe to those who draw iniquity with cords of falsehood,   and wickedness as with cart rope, ",
      "19": "  who say, “Let him make haste, let him hasten his work, that we may see it;   let the counsel of the Holy One of Israel draw near and come,   that we may know it!” ",
      "20": "  Woe to those who call evil good, and good evil;   who put darkness for light,   and light for darkness;   who put bitter for sweet,   and sweet for bitter! ",
      "21": "  Woe to those who are wise in their own eyes,   and prudent in their own sight! ",
      "22": "  Woe to those who are mighty to drink wine,   and champions at mixing strong drink; ",
      "23": "  who acquit the guilty for a bribe,   but deny justice for the innocent! ",
      "24": "  Therefore as the tongue of fire devours the stubble,   and as the dry grass sinks down in the flame,   so their root shall be as rottenness,   and their blossom shall go up as dust,   because they have rejected the law of Yahweh of Armies,   and despised the word of the Holy One of Israel. ",
      "25": "  Therefore Yahweh’s anger burns against his people,   and he has stretched out his hand against them and has struck them.   The mountains tremble,   and their dead bodies are as refuse in the middle of the streets.   For all this, his anger is not turned away,   but his hand is still stretched out. ",
      "26": "  He will lift up a banner to the nations from far away,   and he will whistle for them from the end of the earth.   Behold, they will come speedily and swiftly. ",
      "27": "  No one shall be weary nor stumble among them;   no one shall slumber nor sleep,   neither shall the belt of their waist be untied,   nor the strap of their sandals be broken, ",
      "28": "  whose arrows are sharp,   and all their bows bent.   Their horses’ hoofs will be like flint,   and their wheels like a whirlwind. ",
      "29": "  Their roaring will be like a lioness.   They will roar like young lions.   Yes, they shall roar,   and seize their prey and carry it off,   and there will be no one to deliver. ",
      "30": "  They will roar against them in that day like the roaring of the sea.   If one looks to the land, behold, darkness and distress.   The light is darkened in its clouds."
    },
    "6": {
      "1": "In the year that King Uzziah died, I saw the Lord sitting on a throne, high and lifted up; and his train filled the temple.",
      "2": "Above him stood the seraphim. Each one had six wings. With two he covered his face. With two he covered his feet. With two he flew.",
      "3": "One called to another, and said,   “Holy, holy, holy, is Yahweh of Armies!   The whole earth is full of his glory!” ",
      "4": "The foundations of the thresholds shook at the voice of him who called, and the house was filled with smoke.",
      "5": "Then I said, “Woe is me! For I am undone, because I am a man of unclean lips and I live among a people of unclean lips, for my eyes have seen the King, Yahweh of Armies!” ",
      "6": "Then one of the seraphim flew to me, having a live coal in his hand, which he had taken with the tongs from off the altar.",
      "7": "He touched my mouth with it, and said, “Behold, this has touched your lips; and your iniquity is taken away, and your sin forgiven.” ",
      "8": "I heard the Lord’s voice, saying, “Whom shall I send, and who will go for us?” Then I said, “Here I am. Send me!” ",
      "9": "He said, “Go, and tell this people,   ‘You hear indeed,   but don’t understand.   You see indeed,   but don’t perceive.’ ",
      "10": "  Make the heart of this people fat.   Make their ears heavy, and shut their eyes;   lest they see with their eyes,   hear with their ears,   understand with their heart,   and turn again, and be healed.” ",
      "11": "Then I said, “Lord, how long?” He answered,   “Until cities are waste without inhabitant,   houses without man,   the land becomes utterly waste, ",
      "12": "  and Yahweh has removed men far away,   and the forsaken places are many within the land. ",
      "13": "  If there is a tenth left in it,   that also will in turn be consumed,   as a terebinth, and as an oak whose stump remains when they are cut down,   so the holy seed is its stump.”"
    },
    "7": {
      "1": "In the days of Ahaz the son of Jotham, the son of Uzziah, king of Judah, Rezin the king of Syria and Pekah the son of Remaliah, king of Israel, went up to Jerusalem to war against it, but could not prevail against it.",
      "2": "David’s house was told, “Syria is allied with Ephraim.” His heart trembled, and the heart of his people, as the trees of the forest tremble with the wind. ",
      "3": "Then Yahweh said to Isaiah, “Go out now to meet Ahaz, you, and Shearjashub your son, at the end of the conduit of the upper pool, on the highway of the fuller’s field.",
      "4": "Tell him, ‘Be careful, and keep calm. Don’t be afraid, neither let your heart be faint because of these two tails of smoking torches, for the fierce anger of Rezin and Syria, and of the son of Remaliah.",
      "5": "Because Syria, Ephraim, and the son of Remaliah, have plotted evil against you, saying,",
      "6": "“Let’s go up against Judah, and tear it apart, and let’s divide it among ourselves, and set up a king within it, even the son of Tabeel.”",
      "7": "This is what the Lord Yahweh says: “It shall not stand, neither shall it happen.”",
      "8": "For the head of Syria is Damascus, and the head of Damascus is Rezin. Within sixty-five years Ephraim shall be broken in pieces, so that it shall not be a people.",
      "9": "The head of Ephraim is Samaria, and the head of Samaria is Remaliah’s son. If you will not believe, surely you shall not be established.’” ",
      "10": "Yahweh spoke again to Ahaz, saying,",
      "11": "“Ask a sign of Yahweh your God; ask it either in the depth, or in the height above.” ",
      "12": "But Ahaz said, “I won’t ask. I won’t tempt Yahweh.” ",
      "13": "He said, “Listen now, house of David. Is it not enough for you to try the patience of men, that you will try the patience of my God also?",
      "14": "Therefore the Lord himself will give you a sign. Behold, the virgin will conceive, and bear a son, and shall call his name Immanuel. ",
      "15": "He shall eat butter and honey when he knows to refuse the evil and choose the good.",
      "16": "For before the child knows to refuse the evil and choose the good, the land whose two kings you abhor shall be forsaken.",
      "17": "Yahweh will bring on you, on your people, and on your father’s house days that have not come, from the day that Ephraim departed from Judah, even the king of Assyria. ",
      "18": "It will happen in that day that Yahweh will whistle for the fly that is in the uttermost part of the rivers of Egypt, and for the bee that is in the land of Assyria.",
      "19": "They shall come, and shall all rest in the desolate valleys, in the clefts of the rocks, on all thorn hedges, and on all pastures. ",
      "20": "In that day the Lord will shave with a razor that is hired in the parts beyond the River, even with the king of Assyria, the head and the hair of the feet; and it shall also consume the beard. ",
      "21": "It shall happen in that day that a man shall keep alive a young cow, and two sheep.",
      "22": "It shall happen, that because of the abundance of milk which they shall give he shall eat butter, for everyone will eat butter and honey that is left within the land. ",
      "23": "It will happen in that day that every place where there were a thousand vines worth a thousand silver shekels,  will be for briers and thorns.",
      "24": "People will go there with arrows and with bow, because all the land will be briers and thorns.",
      "25": "All the hills that were cultivated with the hoe, you shall not come there for fear of briers and thorns; but it shall be for the sending out of oxen, and for sheep to tread on.”"
    },
    "8": {
      "1": "Yahweh said to me, “Take a large tablet, and write on it with a man’s pen, ‘For Maher Shalal Hash Baz’; ",
      "2": "and I will take for myself faithful witnesses to testify: Uriah the priest, and Zechariah the son of Jeberechiah.” ",
      "3": "I went to the prophetess, and she conceived, and bore a son. Then Yahweh said to me, “Call his name ‘Maher Shalal Hash Baz.’",
      "4": "For before the child knows how to say, ‘My father’ and ‘My mother,’ the riches of Damascus and the plunder of Samaria will be carried away by the king of Assyria.” ",
      "5": "Yahweh spoke to me yet again, saying,",
      "6": "“Because this people has refused the waters of Shiloah that go softly, and rejoice in Rezin and Remaliah’s son;",
      "7": "now therefore, behold, the Lord brings upon them the mighty flood waters of the River: the king of Assyria and all his glory. It will come up over all its channels, and go over all its banks.",
      "8": "It will sweep onward into Judah. It will overflow and pass through. It will reach even to the neck. The stretching out of its wings will fill the width of your land, O Immanuel. ",
      "9": "Make an uproar, you peoples, and be broken in pieces! Listen, all you from far countries: dress for battle, and be shattered! Dress for battle, and be shattered!",
      "10": "Take counsel together, and it will be brought to nothing; speak the word, and it will not stand, for God is with us.” ",
      "11": "For Yahweh spoke this to me with a strong hand, and instructed me not to walk in the way of this people, saying,",
      "12": "“Don’t call a conspiracy all that this people call a conspiracy. Don’t fear their threats or be terrorized.",
      "13": "Yahweh of Armies is who you must respect as holy. He is the one you must fear. He is the one you must dread.",
      "14": "He will be a sanctuary, but for both houses of Israel, he will be a stumbling stone and a rock that makes them fall. For the people of Jerusalem, he will be a trap and a snare.",
      "15": "Many will stumble over it, fall, be broken, be snared, and be captured.” ",
      "16": "Wrap up the covenant. Seal the law among my disciples.",
      "17": "I will wait for Yahweh, who hides his face from the house of Jacob, and I will look for him.",
      "18": "Behold, I and the children whom Yahweh has given me are for signs and for wonders in Israel from Yahweh of Armies, who dwells in Mount Zion. ",
      "19": "When they tell you, “Consult with those who have familiar spirits and with the wizards, who chirp and who mutter,” shouldn’t a people consult with their God? Should they consult the dead on behalf of the living?",
      "20": "Turn to the law and to the covenant! If they don’t speak according to this word, surely there is no morning for them.",
      "21": "They will pass through it, very distressed and hungry. It will happen that when they are hungry, they will worry, and curse their king and their God. They will turn their faces upward,",
      "22": "then look to the earth and see distress, darkness, and the gloom of anguish. They will be driven into thick darkness."
    },
    "9": {
      "1": "But there shall be no more gloom for her who was in anguish. In the former time, he brought into contempt the land of Zebulun and the land of Naphtali; but in the latter time he has made it glorious, by the way of the sea, beyond the Jordan, Galilee of the nations. ",
      "2": "The people who walked in darkness have seen a great light.   The light has shined on those who lived in the land of the shadow of death. ",
      "3": "  You have multiplied the nation.   You have increased their joy. They rejoice before you according to the joy in harvest, as men rejoice when they divide the plunder.",
      "4": "For the yoke of his burden, and the staff of his shoulder, the rod of his oppressor, you have broken as in the day of Midian.",
      "5": "For all the armor of the armed man in the noisy battle, and the garments rolled in blood, will be for burning, fuel for the fire.",
      "6": "For a child is born to us. A son is given to us; and the government will be on his shoulders. His name will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.",
      "7": "Of the increase of his government and of peace there shall be no end, on David’s throne, and on his kingdom, to establish it, and to uphold it with justice and with righteousness from that time on, even forever. The zeal of Yahweh of Armies will perform this. ",
      "8": "The Lord sent a word into Jacob,   and it falls on Israel. ",
      "9": "  All the people will know,   including Ephraim and the inhabitants of Samaria, who say in pride and in arrogance of heart, ",
      "10": "  “The bricks have fallen,   but we will build with cut stone.   The sycamore fig trees have been cut down,   but we will put cedars in their place.” ",
      "11": "  Therefore Yahweh will set up on high against him the adversaries of Rezin,   and will stir up his enemies, ",
      "12": "  The Syrians in front,   and the Philistines behind;   and they will devour Israel with open mouth.   For all this, his anger is not turned away,   but his hand is stretched out still. ",
      "13": "  Yet the people have not turned to him who struck them,   neither have they sought Yahweh of Armies. ",
      "14": "  Therefore Yahweh will cut off from Israel head and tail,   palm branch and reed, in one day. ",
      "15": "  The elder and the honorable man is the head,   and the prophet who teaches lies is the tail. ",
      "16": "  For those who lead this people lead them astray;   and those who are led by them are destroyed. ",
      "17": "  Therefore the Lord will not rejoice over their young men,   neither will he have compassion on their fatherless and widows;   for everyone is profane and an evildoer,   and every mouth speaks folly.   For all this his anger is not turned away,   but his hand is stretched out still. ",
      "18": "  For wickedness burns like a fire.   It devours the briers and thorns;   yes, it kindles in the thickets of the forest,   and they roll upward in a column of smoke. ",
      "19": "  Through Yahweh of Armies’ wrath, the land is burned up;   and the people are the fuel for the fire.   No one spares his brother. ",
      "20": "  One will devour on the right hand, and be hungry;   and he will eat on the left hand, and they will not be satisfied.   Everyone will eat the flesh of his own arm: ",
      "21": "  Manasseh eating Ephraim and Ephraim eating Manasseh, and they together will be against Judah.   For all this his anger is not turned away,   but his hand is stretched out still."
    },
    "10": {
      "1": "Woe to those who decree unrighteous decrees, and to the writers who write oppressive decrees",
      "2": "to deprive the needy of justice, and to rob the poor among my people of their rights, that widows may be their plunder, and that they may make the fatherless their prey!",
      "3": "What will you do in the day of visitation, and in the desolation which will come from afar? To whom will you flee for help? Where will you leave your wealth? ",
      "4": "They will only bow down under the prisoners,   and will fall under the slain.   For all this his anger is not turned away,   but his hand is stretched out still. ",
      "5": "Alas Assyrian, the rod of my anger, the staff in whose hand is my indignation!",
      "6": "I will send him against a profane nation, and against the people who anger me I will give him a command to take the plunder and to take the prey, and to tread them down like the mire of the streets.",
      "7": "However, he doesn’t mean so, neither does his heart think so; but it is in his heart to destroy, and to cut off not a few nations.",
      "8": "For he says, “Aren’t all of my princes kings?",
      "9": "Isn’t Calno like Carchemish? Isn’t Hamath like Arpad? Isn’t Samaria like Damascus?”",
      "10": "As my hand has found the kingdoms of the idols, whose engraved images exceeded those of Jerusalem and of Samaria,",
      "11": "shall I not, as I have done to Samaria and her idols, so do to Jerusalem and her idols? ",
      "12": "Therefore it will happen that when the Lord has performed his whole work on Mount Zion and on Jerusalem, I will punish the fruit of the willful proud heart of the king of Assyria, and the insolence of his arrogant looks.",
      "13": "For he has said, “By the strength of my hand I have done it, and by my wisdom, for I have understanding. I have removed the boundaries of the peoples, and have robbed their treasures. Like a valiant man I have brought down their rulers.",
      "14": "My hand has found the riches of the peoples like a nest, and like one gathers eggs that are abandoned, I have gathered all the earth. There was no one who moved their wing, or that opened their mouth, or chirped.” ",
      "15": "Should an ax brag against him who chops with it? Should a saw exalt itself above him who saws with it? As if a rod should lift those who lift it up, or as if a staff should lift up someone who is not wood.",
      "16": "Therefore the Lord, Yahweh of Armies, will send among his fat ones leanness; and under his glory a burning will be kindled like the burning of fire.",
      "17": "The light of Israel will be for a fire, and his Holy One for a flame; and it will burn and devour his thorns and his briers in one day.",
      "18": "He will consume the glory of his forest and of his fruitful field, both soul and body. It will be as when a standard bearer faints.",
      "19": "The remnant of the trees of his forest shall be few, so that a child could write their number. ",
      "20": "It will come to pass in that day that the remnant of Israel, and those who have escaped from the house of Jacob will no more again lean on him who struck them, but shall lean on Yahweh, the Holy One of Israel, in truth.",
      "21": "A remnant will return, even the remnant of Jacob, to the mighty God.",
      "22": "For though your people, Israel, are like the sand of the sea, only a remnant of them will return. A destruction is determined, overflowing with righteousness.",
      "23": "For the Lord, Yahweh of Armies, will make a full end, and that determined, throughout all the earth. ",
      "24": "Therefore the Lord, Yahweh of Armies, says, “My people who dwell in Zion, don’t be afraid of the Assyrian, though he strike you with the rod, and lift up his staff against you, as Egypt did.",
      "25": "For yet a very little while, and the indignation against you will be accomplished, and my anger will be directed to his destruction.”",
      "26": "Yahweh of Armies will stir up a scourge against him, as in the slaughter of Midian at the rock of Oreb. His rod will be over the sea, and he will lift it up like he did against Egypt.",
      "27": "It will happen in that day that his burden will depart from off your shoulder, and his yoke from off your neck, and the yoke shall be destroyed because of the anointing oil. ",
      "28": "He has come to Aiath. He has passed through Migron. At Michmash he stores his baggage.",
      "29": "They have gone over the pass. They have taken up their lodging at Geba. Ramah trembles. Gibeah of Saul has fled.",
      "30": "Cry aloud with your voice, daughter of Gallim! Listen, Laishah! You poor Anathoth!",
      "31": "Madmenah is a fugitive. The inhabitants of Gebim flee for safety.",
      "32": "This very day he will halt at Nob. He shakes his hand at the mountain of the daughter of Zion, the hill of Jerusalem. ",
      "33": "Behold, the Lord, Yahweh of Armies, will lop the boughs with terror. The tall will be cut down, and the lofty will be brought low.",
      "34": "He will cut down the thickets of the forest with iron, and Lebanon will fall by the Mighty One."
    },
    "11": {
      "1": "  A shoot will come out of the stock of Jesse,   and a branch out of his roots will bear fruit. ",
      "2": "  Yahweh’s Spirit will rest on him:   the spirit of wisdom and understanding,   the spirit of counsel and might,   the spirit of knowledge and of the fear of Yahweh. ",
      "3": "  His delight will be in the fear of Yahweh.   He will not judge by the sight of his eyes,   neither decide by the hearing of his ears; ",
      "4": "  but he will judge the poor with righteousness,   and decide with equity for the humble of the earth.   He will strike the earth with the rod of his mouth;   and with the breath of his lips he will kill the wicked. ",
      "5": "  Righteousness will be the belt around his waist,   and faithfulness the belt around his waist. ",
      "6": "  The wolf will live with the lamb,   and the leopard will lie down with the young goat,   the calf, the young lion, and the fattened calf together;   and a little child will lead them. ",
      "7": "  The cow and the bear will graze.   Their young ones will lie down together.   The lion will eat straw like the ox. ",
      "8": "  The nursing child will play near a cobra’s hole,   and the weaned child will put his hand on the viper’s den. ",
      "9": "  They will not hurt nor destroy in all my holy mountain;   for the earth will be full of the knowledge of Yahweh,   as the waters cover the sea. ",
      "10": "It will happen in that day that the nations will seek the root of Jesse, who stands as a banner of the peoples; and his resting place will be glorious. ",
      "11": "It will happen in that day that the Lord will set his hand again the second time to recover the remnant that is left of his people from Assyria, from Egypt, from Pathros, from Cush, from Elam, from Shinar, from Hamath, and from the islands of the sea.",
      "12": "He will set up a banner for the nations, and will assemble the outcasts of Israel, and gather together the dispersed of Judah from the four corners of the earth.",
      "13": "The envy also of Ephraim will depart, and those who persecute Judah will be cut off. Ephraim won’t envy Judah, and Judah won’t persecute Ephraim.",
      "14": "They will fly down on the shoulders of the Philistines on the west. Together they will plunder the children of the east. They will extend their power over Edom and Moab, and the children of Ammon will obey them.",
      "15": "Yahweh will utterly destroy the tongue of the Egyptian sea; and with his scorching wind he will wave his hand over the River, and will split it into seven streams, and cause men to march over in sandals.",
      "16": "There will be a highway for the remnant that is left of his people from Assyria, like there was for Israel in the day that he came up out of the land of Egypt."
    },
    "12": {
      "1": "In that day you will say, “I will give thanks to you, Yahweh; for though you were angry with me, your anger has turned away and you comfort me.",
      "2": "Behold, God is my salvation. I will trust, and will not be afraid; for Yah, Yahweh, is my strength and song; and he has become my salvation.”",
      "3": "Therefore with joy you will draw water out of the wells of salvation.",
      "4": "In that day you will say, “Give thanks to Yahweh! Call on his name! Declare his doings among the peoples! Proclaim that his name is exalted!",
      "5": "Sing to Yahweh, for he has done excellent things! Let this be known in all the earth!",
      "6": "Cry aloud and shout, you inhabitant of Zion, for the Holy One of Israel is great among you!”"
    },
    "13": {
      "1": "The burden of Babylon, which Isaiah the son of Amoz saw. ",
      "2": "Set up a banner on the bare mountain! Lift up your voice to them! Wave your hand, that they may go into the gates of the nobles.",
      "3": "I have commanded my consecrated ones; yes, I have called my mighty men for my anger, even my proudly exulting ones.",
      "4": "The noise of a multitude is in the mountains, as of a great people; the noise of an uproar of the kingdoms of the nations gathered together! Yahweh of Armies is mustering the army for the battle.",
      "5": "They come from a far country, from the uttermost part of heaven, even Yahweh, and the weapons of his indignation, to destroy the whole land. ",
      "6": "Wail, for Yahweh’s day is at hand! It will come as destruction from the Almighty.",
      "7": "Therefore all hands will be feeble, and everyone’s heart will melt.",
      "8": "They will be dismayed. Pangs and sorrows will seize them. They will be in pain like a woman in labor. They will look in amazement one at another. Their faces will be faces of flame.",
      "9": "Behold, the day of Yahweh comes, cruel, with wrath and fierce anger; to make the land a desolation, and to destroy its sinners out of it.",
      "10": "For the stars of the sky and its constellations will not give their light. The sun will be darkened in its going out, and the moon will not cause its light to shine.",
      "11": "I will punish the world for their evil, and the wicked for their iniquity. I will cause the arrogance of the proud to cease, and will humble the arrogance of the terrible.",
      "12": "I will make people more rare than fine gold, even a person than the pure gold of Ophir.",
      "13": "Therefore I will make the heavens tremble, and the earth will be shaken out of its place in Yahweh of Armies’ wrath, and in the day of his fierce anger.",
      "14": "It will happen that like a hunted gazelle and like sheep that no one gathers, they will each turn to their own people, and will each flee to their own land.",
      "15": "Everyone who is found will be thrust through. Everyone who is captured will fall by the sword.",
      "16": "Their infants also will be dashed in pieces before their eyes. Their houses will be ransacked, and their wives raped. ",
      "17": "Behold, I will stir up the Medes against them, who will not value silver, and as for gold, they will not delight in it.",
      "18": "Their bows will dash the young men in pieces; and they shall have no pity on the fruit of the womb. Their eyes will not spare children.",
      "19": "Babylon, the glory of kingdoms, the beauty of the Chaldeans’ pride, will be like when God overthrew Sodom and Gomorrah.",
      "20": "It will never be inhabited, neither will it be lived in from generation to generation. The Arabian will not pitch a tent there, neither will shepherds make their flocks lie down there.",
      "21": "But wild animals of the desert will lie there, and their houses will be full of jackals. Ostriches will dwell there, and wild goats will frolic there.",
      "22": "Hyenas will cry in their fortresses, and jackals in the pleasant palaces. Her time is near to come, and her days will not be prolonged."
    },
    "14": {
      "1": "For Yahweh will have compassion on Jacob, and will yet choose Israel, and set them in their own land. The foreigner will join himself with them, and they will unite with the house of Jacob.",
      "2": "The peoples will take them, and bring them to their place. The house of Israel will possess them in Yahweh’s land for servants and for handmaids. They will take as captives those whose captives they were; and they shall rule over their oppressors. ",
      "3": "It will happen in the day that Yahweh will give you rest from your sorrow, from your trouble, and from the hard service in which you were made to serve,",
      "4": "that you will take up this parable against the king of Babylon, and say, “How the oppressor has ceased! The golden city has ceased!”",
      "5": "Yahweh has broken the staff of the wicked, the scepter of the rulers,",
      "6": "who struck the peoples in wrath with a continual stroke, who ruled the nations in anger, with a persecution that no one restrained.",
      "7": "The whole earth is at rest, and is quiet. They break out in song.",
      "8": "Yes, the cypress trees rejoice with you, with the cedars of Lebanon, saying, “Since you are humbled, no lumberjack has come up against us.”",
      "9": "Sheol  from beneath has moved for you to meet you at your coming. It stirs up the departed spirits for you, even all the rulers of the earth. It has raised up from their thrones all the kings of the nations.",
      "10": "They all will answer and ask you, “Have you also become as weak as we are? Have you become like us?”",
      "11": "Your pomp is brought down to Sheol,  with the sound of your stringed instruments. Maggots are spread out under you, and worms cover you. ",
      "12": "How you have fallen from heaven, shining one, son of the dawn! How you are cut down to the ground, who laid the nations low!",
      "13": "You said in your heart, “I will ascend into heaven! I will exalt my throne above the stars of God! I will sit on the mountain of assembly, in the far north!",
      "14": "I will ascend above the heights of the clouds! I will make myself like the Most High!”",
      "15": "Yet you shall be brought down to Sheol,  to the depths of the pit.",
      "16": "Those who see you will stare at you. They will ponder you, saying, “Is this the man who made the earth to tremble, who shook kingdoms,",
      "17": "who made the world like a wilderness, and overthrew its cities, who didn’t release his prisoners to their home?” ",
      "18": "All the kings of the nations sleep in glory, everyone in his own house.",
      "19": "But you are cast away from your tomb like an abominable branch, clothed with the slain who are thrust through with the sword, who go down to the stones of the pit; like a dead body trodden under foot.",
      "20": "You will not join them in burial, because you have destroyed your land. You have killed your people. The offspring of evildoers will not be named forever. ",
      "21": "Prepare for slaughter of his children because of the iniquity of their fathers, that they not rise up and possess the earth, and fill the surface of the world with cities.",
      "22": "“I will rise up against them,” says Yahweh of Armies, “and cut off from Babylon name and remnant, and son and son’s son,” says Yahweh.",
      "23": "“I will also make it a possession for the porcupine, and pools of water. I will sweep it with the broom of destruction,” says Yahweh of Armies. ",
      "24": "Yahweh of Armies has sworn, saying, “Surely, as I have thought, so shall it happen; and as I have purposed, so shall it stand:",
      "25": "that I will break the Assyrian in my land, and tread him under foot on my mountains. Then his yoke will leave them, and his burden leave their shoulders.",
      "26": "This is the plan that is determined for the whole earth. This is the hand that is stretched out over all the nations.",
      "27": "For Yahweh of Armies has planned, and who can stop it? His hand is stretched out, and who can turn it back?” ",
      "28": "This burden was in the year that King Ahaz died. ",
      "29": "Don’t rejoice, O Philistia, all of you, because the rod that struck you is broken; for out of the serpent’s root an adder will emerge, and his fruit will be a fiery flying serpent.",
      "30": "The firstborn of the poor will eat, and the needy will lie down in safety; and I will kill your root with famine, and your remnant will be killed. ",
      "31": "Howl, gate! Cry, city! You are melted away, Philistia, all of you; for smoke comes out of the north, and there is no straggler in his ranks. ",
      "32": "What will they answer the messengers of the nation? That Yahweh has founded Zion, and in her the afflicted of his people will take refuge."
    },
    "15": {
      "1": "The burden of Moab. For in a night, Ar of Moab is laid waste, and brought to nothing. For in a night Kir of Moab is laid waste, and brought to nothing.",
      "2": "They have gone up to Bayith, and to Dibon, to the high places, to weep. Moab wails over Nebo and over Medeba. Baldness is on all of their heads. Every beard is cut off.",
      "3": "In their streets, they clothe themselves in sackcloth. In their streets and on their housetops, everyone wails, weeping abundantly.",
      "4": "Heshbon cries out with Elealeh. Their voice is heard even to Jahaz. Therefore the armed men of Moab cry aloud. Their souls tremble within them.",
      "5": "My heart cries out for Moab! Her nobles flee to Zoar, to Eglath Shelishiyah; for they go up by the ascent of Luhith with weeping; for on the way to Horonaim, they raise up a cry of destruction.",
      "6": "For the waters of Nimrim will be desolate; for the grass has withered away, the tender grass fails, there is no green thing.",
      "7": "Therefore they will carry away the abundance they have gotten, and that which they have stored up, over the brook of the willows.",
      "8": "For the cry has gone around the borders of Moab, its wailing to Eglaim, and its wailing to Beer Elim.",
      "9": "For the waters of Dimon are full of blood; for I will bring yet more on Dimon, a lion on those of Moab who escape, and on the remnant of the land."
    },
    "16": {
      "1": "Send the lambs for the ruler of the land from Selah to the wilderness, to the mountain of the daughter of Zion.",
      "2": "For it will be that as wandering birds, as a scattered nest, so will the daughters of Moab be at the fords of the Arnon.",
      "3": "Give counsel! Execute justice! Make your shade like the night in the middle of the noonday! Hide the outcasts! Don’t betray the fugitive!",
      "4": "Let my outcasts dwell with you! As for Moab, be a hiding place for him from the face of the destroyer. For the extortionist is brought to nothing. Destruction ceases. The oppressors are consumed out of the land.",
      "5": "A throne will be established in loving kindness. One will sit on it in truth, in the tent of David, judging, seeking justice, and swift to do righteousness. ",
      "6": "We have heard of the pride of Moab, that he is very proud; even of his arrogance, his pride, and his wrath. His boastings are nothing.",
      "7": "Therefore Moab will wail for Moab. Everyone will wail. You will mourn for the raisin cakes of Kir Hareseth, utterly stricken.",
      "8": "For the fields of Heshbon languish with the vine of Sibmah. The lords of the nations have broken down its choice branches, which reached even to Jazer, which wandered into the wilderness. Its shoots were spread abroad. They passed over the sea.",
      "9": "Therefore I will weep with the weeping of Jazer for the vine of Sibmah. I will water you with my tears, Heshbon, and Elealeh: for on your summer fruits and on your harvest the battle shout has fallen.",
      "10": "Gladness is taken away, and joy out of the fruitful field; and in the vineyards there will be no singing, neither joyful noise. Nobody will tread out wine in the presses. I have made the shouting stop.",
      "11": "Therefore my heart sounds like a harp for Moab, and my inward parts for Kir Heres.",
      "12": "It will happen that when Moab presents himself, when he wearies himself on the high place, and comes to his sanctuary to pray, that he will not prevail. ",
      "13": "This is the word that Yahweh spoke concerning Moab in time past.",
      "14": "But now Yahweh has spoken, saying, “Within three years, as a worker bound by contract would count them, the glory of Moab shall be brought into contempt, with all his great multitude; and the remnant will be very small and feeble.”"
    },
    "17": {
      "1": "The burden of Damascus. “Behold, Damascus is taken away from being a city, and it will be a ruinous heap.",
      "2": "The cities of Aroer are forsaken. They will be for flocks, which shall lie down, and no one shall make them afraid.",
      "3": "The fortress shall cease from Ephraim, and the kingdom from Damascus, and the remnant of Syria. They will be as the glory of the children of Israel,” says Yahweh of Armies. ",
      "4": "“It will happen in that day that the glory of Jacob will be made thin, and the fatness of his flesh will become lean.",
      "5": "It will be like when the harvester gathers the wheat, and his arm reaps the grain. Yes, it will be like when one gleans grain in the valley of Rephaim.",
      "6": "Yet gleanings will be left there, like the shaking of an olive tree, two or three olives in the top of the uppermost bough, four or five in the outermost branches of a fruitful tree,” says Yahweh, the God of Israel.",
      "7": "In that day, people will look to their Maker, and their eyes will have respect for the Holy One of Israel.",
      "8": "They will not look to the altars, the work of their hands; neither shall they respect that which their fingers have made, either the Asherah poles or the incense altars.",
      "9": "In that day, their strong cities will be like the forsaken places in the woods and on the mountain top, which were forsaken from before the children of Israel; and it will be a desolation.",
      "10": "For you have forgotten the God of your salvation, and have not remembered the rock of your strength. Therefore you plant pleasant plants, and set out foreign seedlings.",
      "11": "In the day of your planting, you hedge it in. In the morning, you make your seed blossom, but the harvest flees away in the day of grief and of desperate sorrow. ",
      "12": "Ah, the uproar of many peoples who roar like the roaring of the seas; and the rushing of nations that rush like the rushing of mighty waters!",
      "13": "The nations will rush like the rushing of many waters, but he will rebuke them, and they will flee far off, and will be chased like the chaff of the mountains before the wind, and like the whirling dust before the storm.",
      "14": "At evening, behold, terror! Before the morning, they are no more. This is the portion of those who plunder us, and the lot of those who rob us."
    },
    "18": {
      "1": "Ah, the land of the rustling of wings, which is beyond the rivers of Ethiopia;",
      "2": "that sends ambassadors by the sea, even in vessels of papyrus on the waters, saying, “Go, you swift messengers, to a nation tall and smooth, to a people awesome from their beginning onward, a nation that measures out and treads down, whose land the rivers divide!”",
      "3": "All you inhabitants of the world, and you dwellers on the earth, when a banner is lifted up on the mountains, look! When the trumpet is blown, listen! ",
      "4": "For Yahweh said to me, “I will be still, and I will see in my dwelling place, like clear heat in sunshine, like a cloud of dew in the heat of harvest.”",
      "5": "For before the harvest, when the blossom is over, and the flower becomes a ripening grape, he will cut off the sprigs with pruning hooks, and he will cut down and take away the spreading branches.",
      "6": "They will be left together for the ravenous birds of the mountains, and for the animals of the earth. The ravenous birds will eat them in the summer, and all the animals of the earth will eat them in the winter.",
      "7": "In that time, a present will be brought to Yahweh of Armies from a people tall and smooth, even from a people awesome from their beginning onward, a nation that measures out and treads down, whose land the rivers divide, to the place of the name of Yahweh of Armies, Mount Zion."
    },
    "19": {
      "1": "The burden of Egypt. “Behold, Yahweh rides on a swift cloud, and comes to Egypt. The idols of Egypt will tremble at his presence; and the heart of Egypt will melt within it.",
      "2": "I will stir up the Egyptians against the Egyptians, and they will fight everyone against his brother, and everyone against his neighbor; city against city, and kingdom against kingdom.",
      "3": "The spirit of the Egyptians will fail within them. I will destroy their counsel. They will seek the idols, the charmers, those who have familiar spirits, and the wizards.",
      "4": "I will give over the Egyptians into the hand of a cruel lord. A fierce king will rule over them,” says the Lord, Yahweh of Armies. ",
      "5": "The waters will fail from the sea, and the river will be wasted and become dry.",
      "6": "The rivers will become foul. The streams of Egypt will be diminished and dried up. The reeds and flags will wither away.",
      "7": "The meadows by the Nile, by the brink of the Nile, and all the sown fields of the Nile, will become dry, be driven away, and be no more.",
      "8": "The fishermen will lament, and all those who fish in the Nile will mourn, and those who spread nets on the waters will languish.",
      "9": "Moreover those who work in combed flax, and those who weave white cloth, will be confounded.",
      "10": "The pillars will be broken in pieces. All those who work for hire will be grieved in soul. ",
      "11": "The princes of Zoan are utterly foolish. The counsel of the wisest counselors of Pharaoh has become stupid. How do you say to Pharaoh, “I am the son of the wise, the son of ancient kings”?",
      "12": "Where then are your wise men? Let them tell you now; and let them know what Yahweh of Armies has purposed concerning Egypt.",
      "13": "The princes of Zoan have become fools. The princes of Memphis are deceived. They have caused Egypt to go astray, those who are the cornerstone of her tribes.",
      "14": "Yahweh has mixed a spirit of perverseness in the middle of her; and they have caused Egypt to go astray in all of its works, like a drunken man staggers in his vomit.",
      "15": "Neither shall there be any work for Egypt, which head or tail, palm branch or rush, may do.",
      "16": "In that day the Egyptians will be like women. They will tremble and fear because of the shaking of Yahweh of Armies’s hand, which he shakes over them.",
      "17": "The land of Judah will become a terror to Egypt. Everyone to whom mention is made of it will be afraid, because of the plans of Yahweh of Armies, which he determines against it.",
      "18": "In that day, there will be five cities in the land of Egypt that speak the language of Canaan, and swear to Yahweh of Armies. One will be called “The city of destruction.” ",
      "19": "In that day, there will be an altar to Yahweh in the middle of the land of Egypt, and a pillar to Yahweh at its border.",
      "20": "It will be for a sign and for a witness to Yahweh of Armies in the land of Egypt; for they will cry to Yahweh because of oppressors, and he will send them a savior and a defender, and he will deliver them.",
      "21": "Yahweh will be known to Egypt, and the Egyptians will know Yahweh in that day. Yes, they will worship with sacrifice and offering, and will vow a vow to Yahweh, and will perform it.",
      "22": "Yahweh will strike Egypt, striking and healing. They will return to Yahweh, and he will be entreated by them, and will heal them. ",
      "23": "In that day there will be a highway out of Egypt to Assyria, and the Assyrian shall come into Egypt, and the Egyptian into Assyria; and the Egyptians will worship with the Assyrians. ",
      "24": "In that day, Israel will be the third with Egypt and with Assyria, a blessing within the earth;",
      "25": "because Yahweh of Armies has blessed them, saying, “Blessed be Egypt my people, Assyria the work of my hands, and Israel my inheritance.”"
    },
    "20": {
      "1": "In the year that Tartan came to Ashdod, when Sargon the king of Assyria sent him, and he fought against Ashdod and took it;",
      "2": "at that time Yahweh spoke by Isaiah the son of Amoz, saying, “Go, and loosen the sackcloth from off your waist, and take your sandals from off your feet.” He did so, walking naked and barefoot.",
      "3": "Yahweh said, “As my servant Isaiah has walked naked and barefoot three years for a sign and a wonder concerning Egypt and concerning Ethiopia,",
      "4": "so the king of Assyria will lead away the captives of Egypt and the exiles of Ethiopia, young and old, naked and barefoot, and with buttocks uncovered, to the shame of Egypt.",
      "5": "They will be dismayed and confounded, because of Ethiopia their expectation, and of Egypt their glory.",
      "6": "The inhabitants of this coast land will say in that day, ‘Behold, this is our expectation, where we fled for help to be delivered from the king of Assyria. And we, how will we escape?’”"
    },
    "21": {
      "1": "The burden of the wilderness of the sea. As whirlwinds in the South sweep through, it comes from the wilderness, from an awesome land.",
      "2": "A grievous vision is declared to me. The treacherous man deals treacherously, and the destroyer destroys. Go up, Elam; attack! I have stopped all of Media’s sighing.",
      "3": "Therefore my thighs are filled with anguish. Pains have seized me, like the pains of a woman in labor. I am in so much pain that I can’t hear. I am so dismayed that I can’t see.",
      "4": "My heart flutters. Horror has frightened me. The twilight that I desired has been turned into trembling for me.",
      "5": "They prepare the table. They set the watch. They eat. They drink. Rise up, you princes, oil the shield!",
      "6": "For the Lord said to me, “Go, set a watchman. Let him declare what he sees.",
      "7": "When he sees a troop, horsemen in pairs, a troop of donkeys, a troop of camels, he shall listen diligently with great attentiveness.”",
      "8": "He cried like a lion: “Lord, I stand continually on the watchtower in the daytime, and every night I stay at my post.",
      "9": "Behold, here comes a troop of men, horsemen in pairs.” He answered, “Fallen, fallen is Babylon; and all the engraved images of her gods are broken to the ground. ",
      "10": "You are my threshing, and the grain of my floor!” That which I have heard from Yahweh of Armies, the God of Israel, I have declared to you. ",
      "11": "The burden of Dumah. One calls to me out of Seir, “Watchman, what of the night? Watchman, what of the night?”",
      "12": "The watchman said, “The morning comes, and also the night. If you will inquire, inquire. Come back again.” ",
      "13": "The burden on Arabia. You will lodge in the thickets in Arabia, you caravans of Dedanites.",
      "14": "They brought water to him who was thirsty. The inhabitants of the land of Tema met the fugitives with their bread.",
      "15": "For they fled away from the swords, from the drawn sword, from the bent bow, and from the heat of battle.",
      "16": "For the Lord said to me, “Within a year, as a worker bound by contract would count it, all the glory of Kedar will fail,",
      "17": "and the residue of the number of the archers, the mighty men of the children of Kedar, will be few; for Yahweh, the God of Israel, has spoken it.”"
    },
    "22": {
      "1": "The burden of the valley of vision. What ails you now, that you have all gone up to the housetops?",
      "2": "You that are full of shouting, a tumultuous city, a joyous town, your slain are not slain with the sword, neither are they dead in battle.",
      "3": "All your rulers fled away together. They were bound by the archers. All who were found by you were bound together. They fled far away.",
      "4": "Therefore I said, “Look away from me. I will weep bitterly. Don’t labor to comfort me for the destruction of the daughter of my people. ",
      "5": "For it is a day of confusion, and of treading down, and of perplexity from the Lord, Yahweh of Armies, in the valley of vision, a breaking down of the walls, and a crying to the mountains.”",
      "6": "Elam carried his quiver, with chariots of men and horsemen; and Kir uncovered the shield.",
      "7": "Your choicest valleys were full of chariots, and the horsemen set themselves in array at the gate.",
      "8": "He took away the covering of Judah; and you looked in that day to the armor in the house of the forest.",
      "9": "You saw the breaches of David’s city, that they were many; and you gathered together the waters of the lower pool.",
      "10": "You counted the houses of Jerusalem, and you broke down the houses to fortify the wall.",
      "11": "You also made a reservoir between the two walls for the water of the old pool. But you didn’t look to him who had done this, neither did you have respect for him who planned it long ago. ",
      "12": "In that day, the Lord, Yahweh of Armies, called to weeping, to mourning, to baldness, and to dressing in sackcloth;",
      "13": "and behold, there is joy and gladness, killing cattle and killing sheep, eating meat and drinking wine: “Let’s eat and drink, for tomorrow we will die.”",
      "14": "Yahweh of Armies revealed himself in my ears, “Surely this iniquity will not be forgiven you until you die,” says the Lord, Yahweh of Armies. ",
      "15": "The Lord, Yahweh of Armies says, “Go, get yourself to this treasurer, even to Shebna, who is over the house, and say,",
      "16": "‘What are you doing here? Who has you here, that you have dug out a tomb here?’ Cutting himself out a tomb on high, chiseling a habitation for himself in the rock!”",
      "17": "Behold, Yahweh will overcome you and hurl you away violently. Yes, he will grasp you firmly.",
      "18": "He will surely wind you around and around, and throw you like a ball into a large country. There you will die, and there the chariots of your glory will be, you disgrace of your lord’s house.",
      "19": "I will thrust you from your office. You will be pulled down from your station. ",
      "20": "It will happen in that day that I will call my servant Eliakim the son of Hilkiah,",
      "21": "and I will clothe him with your robe, and strengthen him with your belt. I will commit your government into his hand; and he will be a father to the inhabitants of Jerusalem, and to the house of Judah.",
      "22": "I will lay the key of David’s house on his shoulder. He will open, and no one will shut. He will shut, and no one will open.",
      "23": "I will fasten him like a nail in a sure place. He will be for a throne of glory to his father’s house.",
      "24": "They will hang on him all the glory of his father’s house, the offspring and the issue, every small vessel, from the cups even to all the pitchers.",
      "25": "“In that day,” says Yahweh of Armies, “the nail that was fastened in a sure place will give way. It will be cut down and fall. The burden that was on it will be cut off, for Yahweh has spoken it.”"
    }
  }
};

