
	
export const bib_verses = {
  "jeremiah": {
    "48": {
      "1": "Of Moab. Yahweh of Armies, the God of Israel, says:   “Woe to Nebo!   For it is laid waste.   Kiriathaim is disappointed.   It is taken.   Misgab  is put to shame   and broken down. ",
      "2": "  The praise of Moab is no more.   In Heshbon they have devised evil against her:   ‘Come! Let’s cut her off from being a nation.’   You also, Madmen, will be brought to silence.   The sword will pursue you. ",
      "3": "  The sound of a cry from Horonaim,   desolation and great destruction! ",
      "4": "  Moab is destroyed.   Her little ones have caused a cry to be heard. ",
      "5": "  For they will go up by the ascent of Luhith with continual weeping.   For at the descent of Horonaim they have heard the distress of the cry of destruction. ",
      "6": "  Flee! Save your lives!   Be like the juniper bush in the wilderness. ",
      "7": "  For, because you have trusted in your works and in your treasures,   you also will be taken.   Chemosh will go out into captivity,   his priests and his princes together. ",
      "8": "  The destroyer will come on every city,   and no city will escape;   the valley also will perish,   and the plain will be destroyed, as Yahweh has spoken. ",
      "9": "  Give wings to Moab,   that she may fly and get herself away:   and her cities will become a desolation,   without anyone to dwell in them. ",
      "10": "  “Cursed is he who does the work of Yahweh negligently;   and cursed is he who keeps back his sword from blood. ",
      "11": "  “Moab has been at ease from his youth,   and he has settled on his dregs,   and has not been emptied from vessel to vessel,   neither has he gone into captivity;   therefore his taste remains in him,   and his scent is not changed. ",
      "12": "  Therefore behold, the days come,” says Yahweh,   “that I will send to him those who pour off,   and they will pour him off;   and they will empty his vessels,   and break their containers in pieces. ",
      "13": "  Moab will be ashamed of Chemosh,   as the house of Israel was ashamed of Bethel, their confidence. ",
      "14": "  “How do you say, ‘We are mighty men,   and valiant men for the war’? ",
      "15": "  Moab is laid waste,   and they have gone up into his cities,   and his chosen young men have gone down to the slaughter,”   says the King, whose name is Yahweh of Armies. ",
      "16": "  “The calamity of Moab is near to come,   and his affliction hurries fast. ",
      "17": "  All you who are around him, bemoan him;   and all you who know his name, say,   ‘How the strong staff is broken,   the beautiful rod!’ ",
      "18": "  “You daughter who dwells in Dibon,   come down from your glory,   and sit in thirst;   for the destroyer of Moab has come up against you.   He has destroyed your strongholds. ",
      "19": "  Inhabitant of Aroer, stand by the way and watch.   Ask him who flees, and her who escapes;   say, ‘What has been done?’ ",
      "20": "  Moab is disappointed;   for it is broken down.   Wail and cry!   Tell it by the Arnon, that Moab is laid waste. ",
      "21": "  Judgment has come on the plain country—   on Holon, on Jahzah, on Mephaath, ",
      "22": "  on Dibon, on Nebo, on Beth Diblathaim, ",
      "23": "  on Kiriathaim, on Beth Gamul, on Beth Meon, ",
      "24": "  on Kerioth, on Bozrah,   and on all the cities of the land of Moab, far or near. ",
      "25": "  The horn of Moab is cut off,   and his arm is broken,” says Yahweh. ",
      "26": "  “Make him drunk,   for he magnified himself against Yahweh.   Moab will wallow in his vomit,   and he also will be in derision. ",
      "27": "  For wasn’t Israel a derision to you?   Was he found among thieves?   For as often as you speak of him,   you shake your head. ",
      "28": "  You inhabitants of Moab, leave the cities, and dwell in the rock.   Be like the dove that makes her nest over the mouth of the abyss. ",
      "29": "  “We have heard of the pride of Moab.   He is very proud in his loftiness, his pride,   his arrogance, and the arrogance of his heart. ",
      "30": "  I know his wrath,” says Yahweh, “that it is nothing;   his boastings have done nothing. ",
      "31": "  Therefore I will wail for Moab.   Yes, I will cry out for all Moab.   They will mourn for the men of Kir Heres. ",
      "32": "  With more than the weeping of Jazer   I will weep for you, vine of Sibmah.   Your branches passed over the sea.   They reached even to the sea of Jazer.   The destroyer has fallen on your summer fruits   and on your vintage. ",
      "33": "  Gladness and joy is taken away from the fruitful field   and from the land of Moab.   I have caused wine to cease from the wine presses.   No one will tread with shouting.   The shouting will be no shouting. ",
      "34": "  From the cry of Heshbon even to Elealeh,   even to Jahaz they have uttered their voice,   from Zoar even to Horonaim, to Eglath Shelishiyah;   for the waters of Nimrim will also become desolate. ",
      "35": "  Moreover I will cause to cease in Moab,” says Yahweh,   “him who offers in the high place,   and him who burns incense to his gods. ",
      "36": "  Therefore my heart sounds for Moab like flutes,   and my heart sounds like flutes for the men of Kir Heres.   Therefore the abundance that he has gotten has perished. ",
      "37": "  For every head is bald,   and every beard clipped.   There are cuttings on all the hands,   and sackcloth on the waist. ",
      "38": "  On all the housetops of Moab,   and in its streets, there is lamentation everywhere;   for I have broken Moab like a vessel in which no one delights,” says Yahweh. ",
      "39": "  “How it is broken down!   How they wail!   How Moab has turned the back with shame!   So will Moab become a derision   and a terror to all who are around him.” ",
      "40": "  For Yahweh says: “Behold, he will fly as an eagle,   and will spread out his wings against Moab. ",
      "41": "  Kerioth is taken,   and the strongholds are seized.   The heart of the mighty men of Moab at that day   will be as the heart of a woman in her pangs. ",
      "42": "  Moab will be destroyed from being a people,   because he has magnified himself against Yahweh. ",
      "43": "  Terror, the pit, and the snare are on you,   inhabitant of Moab,” says Yahweh. ",
      "44": "  “He who flees from the terror will fall into the pit;   and he who gets up out of the pit will be taken in the snare,   for I will bring on him, even on Moab,   the year of their visitation,” says Yahweh. ",
      "45": "  “Those who fled stand without strength under the shadow of Heshbon;   for a fire has gone out of Heshbon,   and a flame from the middle of Sihon,   and has devoured the corner of Moab,   and the crown of the head of the tumultuous ones. ",
      "46": "  Woe to you, O Moab!   The people of Chemosh are undone;   for your sons are taken away captive,   and your daughters into captivity. ",
      "47": "  “Yet I will reverse the captivity of Moab in the latter days,”   says Yahweh. Thus far is the judgment of Moab."
    },
    "49": {
      "1": "Of the children of Ammon. Yahweh says:   “Has Israel no sons?   Has he no heir?   Why then does Malcam possess Gad,   and his people dwell in its cities? ",
      "2": "  Therefore behold, the days come,”   says Yahweh,   “that I will cause an alarm of war to be heard against Rabbah of the children of Ammon,   and it will become a desolate heap,   and her daughters will be burned with fire;   then Israel will possess those who possessed him,”   says Yahweh. ",
      "3": "  “Wail, Heshbon, for Ai is laid waste!   Cry, you daughters of Rabbah!   Clothe yourself in sackcloth.   Lament, and run back and forth among the fences;   for Malcam will go into captivity,   his priests and his princes together. ",
      "4": "  Why do you boast in the valleys,   your flowing valley, backsliding daughter?   You trusted in her treasures,   saying, ‘Who will come to me?’ ",
      "5": "  Behold, I will bring a terror on you,”   says the Lord, Yahweh of Armies,   “from all who are around you.   All of you will be driven completely out,   and there will be no one to gather together the fugitives. ",
      "6": "  “But afterward I will reverse the captivity of the children of Ammon,”   says Yahweh. ",
      "7": "Of Edom, Yahweh of Armies says:   “Is wisdom no more in Teman?   Has counsel perished from the prudent?   Has their wisdom vanished? ",
      "8": "  Flee! Turn back!   Dwell in the depths, inhabitants of Dedan;   for I will bring the calamity of Esau on him when I visit him. ",
      "9": "  If grape gatherers came to you,   would they not leave some gleaning grapes?   If thieves came by night,   wouldn’t they steal until they had enough? ",
      "10": "  But I have made Esau bare,   I have uncovered his secret places,   and he will not be able to hide himself.   His offspring is destroyed,   with his brothers and his neighbors;   and he is no more. ",
      "11": "  Leave your fatherless children.   I will preserve them alive.   Let your widows trust in me.” ",
      "12": "For Yahweh says: “Behold, they to whom it didn’t pertain to drink of the cup will certainly drink; and are you he who will altogether go unpunished? You won’t go unpunished, but you will surely drink.",
      "13": "For I have sworn by myself,” says Yahweh, “that Bozrah will become an astonishment, a reproach, a waste, and a curse. All its cities will be perpetual wastes.” ",
      "14": "  I have heard news from Yahweh,   and an ambassador is sent among the nations,   saying, “Gather yourselves together!   Come against her!   Rise up to the battle!” ",
      "15": "  “For, behold, I have made you small among the nations,   and despised among men. ",
      "16": "  As for your terror,   the pride of your heart has deceived you,   O you who dwell in the clefts of the rock,   who hold the height of the hill,   though you should make your nest as high as the eagle,   I will bring you down from there,” says Yahweh. ",
      "17": "  “Edom will become an astonishment.   Everyone who passes by it will be astonished,   and will hiss at all its plagues. ",
      "18": "  As in the overthrow of Sodom and Gomorrah and its neighbor cities,” says Yahweh,   “no man will dwell there,   neither will any son of man live therein. ",
      "19": "  “Behold, he will come up like a lion from the pride of the Jordan against the strong habitation;   for I will suddenly make them run away from it,   and whoever is chosen,   I will appoint him over it.   For who is like me?   Who will appoint me a time?   Who is the shepherd who will stand before me?” ",
      "20": "  Therefore hear the counsel of Yahweh, that he has taken against Edom,   and his purposes that he has purposed against the inhabitants of Teman:   Surely they will drag them away,   the little ones of the flock.   Surely he will make their habitation desolate over them. ",
      "21": "  The earth trembles at the noise of their fall;   there is a cry, the noise which is heard in the Red Sea. ",
      "22": "  Behold, he will come up and fly as the eagle,   and spread out his wings against Bozrah.   The heart of the mighty men of Edom at that day will be as the heart of a woman in her pangs. ",
      "23": "Of Damascus:   “Hamath and Arpad are confounded,   for they have heard evil news.   They have melted away.   There is sorrow on the sea.   It can’t be quiet. ",
      "24": "  Damascus has grown feeble,   she turns herself to flee,   and trembling has seized her.   Anguish and sorrows have taken hold of her,   as of a woman in travail. ",
      "25": "  How is the city of praise not forsaken,   the city of my joy? ",
      "26": "  Therefore her young men will fall in her streets,   and all the men of war will be brought to silence in that day,”   says Yahweh of Armies. ",
      "27": "  “I will kindle a fire in the wall of Damascus,   and it will devour the palaces of Ben Hadad.” ",
      "28": "  Of Kedar, and of the kingdoms of Hazor, which Nebuchadnezzar king of Babylon struck, Yahweh says:   “Arise, go up to Kedar,   and destroy the children of the east. ",
      "29": "  They will take their tents and their flocks.   they will carry away for themselves their curtains,   all their vessels, and their camels;   and they will cry to them, ‘Terror on every side!’ ",
      "30": "  Flee!   Wander far off!   Dwell in the depths, you inhabitants of Hazor,” says Yahweh;   “for Nebuchadnezzar king of Babylon has taken counsel against you,   and has conceived a purpose against you. ",
      "31": "  Arise! Go up to a nation that is at ease,   that dwells without care,” says Yahweh;   “that has neither gates nor bars,   that dwells alone. ",
      "32": "  Their camels will be a booty,   and the multitude of their livestock a plunder.   I will scatter to all winds those who have the corners of their beards cut off;   and I will bring their calamity from every side of them,”   says Yahweh. ",
      "33": "  Hazor will be a dwelling place of jackals,   a desolation forever.   No man will dwell there,   neither will any son of man live therein.” ",
      "34": "Yahweh’s word that came to Jeremiah the prophet concerning Elam, in the beginning of the reign of Zedekiah king of Judah, saying,",
      "35": "“Yahweh of Armies says:   ‘Behold, I will break the bow of Elam,   the chief of their might. ",
      "36": "  I will bring on Elam the four winds from the four quarters of the sky,   and will scatter them toward all those winds.   There will be no nation where the outcasts of Elam will not come. ",
      "37": "  I will cause Elam to be dismayed before their enemies,   and before those who seek their life.   I will bring evil on them, even my fierce anger,’ says Yahweh;   ‘and I will send the sword after them,   until I have consumed them. ",
      "38": "  I will set my throne in Elam,   and will destroy from there king and princes,’ says Yahweh. ",
      "39": "  ‘But it will happen in the latter days   that I will reverse the captivity of Elam,’ says Yahweh.”"
    },
    "50": {
      "1": "The word that Yahweh spoke concerning Babylon, concerning the land of the Chaldeans, by Jeremiah the prophet. ",
      "2": "  “Declare among the nations and publish,   and set up a standard;   publish, and don’t conceal;   say, ‘Babylon has been taken,   Bel is disappointed,   Merodach is dismayed!   Her images are disappointed.   Her idols are dismayed.’ ",
      "3": "  For a nation comes up out of the north against her,   which will make her land desolate,   and no one will dwell in it.   They have fled.   They are gone,   both man and animal. ",
      "4": "  “In those days, and in that time,” says Yahweh,   “the children of Israel will come,   they and the children of Judah together;   they will go on their way weeping,   and will seek Yahweh their God. ",
      "5": "  They will inquire concerning Zion with their faces turned toward it,   saying, ‘Come, and join yourselves to Yahweh in an everlasting covenant   that will not be forgotten.’ ",
      "6": "  My people have been lost sheep.   Their shepherds have caused them to go astray.   They have turned them away on the mountains.   They have gone from mountain to hill.   They have forgotten their resting place. ",
      "7": "  All who found them have devoured them.   Their adversaries said, ‘We are not guilty,   because they have sinned against Yahweh,   the habitation of righteousness,   even Yahweh, the hope of their fathers.’ ",
      "8": "  “Flee out of the middle of Babylon!   Go out of the land of the Chaldeans,   and be as the male goats before the flocks. ",
      "9": "  For, behold, I will stir up   and cause to come up against Babylon a company of great nations from the north country;   and they will set themselves in array against her.   She will be taken from there.   Their arrows will be as of an expert mighty man.   None of them will return in vain. ",
      "10": "  Chaldea will be a prey.   All who prey on her will be satisfied,” says Yahweh. ",
      "11": "  “Because you are glad,   because you rejoice,   O you who plunder my heritage,   because you are wanton as a heifer that treads out the grain,   and neigh as strong horses, ",
      "12": "  your mother will be utterly disappointed.   She who bore you will be confounded.   Behold, she will be the least of the nations,   a wilderness, a dry land, and a desert. ",
      "13": "  Because of Yahweh’s wrath she won’t be inhabited,   but she will be wholly desolate.   Everyone who goes by Babylon will be astonished,   and hiss at all her plagues. ",
      "14": "  Set yourselves in array against Babylon all around,   all you who bend the bow;   shoot at her.   Spare no arrows,   for she has sinned against Yahweh. ",
      "15": "  Shout against her all around.   She has submitted herself.   Her bulwarks have fallen.   Her walls have been thrown down,   for it is the vengeance of Yahweh.   Take vengeance on her.   As she has done, do to her. ",
      "16": "  Cut off the sower from Babylon,   and him who handles the sickle in the time of harvest.   For fear of the oppressing sword,   they will each return to their own people,   and they will each flee to their own land. ",
      "17": "  “Israel is a hunted sheep.   The lions have driven him away.   First, the king of Assyria devoured him,   and now at last Nebuchadnezzar king of Babylon has broken his bones.” ",
      "18": "Therefore Yahweh of Armies, the God of Israel, says:   “Behold, I will punish the king of Babylon and his land,   as I have punished the king of Assyria. ",
      "19": "  I will bring Israel again to his pasture,   and he will feed on Carmel and Bashan.   His soul will be satisfied on the hills of Ephraim and in Gilead. ",
      "20": "  In those days, and in that time,” says Yahweh,   “the iniquity of Israel will be sought for,   and there will be none,   also the sins of Judah,   and they won’t be found;   for I will pardon them whom I leave as a remnant. ",
      "21": "  “Go up against the land of Merathaim,   even against it, and against the inhabitants of Pekod.   Kill and utterly destroy after them,” says Yahweh,   “and do according to all that I have commanded you. ",
      "22": "  A sound of battle is in the land,   and of great destruction. ",
      "23": "  How the hammer of the whole earth is cut apart and broken!   How Babylon has become a desolation among the nations! ",
      "24": "  I have laid a snare for you,   and you are also taken, Babylon,   and you weren’t aware.   You are found,   and also caught,   because you have fought against Yahweh. ",
      "25": "  Yahweh has opened his armory,   and has brought out the weapons of his indignation;   for the Lord, Yahweh of Armies, has a work to do in the land of the Chaldeans. ",
      "26": "  Come against her from the farthest border.   Open her storehouses.   Cast her up as heaps.   Destroy her utterly.   Let nothing of her be left. ",
      "27": "  Kill all her bulls.   Let them go down to the slaughter.   Woe to them! For their day has come,   the time of their visitation. ",
      "28": "  Listen to those who flee and escape out of the land of Babylon,   to declare in Zion the vengeance of Yahweh our God,   the vengeance of his temple. ",
      "29": "  “Call together the archers against Babylon,   all those who bend the bow.   Encamp against her all around.   Let none of it escape.   Pay her back according to her work.   According to all that she has done, do to her;   for she has been proud against Yahweh,   against the Holy One of Israel. ",
      "30": "  Therefore her young men will fall in her streets.   All her men of war will be brought to silence in that day,” says Yahweh. ",
      "31": "  “Behold, I am against you, you proud one,” says the Lord, Yahweh of Armies;   “for your day has come,   the time that I will visit you. ",
      "32": "  The proud one will stumble and fall,   and no one will raise him up.   I will kindle a fire in his cities,   and it will devour all who are around him.” ",
      "33": "  Yahweh of Armies says: “The children of Israel and the children of Judah are oppressed together.   All who took them captive hold them fast.   They refuse to let them go. ",
      "34": "  Their Redeemer is strong.   Yahweh of Armies is his name.   He will thoroughly plead their cause,   that he may give rest to the earth,   and disquiet the inhabitants of Babylon. ",
      "35": "  “A sword is on the Chaldeans,” says Yahweh,   “and on the inhabitants of Babylon,   on her princes,   and on her wise men. ",
      "36": "  A sword is on the boasters,   and they will become fools.   A sword is on her mighty men,   and they will be dismayed. ",
      "37": "  A sword is on their horses,   on their chariots,   and on all the mixed people who are in the middle of her;   and they will become as women.   A sword is on her treasures,   and they will be robbed. ",
      "38": "  A drought is on her waters,   and they will be dried up;   for it is a land of engraved images,   and they are mad over idols. ",
      "39": "  Therefore the wild animals of the desert   with the wolves will dwell there.   The ostriches will dwell therein.   It will be inhabited no more forever,   neither will it be lived in from generation to generation. ",
      "40": "  As when God overthrew Sodom and Gomorrah and its neighbor cities,” says Yahweh,   “so no man will dwell there,   neither will any son of man live therein. ",
      "41": "  “Behold, a people comes from the north.   A great nation and many kings will be stirred up from the uttermost parts of the earth. ",
      "42": "  They take up bow and spear.   They are cruel, and have no mercy.   Their voice roars like the sea.   They ride on horses,   everyone set in array,   as a man to the battle,   against you, daughter of Babylon. ",
      "43": "  The king of Babylon has heard the news of them,   and his hands become feeble.   Anguish has taken hold of him,   pains as of a woman in labor. ",
      "44": "  Behold, the enemy will come up like a lion   from the thickets of the Jordan against the strong habitation;   for I will suddenly make them run away from it.   Whoever is chosen,   I will appoint him over it,   for who is like me?   Who will appoint me a time?   Who is the shepherd who can stand before me?” ",
      "45": "  Therefore hear the counsel of Yahweh   that he has taken against Babylon;   and his purposes   that he has purposed against the land of the Chaldeans:   Surely they will drag them away,   even the little ones of the flock.   Surely he will make their habitation desolate over them. ",
      "46": "  The earth trembles at the noise of the taking of Babylon.   The cry is heard among the nations."
    },
    "51": {
      "1": "Yahweh says:   “Behold, I will raise up against Babylon,   and against those who dwell in Lebkamai, a destroying wind. ",
      "2": "  I will send to Babylon strangers, who will winnow her.   They will empty her land;   for in the day of trouble they will be against her all around. ",
      "3": "  Against him who bends, let the archer bend his bow,   also against him who lifts himself up in his coat of mail.   Don’t spare her young men!   Utterly destroy all her army! ",
      "4": "  They will fall down slain in the land of the Chaldeans,   and thrust through in her streets. ",
      "5": "  For Israel is not forsaken, nor Judah, by his God,   by Yahweh of Armies;   though their land is full of guilt against the Holy One of Israel. ",
      "6": "  “Flee out of the middle of Babylon!   Everyone save his own life!   Don’t be cut off in her iniquity,   for it is the time of Yahweh’s vengeance.   He will render to her a recompense. ",
      "7": "  Babylon has been a golden cup in Yahweh’s hand,   who made all the earth drunk.   The nations have drunk of her wine;   therefore the nations have gone mad. ",
      "8": "  Babylon has suddenly fallen and been destroyed!   Wail for her!   Take balm for her pain.   Perhaps she may be healed. ",
      "9": "  “We would have healed Babylon,   but she is not healed.   Forsake her,   and let’s each go into his own country;   for her judgment reaches to heaven,   and is lifted up even to the skies. ",
      "10": "  ‘Yahweh has produced our righteousness.   Come, and let’s declare in Zion the work of Yahweh our God.’ ",
      "11": "  “Make the arrows sharp!   Hold the shields firmly!   Yahweh has stirred up the spirit of the kings of the Medes,   because his purpose is against Babylon, to destroy it;   for it is the vengeance of Yahweh,   the vengeance of his temple. ",
      "12": "  Set up a standard against the walls of Babylon!   Make the watch strong!   Set the watchmen,   and prepare the ambushes;   for Yahweh has both purposed and done   that which he spoke concerning the inhabitants of Babylon. ",
      "13": "  You who dwell on many waters, abundant in treasures,   your end has come, the measure of your covetousness. ",
      "14": "  Yahweh of Armies has sworn by himself, saying,   ‘Surely I will fill you with men,   as with locusts,   and they will lift up a shout against you.’ ",
      "15": "  “He has made the earth by his power.   He has established the world by his wisdom.   By his understanding he has stretched out the heavens. ",
      "16": "  When he utters his voice,   there is a roar of waters in the heavens,   and he causes the vapors to ascend from the ends of the earth.   He makes lightning for the rain,   and brings the wind out of his treasuries. ",
      "17": "  “Every man has become stupid and without knowledge.   Every goldsmith is disappointed by his image,   for his molten images are falsehood,   and there is no breath in them. ",
      "18": "  They are vanity,   a work of delusion.   In the time of their visitation, they will perish. ",
      "19": "  The portion of Jacob is not like these,   for he formed all things,   including the tribe of his inheritance.   Yahweh of Armies is his name. ",
      "20": "  “You are my battle ax and weapons of war.   With you I will break the nations into pieces.   With you I will destroy kingdoms. ",
      "21": "  With you I will break in pieces   the horse and his rider. ",
      "22": "  With you I will break in pieces   the chariot and him who rides therein.   With you I will break in pieces   man and woman.   With you I will break in pieces   the old man and the youth.   With you I will break in pieces   the young man and the virgin. ",
      "23": "  With you I will break in pieces   the shepherd and his flock.   With you I will break in pieces   the farmer and his yoke.   With you I will break in pieces   governors and deputies. ",
      "24": "“I will render to Babylon and to all the inhabitants of Chaldea all their evil that they have done in Zion in your sight,” says Yahweh. ",
      "25": "  “Behold, I am against you, destroying mountain,” says Yahweh,   “which destroys all the earth.   I will stretch out my hand on you,   roll you down from the rocks,   and will make you a burned mountain. ",
      "26": "  They won’t take a cornerstone from you,   nor a stone for foundations;   but you will be desolate forever,” says Yahweh. ",
      "27": "  “Set up a standard in the land!   Blow the trumpet among the nations!   Prepare the nations against her!   Call together against her the kingdoms of Ararat, Minni, and Ashkenaz!   Appoint a marshal against her!   Cause the horses to come up as the swarming locusts! ",
      "28": "  Prepare against her the nations,   the kings of the Medes, its governors, and all its deputies, and all the land of their dominion! ",
      "29": "  The land trembles and is in pain;   for the purposes of Yahweh against Babylon stand,   to make the land of Babylon a desolation, without inhabitant. ",
      "30": "  The mighty men of Babylon have stopped fighting,   they remain in their strongholds.   Their might has failed.   They have become as women.   Her dwelling places are set on fire.   Her bars are broken. ",
      "31": "  One runner will run to meet another,   and one messenger to meet another,   to show the king of Babylon that his city is taken on every quarter. ",
      "32": "  So the passages are seized.   They have burned the reeds with fire.   The men of war are frightened.” ",
      "33": "For Yahweh of Armies, the God of Israel says:   “The daughter of Babylon is like a threshing floor at the time when it is trodden.   Yet a little while, and the time of harvest comes for her.” ",
      "34": "  “Nebuchadnezzar the king of Babylon has devoured me.   He has crushed me.   He has made me an empty vessel.   He has, like a monster, swallowed me up.   He has filled his mouth with my delicacies.   He has cast me out. ",
      "35": "  May the violence done to me and to my flesh be on Babylon!”   the inhabitant of Zion will say; and,   “May my blood be on the inhabitants of Chaldea!”   will Jerusalem say. ",
      "36": "Therefore Yahweh says:   “Behold, I will plead your cause,   and take vengeance for you.   I will dry up her sea,   and make her fountain dry. ",
      "37": "  Babylon will become heaps,   a dwelling place for jackals,   an astonishment, and a hissing,   without inhabitant. ",
      "38": "  They will roar together like young lions.   They will growl as lions’ cubs. ",
      "39": "  When they are inflamed, I will make their feast,   and I will make them drunk,   that they may rejoice,   and sleep a perpetual sleep,   and not wake up,” says Yahweh. ",
      "40": "  “I will bring them down like lambs to the slaughter,   like rams with male goats. ",
      "41": "  “How Sheshach is taken!   How the praise of the whole earth is seized!   How Babylon has become a desolation among the nations! ",
      "42": "  The sea has come up on Babylon.   She is covered with the multitude of its waves. ",
      "43": "  Her cities have become a desolation,   a dry land, and a desert,   a land in which no man dwells.   No son of man passes by it. ",
      "44": "  I will execute judgment on Bel in Babylon,   and I will bring out of his mouth that which he has swallowed up.   The nations will not flow any more to him.   Yes, the wall of Babylon will fall. ",
      "45": "  “My people, go away from the middle of her,   and each of you save yourselves from Yahweh’s fierce anger. ",
      "46": "  Don’t let your heart faint.   Don’t fear for the news that will be heard in the land.   For news will come one year,   and after that in another year news will come,   and violence in the land,   ruler against ruler. ",
      "47": "  Therefore behold, the days come that I will execute judgment on the engraved images of Babylon;   and her whole land will be confounded.   All her slain will fall in the middle of her. ",
      "48": "  Then the heavens and the earth,   and all that is therein,   will sing for joy over Babylon;   for the destroyers will come to her from the north,” says Yahweh. ",
      "49": "  “As Babylon has caused the slain of Israel to fall,   so the slain of all the land will fall at Babylon. ",
      "50": "  You who have escaped the sword, go!   Don’t stand still!   Remember Yahweh from afar,   and let Jerusalem come into your mind.” ",
      "51": "  “We are confounded   because we have heard reproach.   Confusion has covered our faces,   for strangers have come into the sanctuaries of Yahweh’s house.” ",
      "52": "  “Therefore behold, the days come,” says Yahweh,   “that I will execute judgment on her engraved images;   and through all her land the wounded will groan. ",
      "53": "  Though Babylon should mount up to the sky,   and though she should fortify the height of her strength,   yet destroyers will come to her from me,” says Yahweh. ",
      "54": "  “The sound of a cry comes from Babylon,   and of great destruction from the land of the Chaldeans! ",
      "55": "  For Yahweh lays Babylon waste,   and destroys out of her the great voice!   Their waves roar like many waters.   The noise of their voice is uttered. ",
      "56": "  For the destroyer has come on her,   even on Babylon.   Her mighty men are taken.   Their bows are broken in pieces,   for Yahweh is a God of retribution.   He will surely repay. ",
      "57": "  I will make her princes, her wise men,   her governors, her deputies, and her mighty men drunk.   They will sleep a perpetual sleep,   and not wake up,”   says the King, whose name is Yahweh of Armies. ",
      "58": "Yahweh of Armies says:   “The wide walls of Babylon will be utterly overthrown.   Her high gates will be burned with fire.   The peoples will labor for vanity,   and the nations for the fire;   and they will be weary.” ",
      "59": "The word which Jeremiah the prophet commanded Seraiah the son of Neriah, the son of Mahseiah, when he went with Zedekiah the king of Judah to Babylon in the fourth year of his reign. Now Seraiah was chief quartermaster.",
      "60": "Jeremiah wrote in a book all the evil that should come on Babylon, even all these words that are written concerning Babylon.",
      "61": "Jeremiah said to Seraiah, “When you come to Babylon, then see that you read all these words,",
      "62": "and say, ‘Yahweh, you have spoken concerning this place, to cut it off, that no one will dwell in it, neither man nor animal, but that it will be desolate forever.’",
      "63": "It will be, when you have finished reading this book, that you shall bind a stone to it, and cast it into the middle of the Euphrates.",
      "64": "Then you shall say, ‘Thus will Babylon sink, and will not rise again because of the evil that I will bring on her; and they will be weary.’” Thus far are the words of Jeremiah."
    },
    "52": {
      "1": "Zedekiah was twenty-one years old when he began to reign. He reigned eleven years in Jerusalem. His mother’s name was Hamutal the daughter of Jeremiah of Libnah.",
      "2": "He did that which was evil in Yahweh’s sight, according to all that Jehoiakim had done.",
      "3": "For through Yahweh’s anger this happened in Jerusalem and Judah, until he had cast them out from his presence. Zedekiah rebelled against the king of Babylon.",
      "4": "In the ninth year of his reign, in the tenth month, in the tenth day of the month, Nebuchadnezzar king of Babylon came, he and all his army, against Jerusalem, and encamped against it; and they built forts against it round about.",
      "5": "So the city was besieged to the eleventh year of King Zedekiah. ",
      "6": "In the fourth month, in the ninth day of the month, the famine was severe in the city, so that there was no bread for the people of the land.",
      "7": "Then a breach was made in the city, and all the men of war fled, and went out of the city by night by the way of the gate between the two walls, which was by the king’s garden. Now the Chaldeans were against the city all around. The men of war went toward the Arabah,",
      "8": "but the army of the Chaldeans pursued the king, and overtook Zedekiah in the plains of Jericho; and all his army was scattered from him.",
      "9": "Then they took the king, and carried him up to the king of Babylon to Riblah in the land of Hamath; and he pronounced judgment on him.",
      "10": "The king of Babylon killed the sons of Zedekiah before his eyes. He also killed all the princes of Judah in Riblah.",
      "11": "He put out the eyes of Zedekiah; and the king of Babylon bound him in fetters, and carried him to Babylon, and put him in prison until the day of his death. ",
      "12": "Now in the fifth month, in the tenth day of the month, which was the nineteenth year of King Nebuchadnezzar, king of Babylon, Nebuzaradan the captain of the guard, who stood before the king of Babylon, came into Jerusalem.",
      "13": "He burned Yahweh’s house, and the king’s house; and all the houses of Jerusalem, even every great house, he burned with fire.",
      "14": "All the army of the Chaldeans, who were with the captain of the guard, broke down all the walls of Jerusalem all around.",
      "15": "Then Nebuzaradan the captain of the guard carried away captive of the poorest of the people, and the rest of the people who were left in the city, and those who fell away, who defected to the king of Babylon, and the rest of the multitude.",
      "16": "But Nebuzaradan the captain of the guard left of the poorest of the land to be vineyard keepers and farmers. ",
      "17": "The Chaldeans broke the pillars of bronze that were in Yahweh’s house and the bases and the bronze sea that were in Yahweh’s house in pieces, and carried all of their bronze to Babylon.",
      "18": "They also took away the pots, the shovels, the snuffers, the basins, the spoons, and all the vessels of bronze with which they ministered.",
      "19": "The captain of the guard took away the cups, the fire pans, the basins, the pots, the lamp stands, the spoons, and the bowls; that which was of gold, as gold, and that which was of silver, as silver. ",
      "20": "They took the two pillars, the one sea, and the twelve bronze bulls that were under the bases, which King Solomon had made for Yahweh’s house. The bronze of all these vessels was without weight.",
      "21": "As for the pillars, the height of the one pillar was eighteen cubits;  and a line of twelve cubits encircled it; and its thickness was four fingers. It was hollow.",
      "22": "A capital of bronze was on it; and the height of the one capital was five cubits,  with network and pomegranates on the capital all around, all of bronze. The second pillar also had the same, with pomegranates.",
      "23": "There were ninety-six pomegranates on the sides; all the pomegranates were one hundred on the network all around. ",
      "24": "The captain of the guard took Seraiah the chief priest, and Zephaniah the second priest, and the three keepers of the threshold,",
      "25": "and out of the city he took an officer who was set over the men of war; and seven men of those who saw the king’s face, who were found in the city; and the scribe of the captain of the army, who mustered the people of the land; and sixty men of the people of the land, who were found in the middle of the city.",
      "26": "Nebuzaradan the captain of the guard took them, and brought them to the king of Babylon to Riblah.",
      "27": "The king of Babylon struck them, and put them to death at Riblah in the land of Hamath. So Judah was carried away captive out of his land.",
      "28": "This is the number of the people whom Nebuchadnezzar carried away captive:  in the seventh year, three thousand twenty-three Jews;",
      "29": "  in the eighteenth year of Nebuchadnezzar, he carried away captive from Jerusalem eight hundred thirty-two persons;",
      "30": "  in the twenty-third year of Nebuchadnezzar, Nebuzaradan the captain of the guard carried away captive of the Jews seven hundred forty-five people.  All the people numbered four thousand six hundred. ",
      "31": "In the thirty-seventh year of the captivity of Jehoiachin king of Judah, in the twelfth month, in the twenty-fifth day of the month, Evilmerodach king of Babylon, in the first year of his reign, lifted up the head of Jehoiachin king of Judah, and released him from prison.",
      "32": "He spoke kindly to him, and set his throne above the throne of the kings who were with him in Babylon,",
      "33": "and changed his prison garments. Jehoiachin ate bread before him continually all the days of his life.",
      "34": "For his allowance, there was a continual allowance given him by the king of Babylon, every day a portion until the day of his death, all the days of his life."
    }
  },
  "lamentations": {
    "1": {
      "1": "How the city sits solitary,   that was full of people!   She has become as a widow,   who was great among the nations!   She who was a princess among the provinces   has become a slave! ",
      "2": "  She weeps bitterly in the night.   Her tears are on her cheeks.   Among all her lovers   she has no one to comfort her.   All her friends have dealt treacherously with her.   They have become her enemies. ",
      "3": "  Judah has gone into captivity because of affliction   and because of great servitude.   She dwells among the nations.   She finds no rest.   All her persecutors overtook her in her distress. ",
      "4": "  The roads to Zion mourn,   because no one comes to the solemn assembly.   All her gates are desolate.   Her priests sigh.   Her virgins are afflicted,   and she herself is in bitterness. ",
      "5": "  Her adversaries have become the head.   Her enemies prosper;   for Yahweh  has afflicted her for the multitude of her transgressions.   Her young children have gone into captivity before the adversary. ",
      "6": "  All majesty has departed from the daughter of Zion.   Her princes have become like deer that find no pasture.   They have gone without strength before the pursuer. ",
      "7": "  Jerusalem remembers in the days of her affliction and of her miseries   all her pleasant things that were from the days of old;   when her people fell into the hand of the adversary,   and no one helped her.   The adversaries saw her.   They mocked at her desolations. ",
      "8": "  Jerusalem has grievously sinned.   Therefore she has become unclean.   All who honored her despise her,   because they have seen her nakedness.   Yes, she sighs and turns backward. ",
      "9": "  Her filthiness was in her skirts.   She didn’t remember her latter end.   Therefore she has come down astoundingly.   She has no comforter.   “See, Yahweh, my affliction;   for the enemy has magnified himself.” ",
      "10": "  The adversary has spread out his hand on all her pleasant things;   for she has seen that the nations have entered into her sanctuary,   concerning whom you commanded that they should not enter into your assembly. ",
      "11": "  All her people sigh.   They seek bread.   They have given their pleasant things for food to refresh their soul.   “Look, Yahweh, and see,   for I have become despised.” ",
      "12": "  “Is it nothing to you, all you who pass by?   Look, and see if there is any sorrow like my sorrow,   which is brought on me,   with which Yahweh has afflicted me in the day of his fierce anger. ",
      "13": "  “From on high has he sent fire into my bones,   and it prevails against them.   He has spread a net for my feet.   He has turned me back.   He has made me desolate and I faint all day long. ",
      "14": "  “The yoke of my transgressions is bound by his hand.   They are knit together.   They have come up on my neck.   He made my strength fail.   The Lord  has delivered me into their hands,   against whom I am not able to stand. ",
      "15": "  “The Lord has set at nothing all my mighty men within me.   He has called a solemn assembly against me to crush my young men.   The Lord has trodden the virgin daughter of Judah as in a wine press. ",
      "16": "  “For these things I weep.   My eye, my eye runs down with water,   because the comforter who should refresh my soul is far from me.   My children are desolate,   because the enemy has prevailed.” ",
      "17": "  Zion spreads out her hands.   There is no one to comfort her.   Yahweh has commanded concerning Jacob,   that those who are around him should be his adversaries.   Jerusalem is among them as an unclean thing. ",
      "18": "  “Yahweh is righteous,   for I have rebelled against his commandment.   Please hear all you peoples,   and see my sorrow.   My virgins and my young men have gone into captivity. ",
      "19": "  “I called for my lovers,   but they deceived me.   My priests and my elders gave up the spirit in the city,   while they sought food for themselves to refresh their souls. ",
      "20": "  “Look, Yahweh; for I am in distress.   My heart is troubled.   My heart turns over within me,   for I have grievously rebelled.   Abroad, the sword bereaves.   At home, it is like death. ",
      "21": "  “They have heard that I sigh.   There is no one to comfort me.   All my enemies have heard of my trouble.   They are glad that you have done it.   You will bring the day that you have proclaimed,   and they will be like me. ",
      "22": "  “Let all their wickedness come before you.   Do to them as you have done to me for all my transgressions.   For my sighs are many,   and my heart is faint."
    },
    "2": {
      "1": "How has the Lord covered the daughter of Zion with a cloud in his anger!   He has cast the beauty of Israel down from heaven to the earth,   and hasn’t remembered his footstool in the day of his anger. ",
      "2": "  The Lord has swallowed up all the dwellings of Jacob   without pity.   He has thrown down in his wrath the strongholds of the daughter of Judah.   He has brought them down to the ground.   He has profaned the kingdom and its princes. ",
      "3": "  He has cut off all the horn of Israel in fierce anger.   He has drawn back his right hand from before the enemy.   He has burned up Jacob like a flaming fire,   which devours all around. ",
      "4": "  He has bent his bow like an enemy.   He has stood with his right hand as an adversary.   He has killed all that were pleasant to the eye.   In the tent of the daughter of Zion, he has poured out his wrath like fire. ",
      "5": "  The Lord has become as an enemy.   He has swallowed up Israel.   He has swallowed up all her palaces.   He has destroyed his strongholds.   He has multiplied mourning and lamentation in the daughter of Judah. ",
      "6": "  He has violently taken away his tabernacle,   as if it were a garden.   He has destroyed his place of assembly.   Yahweh has caused solemn assembly and Sabbath to be forgotten in Zion.   In the indignation of his anger, he has despised the king and the priest. ",
      "7": "  The Lord has cast off his altar.   He has abhorred his sanctuary.   He has given the walls of her palaces into the hand of the enemy.   They have made a noise in Yahweh’s house,   as in the day of a solemn assembly. ",
      "8": "  Yahweh has purposed to destroy the wall of the daughter of Zion.   He has stretched out the line.   He has not withdrawn his hand from destroying;   He has made the rampart and wall lament.   They languish together. ",
      "9": "  Her gates have sunk into the ground.   He has destroyed and broken her bars.   Her king and her princes are among the nations where the law is not.   Yes, her prophets find no vision from Yahweh. ",
      "10": "  The elders of the daughter of Zion sit on the ground.   They keep silence.   They have cast up dust on their heads.   They have clothed themselves with sackcloth.   The virgins of Jerusalem hang down their heads to the ground. ",
      "11": "  My eyes fail with tears.   My heart is troubled.   My bile is poured on the earth,   because of the destruction of the daughter of my people,   because the young children and the infants swoon in the streets of the city. ",
      "12": "  They ask their mothers,   “Where is grain and wine?”   when they swoon as the wounded in the streets of the city,   when their soul is poured out into their mothers’ bosom. ",
      "13": "  What shall I testify to you?   What shall I liken to you, daughter of Jerusalem?   What shall I compare to you,   that I may comfort you, virgin daughter of Zion?   For your breach is as big as the sea.   Who can heal you? ",
      "14": "  Your prophets have seen false and foolish visions for you.   They have not uncovered your iniquity,   to reverse your captivity,   but have seen for you false revelations and causes of banishment. ",
      "15": "  All that pass by clap their hands at you.   They hiss and wag their head at the daughter of Jerusalem, saying,   “Is this the city that men called ‘The perfection of beauty,   the joy of the whole earth’?” ",
      "16": "  All your enemies have opened their mouth wide against you.   They hiss and gnash their teeth.   They say, “We have swallowed her up.   Certainly this is the day that we looked for.   We have found it.   We have seen it.” ",
      "17": "  Yahweh has done that which he planned.   He has fulfilled his word that he commanded in the days of old.   He has thrown down,   and has not pitied.   He has caused the enemy to rejoice over you.   He has exalted the horn of your adversaries. ",
      "18": "  Their heart cried to the Lord.   O wall of the daughter of Zion,   let tears run down like a river day and night.   Give yourself no relief.   Don’t let your eyes rest. ",
      "19": "  Arise, cry out in the night,   at the beginning of the watches!   Pour out your heart like water before the face of the Lord.   Lift up your hands toward him for the life of your young children,   who faint for hunger at the head of every street. ",
      "20": "  “Look, Yahweh, and see to whom you have done thus!   Should the women eat their offspring,   the children that they held and bounced on their knees?   Should the priest and the prophet be killed in the sanctuary of the Lord? ",
      "21": "  “The youth and the old man lie on the ground in the streets.   My virgins and my young men have fallen by the sword.   You have killed them in the day of your anger.   You have slaughtered, and not pitied. ",
      "22": "  “You have called, as in the day of a solemn assembly, my terrors on every side.   There was no one that escaped or remained in the day of Yahweh’s anger.   My enemy has consumed those whom I have cared for and brought up."
    },
    "3": {
      "1": "  I am the man who has seen affliction   by the rod of his wrath. ",
      "2": "  He has led me and caused me to walk in darkness,   and not in light. ",
      "3": "  Surely he turns his hand against me   again and again all day long. ",
      "4": "  He has made my flesh and my skin old.   He has broken my bones. ",
      "5": "  He has built against me,   and surrounded me with bitterness and hardship. ",
      "6": "  He has made me dwell in dark places,   as those who have been long dead. ",
      "7": "  He has walled me about, so that I can’t go out.   He has made my chain heavy. ",
      "8": "  Yes, when I cry, and call for help,   he shuts out my prayer. ",
      "9": "  He has walled up my ways with cut stone.   He has made my paths crooked. ",
      "10": "  He is to me as a bear lying in wait,   as a lion in hiding. ",
      "11": "  He has turned away my path,   and pulled me in pieces.   He has made me desolate. ",
      "12": "  He has bent his bow,   and set me as a mark for the arrow. ",
      "13": "  He has caused the shafts of his quiver to enter into my kidneys. ",
      "14": "  I have become a derision to all my people,   and their song all day long. ",
      "15": "  He has filled me with bitterness.   He has stuffed me with wormwood. ",
      "16": "  He has also broken my teeth with gravel.   He has covered me with ashes. ",
      "17": "  You have removed my soul far away from peace.   I forgot prosperity. ",
      "18": "  I said, “My strength has perished,   along with my expectation from Yahweh.” ",
      "19": "  Remember my affliction and my misery,   the wormwood and the bitterness. ",
      "20": "  My soul still remembers them,   and is bowed down within me. ",
      "21": "  This I recall to my mind;   therefore I have hope. ",
      "22": "  It is because of Yahweh’s loving kindnesses that we are not consumed,   because his mercies don’t fail. ",
      "23": "  They are new every morning.   Great is your faithfulness. ",
      "24": "  “Yahweh is my portion,” says my soul.   “Therefore I will hope in him.” ",
      "25": "  Yahweh is good to those who wait for him,   to the soul who seeks him. ",
      "26": "  It is good that a man should hope   and quietly wait for the salvation of Yahweh. ",
      "27": "  It is good for a man that he bear the yoke in his youth. ",
      "28": "  Let him sit alone and keep silence,   because he has laid it on him. ",
      "29": "  Let him put his mouth in the dust,   if it is so that there may be hope. ",
      "30": "  Let him give his cheek to him who strikes him.   Let him be filled full of reproach. ",
      "31": "  For the Lord will not cast off forever. ",
      "32": "  For though he causes grief,   yet he will have compassion according to the multitude of his loving kindnesses. ",
      "33": "  For he does not afflict willingly,   nor grieve the children of men. ",
      "34": "  To crush under foot all the prisoners of the earth, ",
      "35": "  to turn away the right of a man before the face of the Most High, ",
      "36": "  to subvert a man in his cause, the Lord doesn’t approve. ",
      "37": "  Who is he who says, and it comes to pass,   when the Lord doesn’t command it? ",
      "38": "  Doesn’t evil and good come out of the mouth of the Most High? ",
      "39": "  Why should a living man complain,   a man for the punishment of his sins? ",
      "40": "  Let us search and try our ways,   and turn again to Yahweh. ",
      "41": "  Let’s lift up our heart with our hands to God  in the heavens. ",
      "42": "  “We have transgressed and have rebelled.   You have not pardoned. ",
      "43": "  “You have covered us with anger and pursued us.   You have killed.   You have not pitied. ",
      "44": "  You have covered yourself with a cloud,   so that no prayer can pass through. ",
      "45": "  You have made us an off-scouring and refuse   in the middle of the peoples. ",
      "46": "  “All our enemies have opened their mouth wide against us. ",
      "47": "  Terror and the pit have come on us,   devastation and destruction.” ",
      "48": "  My eye runs down with streams of water,   for the destruction of the daughter of my people. ",
      "49": "  My eye pours down   and doesn’t cease,   without any intermission, ",
      "50": "  until Yahweh looks down,   and sees from heaven. ",
      "51": "  My eye affects my soul,   because of all the daughters of my city. ",
      "52": "  They have chased me relentlessly like a bird,   those who are my enemies without cause. ",
      "53": "  They have cut off my life in the dungeon,   and have cast a stone on me. ",
      "54": "  Waters flowed over my head.   I said, “I am cut off.” ",
      "55": "  I called on your name, Yahweh,   out of the lowest dungeon. ",
      "56": "  You heard my voice:   “Don’t hide your ear from my sighing,   and my cry.” ",
      "57": "  You came near in the day that I called on you.   You said, “Don’t be afraid.” ",
      "58": "  Lord, you have pleaded the causes of my soul.   You have redeemed my life. ",
      "59": "  Yahweh, you have seen my wrong.   Judge my cause. ",
      "60": "  You have seen all their vengeance   and all their plans against me. ",
      "61": "  You have heard their reproach, Yahweh,   and all their plans against me, ",
      "62": "  the lips of those that rose up against me,   and their plots against me all day long. ",
      "63": "  You see their sitting down and their rising up.   I am their song. ",
      "64": "  You will pay them back, Yahweh,   according to the work of their hands. ",
      "65": "  You will give them hardness of heart,   your curse to them. ",
      "66": "  You will pursue them in anger,   and destroy them from under the heavens of Yahweh."
    },
    "4": {
      "1": "  How the gold has become dim!   The most pure gold has changed!   The stones of the sanctuary are poured out   at the head of every street. ",
      "2": "  The precious sons of Zion,   comparable to fine gold,   how they are esteemed as earthen pitchers,   the work of the hands of the potter! ",
      "3": "  Even the jackals offer their breast.   They nurse their young ones.   But the daughter of my people has become cruel,   like the ostriches in the wilderness. ",
      "4": "  The tongue of the nursing child clings to the roof of his mouth for thirst.   The young children ask for bread,   and no one breaks it for them. ",
      "5": "  Those who ate delicacies are desolate in the streets.   Those who were brought up in purple embrace dunghills. ",
      "6": "  For the iniquity of the daughter of my people is greater than the sin of Sodom,   which was overthrown as in a moment.   No hands were laid on her. ",
      "7": "  Her nobles were purer than snow.   They were whiter than milk.   They were more ruddy in body than rubies.   Their polishing was like sapphire. ",
      "8": "  Their appearance is blacker than a coal.   They are not known in the streets.   Their skin clings to their bones.   It is withered.   It has become like wood. ",
      "9": "  Those who are killed with the sword are better than those who are killed with hunger;   for these pine away, stricken through,   for lack of the fruits of the field. ",
      "10": "  The hands of the pitiful women have boiled their own children.   They were their food in the destruction of the daughter of my people. ",
      "11": "  Yahweh has accomplished his wrath.   He has poured out his fierce anger.   He has kindled a fire in Zion,   which has devoured its foundations. ",
      "12": "  The kings of the earth didn’t believe,   neither did all the inhabitants of the world,   that the adversary and the enemy would enter into the gates of Jerusalem. ",
      "13": "  It is because of the sins of her prophets   and the iniquities of her priests,   that have shed the blood of the just in the middle of her. ",
      "14": "  They wander as blind men in the streets.   They are polluted with blood,   So that men can’t touch their garments. ",
      "15": "  “Go away!” they cried to them.   “Unclean! Go away! Go away! Don’t touch!   When they fled away and wandered, men said among the nations,   “They can’t live here any more.” ",
      "16": "  Yahweh’s anger has scattered them.   He will not pay attention to them any more.   They didn’t respect the persons of the priests.   They didn’t favor the elders. ",
      "17": "  Our eyes still fail,   looking in vain for our help.   In our watching we have watched for a nation that could not save. ",
      "18": "  They hunt our steps,   so that we can’t go in our streets.   Our end is near.   Our days are fulfilled,   for our end has come. ",
      "19": "  Our pursuers were swifter than the eagles of the sky.   They chased us on the mountains.   They set an ambush for us in the wilderness. ",
      "20": "  The breath of our nostrils,   the anointed of Yahweh,   was taken in their pits;   of whom we said,   under his shadow we will live among the nations. ",
      "21": "  Rejoice and be glad, daughter of Edom,   who dwells in the land of Uz.   The cup will pass through to you also.   You will be drunken,   and will make yourself naked. ",
      "22": "  The punishment of your iniquity is accomplished, daughter of Zion.   He will no more carry you away into captivity.   He will visit your iniquity, daughter of Edom.   He will uncover your sins."
    },
    "5": {
      "1": "  Remember, Yahweh, what has come on us.   Look, and see our reproach. ",
      "2": "  Our inheritance has been turned over to strangers,   our houses to aliens. ",
      "3": "  We are orphans and fatherless.   Our mothers are as widows. ",
      "4": "  We must pay for water to drink.   Our wood is sold to us. ",
      "5": "  Our pursuers are on our necks.   We are weary, and have no rest. ",
      "6": "  We have given our hands to the Egyptians,   and to the Assyrians, to be satisfied with bread. ",
      "7": "  Our fathers sinned, and are no more.   We have borne their iniquities. ",
      "8": "  Servants rule over us.   There is no one to deliver us out of their hand. ",
      "9": "  We get our bread at the peril of our lives,   because of the sword in the wilderness. ",
      "10": "  Our skin is black like an oven,   because of the burning heat of famine. ",
      "11": "  They ravished the women in Zion,   the virgins in the cities of Judah. ",
      "12": "  Princes were hanged up by their hands.   The faces of elders were not honored. ",
      "13": "  The young men carry millstones.   The children stumbled under loads of wood. ",
      "14": "  The elders have ceased from the gate,   and the young men from their music. ",
      "15": "  The joy of our heart has ceased.   Our dance is turned into mourning. ",
      "16": "  The crown has fallen from our head.   Woe to us, for we have sinned! ",
      "17": "  For this our heart is faint.   For these things our eyes are dim: ",
      "18": "  for the mountain of Zion, which is desolate.   The foxes walk on it. ",
      "19": "  You, Yahweh, remain forever.   Your throne is from generation to generation. ",
      "20": "  Why do you forget us forever,   and forsake us for so long a time? ",
      "21": "  Turn us to yourself, Yahweh, and we will be turned.   Renew our days as of old. ",
      "22": "  But you have utterly rejected us.   You are very angry against us."
    }
  },
  "ezekiel": {
    "1": {
      "1": "Now in the thirtieth year, in the fourth month, in the fifth day of the month, as I was among the captives by the river Chebar, the heavens were opened, and I saw visions of God.  ",
      "2": "In the fifth of the month, which was the fifth year of King Jehoiachin’s captivity,",
      "3": "Yahweh’s  word came to Ezekiel the priest, the son of Buzi, in the land of the Chaldeans by the river Chebar; and Yahweh’s hand was there on him. ",
      "4": "I looked, and behold,  a stormy wind came out of the north: a great cloud, with flashing lightning, and a brightness around it, and out of the middle of it as it were glowing metal, out of the middle of the fire.",
      "5": "Out of its center came the likeness of four living creatures. This was their appearance: They had the likeness of a man.",
      "6": "Everyone had four faces, and each one of them had four wings.",
      "7": "Their feet were straight feet. The sole of their feet was like the sole of a calf’s foot; and they sparkled like burnished bronze.",
      "8": "They had the hands of a man under their wings on their four sides. The four of them had their faces and their wings like this:",
      "9": "Their wings were joined to one another. They didn’t turn when they went. Each one went straight forward. ",
      "10": "As for the likeness of their faces, they had the face of a man. The four of them had the face of a lion on the right side. The four of them had the face of an ox on the left side. The four of them also had the face of an eagle.",
      "11": "Such were their faces. Their wings were spread out above. Two wings of each one touched another, and two covered their bodies.",
      "12": "Each one went straight forward. Where the spirit was to go, they went. They didn’t turn when they went.",
      "13": "As for the likeness of the living creatures, their appearance was like burning coals of fire, like the appearance of torches. The fire went up and down among the living creatures. The fire was bright, and lightning went out of the fire.",
      "14": "The living creatures ran and returned as the appearance of a flash of lightning. ",
      "15": "Now as I saw the living creatures, behold, there was one wheel on the earth beside the living creatures, for each of the four faces of it.",
      "16": "The appearance of the wheels and their work was like a beryl. The four of them had one likeness. Their appearance and their work was as it were a wheel within a wheel.",
      "17": "When they went, they went in their four directions. They didn’t turn when they went.",
      "18": "As for their rims, they were high and dreadful; and the four of them had their rims full of eyes all around. ",
      "19": "When the living creatures went, the wheels went beside them. When the living creatures were lifted up from the earth, the wheels were lifted up.",
      "20": "Wherever the spirit was to go, they went. The spirit was to go there. The wheels were lifted up beside them; for the spirit of the living creature was in the wheels.",
      "21": "When those went, these went. When those stood, these stood. When those were lifted up from the earth, the wheels were lifted up beside them; for the spirit of the living creature was in the wheels. ",
      "22": "Over the head of the living creature there was the likeness of an expanse, like an awesome crystal to look at, stretched out over their heads above.",
      "23": "Under the expanse, their wings were straight, one toward the other. Each one had two which covered on this side, and each one had two which covered their bodies on that side.",
      "24": "When they went, I heard the noise of their wings like the noise of great waters, like the voice of the Almighty, a noise of tumult like the noise of an army. When they stood, they let down their wings. ",
      "25": "There was a voice above the expanse that was over their heads. When they stood, they let down their wings.",
      "26": "Above the expanse that was over their heads was the likeness of a throne, as the appearance of a sapphire  stone. On the likeness of the throne was a likeness as the appearance of a man on it above.",
      "27": "I saw as it were glowing metal, as the appearance of fire within it all around, from the appearance of his waist and upward; and from the appearance of his waist and downward I saw as it were the appearance of fire, and there was brightness around him.",
      "28": "As the appearance of the rainbow that is in the cloud in the day of rain, so was the appearance of the brightness all around. This was the appearance of the likeness of Yahweh’s glory. When I saw it, I fell on my face, and I heard a voice of one that spoke."
    },
    "2": {
      "1": "He said to me, “Son of man, stand on your feet, and I will speak with you.”",
      "2": "The Spirit entered into me when he spoke to me, and set me on my feet; and I heard him who spoke to me. ",
      "3": "He said to me, “Son of man, I send you to the children of Israel, to a nation of rebels who have rebelled against me. They and their fathers have transgressed against me even to this very day.",
      "4": "The children are impudent and stiff-hearted. I am sending you to them, and you shall tell them, ‘This is what the Lord  Yahweh says.’",
      "5": "They, whether they will hear, or whether they will refuse—for they are a rebellious house—yet they will know that there has been a prophet among them.",
      "6": "You, son of man, don’t be afraid of them, neither be afraid of their words, though briers and thorns are with you, and you dwell among scorpions. Don’t be afraid of their words, nor be dismayed at their looks, though they are a rebellious house.",
      "7": "You shall speak my words to them, whether they will hear or whether they will refuse; for they are most rebellious.",
      "8": "But you, son of man, hear what I tell you. Don’t be rebellious like that rebellious house. Open your mouth, and eat that which I give you.” ",
      "9": "When I looked, behold, a hand was stretched out to me; and behold, a scroll of a book was in it.",
      "10": "He spread it before me. It was written within and without; and lamentations, mourning, and woe were written in it."
    },
    "3": {
      "1": "He said to me, “Son of man, eat what you find. Eat this scroll, and go, speak to the house of Israel.” ",
      "2": "So I opened my mouth, and he caused me to eat the scroll. ",
      "3": "He said to me, “Son of man, eat this scroll that I give you and fill your belly and your bowels with it.” Then I ate it. It was as sweet as honey in my mouth. ",
      "4": "He said to me, “Son of man, go to the house of Israel, and speak my words to them.",
      "5": "For you are not sent to a people of a strange speech and of a hard language, but to the house of Israel—",
      "6": "not to many peoples of a strange speech and of a hard language, whose words you can’t understand. Surely, if I sent you to them, they would listen to you.",
      "7": "But the house of Israel will not listen to you, for they will not listen to me; for all the house of Israel are obstinate  and hard-hearted.",
      "8": "Behold, I have made your face hard against their faces, and your forehead hard against their foreheads.",
      "9": "I have made your forehead as a diamond, harder than flint. Don’t be afraid of them, neither be dismayed at their looks, though they are a rebellious house.” ",
      "10": "Moreover he said to me, “Son of man, receive in your heart and hear with your ears all my words that I speak to you.",
      "11": "Go to them of the captivity, to the children of your people, and speak to them, and tell them, ‘This is what the Lord Yahweh says,’ whether they will hear, or whether they will refuse.” ",
      "12": "Then the Spirit lifted me up, and I heard behind me the voice of a great rushing, saying, “Blessed be Yahweh’s glory from his place.”",
      "13": "I heard the noise of the wings of the living creatures as they touched one another, and the noise of the wheels beside them, even the noise of a great rushing.",
      "14": "So the Spirit lifted me up, and took me away; and I went in bitterness, in the heat of my spirit; and Yahweh’s hand was strong on me.",
      "15": "Then I came to them of the captivity at Tel Aviv who lived by the river Chebar, and to where they lived; and I sat there overwhelmed among them seven days. ",
      "16": "At the end of seven days, Yahweh’s word came to me, saying,",
      "17": "“Son of man, I have made you a watchman to the house of Israel. Therefore hear the word from my mouth, and warn them from me.",
      "18": "When I tell the wicked, ‘You will surely die;’ and you give him no warning, nor speak to warn the wicked from his wicked way, to save his life, that wicked man will die in his iniquity; but I will require his blood at your hand.",
      "19": "Yet if you warn the wicked, and he doesn’t turn from his wickedness, nor from his wicked way, he will die in his iniquity; but you have delivered your soul.” ",
      "20": "“Again, when a righteous man turns from his righteousness and commits iniquity, and I lay a stumbling block before him, he will die. Because you have not given him warning, he will die in his sin, and his righteous deeds which he has done will not be remembered; but I will require his blood at your hand.",
      "21": "Nevertheless if you warn the righteous man, that the righteous not sin, and he does not sin, he will surely live, because he took warning; and you have delivered your soul.” ",
      "22": "Yahweh’s hand was there on me; and he said to me, “Arise, go out into the plain, and I will talk with you there.” ",
      "23": "Then I arose, and went out into the plain, and behold, Yahweh’s glory stood there, like the glory which I saw by the river Chebar. Then I fell on my face. ",
      "24": "Then the Spirit entered into me and set me on my feet. He spoke with me, and said to me, “Go, shut yourself inside your house.",
      "25": "But you, son of man, behold, they will put ropes on you, and will bind you with them, and you will not go out among them.",
      "26": "I will make your tongue stick to the roof of your mouth so that you will be mute and will not be able to correct them, for they are a rebellious house.",
      "27": "But when I speak with you, I will open your mouth, and you shall tell them, ‘This is what the Lord Yahweh says.’ He who hears, let him hear; and he who refuses, let him refuse; for they are a rebellious house.”"
    },
    "4": {
      "1": "“You also, son of man, take a tile, and lay it before yourself, and portray on it a city, even Jerusalem.",
      "2": "Lay siege against it, build forts against it, and cast up a mound against it. Also set camps against it and plant battering rams against it all around.",
      "3": "Take for yourself an iron pan and set it for a wall of iron between you and the city. Then set your face toward it. It will be besieged, and you shall lay siege against it. This shall be a sign to the house of Israel. ",
      "4": "“Moreover lie on your left side, and lay the iniquity of the house of Israel on it. According to the number of the days that you shall lie on it, you shall bear their iniquity.",
      "5": "For I have appointed the years of their iniquity to be to you a number of days, even three hundred ninety days. So you shall bear the iniquity of the house of Israel. ",
      "6": "“Again, when you have accomplished these, you shall lie on your right side, and shall bear the iniquity of the house of Judah. I have appointed forty days, each day for a year, to you.",
      "7": "You shall set your face toward the siege of Jerusalem, with your arm uncovered; and you shall prophesy against it.",
      "8": "Behold, I put ropes on you, and you shall not turn yourself from one side to the other, until you have accomplished the days of your siege. ",
      "9": "“Take for yourself also wheat, barley, beans, lentils, millet, and spelt, and put them in one vessel. Make bread of it. According to the number of the days that you will lie on your side, even three hundred ninety days, you shall eat of it.",
      "10": "Your food which you shall eat shall be by weight, twenty shekels  a day. From time to time you shall eat it.",
      "11": "You shall drink water by measure, the sixth part of a hin.  From time to time you shall drink.",
      "12": "You shall eat it as barley cakes, and you shall bake it in their sight with dung that comes out of man.”",
      "13": "Yahweh said, “Even thus will the children of Israel eat their bread unclean, among the nations where I will drive them.” ",
      "14": "Then I said, “Ah Lord Yahweh! Behold, my soul has not been polluted; for from my youth up even until now I have not eaten of that which dies of itself, or is torn of animals. No abominable meat has come into my mouth!” ",
      "15": "Then he said to me, “Behold, I have given you cow’s dung for man’s dung, and you shall prepare your bread on it.” ",
      "16": "Moreover he said to me, “Son of man, behold, I will break the staff of bread in Jerusalem. They will eat bread by weight, and with fearfulness. They will drink water by measure, and in dismay;",
      "17": "that they may lack bread and water, be dismayed one with another, and pine away in their iniquity."
    },
    "5": {
      "1": "“You, son of man, take a sharp sword. You shall take it as a barber’s razor to yourself, and shall cause it to pass over your head and over your beard. Then take balances to weigh and divide the hair.",
      "2": "A third part you shall burn in the fire in the middle of the city, when the days of the siege are fulfilled. You shall take a third part, and strike with the sword around it. A third part you shall scatter to the wind, and I will draw out a sword after them.",
      "3": "You shall take a small number of these and bind them in the folds of your robe.",
      "4": "Of these again you shall take, and cast them into the middle of the fire, and burn them in the fire. From it a fire will come out into all the house of Israel. ",
      "5": "“The Lord Yahweh says: ‘This is Jerusalem. I have set her in the middle of the nations, and countries are around her.",
      "6": "She has rebelled against my ordinances in doing wickedness more than the nations, and against my statutes more than the countries that are around her; for they have rejected my ordinances, and as for my statutes, they have not walked in them.’ ",
      "7": "“Therefore the Lord Yahweh says: ‘Because you are more turbulent than the nations that are around you, and have not walked in my statutes, neither have kept my ordinances, neither have followed the ordinances of the nations that are around you;",
      "8": "therefore the Lord Yahweh says: ‘Behold, I, even I, am against you; and I will execute judgments among you in the sight of the nations.",
      "9": "I will do in you that which I have not done, and which I will not do anything like it any more, because of all your abominations.",
      "10": "Therefore the fathers will eat the sons within you, and the sons will eat their fathers. I will execute judgments on you; and I will scatter the whole remnant of you to all the winds.",
      "11": "Therefore as I live,’ says the Lord Yahweh, ‘surely, because you have defiled my sanctuary with all your detestable things, and with all your abominations, therefore I will also diminish you. My eye won’t spare, and I will have no pity.",
      "12": "A third part of you will die with the pestilence, and they will be consumed with famine within you. A third part will fall by the sword around you. A third part I will scatter to all the winds, and will draw out a sword after them. ",
      "13": "“‘Thus my anger will be accomplished, and I will cause my wrath toward them to rest, and I will be comforted. They will know that I, Yahweh, have spoken in my zeal, when I have accomplished my wrath on them. ",
      "14": "“‘Moreover I will make you a desolation and a reproach among the nations that are around you, in the sight of all that pass by.",
      "15": "So it will be a reproach and a taunt, an instruction and an astonishment, to the nations that are around you, when I execute judgments on you in anger and in wrath, and in wrathful rebukes—I, Yahweh, have spoken it—",
      "16": "when I send on them the evil arrows of famine that are for destruction, which I will send to destroy you. I will increase the famine on you and will break your staff of bread.",
      "17": "I will send on you famine and evil animals, and they will bereave you. Pestilence and blood will pass through you. I will bring the sword on you. I, Yahweh, have spoken it.’”"
    },
    "6": {
      "1": "Yahweh’s word came to me, saying,",
      "2": "“Son of man, set your face toward the mountains of Israel, and prophesy to them,",
      "3": "and say, ‘You mountains of Israel, hear the word of the Lord Yahweh! The Lord Yahweh says to the mountains and to the hills, to the watercourses and to the valleys: “Behold, I, even I, will bring a sword on you, and I will destroy your high places.",
      "4": "Your altars will become desolate, and your incense altars will be broken. I will cast down your slain men before your idols.",
      "5": "I will lay the dead bodies of the children of Israel before their idols. I will scatter your bones around your altars.",
      "6": "In all your dwelling places, the cities will be laid waste and the high places will be desolate, so that your altars may be laid waste and made desolate, and your idols may be broken and cease, and your incense altars may be cut down, and your works may be abolished.",
      "7": "The slain will fall among you, and you will know that I am Yahweh. ",
      "8": "“‘“Yet I will leave a remnant, in that you will have some that escape the sword among the nations, when you are scattered through the countries.",
      "9": "Those of you that escape will remember me among the nations where they are carried captive, how I have been broken with their lewd heart, which has departed from me, and with their eyes, which play the prostitute after their idols. Then they will loathe themselves in their own sight for the evils which they have committed in all their abominations.",
      "10": "They will know that I am Yahweh. I have not said in vain that I would do this evil to them.”’ ",
      "11": "“The Lord Yahweh says: ‘Strike with your hand, and stamp with your foot, and say, “Alas!”, because of all the evil abominations of the house of Israel; for they will fall by the sword, by the famine, and by the pestilence.",
      "12": "He who is far off will die of the pestilence. He who is near will fall by the sword. He who remains and is besieged will die by the famine. Thus I will accomplish my wrath on them.",
      "13": "You will know that I am Yahweh when their slain men are among their idols around their altars, on every high hill, on all the tops of the mountains, under every green tree, and under every thick oak—the places where they offered pleasant aroma to all their idols.",
      "14": "I will stretch out my hand on them and make the land desolate and waste, from the wilderness toward Diblah, throughout all their habitations. Then they will know that I am Yahweh.’”  "
    }
  }
};

