
	
export const bib_verses = {
  "luke": {
    "17": {
      "1": "He said to the disciples,  “It is impossible that no occasions of stumbling should come, but woe to him through whom they come!  ",
      "2": " It would be better for him if a millstone were hung around his neck, and he were thrown into the sea, rather than that he should cause one of these little ones to stumble.  ",
      "3": " Be careful. If your brother sins against you, rebuke him. If he repents, forgive him.  ",
      "4": " If he sins against you seven times in the day, and seven times returns, saying, ‘I repent,’ you shall forgive him.”  ",
      "5": "The apostles said to the Lord, “Increase our faith.” ",
      "6": "The Lord said,  “If you had faith like a grain of mustard seed, you would tell this sycamore tree, ‘Be uprooted and be planted in the sea,’ and it would obey you.  ",
      "7": " But who is there among you, having a servant plowing or keeping sheep, that will say when he comes in from the field, ‘Come immediately and sit down at the table’?  ",
      "8": " Wouldn’t he rather tell him, ‘Prepare my supper, clothe yourself properly, and serve me while I eat and drink. Afterward you shall eat and drink’?  ",
      "9": " Does he thank that servant because he did the things that were commanded? I think not.  ",
      "10": " Even so you also, when you have done all the things that are commanded you, say, ‘We are unworthy servants. We have done our duty.’”   ",
      "11": "As he was on his way to Jerusalem, he was passing along the borders of Samaria and Galilee.",
      "12": "As he entered into a certain village, ten men who were lepers met him, who stood at a distance.",
      "13": "They lifted up their voices, saying, “Jesus, Master, have mercy on us!” ",
      "14": "When he saw them, he said to them,  “Go and show yourselves to the priests.”  As they went, they were cleansed.",
      "15": "One of them, when he saw that he was healed, turned back, glorifying God with a loud voice.",
      "16": "He fell on his face at Jesus’ feet, giving him thanks; and he was a Samaritan. ",
      "17": "Jesus answered,  “Weren’t the ten cleansed? But where are the nine?  ",
      "18": " Were there none found who returned to give glory to God, except this foreigner?” ",
      "19": "Then he said to him,  “Get up, and go your way. Your faith has healed you.”  ",
      "20": "Being asked by the Pharisees when God’s Kingdom would come, he answered them,  “God’s Kingdom doesn’t come with observation;  ",
      "21": " neither will they say, ‘Look, here!’ or, ‘Look, there!’ for behold, God’s Kingdom is within you.”  ",
      "22": "He said to the disciples,  “The days will come when you will desire to see one of the days of the Son of Man, and you will not see it.  ",
      "23": " They will tell you, ‘Look, here!’ or ‘Look, there!’ Don’t go away or follow after them,  ",
      "24": " for as the lightning, when it flashes out of one part under the sky, shines to another part under the sky, so will the Son of Man be in his day.  ",
      "25": " But first, he must suffer many things and be rejected by this generation.  ",
      "26": " As it was in the days of Noah, even so it will also be in the days of the Son of Man.  ",
      "27": " They ate, they drank, they married, and they were given in marriage until the day that Noah entered into the ship, and the flood came and destroyed them all.  ",
      "28": " Likewise, even as it was in the days of Lot: they ate, they drank, they bought, they sold, they planted, they built;  ",
      "29": " but in the day that Lot went out from Sodom, it rained fire and sulfur from the sky and destroyed them all.  ",
      "30": " It will be the same way in the day that the Son of Man is revealed.  ",
      "31": " In that day, he who will be on the housetop and his goods in the house, let him not go down to take them away. Let him who is in the field likewise not turn back.  ",
      "32": " Remember Lot’s wife!  ",
      "33": " Whoever seeks to save his life loses it, but whoever loses his life preserves it.  ",
      "34": " I tell you, in that night there will be two people in one bed. One will be taken and the other will be left.  ",
      "35": " There will be two grinding grain together. One will be taken and the other will be left.” ",
      "36": "  ",
      "37": "They, answering, asked him, “Where, Lord?” He said to them,  “Where the body is, there the vultures will also be gathered together.” "
    },
    "18": {
      "1": "He also spoke a parable to them that they must always pray and not give up,",
      "2": "saying,  “There was a judge in a certain city who didn’t fear God and didn’t respect man.  ",
      "3": " A widow was in that city, and she often came to him, saying, ‘Defend me from my adversary!’  ",
      "4": " He wouldn’t for a while; but afterward he said to himself, ‘Though I neither fear God nor respect man,  ",
      "5": " yet because this widow bothers me, I will defend her, or else she will wear me out by her continual coming.’”  ",
      "6": "The Lord said,  “Listen to what the unrighteous judge says.  ",
      "7": " Won’t God avenge his chosen ones who are crying out to him day and night, and yet he exercises patience with them?  ",
      "8": " I tell you that he will avenge them quickly. Nevertheless, when the Son of Man comes, will he find faith on the earth?”  ",
      "9": "He also spoke this parable to certain people who were convinced of their own righteousness, and who despised all others:",
      "10": " “Two men went up into the temple to pray; one was a Pharisee, and the other was a tax collector.  ",
      "11": " The Pharisee stood and prayed by himself like this: ‘God, I thank you that I am not like the rest of men: extortionists, unrighteous, adulterers, or even like this tax collector.  ",
      "12": " I fast twice a week. I give tithes of all that I get.’  ",
      "13": " But the tax collector, standing far away, wouldn’t even lift up his eyes to heaven, but beat his chest, saying, ‘God, be merciful to me, a sinner!’  ",
      "14": " I tell you, this man went down to his house justified rather than the other; for everyone who exalts himself will be humbled, but he who humbles himself will be exalted.”  ",
      "15": "They were also bringing their babies to him, that he might touch them. But when the disciples saw it, they rebuked them.",
      "16": "Jesus summoned them, saying,  “Allow the little children to come to me, and don’t hinder them, for God’s Kingdom belongs to such as these.  ",
      "17": " Most certainly, I tell you, whoever doesn’t receive God’s Kingdom like a little child, he will in no way enter into it.”  ",
      "18": "A certain ruler asked him, saying, “Good Teacher, what shall I do to inherit eternal life?” ",
      "19": "Jesus asked him,  “Why do you call me good? No one is good, except one: God.  ",
      "20": " You know the commandments: ‘Don’t commit adultery,’ ‘Don’t murder,’ ‘Don’t steal,’ ‘Don’t give false testimony,’ ‘Honor your father and your mother.’”     ",
      "21": "He said, “I have observed all these things from my youth up.” ",
      "22": "When Jesus heard these things, he said to him,  “You still lack one thing. Sell all that you have and distribute it to the poor. Then you will have treasure in heaven; then come, follow me.”  ",
      "23": "But when he heard these things, he became very sad, for he was very rich. ",
      "24": "Jesus, seeing that he became very sad, said,  “How hard it is for those who have riches to enter into God’s Kingdom!  ",
      "25": " For it is easier for a camel to enter in through a needle’s eye than for a rich man to enter into God’s Kingdom.”  ",
      "26": "Those who heard it said, “Then who can be saved?” ",
      "27": "But he said,  “The things which are impossible with men are possible with God.”  ",
      "28": "Peter said, “Look, we have left everything and followed you.” ",
      "29": "He said to them,  “Most certainly I tell you, there is no one who has left house, or wife, or brothers, or parents, or children, for God’s Kingdom’s sake,  ",
      "30": " who will not receive many times more in this time, and in the world to come, eternal life.”  ",
      "31": "He took the twelve aside and said to them,  “Behold, we are going up to Jerusalem, and all the things that are written through the prophets concerning the Son of Man will be completed.  ",
      "32": " For he will be delivered up to the Gentiles, will be mocked, treated shamefully, and spit on.  ",
      "33": " They will scourge and kill him. On the third day, he will rise again.”  ",
      "34": "They understood none of these things. This saying was hidden from them, and they didn’t understand the things that were said. ",
      "35": "As he came near Jericho, a certain blind man sat by the road, begging.",
      "36": "Hearing a multitude going by, he asked what this meant.",
      "37": "They told him that Jesus of Nazareth was passing by.",
      "38": "He cried out, “Jesus, you son of David, have mercy on me!”",
      "39": "Those who led the way rebuked him, that he should be quiet; but he cried out all the more, “You son of David, have mercy on me!” ",
      "40": "Standing still, Jesus commanded him to be brought to him. When he had come near, he asked him,",
      "41": " “What do you want me to do?”  He said, “Lord, that I may see again.” ",
      "42": "Jesus said to him,  “Receive your sight. Your faith has healed you.”   ",
      "43": "Immediately he received his sight and followed him, glorifying God. All the people, when they saw it, praised God."
    },
    "19": {
      "1": "He entered and was passing through Jericho.",
      "2": "There was a man named Zacchaeus. He was a chief tax collector, and he was rich.",
      "3": "He was trying to see who Jesus was, and couldn’t because of the crowd, because he was short.",
      "4": "He ran on ahead and climbed up into a sycamore tree to see him, for he was going to pass that way.",
      "5": "When Jesus came to the place, he looked up and saw him, and said to him,  “Zacchaeus, hurry and come down, for today I must stay at your house.”  ",
      "6": "He hurried, came down, and received him joyfully.",
      "7": "When they saw it, they all murmured, saying, “He has gone in to lodge with a man who is a sinner.” ",
      "8": "Zacchaeus stood and said to the Lord, “Behold, Lord, half of my goods I give to the poor. If I have wrongfully exacted anything of anyone, I restore four times as much.” ",
      "9": "Jesus said to him,  “Today, salvation has come to this house, because he also is a son of Abraham.  ",
      "10": " For the Son of Man came to seek and to save that which was lost.”   ",
      "11": "As they heard these things, he went on and told a parable, because he was near Jerusalem, and they supposed that God’s Kingdom would be revealed immediately.",
      "12": "He said therefore,  “A certain nobleman went into a far country to receive for himself a kingdom and to return.  ",
      "13": " He called ten servants of his and gave them ten mina coins,     and told them, ‘Conduct business until I come.’  ",
      "14": " But his citizens hated him, and sent an envoy after him, saying, ‘We don’t want this man to reign over us.’  ",
      "15": " “When he had come back again, having received the kingdom, he commanded these servants, to whom he had given the money, to be called to him, that he might know what they had gained by conducting business.  ",
      "16": " The first came before him, saying, ‘Lord, your mina has made ten more minas.’  ",
      "17": " “He said to him, ‘Well done, you good servant! Because you were found faithful with very little, you shall have authority over ten cities.’   ",
      "18": " “The second came, saying, ‘Your mina, Lord, has made five minas.’   ",
      "19": " “So he said to him, ‘And you are to be over five cities.’   ",
      "20": " Another came, saying, ‘Lord, behold, your mina, which I kept laid away in a handkerchief,  ",
      "21": " for I feared you, because you are an exacting man. You take up that which you didn’t lay down, and reap that which you didn’t sow.’  ",
      "22": " “He said to him, ‘Out of your own mouth I will judge you, you wicked servant! You knew that I am an exacting man, taking up that which I didn’t lay down and reaping that which I didn’t sow.  ",
      "23": " Then why didn’t you deposit my money in the bank, and at my coming, I might have earned interest on it?’  ",
      "24": " He said to those who stood by, ‘Take the mina away from him and give it to him who has the ten minas.’  ",
      "25": " “They said to him, ‘Lord, he has ten minas!’  ",
      "26": " ‘For I tell you that to everyone who has, will more be given; but from him who doesn’t have, even that which he has will be taken away from him.  ",
      "27": " But bring those enemies of mine who didn’t want me to reign over them here, and kill them before me.’” ",
      "28": "Having said these things, he went on ahead, going up to Jerusalem. ",
      "29": "When he came near to Bethsphage  and Bethany, at the mountain that is called Olivet, he sent two of his disciples,",
      "30": "saying,  “Go your way into the village on the other side, in which, as you enter, you will find a colt tied, which no man has ever sat upon. Untie it and bring it.  ",
      "31": " If anyone asks you, ‘Why are you untying it?’ say to him: ‘The Lord needs it.’”  ",
      "32": "Those who were sent went away and found things just as he had told them.",
      "33": "As they were untying the colt, its owners said to them, “Why are you untying the colt?”",
      "34": "They said, “The Lord needs it.”",
      "35": "Then they brought it to Jesus. They threw their cloaks on the colt and sat Jesus on them.",
      "36": "As he went, they spread their cloaks on the road. ",
      "37": "As he was now getting near, at the descent of the Mount of Olives, the whole multitude of the disciples began to rejoice and praise God with a loud voice for all the mighty works which they had seen,",
      "38": "saying, “Blessed is the King who comes in the name of the Lord!   Peace in heaven, and glory in the highest!” ",
      "39": "Some of the Pharisees from the multitude said to him, “Teacher, rebuke your disciples!” ",
      "40": "He answered them,  “I tell you that if these were silent, the stones would cry out.”  ",
      "41": "When he came near, he saw the city and wept over it,",
      "42": "saying,  “If you, even you, had known today the things which belong to your peace! But now, they are hidden from your eyes.  ",
      "43": " For the days will come on you when your enemies will throw up a barricade against you, surround you, hem you in on every side,  ",
      "44": " and will dash you and your children within you to the ground. They will not leave in you one stone on another, because you didn’t know the time of your visitation.”  ",
      "45": "He entered into the temple and began to drive out those who bought and sold in it,",
      "46": "saying to them,  “It is written, ‘My house is a house of prayer,’     but you have made it a ‘den of robbers’!”    ",
      "47": "He was teaching daily in the temple, but the chief priests, the scribes, and the leading men among the people sought to destroy him.",
      "48": "They couldn’t find what they might do, for all the people hung on to every word that he said."
    },
    "20": {
      "1": "On one of those days, as he was teaching the people in the temple and preaching the Good News, the  priests and scribes came to him with the elders.",
      "2": "They asked him, “Tell us: by what authority do you do these things? Or who is giving you this authority?” ",
      "3": "He answered them,  “I also will ask you one question. Tell me:  ",
      "4": " the baptism of John, was it from heaven, or from men?”  ",
      "5": "They reasoned with themselves, saying, “If we say, ‘From heaven,’ he will say, ‘Why didn’t you believe him?’",
      "6": "But if we say, ‘From men,’ all the people will stone us, for they are persuaded that John was a prophet.”",
      "7": "They answered that they didn’t know where it was from. ",
      "8": "Jesus said to them,  “Neither will I tell you by what authority I do these things.”  ",
      "9": "He began to tell the people this parable:  “A     man planted a vineyard and rented it out to some farmers, and went into another country for a long time.  ",
      "10": " At the proper season, he sent a servant to the farmers to collect his share of the fruit of the vineyard. But the farmers beat him and sent him away empty.  ",
      "11": " He sent yet another servant, and they also beat him and treated him shamefully, and sent him away empty.  ",
      "12": " He sent yet a third, and they also wounded him and threw him out.  ",
      "13": " The lord of the vineyard said, ‘What shall I do? I will send my beloved son. It may be that seeing him, they will respect him.’  ",
      "14": " “But when the farmers saw him, they reasoned among themselves, saying, ‘This is the heir. Come, let’s kill him, that the inheritance may be ours.’  ",
      "15": " Then they threw him out of the vineyard and killed him. What therefore will the lord of the vineyard do to them?  ",
      "16": " He will come and destroy these farmers, and will give the vineyard to others.”  When they heard that, they said, “May that never be!” ",
      "17": "But he looked at them and said,  “Then what is this that is written,     ‘The stone which the builders rejected     was made the chief cornerstone’?   ",
      "18": "    Everyone who falls on that stone will be broken to pieces,      but it will crush whomever it falls on to dust.”  ",
      "19": "The chief priests and the scribes sought to lay hands on him that very hour, but they feared the people—for they knew he had spoken this parable against them.",
      "20": "They watched him and sent out spies, who pretended to be righteous, that they might trap him in something he said, so as to deliver him up to the power and authority of the governor.",
      "21": "They asked him, “Teacher, we know that you say and teach what is right, and aren’t partial to anyone, but truly teach the way of God.",
      "22": "Is it lawful for us to pay taxes to Caesar, or not?” ",
      "23": "But he perceived their craftiness, and said to them,  “Why do you test me?  ",
      "24": " Show me a denarius. Whose image and inscription are on it?”   They answered, “Caesar’s.” ",
      "25": "He said to them,  “Then give to Caesar the things that are Caesar’s, and to God the things that are God’s.”  ",
      "26": "They weren’t able to trap him in his words before the people. They marveled at his answer and were silent.",
      "27": "Some of the Sadducees came to him, those who deny that there is a resurrection.",
      "28": "They asked him, “Teacher, Moses wrote to us that if a man’s brother dies having a wife, and he is childless, his brother should take the wife and raise up children for his brother.",
      "29": "There were therefore seven brothers. The first took a wife, and died childless.",
      "30": "The second took her as wife, and he died childless.",
      "31": "The third took her, and likewise the seven all left no children, and died.",
      "32": "Afterward the woman also died.",
      "33": "Therefore in the resurrection whose wife of them will she be? For the seven had her as a wife.” ",
      "34": "Jesus said to them,  “The children of this age marry and are given in marriage.  ",
      "35": " But those who are considered worthy to attain to that age and the resurrection from the dead neither marry nor are given in marriage.  ",
      "36": " For they can’t die any more, for they are like the angels and are children of God, being children of the resurrection.  ",
      "37": " But that the dead are raised, even Moses showed at the bush, when he called the Lord ‘The God of Abraham, the God of Isaac, and the God of Jacob.’   ",
      "38": " Now he is not the God of the dead, but of the living, for all are alive to him.”  ",
      "39": "Some of the scribes answered, “Teacher, you speak well.”",
      "40": "They didn’t dare to ask him any more questions. ",
      "41": "He said to them,  “Why do they say that the Christ is David’s son?  ",
      "42": " David himself says in the book of Psalms,     ‘The Lord said to my Lord,     “Sit at my right hand,  ",
      "43": "    until I make your enemies the footstool of your feet.”’    ",
      "44": " “David therefore calls him Lord, so how is he his son?”  ",
      "45": "In the hearing of all the people, he said to his disciples,",
      "46": " “Beware of those scribes who like to walk in long robes, and love greetings in the marketplaces, the best seats in the synagogues, and the best places at feasts;  ",
      "47": " who devour widows’ houses, and for a pretense make long prayers. These will receive greater condemnation.” "
    },
    "21": {
      "1": "He looked up and saw the rich people who were putting their gifts into the treasury.",
      "2": "He saw a certain poor widow casting in two small brass coins. ",
      "3": "He said,  “Truly I tell you, this poor widow put in more than all of them,  ",
      "4": " for all these put in gifts for God from their abundance, but she, out of her poverty, put in all that she had to live on.”  ",
      "5": "As some were talking about the temple and how it was decorated with beautiful stones and gifts, he said,",
      "6": " “As for these things which you see, the days will come in which there will not be left here one stone on another that will not be thrown down.”  ",
      "7": "They asked him, “Teacher, so when will these things be? What is the sign that these things are about to happen?” ",
      "8": "He said,  “Watch out that you don’t get led astray, for many will come in my name, saying, ‘I am he   ,’ and, ‘The time is at hand.’ Therefore don’t follow them.  ",
      "9": " When you hear of wars and disturbances, don’t be terrified, for these things must happen first, but the end won’t come immediately.”  ",
      "10": "Then he said to them,  “Nation will rise against nation, and kingdom against kingdom.  ",
      "11": " There will be great earthquakes, famines, and plagues in various places. There will be terrors and great signs from heaven.  ",
      "12": " But before all these things, they will lay their hands on you and will persecute you, delivering you up to synagogues and prisons, bringing you before kings and governors for my name’s sake.  ",
      "13": " It will turn out as a testimony for you.  ",
      "14": " Settle it therefore in your hearts not to meditate beforehand how to answer,  ",
      "15": " for I will give you a mouth and wisdom which all your adversaries will not be able to withstand or to contradict.  ",
      "16": " You will be handed over even by parents, brothers, relatives, and friends. They will cause some of you to be put to death.  ",
      "17": " You will be hated by all men for my name’s sake.  ",
      "18": " And not a hair of your head will perish.  ",
      "19": " “By your endurance you will win your lives.  ",
      "20": " “But when you see Jerusalem surrounded by armies, then know that its desolation is at hand.  ",
      "21": " Then let those who are in Judea flee to the mountains. Let those who are in the middle of her depart. Let those who are in the country not enter therein.  ",
      "22": " For these are days of vengeance, that all things which are written may be fulfilled.  ",
      "23": " Woe to those who are pregnant and to those who nurse infants in those days! For there will be great distress in the land and wrath to this people.  ",
      "24": " They will fall by the edge of the sword, and will be led captive into all the nations. Jerusalem will be trampled down by the Gentiles until the times of the Gentiles are fulfilled.   ",
      "25": " “There will be signs in the sun, moon, and stars; and on the earth anxiety of nations, in perplexity for the roaring of the sea and the waves;  ",
      "26": " men fainting for fear and for expectation of the things which are coming on the world, for the powers of the heavens will be shaken.  ",
      "27": " Then they will see the Son of Man coming in a cloud with power and great glory.  ",
      "28": " But when these things begin to happen, look up and lift up your heads, because your redemption is near.”  ",
      "29": "He told them a parable.  “See the fig tree and all the trees.  ",
      "30": " When they are already budding, you see it and know by your own selves that the summer is already near.  ",
      "31": " Even so you also, when you see these things happening, know that God’s Kingdom is near.  ",
      "32": " Most certainly I tell you, this generation will not pass away until all things are accomplished.  ",
      "33": " Heaven and earth will pass away, but my words will by no means pass away.  ",
      "34": " “So be careful, or your hearts will be loaded down with carousing, drunkenness, and cares of this life, and that day will come on you suddenly.  ",
      "35": " For it will come like a snare on all those who dwell on the surface of all the earth.  ",
      "36": " Therefore be watchful all the time, praying that you may be counted worthy to escape all these things that will happen, and to stand before the Son of Man.”  ",
      "37": "Every day Jesus was teaching in the temple, and every night he would go out and spend the night on the mountain that is called Olivet.",
      "38": "All the people came early in the morning to him in the temple to hear him."
    },
    "22": {
      "1": "Now the feast of unleavened bread, which is called the Passover, was approaching.",
      "2": "The chief priests and the scribes sought how they might put him to death, for they feared the people. ",
      "3": "Satan entered into Judas, who was also called Iscariot, who was counted with the twelve.",
      "4": "He went away and talked with the chief priests and captains about how he might deliver him to them.",
      "5": "They were glad, and agreed to give him money.",
      "6": "He consented and sought an opportunity to deliver him to them in the absence of the multitude. ",
      "7": "The day of unleavened bread came, on which the Passover must be sacrificed.",
      "8": "Jesus sent Peter and John, saying,  “Go and prepare the Passover for us, that we may eat.”  ",
      "9": "They said to him, “Where do you want us to prepare?” ",
      "10": "He said to them,  “Behold, when you have entered into the city, a man carrying a pitcher of water will meet you. Follow him into the house which he enters.  ",
      "11": " Tell the master of the house, ‘The Teacher says to you, “Where is the guest room, where I may eat the Passover with my disciples?”’  ",
      "12": " He will show you a large, furnished upper room. Make preparations there.”  ",
      "13": "They went, found things as Jesus had told them, and they prepared the Passover. ",
      "14": "When the hour had come, he sat down with the twelve apostles.",
      "15": "He said to them,  “I have earnestly desired to eat this Passover with you before I suffer,  ",
      "16": " for I tell you, I will no longer by any means eat of it until it is fulfilled in God’s Kingdom.” ",
      "17": "He received a cup, and when he had given thanks, he said,  “Take this and share it among yourselves,  ",
      "18": " for I tell you, I will not drink at all again from the fruit of the vine, until God’s Kingdom comes.”  ",
      "19": "He took bread, and when he had given thanks, he broke and gave it to them, saying,  “This is my body which is given for you. Do this in memory of me.” ",
      "20": "Likewise, he took the cup after supper, saying,  “This cup is the new covenant in my blood, which is poured out for you.  ",
      "21": " But behold, the hand of him who betrays me is with me on the table.  ",
      "22": " The Son of Man indeed goes as it has been determined, but woe to that man through whom he is betrayed!”  ",
      "23": "They began to question among themselves which of them it was who would do this thing. ",
      "24": "A dispute also arose among them, which of them was considered to be greatest.",
      "25": "He said to them,  “The kings of the nations lord it over them, and those who have authority over them are called ‘benefactors.’  ",
      "26": " But not so with you. Rather, the one who is greater among you, let him become as the younger, and one who is governing, as one who serves.  ",
      "27": " For who is greater, one who sits at the table, or one who serves? Isn’t it he who sits at the table? But I am among you as one who serves.   ",
      "28": " “But you are those who have continued with me in my trials.  ",
      "29": " I confer on you a kingdom, even as my Father conferred on me,  ",
      "30": " that you may eat and drink at my table in my Kingdom. You will sit on thrones, judging the twelve tribes of Israel.”  ",
      "31": "The Lord said,  “Simon, Simon, behold, Satan asked to have all of you, that he might sift you as wheat,  ",
      "32": " but I prayed for you, that your faith wouldn’t fail. You, when once you have turned again, establish your brothers.”   ",
      "33": "He said to him, “Lord, I am ready to go with you both to prison and to death!” ",
      "34": "He said,  “I tell you, Peter, the rooster will by no means crow today until you deny that you know me three times.”  ",
      "35": "He said to them,  “When I sent you out without purse, bag, and sandals, did you lack anything?”  They said, “Nothing.” ",
      "36": "Then he said to them,  “But now, whoever has a purse, let him take it, and likewise a bag. Whoever has none, let him sell his cloak, and buy a sword.  ",
      "37": " For I tell you that this which is written must still be fulfilled in me: ‘He was counted with transgressors.’    For that which concerns me is being fulfilled.”  ",
      "38": "They said, “Lord, behold, here are two swords.” He said to them,  “That is enough.”  ",
      "39": "He came out and went, as his custom was, to the Mount of Olives. His disciples also followed him.",
      "40": "When he was at the place, he said to them,  “Pray that you don’t enter into temptation.”  ",
      "41": "He was withdrawn from them about a stone’s throw, and he knelt down and prayed,",
      "42": "saying,  “Father, if you are willing, remove this cup from me. Nevertheless, not my will, but yours, be done.”  ",
      "43": "An angel from heaven appeared to him, strengthening him.",
      "44": "Being in agony, he prayed more earnestly. His sweat became like great drops of blood falling down on the ground. ",
      "45": "When he rose up from his prayer, he came to the disciples and found them sleeping because of grief,",
      "46": "and said to them,  “Why do you sleep? Rise and pray that you may not enter into temptation.”  ",
      "47": "While he was still speaking, a crowd appeared. He who was called Judas, one of the twelve, was leading them. He came near to Jesus to kiss him.",
      "48": "But Jesus said to him,  “Judas, do you betray the Son of Man with a kiss?”  ",
      "49": "When those who were around him saw what was about to happen, they said to him, “Lord, shall we strike with the sword?”",
      "50": "A certain one of them struck the servant of the high priest, and cut off his right ear. ",
      "51": "But Jesus answered,  “Let me at least do this” —and he touched his ear and healed him.",
      "52": "Jesus said to the chief priests, captains of the temple, and elders, who had come against him,  “Have you come out as against a robber, with swords and clubs?  ",
      "53": " When I was with you in the temple daily, you didn’t stretch out your hands against me. But this is your hour, and the power of darkness.”   ",
      "54": "They seized him and led him away, and brought him into the high priest’s house. But Peter followed from a distance.",
      "55": "When they had kindled a fire in the middle of the courtyard and had sat down together, Peter sat among them.",
      "56": "A certain servant girl saw him as he sat in the light, and looking intently at him, said, “This man also was with him.” ",
      "57": "He denied Jesus, saying, “Woman, I don’t know him.” ",
      "58": "After a little while someone else saw him and said, “You also are one of them!” But Peter answered, “Man, I am not!” ",
      "59": "After about one hour passed, another confidently affirmed, saying, “Truly this man also was with him, for he is a Galilean!” ",
      "60": "But Peter said, “Man, I don’t know what you are talking about!” Immediately, while he was still speaking, a rooster crowed.",
      "61": "The Lord turned and looked at Peter. Then Peter remembered the Lord’s word, how he said to him,  “Before the rooster crows you will deny me three times.” ",
      "62": "He went out, and wept bitterly. ",
      "63": "The men who held Jesus mocked him and beat him.",
      "64": "Having blindfolded him, they struck him on the face and asked him, “Prophesy! Who is the one who struck you?”",
      "65": "They spoke many other things against him, insulting him. ",
      "66": "As soon as it was day, the assembly of the elders of the people were gathered together, both chief priests and scribes, and they led him away into their council, saying,",
      "67": "“If you are the Christ, tell us.” But he said to them,  “If I tell you, you won’t believe,  ",
      "68": " and if I ask, you will in no way answer me or let me go.  ",
      "69": " From now on, the Son of Man will be seated at the right hand of the power of God.”  ",
      "70": "They all said, “Are you then the Son of God?” He said to them,  “You say it, because I am.”  ",
      "71": "They said, “Why do we need any more witness? For we ourselves have heard from his own mouth!”"
    },
    "23": {
      "1": "The whole company of them rose up and brought him before Pilate.",
      "2": "They began to accuse him, saying, “We found this man perverting the nation, forbidding paying taxes to Caesar, and saying that he himself is Christ, a king.” ",
      "3": "Pilate asked him, “Are you the King of the Jews?” He answered him,  “So you say.”  ",
      "4": "Pilate said to the chief priests and the multitudes, “I find no basis for a charge against this man.” ",
      "5": "But they insisted, saying, “He stirs up the people, teaching throughout all Judea, beginning from Galilee even to this place.” ",
      "6": "But when Pilate heard Galilee mentioned, he asked if the man was a Galilean.",
      "7": "When he found out that he was in Herod’s jurisdiction, he sent him to Herod, who was also in Jerusalem during those days. ",
      "8": "Now when Herod saw Jesus, he was exceedingly glad, for he had wanted to see him for a long time, because he had heard many things about him. He hoped to see some miracle done by him.",
      "9": "He questioned him with many words, but he gave no answers.",
      "10": "The chief priests and the scribes stood, vehemently accusing him.",
      "11": "Herod with his soldiers humiliated him and mocked him. Dressing him in luxurious clothing, they sent him back to Pilate.",
      "12": "Herod and Pilate became friends with each other that very day, for before that they were enemies with each other. ",
      "13": "Pilate called together the chief priests, the rulers, and the people,",
      "14": "and said to them, “You brought this man to me as one that perverts the people, and behold, having examined him before you, I found no basis for a charge against this man concerning those things of which you accuse him.",
      "15": "Neither has Herod, for I sent you to him, and see, nothing worthy of death has been done by him.",
      "16": "I will therefore chastise him and release him.” ",
      "17": "Now he had to release one prisoner to them at the feast. ",
      "18": "But they all cried out together, saying, “Away with this man! Release to us Barabbas!”—",
      "19": "one who was thrown into prison for a certain revolt in the city, and for murder. ",
      "20": "Then Pilate spoke to them again, wanting to release Jesus,",
      "21": "but they shouted, saying, “Crucify! Crucify him!” ",
      "22": "He said to them the third time, “Why? What evil has this man done? I have found no capital crime in him. I will therefore chastise him and release him.”",
      "23": "But they were urgent with loud voices, asking that he might be crucified. Their voices and the voices of the chief priests prevailed.",
      "24": "Pilate decreed that what they asked for should be done.",
      "25": "He released him who had been thrown into prison for insurrection and murder, for whom they asked, but he delivered Jesus up to their will. ",
      "26": "When they led him away, they grabbed one Simon of Cyrene, coming from the country, and laid the cross on him to carry it after Jesus.",
      "27": "A great multitude of the people followed him, including women who also mourned and lamented him.",
      "28": "But Jesus, turning to them, said,  “Daughters of Jerusalem, don’t weep for me, but weep for yourselves and for your children.  ",
      "29": " For behold, the days are coming in which they will say, ‘Blessed are the barren, the wombs that never bore, and the breasts that never nursed.’  ",
      "30": " Then they will begin to tell the mountains, ‘Fall on us!’ and tell the hills, ‘Cover us.’  ",
      "31": " For if they do these things in the green tree, what will be done in the dry?”  ",
      "32": "There were also others, two criminals, led with him to be put to death.",
      "33": "When they came to the place that is called “The Skull”, they crucified him there with the criminals, one on the right and the other on the left. ",
      "34": "Jesus said,  “Father, forgive them, for they don’t know what they are doing.”  Dividing his garments among them, they cast lots.",
      "35": "The people stood watching. The rulers with them also scoffed at him, saying, “He saved others. Let him save himself, if this is the Christ of God, his chosen one!” ",
      "36": "The soldiers also mocked him, coming to him and offering him vinegar,",
      "37": "and saying, “If you are the King of the Jews, save yourself!” ",
      "38": "An inscription was also written over him in letters of Greek, Latin, and Hebrew: “THIS IS THE KING OF THE JEWS.” ",
      "39": "One of the criminals who was hanged insulted him, saying, “If you are the Christ, save yourself and us!” ",
      "40": "But the other answered, and rebuking him said, “Don’t you even fear God, seeing you are under the same condemnation?",
      "41": "And we indeed justly, for we receive the due reward for our deeds, but this man has done nothing wrong.”",
      "42": "He said to Jesus, “Lord, remember me when you come into your Kingdom.” ",
      "43": "Jesus said to him,  “Assuredly I tell you, today you will be with me in Paradise.”  ",
      "44": "It was now about the sixth hour,  and darkness came over the whole land until the ninth hour. ",
      "45": "The sun was darkened, and the veil of the temple was torn in two.",
      "46": "Jesus, crying with a loud voice, said,  “Father, into your hands I commit my spirit!”  Having said this, he breathed his last. ",
      "47": "When the centurion saw what was done, he glorified God, saying, “Certainly this was a righteous man.”",
      "48": "All the multitudes that came together to see this, when they saw the things that were done, returned home beating their chests.",
      "49": "All his acquaintances and the women who followed with him from Galilee stood at a distance, watching these things. ",
      "50": "Behold, there was a man named Joseph, who was a member of the council, a good and righteous man",
      "51": "(he had not consented to their counsel and deed), from Arimathaea, a city of the Jews, who was also waiting for God’s Kingdom.",
      "52": "This man went to Pilate, and asked for Jesus’ body.",
      "53": "He took it down and wrapped it in a linen cloth, and laid him in a tomb that was cut in stone, where no one had ever been laid.",
      "54": "It was the day of the Preparation, and the Sabbath was drawing near.",
      "55": "The women who had come with him out of Galilee followed after, and saw the tomb and how his body was laid.",
      "56": "They returned and prepared spices and ointments. On the Sabbath they rested according to the commandment."
    },
    "24": {
      "1": "But on the first day of the week, at early dawn, they and some others came to the tomb, bringing the spices which they had prepared.",
      "2": "They found the stone rolled away from the tomb.",
      "3": "They entered in, and didn’t find the Lord Jesus’ body.",
      "4": "While they were greatly perplexed about this, behold, two men stood by them in dazzling clothing.",
      "5": "Becoming terrified, they bowed their faces down to the earth. The men said to them, “Why do you seek the living among the dead?",
      "6": "He isn’t here, but is risen. Remember what he told you when he was still in Galilee,",
      "7": "saying that the Son of Man must be delivered up into the hands of sinful men and be crucified, and the third day rise again?” ",
      "8": "They remembered his words,",
      "9": "returned from the tomb, and told all these things to the eleven and to all the rest.",
      "10": "Now they were Mary Magdalene, Joanna, and Mary the mother of James. The other women with them told these things to the apostles.",
      "11": "These words seemed to them to be nonsense, and they didn’t believe them.",
      "12": "But Peter got up and ran to the tomb. Stooping and looking in, he saw the strips of linen lying by themselves, and he departed to his home, wondering what had happened. ",
      "13": "Behold, two of them were going that very day to a village named Emmaus, which was sixty stadia  from Jerusalem.",
      "14": "They talked with each other about all of these things which had happened.",
      "15": "While they talked and questioned together, Jesus himself came near, and went with them.",
      "16": "But their eyes were kept from recognizing him.",
      "17": "He said to them,  “What are you talking about as you walk, and are sad?”  ",
      "18": "One of them, named Cleopas, answered him, “Are you the only stranger in Jerusalem who doesn’t know the things which have happened there in these days?” ",
      "19": "He said to them,  “What things?”  They said to him, “The things concerning Jesus the Nazarene, who was a prophet mighty in deed and word before God and all the people;",
      "20": "and how the chief priests and our rulers delivered him up to be condemned to death, and crucified him.",
      "21": "But we were hoping that it was he who would redeem Israel. Yes, and besides all this, it is now the third day since these things happened.",
      "22": "Also, certain women of our company amazed us, having arrived early at the tomb;",
      "23": "and when they didn’t find his body, they came saying that they had also seen a vision of angels, who said that he was alive.",
      "24": "Some of us went to the tomb and found it just like the women had said, but they didn’t see him.” ",
      "25": "He said to them,  “Foolish people, and slow of heart to believe in all that the prophets have spoken!  ",
      "26": " Didn’t the Christ have to suffer these things and to enter into his glory?” ",
      "27": "Beginning from Moses and from all the prophets, he explained to them in all the Scriptures the things concerning himself. ",
      "28": "They came near to the village where they were going, and he acted like he would go further. ",
      "29": "They urged him, saying, “Stay with us, for it is almost evening, and the day is almost over.” He went in to stay with them.",
      "30": "When he had sat down at the table with them, he took the bread and gave thanks. Breaking it, he gave it to them.",
      "31": "Their eyes were opened and they recognized him; then he vanished out of their sight.",
      "32": "They said to one another, “Weren’t our hearts burning within us while he spoke to us along the way, and while he opened the Scriptures to us?”",
      "33": "They rose up that very hour, returned to Jerusalem, and found the eleven gathered together, and those who were with them,",
      "34": "saying, “The Lord is risen indeed, and has appeared to Simon!”",
      "35": "They related the things that happened along the way, and how he was recognized by them in the breaking of the bread. ",
      "36": "As they said these things, Jesus himself stood among them, and said to them,  “Peace be to you.”  ",
      "37": "But they were terrified and filled with fear, and supposed that they had seen a spirit. ",
      "38": "He said to them,  “Why are you troubled? Why do doubts arise in your hearts?  ",
      "39": " See my hands and my feet, that it is truly me. Touch me and see, for a spirit doesn’t have flesh and bones, as you see that I have.” ",
      "40": "When he had said this, he showed them his hands and his feet.",
      "41": "While they still didn’t believe for joy, and wondered, he said to them,  “Do you have anything here to eat?”  ",
      "42": "They gave him a piece of a broiled fish and some honeycomb.",
      "43": "He took them, and ate in front of them.",
      "44": "He said to them,  “This is what I told you while I was still with you, that all things which are written in the law of Moses, the prophets, and the psalms concerning me must be fulfilled.”  ",
      "45": "Then he opened their minds, that they might understand the Scriptures.",
      "46": "He said to them,  “Thus it is written, and thus it was necessary for the Christ to suffer and to rise from the dead the third day,  ",
      "47": " and that repentance and remission of sins should be preached in his name to all the nations, beginning at Jerusalem.  ",
      "48": " You are witnesses of these things.  ",
      "49": " Behold, I send out the promise of my Father on you. But wait in the city of Jerusalem until you are clothed with power from on high.”   ",
      "50": "He led them out as far as Bethany, and he lifted up his hands and blessed them.",
      "51": "While he blessed them, he withdrew from them and was carried up into heaven.",
      "52": "They worshiped him and returned to Jerusalem with great joy,",
      "53": "and were continually in the temple, praising and blessing God. Amen."
    }
  },
  "john": {
    "1": {
      "1": "In the beginning was the Word, and the Word was with God, and the Word was God.",
      "2": "The same was in the beginning with God.",
      "3": "All things were made through him. Without him, nothing was made that has been made.",
      "4": "In him was life, and the life was the light of men.",
      "5": "The light shines in the darkness, and the darkness hasn’t overcome  it. ",
      "6": "There came a man sent from God, whose name was John.",
      "7": "The same came as a witness, that he might testify about the light, that all might believe through him.",
      "8": "He was not the light, but was sent that he might testify about the light.",
      "9": "The true light that enlightens everyone was coming into the world. ",
      "10": "He was in the world, and the world was made through him, and the world didn’t recognize him.",
      "11": "He came to his own, and those who were his own didn’t receive him.",
      "12": "But as many as received him, to them he gave the right to become God’s children, to those who believe in his name:",
      "13": "who were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God. ",
      "14": "The Word became flesh and lived among us. We saw his glory, such glory as of the only born  Son of the Father, full of grace and truth.",
      "15": "John testified about him. He cried out, saying, “This was he of whom I said, ‘He who comes after me has surpassed me, for he was before me.’”",
      "16": "From his fullness we all received grace upon grace.",
      "17": "For the law was given through Moses. Grace and truth were realized through Jesus Christ. ",
      "18": "No one has seen God at any time. The only born  Son,  who is in the bosom of the Father, has declared him. ",
      "19": "This is John’s testimony, when the Jews sent priests and Levites from Jerusalem to ask him, “Who are you?” ",
      "20": "He declared, and didn’t deny, but he declared, “I am not the Christ.” ",
      "21": "They asked him, “What then? Are you Elijah?” He said, “I am not.” “Are you the prophet?” He answered, “No.” ",
      "22": "They said therefore to him, “Who are you? Give us an answer to take back to those who sent us. What do you say about yourself?” ",
      "23": "He said, “I am the voice of one crying in the wilderness, ‘Make straight the way of the Lord,’  as Isaiah the prophet said.” ",
      "24": "The ones who had been sent were from the Pharisees.",
      "25": "They asked him, “Why then do you baptize if you are not the Christ, nor Elijah, nor the prophet?” ",
      "26": "John answered them, “I baptize in water, but among you stands one whom you don’t know.",
      "27": "He is the one who comes after me, who is preferred before me, whose sandal strap I’m not worthy to loosen.”",
      "28": "These things were done in Bethany beyond the Jordan, where John was baptizing. ",
      "29": "The next day, he saw Jesus coming to him, and said, “Behold,  the Lamb of God, who takes away the sin of the world!",
      "30": "This is he of whom I said, ‘After me comes a man who is preferred before me, for he was before me.’",
      "31": "I didn’t know him, but for this reason I came baptizing in water, that he would be revealed to Israel.”",
      "32": "John testified, saying, “I have seen the Spirit descending like a dove out of heaven, and it remained on him.",
      "33": "I didn’t recognize him, but he who sent me to baptize in water said to me, ‘On whomever you will see the Spirit descending and remaining on him is he who baptizes in the Holy Spirit.’",
      "34": "I have seen and have testified that this is the Son of God.” ",
      "35": "Again, the next day, John was standing with two of his disciples,",
      "36": "and he looked at Jesus as he walked, and said, “Behold, the Lamb of God!”",
      "37": "The two disciples heard him speak, and they followed Jesus.",
      "38": "Jesus turned and saw them following, and said to them,  “What are you looking for?”  They said to him, “Rabbi” (which is to say, being interpreted, Teacher), “where are you staying?” ",
      "39": "He said to them,  “Come and see.”  They came and saw where he was staying, and they stayed with him that day. It was about the tenth hour. ",
      "40": "One of the two who heard John and followed him was Andrew, Simon Peter’s brother.",
      "41": "He first found his own brother, Simon, and said to him, “We have found the Messiah!” (which is, being interpreted, Christ ).",
      "42": "He brought him to Jesus. Jesus looked at him and said,  “You are Simon the son of Jonah. You shall be called Cephas”  (which is by interpretation, Peter).  ",
      "43": "On the next day, he was determined to go out into Galilee, and he found Philip. Jesus said to him,  “Follow me.” ",
      "44": "Now Philip was from Bethsaida, the city of Andrew and Peter.",
      "45": "Philip found Nathanael, and said to him, “We have found him of whom Moses in the law and also the prophets, wrote: Jesus of Nazareth, the son of Joseph.” ",
      "46": "Nathanael said to him, “Can any good thing come out of Nazareth?” Philip said to him, “Come and see.” ",
      "47": "Jesus saw Nathanael coming to him, and said about him,  “Behold, an Israelite indeed, in whom is no deceit!”  ",
      "48": "Nathanael said to him, “How do you know me?” Jesus answered him,  “Before Philip called you, when you were under the fig tree, I saw you.”  ",
      "49": "Nathanael answered him, “Rabbi, you are the Son of God! You are King of Israel!” ",
      "50": "Jesus answered him,  “Because I told you, ‘I saw you underneath the fig tree,’ do you believe? You will see greater things than these!” ",
      "51": "He said to him,  “Most certainly, I tell you all, hereafter you will see heaven opened, and the angels of God ascending and descending on the Son of Man.” "
    },
    "2": {
      "1": "The third day, there was a wedding in Cana of Galilee. Jesus’ mother was there.",
      "2": "Jesus also was invited, with his disciples, to the wedding.",
      "3": "When the wine ran out, Jesus’ mother said to him, “They have no wine.” ",
      "4": "Jesus said to her,  “Woman, what does that have to do with you and me? My hour has not yet come.”  ",
      "5": "His mother said to the servants, “Whatever he says to you, do it.” ",
      "6": "Now there were six water pots of stone set there after the Jews’ way of purifying, containing two or three metretes  apiece.",
      "7": "Jesus said to them,  “Fill the water pots with water.”  So they filled them up to the brim.",
      "8": "He said to them,  “Now draw some out, and take it to the ruler of the feast.”  So they took it.",
      "9": "When the ruler of the feast tasted the water now become wine, and didn’t know where it came from (but the servants who had drawn the water knew), the ruler of the feast called the bridegroom",
      "10": "and said to him, “Everyone serves the good wine first, and when the guests have drunk freely, then that which is worse. You have kept the good wine until now!”",
      "11": "This beginning of his signs Jesus did in Cana of Galilee, and revealed his glory; and his disciples believed in him. ",
      "12": "After this, he went down to Capernaum, he, and his mother, his brothers, and his disciples; and they stayed there a few days. ",
      "13": "The Passover of the Jews was at hand, and Jesus went up to Jerusalem.",
      "14": "He found in the temple those who sold oxen, sheep, and doves, and the changers of money sitting.",
      "15": "He made a whip of cords and drove all out of the temple, both the sheep and the oxen; and he poured out the changers’ money and overthrew their tables.",
      "16": "To those who sold the doves, he said,  “Take these things out of here! Don’t make my Father’s house a marketplace!” ",
      "17": "His disciples remembered that it was written, “Zeal for your house will eat me up.”  ",
      "18": "The Jews therefore answered him, “What sign do you show us, seeing that you do these things?” ",
      "19": "Jesus answered them,  “Destroy this temple, and in three days I will raise it up.”  ",
      "20": "The Jews therefore said, “It took forty-six years to build this temple! Will you raise it up in three days?”",
      "21": "But he spoke of the temple of his body.",
      "22": "When therefore he was raised from the dead, his disciples remembered that he said this, and they believed the Scripture and the word which Jesus had said. ",
      "23": "Now when he was in Jerusalem at the Passover, during the feast, many believed in his name, observing his signs which he did.",
      "24": "But Jesus didn’t entrust himself to them, because he knew everyone,",
      "25": "and because he didn’t need for anyone to testify concerning man; for he himself knew what was in man."
    },
    "3": {
      "1": "Now there was a man of the Pharisees named Nicodemus, a ruler of the Jews.",
      "2": "He came to Jesus by night and said to him, “Rabbi, we know that you are a teacher come from God, for no one can do these signs that you do, unless God is with him.” ",
      "3": "Jesus answered him,  “Most certainly I tell you, unless one is born anew,     he can’t see God’s Kingdom.”  ",
      "4": "Nicodemus said to him, “How can a man be born when he is old? Can he enter a second time into his mother’s womb and be born?” ",
      "5": "Jesus answered,  “Most certainly I tell you, unless one is born of water and Spirit, he can’t enter into God’s Kingdom. ",
      "6": " That which is born of the flesh is flesh. That which is born of the Spirit is spirit.  ",
      "7": " Don’t marvel that I said to you, ‘You must be born anew.’  ",
      "8": " The wind    blows where it wants to, and you hear its sound, but don’t know where it comes from and where it is going. So is everyone who is born of the Spirit.”  ",
      "9": "Nicodemus answered him, “How can these things be?” ",
      "10": "Jesus answered him,  “Are you the teacher of Israel, and don’t understand these things?  ",
      "11": " Most certainly I tell you, we speak that which we know and testify of that which we have seen, and you don’t receive our witness.  ",
      "12": " If I told you earthly things and you don’t believe, how will you believe if I tell you heavenly things?  ",
      "13": " No one has ascended into heaven but he who descended out of heaven, the Son of Man, who is in heaven.  ",
      "14": " As Moses lifted up the serpent in the wilderness, even so must the Son of Man be lifted up,  ",
      "15": " that whoever believes in him should not perish, but have eternal life.  ",
      "16": " For God so loved the world, that he gave his only born    Son, that whoever believes in him should not perish, but have eternal life.  ",
      "17": " For God didn’t send his Son into the world to judge the world, but that the world should be saved through him.  ",
      "18": " He who believes in him is not judged. He who doesn’t believe has been judged already, because he has not believed in the name of the only born Son of God.  ",
      "19": " This is the judgment, that the light has come into the world, and men loved the darkness rather than the light, for their works were evil.  ",
      "20": " For everyone who does evil hates the light and doesn’t come to the light, lest his works would be exposed.  ",
      "21": " But he who does the truth comes to the light, that his works may be revealed, that they have been done in God.”  ",
      "22": "After these things, Jesus came with his disciples into the land of Judea. He stayed there with them and baptized.",
      "23": "John also was baptizing in Enon near Salim, because there was much water there. They came and were baptized;",
      "24": "for John was not yet thrown into prison.",
      "25": "Therefore a dispute arose on the part of John’s disciples with some Jews about purification.",
      "26": "They came to John and said to him, “Rabbi, he who was with you beyond the Jordan, to whom you have testified, behold, he baptizes, and everyone is coming to him.” ",
      "27": "John answered, “A man can receive nothing unless it has been given him from heaven.",
      "28": "You yourselves testify that I said, ‘I am not the Christ,’ but, ‘I have been sent before him.’",
      "29": "He who has the bride is the bridegroom; but the friend of the bridegroom, who stands and hears him, rejoices greatly because of the bridegroom’s voice. Therefore my joy is made full.",
      "30": "He must increase, but I must decrease. ",
      "31": "“He who comes from above is above all. He who is from the earth belongs to the earth and speaks of the earth. He who comes from heaven is above all.",
      "32": "What he has seen and heard, of that he testifies; and no one receives his witness.",
      "33": "He who has received his witness has set his seal to this, that God is true.",
      "34": "For he whom God has sent speaks the words of God; for God gives the Spirit without measure.",
      "35": "The Father loves the Son, and has given all things into his hand.",
      "36": "One who believes in the Son has eternal life, but one who disobeys  the Son won’t see life, but the wrath of God remains on him.”"
    }
  }
};

