
	
export const bib_verses = {
  "numbers": {
    "25": {
      "1": "Israel stayed in Shittim; and the people began to play the prostitute with the daughters of Moab;",
      "2": "for they called the people to the sacrifices of their gods. The people ate and bowed down to their gods.",
      "3": "Israel joined himself to Baal Peor, and Yahweh’s anger burned against Israel.",
      "4": "Yahweh said to Moses, “Take all the chiefs of the people, and hang them up to Yahweh before the sun, that the fierce anger of Yahweh may turn away from Israel.” ",
      "5": "Moses said to the judges of Israel, “Everyone kill his men who have joined themselves to Baal Peor.” ",
      "6": "Behold, one of the children of Israel came and brought to his brothers a Midianite woman in the sight of Moses, and in the sight of all the congregation of the children of Israel, while they were weeping at the door of the Tent of Meeting.",
      "7": "When Phinehas, the son of Eleazar, the son of Aaron the priest, saw it, he rose up from the middle of the congregation, and took a spear in his hand.",
      "8": "He went after the man of Israel into the pavilion, and thrust both of them through, the man of Israel, and the woman through her body. So the plague was stopped among the children of Israel.",
      "9": "Those who died by the plague were twenty-four thousand. ",
      "10": "Yahweh spoke to Moses, saying,",
      "11": "“Phinehas, the son of Eleazar, the son of Aaron the priest, has turned my wrath away from the children of Israel, in that he was jealous with my jealousy among them, so that I didn’t consume the children of Israel in my jealousy.",
      "12": "Therefore say, ‘Behold, I give to him my covenant of peace.",
      "13": "It shall be to him, and to his offspring after him, the covenant of an everlasting priesthood, because he was jealous for his God, and made atonement for the children of Israel.’” ",
      "14": "Now the name of the man of Israel that was slain, who was slain with the Midianite woman, was Zimri, the son of Salu, a prince of a fathers’ house among the Simeonites.",
      "15": "The name of the Midianite woman who was slain was Cozbi, the daughter of Zur. He was head of the people of a fathers’ house in Midian. ",
      "16": "Yahweh spoke to Moses, saying,",
      "17": "“Harass the Midianites, and strike them;",
      "18": "for they harassed you with their wiles, wherein they have deceived you in the matter of Peor, and in the incident regarding Cozbi, the daughter of the prince of Midian, their sister, who was slain on the day of the plague in the matter of Peor.”"
    },
    "26": {
      "1": "After the plague, Yahweh spoke to Moses and to Eleazar the son of Aaron the priest, saying,",
      "2": "“Take a census of all the congregation of the children of Israel, from twenty years old and upward, by their fathers’ houses, all who are able to go out to war in Israel.”",
      "3": "Moses and Eleazar the priest spoke with them in the plains of Moab by the Jordan at Jericho, saying,",
      "4": "“Take a census, from twenty years old and upward, as Yahweh commanded Moses and the children of Israel.” These are those who came out of the land of Egypt.",
      "5": "Reuben, the firstborn of Israel; the sons of Reuben: of Hanoch, the family of the Hanochites; of Pallu, the family of the Palluites;",
      "6": "of Hezron, the family of the Hezronites; of Carmi, the family of the Carmites.",
      "7": "These are the families of the Reubenites; and those who were counted of them were forty-three thousand seven hundred thirty.",
      "8": "The son of Pallu: Eliab.",
      "9": "The sons of Eliab: Nemuel, Dathan, and Abiram. These are that Dathan and Abiram who were called by the congregation, who rebelled against Moses and against Aaron in the company of Korah when they rebelled against Yahweh;",
      "10": "and the earth opened its mouth, and swallowed them up together with Korah when that company died; at the time the fire devoured two hundred fifty men, and they became a sign.",
      "11": "Notwithstanding, the sons of Korah didn’t die.",
      "12": "The sons of Simeon after their families: of Nemuel, the family of the Nemuelites; of Jamin, the family of the Jaminites; of Jachin, the family of the Jachinites;",
      "13": "of Zerah, the family of the Zerahites; of Shaul, the family of the Shaulites.",
      "14": "These are the families of the Simeonites, twenty-two thousand two hundred.",
      "15": "The sons of Gad after their families: of Zephon, the family of the Zephonites; of Haggi, the family of the Haggites; of Shuni, the family of the Shunites;",
      "16": "of Ozni, the family of the Oznites; of Eri, the family of the Erites;",
      "17": "of Arod, the family of the Arodites; of Areli, the family of the Arelites.",
      "18": "These are the families of the sons of Gad according to those who were counted of them, forty thousand and five hundred.",
      "19": "The sons of Judah: Er and Onan. Er and Onan died in the land of Canaan.",
      "20": "The sons of Judah after their families were: of Shelah, the family of the Shelanites; of Perez, the family of the Perezites; of Zerah, the family of the Zerahites.",
      "21": "The sons of Perez were: of Hezron, the family of the Hezronites; of Hamul, the family of the Hamulites.",
      "22": "These are the families of Judah according to those who were counted of them, seventy-six thousand five hundred.",
      "23": "The sons of Issachar after their families: of Tola, the family of the Tolaites; of Puvah, the family of the Punites;",
      "24": "of Jashub, the family of the Jashubites; of Shimron, the family of the Shimronites.",
      "25": "These are the families of Issachar according to those who were counted of them, sixty-four thousand three hundred.",
      "26": "The sons of Zebulun after their families: of Sered, the family of the Seredites; of Elon, the family of the Elonites; of Jahleel, the family of the Jahleelites.",
      "27": "These are the families of the Zebulunites according to those who were counted of them, sixty thousand five hundred.",
      "28": "The sons of Joseph after their families: Manasseh and Ephraim.",
      "29": "The sons of Manasseh: of Machir, the family of the Machirites; and Machir became the father of Gilead; of Gilead, the family of the Gileadites.",
      "30": "These are the sons of Gilead: of Iezer, the family of the Iezerites; of Helek, the family of the Helekites;",
      "31": "and Asriel, the family of the Asrielites; and Shechem, the family of the Shechemites;",
      "32": "and Shemida, the family of the Shemidaites; and Hepher, the family of the Hepherites.",
      "33": "Zelophehad the son of Hepher had no sons, but daughters: and the names of the daughters of Zelophehad were Mahlah, Noah, Hoglah, Milcah, and Tirzah.",
      "34": "These are the families of Manasseh. Those who were counted of them were fifty-two thousand seven hundred.",
      "35": "These are the sons of Ephraim after their families: of Shuthelah, the family of the Shuthelahites; of Becher, the family of the Becherites; of Tahan, the family of the Tahanites.",
      "36": "These are the sons of Shuthelah: of Eran, the family of the Eranites.",
      "37": "These are the families of the sons of Ephraim according to those who were counted of them, thirty-two thousand five hundred. These are the sons of Joseph after their families.",
      "38": "The sons of Benjamin after their families: of Bela, the family of the Belaites; of Ashbel, the family of the Ashbelites; of Ahiram, the family of the Ahiramites;",
      "39": "of Shephupham, the family of the Shuphamites; of Hupham, the family of the Huphamites.",
      "40": "The sons of Bela were Ard and Naaman: the family of the Ardites; and of Naaman, the family of the Naamites.",
      "41": "These are the sons of Benjamin after their families; and those who were counted of them were forty-five thousand six hundred.",
      "42": "These are the sons of Dan after their families: of Shuham, the family of the Shuhamites. These are the families of Dan after their families.",
      "43": "All the families of the Shuhamites, according to those who were counted of them, were sixty-four thousand four hundred.",
      "44": "The sons of Asher after their families: of Imnah, the family of the Imnites; of Ishvi, the family of the Ishvites; of Beriah, the family of the Berites.",
      "45": "Of the sons of Beriah: of Heber, the family of the Heberites; of Malchiel, the family of the Malchielites.",
      "46": "The name of the daughter of Asher was Serah.",
      "47": "These are the families of the sons of Asher according to those who were counted of them, fifty-three thousand four hundred.",
      "48": "The sons of Naphtali after their families: of Jahzeel, the family of the Jahzeelites; of Guni, the family of the Gunites;",
      "49": "of Jezer, the family of the Jezerites; of Shillem, the family of the Shillemites.",
      "50": "These are the families of Naphtali according to their families; and those who were counted of them were forty-five thousand four hundred.",
      "51": "These are those who were counted of the children of Israel, six hundred one thousand seven hundred thirty. ",
      "52": "Yahweh spoke to Moses, saying,",
      "53": "“To these the land shall be divided for an inheritance according to the number of names.",
      "54": "To the more you shall give the more inheritance, and to the fewer you shall give the less inheritance. To everyone according to those who were counted of him shall his inheritance be given.",
      "55": "Notwithstanding, the land shall be divided by lot. According to the names of the tribes of their fathers they shall inherit.",
      "56": "According to the lot shall their inheritance be divided between the more and the fewer.” ",
      "57": "These are those who were counted of the Levites after their families: of Gershon, the family of the Gershonites; of Kohath, the family of the Kohathites; of Merari, the family of the Merarites.",
      "58": "These are the families of Levi: the family of the Libnites, the family of the Hebronites, the family of the Mahlites, the family of the Mushites, and the family of the Korahites. Kohath became the father of Amram.",
      "59": "The name of Amram’s wife was Jochebed, the daughter of Levi, who was born to Levi in Egypt. She bore to Amram Aaron and Moses, and Miriam their sister.",
      "60": "To Aaron were born Nadab and Abihu, Eleazar and Ithamar.",
      "61": "Nadab and Abihu died when they offered strange fire before Yahweh.",
      "62": "Those who were counted of them were twenty-three thousand, every male from a month old and upward; for they were not counted among the children of Israel, because there was no inheritance given them among the children of Israel.",
      "63": "These are those who were counted by Moses and Eleazar the priest, who counted the children of Israel in the plains of Moab by the Jordan at Jericho.",
      "64": "But among these there was not a man of them who were counted by Moses and Aaron the priest, who counted the children of Israel in the wilderness of Sinai.",
      "65": "For Yahweh had said of them, “They shall surely die in the wilderness.” There was not a man left of them, except Caleb the son of Jephunneh, and Joshua the son of Nun."
    },
    "27": {
      "1": "Then the daughters of Zelophehad, the son of Hepher, the son of Gilead, the son of Machir, the son of Manasseh, of the families of Manasseh the son of Joseph came near. These are the names of his daughters: Mahlah, Noah, Hoglah, Milcah, and Tirzah.",
      "2": "They stood before Moses, before Eleazar the priest, and before the princes and all the congregation, at the door of the Tent of Meeting, saying,",
      "3": "“Our father died in the wilderness. He was not among the company of those who gathered themselves together against Yahweh in the company of Korah, but he died in his own sin. He had no sons.",
      "4": "Why should the name of our father be taken away from among his family, because he had no son? Give to us a possession among the brothers of our father.” ",
      "5": "Moses brought their cause before Yahweh.",
      "6": "Yahweh spoke to Moses, saying,",
      "7": "“The daughters of Zelophehad speak right. You shall surely give them a possession of an inheritance among their father’s brothers. You shall cause the inheritance of their father to pass to them.",
      "8": "You shall speak to the children of Israel, saying, ‘If a man dies, and has no son, then you shall cause his inheritance to pass to his daughter.",
      "9": "If he has no daughter, then you shall give his inheritance to his brothers.",
      "10": "If he has no brothers, then you shall give his inheritance to his father’s brothers.",
      "11": "If his father has no brothers, then you shall give his inheritance to his kinsman who is next to him of his family, and he shall possess it. This shall be a statute and ordinance for the children of Israel, as Yahweh commanded Moses.’” ",
      "12": "Yahweh said to Moses, “Go up into this mountain of Abarim, and see the land which I have given to the children of Israel.",
      "13": "When you have seen it, you also shall be gathered to your people, as Aaron your brother was gathered;",
      "14": "because in the strife of the congregation, you rebelled against my word in the wilderness of Zin, to honor me as holy at the waters before their eyes.” (These are the waters of Meribah of Kadesh in the wilderness of Zin.) ",
      "15": "Moses spoke to Yahweh, saying,",
      "16": "“Let Yahweh, the God of the spirits of all flesh, appoint a man over the congregation,",
      "17": "who may go out before them, and who may come in before them, and who may lead them out, and who may bring them in, that the congregation of Yahweh may not be as sheep which have no shepherd.” ",
      "18": "Yahweh said to Moses, “Take Joshua the son of Nun, a man in whom is the Spirit, and lay your hand on him.",
      "19": "Set him before Eleazar the priest, and before all the congregation; and commission him in their sight.",
      "20": "You shall give authority to him, that all the congregation of the children of Israel may obey.",
      "21": "He shall stand before Eleazar the priest, who shall inquire for him by the judgment of the Urim before Yahweh. At his word they shall go out, and at his word they shall come in, both he and all the children of Israel with him, even all the congregation.” ",
      "22": "Moses did as Yahweh commanded him. He took Joshua, and set him before Eleazar the priest and before all the congregation.",
      "23": "He laid his hands on him and commissioned him, as Yahweh spoke by Moses."
    },
    "28": {
      "1": "Yahweh spoke to Moses, saying,",
      "2": "“Command the children of Israel, and tell them, ‘See that you present my offering, my food for my offerings made by fire, as a pleasant aroma to me, in their due season.’",
      "3": "You shall tell them, ‘This is the offering made by fire which you shall offer to Yahweh: male lambs a year old without defect, two day by day, for a continual burnt offering.",
      "4": "You shall offer the one lamb in the morning, and you shall offer the other lamb at evening,",
      "5": "with one tenth of an ephah  of fine flour for a meal offering, mixed with the fourth part of a hin  of beaten oil.",
      "6": "It is a continual burnt offering which was ordained in Mount Sinai for a pleasant aroma, an offering made by fire to Yahweh.",
      "7": "Its drink offering shall be the fourth part of a hin  for each lamb. You shall pour out a drink offering of strong drink to Yahweh in the holy place.",
      "8": "The other lamb you shall offer at evening. As the meal offering of the morning, and as its drink offering, you shall offer it, an offering made by fire, for a pleasant aroma to Yahweh. ",
      "9": "“‘On the Sabbath day, you shall offer two male lambs a year old without defect, and two tenths of an ephah  of fine flour for a meal offering mixed with oil, and its drink offering:",
      "10": "this is the burnt offering of every Sabbath, in addition to the continual burnt offering and its drink offering. ",
      "11": "“‘In the beginnings of your months, you shall offer a burnt offering to Yahweh: two young bulls, one ram, seven male lambs a year old without defect,",
      "12": "and three tenths of an ephah  of fine flour for a meal offering mixed with oil, for each bull; and two tenth parts of fine flour for a meal offering mixed with oil, for the one ram;",
      "13": "and one tenth part of fine flour mixed with oil for a meal offering to every lamb, as a burnt offering of a pleasant aroma, an offering made by fire to Yahweh.",
      "14": "Their drink offerings shall be half a hin of wine for a bull, the third part of a hin for the ram, and the fourth part of a hin for a lamb. This is the burnt offering of every month throughout the months of the year.",
      "15": "Also, one male goat for a sin offering to Yahweh shall be offered in addition to the continual burnt offering and its drink offering. ",
      "16": "“‘In the first month, on the fourteenth day of the month, is Yahweh’s Passover.",
      "17": "On the fifteenth day of this month shall be a feast. Unleavened bread shall be eaten for seven days.",
      "18": "In the first day shall be a holy convocation. You shall do no regular work,",
      "19": "but you shall offer an offering made by fire, a burnt offering to Yahweh: two young bulls, one ram, and seven male lambs a year old. They shall be without defect,",
      "20": "with their meal offering, fine flour mixed with oil. You shall offer three tenths for a bull, and two tenths for the ram.",
      "21": "You shall offer one tenth for every lamb of the seven lambs;",
      "22": "and one male goat for a sin offering, to make atonement for you.",
      "23": "You shall offer these in addition to the burnt offering of the morning, which is for a continual burnt offering.",
      "24": "In this way you shall offer daily, for seven days, the food of the offering made by fire, of a pleasant aroma to Yahweh. It shall be offered in addition to the continual burnt offering and its drink offering.",
      "25": "On the seventh day you shall have a holy convocation. You shall do no regular work. ",
      "26": "“‘Also in the day of the first fruits, when you offer a new meal offering to Yahweh in your feast of weeks, you shall have a holy convocation. You shall do no regular work;",
      "27": "but you shall offer a burnt offering for a pleasant aroma to Yahweh: two young bulls, one ram, seven male lambs a year old;",
      "28": "and their meal offering, fine flour mixed with oil, three tenths for each bull, two tenths for the one ram,",
      "29": "one tenth for every lamb of the seven lambs;",
      "30": "and one male goat, to make atonement for you.",
      "31": "Besides the continual burnt offering and its meal offering, you shall offer them and their drink offerings. See that they are without defect."
    },
    "29": {
      "1": "“‘In the seventh month, on the first day of the month, you shall have a holy convocation; you shall do no regular work. It is a day of blowing of trumpets to you.",
      "2": "You shall offer a burnt offering for a pleasant aroma to Yahweh: one young bull, one ram, seven male lambs a year old without defect;",
      "3": "and their meal offering, fine flour mixed with oil: three tenths for the bull, two tenths for the ram,",
      "4": "and one tenth for every lamb of the seven lambs;",
      "5": "and one male goat for a sin offering, to make atonement for you;",
      "6": "in addition to the burnt offering of the new moon with its meal offering, and the continual burnt offering with its meal offering, and their drink offerings, according to their ordinance, for a pleasant aroma, an offering made by fire to Yahweh. ",
      "7": "“‘On the tenth day of this seventh month you shall have a holy convocation. You shall afflict your souls. You shall do no kind of work;",
      "8": "but you shall offer a burnt offering to Yahweh for a pleasant aroma: one young bull, one ram, seven male lambs a year old, all without defect;",
      "9": "and their meal offering, fine flour mixed with oil: three tenths for the bull, two tenths for the one ram,",
      "10": "one tenth for every lamb of the seven lambs;",
      "11": "one male goat for a sin offering, in addition to the sin offering of atonement, and the continual burnt offering, and its meal offering, and their drink offerings. ",
      "12": "“‘On the fifteenth day of the seventh month you shall have a holy convocation. You shall do no regular work. You shall keep a feast to Yahweh seven days.",
      "13": "You shall offer a burnt offering, an offering made by fire, of a pleasant aroma to Yahweh: thirteen young bulls, two rams, fourteen male lambs a year old, all without defect;",
      "14": "and their meal offering, fine flour mixed with oil: three tenths for every bull of the thirteen bulls, two tenths for each ram of the two rams,",
      "15": "and one tenth for every lamb of the fourteen lambs;",
      "16": "and one male goat for a sin offering, in addition to the continual burnt offering, its meal offering, and its drink offering. ",
      "17": "“‘On the second day you shall offer twelve young bulls, two rams, and fourteen male lambs a year old without defect;",
      "18": "and their meal offering and their drink offerings for the bulls, for the rams, and for the lambs, according to their number, after the ordinance;",
      "19": "and one male goat for a sin offering, in addition to the continual burnt offering, with its meal offering and their drink offerings. ",
      "20": "“‘On the third day: eleven bulls, two rams, fourteen male lambs a year old without defect;",
      "21": "and their meal offering and their drink offerings for the bulls, for the rams, and for the lambs, according to their number, after the ordinance;",
      "22": "and one male goat for a sin offering, in addition to the continual burnt offering, and its meal offering, and its drink offering. ",
      "23": "“‘On the fourth day ten bulls, two rams, fourteen male lambs a year old without defect;",
      "24": "their meal offering and their drink offerings for the bulls, for the rams, and for the lambs, according to their number, after the ordinance;",
      "25": "and one male goat for a sin offering; in addition to the continual burnt offering, its meal offering, and its drink offering. ",
      "26": "“‘On the fifth day: nine bulls, two rams, fourteen male lambs a year old without defect;",
      "27": "and their meal offering and their drink offerings for the bulls, for the rams, and for the lambs, according to their number, after the ordinance,",
      "28": "and one male goat for a sin offering, in addition to the continual burnt offering, and its meal offering, and its drink offering. ",
      "29": "“‘On the sixth day: eight bulls, two rams, fourteen male lambs a year old without defect;",
      "30": "and their meal offering and their drink offerings for the bulls, for the rams, and for the lambs, according to their number, after the ordinance,",
      "31": "and one male goat for a sin offering; in addition to the continual burnt offering, its meal offering, and the drink offerings of it. ",
      "32": "“‘On the seventh day: seven bulls, two rams, fourteen male lambs a year old without defect;",
      "33": "and their meal offering and their drink offerings for the bulls, for the rams, and for the lambs, according to their number, after the ordinance,",
      "34": "and one male goat for a sin offering; in addition to the continual burnt offering, its meal offering, and its drink offering. ",
      "35": "“‘On the eighth day you shall have a solemn assembly. You shall do no regular work;",
      "36": "but you shall offer a burnt offering, an offering made by fire, a pleasant aroma to Yahweh: one bull, one ram, seven male lambs a year old without defect;",
      "37": "their meal offering and their drink offerings for the bull, for the ram, and for the lambs, shall be according to their number, after the ordinance,",
      "38": "and one male goat for a sin offering, in addition to the continual burnt offering, with its meal offering, and its drink offering. ",
      "39": "“‘You shall offer these to Yahweh in your set feasts—in addition to your vows and your free will offerings—for your burnt offerings, your meal offerings, your drink offerings, and your peace offerings.’” ",
      "40": "Moses told the children of Israel according to all that Yahweh commanded Moses."
    },
    "30": {
      "1": "Moses spoke to the heads of the tribes of the children of Israel, saying, “This is the thing which Yahweh has commanded.",
      "2": "When a man vows a vow to Yahweh, or swears an oath to bind his soul with a bond, he shall not break his word. He shall do according to all that proceeds out of his mouth. ",
      "3": "“Also, when a woman vows a vow to Yahweh and binds herself by a pledge, being in her father’s house, in her youth,",
      "4": "and her father hears her vow and her pledge with which she has bound her soul, and her father says nothing to her, then all her vows shall stand, and every pledge with which she has bound her soul shall stand.",
      "5": "But if her father forbids her in the day that he hears, none of her vows or of her pledges with which she has bound her soul, shall stand. Yahweh will forgive her, because her father has forbidden her. ",
      "6": "“If she has a husband, while her vows are on her, or the rash utterance of her lips with which she has bound her soul,",
      "7": "and her husband hears it, and says nothing to her in the day that he hears it; then her vows shall stand, and her pledges with which she has bound her soul shall stand.",
      "8": "But if her husband forbids her in the day that he hears it, then he makes void her vow which is on her and the rash utterance of her lips, with which she has bound her soul. Yahweh will forgive her. ",
      "9": "“But the vow of a widow, or of her who is divorced, everything with which she has bound her soul shall stand against her. ",
      "10": "“If she vowed in her husband’s house or bound her soul by a bond with an oath,",
      "11": "and her husband heard it, and held his peace at her and didn’t disallow her, then all her vows shall stand, and every pledge with which she bound her soul shall stand.",
      "12": "But if her husband made them null and void in the day that he heard them, then whatever proceeded out of her lips concerning her vows, or concerning the bond of her soul, shall not stand. Her husband has made them void. Yahweh will forgive her.",
      "13": "Every vow, and every binding oath to afflict the soul, her husband may establish it, or her husband may make it void.",
      "14": "But if her husband says nothing to her from day to day, then he establishes all her vows or all her pledges which are on her. He has established them, because he said nothing to her in the day that he heard them.",
      "15": "But if he makes them null and void after he has heard them, then he shall bear her iniquity.” ",
      "16": "These are the statutes which Yahweh commanded Moses, between a man and his wife, between a father and his daughter, being in her youth, in her father’s house."
    },
    "31": {
      "1": "Yahweh spoke to Moses, saying,",
      "2": "“Avenge the children of Israel on the Midianites. Afterward you shall be gathered to your people.” ",
      "3": "Moses spoke to the people, saying, “Arm men from among you for war, that they may go against Midian, to execute Yahweh’s vengeance on Midian.",
      "4": "You shall send one thousand out of every tribe, throughout all the tribes of Israel, to the war.”",
      "5": "So there were delivered, out of the thousands of Israel, a thousand from every tribe, twelve thousand armed for war.",
      "6": "Moses sent them, one thousand of every tribe, to the war with Phinehas the son of Eleazar the priest, to the war, with the vessels of the sanctuary and the trumpets for the alarm in his hand.",
      "7": "They fought against Midian, as Yahweh commanded Moses. They killed every male.",
      "8": "They killed the kings of Midian with the rest of their slain: Evi, Rekem, Zur, Hur, and Reba, the five kings of Midian. They also killed Balaam the son of Beor with the sword.",
      "9": "The children of Israel took the women of Midian captive with their little ones; and all their livestock, all their flocks, and all their goods, they took as plunder.",
      "10": "All their cities in the places in which they lived, and all their encampments, they burned with fire.",
      "11": "They took all the captives, and all the plunder, both of man and of animal.",
      "12": "They brought the captives with the prey and the plunder, to Moses, and to Eleazar the priest, and to the congregation of the children of Israel, to the camp at the plains of Moab, which are by the Jordan at Jericho.",
      "13": "Moses and Eleazar the priest, with all the princes of the congregation, went out to meet them outside of the camp.",
      "14": "Moses was angry with the officers of the army, the captains of thousands and the captains of hundreds, who came from the service of the war.",
      "15": "Moses said to them, “Have you saved all the women alive?",
      "16": "Behold, these caused the children of Israel, through the counsel of Balaam, to commit trespass against Yahweh in the matter of Peor, and so the plague was among the congregation of Yahweh.",
      "17": "Now therefore kill every male among the little ones, and kill every woman who has known man by lying with him.",
      "18": "But all the girls, who have not known man by lying with him, keep alive for yourselves. ",
      "19": "“Encamp outside of the camp for seven days. Whoever has killed any person, and whoever has touched any slain, purify yourselves on the third day and on the seventh day, you and your captives.",
      "20": "You shall purify every garment, and all that is made of skin, and all work of goats’ hair, and all things made of wood.” ",
      "21": "Eleazar the priest said to the men of war who went to the battle, “This is the statute of the law which Yahweh has commanded Moses.",
      "22": "However the gold, and the silver, the bronze, the iron, the tin, and the lead,",
      "23": "everything that may withstand the fire, you shall make to go through the fire, and it shall be clean; nevertheless it shall be purified with the water for impurity. All that doesn’t withstand the fire you shall make to go through the water.",
      "24": "You shall wash your clothes on the seventh day, and you shall be clean. Afterward you shall come into the camp.” ",
      "25": "Yahweh spoke to Moses, saying,",
      "26": "“Count the plunder that was taken, both of man and of animal, you, and Eleazar the priest, and the heads of the fathers’ households of the congregation;",
      "27": "and divide the plunder into two parts: between the men skilled in war, who went out to battle, and all the congregation.",
      "28": "Levy a tribute to Yahweh of the men of war who went out to battle: one soul of five hundred; of the persons, of the cattle, of the donkeys, and of the flocks.",
      "29": "Take it from their half, and give it to Eleazar the priest, for Yahweh’s wave offering.",
      "30": "Of the children of Israel’s half, you shall take one drawn out of every fifty, of the persons, of the cattle, of the donkeys, and of the flocks, of all the livestock, and give them to the Levites, who perform the duty of Yahweh’s tabernacle.” ",
      "31": "Moses and Eleazar the priest did as Yahweh commanded Moses. ",
      "32": "Now the plunder, over and above the booty which the men of war took, was six hundred seventy-five thousand sheep,",
      "33": "seventy-two thousand head of cattle,",
      "34": "sixty-one thousand donkeys,",
      "35": "and thirty-two thousand persons in all, of the women who had not known man by lying with him.",
      "36": "The half, which was the portion of those who went out to war, was in number three hundred thirty-seven thousand five hundred sheep;",
      "37": "and Yahweh’s tribute of the sheep was six hundred seventy-five.",
      "38": "The cattle were thirty-six thousand, of which Yahweh’s tribute was seventy-two.",
      "39": "The donkeys were thirty thousand five hundred, of which Yahweh’s tribute was sixty-one.",
      "40": "The persons were sixteen thousand, of whom Yahweh’s tribute was thirty-two persons.",
      "41": "Moses gave the tribute, which was Yahweh’s wave offering, to Eleazar the priest, as Yahweh commanded Moses.",
      "42": "Of the children of Israel’s half, which Moses divided off from the men who fought",
      "43": "(now the congregation’s half was three hundred thirty-seven thousand five hundred sheep,",
      "44": "thirty-six thousand head of cattle,",
      "45": "thirty thousand five hundred donkeys,",
      "46": "and sixteen thousand persons),",
      "47": "even of the children of Israel’s half, Moses took one drawn out of every fifty, both of man and of animal, and gave them to the Levites, who performed the duty of Yahweh’s tabernacle, as Yahweh commanded Moses. ",
      "48": "The officers who were over the thousands of the army, the captains of thousands, and the captains of hundreds, came near to Moses.",
      "49": "They said to Moses, “Your servants have taken the sum of the men of war who are under our command, and there lacks not one man of us.",
      "50": "We have brought Yahweh’s offering, what every man found: gold ornaments, armlets, bracelets, signet rings, earrings, and necklaces, to make atonement for our souls before Yahweh.” ",
      "51": "Moses and Eleazar the priest took their gold, even all worked jewels.",
      "52": "All the gold of the wave offering that they offered up to Yahweh, of the captains of thousands, and of the captains of hundreds, was sixteen thousand seven hundred fifty shekels. ",
      "53": "The men of war had taken booty, every man for himself.",
      "54": "Moses and Eleazar the priest took the gold of the captains of thousands and of hundreds, and brought it into the Tent of Meeting for a memorial for the children of Israel before Yahweh."
    },
    "32": {
      "1": "Now the children of Reuben and the children of Gad had a very great multitude of livestock. They saw the land of Jazer, and the land of Gilead. Behold, the place was a place for livestock.",
      "2": "Then the children of Gad and the children of Reuben came and spoke to Moses, and to Eleazar the priest, and to the princes of the congregation, saying,",
      "3": "“Ataroth, Dibon, Jazer, Nimrah, Heshbon, Elealeh, Sebam, Nebo, and Beon,",
      "4": "the land which Yahweh struck before the congregation of Israel, is a land for livestock; and your servants have livestock.”",
      "5": "They said, “If we have found favor in your sight, let this land be given to your servants for a possession. Don’t bring us over the Jordan.” ",
      "6": "Moses said to the children of Gad, and to the children of Reuben, “Shall your brothers go to war while you sit here?",
      "7": "Why do you discourage the heart of the children of Israel from going over into the land which Yahweh has given them?",
      "8": "Your fathers did so when I sent them from Kadesh Barnea to see the land.",
      "9": "For when they went up to the valley of Eshcol, and saw the land, they discouraged the heart of the children of Israel, that they should not go into the land which Yahweh had given them.",
      "10": "Yahweh’s anger burned in that day, and he swore, saying,",
      "11": "‘Surely none of the men who came up out of Egypt, from twenty years old and upward, shall see the land which I swore to Abraham, to Isaac, and to Jacob; because they have not wholly followed me,",
      "12": "except Caleb the son of Jephunneh the Kenizzite, and Joshua the son of Nun, because they have followed Yahweh completely.’",
      "13": "Yahweh’s anger burned against Israel, and he made them wander back and forth in the wilderness forty years, until all the generation who had done evil in Yahweh’s sight was consumed. ",
      "14": "“Behold, you have risen up in your fathers’ place, an increase of sinful men, to increase the fierce anger of Yahweh toward Israel.",
      "15": "For if you turn away from after him, he will yet again leave them in the wilderness; and you will destroy all these people.” ",
      "16": "They came near to him, and said, “We will build sheepfolds here for our livestock, and cities for our little ones;",
      "17": "but we ourselves will be ready armed to go before the children of Israel, until we have brought them to their place. Our little ones shall dwell in the fortified cities because of the inhabitants of the land.",
      "18": "We will not return to our houses until the children of Israel have all received their inheritance.",
      "19": "For we will not inherit with them on the other side of the Jordan and beyond, because our inheritance has come to us on this side of the Jordan eastward.” ",
      "20": "Moses said to them: “If you will do this thing, if you will arm yourselves to go before Yahweh to the war,",
      "21": "and every one of your armed men will pass over the Jordan before Yahweh until he has driven out his enemies from before him,",
      "22": "and the land is subdued before Yahweh; then afterward you shall return, and be clear of obligation to Yahweh and to Israel. Then this land shall be your possession before Yahweh. ",
      "23": "“But if you will not do so, behold, you have sinned against Yahweh; and be sure your sin will find you out.",
      "24": "Build cities for your little ones, and folds for your sheep; and do that which has proceeded out of your mouth.” ",
      "25": "The children of Gad and the children of Reuben spoke to Moses, saying, “Your servants will do as my lord commands.",
      "26": "Our little ones, our wives, our flocks, and all our livestock shall be there in the cities of Gilead;",
      "27": "but your servants will pass over, every man who is armed for war, before Yahweh to battle, as my lord says.” ",
      "28": "So Moses commanded concerning them to Eleazar the priest, and to Joshua the son of Nun, and to the heads of the fathers’ households of the tribes of the children of Israel.",
      "29": "Moses said to them, “If the children of Gad and the children of Reuben will pass with you over the Jordan, every man who is armed to battle before Yahweh, and the land is subdued before you, then you shall give them the land of Gilead for a possession;",
      "30": "but if they will not pass over with you armed, they shall have possessions among you in the land of Canaan.” ",
      "31": "The children of Gad and the children of Reuben answered, saying, “As Yahweh has said to your servants, so will we do.",
      "32": "We will pass over armed before Yahweh into the land of Canaan, and the possession of our inheritance shall remain with us beyond the Jordan.” ",
      "33": "Moses gave to them, even to the children of Gad, and to the children of Reuben, and to the half-tribe of Manasseh the son of Joseph, the kingdom of Sihon king of the Amorites, and the kingdom of Og king of Bashan; the land, according to its cities and borders, even the cities of the surrounding land.",
      "34": "The children of Gad built Dibon, Ataroth, Aroer,",
      "35": "Atroth-shophan, Jazer, Jogbehah,",
      "36": "Beth Nimrah, and Beth Haran: fortified cities and folds for sheep.",
      "37": "The children of Reuben built Heshbon, Elealeh, Kiriathaim,",
      "38": "Nebo, and Baal Meon, (their names being changed), and Sibmah. They gave other names to the cities which they built.",
      "39": "The children of Machir the son of Manasseh went to Gilead, took it, and dispossessed the Amorites who were therein.",
      "40": "Moses gave Gilead to Machir the son of Manasseh; and he lived therein.",
      "41": "Jair the son of Manasseh went and took its villages, and called them Havvoth Jair.",
      "42": "Nobah went and took Kenath and its villages, and called it Nobah, after his own name."
    },
    "33": {
      "1": "These are the journeys of the children of Israel, when they went out of the land of Egypt by their armies under the hand of Moses and Aaron.",
      "2": "Moses wrote the starting points of their journeys by the commandment of Yahweh. These are their journeys according to their starting points.",
      "3": "They traveled from Rameses in the first month, on the fifteenth day of the first month; on the next day after the Passover, the children of Israel went out with a high hand in the sight of all the Egyptians,",
      "4": "while the Egyptians were burying all their firstborn, whom Yahweh had struck among them. Yahweh also executed judgments on their gods.",
      "5": "The children of Israel traveled from Rameses, and encamped in Succoth.",
      "6": "They traveled from Succoth, and encamped in Etham, which is in the edge of the wilderness.",
      "7": "They traveled from Etham, and turned back to Pihahiroth, which is before Baal Zephon, and they encamped before Migdol.",
      "8": "They traveled from before Hahiroth, and crossed through the middle of the sea into the wilderness. They went three days’ journey in the wilderness of Etham, and encamped in Marah.",
      "9": "They traveled from Marah, and came to Elim. In Elim, there were twelve springs of water and seventy palm trees, and they encamped there.",
      "10": "They traveled from Elim, and encamped by the Red Sea.",
      "11": "They traveled from the Red Sea, and encamped in the wilderness of Sin.",
      "12": "They traveled from the wilderness of Sin, and encamped in Dophkah.",
      "13": "They traveled from Dophkah, and encamped in Alush.",
      "14": "They traveled from Alush, and encamped in Rephidim, where there was no water for the people to drink.",
      "15": "They traveled from Rephidim, and encamped in the wilderness of Sinai.",
      "16": "They traveled from the wilderness of Sinai, and encamped in Kibroth Hattaavah.",
      "17": "They traveled from Kibroth Hattaavah, and encamped in Hazeroth.",
      "18": "They traveled from Hazeroth, and encamped in Rithmah.",
      "19": "They traveled from Rithmah, and encamped in Rimmon Perez.",
      "20": "They traveled from Rimmon Perez, and encamped in Libnah.",
      "21": "They traveled from Libnah, and encamped in Rissah.",
      "22": "They traveled from Rissah, and encamped in Kehelathah.",
      "23": "They traveled from Kehelathah, and encamped in Mount Shepher.",
      "24": "They traveled from Mount Shepher, and encamped in Haradah.",
      "25": "They traveled from Haradah, and encamped in Makheloth.",
      "26": "They traveled from Makheloth, and encamped in Tahath.",
      "27": "They traveled from Tahath, and encamped in Terah.",
      "28": "They traveled from Terah, and encamped in Mithkah.",
      "29": "They traveled from Mithkah, and encamped in Hashmonah.",
      "30": "They traveled from Hashmonah, and encamped in Moseroth.",
      "31": "They traveled from Moseroth, and encamped in Bene Jaakan.",
      "32": "They traveled from Bene Jaakan, and encamped in Hor Haggidgad.",
      "33": "They traveled from Hor Haggidgad, and encamped in Jotbathah.",
      "34": "They traveled from Jotbathah, and encamped in Abronah.",
      "35": "They traveled from Abronah, and encamped in Ezion Geber.",
      "36": "They traveled from Ezion Geber, and encamped at Kadesh in the wilderness of Zin.",
      "37": "They traveled from Kadesh, and encamped in Mount Hor, in the edge of the land of Edom.",
      "38": "Aaron the priest went up into Mount Hor at the commandment of Yahweh and died there, in the fortieth year after the children of Israel had come out of the land of Egypt, in the fifth month, on the first day of the month.",
      "39": "Aaron was one hundred twenty-three years old when he died in Mount Hor.",
      "40": "The Canaanite king of Arad, who lived in the South in the land of Canaan, heard of the coming of the children of Israel.",
      "41": "They traveled from Mount Hor, and encamped in Zalmonah.",
      "42": "They traveled from Zalmonah, and encamped in Punon.",
      "43": "They traveled from Punon, and encamped in Oboth.",
      "44": "They traveled from Oboth, and encamped in Iye Abarim, in the border of Moab.",
      "45": "They traveled from Iyim, and encamped in Dibon Gad.",
      "46": "They traveled from Dibon Gad, and encamped in Almon Diblathaim.",
      "47": "They traveled from Almon Diblathaim, and encamped in the mountains of Abarim, before Nebo.",
      "48": "They traveled from the mountains of Abarim, and encamped in the plains of Moab by the Jordan at Jericho.",
      "49": "They encamped by the Jordan, from Beth Jeshimoth even to Abel Shittim in the plains of Moab.",
      "50": "Yahweh spoke to Moses in the plains of Moab by the Jordan at Jericho, saying,",
      "51": "Speak to the children of Israel, and tell them, “When you pass over the Jordan into the land of Canaan,",
      "52": "then you shall drive out all the inhabitants of the land from before you, destroy all their stone idols, destroy all their molten images, and demolish all their high places.",
      "53": "You shall take possession of the land, and dwell therein; for I have given the land to you to possess it.",
      "54": "You shall inherit the land by lot according to your families; to the larger groups you shall give a larger inheritance, and to the smaller you shall give a smaller inheritance. Wherever the lot falls to any man, that shall be his. You shall inherit according to the tribes of your fathers. ",
      "55": "“But if you do not drive out the inhabitants of the land from before you, then those you let remain of them will be like pricks in your eyes and thorns in your sides. They will harass you in the land in which you dwell.",
      "56": "It shall happen that as I thought to do to them, so I will do to you.”"
    },
    "34": {
      "1": "Yahweh spoke to Moses, saying,",
      "2": "“Command the children of Israel, and tell them, ‘When you come into the land of Canaan (this is the land that shall fall to you for an inheritance, even the land of Canaan according to its borders),",
      "3": "then your south quarter shall be from the wilderness of Zin along by the side of Edom, and your south border shall be from the end of the Salt Sea eastward.",
      "4": "Your border shall turn about southward of the ascent of Akrabbim, and pass along to Zin; and it shall pass southward of Kadesh Barnea; and it shall go from there to Hazar Addar, and pass along to Azmon.",
      "5": "The border shall turn about from Azmon to the brook of Egypt, and it shall end at the sea. ",
      "6": "“‘For the western border, you shall have the great sea and its border. This shall be your west border. ",
      "7": "“‘This shall be your north border: from the great sea you shall mark out for yourselves Mount Hor.",
      "8": "From Mount Hor you shall mark out to the entrance of Hamath; and the border shall pass by Zedad.",
      "9": "Then the border shall go to Ziphron, and it shall end at Hazar Enan. This shall be your north border. ",
      "10": "“‘You shall mark out your east border from Hazar Enan to Shepham.",
      "11": "The border shall go down from Shepham to Riblah, on the east side of Ain. The border shall go down, and shall reach to the side of the sea of Chinnereth eastward.",
      "12": "The border shall go down to the Jordan, and end at the Salt Sea. This shall be your land according to its borders around it.’” ",
      "13": "Moses commanded the children of Israel, saying, “This is the land which you shall inherit by lot, which Yahweh has commanded to give to the nine tribes, and to the half-tribe;",
      "14": "for the tribe of the children of Reuben according to their fathers’ houses, the tribe of the children of Gad according to their fathers’ houses, and the half-tribe of Manasseh have received their inheritance.",
      "15": "The two tribes and the half-tribe have received their inheritance beyond the Jordan at Jericho eastward, toward the sunrise.” ",
      "16": "Yahweh spoke to Moses, saying,",
      "17": "“These are the names of the men who shall divide the land to you for inheritance: Eleazar the priest, and Joshua the son of Nun.",
      "18": "You shall take one prince of every tribe, to divide the land for inheritance.",
      "19": "These are the names of the men: Of the tribe of Judah, Caleb the son of Jephunneh.",
      "20": "Of the tribe of the children of Simeon, Shemuel the son of Ammihud.",
      "21": "Of the tribe of Benjamin, Elidad the son of Chislon.",
      "22": "Of the tribe of the children of Dan a prince, Bukki the son of Jogli.",
      "23": "Of the children of Joseph: of the tribe of the children of Manasseh a prince, Hanniel the son of Ephod.",
      "24": "Of the tribe of the children of Ephraim a prince, Kemuel the son of Shiphtan.",
      "25": "Of the tribe of the children of Zebulun a prince, Elizaphan the son of Parnach.",
      "26": "Of the tribe of the children of Issachar a prince, Paltiel the son of Azzan.",
      "27": "Of the tribe of the children of Asher a prince, Ahihud the son of Shelomi.",
      "28": "Of the tribe of the children of Naphtali a prince, Pedahel the son of Ammihud.”",
      "29": "These are they whom Yahweh commanded to divide the inheritance to the children of Israel in the land of Canaan."
    },
    "35": {
      "1": "Yahweh spoke to Moses in the plains of Moab by the Jordan at Jericho, saying,",
      "2": "“Command the children of Israel to give to the Levites cities to dwell in out of their inheritance. You shall give pasture lands for the cities around them to the Levites.",
      "3": "They shall have the cities to dwell in. Their pasture lands shall be for their livestock, and for their possessions, and for all their animals. ",
      "4": "“The pasture lands of the cities, which you shall give to the Levites, shall be from the wall of the city and outward one thousand cubits  around it.",
      "5": "You shall measure outside of the city for the east side two thousand cubits, and for the south side two thousand cubits, and for the west side two thousand cubits, and for the north side two thousand cubits, the city being in the middle. This shall be the pasture lands of their cities. ",
      "6": "“The cities which you shall give to the Levites, they shall be the six cities of refuge, which you shall give for the man slayer to flee to. Besides them you shall give forty-two cities.",
      "7": "All the cities which you shall give to the Levites shall be forty-eight cities together with their pasture lands.",
      "8": "Concerning the cities which you shall give of the possession of the children of Israel, from the many you shall take many, and from the few you shall take few. Everyone according to his inheritance which he inherits shall give some of his cities to the Levites.”",
      "9": "Yahweh spoke to Moses, saying,",
      "10": "“Speak to the children of Israel, and tell them, ‘When you pass over the Jordan into the land of Canaan,",
      "11": "then you shall appoint for yourselves cities to be cities of refuge for you, that the man slayer who kills any person unwittingly may flee there.",
      "12": "The cities shall be for your refuge from the avenger, that the man slayer not die until he stands before the congregation for judgment.",
      "13": "The cities which you shall give shall be for you six cities of refuge.",
      "14": "You shall give three cities beyond the Jordan, and you shall give three cities in the land of Canaan. They shall be cities of refuge.",
      "15": "These six cities shall be refuge for the children of Israel, for the stranger, and for the foreigner living among them, that everyone who kills any person unwittingly may flee there. ",
      "16": "“‘But if he struck him with an instrument of iron, so that he died, he is a murderer. The murderer shall surely be put to death.",
      "17": "If he struck him with a stone in the hand, by which a man may die, and he died, he is a murderer. The murderer shall surely be put to death.",
      "18": "Or if he struck him with a weapon of wood in the hand, by which a man may die, and he died, he is a murderer. The murderer shall surely be put to death.",
      "19": "The avenger of blood shall himself put the murderer to death. When he meets him, he shall put him to death.",
      "20": "If he shoved him out of hatred, or hurled something at him while lying in wait, so that he died,",
      "21": "or in hostility struck him with his hand, so that he died, he who struck him shall surely be put to death. He is a murderer. The avenger of blood shall put the murderer to death when he meets him. ",
      "22": "“‘But if he shoved him suddenly without hostility, or hurled on him anything without lying in wait,",
      "23": "or with any stone, by which a man may die, not seeing him, and cast it on him so that he died, and he was not his enemy and not seeking his harm,",
      "24": "then the congregation shall judge between the striker and the avenger of blood according to these ordinances.",
      "25": "The congregation shall deliver the man slayer out of the hand of the avenger of blood, and the congregation shall restore him to his city of refuge, where he had fled. He shall dwell therein until the death of the high priest, who was anointed with the holy oil. ",
      "26": "“‘But if the man slayer shall at any time go beyond the border of his city of refuge where he flees,",
      "27": "and the avenger of blood finds him outside of the border of his city of refuge, and the avenger of blood kills the man slayer, he shall not be guilty of blood,",
      "28": "because he should have remained in his city of refuge until the death of the high priest. But after the death of the high priest, the man slayer shall return into the land of his possession. ",
      "29": "“‘These things shall be for a statute and ordinance to you throughout your generations in all your dwellings. ",
      "30": "“‘Whoever kills any person, the murderer shall be slain based on the testimony of witnesses; but one witness shall not testify alone against any person so that he dies. ",
      "31": "“‘Moreover you shall take no ransom for the life of a murderer who is guilty of death. He shall surely be put to death. ",
      "32": "“‘You shall take no ransom for him who has fled to his city of refuge, that he may come again to dwell in the land before the death of the priest. ",
      "33": "“‘So you shall not pollute the land where you live; for blood pollutes the land. No atonement can be made for the land for the blood that is shed in it, but by the blood of him who shed it.",
      "34": "You shall not defile the land which you inhabit, where I dwell; for I, Yahweh, dwell among the children of Israel.’”"
    },
    "36": {
      "1": "The heads of the fathers’ households of the family of the children of Gilead, the son of Machir, the son of Manasseh, of the families of the sons of Joseph, came near and spoke before Moses and before the princes, the heads of the fathers’ households of the children of Israel.",
      "2": "They said, “Yahweh commanded my lord to give the land for inheritance by lot to the children of Israel. My lord was commanded by Yahweh to give the inheritance of Zelophehad our brother to his daughters.",
      "3": "If they are married to any of the sons of the other tribes of the children of Israel, then their inheritance will be taken away from the inheritance of our fathers, and will be added to the inheritance of the tribe to which they shall belong. So it will be taken away from the lot of our inheritance.",
      "4": "When the jubilee of the children of Israel comes, then their inheritance will be added to the inheritance of the tribe to which they shall belong. So their inheritance will be taken away from the inheritance of the tribe of our fathers.” ",
      "5": "Moses commanded the children of Israel according to Yahweh’s word, saying, “The tribe of the sons of Joseph speak what is right.",
      "6": "This is the thing which Yahweh commands concerning the daughters of Zelophehad, saying, ‘Let them be married to whom they think best, only they shall marry into the family of the tribe of their father.",
      "7": "So shall no inheritance of the children of Israel move from tribe to tribe; for the children of Israel shall all keep the inheritance of the tribe of his fathers.",
      "8": "Every daughter who possesses an inheritance in any tribe of the children of Israel shall be wife to one of the family of the tribe of her father, that the children of Israel may each possess the inheritance of his fathers.",
      "9": "So shall no inheritance move from one tribe to another tribe; for the tribes of the children of Israel shall each keep his own inheritance.’” ",
      "10": "The daughters of Zelophehad did as Yahweh commanded Moses:",
      "11": "for Mahlah, Tirzah, Hoglah, Milcah, and Noah, the daughters of Zelophehad, were married to their father’s brothers’ sons.",
      "12": "They were married into the families of the sons of Manasseh the son of Joseph. Their inheritance remained in the tribe of the family of their father. ",
      "13": "These are the commandments and the ordinances which Yahweh commanded by Moses to the children of Israel in the plains of Moab by the Jordan at Jericho."
    }
  },
  "deuteronomy": {
    "1": {
      "1": "These are the words which Moses spoke to all Israel beyond the Jordan in the wilderness, in the Arabah opposite Suf, between Paran, Tophel, Laban, Hazeroth, and Dizahab.",
      "2": "It is eleven days’ journey from Horeb by the way of Mount Seir to Kadesh Barnea.",
      "3": "In the fortieth year, in the eleventh month, on the first day of the month, Moses spoke to the children of Israel according to all that Yahweh  had given him in commandment to them,",
      "4": "after he had struck Sihon the king of the Amorites who lived in Heshbon, and Og the king of Bashan who lived in Ashtaroth, at Edrei.",
      "5": "Beyond the Jordan, in the land of Moab, Moses began to declare this law, saying,",
      "6": "“Yahweh our God  spoke to us in Horeb, saying, ‘You have lived long enough at this mountain.",
      "7": "Turn, and take your journey, and go to the hill country of the Amorites and to all the places near there: in the Arabah, in the hill country, in the lowland, in the South, by the seashore, in the land of the Canaanites, and in Lebanon as far as the great river, the river Euphrates.",
      "8": "Behold,  I have set the land before you. Go in and possess the land which Yahweh swore to your fathers—to Abraham, to Isaac, and to Jacob—to give to them and to their offspring  after them.’” ",
      "9": "I spoke to you at that time, saying, “I am not able to bear you myself alone.",
      "10": "Yahweh your God has multiplied you, and behold, you are today as the stars of the sky for multitude.",
      "11": "May Yahweh, the God of your fathers, make you a thousand times as many as you are and bless you, as he has promised you!",
      "12": "How can I myself alone bear your problems, your burdens, and your strife?",
      "13": "Take wise men of understanding who are respected among your tribes, and I will make them heads over you.” ",
      "14": "You answered me, and said, “The thing which you have spoken is good to do.”",
      "15": "So I took the heads of your tribes, wise and respected men, and made them heads over you, captains of thousands, captains of hundreds, captains of fifties, captains of tens, and officers, according to your tribes.",
      "16": "I commanded your judges at that time, saying, “Hear cases between your brothers and judge righteously between a man and his brother, and the foreigner who is living with him.",
      "17": "You shall not show partiality in judgment; you shall hear the small and the great alike. You shall not be afraid of the face of man, for the judgment is God’s. The case that is too hard for you, you shall bring to me, and I will hear it.”",
      "18": "I commanded you at that time all the things which you should do.",
      "19": "We traveled from Horeb and went through all that great and terrible wilderness which you saw, by the way to the hill country of the Amorites, as Yahweh our God commanded us; and we came to Kadesh Barnea.",
      "20": "I said to you, “You have come to the hill country of the Amorites, which Yahweh our God gives to us.",
      "21": "Behold, Yahweh your God has set the land before you. Go up, take possession, as Yahweh the God of your fathers has spoken to you. Don’t be afraid, neither be dismayed.” ",
      "22": "You came near to me, everyone of you, and said, “Let’s send men before us, that they may search the land for us, and bring back to us word of the way by which we must go up, and the cities to which we shall come.” ",
      "23": "The thing pleased me well. I took twelve of your men, one man for every tribe.",
      "24": "They turned and went up into the hill country, and came to the valley of Eshcol, and spied it out.",
      "25": "They took some of the fruit of the land in their hands and brought it down to us, and brought us word again, and said, “It is a good land which Yahweh our God gives to us.” ",
      "26": "Yet you wouldn’t go up, but rebelled against the commandment of Yahweh your God.",
      "27": "You murmured in your tents, and said, “Because Yahweh hated us, he has brought us out of the land of Egypt, to deliver us into the hand of the Amorites to destroy us.",
      "28": "Where are we going up? Our brothers have made our heart melt, saying, ‘The people are greater and taller than we. The cities are great and fortified up to the sky. Moreover we have seen the sons of the Anakim there!’” ",
      "29": "Then I said to you, “Don’t be terrified. Don’t be afraid of them.",
      "30": "Yahweh your God, who goes before you, he will fight for you, according to all that he did for you in Egypt before your eyes,",
      "31": "and in the wilderness where you have seen how that Yahweh your God carried you, as a man carries his son, in all the way that you went, until you came to this place.” ",
      "32": "Yet in this thing you didn’t believe Yahweh your God,",
      "33": "who went before you on the way, to seek out a place for you to pitch your tents in: in fire by night, to show you by what way you should go, and in the cloud by day.",
      "34": "Yahweh heard the voice of your words and was angry, and swore, saying,",
      "35": "“Surely not one of these men of this evil generation shall see the good land which I swore to give to your fathers,",
      "36": "except Caleb the son of Jephunneh. He shall see it. I will give the land that he has trodden on to him and to his children, because he has wholly followed Yahweh.” ",
      "37": "Also Yahweh was angry with me for your sakes, saying, “You also shall not go in there.",
      "38": "Joshua the son of Nun, who stands before you, shall go in there. Encourage him, for he shall cause Israel to inherit it.",
      "39": "Moreover your little ones, whom you said would be captured or killed, your children, who today have no knowledge of good or evil, shall go in there. I will give it to them, and they shall possess it.",
      "40": "But as for you, turn, and take your journey into the wilderness by the way to the Red Sea.” ",
      "41": "Then you answered and said to me, “We have sinned against Yahweh. We will go up and fight, according to all that Yahweh our God commanded us.” Every man of you put on his weapons of war, and presumed to go up into the hill country. ",
      "42": "Yahweh said to me, “Tell them, ‘Don’t go up and don’t fight; for I am not among you, lest you be struck before your enemies.’” ",
      "43": "So I spoke to you, and you didn’t listen; but you rebelled against the commandment of Yahweh, and were presumptuous, and went up into the hill country.",
      "44": "The Amorites, who lived in that hill country, came out against you and chased you as bees do, and beat you down in Seir, even to Hormah.",
      "45": "You returned and wept before Yahweh, but Yahweh didn’t listen to your voice, nor turn his ear to you.",
      "46": "So you stayed in Kadesh many days, according to the days that you remained."
    },
    "2": {
      "1": "Then we turned, and took our journey into the wilderness by the way to the Red Sea, as Yahweh spoke to me; and we encircled Mount Seir many days. ",
      "2": "Yahweh spoke to me, saying,",
      "3": "“You have encircled this mountain long enough. Turn northward.",
      "4": "Command the people, saying, ‘You are to pass through the border of your brothers, the children of Esau, who dwell in Seir; and they will be afraid of you. Therefore be careful.",
      "5": "Don’t contend with them; for I will not give you any of their land, no, not so much as for the sole of the foot to tread on, because I have given Mount Seir to Esau for a possession.",
      "6": "You shall purchase food from them for money, that you may eat. You shall also buy water from them for money, that you may drink.’” ",
      "7": "For Yahweh your God has blessed you in all the work of your hands. He has known your walking through this great wilderness. These forty years, Yahweh your God has been with you. You have lacked nothing. ",
      "8": "So we passed by from our brothers, the children of Esau, who dwell in Seir, from the way of the Arabah from Elath and from Ezion Geber. We turned and passed by the way of the wilderness of Moab. ",
      "9": "Yahweh said to me, “Don’t bother Moab, neither contend with them in battle; for I will not give you any of his land for a possession, because I have given Ar to the children of Lot for a possession.” ",
      "10": "(The Emim lived there before, a great and numerous people, and tall as the Anakim.",
      "11": "These also are considered to be Rephaim, as the Anakim; but the Moabites call them Emim.",
      "12": "The Horites also lived in Seir in the past, but the children of Esau succeeded them. They destroyed them from before them, and lived in their place, as Israel did to the land of his possession, which Yahweh gave to them.) ",
      "13": "“Now rise up and cross over the brook Zered.” We went over the brook Zered. ",
      "14": "The days in which we came from Kadesh Barnea until we had come over the brook Zered were thirty-eight years, until all the generation of the men of war were consumed from the middle of the camp, as Yahweh swore to them.",
      "15": "Moreover Yahweh’s hand was against them, to destroy them from the middle of the camp, until they were consumed.",
      "16": "So, when all the men of war were consumed and dead from among the people,",
      "17": "Yahweh spoke to me, saying,",
      "18": "“You are to pass over Ar, the border of Moab, today.",
      "19": "When you come near the border of the children of Ammon, don’t bother them, nor contend with them; for I will not give you any of the land of the children of Ammon for a possession, because I have given it to the children of Lot for a possession.” ",
      "20": "(That also is considered a land of Rephaim. Rephaim lived there in the past, but the Ammonites call them Zamzummim,",
      "21": "a great people, many, and tall, as the Anakim; but Yahweh destroyed them from before Israel, and they succeeded them, and lived in their place,",
      "22": "as he did for the children of Esau who dwell in Seir, when he destroyed the Horites from before them; and they succeeded them, and lived in their place even to this day.",
      "23": "Then the Avvim, who lived in villages as far as Gaza: the Caphtorim, who came out of Caphtor, destroyed them and lived in their place.) ",
      "24": "“Rise up, take your journey, and pass over the valley of the Arnon. Behold, I have given into your hand Sihon the Amorite, king of Heshbon, and his land; begin to possess it, and contend with him in battle.",
      "25": "Today I will begin to put the dread of you and the fear of you on the peoples who are under the whole sky, who shall hear the report of you, and shall tremble and be in anguish because of you.” ",
      "26": "I sent messengers out of the wilderness of Kedemoth to Sihon king of Heshbon with words of peace, saying,",
      "27": "“Let me pass through your land. I will go along by the highway. I will turn neither to the right hand nor to the left.",
      "28": "You shall sell me food for money, that I may eat; and give me water for money, that I may drink. Just let me pass through on my feet,",
      "29": "as the children of Esau who dwell in Seir, and the Moabites who dwell in Ar, did to me, until I pass over the Jordan into the land which Yahweh our God gives us.”",
      "30": "But Sihon king of Heshbon would not let us pass by him, for Yahweh your God hardened his spirit and made his heart obstinate, that he might deliver him into your hand, as it is today. ",
      "31": "Yahweh said to me, “Behold, I have begun to deliver up Sihon and his land before you. Begin to possess, that you may inherit his land.”",
      "32": "Then Sihon came out against us, he and all his people, to battle at Jahaz.",
      "33": "Yahweh our God delivered him up before us; and we struck him, his sons, and all his people.",
      "34": "We took all his cities at that time, and utterly destroyed every inhabited city, with the women and the little ones. We left no one remaining.",
      "35": "Only the livestock we took for plunder for ourselves, with the plunder of the cities which we had taken.",
      "36": "From Aroer, which is on the edge of the valley of the Arnon, and the city that is in the valley, even to Gilead, there was not a city too high for us. Yahweh our God delivered up all before us.",
      "37": "Only to the land of the children of Ammon you didn’t come near: all the banks of the river Jabbok, and the cities of the hill country, and wherever Yahweh our God forbade us."
    }
  }
};

