
	
export const bib_verses = {
  "micah": {
    "1": {
      "1": "The word of the LORD that came to Micah the Morasthite in the days of Jotham, Ahaz,  and  Hezekiah, kings of Judah, which he saw concerning Samaria and Jerusalem.",
      "2": "Hear, all ye people; hearken, O earth, and all that therein is: and let the Lord GOD be witness against you, the Lord from his holy temple.  ",
      "3": "For, behold, the LORD cometh forth out of his place, and will come down, and tread upon the high places of the earth.",
      "4": "And the mountains shall be molten under him, and the valleys shall be cleft, as wax before the fire,  and  as the waters  that are  poured down a steep place. ",
      "5": "For the transgression of Jacob  is  all this, and for the sins of the house of Israel. What  is  the transgression of Jacob?  is it  not Samaria? and what  are  the high places of Judah?  are they  not Jerusalem?",
      "6": "Therefore I will make Samaria as an heap of the field,  and  as plantings of a vineyard: and I will pour down the stones thereof into the valley, and I will discover the foundations thereof.",
      "7": "And all the graven images thereof shall be beaten to pieces, and all the hires thereof shall be burned with the fire, and all the idols thereof will I lay desolate: for she gathered  it  of the hire of an harlot, and they shall return to the hire of an harlot. ",
      "8": "Therefore I will wail and howl, I will go stripped and naked: I will make a wailing like the dragons, and mourning as the owls. ",
      "9": "For her wound  is  incurable; for it is come unto Judah; he is come unto the gate of my people,  even  to Jerusalem. ",
      "10": "Declare ye  it  not at Gath, weep ye not at all: in the house of Aphrah roll thyself in the dust. ",
      "11": "Pass ye away, thou inhabitant of Saphir, having thy shame naked: the inhabitant of Zaanan came not forth in the mourning of Bethezel; he shall receive of you his standing.    ",
      "12": "For the inhabitant of Maroth waited carefully for good: but evil came down from the LORD unto the gate of Jerusalem.  ",
      "13": "O thou inhabitant of Lachish, bind the chariot to the swift beast: she  is  the beginning of the sin to the daughter of Zion: for the transgressions of Israel were found in thee. ",
      "14": "Therefore shalt thou give presents to Moreshethgath: the houses of Achzib  shall be  a lie to the kings of Israel.  ",
      "15": "Yet will I bring an heir unto thee, O inhabitant of Mareshah: he shall come unto Adullam the glory of Israel.  ",
      "16": "Make thee bald, and poll thee for thy delicate children; enlarge thy baldness as the eagle; for they are gone into captivity from thee. "
    },
    "2": {
      "1": "Woe to them that devise iniquity, and work evil upon their beds! when the morning is light, they practise it, because it is in the power of their hand.",
      "2": "And they covet fields, and take  them  by violence; and houses, and take  them  away: so they oppress a man and his house, even a man and his heritage. ",
      "3": "Therefore thus saith the LORD; Behold, against this family do I devise an evil, from which ye shall not remove your necks; neither shall ye go haughtily: for this time  is  evil.",
      "4": "In that day shall  one  take up a parable against you, and lament with a doleful lamentation,  and  say, We be utterly spoiled: he hath changed the portion of my people: how hath he removed  it  from me! turning away he hath divided our fields.  ",
      "5": "Therefore thou shalt have none that shall cast a cord by lot in the congregation of the LORD. ",
      "6": "Prophesy ye not,  say they to them that  prophesy: they shall not prophesy to them,  that  they shall not take shame. ",
      "7": "O  thou that art  named the house of Jacob, is the spirit of the LORD straitened?  are  these his doings? do not my words do good to him that walketh uprightly?  ",
      "8": "Even of late my people is risen up as an enemy: ye pull off the robe with the garment from them that pass by securely as men averse from war.  ",
      "9": "The women of my people have ye cast out from their pleasant houses; from their children have ye taken away my glory for ever. ",
      "10": "Arise ye, and depart; for this  is  not  your  rest: because it is polluted, it shall destroy  you , even with a sore destruction.",
      "11": "If a man walking in the spirit and falsehood do lie,  saying , I will prophesy unto thee of wine and of strong drink; he shall even be the prophet of this people.  ",
      "12": "I will surely assemble, O Jacob, all of thee; I will surely gather the remnant of Israel; I will put them together as the sheep of Bozrah, as the flock in the midst of their fold: they shall make great noise by reason of  the multitude of  men.",
      "13": "The breaker is come up before them: they have broken up, and have passed through the gate, and are gone out by it: and their king shall pass before them, and the LORD on the head of them. "
    },
    "3": {
      "1": "And I said, Hear, I pray you, O heads of Jacob, and ye princes of the house of Israel;  Is it  not for you to know judgment?",
      "2": "Who hate the good, and love the evil; who pluck off their skin from off them, and their flesh from off their bones;",
      "3": "Who also eat the flesh of my people, and flay their skin from off them; and they break their bones, and chop them in pieces, as for the pot, and as flesh within the caldron.",
      "4": "Then shall they cry unto the LORD, but he will not hear them: he will even hide his face from them at that time, as they have behaved themselves ill in their doings.",
      "5": "Thus saith the LORD concerning the prophets that make my people err, that bite with their teeth, and cry, Peace; and he that putteth not into their mouths, they even prepare war against him.",
      "6": "Therefore night  shall be  unto you, that ye shall not have a vision; and it shall be dark unto you, that ye shall not divine; and the sun shall go down over the prophets, and the day shall be dark over them.  ",
      "7": "Then shall the seers be ashamed, and the diviners confounded: yea, they shall all cover their lips; for  there is  no answer of God.  ",
      "8": "But truly I am full of power by the spirit of the LORD, and of judgment, and of might, to declare unto Jacob his transgression, and to Israel his sin.",
      "9": "Hear this, I pray you, ye heads of the house of Jacob, and princes of the house of Israel, that abhor judgment, and pervert all equity.",
      "10": "They build up Zion with blood, and Jerusalem with iniquity. ",
      "11": "The heads thereof judge for reward, and the priests thereof teach for hire, and the prophets thereof divine for money: yet will they lean upon the LORD, and say,  Is  not the LORD among us? none evil can come upon us. ",
      "12": "Therefore shall Zion for your sake be plowed  as  a field, and Jerusalem shall become heaps, and the mountain of the house as the high places of the forest. "
    },
    "4": {
      "1": "But in the last days it shall come to pass,  that  the mountain of the house of the LORD shall be established in the top of the mountains, and it shall be exalted above the hills; and people shall flow unto it.",
      "2": "And many nations shall come, and say, Come, and let us go up to the mountain of the LORD, and to the house of the God of Jacob; and he will teach us of his ways, and we will walk in his paths: for the law shall go forth of Zion, and the word of the LORD from Jerusalem.",
      "3": "And he shall judge among many people, and rebuke strong nations afar off; and they shall beat their swords into plowshares, and their spears into pruninghooks: nation shall not lift up a sword against nation, neither shall they learn war any more. ",
      "4": "But they shall sit every man under his vine and under his fig tree; and none shall make  them  afraid: for the mouth of the LORD of hosts hath spoken  it .",
      "5": "For all people will walk every one in the name of his god, and we will walk in the name of the LORD our God for ever and ever.",
      "6": "In that day, saith the LORD, will I assemble her that halteth, and I will gather her that is driven out, and her that I have afflicted;",
      "7": "And I will make her that halted a remnant, and her that was cast far off a strong nation: and the LORD shall reign over them in mount Zion from henceforth, even for ever. ",
      "8": "And thou, O tower of the flock, the strong hold of the daughter of Zion, unto thee shall it come, even the first dominion; the kingdom shall come to the daughter of Jerusalem.",
      "9": "Now why dost thou cry out aloud?  is there  no king in thee? is thy counsellor perished? for pangs have taken thee as a woman in travail.",
      "10": "Be in pain, and labour to bring forth, O daughter of Zion, like a woman in travail: for now shalt thou go forth out of the city, and thou shalt dwell in the field, and thou shalt go  even  to Babylon; there shalt thou be delivered; there the LORD shall redeem thee from the hand of thine enemies.",
      "11": "Now also many nations are gathered against thee, that say, Let her be defiled, and let our eye look upon Zion.",
      "12": "But they know not the thoughts of the LORD, neither understand they his counsel: for he shall gather them as the sheaves into the floor.",
      "13": "Arise and thresh, O daughter of Zion: for I will make thine horn iron, and I will make thy hoofs brass: and thou shalt beat in pieces many people: and I will consecrate their gain unto the LORD, and their substance unto the Lord of the whole earth. "
    },
    "5": {
      "1": "Now gather thyself in troops, O daughter of troops: he hath laid siege against us: they shall smite the judge of Israel with a rod upon the cheek.",
      "2": "But thou, Bethlehem Ephratah,  though  thou be little among the thousands of Judah,  yet  out of thee shall he come forth unto me  that is  to be ruler in Israel; whose goings forth  have been  from of old, from everlasting. ",
      "3": "Therefore will he give them up, until the time  that  she which travaileth hath brought forth: then the remnant of his brethren shall return unto the children of Israel.",
      "4": "And he shall stand and feed in the strength of the LORD, in the majesty of the name of the LORD his God; and they shall abide: for now shall he be great unto the ends of the earth. ",
      "5": "And this  man  shall be the peace, when the Assyrian shall come into our land: and when he shall tread in our palaces, then shall we raise against him seven shepherds, and eight principal men. ",
      "6": "And they shall waste the land of Assyria with the sword, and the land of Nimrod in the entrances thereof: thus shall he deliver  us  from the Assyrian, when he cometh into our land, and when he treadeth within our borders.   ",
      "7": "And the remnant of Jacob shall be in the midst of many people as a dew from the LORD, as the showers upon the grass, that tarrieth not for man, nor waiteth for the sons of men.",
      "8": "And the remnant of Jacob shall be among the Gentiles in the midst of many people as a lion among the beasts of the forest, as a young lion among the flocks of sheep: who, if he go through, both treadeth down, and teareth in pieces, and none can deliver. ",
      "9": "Thine hand shall be lifted up upon thine adversaries, and all thine enemies shall be cut off.",
      "10": "And it shall come to pass in that day, saith the LORD, that I will cut off thy horses out of the midst of thee, and I will destroy thy chariots:",
      "11": "And I will cut off the cities of thy land, and throw down all thy strong holds:",
      "12": "And I will cut off witchcrafts out of thine hand; and thou shalt have no  more  soothsayers:",
      "13": "Thy graven images also will I cut off, and thy standing images out of the midst of thee; and thou shalt no more worship the work of thine hands. ",
      "14": "And I will pluck up thy groves out of the midst of thee: so will I destroy thy cities. ",
      "15": "And I will execute vengeance in anger and fury upon the heathen, such as they have not heard. "
    },
    "6": {
      "1": "Hear ye now what the LORD saith; Arise, contend thou before the mountains, and let the hills hear thy voice. ",
      "2": "Hear ye, O mountains, the LORD'S controversy, and ye strong foundations of the earth: for the LORD hath a controversy with his people, and he will plead with Israel.",
      "3": "O my people, what have I done unto thee? and wherein have I wearied thee? testify against me.",
      "4": "For I brought thee up out of the land of Egypt, and redeemed thee out of the house of servants; and I sent before thee Moses, Aaron, and Miriam.",
      "5": "O my people, remember now what Balak king of Moab consulted, and what Balaam the son of Beor answered him from Shittim unto Gilgal; that ye may know the righteousness of the LORD. ",
      "6": "Wherewith shall I come before the LORD,  and  bow myself before the high God? shall I come before him with burnt offerings, with calves of a year old? ",
      "7": "Will the LORD be pleased with thousands of rams,  or  with ten thousands of rivers of oil? shall I give my firstborn  for  my transgression, the fruit of my body  for  the sin of my soul? ",
      "8": "He hath shewed thee, O man, what  is  good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?  ",
      "9": "The LORD'S voice crieth unto the city, and  the man of  wisdom shall see thy name: hear ye the rod, and who hath appointed it. ",
      "10": "Are there yet the treasures of wickedness in the house of the wicked, and the scant measure  that is  abominable?  ",
      "11": "Shall I count  them  pure with the wicked balances, and with the bag of deceitful weights? ",
      "12": "For the rich men thereof are full of violence, and the inhabitants thereof have spoken lies, and their tongue  is  deceitful in their mouth.",
      "13": "Therefore also will I make  thee  sick in smiting thee, in making  thee  desolate because of thy sins.",
      "14": "Thou shalt eat, but not be satisfied; and thy casting down  shall be  in the midst of thee; and thou shalt take hold, but shalt not deliver; and  that  which thou deliverest will I give up to the sword.",
      "15": "Thou shalt sow, but thou shalt not reap; thou shalt tread the olives, but thou shalt not anoint thee with oil; and sweet wine, but shalt not drink wine.",
      "16": "For the statutes of Omri are kept, and all the works of the house of Ahab, and ye walk in their counsels; that I should make thee a desolation, and the inhabitants thereof an hissing: therefore ye shall bear the reproach of my people.   "
    },
    "7": {
      "1": "Woe is me! for I am as when they have gathered the summer fruits, as the grapegleanings of the vintage:  there is  no cluster to eat: my soul desired the firstripe fruit. ",
      "2": "The good  man  is perished out of the earth: and  there is  none upright among men: they all lie in wait for blood; they hunt every man his brother with a net. ",
      "3": "That they may do evil with both hands earnestly, the prince asketh, and the judge  asketh  for a reward; and the great  man , he uttereth his mischievous desire: so they wrap it up. ",
      "4": "The best of them  is  as a brier: the most upright  is sharper  than a thorn hedge: the day of thy watchmen  and  thy visitation cometh; now shall be their perplexity.",
      "5": "Trust ye not in a friend, put ye not confidence in a guide: keep the doors of thy mouth from her that lieth in thy bosom.",
      "6": "For the son dishonoureth the father, the daughter riseth up against her mother, the daughter in law against her mother in law; a man's enemies  are  the men of his own house. ",
      "7": "Therefore I will look unto the LORD; I will wait for the God of my salvation: my God will hear me.",
      "8": "Rejoice not against me, O mine enemy: when I fall, I shall arise; when I sit in darkness, the LORD  shall be  a light unto me.",
      "9": "I will bear the indignation of the LORD, because I have sinned against him, until he plead my cause, and execute judgment for me: he will bring me forth to the light,  and  I shall behold his righteousness.",
      "10": "Then  she that is  mine enemy shall see  it , and shame shall cover her which said unto me, Where is the LORD thy God? mine eyes shall behold her: now shall she be trodden down as the mire of the streets.  ",
      "11": " In  the day that thy walls are to be built,  in  that day shall the decree be far removed.",
      "12": " In  that day  also  he shall come even to thee from Assyria, and  from  the fortified cities, and from the fortress even to the river, and from sea to sea, and  from  mountain to mountain. ",
      "13": "Notwithstanding the land shall be desolate because of them that dwell therein, for the fruit of their doings.  ",
      "14": "Feed thy people with thy rod, the flock of thine heritage, which dwell solitarily  in  the wood, in the midst of Carmel: let them feed  in  Bashan and Gilead, as in the days of old. ",
      "15": "According to the days of thy coming out of the land of Egypt will I shew unto him marvellous  things .",
      "16": "The nations shall see and be confounded at all their might: they shall lay  their  hand upon  their  mouth, their ears shall be deaf.",
      "17": "They shall lick the dust like a serpent, they shall move out of their holes like worms of the earth: they shall be afraid of the LORD our God, and shall fear because of thee. ",
      "18": "Who  is  a God like unto thee, that pardoneth iniquity, and passeth by the transgression of the remnant of his heritage? he retaineth not his anger for ever, because he delighteth  in  mercy.",
      "19": "He will turn again, he will have compassion upon us; he will subdue our iniquities; and thou wilt cast all their sins into the depths of the sea.",
      "20": "Thou wilt perform the truth to Jacob,  and  the mercy to Abraham, which thou hast sworn unto our fathers from the days of old. "
    }
  },
  "nahum": {
    "1": {
      "1": "The burden of Nineveh. The book of the vision of Nahum the Elkoshite. ",
      "2": "God  is  jealous, and the LORD revengeth; the LORD revengeth, and  is  furious; the LORD will take vengeance on his adversaries, and he reserveth  wrath  for his enemies.  ",
      "3": "The LORD  is  slow to anger, and great in power, and will not at all acquit  the wicked : the LORD hath his way in the whirlwind and in the storm, and the clouds  are  the dust of his feet.",
      "4": "He rebuketh the sea, and maketh it dry, and drieth up all the rivers: Bashan languisheth, and Carmel, and the flower of Lebanon languisheth.",
      "5": "The mountains quake at him, and the hills melt, and the earth is burned at his presence, yea, the world, and all that dwell therein.",
      "6": "Who can stand before his indignation? and who can abide in the fierceness of his anger? his fury is poured out like fire, and the rocks are thrown down by him. ",
      "7": "The LORD  is  good, a strong hold in the day of trouble; and he knoweth them that trust in him. ",
      "8": "But with an overrunning flood he will make an utter end of the place thereof, and darkness shall pursue his enemies. ",
      "9": "What do ye imagine against the LORD? he will make an utter end: affliction shall not rise up the second time.",
      "10": "For while  they be  folden together  as  thorns, and while they are drunken  as  drunkards, they shall be devoured as stubble fully dry.",
      "11": "There is  one  come out of thee, that imagineth evil against the LORD, a wicked counsellor. ",
      "12": "Thus saith the LORD; Though  they be  quiet, and likewise many, yet thus shall they be cut down, when he shall pass through. Though I have afflicted thee, I will afflict thee no more.  ",
      "13": "For now will I break his yoke from off thee, and will burst thy bonds in sunder.",
      "14": "And the LORD hath given a commandment concerning thee,  that  no more of thy name be sown: out of the house of thy gods will I cut off the graven image and the molten image: I will make thy grave; for thou art vile.",
      "15": "Behold upon the mountains the feet of him that bringeth good tidings, that publisheth peace! O Judah, keep thy solemn feasts, perform thy vows: for the wicked shall no more pass through thee; he is utterly cut off.   "
    },
    "2": {
      "1": "He that dasheth in pieces is come up before thy face: keep the munition, watch the way, make  thy  loins strong, fortify  thy  power mightily. ",
      "2": "For the LORD hath turned away the excellency of Jacob, as the excellency of Israel: for the emptiers have emptied them out, and marred their vine branches. ",
      "3": "The shield of his mighty men is made red, the valiant men  are  in scarlet: the chariots  shall be  with flaming torches in the day of his preparation, and the fir trees shall be terribly shaken.  ",
      "4": "The chariots shall rage in the streets, they shall justle one against another in the broad ways: they shall seem like torches, they shall run like the lightnings. ",
      "5": "He shall recount his worthies: they shall stumble in their walk; they shall make haste to the wall thereof, and the defence shall be prepared.  ",
      "6": "The gates of the rivers shall be opened, and the palace shall be dissolved. ",
      "7": "And Huzzab shall be led away captive, she shall be brought up, and her maids shall lead  her  as with the voice of doves, tabering upon their breasts.  ",
      "8": "But Nineveh  is  of old like a pool of water: yet they shall flee away. Stand, stand,  shall they cry ; but none shall look back.  ",
      "9": "Take ye the spoil of silver, take the spoil of gold: for  there is  none end of the store  and  glory out of all the pleasant furniture.  ",
      "10": "She is empty, and void, and waste: and the heart melteth, and the knees smite together, and much pain  is  in all loins, and the faces of them all gather blackness. ",
      "11": "Where  is  the dwelling of the lions, and the feedingplace of the young lions, where the lion,  even  the old lion, walked,  and  the lion's whelp, and none made  them  afraid?",
      "12": "The lion did tear in pieces enough for his whelps, and strangled for his lionesses, and filled his holes with prey, and his dens with ravin.",
      "13": "Behold, I  am  against thee, saith the LORD of hosts, and I will burn her chariots in the smoke, and the sword shall devour thy young lions: and I will cut off thy prey from the earth, and the voice of thy messengers shall no more be heard. "
    },
    "3": {
      "1": "Woe to the bloody city! it  is  all full of lies  and  robbery; the prey departeth not; ",
      "2": "The noise of a whip, and the noise of the rattling of the wheels, and of the pransing horses, and of the jumping chariots.",
      "3": "The horseman lifteth up both the bright sword and the glittering spear: and  there is  a multitude of slain, and a great number of carcases; and  there is  none end of  their  corpses; they stumble upon their corpses: ",
      "4": "Because of the multitude of the whoredoms of the wellfavoured harlot, the mistress of witchcrafts, that selleth nations through her whoredoms, and families through her witchcrafts.",
      "5": "Behold, I  am  against thee, saith the LORD of hosts; and I will discover thy skirts upon thy face, and I will shew the nations thy nakedness, and the kingdoms thy shame.",
      "6": "And I will cast abominable filth upon thee, and make thee vile, and will set thee as a gazingstock.",
      "7": "And it shall come to pass,  that  all they that look upon thee shall flee from thee, and say, Nineveh is laid waste: who will bemoan her? whence shall I seek comforters for thee? ",
      "8": "Art thou better than populous No, that was situate among the rivers,  that had  the waters round about it, whose rampart  was  the sea,  and  her wall  was  from the sea? ",
      "9": "Ethiopia and Egypt  were  her strength, and  it was  infinite; Put and Lubim were thy helpers. ",
      "10": "Yet  was  she carried away, she went into captivity: her young children also were dashed in pieces at the top of all the streets: and they cast lots for her honourable men, and all her great men were bound in chains.",
      "11": "Thou also shalt be drunken: thou shalt be hid, thou also shalt seek strength because of the enemy.",
      "12": "All thy strong holds  shall be like  fig trees with the firstripe figs: if they be shaken, they shall even fall into the mouth of the eater.",
      "13": "Behold, thy people in the midst of thee  are  women: the gates of thy land shall be set wide open unto thine enemies: the fire shall devour thy bars.",
      "14": "Draw thee waters for the siege, fortify thy strong holds: go into clay, and tread the morter, make strong the brickkiln.",
      "15": "There shall the fire devour thee; the sword shall cut thee off, it shall eat thee up like the cankerworm: make thyself many as the cankerworm, make thyself many as the locusts.",
      "16": "Thou hast multiplied thy merchants above the stars of heaven: the cankerworm spoileth, and flieth away. ",
      "17": "Thy crowned  are  as the locusts, and thy captains as the great grasshoppers, which camp in the hedges in the cold day,  but  when the sun ariseth they flee away, and their place is not known where they  are .",
      "18": "Thy shepherds slumber, O king of Assyria: thy nobles shall dwell  in the dust : thy people is scattered upon the mountains, and no man gathereth  them . ",
      "19": " There is  no healing of thy bruise; thy wound is grievous: all that hear the bruit of thee shall clap the hands over thee: for upon whom hath not thy wickedness passed continually?  "
    }
  },
  "habakkuk": {
    "1": {
      "1": "The burden which Habakkuk the prophet did see.",
      "2": "O LORD, how long shall I cry, and thou wilt not hear!  even  cry out unto thee  of  violence, and thou wilt not save!",
      "3": "Why dost thou shew me iniquity, and cause  me  to behold grievance? for spoiling and violence  are  before me: and there are  that  raise up strife and contention.",
      "4": "Therefore the law is slacked, and judgment doth never go forth: for the wicked doth compass about the righteous; therefore wrong judgment proceedeth.  ",
      "5": "Behold ye among the heathen, and regard, and wonder marvellously: for  I  will work a work in your days,  which  ye will not believe, though it be told  you .",
      "6": "For, lo, I raise up the Chaldeans,  that  bitter and hasty nation, which shall march through the breadth of the land, to possess the dwellingplaces  that are  not theirs. ",
      "7": "They  are  terrible and dreadful: their judgment and their dignity shall proceed of themselves. ",
      "8": "Their horses also are swifter than the leopards, and are more fierce than the evening wolves: and their horsemen shall spread themselves, and their horsemen shall come from far; they shall fly as the eagle  that  hasteth to eat. ",
      "9": "They shall come all for violence: their faces shall sup up  as  the east wind, and they shall gather the captivity as the sand. ",
      "10": "And they shall scoff at the kings, and the princes shall be a scorn unto them: they shall deride every strong hold; for they shall heap dust, and take it.",
      "11": "Then shall  his  mind change, and he shall pass over, and offend,  imputing  this his power unto his god. ",
      "12": " Art  thou not from everlasting, O LORD my God, mine Holy One? we shall not die. O LORD, thou hast ordained them for judgment; and, O mighty God, thou hast established them for correction. ",
      "13": " Thou art  of purer eyes than to behold evil, and canst not look on iniquity: wherefore lookest thou upon them that deal treacherously,  and  holdest thy tongue when the wicked devoureth  the man that is  more righteous than he? ",
      "14": "And makest men as the fishes of the sea, as the creeping things,  that have  no ruler over them? ",
      "15": "They take up all of them with the angle, they catch them in their net, and gather them in their drag: therefore they rejoice and are glad. ",
      "16": "Therefore they sacrifice unto their net, and burn incense unto their drag; because by them their portion  is  fat, and their meat plenteous. ",
      "17": "Shall they therefore empty their net, and not spare continually to slay the nations? "
    },
    "2": {
      "1": "I will stand upon my watch, and set me upon the tower, and will watch to see what he will say unto me, and what I shall answer when I am reproved.   ",
      "2": "And the LORD answered me, and said, Write the vision, and make  it  plain upon tables, that he may run that readeth it.",
      "3": "For the vision  is  yet for an appointed time, but at the end it shall speak, and not lie: though it tarry, wait for it; because it will surely come, it will not tarry.",
      "4": "Behold, his soul  which  is lifted up is not upright in him: but the just shall live by his faith. ",
      "5": "Yea also, because he transgresseth by wine,  he is  a proud man, neither keepeth at home, who enlargeth his desire as hell, and  is  as death, and cannot be satisfied, but gathereth unto him all nations, and heapeth unto him all people: ",
      "6": "Shall not all these take up a parable against him, and a taunting proverb against him, and say, Woe to him that increaseth  that which is  not his! how long? and to him that ladeth himself with thick clay! ",
      "7": "Shall they not rise up suddenly that shall bite thee, and awake that shall vex thee, and thou shalt be for booties unto them?",
      "8": "Because thou hast spoiled many nations, all the remnant of the people shall spoil thee; because of men's blood, and  for  the violence of the land, of the city, and of all that dwell therein. ",
      "9": "Woe to him that coveteth an evil covetousness to his house, that he may set his nest on high, that he may be delivered from the power of evil!  ",
      "10": "Thou hast consulted shame to thy house by cutting off many people, and hast sinned  against  thy soul.",
      "11": "For the stone shall cry out of the wall, and the beam out of the timber shall answer it.  ",
      "12": "Woe to him that buildeth a town with blood, and stablisheth a city by iniquity! ",
      "13": "Behold,  is it  not of the LORD of hosts that the people shall labour in the very fire, and the people shall weary themselves for very vanity? ",
      "14": "For the earth shall be filled with the knowledge of the glory of the LORD, as the waters cover the sea.  ",
      "15": "Woe unto him that giveth his neighbour drink, that puttest thy bottle to  him , and makest  him  drunken also, that thou mayest look on their nakedness!",
      "16": "Thou art filled with shame for glory: drink thou also, and let thy foreskin be uncovered: the cup of the LORD'S right hand shall be turned unto thee, and shameful spewing  shall be  on thy glory. ",
      "17": "For the violence of Lebanon shall cover thee, and the spoil of beasts,  which  made them afraid, because of men's blood, and for the violence of the land, of the city, and of all that dwell therein.",
      "18": "What profiteth the graven image that the maker thereof hath graven it; the molten image, and a teacher of lies, that the maker of his work trusteth therein, to make dumb idols? ",
      "19": "Woe unto him that saith to the wood, Awake; to the dumb stone, Arise, it shall teach! Behold, it  is  laid over with gold and silver, and  there is  no breath at all in the midst of it.",
      "20": "But the LORD  is  in his holy temple: let all the earth keep silence before him.  "
    },
    "3": {
      "1": "A prayer of Habakkuk the prophet upon Shigionoth. ",
      "2": "O LORD, I have heard thy speech,  and  was afraid: O LORD, revive thy work in the midst of the years, in the midst of the years make known; in wrath remember mercy.   ",
      "3": "God came from Teman, and the Holy One from mount Paran. Selah. His glory covered the heavens, and the earth was full of his praise. ",
      "4": "And  his  brightness was as the light; he had horns  coming  out of his hand: and there  was  the hiding of his power. ",
      "5": "Before him went the pestilence, and burning coals went forth at his feet. ",
      "6": "He stood, and measured the earth: he beheld, and drove asunder the nations; and the everlasting mountains were scattered, the perpetual hills did bow: his ways  are  everlasting.",
      "7": "I saw the tents of Cushan in affliction:  and  the curtains of the land of Midian did tremble.  ",
      "8": "Was the LORD displeased against the rivers?  was  thine anger against the rivers?  was  thy wrath against the sea, that thou didst ride upon thine horses  and  thy chariots of salvation? ",
      "9": "Thy bow was made quite naked,  according  to the oaths of the tribes,  even thy  word. Selah. Thou didst cleave the earth with rivers. ",
      "10": "The mountains saw thee,  and  they trembled: the overflowing of the water passed by: the deep uttered his voice,  and  lifted up his hands on high.",
      "11": "The sun  and  moon stood still in their habitation: at the light of thine arrows they went,  and  at the shining of thy glittering spear. ",
      "12": "Thou didst march through the land in indignation, thou didst thresh the heathen in anger.",
      "13": "Thou wentest forth for the salvation of thy people,  even  for salvation with thine anointed; thou woundedst the head out of the house of the wicked, by discovering the foundation unto the neck. Selah. ",
      "14": "Thou didst strike through with his staves the head of his villages: they came out as a whirlwind to scatter me: their rejoicing  was  as to devour the poor secretly. ",
      "15": "Thou didst walk through the sea with thine horses,  through  the heap of great waters.  ",
      "16": "When I heard, my belly trembled; my lips quivered at the voice: rottenness entered into my bones, and I trembled in myself, that I might rest in the day of trouble: when he cometh up unto the people, he will invade them with his troops. ",
      "17": "Although the fig tree shall not blossom, neither  shall  fruit  be  in the vines; the labour of the olive shall fail, and the fields shall yield no meat; the flock shall be cut off from the fold, and  there shall be  no herd in the stalls: ",
      "18": "Yet I will rejoice in the LORD, I will joy in the God of my salvation.",
      "19": "The LORD God  is  my strength, and he will make my feet like hinds'  feet , and he will make me to walk upon mine high places. To the chief singer on my stringed instruments.  "
    }
  },
  "zephaniah": {
    "1": {
      "1": "The word of the LORD which came unto Zephaniah the son of Cushi, the son of Gedaliah, the son of Amariah, the son of Hizkiah, in the days of Josiah the son of Amon, king of Judah.",
      "2": "I will utterly consume all  things  from off the land, saith the LORD.  ",
      "3": "I will consume man and beast; I will consume the fowls of the heaven, and the fishes of the sea, and the stumblingblocks with the wicked; and I will cut off man from off the land, saith the LORD. ",
      "4": "I will also stretch out mine hand upon Judah, and upon all the inhabitants of Jerusalem; and I will cut off the remnant of Baal from this place,  and  the name of the Chemarims with the priests;",
      "5": "And them that worship the host of heaven upon the housetops; and them that worship  and  that swear by the LORD, and that swear by Malcham; ",
      "6": "And them that are turned back from the LORD; and  those  that have not sought the LORD, nor enquired for him. ",
      "7": "Hold thy peace at the presence of the Lord GOD: for the day of the LORD  is  at hand: for the LORD hath prepared a sacrifice, he hath bid his guests. ",
      "8": "And it shall come to pass in the day of the LORD'S sacrifice, that I will punish the princes, and the king's children, and all such as are clothed with strange apparel. ",
      "9": "In the same day also will I punish all those that leap on the threshold, which fill their masters' houses with violence and deceit.",
      "10": "And it shall come to pass in that day, saith the LORD,  that there shall be  the noise of a cry from the fish gate, and an howling from the second, and a great crashing from the hills.",
      "11": "Howl, ye inhabitants of Maktesh, for all the merchant people are cut down; all they that bear silver are cut off.",
      "12": "And it shall come to pass at that time,  that  I will search Jerusalem with candles, and punish the men that are settled on their lees: that say in their heart, The LORD will not do good, neither will he do evil. ",
      "13": "Therefore their goods shall become a booty, and their houses a desolation: they shall also build houses, but not inhabit  them ; and they shall plant vineyards, but not drink the wine thereof. ",
      "14": "The great day of the LORD  is  near,  it is  near, and hasteth greatly,  even  the voice of the day of the LORD: the mighty man shall cry there bitterly.",
      "15": "That day  is  a day of wrath, a day of trouble and distress, a day of wasteness and desolation, a day of darkness and gloominess, a day of clouds and thick darkness,",
      "16": "A day of the trumpet and alarm against the fenced cities, and against the high towers.",
      "17": "And I will bring distress upon men, that they shall walk like blind men, because they have sinned against the LORD: and their blood shall be poured out as dust, and their flesh as the dung.",
      "18": "Neither their silver nor their gold shall be able to deliver them in the day of the LORD'S wrath; but the whole land shall be devoured by the fire of his jealousy: for he shall make even a speedy riddance of all them that dwell in the land. "
    },
    "2": {
      "1": "Gather yourselves together, yea, gather together, O nation not desired; ",
      "2": "Before the decree bring forth,  before  the day pass as the chaff, before the fierce anger of the LORD come upon you, before the day of the LORD'S anger come upon you.",
      "3": "Seek ye the LORD, all ye meek of the earth, which have wrought his judgment; seek righteousness, seek meekness: it may be ye shall be hid in the day of the LORD'S anger. ",
      "4": "For Gaza shall be forsaken, and Ashkelon a desolation: they shall drive out Ashdod at the noon day, and Ekron shall be rooted up.",
      "5": "Woe unto the inhabitants of the sea coast, the nation of the Cherethites! the word of the LORD  is  against you; O Canaan, the land of the Philistines, I will even destroy thee, that there shall be no inhabitant.",
      "6": "And the sea coast shall be dwellings  and  cottages for shepherds, and folds for flocks.",
      "7": "And the coast shall be for the remnant of the house of Judah; they shall feed thereupon: in the houses of Ashkelon shall they lie down in the evening: for the LORD their God shall visit them, and turn away their captivity.  ",
      "8": "I have heard the reproach of Moab, and the revilings of the children of Ammon, whereby they have reproached my people, and magnified  themselves  against their border.",
      "9": "Therefore  as  I live, saith the LORD of hosts, the God of Israel, Surely Moab shall be as Sodom, and the children of Ammon as Gomorrah,  even  the breeding of nettles, and saltpits, and a perpetual desolation: the residue of my people shall spoil them, and the remnant of my people shall possess them.",
      "10": "This shall they have for their pride, because they have reproached and magnified  themselves  against the people of the LORD of hosts.",
      "11": "The LORD  will be  terrible unto them: for he will famish all the gods of the earth; and  men  shall worship him, every one from his place,  even  all the isles of the heathen.  ",
      "12": "Ye Ethiopians also, ye  shall be  slain by my sword.",
      "13": "And he will stretch out his hand against the north, and destroy Assyria; and will make Nineveh a desolation,  and  dry like a wilderness.",
      "14": "And flocks shall lie down in the midst of her, all the beasts of the nations: both the cormorant and the bittern shall lodge in the upper lintels of it;  their  voice shall sing in the windows; desolation  shall be  in the thresholds: for he shall uncover the cedar work.   ",
      "15": "This  is  the rejoicing city that dwelt carelessly, that said in her heart, I  am , and  there is  none beside me: how is she become a desolation, a place for beasts to lie down in! every one that passeth by her shall hiss,  and  wag his hand. "
    },
    "3": {
      "1": "Woe to her that is filthy and polluted, to the oppressing city! ",
      "2": "She obeyed not the voice; she received not correction; she trusted not in the LORD; she drew not near to her God. ",
      "3": "Her princes within her  are  roaring lions; her judges  are  evening wolves; they gnaw not the bones till the morrow.",
      "4": "Her prophets  are  light  and  treacherous persons: her priests have polluted the sanctuary, they have done violence to the law.",
      "5": "The just LORD  is  in the midst thereof; he will not do iniquity: every morning doth he bring his judgment to light, he faileth not; but the unjust knoweth no shame. ",
      "6": "I have cut off the nations: their towers are desolate; I made their streets waste, that none passeth by: their cities are destroyed, so that there is no man, that there is none inhabitant. ",
      "7": "I said, Surely thou wilt fear me, thou wilt receive instruction; so their dwelling should not be cut off, howsoever I punished them: but they rose early,  and  corrupted all their doings. ",
      "8": "Therefore wait ye upon me, saith the LORD, until the day that I rise up to the prey: for my determination  is  to gather the nations, that I may assemble the kingdoms, to pour upon them mine indignation,  even  all my fierce anger: for all the earth shall be devoured with the fire of my jealousy.",
      "9": "For then will I turn to the people a pure language, that they may all call upon the name of the LORD, to serve him with one consent.  ",
      "10": "From beyond the rivers of Ethiopia my suppliants,  even  the daughter of my dispersed, shall bring mine offering.",
      "11": "In that day shalt thou not be ashamed for all thy doings, wherein thou hast transgressed against me: for then I will take away out of the midst of thee them that rejoice in thy pride, and thou shalt no more be haughty because of my holy mountain. ",
      "12": "I will also leave in the midst of thee an afflicted and poor people, and they shall trust in the name of the LORD.",
      "13": "The remnant of Israel shall not do iniquity, nor speak lies; neither shall a deceitful tongue be found in their mouth: for they shall feed and lie down, and none shall make  them  afraid. ",
      "14": "Sing, O daughter of Zion; shout, O Israel; be glad and rejoice with all the heart, O daughter of Jerusalem.",
      "15": "The LORD hath taken away thy judgments, he hath cast out thine enemy: the king of Israel,  even  the LORD,  is  in the midst of thee: thou shalt not see evil any more.",
      "16": "In that day it shall be said to Jerusalem, Fear thou not:  and to  Zion, Let not thine hands be slack. ",
      "17": "The LORD thy God in the midst of thee  is  mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing. ",
      "18": "I will gather  them that are  sorrowful for the solemn assembly,  who  are of thee,  to whom  the reproach of it  was  a burden. ",
      "19": "Behold, at that time I will undo all that afflict thee: and I will save her that halteth, and gather her that was driven out; and I will get them praise and fame in every land where they have been put to shame.  ",
      "20": "At that time will I bring you  again , even in the time that I gather you: for I will make you a name and a praise among all people of the earth, when I turn back your captivity before your eyes, saith the LORD. "
    }
  },
  "haggai": {
    "1": {
      "1": "In the second year of Darius the king, in the sixth month, in the first day of the month, came the word of the LORD by Haggai the prophet unto Zerubbabel the son of Shealtiel, governor of Judah, and to Joshua the son of Josedech, the high priest, saying,  ",
      "2": "Thus speaketh the LORD of hosts, saying, This people say, The time is not come, the time that the LORD'S house should be built.",
      "3": "Then came the word of the LORD by Haggai the prophet, saying,",
      "4": " Is it  time for you, O ye, to dwell in your cieled houses, and this house  lie  waste?",
      "5": "Now therefore thus saith the LORD of hosts; Consider your ways. ",
      "6": "Ye have sown much, and bring in little; ye eat, but ye have not enough; ye drink, but ye are not filled with drink; ye clothe you, but there is none warm; and he that earneth wages earneth wages  to put it  into a bag with holes. ",
      "7": "Thus saith the LORD of hosts; Consider your ways. ",
      "8": "Go up to the mountain, and bring wood, and build the house; and I will take pleasure in it, and I will be glorified, saith the LORD.",
      "9": "Ye looked for much, and, lo,  it came  to little; and when ye brought  it  home, I did blow upon it. Why? saith the LORD of hosts. Because of mine house that  is  waste, and ye run every man unto his own house. ",
      "10": "Therefore the heaven over you is stayed from dew, and the earth is stayed  from  her fruit.",
      "11": "And I called for a drought upon the land, and upon the mountains, and upon the corn, and upon the new wine, and upon the oil, and upon  that  which the ground bringeth forth, and upon men, and upon cattle, and upon all the labour of the hands. ",
      "12": "Then Zerubbabel the son of Shealtiel, and Joshua the son of Josedech, the high priest, with all the remnant of the people, obeyed the voice of the LORD their God, and the words of Haggai the prophet, as the LORD their God had sent him, and the people did fear before the LORD.",
      "13": "Then spake Haggai the LORD'S messenger in the LORD'S message unto the people, saying, I  am  with you, saith the LORD.",
      "14": "And the LORD stirred up the spirit of Zerubbabel the son of Shealtiel, governor of Judah, and the spirit of Joshua the son of Josedech, the high priest, and the spirit of all the remnant of the people; and they came and did work in the house of the LORD of hosts, their God,",
      "15": "In the four and twentieth day of the sixth month, in the second year of Darius the king. "
    },
    "2": {
      "1": "In the seventh  month , in the one and twentieth  day  of the month, came the word of the LORD by the prophet Haggai, saying, ",
      "2": "Speak now to Zerubbabel the son of Shealtiel, governor of Judah, and to Joshua the son of Josedech, the high priest, and to the residue of the people, saying,",
      "3": "Who  is  left among you that saw this house in her first glory? and how do ye see it now?  is it  not in your eyes in comparison of it as nothing?",
      "4": "Yet now be strong, O Zerubbabel, saith the LORD; and be strong, O Joshua, son of Josedech, the high priest; and be strong, all ye people of the land, saith the LORD, and work: for I  am  with you, saith the LORD of hosts:",
      "5": " According to  the word that I covenanted with you when ye came out of Egypt, so my spirit remaineth among you: fear ye not.",
      "6": "For thus saith the LORD of hosts; Yet once, it  is  a little while, and I will shake the heavens, and the earth, and the sea, and the dry  land ;",
      "7": "And I will shake all nations, and the desire of all nations shall come: and I will fill this house with glory, saith the LORD of hosts.",
      "8": "The silver  is  mine, and the gold  is  mine, saith the LORD of hosts.",
      "9": "The glory of this latter house shall be greater than of the former, saith the LORD of hosts: and in this place will I give peace, saith the LORD of hosts. ",
      "10": "In the four and twentieth  day  of the ninth  month , in the second year of Darius, came the word of the LORD by Haggai the prophet, saying,",
      "11": "Thus saith the LORD of hosts; Ask now the priests  concerning  the law, saying,",
      "12": "If one bear holy flesh in the skirt of his garment, and with his skirt do touch bread, or pottage, or wine, or oil, or any meat, shall it be holy? And the priests answered and said, No.",
      "13": "Then said Haggai, If  one that is  unclean by a dead body touch any of these, shall it be unclean? And the priests answered and said, It shall be unclean.",
      "14": "Then answered Haggai, and said, So  is  this people, and so  is  this nation before me, saith the LORD; and so  is  every work of their hands; and that which they offer there  is  unclean.",
      "15": "And now, I pray you, consider from this day and upward, from before a stone was laid upon a stone in the temple of the LORD:",
      "16": "Since those  days  were, when  one  came to an heap of twenty  measures , there were  but  ten: when  one  came to the pressfat for to draw out fifty  vessels  out of the press, there were  but  twenty.",
      "17": "I smote you with blasting and with mildew and with hail in all the labours of your hands; yet ye  turned  not to me, saith the LORD.",
      "18": "Consider now from this day and upward, from the four and twentieth day of the ninth  month, even  from the day that the foundation of the LORD'S temple was laid, consider  it .",
      "19": "Is the seed yet in the barn? yea, as yet the vine, and the fig tree, and the pomegranate, and the olive tree, hath not brought forth: from this day will I bless  you . ",
      "20": "And again the word of the LORD came unto Haggai in the four and twentieth  day  of the month, saying,",
      "21": "Speak to Zerubbabel, governor of Judah, saying, I will shake the heavens and the earth;",
      "22": "And I will overthrow the throne of kingdoms, and I will destroy the strength of the kingdoms of the heathen; and I will overthrow the chariots, and those that ride in them; and the horses and their riders shall come down, every one by the sword of his brother.",
      "23": "In that day, saith the LORD of hosts, will I take thee, O Zerubbabel, my servant, the son of Shealtiel, saith the LORD, and will make thee as a signet: for I have chosen thee, saith the LORD of hosts. "
    }
  },
  "zechariah": {
    "1": {
      "1": "In the eighth month, in the second year of Darius, came the word of the LORD unto Zechariah, the son of Berechiah, the son of Iddo the prophet, saying,",
      "2": "The LORD hath been sore displeased with your fathers. ",
      "3": "Therefore say thou unto them, Thus saith the LORD of hosts; Turn ye unto me, saith the LORD of hosts, and I will turn unto you, saith the LORD of hosts.",
      "4": "Be ye not as your fathers, unto whom the former prophets have cried, saying, Thus saith the LORD of hosts; Turn ye now from your evil ways, and  from  your evil doings: but they did not hear, nor hearken unto me, saith the LORD.",
      "5": "Your fathers, where  are  they? and the prophets, do they live for ever?",
      "6": "But my words and my statutes, which I commanded my servants the prophets, did they not take hold of your fathers? and they returned and said, Like as the LORD of hosts thought to do unto us, according to our ways, and according to our doings, so hath he dealt with us.  ",
      "7": "Upon the four and twentieth day of the eleventh month, which  is  the month Sebat, in the second year of Darius, came the word of the LORD unto Zechariah, the son of Berechiah, the son of Iddo the prophet, saying,",
      "8": "I saw by night, and behold a man riding upon a red horse, and he stood among the myrtle trees that  were  in the bottom; and behind him  were there  red horses, speckled, and white. ",
      "9": "Then said I, O my lord, what  are  these? And the angel that talked with me said unto me, I will shew thee what these  be .",
      "10": "And the man that stood among the myrtle trees answered and said, These  are they  whom the LORD hath sent to walk to and fro through the earth.",
      "11": "And they answered the angel of the LORD that stood among the myrtle trees, and said, We have walked to and fro through the earth, and, behold, all the earth sitteth still, and is at rest.",
      "12": "Then the angel of the LORD answered and said, O LORD of hosts, how long wilt thou not have mercy on Jerusalem and on the cities of Judah, against which thou hast had indignation these threescore and ten years?",
      "13": "And the LORD answered the angel that talked with me  with  good words  and  comfortable words.",
      "14": "So the angel that communed with me said unto me, Cry thou, saying, Thus saith the LORD of hosts; I am jealous for Jerusalem and for Zion with a great jealousy.",
      "15": "And I am very sore displeased with the heathen  that are  at ease: for I was but a little displeased, and they helped forward the affliction.",
      "16": "Therefore thus saith the LORD; I am returned to Jerusalem with mercies: my house shall be built in it, saith the LORD of hosts, and a line shall be stretched forth upon Jerusalem.",
      "17": "Cry yet, saying, Thus saith the LORD of hosts; My cities through prosperity shall yet be spread abroad; and the LORD shall yet comfort Zion, and shall yet choose Jerusalem.  ",
      "18": "Then lifted I up mine eyes, and saw, and behold four horns.",
      "19": "And I said unto the angel that talked with me, What  be  these? And he answered me, These  are  the horns which have scattered Judah, Israel, and Jerusalem.",
      "20": "And the LORD shewed me four carpenters.",
      "21": "Then said I, What come these to do? And he spake, saying, These  are  the horns which have scattered Judah, so that no man did lift up his head: but these are come to fray them, to cast out the horns of the Gentiles, which lifted up  their  horn over the land of Judah to scatter it. "
    },
    "2": {
      "1": "I lifted up mine eyes again, and looked, and behold a man with a measuring line in his hand.",
      "2": "Then said I, Whither goest thou? And he said unto me, To measure Jerusalem, to see what  is  the breadth thereof, and what  is  the length thereof.",
      "3": "And, behold, the angel that talked with me went forth, and another angel went out to meet him,",
      "4": "And said unto him, Run, speak to this young man, saying, Jerusalem shall be inhabited  as  towns without walls for the multitude of men and cattle therein:",
      "5": "For I, saith the LORD, will be unto her a wall of fire round about, and will be the glory in the midst of her. ",
      "6": "Ho, ho,  come forth , and flee from the land of the north, saith the LORD: for I have spread you abroad as the four winds of the heaven, saith the LORD.",
      "7": "Deliver thyself, O Zion, that dwellest  with  the daughter of Babylon.",
      "8": "For thus saith the LORD of hosts; After the glory hath he sent me unto the nations which spoiled you: for he that toucheth you toucheth the apple of his eye.",
      "9": "For, behold, I will shake mine hand upon them, and they shall be a spoil to their servants: and ye shall know that the LORD of hosts hath sent me. ",
      "10": "Sing and rejoice, O daughter of Zion: for, lo, I come, and I will dwell in the midst of thee, saith the LORD.",
      "11": "And many nations shall be joined to the LORD in that day, and shall be my people: and I will dwell in the midst of thee, and thou shalt know that the LORD of hosts hath sent me unto thee.",
      "12": "And the LORD shall inherit Judah his portion in the holy land, and shall choose Jerusalem again.",
      "13": "Be silent, O all flesh, before the LORD: for he is raised up out of his holy habitation.  "
    },
    "3": {
      "1": "And he shewed me Joshua the high priest standing before the angel of the LORD, and Satan standing at his right hand to resist him.  ",
      "2": "And the LORD said unto Satan, The LORD rebuke thee, O Satan; even the LORD that hath chosen Jerusalem rebuke thee:  is  not this a brand plucked out of the fire?",
      "3": "Now Joshua was clothed with filthy garments, and stood before the angel.",
      "4": "And he answered and spake unto those that stood before him, saying, Take away the filthy garments from him. And unto him he said, Behold, I have caused thine iniquity to pass from thee, and I will clothe thee with change of raiment.",
      "5": "And I said, Let them set a fair mitre upon his head. So they set a fair mitre upon his head, and clothed him with garments. And the angel of the LORD stood by.",
      "6": "And the angel of the LORD protested unto Joshua, saying,",
      "7": "Thus saith the LORD of hosts; If thou wilt walk in my ways, and if thou wilt keep my charge, then thou shalt also judge my house, and shalt also keep my courts, and I will give thee places to walk among these that stand by.   ",
      "8": "Hear now, O Joshua the high priest, thou, and thy fellows that sit before thee: for they  are  men wondered at: for, behold, I will bring forth my servant the BRANCH. ",
      "9": "For behold the stone that I have laid before Joshua; upon one stone  shall be  seven eyes: behold, I will engrave the graving thereof, saith the LORD of hosts, and I will remove the iniquity of that land in one day.",
      "10": "In that day, saith the LORD of hosts, shall ye call every man his neighbour under the vine and under the fig tree. "
    },
    "4": {
      "1": "And the angel that talked with me came again, and waked me, as a man that is wakened out of his sleep,",
      "2": "And said unto me, What seest thou? And I said, I have looked, and behold a candlestick all  of  gold, with a bowl upon the top of it, and his seven lamps thereon, and seven pipes to the seven lamps, which  are  upon the top thereof:  ",
      "3": "And two olive trees by it, one upon the right  side  of the bowl, and the other upon the left  side  thereof.",
      "4": "So I answered and spake to the angel that talked with me, saying, What  are  these, my lord?",
      "5": "Then the angel that talked with me answered and said unto me, Knowest thou not what these be? And I said, No, my lord.",
      "6": "Then he answered and spake unto me, saying, This  is  the word of the LORD unto Zerubbabel, saying, Not by might, nor by power, but by my spirit, saith the LORD of hosts. ",
      "7": "Who  art  thou, O great mountain? before Zerubbabel  thou shalt become  a plain: and he shall bring forth the headstone  thereof with  shoutings,  crying , Grace, grace unto it.",
      "8": "Moreover the word of the LORD came unto me, saying,",
      "9": "The hands of Zerubbabel have laid the foundation of this house; his hands shall also finish it; and thou shalt know that the LORD of hosts hath sent me unto you.",
      "10": "For who hath despised the day of small things? for they shall rejoice, and shall see the plummet in the hand of Zerubbabel  with  those seven; they  are  the eyes of the LORD, which run to and fro through the whole earth.   ",
      "11": "Then answered I, and said unto him, What  are  these two olive trees upon the right  side  of the candlestick and upon the left  side  thereof?",
      "12": "And I answered again, and said unto him, What  be these  two olive branches which through the two golden pipes empty the golden  oil  out of themselves?   ",
      "13": "And he answered me and said, Knowest thou not what these  be ? And I said, No, my lord.",
      "14": "Then said he, These  are  the two anointed ones, that stand by the Lord of the whole earth.  "
    },
    "5": {
      "1": "Then I turned, and lifted up mine eyes, and looked, and behold a flying roll.",
      "2": "And he said unto me, What seest thou? And I answered, I see a flying roll; the length thereof  is  twenty cubits, and the breadth thereof ten cubits.",
      "3": "Then said he unto me, This  is  the curse that goeth forth over the face of the whole earth: for every one that stealeth shall be cut off  as  on this side according to it; and every one that sweareth shall be cut off  as  on that side according to it. ",
      "4": "I will bring it forth, saith the LORD of hosts, and it shall enter into the house of the thief, and into the house of him that sweareth falsely by my name: and it shall remain in the midst of his house, and shall consume it with the timber thereof and the stones thereof. ",
      "5": "Then the angel that talked with me went forth, and said unto me, Lift up now thine eyes, and see what  is  this that goeth forth.",
      "6": "And I said, What  is  it? And he said, This  is  an ephah that goeth forth. He said moreover, This  is  their resemblance through all the earth.",
      "7": "And, behold, there was lifted up a talent of lead: and this  is  a woman that sitteth in the midst of the ephah. ",
      "8": "And he said, This  is  wickedness. And he cast it into the midst of the ephah; and he cast the weight of lead upon the mouth thereof.",
      "9": "Then lifted I up mine eyes, and looked, and, behold, there came out two women, and the wind  was  in their wings; for they had wings like the wings of a stork: and they lifted up the ephah between the earth and the heaven.",
      "10": "Then said I to the angel that talked with me, Whither do these bear the ephah?",
      "11": "And he said unto me, To build it an house in the land of Shinar: and it shall be established, and set there upon her own base. "
    },
    "6": {
      "1": "And I turned, and lifted up mine eyes, and looked, and, behold, there came four chariots out from between two mountains; and the mountains  were  mountains of brass.",
      "2": "In the first chariot  were  red horses; and in the second chariot black horses;",
      "3": "And in the third chariot white horses; and in the fourth chariot grisled and bay horses. ",
      "4": "Then I answered and said unto the angel that talked with me, What  are  these, my lord?",
      "5": "And the angel answered and said unto me, These  are  the four spirits of the heavens, which go forth from standing before the Lord of all the earth. ",
      "6": "The black horses which  are  therein go forth into the north country; and the white go forth after them; and the grisled go forth toward the south country.",
      "7": "And the bay went forth, and sought to go that they might walk to and fro through the earth: and he said, Get you hence, walk to and fro through the earth. So they walked to and fro through the earth.",
      "8": "Then cried he upon me, and spake unto me, saying, Behold, these that go toward the north country have quieted my spirit in the north country. ",
      "9": "And the word of the LORD came unto me, saying,",
      "10": "Take of  them of  the captivity,  even  of Heldai, of Tobijah, and of Jedaiah, which are come from Babylon, and come thou the same day, and go into the house of Josiah the son of Zephaniah;",
      "11": "Then take silver and gold, and make crowns, and set  them  upon the head of Joshua the son of Josedech, the high priest;",
      "12": "And speak unto him, saying, Thus speaketh the LORD of hosts, saying, Behold the man whose name  is  The BRANCH; and he shall grow up out of his place, and he shall build the temple of the LORD: ",
      "13": "Even he shall build the temple of the LORD; and he shall bear the glory, and shall sit and rule upon his throne; and he shall be a priest upon his throne: and the counsel of peace shall be between them both.",
      "14": "And the crowns shall be to Helem, and to Tobijah, and to Jedaiah, and to Hen the son of Zephaniah, for a memorial in the temple of the LORD.",
      "15": "And they  that are  far off shall come and build in the temple of the LORD, and ye shall know that the LORD of hosts hath sent me unto you. And  this  shall come to pass, if ye will diligently obey the voice of the LORD your God. "
    },
    "7": {
      "1": "And it came to pass in the fourth year of king Darius,  that  the word of the LORD came unto Zechariah in the fourth  day  of the ninth month,  even  in Chisleu;",
      "2": "When they had sent unto the house of God Sherezer and Regemmelech, and their men, to pray before the LORD, ",
      "3": " And  to speak unto the priests which  were  in the house of the LORD of hosts, and to the prophets, saying, Should I weep in the fifth month, separating myself, as I have done these so many years?",
      "4": "Then came the word of the LORD of hosts unto me, saying,",
      "5": "Speak unto all the people of the land, and to the priests, saying, When ye fasted and mourned in the fifth and seventh  month , even those seventy years, did ye at all fast unto me,  even  to me?",
      "6": "And when ye did eat, and when ye did drink, did not ye eat  for yourselves , and drink  for yourselves ? ",
      "7": " Should ye  not  hear  the words which the LORD hath cried by the former prophets, when Jerusalem was inhabited and in prosperity, and the cities thereof round about her, when  men  inhabited the south and the plain?   ",
      "8": "And the word of the LORD came unto Zechariah, saying,",
      "9": "Thus speaketh the LORD of hosts, saying, Execute true judgment, and shew mercy and compassions every man to his brother: ",
      "10": "And oppress not the widow, nor the fatherless, the stranger, nor the poor; and let none of you imagine evil against his brother in your heart.",
      "11": "But they refused to hearken, and pulled away the shoulder, and stopped their ears, that they should not hear.  ",
      "12": "Yea, they made their hearts  as  an adamant stone, lest they should hear the law, and the words which the LORD of hosts hath sent in his spirit by the former prophets: therefore came a great wrath from the LORD of hosts. ",
      "13": "Therefore it is come to pass,  that  as he cried, and they would not hear; so they cried, and I would not hear, saith the LORD of hosts:",
      "14": "But I scattered them with a whirlwind among all the nations whom they knew not. Thus the land was desolate after them, that no man passed through nor returned: for they laid the pleasant land desolate.  "
    },
    "8": {
      "1": "Again the word of the LORD of hosts came  to me , saying,",
      "2": "Thus saith the LORD of hosts; I was jealous for Zion with great jealousy, and I was jealous for her with great fury.",
      "3": "Thus saith the LORD; I am returned unto Zion, and will dwell in the midst of Jerusalem: and Jerusalem shall be called a city of truth; and the mountain of the LORD of hosts the holy mountain.",
      "4": "Thus saith the LORD of hosts; There shall yet old men and old women dwell in the streets of Jerusalem, and every man with his staff in his hand for very age. ",
      "5": "And the streets of the city shall be full of boys and girls playing in the streets thereof.",
      "6": "Thus saith the LORD of hosts; If it be marvellous in the eyes of the remnant of this people in these days, should it also be marvellous in mine eyes? saith the LORD of hosts. ",
      "7": "Thus saith the LORD of hosts; Behold, I will save my people from the east country, and from the west country; ",
      "8": "And I will bring them, and they shall dwell in the midst of Jerusalem: and they shall be my people, and I will be their God, in truth and in righteousness. ",
      "9": "Thus saith the LORD of hosts; Let your hands be strong, ye that hear in these days these words by the mouth of the prophets, which  were  in the day  that  the foundation of the house of the LORD of hosts was laid, that the temple might be built.",
      "10": "For before these days there was no hire for man, nor any hire for beast; neither  was there any  peace to him that went out or came in because of the affliction: for I set all men every one against his neighbour. ",
      "11": "But now I  will  not  be  unto the residue of this people as in the former days, saith the LORD of hosts.",
      "12": "For the seed  shall be  prosperous; the vine shall give her fruit, and the ground shall give her increase, and the heavens shall give their dew; and I will cause the remnant of this people to possess all these  things . ",
      "13": "And it shall come to pass,  that  as ye were a curse among the heathen, O house of Judah, and house of Israel; so will I save you, and ye shall be a blessing: fear not,  but  let your hands be strong.",
      "14": "For thus saith the LORD of hosts; As I thought to punish you, when your fathers provoked me to wrath, saith the LORD of hosts, and I repented not:",
      "15": "So again have I thought in these days to do well unto Jerusalem and to the house of Judah: fear ye not.",
      "16": "These  are  the things that ye shall do; Speak ye every man the truth to his neighbour; execute the judgment of truth and peace in your gates: ",
      "17": "And let none of you imagine evil in your hearts against his neighbour; and love no false oath: for all these  are things  that I hate, saith the LORD. ",
      "18": "And the word of the LORD of hosts came unto me, saying,",
      "19": "Thus saith the LORD of hosts; The fast of the fourth  month , and the fast of the fifth, and the fast of the seventh, and the fast of the tenth, shall be to the house of Judah joy and gladness, and cheerful feasts; therefore love the truth and peace. ",
      "20": "Thus saith the LORD of hosts;  It shall  yet  come to pass , that there shall come people, and the inhabitants of many cities:",
      "21": "And the inhabitants of one  city  shall go to another, saying, Let us go speedily to pray before the LORD, and to seek the LORD of hosts: I will go also.  ",
      "22": "Yea, many people and strong nations shall come to seek the LORD of hosts in Jerusalem, and to pray before the LORD. ",
      "23": "Thus saith the LORD of hosts; In those days  it shall come to pass , that ten men shall take hold out of all languages of the nations, even shall take hold of the skirt of him that is a Jew, saying, We will go with you: for we have heard  that  God  is  with you. "
    },
    "9": {
      "1": "The burden of the word of the LORD in the land of Hadrach, and Damascus  shall be  the rest thereof: when the eyes of man, as of all the tribes of Israel,  shall be  toward the LORD.",
      "2": "And Hamath also shall border thereby; Tyrus, and Zidon, though it be very wise.",
      "3": "And Tyrus did build herself a strong hold, and heaped up silver as the dust, and fine gold as the mire of the streets.",
      "4": "Behold, the Lord will cast her out, and he will smite her power in the sea; and she shall be devoured with fire.",
      "5": "Ashkelon shall see  it , and fear; Gaza also  shall see it , and be very sorrowful, and Ekron; for her expectation shall be ashamed; and the king shall perish from Gaza, and Ashkelon shall not be inhabited.",
      "6": "And a bastard shall dwell in Ashdod, and I will cut off the pride of the Philistines.",
      "7": "And I will take away his blood out of his mouth, and his abominations from between his teeth: but he that remaineth, even he,  shall be  for our God, and he shall be as a governor in Judah, and Ekron as a Jebusite. ",
      "8": "And I will encamp about mine house because of the army, because of him that passeth by, and because of him that returneth: and no oppressor shall pass through them any more: for now have I seen with mine eyes. ",
      "9": "Rejoice greatly, O daughter of Zion; shout, O daughter of Jerusalem: behold, thy King cometh unto thee: he  is  just, and having salvation; lowly, and riding upon an ass, and upon a colt the foal of an ass. ",
      "10": "And I will cut off the chariot from Ephraim, and the horse from Jerusalem, and the battle bow shall be cut off: and he shall speak peace unto the heathen: and his dominion  shall be  from sea  even  to sea, and from the river  even  to the ends of the earth.",
      "11": "As for thee also, by the blood of thy covenant I have sent forth thy prisoners out of the pit wherein  is  no water.  ",
      "12": "Turn you to the strong hold, ye prisoners of hope: even to day do I declare  that  I will render double unto thee;",
      "13": "When I have bent Judah for me, filled the bow with Ephraim, and raised up thy sons, O Zion, against thy sons, O Greece, and made thee as the sword of a mighty man.",
      "14": "And the LORD shall be seen over them, and his arrow shall go forth as the lightning: and the Lord GOD shall blow the trumpet, and shall go with whirlwinds of the south.",
      "15": "The LORD of hosts shall defend them; and they shall devour, and subdue with sling stones; and they shall drink,  and  make a noise as through wine; and they shall be filled like bowls,  and  as the corners of the altar.  ",
      "16": "And the LORD their God shall save them in that day as the flock of his people: for they  shall be as  the stones of a crown, lifted up as an ensign upon his land.",
      "17": "For how great  is  his goodness, and how great  is  his beauty! corn shall make the young men cheerful, and new wine the maids.  "
    },
    "10": {
      "1": "Ask ye of the LORD rain in the time of the latter rain;  so  the LORD shall make bright clouds, and give them showers of rain, to every one grass in the field. ",
      "2": "For the idols have spoken vanity, and the diviners have seen a lie, and have told false dreams; they comfort in vain: therefore they went their way as a flock, they were troubled, because  there was  no shepherd.  ",
      "3": "Mine anger was kindled against the shepherds, and I punished the goats: for the LORD of hosts hath visited his flock the house of Judah, and hath made them as his goodly horse in the battle. ",
      "4": "Out of him came forth the corner, out of him the nail, out of him the battle bow, out of him every oppressor together. ",
      "5": "And they shall be as mighty  men , which tread down  their enemies  in the mire of the streets in the battle: and they shall fight, because the LORD  is  with them, and the riders on horses shall be confounded. ",
      "6": "And I will strengthen the house of Judah, and I will save the house of Joseph, and I will bring them again to place them; for I have mercy upon them: and they shall be as though I had not cast them off: for I  am  the LORD their God, and will hear them.",
      "7": "And  they of  Ephraim shall be like a mighty  man , and their heart shall rejoice as through wine: yea, their children shall see  it , and be glad; their heart shall rejoice in the LORD.",
      "8": "I will hiss for them, and gather them; for I have redeemed them: and they shall increase as they have increased.",
      "9": "And I will sow them among the people: and they shall remember me in far countries; and they shall live with their children, and turn again.",
      "10": "I will bring them again also out of the land of Egypt, and gather them out of Assyria; and I will bring them into the land of Gilead and Lebanon; and  place  shall not be found for them.",
      "11": "And he shall pass through the sea with affliction, and shall smite the waves in the sea, and all the deeps of the river shall dry up: and the pride of Assyria shall be brought down, and the sceptre of Egypt shall depart away.",
      "12": "And I will strengthen them in the LORD; and they shall walk up and down in his name, saith the LORD. "
    },
    "11": {
      "1": "Open thy doors, O Lebanon, that the fire may devour thy cedars.",
      "2": "Howl, fir tree; for the cedar is fallen; because the mighty are spoiled: howl, O ye oaks of Bashan; for the forest of the vintage is come down.  ",
      "3": " There is  a voice of the howling of the shepherds; for their glory is spoiled: a voice of the roaring of young lions; for the pride of Jordan is spoiled. ",
      "4": "Thus saith the LORD my God; Feed the flock of the slaughter;",
      "5": "Whose possessors slay them, and hold themselves not guilty: and they that sell them say, Blessed  be  the LORD; for I am rich: and their own shepherds pity them not.",
      "6": "For I will no more pity the inhabitants of the land, saith the LORD: but, lo, I will deliver the men every one into his neighbour's hand, and into the hand of his king: and they shall smite the land, and out of their hand I will not deliver  them . ",
      "7": "And I will feed the flock of slaughter,  even  you, O poor of the flock. And I took unto me two staves; the one I called Beauty, and the other I called Bands; and I fed the flock.  ",
      "8": "Three shepherds also I cut off in one month; and my soul lothed them, and their soul also abhorred me. ",
      "9": "Then said I, I will not feed you: that that dieth, let it die; and that that is to be cut off, let it be cut off; and let the rest eat every one the flesh of another. ",
      "10": "And I took my staff,  even  Beauty, and cut it asunder, that I might break my covenant which I had made with all the people.",
      "11": "And it was broken in that day: and so the poor of the flock that waited upon me knew that it  was  the word of the LORD. ",
      "12": "And I said unto them, If ye think good, give  me  my price; and if not, forbear. So they weighed for my price thirty  pieces  of silver. ",
      "13": "And the LORD said unto me, Cast it unto the potter: a goodly price that I was prised at of them. And I took the thirty  pieces  of silver, and cast them to the potter in the house of the LORD.",
      "14": "Then I cut asunder mine other staff,  even  Bands, that I might break the brotherhood between Judah and Israel.  ",
      "15": "And the LORD said unto me, Take unto thee yet the instruments of a foolish shepherd.",
      "16": "For, lo, I will raise up a shepherd in the land,  which  shall not visit those that be cut off, neither shall seek the young one, nor heal that that is broken, nor feed that that standeth still: but he shall eat the flesh of the fat, and tear their claws in pieces.  ",
      "17": "Woe to the idol shepherd that leaveth the flock! the sword  shall be  upon his arm, and upon his right eye: his arm shall be clean dried up, and his right eye shall be utterly darkened. "
    },
    "12": {
      "1": "The burden of the word of the LORD for Israel, saith the LORD, which stretcheth forth the heavens, and layeth the foundation of the earth, and formeth the spirit of man within him.",
      "2": "Behold, I will make Jerusalem a cup of trembling unto all the people round about, when they shall be in the siege both against Judah  and  against Jerusalem.  ",
      "3": "And in that day will I make Jerusalem a burdensome stone for all people: all that burden themselves with it shall be cut in pieces, though all the people of the earth be gathered together against it.",
      "4": "In that day, saith the LORD, I will smite every horse with astonishment, and his rider with madness: and I will open mine eyes upon the house of Judah, and will smite every horse of the people with blindness.",
      "5": "And the governors of Judah shall say in their heart, The inhabitants of Jerusalem  shall be  my strength in the LORD of hosts their God. ",
      "6": "In that day will I make the governors of Judah like an hearth of fire among the wood, and like a torch of fire in a sheaf; and they shall devour all the people round about, on the right hand and on the left: and Jerusalem shall be inhabited again in her own place,  even  in Jerusalem.",
      "7": "The LORD also shall save the tents of Judah first, that the glory of the house of David and the glory of the inhabitants of Jerusalem do not magnify  themselves  against Judah.",
      "8": "In that day shall the LORD defend the inhabitants of Jerusalem; and he that is feeble among them at that day shall be as David; and the house of David  shall be  as God, as the angel of the LORD before them.  ",
      "9": "And it shall come to pass in that day,  that  I will seek to destroy all the nations that come against Jerusalem.",
      "10": "And I will pour upon the house of David, and upon the inhabitants of Jerusalem, the spirit of grace and of supplications: and they shall look upon me whom they have pierced, and they shall mourn for him, as one mourneth for  his  only  son , and shall be in bitterness for him, as one that is in bitterness for  his  firstborn.",
      "11": "In that day shall there be a great mourning in Jerusalem, as the mourning of Hadadrimmon in the valley of Megiddon.",
      "12": "And the land shall mourn, every family apart; the family of the house of David apart, and their wives apart; the family of the house of Nathan apart, and their wives apart; ",
      "13": "The family of the house of Levi apart, and their wives apart; the family of Shimei apart, and their wives apart; ",
      "14": "All the families that remain, every family apart, and their wives apart. "
    },
    "13": {
      "1": "In that day there shall be a fountain opened to the house of David and to the inhabitants of Jerusalem for sin and for uncleanness. ",
      "2": "And it shall come to pass in that day, saith the LORD of hosts,  that  I will cut off the names of the idols out of the land, and they shall no more be remembered: and also I will cause the prophets and the unclean spirit to pass out of the land.",
      "3": "And it shall come to pass,  that  when any shall yet prophesy, then his father and his mother that begat him shall say unto him, Thou shalt not live; for thou speakest lies in the name of the LORD: and his father and his mother that begat him shall thrust him through when he prophesieth.",
      "4": "And it shall come to pass in that day,  that  the prophets shall be ashamed every one of his vision, when he hath prophesied; neither shall they wear a rough garment to deceive:  ",
      "5": "But he shall say, I  am  no prophet, I  am  an husbandman; for man taught me to keep cattle from my youth.",
      "6": "And  one  shall say unto him, What  are  these wounds in thine hands? Then he shall answer,  Those  with which I was wounded  in  the house of my friends. ",
      "7": "Awake, O sword, against my shepherd, and against the man  that is  my fellow, saith the LORD of hosts: smite the shepherd, and the sheep shall be scattered: and I will turn mine hand upon the little ones.",
      "8": "And it shall come to pass,  that  in all the land, saith the LORD, two parts therein shall be cut off  and  die; but the third shall be left therein.",
      "9": "And I will bring the third part through the fire, and will refine them as silver is refined, and will try them as gold is tried: they shall call on my name, and I will hear them: I will say, It  is  my people: and they shall say, The LORD  is  my God. "
    },
    "14": {
      "1": "Behold, the day of the LORD cometh, and thy spoil shall be divided in the midst of thee.",
      "2": "For I will gather all nations against Jerusalem to battle; and the city shall be taken, and the houses rifled, and the women ravished; and half of the city shall go forth into captivity, and the residue of the people shall not be cut off from the city.",
      "3": "Then shall the LORD go forth, and fight against those nations, as when he fought in the day of battle.",
      "4": "And his feet shall stand in that day upon the mount of Olives, which  is  before Jerusalem on the east, and the mount of Olives shall cleave in the midst thereof toward the east and toward the west,  and there shall be  a very great valley; and half of the mountain shall remove toward the north, and half of it toward the south.",
      "5": "And ye shall flee  to  the valley of the mountains; for the valley of the mountains shall reach unto Azal: yea, ye shall flee, like as ye fled from before the earthquake in the days of Uzziah king of Judah: and the LORD my God shall come,  and  all the saints with thee.  ",
      "6": "And it shall come to pass in that day,  that  the light shall not be clear,  nor  dark:   ",
      "7": "But it shall be one day which shall be known to the LORD, not day, nor night: but it shall come to pass,  that  at evening time it shall be light.  ",
      "8": "And it shall be in that day,  that  living waters shall go out from Jerusalem; half of them toward the former sea, and half of them toward the hinder sea: in summer and in winter shall it be. ",
      "9": "And the LORD shall be king over all the earth: in that day shall there be one LORD, and his name one.",
      "10": "All the land shall be turned as a plain from Geba to Rimmon south of Jerusalem: and it shall be lifted up, and inhabited in her place, from Benjamin's gate unto the place of the first gate, unto the corner gate, and  from  the tower of Hananeel unto the king's winepresses.  ",
      "11": "And  men  shall dwell in it, and there shall be no more utter destruction; but Jerusalem shall be safely inhabited. ",
      "12": "And this shall be the plague wherewith the LORD will smite all the people that have fought against Jerusalem; Their flesh shall consume away while they stand upon their feet, and their eyes shall consume away in their holes, and their tongue shall consume away in their mouth.",
      "13": "And it shall come to pass in that day,  that  a great tumult from the LORD shall be among them; and they shall lay hold every one on the hand of his neighbour, and his hand shall rise up against the hand of his neighbour.",
      "14": "And Judah also shall fight at Jerusalem; and the wealth of all the heathen round about shall be gathered together, gold, and silver, and apparel, in great abundance.  ",
      "15": "And so shall be the plague of the horse, of the mule, of the camel, and of the ass, and of all the beasts that shall be in these tents, as this plague. ",
      "16": "And it shall come to pass,  that  every one that is left of all the nations which came against Jerusalem shall even go up from year to year to worship the King, the LORD of hosts, and to keep the feast of tabernacles.",
      "17": "And it shall be,  that  whoso will not come up of  all  the families of the earth unto Jerusalem to worship the King, the LORD of hosts, even upon them shall be no rain.",
      "18": "And if the family of Egypt go not up, and come not, that  have  no  rain ; there shall be the plague, wherewith the LORD will smite the heathen that come not up to keep the feast of tabernacles. ",
      "19": "This shall be the punishment of Egypt, and the punishment of all nations that come not up to keep the feast of tabernacles. ",
      "20": "In that day shall there be upon the bells of the horses, HOLINESS UNTO THE LORD; and the pots in the LORD'S house shall be like the bowls before the altar. ",
      "21": "Yea, every pot in Jerusalem and in Judah shall be holiness unto the LORD of hosts: and all they that sacrifice shall come and take of them, and seethe therein: and in that day there shall be no more the Canaanite in the house of the LORD of hosts. "
    }
  }
};

