
	
export const bib_verses = {
  "2_samuel": {
    "18": {
      "1": "And David numbered the people that  were  with him, and set captains of thousands and captains of hundreds over them.",
      "2": "And David sent forth a third part of the people under the hand of Joab, and a third part under the hand of Abishai the son of Zeruiah, Joab's brother, and a third part under the hand of Ittai the Gittite. And the king said unto the people, I will surely go forth with you myself also.",
      "3": "But the people answered, Thou shalt not go forth: for if we flee away, they will not care for us; neither if half of us die, will they care for us: but now  thou art  worth ten thousand of us: therefore now  it is  better that thou succour us out of the city.   ",
      "4": "And the king said unto them, What seemeth you best I will do. And the king stood by the gate side, and all the people came out by hundreds and by thousands.",
      "5": "And the king commanded Joab and Abishai and Ittai, saying,  Deal  gently for my sake with the young man,  even  with Absalom. And all the people heard when the king gave all the captains charge concerning Absalom.",
      "6": "So the people went out into the field against Israel: and the battle was in the wood of Ephraim;",
      "7": "Where the people of Israel were slain before the servants of David, and there was there a great slaughter that day of twenty thousand  men .",
      "8": "For the battle was there scattered over the face of all the country: and the wood devoured more people that day than the sword devoured.  ",
      "9": "And Absalom met the servants of David. And Absalom rode upon a mule, and the mule went under the thick boughs of a great oak, and his head caught hold of the oak, and he was taken up between the heaven and the earth; and the mule that  was  under him went away.",
      "10": "And a certain man saw  it , and told Joab, and said, Behold, I saw Absalom hanged in an oak.",
      "11": "And Joab said unto the man that told him, And, behold, thou sawest  him , and why didst thou not smite him there to the ground? and I would have given thee ten  shekels  of silver, and a girdle.",
      "12": "And the man said unto Joab, Though I should receive a thousand  shekels  of silver in mine hand,  yet  would I not put forth mine hand against the king's son: for in our hearing the king charged thee and Abishai and Ittai, saying, Beware that none  touch  the young man Absalom.  ",
      "13": "Otherwise I should have wrought falsehood against mine own life: for there is no matter hid from the king, and thou thyself wouldest have set thyself against  me .",
      "14": "Then said Joab, I may not tarry thus with thee. And he took three darts in his hand, and thrust them through the heart of Absalom, while he  was  yet alive in the midst of the oak.  ",
      "15": "And ten young men that bare Joab's armour compassed about and smote Absalom, and slew him.",
      "16": "And Joab blew the trumpet, and the people returned from pursuing after Israel: for Joab held back the people.",
      "17": "And they took Absalom, and cast him into a great pit in the wood, and laid a very great heap of stones upon him: and all Israel fled every one to his tent.",
      "18": "Now Absalom in his lifetime had taken and reared up for himself a pillar, which  is  in the king's dale: for he said, I have no son to keep my name in remembrance: and he called the pillar after his own name: and it is called unto this day, Absalom's place. ",
      "19": "Then said Ahimaaz the son of Zadok, Let me now run, and bear the king tidings, how that the LORD hath avenged him of his enemies. ",
      "20": "And Joab said unto him, Thou shalt not bear tidings this day, but thou shalt bear tidings another day: but this day thou shalt bear no tidings, because the king's son is dead. ",
      "21": "Then said Joab to Cushi, Go tell the king what thou hast seen. And Cushi bowed himself unto Joab, and ran.",
      "22": "Then said Ahimaaz the son of Zadok yet again to Joab, But howsoever, let me, I pray thee, also run after Cushi. And Joab said, Wherefore wilt thou run, my son, seeing that thou hast no tidings ready?  ",
      "23": "But howsoever,  said he , let me run. And he said unto him, Run. Then Ahimaaz ran by the way of the plain, and overran Cushi.",
      "24": "And David sat between the two gates: and the watchman went up to the roof over the gate unto the wall, and lifted up his eyes, and looked, and behold a man running alone.",
      "25": "And the watchman cried, and told the king. And the king said, If he  be  alone,  there is  tidings in his mouth. And he came apace, and drew near.",
      "26": "And the watchman saw another man running: and the watchman called unto the porter, and said, Behold  another  man running alone. And the king said, He also bringeth tidings.",
      "27": "And the watchman said, Me thinketh the running of the foremost is like the running of Ahimaaz the son of Zadok. And the king said, He  is  a good man, and cometh with good tidings. ",
      "28": "And Ahimaaz called, and said unto the king, All is well. And he fell down to the earth upon his face before the king, and said, Blessed  be  the LORD thy God, which hath delivered up the men that lifted up their hand against my lord the king.  ",
      "29": "And the king said, Is the young man Absalom safe? And Ahimaaz answered, When Joab sent the king's servant, and  me  thy servant, I saw a great tumult, but I knew not what  it was . ",
      "30": "And the king said  unto him , Turn aside,  and  stand here. And he turned aside, and stood still.",
      "31": "And, behold, Cushi came; and Cushi said, Tidings, my lord the king: for the LORD hath avenged thee this day of all them that rose up against thee. ",
      "32": "And the king said unto Cushi, Is the young man Absalom safe? And Cushi answered, The enemies of my lord the king, and all that rise against thee to do  thee  hurt, be as  that  young man  is .",
      "33": "And the king was much moved, and went up to the chamber over the gate, and wept: and as he went, thus he said, O my son Absalom, my son, my son Absalom! would God I had died for thee, O Absalom, my son, my son! "
    },
    "19": {
      "1": "And it was told Joab, Behold, the king weepeth and mourneth for Absalom.",
      "2": "And the victory that day was  turned  into mourning unto all the people: for the people heard say that day how the king was grieved for his son. ",
      "3": "And the people gat them by stealth that day into the city, as people being ashamed steal away when they flee in battle.",
      "4": "But the king covered his face, and the king cried with a loud voice, O my son Absalom, O Absalom, my son, my son!",
      "5": "And Joab came into the house to the king, and said, Thou hast shamed this day the faces of all thy servants, which this day have saved thy life, and the lives of thy sons and of thy daughters, and the lives of thy wives, and the lives of thy concubines;",
      "6": "In that thou lovest thine enemies, and hatest thy friends. For thou hast declared this day, that thou regardest neither princes nor servants: for this day I perceive, that if Absalom had lived, and all we had died this day, then it had pleased thee well.  ",
      "7": "Now therefore arise, go forth, and speak comfortably unto thy servants: for I swear by the LORD, if thou go not forth, there will not tarry one with thee this night: and that will be worse unto thee than all the evil that befell thee from thy youth until now. ",
      "8": "Then the king arose, and sat in the gate. And they told unto all the people, saying, Behold, the king doth sit in the gate. And all the people came before the king: for Israel had fled every man to his tent. ",
      "9": "And all the people were at strife throughout all the tribes of Israel, saying, The king saved us out of the hand of our enemies, and he delivered us out of the hand of the Philistines; and now he is fled out of the land for Absalom.",
      "10": "And Absalom, whom we anointed over us, is dead in battle. Now therefore why speak ye not a word of bringing the king back? ",
      "11": "And king David sent to Zadok and to Abiathar the priests, saying, Speak unto the elders of Judah, saying, Why are ye the last to bring the king back to his house? seeing the speech of all Israel is come to the king,  even  to his house.",
      "12": "Ye  are  my brethren, ye  are  my bones and my flesh: wherefore then are ye the last to bring back the king?",
      "13": "And say ye to Amasa,  Art  thou not of my bone, and of my flesh? God do so to me, and more also, if thou be not captain of the host before me continually in the room of Joab.",
      "14": "And he bowed the heart of all the men of Judah, even as  the heart of  one man; so that they sent  this word  unto the king, Return thou, and all thy servants.",
      "15": "So the king returned, and came to Jordan. And Judah came to Gilgal, to go to meet the king, to conduct the king over Jordan. ",
      "16": "And Shimei the son of Gera, a Benjamite, which  was  of Bahurim, hasted and came down with the men of Judah to meet king David.",
      "17": "And  there were  a thousand men of Benjamin with him, and Ziba the servant of the house of Saul, and his fifteen sons and his twenty servants with him; and they went over Jordan before the king.",
      "18": "And there went over a ferry boat to carry over the king's household, and to do what he thought good. And Shimei the son of Gera fell down before the king, as he was come over Jordan; ",
      "19": "And said unto the king, Let not my lord impute iniquity unto me, neither do thou remember that which thy servant did perversely the day that my lord the king went out of Jerusalem, that the king should take it to his heart.",
      "20": "For thy servant doth know that I have sinned: therefore, behold, I am come the first this day of all the house of Joseph to go down to meet my lord the king.",
      "21": "But Abishai the son of Zeruiah answered and said, Shall not Shimei be put to death for this, because he cursed the LORD'S anointed?",
      "22": "And David said, What have I to do with you, ye sons of Zeruiah, that ye should this day be adversaries unto me? shall there any man be put to death this day in Israel? for do not I know that I  am  this day king over Israel?",
      "23": "Therefore the king said unto Shimei, Thou shalt not die. And the king sware unto him. ",
      "24": "And Mephibosheth the son of Saul came down to meet the king, and had neither dressed his feet, nor trimmed his beard, nor washed his clothes, from the day the king departed until the day he came  again  in peace.",
      "25": "And it came to pass, when he was come to Jerusalem to meet the king, that the king said unto him, Wherefore wentest not thou with me, Mephibosheth?",
      "26": "And he answered, My lord, O king, my servant deceived me: for thy servant said, I will saddle me an ass, that I may ride thereon, and go to the king; because thy servant  is  lame.",
      "27": "And he hath slandered thy servant unto my lord the king; but my lord the king  is  as an angel of God: do therefore  what is  good in thine eyes.",
      "28": "For all  of  my father's house were but dead men before my lord the king: yet didst thou set thy servant among them that did eat at thine own table. What right therefore have I yet to cry any more unto the king? ",
      "29": "And the king said unto him, Why speakest thou any more of thy matters? I have said, Thou and Ziba divide the land.",
      "30": "And Mephibosheth said unto the king, Yea, let him take all, forasmuch as my lord the king is come again in peace unto his own house. ",
      "31": "And Barzillai the Gileadite came down from Rogelim, and went over Jordan with the king, to conduct him over Jordan.",
      "32": "Now Barzillai was a very aged man,  even  fourscore years old: and he had provided the king of sustenance while he lay at Mahanaim; for he  was  a very great man.",
      "33": "And the king said unto Barzillai, Come thou over with me, and I will feed thee with me in Jerusalem.",
      "34": "And Barzillai said unto the king, How long have I to live, that I should go up with the king unto Jerusalem? ",
      "35": "I  am  this day fourscore years old:  and  can I discern between good and evil? can thy servant taste what I eat or what I drink? can I hear any more the voice of singing men and singing women? wherefore then should thy servant be yet a burden unto my lord the king?",
      "36": "Thy servant will go a little way over Jordan with the king: and why should the king recompense it me with such a reward?",
      "37": "Let thy servant, I pray thee, turn back again, that I may die in mine own city,  and be buried  by the grave of my father and of my mother. But behold thy servant Chimham; let him go over with my lord the king; and do to him what shall seem good unto thee.",
      "38": "And the king answered, Chimham shall go over with me, and I will do to him that which shall seem good unto thee: and whatsoever thou shalt require of me,  that  will I do for thee. ",
      "39": "And all the people went over Jordan. And when the king was come over, the king kissed Barzillai, and blessed him; and he returned unto his own place. ",
      "40": "Then the king went on to Gilgal, and Chimham went on with him: and all the people of Judah conducted the king, and also half the people of Israel. ",
      "41": "And, behold, all the men of Israel came to the king, and said unto the king, Why have our brethren the men of Judah stolen thee away, and have brought the king, and his household, and all David's men with him, over Jordan?",
      "42": "And all the men of Judah answered the men of Israel, Because the king  is  near of kin to us: wherefore then be ye angry for this matter? have we eaten at all of the king's  cost ? or hath he given us any gift?",
      "43": "And the men of Israel answered the men of Judah, and said, We have ten parts in the king, and we have also more  right  in David than ye: why then did ye despise us, that our advice should not be first had in bringing back our king? And the words of the men of Judah were fiercer than the words of the men of Israel.  "
    },
    "20": {
      "1": "And there happened to be there a man of Belial, whose name  was  Sheba, the son of Bichri, a Benjamite: and he blew a trumpet, and said, We have no part in David, neither have we inheritance in the son of Jesse: every man to his tents, O Israel.",
      "2": "So every man of Israel went up from after David,  and  followed Sheba the son of Bichri: but the men of Judah clave unto their king, from Jordan even to Jerusalem.",
      "3": "And David came to his house at Jerusalem; and the king took the ten women  his  concubines, whom he had left to keep the house, and put them in ward, and fed them, but went not in unto them. So they were shut up unto the day of their death, living in widowhood.    ",
      "4": "Then said the king to Amasa, Assemble me the men of Judah within three days, and be thou here present. ",
      "5": "So Amasa went to assemble  the men of  Judah: but he tarried longer than the set time which he had appointed him. ",
      "6": "And David said to Abishai, Now shall Sheba the son of Bichri do us more harm than  did  Absalom: take thou thy lord's servants, and pursue after him, lest he get him fenced cities, and escape us. ",
      "7": "And there went out after him Joab's men, and the Cherethites, and the Pelethites, and all the mighty men: and they went out of Jerusalem, to pursue after Sheba the son of Bichri.",
      "8": "When they  were  at the great stone which  is  in Gibeon, Amasa went before them. And Joab's garment that he had put on was girded unto him, and upon it a girdle  with  a sword fastened upon his loins in the sheath thereof; and as he went forth it fell out.",
      "9": "And Joab said to Amasa,  Art  thou in health, my brother? And Joab took Amasa by the beard with the right hand to kiss him.",
      "10": "But Amasa took no heed to the sword that  was  in Joab's hand: so he smote him therewith in the fifth  rib , and shed out his bowels to the ground, and struck him not again; and he died. So Joab and Abishai his brother pursued after Sheba the son of Bichri. ",
      "11": "And one of Joab's men stood by him, and said, He that favoureth Joab, and he that  is  for David,  let him go  after Joab.",
      "12": "And Amasa wallowed in blood in the midst of the highway. And when the man saw that all the people stood still, he removed Amasa out of the highway into the field, and cast a cloth upon him, when he saw that every one that came by him stood still.",
      "13": "When he was removed out of the highway, all the people went on after Joab, to pursue after Sheba the son of Bichri. ",
      "14": "And he went through all the tribes of Israel unto Abel, and to Bethmaachah, and all the Berites: and they were gathered together, and went also after him.",
      "15": "And they came and besieged him in Abel of Bethmaachah, and they cast up a bank against the city, and it stood in the trench: and all the people that  were  with Joab battered the wall, to throw it down.  ",
      "16": "Then cried a wise woman out of the city, Hear, hear; say, I pray you, unto Joab, Come near hither, that I may speak with thee.",
      "17": "And when he was come near unto her, the woman said,  Art  thou Joab? And he answered, I  am he . Then she said unto him, Hear the words of thine handmaid. And he answered, I do hear.",
      "18": "Then she spake, saying, They were wont to speak in old time, saying, They shall surely ask  counsel  at Abel: and so they ended  the matter . ",
      "19": "I  am one of them that are  peaceable  and  faithful in Israel: thou seekest to destroy a city and a mother in Israel: why wilt thou swallow up the inheritance of the LORD?",
      "20": "And Joab answered and said, Far be it, far be it from me, that I should swallow up or destroy.",
      "21": "The matter  is  not so: but a man of mount Ephraim, Sheba the son of Bichri by name, hath lifted up his hand against the king,  even  against David: deliver him only, and I will depart from the city. And the woman said unto Joab, Behold, his head shall be thrown to thee over the wall. ",
      "22": "Then the woman went unto all the people in her wisdom. And they cut off the head of Sheba the son of Bichri, and cast  it  out to Joab. And he blew a trumpet, and they retired from the city, every man to his tent. And Joab returned to Jerusalem unto the king.  ",
      "23": "Now Joab  was  over all the host of Israel: and Benaiah the son of Jehoiada  was  over the Cherethites and over the Pelethites:",
      "24": "And Adoram  was  over the tribute: and Jehoshaphat the son of Ahilud  was  recorder: ",
      "25": "And Sheva  was  scribe: and Zadok and Abiathar  were  the priests:",
      "26": "And Ira also the Jairite was a chief ruler about David.  "
    },
    "21": {
      "1": "Then there was a famine in the days of David three years, year after year; and David enquired of the LORD. And the LORD answered,  It is  for Saul, and for  his  bloody house, because he slew the Gibeonites. ",
      "2": "And the king called the Gibeonites, and said unto them; (now the Gibeonites  were  not of the children of Israel, but of the remnant of the Amorites; and the children of Israel had sworn unto them: and Saul sought to slay them in his zeal to the children of Israel and Judah.)",
      "3": "Wherefore David said unto the Gibeonites, What shall I do for you? and wherewith shall I make the atonement, that ye may bless the inheritance of the LORD?",
      "4": "And the Gibeonites said unto him, We will have no silver nor gold of Saul, nor of his house; neither for us shalt thou kill any man in Israel. And he said, What ye shall say,  that  will I do for you. ",
      "5": "And they answered the king, The man that consumed us, and that devised against us  that  we should be destroyed from remaining in any of the coasts of Israel, ",
      "6": "Let seven men of his sons be delivered unto us, and we will hang them up unto the LORD in Gibeah of Saul,  whom  the LORD did choose. And the king said, I will give  them . ",
      "7": "But the king spared Mephibosheth, the son of Jonathan the son of Saul, because of the LORD'S oath that  was  between them, between David and Jonathan the son of Saul.",
      "8": "But the king took the two sons of Rizpah the daughter of Aiah, whom she bare unto Saul, Armoni and Mephibosheth; and the five sons of Michal the daughter of Saul, whom she brought up for Adriel the son of Barzillai the Meholathite:  ",
      "9": "And he delivered them into the hands of the Gibeonites, and they hanged them in the hill before the LORD: and they fell  all  seven together, and were put to death in the days of harvest, in the first  days , in the beginning of barley harvest. ",
      "10": "And Rizpah the daughter of Aiah took sackcloth, and spread it for her upon the rock, from the beginning of harvest until water dropped upon them out of heaven, and suffered neither the birds of the air to rest on them by day, nor the beasts of the field by night.",
      "11": "And it was told David what Rizpah the daughter of Aiah, the concubine of Saul, had done.",
      "12": "And David went and took the bones of Saul and the bones of Jonathan his son from the men of Jabeshgilead, which had stolen them from the street of Bethshan, where the Philistines had hanged them, when the Philistines had slain Saul in Gilboa:",
      "13": "And he brought up from thence the bones of Saul and the bones of Jonathan his son; and they gathered the bones of them that were hanged.",
      "14": "And the bones of Saul and Jonathan his son buried they in the country of Benjamin in Zelah, in the sepulchre of Kish his father: and they performed all that the king commanded. And after that God was intreated for the land. ",
      "15": "Moreover the Philistines had yet war again with Israel; and David went down, and his servants with him, and fought against the Philistines: and David waxed faint.",
      "16": "And Ishbibenob, which  was  of the sons of the giant, the weight of whose spear  weighed  three hundred  shekels  of brass in weight, he being girded with a new  sword , thought to have slain David.  ",
      "17": "But Abishai the son of Zeruiah succoured him, and smote the Philistine, and killed him. Then the men of David sware unto him, saying, Thou shalt go no more out with us to battle, that thou quench not the light of Israel. ",
      "18": "And it came to pass after this, that there was again a battle with the Philistines at Gob: then Sibbechai the Hushathite slew Saph, which  was  of the sons of the giant.  ",
      "19": "And there was again a battle in Gob with the Philistines, where Elhanan the son of Jaareoregim, a Bethlehemite, slew  the brother of  Goliath the Gittite, the staff of whose spear  was  like a weaver's beam. ",
      "20": "And there was yet a battle in Gath, where was a man of  great  stature, that had on every hand six fingers, and on every foot six toes, four and twenty in number; and he also was born to the giant. ",
      "21": "And when he defied Israel, Jonathan the son of Shimea the brother of David slew him. ",
      "22": "These four were born to the giant in Gath, and fell by the hand of David, and by the hand of his servants. "
    },
    "22": {
      "1": "And David spake unto the LORD the words of this song in the day  that  the LORD had delivered him out of the hand of all his enemies, and out of the hand of Saul: ",
      "2": "And he said, The LORD  is  my rock, and my fortress, and my deliverer;",
      "3": "The God of my rock; in him will I trust:  he is  my shield, and the horn of my salvation, my high tower, and my refuge, my saviour; thou savest me from violence.",
      "4": "I will call on the LORD,  who is  worthy to be praised: so shall I be saved from mine enemies.",
      "5": "When the waves of death compassed me, the floods of ungodly men made me afraid;  ",
      "6": "The sorrows of hell compassed me about; the snares of death prevented me; ",
      "7": "In my distress I called upon the LORD, and cried to my God: and he did hear my voice out of his temple, and my cry  did enter  into his ears.",
      "8": "Then the earth shook and trembled; the foundations of heaven moved and shook, because he was wroth.",
      "9": "There went up a smoke out of his nostrils, and fire out of his mouth devoured: coals were kindled by it. ",
      "10": "He bowed the heavens also, and came down; and darkness  was  under his feet.",
      "11": "And he rode upon a cherub, and did fly: and he was seen upon the wings of the wind.",
      "12": "And he made darkness pavilions round about him, dark waters,  and  thick clouds of the skies. ",
      "13": "Through the brightness before him were coals of fire kindled.",
      "14": "The LORD thundered from heaven, and the most High uttered his voice.",
      "15": "And he sent out arrows, and scattered them; lightning, and discomfited them.",
      "16": "And the channels of the sea appeared, the foundations of the world were discovered, at the rebuking of the LORD, at the blast of the breath of his nostrils.",
      "17": "He sent from above, he took me; he drew me out of many waters; ",
      "18": "He delivered me from my strong enemy,  and  from them that hated me: for they were too strong for me.",
      "19": "They prevented me in the day of my calamity: but the LORD was my stay.",
      "20": "He brought me forth also into a large place: he delivered me, because he delighted in me.",
      "21": "The LORD rewarded me according to my righteousness: according to the cleanness of my hands hath he recompensed me.",
      "22": "For I have kept the ways of the LORD, and have not wickedly departed from my God.",
      "23": "For all his judgments  were  before me: and  as for  his statutes, I did not depart from them.",
      "24": "I was also upright before him, and have kept myself from mine iniquity. ",
      "25": "Therefore the LORD hath recompensed me according to my righteousness; according to my cleanness in his eye sight. ",
      "26": "With the merciful thou wilt shew thyself merciful,  and  with the upright man thou wilt shew thyself upright.",
      "27": "With the pure thou wilt shew thyself pure; and with the froward thou wilt shew thyself unsavoury. ",
      "28": "And the afflicted people thou wilt save: but thine eyes  are  upon the haughty,  that  thou mayest bring  them  down.",
      "29": "For thou  art  my lamp, O LORD: and the LORD will lighten my darkness. ",
      "30": "For by thee I have run through a troop: by my God have I leaped over a wall. ",
      "31": " As for  God, his way  is  perfect; the word of the LORD  is  tried: he  is  a buckler to all them that trust in him. ",
      "32": "For who  is  God, save the LORD? and who  is  a rock, save our God?",
      "33": "God  is  my strength  and  power: and he maketh my way perfect. ",
      "34": "He maketh my feet like hinds'  feet : and setteth me upon my high places. ",
      "35": "He teacheth my hands to war; so that a bow of steel is broken by mine arms. ",
      "36": "Thou hast also given me the shield of thy salvation: and thy gentleness hath made me great. ",
      "37": "Thou hast enlarged my steps under me; so that my feet did not slip. ",
      "38": "I have pursued mine enemies, and destroyed them; and turned not again until I had consumed them.",
      "39": "And I have consumed them, and wounded them, that they could not arise: yea, they are fallen under my feet.",
      "40": "For thou hast girded me with strength to battle: them that rose up against me hast thou subdued under me. ",
      "41": "Thou hast also given me the necks of mine enemies, that I might destroy them that hate me.",
      "42": "They looked, but  there was  none to save;  even  unto the LORD, but he answered them not.",
      "43": "Then did I beat them as small as the dust of the earth, I did stamp them as the mire of the street,  and  did spread them abroad.",
      "44": "Thou also hast delivered me from the strivings of my people, thou hast kept me  to be  head of the heathen: a people  which  I knew not shall serve me.",
      "45": "Strangers shall submit themselves unto me: as soon as they hear, they shall be obedient unto me.  ",
      "46": "Strangers shall fade away, and they shall be afraid out of their close places.",
      "47": "The LORD liveth; and blessed  be  my rock; and exalted be the God of the rock of my salvation.",
      "48": "It  is  God that avengeth me, and that bringeth down the people under me, ",
      "49": "And that bringeth me forth from mine enemies: thou also hast lifted me up on high above them that rose up against me: thou hast delivered me from the violent man.",
      "50": "Therefore I will give thanks unto thee, O LORD, among the heathen, and I will sing praises unto thy name.",
      "51": " He is  the tower of salvation for his king: and sheweth mercy to his anointed, unto David, and to his seed for evermore. "
    },
    "23": {
      "1": "Now these  be  the last words of David. David the son of Jesse said, and the man  who was  raised up on high, the anointed of the God of Jacob, and the sweet psalmist of Israel, said,",
      "2": "The Spirit of the LORD spake by me, and his word  was  in my tongue.",
      "3": "The God of Israel said, the Rock of Israel spake to me, He that ruleth over men  must be  just, ruling in the fear of God. ",
      "4": "And  he shall be  as the light of the morning,  when  the sun riseth,  even  a morning without clouds;  as  the tender grass  springing  out of the earth by clear shining after rain.",
      "5": "Although my house  be  not so with God; yet he hath made with me an everlasting covenant, ordered in all  things , and sure: for  this is  all my salvation, and all  my  desire, although he make  it  not to grow.",
      "6": "But  the sons  of Belial  shall be  all of them as thorns thrust away, because they cannot be taken with hands:",
      "7": "But the man  that  shall touch them must be fenced with iron and the staff of a spear; and they shall be utterly burned with fire in the  same  place.  ",
      "8": "These  be  the names of the mighty men whom David had: The Tachmonite that sat in the seat, chief among the captains; the same  was  Adino the Eznite:  he lift up his spear  against eight hundred, whom he slew at one time. ",
      "9": "And after him  was  Eleazar the son of Dodo the Ahohite,  one  of the three mighty men with David, when they defied the Philistines  that  were there gathered together to battle, and the men of Israel were gone away:",
      "10": "He arose, and smote the Philistines until his hand was weary, and his hand clave unto the sword: and the LORD wrought a great victory that day; and the people returned after him only to spoil.",
      "11": "And after him  was  Shammah the son of Agee the Hararite. And the Philistines were gathered together into a troop, where was a piece of ground full of lentiles: and the people fled from the Philistines. ",
      "12": "But he stood in the midst of the ground, and defended it, and slew the Philistines: and the LORD wrought a great victory.",
      "13": "And three of the thirty chief went down, and came to David in the harvest time unto the cave of Adullam: and the troop of the Philistines pitched in the valley of Rephaim. ",
      "14": "And David  was  then in an hold, and the garrison of the Philistines  was  then  in  Bethlehem.",
      "15": "And David longed, and said, Oh that one would give me drink of the water of the well of Bethlehem, which  is  by the gate!",
      "16": "And the three mighty men brake through the host of the Philistines, and drew water out of the well of Bethlehem, that  was  by the gate, and took  it , and brought  it  to David: nevertheless he would not drink thereof, but poured it out unto the LORD.",
      "17": "And he said, Be it far from me, O LORD, that I should do this:  is not this  the blood of the men that went in jeopardy of their lives? therefore he would not drink it. These things did these three mighty men.",
      "18": "And Abishai, the brother of Joab, the son of Zeruiah, was chief among three. And he lifted up his spear against three hundred,  and  slew  them , and had the name among three. ",
      "19": "Was he not most honourable of three? therefore he was their captain: howbeit he attained not unto the  first  three.",
      "20": "And Benaiah the son of Jehoiada, the son of a valiant man, of Kabzeel, who had done many acts, he slew two lionlike men of Moab: he went down also and slew a lion in the midst of a pit in time of snow:  ",
      "21": "And he slew an Egyptian, a goodly man: and the Egyptian had a spear in his hand; but he went down to him with a staff, and plucked the spear out of the Egyptian's hand, and slew him with his own spear. ",
      "22": "These  things  did Benaiah the son of Jehoiada, and had the name among three mighty men.",
      "23": "He was more honourable than the thirty, but he attained not to the  first  three. And David set him over his guard.  ",
      "24": "Asahel the brother of Joab  was  one of the thirty; Elhanan the son of Dodo of Bethlehem,",
      "25": "Shammah the Harodite, Elika the Harodite,",
      "26": "Helez the Paltite, Ira the son of Ikkesh the Tekoite,",
      "27": "Abiezer the Anethothite, Mebunnai the Hushathite,",
      "28": "Zalmon the Ahohite, Maharai the Netophathite,",
      "29": "Heleb the son of Baanah, a Netophathite, Ittai the son of Ribai out of Gibeah of the children of Benjamin,",
      "30": "Benaiah the Pirathonite, Hiddai of the brooks of Gaash, ",
      "31": "Abialbon the Arbathite, Azmaveth the Barhumite,",
      "32": "Eliahba the Shaalbonite, of the sons of Jashen, Jonathan,",
      "33": "Shammah the Hararite, Ahiam the son of Sharar the Hararite,",
      "34": "Eliphelet the son of Ahasbai, the son of the Maachathite, Eliam the son of Ahithophel the Gilonite,",
      "35": "Hezrai the Carmelite, Paarai the Arbite,",
      "36": "Igal the son of Nathan of Zobah, Bani the Gadite,",
      "37": "Zelek the Ammonite, Naharai the Beerothite, armourbearer to Joab the son of Zeruiah,",
      "38": "Ira an Ithrite, Gareb an Ithrite,",
      "39": "Uriah the Hittite: thirty and seven in all. "
    },
    "24": {
      "1": "And again the anger of the LORD was kindled against Israel, and he moved David against them to say, Go, number Israel and Judah.",
      "2": "For the king said to Joab the captain of the host, which  was  with him, Go now through all the tribes of Israel, from Dan even to Beersheba, and number ye the people, that I may know the number of the people. ",
      "3": "And Joab said unto the king, Now the LORD thy God add unto the people, how many soever they be, an hundredfold, and that the eyes of my lord the king may see  it : but why doth my lord the king delight in this thing?",
      "4": "Notwithstanding the king's word prevailed against Joab, and against the captains of the host. And Joab and the captains of the host went out from the presence of the king, to number the people of Israel.",
      "5": "And they passed over Jordan, and pitched in Aroer, on the right side of the city that  lieth  in the midst of the river of Gad, and toward Jazer: ",
      "6": "Then they came to Gilead, and to the land of Tahtimhodshi; and they came to Danjaan, and about to Zidon, ",
      "7": "And came to the strong hold of Tyre, and to all the cities of the Hivites, and of the Canaanites: and they went out to the south of Judah,  even  to Beersheba.",
      "8": "So when they had gone through all the land, they came to Jerusalem at the end of nine months and twenty days.",
      "9": "And Joab gave up the sum of the number of the people unto the king: and there were in Israel eight hundred thousand valiant men that drew the sword; and the men of Judah  were  five hundred thousand men. ",
      "10": "And David's heart smote him after that he had numbered the people. And David said unto the LORD, I have sinned greatly in that I have done: and now, I beseech thee, O LORD, take away the iniquity of thy servant; for I have done very foolishly.",
      "11": "For when David was up in the morning, the word of the LORD came unto the prophet Gad, David's seer, saying,",
      "12": "Go and say unto David, Thus saith the LORD, I offer thee three  things ; choose thee one of them, that I may  do it  unto thee.",
      "13": "So Gad came to David, and told him, and said unto him, Shall seven years of famine come unto thee in thy land? or wilt thou flee three months before thine enemies, while they pursue thee? or that there be three days' pestilence in thy land? now advise, and see what answer I shall return to him that sent me.",
      "14": "And David said unto Gad, I am in a great strait: let us fall now into the hand of the LORD; for his mercies  are  great: and let me not fall into the hand of man. ",
      "15": "So the LORD sent a pestilence upon Israel from the morning even to the time appointed: and there died of the people from Dan even to Beersheba seventy thousand men.",
      "16": "And when the angel stretched out his hand upon Jerusalem to destroy it, the LORD repented him of the evil, and said to the angel that destroyed the people, It is enough: stay now thine hand. And the angel of the LORD was by the threshingplace of Araunah the Jebusite.",
      "17": "And David spake unto the LORD when he saw the angel that smote the people, and said, Lo, I have sinned, and I have done wickedly: but these sheep, what have they done? let thine hand, I pray thee, be against me, and against my father's house. ",
      "18": "And Gad came that day to David, and said unto him, Go up, rear an altar unto the LORD in the threshingfloor of Araunah the Jebusite. ",
      "19": "And David, according to the saying of Gad, went up as the LORD commanded.",
      "20": "And Araunah looked, and saw the king and his servants coming on toward him: and Araunah went out, and bowed himself before the king on his face upon the ground.",
      "21": "And Araunah said, Wherefore is my lord the king come to his servant? And David said, To buy the threshingfloor of thee, to build an altar unto the LORD, that the plague may be stayed from the people.",
      "22": "And Araunah said unto David, Let my lord the king take and offer up what  seemeth  good unto him: behold,  here be  oxen for burnt sacrifice, and threshing instruments and  other  instruments of the oxen for wood.",
      "23": "All these  things  did Araunah,  as  a king, give unto the king. And Araunah said unto the king, The LORD thy God accept thee.",
      "24": "And the king said unto Araunah, Nay; but I will surely buy  it  of thee at a price: neither will I offer burnt offerings unto the LORD my God of that which doth cost me nothing. So David bought the threshingfloor and the oxen for fifty shekels of silver.",
      "25": "And David built there an altar unto the LORD, and offered burnt offerings and peace offerings. So the LORD was intreated for the land, and the plague was stayed from Israel. "
    }
  },
  "1_kings": {
    "1": {
      "1": "Now king David was old  and  stricken in years; and they covered him with clothes, but he gat no heat. ",
      "2": "Wherefore his servants said unto him, Let there be sought for my lord the king a young virgin: and let her stand before the king, and let her cherish him, and let her lie in thy bosom, that my lord the king may get heat.   ",
      "3": "So they sought for a fair damsel throughout all the coasts of Israel, and found Abishag a Shunammite, and brought her to the king.",
      "4": "And the damsel  was  very fair, and cherished the king, and ministered to him: but the king knew her not. ",
      "5": "Then Adonijah the son of Haggith exalted himself, saying, I will be king: and he prepared him chariots and horsemen, and fifty men to run before him. ",
      "6": "And his father had not displeased him at any time in saying, Why hast thou done so? and he also  was a  very goodly  man ; and  his mother  bare him after Absalom. ",
      "7": "And he conferred with Joab the son of Zeruiah, and with Abiathar the priest: and they following Adonijah helped  him .  ",
      "8": "But Zadok the priest, and Benaiah the son of Jehoiada, and Nathan the prophet, and Shimei, and Rei, and the mighty men which  belonged  to David, were not with Adonijah.",
      "9": "And Adonijah slew sheep and oxen and fat cattle by the stone of Zoheleth, which  is  by Enrogel, and called all his brethren the king's sons, and all the men of Judah the king's servants: ",
      "10": "But Nathan the prophet, and Benaiah, and the mighty men, and Solomon his brother, he called not. ",
      "11": "Wherefore Nathan spake unto Bathsheba the mother of Solomon, saying, Hast thou not heard that Adonijah the son of Haggith doth reign, and David our lord knoweth  it  not?",
      "12": "Now therefore come, let me, I pray thee, give thee counsel, that thou mayest save thine own life, and the life of thy son Solomon.",
      "13": "Go and get thee in unto king David, and say unto him, Didst not thou, my lord, O king, swear unto thine handmaid, saying, Assuredly Solomon thy son shall reign after me, and he shall sit upon my throne? why then doth Adonijah reign?",
      "14": "Behold, while thou yet talkest there with the king, I also will come in after thee, and confirm thy words. ",
      "15": "And Bathsheba went in unto the king into the chamber: and the king was very old; and Abishag the Shunammite ministered unto the king.",
      "16": "And Bathsheba bowed, and did obeisance unto the king. And the king said, What wouldest thou? ",
      "17": "And she said unto him, My lord, thou swarest by the LORD thy God unto thine handmaid,  saying , Assuredly Solomon thy son shall reign after me, and he shall sit upon my throne.",
      "18": "And now, behold, Adonijah reigneth; and now, my lord the king, thou knowest  it  not:",
      "19": "And he hath slain oxen and fat cattle and sheep in abundance, and hath called all the sons of the king, and Abiathar the priest, and Joab the captain of the host: but Solomon thy servant hath he not called.",
      "20": "And thou, my lord, O king, the eyes of all Israel  are  upon thee, that thou shouldest tell them who shall sit on the throne of my lord the king after him.",
      "21": "Otherwise it shall come to pass, when my lord the king shall sleep with his fathers, that I and my son Solomon shall be counted offenders. ",
      "22": "And, lo, while she yet talked with the king, Nathan the prophet also came in.",
      "23": "And they told the king, saying, Behold Nathan the prophet. And when he was come in before the king, he bowed himself before the king with his face to the ground.",
      "24": "And Nathan said, My lord, O king, hast thou said, Adonijah shall reign after me, and he shall sit upon my throne?",
      "25": "For he is gone down this day, and hath slain oxen and fat cattle and sheep in abundance, and hath called all the king's sons, and the captains of the host, and Abiathar the priest; and, behold, they eat and drink before him, and say, God save king Adonijah. ",
      "26": "But me,  even  me thy servant, and Zadok the priest, and Benaiah the son of Jehoiada, and thy servant Solomon, hath he not called.",
      "27": "Is this thing done by my lord the king, and thou hast not shewed  it  unto thy servant, who should sit on the throne of my lord the king after him?",
      "28": "Then king David answered and said, Call me Bathsheba. And she came into the king's presence, and stood before the king. ",
      "29": "And the king sware, and said,  As  the LORD liveth, that hath redeemed my soul out of all distress,",
      "30": "Even as I sware unto thee by the LORD God of Israel, saying, Assuredly Solomon thy son shall reign after me, and he shall sit upon my throne in my stead; even so will I certainly do this day.",
      "31": "Then Bathsheba bowed with  her  face to the earth, and did reverence to the king, and said, Let my lord king David live for ever. ",
      "32": "And king David said, Call me Zadok the priest, and Nathan the prophet, and Benaiah the son of Jehoiada. And they came before the king.",
      "33": "The king also said unto them, Take with you the servants of your lord, and cause Solomon my son to ride upon mine own mule, and bring him down to Gihon: ",
      "34": "And let Zadok the priest and Nathan the prophet anoint him there king over Israel: and blow ye with the trumpet, and say, God save king Solomon.",
      "35": "Then ye shall come up after him, that he may come and sit upon my throne; for he shall be king in my stead: and I have appointed him to be ruler over Israel and over Judah.",
      "36": "And Benaiah the son of Jehoiada answered the king, and said, Amen: the LORD God of my lord the king say so  too .",
      "37": "As the LORD hath been with my lord the king, even so be he with Solomon, and make his throne greater than the throne of my lord king David.",
      "38": "So Zadok the priest, and Nathan the prophet, and Benaiah the son of Jehoiada, and the Cherethites, and the Pelethites, went down, and caused Solomon to ride upon king David's mule, and brought him to Gihon.",
      "39": "And Zadok the priest took an horn of oil out of the tabernacle, and anointed Solomon. And they blew the trumpet; and all the people said, God save king Solomon.",
      "40": "And all the people came up after him, and the people piped with pipes, and rejoiced with great joy, so that the earth rent with the sound of them.  ",
      "41": "And Adonijah and all the guests that  were  with him heard  it  as they had made an end of eating. And when Joab heard the sound of the trumpet, he said, Wherefore  is this  noise of the city being in an uproar?",
      "42": "And while he yet spake, behold, Jonathan the son of Abiathar the priest came: and Adonijah said unto him, Come in; for thou  art  a valiant man, and bringest good tidings.",
      "43": "And Jonathan answered and said to Adonijah, Verily our lord king David hath made Solomon king.",
      "44": "And the king hath sent with him Zadok the priest, and Nathan the prophet, and Benaiah the son of Jehoiada, and the Cherethites, and the Pelethites, and they have caused him to ride upon the king's mule:",
      "45": "And Zadok the priest and Nathan the prophet have anointed him king in Gihon: and they are come up from thence rejoicing, so that the city rang again. This  is  the noise that ye have heard.",
      "46": "And also Solomon sitteth on the throne of the kingdom.",
      "47": "And moreover the king's servants came to bless our lord king David, saying, God make the name of Solomon better than thy name, and make his throne greater than thy throne. And the king bowed himself upon the bed.",
      "48": "And also thus said the king, Blessed  be  the LORD God of Israel, which hath given  one  to sit on my throne this day, mine eyes even seeing  it .",
      "49": "And all the guests that  were  with Adonijah were afraid, and rose up, and went every man his way.",
      "50": "And Adonijah feared because of Solomon, and arose, and went, and caught hold on the horns of the altar.",
      "51": "And it was told Solomon, saying, Behold, Adonijah feareth king Solomon: for, lo, he hath caught hold on the horns of the altar, saying, Let king Solomon swear unto me to day that he will not slay his servant with the sword.",
      "52": "And Solomon said, If he will shew himself a worthy man, there shall not an hair of him fall to the earth: but if wickedness shall be found in him, he shall die.",
      "53": "So king Solomon sent, and they brought him down from the altar. And he came and bowed himself to king Solomon: and Solomon said unto him, Go to thine house. "
    },
    "2": {
      "1": "Now the days of David drew nigh that he should die; and he charged Solomon his son, saying,",
      "2": "I go the way of all the earth: be thou strong therefore, and shew thyself a man;",
      "3": "And keep the charge of the LORD thy God, to walk in his ways, to keep his statutes, and his commandments, and his judgments, and his testimonies, as it is written in the law of Moses, that thou mayest prosper in all that thou doest, and whithersoever thou turnest thyself: ",
      "4": "That the LORD may continue his word which he spake concerning me, saying, If thy children take heed to their way, to walk before me in truth with all their heart and with all their soul, there shall not fail thee (said he) a man on the throne of Israel. ",
      "5": "Moreover thou knowest also what Joab the son of Zeruiah did to me,  and  what he did to the two captains of the hosts of Israel, unto Abner the son of Ner, and unto Amasa the son of Jether, whom he slew, and shed the blood of war in peace, and put the blood of war upon his girdle that  was  about his loins, and in his shoes that  were  on his feet. ",
      "6": "Do therefore according to thy wisdom, and let not his hoar head go down to the grave in peace.",
      "7": "But shew kindness unto the sons of Barzillai the Gileadite, and let them be of those that eat at thy table: for so they came to me when I fled because of Absalom thy brother.",
      "8": "And, behold,  thou hast  with thee Shimei the son of Gera, a Benjamite of Bahurim, which cursed me with a grievous curse in the day when I went to Mahanaim: but he came down to meet me at Jordan, and I sware to him by the LORD, saying, I will not put thee to death with the sword. ",
      "9": "Now therefore hold him not guiltless: for thou  art  a wise man, and knowest what thou oughtest to do unto him; but his hoar head bring thou down to the grave with blood.",
      "10": "So David slept with his fathers, and was buried in the city of David.",
      "11": "And the days that David reigned over Israel  were  forty years: seven years reigned he in Hebron, and thirty and three years reigned he in Jerusalem. ",
      "12": "Then sat Solomon upon the throne of David his father; and his kingdom was established greatly.",
      "13": "And Adonijah the son of Haggith came to Bathsheba the mother of Solomon. And she said, Comest thou peaceably? And he said, Peaceably.",
      "14": "He said moreover, I have somewhat to say unto thee. And she said, Say on.",
      "15": "And he said, Thou knowest that the kingdom was mine, and  that  all Israel set their faces on me, that I should reign: howbeit the kingdom is turned about, and is become my brother's: for it was his from the LORD.",
      "16": "And now I ask one petition of thee, deny me not. And she said unto him, Say on. ",
      "17": "And he said, Speak, I pray thee, unto Solomon the king, (for he will not say thee nay,) that he give me Abishag the Shunammite to wife.",
      "18": "And Bathsheba said, Well; I will speak for thee unto the king.",
      "19": "Bathsheba therefore went unto king Solomon, to speak unto him for Adonijah. And the king rose up to meet her, and bowed himself unto her, and sat down on his throne, and caused a seat to be set for the king's mother; and she sat on his right hand.",
      "20": "Then she said, I desire one small petition of thee;  I pray thee , say me not nay. And the king said unto her, Ask on, my mother: for I will not say thee nay.",
      "21": "And she said, Let Abishag the Shunammite be given to Adonijah thy brother to wife.",
      "22": "And king Solomon answered and said unto his mother, And why dost thou ask Abishag the Shunammite for Adonijah? ask for him the kingdom also; for he  is  mine elder brother; even for him, and for Abiathar the priest, and for Joab the son of Zeruiah.",
      "23": "Then king Solomon sware by the LORD, saying, God do so to me, and more also, if Adonijah have not spoken this word against his own life.",
      "24": "Now therefore,  as  the LORD liveth, which hath established me, and set me on the throne of David my father, and who hath made me an house, as he promised, Adonijah shall be put to death this day.",
      "25": "And king Solomon sent by the hand of Benaiah the son of Jehoiada; and he fell upon him that he died. ",
      "26": "And unto Abiathar the priest said the king, Get thee to Anathoth, unto thine own fields; for thou  art  worthy of death: but I will not at this time put thee to death, because thou barest the ark of the Lord GOD before David my father, and because thou hast been afflicted in all wherein my father was afflicted. ",
      "27": "So Solomon thrust out Abiathar from being priest unto the LORD; that he might fulfil the word of the LORD, which he spake concerning the house of Eli in Shiloh.",
      "28": "Then tidings came to Joab: for Joab had turned after Adonijah, though he turned not after Absalom. And Joab fled unto the tabernacle of the LORD, and caught hold on the horns of the altar.",
      "29": "And it was told king Solomon that Joab was fled unto the tabernacle of the LORD; and, behold,  he is  by the altar. Then Solomon sent Benaiah the son of Jehoiada, saying, Go, fall upon him.",
      "30": "And Benaiah came to the tabernacle of the LORD, and said unto him, Thus saith the king, Come forth. And he said, Nay; but I will die here. And Benaiah brought the king word again, saying, Thus said Joab, and thus he answered me.",
      "31": "And the king said unto him, Do as he hath said, and fall upon him, and bury him; that thou mayest take away the innocent blood, which Joab shed, from me, and from the house of my father.",
      "32": "And the LORD shall return his blood upon his own head, who fell upon two men more righteous and better than he, and slew them with the sword, my father David not knowing  thereof, to wit , Abner the son of Ner, captain of the host of Israel, and Amasa the son of Jether, captain of the host of Judah.",
      "33": "Their blood shall therefore return upon the head of Joab, and upon the head of his seed for ever: but upon David, and upon his seed, and upon his house, and upon his throne, shall there be peace for ever from the LORD.",
      "34": "So Benaiah the son of Jehoiada went up, and fell upon him, and slew him: and he was buried in his own house in the wilderness. ",
      "35": "And the king put Benaiah the son of Jehoiada in his room over the host: and Zadok the priest did the king put in the room of Abiathar.",
      "36": "And the king sent and called for Shimei, and said unto him, Build thee an house in Jerusalem, and dwell there, and go not forth thence any whither.",
      "37": "For it shall be,  that  on the day thou goest out, and passest over the brook Kidron, thou shalt know for certain that thou shalt surely die: thy blood shall be upon thine own head.",
      "38": "And Shimei said unto the king, The saying  is  good: as my lord the king hath said, so will thy servant do. And Shimei dwelt in Jerusalem many days.",
      "39": "And it came to pass at the end of three years, that two of the servants of Shimei ran away unto Achish son of Maachah king of Gath. And they told Shimei, saying, Behold, thy servants  be  in Gath.",
      "40": "And Shimei arose, and saddled his ass, and went to Gath to Achish to seek his servants: and Shimei went, and brought his servants from Gath.",
      "41": "And it was told Solomon that Shimei had gone from Jerusalem to Gath, and was come again.",
      "42": "And the king sent and called for Shimei, and said unto him, Did I not make thee to swear by the LORD, and protested unto thee, saying, Know for a certain, on the day thou goest out, and walkest abroad any whither, that thou shalt surely die? and thou saidst unto me, The word  that  I have heard  is  good.",
      "43": "Why then hast thou not kept the oath of the LORD, and the commandment that I have charged thee with?",
      "44": "The king said moreover to Shimei, Thou knowest all the wickedness which thine heart is privy to, that thou didst to David my father: therefore the LORD shall return thy wickedness upon thine own head;",
      "45": "And king Solomon  shall be  blessed, and the throne of David shall be established before the LORD for ever.",
      "46": "So the king commanded Benaiah the son of Jehoiada; which went out, and fell upon him, that he died. And the kingdom was established in the hand of Solomon. "
    },
    "3": {
      "1": "And Solomon made affinity with Pharaoh king of Egypt, and took Pharaoh's daughter, and brought her into the city of David, until he had made an end of building his own house, and the house of the LORD, and the wall of Jerusalem round about.",
      "2": "Only the people sacrificed in high places, because there was no house built unto the name of the LORD, until those days.",
      "3": "And Solomon loved the LORD, walking in the statutes of David his father: only he sacrificed and burnt incense in high places.",
      "4": "And the king went to Gibeon to sacrifice there; for that  was  the great high place: a thousand burnt offerings did Solomon offer upon that altar. ",
      "5": "In Gibeon the LORD appeared to Solomon in a dream by night: and God said, Ask what I shall give thee.",
      "6": "And Solomon said, Thou hast shewed unto thy servant David my father great mercy, according as he walked before thee in truth, and in righteousness, and in uprightness of heart with thee; and thou hast kept for him this great kindness, that thou hast given him a son to sit on his throne, as  it is  this day. ",
      "7": "And now, O LORD my God, thou hast made thy servant king instead of David my father: and I  am but  a little child: I know not  how  to go out or come in.",
      "8": "And thy servant  is  in the midst of thy people which thou hast chosen, a great people, that cannot be numbered nor counted for multitude.",
      "9": "Give therefore thy servant an understanding heart to judge thy people, that I may discern between good and bad: for who is able to judge this thy so great a people? ",
      "10": "And the speech pleased the Lord, that Solomon had asked this thing.",
      "11": "And God said unto him, Because thou hast asked this thing, and hast not asked for thyself long life; neither hast asked riches for thyself, nor hast asked the life of thine enemies; but hast asked for thyself understanding to discern judgment;  ",
      "12": "Behold, I have done according to thy words: lo, I have given thee a wise and an understanding heart; so that there was none like thee before thee, neither after thee shall any arise like unto thee.",
      "13": "And I have also given thee that which thou hast not asked, both riches, and honour: so that there shall not be any among the kings like unto thee all thy days. ",
      "14": "And if thou wilt walk in my ways, to keep my statutes and my commandments, as thy father David did walk, then I will lengthen thy days.",
      "15": "And Solomon awoke; and, behold,  it was  a dream. And he came to Jerusalem, and stood before the ark of the covenant of the LORD, and offered up burnt offerings, and offered peace offerings, and made a feast to all his servants. ",
      "16": "Then came there two women,  that were  harlots, unto the king, and stood before him.",
      "17": "And the one woman said, O my lord, I and this woman dwell in one house; and I was delivered of a child with her in the house.",
      "18": "And it came to pass the third day after that I was delivered, that this woman was delivered also: and we  were  together;  there was  no stranger with us in the house, save we two in the house.",
      "19": "And this woman's child died in the night; because she overlaid it.",
      "20": "And she arose at midnight, and took my son from beside me, while thine handmaid slept, and laid it in her bosom, and laid her dead child in my bosom.",
      "21": "And when I rose in the morning to give my child suck, behold, it was dead: but when I had considered it in the morning, behold, it was not my son, which I did bear.",
      "22": "And the other woman said, Nay; but the living  is  my son, and the dead  is  thy son. And this said, No; but the dead  is  thy son, and the living  is  my son. Thus they spake before the king.",
      "23": "Then said the king, The one saith, This  is  my son that liveth, and thy son  is  the dead: and the other saith, Nay; but thy son  is  the dead, and my son  is  the living.",
      "24": "And the king said, Bring me a sword. And they brought a sword before the king.",
      "25": "And the king said, Divide the living child in two, and give half to the one, and half to the other.",
      "26": "Then spake the woman whose the living child  was  unto the king, for her bowels yearned upon her son, and she said, O my lord, give her the living child, and in no wise slay it. But the other said, Let it be neither mine nor thine,  but  divide  it . ",
      "27": "Then the king answered and said, Give her the living child, and in no wise slay it: she  is  the mother thereof.",
      "28": "And all Israel heard of the judgment which the king had judged; and they feared the king: for they saw that the wisdom of God  was  in him, to do judgment.  "
    },
    "4": {
      "1": "So king Solomon was king over all Israel.",
      "2": "And these  were  the princes which he had; Azariah the son of Zadok the priest, ",
      "3": "Elihoreph and Ahiah, the sons of Shisha, scribes; Jehoshaphat the son of Ahilud, the recorder.  ",
      "4": "And Benaiah the son of Jehoiada  was  over the host: and Zadok and Abiathar  were  the priests:",
      "5": "And Azariah the son of Nathan  was  over the officers: and Zabud the son of Nathan  was  principal officer,  and  the king's friend:",
      "6": "And Ahishar  was  over the household: and Adoniram the son of Abda  was  over the tribute. ",
      "7": "And Solomon had twelve officers over all Israel, which provided victuals for the king and his household: each man his month in a year made provision.",
      "8": "And these  are  their names: The son of Hur, in mount Ephraim: ",
      "9": "The son of Dekar, in Makaz, and in Shaalbim, and Bethshemesh, and Elonbethhanan: ",
      "10": "The son of Hesed, in Aruboth; to him  pertained  Sochoh, and all the land of Hepher: ",
      "11": "The son of Abinadab, in all the region of Dor; which had Taphath the daughter of Solomon to wife: ",
      "12": "Baana the son of Ahilud;  to him pertained  Taanach and Megiddo, and all Bethshean, which  is  by Zartanah beneath Jezreel, from Bethshean to Abelmeholah,  even  unto  the place that is  beyond Jokneam:",
      "13": "The son of Geber, in Ramothgilead; to him  pertained  the towns of Jair the son of Manasseh, which  are  in Gilead; to him  also pertained  the region of Argob, which  is  in Bashan, threescore great cities with walls and brasen bars: ",
      "14": "Ahinadab the son of Iddo  had  Mahanaim: ",
      "15": "Ahimaaz  was  in Naphtali; he also took Basmath the daughter of Solomon to wife:",
      "16": "Baanah the son of Hushai  was  in Asher and in Aloth:",
      "17": "Jehoshaphat the son of Paruah, in Issachar:",
      "18": "Shimei the son of Elah, in Benjamin:",
      "19": "Geber the son of Uri  was  in the country of Gilead,  in  the country of Sihon king of the Amorites, and of Og king of Bashan; and  he was  the only officer which  was  in the land. ",
      "20": "Judah and Israel  were  many, as the sand which  is  by the sea in multitude, eating and drinking, and making merry.",
      "21": "And Solomon reigned over all kingdoms from the river unto the land of the Philistines, and unto the border of Egypt: they brought presents, and served Solomon all the days of his life.",
      "22": "And Solomon's provision for one day was thirty measures of fine flour, and threescore measures of meal,  ",
      "23": "Ten fat oxen, and twenty oxen out of the pastures, and an hundred sheep, beside harts, and roebucks, and fallowdeer, and fatted fowl.",
      "24": "For he had dominion over all  the region  on this side the river, from Tiphsah even to Azzah, over all the kings on this side the river: and he had peace on all sides round about him.",
      "25": "And Judah and Israel dwelt safely, every man under his vine and under his fig tree, from Dan even to Beersheba, all the days of Solomon. ",
      "26": "And Solomon had forty thousand stalls of horses for his chariots, and twelve thousand horsemen.",
      "27": "And those officers provided victual for king Solomon, and for all that came unto king Solomon's table, every man in his month: they lacked nothing.",
      "28": "Barley also and straw for the horses and dromedaries brought they unto the place where  the officers  were, every man according to his charge.  ",
      "29": "And God gave Solomon wisdom and understanding exceeding much, and largeness of heart, even as the sand that  is  on the sea shore.",
      "30": "And Solomon's wisdom excelled the wisdom of all the children of the east country, and all the wisdom of Egypt.",
      "31": "For he was wiser than all men; than Ethan the Ezrahite, and Heman, and Chalcol, and Darda, the sons of Mahol: and his fame was in all nations round about.",
      "32": "And he spake three thousand proverbs: and his songs were a thousand and five.",
      "33": "And he spake of trees, from the cedar tree that  is  in Lebanon even unto the hyssop that springeth out of the wall: he spake also of beasts, and of fowl, and of creeping things, and of fishes.",
      "34": "And there came of all people to hear the wisdom of Solomon, from all kings of the earth, which had heard of his wisdom. "
    },
    "5": {
      "1": "And Hiram king of Tyre sent his servants unto Solomon; for he had heard that they had anointed him king in the room of his father: for Hiram was ever a lover of David.",
      "2": "And Solomon sent to Hiram, saying,",
      "3": "Thou knowest how that David my father could not build an house unto the name of the LORD his God for the wars which were about him on every side, until the LORD put them under the soles of his feet.",
      "4": "But now the LORD my God hath given me rest on every side,  so that there is  neither adversary nor evil occurrent.",
      "5": "And, behold, I purpose to build an house unto the name of the LORD my God, as the LORD spake unto David my father, saying, Thy son, whom I will set upon thy throne in thy room, he shall build an house unto my name. ",
      "6": "Now therefore command thou that they hew me cedar trees out of Lebanon; and my servants shall be with thy servants: and unto thee will I give hire for thy servants according to all that thou shalt appoint: for thou knowest that  there is  not among us any that can skill to hew timber like unto the Sidonians. ",
      "7": "And it came to pass, when Hiram heard the words of Solomon, that he rejoiced greatly, and said, Blessed  be  the LORD this day, which hath given unto David a wise son over this great people.",
      "8": "And Hiram sent to Solomon, saying, I have considered the things which thou sentest to me for:  and  I will do all thy desire concerning timber of cedar, and concerning timber of fir. ",
      "9": "My servants shall bring  them  down from Lebanon unto the sea: and I will convey them by sea in floats unto the place that thou shalt appoint me, and will cause them to be discharged there, and thou shalt receive  them : and thou shalt accomplish my desire, in giving food for my household.  ",
      "10": "So Hiram gave Solomon cedar trees and fir trees  according to  all his desire.",
      "11": "And Solomon gave Hiram twenty thousand measures of wheat  for  food to his household, and twenty measures of pure oil: thus gave Solomon to Hiram year by year. ",
      "12": "And the LORD gave Solomon wisdom, as he promised him: and there was peace between Hiram and Solomon; and they two made a league together.",
      "13": "And king Solomon raised a levy out of all Israel; and the levy was thirty thousand men. ",
      "14": "And he sent them to Lebanon, ten thousand a month by courses: a month they were in Lebanon,  and  two months at home: and Adoniram  was  over the levy.",
      "15": "And Solomon had threescore and ten thousand that bare burdens, and fourscore thousand hewers in the mountains;",
      "16": "Beside the chief of Solomon's officers which  were  over the work, three thousand and three hundred, which ruled over the people that wrought in the work.",
      "17": "And the king commanded, and they brought great stones, costly stones,  and  hewed stones, to lay the foundation of the house.",
      "18": "And Solomon's builders and Hiram's builders did hew  them , and the stonesquarers: so they prepared timber and stones to build the house.  "
    },
    "6": {
      "1": "And it came to pass in the four hundred and eightieth year after the children of Israel were come out of the land of Egypt, in the fourth year of Solomon's reign over Israel, in the month Zif, which  is  the second month, that he began to build the house of the LORD. ",
      "2": "And the house which king Solomon built for the LORD, the length thereof  was  threescore cubits, and the breadth thereof twenty  cubits , and the height thereof thirty cubits.",
      "3": "And the porch before the temple of the house, twenty cubits  was  the length thereof, according to the breadth of the house;  and  ten cubits  was  the breadth thereof before the house.",
      "4": "And for the house he made windows of narrow lights. ",
      "5": "And against the wall of the house he built chambers round about,  against  the walls of the house round about,  both  of the temple and of the oracle: and he made chambers round about:   ",
      "6": "The nethermost chamber  was  five cubits broad, and the middle  was  six cubits broad, and the third  was  seven cubits broad: for without  in the wall  of the house he made narrowed rests round about, that  the beams  should not be fastened in the walls of the house. ",
      "7": "And the house, when it was in building, was built of stone made ready before it was brought thither: so that there was neither hammer nor axe  nor  any tool of iron heard in the house, while it was in building.",
      "8": "The door for the middle chamber  was  in the right side of the house: and they went up with winding stairs into the middle  chamber , and out of the middle into the third. ",
      "9": "So he built the house, and finished it; and covered the house with beams and boards of cedar. ",
      "10": "And  then  he built chambers against all the house, five cubits high: and they rested on the house  with  timber of cedar. ",
      "11": "And the word of the LORD came to Solomon, saying,",
      "12": " Concerning  this house which thou art in building, if thou wilt walk in my statutes, and execute my judgments, and keep all my commandments to walk in them; then will I perform my word with thee, which I spake unto David thy father:",
      "13": "And I will dwell among the children of Israel, and will not forsake my people Israel.",
      "14": "So Solomon built the house, and finished it. ",
      "15": "And he built the walls of the house within with boards of cedar, both the floor of the house, and the walls of the cieling:  and  he covered  them  on the inside with wood, and covered the floor of the house with planks of fir. ",
      "16": "And he built twenty cubits on the sides of the house, both the floor and the walls with boards of cedar: he even built  them  for it within,  even  for the oracle,  even  for the most holy  place .",
      "17": "And the house, that  is , the temple before it, was forty cubits  long .",
      "18": "And the cedar of the house within  was  carved with knops and open flowers: all  was  cedar; there was no stone seen.  ",
      "19": "And the oracle he prepared in the house within, to set there the ark of the covenant of the LORD.",
      "20": "And the oracle in the forepart  was  twenty cubits in length, and twenty cubits in breadth, and twenty cubits in the height thereof: and he overlaid it with pure gold; and  so  covered the altar  which was of  cedar. ",
      "21": "So Solomon overlaid the house within with pure gold: and he made a partition by the chains of gold before the oracle; and he overlaid it with gold.",
      "22": "And the whole house he overlaid with gold, until he had finished all the house: also the whole altar that  was  by the oracle he overlaid with gold.",
      "23": "And within the oracle he made two cherubims  of  olive tree,  each  ten cubits high. ",
      "24": "And five cubits  was  the one wing of the cherub, and five cubits the other wing of the cherub: from the uttermost part of the one wing unto the uttermost part of the other  were  ten cubits.",
      "25": "And the other cherub  was  ten cubits: both the cherubims  were  of one measure and one size.",
      "26": "The height of the one cherub  was  ten cubits, and so  was it  of the other cherub.",
      "27": "And he set the cherubims within the inner house: and they stretched forth the wings of the cherubims, so that the wing of the one touched the  one  wall, and the wing of the other cherub touched the other wall; and their wings touched one another in the midst of the house. ",
      "28": "And he overlaid the cherubims with gold.",
      "29": "And he carved all the walls of the house round about with carved figures of cherubims and palm trees and open flowers, within and without. ",
      "30": "And the floor of the house he overlaid with gold, within and without.",
      "31": "And for the entering of the oracle he made doors  of  olive tree: the lintel  and  side posts  were  a fifth part  of the wall . ",
      "32": "The two doors also  were of  olive tree; and he carved upon them carvings of cherubims and palm trees and open flowers, and overlaid  them  with gold, and spread gold upon the cherubims, and upon the palm trees.  ",
      "33": "So also made he for the door of the temple posts  of  olive tree, a fourth part  of the wall . ",
      "34": "And the two doors  were of  fir tree: the two leaves of the one door  were  folding, and the two leaves of the other door  were  folding.",
      "35": "And he carved  thereon  cherubims and palm trees and open flowers: and covered  them  with gold fitted upon the carved work.",
      "36": "And he built the inner court with three rows of hewed stone, and a row of cedar beams.",
      "37": "In the fourth year was the foundation of the house of the LORD laid, in the month Zif:",
      "38": "And in the eleventh year, in the month Bul, which  is  the eighth month, was the house finished throughout all the parts thereof, and according to all the fashion of it. So was he seven years in building it.  "
    },
    "7": {
      "1": "But Solomon was building his own house thirteen years, and he finished all his house.",
      "2": "He built also the house of the forest of Lebanon; the length thereof  was  an hundred cubits, and the breadth thereof fifty cubits, and the height thereof thirty cubits, upon four rows of cedar pillars, with cedar beams upon the pillars.",
      "3": "And  it was  covered with cedar above upon the beams, that  lay  on forty five pillars, fifteen  in  a row. ",
      "4": "And  there were  windows  in  three rows, and light  was  against light  in  three ranks. ",
      "5": "And all the doors and posts  were  square, with the windows: and light  was  against light  in  three ranks. ",
      "6": "And he made a porch of pillars; the length thereof  was  fifty cubits, and the breadth thereof thirty cubits: and the porch  was  before them: and the  other  pillars and the thick beam  were  before them. ",
      "7": "Then he made a porch for the throne where he might judge,  even  the porch of judgment: and  it was  covered with cedar from one side of the floor to the other. ",
      "8": "And his house where he dwelt  had  another court within the porch,  which  was of the like work. Solomon made also an house for Pharaoh's daughter, whom he had taken  to wife , like unto this porch.",
      "9": "All these  were of  costly stones, according to the measures of hewed stones, sawed with saws, within and without, even from the foundation unto the coping, and  so  on the outside toward the great court.",
      "10": "And the foundation  was of  costly stones, even great stones, stones of ten cubits, and stones of eight cubits.",
      "11": "And above  were  costly stones, after the measures of hewed stones, and cedars.",
      "12": "And the great court round about  was  with three rows of hewed stones, and a row of cedar beams, both for the inner court of the house of the LORD, and for the porch of the house. ",
      "13": "And king Solomon sent and fetched Hiram out of Tyre.",
      "14": "He  was  a widow's son of the tribe of Naphtali, and his father  was  a man of Tyre, a worker in brass: and he was filled with wisdom, and understanding, and cunning to work all works in brass. And he came to king Solomon, and wrought all his work. ",
      "15": "For he cast two pillars of brass, of eighteen cubits high apiece: and a line of twelve cubits did compass either of them about. ",
      "16": "And he made two chapiters  of  molten brass, to set upon the tops of the pillars: the height of the one chapiter  was  five cubits, and the height of the other chapiter  was  five cubits:",
      "17": " And  nets of checker work, and wreaths of chain work, for the chapiters which  were  upon the top of the pillars; seven for the one chapiter, and seven for the other chapiter.",
      "18": "And he made the pillars, and two rows round about upon the one network, to cover the chapiters that  were  upon the top, with pomegranates: and so did he for the other chapiter.",
      "19": "And the chapiters that  were  upon the top of the pillars  were  of lily work in the porch, four cubits.",
      "20": "And the chapiters upon the two pillars  had pomegranates  also above, over against the belly which  was  by the network: and the pomegranates  were  two hundred in rows round about upon the other chapiter.",
      "21": "And he set up the pillars in the porch of the temple: and he set up the right pillar, and called the name thereof Jachin: and he set up the left pillar, and called the name thereof Boaz.  ",
      "22": "And upon the top of the pillars  was  lily work: so was the work of the pillars finished.",
      "23": "And he made a molten sea, ten cubits from the one brim to the other:  it was  round all about, and his height  was  five cubits: and a line of thirty cubits did compass it round about. ",
      "24": "And under the brim of it round about  there were  knops compassing it, ten in a cubit, compassing the sea round about: the knops  were  cast in two rows, when it was cast.",
      "25": "It stood upon twelve oxen, three looking toward the north, and three looking toward the west, and three looking toward the south, and three looking toward the east: and the sea  was set  above upon them, and all their hinder parts  were  inward.",
      "26": "And it  was  an hand breadth thick, and the brim thereof was wrought like the brim of a cup, with flowers of lilies: it contained two thousand baths.",
      "27": "And he made ten bases of brass; four cubits  was  the length of one base, and four cubits the breadth thereof, and three cubits the height of it.",
      "28": "And the work of the bases  was  on this  manner : they had borders, and the borders  were  between the ledges:",
      "29": "And on the borders that  were  between the ledges  were  lions, oxen, and cherubims: and upon the ledges  there was  a base above: and beneath the lions and oxen  were  certain additions made of thin work.",
      "30": "And every base had four brasen wheels, and plates of brass: and the four corners thereof had undersetters: under the laver  were  undersetters molten, at the side of every addition.",
      "31": "And the mouth of it within the chapiter and above  was  a cubit: but the mouth thereof  was  round  after  the work of the base, a cubit and an half: and also upon the mouth of it  were  gravings with their borders, foursquare, not round.",
      "32": "And under the borders  were  four wheels; and the axletrees of the wheels  were joined  to the base: and the height of a wheel  was  a cubit and half a cubit. ",
      "33": "And the work of the wheels  was  like the work of a chariot wheel: their axletrees, and their naves, and their felloes, and their spokes,  were  all molten.",
      "34": "And  there were  four undersetters to the four corners of one base:  and  the undersetters  were  of the very base itself.",
      "35": "And in the top of the base  was there  a round compass of half a cubit high: and on the top of the base the ledges thereof and the borders thereof  were  of the same.",
      "36": "For on the plates of the ledges thereof, and on the borders thereof, he graved cherubims, lions, and palm trees, according to the proportion of every one, and additions round about. ",
      "37": "After this  manner  he made the ten bases: all of them had one casting, one measure,  and  one size.",
      "38": "Then made he ten lavers of brass: one laver contained forty baths:  and  every laver was four cubits:  and  upon every one of the ten bases one laver.",
      "39": "And he put five bases on the right side of the house, and five on the left side of the house: and he set the sea on the right side of the house eastward over against the south. ",
      "40": "And Hiram made the lavers, and the shovels, and the basons. So Hiram made an end of doing all the work that he made king Solomon for the house of the LORD: ",
      "41": "The two pillars, and the  two  bowls of the chapiters that  were  on the top of the two pillars; and the two networks, to cover the two bowls of the chapiters which  were  upon the top of the pillars;",
      "42": "And four hundred pomegranates for the two networks,  even  two rows of pomegranates for one network, to cover the two bowls of the chapiters that  were  upon the pillars; ",
      "43": "And the ten bases, and ten lavers on the bases;",
      "44": "And one sea, and twelve oxen under the sea;",
      "45": "And the pots, and the shovels, and the basons: and all these vessels, which Hiram made to king Solomon for the house of the LORD,  were of  bright brass. ",
      "46": "In the plain of Jordan did the king cast them, in the clay ground between Succoth and Zarthan. ",
      "47": "And Solomon left all the vessels  unweighed , because they were exceeding many: neither was the weight of the brass found out.   ",
      "48": "And Solomon made all the vessels that  pertained  unto the house of the LORD: the altar of gold, and the table of gold, whereupon the shewbread  was ,",
      "49": "And the candlesticks of pure gold, five on the right  side , and five on the left, before the oracle, with the flowers, and the lamps, and the tongs  of  gold,",
      "50": "And the bowls, and the snuffers, and the basons, and the spoons, and the censers  of  pure gold; and the hinges  of  gold,  both  for the doors of the inner house, the most holy  place, and  for the doors of the house,  to wit , of the temple. ",
      "51": "So was ended all the work that king Solomon made for the house of the LORD. And Solomon brought in the things which David his father had dedicated;  even  the silver, and the gold, and the vessels, did he put among the treasures of the house of the LORD.  "
    }
  }
};

