
	
export const bib_verses = {
  "2_kings": {
    "17": {
      "1": "In the twelfth year of Ahaz king of Judah began Hoshea the son of Elah to reign in Samaria over Israel nine years.",
      "2": "And he did  that which was  evil in the sight of the LORD, but not as the kings of Israel that were before him.",
      "3": "Against him came up Shalmaneser king of Assyria; and Hoshea became his servant, and gave him presents.  ",
      "4": "And the king of Assyria found conspiracy in Hoshea: for he had sent messengers to So king of Egypt, and brought no present to the king of Assyria, as  he had done  year by year: therefore the king of Assyria shut him up, and bound him in prison. ",
      "5": "Then the king of Assyria came up throughout all the land, and went up to Samaria, and besieged it three years.",
      "6": "In the ninth year of Hoshea the king of Assyria took Samaria, and carried Israel away into Assyria, and placed them in Halah and in Habor  by  the river of Gozan, and in the cities of the Medes. ",
      "7": "For  so  it was, that the children of Israel had sinned against the LORD their God, which had brought them up out of the land of Egypt, from under the hand of Pharaoh king of Egypt, and had feared other gods,",
      "8": "And walked in the statutes of the heathen, whom the LORD cast out from before the children of Israel, and of the kings of Israel, which they had made.",
      "9": "And the children of Israel did secretly  those  things that  were  not right against the LORD their God, and they built them high places in all their cities, from the tower of the watchmen to the fenced city.",
      "10": "And they set them up images and groves in every high hill, and under every green tree: ",
      "11": "And there they burnt incense in all the high places, as  did  the heathen whom the LORD carried away before them; and wrought wicked things to provoke the LORD to anger:",
      "12": "For they served idols, whereof the LORD had said unto them, Ye shall not do this thing.",
      "13": "Yet the LORD testified against Israel, and against Judah, by all the prophets,  and by  all the seers, saying, Turn ye from your evil ways, and keep my commandments  and  my statutes, according to all the law which I commanded your fathers, and which I sent to you by my servants the prophets. ",
      "14": "Notwithstanding they would not hear, but hardened their necks, like to the neck of their fathers, that did not believe in the LORD their God.",
      "15": "And they rejected his statutes, and his covenant that he made with their fathers, and his testimonies which he testified against them; and they followed vanity, and became vain, and went after the heathen that  were  round about them,  concerning  whom the LORD had charged them, that they should not do like them.",
      "16": "And they left all the commandments of the LORD their God, and made them molten images,  even  two calves, and made a grove, and worshipped all the host of heaven, and served Baal.",
      "17": "And they caused their sons and their daughters to pass through the fire, and used divination and enchantments, and sold themselves to do evil in the sight of the LORD, to provoke him to anger.",
      "18": "Therefore the LORD was very angry with Israel, and removed them out of his sight: there was none left but the tribe of Judah only.",
      "19": "Also Judah kept not the commandments of the LORD their God, but walked in the statutes of Israel which they made.",
      "20": "And the LORD rejected all the seed of Israel, and afflicted them, and delivered them into the hand of spoilers, until he had cast them out of his sight.",
      "21": "For he rent Israel from the house of David; and they made Jeroboam the son of Nebat king: and Jeroboam drave Israel from following the LORD, and made them sin a great sin.",
      "22": "For the children of Israel walked in all the sins of Jeroboam which he did; they departed not from them;",
      "23": "Until the LORD removed Israel out of his sight, as he had said by all his servants the prophets. So was Israel carried away out of their own land to Assyria unto this day. ",
      "24": "And the king of Assyria brought  men  from Babylon, and from Cuthah, and from Ava, and from Hamath, and from Sepharvaim, and placed  them  in the cities of Samaria instead of the children of Israel: and they possessed Samaria, and dwelt in the cities thereof.",
      "25": "And  so  it was at the beginning of their dwelling there,  that  they feared not the LORD: therefore the LORD sent lions among them, which slew  some  of them.",
      "26": "Wherefore they spake to the king of Assyria, saying, The nations which thou hast removed, and placed in the cities of Samaria, know not the manner of the God of the land: therefore he hath sent lions among them, and, behold, they slay them, because they know not the manner of the God of the land.",
      "27": "Then the king of Assyria commanded, saying, Carry thither one of the priests whom ye brought from thence; and let them go and dwell there, and let him teach them the manner of the God of the land.",
      "28": "Then one of the priests whom they had carried away from Samaria came and dwelt in Bethel, and taught them how they should fear the LORD.",
      "29": "Howbeit every nation made gods of their own, and put  them  in the houses of the high places which the Samaritans had made, every nation in their cities wherein they dwelt.",
      "30": "And the men of Babylon made Succothbenoth, and the men of Cuth made Nergal, and the men of Hamath made Ashima,",
      "31": "And the Avites made Nibhaz and Tartak, and the Sepharvites burnt their children in fire to Adrammelech and Anammelech, the gods of Sepharvaim.",
      "32": "So they feared the LORD, and made unto themselves of the lowest of them priests of the high places, which sacrificed for them in the houses of the high places.",
      "33": "They feared the LORD, and served their own gods, after the manner of the nations whom they carried away from thence. ",
      "34": "Unto this day they do after the former manners: they fear not the LORD, neither do they after their statutes, or after their ordinances, or after the law and commandment which the LORD commanded the children of Jacob, whom he named Israel;",
      "35": "With whom the LORD had made a covenant, and charged them, saying, Ye shall not fear other gods, nor bow yourselves to them, nor serve them, nor sacrifice to them:",
      "36": "But the LORD, who brought you up out of the land of Egypt with great power and a stretched out arm, him shall ye fear, and him shall ye worship, and to him shall ye do sacrifice.",
      "37": "And the statutes, and the ordinances, and the law, and the commandment, which he wrote for you, ye shall observe to do for evermore; and ye shall not fear other gods.",
      "38": "And the covenant that I have made with you ye shall not forget; neither shall ye fear other gods.",
      "39": "But the LORD your God ye shall fear; and he shall deliver you out of the hand of all your enemies.",
      "40": "Howbeit they did not hearken, but they did after their former manner.",
      "41": "So these nations feared the LORD, and served their graven images, both their children, and their children's children: as did their fathers, so do they unto this day. "
    },
    "18": {
      "1": "Now it came to pass in the third year of Hoshea son of Elah king of Israel,  that  Hezekiah the son of Ahaz king of Judah began to reign. ",
      "2": "Twenty and five years old was he when he began to reign; and he reigned twenty and nine years in Jerusalem. His mother's name also  was  Abi, the daughter of Zachariah.",
      "3": "And he did  that which was  right in the sight of the LORD, according to all that David his father did.",
      "4": "He removed the high places, and brake the images, and cut down the groves, and brake in pieces the brasen serpent that Moses had made: for unto those days the children of Israel did burn incense to it: and he called it Nehushtan.  ",
      "5": "He trusted in the LORD God of Israel; so that after him was none like him among all the kings of Judah, nor  any  that were before him.",
      "6": "For he clave to the LORD,  and  departed not from following him, but kept his commandments, which the LORD commanded Moses. ",
      "7": "And the LORD was with him;  and  he prospered whithersoever he went forth: and he rebelled against the king of Assyria, and served him not.",
      "8": "He smote the Philistines,  even  unto Gaza, and the borders thereof, from the tower of the watchmen to the fenced city.  ",
      "9": "And it came to pass in the fourth year of king Hezekiah, which  was  the seventh year of Hoshea son of Elah king of Israel,  that  Shalmaneser king of Assyria came up against Samaria, and besieged it.",
      "10": "And at the end of three years they took it:  even  in the sixth year of Hezekiah, that  is  the ninth year of Hoshea king of Israel, Samaria was taken.",
      "11": "And the king of Assyria did carry away Israel unto Assyria, and put them in Halah and in Habor  by  the river of Gozan, and in the cities of the Medes:",
      "12": "Because they obeyed not the voice of the LORD their God, but transgressed his covenant,  and  all that Moses the servant of the LORD commanded, and would not hear  them , nor do  them .",
      "13": "Now in the fourteenth year of king Hezekiah did Sennacherib king of Assyria come up against all the fenced cities of Judah, and took them. ",
      "14": "And Hezekiah king of Judah sent to the king of Assyria to Lachish, saying, I have offended; return from me: that which thou puttest on me will I bear. And the king of Assyria appointed unto Hezekiah king of Judah three hundred talents of silver and thirty talents of gold.",
      "15": "And Hezekiah gave  him  all the silver that was found in the house of the LORD, and in the treasures of the king's house.",
      "16": "At that time did Hezekiah cut off  the gold from  the doors of the temple of the LORD, and  from  the pillars which Hezekiah king of Judah had overlaid, and gave it to the king of Assyria.  ",
      "17": "And the king of Assyria sent Tartan and Rabsaris and Rabshakeh from Lachish to king Hezekiah with a great host against Jerusalem. And they went up and came to Jerusalem. And when they were come up, they came and stood by the conduit of the upper pool, which  is  in the highway of the fuller's field. ",
      "18": "And when they had called to the king, there came out to them Eliakim the son of Hilkiah, which  was  over the household, and Shebna the scribe, and Joah the son of Asaph the recorder. ",
      "19": "And Rabshakeh said unto them, Speak ye now to Hezekiah, Thus saith the great king, the king of Assyria, What confidence  is  this wherein thou trustest?",
      "20": "Thou sayest, (but  they are but  vain words,)  I have  counsel and strength for the war. Now on whom dost thou trust, that thou rebellest against me?   ",
      "21": "Now, behold, thou trustest upon the staff of this bruised reed,  even  upon Egypt, on which if a man lean, it will go into his hand, and pierce it: so  is  Pharaoh king of Egypt unto all that trust on him. ",
      "22": "But if ye say unto me, We trust in the LORD our God:  is  not that he, whose high places and whose altars Hezekiah hath taken away, and hath said to Judah and Jerusalem, Ye shall worship before this altar in Jerusalem?",
      "23": "Now therefore, I pray thee, give pledges to my lord the king of Assyria, and I will deliver thee two thousand horses, if thou be able on thy part to set riders upon them. ",
      "24": "How then wilt thou turn away the face of one captain of the least of my master's servants, and put thy trust on Egypt for chariots and for horsemen?",
      "25": "Am I now come up without the LORD against this place to destroy it? The LORD said to me, Go up against this land, and destroy it.",
      "26": "Then said Eliakim the son of Hilkiah, and Shebna, and Joah, unto Rabshakeh, Speak, I pray thee, to thy servants in the Syrian language; for we understand  it : and talk not with us in the Jews' language in the ears of the people that  are  on the wall.",
      "27": "But Rabshakeh said unto them, Hath my master sent me to thy master, and to thee, to speak these words?  hath he  not  sent me  to the men which sit on the wall, that they may eat their own dung, and drink their own piss with you? ",
      "28": "Then Rabshakeh stood and cried with a loud voice in the Jews' language, and spake, saying, Hear the word of the great king, the king of Assyria:",
      "29": "Thus saith the king, Let not Hezekiah deceive you: for he shall not be able to deliver you out of his hand:",
      "30": "Neither let Hezekiah make you trust in the LORD, saying, The LORD will surely deliver us, and this city shall not be delivered into the hand of the king of Assyria.",
      "31": "Hearken not to Hezekiah: for thus saith the king of Assyria, Make  an agreement  with me by a present, and come out to me, and  then  eat ye every man of his own vine, and every one of his fig tree, and drink ye every one the waters of his cistern:  ",
      "32": "Until I come and take you away to a land like your own land, a land of corn and wine, a land of bread and vineyards, a land of oil olive and of honey, that ye may live, and not die: and hearken not unto Hezekiah, when he persuadeth you, saying, The LORD will deliver us. ",
      "33": "Hath any of the gods of the nations delivered at all his land out of the hand of the king of Assyria?",
      "34": "Where  are  the gods of Hamath, and of Arpad? where  are  the gods of Sepharvaim, Hena, and Ivah? have they delivered Samaria out of mine hand?",
      "35": "Who  are  they among all the gods of the countries, that have delivered their country out of mine hand, that the LORD should deliver Jerusalem out of mine hand?",
      "36": "But the people held their peace, and answered him not a word: for the king's commandment was, saying, Answer him not.",
      "37": "Then came Eliakim the son of Hilkiah, which  was  over the household, and Shebna the scribe, and Joah the son of Asaph the recorder, to Hezekiah with  their  clothes rent, and told him the words of Rabshakeh. "
    },
    "19": {
      "1": "And it came to pass, when king Hezekiah heard  it , that he rent his clothes, and covered himself with sackcloth, and went into the house of the LORD.",
      "2": "And he sent Eliakim, which  was  over the household, and Shebna the scribe, and the elders of the priests, covered with sackcloth, to Isaiah the prophet the son of Amoz.",
      "3": "And they said unto him, Thus saith Hezekiah, This day  is  a day of trouble, and of rebuke, and blasphemy: for the children are come to the birth, and  there is  not strength to bring forth. ",
      "4": "It may be the LORD thy God will hear all the words of Rabshakeh, whom the king of Assyria his master hath sent to reproach the living God; and will reprove the words which the LORD thy God hath heard: wherefore lift up  thy  prayer for the remnant that are left. ",
      "5": "So the servants of king Hezekiah came to Isaiah.",
      "6": "And Isaiah said unto them, Thus shall ye say to your master, Thus saith the LORD, Be not afraid of the words which thou hast heard, with which the servants of the king of Assyria have blasphemed me.",
      "7": "Behold, I will send a blast upon him, and he shall hear a rumour, and shall return to his own land; and I will cause him to fall by the sword in his own land. ",
      "8": "So Rabshakeh returned, and found the king of Assyria warring against Libnah: for he had heard that he was departed from Lachish.",
      "9": "And when he heard say of Tirhakah king of Ethiopia, Behold, he is come out to fight against thee: he sent messengers again unto Hezekiah, saying,",
      "10": "Thus shall ye speak to Hezekiah king of Judah, saying, Let not thy God in whom thou trustest deceive thee, saying, Jerusalem shall not be delivered into the hand of the king of Assyria.",
      "11": "Behold, thou hast heard what the kings of Assyria have done to all lands, by destroying them utterly: and shalt thou be delivered?",
      "12": "Have the gods of the nations delivered them which my fathers have destroyed;  as  Gozan, and Haran, and Rezeph, and the children of Eden which  were  in Thelasar?",
      "13": "Where  is  the king of Hamath, and the king of Arpad, and the king of the city of Sepharvaim, of Hena, and Ivah?",
      "14": "And Hezekiah received the letter of the hand of the messengers, and read it: and Hezekiah went up into the house of the LORD, and spread it before the LORD.",
      "15": "And Hezekiah prayed before the LORD, and said, O LORD God of Israel, which dwellest  between  the cherubims, thou art the God,  even  thou alone, of all the kingdoms of the earth; thou hast made heaven and earth.",
      "16": "LORD, bow down thine ear, and hear: open, LORD, thine eyes, and see: and hear the words of Sennacherib, which hath sent him to reproach the living God.",
      "17": "Of a truth, LORD, the kings of Assyria have destroyed the nations and their lands,",
      "18": "And have cast their gods into the fire: for they  were  no gods, but the work of men's hands, wood and stone: therefore they have destroyed them. ",
      "19": "Now therefore, O LORD our God, I beseech thee, save thou us out of his hand, that all the kingdoms of the earth may know that thou  art  the LORD God,  even  thou only. ",
      "20": "Then Isaiah the son of Amoz sent to Hezekiah, saying, Thus saith the LORD God of Israel,  That  which thou hast prayed to me against Sennacherib king of Assyria I have heard.",
      "21": "This  is  the word that the LORD hath spoken concerning him; The virgin the daughter of Zion hath despised thee,  and  laughed thee to scorn; the daughter of Jerusalem hath shaken her head at thee.",
      "22": "Whom hast thou reproached and blasphemed? and against whom hast thou exalted  thy  voice, and lifted up thine eyes on high?  even  against the Holy  One  of Israel.",
      "23": "By thy messengers thou hast reproached the Lord, and hast said, With the multitude of my chariots I am come up to the height of the mountains, to the sides of Lebanon, and will cut down the tall cedar trees thereof,  and  the choice fir trees thereof: and I will enter into the lodgings of his borders,  and into  the forest of his Carmel.   ",
      "24": "I have digged and drunk strange waters, and with the sole of my feet have I dried up all the rivers of besieged places. ",
      "25": "Hast thou not heard long ago  how  I have done it,  and  of ancient times that I have formed it? now have I brought it to pass, that thou shouldest be to lay waste fenced cities  into  ruinous heaps. ",
      "26": "Therefore their inhabitants were of small power, they were dismayed and confounded; they were  as  the grass of the field, and  as  the green herb,  as  the grass on the housetops, and  as corn  blasted before it be grown up. ",
      "27": "But I know thy abode, and thy going out, and thy coming in, and thy rage against me. ",
      "28": "Because thy rage against me and thy tumult is come up into mine ears, therefore I will put my hook in thy nose, and my bridle in thy lips, and I will turn thee back by the way by which thou camest.",
      "29": "And this  shall be  a sign unto thee, Ye shall eat this year such things as grow of themselves, and in the second year that which springeth of the same; and in the third year sow ye, and reap, and plant vineyards, and eat the fruits thereof.",
      "30": "And the remnant that is escaped of the house of Judah shall yet again take root downward, and bear fruit upward. ",
      "31": "For out of Jerusalem shall go forth a remnant, and they that escape out of mount Zion: the zeal of the LORD  of hosts  shall do this. ",
      "32": "Therefore thus saith the LORD concerning the king of Assyria, He shall not come into this city, nor shoot an arrow there, nor come before it with shield, nor cast a bank against it.",
      "33": "By the way that he came, by the same shall he return, and shall not come into this city, saith the LORD.",
      "34": "For I will defend this city, to save it, for mine own sake, and for my servant David's sake. ",
      "35": "And it came to pass that night, that the angel of the LORD went out, and smote in the camp of the Assyrians an hundred fourscore and five thousand: and when they arose early in the morning, behold, they  were  all dead corpses.",
      "36": "So Sennacherib king of Assyria departed, and went and returned, and dwelt at Nineveh.",
      "37": "And it came to pass, as he was worshipping in the house of Nisroch his god, that Adrammelech and Sharezer his sons smote him with the sword: and they escaped into the land of Armenia. And Esarhaddon his son reigned in his stead.  "
    },
    "20": {
      "1": "In those days was Hezekiah sick unto death. And the prophet Isaiah the son of Amoz came to him, and said unto him, Thus saith the LORD, Set thine house in order; for thou shalt die, and not live. ",
      "2": "Then he turned his face to the wall, and prayed unto the LORD, saying,",
      "3": "I beseech thee, O LORD, remember now how I have walked before thee in truth and with a perfect heart, and have done  that which is  good in thy sight. And Hezekiah wept sore. ",
      "4": "And it came to pass, afore Isaiah was gone out into the middle court, that the word of the LORD came to him, saying, ",
      "5": "Turn again, and tell Hezekiah the captain of my people, Thus saith the LORD, the God of David thy father, I have heard thy prayer, I have seen thy tears: behold, I will heal thee: on the third day thou shalt go up unto the house of the LORD.",
      "6": "And I will add unto thy days fifteen years; and I will deliver thee and this city out of the hand of the king of Assyria; and I will defend this city for mine own sake, and for my servant David's sake.",
      "7": "And Isaiah said, Take a lump of figs. And they took and laid  it  on the boil, and he recovered.",
      "8": "And Hezekiah said unto Isaiah, What  shall be  the sign that the LORD will heal me, and that I shall go up into the house of the LORD the third day?",
      "9": "And Isaiah said, This sign shalt thou have of the LORD, that the LORD will do the thing that he hath spoken: shall the shadow go forward ten degrees, or go back ten degrees?",
      "10": "And Hezekiah answered, It is a light thing for the shadow to go down ten degrees: nay, but let the shadow return backward ten degrees.",
      "11": "And Isaiah the prophet cried unto the LORD: and he brought the shadow ten degrees backward, by which it had gone down in the dial of Ahaz.  ",
      "12": "At that time Berodachbaladan, the son of Baladan, king of Babylon, sent letters and a present unto Hezekiah: for he had heard that Hezekiah had been sick. ",
      "13": "And Hezekiah hearkened unto them, and shewed them all the house of his precious things, the silver, and the gold, and the spices, and the precious ointment, and  all  the house of his armour, and all that was found in his treasures: there was nothing in his house, nor in all his dominion, that Hezekiah shewed them not.  ",
      "14": "Then came Isaiah the prophet unto king Hezekiah, and said unto him, What said these men? and from whence came they unto thee? And Hezekiah said, They are come from a far country,  even  from Babylon.",
      "15": "And he said, What have they seen in thine house? And Hezekiah answered, All  the things  that  are  in mine house have they seen: there is nothing among my treasures that I have not shewed them.",
      "16": "And Isaiah said unto Hezekiah, Hear the word of the LORD.",
      "17": "Behold, the days come, that all that  is  in thine house, and that which thy fathers have laid up in store unto this day, shall be carried into Babylon: nothing shall be left, saith the LORD.",
      "18": "And of thy sons that shall issue from thee, which thou shalt beget, shall they take away; and they shall be eunuchs in the palace of the king of Babylon.",
      "19": "Then said Hezekiah unto Isaiah, Good  is  the word of the LORD which thou hast spoken. And he said,  Is it  not  good , if peace and truth be in my days? ",
      "20": "And the rest of the acts of Hezekiah, and all his might, and how he made a pool, and a conduit, and brought water into the city,  are  they not written in the book of the chronicles of the kings of Judah?",
      "21": "And Hezekiah slept with his fathers: and Manasseh his son reigned in his stead. "
    },
    "21": {
      "1": "Manasseh  was  twelve years old when he began to reign, and reigned fifty and five years in Jerusalem. And his mother's name  was  Hephzibah.",
      "2": "And he did  that which was  evil in the sight of the LORD, after the abominations of the heathen, whom the LORD cast out before the children of Israel.",
      "3": "For he built up again the high places which Hezekiah his father had destroyed; and he reared up altars for Baal, and made a grove, as did Ahab king of Israel; and worshipped all the host of heaven, and served them.",
      "4": "And he built altars in the house of the LORD, of which the LORD said, In Jerusalem will I put my name.",
      "5": "And he built altars for all the host of heaven in the two courts of the house of the LORD.",
      "6": "And he made his son pass through the fire, and observed times, and used enchantments, and dealt with familiar spirits and wizards: he wrought much wickedness in the sight of the LORD, to provoke  him  to anger.",
      "7": "And he set a graven image of the grove that he had made in the house, of which the LORD said to David, and to Solomon his son, In this house, and in Jerusalem, which I have chosen out of all tribes of Israel, will I put my name for ever:",
      "8": "Neither will I make the feet of Israel move any more out of the land which I gave their fathers; only if they will observe to do according to all that I have commanded them, and according to all the law that my servant Moses commanded them.",
      "9": "But they hearkened not: and Manasseh seduced them to do more evil than did the nations whom the LORD destroyed before the children of Israel. ",
      "10": "And the LORD spake by his servants the prophets, saying,",
      "11": "Because Manasseh king of Judah hath done these abominations,  and  hath done wickedly above all that the Amorites did, which  were  before him, and hath made Judah also to sin with his idols:",
      "12": "Therefore thus saith the LORD God of Israel, Behold, I  am  bringing  such  evil upon Jerusalem and Judah, that whosoever heareth of it, both his ears shall tingle.",
      "13": "And I will stretch over Jerusalem the line of Samaria, and the plummet of the house of Ahab: and I will wipe Jerusalem as  a man  wipeth a dish, wiping  it , and turning  it  upside down. ",
      "14": "And I will forsake the remnant of mine inheritance, and deliver them into the hand of their enemies; and they shall become a prey and a spoil to all their enemies;",
      "15": "Because they have done  that which was  evil in my sight, and have provoked me to anger, since the day their fathers came forth out of Egypt, even unto this day.",
      "16": "Moreover Manasseh shed innocent blood very much, till he had filled Jerusalem from one end to another; beside his sin wherewith he made Judah to sin, in doing  that which was  evil in the sight of the LORD. ",
      "17": "Now the rest of the acts of Manasseh, and all that he did, and his sin that he sinned,  are  they not written in the book of the chronicles of the kings of Judah?",
      "18": "And Manasseh slept with his fathers, and was buried in the garden of his own house, in the garden of Uzza: and Amon his son reigned in his stead. ",
      "19": "Amon  was  twenty and two years old when he began to reign, and he reigned two years in Jerusalem. And his mother's name  was  Meshullemeth, the daughter of Haruz of Jotbah.",
      "20": "And he did  that which was  evil in the sight of the LORD, as his father Manasseh did.",
      "21": "And he walked in all the way that his father walked in, and served the idols that his father served, and worshipped them:",
      "22": "And he forsook the LORD God of his fathers, and walked not in the way of the LORD.",
      "23": "And the servants of Amon conspired against him, and slew the king in his own house.",
      "24": "And the people of the land slew all them that had conspired against king Amon; and the people of the land made Josiah his son king in his stead.",
      "25": "Now the rest of the acts of Amon which he did,  are  they not written in the book of the chronicles of the kings of Judah?",
      "26": "And he was buried in his sepulchre in the garden of Uzza: and Josiah his son reigned in his stead.  "
    },
    "22": {
      "1": "Josiah  was  eight years old when he began to reign, and he reigned thirty and one years in Jerusalem. And his mother's name  was  Jedidah, the daughter of Adaiah of Boscath.",
      "2": "And he did  that which was  right in the sight of the LORD, and walked in all the way of David his father, and turned not aside to the right hand or to the left.",
      "3": "And it came to pass in the eighteenth year of king Josiah,  that  the king sent Shaphan the son of Azaliah, the son of Meshullam, the scribe, to the house of the LORD, saying,",
      "4": "Go up to Hilkiah the high priest, that he may sum the silver which is brought into the house of the LORD, which the keepers of the door have gathered of the people: ",
      "5": "And let them deliver it into the hand of the doers of the work, that have the oversight of the house of the LORD: and let them give it to the doers of the work which  is  in the house of the LORD, to repair the breaches of the house,",
      "6": "Unto carpenters, and builders, and masons, and to buy timber and hewn stone to repair the house.",
      "7": "Howbeit there was no reckoning made with them of the money that was delivered into their hand, because they dealt faithfully.",
      "8": "And Hilkiah the high priest said unto Shaphan the scribe, I have found the book of the law in the house of the LORD. And Hilkiah gave the book to Shaphan, and he read it.",
      "9": "And Shaphan the scribe came to the king, and brought the king word again, and said, Thy servants have gathered the money that was found in the house, and have delivered it into the hand of them that do the work, that have the oversight of the house of the LORD. ",
      "10": "And Shaphan the scribe shewed the king, saying, Hilkiah the priest hath delivered me a book. And Shaphan read it before the king. ",
      "11": "And it came to pass, when the king had heard the words of the book of the law, that he rent his clothes.",
      "12": "And the king commanded Hilkiah the priest, and Ahikam the son of Shaphan, and Achbor the son of Michaiah, and Shaphan the scribe, and Asahiah a servant of the king's, saying,",
      "13": "Go ye, enquire of the LORD for me, and for the people, and for all Judah, concerning the words of this book that is found: for great  is  the wrath of the LORD that is kindled against us, because our fathers have not hearkened unto the words of this book, to do according unto all that which is written concerning us.",
      "14": "So Hilkiah the priest, and Ahikam, and Achbor, and Shaphan, and Asahiah, went unto Huldah the prophetess, the wife of Shallum the son of Tikvah, the son of Harhas, keeper of the wardrobe; (now she dwelt in Jerusalem in the college;) and they communed with her.  ",
      "15": "And she said unto them, Thus saith the LORD God of Israel, Tell the man that sent you to me,",
      "16": "Thus saith the LORD, Behold, I will bring evil upon this place, and upon the inhabitants thereof,  even  all the words of the book which the king of Judah hath read:",
      "17": "Because they have forsaken me, and have burned incense unto other gods, that they might provoke me to anger with all the works of their hands; therefore my wrath shall be kindled against this place, and shall not be quenched.",
      "18": "But to the king of Judah which sent you to enquire of the LORD, thus shall ye say to him, Thus saith the LORD God of Israel,  As touching  the words which thou hast heard;",
      "19": "Because thine heart was tender, and thou hast humbled thyself before the LORD, when thou heardest what I spake against this place, and against the inhabitants thereof, that they should become a desolation and a curse, and hast rent thy clothes, and wept before me; I also have heard  thee , saith the LORD.",
      "20": "Behold therefore, I will gather thee unto thy fathers, and thou shalt be gathered into thy grave in peace; and thine eyes shall not see all the evil which I will bring upon this place. And they brought the king word again. "
    },
    "23": {
      "1": "And the king sent, and they gathered unto him all the elders of Judah and of Jerusalem.",
      "2": "And the king went up into the house of the LORD, and all the men of Judah and all the inhabitants of Jerusalem with him, and the priests, and the prophets, and all the people, both small and great: and he read in their ears all the words of the book of the covenant which was found in the house of the LORD. ",
      "3": "And the king stood by a pillar, and made a covenant before the LORD, to walk after the LORD, and to keep his commandments and his testimonies and his statutes with all  their  heart and all  their  soul, to perform the words of this covenant that were written in this book. And all the people stood to the covenant. ",
      "4": "And the king commanded Hilkiah the high priest, and the priests of the second order, and the keepers of the door, to bring forth out of the temple of the LORD all the vessels that were made for Baal, and for the grove, and for all the host of heaven: and he burned them without Jerusalem in the fields of Kidron, and carried the ashes of them unto Bethel.",
      "5": "And he put down the idolatrous priests, whom the kings of Judah had ordained to burn incense in the high places in the cities of Judah, and in the places round about Jerusalem; them also that burned incense unto Baal, to the sun, and to the moon, and to the planets, and to all the host of heaven.   ",
      "6": "And he brought out the grove from the house of the LORD, without Jerusalem, unto the brook Kidron, and burned it at the brook Kidron, and stamped  it  small to powder, and cast the powder thereof upon the graves of the children of the people.",
      "7": "And he brake down the houses of the sodomites, that  were  by the house of the LORD, where the women wove hangings for the grove. ",
      "8": "And he brought all the priests out of the cities of Judah, and defiled the high places where the priests had burned incense, from Geba to Beersheba, and brake down the high places of the gates that  were  in the entering in of the gate of Joshua the governor of the city, which  were  on a man's left hand at the gate of the city.",
      "9": "Nevertheless the priests of the high places came not up to the altar of the LORD in Jerusalem, but they did eat of the unleavened bread among their brethren.",
      "10": "And he defiled Topheth, which  is  in the valley of the children of Hinnom, that no man might make his son or his daughter to pass through the fire to Molech.",
      "11": "And he took away the horses that the kings of Judah had given to the sun, at the entering in of the house of the LORD, by the chamber of Nathanmelech the chamberlain, which  was  in the suburbs, and burned the chariots of the sun with fire. ",
      "12": "And the altars that  were  on the top of the upper chamber of Ahaz, which the kings of Judah had made, and the altars which Manasseh had made in the two courts of the house of the LORD, did the king beat down, and brake  them  down from thence, and cast the dust of them into the brook Kidron. ",
      "13": "And the high places that  were  before Jerusalem, which  were  on the right hand of the mount of corruption, which Solomon the king of Israel had builded for Ashtoreth the abomination of the Zidonians, and for Chemosh the abomination of the Moabites, and for Milcom the abomination of the children of Ammon, did the king defile. ",
      "14": "And he brake in pieces the images, and cut down the groves, and filled their places with the bones of men. ",
      "15": "Moreover the altar that  was  at Bethel,  and  the high place which Jeroboam the son of Nebat, who made Israel to sin, had made, both that altar and the high place he brake down, and burned the high place,  and  stamped  it  small to powder, and burned the grove.",
      "16": "And as Josiah turned himself, he spied the sepulchres that  were  there in the mount, and sent, and took the bones out of the sepulchres, and burned  them  upon the altar, and polluted it, according to the word of the LORD which the man of God proclaimed, who proclaimed these words.",
      "17": "Then he said, What title  is  that that I see? And the men of the city told him,  It is  the sepulchre of the man of God, which came from Judah, and proclaimed these things that thou hast done against the altar of Bethel.",
      "18": "And he said, Let him alone; let no man move his bones. So they let his bones alone, with the bones of the prophet that came out of Samaria. ",
      "19": "And all the houses also of the high places that  were  in the cities of Samaria, which the kings of Israel had made to provoke  the LORD  to anger, Josiah took away, and did to them according to all the acts that he had done in Bethel.",
      "20": "And he slew all the priests of the high places that  were  there upon the altars, and burned men's bones upon them, and returned to Jerusalem. ",
      "21": "And the king commanded all the people, saying, Keep the passover unto the LORD your God, as  it is  written in the book of this covenant.",
      "22": "Surely there was not holden such a passover from the days of the judges that judged Israel, nor in all the days of the kings of Israel, nor of the kings of Judah;",
      "23": "But in the eighteenth year of king Josiah,  wherein  this passover was holden to the LORD in Jerusalem.",
      "24": "Moreover the  workers with  familiar spirits, and the wizards, and the images, and the idols, and all the abominations that were spied in the land of Judah and in Jerusalem, did Josiah put away, that he might perform the words of the law which were written in the book that Hilkiah the priest found in the house of the LORD.  ",
      "25": "And like unto him was there no king before him, that turned to the LORD with all his heart, and with all his soul, and with all his might, according to all the law of Moses; neither after him arose there  any  like him.",
      "26": "Notwithstanding the LORD turned not from the fierceness of his great wrath, wherewith his anger was kindled against Judah, because of all the provocations that Manasseh had provoked him withal. ",
      "27": "And the LORD said, I will remove Judah also out of my sight, as I have removed Israel, and will cast off this city Jerusalem which I have chosen, and the house of which I said, My name shall be there.",
      "28": "Now the rest of the acts of Josiah, and all that he did,  are  they not written in the book of the chronicles of the kings of Judah?",
      "29": "In his days Pharaohnechoh king of Egypt went up against the king of Assyria to the river Euphrates: and king Josiah went against him; and he slew him at Megiddo, when he had seen him.",
      "30": "And his servants carried him in a chariot dead from Megiddo, and brought him to Jerusalem, and buried him in his own sepulchre. And the people of the land took Jehoahaz the son of Josiah, and anointed him, and made him king in his father's stead. ",
      "31": "Jehoahaz  was  twenty and three years old when he began to reign; and he reigned three months in Jerusalem. And his mother's name  was  Hamutal, the daughter of Jeremiah of Libnah.",
      "32": "And he did  that which was  evil in the sight of the LORD, according to all that his fathers had done.",
      "33": "And Pharaohnechoh put him in bands at Riblah in the land of Hamath, that he might not reign in Jerusalem; and put the land to a tribute of an hundred talents of silver, and a talent of gold.  ",
      "34": "And Pharaohnechoh made Eliakim the son of Josiah king in the room of Josiah his father, and turned his name to Jehoiakim, and took Jehoahaz away: and he came to Egypt, and died there.",
      "35": "And Jehoiakim gave the silver and the gold to Pharaoh; but he taxed the land to give the money according to the commandment of Pharaoh: he exacted the silver and the gold of the people of the land, of every one according to his taxation, to give  it  unto Pharaohnechoh.",
      "36": "Jehoiakim  was  twenty and five years old when he began to reign; and he reigned eleven years in Jerusalem. And his mother's name  was  Zebudah, the daughter of Pedaiah of Rumah.",
      "37": "And he did  that which was  evil in the sight of the LORD, according to all that his fathers had done. "
    },
    "24": {
      "1": "In his days Nebuchadnezzar king of Babylon came up, and Jehoiakim became his servant three years: then he turned and rebelled against him.",
      "2": "And the LORD sent against him bands of the Chaldees, and bands of the Syrians, and bands of the Moabites, and bands of the children of Ammon, and sent them against Judah to destroy it, according to the word of the LORD, which he spake by his servants the prophets. ",
      "3": "Surely at the commandment of the LORD came  this  upon Judah, to remove  them  out of his sight, for the sins of Manasseh, according to all that he did;",
      "4": "And also for the innocent blood that he shed: for he filled Jerusalem with innocent blood; which the LORD would not pardon.",
      "5": "Now the rest of the acts of Jehoiakim, and all that he did,  are  they not written in the book of the chronicles of the kings of Judah?",
      "6": "So Jehoiakim slept with his fathers: and Jehoiachin his son reigned in his stead.",
      "7": "And the king of Egypt came not again any more out of his land: for the king of Babylon had taken from the river of Egypt unto the river Euphrates all that pertained to the king of Egypt. ",
      "8": "Jehoiachin  was  eighteen years old when he began to reign, and he reigned in Jerusalem three months. And his mother's name  was  Nehushta, the daughter of Elnathan of Jerusalem.",
      "9": "And he did  that which was  evil in the sight of the LORD, according to all that his father had done.",
      "10": "At that time the servants of Nebuchadnezzar king of Babylon came up against Jerusalem, and the city was besieged. ",
      "11": "And Nebuchadnezzar king of Babylon came against the city, and his servants did besiege it.",
      "12": "And Jehoiachin the king of Judah went out to the king of Babylon, he, and his mother, and his servants, and his princes, and his officers: and the king of Babylon took him in the eighth year of his reign.  ",
      "13": "And he carried out thence all the treasures of the house of the LORD, and the treasures of the king's house, and cut in pieces all the vessels of gold which Solomon king of Israel had made in the temple of the LORD, as the LORD had said.",
      "14": "And he carried away all Jerusalem, and all the princes, and all the mighty men of valour,  even  ten thousand captives, and all the craftsmen and smiths: none remained, save the poorest sort of the people of the land.",
      "15": "And he carried away Jehoiachin to Babylon, and the king's mother, and the king's wives, and his officers, and the mighty of the land,  those  carried he into captivity from Jerusalem to Babylon. ",
      "16": "And all the men of might,  even  seven thousand, and craftsmen and smiths a thousand, all  that were  strong  and  apt for war, even them the king of Babylon brought captive to Babylon.",
      "17": "And the king of Babylon made Mattaniah his father's brother king in his stead, and changed his name to Zedekiah.",
      "18": "Zedekiah  was  twenty and one years old when he began to reign, and he reigned eleven years in Jerusalem. And his mother's name  was  Hamutal, the daughter of Jeremiah of Libnah.",
      "19": "And he did  that which was  evil in the sight of the LORD, according to all that Jehoiakim had done.",
      "20": "For through the anger of the LORD it came to pass in Jerusalem and Judah, until he had cast them out from his presence, that Zedekiah rebelled against the king of Babylon. "
    },
    "25": {
      "1": "And it came to pass in the ninth year of his reign, in the tenth month, in the tenth  day  of the month,  that  Nebuchadnezzar king of Babylon came, he, and all his host, against Jerusalem, and pitched against it; and they built forts against it round about.",
      "2": "And the city was besieged unto the eleventh year of king Zedekiah.",
      "3": "And on the ninth  day  of the  fourth  month the famine prevailed in the city, and there was no bread for the people of the land.",
      "4": "And the city was broken up, and all the men of war  fled  by night by the way of the gate between two walls, which  is  by the king's garden: (now the Chaldees  were  against the city round about:) and  the king  went the way toward the plain.",
      "5": "And the army of the Chaldees pursued after the king, and overtook him in the plains of Jericho: and all his army were scattered from him.",
      "6": "So they took the king, and brought him up to the king of Babylon to Riblah; and they gave judgment upon him. ",
      "7": "And they slew the sons of Zedekiah before his eyes, and put out the eyes of Zedekiah, and bound him with fetters of brass, and carried him to Babylon.  ",
      "8": "And in the fifth month, on the seventh  day  of the month, which  is  the nineteenth year of king Nebuchadnezzar king of Babylon, came Nebuzaradan, captain of the guard, a servant of the king of Babylon, unto Jerusalem: ",
      "9": "And he burnt the house of the LORD, and the king's house, and all the houses of Jerusalem, and every great  man's  house burnt he with fire.",
      "10": "And all the army of the Chaldees, that  were with  the captain of the guard, brake down the walls of Jerusalem round about.",
      "11": "Now the rest of the people  that were  left in the city, and the fugitives that fell away to the king of Babylon, with the remnant of the multitude, did Nebuzaradan the captain of the guard carry away. ",
      "12": "But the captain of the guard left of the poor of the land  to be  vinedressers and husbandmen.",
      "13": "And the pillars of brass that  were  in the house of the LORD, and the bases, and the brasen sea that  was  in the house of the LORD, did the Chaldees break in pieces, and carried the brass of them to Babylon.",
      "14": "And the pots, and the shovels, and the snuffers, and the spoons, and all the vessels of brass wherewith they ministered, took they away.",
      "15": "And the firepans, and the bowls,  and  such things as  were  of gold,  in  gold, and of silver,  in  silver, the captain of the guard took away.",
      "16": "The two pillars, one sea, and the bases which Solomon had made for the house of the LORD; the brass of all these vessels was without weight. ",
      "17": "The height of the one pillar  was  eighteen cubits, and the chapiter upon it  was  brass: and the height of the chapiter three cubits; and the wreathen work, and pomegranates upon the chapiter round about, all of brass: and like unto these had the second pillar with wreathen work.",
      "18": "And the captain of the guard took Seraiah the chief priest, and Zephaniah the second priest, and the three keepers of the door: ",
      "19": "And out of the city he took an officer that was set over the men of war, and five men of them that were in the king's presence, which were found in the city, and the principal scribe of the host, which mustered the people of the land, and threescore men of the people of the land  that were  found in the city:   ",
      "20": "And Nebuzaradan captain of the guard took these, and brought them to the king of Babylon to Riblah:",
      "21": "And the king of Babylon smote them, and slew them at Riblah in the land of Hamath. So Judah was carried away out of their land. ",
      "22": "And  as for  the people that remained in the land of Judah, whom Nebuchadnezzar king of Babylon had left, even over them he made Gedaliah the son of Ahikam, the son of Shaphan, ruler.",
      "23": "And when all the captains of the armies, they and their men, heard that the king of Babylon had made Gedaliah governor, there came to Gedaliah to Mizpah, even Ishmael the son of Nethaniah, and Johanan the son of Careah, and Seraiah the son of Tanhumeth the Netophathite, and Jaazaniah the son of a Maachathite, they and their men.",
      "24": "And Gedaliah sware to them, and to their men, and said unto them, Fear not to be the servants of the Chaldees: dwell in the land, and serve the king of Babylon; and it shall be well with you.",
      "25": "But it came to pass in the seventh month, that Ishmael the son of Nethaniah, the son of Elishama, of the seed royal, came, and ten men with him, and smote Gedaliah, that he died, and the Jews and the Chaldees that were with him at Mizpah. ",
      "26": "And all the people, both small and great, and the captains of the armies, arose, and came to Egypt: for they were afraid of the Chaldees.",
      "27": "And it came to pass in the seven and thirtieth year of the captivity of Jehoiachin king of Judah, in the twelfth month, on the seven and twentieth  day  of the month,  that  Evilmerodach king of Babylon in the year that he began to reign did lift up the head of Jehoiachin king of Judah out of prison;",
      "28": "And he spake kindly to him, and set his throne above the throne of the kings that  were  with him in Babylon; ",
      "29": "And changed his prison garments: and he did eat bread continually before him all the days of his life.",
      "30": "And his allowance  was  a continual allowance given him of the king, a daily rate for every day, all the days of his life. "
    }
  },
  "1_chronicles": {
    "1": {
      "1": "Adam, Sheth, Enosh,",
      "2": "Kenan, Mahalaleel, Jered,",
      "3": "Henoch, Methuselah, Lamech,",
      "4": "Noah, Shem, Ham, and Japheth.",
      "5": "The sons of Japheth; Gomer, and Magog, and Madai, and Javan, and Tubal, and Meshech, and Tiras.",
      "6": "And the sons of Gomer; Ashchenaz, and Riphath, and Togarmah. ",
      "7": "And the sons of Javan; Elishah, and Tarshish, Kittim, and Dodanim. ",
      "8": "The sons of Ham; Cush, and Mizraim, Put, and Canaan.",
      "9": "And the sons of Cush; Seba, and Havilah, and Sabta, and Raamah, and Sabtecha. And the sons of Raamah; Sheba, and Dedan.",
      "10": "And Cush begat Nimrod: he began to be mighty upon the earth.",
      "11": "And Mizraim begat Ludim, and Anamim, and Lehabim, and Naphtuhim,",
      "12": "And Pathrusim, and Casluhim, (of whom came the Philistines,) and Caphthorim.",
      "13": "And Canaan begat Zidon his firstborn, and Heth,",
      "14": "The Jebusite also, and the Amorite, and the Girgashite,",
      "15": "And the Hivite, and the Arkite, and the Sinite,",
      "16": "And the Arvadite, and the Zemarite, and the Hamathite.",
      "17": "The sons of Shem; Elam, and Asshur, and Arphaxad, and Lud, and Aram, and Uz, and Hul, and Gether, and Meshech. ",
      "18": "And Arphaxad begat Shelah, and Shelah begat Eber.",
      "19": "And unto Eber were born two sons: the name of the one  was  Peleg; because in his days the earth was divided: and his brother's name  was  Joktan. ",
      "20": "And Joktan begat Almodad, and Sheleph, and Hazarmaveth, and Jerah,",
      "21": "Hadoram also, and Uzal, and Diklah,",
      "22": "And Ebal, and Abimael, and Sheba,",
      "23": "And Ophir, and Havilah, and Jobab. All these  were  the sons of Joktan.",
      "24": "Shem, Arphaxad, Shelah,",
      "25": "Eber, Peleg, Reu,",
      "26": "Serug, Nahor, Terah,",
      "27": "Abram; the same  is  Abraham. ",
      "28": "The sons of Abraham; Isaac, and Ishmael.",
      "29": "These  are  their generations: The firstborn of Ishmael, Nebaioth; then Kedar, and Adbeel, and Mibsam,",
      "30": "Mishma, and Dumah, Massa, Hadad, and Tema,",
      "31": "Jetur, Naphish, and Kedemah. These are the sons of Ishmael.",
      "32": "Now the sons of Keturah, Abraham's concubine: she bare Zimran, and Jokshan, and Medan, and Midian, and Ishbak, and Shuah. And the sons of Jokshan; Sheba, and Dedan.",
      "33": "And the sons of Midian; Ephah, and Epher, and Henoch, and Abida, and Eldaah. All these  are  the sons of Keturah.",
      "34": "And Abraham begat Isaac. The sons of Isaac; Esau and Israel.",
      "35": "The sons of Esau; Eliphaz, Reuel, and Jeush, and Jaalam, and Korah.",
      "36": "The sons of Eliphaz; Teman, and Omar, Zephi, and Gatam, Kenaz, and Timna, and Amalek. ",
      "37": "The sons of Reuel; Nahath, Zerah, Shammah, and Mizzah.",
      "38": "And the sons of Seir; Lotan, and Shobal, and Zibeon, and Anah, and Dishon, and Ezer, and Dishan.",
      "39": "And the sons of Lotan; Hori, and Homam: and Timna  was  Lotan's sister. ",
      "40": "The sons of Shobal; Alian, and Manahath, and Ebal, Shephi, and Onam. And the sons of Zibeon; Aiah, and Anah.",
      "41": "The sons of Anah; Dishon. And the sons of Dishon; Amram, and Eshban, and Ithran, and Cheran. ",
      "42": "The sons of Ezer; Bilhan, and Zavan,  and  Jakan. The sons of Dishan; Uz, and Aran. ",
      "43": "Now these  are  the kings that reigned in the land of Edom before  any  king reigned over the children of Israel; Bela the son of Beor: and the name of his city  was  Dinhabah.",
      "44": "And when Bela was dead, Jobab the son of Zerah of Bozrah reigned in his stead.",
      "45": "And when Jobab was dead, Husham of the land of the Temanites reigned in his stead.",
      "46": "And when Husham was dead, Hadad the son of Bedad, which smote Midian in the field of Moab, reigned in his stead: and the name of his city  was  Avith.",
      "47": "And when Hadad was dead, Samlah of Masrekah reigned in his stead.",
      "48": "And when Samlah was dead, Shaul of Rehoboth by the river reigned in his stead.",
      "49": "And when Shaul was dead, Baalhanan the son of Achbor reigned in his stead.",
      "50": "And when Baalhanan was dead, Hadad reigned in his stead: and the name of his city  was  Pai; and his wife's name  was  Mehetabel, the daughter of Matred, the daughter of Mezahab.  ",
      "51": "Hadad died also. And the dukes of Edom were; duke Timnah, duke Aliah, duke Jetheth,",
      "52": "Duke Aholibamah, duke Elah, duke Pinon,",
      "53": "Duke Kenaz, duke Teman, duke Mibzar,",
      "54": "Duke Magdiel, duke Iram. These  are  the dukes of Edom. "
    },
    "2": {
      "1": "These  are  the sons of Israel; Reuben, Simeon, Levi, and Judah, Issachar, and Zebulun, ",
      "2": "Dan, Joseph, and Benjamin, Naphtali, Gad, and Asher.",
      "3": "The sons of Judah; Er, and Onan, and Shelah:  which  three were born unto him of the daughter of Shua the Canaanitess. And Er, the firstborn of Judah, was evil in the sight of the LORD; and he slew him.",
      "4": "And Tamar his daughter in law bare him Pharez and Zerah. All the sons of Judah  were  five.",
      "5": "The sons of Pharez; Hezron, and Hamul.",
      "6": "And the sons of Zerah; Zimri, and Ethan, and Heman, and Calcol, and Dara: five of them in all.  ",
      "7": "And the sons of Carmi; Achar, the troubler of Israel, who transgressed in the thing accursed. ",
      "8": "And the sons of Ethan; Azariah.",
      "9": "The sons also of Hezron, that were born unto him; Jerahmeel, and Ram, and Chelubai.  ",
      "10": "And Ram begat Amminadab; and Amminadab begat Nahshon, prince of the children of Judah;",
      "11": "And Nahshon begat Salma, and Salma begat Boaz,",
      "12": "And Boaz begat Obed, and Obed begat Jesse,",
      "13": "And Jesse begat his firstborn Eliab, and Abinadab the second, and Shimma the third, ",
      "14": "Nethaneel the fourth, Raddai the fifth,",
      "15": "Ozem the sixth, David the seventh:",
      "16": "Whose sisters  were  Zeruiah, and Abigail. And the sons of Zeruiah; Abishai, and Joab, and Asahel, three.",
      "17": "And Abigail bare Amasa: and the father of Amasa  was  Jether the Ishmeelite. ",
      "18": "And Caleb the son of Hezron begat  children  of Azubah  his  wife, and of Jerioth: her sons  are  these; Jesher, and Shobab, and Ardon.",
      "19": "And when Azubah was dead, Caleb took unto him Ephrath, which bare him Hur.",
      "20": "And Hur begat Uri, and Uri begat Bezaleel.",
      "21": "And afterward Hezron went in to the daughter of Machir the father of Gilead, whom he married when he  was  threescore years old; and she bare him Segub. ",
      "22": "And Segub begat Jair, who had three and twenty cities in the land of Gilead.",
      "23": "And he took Geshur, and Aram, with the towns of Jair, from them, with Kenath, and the towns thereof,  even  threescore cities. All these  belonged to  the sons of Machir the father of Gilead.",
      "24": "And after that Hezron was dead in Calebephratah, then Abiah Hezron's wife bare him Ashur the father of Tekoa.",
      "25": "And the sons of Jerahmeel the firstborn of Hezron were, Ram the firstborn, and Bunah, and Oren, and Ozem,  and  Ahijah.",
      "26": "Jerahmeel had also another wife, whose name  was  Atarah; she  was  the mother of Onam.",
      "27": "And the sons of Ram the firstborn of Jerahmeel were, Maaz, and Jamin, and Eker.",
      "28": "And the sons of Onam were, Shammai, and Jada. And the sons of Shammai; Nadab, and Abishur.",
      "29": "And the name of the wife of Abishur  was  Abihail, and she bare him Ahban, and Molid.",
      "30": "And the sons of Nadab; Seled, and Appaim: but Seled died without children.",
      "31": "And the sons of Appaim; Ishi. And the sons of Ishi; Sheshan. And the children of Sheshan; Ahlai.",
      "32": "And the sons of Jada the brother of Shammai; Jether, and Jonathan: and Jether died without children.",
      "33": "And the sons of Jonathan; Peleth, and Zaza. These were the sons of Jerahmeel.",
      "34": "Now Sheshan had no sons, but daughters. And Sheshan had a servant, an Egyptian, whose name  was  Jarha.",
      "35": "And Sheshan gave his daughter to Jarha his servant to wife; and she bare him Attai.",
      "36": "And Attai begat Nathan, and Nathan begat Zabad,",
      "37": "And Zabad begat Ephlal, and Ephlal begat Obed,",
      "38": "And Obed begat Jehu, and Jehu begat Azariah,",
      "39": "And Azariah begat Helez, and Helez begat Eleasah,",
      "40": "And Eleasah begat Sisamai, and Sisamai begat Shallum,",
      "41": "And Shallum begat Jekamiah, and Jekamiah begat Elishama.",
      "42": "Now the sons of Caleb the brother of Jerahmeel  were , Mesha his firstborn, which was the father of Ziph; and the sons of Mareshah the father of Hebron.",
      "43": "And the sons of Hebron; Korah, and Tappuah, and Rekem, and Shema.",
      "44": "And Shema begat Raham, the father of Jorkoam: and Rekem begat Shammai.",
      "45": "And the son of Shammai  was  Maon: and Maon  was  the father of Bethzur.",
      "46": "And Ephah, Caleb's concubine, bare Haran, and Moza, and Gazez: and Haran begat Gazez.",
      "47": "And the sons of Jahdai; Regem, and Jotham, and Geshan, and Pelet, and Ephah, and Shaaph.",
      "48": "Maachah, Caleb's concubine, bare Sheber, and Tirhanah.",
      "49": "She bare also Shaaph the father of Madmannah, Sheva the father of Machbenah, and the father of Gibea: and the daughter of Caleb  was  Achsah.",
      "50": "These were the sons of Caleb the son of Hur, the firstborn of Ephratah; Shobal the father of Kirjathjearim,",
      "51": "Salma the father of Bethlehem, Hareph the father of Bethgader.",
      "52": "And Shobal the father of Kirjathjearim had sons; Haroeh,  and  half of the Manahethites.  ",
      "53": "And the families of Kirjathjearim; the Ithrites, and the Puhites, and the Shumathites, and the Mishraites; of them came the Zareathites, and the Eshtaulites.",
      "54": "The sons of Salma; Bethlehem, and the Netophathites, Ataroth, the house of Joab, and half of the Manahethites, the Zorites. ",
      "55": "And the families of the scribes which dwelt at Jabez; the Tirathites, the Shimeathites,  and  Suchathites. These  are  the Kenites that came of Hemath, the father of the house of Rechab. "
    },
    "3": {
      "1": "Now these were the sons of David, which were born unto him in Hebron; the firstborn Amnon, of Ahinoam the Jezreelitess; the second Daniel, of Abigail the Carmelitess: ",
      "2": "The third, Absalom the son of Maachah the daughter of Talmai king of Geshur: the fourth, Adonijah the son of Haggith:",
      "3": "The fifth, Shephatiah of Abital: the sixth, Ithream by Eglah his wife.",
      "4": " These  six were born unto him in Hebron; and there he reigned seven years and six months: and in Jerusalem he reigned thirty and three years.",
      "5": "And these were born unto him in Jerusalem; Shimea, and Shobab, and Nathan, and Solomon, four, of Bathshua the daughter of Ammiel:   ",
      "6": "Ibhar also, and Elishama, and Eliphelet, ",
      "7": "And Nogah, and Nepheg, and Japhia,",
      "8": "And Elishama, and Eliada, and Eliphelet, nine. ",
      "9": " These were  all the sons of David, beside the sons of the concubines, and Tamar their sister. ",
      "10": "And Solomon's son  was  Rehoboam, Abia his son, Asa his son, Jehoshaphat his son, ",
      "11": "Joram his son, Ahaziah his son, Joash his son, ",
      "12": "Amaziah his son, Azariah his son, Jotham his son, ",
      "13": "Ahaz his son, Hezekiah his son, Manasseh his son,",
      "14": "Amon his son, Josiah his son.",
      "15": "And the sons of Josiah  were , the firstborn Johanan, the second Jehoiakim, the third Zedekiah, the fourth Shallum.   ",
      "16": "And the sons of Jehoiakim: Jeconiah his son, Zedekiah his son. ",
      "17": "And the sons of Jeconiah; Assir, Salathiel his son, ",
      "18": "Malchiram also, and Pedaiah, and Shenazar, Jecamiah, Hoshama, and Nedabiah.",
      "19": "And the sons of Pedaiah  were , Zerubbabel, and Shimei: and the sons of Zerubbabel; Meshullam, and Hananiah, and Shelomith their sister:",
      "20": "And Hashubah, and Ohel, and Berechiah, and Hasadiah, Jushabhesed, five.",
      "21": "And the sons of Hananiah; Pelatiah, and Jesaiah: the sons of Rephaiah, the sons of Arnan, the sons of Obadiah, the sons of Shechaniah.",
      "22": "And the sons of Shechaniah; Shemaiah: and the sons of Shemaiah; Hattush, and Igeal, and Bariah, and Neariah, and Shaphat, six.",
      "23": "And the sons of Neariah; Elioenai, and Hezekiah, and Azrikam, three. ",
      "24": "And the sons of Elioenai  were , Hodaiah, and Eliashib, and Pelaiah, and Akkub, and Johanan, and Dalaiah, and Anani, seven. "
    },
    "4": {
      "1": "The sons of Judah; Pharez, Hezron, and Carmi, and Hur, and Shobal. ",
      "2": "And Reaiah the son of Shobal begat Jahath; and Jahath begat Ahumai, and Lahad. These  are  the families of the Zorathites. ",
      "3": "And these  were of  the father of Etam; Jezreel, and Ishma, and Idbash: and the name of their sister  was  Hazelelponi:",
      "4": "And Penuel the father of Gedor, and Ezer the father of Hushah. These  are  the sons of Hur, the firstborn of Ephratah, the father of Bethlehem.",
      "5": "And Ashur the father of Tekoa had two wives, Helah and Naarah.",
      "6": "And Naarah bare him Ahuzam, and Hepher, and Temeni, and Haahashtari. These  were  the sons of Naarah.",
      "7": "And the sons of Helah  were , Zereth, and Jezoar, and Ethnan.",
      "8": "And Coz begat Anub, and Zobebah, and the families of Aharhel the son of Harum.",
      "9": "And Jabez was more honourable than his brethren: and his mother called his name Jabez, saying, Because I bare him with sorrow. ",
      "10": "And Jabez called on the God of Israel, saying, Oh that thou wouldest bless me indeed, and enlarge my coast, and that thine hand might be with me, and that thou wouldest keep  me  from evil, that it may not grieve me! And God granted him that which he requested.   ",
      "11": "And Chelub the brother of Shuah begat Mehir, which  was  the father of Eshton.",
      "12": "And Eshton begat Bethrapha, and Paseah, and Tehinnah the father of Irnahash. These  are  the men of Rechah. ",
      "13": "And the sons of Kenaz; Othniel, and Seraiah: and the sons of Othniel; Hathath. ",
      "14": "And Meonothai begat Ophrah: and Seraiah begat Joab, the father of the valley of Charashim; for they were craftsmen.   ",
      "15": "And the sons of Caleb the son of Jephunneh; Iru, Elah, and Naam: and the sons of Elah, even Kenaz. ",
      "16": "And the sons of Jehaleleel; Ziph, and Ziphah, Tiria, and Asareel.",
      "17": "And the sons of Ezra  were , Jether, and Mered, and Epher, and Jalon: and she bare Miriam, and Shammai, and Ishbah the father of Eshtemoa.",
      "18": "And his wife Jehudijah bare Jered the father of Gedor, and Heber the father of Socho, and Jekuthiel the father of Zanoah. And these  are  the sons of Bithiah the daughter of Pharaoh, which Mered took. ",
      "19": "And the sons of  his  wife Hodiah the sister of Naham, the father of Keilah the Garmite, and Eshtemoa the Maachathite. ",
      "20": "And the sons of Shimon  were , Amnon, and Rinnah, Benhanan, and Tilon. And the sons of Ishi  were , Zoheth, and Benzoheth.",
      "21": "The sons of Shelah the son of Judah  were , Er the father of Lecah, and Laadah the father of Mareshah, and the families of the house of them that wrought fine linen, of the house of Ashbea,",
      "22": "And Jokim, and the men of Chozeba, and Joash, and Saraph, who had the dominion in Moab, and Jashubilehem. And  these are  ancient things.",
      "23": "These  were  the potters, and those that dwelt among plants and hedges: there they dwelt with the king for his work. ",
      "24": "The sons of Simeon  were , Nemuel, and Jamin, Jarib, Zerah,  and  Shaul:  ",
      "25": "Shallum his son, Mibsam his son, Mishma his son.",
      "26": "And the sons of Mishma; Hamuel his son, Zacchur his son, Shimei his son.",
      "27": "And Shimei had sixteen sons and six daughters; but his brethren had not many children, neither did all their family multiply, like to the children of Judah. ",
      "28": "And they dwelt at Beersheba, and Moladah, and Hazarshual,",
      "29": "And at Bilhah, and at Ezem, and at Tolad,  ",
      "30": "And at Bethuel, and at Hormah, and at Ziklag,",
      "31": "And at Bethmarcaboth, and Hazarsusim, and at Bethbirei, and at Shaaraim. These  were  their cities unto the reign of David. ",
      "32": "And their villages  were , Etam, and Ain, Rimmon, and Tochen, and Ashan, five cities: ",
      "33": "And all their villages that  were  round about the same cities, unto Baal. These  were  their habitations, and their genealogy.  ",
      "34": "And Meshobab, and Jamlech, and Joshah the son of Amaziah,",
      "35": "And Joel, and Jehu the son of Josibiah, the son of Seraiah, the son of Asiel,",
      "36": "And Elioenai, and Jaakobah, and Jeshohaiah, and Asaiah, and Adiel, and Jesimiel, and Benaiah,",
      "37": "And Ziza the son of Shiphi, the son of Allon, the son of Jedaiah, the son of Shimri, the son of Shemaiah;",
      "38": "These mentioned by  their  names  were  princes in their families: and the house of their fathers increased greatly. ",
      "39": "And they went to the entrance of Gedor,  even  unto the east side of the valley, to seek pasture for their flocks.",
      "40": "And they found fat pasture and good, and the land  was  wide, and quiet, and peaceable; for  they  of Ham had dwelt there of old.",
      "41": "And these written by name came in the days of Hezekiah king of Judah, and smote their tents, and the habitations that were found there, and destroyed them utterly unto this day, and dwelt in their rooms: because  there was  pasture there for their flocks.",
      "42": "And  some  of them,  even  of the sons of Simeon, five hundred men, went to mount Seir, having for their captains Pelatiah, and Neariah, and Rephaiah, and Uzziel, the sons of Ishi.",
      "43": "And they smote the rest of the Amalekites that were escaped, and dwelt there unto this day. "
    },
    "5": {
      "1": "Now the sons of Reuben the firstborn of Israel, (for he  was  the firstborn; but, forasmuch as he defiled his father's bed, his birthright was given unto the sons of Joseph the son of Israel: and the genealogy is not to be reckoned after the birthright.",
      "2": "For Judah prevailed above his brethren, and of him  came  the chief ruler; but the birthright  was  Joseph's:) ",
      "3": "The sons,  I say , of Reuben the firstborn of Israel  were , Hanoch, and Pallu, Hezron, and Carmi.",
      "4": "The sons of Joel; Shemaiah his son, Gog his son, Shimei his son,",
      "5": "Micah his son, Reaia his son, Baal his son,",
      "6": "Beerah his son, whom Tilgathpilneser king of Assyria carried away  captive : he  was  prince of the Reubenites. ",
      "7": "And his brethren by their families, when the genealogy of their generations was reckoned,  were  the chief, Jeiel, and Zechariah,",
      "8": "And Bela the son of Azaz, the son of Shema, the son of Joel, who dwelt in Aroer, even unto Nebo and Baalmeon: ",
      "9": "And eastward he inhabited unto the entering in of the wilderness from the river Euphrates: because their cattle were multiplied in the land of Gilead.",
      "10": "And in the days of Saul they made war with the Hagarites, who fell by their hand: and they dwelt in their tents throughout all the east  land  of Gilead. ",
      "11": "And the children of Gad dwelt over against them, in the land of Bashan unto Salchah:",
      "12": "Joel the chief, and Shapham the next, and Jaanai, and Shaphat in Bashan.",
      "13": "And their brethren of the house of their fathers  were , Michael, and Meshullam, and Sheba, and Jorai, and Jachan, and Zia, and Heber, seven.",
      "14": "These  are  the children of Abihail the son of Huri, the son of Jaroah, the son of Gilead, the son of Michael, the son of Jeshishai, the son of Jahdo, the son of Buz;",
      "15": "Ahi the son of Abdiel, the son of Guni, chief of the house of their fathers.",
      "16": "And they dwelt in Gilead in Bashan, and in her towns, and in all the suburbs of Sharon, upon their borders. ",
      "17": "All these were reckoned by genealogies in the days of Jotham king of Judah, and in the days of Jeroboam king of Israel. ",
      "18": "The sons of Reuben, and the Gadites, and half the tribe of Manasseh, of valiant men, men able to bear buckler and sword, and to shoot with bow, and skilful in war,  were  four and forty thousand seven hundred and threescore, that went out to the war. ",
      "19": "And they made war with the Hagarites, with Jetur, and Nephish, and Nodab.",
      "20": "And they were helped against them, and the Hagarites were delivered into their hand, and all that  were  with them: for they cried to God in the battle, and he was intreated of them; because they put their trust in him.",
      "21": "And they took away their cattle; of their camels fifty thousand, and of sheep two hundred and fifty thousand, and of asses two thousand, and of men an hundred thousand.  ",
      "22": "For there fell down many slain, because the war  was  of God. And they dwelt in their steads until the captivity.",
      "23": "And the children of the half tribe of Manasseh dwelt in the land: they increased from Bashan unto Baalhermon and Senir, and unto mount Hermon.",
      "24": "And these  were  the heads of the house of their fathers, even Epher, and Ishi, and Eliel, and Azriel, and Jeremiah, and Hodaviah, and Jahdiel, mighty men of valour, famous men,  and  heads of the house of their fathers. ",
      "25": "And they transgressed against the God of their fathers, and went a whoring after the gods of the people of the land, whom God destroyed before them.",
      "26": "And the God of Israel stirred up the spirit of Pul king of Assyria, and the spirit of Tilgathpilneser king of Assyria, and he carried them away, even the Reubenites, and the Gadites, and the half tribe of Manasseh, and brought them unto Halah, and Habor, and Hara, and to the river Gozan, unto this day. "
    }
  }
};

