
	
export const bib_verses = {
  "galatians": {
    "5": {
      "1": "Stand fast therefore in the liberty wherewith Christ hath made us free, and be not entangled again with the yoke of bondage.",
      "2": "Behold, I Paul say unto you, that if ye be circumcised, Christ shall profit you nothing.",
      "3": "For I testify again to every man that is circumcised, that he is a debtor to do the whole law.",
      "4": "Christ is become of no effect unto you, whosoever of you are justified by the law; ye are fallen from grace.",
      "5": "For we through the Spirit wait for the hope of righteousness by faith.",
      "6": "For in Jesus Christ neither circumcision availeth any thing, nor uncircumcision; but faith which worketh by love.",
      "7": "Ye did run well; who did hinder you that ye should not obey the truth? ",
      "8": "This persuasion  cometh  not of him that calleth you.",
      "9": "A little leaven leaveneth the whole lump.",
      "10": "I have confidence in you through the Lord, that ye will be none otherwise minded: but he that troubleth you shall bear his judgment, whosoever he be.",
      "11": "And I, brethren, if I yet preach circumcision, why do I yet suffer persecution? then is the offence of the cross ceased.",
      "12": "I would they were even cut off which trouble you. ",
      "13": "For, brethren, ye have been called unto liberty; only  use  not liberty for an occasion to the flesh, but by love serve one another.",
      "14": "For all the law is fulfilled in one word,  even  in this;  Thou shalt love thy neighbour as thyself. ",
      "15": "But if ye bite and devour one another, take heed that ye be not consumed one of another.",
      "16": " This  I say then, Walk in the Spirit, and ye shall not fulfil the lust of the flesh. ",
      "17": "For the flesh lusteth against the Spirit, and the Spirit against the flesh: and these are contrary the one to the other: so that ye cannot do the things that ye would.",
      "18": "But if ye be led of the Spirit, ye are not under the law.",
      "19": "Now the works of the flesh are manifest, which are  these ; Adultery, fornication, uncleanness, lasciviousness,",
      "20": "Idolatry, witchcraft, hatred, variance, emulations, wrath, strife, seditions, heresies,",
      "21": "Envyings, murders, drunkenness, revellings, and such like: of the which I tell you before, as I have also told  you  in time past, that they which do such things shall not inherit the kingdom of God.",
      "22": "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith,",
      "23": "Meekness, temperance: against such there is no law.",
      "24": "And they that are Christ's have crucified the flesh with the affections and lusts. ",
      "25": "If we live in the Spirit, let us also walk in the Spirit.",
      "26": "Let us not be desirous of vain glory, provoking one another, envying one another. "
    },
    "6": {
      "1": "Brethren, if a man be overtaken in a fault, ye which are spiritual, restore such an one in the spirit of meekness; considering thyself, lest thou also be tempted. ",
      "2": "Bear ye one another's burdens, and so fulfil the law of Christ.",
      "3": "For if a man think himself to be something, when he is nothing, he deceiveth himself.",
      "4": "But let every man prove his own work, and then shall he have rejoicing in himself alone, and not in another.",
      "5": "For every man shall bear his own burden.",
      "6": "Let him that is taught in the word communicate unto him that teacheth in all good things.",
      "7": "Be not deceived; God is not mocked: for whatsoever a man soweth, that shall he also reap.",
      "8": "For he that soweth to his flesh shall of the flesh reap corruption; but he that soweth to the Spirit shall of the Spirit reap life everlasting.",
      "9": "And let us not be weary in well doing: for in due season we shall reap, if we faint not.",
      "10": "As we have therefore opportunity, let us do good unto all  men , especially unto them who are of the household of faith. ",
      "11": "Ye see how large a letter I have written unto you with mine own hand.",
      "12": "As many as desire to make a fair shew in the flesh, they constrain you to be circumcised; only lest they should suffer persecution for the cross of Christ.",
      "13": "For neither they themselves who are circumcised keep the law; but desire to have you circumcised, that they may glory in your flesh.",
      "14": "But God forbid that I should glory, save in the cross of our Lord Jesus Christ, by whom the world is crucified unto me, and I unto the world. ",
      "15": "For in Christ Jesus neither circumcision availeth any thing, nor uncircumcision, but a new creature.",
      "16": "And as many as walk according to this rule, peace  be  on them, and mercy, and upon the Israel of God.",
      "17": "From henceforth let no man trouble me: for I bear in my body the marks of the Lord Jesus.",
      "18": "Brethren, the grace of our Lord Jesus Christ  be  with your spirit. Amen.  "
    }
  },
  "ephesians": {
    "1": {
      "1": "Paul, an apostle of Jesus Christ by the will of God, to the saints which are at Ephesus, and to the faithful in Christ Jesus:",
      "2": "Grace  be  to you, and peace, from God our Father, and  from  the Lord Jesus Christ. ",
      "3": "Blessed  be  the God and Father of our Lord Jesus Christ, who hath blessed us with all spiritual blessings in heavenly  places  in Christ: ",
      "4": "According as he hath chosen us in him before the foundation of the world, that we should be holy and without blame before him in love:",
      "5": "Having predestinated us unto the adoption of children by Jesus Christ to himself, according to the good pleasure of his will,",
      "6": "To the praise of the glory of his grace, wherein he hath made us accepted in the beloved.",
      "7": "In whom we have redemption through his blood, the forgiveness of sins, according to the riches of his grace;",
      "8": "Wherein he hath abounded toward us in all wisdom and prudence;",
      "9": "Having made known unto us the mystery of his will, according to his good pleasure which he hath purposed in himself:",
      "10": "That in the dispensation of the fulness of times he might gather together in one all things in Christ, both which are in heaven, and which are on earth;  even  in him: ",
      "11": "In whom also we have obtained an inheritance, being predestinated according to the purpose of him who worketh all things after the counsel of his own will:",
      "12": "That we should be to the praise of his glory, who first trusted in Christ. ",
      "13": "In whom ye also  trusted , after that ye heard the word of truth, the gospel of your salvation: in whom also after that ye believed, ye were sealed with that holy Spirit of promise,",
      "14": "Which is the earnest of our inheritance until the redemption of the purchased possession, unto the praise of his glory. ",
      "15": "Wherefore I also, after I heard of your faith in the Lord Jesus, and love unto all the saints,",
      "16": "Cease not to give thanks for you, making mention of you in my prayers;",
      "17": "That the God of our Lord Jesus Christ, the Father of glory, may give unto you the spirit of wisdom and revelation in the knowledge of him: ",
      "18": "The eyes of your understanding being enlightened; that ye may know what is the hope of his calling, and what the riches of the glory of his inheritance in the saints,",
      "19": "And what  is  the exceeding greatness of his power to us-ward who believe, according to the working of his mighty power, ",
      "20": "Which he wrought in Christ, when he raised him from the dead, and set  him  at his own right hand in the heavenly  places ,",
      "21": "Far above all principality, and power, and might, and dominion, and every name that is named, not only in this world, but also in that which is to come:",
      "22": "And hath put all  things  under his feet, and gave him  to be  the head over all  things  to the church,",
      "23": "Which is his body, the fulness of him that filleth all in all. "
    },
    "2": {
      "1": "And you  hath he quickened , who were dead in trespasses and sins;",
      "2": "Wherein in time past ye walked according to the course of this world, according to the prince of the power of the air, the spirit that now worketh in the children of disobedience:",
      "3": "Among whom also we all had our conversation in times past in the lusts of our flesh, fulfilling the desires of the flesh and of the mind; and were by nature the children of wrath, even as others.  ",
      "4": "But God, who is rich in mercy, for his great love wherewith he loved us,",
      "5": "Even when we were dead in sins, hath quickened us together with Christ, (by grace ye are saved;) ",
      "6": "And hath raised  us  up together, and made  us  sit together in heavenly  places  in Christ Jesus:",
      "7": "That in the ages to come he might shew the exceeding riches of his grace in  his  kindness toward us through Christ Jesus.",
      "8": "For by grace are ye saved through faith; and that not of yourselves:  it is  the gift of God:",
      "9": "Not of works, lest any man should boast.",
      "10": "For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.  ",
      "11": "Wherefore remember, that ye  being  in time past Gentiles in the flesh, who are called Uncircumcision by that which is called the Circumcision in the flesh made by hands;",
      "12": "That at that time ye were without Christ, being aliens from the commonwealth of Israel, and strangers from the covenants of promise, having no hope, and without God in the world:",
      "13": "But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ. ",
      "14": "For he is our peace, who hath made both one, and hath broken down the middle wall of partition  between us ;",
      "15": "Having abolished in his flesh the enmity,  even  the law of commandments  contained  in ordinances; for to make in himself of twain one new man,  so  making peace;",
      "16": "And that he might reconcile both unto God in one body by the cross, having slain the enmity thereby: ",
      "17": "And came and preached peace to you which were afar off, and to them that were nigh.",
      "18": "For through him we both have access by one Spirit unto the Father.",
      "19": "Now therefore ye are no more strangers and foreigners, but fellowcitizens with the saints, and of the household of God;",
      "20": "And are built upon the foundation of the apostles and prophets, Jesus Christ himself being the chief corner  stone ;",
      "21": "In whom all the building fitly framed together groweth unto an holy temple in the Lord:",
      "22": "In whom ye also are builded together for an habitation of God through the Spirit. "
    },
    "3": {
      "1": "For this cause I Paul, the prisoner of Jesus Christ for you Gentiles,",
      "2": "If ye have heard of the dispensation of the grace of God which is given me to you-ward:",
      "3": "How that by revelation he made known unto me the mystery; (as I wrote afore in few words, ",
      "4": "Whereby, when ye read, ye may understand my knowledge in the mystery of Christ)",
      "5": "Which in other ages was not made known unto the sons of men, as it is now revealed unto his holy apostles and prophets by the Spirit;",
      "6": "That the Gentiles should be fellowheirs, and of the same body, and partakers of his promise in Christ by the gospel:",
      "7": "Whereof I was made a minister, according to the gift of the grace of God given unto me by the effectual working of his power.",
      "8": "Unto me, who am less than the least of all saints, is this grace given, that I should preach among the Gentiles the unsearchable riches of Christ;",
      "9": "And to make all  men  see what  is  the fellowship of the mystery, which from the beginning of the world hath been hid in God, who created all things by Jesus Christ:",
      "10": "To the intent that now unto the principalities and powers in heavenly  places  might be known by the church the manifold wisdom of God,",
      "11": "According to the eternal purpose which he purposed in Christ Jesus our Lord:",
      "12": "In whom we have boldness and access with confidence by the faith of him.",
      "13": "Wherefore I desire that ye faint not at my tribulations for you, which is your glory. ",
      "14": "For this cause I bow my knees unto the Father of our Lord Jesus Christ,",
      "15": "Of whom the whole family in heaven and earth is named,",
      "16": "That he would grant you, according to the riches of his glory, to be strengthened with might by his Spirit in the inner man;",
      "17": "That Christ may dwell in your hearts by faith; that ye, being rooted and grounded in love,",
      "18": "May be able to comprehend with all saints what  is  the breadth, and length, and depth, and height;",
      "19": "And to know the love of Christ, which passeth knowledge, that ye might be filled with all the fulness of God.",
      "20": "Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us,",
      "21": "Unto him  be  glory in the church by Christ Jesus throughout all ages, world without end. Amen. "
    },
    "4": {
      "1": "I therefore, the prisoner of the Lord, beseech you that ye walk worthy of the vocation wherewith ye are called,  ",
      "2": "With all lowliness and meekness, with longsuffering, forbearing one another in love;",
      "3": "Endeavouring to keep the unity of the Spirit in the bond of peace.",
      "4": " There is  one body, and one Spirit, even as ye are called in one hope of your calling;",
      "5": "One Lord, one faith, one baptism,",
      "6": "One God and Father of all, who  is  above all, and through all, and in you all.",
      "7": "But unto every one of us is given grace according to the measure of the gift of Christ.",
      "8": "Wherefore he saith,  When he ascended up on high, he led captivity captive, and gave gifts unto men.  ",
      "9": "(Now that he ascended, what is it but that he also descended first into the lower parts of the earth?",
      "10": "He that descended is the same also that ascended up far above all heavens, that he might fill all things.) ",
      "11": "And he gave some, apostles; and some, prophets; and some, evangelists; and some, pastors and teachers;",
      "12": "For the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ:",
      "13": "Till we all come in the unity of the faith, and of the knowledge of the Son of God, unto a perfect man, unto the measure of the stature of the fulness of Christ:  ",
      "14": "That we  henceforth  be no more children, tossed to and fro, and carried about with every wind of doctrine, by the sleight of men,  and  cunning craftiness, whereby they lie in wait to deceive;",
      "15": "But speaking the truth in love, may grow up into him in all things, which is the head,  even  Christ: ",
      "16": "From whom the whole body fitly joined together and compacted by that which every joint supplieth, according to the effectual working in the measure of every part, maketh increase of the body unto the edifying of itself in love. ",
      "17": "This I say therefore, and testify in the Lord, that ye henceforth walk not as other Gentiles walk, in the vanity of their mind,",
      "18": "Having the understanding darkened, being alienated from the life of God through the ignorance that is in them, because of the blindness of their heart: ",
      "19": "Who being past feeling have given themselves over unto lasciviousness, to work all uncleanness with greediness.",
      "20": "But ye have not so learned Christ;",
      "21": "If so be that ye have heard him, and have been taught by him, as the truth is in Jesus:",
      "22": "That ye put off concerning the former conversation the old man, which is corrupt according to the deceitful lusts;",
      "23": "And be renewed in the spirit of your mind;",
      "24": "And that ye put on the new man, which after God is created in righteousness and true holiness. ",
      "25": "Wherefore putting away lying,  speak every man truth with his neighbour:  for we are members one of another.",
      "26": " Be ye angry, and sin not: let not the sun go down upon your wrath: ",
      "27": "Neither give place to the devil.",
      "28": "Let him that stole steal no more: but rather let him labour, working with  his  hands the thing which is good, that he may have to give to him that needeth. ",
      "29": "Let no corrupt communication proceed out of your mouth, but that which is good to the use of edifying, that it may minister grace unto the hearers. ",
      "30": "And grieve not the holy Spirit of God, whereby ye are sealed unto the day of redemption.",
      "31": "Let all bitterness, and wrath, and anger, and clamour, and evil speaking, be put away from you, with all malice:",
      "32": "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you. "
    },
    "5": {
      "1": "Be ye therefore followers of God, as dear children;",
      "2": "And walk in love, as Christ also hath loved us, and hath given himself for us an offering and a sacrifice to God for a sweetsmelling savour. ",
      "3": "But fornication, and all uncleanness, or covetousness, let it not be once named among you, as becometh saints;",
      "4": "Neither filthiness, nor foolish talking, nor jesting, which are not convenient: but rather giving of thanks.",
      "5": "For this ye know, that no whoremonger, nor unclean person, nor covetous man, who is an idolater, hath any inheritance in the kingdom of Christ and of God.",
      "6": "Let no man deceive you with vain words: for because of these things cometh the wrath of God upon the children of disobedience. ",
      "7": "Be not ye therefore partakers with them.",
      "8": "For ye were sometimes darkness, but now  are ye  light in the Lord: walk as children of light:",
      "9": "(For the fruit of the Spirit  is  in all goodness and righteousness and truth;)",
      "10": "Proving what is acceptable unto the Lord.",
      "11": "And have no fellowship with the unfruitful works of darkness, but rather reprove  them .",
      "12": "For it is a shame even to speak of those things which are done of them in secret.",
      "13": "But all things that are reproved are made manifest by the light: for whatsoever doth make manifest is light. ",
      "14": "Wherefore he saith,  Awake thou that sleepest, and arise from the dead, and Christ shall give thee light.  ",
      "15": "See then that ye walk circumspectly, not as fools, but as wise,",
      "16": "Redeeming the time, because the days are evil.",
      "17": "Wherefore be ye not unwise, but understanding what the will of the Lord  is .",
      "18": "And be not drunk with wine, wherein is excess; but be filled with the Spirit;",
      "19": "Speaking to yourselves in psalms and hymns and spiritual songs, singing and making melody in your heart to the Lord;",
      "20": "Giving thanks always for all things unto God and the Father in the name of our Lord Jesus Christ; ",
      "21": "Submitting yourselves one to another in the fear of God.",
      "22": "Wives, submit yourselves unto your own husbands, as unto the Lord.",
      "23": "For the husband is the head of the wife, even as Christ is the head of the church: and he is the saviour of the body.",
      "24": "Therefore as the church is subject unto Christ, so  let  the wives  be  to their own husbands in every thing.",
      "25": "Husbands, love your wives, even as Christ also loved the church, and gave himself for it;",
      "26": "That he might sanctify and cleanse it with the washing of water by the word,",
      "27": "That he might present it to himself a glorious church, not having spot, or wrinkle, or any such thing; but that it should be holy and without blemish.",
      "28": "So ought men to love their wives as their own bodies. He that loveth his wife loveth himself.",
      "29": "For no man ever yet hated his own flesh; but nourisheth and cherisheth it, even as the Lord the church:",
      "30": "For we are members of his body, of his flesh, and of his bones.",
      "31": " For this cause shall a man leave his father and mother, and shall be joined unto his wife, and they two shall be one flesh. ",
      "32": "This is a great mystery: but I speak concerning Christ and the church.",
      "33": "Nevertheless let every one of you in particular so love his wife even as himself; and the wife  see  that she reverence  her  husband. "
    },
    "6": {
      "1": "Children, obey your parents in the Lord: for this is right.",
      "2": " Honour thy father and mother;  (which is the first commandment with promise;)",
      "3": " That it may be well with thee, and thou mayest live long on the earth. ",
      "4": "And, ye fathers, provoke not your children to wrath: but bring them up in the nurture and admonition of the Lord.",
      "5": "Servants, be obedient to them that are  your  masters according to the flesh, with fear and trembling, in singleness of your heart, as unto Christ;",
      "6": "Not with eyeservice, as menpleasers; but as the servants of Christ, doing the will of God from the heart;",
      "7": "With good will doing service, as to the Lord, and not to men:",
      "8": "Knowing that whatsoever good thing any man doeth, the same shall he receive of the Lord, whether  he be  bond or free.",
      "9": "And, ye masters, do the same things unto them, forbearing threatening: knowing that your Master also is in heaven; neither is there respect of persons with him.   ",
      "10": "Finally, my brethren, be strong in the Lord, and in the power of his might.",
      "11": "Put on the whole armour of God, that ye may be able to stand against the wiles of the devil.",
      "12": "For we wrestle not against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this world, against spiritual wickedness in high  places .   ",
      "13": "Wherefore take unto you the whole armour of God, that ye may be able to withstand in the evil day, and having done all, to stand. ",
      "14": "Stand therefore, having your loins girt about with truth, and having on the breastplate of righteousness;",
      "15": "And your feet shod with the preparation of the gospel of peace;",
      "16": "Above all, taking the shield of faith, wherewith ye shall be able to quench all the fiery darts of the wicked.",
      "17": "And take the helmet of salvation, and the sword of the Spirit, which is the word of God:",
      "18": "Praying always with all prayer and supplication in the Spirit, and watching thereunto with all perseverance and supplication for all saints; ",
      "19": "And for me, that utterance may be given unto me, that I may open my mouth boldly, to make known the mystery of the gospel,",
      "20": "For which I am an ambassador in bonds: that therein I may speak boldly, as I ought to speak.  ",
      "21": "But that ye also may know my affairs,  and  how I do, Tychicus, a beloved brother and faithful minister in the Lord, shall make known to you all things:",
      "22": "Whom I have sent unto you for the same purpose, that ye might know our affairs, and  that  he might comfort your hearts.",
      "23": "Peace  be  to the brethren, and love with faith, from God the Father and the Lord Jesus Christ.",
      "24": "Grace  be  with all them that love our Lord Jesus Christ in sincerity. Amen.    "
    }
  },
  "philippians": {
    "1": {
      "1": "Paul and Timotheus, the servants of Jesus Christ, to all the saints in Christ Jesus which are at Philippi, with the bishops and deacons:",
      "2": "Grace  be  unto you, and peace, from God our Father, and  from  the Lord Jesus Christ. ",
      "3": "I thank my God upon every remembrance of you, ",
      "4": "Always in every prayer of mine for you all making request with joy,",
      "5": "For your fellowship in the gospel from the first day until now;",
      "6": "Being confident of this very thing, that he which hath begun a good work in you will perform  it  until the day of Jesus Christ:  ",
      "7": "Even as it is meet for me to think this of you all, because I have you in my heart; inasmuch as both in my bonds, and in the defence and confirmation of the gospel, ye all are partakers of my grace.  ",
      "8": "For God is my record, how greatly I long after you all in the bowels of Jesus Christ. ",
      "9": "And this I pray, that your love may abound yet more and more in knowledge and  in  all judgment; ",
      "10": "That ye may approve things that are excellent; that ye may be sincere and without offence till the day of Christ;  ",
      "11": "Being filled with the fruits of righteousness, which are by Jesus Christ, unto the glory and praise of God. ",
      "12": "But I would ye should understand, brethren, that the things  which happened  unto me have fallen out rather unto the furtherance of the gospel;",
      "13": "So that my bonds in Christ are manifest in all the palace, and in all other  places ;   ",
      "14": "And many of the brethren in the Lord, waxing confident by my bonds, are much more bold to speak the word without fear.",
      "15": "Some indeed preach Christ even of envy and strife; and some also of good will:",
      "16": "The one preach Christ of contention, not sincerely, supposing to add affliction to my bonds:",
      "17": "But the other of love, knowing that I am set for the defence of the gospel.",
      "18": "What then? notwithstanding, every way, whether in pretence, or in truth, Christ is preached; and I therein do rejoice, yea, and will rejoice.",
      "19": "For I know that this shall turn to my salvation through your prayer, and the supply of the Spirit of Jesus Christ,",
      "20": "According to my earnest expectation and  my  hope, that in nothing I shall be ashamed, but  that  with all boldness, as always,  so  now also Christ shall be magnified in my body, whether  it be  by life, or by death. ",
      "21": "For to me to live  is  Christ, and to die  is  gain.",
      "22": "But if I live in the flesh, this  is  the fruit of my labour: yet what I shall choose I wot not.",
      "23": "For I am in a strait betwixt two, having a desire to depart, and to be with Christ; which is far better:",
      "24": "Nevertheless to abide in the flesh  is  more needful for you.",
      "25": "And having this confidence, I know that I shall abide and continue with you all for your furtherance and joy of faith;",
      "26": "That your rejoicing may be more abundant in Jesus Christ for me by my coming to you again. ",
      "27": "Only let your conversation be as it becometh the gospel of Christ: that whether I come and see you, or else be absent, I may hear of your affairs, that ye stand fast in one spirit, with one mind striving together for the faith of the gospel;",
      "28": "And in nothing terrified by your adversaries: which is to them an evident token of perdition, but to you of salvation, and that of God.",
      "29": "For unto you it is given in the behalf of Christ, not only to believe on him, but also to suffer for his sake;",
      "30": "Having the same conflict which ye saw in me, and now hear  to be  in me. "
    },
    "2": {
      "1": "If  there be  therefore any consolation in Christ, if any comfort of love, if any fellowship of the Spirit, if any bowels and mercies,",
      "2": "Fulfil ye my joy, that ye be likeminded, having the same love,  being  of one accord, of one mind.",
      "3": " Let  nothing  be done  through strife or vainglory; but in lowliness of mind let each esteem other better than themselves.",
      "4": "Look not every man on his own things, but every man also on the things of others.",
      "5": " Let this mind be in you, which was also in Christ Jesus:",
      "6": "Who, being in the form of God, thought it not robbery to be equal with God:",
      "7": "But made himself of no reputation, and took upon him the form of a servant, and was made in the likeness of men:",
      "8": "And being found in fashion as a man, he humbled himself, and became obedient unto death, even the death of the cross. ",
      "9": "Wherefore God also hath highly exalted him, and given him a name which is above every name:",
      "10": "That at the name of Jesus  every knee should bow , of  things  in heaven, and  things  in earth, and  things  under the earth;",
      "11": "And  that  every tongue should confess that Jesus Christ  is  Lord, to the glory of God the Father. ",
      "12": "Wherefore, my beloved, as ye have always obeyed, not as in my presence only, but now much more in my absence, work out your own salvation with fear and trembling.",
      "13": "For it is God which worketh in you both to will and to do of  his  good pleasure. ",
      "14": "Do all things without murmurings and disputings:",
      "15": "That ye may be blameless and harmless, the sons of God, without rebuke, in the midst of a crooked and perverse nation, among whom ye shine as lights in the world;  ",
      "16": "Holding forth the word of life; that I may rejoice in the day of Christ, that I have not run in vain, neither laboured in vain.",
      "17": "Yea, and if I be offered upon the sacrifice and service of your faith, I joy, and rejoice with you all. ",
      "18": "For the same cause also do ye joy, and rejoice with me.",
      "19": "But I trust in the Lord Jesus to send Timotheus shortly unto you, that I also may be of good comfort, when I know your state. ",
      "20": "For I have no man likeminded, who will naturally care for your state. ",
      "21": "For all seek their own, not the things which are Jesus Christ's.",
      "22": "But ye know the proof of him, that, as a son with the father, he hath served with me in the gospel.",
      "23": "Him therefore I hope to send presently, so soon as I shall see how it will go with me.",
      "24": "But I trust in the Lord that I also myself shall come shortly.",
      "25": "Yet I supposed it necessary to send to you Epaphroditus, my brother, and companion in labour, and fellowsoldier, but your messenger, and he that ministered to my wants.",
      "26": "For he longed after you all, and was full of heaviness, because that ye had heard that he had been sick.",
      "27": "For indeed he was sick nigh unto death: but God had mercy on him; and not on him only, but on me also, lest I should have sorrow upon sorrow.",
      "28": "I sent him therefore the more carefully, that, when ye see him again, ye may rejoice, and that I may be the less sorrowful.",
      "29": "Receive him therefore in the Lord with all gladness; and hold such in reputation: ",
      "30": "Because for the work of Christ he was nigh unto death, not regarding his life, to supply your lack of service toward me. "
    },
    "3": {
      "1": "Finally, my brethren, rejoice in the Lord. To write the same things to you, to me indeed  is  not grievous, but for you  it is  safe.",
      "2": "Beware of dogs, beware of evil workers, beware of the concision.",
      "3": "For we are the circumcision, which worship God in the spirit, and rejoice in Christ Jesus, and have no confidence in the flesh. ",
      "4": "Though I might also have confidence in the flesh. If any other man thinketh that he hath whereof he might trust in the flesh, I more:",
      "5": "Circumcised the eighth day, of the stock of Israel,  of  the tribe of Benjamin, an Hebrew of the Hebrews; as touching the law, a Pharisee;",
      "6": "Concerning zeal, persecuting the church; touching the righteousness which is in the law, blameless.",
      "7": "But what things were gain to me, those I counted loss for Christ.",
      "8": "Yea doubtless, and I count all things  but  loss for the excellency of the knowledge of Christ Jesus my Lord: for whom I have suffered the loss of all things, and do count them  but  dung, that I may win Christ, ",
      "9": "And be found in him, not having mine own righteousness, which is of the law, but that which is through the faith of Christ, the righteousness which is of God by faith:",
      "10": "That I may know him, and the power of his resurrection, and the fellowship of his sufferings, being made conformable unto his death;",
      "11": "If by any means I might attain unto the resurrection of the dead.",
      "12": "Not as though I had already attained, either were already perfect: but I follow after, if that I may apprehend that for which also I am apprehended of Christ Jesus.",
      "13": "Brethren, I count not myself to have apprehended: but  this  one thing  I do , forgetting those things which are behind, and reaching forth unto those things which are before,",
      "14": "I press toward the mark for the prize of the high calling of God in Christ Jesus. ",
      "15": "Let us therefore, as many as be perfect, be thus minded: and if in any thing ye be otherwise minded, God shall reveal even this unto you.",
      "16": "Nevertheless, whereto we have already attained, let us walk by the same rule, let us mind the same thing. ",
      "17": "Brethren, be followers together of me, and mark them which walk so as ye have us for an ensample.",
      "18": "(For many walk, of whom I have told you often, and now tell you even weeping,  that they are  the enemies of the cross of Christ:",
      "19": "Whose end  is  destruction, whose God  is their  belly, and  whose  glory  is  in their shame, who mind earthly things.)",
      "20": "For our conversation is in heaven; from whence also we look for the Saviour, the Lord Jesus Christ: ",
      "21": "Who shall change our vile body, that it may be fashioned like unto his glorious body, according to the working whereby he is able even to subdue all things unto himself. "
    },
    "4": {
      "1": "Therefore, my brethren dearly beloved and longed for, my joy and crown, so stand fast in the Lord,  my  dearly beloved.",
      "2": "I beseech Euodias, and beseech Syntyche, that they be of the same mind in the Lord.",
      "3": "And I intreat thee also, true yokefellow, help those women which laboured with me in the gospel, with Clement also, and  with  other my fellowlabourers, whose names  are  in the book of life.",
      "4": "Rejoice in the Lord alway:  and  again I say, Rejoice.",
      "5": "Let your moderation be known unto all men. The Lord  is  at hand.",
      "6": "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.",
      "7": "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
      "8": "Finally, brethren, whatsoever things are true, whatsoever things  are  honest, whatsoever things  are  just, whatsoever things  are  pure, whatsoever things  are  lovely, whatsoever things  are  of good report; if  there be  any virtue, and if  there be  any praise, think on these things. ",
      "9": "Those things, which ye have both learned, and received, and heard, and seen in me, do: and the God of peace shall be with you. ",
      "10": "But I rejoiced in the Lord greatly, that now at the last your care of me hath flourished again; wherein ye were also careful, but ye lacked opportunity. ",
      "11": "Not that I speak in respect of want: for I have learned, in whatsoever state I am,  therewith  to be content.",
      "12": " I know both how to be abased, and I know how to abound: every where and in all things I am instructed both to be full and to be hungry, both to abound and to suffer need.",
      "13": "I can do all things through Christ which strengtheneth me.",
      "14": "Notwithstanding ye have well done, that ye did communicate with my affliction.",
      "15": "Now ye Philippians know also, that in the beginning of the gospel, when I departed from Macedonia, no church communicated with me as concerning giving and receiving, but ye only.",
      "16": "For even in Thessalonica ye sent once and again unto my necessity.",
      "17": "Not because I desire a gift: but I desire fruit that may abound to your account.",
      "18": "But I have all, and abound: I am full, having received of Epaphroditus the things  which were sent  from you, an odour of a sweet smell, a sacrifice acceptable, wellpleasing to God. ",
      "19": "But my God shall supply all your need according to his riches in glory by Christ Jesus. ",
      "20": "Now unto God and our Father  be  glory for ever and ever. Amen.",
      "21": "Salute every saint in Christ Jesus. The brethren which are with me greet you.",
      "22": "All the saints salute you, chiefly they that are of Caesar's household.",
      "23": "The grace of our Lord Jesus Christ  be  with you all. Amen.  "
    }
  },
  "colossians": {
    "1": {
      "1": "Paul, an apostle of Jesus Christ by the will of God, and Timotheus  our  brother,",
      "2": "To the saints and faithful brethren in Christ which are at Colosse: Grace  be  unto you, and peace, from God our Father and the Lord Jesus Christ. ",
      "3": "We give thanks to God and the Father of our Lord Jesus Christ, praying always for you,",
      "4": "Since we heard of your faith in Christ Jesus, and of the love  which   ye have  to all the saints,",
      "5": "For the hope which is laid up for you in heaven, whereof ye heard before in the word of the truth of the gospel;",
      "6": "Which is come unto you, as  it is  in all the world; and bringeth forth fruit, as  it doth  also in you, since the day ye heard  of it , and knew the grace of God in truth:",
      "7": "As ye also learned of Epaphras our dear fellowservant, who is for you a faithful minister of Christ;",
      "8": "Who also declared unto us your love in the Spirit. ",
      "9": "For this cause we also, since the day we heard  it , do not cease to pray for you, and to desire that ye might be filled with the knowledge of his will in all wisdom and spiritual understanding;",
      "10": "That ye might walk worthy of the Lord unto all pleasing, being fruitful in every good work, and increasing in the knowledge of God;",
      "11": "Strengthened with all might, according to his glorious power, unto all patience and longsuffering with joyfulness; ",
      "12": "Giving thanks unto the Father, which hath made us meet to be partakers of the inheritance of the saints in light:",
      "13": "Who hath delivered us from the power of darkness, and hath translated  us  into the kingdom of his dear Son: ",
      "14": "In whom we have redemption through his blood,  even  the forgiveness of sins:",
      "15": "Who is the image of the invisible God, the firstborn of every creature:",
      "16": "For by him were all things created, that are in heaven, and that are in earth, visible and invisible, whether  they be  thrones, or dominions, or principalities, or powers: all things were created by him, and for him:",
      "17": "And he is before all things, and by him all things consist.",
      "18": "And he is the head of the body, the church: who is the beginning, the firstborn from the dead; that in all  things  he might have the preeminence. ",
      "19": "For it pleased  the Father  that in him should all fulness dwell;",
      "20": "And, having made peace through the blood of his cross, by him to reconcile all things unto himself; by him,  I say , whether  they be  things in earth, or things in heaven. ",
      "21": "And you, that were sometime alienated and enemies in  your  mind by wicked works, yet now hath he reconciled ",
      "22": "In the body of his flesh through death, to present you holy and unblameable and unreproveable in his sight:",
      "23": "If ye continue in the faith grounded and settled, and  be  not moved away from the hope of the gospel, which ye have heard,  and  which was preached to every creature which is under heaven; whereof I Paul am made a minister;",
      "24": "Who now rejoice in my sufferings for you, and fill up that which is behind of the afflictions of Christ in my flesh for his body's sake, which is the church:",
      "25": "Whereof I am made a minister, according to the dispensation of God which is given to me for you, to fulfil the word of God; ",
      "26": " Even  the mystery which hath been hid from ages and from generations, but now is made manifest to his saints:",
      "27": "To whom God would make known what  is  the riches of the glory of this mystery among the Gentiles; which is Christ in you, the hope of glory: ",
      "28": "Whom we preach, warning every man, and teaching every man in all wisdom; that we may present every man perfect in Christ Jesus:",
      "29": "Whereunto I also labour, striving according to his working, which worketh in me mightily. "
    },
    "2": {
      "1": "For I would that ye knew what great conflict I have for you, and  for  them at Laodicea, and  for  as many as have not seen my face in the flesh; ",
      "2": "That their hearts might be comforted, being knit together in love, and unto all riches of the full assurance of understanding, to the acknowledgement of the mystery of God, and of the Father, and of Christ;",
      "3": "In whom are hid all the treasures of wisdom and knowledge.  ",
      "4": "And this I say, lest any man should beguile you with enticing words.",
      "5": "For though I be absent in the flesh, yet am I with you in the spirit, joying and beholding your order, and the stedfastness of your faith in Christ.",
      "6": "As ye have therefore received Christ Jesus the Lord,  so  walk ye in him:",
      "7": "Rooted and built up in him, and stablished in the faith, as ye have been taught, abounding therein with thanksgiving.",
      "8": "Beware lest any man spoil you through philosophy and vain deceit, after the tradition of men, after the rudiments of the world, and not after Christ.  ",
      "9": "For in him dwelleth all the fulness of the Godhead bodily.",
      "10": "And ye are complete in him, which is the head of all principality and power:",
      "11": "In whom also ye are circumcised with the circumcision made without hands, in putting off the body of the sins of the flesh by the circumcision of Christ:",
      "12": "Buried with him in baptism, wherein also ye are risen with  him  through the faith of the operation of God, who hath raised him from the dead. ",
      "13": "And you, being dead in your sins and the uncircumcision of your flesh, hath he quickened together with him, having forgiven you all trespasses;",
      "14": "Blotting out the handwriting of ordinances that was against us, which was contrary to us, and took it out of the way, nailing it to his cross;",
      "15": " And  having spoiled principalities and powers, he made a shew of them openly, triumphing over them in it.  ",
      "16": "Let no man therefore judge you in meat, or in drink, or in respect of an holyday, or of the new moon, or of the sabbath  days :  ",
      "17": "Which are a shadow of things to come; but the body  is  of Christ.",
      "18": "Let no man beguile you of your reward in a voluntary humility and worshipping of angels, intruding into those things which he hath not seen, vainly puffed up by his fleshly mind,  ",
      "19": "And not holding the Head, from which all the body by joints and bands having nourishment ministered, and knit together, increaseth with the increase of God.",
      "20": "Wherefore if ye be dead with Christ from the rudiments of the world, why, as though living in the world, are ye subject to ordinances, ",
      "21": "(Touch not; taste not; handle not;",
      "22": "Which all are to perish with the using;) after the commandments and doctrines of men?",
      "23": "Which things have indeed a shew of wisdom in will worship, and humility, and neglecting of the body; not in any honour to the satisfying of the flesh.  "
    },
    "3": {
      "1": "If ye then be risen with Christ, seek those things which are above, where Christ sitteth on the right hand of God.",
      "2": "Set your affection on things above, not on things on the earth. ",
      "3": "For ye are dead, and your life is hid with Christ in God.",
      "4": "When Christ,  who is  our life, shall appear, then shall ye also appear with him in glory. ",
      "5": "Mortify therefore your members which are upon the earth; fornication, uncleanness, inordinate affection, evil concupiscence, and covetousness, which is idolatry:",
      "6": "For which things' sake the wrath of God cometh on the children of disobedience:",
      "7": "In the which ye also walked some time, when ye lived in them. ",
      "8": "But now ye also put off all these; anger, wrath, malice, blasphemy, filthy communication out of your mouth.",
      "9": "Lie not one to another, seeing that ye have put off the old man with his deeds;",
      "10": "And have put on the new  man , which is renewed in knowledge after the image of him that created him:",
      "11": "Where there is neither Greek nor Jew, circumcision nor uncircumcision, Barbarian, Scythian, bond  nor  free: but Christ  is  all, and in all. ",
      "12": "Put on therefore, as the elect of God, holy and beloved, bowels of mercies, kindness, humbleness of mind, meekness, longsuffering;",
      "13": "Forbearing one another, and forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also  do  ye. ",
      "14": "And above all these things  put on  charity, which is the bond of perfectness.",
      "15": "And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful.",
      "16": "Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord.",
      "17": "And whatsoever ye do in word or deed,  do  all in the name of the Lord Jesus, giving thanks to God and the Father by him. ",
      "18": "Wives, submit yourselves unto your own husbands, as it is fit in the Lord.",
      "19": "Husbands, love  your  wives, and be not bitter against them.",
      "20": "Children, obey  your  parents in all things: for this is well pleasing unto the Lord.",
      "21": "Fathers, provoke not your children  to anger , lest they be discouraged.",
      "22": "Servants, obey in all things  your  masters according to the flesh; not with eyeservice, as menpleasers; but in singleness of heart, fearing God:",
      "23": "And whatsoever ye do, do  it  heartily, as to the Lord, and not unto men;",
      "24": "Knowing that of the Lord ye shall receive the reward of the inheritance: for ye serve the Lord Christ.",
      "25": "But he that doeth wrong shall receive for the wrong which he hath done: and there is no respect of persons. "
    },
    "4": {
      "1": "Masters, give unto  your  servants that which is just and equal; knowing that ye also have a Master in heaven. ",
      "2": "Continue in prayer, and watch in the same with thanksgiving;",
      "3": "Withal praying also for us, that God would open unto us a door of utterance, to speak the mystery of Christ, for which I am also in bonds:",
      "4": "That I may make it manifest, as I ought to speak. ",
      "5": "Walk in wisdom toward them that are without, redeeming the time.",
      "6": "Let your speech  be  alway with grace, seasoned with salt, that ye may know how ye ought to answer every man. ",
      "7": "All my state shall Tychicus declare unto you,  who is  a beloved brother, and a faithful minister and fellowservant in the Lord:",
      "8": "Whom I have sent unto you for the same purpose, that he might know your estate, and comfort your hearts;",
      "9": "With Onesimus, a faithful and beloved brother, who is  one  of you. They shall make known unto you all things which  are done  here.",
      "10": "Aristarchus my fellowprisoner saluteth you, and Marcus, sister's son to Barnabas, (touching whom ye received commandments: if he come unto you, receive him;)",
      "11": "And Jesus, which is called Justus, who are of the circumcision. These only  are my  fellowworkers unto the kingdom of God, which have been a comfort unto me.",
      "12": "Epaphras, who is  one  of you, a servant of Christ, saluteth you, always labouring fervently for you in prayers, that ye may stand perfect and complete in all the will of God.  ",
      "13": "For I bear him record, that he hath a great zeal for you, and them  that are  in Laodicea, and them in Hierapolis.",
      "14": "Luke, the beloved physician, and Demas, greet you.",
      "15": "Salute the brethren which are in Laodicea, and Nymphas, and the church which is in his house.",
      "16": "And when this epistle is read among you, cause that it be read also in the church of the Laodiceans; and that ye likewise read the  epistle  from Laodicea.",
      "17": "And say to Archippus, Take heed to the ministry which thou hast received in the Lord, that thou fulfil it.",
      "18": "The salutation by the hand of me Paul. Remember my bonds. Grace  be  with you. Amen.   "
    }
  },
  "1_thessalonians": {
    "1": {
      "1": "Paul, and Silvanus, and Timotheus, unto the church of the Thessalonians  which is  in God the Father and  in  the Lord Jesus Christ: Grace  be  unto you, and peace, from God our Father, and the Lord Jesus Christ. ",
      "2": "We give thanks to God always for you all, making mention of you in our prayers;",
      "3": "Remembering without ceasing your work of faith, and labour of love, and patience of hope in our Lord Jesus Christ, in the sight of God and our Father;",
      "4": "Knowing, brethren beloved, your election of God. ",
      "5": "For our gospel came not unto you in word only, but also in power, and in the Holy Ghost, and in much assurance; as ye know what manner of men we were among you for your sake. ",
      "6": "And ye became followers of us, and of the Lord, having received the word in much affliction, with joy of the Holy Ghost:",
      "7": "So that ye were ensamples to all that believe in Macedonia and Achaia.",
      "8": "For from you sounded out the word of the Lord not only in Macedonia and Achaia, but also in every place your faith to God-ward is spread abroad; so that we need not to speak any thing.",
      "9": "For they themselves shew of us what manner of entering in we had unto you, and how ye turned to God from idols to serve the living and true God;",
      "10": "And to wait for his Son from heaven, whom he raised from the dead,  even  Jesus, which delivered us from the wrath to come. "
    },
    "2": {
      "1": "For yourselves, brethren, know our entrance in unto you, that it was not in vain:",
      "2": "But even after that we had suffered before, and were shamefully entreated, as ye know, at Philippi, we were bold in our God to speak unto you the gospel of God with much contention.",
      "3": "For our exhortation  was  not of deceit, nor of uncleanness, nor in guile:",
      "4": "But as we were allowed of God to be put in trust with the gospel, even so we speak; not as pleasing men, but God, which trieth our hearts.",
      "5": "For neither at any time used we flattering words, as ye know, nor a cloke of covetousness; God  is  witness:",
      "6": "Nor of men sought we glory, neither of you, nor  yet  of others, when we might have been burdensome, as the apostles of Christ.  ",
      "7": "But we were gentle among you, even as a nurse cherisheth her children:",
      "8": "So being affectionately desirous of you, we were willing to have imparted unto you, not the gospel of God only, but also our own souls, because ye were dear unto us.",
      "9": "For ye remember, brethren, our labour and travail: for labouring night and day, because we would not be chargeable unto any of you, we preached unto you the gospel of God.",
      "10": "Ye  are  witnesses, and God  also , how holily and justly and unblameably we behaved ourselves among you that believe:",
      "11": "As ye know how we exhorted and comforted and charged every one of you, as a father  doth  his children,",
      "12": " That ye would walk worthy of God, who hath called you unto his kingdom and glory. ",
      "13": "For this cause also thank we God without ceasing, because, when ye received the word of God which ye heard of us, ye received  it  not  as  the word of men, but as it is in truth, the word of God, which effectually worketh also in you that believe.",
      "14": "For ye, brethren, became followers of the churches of God which in Judaea are in Christ Jesus: for ye also have suffered like things of your own countrymen, even as they  have  of the Jews:",
      "15": "Who both killed the Lord Jesus, and their own prophets, and have persecuted us; and they please not God, and are contrary to all men: ",
      "16": "Forbidding us to speak to the Gentiles that they might be saved, to fill up their sins alway: for the wrath is come upon them to the uttermost. ",
      "17": "But we, brethren, being taken from you for a short time in presence, not in heart, endeavoured the more abundantly to see your face with great desire.",
      "18": "Wherefore we would have come unto you, even I Paul, once and again; but Satan hindered us.",
      "19": "For what  is  our hope, or joy, or crown of rejoicing?  Are  not even ye in the presence of our Lord Jesus Christ at his coming? ",
      "20": "For ye are our glory and joy. "
    },
    "3": {
      "1": "Wherefore when we could no longer forbear, we thought it good to be left at Athens alone;",
      "2": "And sent Timotheus, our brother, and minister of God, and our fellowlabourer in the gospel of Christ, to establish you, and to comfort you concerning your faith:",
      "3": "That no man should be moved by these afflictions: for yourselves know that we are appointed thereunto. ",
      "4": "For verily, when we were with you, we told you before that we should suffer tribulation; even as it came to pass, and ye know.",
      "5": "For this cause, when I could no longer forbear, I sent to know your faith, lest by some means the tempter have tempted you, and our labour be in vain. ",
      "6": "But now when Timotheus came from you unto us, and brought us good tidings of your faith and charity, and that ye have good remembrance of us always, desiring greatly to see us, as we also  to see  you:",
      "7": "Therefore, brethren, we were comforted over you in all our affliction and distress by your faith:",
      "8": "For now we live, if ye stand fast in the Lord.",
      "9": "For what thanks can we render to God again for you, for all the joy wherewith we joy for your sakes before our God;",
      "10": "Night and day praying exceedingly that we might see your face, and might perfect that which is lacking in your faith? ",
      "11": "Now God himself and our Father, and our Lord Jesus Christ, direct our way unto you. ",
      "12": "And the Lord make you to increase and abound in love one toward another, and toward all  men , even as we  do  toward you:",
      "13": "To the end he may stablish your hearts unblameable in holiness before God, even our Father, at the coming of our Lord Jesus Christ with all his saints.  "
    },
    "4": {
      "1": "Furthermore then we beseech you, brethren, and exhort  you  by the Lord Jesus, that as ye have received of us how ye ought to walk and to please God,  so  ye would abound more and more.  ",
      "2": "For ye know what commandments we gave you by the Lord Jesus.",
      "3": "For this is the will of God,  even  your sanctification, that ye should abstain from fornication:",
      "4": "That every one of you should know how to possess his vessel in sanctification and honour;",
      "5": "Not in the lust of concupiscence, even as the Gentiles which know not God:",
      "6": "That no  man  go beyond and defraud his brother in  any  matter: because that the Lord  is  the avenger of all such, as we also have forewarned you and testified.  ",
      "7": "For God hath not called us unto uncleanness, but unto holiness.",
      "8": "He therefore that despiseth, despiseth not man, but God, who hath also given unto us his holy Spirit.  ",
      "9": "But as touching brotherly love ye need not that I write unto you: for ye yourselves are taught of God to love one another.",
      "10": "And indeed ye do it toward all the brethren which are in all Macedonia: but we beseech you, brethren, that ye increase more and more;",
      "11": "And that ye study to be quiet, and to do your own business, and to work with your own hands, as we commanded you;",
      "12": "That ye may walk honestly toward them that are without, and  that  ye may have lack of nothing.  ",
      "13": "But I would not have you to be ignorant, brethren, concerning them which are asleep, that ye sorrow not, even as others which have no hope.",
      "14": "For if we believe that Jesus died and rose again, even so them also which sleep in Jesus will God bring with him.",
      "15": "For this we say unto you by the word of the Lord, that we which are alive  and  remain unto the coming of the Lord shall not prevent them which are asleep. ",
      "16": "For the Lord himself shall descend from heaven with a shout, with the voice of the archangel, and with the trump of God: and the dead in Christ shall rise first:",
      "17": "Then we which are alive  and  remain shall be caught up together with them in the clouds, to meet the Lord in the air: and so shall we ever be with the Lord.",
      "18": "Wherefore comfort one another with these words.  "
    },
    "5": {
      "1": "But of the times and the seasons, brethren, ye have no need that I write unto you.",
      "2": "For yourselves know perfectly that the day of the Lord so cometh as a thief in the night.",
      "3": "For when they shall say, Peace and safety; then sudden destruction cometh upon them, as travail upon a woman with child; and they shall not escape.",
      "4": "But ye, brethren, are not in darkness, that that day should overtake you as a thief.",
      "5": "Ye are all the children of light, and the children of the day: we are not of the night, nor of darkness. ",
      "6": "Therefore let us not sleep, as  do  others; but let us watch and be sober.",
      "7": "For they that sleep sleep in the night; and they that be drunken are drunken in the night.",
      "8": "But let us, who are of the day, be sober, putting on the breastplate of faith and love; and for an helmet, the hope of salvation.",
      "9": "For God hath not appointed us to wrath, but to obtain salvation by our Lord Jesus Christ,",
      "10": "Who died for us, that, whether we wake or sleep, we should live together with him. ",
      "11": "Wherefore comfort yourselves together, and edify one another, even as also ye do. ",
      "12": "And we beseech you, brethren, to know them which labour among you, and are over you in the Lord, and admonish you;",
      "13": "And to esteem them very highly in love for their work's sake.  And  be at peace among yourselves.",
      "14": "Now we exhort you, brethren, warn them that are unruly, comfort the feebleminded, support the weak, be patient toward all  men .  ",
      "15": "See that none render evil for evil unto any  man ; but ever follow that which is good, both among yourselves, and to all  men . ",
      "16": "Rejoice evermore.",
      "17": "Pray without ceasing.",
      "18": "In every thing give thanks: for this is the will of God in Christ Jesus concerning you.",
      "19": "Quench not the Spirit.",
      "20": "Despise not prophesyings.",
      "21": "Prove all things; hold fast that which is good.",
      "22": "Abstain from all appearance of evil. ",
      "23": "And the very God of peace sanctify you wholly; and  I pray God  your whole spirit and soul and body be preserved blameless unto the coming of our Lord Jesus Christ.",
      "24": "Faithful  is  he that calleth you, who also will do  it .",
      "25": "Brethren, pray for us.",
      "26": "Greet all the brethren with an holy kiss.",
      "27": "I charge you by the Lord that this epistle be read unto all the holy brethren. ",
      "28": "The grace of our Lord Jesus Christ  be  with you. Amen.  "
    }
  },
  "2_thessalonians": {
    "1": {
      "1": "Paul, and Silvanus, and Timotheus, unto the church of the Thessalonians in God our Father and the Lord Jesus Christ:",
      "2": "Grace unto you, and peace, from God our Father and the Lord Jesus Christ.",
      "3": "We are bound to thank God always for you, brethren, as it is meet, because that your faith groweth exceedingly, and the charity of every one of you all toward each other aboundeth;",
      "4": "So that we ourselves glory in you in the churches of God for your patience and faith in all your persecutions and tribulations that ye endure: ",
      "5": " Which is  a manifest token of the righteous judgment of God, that ye may be counted worthy of the kingdom of God, for which ye also suffer:",
      "6": "Seeing  it is  a righteous thing with God to recompense tribulation to them that trouble you;",
      "7": "And to you who are troubled rest with us, when the Lord Jesus shall be revealed from heaven with his mighty angels, ",
      "8": "In flaming fire taking vengeance on them that know not God, and that obey not the gospel of our Lord Jesus Christ: ",
      "9": "Who shall be punished with everlasting destruction from the presence of the Lord, and from the glory of his power;",
      "10": "When he shall come to be glorified in his saints, and to be admired in all them that believe (because our testimony among you was believed) in that day. ",
      "11": "Wherefore also we pray always for you, that our God would count you worthy of  this  calling, and fulfil all the good pleasure of  his  goodness, and the work of faith with power: ",
      "12": "That the name of our Lord Jesus Christ may be glorified in you, and ye in him, according to the grace of our God and the Lord Jesus Christ. "
    }
  }
};

