
	
export const bib_verses = {
  "luke": {
    "17": {
      "1": "Then said he unto the disciples,  It is impossible but that offences will come: but woe  unto him , through whom they come! ",
      "2": " It were better for him that a millstone were hanged about his neck, and he cast into the sea, than that he should offend one of these little ones. ",
      "3": " Take heed to yourselves: If thy brother trespass against thee, rebuke him; and if he repent, forgive him. ",
      "4": " And if he trespass against thee seven times in a day, and seven times in a day turn again to thee, saying, I repent; thou shalt forgive him. ",
      "5": "And the apostles said unto the Lord, Increase our faith.",
      "6": "And the Lord said,  If ye had faith as a grain of mustard seed, ye might say unto this sycamine tree, Be thou plucked up by the root, and be thou planted in the sea; and it should obey you. ",
      "7": " But which of you, having a servant plowing or feeding cattle, will say unto him by and by, when he is come from the field, Go and sit down to meat? ",
      "8": " And will not rather say unto him, Make ready wherewith I may sup, and gird thyself, and serve me, till I have eaten and drunken; and afterward thou shalt eat and drink? ",
      "9": "  Doth he thank that servant because he did the things that were commanded him? I trow not. ",
      "10": " So likewise ye, when ye shall have done all those things which are commanded you, say, We are unprofitable servants: we have done that which was our duty to do.  ",
      "11": "And it came to pass, as he went to Jerusalem, that he passed through the midst of Samaria and Galilee.",
      "12": "And as he entered into a certain village, there met him ten men that were lepers, which stood afar off:",
      "13": "And they lifted up  their  voices, and said, Jesus, Master, have mercy on us.",
      "14": "And when he saw  them , he said unto them,  Go shew yourselves unto the priests.  And it came to pass, that, as they went, they were cleansed.",
      "15": "And one of them, when he saw that he was healed, turned back, and with a loud voice glorified God,",
      "16": "And fell down on  his  face at his feet, giving him thanks: and he was a Samaritan.",
      "17": "And Jesus answering said,  Were there not ten cleansed? but where  are  the nine? ",
      "18": " There are not found that returned to give glory to God, save this stranger. ",
      "19": "And he said unto him,  Arise, go thy way: thy faith hath made thee whole.  ",
      "20": "And when he was demanded of the Pharisees, when the kingdom of God should come, he answered them and said,  The kingdom of God cometh not with observation:  ",
      "21": " Neither shall they say, Lo here! or, lo there! for, behold, the kingdom of God is within you.  ",
      "22": "And he said unto the disciples,  The days will come, when ye shall desire to see one of the days of the Son of man, and ye shall not see  it . ",
      "23": " And they shall say to you, See here; or, see there: go not after  them , nor follow  them . ",
      "24": " For as the lightning, that lighteneth out of the one  part  under heaven, shineth unto the other  part  under heaven; so shall also the Son of man be in his day. ",
      "25": " But first must he suffer many things, and be rejected of this generation. ",
      "26": " And as it was in the days of Noe, so shall it be also in the days of the Son of man. ",
      "27": " They did eat, they drank, they married wives, they were given in marriage, until the day that Noe entered into the ark, and the flood came, and destroyed them all. ",
      "28": " Likewise also as it was in the days of Lot; they did eat, they drank, they bought, they sold, they planted, they builded; ",
      "29": " But the same day that Lot went out of Sodom it rained fire and brimstone from heaven, and destroyed  them  all. ",
      "30": " Even thus shall it be in the day when the Son of man is revealed. ",
      "31": " In that day, he which shall be upon the housetop, and his stuff in the house, let him not come down to take it away: and he that is in the field, let him likewise not return back. ",
      "32": " Remember Lot's wife. ",
      "33": " Whosoever shall seek to save his life shall lose it; and whosoever shall lose his life shall preserve it. ",
      "34": " I tell you, in that night there shall be two  men  in one bed; the one shall be taken, and the other shall be left. ",
      "35": " Two  women  shall be grinding together; the one shall be taken, and the other left. ",
      "36": " Two  men  shall be in the field; the one shall be taken, and the other left.  ",
      "37": "And they answered and said unto him, Where, Lord? And he said unto them,  Wheresoever the body  is , thither will the eagles be gathered together.  "
    },
    "18": {
      "1": "And he spake a parable unto them  to this end , that men ought always to pray, and not to faint;",
      "2": "Saying,  There was in a city a judge, which feared not God, neither regarded man:  ",
      "3": " And there was a widow in that city; and she came unto him, saying, Avenge me of mine adversary. ",
      "4": " And he would not for a while: but afterward he said within himself, Though I fear not God, nor regard man; ",
      "5": " Yet because this widow troubleth me, I will avenge her, lest by her continual coming she weary me. ",
      "6": "And the Lord said,  Hear what the unjust judge saith. ",
      "7": " And shall not God avenge his own elect, which cry day and night unto him, though he bear long with them? ",
      "8": " I tell you that he will avenge them speedily. Nevertheless when the Son of man cometh, shall he find faith on the earth?  ",
      "9": "And he spake this parable unto certain which trusted in themselves that they were righteous, and despised others: ",
      "10": " Two men went up into the temple to pray; the one a Pharisee, and the other a publican. ",
      "11": " The Pharisee stood and prayed thus with himself, God, I thank thee, that I am not as other men  are , extortioners, unjust, adulterers, or even as this publican. ",
      "12": " I fast twice in the week, I give tithes of all that I possess. ",
      "13": " And the publican, standing afar off, would not lift up so much as  his  eyes unto heaven, but smote upon his breast, saying, God be merciful to me a sinner. ",
      "14": " I tell you, this man went down to his house justified  rather  than the other: for every one that exalteth himself shall be abased; and he that humbleth himself shall be exalted.  ",
      "15": "And they brought unto him also infants, that he would touch them: but when  his  disciples saw  it , they rebuked them.",
      "16": "But Jesus called them  unto him , and said,  Suffer little children to come unto me, and forbid them not: for of such is the kingdom of God. ",
      "17": " Verily I say unto you, Whosoever shall not receive the kingdom of God as a little child shall in no wise enter therein.  ",
      "18": "And a certain ruler asked him, saying, Good Master, what shall I do to inherit eternal life?",
      "19": "And Jesus said unto him,  Why callest thou me good? none  is  good, save one,  that is , God. ",
      "20": " Thou knowest the commandments, Do not commit adultery, Do not kill, Do not steal, Do not bear false witness, Honour thy father and thy mother. ",
      "21": "And he said, All these have I kept from my youth up.",
      "22": "Now when Jesus heard these things, he said unto him,  Yet lackest thou one thing: sell all that thou hast, and distribute unto the poor, and thou shalt have treasure in heaven: and come, follow me. ",
      "23": "And when he heard this, he was very sorrowful: for he was very rich.",
      "24": "And when Jesus saw that he was very sorrowful, he said,  How hardly shall they that have riches enter into the kingdom of God! ",
      "25": " For it is easier for a camel to go through a needle's eye, than for a rich man to enter into the kingdom of God. ",
      "26": "And they that heard  it  said, Who then can be saved?",
      "27": "And he said,  The things which are impossible with men are possible with God. ",
      "28": "Then Peter said, Lo, we have left all, and followed thee.",
      "29": "And he said unto them,  Verily I say unto you, There is no man that hath left house, or parents, or brethren, or wife, or children, for the kingdom of God's sake, ",
      "30": " Who shall not receive manifold more in this present time, and in the world to come life everlasting.  ",
      "31": "Then he took  unto him  the twelve, and said unto them,  Behold, we go up to Jerusalem, and all things that are written by the prophets concerning the Son of man shall be accomplished. ",
      "32": " For he shall be delivered unto the Gentiles, and shall be mocked, and spitefully entreated, and spitted on: ",
      "33": " And they shall scourge  him , and put him to death: and the third day he shall rise again. ",
      "34": "And they understood none of these things: and this saying was hid from them, neither knew they the things which were spoken. ",
      "35": "And it came to pass, that as he was come nigh unto Jericho, a certain blind man sat by the way side begging:",
      "36": "And hearing the multitude pass by, he asked what it meant.",
      "37": "And they told him, that Jesus of Nazareth passeth by.",
      "38": "And he cried, saying, Jesus,  thou  Son of David, have mercy on me.",
      "39": "And they which went before rebuked him, that he should hold his peace: but he cried so much the more,  Thou  Son of David, have mercy on me.",
      "40": "And Jesus stood, and commanded him to be brought unto him: and when he was come near, he asked him,",
      "41": "Saying,  What wilt thou that I shall do unto thee?  And he said, Lord, that I may receive my sight.",
      "42": "And Jesus said unto him,  Receive thy sight: thy faith hath saved thee. ",
      "43": "And immediately he received his sight, and followed him, glorifying God: and all the people, when they saw  it , gave praise unto God. "
    },
    "19": {
      "1": "And  Jesus  entered and passed through Jericho.",
      "2": "And, behold,  there was  a man named Zacchaeus, which was the chief among the publicans, and he was rich.",
      "3": "And he sought to see Jesus who he was; and could not for the press, because he was little of stature.",
      "4": "And he ran before, and climbed up into a sycomore tree to see him: for he was to pass that  way .",
      "5": "And when Jesus came to the place, he looked up, and saw him, and said unto him,  Zacchaeus, make haste, and come down; for to day I must abide at thy house. ",
      "6": "And he made haste, and came down, and received him joyfully.",
      "7": "And when they saw  it , they all murmured, saying, That he was gone to be guest with a man that is a sinner.",
      "8": "And Zacchaeus stood, and said unto the Lord; Behold, Lord, the half of my goods I give to the poor; and if I have taken any thing from any man by false accusation, I restore  him  fourfold.",
      "9": "And Jesus said unto him,  This day is salvation come to this house, forsomuch as he also is a son of Abraham. ",
      "10": " For the Son of man is come to seek and to save that which was lost.  ",
      "11": "And as they heard these things, he added and spake a parable, because he was nigh to Jerusalem, and because they thought that the kingdom of God should immediately appear.",
      "12": "He said therefore,  A certain nobleman went into a far country to receive for himself a kingdom, and to return. ",
      "13": " And he called his ten servants, and delivered them ten pounds, and said unto them, Occupy till I come.  ",
      "14": " But his citizens hated him, and sent a message after him, saying, We will not have this  man  to reign over us. ",
      "15": " And it came to pass, that when he was returned, having received the kingdom, then he commanded these servants to be called unto him, to whom he had given the money, that he might know how much every man had gained by trading. ",
      "16": " Then came the first, saying, Lord, thy pound hath gained ten pounds. ",
      "17": " And he said unto him, Well, thou good servant: because thou hast been faithful in a very little, have thou authority over ten cities. ",
      "18": " And the second came, saying, Lord, thy pound hath gained five pounds. ",
      "19": " And he said likewise to him, Be thou also over five cities. ",
      "20": " And another came, saying, Lord, behold,  here is  thy pound, which I have kept laid up in a napkin: ",
      "21": " For I feared thee, because thou art an austere man: thou takest up that thou layedst not down, and reapest that thou didst not sow. ",
      "22": " And he saith unto him, Out of thine own mouth will I judge thee,  thou  wicked servant. Thou knewest that I was an austere man, taking up that I laid not down, and reaping that I did not sow: ",
      "23": " Wherefore then gavest not thou my money into the bank, that at my coming I might have required mine own with usury? ",
      "24": " And he said unto them that stood by, Take from him the pound, and give  it  to him that hath ten pounds. ",
      "25": " (And they said unto him, Lord, he hath ten pounds.) ",
      "26": " For I say unto you, That unto every one which hath shall be given; and from him that hath not, even that he hath shall be taken away from him. ",
      "27": " But those mine enemies, which would not that I should reign over them, bring hither, and slay  them  before me.  ",
      "28": "And when he had thus spoken, he went before, ascending up to Jerusalem.",
      "29": "And it came to pass, when he was come nigh to Bethphage and Bethany, at the mount called  the mount  of Olives, he sent two of his disciples,",
      "30": "Saying,  Go ye into the village over against  you ; in the which at your entering ye shall find a colt tied, whereon yet never man sat: loose him, and bring  him hither . ",
      "31": " And if any man ask you, Why do ye loose  him ? thus shall ye say unto him, Because the Lord hath need of him. ",
      "32": "And they that were sent went their way, and found even as he had said unto them.",
      "33": "And as they were loosing the colt, the owners thereof said unto them, Why loose ye the colt?",
      "34": "And they said, The Lord hath need of him.",
      "35": "And they brought him to Jesus: and they cast their garments upon the colt, and they set Jesus thereon.",
      "36": "And as he went, they spread their clothes in the way.",
      "37": "And when he was come nigh, even now at the descent of the mount of Olives, the whole multitude of the disciples began to rejoice and praise God with a loud voice for all the mighty works that they had seen;",
      "38": "Saying,  Blessed  be  the King that cometh in the name of the Lord:  peace in heaven, and glory in the highest.",
      "39": "And some of the Pharisees from among the multitude said unto him, Master, rebuke thy disciples.",
      "40": "And he answered and said unto them,  I tell you that, if these should hold their peace, the stones would immediately cry out.  ",
      "41": "And when he was come near, he beheld the city, and wept over it,",
      "42": "Saying,  If thou hadst known, even thou, at least in this thy day, the things  which belong  unto thy peace! but now they are hid from thine eyes. ",
      "43": " For the days shall come upon thee, that thine enemies shall cast a trench about thee, and compass thee round, and keep thee in on every side, ",
      "44": " And shall lay thee even with the ground, and thy children within thee; and they shall not leave in thee one stone upon another; because thou knewest not the time of thy visitation. ",
      "45": "And he went into the temple, and began to cast out them that sold therein, and them that bought;",
      "46": "Saying unto them,  It is written, My house is the house of prayer: but ye have made it a den of thieves. ",
      "47": "And he taught daily in the temple. But the chief priests and the scribes and the chief of the people sought to destroy him,",
      "48": "And could not find what they might do: for all the people were very attentive to hear him.  "
    },
    "20": {
      "1": "And it came to pass,  that  on one of those days, as he taught the people in the temple, and preached the gospel, the chief priests and the scribes came upon  him  with the elders,",
      "2": "And spake unto him, saying, Tell us, by what authority doest thou these things? or who is he that gave thee this authority?",
      "3": "And he answered and said unto them,  I will also ask you one thing; and answer me: ",
      "4": " The baptism of John, was it from heaven, or of men? ",
      "5": "And they reasoned with themselves, saying, If we shall say, From heaven; he will say, Why then believed ye him not?",
      "6": "But and if we say, Of men; all the people will stone us: for they be persuaded that John was a prophet.",
      "7": "And they answered, that they could not tell whence  it was .",
      "8": "And Jesus said unto them,  Neither tell I you by what authority I do these things.  ",
      "9": "Then began he to speak to the people this parable;  A certain man planted a vineyard, and let it forth to husbandmen, and went into a far country for a long time. ",
      "10": " And at the season he sent a servant to the husbandmen, that they should give him of the fruit of the vineyard: but the husbandmen beat him, and sent  him  away empty. ",
      "11": " And again he sent another servant: and they beat him also, and entreated  him  shamefully, and sent  him  away empty. ",
      "12": " And again he sent a third: and they wounded him also, and cast  him  out. ",
      "13": " Then said the lord of the vineyard, What shall I do? I will send my beloved son: it may be they will reverence  him  when they see him. ",
      "14": " But when the husbandmen saw him, they reasoned among themselves, saying, This is the heir: come, let us kill him, that the inheritance may be ours. ",
      "15": " So they cast him out of the vineyard, and killed  him . What therefore shall the lord of the vineyard do unto them? ",
      "16": " He shall come and destroy these husbandmen, and shall give the vineyard to others.  And when they heard  it , they said, God forbid.",
      "17": "And he beheld them, and said,  What is this then that is written,  The stone which the builders rejected, the same is become the head of the corner?  ",
      "18": " Whosoever shall fall upon that stone shall be broken; but on whomsoever it shall fall, it will grind him to powder. ",
      "19": "And the chief priests and the scribes the same hour sought to lay hands on him; and they feared the people: for they perceived that he had spoken this parable against them. ",
      "20": "And they watched  him , and sent forth spies, which should feign themselves just men, that they might take hold of his words, that so they might deliver him unto the power and authority of the governor.",
      "21": "And they asked him, saying, Master, we know that thou sayest and teachest rightly, neither acceptest thou the person  of any , but teachest the way of God truly: ",
      "22": "Is it lawful for us to give tribute unto Caesar, or no?",
      "23": "But he perceived their craftiness, and said unto them,  Why tempt ye me? ",
      "24": " Shew me a penny. Whose image and superscription hath it?  They answered and said, Caesar's.",
      "25": "And he said unto them,  Render therefore unto Caesar the things which be Caesar's, and unto God the things which be God's. ",
      "26": "And they could not take hold of his words before the people: and they marvelled at his answer, and held their peace. ",
      "27": "Then came to  him  certain of the Sadducees, which deny that there is any resurrection; and they asked him,",
      "28": "Saying, Master, Moses wrote unto us, If any man's brother die, having a wife, and he die without children, that his brother should take his wife, and raise up seed unto his brother.",
      "29": "There were therefore seven brethren: and the first took a wife, and died without children.",
      "30": "And the second took her to wife, and he died childless.",
      "31": "And the third took her; and in like manner the seven also: and they left no children, and died.",
      "32": " Last of all the woman died also.",
      "33": "Therefore in the resurrection whose wife of them is she? for seven had her to wife.",
      "34": "And Jesus answering said unto them,  The children of this world marry, and are given in marriage: ",
      "35": " But they which shall be accounted worthy to obtain that world, and the resurrection from the dead, neither marry, nor are given in marriage: ",
      "36": " Neither can they die any more: for they are equal unto the angels; and are the children of God, being the children of the resurrection. ",
      "37": " Now that the dead are raised, even Moses shewed at the bush, when he calleth the Lord the God of Abraham, and the God of Isaac, and the God of Jacob. ",
      "38": " For he is not a God of the dead, but of the living: for all live unto him.  ",
      "39": "Then certain of the scribes answering said, Master, thou hast well said.",
      "40": "And after that they durst not ask him any  question at all .",
      "41": "And he said unto them,  How say they that Christ is David's son? ",
      "42": " And David himself saith in the book of Psalms,  The LORD said unto my Lord, Sit thou on my right hand,  ",
      "43": "  Till I make thine enemies thy footstool.  ",
      "44": " David therefore calleth him Lord, how is he then his son? ",
      "45": "Then in the audience of all the people he said unto his disciples,",
      "46": " Beware of the scribes, which desire to walk in long robes, and love greetings in the markets, and the highest seats in the synagogues, and the chief rooms at feasts; ",
      "47": " Which devour widows' houses, and for a shew make long prayers: the same shall receive greater damnation.  "
    },
    "21": {
      "1": "And he looked up, and saw the rich men casting their gifts into the treasury.",
      "2": "And he saw also a certain poor widow casting in thither two mites.",
      "3": "And he said,  Of a truth I say unto you, that this poor widow hath cast in more than they all: ",
      "4": " For all these have of their abundance cast in unto the offerings of God: but she of her penury hath cast in all the living that she had.  ",
      "5": "And as some spake of the temple, how it was adorned with goodly stones and gifts, he said,",
      "6": "  As for  these things which ye behold, the days will come, in the which there shall not be left one stone upon another, that shall not be thrown down. ",
      "7": "And they asked him, saying, Master, but when shall these things be? and what sign  will there be  when these things shall come to pass?",
      "8": "And he said,  Take heed that ye be not deceived: for many shall come in my name, saying, I am  Christ ; and the time draweth near: go ye not therefore after them.  ",
      "9": " But when ye shall hear of wars and commotions, be not terrified: for these things must first come to pass; but the end  is  not by and by. ",
      "10": "Then said he unto them,  Nation shall rise against nation, and kingdom against kingdom: ",
      "11": " And great earthquakes shall be in divers places, and famines, and pestilences; and fearful sights and great signs shall there be from heaven. ",
      "12": " But before all these, they shall lay their hands on you, and persecute  you , delivering  you  up to the synagogues, and into prisons, being brought before kings and rulers for my name's sake. ",
      "13": " And it shall turn to you for a testimony. ",
      "14": " Settle  it  therefore in your hearts, not to meditate before what ye shall answer: ",
      "15": " For I will give you a mouth and wisdom, which all your adversaries shall not be able to gainsay nor resist. ",
      "16": " And ye shall be betrayed both by parents, and brethren, and kinsfolks, and friends; and  some  of you shall they cause to be put to death. ",
      "17": " And ye shall be hated of all  men  for my name's sake. ",
      "18": " But there shall not an hair of your head perish. ",
      "19": " In your patience possess ye your souls.  ",
      "20": " And when ye shall see Jerusalem compassed with armies, then know that the desolation thereof is nigh. ",
      "21": " Then let them which are in Judaea flee to the mountains; and let them which are in the midst of it depart out; and let not them that are in the countries enter thereinto. ",
      "22": " For these be the days of vengeance, that all things which are written may be fulfilled. ",
      "23": " But woe unto them that are with child, and to them that give suck, in those days! for there shall be great distress in the land, and wrath upon this people. ",
      "24": " And they shall fall by the edge of the sword, and shall be led away captive into all nations: and Jerusalem shall be trodden down of the Gentiles, until the times of the Gentiles be fulfilled. ",
      "25": " And there shall be signs in the sun, and in the moon, and in the stars; and upon the earth distress of nations, with perplexity; the sea and the waves roaring; ",
      "26": " Men's hearts failing them for fear, and for looking after those things which are coming on the earth: for the powers of heaven shall be shaken. ",
      "27": " And then shall they see the Son of man coming in a cloud with power and great glory. ",
      "28": " And when these things begin to come to pass, then look up, and lift up your heads; for your redemption draweth nigh.  ",
      "29": "And he spake to them a parable;  Behold the fig tree, and all the trees; ",
      "30": " When they now shoot forth, ye see and know of your own selves that summer is now nigh at hand. ",
      "31": " So likewise ye, when ye see these things come to pass, know ye that the kingdom of God is nigh at hand. ",
      "32": " Verily I say unto you, This generation shall not pass away, till all be fulfilled. ",
      "33": " Heaven and earth shall pass away: but my words shall not pass away. ",
      "34": " And take heed to yourselves, lest at any time your hearts be overcharged with surfeiting, and drunkenness, and cares of this life, and  so  that day come upon you unawares. ",
      "35": " For as a snare shall it come on all them that dwell on the face of the whole earth. ",
      "36": " Watch ye therefore, and pray always, that ye may be accounted worthy to escape all these things that shall come to pass, and to stand before the Son of man. ",
      "37": "And in the day time he was teaching in the temple; and at night he went out, and abode in the mount that is called  the mount  of Olives.",
      "38": "And all the people came early in the morning to him in the temple, for to hear him. "
    },
    "22": {
      "1": "Now the feast of unleavened bread drew nigh, which is called the Passover.",
      "2": "And the chief priests and scribes sought how they might kill him; for they feared the people.",
      "3": "Then entered Satan into Judas surnamed Iscariot, being of the number of the twelve.",
      "4": "And he went his way, and communed with the chief priests and captains, how he might betray him unto them.",
      "5": "And they were glad, and covenanted to give him money.",
      "6": "And he promised, and sought opportunity to betray him unto them in the absence of the multitude.  ",
      "7": "Then came the day of unleavened bread, when the passover must be killed.",
      "8": "And he sent Peter and John, saying,  Go and prepare us the passover, that we may eat. ",
      "9": "And they said unto him, Where wilt thou that we prepare?",
      "10": "And he said unto them,  Behold, when ye are entered into the city, there shall a man meet you, bearing a pitcher of water; follow him into the house where he entereth in. ",
      "11": " And ye shall say unto the goodman of the house, The Master saith unto thee, Where is the guestchamber, where I shall eat the passover with my disciples? ",
      "12": " And he shall shew you a large upper room furnished: there make ready. ",
      "13": "And they went, and found as he had said unto them: and they made ready the passover.",
      "14": "And when the hour was come, he sat down, and the twelve apostles with him.",
      "15": "And he said unto them,  With desire I have desired to eat this passover with you before I suffer:  ",
      "16": " For I say unto you, I will not any more eat thereof, until it be fulfilled in the kingdom of God. ",
      "17": "And he took the cup, and gave thanks, and said,  Take this, and divide  it  among yourselves: ",
      "18": " For I say unto you, I will not drink of the fruit of the vine, until the kingdom of God shall come. ",
      "19": "And he took bread, and gave thanks, and brake  it , and gave unto them, saying,  This is my body which is given for you: this do in remembrance of me. ",
      "20": "Likewise also the cup after supper, saying,  This cup  is  the new testament in my blood, which is shed for you.  ",
      "21": " But, behold, the hand of him that betrayeth me  is  with me on the table. ",
      "22": " And truly the Son of man goeth, as it was determined: but woe unto that man by whom he is betrayed! ",
      "23": "And they began to enquire among themselves, which of them it was that should do this thing.",
      "24": "And there was also a strife among them, which of them should be accounted the greatest.",
      "25": "And he said unto them,  The kings of the Gentiles exercise lordship over them; and they that exercise authority upon them are called benefactors. ",
      "26": " But ye  shall  not  be  so: but he that is greatest among you, let him be as the younger; and he that is chief, as he that doth serve. ",
      "27": " For whether  is  greater, he that sitteth at meat, or he that serveth?  is  not he that sitteth at meat? but I am among you as he that serveth. ",
      "28": "  Ye are they which have continued with me in my temptations. ",
      "29": " And I appoint unto you a kingdom, as my Father hath appointed unto me; ",
      "30": " That ye may eat and drink at my table in my kingdom, and sit on thrones judging the twelve tribes of Israel. ",
      "31": "And the Lord said,  Simon, Simon, behold, Satan hath desired  to have  you, that he may sift  you  as wheat: ",
      "32": " But I have prayed for thee, that thy faith fail not: and when thou art converted, strengthen thy brethren. ",
      "33": "And he said unto him, Lord, I am ready to go with thee, both into prison, and to death.",
      "34": "And he said,  I tell thee, Peter, the cock shall not crow this day, before that thou shalt thrice deny that thou knowest me. ",
      "35": "And he said unto them,  When I sent you without purse, and scrip, and shoes, lacked ye any thing?  And they said, Nothing.",
      "36": "Then said he unto them,  But now, he that hath a purse, let him take  it , and likewise  his  scrip: and he that hath no sword, let him sell his garment, and buy one. ",
      "37": " For I say unto you, that this that is written must yet be accomplished in me,  And he was reckoned among the transgressors:  for the things concerning me have an end. ",
      "38": "And they said, Lord, behold, here  are  two swords. And he said unto them,  It is enough.  ",
      "39": "And he came out, and went, as he was wont, to the mount of Olives; and his disciples also followed him.",
      "40": "And when he was at the place, he said unto them,  Pray that ye enter not into temptation. ",
      "41": "And he was withdrawn from them about a stone's cast, and kneeled down, and prayed,",
      "42": "Saying,  Father, if thou be willing, remove this cup from me: nevertheless not my will, but thine, be done.  ",
      "43": "And there appeared an angel unto him from heaven, strengthening him.",
      "44": "And being in an agony he prayed more earnestly: and his sweat was as it were great drops of blood falling down to the ground.",
      "45": "And when he rose up from prayer, and was come to his disciples, he found them sleeping for sorrow,",
      "46": "And said unto them,  Why sleep ye? rise and pray, lest ye enter into temptation.  ",
      "47": "And while he yet spake, behold a multitude, and he that was called Judas, one of the twelve, went before them, and drew near unto Jesus to kiss him.",
      "48": "But Jesus said unto him,  Judas, betrayest thou the Son of man with a kiss? ",
      "49": "When they which were about him saw what would follow, they said unto him, Lord, shall we smite with the sword?",
      "50": "And one of them smote the servant of the high priest, and cut off his right ear.",
      "51": "And Jesus answered and said,  Suffer ye thus far.  And he touched his ear, and healed him.",
      "52": "Then Jesus said unto the chief priests, and captains of the temple, and the elders, which were come to him,  Be ye come out, as against a thief, with swords and staves? ",
      "53": " When I was daily with you in the temple, ye stretched forth no hands against me: but this is your hour, and the power of darkness.  ",
      "54": "Then took they him, and led  him , and brought him into the high priest's house. And Peter followed afar off.",
      "55": "And when they had kindled a fire in the midst of the hall, and were set down together, Peter sat down among them.",
      "56": "But a certain maid beheld him as he sat by the fire, and earnestly looked upon him, and said, This man was also with him.",
      "57": "And he denied him, saying, Woman, I know him not.",
      "58": "And after a little while another saw him, and said, Thou art also of them. And Peter said, Man, I am not.",
      "59": "And about the space of one hour after another confidently affirmed, saying, Of a truth this  fellow  also was with him: for he is a Galilaean.",
      "60": "And Peter said, Man, I know not what thou sayest. And immediately, while he yet spake, the cock crew.",
      "61": "And the Lord turned, and looked upon Peter. And Peter remembered the word of the Lord, how he had said unto him,  Before the cock crow, thou shalt deny me thrice. ",
      "62": "And Peter went out, and wept bitterly. ",
      "63": "And the men that held Jesus mocked him, and smote  him .",
      "64": "And when they had blindfolded him, they struck him on the face, and asked him, saying, Prophesy, who is it that smote thee?",
      "65": "And many other things blasphemously spake they against him.",
      "66": "And as soon as it was day, the elders of the people and the chief priests and the scribes came together, and led him into their council, saying,",
      "67": " Art thou the Christ? tell us. And he said unto them,  If I tell you, ye will not believe: ",
      "68": " And if I also ask  you , ye will not answer me, nor let  me  go. ",
      "69": " Hereafter shall the Son of man sit on the right hand of the power of God. ",
      "70": "Then said they all, Art thou then the Son of God? And he said unto them,  Ye say that I am. ",
      "71": "And they said, What need we any further witness? for we ourselves have heard of his own mouth. "
    },
    "23": {
      "1": "And the whole multitude of them arose, and led him unto Pilate.",
      "2": "And they began to accuse him, saying, We found this  fellow  perverting the nation, and forbidding to give tribute to Caesar, saying that he himself is Christ a King.",
      "3": "And Pilate asked him, saying, Art thou the King of the Jews? And he answered him and said,  Thou sayest  it . ",
      "4": "Then said Pilate to the chief priests and  to  the people, I find no fault in this man.",
      "5": "And they were the more fierce, saying, He stirreth up the people, teaching throughout all Jewry, beginning from Galilee to this place.",
      "6": "When Pilate heard of Galilee, he asked whether the man were a Galilaean.",
      "7": "And as soon as he knew that he belonged unto Herod's jurisdiction, he sent him to Herod, who himself also was at Jerusalem at that time.",
      "8": "And when Herod saw Jesus, he was exceeding glad: for he was desirous to see him of a long  season , because he had heard many things of him; and he hoped to have seen some miracle done by him.",
      "9": "Then he questioned with him in many words; but he answered him nothing.",
      "10": "And the chief priests and scribes stood and vehemently accused him.",
      "11": "And Herod with his men of war set him at nought, and mocked  him , and arrayed him in a gorgeous robe, and sent him again to Pilate.",
      "12": "And the same day Pilate and Herod were made friends together: for before they were at enmity between themselves. ",
      "13": "And Pilate, when he had called together the chief priests and the rulers and the people,",
      "14": "Said unto them, Ye have brought this man unto me, as one that perverteth the people: and, behold, I, having examined  him  before you, have found no fault in this man touching those things whereof ye accuse him:",
      "15": "No, nor yet Herod: for I sent you to him; and, lo, nothing worthy of death is done unto him.",
      "16": "I will therefore chastise him, and release  him .",
      "17": "(For of necessity he must release one unto them at the feast.)",
      "18": "And they cried out all at once, saying, Away with this  man , and release unto us Barabbas:",
      "19": "(Who for a certain sedition made in the city, and for murder, was cast into prison.)",
      "20": "Pilate therefore, willing to release Jesus, spake again to them.",
      "21": "But they cried, saying, Crucify  him , crucify him.",
      "22": "And he said unto them the third time, Why, what evil hath he done? I have found no cause of death in him: I will therefore chastise him, and let  him  go.",
      "23": "And they were instant with loud voices, requiring that he might be crucified. And the voices of them and of the chief priests prevailed.",
      "24": "And Pilate gave sentence that it should be as they required. ",
      "25": "And he released unto them him that for sedition and murder was cast into prison, whom they had desired; but he delivered Jesus to their will. ",
      "26": "And as they led him away, they laid hold upon one Simon, a Cyrenian, coming out of the country, and on him they laid the cross, that he might bear  it  after Jesus.",
      "27": "And there followed him a great company of people, and of women, which also bewailed and lamented him.",
      "28": "But Jesus turning unto them said,  Daughters of Jerusalem, weep not for me, but weep for yourselves, and for your children. ",
      "29": " For, behold, the days are coming, in the which they shall say, Blessed  are  the barren, and the wombs that never bare, and the paps which never gave suck. ",
      "30": "  Then shall they begin to say to the mountains, Fall on us; and to the hills, Cover us.  ",
      "31": " For if they do these things in a green tree, what shall be done in the dry?  ",
      "32": "And there were also two other, malefactors, led with him to be put to death.",
      "33": "And when they were come to the place, which is called Calvary, there they crucified him, and the malefactors, one on the right hand, and the other on the left. ",
      "34": "Then said Jesus,  Father, forgive them; for they know not what they do.  And they parted his raiment, and cast lots.",
      "35": "And the people stood beholding. And the rulers also with them derided  him , saying, He saved others; let him save himself, if he be Christ, the chosen of God.",
      "36": "And the soldiers also mocked him, coming to him, and offering him vinegar,",
      "37": "And saying, If thou be the king of the Jews, save thyself.",
      "38": "And a superscription also was written over him in letters of Greek, and Latin, and Hebrew, THIS IS THE KING OF THE JEWS.",
      "39": "And one of the malefactors which were hanged railed on him, saying, If thou be Christ, save thyself and us.",
      "40": "But the other answering rebuked him, saying, Dost not thou fear God, seeing thou art in the same condemnation?",
      "41": "And we indeed justly; for we receive the due reward of our deeds: but this man hath done nothing amiss.",
      "42": "And he said unto Jesus, Lord, remember me when thou comest into thy kingdom.",
      "43": "And Jesus said unto him,  Verily I say unto thee, To day shalt thou be with me in paradise.  ",
      "44": "And it was about the sixth hour, and there was a darkness over all the earth until the ninth hour. ",
      "45": "And the sun was darkened, and the veil of the temple was rent in the midst.",
      "46": "And when Jesus had cried with a loud voice, he said,  Father,  into thy hands I commend my spirit:   and having said thus, he gave up the ghost.",
      "47": "Now when the centurion saw what was done, he glorified God, saying, Certainly this was a righteous man.",
      "48": "And all the people that came together to that sight, beholding the things which were done, smote their breasts, and returned.",
      "49": "And all his acquaintance, and the women that followed him from Galilee, stood afar off, beholding these things. ",
      "50": "And, behold,  there was  a man named Joseph, a counsellor;  and he was  a good man, and a just:",
      "51": "(The same had not consented to the counsel and deed of them;)  he was  of Arimathaea, a city of the Jews: who also himself waited for the kingdom of God.",
      "52": "This  man  went unto Pilate, and begged the body of Jesus.",
      "53": "And he took it down, and wrapped it in linen, and laid it in a sepulchre that was hewn in stone, wherein never man before was laid.",
      "54": "And that day was the preparation, and the sabbath drew on.",
      "55": "And the women also, which came with him from Galilee, followed after, and beheld the sepulchre, and how his body was laid.",
      "56": "And they returned, and prepared spices and ointments; and rested the sabbath day according to the commandment. "
    },
    "24": {
      "1": "Now upon the first  day  of the week, very early in the morning, they came unto the sepulchre, bringing the spices which they had prepared, and certain  others  with them.",
      "2": "And they found the stone rolled away from the sepulchre.",
      "3": "And they entered in, and found not the body of the Lord Jesus.",
      "4": "And it came to pass, as they were much perplexed thereabout, behold, two men stood by them in shining garments:",
      "5": "And as they were afraid, and bowed down  their  faces to the earth, they said unto them, Why seek ye the living among the dead? ",
      "6": "He is not here, but is risen: remember how he spake unto you when he was yet in Galilee,",
      "7": "Saying,  The Son of man must be delivered into the hands of sinful men, and be crucified, and the third day rise again. ",
      "8": "And they remembered his words,",
      "9": "And returned from the sepulchre, and told all these things unto the eleven, and to all the rest.",
      "10": " It was Mary Magdalene, and Joanna, and Mary  the mother  of James, and other  women that were  with them, which told these things unto the apostles.",
      "11": "And their words seemed to them as idle tales, and they believed them not.",
      "12": "Then arose Peter, and ran unto the sepulchre; and stooping down, he beheld the linen clothes laid by themselves, and departed, wondering in himself at that which was come to pass. ",
      "13": "And, behold, two of them went that same day to a village called Emmaus, which was from Jerusalem  about  threescore furlongs.",
      "14": "And they talked together of all these things which had happened.",
      "15": "And it came to pass, that, while they communed  together  and reasoned, Jesus himself drew near, and went with them.",
      "16": "But their eyes were holden that they should not know him.",
      "17": "And he said unto them,  What manner of communications  are  these that ye have one to another, as ye walk, and are sad? ",
      "18": "And the one of them, whose name was Cleopas, answering said unto him, Art thou only a stranger in Jerusalem, and hast not known the things which are come to pass there in these days?",
      "19": "And he said unto them,  What things?  And they said unto him, Concerning Jesus of Nazareth, which was a prophet mighty in deed and word before God and all the people:",
      "20": "And how the chief priests and our rulers delivered him to be condemned to death, and have crucified him.",
      "21": "But we trusted that it had been he which should have redeemed Israel: and beside all this, to day is the third day since these things were done.",
      "22": "Yea, and certain women also of our company made us astonished, which were early at the sepulchre;",
      "23": "And when they found not his body, they came, saying, that they had also seen a vision of angels, which said that he was alive.",
      "24": "And certain of them which were with us went to the sepulchre, and found  it  even so as the women had said: but him they saw not.",
      "25": "Then he said unto them,  O fools, and slow of heart to believe all that the prophets have spoken: ",
      "26": " Ought not Christ to have suffered these things, and to enter into his glory? ",
      "27": "And beginning at Moses and all the prophets, he expounded unto them in all the scriptures the things concerning himself.",
      "28": "And they drew nigh unto the village, whither they went: and he made as though he would have gone further.",
      "29": "But they constrained him, saying, Abide with us: for it is toward evening, and the day is far spent. And he went in to tarry with them.",
      "30": "And it came to pass, as he sat at meat with them, he took bread, and blessed  it , and brake, and gave to them.",
      "31": "And their eyes were opened, and they knew him; and he vanished out of their sight. ",
      "32": "And they said one to another, Did not our heart burn within us, while he talked with us by the way, and while he opened to us the scriptures?",
      "33": "And they rose up the same hour, and returned to Jerusalem, and found the eleven gathered together, and them that were with them,",
      "34": "Saying, The Lord is risen indeed, and hath appeared to Simon.",
      "35": "And they told what things  were done  in the way, and how he was known of them in breaking of bread. ",
      "36": "And as they thus spake, Jesus himself stood in the midst of them, and saith unto them,  Peace  be  unto you. ",
      "37": "But they were terrified and affrighted, and supposed that they had seen a spirit.",
      "38": "And he said unto them,  Why are ye troubled? and why do thoughts arise in your hearts? ",
      "39": " Behold my hands and my feet, that it is I myself: handle me, and see; for a spirit hath not flesh and bones, as ye see me have. ",
      "40": "And when he had thus spoken, he shewed them  his  hands and  his  feet.",
      "41": "And while they yet believed not for joy, and wondered, he said unto them,  Have ye here any meat? ",
      "42": "And they gave him a piece of a broiled fish, and of an honeycomb.",
      "43": "And he took  it , and did eat before them.",
      "44": "And he said unto them,  These  are  the words which I spake unto you, while I was yet with you, that all things must be fulfilled, which were written in the law of Moses, and  in  the prophets, and  in  the psalms, concerning me. ",
      "45": "Then opened he their understanding, that they might understand the scriptures,",
      "46": "And said unto them,  Thus it is written, and thus it behoved Christ to suffer, and to rise from the dead the third day: ",
      "47": " And that repentance and remission of sins should be preached in his name among all nations, beginning at Jerusalem. ",
      "48": " And ye are witnesses of these things. ",
      "49": " And, behold, I send the promise of my Father upon you: but tarry ye in the city of Jerusalem, until ye be endued with power from on high.  ",
      "50": "And he led them out as far as to Bethany, and he lifted up his hands, and blessed them.",
      "51": "And it came to pass, while he blessed them, he was parted from them, and carried up into heaven.",
      "52": "And they worshipped him, and returned to Jerusalem with great joy:",
      "53": "And were continually in the temple, praising and blessing God. Amen. "
    }
  },
  "john": {
    "1": {
      "1": "In the beginning was the Word, and the Word was with God, and the Word was God.",
      "2": "The same was in the beginning with God.",
      "3": "All things were made by him; and without him was not any thing made that was made.",
      "4": "In him was life; and the life was the light of men. ",
      "5": "And the light shineth in darkness; and the darkness comprehended it not. ",
      "6": "There was a man sent from God, whose name  was  John.",
      "7": "The same came for a witness, to bear witness of the Light, that all  men  through him might believe.",
      "8": "He was not that Light, but  was sent  to bear witness of that Light.",
      "9": " That  was the true Light, which lighteth every man that cometh into the world.",
      "10": "He was in the world, and the world was made by him, and the world knew him not.",
      "11": "He came unto his own, and his own received him not.",
      "12": "But as many as received him, to them gave he power to become the sons of God,  even  to them that believe on his name: ",
      "13": "Which were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God.",
      "14": "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth. ",
      "15": "John bare witness of him, and cried, saying, This was he of whom I spake, He that cometh after me is preferred before me: for he was before me.",
      "16": "And of his fulness have all we received, and grace for grace.",
      "17": "For the law was given by Moses,  but  grace and truth came by Jesus Christ.",
      "18": "No man hath seen God at any time; the only begotten Son, which is in the bosom of the Father, he hath declared  him . ",
      "19": "And this is the record of John, when the Jews sent priests and Levites from Jerusalem to ask him, Who art thou?",
      "20": "And he confessed, and denied not; but confessed, I am not the Christ.",
      "21": "And they asked him, What then? Art thou Elias? And he saith, I am not. Art thou that prophet? And he answered, No. ",
      "22": "Then said they unto him, Who art thou? that we may give an answer to them that sent us. What sayest thou of thyself?",
      "23": "He said, I  am   the voice of one crying in the wilderness, Make straight the way of the Lord,  as said the prophet Esaias.",
      "24": "And they which were sent were of the Pharisees.",
      "25": "And they asked him, and said unto him, Why baptizest thou then, if thou be not that Christ, nor Elias, neither that prophet?",
      "26": "John answered them, saying, I baptize with water: but there standeth one among you, whom ye know not;",
      "27": "He it is, who coming after me is preferred before me, whose shoe's latchet I am not worthy to unloose.",
      "28": "These things were done in Bethabara beyond Jordan, where John was baptizing. ",
      "29": "The next day John seeth Jesus coming unto him, and saith, Behold the Lamb of God, which taketh away the sin of the world. ",
      "30": "This is he of whom I said, After me cometh a man which is preferred before me: for he was before me.",
      "31": "And I knew him not: but that he should be made manifest to Israel, therefore am I come baptizing with water.",
      "32": "And John bare record, saying, I saw the Spirit descending from heaven like a dove, and it abode upon him.",
      "33": "And I knew him not: but he that sent me to baptize with water, the same said unto me, Upon whom thou shalt see the Spirit descending, and remaining on him, the same is he which baptizeth with the Holy Ghost.",
      "34": "And I saw, and bare record that this is the Son of God.",
      "35": "Again the next day after John stood, and two of his disciples;",
      "36": "And looking upon Jesus as he walked, he saith, Behold the Lamb of God! ",
      "37": "And the two disciples heard him speak, and they followed Jesus.",
      "38": "Then Jesus turned, and saw them following, and saith unto them,  What seek ye?  They said unto him, Rabbi, (which is to say, being interpreted, Master,) where dwellest thou? ",
      "39": "He saith unto them,  Come and see.  They came and saw where he dwelt, and abode with him that day: for it was about the tenth hour. ",
      "40": "One of the two which heard John  speak , and followed him, was Andrew, Simon Peter's brother.",
      "41": "He first findeth his own brother Simon, and saith unto him, We have found the Messias, which is, being interpreted, the Christ. ",
      "42": "And he brought him to Jesus. And when Jesus beheld him, he said,  Thou art Simon the son of Jona: thou shalt be called Cephas,  which is by interpretation,  A stone.  ",
      "43": "The day following Jesus would go forth into Galilee, and findeth Philip, and saith unto him,  Follow me. ",
      "44": "Now Philip was of Bethsaida, the city of Andrew and Peter.",
      "45": "Philip findeth Nathanael, and saith unto him, We have found him, of whom Moses in the law, and the prophets, did write, Jesus of Nazareth, the son of Joseph.",
      "46": "And Nathanael said unto him, Can there any good thing come out of Nazareth? Philip saith unto him, Come and see.",
      "47": "Jesus saw Nathanael coming to him, and saith of him,  Behold an Israelite indeed, in whom is no guile! ",
      "48": "Nathanael saith unto him, Whence knowest thou me? Jesus answered and said unto him,  Before that Philip called thee, when thou wast under the fig tree, I saw thee. ",
      "49": "Nathanael answered and saith unto him, Rabbi, thou art the Son of God; thou art the King of Israel.",
      "50": "Jesus answered and said unto him,  Because I said unto thee, I saw thee under the fig tree, believest thou? thou shalt see greater things than these. ",
      "51": "And he saith unto him,  Verily, verily, I say unto you, Hereafter ye shall see heaven open, and the angels of God ascending and descending upon the Son of man.  "
    },
    "2": {
      "1": "And the third day there was a marriage in Cana of Galilee; and the mother of Jesus was there:",
      "2": "And both Jesus was called, and his disciples, to the marriage.",
      "3": "And when they wanted wine, the mother of Jesus saith unto him, They have no wine.",
      "4": "Jesus saith unto her,  Woman, what have I to do with thee? mine hour is not yet come. ",
      "5": "His mother saith unto the servants, Whatsoever he saith unto you, do  it .",
      "6": "And there were set there six waterpots of stone, after the manner of the purifying of the Jews, containing two or three firkins apiece.",
      "7": "Jesus saith unto them,  Fill the waterpots with water.  And they filled them up to the brim.",
      "8": "And he saith unto them,  Draw out now, and bear unto the governor of the feast.  And they bare  it .",
      "9": " When the ruler of the feast had tasted the water that was made wine, and knew not whence it was: (but the servants which drew the water knew;) the governor of the feast called the bridegroom,",
      "10": "And saith unto him, Every man at the beginning doth set forth good wine; and when men have well drunk, then that which is worse:  but  thou hast kept the good wine until now.",
      "11": "This beginning of miracles did Jesus in Cana of Galilee, and manifested forth his glory; and his disciples believed on him. ",
      "12": "After this he went down to Capernaum, he, and his mother, and his brethren, and his disciples: and they continued there not many days.",
      "13": "And the Jews' passover was at hand, and Jesus went up to Jerusalem,",
      "14": "And found in the temple those that sold oxen and sheep and doves, and the changers of money sitting:",
      "15": "And when he had made a scourge of small cords, he drove them all out of the temple, and the sheep, and the oxen; and poured out the changers' money, and overthrew the tables;",
      "16": "And said unto them that sold doves,  Take these things hence; make not my Father's house an house of merchandise. ",
      "17": "And his disciples remembered that it was written,  The zeal of thine house hath eaten me up. ",
      "18": "Then answered the Jews and said unto him, What sign shewest thou unto us, seeing that thou doest these things?",
      "19": "Jesus answered and said unto them,  Destroy this temple, and in three days I will raise it up. ",
      "20": "Then said the Jews, Forty and six years was this temple in building, and wilt thou rear it up in three days?",
      "21": "But he spake of the temple of his body.",
      "22": "When therefore he was risen from the dead, his disciples remembered that he had said this unto them; and they believed the scripture, and the word which Jesus had said. ",
      "23": "Now when he was in Jerusalem at the passover, in the feast  day , many believed in his name, when they saw the miracles which he did.",
      "24": "But Jesus did not commit himself unto them, because he knew all  men ,",
      "25": "And needed not that any should testify of man: for he knew what was in man. "
    },
    "3": {
      "1": " There was a man of the Pharisees, named Nicodemus, a ruler of the Jews:",
      "2": "The same came to Jesus by night, and said unto him, Rabbi, we know that thou art a teacher come from God: for no man can do these miracles that thou doest, except God be with him.",
      "3": "Jesus answered and said unto him,  Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God.  ",
      "4": "Nicodemus saith unto him, How can a man be born when he is old? can he enter the second time into his mother's womb, and be born?",
      "5": "Jesus answered,  Verily, verily, I say unto thee, Except a man be born of water and  of  the Spirit, he cannot enter into the kingdom of God. ",
      "6": " That which is born of the flesh is flesh; and that which is born of the Spirit is spirit. ",
      "7": " Marvel not that I said unto thee, Ye must be born again.  ",
      "8": " The wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh, and whither it goeth: so is every one that is born of the Spirit. ",
      "9": "Nicodemus answered and said unto him, How can these things be?",
      "10": "Jesus answered and said unto him,  Art thou a master of Israel, and knowest not these things? ",
      "11": " Verily, verily, I say unto thee, We speak that we do know, and testify that we have seen; and ye receive not our witness. ",
      "12": " If I have told you earthly things, and ye believe not, how shall ye believe, if I tell you  of  heavenly things? ",
      "13": " And no man hath ascended up to heaven, but he that came down from heaven,  even  the Son of man which is in heaven. ",
      "14": " And as Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up: ",
      "15": " That whosoever believeth in him should not perish, but have eternal life. ",
      "16": " For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life. ",
      "17": " For God sent not his Son into the world to condemn the world; but that the world through him might be saved. ",
      "18": " He that believeth on him is not condemned: but he that believeth not is condemned already, because he hath not believed in the name of the only begotten Son of God. ",
      "19": " And this is the condemnation, that light is come into the world, and men loved darkness rather than light, because their deeds were evil. ",
      "20": " For every one that doeth evil hateth the light, neither cometh to the light, lest his deeds should be reproved.  ",
      "21": " But he that doeth truth cometh to the light, that his deeds may be made manifest, that they are wrought in God.  ",
      "22": "After these things came Jesus and his disciples into the land of Judaea; and there he tarried with them, and baptized.",
      "23": "And John also was baptizing in Aenon near to Salim, because there was much water there: and they came, and were baptized.",
      "24": "For John was not yet cast into prison.",
      "25": "Then there arose a question between  some  of John's disciples and the Jews about purifying.",
      "26": "And they came unto John, and said unto him, Rabbi, he that was with thee beyond Jordan, to whom thou barest witness, behold, the same baptizeth, and all  men  come to him.",
      "27": "John answered and said, A man can receive nothing, except it be given him from heaven. ",
      "28": "Ye yourselves bear me witness, that I said, I am not the Christ, but that I am sent before him.",
      "29": "He that hath the bride is the bridegroom: but the friend of the bridegroom, which standeth and heareth him, rejoiceth greatly because of the bridegroom's voice: this my joy therefore is fulfilled.",
      "30": "He must increase, but I  must  decrease.",
      "31": "He that cometh from above is above all: he that is of the earth is earthly, and speaketh of the earth: he that cometh from heaven is above all.",
      "32": "And what he hath seen and heard, that he testifieth; and no man receiveth his testimony.",
      "33": "He that hath received his testimony hath set to his seal that God is true.",
      "34": "For he whom God hath sent speaketh the words of God: for God giveth not the Spirit by measure  unto him .",
      "35": "The Father loveth the Son, and hath given all things into his hand.",
      "36": "He that believeth on the Son hath everlasting life: and he that believeth not the Son shall not see life; but the wrath of God abideth on him. "
    }
  }
};

