
	
export const bib_verses = {
  "hebrews": {
    "11": {
      "1": "Now faith is the substance of things hoped for, the evidence of things not seen. ",
      "2": "For by it the elders obtained a good report.",
      "3": "Through faith we understand that the worlds were framed by the word of God, so that things which are seen were not made of things which do appear. ",
      "4": "By faith Abel offered unto God a more excellent sacrifice than Cain, by which he obtained witness that he was righteous, God testifying of his gifts: and by it he being dead yet speaketh. ",
      "5": "By faith Enoch was translated that he should not see death; and was not found, because God had translated him: for before his translation he had this testimony, that he pleased God.",
      "6": "But without faith  it is  impossible to please  him : for he that cometh to God must believe that he is, and  that  he is a rewarder of them that diligently seek him.",
      "7": "By faith Noah, being warned of God of things not seen as yet, moved with fear, prepared an ark to the saving of his house; by the which he condemned the world, and became heir of the righteousness which is by faith. ",
      "8": "By faith Abraham, when he was called to go out into a place which he should after receive for an inheritance, obeyed; and he went out, not knowing whither he went.",
      "9": "By faith he sojourned in the land of promise, as  in  a strange country, dwelling in tabernacles with Isaac and Jacob, the heirs with him of the same promise:",
      "10": "For he looked for a city which hath foundations, whose builder and maker  is  God.",
      "11": "Through faith also Sara herself received strength to conceive seed, and was delivered of a child when she was past age, because she judged him faithful who had promised.",
      "12": "Therefore sprang there even of one, and him as good as dead,  so many  as the stars of the sky in multitude, and as the sand which is by the sea shore innumerable.",
      "13": "These all died in faith, not having received the promises, but having seen them afar off, and were persuaded of  them , and embraced  them , and confessed that they were strangers and pilgrims on the earth. ",
      "14": "For they that say such things declare plainly that they seek a country.",
      "15": "And truly, if they had been mindful of that  country  from whence they came out, they might have had opportunity to have returned.",
      "16": "But now they desire a better  country , that is, an heavenly: wherefore God is not ashamed to be called their God: for he hath prepared for them a city.",
      "17": "By faith Abraham, when he was tried, offered up Isaac: and he that had received the promises offered up his only begotten  son ,",
      "18": "Of whom it was said,  That in Isaac shall thy seed be called:  ",
      "19": "Accounting that God  was  able to raise  him  up, even from the dead; from whence also he received him in a figure.",
      "20": "By faith Isaac blessed Jacob and Esau concerning things to come.",
      "21": "By faith Jacob, when he was a dying, blessed both the sons of Joseph; and worshipped,  leaning  upon the top of his staff.",
      "22": "By faith Joseph, when he died, made mention of the departing of the children of Israel; and gave commandment concerning his bones. ",
      "23": "By faith Moses, when he was born, was hid three months of his parents, because they saw  he was  a proper child; and they were not afraid of the king's commandment.",
      "24": "By faith Moses, when he was come to years, refused to be called the son of Pharaoh's daughter;",
      "25": "Choosing rather to suffer affliction with the people of God, than to enjoy the pleasures of sin for a season;",
      "26": "Esteeming the reproach of Christ greater riches than the treasures in Egypt: for he had respect unto the recompence of the reward. ",
      "27": "By faith he forsook Egypt, not fearing the wrath of the king: for he endured, as seeing him who is invisible.",
      "28": "Through faith he kept the passover, and the sprinkling of blood, lest he that destroyed the firstborn should touch them.",
      "29": "By faith they passed through the Red sea as by dry  land : which the Egyptians assaying to do were drowned.",
      "30": "By faith the walls of Jericho fell down, after they were compassed about seven days.",
      "31": "By faith the harlot Rahab perished not with them that believed not, when she had received the spies with peace.  ",
      "32": "And what shall I more say? for the time would fail me to tell of Gedeon, and  of  Barak, and  of  Samson, and  of  Jephthae;  of  David also, and Samuel, and  of  the prophets:",
      "33": "Who through faith subdued kingdoms, wrought righteousness, obtained promises, stopped the mouths of lions,",
      "34": "Quenched the violence of fire, escaped the edge of the sword, out of weakness were made strong, waxed valiant in fight, turned to flight the armies of the aliens.",
      "35": "Women received their dead raised to life again: and others were tortured, not accepting deliverance; that they might obtain a better resurrection:",
      "36": "And others had trial of  cruel  mockings and scourgings, yea, moreover of bonds and imprisonment:",
      "37": "They were stoned, they were sawn asunder, were tempted, were slain with the sword: they wandered about in sheepskins and goatskins; being destitute, afflicted, tormented;",
      "38": "(Of whom the world was not worthy:) they wandered in deserts, and  in  mountains, and  in  dens and caves of the earth.",
      "39": "And these all, having obtained a good report through faith, received not the promise:",
      "40": "God having provided some better thing for us, that they without us should not be made perfect.  "
    },
    "12": {
      "1": "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset  us , and let us run with patience the race that is set before us,",
      "2": "Looking unto Jesus the author and finisher of  our  faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God. ",
      "3": "For consider him that endured such contradiction of sinners against himself, lest ye be wearied and faint in your minds. ",
      "4": "Ye have not yet resisted unto blood, striving against sin.",
      "5": "And ye have forgotten the exhortation which speaketh unto you as unto children,  My son, despise not thou the chastening of the Lord, nor faint when thou art rebuked of him: ",
      "6": " For whom the Lord loveth he chasteneth, and scourgeth every son whom he receiveth. ",
      "7": "If ye endure chastening, God dealeth with you as with sons; for what son is he whom the father chasteneth not?",
      "8": "But if ye be without chastisement, whereof all are partakers, then are ye bastards, and not sons.",
      "9": "Furthermore we have had fathers of our flesh which corrected  us , and we gave  them  reverence: shall we not much rather be in subjection unto the Father of spirits, and live?",
      "10": "For they verily for a few days chastened  us  after their own pleasure; but he for  our  profit, that  we  might be partakers of his holiness. ",
      "11": "Now no chastening for the present seemeth to be joyous, but grievous: nevertheless afterward it yieldeth the peaceable fruit of righteousness unto them which are exercised thereby.",
      "12": " Wherefore lift up the hands which hang down, and the feeble knees; ",
      "13": "And make straight paths for your feet, lest that which is lame be turned out of the way; but let it rather be healed. ",
      "14": "Follow peace with all  men , and holiness, without which no man shall see the Lord:",
      "15": "Looking diligently lest any man fail of the grace of God; lest any root of bitterness springing up trouble  you , and thereby many be defiled; ",
      "16": "Lest there  be  any fornicator, or profane person, as Esau, who for one morsel of meat sold his birthright.",
      "17": "For ye know how that afterward, when he would have inherited the blessing, he was rejected: for he found no place of repentance, though he sought it carefully with tears.  ",
      "18": "For ye are not come unto the mount that might be touched, and that burned with fire, nor unto blackness, and darkness, and tempest,",
      "19": "And the sound of a trumpet, and the voice of words; which  voice  they that heard intreated that the word should not be spoken to them any more:",
      "20": "(For they could not endure that which was commanded, And if so much as a beast touch the mountain, it shall be stoned, or thrust through with a dart:",
      "21": "And so terrible was the sight,  that  Moses said, I exceedingly fear and quake:)",
      "22": "But ye are come unto mount Sion, and unto the city of the living God, the heavenly Jerusalem, and to an innumerable company of angels,",
      "23": "To the general assembly and church of the firstborn, which are written in heaven, and to God the Judge of all, and to the spirits of just men made perfect, ",
      "24": "And to Jesus the mediator of the new covenant, and to the blood of sprinkling, that speaketh better things than  that of  Abel. ",
      "25": "See that ye refuse not him that speaketh. For if they escaped not who refused him that spake on earth, much more  shall not  we  escape , if we turn away from him that  speaketh  from heaven:",
      "26": "Whose voice then shook the earth: but now he hath promised, saying,  Yet once more I shake not the earth only, but also heaven. ",
      "27": "And this  word , Yet once more, signifieth the removing of those things that are shaken, as of things that are made, that those things which cannot be shaken may remain. ",
      "28": "Wherefore we receiving a kingdom which cannot be moved, let us have grace, whereby we may serve God acceptably with reverence and godly fear: ",
      "29": " For our God  is  a consuming fire.  "
    },
    "13": {
      "1": "Let brotherly love continue.",
      "2": "Be not forgetful to entertain strangers: for thereby some have entertained angels unawares.",
      "3": "Remember them that are in bonds, as bound with them;  and  them which suffer adversity, as being yourselves also in the body.",
      "4": "Marriage  is  honourable in all, and the bed undefiled: but whoremongers and adulterers God will judge.",
      "5": " Let your  conversation  be  without covetousness;  and be  content with such things as ye have: for he hath said,  I will never leave thee, nor forsake thee. ",
      "6": "So that we may boldly say,  The Lord  is  my helper, and I will not fear what man shall do unto me. ",
      "7": "Remember them which have the rule over you, who have spoken unto you the word of God: whose faith follow, considering the end of  their  conversation. ",
      "8": "Jesus Christ the same yesterday, and to day, and for ever.",
      "9": "Be not carried about with divers and strange doctrines. For  it is  a good thing that the heart be established with grace; not with meats, which have not profited them that have been occupied therein.",
      "10": "We have an altar, whereof they have no right to eat which serve the tabernacle.",
      "11": "For the bodies of those beasts, whose blood is brought into the sanctuary by the high priest for sin, are burned without the camp.",
      "12": "Wherefore Jesus also, that he might sanctify the people with his own blood, suffered without the gate.",
      "13": "Let us go forth therefore unto him without the camp, bearing his reproach.",
      "14": "For here have we no continuing city, but we seek one to come.",
      "15": "By him therefore let us offer the sacrifice of praise to God continually, that is, the fruit of  our  lips giving thanks to his name. ",
      "16": "But to do good and to communicate forget not: for with such sacrifices God is well pleased.",
      "17": "Obey them that have the rule over you, and submit yourselves: for they watch for your souls, as they that must give account, that they may do it with joy, and not with grief: for that  is  unprofitable for you.  ",
      "18": "Pray for us: for we trust we have a good conscience, in all things willing to live honestly.",
      "19": "But I beseech  you  the rather to do this, that I may be restored to you the sooner.",
      "20": "Now the God of peace, that brought again from the dead our Lord Jesus, that great shepherd of the sheep, through the blood of the everlasting covenant, ",
      "21": "Make you perfect in every good work to do his will, working in you that which is wellpleasing in his sight, through Jesus Christ; to whom  be  glory for ever and ever. Amen. ",
      "22": "And I beseech you, brethren, suffer the word of exhortation: for I have written a letter unto you in few words.",
      "23": "Know ye that  our  brother Timothy is set at liberty; with whom, if he come shortly, I will see you.",
      "24": "Salute all them that have the rule over you, and all the saints. They of Italy salute you.",
      "25": "Grace  be  with you all. Amen.   "
    }
  },
  "james": {
    "1": {
      "1": "James, a servant of God and of the Lord Jesus Christ, to the twelve tribes which are scattered abroad, greeting. ",
      "2": "My brethren, count it all joy when ye fall into divers temptations; ",
      "3": "Knowing  this , that the trying of your faith worketh patience.",
      "4": "But let patience have  her  perfect work, that ye may be perfect and entire, wanting nothing.",
      "5": " If any of you lack wisdom, let him ask of God, that giveth to all  men  liberally, and upbraideth not; and it shall be given him.",
      "6": "But let him ask in faith, nothing wavering. For he that wavereth is like a wave of the sea driven with the wind and tossed.",
      "7": "For let not that man think that he shall receive any thing of the Lord.",
      "8": "A double minded man  is  unstable in all his ways.",
      "9": " Let the brother of low degree rejoice in that he is exalted:  ",
      "10": "But the rich, in that he is made low: because as the flower of the grass he shall pass away.",
      "11": "For the sun is no sooner risen with a burning heat, but it withereth the grass, and the flower thereof falleth, and the grace of the fashion of it perisheth: so also shall the rich man fade away in his ways.",
      "12": "Blessed  is  the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him. ",
      "13": "Let no man say when he is tempted, I am tempted of God: for God cannot be tempted with evil, neither tempteth he any man: ",
      "14": "But every man is tempted, when he is drawn away of his own lust, and enticed.",
      "15": "Then when lust hath conceived, it bringeth forth sin: and sin, when it is finished, bringeth forth death.",
      "16": "Do not err, my beloved brethren.",
      "17": "Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning.",
      "18": "Of his own will begat he us with the word of truth, that we should be a kind of firstfruits of his creatures. ",
      "19": "Wherefore, my beloved brethren, let every man be swift to hear, slow to speak, slow to wrath:",
      "20": "For the wrath of man worketh not the righteousness of God.",
      "21": "Wherefore lay apart all filthiness and superfluity of naughtiness, and receive with meekness the engrafted word, which is able to save your souls.",
      "22": "But be ye doers of the word, and not hearers only, deceiving your own selves.",
      "23": "For if any be a hearer of the word, and not a doer, he is like unto a man beholding his natural face in a glass:",
      "24": "For he beholdeth himself, and goeth his way, and straightway forgetteth what manner of man he was.",
      "25": "But whoso looketh into the perfect law of liberty, and continueth  therein , he being not a forgetful hearer, but a doer of the work, this man shall be blessed in his deed. ",
      "26": "If any man among you seem to be religious, and bridleth not his tongue, but deceiveth his own heart, this man's religion  is  vain.",
      "27": "Pure religion and undefiled before God and the Father is this, To visit the fatherless and widows in their affliction,  and  to keep himself unspotted from the world. "
    },
    "2": {
      "1": "My brethren, have not the faith of our Lord Jesus Christ,  the Lord  of glory, with respect of persons.",
      "2": "For if there come unto your assembly a man with a gold ring, in goodly apparel, and there come in also a poor man in vile raiment; ",
      "3": "And ye have respect to him that weareth the gay clothing, and say unto him, Sit thou here in a good place; and say to the poor, Stand thou there, or sit here under my footstool: ",
      "4": "Are ye not then partial in yourselves, and are become judges of evil thoughts?",
      "5": "Hearken, my beloved brethren, Hath not God chosen the poor of this world rich in faith, and heirs of the kingdom which he hath promised to them that love him? ",
      "6": "But ye have despised the poor. Do not rich men oppress you, and draw you before the judgment seats?",
      "7": "Do not they blaspheme that worthy name by the which ye are called?  ",
      "8": "If ye fulfil the royal law according to the scripture,  Thou shalt love thy neighbour as thyself,  ye do well:",
      "9": "But if ye have respect to persons, ye commit sin, and are convinced of the law as transgressors.",
      "10": "For whosoever shall keep the whole law, and yet offend in one  point , he is guilty of all.",
      "11": "For he that said, Do not commit adultery, said also, Do not kill. Now if thou commit no adultery, yet if thou kill, thou art become a transgressor of the law. ",
      "12": "So speak ye, and so do, as they that shall be judged by the law of liberty.",
      "13": "For he shall have judgment without mercy, that hath shewed no mercy; and mercy rejoiceth against judgment.  ",
      "14": "What  doth it  profit, my brethren, though a man say he hath faith, and have not works? can faith save him?",
      "15": "If a brother or sister be naked, and destitute of daily food,",
      "16": "And one of you say unto them, Depart in peace, be  ye  warmed and filled; notwithstanding ye give them not those things which are needful to the body; what  doth it  profit?",
      "17": "Even so faith, if it hath not works, is dead, being alone. ",
      "18": "Yea, a man may say, Thou hast faith, and I have works: shew me thy faith without thy works, and I will shew thee my faith by my works. ",
      "19": "Thou believest that there is one God; thou doest well: the devils also believe, and tremble.",
      "20": "But wilt thou know, O vain man, that faith without works is dead?",
      "21": "Was not Abraham our father justified by works, when he had offered Isaac his son upon the altar?",
      "22": "Seest thou how faith wrought with his works, and by works was faith made perfect? ",
      "23": "And the scripture was fulfilled which saith,  Abraham believed God, and it was imputed unto him for righteousness:  and he was called the Friend of God.",
      "24": "Ye see then how that by works a man is justified, and not by faith only.",
      "25": "Likewise also was not Rahab the harlot justified by works, when she had received the messengers, and had sent  them  out another way?",
      "26": "For as the body without the spirit is dead, so faith without works is dead also.  "
    },
    "3": {
      "1": "My brethren, be not many masters, knowing that we shall receive the greater condemnation. ",
      "2": "For in many things we offend all. If any man offend not in word, the same  is  a perfect man,  and  able also to bridle the whole body.",
      "3": "Behold, we put bits in the horses' mouths, that they may obey us; and we turn about their whole body.",
      "4": "Behold also the ships, which though  they be  so great, and  are  driven of fierce winds, yet are they turned about with a very small helm, whithersoever the governor listeth.",
      "5": "Even so the tongue is a little member, and boasteth great things. Behold, how great a matter a little fire kindleth! ",
      "6": "And the tongue  is  a fire, a world of iniquity: so is the tongue among our members, that it defileth the whole body, and setteth on fire the course of nature; and it is set on fire of hell. ",
      "7": "For every kind of beasts, and of birds, and of serpents, and of things in the sea, is tamed, and hath been tamed of mankind:  ",
      "8": "But the tongue can no man tame;  it is  an unruly evil, full of deadly poison.",
      "9": "Therewith bless we God, even the Father; and therewith curse we men, which are made after the similitude of God.",
      "10": "Out of the same mouth proceedeth blessing and cursing. My brethren, these things ought not so to be.",
      "11": "Doth a fountain send forth at the same place sweet  water  and bitter? ",
      "12": "Can the fig tree, my brethren, bear olive berries? either a vine, figs? so  can  no fountain both yield salt water and fresh. ",
      "13": "Who  is  a wise man and endued with knowledge among you? let him shew out of a good conversation his works with meekness of wisdom.",
      "14": "But if ye have bitter envying and strife in your hearts, glory not, and lie not against the truth.",
      "15": "This wisdom descendeth not from above, but  is  earthly, sensual, devilish. ",
      "16": "For where envying and strife  is , there  is  confusion and every evil work. ",
      "17": "But the wisdom that is from above is first pure, then peaceable, gentle,  and  easy to be intreated, full of mercy and good fruits, without partiality, and without hypocrisy. ",
      "18": "And the fruit of righteousness is sown in peace of them that make peace. "
    },
    "4": {
      "1": "From whence  come  wars and fightings among you?  come they  not hence,  even  of your lusts that war in your members?  ",
      "2": "Ye lust, and have not: ye kill, and desire to have, and cannot obtain: ye fight and war, yet ye have not, because ye ask not.",
      "3": "Ye ask, and receive not, because ye ask amiss, that ye may consume  it  upon your lusts. ",
      "4": "Ye adulterers and adulteresses, know ye not that the friendship of the world is enmity with God? whosoever therefore will be a friend of the world is the enemy of God.",
      "5": " Do ye think that the scripture saith in vain, The spirit that dwelleth in us lusteth to envy?  ",
      "6": "But he giveth more grace. Wherefore he saith,  God resisteth the proud, but giveth grace unto the humble. ",
      "7": "Submit yourselves therefore to God. Resist the devil, and he will flee from you.",
      "8": "Draw nigh to God, and he will draw nigh to you. Cleanse  your  hands,  ye  sinners; and purify  your  hearts,  ye  double minded.",
      "9": "Be afflicted, and mourn, and weep: let your laughter be turned to mourning, and  your  joy to heaviness.",
      "10": "Humble yourselves in the sight of the Lord, and he shall lift you up. ",
      "11": "Speak not evil one of another, brethren. He that speaketh evil of  his  brother, and judgeth his brother, speaketh evil of the law, and judgeth the law: but if thou judge the law, thou art not a doer of the law, but a judge.",
      "12": "There is one lawgiver, who is able to save and to destroy: who art thou that judgest another?",
      "13": "Go to now, ye that say, To day or to morrow we will go into such a city, and continue there a year, and buy and sell, and get gain:",
      "14": "Whereas ye know not what  shall be  on the morrow. For what  is  your life? It is even a vapour, that appeareth for a little time, and then vanisheth away. ",
      "15": "For that ye  ought  to say, If the Lord will, we shall live, and do this, or that.",
      "16": "But now ye rejoice in your boastings: all such rejoicing is evil.",
      "17": "Therefore to him that knoweth to do good, and doeth  it  not, to him it is sin. "
    },
    "5": {
      "1": "Go to now,  ye  rich men, weep and howl for your miseries that shall come upon  you .",
      "2": "Your riches are corrupted, and your garments are motheaten.",
      "3": "Your gold and silver is cankered; and the rust of them shall be a witness against you, and shall eat your flesh as it were fire. Ye have heaped treasure together for the last days.",
      "4": "Behold, the hire of the labourers who have reaped down your fields, which is of you kept back by fraud, crieth: and the cries of them which have reaped are entered into the ears of the Lord of sabaoth.",
      "5": "Ye have lived in pleasure on the earth, and been wanton; ye have nourished your hearts, as in a day of slaughter.",
      "6": "Ye have condemned  and  killed the just;  and  he doth not resist you.",
      "7": "Be patient therefore, brethren, unto the coming of the Lord. Behold, the husbandman waiteth for the precious fruit of the earth, and hath long patience for it, until he receive the early and latter rain. ",
      "8": "Be ye also patient; stablish your hearts: for the coming of the Lord draweth nigh.",
      "9": "Grudge not one against another, brethren, lest ye be condemned: behold, the judge standeth before the door. ",
      "10": "Take, my brethren, the prophets, who have spoken in the name of the Lord, for an example of suffering affliction, and of patience.",
      "11": "Behold, we count them happy which endure. Ye have heard of the patience of Job, and have seen the end of the Lord; that the Lord is very pitiful, and of tender mercy. ",
      "12": "But above all things, my brethren, swear not, neither by heaven, neither by the earth, neither by any other oath: but let your yea be yea; and  your  nay, nay; lest ye fall into condemnation.",
      "13": "Is any among you afflicted? let him pray. Is any merry? let him sing psalms.",
      "14": "Is any sick among you? let him call for the elders of the church; and let them pray over him, anointing him with oil in the name of the Lord:",
      "15": "And the prayer of faith shall save the sick, and the Lord shall raise him up; and if he have committed sins, they shall be forgiven him.",
      "16": "Confess  your  faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much.",
      "17": "Elias was a man subject to like passions as we are, and he prayed earnestly that it might not rain: and it rained not on the earth by the space of three years and six months.  ",
      "18": "And he prayed again, and the heaven gave rain, and the earth brought forth her fruit.",
      "19": "Brethren, if any of you do err from the truth, and one convert him;",
      "20": "Let him know, that he which converteth the sinner from the error of his way shall save a soul from death, and shall hide a multitude of sins. "
    }
  },
  "1_peter": {
    "1": {
      "1": "Peter, an apostle of Jesus Christ, to the strangers scattered throughout Pontus, Galatia, Cappadocia, Asia, and Bithynia,",
      "2": "Elect according to the foreknowledge of God the Father, through sanctification of the Spirit, unto obedience and sprinkling of the blood of Jesus Christ: Grace unto you, and peace, be multiplied. ",
      "3": "Blessed  be  the God and Father of our Lord Jesus Christ, which according to his abundant mercy hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead, ",
      "4": "To an inheritance incorruptible, and undefiled, and that fadeth not away, reserved in heaven for you, ",
      "5": "Who are kept by the power of God through faith unto salvation ready to be revealed in the last time. ",
      "6": "Wherein ye greatly rejoice, though now for a season, if need be, ye are in heaviness through manifold temptations:",
      "7": "That the trial of your faith, being much more precious than of gold that perisheth, though it be tried with fire, might be found unto praise and honour and glory at the appearing of Jesus Christ:",
      "8": "Whom having not seen, ye love; in whom, though now ye see  him  not, yet believing, ye rejoice with joy unspeakable and full of glory:",
      "9": "Receiving the end of your faith,  even  the salvation of  your  souls. ",
      "10": "Of which salvation the prophets have enquired and searched diligently, who prophesied of the grace  that should come  unto you:",
      "11": "Searching what, or what manner of time the Spirit of Christ which was in them did signify, when it testified beforehand the sufferings of Christ, and the glory that should follow.",
      "12": "Unto whom it was revealed, that not unto themselves, but unto us they did minister the things, which are now reported unto you by them that have preached the gospel unto you with the Holy Ghost sent down from heaven; which things the angels desire to look into. ",
      "13": "Wherefore gird up the loins of your mind, be sober, and hope to the end for the grace that is to be brought unto you at the revelation of Jesus Christ; ",
      "14": "As obedient children, not fashioning yourselves according to the former lusts in your ignorance:",
      "15": "But as he which hath called you is holy, so be ye holy in all manner of conversation;",
      "16": "Because it is written,  Be ye holy; for I am holy. ",
      "17": "And if ye call on the Father, who without respect of persons judgeth according to every man's work, pass the time of your sojourning  here  in fear:",
      "18": "Forasmuch as ye know that ye were not redeemed with corruptible things,  as  silver and gold, from your vain conversation  received  by tradition from your fathers;",
      "19": "But with the precious blood of Christ, as of a lamb without blemish and without spot:",
      "20": "Who verily was foreordained before the foundation of the world, but was manifest in these last times for you,",
      "21": "Who by him do believe in God, that raised him up from the dead, and gave him glory; that your faith and hope might be in God.",
      "22": "Seeing ye have purified your souls in obeying the truth through the Spirit unto unfeigned love of the brethren,  see that ye  love one another with a pure heart fervently:",
      "23": "Being born again, not of corruptible seed, but of incorruptible, by the word of God, which liveth and abideth for ever. ",
      "24": " For all flesh  is  as grass, and all the glory of man as the flower of grass. The grass withereth, and the flower thereof falleth away:  ",
      "25": " But the word of the Lord endureth for ever.  And this is the word which by the gospel is preached unto you. "
    },
    "2": {
      "1": "Wherefore laying aside all malice, and all guile, and hypocrisies, and envies, and all evil speakings,",
      "2": "As newborn babes, desire the sincere milk of the word, that ye may grow thereby:",
      "3": "If so be ye have tasted that the Lord  is  gracious. ",
      "4": "To whom coming,  as unto  a living stone, disallowed indeed of men, but chosen of God,  and  precious,",
      "5": "Ye also, as lively stones, are built up a spiritual house, an holy priesthood, to offer up spiritual sacrifices, acceptable to God by Jesus Christ. ",
      "6": "Wherefore also it is contained in the scripture,  Behold, I lay in Sion a chief corner stone, elect, precious: and he that believeth on him shall not be confounded. ",
      "7": "Unto you therefore which believe  he is  precious: but unto them which be disobedient,  the stone which the builders disallowed, the same is made the head of the corner,  ",
      "8": "And  a stone of stumbling, and a rock of offence,   even to them  which stumble at the word, being disobedient: whereunto also they were appointed.",
      "9": "But ye  are  a chosen generation, a royal priesthood, an holy nation, a peculiar people; that ye should shew forth the praises of him who hath called you out of darkness into his marvellous light:  ",
      "10": "Which in time past  were  not a people, but  are  now the people of God: which had not obtained mercy, but now have obtained mercy.",
      "11": "Dearly beloved, I beseech  you  as strangers and pilgrims, abstain from fleshly lusts, which war against the soul;",
      "12": "Having your conversation honest among the Gentiles: that, whereas they speak against you as evildoers, they may by  your  good works, which they shall behold, glorify God in the day of visitation.  ",
      "13": " Submit yourselves to every ordinance of man for the Lord's sake: whether it be to the king, as supreme;",
      "14": "Or unto governors, as unto them that are sent by him for the punishment of evildoers, and for the praise of them that do well.",
      "15": "For so is the will of God, that with well doing ye may put to silence the ignorance of foolish men:",
      "16": "As free, and not using  your  liberty for a cloke of maliciousness, but as the servants of God. ",
      "17": "Honour all  men . Love the brotherhood. Fear God. Honour the king. ",
      "18": "Servants,  be  subject to  your  masters with all fear; not only to the good and gentle, but also to the froward.",
      "19": "For this  is  thankworthy, if a man for conscience toward God endure grief, suffering wrongfully. ",
      "20": "For what glory  is it , if, when ye be buffeted for your faults, ye shall take it patiently? but if, when ye do well, and suffer  for it , ye take it patiently, this  is  acceptable with God. ",
      "21": "For even hereunto were ye called: because Christ also suffered for us, leaving us an example, that ye should follow his steps: ",
      "22": " Who did no sin, neither was guile found in his mouth: ",
      "23": "Who, when he was reviled, reviled not again; when he suffered, he threatened not; but committed  himself  to him that judgeth righteously: ",
      "24": "Who his own self bare our sins in his own body on the tree, that we, being dead to sins, should live unto righteousness: by whose stripes ye were healed. ",
      "25": "For ye were as sheep going astray; but are now returned unto the Shepherd and Bishop of your souls. "
    },
    "3": {
      "1": "Likewise, ye wives,  be  in subjection to your own husbands; that, if any obey not the word, they also may without the word be won by the conversation of the wives;",
      "2": "While they behold your chaste conversation  coupled  with fear.",
      "3": "Whose adorning let it not be that outward  adorning  of plaiting the hair, and of wearing of gold, or of putting on of apparel;",
      "4": "But  let it be  the hidden man of the heart, in that which is not corruptible,  even the ornament  of a meek and quiet spirit, which is in the sight of God of great price.",
      "5": "For after this manner in the old time the holy women also, who trusted in God, adorned themselves, being in subjection unto their own husbands:",
      "6": "Even as Sarah obeyed Abraham, calling him lord: whose daughters ye are, as long as ye do well, and are not afraid with any amazement. ",
      "7": "Likewise, ye husbands, dwell with  them  according to knowledge, giving honour unto the wife, as unto the weaker vessel, and as being heirs together of the grace of life; that your prayers be not hindered. ",
      "8": "Finally,  be ye  all of one mind, having compassion one of another, love as brethren,  be  pitiful,  be  courteous: ",
      "9": "Not rendering evil for evil, or railing for railing: but contrariwise blessing; knowing that ye are thereunto called, that ye should inherit a blessing.",
      "10": " For he that will love life, and see good days, let him refrain his tongue from evil, and his lips that they speak no guile: ",
      "11": " Let him eschew evil, and do good; let him seek peace, and ensue it. ",
      "12": " For the eyes of the Lord  are  over the righteous, and his ears  are open  unto their prayers: but the face of the Lord  is  against them that do evil.  ",
      "13": "And who  is  he that will harm you, if ye be followers of that which is good?",
      "14": "But and if ye suffer for righteousness' sake, happy  are ye : and be not afraid of their terror, neither be troubled;",
      "15": "But sanctify the Lord God in your hearts: and  be  ready always to  give  an answer to every man that asketh you a reason of the hope that is in you with meekness and fear:  ",
      "16": "Having a good conscience; that, whereas they speak evil of you, as of evildoers, they may be ashamed that falsely accuse your good conversation in Christ.",
      "17": "For  it is  better, if the will of God be so, that ye suffer for well doing, than for evil doing. ",
      "18": "For Christ also hath once suffered for sins, the just for the unjust, that he might bring us to God, being put to death in the flesh, but quickened by the Spirit:",
      "19": "By which also he went and preached unto the spirits in prison;",
      "20": "Which sometime were disobedient, when once the longsuffering of God waited in the days of Noah, while the ark was a preparing, wherein few, that is, eight souls were saved by water. ",
      "21": "The like figure whereunto  even  baptism doth also now save us (not the putting away of the filth of the flesh, but the answer of a good conscience toward God,) by the resurrection of Jesus Christ:",
      "22": "Who is gone into heaven, and is on the right hand of God; angels and authorities and powers being made subject unto him. "
    },
    "4": {
      "1": "Forasmuch then as Christ hath suffered for us in the flesh, arm yourselves likewise with the same mind: for he that hath suffered in the flesh hath ceased from sin;",
      "2": "That he no longer should live the rest of  his  time in the flesh to the lusts of men, but to the will of God.",
      "3": "For the time past of  our  life may suffice us to have wrought the will of the Gentiles, when we walked in lasciviousness, lusts, excess of wine, revellings, banquetings, and abominable idolatries: ",
      "4": "Wherein they think it strange that ye run not with  them  to the same excess of riot, speaking evil of  you :",
      "5": "Who shall give account to him that is ready to judge the quick and the dead.",
      "6": "For for this cause was the gospel preached also to them that are dead, that they might be judged according to men in the flesh, but live according to God in the spirit. ",
      "7": "But the end of all things is at hand: be ye therefore sober, and watch unto prayer.",
      "8": "And above all things have fervent charity among yourselves:  for charity shall cover the multitude of sins.  ",
      "9": "Use hospitality one to another without grudging.",
      "10": "As every man hath received the gift,  even so  minister the same one to another, as good stewards of the manifold grace of God.",
      "11": "If any man speak,  let him speak  as the oracles of God; if any man minister,  let him do it  as of the ability which God giveth: that God in all things may be glorified through Jesus Christ, to whom be praise and dominion for ever and ever. Amen. ",
      "12": "Beloved, think it not strange concerning the fiery trial which is to try you, as though some strange thing happened unto you:",
      "13": "But rejoice, inasmuch as ye are partakers of Christ's sufferings; that, when his glory shall be revealed, ye may be glad also with exceeding joy.",
      "14": "If ye be reproached for the name of Christ, happy  are ye ; for the spirit of glory and of God resteth upon you: on their part he is evil spoken of, but on your part he is glorified.",
      "15": "But let none of you suffer as a murderer, or  as  a thief, or  as  an evildoer, or as a busybody in other men's matters.",
      "16": "Yet if  any man suffer  as a Christian, let him not be ashamed; but let him glorify God on this behalf.",
      "17": "For the time  is come  that judgment must begin at the house of God: and if  it  first  begin  at us, what shall the end  be  of them that obey not the gospel of God?",
      "18": " And if the righteous scarcely be saved, where shall the ungodly and the sinner appear? ",
      "19": "Wherefore let them that suffer according to the will of God commit the keeping of their souls  to him  in well doing, as unto a faithful Creator. "
    },
    "5": {
      "1": "The elders which are among you I exhort, who am also an elder, and a witness of the sufferings of Christ, and also a partaker of the glory that shall be revealed:",
      "2": "Feed the flock of God which is among you, taking the oversight  thereof , not by constraint, but willingly; not for filthy lucre, but of a ready mind; ",
      "3": "Neither as being lords over  God's  heritage, but being ensamples to the flock. ",
      "4": "And when the chief Shepherd shall appear, ye shall receive a crown of glory that fadeth not away. ",
      "5": "Likewise, ye younger, submit yourselves unto the elder. Yea, all  of you  be subject one to another, and be clothed with humility: for  God resisteth the proud, and giveth grace to the humble. ",
      "6": "Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time:",
      "7": "Casting all your care upon him; for he careth for you. ",
      "8": "Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour:",
      "9": "Whom resist stedfast in the faith, knowing that the same afflictions are accomplished in your brethren that are in the world. ",
      "10": "But the God of all grace, who hath called us unto his eternal glory by Christ Jesus, after that ye have suffered a while, make you perfect, stablish, strengthen, settle  you .",
      "11": "To him  be  glory and dominion for ever and ever. Amen.",
      "12": "By Silvanus, a faithful brother unto you, as I suppose, I have written briefly, exhorting, and testifying that this is the true grace of God wherein ye stand.",
      "13": "The  church that is  at Babylon, elected together with  you , saluteth you; and  so doth  Marcus my son.",
      "14": "Greet ye one another with a kiss of charity. Peace  be  with you all that are in Christ Jesus. Amen. "
    }
  },
  "2_peter": {
    "1": {
      "1": "Simon Peter, a servant and an apostle of Jesus Christ, to them that have obtained like precious faith with us through the righteousness of God and our Saviour Jesus Christ:  ",
      "2": "Grace and peace be multiplied unto you through the knowledge of God, and of Jesus our Lord,",
      "3": "According as his divine power hath given unto us all things that  pertain  unto life and godliness, through the knowledge of him that hath called us to glory and virtue: ",
      "4": "Whereby are given unto us exceeding great and precious promises: that by these ye might be partakers of the divine nature, having escaped the corruption that is in the world through lust. ",
      "5": "And beside this, giving all diligence, add to your faith virtue; and to virtue knowledge;",
      "6": "And to knowledge temperance; and to temperance patience; and to patience godliness;",
      "7": "And to godliness brotherly kindness; and to brotherly kindness charity.",
      "8": "For if these things be in you, and abound, they make  you that ye shall  neither  be  barren nor unfruitful in the knowledge of our Lord Jesus Christ. ",
      "9": "But he that lacketh these things is blind, and cannot see afar off, and hath forgotten that he was purged from his old sins.",
      "10": "Wherefore the rather, brethren, give diligence to make your calling and election sure: for if ye do these things, ye shall never fall:",
      "11": "For so an entrance shall be ministered unto you abundantly into the everlasting kingdom of our Lord and Saviour Jesus Christ. ",
      "12": "Wherefore I will not be negligent to put you always in remembrance of these things, though ye know  them , and be established in the present truth.",
      "13": "Yea, I think it meet, as long as I am in this tabernacle, to stir you up by putting  you  in remembrance;",
      "14": "Knowing that shortly I must put off  this  my tabernacle, even as our Lord Jesus Christ hath shewed me.",
      "15": "Moreover I will endeavour that ye may be able after my decease to have these things always in remembrance. ",
      "16": "For we have not followed cunningly devised fables, when we made known unto you the power and coming of our Lord Jesus Christ, but were eyewitnesses of his majesty.",
      "17": "For he received from God the Father honour and glory, when there came such a voice to him from the excellent glory, This is my beloved Son, in whom I am well pleased.",
      "18": "And this voice which came from heaven we heard, when we were with him in the holy mount. ",
      "19": "We have also a more sure word of prophecy; whereunto ye do well that ye take heed, as unto a light that shineth in a dark place, until the day dawn, and the day star arise in your hearts:",
      "20": "Knowing this first, that no prophecy of the scripture is of any private interpretation.",
      "21": "For the prophecy came not in old time by the will of man: but holy men of God spake  as they were  moved by the Holy Ghost.  "
    },
    "2": {
      "1": "But there were false prophets also among the people, even as there shall be false teachers among you, who privily shall bring in damnable heresies, even denying the Lord that bought them, and bring upon themselves swift destruction.",
      "2": "And many shall follow their pernicious ways; by reason of whom the way of truth shall be evil spoken of.  ",
      "3": "And through covetousness shall they with feigned words make merchandise of you: whose judgment now of a long time lingereth not, and their damnation slumbereth not.",
      "4": "For if God spared not the angels that sinned, but cast  them  down to hell, and delivered  them  into chains of darkness, to be reserved unto judgment;",
      "5": "And spared not the old world, but saved Noah the eighth  person , a preacher of righteousness, bringing in the flood upon the world of the ungodly;",
      "6": "And turning the cities of Sodom and Gomorrha into ashes condemned  them  with an overthrow, making  them  an ensample unto those that after should live ungodly; ",
      "7": "And delivered just Lot, vexed with the filthy conversation of the wicked:",
      "8": "(For that righteous man dwelling among them, in seeing and hearing, vexed  his  righteous soul from day to day with  their  unlawful deeds;)",
      "9": "The Lord knoweth how to deliver the godly out of temptations, and to reserve the unjust unto the day of judgment to be punished: ",
      "10": "But chiefly them that walk after the flesh in the lust of uncleanness, and despise government. Presumptuous  are they , selfwilled, they are not afraid to speak evil of dignities. ",
      "11": "Whereas angels, which are greater in power and might, bring not railing accusation against them before the Lord. ",
      "12": "But these, as natural brute beasts, made to be taken and destroyed, speak evil of the things that they understand not; and shall utterly perish in their own corruption;",
      "13": "And shall receive the reward of unrighteousness,  as  they that count it pleasure to riot in the day time. Spots  they are  and blemishes, sporting themselves with their own deceivings while they feast with you;",
      "14": "Having eyes full of adultery, and that cannot cease from sin; beguiling unstable souls: an heart they have exercised with covetous practices; cursed children: ",
      "15": "Which have forsaken the right way, and are gone astray, following the way of Balaam  the son  of Bosor, who loved the wages of unrighteousness;",
      "16": "But was rebuked for his iniquity: the dumb ass speaking with man's voice forbad the madness of the prophet.",
      "17": "These are wells without water, clouds that are carried with a tempest; to whom the mist of darkness is reserved for ever.",
      "18": "For when they speak great swelling  words  of vanity, they allure through the lusts of the flesh,  through much  wantonness, those that were clean escaped from them who live in error. ",
      "19": "While they promise them liberty, they themselves are the servants of corruption: for of whom a man is overcome, of the same is he brought in bondage.",
      "20": "For if after they have escaped the pollutions of the world through the knowledge of the Lord and Saviour Jesus Christ, they are again entangled therein, and overcome, the latter end is worse with them than the beginning.",
      "21": "For it had been better for them not to have known the way of righteousness, than, after they have known  it , to turn from the holy commandment delivered unto them.",
      "22": "But it is happened unto them according to the true proverb,  The dog  is  turned to his own vomit again;  and the sow that was washed to her wallowing in the mire. "
    },
    "3": {
      "1": "This second epistle, beloved, I now write unto you; in  both  which I stir up your pure minds by way of remembrance:",
      "2": "That ye may be mindful of the words which were spoken before by the holy prophets, and of the commandment of us the apostles of the Lord and Saviour: ",
      "3": "Knowing this first, that there shall come in the last days scoffers, walking after their own lusts,",
      "4": "And saying, Where is the promise of his coming? for since the fathers fell asleep, all things continue as  they were  from the beginning of the creation.",
      "5": "For this they willingly are ignorant of, that by the word of God the heavens were of old, and the earth standing out of the water and in the water: ",
      "6": "Whereby the world that then was, being overflowed with water, perished:",
      "7": "But the heavens and the earth, which are now, by the same word are kept in store, reserved unto fire against the day of judgment and perdition of ungodly men. ",
      "8": "But, beloved, be not ignorant of this one thing, that one day  is  with the Lord as a thousand years, and a thousand years as one day. ",
      "9": "The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance.",
      "10": "But the day of the Lord will come as a thief in the night; in the which the heavens shall pass away with a great noise, and the elements shall melt with fervent heat, the earth also and the works that are therein shall be burned up. ",
      "11": " Seeing  then  that  all these things shall be dissolved, what manner  of persons  ought ye to be in  all  holy conversation and godliness,",
      "12": "Looking for and hasting unto the coming of the day of God, wherein the heavens being on fire shall be dissolved, and the elements shall melt with fervent heat? ",
      "13": "Nevertheless we, according to his promise, look for new heavens and a new earth, wherein dwelleth righteousness.",
      "14": "Wherefore, beloved, seeing that ye look for such things, be diligent that ye may be found of him in peace, without spot, and blameless.",
      "15": "And account  that  the longsuffering of our Lord  is  salvation; even as our beloved brother Paul also according to the wisdom given unto him hath written unto you;",
      "16": "As also in all  his  epistles, speaking in them of these things; in which are some things hard to be understood, which they that are unlearned and unstable wrest, as  they do  also the other scriptures, unto their own destruction.",
      "17": "Ye therefore, beloved, seeing ye know  these things  before, beware lest ye also, being led away with the error of the wicked, fall from your own stedfastness.",
      "18": "But grow in grace, and  in  the knowledge of our Lord and Saviour Jesus Christ. To him  be  glory both now and for ever. Amen. "
    }
  },
  "1_john": {
    "1": {
      "1": "That which was from the beginning, which we have heard, which we have seen with our eyes, which we have looked upon, and our hands have handled, of the Word of life;",
      "2": "(For the life was manifested, and we have seen  it , and bear witness, and shew unto you that eternal life, which was with the Father, and was manifested unto us;)",
      "3": "That which we have seen and heard declare we unto you, that ye also may have fellowship with us: and truly our fellowship  is  with the Father, and with his Son Jesus Christ.",
      "4": "And these things write we unto you, that your joy may be full. ",
      "5": "This then is the message which we have heard of him, and declare unto you, that God is light, and in him is no darkness at all.",
      "6": "If we say that we have fellowship with him, and walk in darkness, we lie, and do not the truth:",
      "7": "But if we walk in the light, as he is in the light, we have fellowship one with another, and the blood of Jesus Christ his Son cleanseth us from all sin. ",
      "8": "If we say that we have no sin, we deceive ourselves, and the truth is not in us.",
      "9": "If we confess our sins, he is faithful and just to forgive us  our  sins, and to cleanse us from all unrighteousness.",
      "10": "If we say that we have not sinned, we make him a liar, and his word is not in us. "
    },
    "2": {
      "1": "My little children, these things write I unto you, that ye sin not. And if any man sin, we have an advocate with the Father, Jesus Christ the righteous:",
      "2": "And he is the propitiation for our sins: and not for ours only, but also for  the sins of  the whole world. ",
      "3": "And hereby we do know that we know him, if we keep his commandments.",
      "4": "He that saith, I know him, and keepeth not his commandments, is a liar, and the truth is not in him.",
      "5": "But whoso keepeth his word, in him verily is the love of God perfected: hereby know we that we are in him.",
      "6": "He that saith he abideth in him ought himself also so to walk, even as he walked. ",
      "7": "Brethren, I write no new commandment unto you, but an old commandment which ye had from the beginning. The old commandment is the word which ye have heard from the beginning.",
      "8": "Again, a new commandment I write unto you, which thing is true in him and in you: because the darkness is past, and the true light now shineth.",
      "9": "He that saith he is in the light, and hateth his brother, is in darkness even until now.",
      "10": "He that loveth his brother abideth in the light, and there is none occasion of stumbling in him. ",
      "11": "But he that hateth his brother is in darkness, and walketh in darkness, and knoweth not whither he goeth, because that darkness hath blinded his eyes. ",
      "12": "I write unto you, little children, because your sins are forgiven you for his name's sake.",
      "13": "I write unto you, fathers, because ye have known him  that is  from the beginning. I write unto you, young men, because ye have overcome the wicked one. I write unto you, little children, because ye have known the Father.",
      "14": "I have written unto you, fathers, because ye have known him  that is  from the beginning. I have written unto you, young men, because ye are strong, and the word of God abideth in you, and ye have overcome the wicked one.",
      "15": "Love not the world, neither the things  that are  in the world. If any man love the world, the love of the Father is not in him.",
      "16": "For all that  is  in the world, the lust of the flesh, and the lust of the eyes, and the pride of life, is not of the Father, but is of the world.",
      "17": "And the world passeth away, and the lust thereof: but he that doeth the will of God abideth for ever. ",
      "18": "Little children, it is the last time: and as ye have heard that antichrist shall come, even now are there many antichrists; whereby we know that it is the last time.",
      "19": "They went out from us, but they were not of us; for if they had been of us, they would  no doubt  have continued with us: but  they went out , that they might be made manifest that they were not all of us. ",
      "20": "But ye have an unction from the Holy One, and ye know all things.",
      "21": "I have not written unto you because ye know not the truth, but because ye know it, and that no lie is of the truth.",
      "22": "Who is a liar but he that denieth that Jesus is the Christ? He is antichrist, that denieth the Father and the Son.",
      "23": "Whosoever denieth the Son, the same hath not the Father:  (but) he that acknowledgeth   the Son   hath   the Father   also .",
      "24": "Let that therefore abide in you, which ye have heard from the beginning. If that which ye have heard from the beginning shall remain in you, ye also shall continue in the Son, and in the Father.",
      "25": "And this is the promise that he hath promised us,  even  eternal life.",
      "26": "These  things  have I written unto you concerning them that seduce you.",
      "27": "But the anointing which ye have received of him abideth in you, and ye need not that any man teach you: but as the same anointing teacheth you of all things, and is truth, and is no lie, and even as it hath taught you, ye shall abide in him.  ",
      "28": "And now, little children, abide in him; that, when he shall appear, we may have confidence, and not be ashamed before him at his coming.",
      "29": "If ye know that he is righteous, ye know that every one that doeth righteousness is born of him.  "
    },
    "3": {
      "1": "Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God: therefore the world knoweth us not, because it knew him not.",
      "2": "Beloved, now are we the sons of God, and it doth not yet appear what we shall be: but we know that, when he shall appear, we shall be like him; for we shall see him as he is.",
      "3": "And every man that hath this hope in him purifieth himself, even as he is pure. ",
      "4": "Whosoever committeth sin transgresseth also the law: for sin is the transgression of the law.",
      "5": "And ye know that he was manifested to take away our sins; and in him is no sin.",
      "6": "Whosoever abideth in him sinneth not: whosoever sinneth hath not seen him, neither known him.",
      "7": "Little children, let no man deceive you: he that doeth righteousness is righteous, even as he is righteous.",
      "8": "He that committeth sin is of the devil; for the devil sinneth from the beginning. For this purpose the Son of God was manifested, that he might destroy the works of the devil.",
      "9": "Whosoever is born of God doth not commit sin; for his seed remaineth in him: and he cannot sin, because he is born of God.",
      "10": "In this the children of God are manifest, and the children of the devil: whosoever doeth not righteousness is not of God, neither he that loveth not his brother. ",
      "11": "For this is the message that ye heard from the beginning, that we should love one another. ",
      "12": "Not as Cain,  who  was of that wicked one, and slew his brother. And wherefore slew he him? Because his own works were evil, and his brother's righteous.",
      "13": "Marvel not, my brethren, if the world hate you. ",
      "14": "We know that we have passed from death unto life, because we love the brethren. He that loveth not  his  brother abideth in death.",
      "15": "Whosoever hateth his brother is a murderer: and ye know that no murderer hath eternal life abiding in him.",
      "16": "Hereby perceive we the love  of God , because he laid down his life for us: and we ought to lay down  our  lives for the brethren.",
      "17": "But whoso hath this world's good, and seeth his brother have need, and shutteth up his bowels  of compassion  from him, how dwelleth the love of God in him?",
      "18": "My little children, let us not love in word, neither in tongue; but in deed and in truth.",
      "19": "And hereby we know that we are of the truth, and shall assure our hearts before him.  ",
      "20": "For if our heart condemn us, God is greater than our heart, and knoweth all things.",
      "21": "Beloved, if our heart condemn us not,  then  have we confidence toward God.",
      "22": "And whatsoever we ask, we receive of him, because we keep his commandments, and do those things that are pleasing in his sight. ",
      "23": "And this is his commandment, That we should believe on the name of his Son Jesus Christ, and love one another, as he gave us commandment.",
      "24": "And he that keepeth his commandments dwelleth in him, and he in him. And hereby we know that he abideth in us, by the Spirit which he hath given us. "
    },
    "4": {
      "1": "Beloved, believe not every spirit, but try the spirits whether they are of God: because many false prophets are gone out into the world.",
      "2": "Hereby know ye the Spirit of God: Every spirit that confesseth that Jesus Christ is come in the flesh is of God:",
      "3": "And every spirit that confesseth not that Jesus Christ is come in the flesh is not of God: and this is that  spirit  of antichrist, whereof ye have heard that it should come; and even now already is it in the world. ",
      "4": "Ye are of God, little children, and have overcome them: because greater is he that is in you, than he that is in the world.",
      "5": "They are of the world: therefore speak they of the world, and the world heareth them.",
      "6": "We are of God: he that knoweth God heareth us; he that is not of God heareth not us. Hereby know we the spirit of truth, and the spirit of error. ",
      "7": "Beloved, let us love one another: for love is of God; and every one that loveth is born of God, and knoweth God.",
      "8": "He that loveth not knoweth not God; for God is love.",
      "9": "In this was manifested the love of God toward us, because that God sent his only begotten Son into the world, that we might live through him.",
      "10": "Herein is love, not that we loved God, but that he loved us, and sent his Son  to be  the propitiation for our sins.",
      "11": "Beloved, if God so loved us, we ought also to love one another.",
      "12": "No man hath seen God at any time. If we love one another, God dwelleth in us, and his love is perfected in us.",
      "13": "Hereby know we that we dwell in him, and he in us, because he hath given us of his Spirit. ",
      "14": "And we have seen and do testify that the Father sent the Son  to be  the Saviour of the world.",
      "15": "Whosoever shall confess that Jesus is the Son of God, God dwelleth in him, and he in God.",
      "16": "And we have known and believed the love that God hath to us. God is love; and he that dwelleth in love dwelleth in God, and God in him. ",
      "17": "Herein is our love made perfect, that we may have boldness in the day of judgment: because as he is, so are we in this world. ",
      "18": "There is no fear in love; but perfect love casteth out fear: because fear hath torment. He that feareth is not made perfect in love.",
      "19": "We love him, because he first loved us.",
      "20": "If a man say, I love God, and hateth his brother, he is a liar: for he that loveth not his brother whom he hath seen, how can he love God whom he hath not seen?",
      "21": "And this commandment have we from him, That he who loveth God love his brother also. "
    },
    "5": {
      "1": "Whosoever believeth that Jesus is the Christ is born of God: and every one that loveth him that begat loveth him also that is begotten of him.",
      "2": "By this we know that we love the children of God, when we love God, and keep his commandments.",
      "3": "For this is the love of God, that we keep his commandments: and his commandments are not grievous.",
      "4": "For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world,  even  our faith.",
      "5": "Who is he that overcometh the world, but he that believeth that Jesus is the Son of God? ",
      "6": "This is he that came by water and blood,  even  Jesus Christ; not by water only, but by water and blood. And it is the Spirit that beareth witness, because the Spirit is truth.",
      "7": "For there are three that bear record in heaven, the Father, the Word, and the Holy Ghost: and these three are one.",
      "8": "And there are three that bear witness in earth, the spirit, and the water, and the blood: and these three agree in one.",
      "9": "If we receive the witness of men, the witness of God is greater: for this is the witness of God which he hath testified of his Son. ",
      "10": "He that believeth on the Son of God hath the witness in himself: he that believeth not God hath made him a liar; because he believeth not the record that God gave of his Son.",
      "11": "And this is the record, that God hath given to us eternal life, and this life is in his Son.",
      "12": "He that hath the Son hath life;  and  he that hath not the Son of God hath not life.",
      "13": "These things have I written unto you that believe on the name of the Son of God; that ye may know that ye have eternal life, and that ye may believe on the name of the Son of God. ",
      "14": "And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us: ",
      "15": "And if we know that he hear us, whatsoever we ask, we know that we have the petitions that we desired of him.",
      "16": "If any man see his brother sin a sin  which is  not unto death, he shall ask, and he shall give him life for them that sin not unto death. There is a sin unto death: I do not say that he shall pray for it.",
      "17": "All unrighteousness is sin: and there is a sin not unto death. ",
      "18": "We know that whosoever is born of God sinneth not; but he that is begotten of God keepeth himself, and that wicked one toucheth him not.",
      "19": " And  we know that we are of God, and the whole world lieth in wickedness.",
      "20": "And we know that the Son of God is come, and hath given us an understanding, that we may know him that is true, and we are in him that is true,  even  in his Son Jesus Christ. This is the true God, and eternal life.",
      "21": "Little children, keep yourselves from idols. Amen. "
    }
  },
  "2_john": {
    "1": {
      "1": "The elder unto the elect lady and her children, whom I love in the truth; and not I only, but also all they that have known the truth;",
      "2": "For the truth's sake, which dwelleth in us, and shall be with us for ever.",
      "3": "Grace be with you, mercy,  and  peace, from God the Father, and from the Lord Jesus Christ, the Son of the Father, in truth and love. ",
      "4": "I rejoiced greatly that I found of thy children walking in truth, as we have received a commandment from the Father. ",
      "5": "And now I beseech thee, lady, not as though I wrote a new commandment unto thee, but that which we had from the beginning, that we love one another.",
      "6": "And this is love, that we walk after his commandments. This is the commandment, That, as ye have heard from the beginning, ye should walk in it. ",
      "7": "For many deceivers are entered into the world, who confess not that Jesus Christ is come in the flesh. This is a deceiver and an antichrist.",
      "8": "Look to yourselves, that we lose not those things which we have wrought, but that we receive a full reward. ",
      "9": "Whosoever transgresseth, and abideth not in the doctrine of Christ, hath not God. He that abideth in the doctrine of Christ, he hath both the Father and the Son. ",
      "10": "If there come any unto you, and bring not this doctrine, receive him not into  your  house, neither bid him God speed:",
      "11": "For he that biddeth him God speed is partaker of his evil deeds. ",
      "12": "Having many things to write unto you, I would not  write  with paper and ink: but I trust to come unto you, and speak face to face, that our joy may be full.  ",
      "13": "The children of thy elect sister greet thee. Amen. "
    }
  },
  "3_john": {
    "1": {
      "1": "The elder unto the wellbeloved Gaius, whom I love in the truth. ",
      "2": "Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth.  ",
      "3": "For I rejoiced greatly, when the brethren came and testified of the truth that is in thee, even as thou walkest in the truth.",
      "4": "I have no greater joy than to hear that my children walk in truth.",
      "5": "Beloved, thou doest faithfully whatsoever thou doest to the brethren, and to strangers;",
      "6": "Which have borne witness of thy charity before the church: whom if thou bring forward on their journey after a godly sort, thou shalt do well: ",
      "7": "Because that for his name's sake they went forth, taking nothing of the Gentiles.",
      "8": "We therefore ought to receive such, that we might be fellowhelpers to the truth.  ",
      "9": "I wrote unto the church: but Diotrephes, who loveth to have the preeminence among them, receiveth us not.",
      "10": "Wherefore, if I come, I will remember his deeds which he doeth, prating against us with malicious words: and not content therewith, neither doth he himself receive the brethren, and forbiddeth them that would, and casteth  them  out of the church.",
      "11": "Beloved, follow not that which is evil, but that which is good. He that doeth good is of God: but he that doeth evil hath not seen God. ",
      "12": "Demetrius hath good report of all  men , and of the truth itself: yea, and we  also  bear record; and ye know that our record is true.",
      "13": "I had many things to write, but I will not with ink and pen write unto thee:",
      "14": "But I trust I shall shortly see thee, and we shall speak face to face. Peace  be  to thee.  Our  friends salute thee. Greet the friends by name.  "
    }
  }
};

