#!/bin/bash

CURR_DIR=$(pwd)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "GENERATING nav_js "${BASH_SOURCE[0]}

cd $SCRIPT_DIR

SRC_DIR=${1}
BOOK_NAM=${2}

echo "GENERATING "${SRC_DIR}/nav2_${BOOK_NAM}.mustache

node fix_nav.js ${SRC_DIR}/nav1_${BOOK_NAM}.mustache > ${SRC_DIR}/nav2_${BOOK_NAM}.mustache

cd ${CURR_DIR}
