
	
export const bib_verses = {
  "proverbs": {
    "7": {
      "1": "HIJO mío, guarda mis razones, Y encierra contigo mis mandamientos.",
      "2": "Guarda mis mandamientos, y vivirás; Y mi ley como las niñas de tus ojos.",
      "3": "Lígalos á tus dedos; Escríbelos en la tabla de tu corazón.",
      "4": "Di á la sabiduría: Tú eres mi hermana; Y á la inteligencia llama parienta:",
      "5": "Para que te guarden de la mujer ajena, Y de la extraña que ablanda sus palabras.",
      "6": "Porque mirando yo por la ventana de mi casa, Por mi celosía,",
      "7": "Vi entre los simples, Consideré entre los jóvenes, Un mancebo falto de entendimiento,",
      "8": "El cual pasaba por la calle, junto á la esquina de aquella, E iba camino de su casa,",
      "9": "A la tarde del día, ya que oscurecía, En la oscuridad y tiniebla de la noche.",
      "10": "Y he aquí, una mujer que le sale al encuentro Con atavío de ramera, astuta de corazón,",
      "11": "Alborotadora y rencillosa, Sus pies no pueden estar en casa;",
      "12": "Unas veces de fuera, ó bien por las plazas, Acechando por todas las esquinas.",
      "13": "Y traba de él, y bésalo; Desvergonzó su rostro, y díjole:",
      "14": "Sacrificios de paz había prometido, Hoy he pagado mis votos;",
      "15": "Por tanto he salido á encontrarte, Buscando diligentemente tu rostro, y te he hallado.",
      "16": "Con paramentos he ataviado mi cama, Recamados con cordoncillo de Egipto.",
      "17": "He sahumado mi cámara Con mirra, áloes, y cinamomo.",
      "18": "Ven, embriaguémonos de amores hasta la mañana; Alegrémonos en amores.",
      "19": "Porque el marido no está en casa, Hase ido á un largo viaje:",
      "20": "El saco de dinero llevó en su mano; El día señalado volverá á su casa.",
      "21": "Rindiólo con la mucha suavidad de sus palabras, Obligóle con la blandura de sus labios.",
      "22": "Vase en pos de ella luego, Como va el buey al degolladero, Y como el loco á las prisiones para ser castigado;",
      "23": "Como el ave que se apresura al lazo, Y no sabe que es contra su vida, Hasta que la saeta traspasó su hígado.",
      "24": "Ahora pues, hijos, oidme, Y estad atentos á las razones de mi boca.",
      "25": "No se aparte á sus caminos tu corazón; No yerres en sus veredas.",
      "26": "Porque á muchos ha hecho caer heridos; Y aun los más fuertes han sido muertos por ella.",
      "27": "Caminos del sepulcro son su casa, Que descienden á las cámaras de la muerte."
    },
    "8": {
      "1": "¿NO clama la sabiduría, Y da su voz la inteligencia?",
      "2": "En los altos cabezos, junto al camino, A las encrucijadas de las veredas se para;",
      "3": "En el lugar de las puertas, á la entrada de la ciudad, A la entrada de las puertas da voces:",
      "4": "Oh hombres, á vosotros clamo; Y mi voz es á los hijos de los hombres.",
      "5": "Entended, simples, discreción; Y vosotros, locos, entrad en cordura.",
      "6": "Oid, porque hablaré cosas excelentes; Y abriré mis labios para cosas rectas.",
      "7": "Porque mi boca hablará verdad, Y la impiedad abominan mis labios.",
      "8": "En justicia son todas las razones de mi boca; No hay en ellas cosa perversa ni torcida.",
      "9": "Todas ellas son rectas al que entiende, Y razonables á los que han hallado sabiduría.",
      "10": "Recibid mi enseñanza, y no plata; Y ciencia antes que el oro escogido.",
      "11": "Porque mejor es la sabiduría que las piedras preciosas; Y todas las cosas que se pueden desear, no son de comparar con ella.",
      "12": "Yo, la sabiduría, habito con la discreción, Y hallo la ciencia de los consejos.",
      "13": "El temor de Jehová es aborrecer el mal; La soberbia y la arrogancia, y el mal camino Y la boca perversa, aborrezco.",
      "14": "Conmigo está el consejo y el ser; Yo soy la inteligencia; mía es la fortaleza.",
      "15": "Por mí reinan los reyes, Y los príncipes determinan justicia.",
      "16": "Por mí dominan los príncipes, Y todos los gobernadores juzgan la tierra.",
      "17": "Yo amo á los que me aman; Y me hallan los que madrugando me buscan.",
      "18": "Las riquezas y la honra están conmigo; Sólidas riquezas, y justicia.",
      "19": "Mejor es mi fruto que el oro, y que el oro refinado; Y mi rédito mejor que la plata escogida.",
      "20": "Por vereda de justicia guiaré, Por en medio de sendas de juicio;",
      "21": "Para hacer heredar á mis amigos el ser, Y que yo hincha sus tesoros.",
      "22": "Jehová me poseía en el principio de su camino, Ya de antiguo, antes de sus obras.",
      "23": "Eternalmente tuve el principado, desde el principio, Antes de la tierra.",
      "24": "Antes de los abismos fuí engendrada; Antes que fuesen las fuentes de las muchas aguas.",
      "25": "Antes que los montes fuesen fundados, Antes de los collados, era yo engendrada:",
      "26": "No había aún hecho la tierra, ni las campiñas, Ni el principio del polvo del mundo.",
      "27": "Cuando formaba los cielos, allí estaba yo; Cuando señalaba por compás la sobrefaz del abismo;",
      "28": "Cuando afirmaba los cielos arriba, Cuando afirmaba las fuentes del abismo;",
      "29": "Cuando ponía á la mar su estatuto, Y á las aguas, que no pasasen su mandamiento; Cuando establecía los fundamentos de la tierra;",
      "30": "Con él estaba yo ordenándolo todo; Y fuí su delicia todos los días, Teniendo solaz delante de él en todo tiempo.",
      "31": "Huélgome en la parte habitable de su tierra; Y mis delicias son con los hijos de los hombres.",
      "32": "Ahora pues, hijos, oidme: Y bienaventurados los que guardaren mis caminos.",
      "33": "Atended el consejo, y sed sabios, Y no lo menospreciéis.",
      "34": "Bienaventurado el hombre que me oye, Velando á mis puertas cada día, Guardando los umbrales de mis entradas.",
      "35": "Porque el que me hallare, hallará la vida, Y alcanzará el favor de Jehová.",
      "36": "Mas el que peca contra mí, defrauda su alma: Todos los que me aborrecen, aman la muerte."
    },
    "9": {
      "1": "LA sabiduría edificó su casa, Labró sus siete columnas;",
      "2": "Mató sus víctimas, templó su vino, Y puso su mesa.",
      "3": "Envió sus criadas; Sobre lo más alto de la ciudad clamó:",
      "4": "Cualquiera simple, venga acá. A los faltos de cordura dijo:",
      "5": "Venid, comed mi pan, Y bebed del vino que yo he templado.",
      "6": "Dejad las simplezas, y vivid; Y andad por el camino de la inteligencia.",
      "7": "El que corrige al escarnecedor, afrenta se acarrea: El que reprende al impío, se atrae mancha.",
      "8": "No reprendas al escarnecedor, porque no te aborrezca: Corrige al sabio, y te amará.",
      "9": "Da al sabio, y será más sabio: Enseña al justo, y acrecerá su saber.",
      "10": "El temor de Jehová es el principio de la sabiduría; Y la ciencia de los santos es inteligencia.",
      "11": "Porque por mí se aumentarán tus días, Y años de vida se te añadirán.",
      "12": "Si fueres sabio, para ti lo serás: Mas si fueres escarnecedor, pagarás tú solo.",
      "13": "La mujer loca es alborotadora; Es simple é ignorante.",
      "14": "Siéntase en una silla á la puerta de su casa, En lo alto de la ciudad,",
      "15": "Para llamar á los que pasan por el camino, Que van por sus caminos derechos.",
      "16": "Cualquiera simple, dice, venga acá. A los faltos de cordura dijo:",
      "17": "Las aguas hurtadas son dulces, Y el pan comido en oculto es suave.",
      "18": "Y no saben que allí están los muertos; Que sus convidados están en los profundos de la sepultura."
    },
    "10": {
      "1": "Las sentencias de Salomón. EL hijo sabio alegra al padre; Y el hijo necio es tristeza de su madre.",
      "2": "Los tesoros de maldad no serán de provecho: Mas la justicia libra de muerte.",
      "3": "Jehová no dejará hambrear el alma del justo: Mas la iniquidad lanzará á los impíos.",
      "4": "La mano negligente hace pobre: Mas la mano de los diligentes enriquece.",
      "5": "El que recoge en el estío es hombre entendido: El que duerme en el tiempo de la siega es hombre afrentoso.",
      "6": "Bendiciones sobre la cabeza del justo: Mas violencia cubrirá la boca de los impíos.",
      "7": "La memoria del justo será bendita: Mas el nombre de los impíos se pudrirá.",
      "8": "El sabio de corazón recibirá los mandamientos: Mas el loco de labios caerá.",
      "9": "El que camina en integridad, anda confiado: Mas el que pervierte sus caminos, será quebrantado.",
      "10": "El que guiña del ojo acarrea tristeza; Y el loco de labios será castigado.",
      "11": "Vena de vida es la boca del justo: Mas violencia cubrirá la boca de los impíos.",
      "12": "El odio despierta rencillas: Mas la caridad cubrirá todas las faltas.",
      "13": "En los labios del prudente se halla sabiduría: Y vara á las espaldas del falto de cordura.",
      "14": "Los sabios guardan la sabiduría: Mas la boca del loco es calamidad cercana.",
      "15": "Las riquezas del rico son su ciudad fuerte; Y el desmayo de los pobres es su pobreza.",
      "16": "La obra del justo es para vida; Mas el fruto del impío es para pecado.",
      "17": "Camino á la vida es guardar la corrección: Mas el que deja la reprensión, yerra.",
      "18": "El que encubre el odio es de labios mentirosos; Y el que echa mala fama es necio.",
      "19": "En las muchas palabras no falta pecado: Mas el que refrena sus labios es prudente.",
      "20": "Plata escogida es la lengua del justo: Mas el entendimiento de los impíos es como nada.",
      "21": "Los labios del justo apacientan á muchos: Mas los necios por falta de entendimiento mueren.",
      "22": "La bendición de Jehová es la que enriquece, Y no añade tristeza con ella.",
      "23": "Hacer abominación es como risa al insensato: Mas el hombre entendido sabe.",
      "24": "Lo que el impío teme, eso le vendrá: Mas á los justos les será dado lo que desean.",
      "25": "Como pasa el torbellino, así el malo no permanece: Mas el justo, fundado para siempre.",
      "26": "Como el vinagre á los dientes, y como el humo á los ojos, Así es el perezoso á los que lo envían.",
      "27": "El temor de Jehová aumentará los días: Mas los años de los impíos serán acortados.",
      "28": "La esperanza de los justos es alegría; Mas la esperanza de los impíos perecerá.",
      "29": "Fortaleza es al perfecto el camino de Jehová: Mas espanto es á los que obran maldad.",
      "30": "El justo eternalmente no será removido: Mas los impíos no habitarán la tierra.",
      "31": "La boca del justo producirá sabiduría: Mas la lengua perversa será cortada.",
      "32": "Los labios del justo conocerán lo que agrada: Mas la boca de los impíos habla perversidades."
    },
    "11": {
      "1": "EL peso falso abominación es á Jehová: Mas la pesa cabal le agrada.",
      "2": "Cuando viene la soberbia, viene también la deshonra: Mas con los humildes es la sabiduría.",
      "3": "La integridad de los rectos los encaminará: Mas destruirá á los pecadores la perversidad de ellos.",
      "4": "No aprovecharán las riquezas en el día de la ira: Mas la justicia librará de muerte.",
      "5": "La justicia del perfecto enderezará su camino: mas el impío por su impiedad caerá.",
      "6": "La justicia de los rectos los librará: Mas los pecadores en su pecado serán presos.",
      "7": "Cuando muere el hombre impío, perece su esperanza; Y la espectativa de los malos perecerá.",
      "8": "El justo es librado de la tribulación: Mas el impío viene en lugar suyo.",
      "9": "El hipócrita con la boca daña á su prójimo: Mas los justos son librados con la sabiduría.",
      "10": "En el bien de los justos la ciudad se alegra: Mas cuando los impíos perecen, hay fiestas.",
      "11": "Por la bendición de los rectos la ciudad será engrandecida: Mas por la boca de los impíos ella será trastornada.",
      "12": "El que carece de entendimiento, menosprecia á su prójimo: Mas el hombre prudente calla.",
      "13": "El que anda en chismes, descubre el secreto: Mas el de espíritu fiel encubre la cosa.",
      "14": "Cuando faltaren las industrias, caerá el pueblo: Mas en la multitud de consejeros hay salud.",
      "15": "Con ansiedad será afligido el que fiare al extraño: Mas el que aborreciere las fianzas vivirá confiado.",
      "16": "La mujer graciosa tendrá honra: Y los fuertes tendrán riquezas.",
      "17": "A su alma hace bien el hombre misericordioso: Mas el cruel atormenta su carne.",
      "18": "El impío hace obra falsa: Mas el que sembrare justicia, tendrá galardón firme.",
      "19": "Como la justicia es para vida, Así el que sigue el mal es para su muerte.",
      "20": "Abominación son á Jehová los perversos de corazón: Mas los perfectos de camino le son agradables.",
      "21": "Aunque llegue la mano á la mano, el malo no quedará sin castigo: Mas la simiente de los justos escapará.",
      "22": "Zarcillo de oro en la nariz del puerco, Es la mujer hermosa y apartada de razón.",
      "23": "El deseo de los justos es solamente bien: Mas la esperanza de los impíos es enojo.",
      "24": "Hay quienes reparten, y les es añadido más: Y hay quienes son escasos más de lo que es justo, mas vienen á pobreza.",
      "25": "El alma liberal será engordada: Y el que saciare, él también será saciado.",
      "26": "Al que retiene el grano, el pueblo lo maldecirá: Mas bendición será sobre la cabeza del que vende.",
      "27": "El que madruga al bien, buscará favor: Mas el que busca el mal, vendrále.",
      "28": "El que confía en sus riquezas, caerá: Mas los justos reverdecerán como ramos.",
      "29": "El que turba su casa heredará viento; Y el necio será siervo del sabio de corazón.",
      "30": "El fruto del justo es árbol de vida: Y el que prende almas, es sabio.",
      "31": "Ciertamente el justo será pagado en la tierra: ­Cuánto más el impío y el pecador!"
    },
    "12": {
      "1": "EL que ama la corrección ama la sabiduría: Mas el que aborrece la reprensión, es ignorante.",
      "2": "El bueno alcanzará favor de Jehová: Mas él condenará al hombre de malos pensamientos.",
      "3": "El hombre no se afirmará por medio de la impiedad: Mas la raíz de los justos no será movida.",
      "4": "La mujer virtuosa corona es de su marido: Mas la mala, como carcoma en sus huesos.",
      "5": "Los pensamientos de los justos son rectitud; Mas los consejos de los impíos, engaño.",
      "6": "Las palabras de los impíos son para acechar la sangre: Mas la boca de los rectos los librará.",
      "7": "Dios trastornará á los impíos, y no serán más: Mas la casa de los justos permanecerá.",
      "8": "Según su sabiduría es alabado el hombre: Mas el perverso de corazón será en menosprecio.",
      "9": "Mejor es el que es menospreciado y tiene servidores, Que el que se precia, y carece de pan.",
      "10": "El justo atiende á la vida de su bestia: Mas las entrañas de los impíos son crueles.",
      "11": "El que labra su tierra, se hartará de pan: Mas el que sigue los vagabundos es falto de entendimiento.",
      "12": "Desea el impío la red de los malos: Mas la raíz de los justos dará fruto.",
      "13": "El impío es enredado en la prevaricación de sus labios: Mas el justo saldrá de la tribulación.",
      "14": "El hombre será harto de bien del fruto de su boca: Y la paga de las manos del hombre le será dada.",
      "15": "El camino del necio es derecho en su opinión: Mas el que obedece al consejo es sabio.",
      "16": "El necio luego al punto da á conocer su ira: Mas el que disimula la injuria es cuerdo.",
      "17": "El que habla verdad, declara justicia; Mas el testigo mentiroso, engaño.",
      "18": "Hay quienes hablan como dando estocadas de espada: Mas la lengua de los sabios es medicina.",
      "19": "El labio de verdad permanecerá para siempre: Mas la lengua de mentira por un momento.",
      "20": "Engaño hay en el corazón de los que piensan mal: Mas alegría en el de los que piensan bien.",
      "21": "Ninguna adversidad acontecerá al justo: Mas los impíos serán llenos de mal.",
      "22": "Los labios mentirosos son abominación á Jehová: Mas los obradores de verdad su contentamiento.",
      "23": "El hombre cuerdo encubre la ciencia: Mas el corazón de los necios publica la necedad.",
      "24": "La mano de los diligentes se enseñoreará: Mas la negligencia será tributaria.",
      "25": "El cuidado congojoso en el corazón del hombre, lo abate; Mas la buena palabra lo alegra.",
      "26": "El justo hace ventaja á su prójimo: Mas el camino de los impíos les hace errar.",
      "27": "El indolente no chamuscará su caza: Mas el haber precioso del hombre es la diligencia.",
      "28": "En el camino de la justicia está la vida; Y la senda de su vereda no es muerte."
    },
    "13": {
      "1": "EL hijo sabio toma el consejo del padre: Mas el burlador no escucha las reprensiones.",
      "2": "Del fruto de su boca el hombre comerá bien: Mas el alma de los prevaricadores hallará mal.",
      "3": "El que guarda su boca guarda su alma: Mas el que mucho abre sus labios tendrá calamidad.",
      "4": "Desea, y nada alcanza el alma del perezoso: Mas el alma de los diligentes será engordada.",
      "5": "El justo aborrece la palabra de mentira: Mas el impío se hace odioso é infame.",
      "6": "La justicia guarda al de perfecto camino: Mas la impiedad trastornará al pecador.",
      "7": "Hay quienes se hacen ricos, y no tienen nada: Y hay quienes se hacen pobres, y tienen muchas riquezas.",
      "8": "La redención de la vida del hombre son sus riquezas: Pero el pobre no oye censuras.",
      "9": "La luz de los justos se alegrará: Mas apagaráse la lámpara de los impíos.",
      "10": "Ciertamente la soberbia parirá contienda: Mas con los avisados es la sabiduría.",
      "11": "Disminuiránse las riquezas de vanidad: Empero multiplicará el que allega con su mano.",
      "12": "La esperanza que se prolonga, es tormento del corazón: Mas árbol de vida es el deseo cumplido.",
      "13": "El que menosprecia la palabra, perecerá por ello: Mas el que teme el mandamiento, será recompensado.",
      "14": "la ley del sabio es manantial de vida, Para apartarse de los lazos de la muerte.",
      "15": "El buen entendimiento conciliará gracia: Mas el camino de los prevaricadores es duro.",
      "16": "Todo hombre cuerdo obra con sabiduría: Mas el necio manifestará necedad.",
      "17": "El mal mensajero caerá en mal: Mas el mensajero fiel es medicina.",
      "18": "Pobreza y vergüenza tendrá el que menosprecia el consejo: Mas el que guarda la corrección, será honrado.",
      "19": "El deseo cumplido deleita el alma: Pero apartarse del mal es abominación á los necios.",
      "20": "El que anda con los sabios, sabio será; Mas el que se allega á los necios, será quebrantado.",
      "21": "Mal perseguirá á los pecadores: Mas á los justos les será bien retribuído.",
      "22": "El bueno dejará herederos á los hijos de los hijos; Y el haber del pecador, para el justo está guardado.",
      "23": "En el barbecho de los pobres hay mucho pan: Mas piérdese por falta de juicio.",
      "24": "El que detiene el castigo, á su hijo aborrece: Mas el que lo ama, madruga á castigarlo.",
      "25": "El justo come hasta saciar su alma: Mas el vientre de los impíos tendrá necesidad."
    },
    "14": {
      "1": "LA mujer sabia edifica su casa: Mas la necia con sus manos la derriba.",
      "2": "El que camina en su rectitud teme á Jehová: Mas el pervertido en sus caminos lo menosprecia.",
      "3": "En la boca del necio está la vara de la soberbia: Mas los labios de los sabios los guardarán.",
      "4": "Sin bueyes el granero está limpio: Mas por la fuerza del buey hay abundancia de pan.",
      "5": "El testigo verdadero no mentirá: Mas el testigo falso hablará mentiras.",
      "6": "Busca el escarnecedor la sabiduría, y no la halla: Mas la sabiduría al hombre entendido es fácil.",
      "7": "Vete de delante del hombre necio, Porque en él no advertirás labios de ciencia.",
      "8": "La ciencia del cuerdo es entender su camino: Mas la indiscreción de los necios es engaño.",
      "9": "Los necios se mofan del pecado: Mas entre los rectos hay favor.",
      "10": "El corazón conoce la amargura de su alma; Y extraño no se entrometerá en su alegría.",
      "11": "La casa de los impíos será asolada: Mas florecerá la tienda de los rectos.",
      "12": "Hay camino que al hombre parece derecho; Empero su fin son caminos de muerte.",
      "13": "Aun en la risa tendrá dolor el corazón; Y el término de la alegría es congoja.",
      "14": "De sus caminos será harto el apartado de razón: Y el hombre de bien estará contento del suyo.",
      "15": "El simple cree á toda palabra: Mas el avisado entiende sus pasos.",
      "16": "El sabio teme, y se aparta del mal: Mas el necio se arrebata, y confía.",
      "17": "El que presto se enoja, hará locura: Y el hombre malicioso será aborrecido.",
      "18": "Los simples heredarán necedad: Mas los cuerdos se coronarán de sabiduría.",
      "19": "Los malos se inclinarán delante de los buenos, Y los impíos á las puertas del justo.",
      "20": "El pobre es odioso aun á su amigo: Pero muchos son los que aman al rico.",
      "21": "Peca el que menosprecia á su prójimo: Mas el que tiene misericordia de los pobres, es bienaventurado.",
      "22": "¿No yerran los que piensan mal? Misericordia empero y verdad alcanzarán los que piensan bien.",
      "23": "En toda labor hay fruto: Mas la palabra de los labios solamente empobrece.",
      "24": "Las riquezas de los sabios son su corona: Mas es infatuación la insensatez de los necios.",
      "25": "El testigo verdadero libra las almas: Mas el engañoso hablará mentiras.",
      "26": "En el temor de Jehová está la fuerte confianza; Y esperanza tendrán sus hijos.",
      "27": "El temor de Jehová es manantial de vida, Para apartarse de los lazos de la muerte.",
      "28": "En la multitud de pueblo está la gloria del rey: Y en la falta de pueblo la flaqueza del príncipe.",
      "29": "El que tarde se aira, es grande de entendimiento: Mas el corto de espíritu engrandece el desatino.",
      "30": "El corazón apacible es vida de las carnes: Mas la envidia, pudrimiento de huesos.",
      "31": "El que oprime al pobre, afrenta á su Hacedor: Mas el que tiene misericordia del pobre, lo honra.",
      "32": "Por su maldad será lanzado el impío: Mas el justo en su muerte tiene esperanza.",
      "33": "En el corazón del cuerdo reposa la sabiduría; Y es conocida en medio de los necios.",
      "34": "La justicia engrandece la nación: Mas el pecado es afrenta de las naciones.",
      "35": "La benevolencia del rey es para con el ministro entendido: Mas su enojo contra el que lo avergüenza."
    },
    "15": {
      "1": "LA blanda respuesta quita la ira: Mas la palabra áspera hace subir el furor.",
      "2": "La lengua de los sabios adornará la sabiduría: Mas la boca de los necios hablará sandeces.",
      "3": "Los ojos de Jehová están en todo lugar, Mirando á los malos y á los buenos.",
      "4": "La sana lengua es árbol de vida: Mas la perversidad en ella es quebrantamiento de espíritu.",
      "5": "El necio menosprecia el consejo de su padre: Mas el que guarda la corrección, vendrá á ser cuerdo.",
      "6": "En la casa del justo hay gran provisión; Empero turbación en las ganancias del impío.",
      "7": "Los labios de los sabios esparcen sabiduría: Mas no así el corazón de los necios.",
      "8": "El sacrificio de los impíos es abominación á Jehová: Mas la oración de los rectos es su gozo.",
      "9": "Abominación es á Jehová el camino del impío: Mas él ama al que sigue justicia.",
      "10": "La reconvención es molesta al que deja el camino: Y el que aborreciere la corrección, morirá.",
      "11": "El infierno y la perdición están delante de Jehová: ­Cuánto más los corazones de los hombres!",
      "12": "El escarnecedor no ama al que le reprende; Ni se allega á los sabios.",
      "13": "El corazón alegre hermosea el rostro: Mas por el dolor de corazón el espíritu se abate.",
      "14": "El corazón entendido busca la sabiduría: Mas la boca de los necios pace necedad.",
      "15": "Todos los días del afligido son trabajosos: Mas el de corazón contento tiene un convite continuo.",
      "16": "Mejor es lo poco con el temor de Jehová, Que el gran tesoro donde hay turbación.",
      "17": "Mejor es la comida de legumbres donde hay amor, Que de buey engordado donde hay odio.",
      "18": "El hombre iracundo mueve contiendas: Mas el que tarde se enoja, apaciguará la rencilla.",
      "19": "El camino del perezoso es como seto de espinos: Mas la vereda de los rectos como una calzada.",
      "20": "El hijo sabio alegra al padre: Mas el hombre necio menosprecia á su madre.",
      "21": "La necedad es alegría al falto de entendimiento: Mas el hombre entendido enderezará su proceder.",
      "22": "Los pensamientos son frustrados donde no hay consejo; Mas en la multitud de consejeros se afirman.",
      "23": "Alégrase el hombre con la respuesta de su boca: Y la palabra á su tiempo, ­cuán buena es!",
      "24": "El camino de la vida es hacia arriba al entendido, Para apartarse del infierno abajo.",
      "25": "Jehová asolará la casa de los soberbios: Mas él afirmará el término de la viuda.",
      "26": "Abominación son á Jehová los pensamientos del malo: Mas las expresiones de los limpios son limpias.",
      "27": "Alborota su casa el codicioso: Mas el que aborrece las dádivas vivirá.",
      "28": "El corazón del justo piensa para responder: Mas la boca de los impíos derrama malas cosas.",
      "29": "Lejos está Jehová de los impíos: Mas él oye la oración de los justos.",
      "30": "La luz de los ojos alegra el corazón; Y la buena fama engorda los huesos.",
      "31": "La oreja que escucha la corrección de vida, Entre los sabios morará.",
      "32": "El que tiene en poco la disciplina, menosprecia su alma: Mas el que escucha la corrección, tiene entendimiento.",
      "33": "El temor de Jehová es enseñanza de sabiduría: Y delante de la honra está la humildad."
    },
    "16": {
      "1": "DEL hombre son las disposiciones del corazón: Mas de Jehová la respuesta de la lengua.",
      "2": "Todos los caminos del hombre son limpios en su opinión: Mas Jehová pesa los espíritus.",
      "3": "Encomienda á Jehová tus obras, Y tus pensamientos serán afirmados.",
      "4": "Todas las cosas ha hecho Jehová por sí mismo, Y aun al impío para el día malo.",
      "5": "Abominación es á Jehová todo altivo de corazón: Aunque esté mano sobre mano, no será reputado inocente.",
      "6": "Con misericordia y verdad se corrige el pecado: Y con el temor de Jehová se apartan del mal los hombres.",
      "7": "Cuando los caminos del hombre son agradables á Jehová, Aun á sus enemigos pacificará con él.",
      "8": "Mejor es lo poco con justicia, Que la muchedumbre de frutos sin derecho.",
      "9": "El corazón del hombre piensa su camino: Mas Jehová endereza sus pasos.",
      "10": "Adivinación está en los labios del rey: En juicio no prevaricará su boca.",
      "11": "Peso y balanzas justas son de Jehová: Obra suya son todas las pesas de la bolsa.",
      "12": "Abominación es á los reyes hacer impiedad: Porque con justicia será afirmado el trono.",
      "13": "Los labios justos son el contentamiento de los reyes; Y aman al que habla lo recto.",
      "14": "La ira del rey es mensajero de muerte: Mas el hombre sabio la evitará.",
      "15": "En la alegría del rostro del rey está la vida; Y su benevolencia es como nube de lluvia tardía.",
      "16": "Mejor es adquirir sabiduría que oro preciado; Y adquirir inteligencia vale más que la plata.",
      "17": "El camino de los rectos es apartarse del mal: Su alma guarda el que guarda su camino.",
      "18": "Antes del quebrantamiento es la soberbia; Y antes de la caída la altivez de espíritu.",
      "19": "Mejor es humillar el espíritu con los humildes, Que partir despojos con los soberbios.",
      "20": "El entendido en la palabra, hallará el bien: Y el que confía en Jehová, él es bienaventurado.",
      "21": "El sabio de corazón es llamado entendido: Y la dulzura de labios aumentará la doctrina.",
      "22": "Manantial de vida es el entendimiento al que lo posee: Mas la erudición de los necios es necedad.",
      "23": "El corazón del sabio hace prudente su boca; Y con sus labios aumenta la doctrina.",
      "24": "Panal de miel son los dichos suaves. Suavidad al alma y medicina á los huesos.",
      "25": "Hay camino que parece derecho al hombre, Mas su salida son caminos de muerte.",
      "26": "El alma del que trabaja, trabaja para sí; Porque su boca le constriñe.",
      "27": "El hombre perverso cava el mal; Y en sus labios hay como llama de fuego.",
      "28": "El hombre perverso levanta contienda; Y el chismoso aparta los mejores amigos.",
      "29": "El hombre malo lisonjea á su prójimo, Y le hace andar por el camino no bueno:",
      "30": "Cierra sus ojos para pensar perversidades; Mueve sus labios, efectúa el mal.",
      "31": "Corona de honra es la vejez, Que se hallará en el camino de justicia.",
      "32": "Mejor es el que tarde se aira que el fuerte; Y el que se enseñorea de su espíritu, que el que toma una ciudad.",
      "33": "La suerte se echa en el seno: Mas de Jehová es el juicio de ella."
    },
    "17": {
      "1": "MEJOR es un bocado seco, y en paz, Que la casa de contienda llena de víctimas.",
      "2": "El siervo prudente se enseñoreará del hijo que deshonra, Y entre los hermanos partirá la herencia.",
      "3": "El crisol para la plata, y la hornaza para el oro: Mas Jehová prueba los corazones.",
      "4": "El malo está atento al labio inicuo; Y el mentiroso escucha á la lengua detractora.",
      "5": "El que escarnece al pobre, afrenta á su Hacedor: Y el que se alegra en la calamidad, no quedará sin castigo.",
      "6": "Corona de los viejos son los hijos de los hijos; Y la honra de los hijos, sus padres.",
      "7": "No conviene al necio la altilocuencia: ­Cuánto menos al príncipe el labio mentiroso!",
      "8": "Piedra preciosa es el cohecho en ojos de sus dueños: A donde quiera que se vuelve, da prosperidad.",
      "9": "El que cubre la prevaricación, busca amistad: Mas el que reitera la palabra, aparta al amigo.",
      "10": "Aprovecha la reprensión en el entendido, Más que si cien veces hiriese en el necio.",
      "11": "El rebelde no busca sino mal; Y mensajero cruel será contra él enviado.",
      "12": "Mejor es se encuentre un hombre con una osa á la cual han robado sus cachorros, Que con un fatuo en su necedad.",
      "13": "El que da mal por bien, No se apartará el mal de su casa.",
      "14": "El que comienza la pendencia es como quien suelta las aguas: Deja pues la porfía, antes que se enmarañe.",
      "15": "El que justifica al impío, y el que condena al justo, Ambos á dos son abominación á Jehová.",
      "16": "¿De qué sirve el precio en la mano del necio para comprar sabiduría, No teniendo entendimiento?",
      "17": "En todo tiempo ama el amigo; Y el hermano para la angustia es nacido.",
      "18": "El hombre falto de entendimiento toca la mano, Fiando á otro delante de su amigo.",
      "19": "La prevaricación ama el que ama pleito; Y el que alza su portada, quebrantamiento busca.",
      "20": "El perverso de corazón nunca hallará bien: Y el que revuelve con su lengua, caerá en mal.",
      "21": "El que engendra al necio, para su tristeza lo engendra: Y el padre del fatuo no se alegrará.",
      "22": "El corazón alegre produce buena disposición: Mas el espíritu triste seca los huesos.",
      "23": "El impío toma dádiva del seno Para pervertir las sendas del derecho.",
      "24": "En el rostro del entendido aparece la sabiduría: Mas los ojos del necio vagan hasta el cabo de la tierra.",
      "25": "El hijo necio es enojo á su padre, Y amargura á la que lo engendró.",
      "26": "Ciertamente no es bueno condenar al justo, Ni herir á los príncipes que hacen lo recto.",
      "27": "Detiene sus dichos el que tiene sabiduría: De prudente espíritu es el hombre entendido.",
      "28": "Aun el necio cuando calla, es contado por sabio: El que cierra sus labios es entendido."
    },
    "18": {
      "1": "SEGUN su antojo busca el que se desvía, Y se entremete en todo negocio.",
      "2": "No toma placer el necio en la inteligencia, Sino en lo que su corazón se descubre.",
      "3": "Cuando viene el impío, viene también el menosprecio, Y con el deshonrador la afrenta.",
      "4": "Aguas profundas son las palabras de la boca del hombre; Y arroyo revertiente, la fuente de la sabiduría.",
      "5": "Tener respeto á la persona del impío, Para hacer caer al justo de su derecho, no es bueno.",
      "6": "Los labios del necio vienen con pleito; Y su boca á cuestiones llama.",
      "7": "La boca del necio es quebrantamiento para sí, Y sus labios son lazos para su alma.",
      "8": "Las palabras del chismoso parecen blandas, Y descienden hasta lo íntimo del vientre.",
      "9": "También el que es negligente en su obra Es hermano del hombre disipador.",
      "10": "Torre fuerte es el nombre de Jehová: A él correrá el justo, y será levantado.",
      "11": "Las riquezas del rico son la ciudad de su fortaleza, Y como un muro alto en su imaginación.",
      "12": "Antes del quebrantamiento se eleva el corazón del hombre, Y antes de la honra es el abatimiento.",
      "13": "El que responde palabra antes de oir, Le es fatuidad y oprobio.",
      "14": "El ánimo del hombre soportará su enfermedad: Mas ¿quién soportará al ánimo angustiado?",
      "15": "El corazón del entendido adquiere sabiduría; Y el oído de los sabios busca la ciencia.",
      "16": "El presente del hombre le ensancha el camino, Y le lleva delante de los grandes.",
      "17": "El primero en su propia causa parece justo; Y su adversario viene, y le sondea.",
      "18": "La suerte pone fin á los pleitos, Y desparte los fuertes.",
      "19": "El hermano ofendido es más tenaz que una ciudad fuerte: Y las contiendas de los hermanos son como cerrojos de alcázar.",
      "20": "Del fruto de la boca del hombre se hartará su vientre; Hartaráse del producto de sus labios.",
      "21": "La muerte y la vida están en poder de la lengua; Y el que la ama comerá de sus frutos.",
      "22": "El que halló esposa halló el bien, Y alcanzó la benevolencia de Jehová.",
      "23": "El pobre habla con ruegos; Mas el rico responde durezas.",
      "24": "El hombre que tiene amigos, ha de mostrarse amigo: Y amigo hay más conjunto que el hermano."
    },
    "19": {
      "1": "MEJOR es el pobre que camina en su sencillez, Que el de perversos labios y fatuo.",
      "2": "El alma sin ciencia no es buena; Y el presuroso de pies peca.",
      "3": "La insensatez del hombre tuerce su camino; Y contra Jehová se aira su corazón.",
      "4": "Las riquezas allegan muchos amigos: Mas el pobre, de su amigo es apartado.",
      "5": "El testigo falso no quedará sin castigo; Y el que habla mentiras no escapará.",
      "6": "Muchos rogarán al príncipe: Mas cada uno es amigo del hombre que da.",
      "7": "Todos los hermanos del pobre le aborrecen: ­Cuánto más sus amigos se alejarán de él! Buscará la palabra y no la hallará.",
      "8": "El que posee entendimiento, ama su alma: El que guarda la inteligencia, hallará el bien.",
      "9": "El testigo falso no quedará sin castigo; Y el que habla mentiras, perecerá.",
      "10": "No conviene al necio el deleite: ­Cuánto menos al siervo ser señor de los príncipes!",
      "11": "La cordura del hombre detiene su furor; Y su honra es disimular la ofensa.",
      "12": "Como el bramido del cachorro de león es la ira del rey; Y su favor como el rocío sobre la hierba.",
      "13": "Dolor es para su padre el hijo necio; Y gotera continua las contiendas de la mujer.",
      "14": "La casa y las riquezas herencia son de los padres: Mas de Jehová la mujer prudente.",
      "15": "La pereza hace caer en sueño; Y el alma negligente hambreará.",
      "16": "El que guarda el mandamiento, guarda su alma: Mas el que menospreciare sus caminos, morirá.",
      "17": "A Jehová empresta el que da al pobre, Y él le dará su paga.",
      "18": "Castiga á tu hijo en tanto que hay esperanza; Mas no se excite tu alma para destruirlo.",
      "19": "El de grande ira llevará la pena: Y si usa de violencias, añadirá nuevos males.",
      "20": "Escucha el consejo, y recibe la corrección, Para que seas sabio en tu vejez.",
      "21": "Muchos pensamientos hay en el corazón del hombre; Mas el consejo de Jehová permanecerá.",
      "22": "Contentamiento es á los hombres hacer misericordia: Pero mejor es el pobre que el mentiroso.",
      "23": "El temor de Jehová es para vida; Y con él vivirá el hombre, lleno de reposo; No será visitado de mal.",
      "24": "El perezoso esconde su mano en el seno: Aun á su boca no la llevará.",
      "25": "Hiere al escarnecedor, y el simple se hará avisado; Y corrigiendo al entendido, entenderá ciencia.",
      "26": "El que roba á su padre y ahuyenta á su madre, Hijo es avergonzador y deshonrador.",
      "27": "Cesa, hijo mío, de oir la enseñanza Que induce á divagar de las razones de sabiduría.",
      "28": "El testigo perverso se burlará del juicio; Y la boca de los impíos encubrirá la iniquidad.",
      "29": "Aparejados están juicios para los escarnecedores, Y azotes para los cuerpos de los insensatos."
    },
    "20": {
      "1": "EL vino es escarnecedor, la cerveza alborotadora; Y cualquiera que por ello errare, no será sabio.",
      "2": "Como bramido de cachorro de león es el terror del rey: El que lo hace enfurecerse, peca contra su alma.",
      "3": "Honra es del hombre dejarse de contienda: Mas todo insensato se envolverá en ella.",
      "4": "El perezoso no ara á causa del invierno; Pedirá pues en la siega, y no hallará.",
      "5": "Como aguas profundas es el consejo en el corazón del hombre: Mas el hombre entendido lo alcanzará.",
      "6": "Muchos hombres publican cada uno su liberalidad: Mas hombre de verdad, ¿quién lo hallará?",
      "7": "El justo que camina en su integridad, Bienaventurados serán sus hijos después de él.",
      "8": "El rey que se sienta en el trono de juicio, Con su mirar disipa todo mal.",
      "9": "¿Quién podrá decir: Yo he limpiado mi corazón, Limpio estoy de mi pecado?",
      "10": "Doble pesa y doble medida, Abominación son á Jehová ambas cosas.",
      "11": "Aun el muchacho es conocido por sus hechos, Si su obra fuere limpia y recta.",
      "12": "El oído que oye, y el ojo que ve, Ambas cosas ha igualmente hecho Jehová.",
      "13": "No ames el sueño, porque no te empobrezcas; Abre tus ojos, y te hartarás de pan.",
      "14": "El que compra dice: Malo es, malo es: Mas en apartándose, se alaba.",
      "15": "Hay oro y multitud de piedras preciosas: Mas los labios sabios son vaso precioso.",
      "16": "Quítale su ropa al que salió por fiador del extraño; Y tómale prenda al que fía la extraña.",
      "17": "Sabroso es al hombre el pan de mentira; Mas después su boca será llena de cascajo.",
      "18": "Los pensamientos con el consejo se ordenan: Y con industria se hace la guerra.",
      "19": "El que descubre el secreto, en chismes anda: No te entrometas, pues, con el que lisonjea con sus labios.",
      "20": "El que maldice á su padre ó á su madre, Su lámpara será apagada en oscuridad tenebrosa.",
      "21": "La herencia adquirida de priesa al principio, Aun su postrimería no será bendita.",
      "22": "No digas, yo me vengaré; Espera á Jehová, y él te salvará.",
      "23": "Abominación son á Jehová las pesas dobles; Y el peso falso no es bueno.",
      "24": "De Jehová son los pasos del hombre: ¿Cómo pues entenderá el hombre su camino?",
      "25": "Lazo es al hombre el devorar lo santo, Y andar pesquisando después de los votos.",
      "26": "El rey sabio esparce los impíos. Y sobre ellos hace tornar la rueda.",
      "27": "Candela de Jehová es el alma del hombre, Que escudriña lo secreto del vientre.",
      "28": "Misericordia y verdad guardan al rey; Y con clemencia sustenta su trono.",
      "29": "La gloria de los jóvenes es su fortaleza, Y la hermosura de los viejos la vejez.",
      "30": "Las señales de las heridas son medicina para lo malo: Y las llagas llegan á lo más secreto del vientre."
    },
    "21": {
      "1": "COMO los repartimientos de las aguas, así está el corazón del rey en la mano de Jehová: A todo lo que quiere lo inclina.",
      "2": "Todo camino del hombre es recto en su opinión: Mas Jehová pesa los corazones.",
      "3": "Hacer justicia y juicio es á Jehová Más agradable que sacrificio.",
      "4": "Altivez de ojos, y orgullo de corazón, Y el brillo de los impíos, son pecado.",
      "5": "Los pensamientos del solícito ciertamente van á abundancia; Mas todo presuroso, indefectiblemente á pobreza.",
      "6": "Allegar tesoros con lengua de mentira, Es vanidad desatentada de aquellos que buscan la muerte.",
      "7": "La rapiña de los impíos los destruirá; Por cuanto no quisieron hacer juicio.",
      "8": "El camino del hombre perverso es torcido y extraño: Mas la obra del limpio es recta.",
      "9": "Mejor es vivir en un rincón de zaquizamí. Que con la mujer rencillosa en espaciosa casa.",
      "10": "El alma del impío desea mal: Su prójimo no le parece bien.",
      "11": "Cuando el escarnecedor es castigado, el simple se hace sabio; Y cuando se amonestare al sabio, aprenderá ciencia.",
      "12": "Considera el justo la casa del impío: Cómo los impíos son trastornados por el mal.",
      "13": "El que cierra su oído al clamor del pobre, También él clamará, y no será oído.",
      "14": "El presente en secreto amansa el furor, Y el don en el seno, la fuerte ira.",
      "15": "Alegría es al justo hacer juicio; Mas quebrantamiento á los que hacen iniquidad.",
      "16": "El hombre que se extravía del camino de la sabiduría, Vendrá á parar en la compañía de los muertos.",
      "17": "Hombre necesitado será el que ama el deleite: Y el que ama el vino y ungüentos no enriquecerá.",
      "18": "El rescate del justo es el impío, Y por los rectos el prevaricador.",
      "19": "Mejor es morar en tierra del desierto, Que con la mujer rencillosa é iracunda.",
      "20": "Tesoro codiciable y pingüe hay en la casa del sabio; Mas el hombre insensato lo disipará.",
      "21": "El que sigue la justicia y la misericordia, Hallará la vida, la justicia, y la honra.",
      "22": "La ciudad de los fuertes tomó el sabio, Y derribó la fuerza en que ella confiaba.",
      "23": "El que guarda su boca y su lengua, Su alma guarda de angustias.",
      "24": "Soberbio y presuntuoso escarnecedor es el nombre Del que obra con orgullosa saña.",
      "25": "El deseo del perezoso le mata, Porque sus manos no quieren trabajar.",
      "26": "Hay quien todo el día codicia: Mas el justo da, y no desperdicia.",
      "27": "El sacrificio de los impíos es abominación: ­Cuánto más ofreciéndolo con maldad!",
      "28": "El testigo mentiroso perecerá: Mas el hombre que oye, permanecerá en su dicho.",
      "29": "El hombre impío afirma rostro: Mas el recto ordena sus caminos.",
      "30": "No hay sabiduría, ni inteligencia, Ni consejo, contra Jehová.",
      "31": "El caballo se apareja para el día de la batalla: Mas de Jehová es el salvar."
    },
    "22": {
      "1": "DE más estima es la buena fama que las muchas riquezas; Y la buena gracia más que la plata y el oro.",
      "2": "El rico y el pobre se encontraron: A todos ellos hizo Jehová.",
      "3": "El avisado ve el mal, y escóndese: Mas los simples pasan, y reciben el daño.",
      "4": "Riquezas, y honra, y vida, Son la remuneración de la humildad y del temor de Jehová.",
      "5": "Espinas y lazos hay en el camino del perverso: El que guarda su alma se alejará de ellos.",
      "6": "Instruye al niño en su carrera: Aun cuando fuere viejo no se apartará de ella.",
      "7": "El rico se enseñoreará de los pobres; Y el que toma prestado, siervo es del que empresta.",
      "8": "El que sembrare iniquidad, iniquidad segará: Y consumiráse la vara de su ira.",
      "9": "El ojo misericordioso será bendito, Porque dió de su pan al indigente.",
      "10": "Echa fuera al escarnecedor, y saldrá la contienda, Y cesará el pleito y la afrenta.",
      "11": "El que ama la limpieza de corazón, Por la gracia de sus labios su amigo será el rey.",
      "12": "Los ojos de Jehová miran por la ciencia; Mas él trastorna las cosas de los prevaricadores.",
      "13": "Dice el perezoso: El león está fuera; En mitad de las calles seré muerto.",
      "14": "Sima profunda es la boca de las extrañas: Aquel contra el cual estuviere Jehová airado, caerá en ella.",
      "15": "La necedad está ligada en el corazón del muchacho; Mas la vara de la corrección la hará alejar de él.",
      "16": "El que oprime al pobre para aumentarse él, Y que da al rico, ciertamente será pobre.",
      "17": "Inclina tu oído, y oye las palabras de los sabios, Y pon tu corazón á mi sabiduría:",
      "18": "Porque es cosa deleitable, si las guardares en tus entrañas; Y que juntamente sean ordenadas en tus labios.",
      "19": "Para que tu confianza sea en Jehová, Te las he hecho saber hoy á ti también.",
      "20": "¿No te he escrito tres veces En consejos y ciencia,",
      "21": "Para hacerte saber la certidumbre de las razones verdaderas, Para que puedas responder razones de verdad á los que á ti enviaren?",
      "22": "No robes al pobre, porque es pobre, Ni quebrantes en la puerta al afligido:",
      "23": "Porque Jehová juzgará la causa de ellos, Y despojará el alma de aquellos que los despojaren.",
      "24": "No te entrometas con el iracundo, Ni te acompañes con el hombre de enojos;",
      "25": "Porque no aprendas sus maneras, Y tomes lazo para tu alma.",
      "26": "No estés entre los que tocan la mano, Entre los que fían por deudas.",
      "27": "Si no tuvieres para pagar, ¿Por qué han de quitar tu cama de debajo de ti?",
      "28": "No traspases el término antiguo Que pusieron tus padres.",
      "29": "¿Has visto hombre solícito en su obra? delante de los reyes estará; No estará delante de los de baja suerte."
    },
    "23": {
      "1": "CUANDO te sentares á comer con algún señor, Considera bien lo que estuviere delante de ti;",
      "2": "Y pon cuchillo á tu garganta, Si tienes gran apetito.",
      "3": "No codicies sus manjares delicados, Porque es pan engañoso",
      "4": "No trabajes por ser rico; Pon coto á tu prudencia.",
      "5": "¿Has de poner tus ojos en las riquezas, siendo ningunas? Porque hacerse han alas, Como alas de águila, y volarán al cielo.",
      "6": "No comas pan de hombre de mal ojo, Ni codicies sus manjares:",
      "7": "Porque cual es su pensamiento en su alma, tal es él. Come y bebe, te dirá; Mas su corazón no está contigo.",
      "8": "Vomitarás la parte que tú comiste, Y perderás tus suaves palabras.",
      "9": "No hables á oídos del necio; Porque menospreciará la prudencia de tus razones.",
      "10": "No traspases el término antiguo, Ni entres en la heredad de los huérfanos:",
      "11": "Porque el defensor de ellos es el Fuerte, El cual juzgará la causa de ellos contra ti.",
      "12": "Aplica tu corazón á la enseñanza, Y tus oídos á las palabras de sabiduría.",
      "13": "No rehuses la corrección del muchacho: Porque si lo hirieres con vara, no morirá.",
      "14": "Tú lo herirás con vara, Y librarás su alma del infierno.",
      "15": "Hijo mío, si tu corazón fuere sabio, También á mí se me alegrará el corazón;",
      "16": "Mis entrañas también se alegrarán, Cuando tus labios hablaren cosas rectas.",
      "17": "No tenga tu corazón envidia de los pecadores, Antes persevera en el temor de Jehová todo tiempo:",
      "18": "Porque ciertamente hay fin, Y tu esperanza no será cortada.",
      "19": "Oye tú, hijo mío, y sé sabio, Y endereza tu corazón al camino.",
      "20": "No estés con los bebedores de vino, Ni con los comedores de carne:",
      "21": "Porque el bebedor y el comilón empobrecerán: Y el sueño hará vestir vestidos rotos.",
      "22": "Oye á tu padre, á aquel que te engendró; Y cuando tu madre envejeciere, no la menosprecies.",
      "23": "Compra la verdad, y no la vendas; La sabiduría, la enseñanza, y la inteligencia.",
      "24": "Mucho se alegrará el padre del justo: Y el que engendró sabio se gozará con él.",
      "25": "Alégrense tu padre y tu madre, Y gócese la que te engendró.",
      "26": "Dame, hijo mío, tu corazón, Y miren tus ojos por mis caminos.",
      "27": "Porque sima profunda es la ramera, Y pozo angosto la extraña.",
      "28": "También ella, como robador, acecha, Y multiplica entre los hombres los prevaricadores.",
      "29": "¿Para quién será el ay? ¿para quién el ay? ¿para quién las rencillas? ¿Para quién las quejas? ¿para quién las heridas en balde? ¿Para quién lo amoratado de los ojos?",
      "30": "Para los que se detienen mucho en el vino, Para los que van buscando la mistura.",
      "31": "No mires al vino cuando rojea, Cuando resplandece su color en el vaso: Entrase suavemente;",
      "32": "Mas al fin como serpiente morderá, Y como basilisco dará dolor:",
      "33": "Tus ojos mirarán las extrañas, Y tu corazón hablará perversidades.",
      "34": "Y serás como el que yace en medio de la mar, O como el que está en la punta de un mastelero.",
      "35": "Y dirás: Hiriéronme, mas no me dolió; Azotáronme, mas no lo sentí; Cuando despertare, aun lo tornaré á buscar."
    }
  }
};

