
	
export const bib_verses = {
  "leviticus": {
    "10": {
      "1": "Y LOS hijos de Aarón, Nadab y Abiú, tomaron cada uno su incensario, y pusieron fuego en ellos, sobre el cual pusieron perfume, y ofrecieron delante de Jehová fuego extraño, que él nunca les mandó.",
      "2": "Y salió fuego de delante de Jehová que los quemó, y murieron delante de Jehová.",
      "3": "Entonces dijo Moisés á Aarón: Esto es lo que habló Jehová, diciendo: En mis allegados me santificaré, y en presencia de todo el pueblo seré glorificado. Y Aarón calló.",
      "4": "Y llamó Moisés á Misael, y á Elzaphán, hijos de Uzziel, tío de Aarón, y díjoles: Llegaos y sacad á vuestros hermanos de delante del santuario fuera del campo.",
      "5": "Y ellos llegaron, y sacáronlos con sus túnicas fuera del campo, como dijo Moisés.",
      "6": "Entonces Moisés dijo á Aarón, y á Eleazar y á Ithamar, sus hijos: No descubráis vuestras cabezas, ni rasguéis vuestros vestidos, porque no muráis, ni se levante la ira sobre toda la congregación: empero vuestros hermanos, toda la casa de Israel, lamentarán el incendio que Jehová ha hecho.",
      "7": "Ni saldréis de la puerta del tabernáculo del testimonio, porque moriréis; por cuanto el aceite de la unción de Jehová está sobre vosotros. Y ellos hicieron conforme al dicho de Moisés.",
      "8": "Y Jehová habló á Aarón, diciendo:",
      "9": "Tú, y tus hijos contigo, no beberéis vino ni sidra, cuando hubiereis de entrar en el tabernáculo del testimonio, porque no muráis: estatuto perpetuo por vuestras generaciones;",
      "10": "Y para poder discernir entre lo santo y lo profano, y entre lo inmundo y lo limpio;",
      "11": "Y para enseñar á los hijos de Israel todos los estatutos que Jehová les ha dicho por medio de Moisés.",
      "12": "Y Moisés dijo á Aarón, y á Eleazar y á Ithamar, sus hijos que habían quedado: Tomad el presente que queda de las ofrendas encendidas á Jehová, y comedlo sin levadura junto al altar, porque es cosa muy santa.",
      "13": "Habéis, pues, de comerlo en el lugar santo: porque esto es fuero para ti, y fuero para tus hijos, de las ofrendas encendidas á Jehová, pues que así me ha sido mandado.",
      "14": "Comeréis asimismo en lugar limpio, tú y tus hijos y tus hijas contigo, el pecho de la mecida, y la espaldilla elevada, porque por fuero para ti, y fuero para tus hijos, son dados de los sacrificios de las paces de los hijos de Israel.",
      "15": "Con las ofrendas de los sebos que se han de encender, traerán la espaldilla que se ha de elevar, y el pecho que será mecido, para que lo mezas por ofrenda agitada delante de Jehová: y será por fuero perpetuo tuyo, y de tus hijos contigo, como Jehová lo ha mandado.",
      "16": "Y Moisés demandó el macho cabrío de la expiación, y hallóse que era quemado: y enojóse contra Eleazar é Ithamar, los hijos de Aarón que habían quedado, diciendo:",
      "17": "¿Por qué no comisteis la expiación en el lugar santo? porque es muy santa, y dióla él á vosotros para llevar la iniquidad de la congregación, para que sean reconciliados delante de Jehová.",
      "18": "Veis que su sangre no fue metida dentro del santuario: habíais de comerla en el lugar santo, como yo mandé.",
      "19": "Y respondió Aarón á Moisés: He aquí hoy han ofrecido su expiación y su holocausto delante de Jehová: pero me han acontecido estas cosas: pues si comiera yo hoy de la expiación, ¿Hubiera sido acepto á Jehová?",
      "20": "Y cuando Moisés oyó esto, dióse por satisfecho."
    },
    "11": {
      "1": "Y HABLO Jehová á Moisés y á Aarón, diciéndoles:",
      "2": "Hablad á los hijos de Israel, diciendo: Estos son los animales que comeréis de todos los animales que están sobre la tierra.",
      "3": "De entre los animales, todo el de pezuña, y que tiene las pezuñas hendidas, y que rumia, éste comeréis.",
      "4": "Estos empero no comeréis de los que rumian y de los que tienen pezuña: el camello, porque rumia mas no tiene pezuña hendida, habéis de tenerlo por inmundo;",
      "5": "También el conejo, porque rumia, mas no tiene pezuña, tendréislo por inmundo;",
      "6": "Asimismo la liebre, porque rumia, mas no tiene pezuña, tendréisla por inmunda;",
      "7": "También el puerco, porque tiene pezuñas, y es de pezuñas hendidas, mas no rumia, tendréislo por inmundo.",
      "8": "De la carne de ellos no comeréis, ni tocaréis su cuerpo muerto: tendréislos por inmundos.",
      "9": "Esto comeréis de todas las cosas que están en las aguas: todas las cosas que tienen aletas y escamas en las aguas de la mar, y en los ríos, aquellas comeréis;",
      "10": "Mas todas las cosas que no tienen aletas ni escamas en la mar y en los ríos, así de todo reptil de agua como de toda cosa viviente que está en las aguas, las tendréis en abominación.",
      "11": "Os serán, pues, en abominación: de su carne no comeréis, y abominaréis sus cuerpos muertos.",
      "12": "Todo lo que no tuviere aletas y escamas en las aguas, tendréislo en abominación.",
      "13": "Y de las aves, éstas tendréis en abominación; no se comerán, serán abominación: el águila, el quebrantahuesos, el esmerejón,",
      "14": "El milano, y el buitre según su especie;",
      "15": "Todo cuervo según su especie;",
      "16": "El avestruz, y la lechuza, y el laro, y el gavilán según su especie;",
      "17": "Y el buho, y el somormujo, y el ibis,",
      "18": "Y el calamón, y el cisne, y el onocrótalo,",
      "19": "Y el herodión, y el caradrión, según su especie, y la abubilla, y el murciélago.",
      "20": "Todo reptil alado que anduviere sobre cuatro pies, tendréis en abominación.",
      "21": "Empero esto comeréis de todo reptil alado que anda sobre cuatro pies, que tuviere piernas además de sus pies para saltar con ellas sobre la tierra;",
      "22": "Estos comeréis de ellos: la langosta según su especie, y el langostín según su especie, y el aregol según su especie, y el haghab según su especie.",
      "23": "Todo reptil alado que tenga cuatro pies, tendréis en abominación.",
      "24": "Y por estas cosas seréis inmundos: cualquiera que tocare á sus cuerpos muertos, será inmundo hasta la tarde:",
      "25": "Y cualquiera que llevare de sus cuerpos muertos, lavará sus vestidos, y será inmundo hasta la tarde.",
      "26": "Todo animal de pezuña, pero que no tiene pezuña hendida, ni rumia, tendréis por inmundo: cualquiera que los tocare será inmundo.",
      "27": "Y de todos los animales que andan á cuatro pies, tendréis por inmundo cualquiera que ande sobre sus garras: cualquiera que tocare sus cuerpos muertos, será inmundo hasta la tarde.",
      "28": "Y el que llevare sus cuerpos muertos, lavará sus vestidos, y será inmundo hasta la tarde: habéis de tenerlos por inmundos.",
      "29": "Y estos tendréis por inmundos de los reptiles que van arrastrando sobre la tierra: la comadreja, y el ratón, y la rana según su especie,",
      "30": "Y el erizo, y el lagarto, y el caracol, y la babosa, y el topo.",
      "31": "Estos tendréis por inmundos de todos los reptiles: cualquiera que los tocare, cuando estuvieren muertos, será inmundo hasta la tarde.",
      "32": "Y todo aquello sobre que cayere alguno de ellos después de muertos, será inmundo; así vaso de madera, como vestido, ó piel, ó saco, cualquier instrumento con que se hace obra, será metido en agua, y será inmundo hasta la tarde, y así será limpio.",
      "33": "Y toda vasija de barro dentro de la cual cayere alguno de ellos, todo lo que estuviere en ella será inmundo, y quebraréis la vasija:",
      "34": "Toda vianda que se come, sobre la cual viniere el agua de tales vasijas, será inmunda: y toda bebida que se bebiere, será en todas esas vasijas inmunda:",
      "35": "Y todo aquello sobre que cayere algo del cuerpo muerto de ellos, será inmundo: el horno ú hornillos se derribarán; son inmundos, y por inmundos los tendréis.",
      "36": "Con todo, la fuente y la cisterna donde se recogen aguas, serán limpias: mas lo que hubiere tocado en sus cuerpos muertos será inmundo.",
      "37": "Y si cayere de sus cuerpos muertos sobre alguna simiente que se haya de sembrar, será limpia.",
      "38": "Mas si se hubiere puesto agua en la simiente, y cayere de sus cuerpos muertos sobre ella, tendréisla por inmunda.",
      "39": "Y si algún animal que tuviereis para comer se muriere, el que tocare su cuerpo muerto será inmundo hasta la tarde:",
      "40": "Y el que comiere de su cuerpo muerto, lavará sus vestidos, y será inmundo hasta la tarde: asimismo el que sacare su cuerpo muerto, lavará sus vestidos, y será inmundo hasta la tarde.",
      "41": "Y todo reptil que va arrastrando sobre la tierra, es abominación; no se comerá.",
      "42": "Todo lo que anda sobre el pecho, y todo lo que anda sobre cuatro ó más pies, de todo reptil que anda arrastrando sobre la tierra, no lo comeréis, porque es abominación.",
      "43": "No ensuciéis vuestras personas con ningún reptil que anda arrastrando, ni os contaminéis con ellos, ni seáis inmundos por ellos.",
      "44": "Pues que yo soy Jehová vuestro Dios, vosotros por tanto os santificaréis, y seréis santos, porque yo soy santo: así que no ensuciéis vuestras personas con ningún reptil que anduviere arrastrando sobre la tierra.",
      "45": "Porque yo soy Jehová, que os hago subir de la tierra de Egipto para seros por Dios: seréis pues santos, porque yo soy santo.",
      "46": "Esta es la ley de los animales y de las aves, y de todo ser viviente que se mueve en las aguas, y de todo animal que anda arrastrando sobre la tierra;",
      "47": "Para hacer diferencia entre inmundo y limpio, y entre los animales que se pueden comer y los animales que no se pueden comer."
    },
    "12": {
      "1": "Y HABLO Jehová á Moisés, diciendo:",
      "2": "Habla á los hijos de Israel, diciendo: La mujer cuando concibiere y pariere varón, será inmunda siete días; conforme á los días que está separada por su menstruo, será inmunda.",
      "3": "Y al octavo día circuncidará la carne de su prepucio.",
      "4": "Mas ella permanecerá treinta y tres días en la sangre de su purgación: ninguna cosa santa tocará, ni vendrá al santuario, hasta que sean cumplidos los días de su purgación.",
      "5": "Y si pariere hembra será inmunda dos semanas, conforme á su separación, y sesenta y seis días estará purificándose de su sangre.",
      "6": "Y cuando los días de su purgación fueren cumplidos, por hijo ó por hija, traerá un cordero de un año para holocausto, y un palomino ó una tórtola para expiación, á la puerta del tabernáculo del testimonio, al sacerdote:",
      "7": "Y él ofrecerá delante de Jehová, y hará expiación por ella, y será limpia del flujo de su sangre. Esta es la ley de la que pariere varón ó hembra.",
      "8": "Y si no alcanzare su mano lo suficiente para un cordero, tomará entonces dos tórtolas ó dos palominos, uno para holocausto, y otro para expiación: y el sacerdote hará expiación por ella, y será limpia."
    },
    "13": {
      "1": "Y HABLO Jehová á Moisés y á Aarón, diciendo:",
      "2": "Cuando el hombre tuviere en la piel de su carne hinchazón, ó postilla, ó mancha blanca, y hubiere en la piel de su carne como llaga de lepra, será traído á Aarón el sacerdote, ó á uno de los sacerdotes sus hijos:",
      "3": "Y el sacerdote mirará la llaga en la piel de la carne: si el pelo en la llaga se ha vuelto blanco, y pareciere la llaga más hundida que la tez de la carne, llaga de lepra es; y el sacerdote le reconocerá, y le dará por inmundo.",
      "4": "Y si en la piel de su carne hubiere mancha blanca, pero no pareciere más hundida que la tez, ni su pelo se hubiere vuelto blanco, entonces el sacerdote encerrará al llagado por siete días;",
      "5": "Y al séptimo día el sacerdote lo mirará; y si la llaga a su parecer se hubiere estancado, no habiéndose extendido en la piel, entonces el sacerdote le volverá á encerrar por otros siete días.",
      "6": "Y al séptimo día el sacerdote le reconocerá de nuevo; y si parece haberse oscurecido la llaga, y que no ha cundido en la piel, entonces el sacerdote lo dará por limpio: era postilla; y lavará sus vestidos, y será limpio.",
      "7": "Mas si hubiere ido creciendo la postilla en la piel, después que fué mostrado al sacerdote para ser limpio, será visto otra vez del sacerdote:",
      "8": "Y si reconociéndolo el sacerdote, ve que la postilla ha crecido en la piel, el sacerdote lo dará por inmundo: es lepra.",
      "9": "Cuando hubiere llaga de lepra en el hombre, será traído al sacerdote;",
      "10": "Y el sacerdote mirará, y si pareciere tumor blanco en la piel, el cual haya mudado el color del pelo, y se descubre asimismo la carne viva,",
      "11": "Lepra es envejecida en la piel de su carne; y le dará por inmundo el sacerdote, y no le encerrará, porque es inmundo.",
      "12": "Mas si brotare la lepra cundiendo por el cutis, y ella cubriere toda la piel del llagado desde su cabeza hasta sus pies, á toda vista de ojos del sacerdote;",
      "13": "Entonces el sacerdote le reconocerá; y si la lepra hubiere cubierto toda su carne, dará por limpio al llagado: hase vuelto toda ella blanca; y él es limpio.",
      "14": "Mas el día que apareciere en él la carne viva, será inmundo.",
      "15": "Y el sacerdote mirará la carne viva, y lo dará por inmundo. Es inmunda la carne viva: es lepra.",
      "16": "Mas cuando la carne viva se mudare y volviere blanca, entonces vendrá al sacerdote;",
      "17": "Y el sacerdote mirará, y si la llaga se hubiere vuelto blanca, el sacerdote dará por limpio al que tenía la llaga, y será limpio.",
      "18": "Y cuando en la carne, en su piel, hubiere apostema, y se sanare,",
      "19": "Y sucediere en el lugar de la apostema tumor blanco, ó mancha blanca embermejecida, será mostrado al sacerdote:",
      "20": "Y el sacerdote mirará; y si pareciere estar más baja que su piel, y su pelo se hubiere vuelto blanco, darálo el sacerdote por inmundo: es llaga de lepra que se originó en la apostema.",
      "21": "Y si el sacerdote la considerare, y no pareciere en ella pelo blanco, ni estuviere más baja que la piel, sino oscura, entonces el sacerdote lo encerrará por siete días:",
      "22": "Y si se fuere extendiendo por la piel, entonces el sacerdote lo dará por inmundo: es llaga.",
      "23": "Empero si la mancha blanca se estuviere en su lugar, que no haya cundido, es la costra de la apostema; y el sacerdote lo dará por limpio.",
      "24": "Asimismo cuando la carne tuviere en su piel quemadura de fuego, y hubiere en lo sanado del fuego mancha blanquecina, bermejiza ó blanca,",
      "25": "El sacerdote la mirará; y si el pelo se hubiere vuelto blanco en la mancha, y pareciere estar más hundida que la piel, es lepra que salió en la quemadura; y el sacerdote declarará al sujeto inmundo, por ser llaga de lepra.",
      "26": "Mas si el sacerdote la mirare, y no pareciere en la mancha pelo blanco, ni estuviere más baja que la tez, sino que está oscura, le encerrará el sacerdote por siete días;",
      "27": "Y al séptimo día el sacerdote la reconocerá: si se hubiere ido extendiendo por la piel, el sacerdote lo dará por inmundo: es llaga de lepra.",
      "28": "Empero si la mancha se estuviere en su lugar, y no se hubiere extendido en la piel, sino que está oscura, hinchazón es de la quemadura: darálo el sacerdote por limpio; que señal de la quemadura es.",
      "29": "Y al hombre ó mujer que le saliere llaga en la cabeza, ó en la barba,",
      "30": "El sacerdote mirará la llaga; y si pareciere estar más profunda que la tez, y el pelo en ella fuera rubio y adelgazado, entonces el sacerdote lo dará por inmundo: es tiña, es lepra de la cabeza ó de la barba.",
      "31": "Mas cuando el sacerdote hubiere mirado la llaga de la tiña, y no pareciere estar más profunda que la tez, ni fuere en ella pelo negro, el sacerdote encerrará al llagado de la tiña por siete días:",
      "32": "Y al séptimo día el sacerdote mirará la llaga: y si la tiña no pareciere haberse extendido, ni hubiere en ella pelo rubio, ni pareciere la tiña más profunda que la tez,",
      "33": "Entonces lo trasquilarán, mas no trasquilarán el lugar de la tiña: y encerrará el sacerdote al que tiene la tiña por otros siete días.",
      "34": "Y al séptimo día mirará el sacerdote la tiña; y si la tiña no hubiere cundido en la piel, ni pareciere estar más profunda que la tez, el sacerdote lo dará por limpio; y lavará sus vestidos, y será limpio.",
      "35": "Empero si la tiña se hubiere ido extendiendo en la piel después de su purificación,",
      "36": "Entonces el sacerdote la mirará; y si la tiña hubiere cundido en la piel, no busque el sacerdote el pelo rubio, es inmundo.",
      "37": "Mas si le pareciere que la tiña está detenida, y que ha salido en ella el pelo negro, la tiña está sanada; él está limpio, y por limpio lo dará el sacerdote.",
      "38": "Asimismo el hombre ó mujer, cuando en la piel de su carne tuviere manchas, manchas blancas,",
      "39": "El sacerdote mirará: y si en la piel de su carne parecieren manchas blancas algo oscurecidas, es empeine que brotó en la piel, está limpia la persona.",
      "40": "Y el hombre, cuando se le pelare la cabeza, es calvo, mas limpio.",
      "41": "Y si á la parte de su rostro se le pelare la cabeza, es calvo por delante, pero limpio.",
      "42": "Mas cuando en la calva ó en la antecalva hubiere llaga blanca rojiza, lepra es que brota en su calva ó en su antecalva.",
      "43": "Entonces el sacerdote lo mirará, y si pareciere la hinchazón de la llaga blanca rojiza en su calva ó en su antecalva, como el parecer de la lepra de la tez de la carne,",
      "44": "Leproso es, es inmundo; el sacerdote lo dará luego por inmundo; en su cabeza tiene su llaga.",
      "45": "Y el leproso en quien hubiere llaga, sus vestidos serán deshechos y su cabeza descubierta, y embozado pregonará: ­Inmundo! ­inmundo!",
      "46": "Todo el tiempo que la llaga estuviere en él, será inmundo; estará impuro: habitará solo; fuera del real será su morada.",
      "47": "Y cuando en el vestido hubiere plaga de lepra, en vestido de lana, ó en vestido de lino;",
      "48": "O en estambre ó en trama, de lino ó de lana, ó en piel, ó en cualquiera obra de piel;",
      "49": "Y que la plaga sea verde, ó bermeja, en vestido ó en piel, ó en estambre, ó en trama, ó en cualquiera obra de piel; plaga es de lepra, y se ha de mostrar al sacerdote.",
      "50": "Y el sacerdote mirará la plaga, y encerrará la cosa plagada por siete días.",
      "51": "Y al séptimo día mirará la plaga: y si hubiere cundido la plaga en el vestido, ó estambre, ó en la trama, ó en piel, ó en cualquiera obra que se hace de pieles, lepra roedora es la plaga; inmunda será.",
      "52": "Será quemado el vestido, ó estambre ó trama, de lana ó de lino, ó cualquiera obra de pieles en que hubiere tal plaga; porque lepra roedora es; al fuego será quemada.",
      "53": "Y si el sacerdote mirare, y no pareciere que la plaga se haya extendido en el vestido, ó estambre, ó en la trama, ó en cualquiera obra de pieles;",
      "54": "Entonces el sacerdote mandará que laven donde está la plaga, y lo encerrará otra vez por siete días.",
      "55": "Y el sacerdote mirará después que la plaga fuere lavada; y si pareciere que la plaga no ha mudado su aspecto, bien que no haya cundido la plaga, inmunda es; la quemarás al fuego; corrosión es penetrante, esté lo raído en la haz ó en el revés de aquella cosa.",
      "56": "Mas si el sacerdote la viere, y pareciere que la plaga se ha oscurecido después que fué lavada, la cortará del vestido, ó de la piel, ó del estambre, ó de la trama.",
      "57": "Y si apareciere más en el vestido, ó estambre, ó trama, ó en cualquiera cosa de pieles, reverdeciendo en ella, quemarás al fuego aquello donde estuviere la plaga.",
      "58": "Empero el vestido, ó estambre, ó trama, ó cualquiera cosa de piel que lavares, y que se le quitare la plaga, lavarse ha segunda vez, y entonces será limpia.",
      "59": "Esta es la ley de la plaga de la lepra del vestido de lana ó de lino, ó del estambre, ó de la trama, ó de cualquiera cosa de piel, para que sea dada por limpia ó por inmunda."
    },
    "14": {
      "1": "Y HABLO Jehová á Moisés, diciendo:",
      "2": "Esta será la ley del leproso cuando se limpiare: Será traído al sacerdote:",
      "3": "Y el sacerdote saldrá fuera del real; y mirará el sacerdote, y viendo que está sana la plaga de la lepra del leproso,",
      "4": "El sacerdote mandará luego que se tomen para el que se purifica dos avecillas vivas, limpias, y palo de cedro, y grana, é hisopo;",
      "5": "Y mandará el sacerdote matar la una avecilla en un vaso de barro sobre aguas vivas;",
      "6": "Después tomará la avecilla viva, y el palo de cedro, y la grana, y el hisopo, y lo mojará con la avecilla viva en la sangre de la avecilla muerta sobre las aguas vivas:",
      "7": "Y rociará siete veces sobre el que se purifica de la lepra, y le dará por limpio; y soltará la avecilla viva sobre la haz del campo.",
      "8": "Y el que se purifica lavará sus vestidos, y raerá todos sus pelos, y se ha de lavar con agua, y será limpio: y después entrará en el real, y morará fuera de su tienda siete días.",
      "9": "Y será, que al séptimo día raerá todos sus pelos, su cabeza, y su barba, y las cejas de sus ojos; finalmente, raerá todo su pelo, y lavará sus vestidos, y lavará su carne en aguas, y será limpio.",
      "10": "Y el día octavo tomará dos corderos sin defecto, y una cordera de un año sin tacha; y tres décimas de flor de harina para presente amasada con aceite, y un log de aceite.",
      "11": "Y el sacerdote que le purifica presentará con aquellas cosas al que se ha de limpiar delante de Jehová, á la puerta del tabernáculo del testimonio:",
      "12": "Y tomará el sacerdote el un cordero, y ofrecerálo por la culpa, con el log de aceite, y lo mecerá como ofrenda agitada delante de Jehová:",
      "13": "Y degollará el cordero en el lugar donde degüellan la víctima por el pecado y el holocausto, en el lugar del santuario: porque como la víctima por el pecado, así también la víctima por la culpa es del sacerdote: es cosa muy sagrada.",
      "14": "Y tomará el sacerdote de la sangre de la víctima por la culpa, y pondrá el sacerdote sobre la ternilla de la oreja derecha del que se purifica, y sobre el pulgar de su mano derecha, y sobre el pulgar de su pie derecho.",
      "15": "Asimismo tomará el sacerdote del log de aceite, y echará sobre la palma de su mano izquierda:",
      "16": "Y mojará su dedo derecho en el aceite que tiene en su mano izquierda, y esparcirá del aceite con su dedo siete veces delante de Jehová:",
      "17": "Y de lo que quedare del aceite que tiene en su mano, pondrá el sacerdote sobre la ternilla de la oreja derecha del que se purifica, y sobre el pulgar de su mano derecha, y sobre el pulgar de su pie derecho, sobre la sangre de la expiación por la culpa:",
      "18": "Y lo que quedare del aceite que tiene en su mano, pondrá sobre la cabeza del que se purifica: y hará el sacerdote expiación por él delante de Jehová.",
      "19": "Ofrecerá luego el sacerdote el sacrificio por el pecado, y hará expiación por el que se ha de purificar de su inmundicia, y después degollará el holocausto:",
      "20": "Y hará subir el sacerdote el holocausto y el presente sobre el altar. Así hará el sacerdote expiación por él, y será limpio.",
      "21": "Mas si fuere pobre, que no alcanzare su mano á tanto, entonces tomará un cordero para ser ofrecido como ofrenda agitada por la culpa, para reconciliarse, y una décima de flor de harina amasada con aceite para presente, y un log de aceite;",
      "22": "Y dos tórtolas, ó dos palominos, lo que alcanzare su mano: y el uno será para expiación por el pecado, y el otro para holocausto;",
      "23": "Las cuales cosas traerá al octavo día de su purificación al sacerdote, á la puerta del tabernáculo del testimonio delante de Jehová.",
      "24": "Y el sacerdote tomará el cordero de la expiación por la culpa, y el log de aceite, y mecerálo el sacerdote como ofrenda agitada delante de Jehová;",
      "25": "Luego degollará el cordero de la culpa, y tomará el sacerdote de la sangre de la culpa, y pondrá sobre la ternilla de la oreja derecha del que se purifica, y sobre el pulgar de su mano derecha, y sobre el pulgar de su pie derecho.",
      "26": "Y el sacerdote echará del aceite sobre la palma de su mano izquierda;",
      "27": "Y con su dedo derecho rociará el sacerdote del aceite que tiene en su mano izquierda, siete veces delante de Jehová.",
      "28": "También pondrá el sacerdote del aceite que tiene en su mano sobre la ternilla de la oreja derecha del que se purifica, y sobre el pulgar de su mano derecha, y sobre el pulgar de su pie derecho, en el lugar de la sangre de la culpa.",
      "29": "Y lo que sobrare del aceite que el sacerdote tiene en su mano, pondrálo sobre la cabeza del que se purifica, para reconciliarlo delante de Jehová.",
      "30": "Asimismo ofrecerá la una de las tórtolas, ó de los palominos, lo que alcanzare su mano:",
      "31": "El uno de lo que alcanzare su mano, en expiación por el pecado, y el otro en holocausto, además del presente: y hará el sacerdote expiación por el que se ha de purificar, delante de Jehová.",
      "32": "Esta es la ley del que hubiere tenido plaga de lepra, cuya mano no alcanzare lo prescrito para purificarse.",
      "33": "Y habló Jehová á Moisés y á Aarón, diciendo:",
      "34": "Cuando hubieres entrado en la tierra de Canaán, la cual yo os doy en posesión, y pusiere yo plaga de lepra en alguna casa de la tierra de vuestra posesión,",
      "35": "Vendrá aquél cuya fuere la casa, y dará aviso al sacerdote, diciendo: Como plaga ha aparecido en mi casa.",
      "36": "Entonces mandará el sacerdote, y despejarán la casa antes que el sacerdote entre á mirar la plaga, por que no sea contaminado todo lo que estuviere en la casa: y después el sacerdote entrará á reconocer la casa:",
      "37": "Y mirará la plaga: y si se vieren manchas en las paredes de la casa, cavernillas verdosas ó rojas, las cuales parecieren más hundidas que la pared,",
      "38": "El sacerdote saldrá de la casa á la puerta de ella, y cerrará la casa por siete días.",
      "39": "Y al séptimo día volverá el sacerdote, y mirará: y si la plaga hubiere crecido en las paredes de la casa,",
      "40": "Entonces mandará el sacerdote, y arrancarán las piedras en que estuviere la plaga, y las echarán fuera de la ciudad, en lugar inmundo:",
      "41": "Y hará descostrar la casa por dentro alrededor, y derramarán el polvo que descostraren fuera de la ciudad en lugar inmundo:",
      "42": "Y tomarán otras piedras, y las pondrán en lugar de las piedras quitadas; y tomarán otro barro, y encostrarán la casa.",
      "43": "Y si la plaga volviere á reverdecer en aquella casa, después que hizo arrancar las piedras, y descostrar la casa, y después que fue encostrada,",
      "44": "Entonces el sacerdote entrará y mirará; y si pareciere haberse extendido la plaga en la casa, lepra roedora está en la casa: inmunda es.",
      "45": "Derribará, por tanto, la tal casa, sus piedras, y sus maderos, y toda la mezcla de la casa; y lo sacará fuera de la ciudad á lugar inmundo.",
      "46": "Y cualquiera que entrare en aquella casa todos los días que la mandó cerrar, será inmundo hasta la tarde.",
      "47": "Y el que durmiere en aquella casa, lavará sus vestidos; también el que comiere en la casa, lavará sus vestidos.",
      "48": "Mas si entrare el sacerdote y mirare, y viere que la plaga no se ha extendido en la casa después que fue encostrada, el sacerdote dará la casa por limpia, porque la plaga ha sanado.",
      "49": "Entonces tomará para limpiar la casa dos avecillas, y palo de cedro, y grana, é hisopo:",
      "50": "Y degollará la una avecilla en una vasija de barro sobre aguas vivas:",
      "51": "Y tomará el palo de cedro, y el hisopo, y la grana, y la avecilla viva, y mojarálo en la sangre de la avecilla muerta y en las aguas vivas, y rociará la casa siete veces:",
      "52": "Y purificará la casa con la sangre de la avecilla, y con las aguas vivas, y con la avecilla viva, y el palo de cedro, y el hisopo, y la grana:",
      "53": "Luego soltará la avecilla viva fuera de la ciudad sobre la haz del campo: Así hará expiación por la casa, y será limpia.",
      "54": "Esta es la ley acerca de toda plaga de lepra, y de tiña;",
      "55": "Y de la lepra del vestido, y de la casa;",
      "56": "Y acerca de la hinchazón, y de la postilla, y de la mancha blanca:",
      "57": "Para enseñar cuándo es inmundo, y cuándo limpio. Aquesta es la ley tocante á la lepra."
    },
    "15": {
      "1": "Y HABLO Jehová á Moisés y á Aarón, diciendo:",
      "2": "Hablad á los hijos de Israel, y decidles: Cualquier varón, cuando su simiente manare de su carne, será inmundo.",
      "3": "Y esta será su inmundicia en su flujo; sea que su carne destiló por causa de su flujo, ó que su carne se obstruyó á causa de su flujo, él será inmundo.",
      "4": "Toda cama en que se acostare el que tuviere flujo, será inmunda; y toda cosa sobre que se sentare, inmunda será.",
      "5": "Y cualquiera que tocare á su cama, lavará sus vestidos; lavaráse también á sí mismo con agua, y será inmundo hasta la tarde.",
      "6": "Y el que se sentare sobre aquello en que se hubiere sentado el que tiene flujo, lavará sus vestidos, se lavará también á sí mismo con agua, y será inmundo hasta la tarde.",
      "7": "Asimismo el que tocare la carne del que tiene flujo, lavará sus vestidos, y á sí mismo se lavará con agua, y será inmundo hasta la tarde.",
      "8": "Y si el que tiene flujo escupiere sobre el limpio, éste lavará sus vestidos, y después de haberse lavado con agua, será inmundo hasta la tarde.",
      "9": "Y toda aparejo sobre que cabalgare el que tuviere flujo, será inmundo.",
      "10": "Y cualquiera que tocare cualquiera cosa que haya estado debajo de él, será inmundo hasta la tarde; y el que la llevare, lavará sus vestidos, y después de lavarse con agua, será inmundo hasta la tarde.",
      "11": "Y todo aquel á quien tocare el que tiene flujo, y no lavare con agua sus manos, lavará sus vestidos, y á sí mismo se lavará con agua, y será inmundo hasta la tarde.",
      "12": "Y la vasija de barro en que tocare el que tiene flujo, será quebrada; y toda vasija de madera será lavada con agua.",
      "13": "Y cuando se hubiere limpiado de su flujo el que tiene flujo, se ha de contar siete días desde su purificación, y lavará sus vestidos, y lavará su carne en aguas vivas, y será limpio.",
      "14": "Y el octavo día tomará dos tórtolas, ó dos palominos, y vendrá delante de Jehová á la puerta del tabernáculo del testimonio, y los dará al sacerdote:",
      "15": "Y harálos el sacerdote, el uno ofrenda por el pecado, y el otro holocausto: y le purificará el sacerdote de su flujo delante de Jehová.",
      "16": "Y el hombre, cuando de él saliere derramamiento de semen, lavará en aguas toda su carne, y será inmundo hasta la tarde.",
      "17": "Y toda vestimenta, ó toda piel sobre la cual hubiere el derramamiento del semen, lavaráse con agua, y será inmunda hasta la tarde.",
      "18": "Y la mujer con quien el varón tuviera ayuntamiento de semen, ambos se lavarán con agua, y serán inmundos hasta la tarde.",
      "19": "Y cuando la mujer tuviere flujo de sangre, y su flujo fuere en su carne, siete días estará apartada; y cualquiera que tocare en ella, será inmundo hasta la tarde.",
      "20": "Y todo aquello sobre que ella se acostare mientras su separación, será inmundo: también todo aquello sobre que se sentare, será inmundo.",
      "21": "Y cualquiera que tocare á su cama, lavará sus vestidos, y después de lavarse con agua, será inmundo hasta la tarde.",
      "22": "También cualquiera que tocare cualquier mueble sobre que ella se hubiere sentado, lavará sus vestidos; lavaráse luego á sí mismo con agua, y será inmundo hasta la tarde.",
      "23": "Y si estuviere sobre la cama, ó sobre la silla en que ella se hubiere sentado, el que tocare en ella será inmundo hasta la tarde.",
      "24": "Y si alguno durmiere con ella, y su menstruo fuere sobre él, será inmundo por siete días; y toda cama sobre que durmiere, será inmunda.",
      "25": "Y la mujer, cuando siguiere el flujo de su sangre por muchos días fuera del tiempo de su costumbre, ó cuando tuviere flujo de sangre más de su costumbre; todo el tiempo del flujo de su inmundicia, será inmunda como en los días de su costumbre.",
      "26": "Toda cama en que durmiere todo el tiempo de su flujo, le será como la cama de su costumbre; y todo mueble sobre que se sentare, será inmundo, como la inmundicia de su costumbre.",
      "27": "Cualquiera que tocare en esas cosas será inmundo; y lavará sus vestidos, y á sí mismo se lavará con agua, y será inmundo hasta la tarde.",
      "28": "Y cuando fuere libre de su flujo, se ha de contar siete días, y después será limpia.",
      "29": "Y el octavo día tomará consigo dos tórtolas, ó dos palominos, y los traerá al sacerdote, á la puerta del tabernáculo del testimonio:",
      "30": "Y el sacerdote hará el uno ofrenda por el pecado, y el otro holocausto; y la purificará el sacerdote delante de Jehová del flujo de su inmundicia.",
      "31": "Así apartaréis los hijos de Israel de sus inmundicias, á fin de que no mueran por sus inmundicias, ensuciando mi tabernáculo que está entre ellos.",
      "32": "Esta es la ley del que tiene flujo, y del que sale derramamiento de semen, viniendo á ser inmundo á causa de ello;",
      "33": "Y de la que padece su costumbre, y acerca del que tuviere flujo, sea varón ó hembra, y del hombre que durmiere con mujer inmunda."
    },
    "16": {
      "1": "Y HABLO Jehová á Moisés, después que murieron los dos hijos de Aarón, cuando se llegaron delante de Jehová, y murieron;",
      "2": "Y Jehová dijo á Moisés: Di á Aarón tu hermano, que no en todo tiempo entre en el santuario del velo adentro, delante de la cubierta que está sobre el arca, para que no muera: porque yo apareceré en la nube sobre la cubierta.",
      "3": "Con esto entrará Aarón en el santuario: con un becerro por expiación, y un carnero en holocausto.",
      "4": "La túnica santa de lino se vestirá, y sobre su carne tendrá pañetes de lino, y ceñiráse el cinto de lino; y con la mitra de lino se cubrirá: son las santas vestiduras: con ellas, después de lavar su carne con agua, se ha de vestir.",
      "5": "Y de la congregación de los hijos de Israel tomará dos machos de cabrío para expiación, y un carnero para holocausto.",
      "6": "Y hará allegar Aarón el becerro de la expiación, que es suyo, y hará la reconciliación por sí y por su casa.",
      "7": "Después tomará los dos machos de cabrío, y los presentará delante de Jehová á la puerta del tabernáculo del testimonio.",
      "8": "Y echará suertes Aarón sobre los dos machos de cabrío; la una suerte por Jehová, y la otra suerte por Azazel.",
      "9": "Y hará allegar Aarón el macho cabrío sobre el cual cayere la suerte por Jehová, y ofrecerálo en expiación.",
      "10": "Mas el macho cabrío, sobre el cual cayere la suerte por Azazel, lo presentará vivo delante de Jehová, para hacer la reconciliación sobre él, para enviarlo á Azazel al desierto.",
      "11": "Y hará llegar Aarón el becerro que era suyo para expiación, y hará la reconciliación por sí y por su casa, y degollará en expiación el becerro que es suyo.",
      "12": "Después tomará el incensario lleno de brasas de fuego, del altar de delante de Jehová, y sus puños llenos del perfume aromático molido, y meterálo del velo adentro:",
      "13": "Y pondrá el perfume sobre el fuego delante de Jehová, y la nube del perfume cubrirá la cubierta que está sobre el testimonio, y no morirá.",
      "14": "Tomará luego de la sangre del becerro, y rociará con su dedo hacia la cubierta al lado oriental: hacia la cubierta esparcirá siete veces de aquella sangre con su dedo.",
      "15": "Después degollará en expiación el macho cabrío, que era del pueblo, y meterá la sangre de él del velo adentro; y hará de su sangre como hizo de la sangre del becerro, y esparcirá sobre la cubierta y delante de la cubierta:",
      "16": "Y limpiará el santuario, de las inmundicias de los hijos de Israel, y de sus rebeliones, y de todos sus pecados: de la misma manera hará también al tabernáculo del testimonio, el cual reside entre ellos en medio de sus inmundicias.",
      "17": "Y ningún hombre estará en el tabernáculo del testimonio cuando él entrare á hacer la reconciliación en el santuario, hasta que él salga, y haya hecho la reconciliación por sí, y por su casa, y por toda la congregación de Israel.",
      "18": "Y saldrá al altar que está delante de Jehová, y lo expiará; y tomará de la sangre del becerro, y de la sangre del macho cabrío, y pondrá sobre los cuernos del altar alrededor.",
      "19": "Y esparcirá sobre él de la sangre con su dedo siete veces, y lo limpiará, y lo santificará de las inmundicias de los hijos de Israel.",
      "20": "Y cuando hubiere acabado de expiar el santuario, y el tabernáculo del testimonio, y el altar, hará llegar el macho cabrío vivo:",
      "21": "Y pondrá Aarón ambas manos suyas sobre la cabeza del macho cabrío vivo, y confesará sobre él todas las iniquidades de los hijos de Israel, y todas sus rebeliones, y todos sus pecados, poniéndolos así sobre la cabeza del macho cabrío, y lo enviará al desierto por mano de un hombre destinado para esto.",
      "22": "Y aquel macho cabrío llevará sobre sí todas las iniquidades de ellos á tierra inhabitada: y dejará ir el macho cabrío por el desierto.",
      "23": "Después vendrá Aarón al tabernáculo del testimonio, y se desnudará las vestimentas de lino, que había vestido para entrar en el santuario, y pondrálas allí.",
      "24": "Lavará luego su carne con agua en el lugar del santuario, y después de ponerse sus vestidos saldrá, y hará su holocausto, y el holocausto del pueblo, y hará la reconciliación por sí y por el pueblo.",
      "25": "Y quemará el sebo de la expiación sobre el altar.",
      "26": "Y el que hubiere llevado el macho cabrío á Azazel, lavará sus vestidos, lavará también con agua su carne, y después entrará en el real.",
      "27": "Y sacará fuera del real el becerro del pecado, y el macho cabrío de la culpa, la sangre de los cuales fué metida para hacer la expiación en el santuario; y quemarán en el fuego sus pellejos, y sus carnes, y su estiércol.",
      "28": "Y el que los quemare, lavará sus vestidos, lavará también su carne con agua, y después entrará en el real.",
      "29": "Y esto tendréis por estatuto perpetuo: En el mes séptimo, á los diez del mes, afligiréis vuestras almas, y ninguna obra haréis, ni el natural ni el extranjero que peregrina entre vosotros:",
      "30": "Porque en este día se os reconciliará para limpiaros; y seréis limpios de todos vuestros pecados delante de Jehová.",
      "31": "Sábado de reposo es para vosotros, y afligiréis vuestras almas, por estatuto perpetuo.",
      "32": "Y hará la reconciliación el sacerdote que fuere ungido, y cuya mano hubiere sido llena para ser sacerdote en lugar de su padre; y se vestirá las vestimentas de lino, las vestiduras sagradas:",
      "33": "Y expiará el santuario santo, y el tabernáculo del testimonio; expiará también el altar, y á los sacerdotes, y á todo el pueblo de la congregación.",
      "34": "Y esto tendréis por estatuto perpetuo, para expiar á los hijos de Israel de todos sus pecados una vez en el año. Y Moisés lo hizo como Jehová le mandó."
    },
    "17": {
      "1": "Y HABLO Jehová á Moisés, diciendo:",
      "2": "Habla á Aarón y á sus hijos, y á todos los hijos de Israel, y diles: Esto es lo que ha mandado Jehová, diciendo:",
      "3": "Cualquier varón de la casa de Israel que degollare buey, ó cordero, ó cabra, en el real, ó fuera del real,",
      "4": "Y no lo trajere á la puerta del tabernáculo del testimonio, para ofrecer ofrenda á Jehová delante del tabernáculo de Jehová, sangre será imputada al tal varón: sangre derramó; cortado será el tal varón de entre su pueblo:",
      "5": "A fin de que traigan los hijos de Israel sus sacrificios, los que sacrifican sobre la haz del campo, para que los traigan á Jehová á la puerta del tabernáculo del testimonio al sacerdote, y sacrifiquen ellos sacrificios de paces á Jehová.",
      "6": "Y el sacerdote esparcirá la sangre sobre el altar de Jehová, á la puerta del tabernáculo del testimonio, y quemará el sebo en olor de suavidad á Jehová.",
      "7": "Y nunca más sacrificarán sus sacrificios á los demonios, tras de los cuales han fornicado: tendrán esto por estatuto perpetuo por sus edades.",
      "8": "Les dirás también: Cualquier varón de la casa de Israel, ó de los extranjeros que peregrinan entre vosotros, que ofreciere holocausto ó sacrificio,",
      "9": "Y no lo trajere á la puerta del tabernáculo del testimonio, para hacerlo á Jehová, el tal varón será igualmente cortado de sus pueblos.",
      "10": "Y cualquier varón de la casa de Israel, ó de los extranjeros que peregrinan entre ellos, que comiere alguna sangre, yo pondré mi rostro contra la persona que comiere sangre, y le cortaré de entre su pueblo.",
      "11": "Porque la vida de la carne en la sangre está: y yo os la he dado para expiar vuestras personas sobre el altar: por lo cual la misma sangre expiará la persona.",
      "12": "Por tanto, he dicho á los hijos de Israel: Ninguna persona de vosotros comerá sangre, ni el extranjero que peregrina entre vosotros comerá sangre.",
      "13": "Y cualquier varón de los hijos de Israel, ó de los extranjeros que peregrinan entre ellos, que cogiere caza de animal ó de ave que sea de comer, derramará su sangre y cubrirála con tierra:",
      "14": "Porque el alma de toda carne, su vida, está en su sangre: por tanto he dicho á los hijos de Israel: No comeréis la sangre de ninguna carne, porque la vida de toda carne es su sangre; cualquiera que la comiere será cortado.",
      "15": "Y cualquiera persona que comiere cosa mortecina ó despedazada por fiera, así de los naturales como de los extranjeros, lavará sus vestidos y á sí mismo se lavará con agua, y será inmundo hasta la tarde; y se limpiará.",
      "16": "Y si no los lavare, ni lavare su carne, llevará su iniquidad."
    },
    "18": {
      "1": "Y HABLO Jehová á Moisés, diciendo:",
      "2": "Habla á los hijos de Israel, y diles: Yo soy Jehová vuestro Dios.",
      "3": "No haréis como hacen en la tierra de Egipto, en la cual morasteis; ni haréis como hacen en la tierra de Canaán, á la cual yo os conduzco; ni andaréis en sus estatutos.",
      "4": "Mis derechos pondréis por obra, y mis estatutos guardaréis, andando en ellos: Yo Jehová vuestro Dios.",
      "5": "Por tanto mis estatutos y mis derechos guardaréis, los cuales haciendo el hombre, vivirá en ellos: Yo Jehová.",
      "6": "Ningún varón se allegue á ninguna cercana de su carne, para descubrir su desnudez: Yo Jehová.",
      "7": "La desnudez de tu padre, ó la desnudez de tu madre, no descubrirás: tu madre es, no descubrirás su desnudez.",
      "8": "La desnudez de la mujer de tu padre no descubrirás; es la desnudez de tu padre.",
      "9": "La desnudez de tu hermana, hija de tu padre, ó hija de tu madre, nacida en casa ó nacida fuera, su desnudez no descubrirás.",
      "10": "La desnudez de la hija de tu hijo, ó de la hija de tu hija, su desnudez no descubirás, porque es la desnudez tuya.",
      "11": "La desnudez de la hija de la mujer de tu padre, engendrada de tu padre, tu hermana es, su desnudez no descubrirás.",
      "12": "La desnudez de la hermana de tu padre no descubrirás: es parienta de tu padre.",
      "13": "La desnudez de la hermana de tu madre no descubrirás: porque parienta de tu madre es.",
      "14": "La desnudez del hermano de tu padre no descubrirás: no llegarás á su mujer: es mujer del hermano de tu padre.",
      "15": "La desnudez de tu nuera no descubrirás: mujer es de tu hijo, no descubrirás su desnudez.",
      "16": "La desnudez de la mujer de tu hermano no descubrirás: es la desnudez de tu hermano.",
      "17": "La desnudez de la mujer y de su hija no descubrirás: no tomarás la hija de su hijo, ni la hija de su hija, para descubrir su desnudez: son parientas, es maldad.",
      "18": "No tomarás mujer juntamente con su hermana, para hacerla su rival, descubriendo su desnudez delante de ella en su vida.",
      "19": "Y no llegarás á la mujer en el apartamiento de su inmundicia, para descubrir su desnudez.",
      "20": "Además, no tendrás acto carnal con la mujer de tu prójimo, contaminándote en ella.",
      "21": "Y no des de tu simiente para hacerla pasar por el fuego á Moloch; no contamines el nombre de tu Dios: Yo Jehová.",
      "22": "No te echarás con varón como con mujer: es abominación.",
      "23": "Ni con ningún animal tendrás ayuntamiento amancillándote con él; ni mujer alguna se pondrá delante de animal para ayuntarse con él: es confusión.",
      "24": "En ninguna de estas cosas os amancillaréis; porque en todas estas cosas se han ensuciado las gentes que yo echo de delante de vosotros:",
      "25": "Y la tierra fue contaminada; y yo visité su maldad sobre ella, y la tierra vomitó sus moradores.",
      "26": "Guardad, pues, vosotros mis estatutos y mis derechos, y no hagáis ninguna de todas estas abominaciones: ni el natural ni el extranjero que peregrina entre vosotros.",
      "27": "(Porque todas estas abominaciones hicieron los hombres de la tierra, que fueron antes de vosotros, y la tierra fue contaminada:)",
      "28": "Y la tierra no os vomitará, por haberla contaminado, como vomitó á la gente que fué antes de vosotros.",
      "29": "Porque cualquiera que hiciere alguna de todas estas abominaciones, las personas que las hicieren, serán cortadas de entre su pueblo.",
      "30": "Guardad, pues, mi ordenanza, no haciendo de las prácticas abominables que tuvieron lugar antes de vosotros, y no os ensuciéis en ellas: Yo Jehová vuestro Dios."
    },
    "19": {
      "1": "Y HABLO Jehová á Moisés, diciendo:",
      "2": "Habla á toda la congregación de los hijos de Israel, y diles: Santos seréis, porque santo soy yo Jehová vuestro Dios.",
      "3": "Cada uno temerá á su madre y á su padre, y mis sábados guardaréis: Yo Jehová vuestro Dios.",
      "4": "No os volveréis á los ídolos, ni haréis para vosotros dioses de fundición: Yo Jehová vuestro Dios.",
      "5": "Y cuando sacrificareis sacrificio de paces á Jehová, de vuestra voluntad lo sacrificaréis.",
      "6": "Será comido el día que lo sacrificareis, y el siguiente día: y lo que quedare para el tercer día, será quemado en el fuego.",
      "7": "Y si se comiere el día tercero, será abominación; no será acepto:",
      "8": "Y el que lo comiere, llevará su delito, por cuanto profanó lo santo de Jehová; y la tal persona será cortada de sus pueblos.",
      "9": "Cuando segareis la mies de vuestra tierra, no acabarás de segar el rincón de tu haza, ni espigarás tu tierra segada.",
      "10": "Y no rebuscarás tu viña, ni recogerás los granos caídos de tu viña; para el pobre y para el extranjero los dejarás: Yo Jehová vuestro Dios.",
      "11": "No hurtaréis, y no engañaréis, ni mentiréis ninguno á su prójimo.",
      "12": "Y no juraréis en mi nombre con mentira, ni profanarás el nombre de tu Dios: Yo Jehová.",
      "13": "No oprimirás á tu prójimo, ni le robarás. No se detendrá el trabajo del jornalero en tu casa hasta la mañana.",
      "14": "No maldigas al sordo, y delante del ciego no pongas tropiezo, mas tendrás temor de tu Dios: Yo Jehová.",
      "15": "No harás agravio en el juicio: no tendrás respeto al pobre, ni honrarás la cara del grande: con justicia juzgarás á tu prójimo.",
      "16": "No andarás chismeando en tus pueblos. No te pondrás contra la sangre de tu prójimo: Yo Jehová.",
      "17": "No aborrecerás á tu hermano en tu corazón: ingenuamente reprenderás á tu prójimo, y no consentirás sobre él pecado.",
      "18": "No te vengarás, ni guardarás rencor á los hijos de tu pueblo: mas amarás á tu prójimo como á ti mismo: Yo Jehová.",
      "19": "Mis estatutos guardaréis. A tu animal no harás ayuntar para misturas; tu haza no sembrarás con mistura de semillas, y no te pondrás vestidos con mezcla de diversas cosas.",
      "20": "Y cuando un hombre tuviere cópula con mujer, y ella fuere sierva desposada con alguno, y no estuviere rescatada, ni le hubiere sido dada libertad, ambos serán azotados: no morirán, por cuanto ella no es libre.",
      "21": "Y él traerá á Jehová, á la puerta del tabernáculo del testimonio, un carnero en expiación por su culpa.",
      "22": "Y con el carnero de la expiación lo reconciliará el sacerdote delante de Jehová, por su pecado que cometió: y se le perdonará su pecado que ha cometido.",
      "23": "Y cuando hubiereis entrado en la tierra, y plantareis todo árbol de comer, quitaréis su prepucio, lo primero de su fruto: tres años os será incircunciso: su fruto no se comerá.",
      "24": "Y el cuarto año todo su fruto será santidad de loores á Jehová.",
      "25": "Mas al quinto año comeréis el fruto de él, para que os haga crecer su fruto: Yo Jehová vuestro Dios.",
      "26": "No comeréis cosa alguna con sangre. No seréis agoreros, ni adivinaréis.",
      "27": "No cortaréis en redondo las extremidades de vuestras cabezas, ni dañarás la punta de tu barba.",
      "28": "Y no haréis rasguños en vuestra carne por un muerto, ni imprimiréis en vosotros señal alguna: Yo Jehová.",
      "29": "No contaminarás tu hija haciéndola fornicar: porque no se prostituya la tierra, y se hincha de maldad.",
      "30": "Mis sábados guardaréis, y mi santuario tendréis en reverencia: Yo Jehová.",
      "31": "No os volváis á los encantadores y á los adivinos: no los consultéis ensuciándoos con ellos: Yo Jehová vuestro Dios.",
      "32": "Delante de las canas te levantarás, y honrarás el rostro del anciano, y de tu Dios tendrás temor: Yo Jehová.",
      "33": "Y cuando el extranjero morare contigo en vuestra tierra, no le oprimiréis.",
      "34": "Como á un natural de vosotros tendréis al extranjero que peregrinare entre vosotros; y ámalo como á ti mismo; porque peregrinos fuisteis en la tierra de Egipto: Yo Jehová vuestro Dios.",
      "35": "No hagáis agravio en juicio, en medida de tierra, ni en peso, ni en otra medida.",
      "36": "Balanzas justas, pesas justas, epha justo, é hin justo tendréis: Yo Jehová vuestro Dios, que os saqué de la tierra de Egipto.",
      "37": "Guardad pues todos mis estatutos, y todos mis derechos, y ponedlos por obra: Yo Jehová."
    },
    "20": {
      "1": "Y HABLO Jehová á Moisés diciendo:",
      "2": "Dirás asimismo á los hijos de Israel: Cualquier varón de los hijos de Israel, ó de los extranjeros que peregrinan en Israel, que diere de su simiente á Moloch, de seguro morirá: el pueblo de la tierra lo apedreará con piedras.",
      "3": "Y yo pondré mi rostro contra el tal varón, y lo cortaré de entre su pueblo; por cuanto dió de su simiente á Moloch, contaminando mi santuario, y amancillando mi santo nombre.",
      "4": "Que si escondiere el pueblo de la tierra sus ojos de aquel varón que hubiere dado de su simiente á Moloch, para no matarle,",
      "5": "Entonces yo pondré mi rostro contra aquel varón, y contra su familia, y le cortaré de entre su pueblo, con todos los que fornicaron en pos de él, prostituyéndose con Moloch.",
      "6": "Y la persona que atendiere á encantadores ó adivinos, para prostituirse tras de ellos, yo pondré mi rostro contra la tal persona, y cortaréla de entre su pueblo.",
      "7": "Santificaos, pues, y sed santos, porque yo Jehová soy vuestro Dios.",
      "8": "Y guardad mis estatutos, y ponedlos por obra: Yo Jehová que os santifico.",
      "9": "Porque varón que maldijere á su padre ó á su madre, de cierto morirá: á su padre ó á su madre maldijo; su sangre será sobre él.",
      "10": "Y el hombre que adulterare con la mujer de otro, el que cometiere adulterio con la mujer de su prójimo, indefectiblemente se hará morir al adúltero y á la adúltera.",
      "11": "Y cualquiera que se echare con la mujer de su padre, la desnudez de su padre descubrió; ambos han de ser muertos; su sangre será sobre ellos.",
      "12": "Y cualquiera que durmiere con su nuera, ambos han de morir: hicieron confusión; su sangre será sobre ellos.",
      "13": "Y cualquiera que tuviere ayuntamiento con varón como con mujer, abominación hicieron: entrambos han de ser muertos; sobre ellos será su sangre.",
      "14": "Y el que tomare mujer y á la madre de ella, comete vileza: quemarán en fuego á él y á ellas, porque no haya vileza entre vosotros.",
      "15": "Y cualquiera que tuviere cópula con bestia, ha de ser muerto; y mataréis á la bestia.",
      "16": "Y la mujer que se allegare á algún animal, para tener ayuntamiento con él, á la mujer y al animal matarás: morirán infaliblemente; será su sangre sobre ellos.",
      "17": "Y cualquiera que tomare á su hermana, hija de su padre ó hija de su madre, y viere su desnudez, y ella viere la suya, cosa es execrable; por tanto serán muertos á ojos de los hijos de su pueblo: descubrió la desnudez de su hermana; su pecado llevará.",
      "18": "Y cualquiera que durmiere con mujer menstruosa, y descubriere su desnudez, su fuente descubrió, y ella descubrió la fuente de su sangre: ambos serán cortados de entre su pueblo.",
      "19": "La desnudez de la hermana de tu madre, ó de la hermana de tu padre, no descubrirás: por cuanto descubrió su parienta, su iniquidad llevarán.",
      "20": "Y cualquiera que durmiere con la mujer del hermano de su padre, la desnudez del hermano de su padre descubrió; su pecado llevarán; morirán sin hijos.",
      "21": "Y el que tomare la mujer de su hermano, es suciedad; la desnudez de su hermano descubrió; sin hijos serán.",
      "22": "Guardad, pues, todos mis estatutos y todos mis derechos, y ponedlos por obra: y no os vomitará la tierra, en la cual yo os introduzco para que habitéis en ella.",
      "23": "Y no andéis en las prácticas de la gente que yo echaré de delante de vosotros: porque ellos hicieron todas estas cosas, y los tuve en abominación.",
      "24": "Empero á vosotros os he dicho: Vosotros poseeréis la tierra de ellos, y yo os la daré para que la poseáis por heredad, tierra que fluye leche y miel: Yo Jehová vuestro Dios, que os he apartado de los pueblos.",
      "25": "Por tanto, vosotros haréis diferencia entre animal limpio é inmundo, y entre ave inmunda y limpia: y no ensuciéis vuestras personas en los animales, ni en las aves, ni en ninguna cosa que va arrastrando por la tierra, las cuales os he apartado por inmundas.",
      "26": "Habéis, pues, de serme santos, porque yo Jehová soy santo, y os he apartado de los pueblos, para que seáis míos.",
      "27": "Y el hombre ó la mujer en quienes hubiere espíritu phitónico ó de adivinación, han de ser muertos: los apedrearán con piedras; su sangre sobre ellos."
    },
    "21": {
      "1": "Y JEHOVA dijo á Moisés: Habla á los sacerdotes hijos de Aarón, y diles que no se contaminen por un muerto en sus pueblos.",
      "2": "Mas por su pariente cercano á sí, por su madre, ó por su padre, ó por su hijo, ó por su hermano,",
      "3": "O por su hermana virgen, á él cercana, la cual no haya tenido marido, por ella se contaminará.",
      "4": "No se contaminará, porque es príncipe en sus pueblos, haciéndose inmundo.",
      "5": "No harán calva en su cabeza, ni raerán la punta de su barba, ni en su carne harán rasguños.",
      "6": "Santos serán á su Dios, y no profanarán el nombre de su Dios; porque los fuegos de Jehová y el pan de su Dios ofrecen: por tanto serán santos.",
      "7": "Mujer ramera ó infame no tomarán: ni tomarán mujer repudiada de su marido: porque es santo á su Dios.",
      "8": "Lo santificarás por tanto, pues el pan de tu Dios ofrece: santo será para ti, porque santo soy yo Jehová vuestro santificador.",
      "9": "Y la hija del varón sacerdote, si comenzare á fornicar, á su padre amancilla: quemada será al fuego.",
      "10": "Y el sumo sacerdote entre sus hermanos, sobre cuya cabeza fué derramado el aceite de la unción, y que hinchió su mano para vestir las vestimentas, no descubrirá su cabeza, ni romperá sus vestidos:",
      "11": "Ni entrará donde haya alguna persona muerta, ni por su padre, ó por su madre se contaminará.",
      "12": "Ni saldrá del santuario, ni contaminará el santuario de su Dios; porque la corona del aceite de la unción de su Dios está sobre él: Yo Jehová.",
      "13": "Y tomará él mujer con su virginidad.",
      "14": "Viuda, ó repudiada, ó infame, ó ramera, éstas no tomará: mas tomará virgen de sus pueblos por mujer.",
      "15": "Y no amancillará su simiente en sus pueblos; porque yo Jehová soy el que los santifico.",
      "16": "Y Jehová habló á Moisés, diciendo:",
      "17": "Habla á Aarón, y dile: El varón de tu simiente en sus generaciones, en el cual hubiere falta, no se allegará para ofrecer el pan de su Dios.",
      "18": "Porque ningún varón en el cual hubiere falta, se allegará: varón ciego, ó cojo, ó falto, ó sobrado,",
      "19": "O varón en el cual hubiere quebradura de pie ó rotura de mano,",
      "20": "O corcobado, ó lagañoso, ó que tuviere nube en el ojo, ó que tenga sarna, ó empeine, ó compañón relajado;",
      "21": "Ningún varón de la simiente de Aarón sacerdote, en el cual hubiere falta, se allegará para ofrecer las ofrendas encendidas de Jehová. Hay falta en él; no se allegará á ofrecer el pan de su Dios.",
      "22": "El pan de su Dios, de lo muy santo y las cosas santificadas, comerá.",
      "23": "Empero no entrará del velo adentro, ni se allegará al altar, por cuanto hay falta en él: y no profanará mi santuario, porque yo Jehová soy el que los santifico.",
      "24": "Y Moisés habló esto á Aarón, y á sus hijos, y á todos los hijos de Israel."
    },
    "22": {
      "1": "Y HABLO Jehová á Moisés, diciendo:",
      "2": "Di á Aarón y á sus hijos, que se abstengan de las santificaciones de los hijos de Israel, y que no profanen mi santo nombre en lo que ellos me santifican: Yo Jehová.",
      "3": "Diles: Todo varón de toda vuestra simiente en vuestras generaciones que llegare á las cosas sagradas, que los hijos de Israel consagran á Jehová, teniendo inmundicia sobre sí, de delante de mí será cortada su alma: Yo Jehová.",
      "4": "Cualquier varón de la simiente de Aarón que fuere leproso, ó padeciere flujo, no comerá de las cosas sagradas hasta que esté limpio: y el que tocare cualquiera cosa inmunda de mortecino, ó el varón del cual hubiere salido derramamiento de semen;",
      "5": "O el varón que hubiere tocado cualquier reptil, por el cual será inmundo, ú hombre por el cual venga á ser inmundo, conforme á cualquiera inmundicia suya;",
      "6": "La persona que lo tocare, será inmunda hasta la tarde, y no comerá de las cosas sagradas antes que haya lavado su carne con agua.",
      "7": "Y cuando el sol se pusiere, será limpio; y después comerá las cosas sagradas, porque su pan es.",
      "8": "Mortecino ni despedazado por fiera no comerá, para contaminarse en ello: Yo Jehová.",
      "9": "Guarden, pues, mi ordenanza, y no lleven pecado por ello, no sea que así mueran cuando la profanaren: Yo Jehová que los santifico.",
      "10": "Ningún extraño comerá cosa sagrada; el huésped del sacerdote, ni el jornalero, no comerá cosa sagrada.",
      "11": "Mas el sacerdote, cuando comprare persona de su dinero, ésta comerá de ella, y el nacido en su casa: estos comerán de su pan.",
      "12": "Empero la hija del sacerdote, cuando se casare con varón extraño, ella no comerá de la ofrenda de las cosas sagradas.",
      "13": "Pero si la hija del sacerdote fuere viuda, ó repudiada, y no tuviere prole, y se hubiere vuelto á la casa de su padre, como en su mocedad, comerá del pan de su padre; mas ningún extraño coma de él.",
      "14": "Y el que por yerro comiere cosa sagrada, añadirá á ella su quinto, y darálo al sacerdote con la cosa sagrada.",
      "15": "No profanarán, pues, las cosas santas de los hijos de Israel, las cuales apartan para Jehová:",
      "16": "Y no les harán llevar la iniquidad del pecado, comiendo las cosas santas de ellos: porque yo Jehová soy el que los santifico.",
      "17": "Y habló Jehová á Moisés, diciendo:",
      "18": "Habla á Aarón y á sus hijos, y á todos los hijos de Israel, y diles: Cualquier varón de la casa de Israel, ó de los extranjeros en Israel, que ofreciere su ofrenda por todos sus votos, y por todas sus voluntarias oblaciones que ofrecieren á Jehová en holocausto;",
      "19": "De vuestra voluntad ofreceréis macho sin defecto de entre las vacas, de entre los corderos, ó de entre las cabras.",
      "20": "Ninguna cosa en que haya falta ofreceréis, porque no será acepto por vosotros.",
      "21": "Asimismo, cuando alguno ofreciere sacrificio de paces á Jehová para presentar voto, ú ofreciendo voluntariamente, sea de vacas ó de ovejas, sin tacha será acepto; no ha de haber en él falta.",
      "22": "Ciego, ó perniquebrado, ó mutilado, ó verrugoso, ó sarnoso ó roñoso, no ofreceréis éstos á Jehová, ni de ellos pondréis ofrenda encendida sobre el altar de Jehová.",
      "23": "Buey ó carnero que tenga de más ó de menos, podrás ofrecer por ofrenda voluntaria; mas por voto no será acepto.",
      "24": "Herido ó magullado, rompido ó cortado, no ofreceréis á Jehová, ni en vuestra tierra lo haréis.",
      "25": "Y de mano de hijo de extranjero no ofreceréis el pan de vuestro Dios de todas estas cosas; porque su corrupción está en ellas: hay en ellas falta, no se os aceptarán.",
      "26": "Y habló Jehová á Moisés, diciendo:",
      "27": "El buey, ó el cordero, ó la cabra, cuando naciere, siete días estará mamando de su madre: mas desde el octavo día en adelante será acepto para ofrenda de sacrificio encendido a Jehová.",
      "28": "Y sea buey ó carnero, no degollaréis en un día á el y á su hijo.",
      "29": "Y cuando sacrificareis sacrificio de hacimiento de gracias á Jehová, de vuestra voluntad lo sacrificaréis.",
      "30": "En el mismo día se comerá; no dejaréis de él para otro día: Yo Jehová.",
      "31": "Guardad pues mis mandamientos, y ejecutadlos: Yo Jehová.",
      "32": "Y no amancilléis mi santo nombre, y yo me santificaré en medio de los hijos de Israel: Yo Jehová que os santifico;",
      "33": "Que os saqué de la tierra de Egipto, para ser vuestro Dios: Yo Jehová."
    },
    "23": {
      "1": "Y HABLO Jehová á Moisés, diciendo:",
      "2": "Habla á los hijos de Israel, y diles: Las solemnidades de Jehová, las cuales proclamaréis santas convocaciones, aquestas serán mis solemnidades.",
      "3": "Seis días se trabajará, y el séptimo día sábado de reposo será, convocación santa: ninguna obra haréis; sábado es de Jehová en todas vuestras habitaciones.",
      "4": "Estas son las solemnidades de Jehová, las convocaciones santas, á las cuales convocaréis en sus tiempos.",
      "5": "En el mes primero, á los catorce del mes, entre las dos tardes, pascua es de Jehová.",
      "6": "Y á los quince días de este mes es la solemnidad de los ázimos á Jehová: siete días comeréis ázimos.",
      "7": "El primer día tendréis santa convocación: ningúna obra servil haréis.",
      "8": "Y ofreceréis á Jehová siete días ofrenda encendida: el séptimo día será santa convocación; ninguna obra servil haréis.",
      "9": "Y habló Jehová á Moisés, diciendo:",
      "10": "Habla á los hijos de Israel, y diles: Cuando hubiereis entrado en la tierra que yo os doy, y segareis su mies, traeréis al sacerdote un omer por primicia de los primeros frutos de vuestra siega;",
      "11": "El cual mecerá el omer delante de Jehová, para que seáis aceptos: el siguiente día del sábado lo mecerá el sacerdote.",
      "12": "Y el día que ofrezcáis el omer, ofreceréis un cordero de un año, sin defecto, en holocausto á Jehová.",
      "13": "Y su presente será dos décimas de flor de harina amasada con aceite, ofrenda encendida á Jehová en olor suavísimo; y su libación de vino, la cuarta parte de un hin.",
      "14": "Y no comeréis pan, ni grano tostado, ni espiga fresca, hasta este mismo día, hasta que hayáis ofrecido la ofrenda de vuestro Dios; estatuto perpetuo es por vuestras edades en todas vuestras habitaciones.",
      "15": "Y os habéis de contar desde el siguiente día del sábado, desde el día en que ofrecisteis el omer de la ofrenda mecida; siete semanas cumplidas serán:",
      "16": "Hasta el siguiente día del sábado séptimo contaréis cincuenta días; entonces ofreceréis nuevo presente a Jehová.",
      "17": "De vuestras habitaciones traeréis dos panes para ofrenda mecida, que serán de dos décimas de flor de harina, cocidos con levadura, por primicias á Jehová.",
      "18": "Y ofreceréis con el pan siete corderos de un año sin defecto, y un becerro de la vacada y dos carneros: serán holocausto á Jehová, con su presente y sus libaciones; ofrenda encendida de suave olor á Jehová.",
      "19": "Ofreceréis además un macho de cabrío por expiación; y dos corderos de un año en sacrificio de paces.",
      "20": "Y el sacerdote los mecerá en ofrenda agitada delante de Jehová, con el pan de las primicias, y los dos corderos: serán cosa sagrada de Jehová para el sacerdote.",
      "21": "Y convocaréis en este mismo día; os será santa convocación: ninguna obra servil haréis: estatuto perpetuo en todas vuestras habitaciones por vuestras edades.",
      "22": "Y cuando segareis la mies de vuestra tierra, no acabarás de segar el rincón de tu haza, ni espigarás tu siega; para el pobre, y para el extranjero la dejarás: Yo Jehová vuestro Dios.",
      "23": "Y habló Jehová á Moisés, diciendo:",
      "24": "Habla á los hijos de Israel, y diles: En el mes séptimo, al primero del mes tendréis sábado, una conmemoración al son de trompetas, y una santa convocación.",
      "25": "Ninguna obra servil haréis; y ofreceréis ofrenda encendida á Jehová.",
      "26": "Y habló Jehová á Moisés, diciendo:",
      "27": "Empero á los diez de este mes séptimo será el día de las expiaciones: tendréis santa convocación, y afligiréis vuestras almas, y ofreceréis ofrenda encendida á Jehová.",
      "28": "Ninguna obra haréis en este mismo día; porque es día de expiaciones, para reconciliaros delante de Jehová vuestro Dios.",
      "29": "Porque toda persona que no se afligiere en este mismo día, será cortada de sus pueblos.",
      "30": "Y cualquiera persona que hiciere obra alguna en este mismo día, yo destruiré la tal persona de entre su pueblo.",
      "31": "Ninguna obra haréis: estatuto perpetuo es por vuestras edades en todas vuestras habitaciones.",
      "32": "Sábado de reposo será á vosotros, y afligiréis vuestras almas, comenzando á los nueve del mes en la tarde: de tarde á tarde holgaréis vuestro sábado.",
      "33": "Y habló Jehová á Moisés, diciendo:",
      "34": "Habla á los hijos de Israel, y diles: A los quince días de este mes séptimo será la solemnidad de las cabañas á Jehová por siete días.",
      "35": "El primer día habrá santa convocación: ninguna obra servil haréis.",
      "36": "Siete días ofreceréis ofrenda encendida á Jehová: el octavo día tendréis santa convocación, y ofreceréis ofrenda encendida á Jehová: es fiesta: ninguna obra servil haréis.",
      "37": "Estas son las solemnidades de Jehová, á las que convocaréis santas reuniones, para ofrecer ofrenda encendida a Jehová, holocausto y presente, sacrificio y libaciones, cada cosa en su tiempo:",
      "38": "Además de los sábados de Jehová y además de vuestros dones, y á más de todos vuestros votos, y además de todas vuestras ofrendas voluntarias, que daréis á Jehová.",
      "39": "Empero á los quince del mes séptimo, cuando hubiereis allegado el fruto de la tierra, haréis fiesta a Jehová por siete días: el primer día será sábado; sábado será también el octavo día.",
      "40": "Y tomaréis el primer día gajos con fruto de árbol hermoso, ramos de palmas, y ramas de árboles espesos, y sauces de los arroyos; y os regocijaréis delante de Jehová vuestro Dios por siete días.",
      "41": "Y le haréis fiesta á Jehová por siete días cada un año; será estatuto perpetuo por vuestras edades; en el mes séptimo la haréis.",
      "42": "En cabañas habitaréis siete días: todo natural de Israel habitará en cabañas;",
      "43": "Para que sepan vuestros descendientes que en cabañas hice yo habitar á los hijos de Israel, cuando los saqué de la tierra de Egipto: Yo Jehová vuestro Dios.",
      "44": "Así habló Moisés á los hijos de Israel sobre las solemnidades de Jehová."
    },
    "24": {
      "1": "Y HABLO Jehová á Moisés, diciendo:",
      "2": "Manda á los hijos de Israel que te traigan aceite de olivas claro, molido, para la luminaria, para hacer arder las lámparas de continuo.",
      "3": "Fuera del velo del testimonio, en el tabernáculo del testimonio, las aderezará Aarón desde la tarde hasta la mañana delante de Jehová, de continuo: estatuto perpetuo por vuestras edades.",
      "4": "Sobre el candelero limpio pondrá siempre en orden las lámparas delante de Jehová.",
      "5": "Y tomarás flor de harina, y cocerás de ella doce tortas: cada torta será de dos décimas.",
      "6": "Y has de ponerlas en dos órdenes, seis en cada orden, sobre la mesa limpia delante de Jehová.",
      "7": "Pondrás también sobre cada orden incienso limpio, y será para el pan por perfume, ofrenda encendida á Jehová.",
      "8": "Cada día de sábado lo pondrá de continuo en orden delante de Jehová, de los hijos de Israel por pacto sempiterno.",
      "9": "Y será de Aarón y de sus hijos, los cuales lo comerán en el lugar santo; porque es cosa muy santa para él, de las ofrendas encendidas á Jehová, por fuero perpetuo.",
      "10": "En aquella sazón el hijo de una mujer Israelita, el cual era hijo de un Egipcio, salió entre los hijos de Israel; y el hijo de la Israelita y un hombre de Israel riñeron en el real:",
      "11": "Y el hijo de la mujer Israelita pronunció el Nombre, y maldijo: entonces le llevaron á Moisés. Y su madre se llamaba Selomith, hija de Dribi, de la tribu de Dan.",
      "12": "Y pusiéronlo en la cárcel, hasta que les fuese declarado por palabra de Jehová.",
      "13": "Y Jehová habló á Moisés, diciendo:",
      "14": "Saca al blasfemo fuera del real, y todos los que le oyeron pongan sus manos sobre la cabeza de él, y apedréelo toda la congregación.",
      "15": "Y á los hijos de Israel hablarás, diciendo: Cualquiera que maldijere á su Dios, llevará su iniquidad.",
      "16": "Y el que blasfemare el nombre de Jehová, ha de ser muerto; toda la congregación lo apedreará: así el extranjero como el natural, si blasfemare el Nombre, que muera.",
      "17": "Asimismo el hombre que hiere de muerte á cualquiera persona, que sufra la muerte.",
      "18": "Y el que hiere á algún animal ha de restituirlo: animal por animal.",
      "19": "Y el que causare lesión en su prójimo, según hizo, así le sea hecho:",
      "20": "Rotura por rotura, ojo por ojo, diente por diente: según la lesión que habrá hecho á otro, tal se hará á él.",
      "21": "El que hiere algún animal, ha de restituirlo; mas el que hiere de muerte á un hombre, que muera.",
      "22": "Un mismo derecho tendréis: como el extranjero, así será el natural: porque yo soy Jehová vuestro Dios.",
      "23": "Y habló Moisés á los hijos de Israel, y ellos sacaron al blasfemo fuera del real, y apedreáronlo con piedras. Y los hijos de Israel hicieron según que Jehová había mandado á Moisés."
    }
  }
};

