
	
export const bib_verses = {
  "2_samuel": {
    "18": {
      "1": "DAVID pues revistó el pueblo que tenía consigo, y puso sobre ellos tribunos y centuriones.",
      "2": "Y consignó la tercera parte del pueblo al mando de Joab, y otra tercera al mando de Abisai, hijo de Sarvia, hermano de Joab, y la otra tercera parte al mando de Ittai Getheo. Y dijo el rey al pueblo: Yo también saldré con vosotros.",
      "3": "Mas el pueblo dijo: No saldrás; porque si nosotros huyéremos, no harán caso de nosotros; y aunque la mitad de nosotros muera, no harán caso de nosotros: mas tú ahora vales tanto como diez mil de nosotros. Será pues mejor que tú nos des ayuda desde la ciudad.",
      "4": "Entonces el rey les dijo: Yo haré lo que bien os pareciere. Y púsose el rey á la entrada de la puerta, mientras salía todo el pueblo de ciento en ciento y de mil en mil.",
      "5": "Y el rey mandó á Joab y á Abisai y á Ittai, diciendo: Tratad benignamente por amor de mí al mozo Absalom. Y todo el pueblo oyó cuando dió el rey orden acerca de Absalom á todos los capitanes.",
      "6": "Salió pues el pueblo al campo contra Israel, y dióse la batalla en el bosque de Ephraim;",
      "7": "Y allí cayó el pueblo de Israel delante de los siervos de David, é hízose una gran matanza de veinte mil hombres.",
      "8": "Y derramándose allí el ejército por la haz de toda la tierra, fueron más los que consumió el bosque de los del pueblo, que los que consumió el cuchillo aquel día.",
      "9": "Y encontróse Absalom con los siervos de David: é iba Absalom sobre un mulo, y el mulo se entró debajo de un espeso y grande alcornoque, y asiósele la cabeza al alcornoque, y quedó entre el cielo y la tierra; pues el mulo en que iba pasó delante.",
      "10": "Y viéndolo uno, avisó á Joab, diciendo: He aquí que he visto á Absalom colgado de un alcornoque.",
      "11": "Y Joab respondió al hombre que le daba la nueva: Y viéndolo tú, ¿por qué no le heriste luego allí echándole á tierra? y sobre mí, que te hubiera dado diez siclos de plata, y un talabarte.",
      "12": "Y el hombre dijo á Joab: Aunque me importara en mis manos mil siclos de plata, no extendiera yo mi mano contra el hijo del rey; porque nosotros lo oímos cuando el rey te mandó á ti y á Abisai y á Ittai, diciendo: Mirad que ninguno toque en el joven Absalom.",
      "13": "Por otra parte, habría yo hecho traición contra mi vida (pues que al rey nada se le esconde), y tú mismo estarías en contra.",
      "14": "Y respondió Joab: No es razón que yo te ruegue. Y tomando tres dardos en sus manos, hincólos en el corazón de Absalom, que aun estaba vivo en medio del alcornoque.",
      "15": "Cercándolo luego diez mancebos escuderos de Joab, hirieron á Absalom, y acabáronle.",
      "16": "Entonces Joab tocó la corneta, y el pueblo se volvió de seguir á Israel, porque Joab detuvo al pueblo.",
      "17": "Tomando después á Absalom, echáronle en un gran hoyo en el bosque, y levantaron sobre él un muy grande montón de piedras; y todo Israel huyó, cada uno á sus estancias.",
      "18": "Y había Absalom en su vida tomado y levantádose una columna, la cual está en el valle del rey; porque había dicho: Yo no tengo hijo que conserve la memoria de mi nombre. Y llamó aquella columna de su nombre: y así se llamó el Lugar de Absalom, hasta hoy.",
      "19": "Entonces Ahimaas hijo de Sadoc dijo: ¿Correré ahora, y daré las nuevas al rey de cómo Jehová ha defendido su causa de la mano de sus enemigos?",
      "20": "Y respondió Joab: Hoy no llevarás las nuevas: las llevarás otro día: no darás hoy la nueva, porque el hijo del rey es muerto.",
      "21": "Y Joab dijo á Cusi: Ve tú, y di al rey lo que has visto. Y Cusi hizo reverencia á Joab, y corrió.",
      "22": "Entonces Ahimaas hijo de Sadoc tornó á decir á Joab: Sea lo que fuere, yo correré ahora tras Cusi. Y Joab dijo: Hijo mío, ¿para qué has tú de correr, pues que no hallarás premio por las nuevas?",
      "23": "Mas él respondió: Sea lo que fuere, yo correré. Entonces le dijo: Corre. Corrió pues Ahimaas por el camino de la llanura, y pasó delante de Cusi.",
      "24": "Estaba David á la sazón sentado entre las dos puertas; y el atalaya había ido al terrado de sobre la puerta en el muro, y alzando sus ojos, miró, y vió á uno que corría solo.",
      "25": "El atalaya dió luego voces, é hízolo saber al rey. Y el rey dijo: Si es solo, buenas nuevas trae. En tanto que él venía acercándose,",
      "26": "Vió el atalaya otro que corría; y dió voces el atalaya al portero, diciendo: He aquí otro hombre que corre solo. Y el rey dijo: Este también es mensajero.",
      "27": "Y el atalaya volvió á decir: Paréceme el correr del primero como el correr de Ahimaas hijo de Sadoc. Y respondió el rey: Ese es hombre de bien, y viene con buena nueva.",
      "28": "Entonces Ahimaas dijo en alta voz al rey: Paz. E inclinóse á tierra delante del rey, y dijo: Bendito sea Jehová Dios tuyo, que ha entregado á los hombres que habían levantado sus manos contra mi señor el rey.",
      "29": "Y el rey dijo: ¿El mozo Absalom tiene paz? Y Ahimaas respondió: Vi yo un grande alboroto cuando envió Joab al siervo del rey y á mí tu siervo; mas no sé qué era.",
      "30": "Y el rey dijo: Pasa, y ponte allí. Y él pasó, y paróse.",
      "31": "Y luego vino Cusi, y dijo: Reciba nueva mi señor el rey, que hoy Jehová ha defendido tu causa de la mano de todos los que se habían levantado contra ti.",
      "32": "El rey entonces dijo á Cusi: ¿El mozo Absalom tiene paz? Y Cusi respondió: Como aquel mozo sean los enemigos de mi señor el rey, y todos los que se levantan contra ti para mal.",
      "33": "Entonces el rey se turbó, y subióse á la sala de la puerta, y lloró; y yendo, decía así: ­Hijo mío Absalom, hijo mío, hijo mío Absalom! ­Quién me diera que muriera yo en lugar de ti, Absalom, hijo mío, hijo mío!"
    },
    "19": {
      "1": "Y DIERON aviso á Joab: He aquí el rey llora, y hace duelo por Absalom.",
      "2": "Y volvióse aquel día la victoria en luto para todo el pueblo; porque oyó decir el pueblo aquel día que el rey tenía dolor por su hijo.",
      "3": "Entróse el pueblo aquel día en la ciudad escondidamente, como suele entrar á escondidas el pueblo avergonzado que ha huído de la batalla.",
      "4": "Mas el rey, cubierto el rostro, clamaba en alta voz: ­Hijo mío Absalom, Absalom, hijo mío, hijo mío!",
      "5": "Y entrando Joab en casa al rey, díjole: Hoy has avergonzado el rostro de todos tus siervos, que han hoy librado tu vida, y la vida de tus hijos y de tus hijas, y la vida de tus mujeres, y la vida de tus concubinas,",
      "6": "Amando á los que te aborrecen, y aborreciendo á los que te aman: porque hoy has declarado que nada te importan tus príncipes y siervos; pues hoy echo de ver que si Absalom viviera, bien que nosotros todos estuviéramos hoy muertos, entonces te contentaras.",
      "7": "Levántate pues ahora, y sal fuera, y halaga á tus siervos: porque juro por Jehová, que si no sales, ni aun uno quede contigo esta noche; y de esto te pesará más que de todos los males que te han sobrevenido desde tu mocedad hasta ahora.",
      "8": "Entonces se levantó el rey, y sentóse á la puerta; y fué declarado á todo el pueblo, diciendo: He aquí el rey está sentado á la puerta. Y vino todo el pueblo delante del rey; mas Israel había huído, cada uno á sus estancias.",
      "9": "Y todo el pueblo porfiaba en todas las tribus de Israel, diciendo: El rey nos ha librado de mano de nuestros enemigos, y él nos ha salvado de mano de los Filisteos; y ahora había huído, de la tierra por miedo de Abaslom.",
      "10": "Y Absalom, á quien habíamos ungido sobre nosotros, es muerto en la batalla. ¿Por qué pues os estáis ahora quedos en orden á hacer volver al rey?",
      "11": "Y el rey David envió á Sadoc y á Abiathar sacerdotes, diciendo: Hablad á los ancianos de Judá y decidles: ¿Por qué seréis vosotros los postreros en volver el rey á su casa, ya que la palabra de todo Israel ha venido al rey de volverle á su casa?",
      "12": "Vosotros sois mis hermanos; mis huesos y mi carne sois: ¿por qué pues seréis vosotros los postreros en volver al rey?",
      "13": "Asimismo diréis á Amasa: ¿No eres tú también hueso mío y carne mía? Así me haga Dios, y así me añada, si no fueres general del ejército delante de mí para siempre, en lugar de Joab.",
      "14": "Así inclinó el corazón de todos los varones de Judá, como el de un solo hombre, para que enviasen á decir al rey: Vuelve tú, y todos tus siervos.",
      "15": "Volvió pues el rey, y vino hasta el Jordán. Y Judá vino á Gilgal, á recibir al rey y pasarlo el Jordán.",
      "16": "Y Semei hijo de Gera, hijo de Benjamín, que era de Bahurim, dióse priesa á venir con los hombres de Judá á recibir al rey David;",
      "17": "Y con él venían mil hombres de Benjamín; asimismo Siba criado de la casa de Saúl, con sus quince hijos y sus veinte siervos, los cuales pasaron el Jordán delante del rey.",
      "18": "Atravesó después la barca para pasar la familia del rey, y para hacer lo que le pluguiera. Entonces Semei hijo de Gera se postró delante del rey cuando él había pasado el Jordán.",
      "19": "Y dijo al rey: No me impute mi señor iniquidad, ni tengas memoria de los males que tu siervo hizo el día que mi señor el rey salió de Jerusalem, para guardarlos el rey en su corazón;",
      "20": "Porque yo tu siervo conozco haber pecado, y he venido hoy el primero de toda la casa de José, para descender á recibir á mi señor el rey.",
      "21": "Y Abisai hijo de Sarvia responidió y dijo: ¿No ha de morir por esto Semei, que maldijo al ungido de Jehová?",
      "22": "David entonces dijo: ¿Qué tenéis vosotros conmigo, hijos de Sarvia, que me habéis de ser hoy adversarios? ¿ha de morir hoy alguno en Israel? ¿no conozco yo que hoy soy rey sobre Israel?",
      "23": "Y dijo el rey á Semei: No morirás. Y el rey se lo juró.",
      "24": "También Mephi-boseth hijo de Saúl descendió á recibir al rey: no había lavado sus pies, ni había cortado su barba, ni tampoco había lavado sus vestidos, desde el día que el rey salió hasta el día que vino en paz.",
      "25": "Y luego que vino él á Jerusalem á recibir al rey, el rey le dijo: Mephi-boseth, ¿Por qué no fuiste conmigo?",
      "26": "Y él dijo: Rey señor mío, mi siervo me ha engañado; pues había tu siervo dicho: Enalbardaré un asno, y subiré en él, é iré al rey; porque tu siervo es cojo.",
      "27": "Empero él revolvió á tu siervo delante de mi señor el rey; mas mi señor el rey es como un ángel de Dios: haz pues lo que bien te pareciere.",
      "28": "Porque toda la casa de mi padre era digna de muerte delante de mi señor el rey, y tú pusiste á tu siervo entre los convidados de tu mesa. ¿Qué derecho pues tengo aún para quejarme más contra el rey?",
      "29": "Y el rey le dijo: ¿Para qué hablas más palabras? Yo he determinado que tú y Siba partáis las tierras.",
      "30": "Y Mephi-boseth dijo al rey: Y aun tómelas él todas, pues que mi señor el rey ha vuelto en paz á su casa.",
      "31": "También Barzillai Galaadita descendió de Rogelim, y pasó el Jordán con el rey, para acompañarle de la otra parte del Jordán.",
      "32": "Y era Barzillai muy viejo, de ochenta años, el cual había dado provisión al rey cuando estaba en Mahanaim, porque era hombre muy rico.",
      "33": "Y el rey dijo á Barzillai: Pasa conmigo, y yo te daré de comer conmigo en Jerusalem.",
      "34": "Mas Barzillai dijo al rey: ¿Cuántos son los días del tiempo de mi vida, para que yo suba con el rey á Jerusalem?",
      "35": "Yo soy hoy día de edad de ochenta años, que ya no haré diferencia entre lo bueno y lo malo: ¿tomará gusto ahora tu siervo en lo que comiere ó bebiere? ¿oiré más la voz de los cantores y de las cantoras? ¿para qué, pues, sería aún tu siervo molesto á mi señor el rey?",
      "36": "Pasará tu siervo un poco el Jordán con el rey: ¿por qué me ha de dar el rey tan grande recompensa?",
      "37": "Yo te ruego que dejes volver á tu siervo, y que muera en mi ciudad, junto al sepulcro de mi padre y de mi madre. He aquí tu siervo Chimham; que pase él con mi señor el rey, y hazle lo que bien te pareciere.",
      "38": "Y el rey dijo: Pues pase conmigo Chimham, y yo haré con él como bien te parezca: y todo lo que tú pidieres de mí, yo lo haré.",
      "39": "Y todo el pueblo pasó el Jordán: y luego que el rey hubo también pasado, el rey besó á Barzillai, y bendíjolo; y él se volvió á su casa.",
      "40": "El rey entonces pasó á Gilgal, y con él pasó Chimham; y todo el pueblo de Judá, con la mitad del pueblo de Israel, pasaron al rey.",
      "41": "Y he aquí todos los varones de Israel vinieron al rey, y le dijeron: ¿Por qué los hombres de Judá, nuestros hermanos, te han llevado, y han hecho pasar el Jordán al rey y á su familia, y á todos los varones de David con él?",
      "42": "Y todos los varones de Judá respondieron á todos los de Israel: Porque el rey es nuestro pariente. Mas ¿por qué os enojáis vosotros de eso? ¿hemos nosotros comido algo del rey? ¿hemos recibido de él algún don?",
      "43": "Entonces respondieron los varones de Israel, y dijeron á los de Judá: Nosotros tenemos en el rey diez partes, y en el mismo David más que vosotros: ¿por qué pues nos habéis tenido en poco? ¿no hablamos nosotros primero en volver á nuestro rey? Y el razonamiento de los varones de Judá fué más fuerte que el de los varones de Israel."
    },
    "20": {
      "1": "Y ACAECIO estar allí un hombre perverso que se llamaba Seba, hijo de Bichri, hombre de Benjamín, el cual tocó la corneta, y dijo: No tenemos nosotros parte en David, ni heredad en el hijo de Isaí: Israel, ­cada uno á sus estancias!",
      "2": "Así se fueron de en pos de David todos los hombres de Israel, y seguían á Seba hijo de Bichri: mas los de Judá fueron adheridos á su rey, desde el Jordán hasta Jerusalem.",
      "3": "Y luego que llegó David á su casa en Jerusalem, tomó el rey las diez mujeres concubinas que había dejado para guardar la casa, y púsolas en una casa en guarda, y dióles de comer: pero nunca más entró á ellas, sino que quedaron encerradas hasta que murieron en viudez de por vida.",
      "4": "Después dijo el rey á Amasa: Júntame los varones de Judá para dentro de tres días, y hállate tú aquí presente.",
      "5": "Fué pues Amasa á juntar á Judá; pero detúvose más del tiempo que le había sido señalado.",
      "6": "Y dijo David á Abisai: Seba hijo de Bichri nos hará ahora más mal que Absalom: toma pues tú los siervos de tu señor, y ve tras él, no sea que halle las ciudades fortificadas, y se nos vaya de delante.",
      "7": "Entonces salieron en pos de él los hombres de Joab, y los Ceretheos y Peletheos, y todos los valientes: salieron de Jerusalem para ir tras Seba hijo de Bichri.",
      "8": "Y estando ellos cerca de la grande peña que está en Gabaón, salióles Amasa al encuentro. Ahora bien, la vestidura que Joab tenía sobrepuesta estábale ceñida, y sobre ella el cinto de una daga pegada á sus lomos en su vaina, de la que así como él avanzó, cayóse aquélla.",
      "9": "Entonces Joab dijo á Amasa: ¿Tienes paz, hermano mío? Y tomó Joab con la diestra la barba de Amasa, para besarlo.",
      "10": "Y como Amasa no se cuidó de la daga que Joab en la mano tenía, hirióle éste con ella en la quinta costilla, y derramó sus entrañas por tierra, y cayó muerto sin darle segundo golpe. Después Joab y su hermano Abisai fueron en seguimiento de Seba hijo de Bichri.",
      "11": "Y uno de los criados de Joab se paró junto á él, diciendo: Cualquiera que amare á Joab y á David vaya en pos de Joab.",
      "12": "Y Amasa se había revolcado en la sangre en mitad del camino: y viendo aquel hombre que todo el pueblo se paraba, apartó á Amasa del camino al campo, y echó sobre él una vestidura, porque veía que todos los que venían se paraban junto á él.",
      "13": "Luego, pues, que fué apartado del camino, pasaron todos los que seguían á Joab, para ir tras Seba hijo de Bichri.",
      "14": "Y él pasó por todas las tribus de Israel hasta Abel y Beth-maachâ y todo Barim: y juntáronse, y siguiéronlo también.",
      "15": "Y vinieron y cercáronlo en Abel de Beth-maachâ, y pusieron baluarte contra la ciudad; y puesto que fué al muro, todo el pueblo que estaba con Joab trabajaba por derribar la muralla.",
      "16": "Entonces una mujer sabia dió voces en la ciudad, diciendo: Oid, oid; ruégoos que digáis á Joab se llegue á acá, para que yo hable con él.",
      "17": "Y como él se acercó á ella, dijo la mujer: ¿Eres tú Joab? Y él respondió: Yo soy. Y ella le dijo: Oye las palabras de tu sierva. Y él respondió: Oigo.",
      "18": "Entonces tornó ella á hablar, diciendo: Antiguamente solían hablar, diciendo: Quien preguntare, pregunte en Abel: y así concluían.",
      "19": "Yo soy de las pacíficas y fieles de Israel: y tú procuras destruir una ciudad que es madre de Israel: ¿por qué destruyes la heredad de Jehová?",
      "20": "Y Joab respondió, diciendo: Nunca tal, nunca tal me acontezca, que yo destruya ni deshaga.",
      "21": "La cosa no es así: mas un hombre del monte de Ephraim, que se llama Seba hijo de Bichri, ha levantado su mano contra el rey David: entregad á ése solamente, y me iré de la ciudad. Y la mujer dijo á Joab: He aquí su cabeza te será echada desde el muro.",
      "22": "La mujer fué luego á todo el pueblo con su sabiduría; y ellos cortaron la cabeza á Seba hijo de Bichri, y echáronla á Joab. Y él tocó la corneta, y esparciéronse de la ciudad, cada uno á su estancia. Y Joab se volvió al rey á Jerusalem.",
      "23": "Así quedó Joab sobre todo el ejército de Israel; y Benaía hijo de Joiada sobre los Ceretheos y Peletheos;",
      "24": "Y Adoram sobre los tributos; y Josaphat hijo de Ahillud, el canciller;",
      "25": "Y Seba, escriba; y Sadoc y Abiathar, sacerdotes;",
      "26": " é Ira Jaireo fué un jefe principal cerca de David."
    },
    "21": {
      "1": "Y EN los días de David hubo hambre por tres años consecutivos. Y David consultó á Jehová, y Jehová le dijo: Es por Saúl, y por aquella casa de sangre; porque mató á los Gabaonitas.",
      "2": "Entonces el rey llamó á los Gabaonitas, y hablóles. (Los Gabaonitas no eran de los hijos de Israel, sino del residuo de los Amorrheos, á los cuales los hijos de Israel habían hecho juramento: mas Saúl había procurado matarlos con motivo de celo por los hijos de Israel y de Judá.)",
      "3": "Dijo pues David á los Gabaonitas: ¿Qué os haré, y con qué expiaré para que bendigáis á la heredad de Jehová?",
      "4": "Y los Gabaonitas le respondieron: No tenemos nosotros querella sobre plata ni sobre oro con Saúl, y con su casa: ni queremos que muera hombre de Israel. Y él les dijo: Lo que vosotros dijereis os haré.",
      "5": "Y ellos respondieron al rey: De aquel hombre que nos destruyó, y que maquinó contra nosotros, para extirparnos sin dejar nada de nosotros en todo el término de Israel;",
      "6": "Dénsenos siete varones de sus hijos, para que los ahorquemos á Jehová en Gabaa de Saúl, el escogido de Jehová. Y el rey dijo: Yo los daré.",
      "7": "Y perdonó el rey á Mephi-boseth, hijo de Jonathán, hijo de Saúl, por el juramento de Jehová que hubo entre ellos, entre David y Jonathán hijo de Saúl.",
      "8": "Mas tomó el rey dos hijos de Rispa hija de Aja, los cuales ella había parido á Saúl, á saber, á Armoni y á Mephi-boseth; y cinco hijos de Michâl hija de Saúl, los cuales ella había parido á Adriel, hijo de Barzillai Molathita;",
      "9": "Y entrególos en manos de los Gabaonitas, y ellos los ahorcaron en el monte delante de Jehová: y murieron juntos aquellos siete, lo cuales fueron muertos en el tiempo de la siega, en los primeros días, en el principio de la siega de las cebadas.",
      "10": "Tomando luego Rispa hija de Aja un saco, tendióselo sobre un peñasco, desde el principio de la siega hasta que llovió sobre ellos agua del cielo; y no dejó á ninguna ave del cielo asentarse sobre ellos de día, ni bestias del campo de noche.",
      "11": "Y fué dicho á David lo que hacía Rispa hija de Aja, concubina de Saúl.",
      "12": "Entonces David fué, y tomó los huesos de Saúl y los huesos de Jonathán su hijo, de los hombres de Jabes de Galaad, que los habían hurtado de la plaza de Beth-san, donde los habían colgado los Filisteos, cuando deshicieron los Filisteos á Saúl en Gilboa:",
      "13": "E hizo llevar de allí los huesos de Saúl y los huesos de Jonathán su hijo; y juntaron también los huesos de los ahorcados.",
      "14": "Y sepultaron los huesos de Saúl y los de su hijo Jonathán en tierra de Benjamín, en Sela, en el sepulcro de Cis su padre; é hicieron todo lo que el rey había mandado. Después se aplacó Dios con la tierra.",
      "15": "Y como los Filisteos tornaron á hacer guerra á Israel, descendió David y sus siervos con él, y pelearon con los Filisteos: y David se cansó.",
      "16": "En esto Isbi-benob, el cual era de los hijos del gigante, y el peso de cuya lanza era de trescientos siclos de metal, y tenía él ceñida una nueva espada, trató de herir á David:",
      "17": "Mas Abisai hijo de Sarvia le socorrió, é hirió al Filisteo, y matólo. Entonces los hombres de David le juraron, diciendo: Nunca más de aquí adelante saldrás con nosotros á batalla, porque no apagues la lámpara de Israel.",
      "18": "Otra segunda guerra hubo después en Gob contra los Filisteos: entonces Sibechâi Husathita hirió á Saph, que era de los hijos del gigante.",
      "19": "Otra guerra hubo en Gob contra los Filisteos, en la cual Elhanan, hijo de Jaare-oregim de Beth-lehem, hirió á Goliath Getheo, el asta de cuya lanza era como un enjullo de telar.",
      "20": "Después hubo otra guerra en Gath, donde hubo un hombre de grande altura, el cual tenía doce dedos en las manos, y otros doce en los pies, veinticuatro en todos: y también era de lo hijos del gigante.",
      "21": "Este desafió á Israel, y matólo Jonathán, hijo de Sima hermano de David.",
      "22": "Estos cuatro le habían nacido al gigante en Gath, los cuales cayeron por la mano de David, y por la mano de sus siervos."
    },
    "22": {
      "1": "Y HABLO David á Jehová las palabras de este cántico, el día que Jehová le había librado de la mano de todos sus enemigos, y de la mano de Saúl.",
      "2": "Y dijo: Jehová es mi roca, y mi fortaleza, y mi libertador;",
      "3": "Dios de mi roca, en él confiaré: Mi escudo, y el cuerno de mi salud, mi fortaleza, y mi refugio; Mi salvador, que me librarás de violencia.",
      "4": "Invocaré á Jehová, digno de ser loado. Y seré salvo de mis enemigos.",
      "5": "Cuando me cercaron ondas de muerte, Y arroyos de iniquidad me asombraron,",
      "6": "Me rodearon los dolores del infierno, Y me tomaron descuidado lazos de muerte.",
      "7": "Tuve angustia, invoqué á Jehová, Y clamé á mi Dios: Y él oyó mi voz desde su templo; Llegó mi clamor á sus oídos.",
      "8": "La tierra se removió, y tembló; Los fundamentos de los cielos fueron movidos, Y se estremecieron, porque él se airó.",
      "9": "Subió humo de sus narices, Y de su boca fuego consumidor, Por el cual se encendieron carbones.",
      "10": "Y abajo los cielos, y descendió: Una oscuridad debajo de sus pies.",
      "11": "Subió sobre el querubín, y voló: Aparecióse sobre las alas del viento.",
      "12": "Puso tinieblas alrededor de sí á modo de pabellones; Aguas negras y espesas nubes.",
      "13": "Del resplandor de su presencia Se encendieron ascuas ardientes.",
      "14": "Jehová tronó desde los cielos, Y el Altísimo dió su voz;",
      "15": "Arrojó saetas, y desbaratólos; Relampagueó, y consumiólos.",
      "16": "Entonces aparecieron los manantiales de la mar, Y los fundamentos del mundo fueron descubiertos, A la reprensión de Jehová, Al resoplido del aliento de su nariz.",
      "17": "Extendió su mano de lo alto, y arrebatóme, Y sacóme de copiosas aguas.",
      "18": "Libróme de fuertes enemigos, De aquellos que me aborrecían, los cuales eran más fuertes que yo.",
      "19": "Asaltáronme en el día de mi calamidad; Mas Jehová fué mi sostén.",
      "20": "Sacóme á anchura; Libróme, porque puso su voluntad en mí.",
      "21": "Remuneróme Jehová conforme á mi justicia: Y conforme á la limpieza de mis manos, me dió la paga.",
      "22": "Porque yo guardé los caminos de Jehová; Y no me aparté impíamente de mi Dios.",
      "23": "Porque delante de mí tengo todas sus ordenanzas; Y atento á sus fueros, no me retiraré de ellos.",
      "24": "Y fuí íntegro para con él, Y guardéme de mi iniquidad.",
      "25": "Remuneróme por tanto Jehová conforme á mi justicia, Y conforme á mi limpieza delante de sus ojos.",
      "26": "Con el bueno eres benigno, Y con el íntegro te muestras íntegro;",
      "27": "Limpio eres para con el limpio, Mas con el perverso eres rígido.",
      "28": "Y tú salvas al pueblo humilde; Mas tus ojos sobre los altivos, para abatirlos.",
      "29": "Porque tú eres mi lámpara, oh Jehová: Jehová da luz á mis tinieblas.",
      "30": "Porque en ti romperé ejércitos, Y con mi Dios saltaré las murallas.",
      "31": "Dios, perfecto su camino: La palabra de Jehová purificada, Escudo es de todos los que en él esperan.",
      "32": "Porque ¿qué Dios hay sino Jehová? ¿O quién es fuerte sino nuestro Dios?",
      "33": "Dios es el que con virtud me corrobora, y el que despeja mi camino;",
      "34": "El que hace mis pies como de ciervas, Y el que me asienta en mis alturas;",
      "35": "El que enseña mis manos para la pelea, y da que con mis brazos quiebre el arco de acero.",
      "36": "Tú me diste asimismo el escudo de tu salud, Y tu benignidad me ha acrecentado.",
      "37": "Tú ensanchaste mis pasos debajo de mí, Para que no titubeasen mis rodillas.",
      "38": "Perseguiré á mis enemigos, y quebrantarélos; Y no me volveré hasta que los acabe.",
      "39": "Los consumiré, y los heriré, y no se levantarán; Y caerán debajo de mis pies.",
      "40": "Ceñísteme de fortaleza para la batalla, Y postraste debajo de mí los que contra mí se levantaron.",
      "41": "Tú me diste la cerviz de mis enemigos, De mis aborrecedores, y que yo los destruyese.",
      "42": "Miraron, y no hubo quien los librase; A Jehová, mas no les respondió.",
      "43": "Yo los desmenuzaré como polvo de la tierra; Hollarélos como á lodo de las plazas, y los disiparé.",
      "44": "Tú me libraste de contiendas de pueblos: Tú me guardaste para que fuese cabeza de gentes: Pueblos que no conocía, me sirvieron.",
      "45": "Los extraños titubeaban á mí: En oyendo, me obedecían.",
      "46": "Los extraños desfallecían, Y temblaban en sus escondrijos.",
      "47": "Viva Jehová, y sea bendita mi roca; Sea ensalzado el Dios, la roca de mi salvamento:",
      "48": "El Dios que me ha vengado, Y sujeta los pueblos debajo de mí:",
      "49": "Y que me saca de entre mis enemigos: Tu me sacaste en alto de entre los que se levantaron contra mi: Librásteme del varón de iniquidades.",
      "50": "Por tanto yo te confesaré entre las gentes, oh Jehová, Y cantaré á tu nombre.",
      "51": "El que engrandece las saludes de su rey, Y hace misericordia á su ungido, A David, y á su simiente, para siempre."
    },
    "23": {
      "1": "ESTAS son las postreras palabras de David. Dijo David hijo de Isaí, Dijo aquel varón que fué levantado alto, El ungido del Dios de Jacob, El suave en cánticos de Israel:",
      "2": "El espíritu de Jehová ha hablado por mí, Y su palabra ha sido en mi lengua.",
      "3": "El Dios de Israel ha dicho, Hablóme el Fuerte de Israel: El señoreador de los hombres será justo. Señoreador en temor de Dios.",
      "4": "Será como la luz de la mañana cuando sale el sol, De la mañana sin nubes; Cuando la hierba de la tierra brota Por medio del resplandor después de la lluvia.",
      "5": "No así mi casa para con Dios: Sin embargo él ha hecho conmigo pacto perpetuo, Ordenado en todas las cosas, y será guardado; Bien que toda esta mi salud, y todo mi deseo No lo haga él florecer todavía.",
      "6": "Mas los de Belial serán todos ellos como espinas arrancadas, Las cuales nadie toma con la mano;",
      "7": "Sino que el que quiere tocar en ellas, Armase de hierro y de asta de lanza, Y son quemadas en su lugar.",
      "8": "Estos son los nombres de los valientes que tuvo David: El Tachmonita, que se sentaba en cátedra, principal de los capitanes: era éste Adino el Eznita, que mató en una ocasión sobre ochocientos hombres.",
      "9": "Después de éste, Eleazar, hijo de Dodo de Ahohi, fué de los tres valientes que estaban con David, cuando desafiaron á los Filisteos que se habían juntado allí á la batalla, y subieron los de Israel.",
      "10": "Este, levantándose, hirió á los Filisteos, hasta que su mano se cansó, y quedósele contraída á la espada. Aquel día Jehová hizo gran salud: y volvióse el pueblo en pos de él solamente á tomar el despojo.",
      "11": "Después de éste fué Samma, hijo de Age Araita: que habiéndose juntado los Filisteos en una aldea, había allí una suerte de tierra llena de lentejas, y el pueblo había huído delante de los Filisteos:",
      "12": "El entonces se paró en medio de la suerte de tierra, y defendióla, é hirió á los Filisteos; y Jehová hizo una gran salud.",
      "13": "Y tres de los treinta principales descendieron y vinieron en tiempo de la siega á David á la cueva de Adullam: y el campo de los Filisteos estaba en el valle de Raphaim.",
      "14": "David entonces estaba en la fortaleza, y la guarnición de los Filisteos estaba en Beth-lehem.",
      "15": "Y David tuvo deseo, y dijo: ­Quién me diera á beber del agua de la cisterna de Beth-lehem, que está á la puerta!",
      "16": "Entonces los tres valientes rompieron por el campo de los Filisteos, y sacaron agua de la cisterna de Beth-lehem, que estaba á la puerta; y tomaron, y trajéronla á David: mas él no la quiso beber, sino derramóla á Jehová, diciendo:",
      "17": "Lejos sea de mí, oh Jehová, que yo haga esto. ¿He de beber yo la sangre de los varones que fueron con peligro de su vida? Y no quiso beberla. Los tres valientes hicieron esto.",
      "18": "Y Abisai hermano de Joab, hijo de Sarvia, fué el principal de los tres; el cual alzó su lanza contra trescientos, que mató; y tuvo nombre entre los tres.",
      "19": "El era el más aventajado de los tres, y el primero de ellos; mas no llegó á los tres primeros.",
      "20": "Después, Benaía hijo de Joiada, hijo de un varón esforzado, grande en hechos, de Cabseel. Este hirió dos leones de Moab: y él mismo descendió, é hirió un león en medio de un foso en el tiempo de la nieve:",
      "21": "También hirió él á un Egipcio, hombre de grande estatura: y tenía el Egipcio una lanza en su mano; mas descendió á él con un palo, y arrebató al Egipcio la lanza de la mano, y matólo con su propia lanza.",
      "22": "Esto hizo Benaía hijo de Joiada, y tuvo nombre entre los tres valientes.",
      "23": "De los treinta fué el más aventajado; pero no llegó á los tres primeros. Y púsolo David en su consejo.",
      "24": "Asael hermano de Joab fué de los treinta; Elhaanan hijo de Dodo de Beth-lehem;",
      "25": "Samma de Harodi, Elica de Harodi;",
      "26": "Heles de Palti, Hira, hijo de Jecces, de Tecoa;",
      "27": "Abiezer de Anathoth, Mebunnai de Husa;",
      "28": "Selmo de Hahoh, Maharai de Netophath;",
      "29": "Helec hijo de Baana de Netophath, Ittai hijo de Ribai de Gabaa de los hijos de Benjamín;",
      "30": "Benaía Pirathonita, Hiddai del arroyo de Gaas;",
      "31": "Abi-albon de Arbath, Asmaveth de Barhum;",
      "32": "Elihaba de Saalbón, Jonathán de los hijo de Jassén;",
      "33": "Samma de Arar, Ahiam hijo de Sarar de Arar.",
      "34": "Elipheleth hijo de Asbai hijo de Maachâti; Eliam hijo de Achîtophel de Gelón;",
      "35": "Hesrai del Carmelo, Pharai de Arbi;",
      "36": "Igheal hijo de Nathán de Soba, Bani de Gadi;",
      "37": "Selec de Ammón, Naharai de Beeroth, escudero de Joab hijo de Sarvia;",
      "38": "Ira de Ithri, Gareb de Ithri;",
      "39": "Uría Hetheo. Entre todos treinta y siete."
    },
    "24": {
      "1": "Y VOLVIO el furor de Jehová á encenderse contra Israel, é incitó á David contra ellos á que dijese: Ve, cuenta á Israel y á Judá.",
      "2": "Y dijo el rey á Joab, general del ejército que tenía consigo: Rodea todas las tribus de Israel, desde Dan hasta Beer-seba, y contad el pueblo, para que yo sepa el número de la gente.",
      "3": "Y Joab respondió al rey: Añada Jehová tu Dios al pueblo cien veces tanto como son, y que lo vea mi señor al rey; mas ¿para qué quiere esto mi señor el rey?",
      "4": "Empero la palabra del rey pudo más que Joab, y que los capitanes del ejército. Salió pues Joab, con los capitanes del ejército, de delante del rey, para contar el pueblo de Israel.",
      "5": "Y pasando el Jordán asentaron en Aroer, á la mano derecha de la ciudad que está en medio de la arroyada de Gad y junto á Jazer.",
      "6": "Después vinieron á Galaad, y á la tierra baja de Absi: y de allí vinieron á Dan-jaán y alrededor de Sidón.",
      "7": "Y vinieron luego á la fortaleza de Tiro, y á todas las ciudades de los Heveos y de los Cananeos; y salieron al mediodía de Judá, á Beer-seba.",
      "8": "Y después que hubieron andado toda la tierra, volvieron á Jerusalem al cabo de nueve meses y veinte días.",
      "9": "Y Joab dió la cuenta del número del pueblo al rey; y fueron los de Israel ochocientos mil hombres fuertes que sacaban espada; y de los de Judá quinientos mil hombres.",
      "10": "Y después que David hubo contado el pueblo, punzóle su corazón; y dijo David á Jehová: Yo he pecado gravemente por haber hecho esto; mas ahora, oh Jehová, ruégote que quites el pecado de tu siervo, porque yo he obrado muy neciamente.",
      "11": "Y por la mañana, cuando David se hubo levantado, fué palabra de Jehová á Gad profeta, vidente de David, diciendo:",
      "12": "Ve, y di á David: Así ha dicho Jehová: Tres cosas te ofrezco: tú te escogerás una de ellas, la cual yo haga.",
      "13": "Vino pues Gad á David, é intimóle, y díjole: ¿Quieres que te vengan siete años de hambre en tu tierra? ¿ó que huyas tres meses delante de tus enemigos, y que ellos te persigan? ¿o que tres días haya pestilencia en tu tierra? Piensa ahora, y mira qué responderé al que me ha enviado.",
      "14": "Entonces David dijo á Gad: En grande angustia estoy: ruego que caiga en la mano de Jehová, porque sus miseraciones son muchas, y que no caiga yo en manos de hombres.",
      "15": "Y envió Jehová pestilencia á Israel desde la mañana hasta el tiempo señalado: y murieron del pueblo, desde Dan hasta Beer-seba, setenta mil hombres.",
      "16": "Y como el ángel extendió su mano sobre Jerusalem para destruirla, Jehová se arrepintió de aquel mal, y dijo al ángel que destruía el pueblo: Basta ahora; detén tu mano. Entonces el ángel de Jehová estaba junto á la era de Arauna Jebuseo.",
      "17": "Y David dijo á Jehová, cuando vió al ángel que hería al pueblo: Yo pequé, yo hice la maldad: ¿qué hicieron estas ovejas? Ruégote que tu mano se torne contra mí, y contra la casa de mi padre.",
      "18": "Y Gad vino á David aquel día, y díjole: Sube, y haz un altar á Jehová en la era de Arauna Jebuseo.",
      "19": "Y subió David, conforme al dicho de Gad, que Jehová le había mandado.",
      "20": "Y mirando Arauna, vió al rey y á sus siervos que pasaban á él. Saliendo entonces Arauna, inclinóse delante del rey hacia tierra.",
      "21": "Y Arauna dijo: ¿Por qué viene mi señor el rey á su siervo? Y David respondió: Para comprar de ti la era, para edificar altar á Jehová, á fin de que la mortandad cese del pueblo.",
      "22": "Y Arauna dijo á David: Tome y sacrifique mi señor el rey lo que bien le pareciere; he aquí bueyes para el holocausto; y trillos y otros pertrechos de bueyes para leña:",
      "23": "Todo lo da como un rey Arauna al rey. Luego dijo Arauna al rey: Jehová tu Dios te sea propicio.",
      "24": "Y el rey dijo á Arauna: No, sino por precio te lo compraré; porque no ofreceré á Jehová mi Dios holocaustos por nada. Entonces David compró la era y los bueyes por cincuenta siclos de plata.",
      "25": "Y edificó allí David un altar á Jehová, y sacrificó holocaustos y pacíficos; y Jehová se aplacó con la tierra, y cesó la plaga de Israel."
    }
  },
  "1_kings": {
    "1": {
      "1": "COMO el rey David era viejo, y entrado en días, cubríanle de vestidos, mas no se calentaba.",
      "2": "Dijéronle por tanto sus siervos: Busquen á mi señor el rey una moza virgen, para que esté delante del rey, y lo abrigue, y duerma á su lado, y calentará á mi señor el rey.",
      "3": "Y buscaron una moza hermosa por todo el término de Israel, y hallaron á Abisag Sunamita, y trajéronla al rey.",
      "4": "Y la moza era hermosa, la cual calentaba al rey, y le servía: mas el rey nunca la conoció.",
      "5": "Entonces Adonía hijo de Haggith se levantó, diciendo: Yo reinaré. E hízose de carros y gente de á caballo, y cincuenta hombres que corriesen delante de él.",
      "6": "Y su padre nunca lo entristeció en todos sus días con decirle: ¿Por qué haces así? Y también éste era de hermoso parecer; y habíalo engendrado después de Absalom.",
      "7": "Y tenía tratos con Joab hijo de Sarvia, y con Abiathar sacerdote, los cuales ayudaban á Adonía.",
      "8": "Mas Sadoc sacerdote, y Benaía hijo de Joiada, y Nathán profeta, y Semei, y Reihi, y todos los grandes de David, no seguían á Adonía.",
      "9": "Y matando Adonía ovejas y vacas y animales engordados junto á la peña de Zoheleth, que está cerca de la fuente de Rogel, convidó á todos sus hermanos los hijos del rey, y á todos los varones de Judá, siervos del rey:",
      "10": "Mas no convidó á Nathán profeta, ni á Benaía, ni á los grandes, ni á Salomón su hermano.",
      "11": "Y habló Nathán á Bath-sheba madre de Salomón, diciendo: ¿No has oído que reina Adonía hijo de Haggith, sin saberlo David nuestro señor?",
      "12": "Ven pues ahora, y toma mi consejo, para que guardes tu vida, y la vida de tu hijo Salomón.",
      "13": "Ve, y entra al rey David, y dile: Rey señor mío, ¿no has tú jurado á tu sierva, diciendo: Salomón tu hijo reinará después de mí, y él se sentará en mi trono? ¿por qué pues reina Adonía?",
      "14": "Y estando tú aún hablando con el rey, yo entraré tras ti, y acabaré tus razones.",
      "15": "Entonces Bath-sheba entró al rey á la cámara: y el rey era muy viejo; y Abisag Sunamita servía al rey.",
      "16": "Y Bath-sheba se inclinó, é hizo reverencia al rey. Y el rey dijo: ¿Qué tienes?",
      "17": "Y ella le respondió: Señor mío, tú juraste á tu sierva por Jehová tu Dios, diciendo: Salomón tu hijo reinará después de mí, y él se sentará en mi trono;",
      "18": "Y he aquí ahora Adonía reina: y tú, mi señor rey, ahora no lo supiste.",
      "19": "Ha matado bueyes, y animales engordados, y muchas ovejas, y ha convidado á todos los hijos del rey, y á Abiathar sacerdote, y á Joab general del ejército; mas á Salomón tu siervo no ha convidado.",
      "20": "Entre tanto, rey señor mío, los ojos de todo Israel están sobre ti, para que les declares quién se ha de sentar en el trono de mi señor el rey después de él.",
      "21": "De otra suerte acontecerá, cuando mi señor el rey durmiere con sus padres, que yo y mi hijo Salomón seremos tenidos por culpables.",
      "22": "Y estando aún hablando ella con el rey, he aquí Nathán profeta, que vino.",
      "23": "Y dieron aviso al rey, diciendo: He aquí Nathán profeta: el cual como entró al rey, postróse delante del rey inclinando su rostro á tierra.",
      "24": "Y dijo Nathán: Rey señor mío, ¿has tú dicho: Adonía reinará después de mí, y él se sentará en mi trono?",
      "25": "Porque hoy ha descendido, y ha matado bueyes, y animales engordados, y muchas ovejas, y ha convidado á todos los hijos del rey, y á los capitanes del ejército, y también á Abiathar sacerdote; y he aquí, están comiendo y bebiendo delante de él, y han dicho: ­Viva el rey Adonía!",
      "26": "Mas ni á mí tu siervo, ni á Sadoc sacerdote, ni á Benaía hijo de Joiada, ni á Salomón tu siervo, ha convidado.",
      "27": "¿Es este negocio ordenado por mi señor el rey, sin haber declarado á tu siervo quién se había de sentar en el trono de mi señor el rey después de él?",
      "28": "Entonces el rey David respondió, y dijo: Llamadme á Bath-sheba. Y ella entró á la presencia del rey, y púsose delante del rey.",
      "29": "Y el rey juró, diciendo: Vive Jehová, que ha redimido mi alma de toda angustia,",
      "30": "Que como yo te he jurado por Jehová Dios de Israel, diciendo: Tu hijo Salomón reinará después de mí, y él se sentará en mi trono en lugar mío; que así lo haré hoy.",
      "31": "Entonces Bath-sheba se inclinó al rey, su rostro á tierra, y haciendo reverencia al rey, dijo: Viva mi señor el rey David para siempre.",
      "32": "Y el rey David dijo: Llamadme á Sadoc sacerdote, y á Nathán profeta, y á Benaía hijo de Joiada. Y ellos entraron á la presencia del rey.",
      "33": "Y el rey les dijo: Tomad con vosotros los siervos de vuestro señor, y haced subir á Salomón mi hijo en mi mula, y llevadlo á Gihón:",
      "34": "Y allí lo ungirán Sadoc sacerdote y Nathán profeta por rey sobre Israel; y tocaréis trompeta, diciendo: ­Viva el rey Salomón!",
      "35": "Después iréis vosotros detrás de él, y vendrá y se sentará en mi trono, y él reinará por mí; porque á él he ordenado para que sea príncipe sobre Israel y sobre Judá.",
      "36": "Entonces Benaía hijo de Joiada respondió al rey, y dijo: Amén. Así lo diga Jehová, Dios de mi señor el rey.",
      "37": "De la manera que Jehová ha sido con mi señor el rey, así sea con Salomón; y él haga mayor su trono que el trono de mi señor el rey David.",
      "38": "Y descendió Sadoc sacerdote, y Nathán profeta, y Benaía hijo de Joiada, y los Ceretheos y los Peletheos, é hicieron subir á Salomón en la mula del rey David, y lleváronlo á Gihón.",
      "39": "Y tomando Sadoc sacerdote el cuerno del aceite del tabernáculo, ungió á Salomón: y tocaron trompeta, y dijo todo el pueblo: ­Viva el rey Salomón!",
      "40": "Después subió todo el pueblo en pos de él, y cantaba la gente con flautas, y hacían grandes alegrías, que parecía que la tierra se hundía con el clamor de ellos.",
      "41": "Y oyólo Adonía, y todos los convidados que con él estaban, cuando ya habían acabado de comer. Y oyendo Joab el sonido de la trompeta, dijo: ¿Por qué se alborota la ciudad con estruendo?",
      "42": "Estando aún él hablando, he aquí Jonathán hijo de Abiathar sacerdote vino, al cual dijo Adonía: Entra, porque tú eres hombre de esfuerzo, y traerás buenas nuevas.",
      "43": "Y Jonathán respondió, y dijo á Adonía: Ciertamente nuestro señor el rey David ha hecho rey á Salomón:",
      "44": "Y el rey ha enviado con él á Sadoc sacerdote y á Nathán profeta, y á Benaía hijo de Joiada, y también á los Ceretheos y á los Peletheos, los cuales le hicieron subir en la mula del rey;",
      "45": "Y Sadoc sacerdote y Nathán profeta lo han ungido en Gihón por rey: y de allá han subido con alegrías, y la ciudad está llena de estruendo. Este es el alboroto que habéis oído.",
      "46": "Y también Salomón se ha sentado en el trono del reino.",
      "47": "Y aun los siervos del rey han venido á bendecir á nuestro señor el rey David, diciendo: Dios haga bueno el nombre de Salomón más que tu nombre, y haga mayor su trono que el tuyo. Y el rey adoró en la cama.",
      "48": "Y también el rey habló así: Bendito sea Jehová Dios de Israel, que ha dado hoy quien se siente en mi trono, viéndolo mis ojos.",
      "49": "Ellos entonces se estremecieron, y levantáronse todos los convidados que estaban con Adonía, y fuése cada uno por su camino.",
      "50": "Mas Adonía, temiendo de la presencia de Salomón, levantóse y fuése, y cogió los cornijales del altar.",
      "51": "Y fué hecho saber á Salomón, diciendo: He aquí que Adonía tiene miedo del rey Salomón: pues ha cogido los cornijales del altar, diciendo: Júreme hoy el rey Salomón que no matará á cuchillo á su siervo.",
      "52": "Y Salomón dijo: Si él fuere virtuoso, ni uno de sus cabellos caerá en tierra: mas si se hallare mal en él, morirá.",
      "53": "Y envió el rey Salomón, y trajéronlo del altar; y él vino, é inclinóse al rey Salomón. Y Salomón le dijo: Vete á tu casa."
    },
    "2": {
      "1": "Y LLEGARONSE los días de David para morir, y mandó á Salomón su hijo, diciendo:",
      "2": "Yo voy el camino de toda la tierra: esfuérzate, y sé varón.",
      "3": "Guarda la ordenanza de Jehová tu Dios, andando en sus caminos, y observando sus estatutos y mandamientos, y sus derechos y sus testimonios, de la manera que está escrito en la ley de Moisés, para que seas dichoso en todo lo que hicieres, y en todo aquello á que te tornares;",
      "4": "Para que confirme Jehová la palabra que me habló, diciendo: Si tus hijos guardaren su camino, andando delante de mí con verdad, de todo su corazón, y de toda su alma, jamás, dice, faltará á ti varón del trono de Israel.",
      "5": "Y ya sabes tú lo que me ha hecho Joab hijo de Sarvia, lo que hizo á dos generales del ejército de Israel, á Abner hijo de Ner, y á Amasa hijo de Jether, los cuales él mató, derramando en paz la sangre de guerra, y poniendo la sangre de guerra en su talabarte que tenía sobre sus lomos, y en sus zapatos que tenía en sus pies.",
      "6": "Tú pues harás conforme á tu sabiduría; no dejarás descender sus canas á la huesa en paz.",
      "7": "Mas á los hijos de Barzillai Galaadita harás misericordia, que sean de los convidados á tu mesa; porque ellos vinieron así á mí, cuando iba huyendo de Absalom tu hermano.",
      "8": "También tienes contigo á Semei hijo de Gera, hijo de Benjamín, de Bahurim, el cual me maldijo con una maldición fuerte el día que yo iba á Mahanaim. Mas él mismo descendió á recibirme al Jordán, y yo le juré por Jehová, diciendo: Yo no te mataré á cuchillo.",
      "9": "Empero ahora no lo absolverás: que hombre sabio eres, y sabes cómo te has de haber con él: y harás descender sus canas con sangre á la sepultura.",
      "10": "Y David durmió con sus padres, y fué sepultado en la ciudad de David.",
      "11": "Los días que reinó David sobre Israel fueron cuarenta años: siete años reinó en Hebrón, y treinta y tres años reinó en Jerusalem.",
      "12": "Y se sentó Salomón en el trono de David su padre, y fué su reino firme en gran manera.",
      "13": "Entonces Adonía hijo de Haggith vino á Bath-sheba madre de Salomón; y ella dijo: ¿Es tu venida de paz? Y él respondió: Sí, de paz.",
      "14": "En seguida dijo: Una palabra tengo que decirte. Y ella dijo: Di.",
      "15": "Y él dijo: Tú sabes que el reino era mío, y que todo Israel había puesto en mí su rostro, para que yo reinara: mas el reino fué traspasado, y vino á mi hermano; porque por Jehová era suyo.",
      "16": "Y ahora yo te hago una petición: no me hagas volver mi rostro. Y ella le dijo: Habla.",
      "17": "El entonces dijo: Yo te ruego que hables al rey Salomón, (porque él no te hará volver tu rostro,) para que me dé á Abisag Sunamita por mujer.",
      "18": "Y Bath-sheba dijo: Bien; yo hablaré por ti al rey.",
      "19": "Y vino Bath-sheba al rey Salomón para hablarle por Adonía. Y el rey se levantó á recibirla, é inclinóse á ella, y volvió á sentarse en su trono, é hizo poner una silla á la madre del rey, la cual se sentó á su diestra.",
      "20": "Y ella dijo: Una pequeña petición pretendo de ti; no me hagas volver mi rostro. Y el rey le dijo: Pide, madre mía, que yo no te haré volver el rostro.",
      "21": "Y ella dijo: Dése Abisag Sunamita por mujer á tu hermano Adonía.",
      "22": "Y el rey Salomón respondió, y dijo á su madre: ¿Por qué pides á Abisag Sunamita para Adonía? Demanda también para él el reino, porque él es mi hermano mayor; y tiene también á Abiathar sacerdote, y á Joab hijo de Sarvia.",
      "23": "Y el rey Salomón juró por Jehová, diciendo: Así me haga Dios y así me añada, que contra su vida ha hablado Adonía esta palabra.",
      "24": "Ahora pues, vive Jehová, que me ha confirmado y me ha puesto sobre el trono de David mi padre, y que me ha hecho casa, como me había dicho, que Adonía morirá hoy.",
      "25": "Entonces el rey Salomón envió por mano de Benaía hijo de Joiada, el cual dió sobre él, y murió.",
      "26": "Y á Abiathar sacerdote dijo el rey: Vete á Anathoth á tus heredades, que tú eres digno de muerte; mas no te mataré hoy, por cuanto has llevado el arca del Señor Jehová delante de David mi padre, y además has sido trabajado en todas las cosas en que fué trabajado mi padre.",
      "27": "Así echó Salomón á Abiathar del sacerdocio de Jehová, para que se cumpliese la palabra de Jehová que había dicho sobre la casa de Eli en Silo.",
      "28": "Y vino la noticia hasta Joab: porque también Joab se había adherido á Adonía, si bien no se había adherido á Absalom. Y huyó Joab al tabernáculo de Jehová, y asióse á los cornijales del altar.",
      "29": "Y fué hecho saber á Salomón que Joab había huído al tabernáculo de Jehová, y que estaba junto al altar. Entonces envió Salomón á Benaía hijo de Joiada, diciendo: Ve, y da sobre él.",
      "30": "Y entró Benaía al tabernáculo de Jehová, y díjole: El rey ha dicho que salgas. Y él dijo: No, sino aquí moriré. Y Benaía volvió con esta respuesta al rey, diciendo: Así habló Joab, y así me respondió.",
      "31": "Y el rey le dijo: Haz como él ha dicho; mátale y entiérralo, y quita de mí y de la casa de mi padre la sangre que Joab ha derramado injustamente.",
      "32": "Y Jehová hará tornar su sangre sobre su cabeza: que él ha muerto dos varones más justos y mejores que él, á los cuales mató á cuchillo sin que mi padre David supiese nada: á Abner hijo de Ner, general del ejército de Israel, y á Amasa hijo de Jether, general de ejército de Judá.",
      "33": "La sangre pues de ellos recaerá sobre la cabeza de Joab, y sobre la cabeza de su simiente para siempre: mas sobre David y sobre su simiente, y sobre su casa y sobre su trono, habrá perpetuamente paz de parte de Jehová.",
      "34": "Entonces Benaía hijo de Joiada subió, y dió sobre él, y matólo; y fué sepultado en su casa en el desierto.",
      "35": "Y el rey puso en su lugar á Benaía hijo de Joiada sobre el ejército: y á Sadoc puso el rey por sacerdote en lugar de Abiathar.",
      "36": "Después envió el rey, é hizo venir á Semei, y díjole: Edifícate una casa en Jerusalem, y mora ahí, y no salgas de allá á una parte ni á otra;",
      "37": "Porque sabe de cierto que el día que salieres, y pasares el torrente de Cedrón, sin duda morirás, y tu sangre será sobre tu cabeza.",
      "38": "Y Semei dijo al rey: La palabra es buena; como el rey mi señor ha dicho, así lo hará tu siervo. Y habitó Semei en Jerusalem muchos días.",
      "39": "Pero pasados tres años, aconteció que se le huyeron á Semei dos siervos á Achîs, hijo de Maachâ, rey de Gath. Y dieron aviso á Semei, diciendo: He aquí que tus siervos están en Gath.",
      "40": "Levantóse entonces Semei, y enalbardó su asno, y fué á Gath, á Achîs, á procurar sus siervos. Fué pues Semei, y volvió sus siervos de Gath.",
      "41": "Díjose luego á Salomón como Semei había ido de Jerusalem hasta Gath, y que había vuelto.",
      "42": "Entonces el rey envió, é hizo venir á Semei, y díjole: ¿No te conjuré yo por Jehová, y te protesté, diciendo: El día que salieres, y fueres acá ó acullá, sabe de cierto que has de morir? Y tú me dijiste: La palabra es buena, yo la obedezco.",
      "43": "¿Por qué pues no guardaste el juramento de Jehová, y el mandamiento que yo te impuse?",
      "44": "Dijo además el rey á Semei: Tú sabes todo el mal, el cual tu corazón bien sabe, que cometiste contra mi padre David; Jehová pues, ha tornado el mal sobre tu cabeza.",
      "45": "Y el rey Salomón será bendito, y el trono de David será firme perpetuamente delante de Jehová.",
      "46": "Entonces el rey mandó á Benaía hijo de Joiada, el cual salió é hirióle; y murió. Y el reino fué confirmado en la mano de Salomón."
    },
    "3": {
      "1": "Y SALOMON hizo parentesco con Faraón rey de Egipto, porque tomó la hija de Faraón, y trájola á la ciudad de David, entre tanto que acababa de edificar su casa, y la casa de Jehová, y los muros de Jerusalem alrededor.",
      "2": "Hasta entonces el pueblo sacrificaba en los altos; porque no había casa edificada al nombre de Jehová hasta aquellos tiempos.",
      "3": "Mas Salomón amó á Jehová, andando en los estatutos de su padre David: solamente sacrificaba y quemaba perfumes en los altos.",
      "4": "E iba el rey á Gabaón, porque aquél era el alto principal, y sacrificaba allí, mil holocaustos sacrificaba Salomón sobre aquel altar.",
      "5": "Y aparecióse Jehová á Salomón en Gabaón una noche en sueños, y díjo le Dios: Pide lo que quisieres que yo te dé.",
      "6": "Y Salomón dijo: Tú hiciste gran misericordia á tu siervo David mi padre, según que él anduvo delante de ti en verdad, en justicia, y con rectitud de corazón para contigo: y tú le has guardado esta tu grande misericordia, que le diste hijo que se sentase en su trono, como sucede en este día.",
      "7": "Ahora pues, Jehová Dios mío, tú has puesto á mí tu siervo por rey en lugar de David mi padre: y yo soy mozo pequeño, que no sé cómo entrar ni salir.",
      "8": "Y tu siervo está en medio de tu pueblo al cual tú escogiste; un pueblo grande, que no se puede contar ni numerar por su multitud.",
      "9": "Da pues á tu siervo corazón dócil para juzgar á tu pueblo, para discernir entre lo bueno y lo malo: porque ¿quién podrá gobernar este tu pueblo tan grande?",
      "10": "Y agradó delante de Adonai que Salomón pidiese esto.",
      "11": "Y díjole Dios: Porque has demandado esto, y no pediste para ti muchos días, ni pediste para ti riquezas, ni pediste la vida de tus enemigos, mas demandaste para ti inteligencia para oir juicio;",
      "12": "He aquí lo he hecho conforme á tus palabras: he aquí que te he dado corazón sabio y entendido, tanto que no haya habido antes de ti otro como tú, ni después de ti se levantará otro como tú.",
      "13": "Y aun también te he dado las cosas que no pediste, riquezas y gloria: tal, que entre los reyes ninguno haya como tú en todos tus días.",
      "14": "Y si anduvieres en mis caminos, guardando mis estatutos y mis mandamientos, como anduvo David tu padre, yo alargaré tus días.",
      "15": "Y como Salomón despertó, vió que era sueño: y vino á Jerusalem, y presentóse delante del arca del pacto de Jehová, y sacrificó holocaustos, é hizo pacíficos; hizo también banquete á todos sus siervos.",
      "16": "En aquella sazón vinieron dos mujeres rameras al rey, y presentáronse delante de él.",
      "17": "Y dijo la una mujer: ­Ah, señor mío! yo y esta mujer morábamos en una misma casa, y yo parí estando con ella en la casa.",
      "18": "Y aconteció al tercer día después que yo parí, que ésta parió también, y morábamos nosotras juntas; ninguno de fuera estaba en casa, sino nosotras dos en la casa.",
      "19": "Y una noche el hijo de esta mujer murió, porque ella se acostó sobre él.",
      "20": "Y levantóse á media noche, y tomó á mi hijo de junto á mí, estando yo tu sierva durmiendo, y púsolo á su lado, y púsome á mi lado su hijo muerto.",
      "21": "Y como yo me levanté por la mañana para dar el pecho á mi hijo, he aquí que estaba muerto: mas observéle por la mañana, y vi que no era mi hijo, que yo había parido.",
      "22": "Entonces la otra mujer dijo: No; mi hijo es el que vive, y tu hijo es el muerto. Y la otra volvió á decir: No; tu hijo es el muerto, y mi hijo es el que vive. Así hablaban delante del rey.",
      "23": "El rey entonces dijo: Esta dice: Mi hijo es el que vive, y tu hijo es el muerto: y la otra dice: No, mas el tuyo es el muerto, y mi hijo es el que vive.",
      "24": "Y dijo el rey: Traedme un cuchillo. Y trajeron al rey un cuchillo.",
      "25": "En seguida el rey dijo: Partid por medio el niño vivo, y dad la mitad á la una, y la otra mitad á la otra.",
      "26": "Entonces la mujer cuyo era el hijo vivo, habló al rey (porque sus entrañas se le conmovieron por su hijo), y dijo: ­Ah, señor mío! dad á ésta el niño vivo, y no lo matéis. Mas la otra dijo: Ni á mí ni á ti; partidlo.",
      "27": "Entonces el rey respondió, y dijo: Dad á aquélla el hijo vivo, y no lo matéis: ella es su madre.",
      "28": "Y todo Israel oyó aquel juicio que había dado el rey: y temieron al rey, porque vieron que había en él sabiduría de Dios para juzgar."
    },
    "4": {
      "1": "FUÉ pues el rey Salomón rey sobre todo Israel.",
      "2": "Y estos fueron los príncipes que tuvo: Azarías hijo de Sadoc, sacerdote;",
      "3": "Elioreph y Ahía, hijos de Sisa, escribas; Josaphat hijo de Ahilud, canciller;",
      "4": "Benaía hijo de Joiada era sobre el ejército; y Sadoc y Abiathar eran los sacerdotes;",
      "5": "Azaría hijo de Nathán era sobre los gobernadores; Zabud hijo de Nathán era principal oficial, amigo del rey;",
      "6": "Y Ahisar era mayordomo; y Adoniram hijo de Abda era sobre el tributo.",
      "7": "Y tenía Salomón doce gobernadores sobre todo Israel, los cuales mantenían al rey y á su casa. Cada uno de ellos estaba obligado á abastecer por un mes en el año.",
      "8": "Y estos son los nombres de ellos: el hijo de Hur en el monte de Ephraim;",
      "9": "El hijo de Decar, en Maccas, y en Saalbim, y en Beth-semes, y en Elón, y en Beth-hanan;",
      "10": "El hijo de Hesed, en Aruboth; éste tenía también á Sochô y toda la tierra de Ephet.",
      "11": "El hijo de Abinadab, en todos los términos de Dor: éste tenía por mujer á Thaphat hija de Salomón;",
      "12": "Baana hijo de Ahilud, en Taanach y Megiddo, y en toda Beth-san, que es cerca de Zaretán, por bajo de Jezreel, desde Beth-san hasta Abel-mehola, y hasta la otra parte de Jocmeam;",
      "13": "El hijo de Geber, en Ramoth de Galaad; éste tenía también las ciudades de Jair hijo de Manasés, las cuales estaban en Galaad; tenía también la provincia de Argob, que era en Basán, sesenta grandes ciudades con muro y cerraduras de bronce;",
      "14": "Ahinadab hijo de Iddo, en Mahanaim;",
      "15": "Ahimaas en Nephtalí; éste tomó también por mujer á Basemath hija de Salomón.",
      "16": "Baana hijo de Husai, en Aser y en Aloth;",
      "17": "Josaphat hijo de Pharua, en Issachâr;",
      "18": "Semei hijo de Ela, en Benjamín;",
      "19": "Geber hijo de Uri, en la tierra de Galaad, la tierra de Sehón rey de los Amorrheos, y de Og rey de Basán; éste era el único gobernador en aquella tierra.",
      "20": "Judá é Israel eran muchos, como la arena que está junto á la mar en multitud, comiendo y bebiendo y alegrándose.",
      "21": "Y Salomón señoreaba sobre todos los reinos, desde el río de la tierra de los Filisteos hasta el término de Egipto: y traían presentes, y sirvieron á Salomón todos los días que vivió.",
      "22": "Y la despensa de Salomón era cada día treinta coros de flor de harina, y sesenta coros de harina.",
      "23": "Diez bueyes engordados, y veinte bueyes de pasto, y cien ovejas; sin los ciervos, cabras, búfalos, y aves engordadas.",
      "24": "Porque él señoreaba en toda la región que estaba de la otra parte del río, desde Tiphsa hasta Gaza, sobre todos los reyes de la otra parte del río; y tuvo paz por todos lados en derredor suyo.",
      "25": "Y Judá é Israel vivían seguros, cada uno debajo de su parra y debajo de su higuera, desde Dan hasta Beer-seba, todos los días de Salomón.",
      "26": "Tenía además de esto Salomón cuarenta mil caballos en sus caballerizas para sus carros, y doce mil jinetes.",
      "27": "Y estos gobernadores mantenían al rey Salomón, y á todos los que á la mesa del rey Salomón venían, cada uno un mes; y hacían que nada faltase.",
      "28": "Hacían también traer cebada y paja para los caballos y para las bestias de carga, al lugar donde él estaba, cada uno conforme al cargo que tenía.",
      "29": "Y dió Dios á Salomón sabiduría, y prudencia muy grande, y anchura de corazón como la arena que está á la orilla del mar.",
      "30": "Que fué mayor la sabiduría de Salomón que la de todos los orientales, y que toda la sabiduría de los Egipcios.",
      "31": "Y aun fué más sabio que todos los hombres; más que Ethán Ezrahita, y que Emán y Calchôl y Darda, hijos de Mahol: y fué nombrado entre todas las naciones de alrededor.",
      "32": "Y propuso tres mil parábolas; y sus versos fueron mil y cinco.",
      "33": "También disertó de los árboles, desde el cedro del Líbano hasta el hisopo que nace en la pared. Asimismo disertó de los animales, de las aves, de los reptiles, y de los peces.",
      "34": "Y venían de todos los pueblos á oir la sabiduría de Salomón, y de todos los reyes de la tierra, donde había llegado la fama de su sabiduría."
    },
    "5": {
      "1": "HIRAM rey de Tiro envió también sus siervos á Salomón, luego que oyó que lo habían ungido por rey en lugar de su padre: porque Hiram había siempre amado á David.",
      "2": "Entonces Salomón envió á decir á Hiram:",
      "3": "Tú sabes como mi padre David no pudo edificar casa al nombre de Jehová su Dios, por las guerras que le cercaron, hasta que Jehová puso sus enemigos bajo las plantas de sus pies.",
      "4": "Ahora Jehová mi Dios me ha dado reposo por todas partes; que ni hay adversarios, ni mal encuentro.",
      "5": "Yo por tanto he determinado ahora edificar casa al nombre de Jehová mi Dios, como Jehová lo habló á David mi padre, diciendo: Tu hijo, que yo pondré en lugar tuyo en tu trono, él edificará casa á mi nombre.",
      "6": "Manda pues ahora que me corten cedros del Líbano; y mis siervos estarán con los tuyos, y yo te daré por tus siervos el salario que tú dijeres: porque tú sabes bien que ninguno hay entre nosotros que sepa labrar la madera como los Sidonios.",
      "7": "Y como Hiram oyó las palabras de Salomón, holgóse en gran manera, y dijo: Bendito sea hoy Jehová, que dió hijo sabio á David sobre este pueblo tan grande.",
      "8": "Y envió Hiram á decir á Salomón: He oído lo que me mandaste á decir: yo haré todo lo que te pluguiere acerca de la madera de cedro, y la madera de haya.",
      "9": "Mis siervos la llevarán desde el Líbano á la mar; y yo la pondré en balsas por la mar hasta el lugar que tú me señalares, y allí se desatará, y tú la tomarás: y tú harás mi voluntad en dar de comer á mi familia.",
      "10": "Dió pues Hiram á Salomón madera de cedro y madera de haya todo lo que quiso.",
      "11": "Y Salomón daba á Hiram veinte mil coros de trigo para el sustento de su familia, y veinte coros de aceite limpio: esto daba Salomón á Hiram cada un año.",
      "12": "Dió pues Jehová á Salomón sabiduría como le había dicho: y hubo paz entre Hiram y Salomón, é hicieron alianza entre ambos.",
      "13": "Y el rey Salomón impuso tributo á todo Israel, y el tributo fué de treinta mil hombres:",
      "14": "Los cuales enviaba al Líbano de diez mil en diez mil, cada mes por su turno, viniendo así á estar un mes en el Líbano, y dos meses en sus casas: y Adoniram estaba sobre aquel tributo.",
      "15": "Tenía también Salomón setenta mil que llevaban las cargas, y ochenta mil cortadores en el monte;",
      "16": "Sin los principales oficiales de Salomón que estaban sobre la obra, tres mil y trescientos, los cuales tenían cargo del pueblo que hacía la obra.",
      "17": "Y mandó el rey que trajesen grandes piedras, piedras de precio, para los cimientos de la casa, y piedras labradas.",
      "18": "Y los albañiles de Salomón y los de Hiram, y los aparejadores, cortaron y aparejaron la madera y la cantería para labrar la casa."
    },
    "6": {
      "1": "Y FUÉ en el año cuatrocientos ochenta después que los hijos de Israel salieron de Egipto, en el cuarto año del principio del reino de Salomón sobre Israel, en el mes de Ziph, que es el mes segundo, que él comenzó á edificar la casa de Jehová.",
      "2": "La casa que el rey Salomón edificó á Jehová, tuvo sesenta codos de largo y veinte de ancho, y treinta codos de alto.",
      "3": "Y el pórtico delante del templo de la casa, de veinte codos de largo, según la anchura de la casa, y su ancho era de diez codos delante de la casa.",
      "4": "E hizo á la casa ventanas anchas por de dentro, y estrechas por de fuera.",
      "5": "Edificó también junto al muro de la casa aposentos alrededor, contra las paredes de la casa en derredor del templo y del oráculo: é hizo cámaras alrededor.",
      "6": "El aposento de abajo era de cinco codos de ancho, y el de en medio de seis codos de ancho, y el tercero de siete codos de ancho: porque por de fuera había hecho disminuciones á la casa en derredor, para no trabar las vigas de las paredes de la casa.",
      "7": "Y la casa cuando se edificó, fabricáronla de piedras que traían ya acabadas; de tal manera que cuando la edificaban, ni martillos ni hachas se oyeron en la casa, ni ningún otro instrumento de hierro.",
      "8": "La puerta del aposento de en medio estaba al lado derecho de la casa: y subíase por un caracol al de en medio, y del aposento de en medio al tercero.",
      "9": "Labró pues la casa, y acabóla; y cubrió la casa con artesonados de cedro.",
      "10": "Y edificó asimismo el aposento en derredor de toda la casa, de altura de cinco codos, el cual se apoyaba en la casa con maderas de cedro.",
      "11": "Y fué palabra de Jehová á Salomón, diciendo:",
      "12": "Esta casa que tú edificas, si anduvieres en mis estatutos, é hicieres mis derechos, y guardares todos mis mandamientos andando en ellos, yo tendré firme contigo mi palabra que hablé á David tu padre;",
      "13": "Y habitaré en medio de los hijos de Israel, y no dejaré á mi pueblo Israel.",
      "14": "Así que, Salomón labró la casa, y acabóla.",
      "15": "Y aparejó las paredes de la casa por de dentro con tablas de cedro, vistiéndola de madera por dentro, desde el solado de la casa hasta las paredes de la techumbre: cubrió también el pavimento con madera de haya.",
      "16": "Asimismo hizo al cabo de la casa un edificio de veinte codos de tablas de cedro, desde el solado hasta lo más alto; y fabricóse en la casa un oráculo, que es el lugar santísimo.",
      "17": "Y la casa, á saber, el templo de dentro, tenía cuarenta codos.",
      "18": "Y la casa estaba cubierta de cedro por de dentro, y tenía entalladuras de calabazas silvestres y de botones de flores. Todo era cedro; ninguna piedra se veía.",
      "19": "Y adornó el oráculo por de dentro en medio de la casa, para poner allí el arca del pacto de Jehová.",
      "20": "Y el oráculo estaba en la parte de adentro, el cual tenía veinte codos de largo, y otros veinte de ancho, y otros veinte de altura; y vistiólo de oro purísimo: asimismo cubrió el altar de cedro.",
      "21": "De suerte que vistió Salomón de oro puro la casa por de dentro, y cerró la entrada del oráculo con cadenas de oro, y vistiólo de oro.",
      "22": "Cubrió pues de oro toda la casa hasta el cabo; y asimismo vistió de oro todo el altar que estaba delante del oráculo.",
      "23": "Hizo también en el oráculo dos querubines de madera de oliva, cada uno de altura de diez codos.",
      "24": "La una ala del querubín tenía cinco codos, y la otra ala del querubín otros cinco codos: así que había diez codos desde la punta de la una ala hasta la punta de la otra.",
      "25": "Asimismo el otro querubín tenía diez codos; porque ambos querubines eran de un tamaño y de una hechura.",
      "26": "La altura del uno era de diez codos, y asimismo el otro.",
      "27": "Y puso estos querubines dentro de la casa de adentro: los cuales querubines extendían sus alas, de modo que el ala del uno tocaba á la pared, y el ala del otro querubín tocaba á la otra pared, y las otras dos alas se tocaban la una á la otra en la mitad de la casa.",
      "28": "Y vistió de oro los querubines.",
      "29": "Y esculpió todas las paredes de la casa alrededor de diversas figuras, de querubines, de palmas, y de botones de flores, por de dentro y por de fuera.",
      "30": "Y cubrió de oro el piso de la casa, de dentro y de fuera.",
      "31": "Y á la entrada del oráculo hizo puertas de madera de oliva; y el umbral y los postes eran de cinco esquinas.",
      "32": "Las dos puertas eran de madera de oliva; y entalló en ellas figuras de querubines y de palmas y de botones de flores, y cubriólas de oro: cubrió también de oro los querubines y las palmas.",
      "33": "Igualmente hizo á la puerta del templo postes de madera de oliva cuadrados.",
      "34": "Pero las dos puertas eran de madera de haya; y los dos lados de la una puerta eran redondos, y los otros dos lados de la otra puerta también redondos.",
      "35": "Y entalló en ellas querubines y palmas y botones de flores, y cubriólas de oro ajustado á las entalladuras.",
      "36": "Y edificó el atrio interior de tres órdenes de piedras labradas, y de un orden de vigas de cedro.",
      "37": "En el cuarto año, en el mes de Ziph, se echaron los cimientos de la casa de Jehová:",
      "38": "Y en el undécimo año, en el mes de Bul, que es el mes octavo, fué acabada la casa con todas sus pertenencias, y con todo lo necesario. Edificóla pues, en siete años."
    },
    "7": {
      "1": "DESPUÉS edificó Salomón su propia casa en trece años, y acabóla toda.",
      "2": "Asimismo edificó la casa del bosque del Líbano, la cual tenía cinco codos de longitud, y cincuenta codos de anchura, y treinta codos de altura, sobre cuatro órdenes de columnas de cedro, con vigas de cedro sobre las columnas.",
      "3": "Y estaba cubierta de tablas de cedro arriba sobre las vigas, que se apoyaban en cuarenta y cinco columnas: cada hilera tenía quince columnas.",
      "4": "Y había tres órdenes de ventanas, una ventana contra la otra en tres órdenes.",
      "5": "Y todas la puertas y postes eran cuadrados: y las unas ventanas estaban frente á las otras en tres órdenes.",
      "6": "También hizo un pórtico de columnas, que tenía de largo cincuenta codos, y treinta codos de ancho; y aqueste pórtico estaba delante de aquellas otras, con sus columnas y maderos correspondientes.",
      "7": "Hizo asimismo el pórtico del trono en que había de juzgar, el pórtico del juicio, y vistiólo de cedro de suelo á suelo.",
      "8": "Y en la casa en que él moraba, había otro atrio dentro del pórtico, de obra semejante á esta. Edificó también Salomón una casa para la hija de Faraón, que había tomado por mujer, de la misma obra de aquel pórtico.",
      "9": "Todas aquellas obras fueron de piedras de precio, cortadas y aserradas con sierras según las medidas, así por de dentro como por de fuera, desde el cimiento hasta los remates, y asimismo por de fuera hasta el gran atrio.",
      "10": "El cimiento era de piedras de precio, de piedras grandes, de piedras de diez codos, y de piedras de ocho codos.",
      "11": "De allí arriba eran también piedras de precio, labradas conforme á sus medidas, y obra de cedro.",
      "12": "Y en el gran atrio alrededor había tres órdenes de piedras labradas, y un orden de vigas de cedro: y así el atrio interior de la casa de Jehová, y el atrio de la casa.",
      "13": "Y envió el rey Salomón, é hizo venir de Tiro á Hiram,",
      "14": "Hijo de una viuda de la tribu de Nephtalí, y su padre había sido de Tiro: trabajaba él en bronce, lleno de sabiduría y de inteligencia y saber en toda obra de metal. Este pues vino al rey Salomón, é hizo toda su obra.",
      "15": "Y vació dos columnas de bronce, la altura de cada cual era de diez y ocho codos: y rodeaba á una y á otra columna un hilo de doce codos.",
      "16": "Hizo también dos capiteles de fundición de bronce, para que fuesen puestos sobre las cabezas de las columnas: la altura de un capitel era de cinco codos, y la del otro capitel de cinco codos.",
      "17": "Había trenzas á manera de red, y unas cintas á manera de cadenas, para los capiteles que se habían de poner sobre las cabezas de las columnas: siete para cada capitel.",
      "18": "Y cuando hubo hecho las columnas, hizo también dos órdenes de granadas alrededor en el un enredado, para cubrir los capiteles que estaban en las cabezas de las columnas con las granadas: y de la misma forma hizo en el otro capitel.",
      "19": "Los capiteles que estaban sobre las columnas en el pórtico, tenían labor de flores por cuatro codos.",
      "20": "Tenían también los capiteles de sobre las dos columnas, doscientas granadas en dos órdenes alrededor en cada capitel, encima del vientre del capitel, el cual vientre estaba delante del enredado.",
      "21": "Estas columnas erigió en el pórtico del templo: y cuando hubo alzado la columna de la mano derecha, púsole por nombre Jachîn: y alzando la columna de la mano izquierda, llamó su nombre Boaz.",
      "22": "Y puso en las cabezas de las columnas labor en forma de azucenas; y así se acabó la obra de las columnas.",
      "23": "Hizo asimismo un mar de fundición, de diez codos del un lado al otro, perfectamente redondo: su altura era de cinco codos, y ceñíalo alrededor un cordón de treinta codos.",
      "24": "Y cercaban aquel mar por debajo de su labio en derredor unas bolas como calabazas, diez en cada codo, que ceñían el mar alrededor en dos órdenes, las cuales habían sido fundidas cuando él fué fundido.",
      "25": "Y estaba asentado sobre doce bueyes: tres miraban al norte, y tres miraban al poniente, y tres miraban al mediodía, y tres miraban al oriente; sobre éstos se apoyaba el mar, y las traseras de ellos estaban hacia la parte de adentro.",
      "26": "El grueso del mar era de un palmo, y su labio era labrado como el labio de un cáliz, ó de flor de lis: y cabían en él dos mil batos.",
      "27": "Hizo también diez basas de bronce, siendo la longitud de cada basa de cuatro codos, y la anchura de cuatro codos, y de tres codos la altura.",
      "28": "La obra de las basas era esta: tenían unas cintas, las cuales estaban entre molduras:",
      "29": "Y sobre aquellas cintas que estaban entre las molduras, figuras de leones, y de bueyes, y de querubines; y sobre las molduras de la basa, así encima como debajo de los leones y de los bueyes, había unas añadiduras de bajo relieve.",
      "30": "Cada basa tenía cuatro ruedas de bronce con mesas de bronce; y en sus cuatro esquinas había unos hombrillos, los cuales nacían de fundición á cada un lado de aquellas añadiduras, para estar debajo de la fuente.",
      "31": "Y la boca del pie de la fuente entraba un codo en el remate que salía para arriba de la basa; y era su boca redonda, de la hechura del mismo remate, y éste de codo y medio. Había también sobre la boca entalladuras con sus cintas, las cuales eran cuadradas, no redondas.",
      "32": "Las cuatro ruedas estaban debajo de las cintas, y los ejes de las ruedas nacían en la misma basa. La altura de cada rueda era de un codo y medio.",
      "33": "Y la hechura de las ruedas era como la hechura de las ruedas de un carro: sus ejes, sus rayos, y sus cubos, y sus cinchos, todo era de fundición.",
      "34": "Asimismo los cuatro hombrillos á las cuatro esquinas de cada basa: y los hombrillos eran de la misma basa.",
      "35": "Y en lo alto de la basa había medio codo de altura redondo por todas partes: y encima de la basa sus molduras y cintas, las cuales eran de ella misma.",
      "36": "E hizo en las tablas de las molduras, y en las cintas, entalladuras de querubines, y de leones, y de palmas, con proporción en el espacio de cada una, y alrededor otros adornos.",
      "37": "De esta forma hizo diez basas fundidas de una misma manera, de una misma medida, y de una misma entalladura.",
      "38": "Hizo también diez fuentes de bronce: cada fuente contenía cuarenta batos, y cada una era de cuatro codos; y asentó una fuente sobre cada una de las diez basas.",
      "39": "Y puso las cinco basas á la mano derecha de la casa, y las otras cinco á la mano izquierda: y asentó el mar al lado derecho de la casa, al oriente, hacia el mediodía.",
      "40": "Asimismo hizo Hiram fuentes, y tenazas, y cuencos. Así acabó toda la obra que hizo á Salomón para la casa de Jehová:",
      "41": "Es á saber, dos columnas, y los vasos redondos de los capiteles que estaban en lo alto de las dos columnas; y dos redes que cubrían los dos vasos redondos de los capiteles que estaban sobre la cabeza de las columnas;",
      "42": "Y cuatrocientas granadas para las dos redes, dos órdenes de granadas en cada red, para cubrir los dos vasos redondos que estaban sobre las cabezas de las columnas;",
      "43": "Y las diez basas, y las diez fuentes sobre las basas;",
      "44": "Y un mar, y doce bueyes debajo del mar;",
      "45": "Y calderos, y paletas, y cuencos; y todos los vasos que Hiram hizo al rey Salomón, para la casa de Jehová de metal acicalado.",
      "46": "Todo lo hizo fundir el rey en la llanura del Jordán, en tierra arcillosa, entre Succoth y Sarthán.",
      "47": "Y dejó Salomón sin inquirir el peso del metal de todos los vasos, por la grande multitud de ellos.",
      "48": "Entonces hizo Salomón todos los vasos que pertenecían á la casa de Jehová: un altar de oro, y una mesa sobre la cual estaban los panes de la proposición, también de oro;",
      "49": "Y cinco candeleros de oro purísimo á la mano derecha, y otros cinco á la izquierda, delante del oráculo; con las flores, y las lámparas, y despabiladeras de oro;",
      "50": "Asimismo los cántaros, vasos, tazas, cucharillas, é incensarios, de oro purísimo; también de oro los quiciales de las puertas de la casa de adentro, del lugar santísimo, y los de las puertas del templo.",
      "51": "Así se acabó toda la obra que dispuso hacer el rey Salomón para la casa de Jehová. Y metió Salomón lo que David su padre había dedicado, es á saber, plata, y oro, y vasos, y púsolo todo en guarda en las tesorerías de la casa de Jehová."
    }
  }
};

