
	
export const bib_verses = {
  "deuteronomy": {
    "3": {
      "1": "Y VOLVIMOS, y subimos camino de Basán, y saliónos al encuentro Og rey de Basán para pelear, él y todo su pueblo, en Edrei.",
      "2": "Y díjome Jehová: No tengas temor de él, porque en tu mano he entregado á él y á todo su pueblo, y su tierra: y harás con él como hiciste con Sehón rey Amorrheo, que habitaba en Hesbón.",
      "3": "Y Jehová nuestro Dios entregó también en nuestra mano á Og rey de Basán, y á todo su pueblo, al cual herimos hasta no quedar de él ninguno.",
      "4": "Y tomamos entonces todas sus ciudades; no quedó ciudad que no les tomásemos: sesenta ciudades, toda la tierra de Argob, del reino de Og en Basán.",
      "5": "Todas éstas eran ciudades fortalecidas con alto muro, con puertas y barras; sin otras muy muchas ciudades sin muro.",
      "6": "Y destruímoslas, como hicimos á Sehón rey de Hesbón, destruyendo en toda ciudad hombres, mujeres, y niños.",
      "7": "Y tomamos para nosotros todas las bestias, y los despojos de las ciudades.",
      "8": "También tomamos en aquel tiempo de mano de dos reyes Amorrheos que estaban de esta parte del Jordán, la tierra desde el arroyo de Arnón hasta el monte de Hermón:",
      "9": "(Los Sidonios llaman á Hermón Sirión; y los Amorrheos, Senir:)",
      "10": "Todas las ciudades de la llanura, y todo Galaad, y todo Basán hasta Salchâ y Edrei, ciudades del reino de Og en Basán.",
      "11": "Porque sólo Og rey de Basán había quedado de los gigantes que quedaron. He aquí su cama, una cama de hierro, ¿no está en Rabbath de los hijos de Ammón?; la longitud de ella de nueve codos, y su anchura de cuatro codos, al codo de un hombre.",
      "12": "Y esta tierra que heredamos entonces desde Aroer, que está al arroyo de Arnón, y la mitad del monte de Galaad con sus ciudades, dí á los Rubenitas y á los Gaditas:",
      "13": "Y el resto de Galaad, y todo Basán, del reino de Og, dí lo á la media tribu de Manasés; toda la tierra de Argob, todo Basán, que se llamaba la tierra de los gigantes.",
      "14": "Jair hijo de Manasés tomó toda la tierra de Argob hasta el término de Gessuri y Machâti; y llamóla de su nombre Basán-havoth-jair, hasta hoy.",
      "15": "Y á Machîr dí á Galaad.",
      "16": "Y á los Rubenitas y Gaditas dí de Galaad hasta el arroyo de Arnón, el medio del arroyo por término; hasta el arroyo de Jaboc, término de los hijos de Ammón:",
      "17": "Asimismo la campiña, y el Jordán, y el término, desde Cinereth hasta la mar del llano, el mar Salado, las vertientes abajo del Pisga al oriente.",
      "18": "Y os mandé entonces, diciendo: Jehová vuestro Dios os ha dado esta tierra para que la poseáis: pasaréis armados delante de vuestros hermanos los hijos de Israel todos los valientes.",
      "19": "Solamente vuestras mujeres, vuestros niños, y vuestros ganados, (yo sé que tenéis mucho ganado,) quedarán en vuestras ciudades que os he dado,",
      "20": "Hasta que Jehová dé reposo á vuestros hermanos, así como á vosotros, y hereden también ellos la tierra que Jehová vuestro Dios les da á la otra parte del Jordán: entonces os volveréis cada uno a su heredad que yo os he dado.",
      "21": "Mandé también á Josué entonces, diciendo: Tus ojos vieron todo lo que Jehová vuestro Dios ha hecho á aquellos dos reyes: así hará Jehová á todos los reinos á los cuales pasarás tú.",
      "22": "No los temáis; que Jehová vuestro Dios, él es el que pelea por vosotros.",
      "23": "Y oré á Jehová en aquel tiempo, diciendo:",
      "24": "Señor Jehová, tú has comenzado á mostrar á tu siervo tu grandeza, y tu mano fuerte: porque ¿qué dios hay en el cielo ni en la tierra que haga según tus obras, y según tus valentías?",
      "25": "Pase yo, ruégote, y vea aquella tierra buena, que está á la parte allá del Jordán, aquel buen monte, y el Líbano.",
      "26": "Mas Jehová se había enojado contra mí por causa de vosotros, por lo cual no me oyó: y díjome Jehová: Bástate, no me hables más de este negocio.",
      "27": "Sube á la cumbre del Pisga, y alza tus ojos al occidente, y al aquilón, y al mediodía, y al oriente, y ve por tus ojos: porque no pasarás este Jordán.",
      "28": "Y manda a Josué, y anímalo, y confórtalo; porque él ha de pasar delante de este pueblo, y él les hará heredar la tierra que verás.",
      "29": "Y paramos en el valle delante de Beth-peor."
    },
    "4": {
      "1": "AHORA pues, oh Israel, oye los estatutos y derechos que yo os enseño, para que los ejecutéis, y viváis, y entréis, y poseáis la tierra que Jehová el Dios de vuestros padres te da.",
      "2": "No añadiréis á la palabra que yo os mando, ni disminuiréis de ella, para que guardéis los mandamientos de Jehová vuestro Dios que yo os ordeno.",
      "3": "Vuestros ojos vieron lo que hizo Jehová con motivo de Baal-peor; que á todo hombre que fué en pos de Baal-peor destruyó Jehová tu Dios de en medio de ti.",
      "4": "Mas vosotros que os allegasteis á Jehová vuestro Dios, todos estáis vivos hoy.",
      "5": "Mirad, yo os he enseñado estatutos y derechos, como Jehová mi Dios me mandó, para que hagáis así en medio de la tierra en la cual entráis para poseerla.",
      "6": "Guardadlos, pues, y ponedlos por obra: porque esta es vuestra sabiduría y vuestra inteligencia en ojos de los pueblos, los cuales oirán todos estos estatutos, y dirán: Ciertamente pueblo sabio y entendido, gente grande es ésta.",
      "7": "Porque ¿qué gente grande hay que tenga los dioses cercanos á sí, como lo está Jehová nuestro Dios en todo cuanto le pedimos?",
      "8": "Y ¿qué gente grande hay que tenga estatutos y derechos justos, como es toda esta ley que yo pongo hoy delante de vosotros?",
      "9": "Por tanto, guárdate, y guarda tu alma con diligencia, que no te olvides de las cosas que tus ojos han visto, ni se aparten de tu corazón todos los días de tu vida: y enseñarlas has á tus hijos, y á los hijos de tus hijos;",
      "10": "El día que estuviste delante de Jehová tu Dios en Horeb, cuando Jehová me dijo: Júntame el pueblo, para que yo les haga oir mis palabras, las cuales aprenderán, para temerme todos los días que vivieren sobre la tierra: y las enseñarán á sus hijos;",
      "11": "Y os llegasteis, y os pusisteis al pie del monte; y el monte ardía en fuego hasta en medio de los cielos con tinieblas, nube, y oscuridad.",
      "12": "Y habló Jehová con vosotros de en medio del fuego: oisteis la voz de sus palabras, mas á excepción de oir la voz, ninguna figura visteis:",
      "13": "Y él os anunció su pacto, el cual os mandó poner por obra, las diez palabras; y escribiólas en dos tablas de piedra.",
      "14": "A mí también me mandó Jehová entonces enseñaros los estatutos y derechos, para que los pusieseis por obra en la tierra á la cual pasáis para poseerla.",
      "15": "Guardad pues mucho vuestras almas: pues ninguna figura visteis el día que Jehová habló con vosotros de en medio del fuego:",
      "16": "Porque no os corrompáis, y hagáis para vosotros escultura, imagen de figura alguna, efigie de varón ó hembra,",
      "17": "Figura de algún animal que sea en la tierra, figura de ave alguna alada que vuele por el aire,",
      "18": "Figura de ningún animal que vaya arrastrando por la tierra, figura de pez alguno que haya en el agua debajo de la tierra:",
      "19": "Y porque alzando tus ojos al cielo, y viendo el sol y la luna y las estrellas, y todo el ejército del cielo, no seas incitado, y te inclines á ellos, y les sirvas; que Jehová tu Dios los ha concedido á todos los pueblos debajo de todos los cielos.",
      "20": "Empero á vosotros Jehová os tomó, y os ha sacado del horno de hierro, de Egipto, para que le seáis por pueblo de heredad como en este día.",
      "21": "Y Jehová se enojó contra mí sobre vuestros negocios, y juró que yo no pasaría el Jordán, ni entraría en la buena tierra, que Jehová tu Dios te da por heredad.",
      "22": "Así que yo voy á morir en esta tierra; y no paso el Jordán: mas vosotros pasaréis, y poseeréis aquella buena tierra.",
      "23": "Guardaos no os olvidéis del pacto de Jehová vuestro Dios, que él estableció con vosotros, y os hagáis escultura ó imagen de cualquier cosa, que Jehová tu Dios te ha vedado.",
      "24": "Porque Jehová tu Dios es fuego que consume, Dios celoso.",
      "25": "Cuando hubiereis engendrado hijos y nietos, y hubiereis envejecido en la tierra, y os corrompiereis, é hiciereis escultura ó imagen de cualquier cosa, é hiciereis mal en ojos de Jehová vuestro Dios, para enojarlo;",
      "26": "Yo pongo hoy por testigos al cielo y á la tierra, que presto pereceréis totalmente de la tierra hacia la cual pasáis el Jordán para poseerla: no estaréis en ella largos días sin que seáis destruídos.",
      "27": "Y Jehová os esparcirá entre los pueblos, y quedaréis pocos en número entre las gentes á las cuales os llevará Jehová:",
      "28": "Y serviréis allí á dioses hechos de manos de hombres, á madera y á piedra, que no ven, ni oyen, ni comen, ni huelen.",
      "29": "Mas si desde allí buscares á Jehová tu Dios, lo hallarás, si lo buscares de todo tu corazón y de toda tu alma.",
      "30": "Cuando estuviereis en angustia, y te alcanzaren todas estas cosas, si en los postreros días te volvieres á Jehová tu Dios, y oyeres su voz;",
      "31": "Porque Dios misericordioso es Jehová tu Dios; no te dejará, ni te destruirá, ni se olvidará del pacto de tus padres que les juró.",
      "32": "Porque pregunta ahora de los tiempos pasados, que han sido antes de ti, desde el día que crió Dios al hombre sobre la tierra, y desde el un cabo del cielo al otro, si se ha hecho cosa semejante á esta gran cosa, ó se haya oído otra como ella.",
      "33": "¿Ha oído pueblo la voz de Dios, que hablase de en medio del fuego, como tú la has oído, y vivido?",
      "34": "¿O ha Dios probado á venir á tomar para sí gente de en medio de otra gente, con pruebas, con señales, con milagros, y con guerra, y mano fuerte, y brazo extendido, y grandes espantos, según todas las cosas que hizo con vosotros Jehová vuestro Dios en Egipto ante tus ojos?",
      "35": "A ti te fué mostrado, para que supieses que Jehová él es Dios; no hay más fuera de él.",
      "36": "De los cielos te hizo oir su voz, para enseñarte: y sobre la tierra te mostró su gran fuego: y has oído sus palabras de en medio del fuego.",
      "37": "Y por cuanto él amó á tus padres, escogió su simiente después de ellos, y sacóte delante de sí de Egipto con su gran poder;",
      "38": "Para echar de delante de ti gentes grandes y más fuertes que tú, y para introducirte, y darte su tierra por heredad, como hoy.",
      "39": "Aprende pues hoy, y reduce á tu corazón que Jehová él es el Dios arriba en el cielo, y abajo sobre la tierra; no hay otro.",
      "40": "Y guarda sus estatutos y sus mandamientos, que yo te mando hoy, para que te vaya bien á ti y á tus hijos después de ti, y prolongues tus días sobre la tierra que Jehová tu Dios te da para siempre.",
      "41": "Entonces apartó Moisés tres ciudades de esta parte del Jordán al nacimiento del sol,",
      "42": "Para que huyese allí el homicida que matase á su prójimo por yerro, sin haber tenido enemistad con él desde ayer ni antes de ayer; y que huyendo á una de estas ciudades salvara la vida:",
      "43": "A Beser en el desierto, en tierra de la llanura, de los Rubenitas; y á Ramoth en Galaad, de los Gaditas; y á Golán en Basán, de los de Manasés.",
      "44": "Esta, pues, es la ley que Moisés propuso delante de los hijos de Israel.",
      "45": "Estos son los testimonios, y los estatutos, y los derechos, que Moisés notificó á los hijos de Israel, cuando hubieron salido de Egipto;",
      "46": "De esta parte del Jordán, en el valle delante de Beth-peor, en la tierra de Sehón rey de los Amorrheos, que habitaba en Hesbón, al cual hirió Moisés con los hijos de Israel, cuando hubieron salido de Egipto:",
      "47": "Y poseyeron su tierra, y la tierra de Og rey de Basán; dos reyes de los Amorrheos que estaban de esta parte del Jordán, al nacimiento del sol:",
      "48": "Desde Aroer, que está junto á la ribera del arroyo de Arnón, hasta el monte de Sión, que es Hermón;",
      "49": "Y toda la llanura de esta parte del Jordán, al oriente, hasta la mar del llano, las vertientes de las aguas abajo del Pisga."
    },
    "5": {
      "1": "Y LLAMO Moisés á todo Israel, y díjoles: Oye, Israel, los estatutos y derechos que yo pronuncio hoy en vuestros oídos: y aprendedlos, y guardadlos, para ponerlos por obra.",
      "2": "Jehová nuestro Dios hizo pacto con nosotros en Horeb.",
      "3": "No con nuestros padres hizo Jehová este pacto, sino con nosotros todos los que estamos aquí hoy vivos.",
      "4": "Cara á cara habló Jehová con vosotros en el monte de en medio del fuego,",
      "5": "(Yo estaba entonces entre Jehová y vosotros, para denunciaros la palabra de Jehová; porque vosotros tuvisteis temor del fuego, y no subisteis al monte;) diciendo:",
      "6": "Yo soy Jehová tu Dios, que te saqué de tierra de Egipto, de casa de siervos.",
      "7": "No tendrás dioses extraños delante de mí.",
      "8": "No harás para ti escultura, ni imagen alguna de cosa que está arriba en los cielos, ó abajo en la tierra, ó en las aguas debajo de la tierra:",
      "9": "No te inclinarás á ellas ni les servirás: porque yo soy Jehová tu Dios, fuerte, celoso, que visito la iniquidad de los padres sobre los hijos, y sobre los terceros, y sobre los cuartos, á los que me aborrecen,",
      "10": "Y que hago misericordia á millares á los que me aman, y guardan mis mandamientos.",
      "11": "No tomarás en vano el nombre de Jehová tu Dios; porque Jehová no dará por inocente al que tomare en vano su nombre.",
      "12": "Guardarás el día del reposo para santificarlo, como Jehová tu Dios te ha mandado.",
      "13": "Seis días trabajarás y harás toda tu obra:",
      "14": "Mas el séptimo es reposo á Jehová tu Dios: ninguna obra harás tú, ni tu hijo, ni tu hija, ni tu siervo, ni tu sierva, ni tu buey, ni tu asno, ni ningún animal tuyo, ni tu peregrino que está dentro de tus puertas: porque descanse tu siervo y tu sierva como tú.",
      "15": "Y acuérdate que fuiste siervo en tierra de Egipto, y que Jehová tu Dios te sacó de allá con mano fuerte y brazo extendido: por lo cual Jehová tu Dios te ha mandado que guardes el día del reposo.",
      "16": "Honra á tu padre y á tu madre, como Jehová tu Dios te ha mandado, para que sean prolongados tus días, y para que te vaya bien sobre la tierra que Jehová tu Dios te da.",
      "17": "No matarás.",
      "18": "No adulterarás.",
      "19": "No hurtarás.",
      "20": "No dirás falso testimonio contra tu prójimo.",
      "21": "No codiciarás la mujer de tu prójimo, ni desearás la casa de tu prójimo, ni su tierra, ni su siervo, ni su sierva, ni su buey, ni su asno, ni ninguna cosa que sea de tu prójimo.",
      "22": "Estas palabras habló Jehová á toda vuestra congregación en el monte, de en medio del fuego, de la nube y de la oscuridad, á gran voz: y no añadió más. Y escribiólas en dos tablas de piedra, las cuales me dió á mí.",
      "23": "Y aconteció, que como vosotros oisteis la voz de en medio de las tinieblas, y visteis al monte que ardía en fuego, llegasteis á mí todos los príncipes de vuestras tribus, y vuestros ancianos;",
      "24": "Y dijisteis: He aquí, Jehová nuestro Dios nos ha mostrado su gloria y su grandeza, y hemos oído su voz de en medio del fuego: hoy hemos visto que Jehová habla al hombre, y éste vive.",
      "25": "Ahora pues, ¿por qué moriremos? que este gran fuego nos consumirá: si tornáremos á oir la voz de Jehová nuestro Dios, moriremos.",
      "26": "Porque, ¿qué es toda carne, para que oiga la voz del Dios viviente que habla de en medio del fuego, como nosotros la oímos, y viva?",
      "27": "Llega tú, y oye todas las cosas que dijere Jehová nuestro Dios; y tú nos dirás todo lo que Jehová nuestro Dios te dijere, y nosotros oiremos y haremos.",
      "28": "Y oyó Jehová la voz de vuestras palabras, cuando me hablabais; y díjome Jehová: He oído la voz de las palabras de este pueblo, que ellos te han hablado: bien está todo lo que han dicho.",
      "29": "Quién diera que tuviesen tal corazón, que me temiesen, y guardasen todos los días todos mis mandamientos, para que á ellos y á sus hijos les fuese bien para siempre!",
      "30": "Ve, diles: Volveos á vuestras tiendas.",
      "31": "Y tú estáte aquí conmigo, y te diré todos los mandamientos, y estatutos, y derechos que les has de enseñar, a fin que los pongan ahora por obra en la tierra que yo les doy para poseerla.",
      "32": "Mirad, pues, que hagáis como Jehová vuestro Dios os ha mandado: no os apartéis á diestra ni á siniestra;",
      "33": "Andad en todo camino que Jehová vuestro Dios os ha mandado, para que viváis, y os vaya bien, y tengáis largos días en la tierra que habéis de poseer."
    },
    "6": {
      "1": "ESTOS pues son los mandamientos, estatutos, y derechos que Jehová vuestro Dios mandó que os enseñase, para que los pongáis por obra en la tierra á la cual pasáis vosotros para poseerla:",
      "2": "Para que temas á Jehová tu Dios, guardando todos sus estatutos y sus mandamientos que yo te mando, tú, y tu hijo, y el hijo de tu hijo, todos los días de tu vida, y que tus días sean prolongados.",
      "3": "Oye pues, oh Israel, y cuida de ponerlos por obra, para que te vaya bien, y seáis multiplicados, como te ha dicho Jehová el Dios de tus padres, en la tierra que destila leche y miel.",
      "4": "Oye, Israel: Jehová nuestro Dios, Jehová uno es:",
      "5": "Y Amarás á Jehová tu Dios de todo tu corazón, y de toda tu alma, y con todo tu poder.",
      "6": "Y estas palabras que yo te mando hoy, estarán sobre tu corazón:",
      "7": "Y las repetirás á tus hijos, y hablarás de ellas estando en tu casa, y andando por el camino, y al acostarte, y cuando te levantes:",
      "8": "Y has de atarlas por señal en tu mano, y estarán por frontales entre tus ojos:",
      "9": "Y las escribirás en los postes de tu casa, y en tus portadas.",
      "10": "Y será, cuando Jehová tu Dios te hubiere introducido en la tierra que juró á tus padres Abraham, Isaac, y Jacob, que te daría; en ciudades grandes y buenas que tú no edificaste,",
      "11": "Y casas llenas de todo bien, que tú no henchiste, y cisternas cavadas, que tú no cavaste, viñas y olivares que no plantaste: luego que comieres y te hartares,",
      "12": "Guárdate que no te olvides de Jehová, que te sacó de tierra de Egipto, de casa de siervos.",
      "13": "A Jehová tu Dios temerás, y á él servirás, y por su nombre jurarás.",
      "14": "No andaréis en pos de dioses ajenos, de los dioses de los pueblos que están en vuestros contornos:",
      "15": "Porque el Dios celoso, Jehová tu Dios, en medio de ti está; porque no se inflame el furor de Jehová tu Dios contra ti, y te destruya de sobre la haz de la tierra.",
      "16": "No tentaréis á Jehová vuestro Dios, como lo tentasteis en Massa.",
      "17": "Guardad cuidadosamente los mandamientos de Jehová vuestro Dios, y sus testimonios, y sus estatutos, que te ha mandado.",
      "18": "Y harás lo recto y bueno en ojos de Jehová, para que te vaya bien, y entres y poseas la buena tierra que Jehová juró á tus padres;",
      "19": "Para que él eche á todos sus enemigos de delante de ti, como Jehová ha dicho.",
      "20": "Cuando mañana te preguntare tu hijo, diciendo: ¿Qué significan los testimonios, y estatutos, y derechos, que Jehová nuestro Dios os mandó?",
      "21": "Entonces dirás á tu hijo: Nosotros éramos siervos de Faraón en Egipto, y Jehová nos sacó de Egipto con mano fuerte;",
      "22": "Y dió Jehová señales y milagros grandes y nocivos en Egipto, sobre Faraón y sobre toda su casa, delante de nuestros ojos;",
      "23": "Y sacónos de allá, para traernos y darnos la tierra que juró á nuestros padres;",
      "24": "Y mandónos Jehová que ejecutásemos todos estos estatutos, y que temamos á Jehová nuestro Dios, porque nos vaya bien todos los días, y para que nos dé vida, como hoy.",
      "25": "Y tendremos justicia cuando cuidáremos de poner por obra todos estos mandamientos delante de Jehová nuestro Dios, como él nos ha mandado."
    },
    "7": {
      "1": "CUANDO Jehová tu Dios te hubiere introducido en la tierra en la cual tú has de entrar para poseerla, y hubiere echado de delante de ti muchas gentes, al Hetheo, al Gergeseo, y al Amorrheo, y al Cananeo, y al Pherezeo, y al Heveo, y al Jebuseo, siete naciones mayores y más fuertes que tú;",
      "2": "Y Jehová tu Dios las hubiere entregado delante de ti, y las hirieres, del todo las destruirás: no harás con ellos alianza, ni las tomarás á merced.",
      "3": "Y no emparentarás con ellos: no darás tu hija á su hijo, ni tomarás á su hija para tu hijo.",
      "4": "Porque desviará á tu hijo de en pos de mí, y servirán á dioses ajenos; y el furor de Jehová se encenderá sobre vosotros, y te destruirá presto.",
      "5": "Mas así habéis de hacer con ellos: sus altares destruiréis, y quebraréis sus estatuas, y cortaréis sus bosques, y quemaréis sus esculturas en el fuego.",
      "6": "Porque tú eres pueblo santo á Jehová tu Dios: Jehová tu Dios te ha escogido para serle un pueblo especial, más que todos los pueblos que están sobre la haz de la tierra.",
      "7": "No por ser vosotros más que todos los pueblos os ha querido Jehová, y os ha escogido; porque vosotros erais los más pocos de todos los pueblos:",
      "8": "Sino porque Jehová os amó, y quiso guardar el juramento que juró á vuestros padres, os ha sacado Jehová con mano fuerte, y os ha rescatado de casa de siervos, de la mano de Faraón, rey de Egipto.",
      "9": "Conoce, pues, que Jehová tu Dios es Dios, Dios fiel, que guarda el pacto y la misericordia á los que le aman y guardan sus mandamientos, hasta las mil generaciones;",
      "10": "Y que da el pago en su cara al que le aborrece, destruyéndolo: ni lo dilatará al que le odia, en su cara le dará el pago.",
      "11": "Guarda por tanto los mandamientos, y estatutos, y derechos que yo te mando hoy que cumplas.",
      "12": "Y será que, por haber oído estos derechos, y guardado y puéstolos por obra, Jehová tu Dios guardará contigo el pacto y la misericordia que juró á tus padres;",
      "13": "Y te amará, y te bendecirá, y te multiplicará, y bendecirá el fruto de tu vientre, y el fruto de tu tierra, y tu grano, y tu mosto, y tu aceite, la cría de tus vacas, y los rebaños de tus ovejas, en la tierra que juró á tus padres que te daría.",
      "14": "Bendito serás más que todos los pueblos: no habrá en ti varón ni hembra estéril, ni en tus bestias.",
      "15": "Y quitará Jehová de ti toda enfermedad; y todas las malas plagas de Egipto, que tú sabes, no las pondrá sobre ti, antes las pondrá sobre todos los que te aborrecieren.",
      "16": "Y consumirás á todos los pueblos que te da Jehová tu Dios: no los perdonará tu ojo; ni servirás á sus dioses, que te será tropiezo.",
      "17": "Cuando dijeres en tu corazón: Estas gentes son muchas más que yo, ¿cómo las podré desarraigar?;",
      "18": "No tengas temor de ellos: acuérdate bien de lo que hizo Jehová tu Dios con Faraón y con todo Egipto;",
      "19": "De las grandes pruebas que vieron tus ojos, y de las señales y milagros, y de la mano fuerte y brazo extendido con que Jehová tu Dios te sacó: así hará Jehová tu Dios con todos los pueblos de cuya presencia tú temieres.",
      "20": "Y también enviará Jehová tu Dios sobre ellos avispas, hasta que perezcan los que quedaren, y los que se hubieren escondido de delante de ti.",
      "21": "No desmayes delante de ellos, que Jehová tu Dios está en medio de ti, Dios grande y terrible.",
      "22": "Y Jehová tu Dios echará á estas gentes de delante de ti poco á poco: no las podrás acabar luego, porque las bestias del campo no se aumenten contra ti.",
      "23": "Mas Jehová tu Dios las entregará delante de ti, y él las quebrantará con grande destrozo, hasta que sean destruídos.",
      "24": "Y él entregará sus reyes en tu mano, y tú destruirás el nombre de ellos de debajo del cielo: nadie te hará frente hasta que los destruyas.",
      "25": "Las esculturas de sus dioses quemarás en el fuego: no codiciarás plata ni oro de sobre ellas para tomarlo para ti, porque no tropieces en ello, pues es abominación á Jehová tu Dios;",
      "26": "Y no meterás abominación en tu casa, porque no seas anatema como ello; del todo lo aborrecerás y lo abominarás; porque es anatema."
    },
    "8": {
      "1": "CUIDARÉIS de poner por obra todo mandamiento que yo os ordeno hoy, porque viváis, y seáis multiplicados, y entréis, y poseáis la tierra, de la cual juró Jehová á vuestros padres.",
      "2": "Y acordarte has de todo el camino por donde te ha traído Jehová tu Dios estos cuarenta años en el desierto, para afligirte, por probarte, para saber lo que estaba en tu corazón, si habías de guardar ó no sus mandamientos.",
      "3": "Y te afligió, é hízote tener hambre, y te sustentó con maná, comida que no conocías tú, ni tus padres la habían conocido; para hacerte saber que el hombre no vivirá de solo pan, mas de todo lo que sale de la boca de Jehová vivirá el hombre.",
      "4": "Tu vestido nunca se envejeció sobre ti, ni el pie se te ha hinchado por estos cuarenta años.",
      "5": "Reconoce asimismo en tu corazón, que como castiga el hombre á su hijo, así Jehová tu Dios te castiga.",
      "6": "Guardarás, pues, los mandamientos de Jehová tu Dios, andando en sus caminos, y temiéndolo.",
      "7": "Porque Jehová tu Dios te introduce en la buena tierra, tierra de arroyos, de aguas, de fuentes, de abismos que brotan por vegas y montes;",
      "8": "Tierra de trigo y cebada, y de vides, é higueras, y granados; tierra de olivas, de aceite, y de miel;",
      "9": "Tierra en la cual no comerás el pan con escasez, no te faltará nada en ella; tierra que sus piedras son hierro, y de sus montes cortarás metal.",
      "10": "Y comerás y te hartarás, y bendecirás á Jehová tu Dios por la buena tierra que te habrá dado.",
      "11": "Guárdate, que no te olvides de Jehová tu Dios, para no observar sus mandamientos, y sus derechos, y sus estatutos, que yo te ordeno hoy:",
      "12": "Que quizá no comas y te hartes, y edifiques buenas casas en que mores,",
      "13": "Y tus vacas y tus ovejas se aumenten, y la plata y el oro se te multiplique, y todo lo que tuvieres se te aumente,",
      "14": "Y se eleve luego tu corazón, y te olvides de Jehová tu Dios, que te sacó de tierra de Egipto, de casa de siervos;",
      "15": "Que te hizo caminar por un desierto grande y espantoso, de serpientes ardientes, y de escorpiones, y de sed, donde ningún agua había, y él te sacó agua de la roca del pedernal;",
      "16": "Que te sustentó con maná en el desierto, comida que tus padres no habían conocido, afligiéndote y probándote, para á la postre hacerte bien;",
      "17": "Y digas en tu corazón: Mi poder y la fortaleza de mi mano me han traído esta riqueza.",
      "18": "Antes acuérdate de Jehová tu Dios: porque él te da el poder para hacer las riquezas, á fin de confirmar su pacto que juró á tus padres, como en este día.",
      "19": "Mas será, si llegares á olvidarte de Jehová tu Dios, y anduvieres en pos de dioses ajenos, y les sirvieres, y á ellos te encorvares, protésto lo hoy contra vosotros, que de cierto pereceréis.",
      "20": "Como las gentes que Jehová destruirá delante de vosotros, así pereceréis; por cuanto no habréis atendido á la voz de Jehová vuestro Dios."
    },
    "9": {
      "1": "OYE, Israel: tú estás hoy para pasar el Jordán, para entrar á poseer gentes más numerosas y más fuertes que tú, ciudades grandes y encastilladas hasta el cielo,",
      "2": "Un pueblo grande y alto, hijos de gigantes, de los cuales tienes tú conocimiento, y has oído decir: ¿Quién se sostendrá delante de los hijos del gigante?",
      "3": "Sabe, pues, hoy que Jehová tu Dios es el que pasa delante de ti, fuego consumidor, que los destruirá y humillará delante de ti: y tú los echarás, y los destruirás luego, como Jehová te ha dicho.",
      "4": "No discurras en tu corazón cuando Jehová tu Dios los habrá echado de delante de ti, diciendo: Por mi justicia me ha metido Jehová á poseer esta tierra; pues por la impiedad de estas gentes Jehová las echa de delante de ti.",
      "5": "No por tu justicia, ni por la rectitud de tu corazón entras a poseer la tierra de ellos; mas por la impiedad de estas gentes Jehová tu Dios las echa de delante de ti, y por confirmar la palabra que Jehová juró á tus padres Abraham, Isaac, y Jacob.",
      "6": "Por tanto, sabe que no por tu justicia Jehová tu Dios te da esta buena tierra para poseerla; que pueblo duro de cerviz eres tú.",
      "7": "Acuérdate, no te olvides que has provocado á ira á Jehová tu Dios en el desierto: desde el día que saliste de la tierra de Egipto, hasta que entrasteis en este lugar, habéis sido rebeldes á Jehová.",
      "8": "Y en Horeb provocasteis á ira á Jehová, y enojóse Jehová contra vosotros para destruiros.",
      "9": "Cuando yo subí al monte para recibir las tablas de piedra, las tablas del pacto que Jehová hizo con vosotros, estuve entonces en el monte cuarenta días y cuarenta noches, sin comer pan ni beber agua:",
      "10": "Y dióme Jehová las dos tablas de piedra escritas con el dedo de Dios; y en ellas estaba escrito conforme á todas las palabras que os habló Jehová en el monte de en medio del fuego, el día de la asamblea.",
      "11": "Y fué al cabo de los cuarenta días y cuarenta noches, que Jehová me dió dos las tablas de piedra, las tablas del pacto.",
      "12": "Y díjome Jehová: Levántate, desciende presto de aquí; que tu pueblo que sacaste de Egipto se ha corrompido: pronto se han apartado del camino que yo les mandé: hanse hecho una efigie de fundición.",
      "13": "Y hablóme Jehová, diciendo: He visto ese pueblo, y he aquí, que él es pueblo duro de cerviz:",
      "14": "Déjame que los destruya, y raiga su nombre de debajo del cielo; que yo te pondré sobre gente fuerte y mucha más que ellos.",
      "15": "Y volví y descendí del monte, el cual ardía en fuego, con las tablas del pacto en mis dos manos.",
      "16": "Y miré, y he aquí habíais pecado contra Jehová vuestro Dios: os habíais hecho un becerro de fundición, apartándoos presto del camino que Jehová os había mandado.",
      "17": "Entonces tomé las dos tablas, y arrojélas de mis dos manos, y quebrélas delante de vuestros ojos.",
      "18": "Y postréme delante de Jehová, como antes, cuarenta días y cuarenta noches: no comí pan ni bebí agua, á causa de todo vuestro pecado que habíais cometido haciendo mal en ojos de Jehová para enojarlo.",
      "19": "Porque temí á causa del furor y de la ira con que Jehová estaba enojado contra vosotros para destruiros. Pero Jehová me oyó aún esta vez.",
      "20": "Contra Aarón también se enojó Jehová en gran manera para destruirlo: y también oré por Aarón entonces.",
      "21": "Y tomé vuestro pecado, el becerro que habíais hecho, y quemélo en el fuego, y lo desmenucé moliéndole muy bien, hasta que fué reducido á polvo: y eché el polvo de él en el arroyo que descendía del monte.",
      "22": "También en Tabera, y en Massa, y en Kibroth-hataavah, enojasteis á Jehová.",
      "23": "Y cuando Jehová os envió desde Cades-barnea, diciendo: Subid y poseed la tierra que yo os he dado; también fuisteis rebeldes al dicho de Jehová vuestro Dios, y no lo creisteis, ni obedecisteis á su voz.",
      "24": "Rebeldes habéis sido á Jehová desde el día que yo os conozco.",
      "25": "Postréme, pues, delante de Jehová cuarenta días y cuarenta noches que estuve postrado; porque Jehová dijo que os había de destruir.",
      "26": "Y oré á Jehová, diciendo: Oh Señor Jehová, no destruyas tu pueblo y tu heredad que has redimido con tu grandeza, al cual sacaste de Egipto con mano fuerte.",
      "27": "Acuérdate de tus siervos Abraham, Isaac, y Jacob; no mires á la dureza de este pueblo, ni á su impiedad, ni á su pecado:",
      "28": "Porque no digan los de la tierra de donde nos sacaste: Por cuanto no pudo Jehová introducirlos en la tierra que les había dicho, ó porque los aborrecía, los sacó para matarlos en el desierto.",
      "29": "Y ellos son tu pueblo y tu heredad, que sacaste con tu gran fortaleza y con tu brazo extendido."
    },
    "10": {
      "1": "EN aquel tiempo Jehová me dijo: Lábrate dos tablas de piedra como las primeras, y sube á mí al monte, y hazte un arca de madera:",
      "2": "Y escribiré en aquellas tablas palabras que estaban en las tablas primeras que quebraste; y las pondrás en el arca.",
      "3": "E hice un arca de madera de Sittim, y labré dos tablas de piedra como las primeras, y subí al monte con las dos tablas en mi mano.",
      "4": "Y escribió en las tablas conforme á la primera escritura, las diez palabras que Jehová os había hablado en el monte de en medio del fuego, el día de la asamblea; y diómelas Jehová.",
      "5": "Y volví y descendí del monte, y puse las tablas en el arca que había hecho; y allí están, como Jehová me mandó.",
      "6": "(Después partieron los hijos de Israel de Beerot-bene-jacaam á Moserá: allí murió Aarón, y allí fué sepultado; y en lugar suyo tuvo el sacerdocio su hijo Eleazar.",
      "7": "De allí partieron á Gudgod, y de Gudgod á Jotbath, tierra de arroyos de aguas.",
      "8": "En aquel tiempo apartó Jehová la tribu de Leví, para que llevase el arca del pacto de Jehová, para que estuviese delante de Jehová para servirle, y para bendecir en su nombre, hasta hoy.",
      "9": "Por lo cual Leví no tuvo parte ni heredad con sus hermanos: Jehová es su heredad, como Jehová tu Dios le dijo.)",
      "10": "Y yo estuve en el monte como los primeros días, cuarenta días y cuarenta noches; y Jehová me oyó también esta vez, y no quiso Jehová destruirte.",
      "11": "Y díjome Jehová: Levántate, anda, para que partas delante del pueblo, para que entren y posean la tierra que juré á sus padres les había de dar.",
      "12": "Ahora pues, Israel, ¿qué pide Jehová tu Dios de ti, sino que temas á Jehová tu Dios, que andes en todos sus caminos, y que lo ames, y sirvas á Jehová tu Dios con todo tu corazón, y con toda tu alma;",
      "13": "Que guardes los mandamientos de Jehová y sus estatutos, que yo te prescribo hoy, para que hayas bien?",
      "14": "He aquí, de Jehová tu Dios son los cielos, y los cielos de los cielos: la tierra, y todas las cosas que hay en ella.",
      "15": "Solamente de tus padres se agradó Jehová para amarlos, y escogió su simiente después de ellos, á vosotros, de entre todos los pueblos, como en este día.",
      "16": "Circuncidad pues el prepucio de vuestro corazón, y no endurezcáis más vuestra cerviz.",
      "17": "Porque Jehová vuestro Dios es Dios de dioses, y Señor de señores, Dios grande, poderoso, y terrible, que no acepta persona, ni toma cohecho;",
      "18": "Que hace justicia al huérfano y á la viuda; que ama también al extranjero dándole pan y vestido.",
      "19": "Amaréis pues al extranjero: porque extranjeros fuisteis vosotros en tierra de Egipto.",
      "20": "A Jehová tu Dios temerás, á él servirás, á él te allegarás, y por su nombre jurarás.",
      "21": "El es tu alabanza, y él es tu Dios, que ha hecho contigo estas grandes y terribles cosas que tus ojos han visto.",
      "22": "Con setenta almas descendieron tus padres á Egipto; y ahora Jehová te ha hecho como las estrellas del cielo en multitud."
    },
    "11": {
      "1": "AMARAS pues á Jehová tu Dios, y guardarás su ordenanza, y sus estatutos y sus derechos y sus mandamientos, todos los días.",
      "2": "Y comprended hoy: porque no hablo con vuestros hijos que no han sabido ni visto el castigo de Jehová vuestro Dios, su grandeza, su mano fuerte, y su brazo extendido,",
      "3": "Y sus señales, y sus obras que hizo en medio de Egipto á Faraón, rey de Egipto, y á toda su tierra;",
      "4": "Y lo que hizo al ejército de Egipto, á sus caballos, y á sus carros; cómo hizo ondear las aguas del mar Bermejo sobre ellos, cuando venían tras vosotros, y Jehová los destruyó hasta hoy;",
      "5": "Y lo que ha hecho con vosotros en el desierto, hasta que habéis llegado á este lugar;",
      "6": "Y lo que hizo con Dathán y Abiram, hijos de Eliab hijo de Rubén; cómo abrió la tierra su boca, y tragóse á ellos y á sus casas, y sus tiendas, y toda la hacienda que tenían en pie en medio de todo Israel:",
      "7": "Mas vuestros ojos han visto todos los grandes hechos que Jehová ha ejecutado.",
      "8": "Guardad, pues, todos los mandamientos que yo os prescribo hoy, para que seáis esforzados, y entréis y poseáis la tierra, á la cual pasáis para poseerla;",
      "9": "Y para que os sean prolongados los días sobre la tierra, que juró Jehová á vuestros padres había de dar á ellos y á su simiente, tierra que fluye leche y miel.",
      "10": "Que la tierra á la cual entras para poseerla, no es como la tierra de Egipto de donde habéis salido, donde sembrabas tu simiente, y regabas con tu pie, como huerto de hortaliza.",
      "11": "La tierra á la cual pasáis para poseerla, es tierra de montes y de vegas; de la lluvia del cielo ha de beber las aguas;",
      "12": "Tierra de la cual Jehová tu Dios cuida: siempre están sobre ella los ojos de Jehová tu Dios, desde el principio del año hasta el fin de él.",
      "13": "Y será que, si obedeciereis cuidadosamente mis mandamientos que yo os prescribo hoy, amando á Jehová vuestro Dios, y sirviéndolo con todo vuestro corazón, y con toda vuestra alma,",
      "14": "Yo daré la lluvia de vuestra tierra en su tiempo, la temprana y la tardía; y cogerás tu grano, y tu vino, y tu aceite.",
      "15": "Daré también hierba en tu campo para tus bestias; y comerás, y te hartarás.",
      "16": "Guardaos, pues, que vuestro corazón no se infatúe, y os apartéis, y sirváis á dioses ajenos, y os inclinéis á ellos;",
      "17": "Y así se encienda el furor de Jehová sobre vosotros, y cierre los cielos, y no haya lluvia, ni la tierra dé su fruto, y perezcáis presto de la buena tierra que os da Jehová.",
      "18": "Por tanto, pondréis estas mis palabras en vuestro corazón y en vuestra alma, y las ataréis por señal en vuestra mano, y serán por frontales entre vuestros ojos.",
      "19": "Y las enseñaréis á vuestros hijos, hablando de ellas, ora sentado en tu casa, ó andando por el camino, cuando te acuestes, y cuando te levantes:",
      "20": "Y las escribirás en los postes de tu casa, y en tus portadas:",
      "21": "Para que sean aumentados vuestros días, y los días de vuestros hijos, sobre la tierra que juró Jehová á vuestros padres que les había de dar, como los días de los cielos sobre la tierra.",
      "22": "Porque si guardareis cuidadosamente todos estos mandamientos que yo os prescribo, para que los cumpláis; como améis á Jehová vuestro Dios andando en todos sus caminos, y á él os allegareis,",
      "23": "Jehová también echará todas estas gentes de delante de vosotros y poseeréis gentes grandes y más fuertes que vosotros.",
      "24": "Todo lugar que pisare la planta de vuestro pie, será vuestro: desde el desierto y el Líbano, desde el río, el río Eufrates, hasta la mar postrera será vuestro término.",
      "25": "Nadie se sostendrá delante de vosotros: miedo y temor de vosotros pondrá Jehová vuestro Dios sobre la haz de toda la tierra que hollareis, como él os ha dicho.",
      "26": "He aquí yo pongo hoy delante de vosotros la bendición y la maldición:",
      "27": "La bendición, si oyereis los mandamientos de Jehová vuestro Dios, que yo os prescribo hoy;",
      "28": "Y la maldición, si no oyereis los mandamientos de Jehová vuestro Dios, y os apartareis del camino que yo os ordeno hoy, para ir en pos de dioses ajenos que no habéis conocido.",
      "29": "Y será que, cuando Jehová tu Dios te introdujere en la tierra á la cual vas para poseerla, pondrás la bendición sobre el monte Gerizim, y la maldición sobre el monte Ebal:",
      "30": "Los cuales están de la otra parte del Jordán, tras el camino del occidente en la tierra del Cananeo, que habita en la campiña delante de Gilgal, junto á los llanos de Moreh.",
      "31": "Porque vosotros pasáis el Jordán, para ir a poseer la tierra que os da Jehová vuestro Dios; y la poseeréis, y habitaréis en ella.",
      "32": "Cuidaréis, pues, de poner por obra todos los estatutos y derechos que yo presento hoy delante de vosotros."
    },
    "12": {
      "1": "ESTOS son los estatutos y derechos que cuidaréis de poner por obra, en la tierra que Jehová el Dios de tus padres te ha dado para que la poseas, todos los días que vosotros viviereis sobre la tierra.",
      "2": "Destruiréis enteramente todos los lugares donde las gentes que vosotros heredareis sirvieron á sus dioses, sobre los montes altos, y sobre los collados, y debajo de todo árbol espeso:",
      "3": "Y derribaréis sus altares, y quebraréis sus imágenes, y sus bosques consumiréis con fuego: y destruiréis las esculturas de sus dioses, y extirparéis el nombre de ellas de aquel lugar.",
      "4": "No haréis así á Jehová vuestro Dios.",
      "5": "Mas el lugar que Jehová vuestro Dios escogiere de todas vuestras tribus, para poner allí su nombre para su habitación, ése buscaréis, y allá iréis:",
      "6": "Y allí llevaréis vuestros holocaustos, y vuestros sacrificios, y vuestros diezmos, y la ofrenda elevada de vuestras manos, y vuestros votos, y vuestras ofrendas voluntarias, y los primerizos de vuestras vacas y de vuestras ovejas:",
      "7": "Y comeréis allí delante de Jehová vuestro Dios, y os alegraréis, vosotros y vuestras familias, en toda obra de vuestras manos en que Jehová tu Dios te hubiere bendecido.",
      "8": "No haréis como todo lo que nosotros hacemos aquí ahora, cada uno lo que le parece,",
      "9": "Porque aun hasta ahora no habéis entrado al reposo y á la heredad que os da Jehová vuestro Dios.",
      "10": "Mas pasaréis el Jordán, y habitaréis en la tierra que Jehová vuestro Dios os hace heredar, y él os dará reposo de todos vuestros enemigos alrededor, y habitaréis seguros.",
      "11": "Y al lugar que Jehová vuestro Dios escogiere para hacer habitar en él su nombre, allí llevaréis todas las cosas que yo os mando: vuestros holocaustos, y vuestros sacrificios, vuestros diezmos, y las ofrendas elevadas de vuestras manos, y todo lo escogido de vuestros votos que hubiereis prometido á Jehová;",
      "12": "Y os alegraréis delante de Jehová vuestro Dios, vosotros, y vuestros hijos, y vuestras hijas, y vuestros siervos, y vuestras siervas, y el Levita que estuviere en vuestras poblaciones: por cuanto no tiene parte ni heredad con vosotros.",
      "13": "Guárdate, que no ofrezcas tus holocaustos en cualquier lugar que vieres;",
      "14": "Mas en el lugar que Jehová escogiere, en una de tus tribus, allí ofrecerás tus holocaustos, y allí harás todo lo que yo te mando.",
      "15": "Con todo, podrás matar y comer carne en todas tus poblaciones conforme al deseo de tu alma, según la bendición de Jehová tu Dios que él te habrá dado: el inmundo y el limpio la comerá, como la de corzo ó de ciervo:",
      "16": "Salvo que sangre no comeréis; sobre la tierra la derramaréis como agua.",
      "17": "Ni podrás comer en tus poblaciones el diezmo de tu grano, ó de tu vino, ó de tu aceite, ni los primerizos de tus vacas, ni de tus ovejas, ni tus votos que prometieres, ni tus ofrendas voluntarias, ni las elevadas ofrendas de tus manos:",
      "18": "Mas delante de Jehová tu Dios las comerás, en el lugar que Jehová tu Dios hubiere escogido, tú, y tu hijo, y tu hija, y tu siervo, y tu sierva, y el Levita que está en tus poblaciones: y alegrarte has delante de Jehová tu Dios en toda obra de tus manos.",
      "19": "Ten cuidado de no desamparar al Levita en todos tus días sobre tu tierra.",
      "20": "Cuando Jehová tu Dios ensanchare tu término, como él te ha dicho, y tú dijeres: Comeré carne, porque deseó tu alma comerla, conforme á todo el deseo de tu alma comerás carne.",
      "21": "Cuando estuviere lejos de ti el lugar que Jehová tu Dios habrá escogido, para poner allí su nombre, matarás de tus vacas y de tus ovejas, que Jehová te hubiere dado, como te he mandado yo, y comerás en tus puertas según todo lo que deseare tu alma.",
      "22": "Lo mismo que se come el corzo y el ciervo, así las comerás: el inmundo y el limpio comerán también de ellas.",
      "23": "Solamente que te esfuerces á no comer sangre: porque la sangre es el alma; y no has de comer el alma juntamente con su carne.",
      "24": "No la comerás: en tierra la derramarás como agua.",
      "25": "No comerás de ella; para que te vaya bien á ti, y á tus hijos después de ti, cuando hicieres lo recto en ojos de Jehová.",
      "26": "Empero las cosas que tuvieres tú consagradas, y tus votos, las tomarás, y vendrás al lugar que Jehová hubiere escogido:",
      "27": "Y ofrecerás tus holocaustos, la carne y la sangre, sobre el altar de Jehová tu Dios: y la sangre de tus sacrificios será derramada sobre el altar de Jehová tu Dios, y comerás la carne.",
      "28": "Guarda y escucha todas estas palabras que yo te mando, porque te vaya bien á ti y á tus hijos después de ti para siempre, cuando hicieres lo bueno y lo recto en los ojos de Jehová tu Dios.",
      "29": "Cuando hubiere devastado delante de ti Jehová tu Dios las naciones á donde tú vas para poseerlas, y las heredares, y habitares en su tierra,",
      "30": "Guárdate que no tropieces en pos de ellas, después que fueren destruídas delante de ti: no preguntes acerca de sus dioses, diciendo: De la manera que servían aquellas gentes á sus dioses, así haré yo también.",
      "31": "No harás así á Jehová tu Dios; porque todo lo que Jehová aborrece, hicieron ellos á sus dioses; pues aun á sus hijos é hijas quemaban en el fuego á sus dioses.",
      "32": "Cuidaréis de hacer todo lo que yo os mando: no añadirás á ello, ni quitarás de ello."
    },
    "13": {
      "1": "CUANDO se levantare en medio de ti profeta, ó soñador de sueños, y te diere señal ó prodigio,",
      "2": "Y acaeciere la señal ó prodigio que él te dijo, diciendo: Vamos en pos de dioses ajenos, que no conociste, y sirvámosles;",
      "3": "No darás oído á las palabras de tal profeta, ni al tal soñador de sueños: porque Jehová vuestro Dios os prueba, para saber si amáis á Jehová vuestro Dios con todo vuestro corazón, y con toda vuestra alma.",
      "4": "En pos de Jehová vuestro Dios andaréis, y á él temeréis, y guardaréis sus mandamientos, y escucharéis su voz, y á él serviréis, y á él os allegaréis.",
      "5": "Y el tal profeta ó soñador de sueños, ha de ser muerto; por cuanto trató de rebelión contra Jehová vuestro Dios, que te sacó de tierra de Egipto, y te rescató de casa de siervos, y de echarte del camino por el que Jehová tu Dios te mandó que anduvieses: y así quitarás el mal de en medio de ti.",
      "6": "Cuando te incitare tu hermano, hijo de tu madre, ó tu hijo, ó tu hija, ó la mujer de tu seno, ó tu amigo que sea como tu alma, diciendo en secreto: Vamos y sirvamos á dioses ajenos, que ni tú ni tus padres conocisteis,",
      "7": "De los dioses de los pueblos que están en vuestros alrededores cercanos á ti, ó lejos de ti, desde el un cabo de la tierra hasta el otro cabo de ella;",
      "8": "No consentirás con él, ni le darás oído; ni tu ojo le perdonará, ni tendrás compasión, ni lo encubrirás:",
      "9": "Antes has de matarlo; tu mano será primero sobre él para matarle, y después la mano de todo el pueblo.",
      "10": "Y has de apedrearlo con piedras, y morirá; por cuanto procuró apartarte de Jehová tu Dios, que te sacó de tierra de Egipto, de casa de siervos:",
      "11": "Para que todo Israel oiga, y tema, y no tornen á hacer cosa semejante á esta mala cosa en medio de ti.",
      "12": "Cuando oyeres de alguna de tus ciudades que Jehová tu Dios te da para que mores en ellas, que se dice:",
      "13": "Hombres, hijos de impiedad, han salido de en medio de ti, que han instigado á los moradores de su ciudad, diciendo: Vamos y sirvamos á dioses ajenos, que vosotros no conocisteis;",
      "14": "Tú inquirirás, y buscarás, y preguntarás con diligencia; y si pareciere verdad, cosa cierta, que tal abominación se hizo en medio de ti,",
      "15": "Irremisiblemente herirás á filo de espada los moradores de aquella ciudad, destruyéndola con todo lo que en ella hubiere, y también sus bestias á filo de espada.",
      "16": "Y juntarás todo el despojo de ella en medio de su plaza, y consumirás con fuego la ciudad y todo su despojo, todo ello, á Jehová tu Dios: y será un montón para siempre: nunca más se edificará.",
      "17": "Y no se pegará algo á tu mano del anatema; porque Jehová se aparte del furor de su ira, y te dé mercedes, y tenga misericordia de ti, y te multiplique, como lo juró á tus padres,",
      "18": "Cuando obedecieres á la voz de Jehová tu Dios, guardando todos sus mandamientos que yo te prescribo hoy, para hacer lo recto en ojos de Jehová tu Dios."
    },
    "14": {
      "1": "HIJOS sois de Jehová vuestro Dios: no os sajaréis, ni pondréis calva sobre vuestros ojos por muerto;",
      "2": "Porque eres pueblo santo á Jehová tu Dios, y Jehová te ha escogido para que le seas un pueblo singular de entre todos los pueblos que están sobre la haz de la tierra.",
      "3": "Nada abominable comerás.",
      "4": "Estos son los animales que comeréis: el buey, la oveja, y la cabra,",
      "5": "El ciervo, el corzo, y el búfalo, y el cabrío salvaje, y el unicornio, y buey salvaje, y cabra montés.",
      "6": "Y todo animal de pezuñas, que tiene hendidura de dos uñas, y que rumiare entre los animales, ese comeréis.",
      "7": "Empero estos no comeréis de los que rumian, ó tienen uña hendida: camello, y liebre, y conejo, porque rumian, mas no tienen uña hendida, os serán inmundos;",
      "8": "Ni puerco: porque tiene uña hendida, mas no rumia, os será inmundo. De la carne de éstos no comeréis, ni tocaréis sus cuerpos muertos.",
      "9": "Esto comeréis de todo lo que está en el agua: todo lo que tiene aleta y escama comeréis;",
      "10": "Mas todo lo que no tuviere aleta y escama, no comeréis: inmundo os será.",
      "11": "Toda ave limpia comeréis.",
      "12": "Y estas son de las que no comeréis: el águila, y el azor, y el esmerejón,",
      "13": "Y el ixio, y el buitre, y el milano según su especie,",
      "14": "Y todo cuervo según su especie,",
      "15": "Y el búho, y la lechuza, y el cuclillo, y el halcón según su especie,",
      "16": "Y el herodión, y el cisne, y el ibis,",
      "17": "Y el somormujo, y el calamón, y el corvejón,",
      "18": "Y la cigüeña, y la garza según su especie, y la abubilla, y el murciélago.",
      "19": "Y todo reptil alado os será inmundo: no se comerá.",
      "20": "Toda ave limpia comeréis.",
      "21": "Ninguna cosa mortecina comeréis: al extranjero que está en tus poblaciones la darás, y él la comerá: ó véndela al extranjero; porque tú eres pueblo santo á Jehová tu Dios. No cocerás el cabrito en la leche de su madre.",
      "22": "Indispensablemente diezmarás todo el producto de tu simiente, que rindiere el campo cada un año.",
      "23": "Y comerás delante de Jehová tu Dios en el lugar que él escogiere para hacer habitar allí su nombre, el diezmo de tu grano, de tu vino, y de tu aceite, y los primerizos de tus manadas, y de tus ganados, para que aprendas á temer á Jehová tu Dios todos los días.",
      "24": "Y si el camino fuere tan largo que tú no puedas llevarlo por él, por estar lejos de ti el lugar que Jehová tu Dios hubiere escogido para poner en él su nombre, cuando Jehová tu Dios te bendijere,",
      "25": "Entonces venderlo has, y atarás el dinero en tu mano, y vendrás al lugar que Jehová tu Dios escogiere;",
      "26": "Y darás el dinero por todo lo que deseare tu alma, por vacas, ó por ovejas, ó por vino, ó por sidra, ó por cualquier cosa que tu alma te demandare: y comerás allí delante de Jehová tu Dios, y te alegrarás tú y tu familia.",
      "27": "Y no desampararás al Levita que habitare en tus poblaciones; porque no tiene parte ni heredad contigo.",
      "28": "Al cabo de cada tres años sacarás todo el diezmo de tus productos de aquel año, y lo guardarás en tus ciudades:",
      "29": "Y vendrá el Levita, que no tiene parte ni heredad contigo, y el extranjero, y el huérfano, y la viuda, que hubiere en tus poblaciones, y comerán y serán saciados; para que Jehová tu Dios te bendiga en toda obra de tus manos que hicieres."
    },
    "15": {
      "1": "AL cabo de siete años harás remisión.",
      "2": "Y esta es la manera de la remisión: perdonará á su deudor todo aquél que hizo empréstito de su mano, con que obligó á su prójimo: no lo demandará más á su prójimo, ó á su hermano; porque la remisión de Jehová es pregonada.",
      "3": "Del extranjero demandarás el reintegro: mas lo que tu hermano tuviere tuyo, lo perdonará tu mano;",
      "4": "Para que así no haya en ti mendigo; porque Jehová te bendecirá con abundancia en la tierra que Jehová tu Dios te da por heredad para que la poseas,",
      "5": "Si empero escuchares fielmente la voz de Jehová tu Dios, para guardar y cumplir todos estos mandamientos que yo te intimo hoy.",
      "6": "Ya que Jehová tu Dios te habrá bendecido, como te ha dicho, prestarás entonces á muchas gentes, mas tú no tomarás prestado; y enseñorearte has de muchas gentes, pero de ti no se enseñorearán.",
      "7": "Cuando hubiere en ti menesteroso de alguno de tus hermanos en alguna de tus ciudades, en tu tierra que Jehová tu Dios te da, no endurecerás tu corazón, ni cerrarás tu mano á tu hermano pobre:",
      "8": "Mas abrirás á él tu mano liberalmente, y en efecto le prestarás lo que basta, lo que hubiere menester.",
      "9": "Guárdate que no haya en tu corazón perverso pensamiento, diciendo: Cerca está el año séptimo, el de la remisión; y tu ojo sea maligno sobre tu hermano menesteroso para no darle: que él podrá clamar contra ti á Jehová, y se te imputará á pecado.",
      "10": "Sin falta le darás, y no sea tu corazón maligno cuando le dieres: que por ello te bendecirá Jehová tu Dios en todos tus hechos, y en todo lo que pusieres mano.",
      "11": "Porque no faltarán menesterosos de en medio de la tierra; por eso yo te mando, diciendo: Abrirás tu mano á tu hermano, á tu pobre, y á tu menesteroso en tu tierra.",
      "12": "Cuando se vendiere á ti tu hermano Hebreo ó Hebrea, y te hubiere servido seis años, al séptimo año le despedirás libre de ti.",
      "13": "Y cuando lo despidieres libre de ti, no lo enviarás vacío:",
      "14": "Le abastecerás liberalmente de tus ovejas, de tu era, y de tu lagar; le darás de aquello en que Jehová te hubiere bendecido.",
      "15": "Y te acordarás que fuiste siervo en la tierra de Egipto, y que Jehová tu Dios te rescató: por tanto yo te mando esto hoy.",
      "16": "Y será que, si él te dijere: No saldré de contigo; porque te ama á ti y á tu casa, que le va bien contigo;",
      "17": "Entonces tomarás una lesna, y horadarás su oreja junto á la puerta, y será tu siervo para siempre: así también harás á tu criada.",
      "18": "No te parezca duro cuando le enviares libre de ti; que doblado del salario de mozo jornalero te sirvió seis años: y Jehová tu Dios te bendecirá en todo cuanto hicieres.",
      "19": "Santificarás á Jehová tu Dios todo primerizo macho que nacerá de tus vacas y de tus ovejas: no te sirvas del primerizo de tus vacas, ni trasquiles el primerizo de tus ovejas.",
      "20": "Delante de Jehová tu Dios los comerás cada un año, tú y tu familia, en el lugar que Jehová escogiere.",
      "21": "Y si hubiere en él tacha, ciego ó cojo, ó cualquiera mala falta, no lo sacrificarás á Jehová tu Dios.",
      "22": "En tus poblaciones lo comerás: el inmundo lo mismo que el limpio comerán de él, como de un corzo ó de un ciervo.",
      "23": "Solamente que no comas su sangre: sobre la tierra la derramarás como agua."
    },
    "16": {
      "1": "GUARDARAS el mes de Abib, y harás pascua á Jehová tu Dios: porque en el mes de Abib te sacó Jehová tu Dios de Egipto de noche.",
      "2": "Y sacrificarás la pascua á Jehová tu Dios, de las ovejas y de las vacas, en el lugar que Jehová escogiere para hacer habitar allí su nombre.",
      "3": "No comerás con ella leudo; siete días comerás con ella pan por leudar, pan de aflicción, porque apriesa saliste de tierra de Egipto: para que te acuerdes del día en que saliste de la tierra de Egipto todos los días de tu vida.",
      "4": "Y no se dejará ver levadura contigo en todo tu término por siete días; y de la carne que matares á la tarde del primer día, no quedará hasta la mañana.",
      "5": "No podrás sacrificar la pascua en ninguna de tus ciudades, que Jehová tu Dios te da;",
      "6": "Sino en el lugar que Jehová tu Dios escogiere para hacer habitar allí su nombre, sacrificarás la pascua por la tarde á puesta del sol, al tiempo que saliste de Egipto:",
      "7": "Y la asarás y comerás en el lugar que Jehová tu Dios hubiere escogido; y por la mañana te volverás y restituirás á tu morada.",
      "8": "Seis días comerás ázimos, y el séptimo día será solemnidad á Jehová tu Dios: no harás obra en él.",
      "9": "Siete semanas te contarás: desde que comenzare la hoz en las mieses comenzarás á contarte las siete semanas.",
      "10": "Y harás la solemnidad de las semanas á Jehová tu Dios: de la suficiencia voluntaria de tu mano será lo que dieres, según Jehová tu Dios te hubiere bendecido.",
      "11": "Y te alegrarás delante de Jehová tu Dios, tú, y tu hijo, y tu hija, y tu siervo, y tu sierva, y el Levita que estuviere en tus ciudades, y el extranjero, y el huérfano, y la viuda, que estuvieren en medio de ti, en el lugar que Jehová tu Dios hubiere escogido para hacer habitar allí su nombre.",
      "12": "Y acuérdate que fuiste siervo en Egipto; por tanto guardarás y cumplirás estos estatutos.",
      "13": "La solemnidad de las cabañas harás por siete días, cuando hubieres hecho la cosecha de tu era y de tu lagar.",
      "14": "Y te alegrarás en tus solemnidades, tú, y tu hijo, y tu hija, y tu siervo, y tu sierva, y el Levita, y el extranjero, y el huérfano, y la viuda, que están en tus poblaciones.",
      "15": "Siete días celebrarás solemnidad á Jehová tu Dios en el lugar que Jehová escogiere; porque te habrá bendecido Jehová tu Dios en todos tus frutos, y en toda obra de tus manos, y estarás ciertamente alegre.",
      "16": "Tres veces cada un año parecerá todo varón tuyo delante de Jehová tu Dios en el lugar que él escogiere: en la solemnidad de los ázimos, y en la solemnidad de las semanas, y en la solemnidad de las cabañas. Y no parecerá vacío delante de Jehová:",
      "17": "Cada uno con el don de su mano, conforme á la bendición de Jehová tu Dios, que te hubiere dado.",
      "18": "Jueces y alcaldes te pondrás en todas tus ciudades que Jehová tu Dios te dará en tus tribus, los cuales juzgarán al pueblo con justo juicio.",
      "19": "No tuerzas el derecho; no hagas acepción de personas, ni tomes soborno; porque el soborno ciega los ojos de los sabios, y pervierte las palabras de los justos.",
      "20": "La justicia, la justicia seguirás, porque vivas y heredes la tierra que Jehová tu Dios te da.",
      "21": "No te plantarás bosque de ningún árbol cerca del altar de Jehová tu Dios, que tú te habrás hecho.",
      "22": "Ni te levantarás estatua; lo cual aborrece Jehová tu Dios."
    },
    "17": {
      "1": "NO sacrificarás á Jehová tu Dios buey, ó cordero, en el cual haya falta ó alguna cosa mala: porque es abominación á Jehová tu Dios.",
      "2": "Cuando se hallare entre ti, en alguna de tus ciudades que Jehová tu Dios te da, hombre, ó mujer, que haya hecho mal en ojos de Jehová tu Dios traspasando su pacto,",
      "3": "Que hubiere ido y servido á dioses ajenos, y se hubiere inclinado á ellos, ora al sol, ó á la luna, ó á todo el ejército del cielo, lo cual yo no he mandado;",
      "4": "Y te fuere dado aviso, y, después que oyeres y hubieres indagado bien, la cosa parece de verdad cierta, que tal abominación ha sido hecha en Israel;",
      "5": "Entonces sacarás al hombre ó mujer que hubiere hecho esta mala cosa, á tus puertas, hombre ó mujer, y los apedrearás con piedras, y así morirán.",
      "6": "Por dicho de dos testigos, ó de tres testigos, morirá el que hubiere de morir; no morirá por el dicho de un solo testigo.",
      "7": "La mano de los testigos será primero sobre él para matarlo, y después la mano de todo el pueblo: así quitarás el mal de en medio de ti.",
      "8": "Cuando alguna cosa te fuere oculta en juicio entre sangre y sangre, entre causa y causa, y entre llaga y llaga, en negocios de litigio en tus ciudades; entonces te levantarás y recurrirás al lugar que Jehová tu Dios escogiere;",
      "9": "Y vendrás á los sacerdotes Levitas, y al juez que fuere en aquellos días, y preguntarás; y te enseñarán la sentencia del juicio.",
      "10": "Y harás según la sentencia que te indicaren los del lugar que Jehová escogiere, y cuidarás de hacer según todo lo que te manifestaren.",
      "11": "Según la ley que ellos te enseñaren, y según el juicio que te dijeren, harás: no te apartarás ni á diestra ni á siniestra de la sentencia que te mostraren.",
      "12": "Y el hombre que procediere con soberbia, no obedeciendo al sacerdote que está para ministrar allí delante de Jehová tu Dios, ó al juez, el tal varón morirá: y quitarás el mal de Israel.",
      "13": "Y todo el pueblo oirá, y temerá, y no se ensoberbecerán más.",
      "14": "Cuando hubieres entrado en la tierra que Jehová tu Dios te da, y la poseyeres, y habitares en ella, y dijeres: Pondré rey sobre mí, como todas las gentes que están en mis alrededores;",
      "15": "Sin duda pondrás por rey sobre ti al que Jehová tu Dios escogiere: de entre tus hermanos pondrás rey sobre ti: no podrás poner sobre ti hombre extranjero, que no sea tu hermano.",
      "16": "Empero que no se aumente caballos, ni haga volver el pueblo á Egipto para acrecentar caballos: porque Jehová os ha dicho: No procuraréis volver más por este camino.",
      "17": "Ni aumentará para sí mujeres, porque su corazón no se desvíe: ni plata ni oro acrecentará para sí en gran copia.",
      "18": "Y será, cuando se asentare sobre el solio de su reino, que ha de escribir para sí en un libro un traslado de esta ley, del original de delante de los sacerdotes Levitas;",
      "19": "Y lo tendrá consigo, y leerá en él todos los días de su vida, para que aprenda á temer á Jehová su Dios, para guardar todas las palabras de aquesta ley y estos estatutos, para ponerlos por obra:",
      "20": "Para que no se eleve su corazón sobre sus hermanos, ni se aparte del mandamiento á diestra ni á siniestra: á fin que prolongue sus días en su reino, él y sus hijos, en medio de Israel."
    },
    "18": {
      "1": "LOS sacerdotes Levitas, toda la tribu de Leví, no tendrán parte ni heredad con Israel; de las ofrendas encendidas á Jehová, y de la heredad de él comerán.",
      "2": "No tendrán, pues, heredad entre sus hermanos: Jehová es su heredad, como él les ha dicho.",
      "3": "Y este será el derecho de los sacerdotes de parte del pueblo, de los que ofrecieren en sacrificio buey ó cordero: darán al sacerdote la espalda, y las quijadas, y el cuajar.",
      "4": "Las primicias de tu grano, de tu vino, y de tu aceite, y las primicias de la lana de tus ovejas le darás:",
      "5": "Porque le ha escogido Jehová tu Dios de todas tus tribus, para que esté para ministrar al nombre de Jehová, él y sus hijos para siempre.",
      "6": "Y cuando el Levita saliere de alguna de tus ciudades de todo Israel, donde hubiere peregrinado, y viniere con todo deseo de su alma al lugar que Jehová escogiere,",
      "7": "Ministrará al nombre de Jehová su Dios, como todos sus hermanos los Levitas que estuvieren allí delante de Jehová.",
      "8": "Porción como la porción de los otros comerán, además de sus patrimonios.",
      "9": "Cuando hubieres entrado en la tierra que Jehová tu Dios te da, no aprenderás á hacer según las abominaciones de aquellas gentes.",
      "10": "No sea hallado en ti quien haga pasar su hijo ó su hija por el fuego, ni practicante de adivinaciones, ni agorero, ni sortílego, ni hechicero,",
      "11": "Ni fraguador de encantamentos, ni quien pregunte á pitón, ni mágico, ni quien pregunte á los muertos.",
      "12": "Porque es abominación á Jehová cualquiera que hace estas cosas, y por estas abominaciones Jehová tu Dios las echó de delante de ti.",
      "13": "Perfecto serás con Jehová tu Dios.",
      "14": "Porque estas gentes que has de heredar, á agoreros y hechiceros oían: mas tú, no así te ha dado Jehová tu Dios.",
      "15": "Profeta de en medio de ti, de tus hermanos, como yo, te levantará Jehová tu Dios: á él oiréis:",
      "16": "Conforme á todo lo que pediste á Jehová tu Dios en Horeb el día de la asamblea, diciendo: No vuelva yo á oir la voz de Jehová mi Dios, ni vea yo más este gran fuego, porque no muera.",
      "17": "Y Jehová me dijo: Bien han dicho.",
      "18": "Profeta les suscitaré de en medio de sus hermanos, como tú; y pondré mis palabras en su boca, y él les hablará todo lo que yo le mandare.",
      "19": "Mas será, que cualquiera que no oyere mis palabras que él hablare en mi nombre, yo le residenciaré.",
      "20": "Empero el profeta que presumiere hablar palabra en mi nombre, que yo no le haya mandado hablar, ó que hablare en nombre de dioses ajenos, el tal profeta morirá.",
      "21": "Y si dijeres en tu corazón: ¿Cómo conoceremos la palabra que Jehová no hubiere hablado?",
      "22": "Cuando el profeta hablare en nombre de Jehová, y no fuere la tal cosa, ni viniere, es palabra que Jehová no ha hablado: con soberbia la habló aquel profeta: no tengas temor de él."
    },
    "19": {
      "1": "CUANDO Jehová tu Dios talare las gentes, cuya tierra Jehová tu Dios te da á ti, y tú las heredares, y habitares en sus ciudades, y en sus casas;",
      "2": "Te apartarás tres ciudades en medio de tu tierra que Jehová tu Dios te da para que la poseas.",
      "3": "Arreglarte has el camino, y dividirás en tres partes el término de tu tierra, que Jehová tu Dios te dará en heredad, y será para que todo homicida se huya allí.",
      "4": "Y este es el caso del homicida que ha de huir allí, y vivirá: el que hiriere á su prójimo por yerro, que no le tenía enemistad desde ayer ni antes de ayer:",
      "5": "Como el que fué con su prójimo al monte á cortar leña, y poniendo fuerza con su mano en el hacha para cortar algún leño, saltó el hierro del cabo, y encontró á su prójimo, y murió; aquél huirá á una de aquestas ciudades, y vivirá;",
      "6": "No sea que el pariente del muerto vaya tras el homicida, cuando se enardeciere su corazón, y le alcance por ser largo el camino, y le hiera de muerte, no debiendo ser condenado á muerte; por cuanto no tenía enemistad desde ayer ni antes de ayer con el muerto.",
      "7": "Por tanto yo te mando, diciendo: Tres ciudades te apartarás.",
      "8": "Y si Jehová tu Dios ensanchare tu término, como lo juró á tus padres, y te diere toda la tierra que dijo á tus padres que había de dar;",
      "9": "Cuando guardases todos estos mandamientos, que yo te prescribo hoy, para ponerlos por obra, que ames á Jehová tu Dios y andes en sus caminos todos los días, entonces añadirás tres ciudades á más de estas tres;",
      "10": "Porque no sea derramada sangre inocente en medio de tu tierra, que Jehová tu Dios te da por heredad, y sea sobre ti sangre.",
      "11": "Mas cuando hubiere alguno que aborreciere á su prójimo, y lo acechare, y se levantare sobre él, y lo hiriere de muerte, y muriere, y huyere á alguna de estas ciudades;",
      "12": "Entonces los ancianos de su ciudad enviarán y lo sacarán de allí, y entregarlo han en mano del pariente del muerto, y morirá.",
      "13": "No le perdonará tu ojo: y quitarás de Israel la sangre inocente, y te irá bien.",
      "14": "No reducirás el término de tu prójimo, el cual señalaron los antiguos en tu heredad, la que poseyeres en la tierra que Jehová tu Dios te da para que la poseas.",
      "15": "No valdrá un testigo contra ninguno en cualquier delito, ó en cualquier pecado, en cualquier pecado que se cometiere. En el dicho de dos testigos, ó en el dicho de tres testigos consistirá el negocio.",
      "16": "Cuando se levantare testigo falso contra alguno, para testificar contra él rebelión,",
      "17": "Entonces los dos hombres litigantes se presentarán delante de Jehová, delante de los sacerdotes y jueces que fueren en aquellos días:",
      "18": "Y los jueces inquirirán bien, y si pareciere ser aquél testigo falso, que testificó falsamente contra su hermano,",
      "19": "Haréis á él como él pensó hacer á su hermano: y quitarás el mal de en medio de ti.",
      "20": "Y los que quedaren oirán, y temerán, y no volverán más á hacer una mala cosa como ésta, en medio de ti.",
      "21": "Y no perdonará tu ojo: vida por vida, ojo por ojo, diente por diente, mano por mano, pie por pie."
    },
    "20": {
      "1": "CUANDO salieres á la guerra contra tus enemigos, y vieres caballos y carros, un pueblo más grande que tú, no tengas temor de ellos, que Jehová tu Dios es contigo, el cual te sacó de tierra de Egipto.",
      "2": "Y será que, cuando os acercareis para combatir, llegaráse el sacerdote, y hablará al pueblo,",
      "3": "Y les dirá: Oye, Israel, vosotros os juntáis hoy en batalla contra vuestros enemigos: no se ablande vuestro corazón, no temáis, no os azoréis, ni tampoco os desalentéis delante de ellos;",
      "4": "Que Jehová vuestro Dios anda con vosotros, para pelear por vosotros contra vuestros enemigos, para salvaros.",
      "5": "Y los oficiales hablarán al pueblo, diciendo: ¿Quién ha edificado casa nueva, y no la ha estrenado? Vaya, y vuélvase á su casa, porque quizá no muera en la batalla, y otro alguno la estrene.",
      "6": "¿Y quién ha plantado viña, y no ha hecho común uso de ella? Vaya, y vuélvase á su casa, porque quizá no muera en la batalla, y otro alguno la goce.",
      "7": "¿Y quién se ha desposado con mujer, y no la ha tomado? Vaya, y vuélvase á su casa, porque quizá no muera en la batalla, y algún otro la tome.",
      "8": "Y tornarán los oficiales á hablar al pueblo, y dirán: ¿Quién es hombre medroso y tierno de corazón? Vaya, y vuélvase á su casa, y no apoque el corazón de sus hermanos, como su corazón.",
      "9": "Y será que, cuando los oficiales acabaren de hablar al pueblo, entonces los capitanes de los ejércitos mandarán delante del pueblo.",
      "10": "Cuando te acercares á una ciudad para combatirla, le intimarás la paz.",
      "11": "Y será que, si te respondiere, Paz, y te abriere, todo el pueblo que en ella fuere hallado te serán tributarios, y te servirán.",
      "12": "Mas si no hiciere paz contigo, y emprendiere contigo guerra, y la cercares,",
      "13": "Luego que Jehová tu Dios la entregare en tu mano, herirás á todo varón suyo á filo de espada.",
      "14": "Solamente las mujeres y los niños, y los animales, y todo lo que hubiere en la ciudad, todos sus despojos, tomarás para ti: y comerás del despojo de tus enemigos, los cuales Jehová tu Dios te entregó.",
      "15": "Así harás á todas la ciudades que estuvieren muy lejos de ti, que no fueren de las ciudades de estas gentes.",
      "16": "Empero de las ciudades de estos pueblos que Jehová tu Dios te da por heredad, ninguna persona dejarás con vida;",
      "17": "Antes del todo los destruirás: al Hetheo, y al Amorrheo, y al Cananeo, y al Pherezeo, y al Heveo, y al Jebuseo; como Jehová tu Dios te ha mandado:",
      "18": "Porque no os enseñen á hacer según todas sus abominaciones, que ellos hacen á sus dioses, y pequéis contra Jehová vuestro Dios.",
      "19": "Cuando pusieres cerco á alguna ciudad, peleando contra ella muchos días para tomarla, no destruyas su arboleda metiendo en ella hacha, porque de ella comerás; y no la talarás, que no es hombre el árbol del campo para venir contra ti en el cerco.",
      "20": "Mas el árbol que supieres que no es árbol para comer, lo destruirás y lo talarás, y construye baluarte contra la ciudad que pelea contigo, hasta sojuzgarla."
    },
    "21": {
      "1": "CUANDO fuere hallado en la tierra que Jehová tu Dios te da para que la poseas, muerto echado en el campo, y no se supiere quién lo hirió,",
      "2": "Entonces tus ancianos y tus jueces saldrán y medirán hasta las ciudades que están alrededor del muerto:",
      "3": "Y será, que los ancianos de aquella ciudad, de la ciudad más cercana al muerto, tomarán de la vacada una becerra que no haya servido, que no haya traído yugo;",
      "4": "Y los ancianos de aquella ciudad traerán la becerra á un valle áspero, que nunca haya sido arado ni sembrado, y cortarán el pescuezo á la becerra allí en el valle.",
      "5": "Entonces vendrán los sacerdotes hijos de Leví, porque á ellos escogió Jehová tu Dios para que le sirvan, y para bendecir en nombre de Jehová; y por el dicho de ellos se determinará todo pleito y toda llaga.",
      "6": "Y todos los ancianos de aquella ciudad más cercana al muerto lavarán sus manos sobre la becerra degollada en el valle.",
      "7": "Y protestarán, y dirán: Nuestras manos no han derramado esta sangre, ni nuestros ojos lo vieron.",
      "8": "Expía á tu pueblo Israel, al cual redimiste, oh Jehová; y no imputes la sangre inocente derramada en medio de tu pueblo Israel. Y la sangre les será perdonada.",
      "9": "Y tú quitarás la culpa de sangre inocente de en medio de ti, cuando hicieres lo que es recto en los ojos de Jehová.",
      "10": "Cuando salieres á la guerra contra tus enemigos, y Jehová tu Dios los entregare en tu mano, y tomares de ellos cautivos,",
      "11": "Y vieres entre los cautivos alguna mujer hermosa, y la codiciares, y la tomares para ti por mujer,",
      "12": "La meterás en tu casa; y ella raerá su cabeza, y cortará sus uñas,",
      "13": "Y se quitará el vestido de su cautiverio, y quedaráse en tu casa: y llorará á su padre y á su madre el tiempo de un mes: y después entrarás á ella, y tu serás su marido, y ella tu mujer.",
      "14": "Y será, si no te agradare, que la has de dejar en su libertad; y no la venderás por dinero, ni mercadearás con ella, por cuanto la afligiste.",
      "15": "Cuando un hombre tuviere dos mujeres, la una amada y la otra aborrecida, y la amada y la aborrecida le parieren hijos, y el hijo primogénito fuere de la aborrecida;",
      "16": "Será que, el día que hiciere heredar á sus hijos lo que tuviere, no podrá dar el derecho de primogenitura á los hijos de la amada en preferencia al hijo de la aborrecida, que es el primogénito;",
      "17": "Mas al hijo de la aborrecida reconocerá por primogénito, para darle dos tantos de todo lo que se hallare que tiene: porque aquél es el principio de su fuerza, el derecho de la primogenitura es suyo.",
      "18": "Cuando alguno tuviere hijo contumaz y rebelde, que no obedeciere á la voz de su padre ni á la voz de su madre, y habiéndolo castigado, no les obedeciere;",
      "19": "Entonces tomarlo han su padre y su madre, y lo sacarán á los ancianos de su ciudad, y á la puerta del lugar suyo;",
      "20": "Y dirán á los ancianos de la ciudad: Este nuestro hijo es contumaz y rebelde, no obedece á nuestra voz; es glotón y borracho.",
      "21": "Entonces todos los hombres de su ciudad lo apedrearán con piedras, y morirá: así quitarás el mal de en medio de ti; y todo Israel oirá, y temerá.",
      "22": "Cuando en alguno hubiere pecado de sentencia de muerte, por el que haya de morir, y le habrás colgado de un madero,",
      "23": "No estará su cuerpo por la noche en el madero, mas sin falta lo enterrarás el mismo día, porque maldición de Dios es el colgado: y no contaminarás tu tierra, que Jehová tu Dios te da por heredad."
    }
  }
};

