
	
export const bib_verses = {
  "acts": {
    "21": {
      "1": "Y HABIENDO partido de ellos, navegamos y vinimos camino derecho á Coos, y al día siguiente á Rhodas, y de allí á Pátara.",
      "2": "Y hallando un barco que pasaba á Fenicia, nos embarcamos, y partimos.",
      "3": "Y como avistamos á Cipro, dejándola á mano izquierda, navegamos á Siria, y vinimos á Tiro: porque el barco había de descargar allí su carga.",
      "4": "Y nos quedamos allí siete días, hallados los discípulos, los cuales decían á Pablo por Espíritu, que no subiese á Jerusalem.",
      "5": "Y cumplidos aquellos días, salimos acompañándonos todos, con sus mujeres é hijos, hasta fuera de la ciudad; y puestos de rodillas en la ribera, oramos.",
      "6": "Y abrazándonos los unos á los otros, subimos al barco, y ellos se volvieron á sus casas.",
      "7": "Y nosotros, cumplida la navegación, vinimos de Tiro á Tolemaida; y habiendo saludado á los hermanos, nos quedamos con ellos un día.",
      "8": "Y otro día, partidos Pablo y los que con él estábamos, vinimos á Cesarea: y entrando en casa de Felipe el evangelista, él cual era uno de los siete, posamos con él.",
      "9": "Y éste tenía cuatro hijas, doncellas, que profetizaban.",
      "10": "Y parando nosotros allí por muchos días, descendió de Judea un profeta, llamado Agabo;",
      "11": "Y venido á nosotros, tomó el cinto de Pablo, y atándose los pies y las manos, dijo: Esto dice el Espíritu Santo: Así atarán los Judíos en Jerusalem al varón cuyo es este cinto, y le entregarán en manos de los Gentiles.",
      "12": "Lo cual como oímos, le rogamos nosotros y los de aquel lugar, que no subiese á Jerusalem.",
      "13": "Entonces Pablo respondió: ¿Qué hacéis llorando y afligiéndome el corazón? porque yo no sólo estoy presto á ser atado, mas aun á morir en Jerusalem por el nombre del Señor Jesús.",
      "14": "Y como no le pudimos persuadir, desistimos, diciendo: Hágase la voluntad del Señor.",
      "15": "Y después de estos días, apercibidos, subimos á Jerusalem.",
      "16": "Y vinieron también con nosotros de Cesarea algunos de los discípulos, trayendo consigo á un Mnasón, Cyprio, discípulo antiguo, con el cual posásemos.",
      "17": "Y cuando llegamos á Jerusalem, los hermanos nos recibieron de buena voluntad.",
      "18": "Y al día siguiente Pablo entró con nosotros á Jacobo, y todos los ancianos se juntaron;",
      "19": "A los cuales, como los hubo saludado, contó por menudo lo que Dios había hecho entre los Gentiles por su ministerio.",
      "20": "Y ellos como lo oyeron, glorificaron á Dios, y le dijeron: Ya ves, hermano, cuántos millares de Judíos hay que han creído; y todos son celadores de la ley:",
      "21": "Mas fueron informados acerca de ti, que enseñas á apartarse de Moisés á todos los Judíos que están entre los Gentiles, diciéndoles que no han de circuncidar á los hijos, ni andar según la costumbre.",
      "22": "¿Qué hay pues? La multitud se reunirá de cierto: porque oirán que has venido.",
      "23": "Haz pues esto que te decimos: Hay entre nosotros cuatro hombres que tienen voto sobre sí:",
      "24": "Tomando á éstos contigo, purifícate con ellos, y gasta con ellos, para que rasuren sus cabezas, y todos entiendan que no hay nada de lo que fueron informados acerca de ti; sino que tú también andas guardando la ley.",
      "25": "Empero cuanto á los que de los Gentiles han creído, nosotros hemos escrito haberse acordado que no guarden nada de esto; solamente que se abstengan de lo que fue sacrificado á los ídolos, y de sangre, y de ahogado, y de fornicación.",
      "26": "Entonces Pablo tomó consigo aquellos hombres, y al día siguiente, habiéndose purificado con ellos, entró en el templo, para anunciar el cumplimiento de los días de la purificación, hasta ser ofrecida ofrenda por cada uno de ellos.",
      "27": "Y cuando estaban para acabarse los siete días, unos Judíos de Asia, como le vieron en el templo, alborotaron todo el pueblo y le echaron mano,",
      "28": "Dando voces: Varones Israelitas, ayudad: Este es el hombre que por todas partes enseña á todos contra el pueblo, y la ley, y este lugar; y además de esto ha metido Gentiles en el templo, y ha contaminado este lugar Santo.",
      "29": "Porque antes habían visto con él en la ciudad á Trófimo, Efesio, al cual pensaban que Pablo había metido en el templo.",
      "30": "Así que, toda la ciudad se alborotó, y agolpóse el pueblo; y tomando á Pablo, hiciéronle salir fuera del templo, y luego las puertas fueron cerradas.",
      "31": "Y procurando ellos matarle, fué dado aviso al tribuno de la compañía, que toda la ciudad de Jerusalem estaba alborotada;",
      "32": "El cual tomando luego soldados y centuriones, corrió á ellos. Y ellos como vieron al tribuno y á los soldados, cesaron de herir á Pablo.",
      "33": "Entonces llegando el tribuno, le prendió, y le mandó atar con dos cadenas; y preguntó quién era, y qué había hecho.",
      "34": "Y entre la multitud, unos gritaban una cosa, y otros otra: y como no podía entender nada de cierto á causa del alboroto, le mandó llevar á la fortaleza.",
      "35": "Y como llegó á las gradas, aconteció que fué llevado de los soldados á causa de la violencia del pueblo;",
      "36": "Porque multitud de pueblo venía detrás, gritando: Mátale.",
      "37": "Y como comenzaron á meter á Pablo en la fortaleza, dice al tribuno: ¿Me será lícito hablarte algo? Y él dijo: ¿Sabes griego?",
      "38": "¿No eres tú aquel Egipcio que levantaste una sedición antes de estos días, y sacaste al desierto cuatro mil hombres salteadores?",
      "39": "Entonces dijo Pablo: Yo de cierto soy hombre Judío, ciudadano de Tarso, ciudad no obscura de Cilicia: empero ruégote que me permitas que hable al pueblo.",
      "40": "Y como él se lo permitió, Pablo, estando en pie en las gradas, hizo señal con la mano al pueblo. Y hecho grande silencio, habló en lengua hebrea, diciendo:"
    },
    "22": {
      "1": "VARONES hermanos y padres, oid la razón que ahora os doy.",
      "2": "(Y como oyeron que les hablaba en lengua hebrea, guardaron más silencio.) Y dijo:",
      "3": "Yo de cierto soy Judío, nacido en Tarso de Cilicia, mas criado en esta ciudad á los pies de Gamaliel, enseñado conforme á la verdad de la ley de la patria, celoso de Dios, como todos vosotros sois hoy.",
      "4": "Que he perseguido este camino hasta la muerte, prendiendo y entregando en cárceles hombres y mujeres:",
      "5": "Como también el príncipe de los sacerdotes me es testigo, y todos los ancianos; de los cuales también tomando letras á los hermanos, iba á Damasco para traer presos á Jerusalem aun á los que estuviesen allí, para que fuesen castigados.",
      "6": "Mas aconteció que yendo yo, y llegando cerca de Damasco, como á medio día, de repente me rodeó mucha luz del cielo:",
      "7": "Y caí en el suelo, y oí una voz que me decía: Saulo, Saulo, ¿por qué me persigues?",
      "8": "Yo entonces respondí: ¿Quién eres, Señor? Y me dijo: Yo soy Jesús de Nazaret, á quién tú persigues.",
      "9": "Y los que estaban conmigo vieron á la verdad la luz, y se espantaron; mas no oyeron la voz del que hablaba conmigo.",
      "10": "Y dije: ¿Qué haré, Señor? Y el Señor me dijo: Levántate, y ve á Damasco, y allí te será dicho todo lo que te está señalado hacer.",
      "11": "Y como yo no viese por causa de la claridad de la luz, llevado de la mano por los que estaban conmigo, vine á Damasco.",
      "12": "Entonces un Ananías, varón pío conforme á la ley, que tenía buen testimonio de todos los Judíos que allí moraban,",
      "13": "Viniendo á mí, y acercándose, me dijo: Hermano Saulo, recibe la vista. Y yo en aquella hora le miré.",
      "14": "Y él dijo: El Dios de nuestros padres te ha predestinado para que conocieses su voluntad, y vieses á aquel Justo, y oyeses la voz de su boca.",
      "15": "Porque has de ser testigo suyo á todos los hombres, de lo que has visto y oído.",
      "16": "Ahora pues, ¿por qué te detienes? Levántate, y bautízate, y lava tus pecados, invocando su nombre.",
      "17": "Y me aconteció, vuelto á Jerusalem, que orando en el templo, fuí arrebatado fuera de mí.",
      "18": "Y le vi que me decía: Date prisa, y sal prestamente fuera de Jerusalem; porque no recibirán tu testimonio de mí.",
      "19": "Y yo dije: Señor, ellos saben que yo encerraba en cárcel, y hería por las sinagogas á los que creían en ti;",
      "20": "Y cuando se derramaba la sangre de Esteban tu testigo, yo también estaba presente, y consentía á su muerte, y guardaba las ropas de los que le mataban.",
      "21": "Y me dijo: Ve, porque yo te tengo que enviar lejos á los Gentiles.",
      "22": "Y le oyeron hasta esta palabra: entonces alzaron la voz, diciendo: Quita de la tierra á un tal hombre, porque no conviene que viva.",
      "23": "Y dando ellos voces, y arrojando sus ropas y echando polvo al aire,",
      "24": "Mandó el tribuno que le llevasen á la fortaleza, y ordenó que fuese examinado con azotes, para saber por qué causa clamaban así contra él.",
      "25": "Y como le ataron con correas, Pablo dijo al centurión que estaba presente: ¿Os es lícito azotar á un hombre Romano sin ser condenado?",
      "26": "Y como el centurión oyó esto, fué y dió aviso al tribuno, diciendo ¿Qué vas á hacer? porque este hombre es Romano.",
      "27": "Y viniendo el tribuno, le dijo: Dime, ¿eres tú Romano? Y él dijo: Sí.",
      "28": "Y respondió el tribuno: Yo con grande suma alcancé esta ciudadanía. Entonces Pablo dijo: Pero yo lo soy de nacimiento.",
      "29": "Así que, luego se apartaron de él los que le habían de atormentar: y aun el tribuno también tuvo temor, entendido que era Romano, por haberle atado.",
      "30": "Y al día siguiente, queriendo saber de cierto la causa por qué era acusado de los Judíos, le soltó de las prisiones, y mandó venir á los príncipes de los sacerdotes, y á todo su concilio: y sacando á Pablo, le presentó delante de ellos."
    },
    "23": {
      "1": "ENTONCES Pablo, poniendo los ojos en el concilio, dice: Varones hermanos, yo con toda buena conciencia he conversado delante de Dios hasta el día de hoy.",
      "2": "El príncipe de los sacerdotes, Ananías, mandó entonces á los que estaban delante de él, que le hiriesen en la boca.",
      "3": "Entonces Pablo le dijo: Herirte ha Dios, pared blanqueada: ¿y estás tú sentado para juzgarme conforme á la ley, y contra la ley me mandas herir?",
      "4": "Y los que estaban presentes dijeron: ¿Al sumo sacerdote de Dios maldices?",
      "5": "Y Pablo dijo: No sabía, hermanos, que era el sumo sacerdote; pues escrito está: Al príncipe de tu pueblo no maldecirás.",
      "6": "Entonces Pablo, sabiendo que la una parte era de Saduceos, y la otra de Fariseos, clamó en el concilio: Varones hermanos, yo soy Fariseo, hijo de Fariseo: de la esperanza y de la resurrección de los muertos soy yo juzgado.",
      "7": "Y como hubo dicho esto, fué hecha disensión entre los Fariseos y los Saduceos; y la multitud fué dividida.",
      "8": "Porque los Saduceos dicen que no hay resurrección, ni ángel, ni espíritu; mas los Fariseos confiesan ambas cosas.",
      "9": "Y levantóse un gran clamor: y levantándose los escribas de la parte de los Fariseos, contendían diciendo: Ningún mal hallamos en este hombre; que si espíritu le ha hablado, ó ángel, no resistamos á Dios.",
      "10": "Y habiendo grande disensión, el tribuno, teniendo temor de que Pablo fuese despedazado de ellos, mandó venir soldados, y arrebatarle de en medio de ellos, y llevarle á la fortaleza.",
      "11": "Y la noche siguiente, presentándosele el Señor, le dijo: Confía, Pablo; que como has testificado de mí en Jerusalem, así es menester testifiques también en Roma.",
      "12": "Y venido el día, algunos de los Judíos se juntaron, é hicieron voto bajo de maldición, diciendo que ni comerían ni beberían hasta que hubiesen muerto á Pablo.",
      "13": "Y eran más de cuarenta los que habían hecho esta conjuración;",
      "14": "Los cuales se fueron á los príncipes de los sacerdotes y á los ancianos, y dijeron: Nosotros hemos hecho voto debajo de maldición, que no hemos de gustar nada hasta que hayamos muerto á Pablo.",
      "15": "Ahora pues, vosotros, con el concilio, requerid al tribuno que le saque mañana á vosotros como que queréis entender de él alguna cosa más cierta; y nosotros, antes que él llegue, estaremos aparejados para matarle.",
      "16": "Entonces un hijo de la hermana de Pablo, oyendo las asechanzas, fué, y entró en la fortaleza, y dió aviso á Pablo.",
      "17": "Y Pablo, llamando á uno de los centuriones, dice: Lleva á este mancebo al tribuno, porque tiene cierto aviso que darle.",
      "18": "El entonces tomándole, le llevó al tribuno, y dijo: El preso Pablo, llamándome, me rogó que trajese á ti este mancebo, que tiene algo que hablarte.",
      "19": "Y el tribuno, tomándole de la mano y retirándose aparte, le preguntó: ¿Qué es lo que tienes que decirme?",
      "20": "Y él dijo: Los Judíos han concertado rogarte que mañana saques á Pablo al concilio, como que han de inquirir de él alguna cosa más cierta.",
      "21": "Mas tú no los creas; porque más de cuarenta hombres de ellos le acechan, los cuales han hecho voto debajo de maldición, de no comer ni beber hasta que le hayan muerto; y ahora están apercibidos esperando tu promesa.",
      "22": "Entonces el tribuno despidió al mancebo, mandándole que á nadie dijese que le había dado aviso de esto.",
      "23": "Y llamados dos centuriones, mandó que apercibiesen para la hora tercia de la noche doscientos soldados, que fuesen hasta Cesarea, y setenta de á caballo, y doscientos lanceros;",
      "24": "Y que aparejasen cabalgaduras en que poniendo á Pablo, le llevasen en salvo á Félix el Presidente.",
      "25": "Y escribió una carta en estos términos:",
      "26": "Claudio Lisias al excelentísimo gobernador Félix: Salud.",
      "27": "A este hombre, aprehendido de los Judíos, y que iban ellos á matar, libré yo acudiendo con la tropa, habiendo entendido que era Romano.",
      "28": "Y queriendo saber la causa por qué le acusaban, le llevé al concilio de ellos:",
      "29": "Y hallé que le acusaban de cuestiones de la ley de ellos, y que ningún crimen tenía digno de muerte ó de prisión.",
      "30": "Mas siéndome dado aviso de asechanzas que le habían aparejado los Judíos, luego al punto le he enviado á ti, intimando también á los acusadores que traten delante de ti lo que tienen contra él. Pásalo bien.",
      "31": "Y los soldados, tomando á Pablo como les era mandado, lleváronle de noche á Antipatris.",
      "32": "Y al día siguiente, dejando á los de á caballo que fuesen con él, se volvieron á la fortaleza.",
      "33": "y como llegaron á Cesarea, y dieron la carta al gobernador, presentaron también á Pablo delante de él.",
      "34": "Y el gobernador, leída la carta, preguntó de qué provincia era; y entendiendo que de Cilicia,",
      "35": "Te oiré, dijo, cuando vinieren tus acusadores. Y mandó que le guardasen en el pretorio de Herodes."
    },
    "24": {
      "1": "Y CINCO días después descendió el sumo sacerdote Ananías, con algunos de los ancianos, y un cierto Tértulo, orador; y parecieron delante del gobernador contra Pablo.",
      "2": "Y citado que fué, Tértulo comenzó á acusar, diciendo: Como por causa tuya vivamos en grande paz, y muchas cosas sean bien gobernadas en el pueblo por tu prudencia,",
      "3": "Siempre y en todo lugar lo recibimos con todo hacimiento de gracias, oh excelentísimo Félix.",
      "4": "Empero por no molestarte más largamente, ruégote que nos oigas brevemente conforme á tu equidad.",
      "5": "Porque hemos hallado que este hombre es pestilencial, y levantador de sediciones entre todos los Judíos por todo el mundo, y príncipe de la secta de los Nazarenos:",
      "6": "El cual también tentó á violar el templo; y prendiéndole, le quisimos juzgar conforme á nuestra ley:",
      "7": "Mas interviniendo el tribuno Lisias, con grande violencia le quitó de nuestras manos,",
      "8": "Mandando á sus acusadores que viniesen á ti; del cual tú mismo juzgando, podrás entender todas estas cosas de que le acusamos.",
      "9": "Y contendían también los Judíos, diciendo ser así estas cosas.",
      "10": "Entonces Pablo, haciéndole el gobernador señal que hablase, respondió: Porque sé que muchos años ha eres gobernador de esta nación, con buen ánimo satisfaré por mí.",
      "11": "Porque tú puedes entender que no hace más de doce días que subí á adorar á Jerusalem;",
      "12": "Y ni me hallaron en el templo disputando con ninguno, ni haciendo concurso de multitud, ni en sinagogas, ni en la ciudad;",
      "13": "Ni te pueden probar las cosas de que ahora me acusan.",
      "14": "Esto empero te confieso, que conforme á aquel Camino que llaman herejía, así sirvo al Dios de mis padres, creyendo todas las cosas que en la ley y en los profetas están escritas;",
      "15": "Teniendo esperanza en Dios que ha de haber resurrección de los muertos, así de justos como de injustos, la cual también ellos esperan.",
      "16": "Y por esto, procuro yo tener siempre conciencia sin remordimiento acerca de Dios y acerca de los hombres.",
      "17": "Mas pasados muchos años, vine á hacer limosnas á mi nación, y ofrendas,",
      "18": "Cuando me hallaron purificado en el templo (no con multitud ni con alboroto) unos Judíos de Asia;",
      "19": "Los cuales debieron comparecer delante de ti, y acusarme, si contra mí tenían algo.",
      "20": "O digan estos mismos si hallaron en mí alguna cosa mal hecha, cuando yo estuve en el concilio,",
      "21": "Si no sea que, estando entre ellos prorrumpí en alta voz: Acerca de la resurrección de los muertos soy hoy juzgado de vosotros.",
      "22": "Entonces Félix, oídas estas cosas, estando bien informado de esta secta, les puso dilación, diciendo: Cuando descendiere el tribuno Lisias acabaré de conocer de vuestro negocio.",
      "23": "Y mandó al centurión que Pablo fuese guardado, y aliviado de las prisiones; y que no vedase á ninguno de sus familiares servirle, ó venir á él.",
      "24": "Y algunos días después, viniendo Félix con Drusila, su mujer, la cual era Judía, llamó á Pablo, y oyó de él la fe que es en Jesucristo.",
      "25": "Y disertando él de la justicia, y de la continencia, y del juicio venidero, espantado Félix, respondió: Ahora vete, mas en teniendo oportunidad te llmaré:",
      "26": "Esperando también con esto, que de parte de Pablo le serían dados dineros, porque le soltase; por lo cual, haciéndole venir muchas veces, hablaba con él.",
      "27": "Mas al cabo de dos años recibió Félix por sucesor á Porcio Festo: y queriendo Félix ganar la gracia de los Judíos, dejó preso á Pablo."
    },
    "25": {
      "1": "FESTO pues, entrado en la provincia, tres días después subió de Cesarea á Jerusalem.",
      "2": "Y vinieron á él los príncipes de los sacerdotes y los principales de los Judíos contra Pablo; y le rogaron,",
      "3": "Pidiendo gracia contra él, que le hiciese traer á Jerusalem, poniendo ellos asechanzas para matarle en el camino.",
      "4": "Mas Festo respondió, que Pablo estaba guardado en Cesarea, y que él mismo partiría presto.",
      "5": "Los que de vosotros pueden, dijo desciendan juntamente; y si hay algún crimen en este varón, acúsenle.",
      "6": "Y deteniéndose entre ellos no más de ocho ó diez días, venido á Cesarea, el siguiente día se sentó en el tribunal, y mandó que Pablo fuese traído.",
      "7": "El cual venido, le rodearon los Judíos que habían venido de Jerusalem, poniendo contra Pablo muchas y graves acusaciones, las cuales no podían probar;",
      "8": "Alegando él por su parte: Ni contra la ley de los Judíos, ni contra el templo, ni contra César he pecado en nada.",
      "9": "Mas Festo, queriendo congraciarse con los Judíos, respondiendo á Pablo, dijo: ¿Quieres subir á Jerusalem, y allá ser juzgado de estas cosas delante de mí?",
      "10": "Y Pablo dijo: Ante el tribunal de César estoy, donde conviene que sea juzgado. A los Judíos no he hecho injuria alguna, como tú sabes muy bien.",
      "11": "Porque si alguna injuria, ó cosa alguna digna de muerte he hecho, no rehuso morir; mas si nada hay de las cosas de que éstos me acusan, nadie puede darme á ellos. A César apelo.",
      "12": "Entonces Festo, habiendo hablado con el consejo, respondió: ¿A César has apelado? á César irás.",
      "13": "Y pasados algunos días, el rey Agripa y Bernice vinieron á Cesarea á saludar á Festo.",
      "14": "Y como estuvieron allí muchos días, Festo declaró la causa de Pablo al rey, diciendo: Un hombre ha sido dejado preso por Félix,",
      "15": "Sobre el cual, cuando fuí á Jerusalem, vinieron á mí los príncipes de los sacerdotes y los ancianos de los Judíos, pidiendo condenación contra él:",
      "16": "A los cuales respondí: no ser costumbre de los Romanos dar alguno á la muerte antes que el que es acusado tenga presentes sus acusadores, y haya lugar de defenderse de la acusación.",
      "17": "Así que, habiendo venido ellos juntos acá, sin ninguna dilación, al día siguiente, sentado en el tribunal, mandé traer al hombre;",
      "18": "Y estando presentes los acusadores, ningún cargo produjeron de los que yo sospechaba:",
      "19": "Solamente tenían contra él ciertas cuestiones acerca de su superstición, y de un cierto Jesús, difunto, el cual Pablo afirmaba que estaba vivo.",
      "20": "Y yo, dudando en cuestión semejante, dije, si quería ir á Jerusalem, y allá ser juzgado de estas cosas.",
      "21": "Mas apelando Pablo á ser guardado al conocimiento de Augusto, mandé que le guardasen hasta que le enviara á César.",
      "22": "Entonces Agripa dijo á Festo: Yo también quisiera oir á ese hombre. Y él dijo: Mañana le oirás.",
      "23": "Y al otro día, viniendo Agripa y Bernice con mucho aparato, y entrando en la audiencia con los tribunos y principales hombres de la ciudad, por mandato de Festo, fué traído Pablo.",
      "24": "Entonces Festo dijo: Rey Agripa, y todos los varones que estáis aquí juntos con nosotros: veis á éste, por el cual toda la multitud de los Judíos me ha demandado en Jerusalem y aquí, dando voces que no conviene que viva más;",
      "25": "Mas yo, hallando que ninguna cosa digna de muerte ha hecho, y él mismo apelando á Augusto, he determinado enviarle:",
      "26": "Del cual no tengo cosa cierta que escriba al señor; por lo que le he sacado á vosotros, y mayormente á tí, oh rey Agripa, para que hecha información, tenga yo qué escribir.",
      "27": "Porque fuera de razón me parece enviar un preso, y no informar de las causas."
    },
    "26": {
      "1": "ENTONCES Agripa dijo á Pablo: Se te permite hablar por ti mismo. Pablo entonces, extendiendo la mano, comenzó á responder por sí, diciendo:",
      "2": "Acerca de todas las cosas de que soy acusado por los Judíos, oh rey Agripa, me tengo por dichoso de que haya hoy de defenderme delante de ti;",
      "3": "Mayormente sabiendo tú todas las costumbres y cuestiones que hay entre los Judíos: por lo cual te ruego que me oigas con paciencia.",
      "4": "Mi vida pues desde la mocedad, la cual desde el principio fué en mi nación, en Jerusalem, todos los Judíos la saben:",
      "5": "Los cuales tienen ya conocido que yo desde el principio, si quieren testificarlo, conforme á la más rigurosa secta de nuestra religión he vivido Fariseo.",
      "6": "Y ahora, por la esperanza de la promesa que hizo Dios á nuestros padres, soy llamado en juicio;",
      "7": "A la cual promesa nuestras doce tribus, sirviendo constantemente de día y de noche, esperan que han de llegar. Por la cual esperanza, oh rey Agripa, soy acusado de los Judíos.",
      "8": "Qué! ¿Júzgase cosa increíble entre vosotros que Dios resucite los muertos?",
      "9": "Yo ciertamente había pensando deber hacer muchas cosas contra el nombre de Jesús de Nazaret:",
      "10": "Lo cual también hice en Jerusalem, y yo encerré en cárcel es á muchos de los santos, recibida potestad de los príncipes de los sacerdotes; y cuando eran matados, yo dí mi voto.",
      "11": "Y muchas veces, castigándolos por todas las sinagogas, los forcé á blasfemar; y enfurecido sobremanera contra ellos, los perseguí hasta en las ciudades extrañas.",
      "12": "En lo cual ocupado, yendo á Damasco con potestad y comisión de los príncipes de los sacerdotes,",
      "13": "En mitad del día, oh rey, vi en el camino una luz del cielo, que sobrepujaba el resplandor del sol, la cual me rodeó y á los que iban conmigo.",
      "14": "Y habiendo caído todos nosotros en tierra, oí una voz que me hablaba, y decía en lengua hebraica: Saulo, Saulo, ¿por qué me persigues? Dura cosa te es dar coces contra los aguijones.",
      "15": "Yo entonces dije: ¿Quién eres, Señor? Y el Señor dijo: Yo soy Jesús, á quien tú persigues.",
      "16": "Mas levántate, y ponte sobre tus pies; porque para esto te he aparecido, para ponerte por ministro y testigo de las cosas que has visto, y de aquellas en que apareceré á ti:",
      "17": "Librándote del pueblo y de los Gentiles, á los cuales ahora te envío,",
      "18": "Para que abras sus ojos, para que se conviertan de las tinieblas á la luz, y de la potestad de Satanás á Dios; para que reciban, por la fe que es en mí, remisión de pecados y suerte entre los santificados.",
      "19": "Por lo cual, oh rey Agripa, no fuí rebelde á la visión celestial:",
      "20": "Antes anuncié primeramente á los que están en Damasco, y Jerusalem, y por toda la tierra de Judea, y á los gentiles, que se arrepintiesen y se convirtiesen á Dios, haciendo obras dignas de arrepentimiento.",
      "21": "Por causa de esto los Judíos, tomándome en el templo, tentaron matarme.",
      "22": "Mas ayudado del auxilio de Dios, persevero hasta el día de hoy, dando testimonio á pequeños y á grandes, no diciendo nada fuera de las cosas que los profetas y Moisés dijeron que habían de venir:",
      "23": "Que Cristo había de padecer, y ser el primero de la resurrección de los muertos, para anunciar luz al pueblo y á los Gentiles.",
      "24": "Y diciendo él estas cosas en su defensa, Festo á gran voz dijo: Estás loco, Pablo: las muchas letras te vuelven loco.",
      "25": "Mas él dijo: No estoy loco, excelentísimo Festo, sino que hablo palabras de verdad y de templanza.",
      "26": "Pues el rey sabe estas cosas, delante del cual también hablo confiadamente. Pues no pienso que ignora nada de esto; pues no ha sido esto hecho en algún rincón.",
      "27": "¿Crees, rey Agripa, á los profetas? Yo sé que crees.",
      "28": "Entonces Agripa dijo á Pablo: Por poco me persuades á ser Cristiano.",
      "29": "Y Pablo dijo: ­Pluguiese á Dios que por poco ó por mucho, no solamente tú, mas también todos los que hoy me oyen, fueseis hechos tales cual yo soy, excepto estas prisiones!",
      "30": "Y como hubo dicho estas cosas, se levantó el rey, y el presidente, y Bernice, y los que se habían sentado con ellos;",
      "31": "Y como se retiraron aparte, hablaban los unos á los otros, diciendo: Ninguna cosa digna ni de muerte, ni de prisión, hace este hombre.",
      "32": "Y Agripa dijo á Festo: Podía este hombre ser suelto, si no hubiera apelado á César."
    },
    "27": {
      "1": "MAS como fué determinado que habíamos de navegar para Italia, entregaron á Pablo y algunos otros presos á un centurión, llamado Julio, de la compañía Augusta.",
      "2": "Así que, embarcándonos en una nave Adrumentina, partimos, estando con nosotros Aristarco, Macedonio de Tesalónica, para navegar junto á los lugares de Asia.",
      "3": "Y otro día llegamos á Sidón; y Julio, tratando á Pablo con humanidad, permitióle que fuese á los amigos, para ser de ellos asistido.",
      "4": "Y haciéndonos á la vela desde allí, navegamos bajo de Cipro, porque los vientos eran contrarios.",
      "5": "Y habiendo pasado la mar de Cilicia y Pamphylia, arribamos á Mira, ciudad de Licia.",
      "6": "Y hallando allí el centurión una nave Alejandrina que navegaba á Italia, nos puso en ella.",
      "7": "Y navegando muchos días despacio, y habiendo apenas llegado delante de Gnido, no dejándonos el viento, navegamos bajo de Creta, junto á Salmón.",
      "8": "Y costeándola difícilmente, llegamos á un lugar que llaman Buenos Puertos, cerca del cual estaba la ciudad de Lasea.",
      "9": "Y pasado mucho tiempo, y siendo ya peligrosa la navegación, porque ya era pasado el ayuno, Pablo amonestaba,",
      "10": "Diciéndoles: Varones, veo que con trabajo y mucho daño, no sólo de la cargazón y de la nave, mas aun de nuestras personas, habrá de ser la navegación.",
      "11": "Mas el centurión creía más al piloto y al patrón de la nave, que á lo que Pablo decía.",
      "12": "Y no habiendo puerto cómodo para invernar, muchos acordaron pasar aún de allí, por si pudiesen arribar á Fenice é invernar allí, que es un puerto de Creta que mira al Nordeste y Sudeste.",
      "13": "Y soplando el austro, pareciéndoles que ya tenían lo que deseaban, alzando velas, iban cerca de la costa de Creta.",
      "14": "Mas no mucho después dió en ella un viento repentino, que se llama Euroclidón.",
      "15": "Y siendo arrebatada la nave, y no pudiendo resistir contra el viento, la dejamos, y erámos llevados.",
      "16": "Y habiendo corrido á sotavento de una pequeña isla que se llama Clauda, apenas pudimos ganar el esquife:",
      "17": "El cual tomado, usaban de remedios, ciñendo la nave; y teniendo temor de que diesen en la Sirte, abajadas las velas, eran así llevados.",
      "18": "Mas siendo atormentados de una vehemente tempestad, al siguiente día alijaron;",
      "19": "Y al tercer día nosotros con nuestras manos arrojamos los aparejos de la nave.",
      "20": "Y no pareciendo sol ni estrellas por muchos días, y viniendo una tempestad no pequeña, ya era perdida toda la esperanza de nuestra salud.",
      "21": "Entonces Pablo, habiendo ya mucho que no comíamos, puesto en pie en medio de ellos, dijo: Fuera de cierto conveniente, oh varones, haberme oído, y no partir de Creta, y evitar este inconveniente y daño.",
      "22": "Mas ahora os amonesto que tengáis buen ánimo; porque ninguna pérdida habrá de persona de vosotros, sino solamente de la nave.",
      "23": "Porque esta noche ha estado conmigo el ángel del Dios del cual yo soy, y al cual sirvo,",
      "24": "Diciendo: Pablo, no temas; es menester que seas presentado delante de César; y he aquí, Dios te ha dado todos los que navegan contigo.",
      "25": "Por tanto, oh varones, tened buen ánimo; porque yo confío en Dios que será así como me ha dicho;",
      "26": "Si bien es menester que demos en una isla.",
      "27": "Y venida la décimacuarta noche, y siendo llevados por el mar Adriático, los marineros á la media noche sospecharon que estaban cerca de alguna tierra;",
      "28": "Y echando la sonda, hallaron veinte brazas, y pasando un poco más adelante, volviendo á echar la sonda, hallaron quince brazas.",
      "29": "Y habiendo temor de dar en lugares escabrosos, echando cuatro anclas de la popa, deseaban que se hiciese de día.",
      "30": "Entonces procurando los marineros huir de la nave, echado que hubieron el esquife á la mar, aparentando como que querían largar las anclas de proa,",
      "31": "Pablo dijo al centurión y á los soldados: Si éstos no quedan en la nave, vosotros no podéis salvaros.",
      "32": "Entonces los soldados cortaron los cabos del esquife, y dejáronlo perder.",
      "33": "Y como comenzó á ser de día, Pablo exhortaba á todos que comiesen, diciendo: Este es el décimocuarto día que esperáis y permanecéis ayunos, no comiendo nada.",
      "34": "Por tanto, os ruego que comáis por vuestra salud: que ni aun un cabello de la cabeza de ninguno de vosotros perecerá.",
      "35": "Y habiendo dicho esto, tomando el pan, hizo gracias á Dios en presencia de todos, y partiendo, comenzó á comer.",
      "36": "Entonces todos teniendo ya mejor ánimo, comieron ellos también.",
      "37": "Y éramos todas las personas en la nave doscientas setenta y seis.",
      "38": "Y satisfechos de comida, aliviaban la nave, echando el grano á la mar.",
      "39": "Y como se hizo de día, no conocían la tierra; mas veían un golfo que tenía orilla, al cual acordaron echar, si pudiesen, la nave.",
      "40": "Cortando pues las anclas, las dejaron en la mar, largando también las ataduras de los gobernalles; y alzada la vela mayor al viento, íbanse á la orilla.",
      "41": "Mas dando en un lugar de dos aguas, hicieron encallar la nave; y la proa, hincada, estaba sin moverse, y la popa se abría con la fuerza de la mar.",
      "42": "Entonces el acuerdo de los soldados era que matasen los presos, porque ninguno se fugase nadando.",
      "43": "Mas el centurión, queriendo salvar á Pablo, estorbó este acuerdo, y mandó que los que pudiesen nadar, se echasen los primeros, y saliesen á tierra;",
      "44": "Y los demás, parte en tablas, parte en cosas de la nave. Y así aconteció que todos se salvaron saliendo á tierra."
    },
    "28": {
      "1": "Y CUANDO escapamos, entonces supimos que la isla se llamaba Melita.",
      "2": "Y los bárbaros nos mostraron no poca humanidad; porque, encendido un fuego, nos recibieron á todos, á causa de la lluvia que venía, y del frío.",
      "3": "Entonces habiendo Pablo recogido algunos sarmientos, y puéstolos en el fuego, una víbora, huyendo del calor, le acometió á la mano.",
      "4": "Y como los bárbaros vieron la víbora colgando de su mano, decían los unos á los otros: Ciertamente este hombre es homicida, á quien, escapado de la mar, la justicia no deja vivir.",
      "5": "Mas él, sacudiendo la víbora en el fuego, ningún mal padeció.",
      "6": "Empero ellos estaban esperando cuándo se había de hinchar, ó caer muerto de repente; mas habiendo esperado mucho, y viendo que ningún mal le venía, mudados, decían que era un dios.",
      "7": "En aquellos lugares había heredades del principal de la isla, llamado Publio, el cual nos recibió y hospedó tres días humanamente.",
      "8": "Y aconteció que el padre de Publio estaba en cama, enfermo de fiebres y de disentería: al cual Pablo entró, y después de haber orado, le puso las manos encima, y le sanó:",
      "9": "Y esto hecho, también otros que en la isla tenían enfermedades, llegaban, y eran sanados:",
      "10": "Los cuales también nos honraron con muchos obsequios; y cuando partimos, nos cargaron de las cosas necesarias.",
      "11": "Así que, pasados tres meses, navegamos en una nave Alejandrina que había invernado en la isla, la cual tenía por enseña á Cástor y Pólux.",
      "12": "Y llegados á Siracusa, estuvimos allí tres días.",
      "13": "De allí, costeando alrededor, vinimos á Regio; y otro día después, soplando el austro, vinimos al segundo día á Puteolos:",
      "14": "Donde habiendo hallado hermanos, nos rogaron que quedásemos con ellos siete días; y luego vinimos á Roma;",
      "15": "De donde, oyendo de nosotros los hermanos, nos salieron á recibir hasta la plaza de Appio, y Las Tres Tabernas: á los cuales como Pablo vió, dió gracias á Dios, y tomó aliento.",
      "16": "Y como llegamos á Roma, el centurión entregó los presos al prefecto de los ejércitos, mas á Pablo fué permitido estar por sí, con un soldado que le guardase.",
      "17": "Y aconteció que tres días después, Pablo convocó á los principales de los Judíos; á los cuales, luego que estuvieron juntos, les dijo: Yo, varones hermanos, no habiendo hecho nada contra el pueblo, ni contra los ritos de la patria, he sido entregado preso desde Jerusalem en manos de los Romanos;",
      "18": "Los cuales, habiéndome examinado, me querían soltar; por no haber en mí ninguna causa de muerte.",
      "19": "Mas contradiciendo los Judíos, fuí forzado á apelar á César; no que tenga de qué acusar á mi nación.",
      "20": "Así que, por esta causa, os he llamado para veros y hablaros; porque por la esperanza de Israel estoy rodeado de esta cadena.",
      "21": "Entonces ellos le dijeron: Nosotros ni hemos recibido cartas tocante á tí de Judea, ni ha venido alguno de los hermanos que haya denunciado ó hablado algún mal de ti.",
      "22": "Mas querríamos oir de ti lo que sientes; porque de esta secta notorio nos es que en todos lugares es contradicha.",
      "23": "Y habiéndole señalado un día, vinieron á él muchos á la posada, á los cuales declaraba y testificaba el reino de Dios, persuadiéndoles lo concerniente á Jesús, por la ley de Moisés y por los profetas, desde la mañana hasta la tarde.",
      "24": "Y algunos asentían á lo que se decía, mas algunos no creían.",
      "25": "Y como fueron entre sí discordes, se fueron, diciendo Pablo esta palabra: Bien ha hablado el Espíritu Santo por el profeta Isaías á nuestros padres,",
      "26": "Diciendo: Ve á este pueblo, y di les: De oído oiréis, y no entenderéis; Y viendo veréis, y no percibiréis:",
      "27": "Porque el corazón de este pueblo se ha engrosado, Y de los oídos oyeron pesadamente, Y sus ojos taparon; Porque no vean con los ojos, Y oigan con los oídos, Y entiendan de corazón, Y se conviertan, Y yo los sane.",
      "28": "Séaos pues notorio que á los Gentiles es enviada esta salud de Dios: y ellos oirán.",
      "29": "Y habiendo dicho esto, los Judíos salieron, teniendo entre sí gran contienda.",
      "30": "Pablo empero, quedó dos años enteros en su casa de alquiler, y recibía á todos los que á él venían,",
      "31": "Predicando el reino de Dios y enseñando lo que es del Señor Jesucristo con toda libertad, sin impedimento."
    }
  },
  "romans": {
    "1": {
      "1": "PABLO, siervo de Jesucristo, llamado á ser apóstol, apartado para el evangelio de Dios,",
      "2": "Que él había antes prometido por sus profetas en las santas Escrituras,",
      "3": "Acerca de su Hijo, (que fué hecho de la simiente de David según la carne;",
      "4": "El cual fué declarado Hijo de Dios con potencia, según el espíritu de santidad, por la resurrección de los muertos), de Jesucristo Señor nuestro,",
      "5": "Por el cual recibimos la gracia y el apostolado, para la obediencia de la fe en todas las naciones en su nombre,",
      "6": "Entre las cuales sois también vosotros, llamados de Jesucristo:",
      "7": "A todos los que estáis en Roma, amados de Dios, llamados santos: Gracia y paz tengáis de Dios nuestro Padre, y del Señor Jesucristo.",
      "8": "Primeramente, doy gracias á mi Dios por Jesucristo acerca de todos vosotros, de que vuestra fe es predicada en todo el mundo.",
      "9": "Porque testigo me es Dios, al cual sirvo en mi espíritu en el evangelio de su Hijo, que sin cesar me acuerdo de vosotros siempre en mis oraciones,",
      "10": "Rogando, si al fin algún tiempo haya de tener, por la voluntad de Dios, próspero viaje para ir á vosotros.",
      "11": "Porque os deseo ver, para repartir con vosotros algún don espiritual, para confirmaros;",
      "12": "Es á saber, para ser juntamente consolado con vosotros por la común fe vuestra y juntamente mía.",
      "13": "Mas no quiero, hermanos, que ingnoréis que muchas veces me he propuesto ir á vosotros (empero hasta ahora he sido estorbado), para tener también entre vosotros algún fruto, como entre los demás Gentiles.",
      "14": "A Griegos y á bárbaros, á sabios y á no sabios soy deudor.",
      "15": "Así que, cuanto á mí, presto estoy á anunciar el evangelio también á vosotros que estáis en Roma.",
      "16": "Porque no me avergüenzo del evangelio: porque es potencia de Dios para salud á todo aquel que cree; al Judío primeramente y también al Griego.",
      "17": "Porque en él la justicia de Dios se descubre de fe en fe; como está escrito: Mas el justo vivirá por la fe.",
      "18": "Porque manifiesta es la ira de Dios del cielo contra toda impiedad é injusticia de los hombres, que detienen la verdad con injusticia:",
      "19": "Porque lo que de Dios se conoce, á ellos es manifiesto; porque Dios se lo manifestó.",
      "20": "Porque las cosas invisibles de él, su eterna potencia y divinidad, se echan de ver desde la creación del mundo, siendo entendidas por las cosas que son hechas; de modo que son inexcusables:",
      "21": "Porque habiendo conocido á Dios, no le glorificaron como á Dios, ni dieron gracias; antes se desvanecieron en sus discursos, y el necio corazón de ellos fué entenebrecido.",
      "22": "Diciéndose ser sabios, se hicieron fatuos,",
      "23": "Y trocaron la gloria del Dios incorruptible en semejanza de imagen de hombre corruptible, y de aves, y de animales de cuatro pies, y de serpientes.",
      "24": "Por lo cual también Dios los entregó á inmundicia, en las concupiscencias de sus corazones, de suerte que contaminaron sus cuerpos entre sí mismos:",
      "25": "Los cuales mudaron la verdad de Dios en mentira, honrando y sirviendo á las criaturas antes que al Criador, el cual es bendito por los siglos. Amén.",
      "26": "Por esto Dios los entregó á afectos vergonzosos; pues aun sus mujeres mudaron el natural uso en el uso que es contra naturaleza:",
      "27": "Y del mismo modo también los hombres, dejando el uso natural de las mujeres, se encendieron en sus concupiscencias los unos con los otros, cometiendo cosas nefandas hombres con hombres, y recibiendo en sí mismos la recompensa que convino á su extravío.",
      "28": "Y como á ellos no les pareció tener á Dios en su noticia, Dios los entregó á una mente depravada, para hacer lo que no conviene,",
      "29": "Estando atestados de toda iniquidad, de fornicación, de malicia, de avaricia, de maldad; llenos de envidia, de homicidios, de contiendas, de engaños, de malignidades;",
      "30": "Murmuradores, detractores, aborrecedores de Dios, injuriosos, soberbios, altivos, inventores de males, desobedientes á los padres,",
      "31": "Necios, desleales, sin afecto natural, implacables, sin misericordia:",
      "32": "Que habiendo entendido el juicio de Dios que los que hacen tales cosas son dignos de muerte, no sólo las hacen, más aún consienten á los que las hacen."
    },
    "2": {
      "1": "POR lo cual eres inexcusable, oh hombre, cuaquiera que juzgas: porque en lo que juzgas á otro, te condenas á ti mismo; porque lo mismo haces, tú que juzgas.",
      "2": "Mas sabemos que el juicio de Dios es según verdad contra los que hacen tales cosas.",
      "3": "¿Y piensas esto, oh hombre, que juzgas á los que hacen tales cosas, y haces las mismas, que tú escaparás del juicio de Dios.?",
      "4": "¿O menosprecias las riquezas de su benignidad, y fhfifhfi ignorando que su benignidad te guía á arrepentimiento?",
      "5": "Mas por tu dureza, y por tu corazón no arrepentido, atesoras para ti mismo ira para el día de la ira y de la manifestación del justo juicio de Dios;",
      "6": "El cual pagará á cada uno conforme á sus obras:",
      "7": "A los que perseverando en bien hacer, buscan gloria y honra e inmortalidad, la vida eterna.",
      "8": "Mas á los que son contenciosos, y no obedecen á la verdad, antes obedecen á la injusticia, enojo é ira;",
      "9": "Tribulación y angustia sobre toda persona humana que obra lo malo, el Judío primeramente, y también el Griego.",
      "10": "Mas gloria y honra y paz á cualquiera que obra el bien, al Judío primeramente, y también al Griego.",
      "11": "Porque no hay acepción de personas para con Dios.",
      "12": "Porque todos lo que sin ley pecaron, sin ley también perecerán; y todos los que en la ley pecaron, por la ley serán juzgados:",
      "13": "Porque no los oidores de la ley son justos para con Dios, mas los hacedores de la ley serán justificados.",
      "14": "Porque los Gentiles que no tienen ley, naturalmente haciendo lo que es de la ley, los tales, aunque no tengan ley, ellos son ley á sí mismos:",
      "15": "Mostrando la obra de la ley escrita en sus corazones, dando testimonio juntamente sus conciencias, y acusándose y también excusándose sus pensamientos unos con otros;",
      "16": "En el día que juzgará el Señor lo encubierto de los hombres, conforme á mi evangelio, por Jesucristo.",
      "17": "He aquí, tú tienes el sobrenombre de Judío, y estás reposado en la ley, y te glorías en Dios,",
      "18": "Y sabes su voluntad, y apruebas lo mejor, instruído por la ley;",
      "19": "Y confías que eres guía de los ciegos, luz de los que están en tinieblas,",
      "20": "Enseñador de los que no saben, maestro de niños, que tienes la forma de la ciencia y de la verdad en la ley:",
      "21": "Tú pues, que enseñas á otro, ¿no te enseñas á ti mismo? ¿Tú, que predicas que no se ha de hurtar, hurtas?",
      "22": "¿Tú, que dices que no se ha de adulterar, adulteras? ¿Tú, que abominas los ídolos, cometes sacrilegio?",
      "23": "¿Tú, que te jactas de la ley, con infracción de la ley deshonras á Dios?",
      "24": "Porque el nombre de Dios es blasfemado por causa de vosotros entre los Gentiles, como está esctrito.",
      "25": "Porque la circuncisión en verdad aprovecha, si guardares la ley; mas si eres rebelde á la ley, tu circuncisión es hecha incircuncisión.",
      "26": "De manera que, si el incircunciso guardare las justicias de la ley, ¿no será tenida su incircuncisión por circuncisión?",
      "27": "Y lo que de su natural es incircunciso, guardando perfectamente la ley, te juzgará á ti, que con la letra y con la circuncisión eres rebelde á la ley.",
      "28": "Porque no es Judío el que lo es en manifiesto; ni la circuncisión es la que es en manifiesto en la carne:",
      "29": "Mas es Judío el que lo es en lo interior; y la circuncisión es la del corazón, en espíritu, no en letra; la alabanza del cual no es de los hombres, sino de Dios."
    },
    "3": {
      "1": "¿QUÉ, pues, tiene más el Judío? ¿ó qué aprovecha la circuncisión?,",
      "2": "Mucho en todas maneras. Lo primero ciertamente, que la palabra de Dios les ha sido confiada.",
      "3": "¿Pues qué si algunos de ellos han sido incrédulos? ¿la incredulidad de ellos habrá hecho vana la verdad de Dios?",
      "4": "En ninguna manera; antes bien sea Dios verdadero, mas todo hombre mentiroso; como está escrito: Para que seas justificado en tus dichos, Y venzas cuando de ti se juzgare.",
      "5": "Y si nuestra iniquidad encarece la justicia de Dios, ¿qué diremos? ¿Será injusto Dios que da castigo? (hablo como hombre.)",
      "6": "En ninguna manera: de otra suerte ¿cómo juzgaría Dios el mundo?",
      "7": "Empero si la verdad de Dios por mi mentira creció á gloria suya, ¿por qué aun así yo soy juzgado como pecador?",
      "8": "¿Y por qué no decir (como somos blasfemados, y como algunos dicen que nosotros decimos): Hagamos males para que vengan bienes? la condenación de los cuales es justa.",
      "9": "¿Qué pues? ¿Somos mejores que ellos? En ninguna manera: porque ya hemos acusado á Judíos y á Gentiles, que todos están debajo de pecado.",
      "10": "Como está escrito: No hay justo, ni aun uno;",
      "11": "No hay quien entienda, No hay quien busque á Dios;",
      "12": "Todos se apartaron, á una fueron hechos inútiles; No hay quien haga lo bueno, no hay ni aun uno:",
      "13": "Sepulcro abierto es su garganta; Con sus lenguas tratan engañosamente; Veneno de áspides está debajo de sus labios;",
      "14": "Cuya boca está llena de maledicencia y de amargura;",
      "15": "Sus pies son ligeros á derramar sangre;",
      "16": "Quebrantamiento y desventura hay en sus caminos;",
      "17": "Y camino de paz no conocieron:",
      "18": "No hay temor de Dios delante de sus ojos.",
      "19": "Empero sabemos que todo lo que la ley dice, á los que están en la ley lo dice, para que toda boca se tape, y que todo el mundo se sujete á Dios:",
      "20": "Porque por las obras de la ley ninguna carne se justificará delante de él; porque por la ley es el conocimiento del pecado.",
      "21": "Mas ahora, sin la ley, la justicia de Dios se ha manifestado, testificada por la ley y por los profetas:",
      "22": "La justicia de Dios por la fe de Jesucristo, para todos los que creen en él: porque no hay diferencia;",
      "23": "Por cuanto todos pecaron, y están distituídos de la gloria de Dios;",
      "24": "Siendo justificados gratuitamente por su gracia por la redención que es en Cristo Jesús;",
      "25": "Al cual Dios ha propuesto en propiciación por la fe en su sangre, para manifestación de su justicia, atento á haber pasado por alto, en su paciencia, los pecados pasados,",
      "26": "Con la mira de manifestar su justicia en este tiempo: para que él sea el justo, y el que justifica al que es de la fe de Jesús.",
      "27": "¿Dondé pues está la jactancia? Es excluída. ¿Por cuál ley? ¿de las obras? No; mas por la ley de la fe.",
      "28": "Así que, concluímos ser el hombre justificado por fe sin las obras de la ley.",
      "29": "¿Es Dios solamente Dios de los Judíos? ¿No es también Dios de los Gentiles? Cierto, también de los Gentiles.",
      "30": "Porque uno es Dios, el cual justificará por la fe la circuncisión, y por medio de la fe la incircuncisión.",
      "31": "¿Luego deshacemos la ley por la fe? En ninguna manera; antes establecemos la ley."
    },
    "4": {
      "1": "¿QUÉ, pues, diremos que halló Abraham nuestro padre según la carne?",
      "2": "Que si Abraham fué justificado por la obras, tiene de qué gloriarse; mas no para con Dios.",
      "3": "Porque ¿qué dice la Escritura? Y creyó Abraham á Dios, y le fué atribuído á justicia.",
      "4": "Empero al que obra, no se le cuenta el salario por merced, sino por deuda.",
      "5": "Mas al que no obra, pero cree en aquél que justifica al impío, la fe le es contada por justicia.",
      "6": "Como también David dice ser bienaventurado el hombre al cual Dios atribuye justicia sin obras,",
      "7": "Diciendo: Bienaventurados aquellos cuyas iniquidades son perdonadas, Y cuyos pecados son cubiertos.",
      "8": "Bienaventurado el varón al cual el Señor no imputó pecado.",
      "9": "¿Es pues esta bienaventuranza solamente en la circuncisión ó también en la incircuncisión? porque decimos que á Abraham fué contada la fe por justicia.",
      "10": "¿Cómo pues le fué contada? ¿en la circuncisión, ó en la incircuncisión? No en la circuncisión, sino en la incircuncisión.",
      "11": "Y recibió la circuncisión por señal, por sello de la justicia de la fe que tuvo en la incircuncisión: para que fuese padre de todos los creyentes no circuncidados, para que también á ellos les sea contado por justicia;",
      "12": "Y padre de la circuncisión, no solamente á los que son de la circuncisión, más también á los que siguen las pisadas de la fe que fué en nuestro padre Abraham antes de ser circuncidado.",
      "13": "Porque no por la ley fué dada la promesa á Abraham ó á su simiente, que sería heredero del mundo, sino por la justicia de la fe.",
      "14": "Porque si los que son de la ley son los herederos, vana es la fe, y anulada es la promesa.",
      "15": "Porque la ley obra ira; porque donde no hay ley, tampoco hay transgresión.",
      "16": "Por tanto es por la fe, para que sea por gracia; para que la promesa sea firme á toda simiente, no solamente al que es de la ley, mas también al que es de la fe de Abraham, el cual es padre de todos nosotros.",
      "17": "(Como está escrito: Que por padre de muchas gentes te he puesto) delante de Dios, al cual creyó; el cual da vida á los muertos, y llama las cosas que no son, como las que son.",
      "18": "El creyó en esperanza contra esperanza, para venir á ser padre de muchas gentes, conforme á lo que le había sido dicho: Así será tu simiente.",
      "19": "Y no se enflaqueció en la fe, ni consideró su cuerpo ya muerto (siendo ya de casi cien años,) ni la matriz muerta de Sara;",
      "20": "Tampoco en la promesa de Dios dudó con desconfianza: antes fué esforzado en fe, dando gloria á Dios,",
      "21": "Plenamente convencido de que todo lo que había prometido, era también poderoso para hacerlo.",
      "22": "Por lo cual también le fué atribuído á justicia.",
      "23": "Y no solamente por él fué escrito que le haya sido imputado;",
      "24": "Sino también por nosotros, á quienes será imputado, esto es, á los que creemos en el que levantó de los muertos á Jesús Señor nuestro,",
      "25": "El cual fué entregado por nuestros delitos, y resucitado para nuestra justificación"
    },
    "5": {
      "1": "JUSTIFICADOS pues por la fe, tenemos paz para con Dios por medio de nuestro Señor Jesucristo:",
      "2": "Por el cual también tenemos entrada por la fe á esta gracia en la cual estamos firmes, y nos gloriamos en la esperanza de la gloria de Dios.",
      "3": "Y no sólo esto, mas aun nos gloriamos en las tribulaciones, sabiendo que la tribulación produce paciencia;",
      "4": "Y la paciencia, prueba; y la prueba, esperanza;",
      "5": "Y la esperanza no avergüenza; porque el amor de Dios está derramado en nuestros corazones por el Espíritu Santo que nos es dado.",
      "6": "Porque Cristo, cuando aún éramos flacos, á su tiempo murió por los impíos.",
      "7": "Ciertamente apenas muere algun por un justo: con todo podrá ser que alguno osara morir por el bueno.",
      "8": "Mas Dios encarece su caridad para con nosotros, porque siendo aún pecadores, Cristo murió por nosotros.",
      "9": "Luego mucho más ahora, justificados en su sangre, por él seremos salvos de la ira.",
      "10": "Porque si siendo enemigos, fuimos reconciliado con Dios por la muerte de su Hijo, mucho más, estando reconciliados, seremos salvos por su vida.",
      "11": "Y no sólo esto, mas aun nos gloriamos en Dios por el Señor nuestro Jesucristo, por el cual hemos ahora recibido la reconciliación.",
      "12": "De consiguiente, vino la reconciliación por uno, así como el pecado entró en el mundo por un hombre, y por el pecado la muerte, y la muerte así pasó á todos los hombres, pues que todos pecaron.",
      "13": "Porque hasta la ley, el pecado estaba en el mundo; pero no se imputa pecado no habiendo ley.",
      "14": "No obstante, reinó la muerte desde Adam hasta Moisés, aun en los que no pecaron á la manera de la rebelión de Adam; el cual es figura del que había de venir.",
      "15": "Mas no como el delito, tal fué el don: porque si por el delito de aquel uno murieron los muchos, mucho más abundó la gracia de Dios á los muchos, y el don por la gracia de un hombre, Jesucristo.",
      "16": "Ni tampoco de la manera que por un pecado, así también el don: porque el juicio á la verdad vino de un pecado para condenación, mas la gracia vino de muchos delitos para justificación.",
      "17": "Porque, si por un delito reinó la muerte por uno, mucho más reinarán en vida por un Jesucristo los que reciben la abundancia de gracia, y del don de la justicia.",
      "18": "Así que, de la manera que por un delito vino la culpa á todos los hombres para condenación, así por una justicia vino la gracia á todos los hombres para justificación de vida.",
      "19": "Porque como por la desobediencia de un hombre los muchos fueron constituídos pecadores, así por la obediencia de uno los muchos serán constituídos justos.",
      "20": "La ley empero entró para que el pecado creciese; mas cuando el pecado creció, sobrepujó la gracia;",
      "21": "Para que, de la manera que el pecado reinó para muerte, así también la gracia reine por la justicia para vida eterna por Jesucristo Señor nuestro."
    },
    "6": {
      "1": "¿PUES qué diremos? Perseveraremos en pecado para que la gracia crezca?",
      "2": "En ninguna manera. Porque los que somos muertos al pecado, ¿cómo viviremos aún en él?",
      "3": "¿O no sabéis que todos los que somos bautizados en Cristo Jesús, somos bautizados en su muerte?",
      "4": "Porque somos sepultados juntamente con él á muerte por el bautismo; para que como Cristo resucitó de los muertos por la gloria del Padre, así también nosotros andemos en novedad de vida.",
      "5": "Porque si fuimos plantados juntamente en él á la semejanza de su muerte, así también lo seremos á la de su resurrección:",
      "6": "Sabiendo esto, que nuestro viejo hombre juntamente fué crucificado con él, para que el cuerpo del pecado sea deshecho, á fin de que no sirvamos más al pecado.",
      "7": "Porque el que es muerto, justificado es del pecado.",
      "8": "Y si morimos con Cristo, creemos que también viviremos con él;",
      "9": "Sabiendo que Cristo, habiendo resucitado de entre los muertos, ya no muere: la muerte no se enseñoreará más de él.",
      "10": "Porque el haber muerto, al pecado murió una vez; mas el vivir, á Dios vive.",
      "11": "Así también vosotros, pensad que de cierto estáis muertos al pecado, mas vivos á Dios en Cristo Jesús Señor nuestro.",
      "12": "No reine, pues, el pecado en vuestro cuerpo mortal, para que le obedezcáis en sus concupiscencias;",
      "13": "Ni tampoco presentéis vuestros miembros al pecado por instrumento de iniquidad; antes presentaos á Dios como vivos de los muertos, y vuestros miembros á Dios por instrumentos de justicia.",
      "14": "Porque el pecado no se enseñoreará de vosotros; pues no estáis bajo la ley, sino bajo la gracia.",
      "15": "¿Pues qué? ¿Pecaremos, porque no estamos bajo de la ley, sino bajo de la gracia? En ninguna manera.",
      "16": "¿No sabéis que á quien os prestáis vosotros mismos por siervos para obedecer le, sois siervos de aquel á quien obedecéis, ó del pecado para muerte, ó de la obediencia para justicia?",
      "17": "Empero gracias á Dios, que aunque fuistes siervos del pecado, habéis obedecido de corazón á aquella forma de doctrina á la cual sois entregados;",
      "18": "Y libertados del pecado, sois hechos siervos de la justicia.",
      "19": "Humana cosa digo, por la flaqueza de vuestra carne: que como para iniquidad presentasteis vuestros miembros á servir á la inmundicia y á la iniquidad, así ahora para santidad presentéis vuestros miembros á servir á la justicia.",
      "20": "Porque cuando fuisteis siervos del pecado, erais libres acerca de la justicia.",
      "21": "¿Qué fruto, pues, teníais de aquellas cosas de las cuales ahora os avergonzáis? porque el fin de ellas es muerte.",
      "22": "Mas ahora, librados del pecado, y hechos siervos á Dios, tenéis por vuestro fruto la santificación, y por fin la vida eterna.",
      "23": "Porque la paga del pecado es muerte: mas la dádiva de Dios es vida eterna en Cristo Jesús Señor nuestro."
    },
    "7": {
      "1": "¿IGNORAIS, hermanos, (porque hablo con los que saben la ley) que la ley se enseñorea del hombre entre tanto que vive?",
      "2": "Porque la mujer que está sujeta á marido, mientras el marido vive está obligada á la ley; mas muerto el marido, libre es de la ley del marido.",
      "3": "Así que, viviendo el marido, se llamará adúltera si fuere de otro varón; mas si su marido muriere, es libre de la ley; de tal manera que no será adúltera si fuere de otro marido.",
      "4": "Así también vosotros, hermanos míos, estáis muertos á la ley por el cuerpo de Cristo, para que seáis de otro, á saber, del que resucitó de los muertos, á fin de que fructifiquemos á Dios.",
      "5": "Porque mientras estábamos en la carne, los afectos de los pecados que eran por la ley, obraban en nuestros miembros fructificando para muerte.",
      "6": "Mas ahora estamos libres de la ley, habiendo muerto á aquella en la cual estábamos detenidos, para que sirvamos en novedad de espíritu, y no en vejez de letra.",
      "7": "¿Qué pues diremos? ¿La ley es pecado? En ninguna manera. Empero yo no conocí el pecado sino por la ley: porque tampoco conociera la concupiscencia, si la ley no dijera: No codiciarás.",
      "8": "Mas el pecado, tomando ocasión, obró en mí por el mandamiento toda concupiscencia: porque sin la ley el pecado está muerto.",
      "9": "Así que, yo sin la ley vivía por algún tiempo: mas venido el mandamiento, el pecado revivió, y yo morí.",
      "10": "Y hallé que el mandamiento, á intimado para vida, para mí era mortal:",
      "11": "Porque el pecado, tomando ocasión, me engañó por el mandamiento, y por él me mató.",
      "12": "De manera que la ley á la verdad es santa, y el mandamiento santo, y justo, y bueno.",
      "13": "¿Luego lo que es bueno, á mí me es hecho muerte? No; sino que el pecado, para mostrarse pecado, por lo bueno me obró la muerte, haciéndose pecado sobremanera pecante por el mandamiento.",
      "14": "Porque sabemos que la ley es espiritual; mas yo soy carnal, vendido á sujeción del pecado.",
      "15": "Porque lo que hago, no lo entiendo; ni lo que quiero, hago; antes lo que aborrezco, aquello hago.",
      "16": "Y si lo que no quiero, esto hago, apruebo que la ley es buena.",
      "17": "De manera que ya no obro aquello, sino el pecado que mora en mí.",
      "18": "Y yo sé que en mí (es á saber, en mi carne) no mora el bien: porque tengo el querer, mas efectuar el bien no lo alcanzo.",
      "19": "Porque no hago el bien que quiero; mas el mal que no quiero, éste hago.",
      "20": "Y si hago lo que no quiero, ya no obro yo, sino el mal que mora en mí.",
      "21": "Así que, queriendo yo hacer el bien, hallo esta ley: Que el mal está en mí.",
      "22": "Porque según el hombre interior, me deleito en la ley de Dios:",
      "23": "Mas veo otra ley en mis miembros, que se rebela contra la ley de mi espíritu, y que me lleva cautivo á la ley del pecado que está en mis miembros.",
      "24": "Miserable hombre de mí! ¿quién me librará del cuerpo de esta muerte?",
      "25": "Gracias doy á Dios, por Jesucristo Señor nuestro. Así que, yo mismo con la mente sirvo á la ley de Dios, mas con la carne á la ley del pecado."
    },
    "8": {
      "1": "AHORA pues, ninguna condenación hay para los que están en Cristo Jesús, los que no andan conforme á la carne, mas conforme al espíritu.",
      "2": "Porque la ley del Espíritu de vida en Cristo Jesús me ha librado de la ley del pecado y de la muerte.",
      "3": "Porque lo que era imposible á la ley, por cuanto era débil por la carne, Dios enviando á su Hijo en semejanza de carne de pecado, y á causa del pecado, condenó al pecado en la carne;",
      "4": "Para que la justicia de la ley fuese cumplida en nosotros, que no andamos conforme á la carne, mas conforme al espíritu.",
      "5": "Porque los que viven conforme á la carne, de las cosas que son de la carne se ocupan; mas los que conforme al espíritu, de las cosas del espíritu.",
      "6": "Porque la intención de la carne es muerte; mas la intención del espíritu, vida y paz:",
      "7": "Por cuanto la intención de la carne es enemistad contra Dios; porque no se sujeta á la ley de Dios, ni tampoco puede.",
      "8": "Así que, los que están en la carne no pueden agradar á Dios.",
      "9": "Mas vosotros no estáis en la carne, sino en el espíritu, si es que el Espíritu de Dios mora en vosotros. Y si alguno no tiene el Espíritu de Cristo, el tal no es de él.",
      "10": "Empero si Cristo está en vosotros, el cuerpo á la verdad está muerto á causa del pecado; mas el espíritu vive á causa de la justicia.",
      "11": "Y si el Espíritu de aquel que levantó de los muertos á Jesús mora en vosotros, el que levantó á Cristo Jesús de los muertos, vivificará también vuestros cuerpos mortales por su Espíritu que mora en vosotros.",
      "12": "Así que, hermanos, deudores somos, no á la carne, para que vivamos conforme á la carne:",
      "13": "Porque si viviereis conforme á la carne, moriréis; mas si por el espíritu mortificáis las obras de la carne, viviréis.",
      "14": "Porque todos los que son guiados por el Espíritu de Dios, los tales son hijos de Dios.",
      "15": "Porque no habéis recibido el espíritu de servidumbre para estar otra vez en temor; mas habéis recibido el espíritu de adopción, por el cual clamamos, Abba, Padre.",
      "16": "Porque el mismo Espíritu da testimonio á nuestro espíritu que somos hijos de Dios.",
      "17": "Y si hijos, también herederos; herederos de Dios, y coherederos de Cristo; si empero padecemos juntamente con él, para que juntamente con él seamos glorificados.",
      "18": "Porque tengo por cierto que lo que en este tiempo se padece, no es de comparar con la gloria venidera que en nosotros ha de ser manifestada.",
      "19": "Porque el continuo anhelar de las criaturas espera la manifestación de los hijos de Dios.",
      "20": "Porque las criaturas sujetas fueron á vanidad, no de grado, mas por causa del que las sujetó con esperanza,",
      "21": "Que también las mismas criaturas serán libradas de la servidumbre de corrupción en la libertad gloriosa de los hijos de Dios.",
      "22": "Porque sabemos que todas las criaturas gimen á una, y á una están de parto hasta ahora.",
      "23": "Y no sólo ellas, mas también nosotros mismos, que tenemos las primicias del Espíritu, nosotros también gemimos dentro de nosotros mismos, esperando la adopción, es á saber, la redención de nuestro cuerpo.",
      "24": "Porque en esperanza somos salvos; mas la esperanza que se ve, no es esperanza; porque lo que alguno ve, ¿á qué esperarlo?",
      "25": "Empero si lo que no vemos esperamos, por paciencia esperamos.",
      "26": "Y asimismo también el Espíritu ayuda nuestra flaqueza: porque qué hemos de pedir como conviene, no lo sabemos; sino que el mismo Espíritu pide por nosotros con gemidos indecibles.",
      "27": "Mas el que escudriña los corazones, sabe cuál es el intento del Espíritu, porque conforme á la voluntad de Dios, demanda por los santos.",
      "28": "Y sabemos que á los que á Dios aman, todas las cosas les ayudan á bien, es á saber, á los que conforme al propósito son llamados.",
      "29": "Porque á los que antes conoció, también predestinó para que fuesen hechos conformes á la imagen de su Hijo, para que él sea el primogénito entre muchos hermanos;",
      "30": "Y á los que predestinó, á éstos también llamó; y á los que llamó, á éstos también justificó; y á los que justificó, á éstos también glorificó.",
      "31": "¿Pues qué diremos á esto? Si Dios por nosotros, ¿quién contra nosotros?",
      "32": "El que aun á su propio Hijo no perdonó, antes le entregó por todos nosotros, ¿cómo no nos dará también con él todas las cosas?",
      "33": "¿Quién acusará á los escogidos de Dios? Dios es el que justifica.",
      "34": "¿Quién es el que condenará? Cristo es el que murió; más aún, el que también resucitó, quien además está á la diestra de Dios, el que también intercede por nosotros.",
      "35": "¿Quién nos apartará del amor de Cristo? tribulación? ó angustia? ó persecución? ó hambre? ó desnudez? ó peligro? ó cuchillo?",
      "36": "Como está escrito: Por causa de ti somos muertos todo el tiempo: Somos estimados como ovejas de matadero.",
      "37": "Antes, en todas estas cosas hacemos más que vencer por medio de aquel que nos amó.",
      "38": "Por lo cual estoy cierto que ni la muerte, ni la vida, ni ángeles, ni principados, ni potestades, ni lo presente, ni lo por venir,",
      "39": "Ni lo alto, ni lo bajo, ni ninguna criatura nos podrá apartar del amor de Dios, que es en Cristo Jesús Señor nuestro."
    }
  }
};

