
	
export const bib_verses = {
  "exodus": {
    "33": {
      "1": "Y JEHOVA dijo á Moisés: Ve, sube de aquí, tú y el pueblo que sacaste de la tierra de Egipto, á la tierra de la cual juré á Abraham, Isaac, y Jacob, diciendo: A tu simiente la daré:",
      "2": "Y yo enviaré delante de ti el ángel, y echaré fuera al Cananeo y al Amorrheo, y al Hetheo, y al Pherezeo, y al Heveo y al Jebuseo:",
      "3": "(A la tierra que fluye leche y miel); porque yo no subiré en medio de ti, porque eres pueblo de dura cerviz, no sea que te consuma en el camino.",
      "4": "Y oyendo el pueblo esta sensible palabra, vistieron luto, y ninguno se puso sus atavíos:",
      "5": "Pues Jehová dijo á Moisés: Di á los hijos de Israel: Vosotros sois pueblo de dura cerviz: en un momento subiré en medio de ti, y te consumiré: quítate pues ahora tus atavíos, que yo sabré lo que te tengo de hacer.",
      "6": "Entonces los hijos de Israel se despojaron de sus atavíos desde el monte Horeb.",
      "7": "Y Moisés tomó el tabernáculo, y extendiólo fuera del campo, lejos del campo, y llamólo el Tabernáculo del Testimonio. Y fué, que cualquiera que requería á Jehová, salía al tabernáculo del testimonio, que estaba fuera del campo.",
      "8": "Y sucedía que, cuando salía Moisés al tabernáculo, todo el pueblo se levantaba, y estaba cada cual en pie á la puerta de su tienda, y miraban en pos de Moisés, hasta que él entraba en el tabernáculo.",
      "9": "Y cuando Moisés entraba en el tabernáculo, la columna de nube descendía, y poníase á la puerta del tabernáculo, y Jehová hablaba con Moisés.",
      "10": "Y viendo todo el pueblo la columna de nube, que estaba á la puerta del tabernáculo, levantábase todo el pueblo, cada uno á la puerta de su tienda y adoraba.",
      "11": "Y hablaba Jehová á Moisés cara á cara, como habla cualquiera á su compañero. Y volvíase al campo; mas el joven Josué, su criado, hijo de Nun, nunca se apartaba de en medio del tabernáculo.",
      "12": "Y dijo Moisés á Jehová: Mira, tú me dices á mí: Saca este pueblo: y tú no me has declarado á quién has de enviar conmigo: sin embargo, tú dices: Yo te he conocido por tu nombre, y has hallado también gracia en mis ojos.",
      "13": "Ahora, pues, si he hallado gracia en tus ojos, ruégote que me muestres ahora tu camino, para que te conozca, porque halle gracia en tus ojos: y mira que tu pueblo es aquesta gente.",
      "14": "Y él dijo: Mi rostro irá contigo, y te haré descansar.",
      "15": "Y él respondió: Si tu rostro no ha de ir conmigo, no nos saques de aquí.",
      "16": "¿Y en qué se conocerá aquí que he hallado gracia en tus ojos, yo y tu pueblo, sino en andar tú con nosotros, y que yo y tu pueblo seamos apartados de todos los pueblos que están sobre la faz de la tierra?",
      "17": "Y Jehová dijo á Moisés: También haré esto que has dicho, por cuanto has hallado gracia en mis ojos, y te he conocido por tu nombre.",
      "18": "El entonces dijo: Ruégote que me muestres tu gloria.",
      "19": "Y respondióle: Yo haré pasar todo mi bien delante de tu rostro, y proclamaré el nombre de Jehová delante de ti; y tendré misericordia del que tendré misericordia, y seré clemente para con el que seré clemente.",
      "20": "Dijo más: No podrás ver mi rostro: porque no me verá hombre, y vivirá.",
      "21": "Y dijo aún Jehová: He aquí lugar junto á mí, y tú estarás sobre la peña:",
      "22": "Y será que, cuando pasare mi gloria, yo te pondré en una hendidura de la peña, y te cubriré con mi mano hasta que haya pasado:",
      "23": "Después apartaré mi mano, y verás mis espaldas; mas no se verá mi rostro."
    },
    "34": {
      "1": "Y JEHOVA dijo á Moisés: Alísate dos tablas de piedra como las primeras, y escribiré sobre esas tablas las palabras que estaban en las tablas primeras que quebraste.",
      "2": "Apercíbete, pues, para mañana, y sube por la mañana al monte de Sinaí, y estáme allí sobre la cumbre del monte.",
      "3": "Y no suba hombre contigo, ni parezca alguno en todo el monte; ni ovejas ni bueyes pazcan delante del monte.",
      "4": "Y Moisés alisó dos tablas de piedra como las primeras; y levantóse por la mañana, y subió al monte de Sinaí, como le mandó Jehová, y llevó en su mano las dos tablas de piedra.",
      "5": "Y Jehová descendió en la nube, y estuvo allí con él, proclamando el nombre de Jehová.",
      "6": "Y pasando Jehová por delante de él, proclamó: Jehová, Jehová, fuerte, misericordioso, y piadoso; tardo para la ira, y grande en benignidad y verdad;",
      "7": "Que guarda la misericordia en millares, que perdona la iniquidad, la rebelión, y el pecado, y que de ningún modo justificará al malvado; que visita la iniquidad de los padres sobre los hijos y sobre los hijos de los hijos, sobre los terceros, y sobre los cuartos.",
      "8": "Entonces Moisés, apresurándose, bajó la cabeza hacia el suelo y encorvóse;",
      "9": "Y dijo: Si ahora, Señor, he hallado gracia en tus ojos, vaya ahora el Señor en medio de nosotros; porque este es pueblo de dura cerviz; y perdona nuestra iniquidad y nuestro pecado, y poséenos.",
      "10": "Y él dijo: He aquí, yo hago concierto delante de todo tu pueblo: haré maravillas que no han sido hechas en toda la tierra, ni en nación alguna; y verá todo el pueblo en medio del cual estás tú, la obra de Jehová; porque ha de ser cosa terrible la que yo haré contigo.",
      "11": "Guarda lo que yo te mando hoy; he aquí que yo echo de delante de tu presencia al Amorrheo, y al Cananeo, y al Hetheo, y al Pherezeo, y al Heveo, y al Jebuseo.",
      "12": "Guárdate que no hagas alianza con los moradores de la tierra donde has de entrar, porque no sean por tropezadero en medio de ti:",
      "13": "Mas derribaréis sus altares, y quebraréis sus estatuas, y talaréis sus bosques:",
      "14": "Porque no te has de inclinar á dios ajeno; que Jehová, cuyo nombre es Celoso, Dios celoso es.",
      "15": "Por tanto no harás alianza con los moradores de aquella tierra; porque fornicarán en pos de sus dioses, y sacrificarán á sus dioses, y te llamarán, y comerás de sus sacrificios;",
      "16": "O tomando de sus hijas para tus hijos, y fornicando sus hijas en pos de sus dioses, harán también fornicar á tus hijos en pos de los dioses de ellas.",
      "17": "No harás dioses de fundición para ti.",
      "18": "La fiesta de los ázimos guardarás: siete días comerás por leudar, según te he mandado, en el tiempo del mes de Abib; porque en el mes de Abib saliste de Egipto.",
      "19": "Todo lo que abre matriz, mío es; y de tu ganado todo primerizo de vaca ó de oveja que fuere macho.",
      "20": "Empero redimirás con cordero el primerizo del asno; y si no lo redimieres, le has de cortar la cabeza. Redimirás todo primogénito de tus hijos, y no serán vistos vacíos delante de mí.",
      "21": "Seis días trabajarás, mas en el séptimo día cesarás: cesarás aun en la arada y en la siega.",
      "22": "Y te harás la fiesta de las semanas á los principios de la siega del trigo: y la fiesta de la cosecha á la vuelta del año.",
      "23": "Tres veces en el año será visto todo varón tuyo delante del Señoreador Jehová, Dios de Israel.",
      "24": "Porque yo arrojaré las gentes de tu presencia, y ensancharé tu término: y ninguno codiciará tu tierra, cuando tú subieres para ser visto delante de Jehová tu Dios tres veces en el año.",
      "25": "No ofrecerás con leudo la sangre de mi sacrificio; ni quedará de la noche para la mañana el sacrificio de la fiesta de la pascua.",
      "26": "La primicia de los primeros frutos de tu tierra meterás en la casa de Jehová tu Dios. No cocerás el cabrito en la leche de su madre.",
      "27": "Y Jehová dijo á Moisés: Escribe tú estas palabras; porque conforme á estas palabras he hecho la alianza contigo y con Israel.",
      "28": "Y él estuvo allí con Jehová cuarenta días y cuarenta noches: no comió pan, ni bebió agua; y escribió en tablas las palabras de la alianza, las diez palabras.",
      "29": "Y aconteció, que descendiendo Moisés del monte Sinaí con las dos tablas del testimonio en su mano, mientras descendía del monte, no sabía él que la tez de su rostro resplandecía, después que hubo con El hablado.",
      "30": "Y miró Aarón y todos los hijos de Israel á Moisés, y he aquí la tez de su rostro era resplandeciente; y tuvieron miedo de llegarse á él.",
      "31": "Y llamólos Moisés; y Aarón y todos los príncipes de la congregación volvieron á él, y Moisés les habló.",
      "32": "Y después se llegaron todos los hijos de Israel, á los cuales mandó todas las cosas que Jehová le había dicho en el monte de Sinaí.",
      "33": "Y cuando hubo acabado Moisés de hablar con ellos, puso un velo sobre su rostro.",
      "34": "Y cuando venía Moisés delante de Jehová para hablar con él, quitábase el velo hasta que salía; y saliendo, hablaba con los hijos de Israel lo que le era mandado;",
      "35": "Y veían los hijos de Israel el rostro de Moisés, que la tez de su rostro era resplandeciente; y volvía Moisés á poner el velo sobre su rostro, hasta que entraba á hablar con El."
    },
    "35": {
      "1": "Y MOISÉS hizo juntar toda la congregación de los hijos de Israel, y díjoles: Estas son las cosas que Jehová ha mandado que hagáis.",
      "2": "Seis días se hará obra, mas el día séptimo os será santo, sábado de reposo á Jehová: cualquiera que en él hiciere obra, morirá.",
      "3": "No encenderéis fuego en todas vuestras moradas en el día del sábado.",
      "4": "Y habló Moisés á toda la congregación de los hijos de Israel, diciendo: Esto es lo que Jehová ha mandado, diciendo:",
      "5": "Tomad de entre vosotros ofrenda para Jehová: todo liberal de corazón la traerá á Jehová: oro, plata, metal;",
      "6": "Y cárdeno, y púrpura, y carmesí, y lino fino, y pelo de cabras;",
      "7": "Y cueros rojos de carneros, y cueros de tejones, y madera de Sittim;",
      "8": "Y aceite para la luminaria, y especias aromáticas para el aceite de la unción, y para el perfume aromático;",
      "9": "Y piedras de onix, y demás pedrería, para el ephod, y para el racional.",
      "10": "Y todo sabio de corazón de entre vosotros, vendrá y hará todas las cosas que Jehová ha mandado:",
      "11": "El tabernáculo, su tienda, y su cubierta, y sus anillos, y sus tablas, sus barras, sus columnas, y sus basas;",
      "12": "El arca, y sus varas, la cubierta, y el velo de la tienda;",
      "13": "La mesa, y sus varas, y todos sus vasos, y el pan de la proposición.",
      "14": "El candelero de la luminaria, y sus vasos, y sus candilejas, y el aceite para la luminaria;",
      "15": "Y el altar del perfume, y sus varas, y el aceite de la unción, y el perfume aromático, y el pabellón de la puerta, para la entrada del tabernáculo;",
      "16": "El altar del holocausto, y su enrejado de metal, y sus varas, y todos sus vasos, y la fuente con su basa;",
      "17": "Las cortinas del atrio, sus columnas, y sus basas, y el pabellón de la puerta del atrio;",
      "18": "Las estacas del tabernáculo, y las estacas del atrio, y sus cuerdas;",
      "19": "Las vestiduras del servicio para ministrar en el santuario, las sagradas vestiduras de Aarón el sacerdote, y las vestiduras de sus hijos para servir en el sacerdocio.",
      "20": "Y salió toda la congregación de los hijos de Israel de delante de Moisés.",
      "21": "Y vino todo varón á quien su corazón estimuló, y todo aquel á quien su espíritu le dió voluntad, y trajeron ofrenda á Jehová para la obra del tabernáculo del testimonio, y para toda su fábrica, y para las sagradas vestiduras.",
      "22": "Y vinieron así hombres como mujeres, todo voluntario de corazón, y trajeron cadenas y zarcillos, sortijas y brazaletes, y toda joya de oro; y cualquiera ofrecía ofrenda de oro á Jehová.",
      "23": "Todo hombre que se hallaba con jacinto, ó púrpura, ó carmesí, ó lino fino, ó pelo de cabras, ó cueros rojos de carneros, ó cueros de tejones, lo traía.",
      "24": "Cualquiera que ofrecía ofrenda de plata ó de metal, traía á Jehová la ofrenda: y todo el que se hallaba con madera de Sittim, traíala para toda la obra del servicio.",
      "25": "Además todas las mujeres sabias de corazón hilaban de sus manos, y traían lo que habían hilado: cárdeno, ó púrpura, ó carmesí, ó lino fino.",
      "26": "Y todas las mujeres cuyo corazón las levantó en sabiduría, hilaron pelos de cabras.",
      "27": "Y los príncipes trajeron piedras de onix, y las piedras de los engastes para el ephod y el racional;",
      "28": "Y la especia aromática y aceite, para la luminaria, y para el aceite de la unción, y para el perfume aromático.",
      "29": "De los hijos de Israel, así hombres como mujeres, todos los que tuvieron corazón voluntario para traer para toda la obra, que Jehová había mandado por medio de Moisés que hiciesen, trajeron ofrenda voluntaria á Jehová.",
      "30": "Y dijo Moisés á los hijos de Israel: Mirad, Jehová ha nombrado á Bezaleel hijo de Uri, hijo de Hur, de la tribu de Judá;",
      "31": "Y lo ha henchido de espíritu de Dios, en sabiduría, en inteligencia, y en ciencia, y en todo artificio,",
      "32": "Para proyectar inventos, para trabajar en oro, y en plata, y en metal,",
      "33": "Y en obra de pedrería para engastar, y en obra de madera, para trabajar en toda invención ingeniosa.",
      "34": "Y ha puesto en su corazón el que pueda enseñar, así él como Aholiab hijo de Ahisamac, de la tribu de Dan:",
      "35": "Y los ha henchido de sabiduría de corazón, para que hagan toda obra de artificio, y de invención, y de recamado en jacinto, y en púrpura, y en carmesí, y en lino fino, y en telar; para que hagan toda labor, é inventen todo diseño."
    },
    "36": {
      "1": "HIZO, pues, Bezaleel y Aholiab, y todo hombre sabio de corazón, á quien Jehová dió sabiduría é inteligencia para que supiesen hacer toda la obra del servicio del santuario, todas las cosas que había mandado Jehová.",
      "2": "Y Moisés llamó á Bezaleel y á Aholiab, y á todo varón sabio de corazón, en cuyo corazón había dado Jehová sabiduría, y á todo hombre á quien su corazón le movió á llegarse á la obra, para trabajar en ella;",
      "3": "Y tomaron de delante de Moisés toda la ofrenda que los hijos de Israel habían traído para la obra del servicio del santuario, á fin de hacerla. Y ellos le traían aún ofrenda voluntaria cada mañana.",
      "4": "Vinieron, por tanto, todos los maestros que hacían toda la obra del santuario, cada uno de la obra que hacía.",
      "5": "Y hablaron á Moisés, diciendo: El pueblo trae mucho más de lo que es menester para la atención de hacer la obra que Jehová ha mandado que se haga.",
      "6": "Entonces Moisés mandó pregonar por el campo, diciendo: Ningún hombre ni mujer haga más obra para ofrecer para el santuario. Y así fue el pueblo impedido de ofrecer;",
      "7": "Pues tenia material abundante para hacer toda la obra, y sobraba.",
      "8": "Y todos los sabios de corazón entre los que hacían la obra, hicieron el tabernáculo de diez cortinas, de lino torcido, y de jacinto, y de púrpura y carmesí; las cuales hicieron de obra prima, con querubines.",
      "9": "La longitud de la una cortina era de veintiocho codos, y la anchura de cuatro codos: todas las cortinas tenían una misma medida.",
      "10": "Y juntó las cinco cortinas la una con la otra: asimismo unió las otras cinco cortinas la una con la otra.",
      "11": "E hizo las lazadas de color de jacinto en la orilla de la una cortina, en el borde, á la juntura; y así hizo en la orilla al borde de la segunda cortina, en la juntura.",
      "12": "Cincuenta lazadas hizo en la una cortina, y otras cincuenta en la segunda cortina, en el borde, en la juntura; las unas lazadas enfrente de las otras.",
      "13": "Hizo también cincuenta corchetes de oro, con los cuales juntó las cortinas, la una con la otra; é hízose un tabernáculo.",
      "14": "Hizo asimismo cortinas de pelo de cabras para la tienda sobre el tabernáculo, é hízolas en número de once.",
      "15": "La longitud de la una cortina era de treinta codos, y la anchura de cuatro codos: las once cortinas tenían una misma medida.",
      "16": "Y juntó las cinco cortinas de por sí, y las seis cortinas aparte.",
      "17": "Hizo además cincuenta lazadas en la orilla de la postrera cortina en la juntura, y otras cincuenta lazadas en la orilla de la otra cortina en la juntura.",
      "18": "Hizo también cincuenta corchetes de metal para juntar la tienda, de modo que fuese una.",
      "19": "E hizo una cubierta para la tienda de cueros rojos de carneros, y una cubierta encima de cueros de tejones.",
      "20": "Además hizo las tablas para el tabernáculo de madera de Sittim, para estar derechas.",
      "21": "La longitud de cada tabla de diez codos, y de codo y medio la anchura.",
      "22": "Cada tabla tenía dos quicios enclavijados el uno delante del otro: así hizo todas las tablas del tabernáculo.",
      "23": "Hizo, pues, las tablas para el tabernáculo: veinte tablas al lado del austro, al mediodía.",
      "24": "Hizo también las cuarenta basas de plata debajo de las veinte tablas: dos basas debajo de la una tabla para sus dos quicios, y dos basas debajo de la otra tabla para sus dos quicios.",
      "25": "Y para el otro lado del tabernáculo, á la parte del aquilón, hizo veinte tablas,",
      "26": "Con sus cuarenta basas de plata: dos basas debajo de la una tabla, y dos basas debajo de la otra tabla.",
      "27": "Y para el lado occidental del tabernáculo hizo seis tablas.",
      "28": "Para las esquinas del tabernáculo en los dos lados hizo dos tablas,",
      "29": "Las cuales se juntaban por abajo, y asimismo por arriba á un gozne: y así hizo á la una y á la otra en las dos esquinas.",
      "30": "Eran, pues, ocho tablas, y sus basas de plata dieciséis; dos basas debajo de cada tabla.",
      "31": "Hizo también las barras de madera de Sittim; cinco para las tablas del un lado del tabernáculo,",
      "32": "Y cinco barras para las tablas del otro lado del tabernáculo, y cinco barras para las tablas del lado del tabernáculo á la parte occidental.",
      "33": "E hizo que la barra del medio pasase por medio de las tablas del un cabo al otro.",
      "34": "Y cubrió las tablas de oro, é hizo de oro los anillos de ellas por donde pasasen las barras: cubrió también de oro las barras.",
      "35": "Hizo asimismo el velo de cárdeno, y púrpura, y carmesí, y lino torcido, el cual hizo con querubines de delicada obra.",
      "36": "Y para él hizo cuatro columnas de madera de Sittim; y cubriólas de oro, los capiteles de las cuales eran de oro; é hizo para ellas cuatro basas de plata de fundición.",
      "37": "Hizo también el velo para la puerta del tabernáculo, de jacinto, y púrpura, y carmesí, y lino torcido, obra de recamador;",
      "38": "Y sus cinco columnas con sus capiteles: y cubrió las cabezas de ellas y sus molduras de oro: pero sus cinco basas las hizo de metal."
    },
    "37": {
      "1": "HIZO también Bezaleel el arca de madera de Sittim: su longitud era de dos codos y medio, y de codo y medio su anchura, y su altura de otro codo y medio:",
      "2": "Y cubrióla de oro puro por de dentro y por de fuera, é hízole una cornisa de oro en derredor.",
      "3": "Hízole además de fundición cuatro anillos de oro á sus cuatro esquinas; en el un lado dos anillos y en el otro lado dos anillos.",
      "4": "Hizo también las varas de madera de Sittim, y cubriólas de oro.",
      "5": "Y metió las varas por los anillos á los lados del arca, para llevar el arca.",
      "6": "Hizo asimismo la cubierta de oro puro: su longitud de dos codos y medio, y su anchura de codo y medio.",
      "7": "Hizo también los dos querubines de oro, hízolos labrados á martillo, á los dos cabos de la cubierta:",
      "8": "El un querubín de esta parte al un cabo, y el otro querubín de la otra parte al otro cabo de la cubierta: hizo los querubines á sus dos cabos.",
      "9": "Y los querubines extendían sus alas por encima, cubriendo con sus alas la cubierta: y sus rostros el uno enfrente del otro, hacia la cubierta los rostros de los querubines.",
      "10": "Hizo también la mesa de madera de Sittim; su longitud de dos codos, y su anchura de un codo, y de codo y medio su altura;",
      "11": "Y cubrióla de oro puro, é hízole una cornisa de oro en derredor.",
      "12": "Hízole también una moldura alrededor, del ancho de una mano, á la cual moldura hizo la cornisa de oro en circunferencia.",
      "13": "Hízole asimismo de fundición cuatro anillos de oro, y púsolos á las cuatro esquinas que correspondían á los cuatro pies de ella.",
      "14": "Delante de la moldura estaban los anillos, por los cuales se metiesen las varas para llevar la mesa.",
      "15": "E hizo las varas de madera de Sittim para llevar la mesa, y cubriólas de oro.",
      "16": "También hizo los vasos que habían de estar sobre la mesa, sus platos, y sus cucharas, y sus cubiertos y sus tazones con que se había de libar, de oro fino.",
      "17": "Hizo asimismo el candelero de oro puro, é hízolo labrado á martillo: su pie y su caña, sus copas, sus manzanas y sus flores eran de lo mismo.",
      "18": "De sus lados salían seis brazos; tres brazos del un lado del candelero, y otros tres brazos del otro lado del candelero:",
      "19": "En el un brazo, tres copas figura de almendras, una manzana y una flor; y en el otro brazo tres copas figura de almendras, una manzana y una flor: y así en los seis brazos que salían del candelero.",
      "20": "Y en el candelero había cuatro copas figura de almendras, sus manzanas y sus flores:",
      "21": "Y una manzana debajo de los dos brazos de lo mismo, y otra manzana debajo de los otros dos brazos de lo mismo, y otra manzana debajo de los otros dos brazos de lo mismo, conforme á los seis brazos que salían de él.",
      "22": "Sus manzanas y sus brazos eran de lo mismo; todo era una pieza labrada á martillo, de oro puro.",
      "23": "Hizo asimismo sus siete candilejas, y sus despabiladeras, y sus platillos, de oro puro;",
      "24": "De un talento de oro puro lo hizo, con todos sus vasos.",
      "25": "Hizo también el altar del perfume de madera de Sittim: un codo su longitud, y otro codo su anchura, era cuadrado; y su altura de dos codos; y sus cuernos de la misma pieza.",
      "26": "Y cubriólo de oro puro, su mesa y sus paredes alrededor, y sus cuernos: é hízole una corona de oro alrededor.",
      "27": "Hízole también dos anillos de oro debajo de la corona en las dos esquinas á los dos lados, para pasar por ellos las varas con que había de ser conducido.",
      "28": "E hizo las varas de madera de Sittim, y cubriólas de oro.",
      "29": "Hizo asimismo el aceite santo de la unción, y el fino perfume aromático, de obra de perfumador."
    },
    "38": {
      "1": "IGUALMENTE hizo el altar del holocausto de madera de Sittim: su longitud de cinco codos, y su anchura de otros cinco codos, cuadrado, y de tres codos de altura.",
      "2": "E hízole sus cuernos á sus cuatro esquinas, los cuales eran de la misma pieza, y cubriólo de metal.",
      "3": "Hizo asimismo todos los vasos del altar: calderas, y tenazas, y tazones, y garfios, y palas: todos sus vasos hizo de metal.",
      "4": "E hizo para el altar el enrejado de metal, de hechura de red, que puso en su cerco por debajo hasta el medio del altar.",
      "5": "Hizo también cuatro anillos de fundición á los cuatro cabos del enrejado de metal, para meter las varas.",
      "6": "E hizo las varas de madera de Sittim, y cubriólas de metal.",
      "7": "Y metió las varas por los anillos á los lados del altar, para llevarlo con ellas: hueco lo hizo, de tablas.",
      "8": "También hizo la fuente de metal, con su basa de metal, de los espejos de las que velaban á la puerta del tabernáculo del testimonio.",
      "9": "Hizo asimismo el atrio; á la parte austral del mediodía las cortinas del atrio eran de cien codos, de lino torcido:",
      "10": "Sus columnas veinte, con sus veinte basas de metal: los capiteles de las columnas y sus molduras, de plata.",
      "11": "Y á la parte del aquilón cortinas de cien codos: sus columnas veinte, con sus veinte basas de metal; los capiteles de las columnas y sus molduras, de plata.",
      "12": "A la parte del occidente cortinas de cincuenta codos: sus columnas diez, y sus diez basas; los capiteles de las columnas y sus molduras, de plata.",
      "13": "Y á la parte oriental, al levante, cortinas de cincuenta codos:",
      "14": "Al un lado cortinas de quince codos, sus tres columnas, y sus tres basas;",
      "15": "Al otro lado, de la una parte y de la otra de la puerta del atrio, cortinas de á quince codos, sus tres columnas, y sus tres basas.",
      "16": "Todas las cortinas del atrio alrededor eran de lino torcido.",
      "17": "Y las basas de las columnas eran de metal; los capiteles de las columnas y sus molduras, de plata; asimismo las cubiertas de las cabezas de ellas, de plata: y todas las columnas del atrio tenían molduras de plata.",
      "18": "Y el pabellón de la puerta del atrio fue de obra de recamado, de jacinto, y púrpura, y carmesí, y lino torcido: la longitud de veinte codos, y la altura en el ancho de cinco codos, conforme á las cortinas del atrio.",
      "19": "Y sus columnas fueron cuatro con sus cuatro basas de metal: y sus capiteles de plata; y las cubiertas de los capiteles de ellas y sus molduras, de plata.",
      "20": "Y todas las estacas del tabernáculo y del atrio alrededor fueron de metal.",
      "21": "Estas son las cuentas del tabernáculo, del tabernáculo del testimonio, lo que fué contado de orden de Moisés por mano de Ithamar, hijo de Aarón sacerdote, para el ministerio de los Levitas.",
      "22": "Y Bezaleel, hijo de Uri, hijo de Hur, de la tribu de Judá, hizo todas las cosas que Jehová mandó á Moisés.",
      "23": "Y con él estaba Aholiab, hijo de Ahisamac, de la tribu de Dan, artífice, y diseñador, y recamador en jacinto, y púrpura, y carmesí, y lino fino.",
      "24": "Todo el oro empleado en la obra, en toda la obra del santuario, el cual fué oro de ofrenda, fué veintinueve talentos, y setecientos y treinta siclos, según el siclo del santuario.",
      "25": "Y la plata de los contados de la congregación fué cien talentos, y mil setecientos setenta y cinco siclos, según el siclo del santuario:",
      "26": "Medio por cabeza, medio siclo, según el siclo del santuario, á todos los que pasaron por cuenta de edad de veinte años y arriba, que fueron seiscientos tres mil quinientos cincuenta.",
      "27": "Hubo además cien talentos de plata para hacer de fundición las basas del santuario y las basas del velo: en cien basas cien talentos, á talento por basa.",
      "28": "Y de los mil setecientos setenta y cinco siclos hizo los capiteles de las columnas, y cubrió los capiteles de ellas, y las ciñó.",
      "29": "Y el metal de la ofrenda fue setenta talentos, y dos mil cuatrocientos siclos;",
      "30": "Del cual hizo las basas de la puerta del tabernáculo del testimonio, y el altar de metal, y su enrejado de metal, y todos los vasos del altar.",
      "31": "Y las basas del atrio alrededor, y las basas de la puerta del atrio, y todas las estacas del tabernáculo, y todas las estacas del atrio alrededor."
    },
    "39": {
      "1": "Y DEL jacinto, y púrpura, y carmesí, hicieron las vestimentas del ministerio para ministrar en el santuario, y asimismo hicieron las vestiduras sagradas para Aarón; como Jehová lo había mandado á Moisés.",
      "2": "Hizo también el ephod de oro, de cárdeno y púrpura y carmesí, y lino torcido.",
      "3": "Y extendieron las planchas de oro, y cortaron hilos para tejerlos entre el jacinto, y entre la púrpura, y entre el carmesí, y entre el lino, con delicada obra.",
      "4": "Hiciéronle las hombreras que se juntasen; y uníanse en sus dos lados.",
      "5": "Y el cinto del ephod que estaba sobre él, era de lo mismo, conforme á su obra; de oro, jacinto, y púrpura, y carmesí, y lino torcido; como Jehová lo había mandado á Moisés.",
      "6": "Y labraron las piedras oniquinas cercadas de engastes de oro, grabadas de grabadura de sello con los nombres de los hijos de Israel:",
      "7": "Y púsolas sobre las hombreras del ephod, por piedras de memoria á los hijos de Israel; como Jehová lo había á Moisés mandado.",
      "8": "Hizo también el racional de primorosa obra, como la obra del ephod, de oro, jacinto, y púrpura, y carmesí, y lino torcido.",
      "9": "Era cuadrado: doblado hicieron el racional: su longitud era de un palmo, y de un palmo su anchura, doblado.",
      "10": "Y engastaron en él cuatro órdenes de piedras. El primer orden era un sardio, un topacio, y un carbunclo: este el primer orden.",
      "11": "El segundo orden, una esmeralda, un zafiro, y un diamante.",
      "12": "El tercer orden, un ligurio, un ágata, y un amatista.",
      "13": "Y el cuarto orden, un berilo, un onix, y un jaspe: cercadas y encajadas en sus engastes de oro.",
      "14": "Las cuales piedras eran conforme á los nombres de los hijos de Israel, doce según los nombres de ellos; como grabaduras de sello, cada una con su nombre según las doce tribus.",
      "15": "Hicieron también sobre el racional las cadenas pequeñas de hechura de trenza, de oro puro.",
      "16": "Hicieron asimismo los dos engastes y los dos anillos, de oro; los cuales dos anillos de oro pusieron en los dos cabos del racional.",
      "17": "Y pusieron las dos trenzas de oro en aquellos dos anillos á los cabos del racional.",
      "18": "Y fijaron los dos cabos de las dos trenzas en los dos engastes, que pusieron sobre las hombreras del ephod, en la parte delantera de él.",
      "19": "E hicieron dos anillos de oro, que pusieron en los dos cabos del racional, en su orilla, á la parte baja del ephod.",
      "20": "Hicieron además dos anillos de oro, los cuales pusieron en las dos hombreras del ephod, abajo en la parte delantera, delante de su juntura, sobre el cinto del ephod.",
      "21": "Y ataron el racional de sus anillos á los anillos del ephod con un cordón de jacinto, para que estuviese sobre el cinto del mismo ephod, y no se apartase el racional del ephod; como Jehová lo había mandado á Moisés.",
      "22": "Hizo también el manto del ephod de obra de tejedor, todo de jacinto.",
      "23": "Con su abertura en medio de él, como el cuello de un coselete, con un borde en derredor de la abertura, porque no se rompiese.",
      "24": "E hicieron en las orillas del manto las granadas de jacinto, y púrpura, y carmesí, y lino torcido.",
      "25": "Hicieron también las campanillas de oro puro, las cuales campanillas pusieron entre las granadas por las orillas del manto alrededor entre las granadas:",
      "26": "Una campanilla y una granada, una campanilla y una granada alrededor, en las orillas del manto, para ministrar; como Jehová lo mandó á Moisés.",
      "27": "Igualmente hicieron las túnicas de lino fino de obra de tejedor, para Aarón y para sus hijos;",
      "28": "Asimismo la mitra de lino fino, y los adornos de los chapeos (tiaras) de lino fino, y los pañetes de lino, de lino torcido;",
      "29": "También el cinto de lino torcido, y de jacinto, y púrpura, y carmesí, de obra de recamador; como Jehová lo mandó á Moisés.",
      "30": "Hicieron asimismo la plancha de la diadema santa de oro puro, y escribieron en ella de grabadura de sello, el rótulo, SANTIDAD A JEHOVA.",
      "31": "Y pusieron en ella un cordón de jacinto, para colocarla en alto sobre la mitra; como Jehová lo había mandado á Moisés.",
      "32": "Y fue acabada toda la obra del tabernáculo, del tabernáculo del testimonio: é hicieron los hijos de Israel como Jehová lo había mandado á Moisés: así lo hicieron.",
      "33": "Y trajeron el tabernáculo á Moisés, el tabernáculo y todos sus vasos; sus corchetes, sus tablas, sus barras, y sus columnas, y sus basas;",
      "34": "Y la cubierta de pieles rojas de carneros, y la cubierta de pieles de tejones, y el velo del pabellón;",
      "35": "El arca del testimonio, y sus varas, y la cubierta;",
      "36": "La mesa, todos sus vasos, y el pan de la proposición;",
      "37": "El candelero limpio, sus candilejas, las lámparas que debían mantenerse en orden, y todos sus vasos, y el aceite para la luminaria;",
      "38": "Y el altar de oro, y el aceite de la unción, y el perfume aromático, y el pabellón para la puerta del tabernáculo;",
      "39": "El altar de metal, con su enrejado de metal, sus varas, y todos sus vasos; y la fuente, y su basa;",
      "40": "Las cortinas del atrio, y sus columnas, y sus basas, y el pabellón para la puerta del atrio, y sus cuerdas, y sus estacas, y todos los vasos del servicio del tabernáculo, del tabernáculo del testimonio;",
      "41": "Las vestimentas del servicio para ministrar en el santuario, las sagradas vestiduras para Aarón el sacerdote, y las vestiduras de sus hijos, para ministrar en el sacerdocio.",
      "42": "En conformidad á todas las cosas que Jehová había mandado á Moisés, así hicieron los hijos de Israel toda la obra.",
      "43": "Y vió Moisés toda la obra, y he aquí que la habían hecho como Jehová había mandado; y bendíjolos."
    },
    "40": {
      "1": "Y JEHOVA habló á Moisés, diciendo:",
      "2": "En el primer día del mes primero harás levantar el tabernáculo, el tabernáculo del testimonio:",
      "3": "Y pondrás en él el arca del testimonio, y la cubrirás con el velo:",
      "4": "Y meterás la mesa, y la pondrás en orden: meterás también el candelero y encenderás sus lámparas:",
      "5": "Y pondrás el altar de oro para el perfume delante del arca del testimonio, y pondrás el pabellón delante de la puerta del tabernáculo.",
      "6": "Después pondrás el altar del holocausto delante de la puerta del tabernáculo, del tabernáculo del testimonio.",
      "7": "Luego pondrás la fuente entre el tabernáculo del testimonio y el altar; y pondrás agua en ella.",
      "8": "Finalmente pondrás el atrio en derredor, y el pabellón de la puerta del atrio.",
      "9": "Y tomarás el aceite de la unción y ungirás el tabernáculo, y todo lo que está en él; y le santificarás con todos sus vasos, y será santo.",
      "10": "Ungirás también el altar del holocausto y todos sus vasos: y santificarás el altar, y será un altar santísimo.",
      "11": "Asimismo ungirás la fuente y su basa, y la santificarás.",
      "12": "Y harás llegar á Aarón y á sus hijos á la puerta del tabernáculo del testimonio, y los lavarás con agua.",
      "13": "Y harás vestir á Aarón las vestiduras sagradas, y lo ungirás, y lo consagrarás, para que sea mi sacerdote.",
      "14": "Después harás llegar sus hijos, y les vestirás las túnicas:",
      "15": "Y los ungirás como ungiste á su padre, y serán mis sacerdotes: y será que su unción les servirá por sacerdocio perpetuo por sus generaciones.",
      "16": "Y Moisés hizo conforme á todo lo que Jehová le mandó; así lo hizo.",
      "17": "Y así en el día primero del primer mes, en el segundo año, el tabernáculo fué erigido.",
      "18": "Y Moisés hizo levantar el tabernáculo, y asentó sus basas, y colocó sus tablas, y puso sus barras, é hizo alzar sus columnas.",
      "19": "Y extendió la tienda sobre el tabernáculo, y puso la sobrecubierta encima del mismo; como Jehová había mandado á Moisés.",
      "20": "Y tomó y puso el testimonio dentro del arca, y colocó las varas en el arca, y encima la cubierta sobre el arca:",
      "21": "Y metió el arca en el tabernáculo, y puso el velo de la tienda, y cubrió el arca del testimonio; como Jehová había mandado á Moisés.",
      "22": "Y puso la mesa en el tabernáculo del testimonio, al lado septentrional del pabellón, fuera del velo:",
      "23": "Y sobre ella puso por orden los panes delante de Jehová, como Jehová había mandado á Moisés.",
      "24": "Y puso el candelero en el tabernáculo del testimonio, enfrente de la mesa, al lado meridional del pabellón.",
      "25": "Y encendió las lámparas delante de Jehová; como Jehová había mandado á Moisés.",
      "26": "Puso también el altar de oro en el tabernáculo del testimonio, delante del velo:",
      "27": "Y encendió sobre él el perfume aromático; como Jehová había mandado á Moisés.",
      "28": "Puso asimismo la cortina de la puerta del tabernáculo.",
      "29": "Y colocó el altar del holocausto á la puerta del tabernáculo, del tabernáculo del testimonio; y ofreció sobre él holocausto y presente; como Jehová había mandado á Moisés.",
      "30": "Y puso la fuente entre el tabernáculo del testimonio y el altar; y puso en ella agua para lavar.",
      "31": "Y Moisés y Aarón y sus hijos lavaban en ella sus manos y sus pies.",
      "32": "Cuando entraban en el tabernáculo del testimonio, y cuando se llegaban al altar, se lavaban; como Jehová había mandado á Moisés.",
      "33": "Finalmente erigió el atrio en derredor del tabernáculo y del altar, y puso la cortina de la puerta del atrio. Y así acabó Moisés la obra.",
      "34": "Entonces una nube cubrió el tabernáculo del testimonio, y la gloria de Jehová hinchió el tabernáculo.",
      "35": "Y no podía Moisés entrar en el tabernáculo del testimonio, porque la nube estaba sobre él, y la gloria de Jehová lo tenía lleno.",
      "36": "Y cuando la nube se alzaba del tabernáculo, los hijos de Israel se movían en todas sus jornadas:",
      "37": "Pero si la nube no se alzaba, no se partían hasta el día en que ella se alzaba.",
      "38": "Porque la nube de Jehová estaba de día sobre el tabernáculo, y el fuego estaba de noche en él, á vista de toda la casa de Israel, en todas sus jornadas."
    }
  },
  "leviticus": {
    "1": {
      "1": "Y LLAMO Jehová á Moisés, y habló con él desde el tabernáculo del testimonio, diciendo:",
      "2": "Habla á los hijos de Israel, y diles: Cuando alguno de entre vosotros ofreciere ofrenda á Jehová, de ganado vacuno ú ovejuno haréis vuestra ofrenda.",
      "3": "Si su ofrenda fuere holocausto de vacas, macho sin tacha lo ofrecerá: de su voluntad lo ofrecerá á la puerta del tabernáculo del testimonio delante de Jehová.",
      "4": "Y pondrá su mano sobre la cabeza del holocausto; y él lo aceptará para expiarle.",
      "5": "Entonces degollará el becerro en la presencia de Jehová; y los sacerdotes, hijos de Aarón, ofrecerán la sangre, y la rociarán alrededor sobre el altar, el cual está á la puerta del tabernáculo del testimonio.",
      "6": "Y desollará el holocausto, y lo dividirá en sus piezas.",
      "7": "Y los hijos de Aarón sacerdote pondrán fuego sobre el altar, y compondrán la leña sobre el fuego.",
      "8": "Luego los sacerdotes, hijos de Aarón, acomodarán las piezas, la cabeza y el redaño, sobre la leña que está sobre el fuego, que habrá encima del altar:",
      "9": "Y lavará con agua sus intestinos y sus piernas: y el sacerdote hará arder todo sobre el altar: holocausto es, ofrenda encendida de olor suave á Jehová.",
      "10": "Y si su ofrenda para holocausto fuere de ovejas, de los corderos, ó de las cabras, macho sin defecto lo ofrecerá.",
      "11": "Y ha de degollarlo al lado septentrional del altar delante de Jehová: y los sacerdotes, hijos de Aarón, rociarán su sangre sobre el altar alrededor.",
      "12": "Y lo dividirá en sus piezas, con su cabeza y su redaño; y el sacerdote las acomodará sobre la leña que está sobre el fuego, que habrá encima del altar;",
      "13": "Y lavará sus entrañas y sus piernas con agua; y el sacerdote lo ofrecerá todo, y harálo arder sobre el altar; holocausto es, ofrenda encendida de olor suave á Jehová.",
      "14": "Y si el holocausto se hubiere de ofrecer á Jehová de aves, presentará su ofrenda de tórtolas, ó de palominos.",
      "15": "Y el sacerdote la ofrecerá sobre el altar, y ha de quitarle la cabeza, y hará que arda en el altar; y su sangre será exprimida sobre la pared del altar.",
      "16": "Y le ha de quitar el buche y las plumas, lo cual echará junto al altar, hacia el oriente, en el lugar de las cenizas.",
      "17": "Y la henderá por sus alas, mas no la dividirá en dos: y el sacerdote la hará arder sobre el altar, sobre la leña que estará en el fuego; holocausto es, ofrenda encendida de olor suave á Jehová."
    },
    "2": {
      "1": "Y CUANDO alguna persona ofreciere oblación de presente á Jehová, su ofrenda será flor de harina, sobre la cual echará aceite, y pondrá sobre ella incienso:",
      "2": "Y la traerá á los sacerdotes, hijos de Aarón; y de ello tomará el sacerdote su puño lleno de su flor de harina y de su aceite, con todo su incienso, y lo hará arder sobre el altar: ofrenda encendida para recuerdo, de olor suave á Jehová.",
      "3": "Y la sobra del presente será de Aarón y de sus hijos: es cosa santísima de las ofrendas que se queman á Jehová.",
      "4": "Y cuando ofrecieres ofrenda de presente cocida en horno, será de tortas de flor de harina sin levadura, amasadas con aceite, y hojaldres sin levadura untadas con aceite.",
      "5": "Mas si tu presente fuere ofrenda de sartén, será de flor de harina sin levadura, amasada con aceite,",
      "6": "La cual partirás en piezas, y echarás sobre ella aceite: es presente.",
      "7": "Y si tu presente fuere ofrenda cocida en cazuela, haráse de flor de harina con aceite.",
      "8": "Y traerás á Jehová la ofrenda que se hará de estas cosas, y la presentarás al sacerdote, el cual la llegará al altar.",
      "9": "Y tomará el sacerdote de aquel presente, en memoria del mismo, y harálo arder sobre el altar; ofrenda encendida, de suave olor á Jehová.",
      "10": "Y lo restante del presente será de Aarón y de sus hijos; es cosa santísima de las ofrendas que se queman á Jehová.",
      "11": "Ningun presente que ofreciereis á Jehová, será con levadura: porque de ninguna cosa leuda, ni de ninguna miel, se ha de quemar ofrenda á Jehová.",
      "12": "En la ofrenda de las primicias las ofreceréis á Jehová: mas no subirán sobre el altar en olor de suavidad.",
      "13": "Y sazonarás toda ofrenda de tu presente con sal; y no harás que falte jamás de tu presente la sal de la alianza de tu Dios: en toda ofrenda tuya ofrecerás sal.",
      "14": "Y si ofrecieres á Jehová presente de primicias, tostarás al fuego las espigas verdes, y el grano desmenuzado ofrecerás por ofrenda de tus primicias.",
      "15": "Y pondrás sobre ella aceite, y pondrás sobre ella incienso: es presente.",
      "16": "Y el sacerdote hará arder, en memoria del don, parte de su grano desmenuzado, y de su aceite con todo su incienso; es ofrenda encendida á Jehová."
    },
    "3": {
      "1": "Y SI su ofrenda fuere sacrificio de paces, si hubiere de ofrecerlo de ganado vacuno, sea macho ó hembra, sin defecto lo ofrecerá delante de Jehová:",
      "2": "Y pondrá su mano sobre la cabeza de su ofrenda, y la degollará á la puerta del tabernáculo del testimonio; y los sacerdotes, hijos de Aarón, rociarán su sangre sobre el altar en derredor.",
      "3": "Luego ofrecerá del sacrificio de las paces, por ofrenda encendida á Jehová, el sebo que cubre los intestinos, y todo el sebo que está sobre las entrañas,",
      "4": "Y los dos riñones, y el sebo que está sobre ellos, y sobre los ijares, y con los riñones quitará el redaño que está sobre el hígado.",
      "5": "Y los hijos de Aarón harán arder esto en el altar, sobre el holocausto que estará sobre la leña que habrá encima del fuego; es ofrenda de olor suave á Jehová.",
      "6": "Mas si de ovejas fuere su ofrenda para sacrificio de paces á Jehová, sea macho ó hembra, ofrecerála sin tacha.",
      "7": "Si ofreciere cordero por su ofrenda, ha de ofrecerlo delante de Jehová:",
      "8": "Y pondrá su mano sobre la cabeza de su ofrenda, y después la degollará delante del tabernáculo del testimonio; y los hijos de Aarón rociarán su sangre sobre el altar en derredor.",
      "9": "Y del sacrificio de las paces ofrecerá por ofrenda encendida á Jehová, su sebo, y la cola entera, la cual quitará á raíz del espinazo, y el sebo que cubre los intestinos, y todo el sebo que está sobre las entrañas:",
      "10": "Asimismo los dos riñones, y el sebo que está sobre ellos, y el que está sobre los ijares, y con los riñones quitará el redaño de sobre el hígado.",
      "11": "Y el sacerdote hará arder esto sobre el altar; vianda de ofrenda encendida á Jehová.",
      "12": "Y si fuere cabra su ofrenda ofrecerála delante de Jehová:",
      "13": "Y pondrá su mano sobre la cabeza de ella, y la degollará delante del tabernáculo del testimonio; y los hijos de Aarón rociarán su sangre sobre el altar en derredor.",
      "14": "Después ofrecerá de ella su ofrenda encendida á Jehová; el sebo que cubre los intestinos, y todo el sebo que está sobre las entrañas,",
      "15": "Y los dos riñones, y el sebo que está sobre ellos, y el que está sobre los ijares, y con los riñones quitará el redaño de sobre el hígado.",
      "16": "Y el sacerdote hará arder esto sobre el altar; es vianda de ofrenda que se quema en olor de suavidad á Jehová: el sebo todo es de Jehová.",
      "17": "Estatuto perpetuo por vuestras edades; en todas vuestras moradas, ningún sebo ni ninguna sangre comeréis."
    },
    "4": {
      "1": "Y HABLO Jehová á Moisés, diciendo:",
      "2": "Habla á los hijos de Israel, diciendo: Cuando alguna persona pecare por yerro en alguno de los mandamientos de Jehová sobre cosas que no se han de hacer, y obrare contra alguno de ellos;",
      "3": "Si sacerdote ungido pecare según el pecado del pueblo, ofrecerá á Jehová, por su pecado que habrá cometido, un becerro sin tacha para expiación.",
      "4": "Y traerá el becerro á la puerta del tabernáculo del testimonio delante de Jehová, y pondrá su mano sobre la cabeza del becerro, y lo degollará delante de Jehová.",
      "5": "Y el sacerdote ungido tomará de la sangre del becerro, y la traerá al tabernáculo del testimonio;",
      "6": "Y mojará el sacerdote su dedo en la sangre, y rociará de aquella sangre siete veces delante de Jehová, hacia el velo del santuario.",
      "7": "Y pondrá el sacerdote de la sangre sobre los cuernos del altar del perfume aromático, que está en el tabernáculo del testimonio delante de Jehová: y echará toda la sangre del becerro al pie del altar del holocausto, que está á la puerta del tabernáculo del testimonio.",
      "8": "Y tomará del becerro para la expiación todo su sebo, el sebo que cubre los intestinos, y todo el sebo que está sobre las entrañas,",
      "9": "Y los dos riñones, y el sebo que está sobre ellos, y el que está sobre los ijares, y con los riñones quitará el redaño de sobre el hígado,",
      "10": "De la manera que se quita del buey del sacrificio de las paces: y el sacerdote lo hará arder sobre el altar del holocausto.",
      "11": "Y el cuero del becerro, y toda su carne, con su cabeza, y sus piernas, y sus intestinos, y su estiércol,",
      "12": "En fin, todo el becerro sacará fuera del campo, á un lugar limpio, donde se echan las cenizas, y lo quemará al fuego sobre la leña: en donde se echan las cenizas será quemado.",
      "13": "Y si toda la congregación de Israel hubiere errado, y el negocio estuviere oculto á los ojos del pueblo, y hubieren hecho algo contra alguno de los mandamientos de Jehová en cosas que no se han de hacer, y fueren culpables;",
      "14": "Luego que fuere entendido el pecado sobre que delinquieron, la congregación ofrecerá un becerro por expiación, y lo traerán delante del tabernáculo del testimonio.",
      "15": "Y los ancianos de la congregación pondrán sus manos sobre la cabeza del becerro delante de Jehová; y en presencia de Jehová degollarán aquel becerro.",
      "16": "Y el sacerdote ungido meterá de la sangre del becerro en el tabernáculo del testimonio.",
      "17": "Y mojará el sacerdote su dedo en la misma sangre, y rociará siete veces delante de Jehová hacia el velo.",
      "18": "Y de aquella sangre pondrá sobre los cuernos del altar que está delante de Jehová en el tabernáculo del testimonio, y derramará toda la sangre al pie del altar del holocausto, que está á la puerta del tabernáculo del testimonio.",
      "19": "Y le quitará todo el sebo, y harálo arder sobre el altar.",
      "20": "Y hará de aquel becerro como hizo con el becerro de la expiación; lo mismo hará de él: así hará el sacerdote expiación por ellos, y obtendrán perdón.",
      "21": "Y sacará el becerro fuera del campamento, y lo quemará como quemó el primer becerro; expiación de la congregación.",
      "22": "Y cuando pecare el príncipe, é hiciere por yerro algo contra alguno de todos los mandamientos de Jehová su Dios, sobre cosas que no se han de hacer, y pecare;",
      "23": "Luego que le fuere conocido su pecado en que ha delinquido, presentará por su ofrenda un macho cabrío sin defecto.",
      "24": "Y pondrá su mano sobre la cabeza del macho cabrío, y lo degollará en el lugar donde se degüella el holocausto delante de Jehová; es expiación.",
      "25": "Y tomará el sacerdote con su dedo de la sangre de la expiación, y pondrá sobre los cuernos del altar del holocausto, y derramará la sangre al pie del altar del holocausto:",
      "26": "Y quemará todo su sebo sobre el altar, como el sebo del sacrificio de las paces: así hará el sacerdote por él la expiación de su pecado, y tendrá perdón.",
      "27": "Y si alguna persona del común del pueblo pecare por yerro, haciendo algo contra alguno de los mandamientos de Jehová en cosas que no se han de hacer, y delinquiere;",
      "28": "Luego que le fuere conocido su pecado que cometió, traerá por su ofrenda una hembra de las cabras, una cabra sin defecto, por su pecado que habrá cometido:",
      "29": "Y pondrá su mano sobre la cabeza de la expiación, y la degollará en el lugar del holocausto.",
      "30": "Luego tomará el sacerdote en su dedo de su sangre, y pondrá sobre los cuernos del altar del holocausto, y derramará toda su sangre al pie del altar.",
      "31": "Y le quitará todo su sebo, de la manera que fue quitado el sebo del sacrificio de las paces; y el sacerdote lo hará arder sobre el altar en olor de suavidad á Jehová: así hará el sacerdote expiación por él, y será perdonado.",
      "32": "Y si trajere cordero para su ofrenda por el pecado, hembra sin defecto traerá.",
      "33": "Y pondrá su mano sobre la cabeza de la expiación, y la degollará por expiación en el lugar donde se degüella el holocausto.",
      "34": "Después tomará el sacerdote con su dedo de la sangre de la expiación, y pondrá sobre los cuernos del altar del holocausto; y derramará toda la sangre al pie del altar.",
      "35": "Y le quitará todo su sebo, como fué quitado el sebo del sacrificio de las paces, y harálo el sacerdote arder en el altar sobre la ofrenda encendida á Jehová: y le hará el sacerdote expiación de su pecado que habrá cometido, y será perdonado."
    },
    "5": {
      "1": "Y CUANDO alguna persona pecare, que hubiere oído la voz del que juró, y él fuere testigo que vió, ó supo, si no lo denunciare, él llevará su pecado.",
      "2": "Asimismo la persona que hubiere tocado en cualquiera cosa inmunda, sea cuerpo muerto de bestia inmunda, ó cuerpo muerto de animal inmundo, ó cuerpo muerto de reptil inmundo, bien que no lo supiere, será inmunda y habrá delinquido:",
      "3": "O si tocare á hombre inmundo en cualquiera inmundicia suya de que es inmundo, y no lo echare de ver; si después llega á saberlo, será culpable.",
      "4": "También la persona que jurare, pronunciando con sus labios hacer mal ó bien, en cualesquiera cosas que el hombre profiere con juramento, y él no lo conociere; si después lo entiende, será culpado en una de estas cosas.",
      "5": "Y será que cuando pecare en alguna de estas cosas, confesará aquello en que pecó:",
      "6": "Y para su expiación traerá á Jehová por su pecado que ha cometido, una hembra de los rebaños, una cordera ó una cabra como ofrenda de expiación; y el sacerdote hará expiación por él de su pecado.",
      "7": "Y si no le alcanzare para un cordero, traerá en expiación por su pecado que cometió, dos tórtolas ó dos palominos á Jehová; el uno para expiación, y el otro para holocausto.",
      "8": "Y ha de traerlos al sacerdote, el cual ofrecerá primero el que es para expiación, y desunirá su cabeza de su cuello, mas no la apartará del todo:",
      "9": "Y rociará de la sangre de la expiación sobre la pared del altar; y lo que sobrare de la sangre lo exprimirá al pie del altar; es expiación.",
      "10": "Y del otro hará holocausto conforme al rito; y hará por él el sacerdote expiación de su pecado que cometió, y será perdonado.",
      "11": "Mas si su posibilidad no alcanzare para dos tórtolas, ó dos palominos, el que pecó traerá por su ofrenda la décima parte de un epha de flor de harina por expiación. No pondrá sobre ella aceite, ni sobre ella pondrá incienso, porque es expiación.",
      "12": "Traerála, pues, al sacerdote, y el sacerdote tomará de ella su puño lleno, en memoria suya, y la hará arder en el altar sobre las ofrendas encendidas á Jehová: es expiación.",
      "13": "Y hará el sacerdote expiación por él de su pecado que cometió en alguna de estas cosas, y será perdonado; y el sobrante será del sacerdote, como el presente de vianda.",
      "14": "Habló más Jehová á Moisés, diciendo:",
      "15": "Cuando alguna persona cometiere falta, y pecare por yerro en las cosas santificadas á Jehová, traerá su expiación á Jehová, un carnero sin tacha de los rebaños, conforme á tu estimación, en siclos de plata del siclo del santuario, en ofrenda por el pecado:",
      "16": "Y pagará aquello de las cosas santas en que hubiere pecado, y añadirá á ello el quinto, y lo dará al sacerdote: y el sacerdote hará expiación por él con el carnero del sacrificio por el pecado, y será perdonado.",
      "17": "Finalmente, si una persona pecare, ó hiciere alguna de todas aquellas cosas que por mandamiento de Jehová no se han de hacer, aun sin hacerlo á sabiendas, es culpable, y llevará su pecado.",
      "18": "Traerá, pues, al sacerdote por expiación, según tú lo estimes, un carnero sin tacha de los rebaños: y el sacerdote hará expiación por él de su yerro que cometió por ignorancia, y será perdonado.",
      "19": "Es infracción, y ciertamente delinquió contra Jehová."
    },
    "6": {
      "1": "Y HABLO Jehová á Moisés, diciendo:",
      "2": "Cuando una persona pecare, é hiciere prevaricación contra Jehová, y negare á su prójimo lo encomendado ó dejado en su mano, ó bien robare, ó calumniare á su prójimo;",
      "3": "O sea que hallando lo perdido, después lo negare, y jurare en falso, en alguna de todas aquellas cosas en que suele pecar el hombre:",
      "4": "Entonces será que, puesto habrá pecado y ofendido, restituirá aquello que robó, ó por el daño de la calumnia, ó el depósito que se le encomendó, ó lo perdido que halló,",
      "5": "O todo aquello sobre que hubiere jurado falsamente; lo restituirá, pues, por entero, y añadirá á ello la quinta parte, que ha de pagar á aquel á quien pertenece en el día de su expiación.",
      "6": "Y por su expiación traerá á Jehová un carnero sin tacha de los rebaños, conforme á tu estimación, al sacerdote para la expiación.",
      "7": "Y el sacerdote hará expiación por él delante de Jehová, y obtendrá perdón de cualquiera de todas las cosas en que suele ofender.",
      "8": "Habló aún Jehová á Moisés, diciendo:",
      "9": "Manda á Aarón y á sus hijos diciendo: Esta es la ley del holocausto: (es holocausto, porque se quema sobre el altar toda la noche hasta la mañana, y el fuego del altar arderá en él:)",
      "10": "El sacerdote se pondrá su vestimenta de lino, y se vestirá pañetes de lino sobre su carne; y cuando el fuego hubiere consumido el holocausto, apartará él las cenizas de sobre el altar, y pondrálas junto al altar.",
      "11": "Después se desnudará de sus vestimentas, y se pondrá otras vestiduras, y sacará las cenizas fuera del real al lugar limpio.",
      "12": "Y el fuego encendido sobre el altar no ha de apagarse, sino que el sacerdote pondrá en él leña cada mañana, y acomodará sobre él el holocausto, y quemará sobre él los sebos de las paces.",
      "13": "El fuego ha de arder continuamente en el altar; no se apagará.",
      "14": "Y esta es la ley del presente: Han de ofrecerlo los hijos de Aarón delante de Jehová, delante del altar.",
      "15": "Y tomará de él un puñado de la flor de harina del presente, y de su aceite, y todo el incienso que está sobre el presente, y harálo arder sobre el altar por memoria, en olor suavísimo á Jehová.",
      "16": "Y el sobrante de ella lo comerán Aarón y sus hijos: sin levadura se comerá en el lugar santo; en el atrio del tabernáculo del testimonio lo comerán.",
      "17": "No se cocerá con levadura: helo dado á ellos por su porción de mis ofrendas encendidas; es cosa santísima, como la expiación por el pecado, y como la expiación por la culpa.",
      "18": "Todos los varones de los hijos de Aarón comerán de ella. Estatuto perpetuo será para vuestras generaciones tocante á las ofrendas encendidas de Jehová: toda cosa que tocare en ellas será santificada.",
      "19": "Y habló Jehová á Moisés, diciendo:",
      "20": "Esta es la ofrenda de Aarón y de sus hijos, que ofrecerán á Jehová el día que serán ungidos: la décima parte de un epha de flor de harina, presente perpetuo, la mitad á la mañana y la mitad á la tarde.",
      "21": "En sartén se aderezará con aceite; frita la traerás, y los pedazos cocidos del presente ofrecerás á Jehová en olor de suavidad.",
      "22": "Y el sacerdote que en lugar de Aarón fuere ungido de entre sus hijos, hará la ofrenda; estatuto perpetuo de Jehová: toda ella será quemada.",
      "23": "Y todo presente de sacerdote será enteramente quemado; no se comerá.",
      "24": "Y habló Jehová á Moisés, diciendo:",
      "25": "Habla á Aarón y á sus hijos, diciendo: Esta es la ley de la expiación: en el lugar donde será degollado el holocausto, será degollada la expiación por el pecado delante de Jehová: es cosa santísima.",
      "26": "El sacerdote que la ofreciere por expiación, la comerá: en el lugar santo será comida, en el atrio del tabernáculo del testimonio.",
      "27": "Todo lo que en su carne tocare, será santificado; y si cayere de su sangre sobre el vestido, lavarás aquello sobre que cayere, en el lugar santo.",
      "28": "Y la vasija de barro en que fuere cocida, será quebrada: y si fuere cocida en vasija de metal, será fregada y lavada con agua.",
      "29": "Todo varón de entre los sacerdotes la comerá: es cosa santísima.",
      "30": "Mas no se comerá de expiación alguna, de cuya sangre se metiere en el tabernáculo del testimonio para reconciliar en el santuario: al fuego será quemada."
    },
    "7": {
      "1": "ASIMISMO esta es la ley de la expiación de la culpa: es cosa muy santa.",
      "2": "En el lugar donde degollaren el holocausto, degollarán la víctima por la culpa; y rociará su sangre en derredor sobre el altar:",
      "3": "Y de ella ofrecerá todo su sebo, la cola, y el sebo que cubre los intestinos.",
      "4": "Y los dos riñones, y el sebo que está sobre ellos, y el que está sobre los ijares; y con los riñones quitará el redaño de sobre el hígado.",
      "5": "Y el sacerdote lo hará arder sobre el altar; ofrenda encendida á Jehová: es expiación de la culpa.",
      "6": "Todo varón de entre los sacerdotes la comerá: será comida en el lugar santo: es cosa muy santa.",
      "7": "Como la expiación por el pecado, así es la expiación de la culpa: una misma ley tendrán: será del sacerdote que habrá hecho la reconciliación con ella.",
      "8": "Y el sacerdote que ofreciere holocausto de alguno, el cuero del holocausto que ofreciere, será para él.",
      "9": "Asimismo todo presente que se cociere en horno, y todo el que fuere aderezado en sartén, ó en cazuela, será del sacerdote que lo ofreciere.",
      "10": "Y todo presente amasado con aceite, y seco, será de todos los hijos de Aarón, tanto al uno como al otro.",
      "11": "Y esta es la ley del sacrificio de las paces, que se ofrecerá á Jehová:",
      "12": "Si se ofreciere en hacimiento de gracias, ofrecerá por sacrificio de hacimiento de gracias tortas sin levadura amasadas con aceite, y hojaldres sin levadura untadas con aceite, y flor de harina frita en tortas amasadas con aceite.",
      "13": "Con tortas de pan leudo ofrecerá su ofrenda en el sacrificio de hacimiento de gracias de sus paces.",
      "14": "Y de toda la ofrenda presentará una parte por ofrenda elevada á Jehová, y será del sacerdote que rociare la sangre de los pacíficos.",
      "15": "Y la carne del sacrificio de sus pacíficos en hacimiento de gracias, se comerá en el día que fuere ofrecida: no dejarán de ella nada para otro día.",
      "16": "Mas si el sacrificio de su ofrenda fuere voto, ó voluntario, el día que ofreciere su sacrificio será comido; y lo que de él quedare, comerse ha el día siguiente:",
      "17": "Y lo que quedare para el tercer día de la carne del sacrificio, será quemado en el fuego.",
      "18": "Y si se comiere de la carne del sacrificio de sus paces el tercer día, el que lo ofreciere no será acepto, ni le será imputado; abominación será, y la persona que de él comiere llevará su pecado.",
      "19": "Y la carne que tocare á alguna cosa inmunda, no se comerá; al fuego será quemada; mas cualquiera limpio comerá de aquesta carne.",
      "20": "Y la persona que comiere la carne del sacrificio de paces, el cual es de Jehová, estando inmunda, aquella persona será cortada de sus pueblos.",
      "21": "Además, la persona que tocare alguna cosa inmunda, en inmundicia de hombre, ó en animal inmundo, ó en cualquiera abominación inmunda, y comiere la carne del sacrificio de las paces, el cual es de Jehová, aquella persona será cortada de sus pueblos.",
      "22": "Habló aún Jehová á Moisés, diciendo:",
      "23": "Habla á los hijos de Israel, diciendo: Ningún sebo de buey, ni de cordero, ni de cabra, comeréis.",
      "24": "El sebo de animal mortecino, y el sebo del que fué arrebatado de fieras, se aparejará para cualquiera otro uso, mas no lo comeréis.",
      "25": "Porque cualquiera que comiere sebo de animal, del cual se ofrece á Jehová ofrenda encendida, la persona que lo comiere, será cortada de sus pueblos.",
      "26": "Además, ninguna sangre comeréis en todas vuestras habitaciones, así de aves como de bestias.",
      "27": "Cualquiera persona que comiere alguna sangre, la tal persona será cortada de sus pueblos.",
      "28": "Habló más Jehová á Moisés, diciendo:",
      "29": "Habla á los hijos de Israel, diciendo: El que ofreciere sacrificio de sus paces á Jehová, traerá su ofrenda del sacrificio de sus paces á Jehová;",
      "30": "Sus manos traerán las ofrendas que se han de quemar á Jehová: traerá el sebo con el pecho: el pecho para que éste sea agitado, como sacrificio agitado delante de Jehová;",
      "31": "Y el sebo lo hará arder el sacerdote en el altar, mas el pecho será de Aarón y de sus hijos.",
      "32": "Y daréis al sacerdote para ser elevada en ofrenda, la espaldilla derecha de los sacrificios de vuestras paces.",
      "33": "El que de los hijos de Aarón ofreciere la sangre de las paces, y el sebo, de él será en porción la espaldilla derecha;",
      "34": "Porque he tomado de los hijos de Israel, de los sacrificios de sus paces, el pecho que se agita, y la espaldilla elevada en ofrenda, y lo he dado á Aarón el sacerdote y á sus hijos, por estatuto perpetuo de los hijos de Israel.",
      "35": "Esta es por la unción de Aarón y la unción de sus hijos, la parte de ellos en las ofrendas encendidas á Jehová, desde el día que él los allegó para ser sacerdotes de Jehová:",
      "36": "Lo cual mandó Jehová que les diesen, desde el día que él los ungió de entre los hijos de Israel, por estatuto perpetuo en sus generaciones.",
      "37": "Esta es la ley del holocausto, del presente, de la expiación por el pecado, y de la culpa, y de las consagraciones, y del sacrificio de las paces:",
      "38": "La cual intimó Jehová á Moisés, en el monte de Sinaí, el día que mandó á los hijos de Israel que ofreciesen sus ofrendas á Jehová en el desierto de Sinaí."
    },
    "8": {
      "1": "Y HABLO Jehová á Moisés, diciendo:",
      "2": "Toma á Aarón y á sus hijos con él, y las vestimentas, y el aceite de la unción, y el becerro de la expiación, y los dos carneros, y el canastillo de los ázimos;",
      "3": "Y reúne toda la congregación á la puerta del tabernáculo del testimonio.",
      "4": "Hizo, pues, Moisés como Jehová le mandó, y juntóse la congregación á la puerta del tabernáculo del testimonio.",
      "5": "Y dijo Moisés á la congregación: Esto es lo que Jehová ha mandado hacer.",
      "6": "Entonces Moisés hizo llegar á Aarón y á sus hijos, y lavólos con agua.",
      "7": "Y puso sobre él la túnica, y ciñólo con el cinto; vistióle después el manto, y puso sobre él el ephod, y ciñólo con el cinto del ephod, y ajustólo con él.",
      "8": "Púsole luego encima el racional, y en él puso el Urim y Thummim.",
      "9": "Después puso la mitra sobre su cabeza; y sobre la mitra en su frente delantero puso la plancha de oro, la diadema santa; como Jehová había mandado á Moisés.",
      "10": "Y tomó Moisés el aceite de la unción, y ungió el tabernáculo, y todas las cosas que estaban en él, y santificólas.",
      "11": "Y roció de él sobre el altar siete veces, y ungió el altar y todos sus vasos, y la fuente y su basa, para santificarlos.",
      "12": "Y derramó del aceite de la unción sobre la cabeza de Aarón, y ungiólo para santificarlo.",
      "13": "Después Moisés hizo llegar los hijos de Aarón, y vistióles las túnicas, y ciñólos con cintos, y ajustóles los chapeos (tiaras), como Jehová lo había mandado á Moisés.",
      "14": "Hizo luego llegar el becerro de la expiación, y Aarón y sus hijos pusieron sus manos sobre la cabeza del becerro de la expiación.",
      "15": "Y degollólo; y Moisés tomó la sangre, y puso con su dedo sobre los cuernos del altar alrededor, y purificó el altar; y echó la demás sangre al pie del altar, y santificólo para reconciliar sobre él.",
      "16": "Después tomó todo el sebo que estaba sobre los intestinos, y el redaño del hígado, y los dos riñones, y el sebo de ellos, é hízolo Moisés arder sobre el altar.",
      "17": "Mas el becerro, y su cuero, y su carne, y su estiércol, quemólo al fuego fuera del real; como Jehová lo había mandado á Moisés.",
      "18": "Después hizo llegar el carnero del holocausto, y Aarón y sus hijos pusieron sus manos sobre la cabeza del carnero:",
      "19": "Y degollólo; y roció Moisés la sangre sobre el altar en derredor.",
      "20": "Y cortó el carnero en trozos; y Moisés hizo arder la cabeza, y los trozos, y el sebo.",
      "21": "Lavó luego con agua los intestinos y piernas, y quemó Moisés todo el carnero sobre el altar: holocausto en olor de suavidad, ofrenda encendida á Jehová; como lo había Jehová mandado á Moisés.",
      "22": "Después hizo llegar el otro carnero, el carnero de las consagraciones, y Aarón y sus hijos pusieron sus manos sobre la cabeza del carnero:",
      "23": "Y degollólo; y tomó Moisés de su sangre, y puso sobre la ternilla de la oreja derecha de Aarón, y sobre el dedo pulgar de su mano derecha, y sobre el dedo pulgar de su pie derecho.",
      "24": "Hizo llegar luego los hijos de Aarón, y puso Moisés de la sangre sobre la ternilla de sus orejas derechas, y sobre los pulgares de sus manos derechas, y sobre los pulgares de sus pies derechos: y roció Moisés la sangre sobre el altar en derredor;",
      "25": "Y después tomó el sebo, y la cola, y todo el sebo que estaba sobre los intestinos, y el redaño del hígado, y los dos riñones, y el sebo de ellos, y la espaldilla derecha;",
      "26": "Y del canastillo de los ázimos, que estaba delante de Jehová, tomó una torta sin levadura, y una torta de pan de aceite, y una lasaña, y púsolo con el sebo y con la espaldilla derecha;",
      "27": "Y púsolo todo en las manos de Aarón, y en las manos de sus hijos, é hízolo mecer: ofrenda agitada delante de Jehová.",
      "28": "Después tomó aquellas cosas Moisés de las manos de ellos, é hízolas arder en el altar sobre el holocausto: las consagraciones en olor de suavidad, ofrenda encendida á Jehová.",
      "29": "Y tomó Moisés el pecho, y meciólo, ofrenda agitada delante de Jehová: del carnero de las consagraciones aquella fue la parte de Moisés; como Jehová lo había mandado á Moisés.",
      "30": "Luego tomó Moisés del aceite de la unción, y de la sangre que estaba sobre el altar, y roció sobre Aarón, y sobre sus vestiduras, sobre sus hijos, y sobre las vestiduras de sus hijos con él; y santificó á Aarón, y sus vestiduras, y á sus hijos, y las vestiduras de sus hijos con él.",
      "31": "Y dijo Moisés á Aarón y á sus hijos: Comed la carne á la puerta del tabernáculo del testimonio; y comedla allí con el pan que está en el canastillo de las consagraciones, según yo he mandado, diciendo: Aarón y sus hijos la comerán.",
      "32": "Y lo que sobrare de la carne y del pan, habéis de quemarlo al fuego.",
      "33": "De la puerta del tabernáculo del testimonio no saldréis en siete días, hasta el día que se cumplieren los días de vuestras consagraciones: porque por siete días seréis consagrados.",
      "34": "De la manera que hoy se ha hecho, mandó hacer Jehová para expiaros.",
      "35": "A la puerta, pues, del tabernáculo del testimonio estaréis día y noche por siete días, y guardaréis la ordenanza delante de Jehová, para que no muráis; porque así me ha sido mandado.",
      "36": "Y Aarón y sus hijos hicieron todas las cosas que mandó Jehová por medio de Moisés."
    },
    "9": {
      "1": "Y FUÉ en el día octavo, que Moisés llamó á Aarón y á sus hijos, y á los ancianos de Israel;",
      "2": "Y dijo á Aarón: Toma de la vacada un becerro para expiación, y un carnero para holocausto, sin defecto, y ofrécelos delante de Jehová.",
      "3": "Y á los hijos de Israel hablarás, diciendo: Tomad un macho cabrío para expiación, y un becerro y un cordero de un año, sin tacha, para holocausto;",
      "4": "Asimismo un buey y un carnero para sacrificio de paces, que inmoléis delante de Jehová; y un presente amasado con aceite: porque Jehová se aparecerá hoy á vosotros.",
      "5": "Y llevaron lo que mandó Moisés delante del tabernáculo del testimonio, y llegóse toda la congregación, y pusiéronse delante de Jehová.",
      "6": "Entonces Moisés dijo: Esto es lo que mandó Jehová; hacedlo, y la gloria de Jehová se os aparecerá.",
      "7": "Y dijo Moisés á Aarón: Llégate al altar, y haz tu expiación, y tu holocausto, y haz la reconciliación por ti y por el pueblo: haz también la ofrenda del pueblo, y haz la reconciliación por ellos; como ha mandado Jehová.",
      "8": "Entonces llegóse Aarón al altar; y degolló su becerro de la expiación que era por él.",
      "9": "Y los hijos de Aarón le trajeron la sangre; y él mojó su dedo en la sangre, y puso sobre los cuernos del altar, y derramó la demás sangre al pie del altar;",
      "10": "Y el sebo y riñones y redaño del hígado, de la expiación, hízolos arder sobre el altar; como Jehová lo había mandado á Moisés.",
      "11": "Mas la carne y el cuero los quemó al fuego fuera del real.",
      "12": "Degolló asimismo el holocausto, y los hijos de Aarón le presentaron la sangre, la cual roció él alrededor sobre el altar.",
      "13": "Presentáronle después el holocausto, á trozos, y la cabeza; é hízolos quemar sobre el altar.",
      "14": "Luego lavó los intestinos y las piernas, y quemólos sobre el holocausto en el altar.",
      "15": "Ofreció también la ofrenda del pueblo, y tomó el macho cabrío que era para la expiación del pueblo, y degollólo, y lo ofreció por el pecado como el primero.",
      "16": "Y ofreció el holocausto, é hizo según el rito.",
      "17": "Ofreció asimismo el presente, é hinchió de él su mano, y lo hizo quemar sobre el altar, además del holocausto de la mañana.",
      "18": "Degolló también el buey y el carnero en sacrificio de paces, que era del pueblo: y los hijos de Aarón le presentaron la sangre (la cual roció él sobre el altar alrededor),",
      "19": "Y los sebos del buey; y del carnero la cola con lo que cubre las entrañas, y los riñones, y el redaño del hígado:",
      "20": "Y pusieron los sebos sobre los pechos, y él quemó los sebos sobre el altar:",
      "21": "Empero los pechos, con la espaldilla derecha, meciólos Aarón por ofrenda agitada delante de Jehová; como Jehová lo había mandado á Moisés.",
      "22": "Después alzó Aarón sus manos hacia el pueblo y bendíjolos: y descendió de hacer la expiación, y el holocausto, y el sacrificio de las paces.",
      "23": "Y entraron Moisés y Aarón en el tabernáculo del testimonio; y salieron, y bendijeron al pueblo: y la gloria de Jehová se apareció á todo el pueblo.",
      "24": "Y salió fuego de delante de Jehová, y consumió el holocausto y los sebos sobre el altar; y viéndolo todo el pueblo, alabaron, y cayeron sobre sus rostros."
    }
  }
};

