
	
export const bib_verses = {
  "jeremiah": {
    "48": {
      "1": "ACERCA de Moab. Así ha dicho Jehová de los ejércitos, Dios de Israel: ­Ay de Nebo! que fué destruída, fué avergonzada; Chîriathaim fué tomada; fué confusa Misgab, y desmayó.",
      "2": "No se alabará ya más Moab; contra Hesbón maquinaron mal, diciendo: Venid, y quitémosla de entre las gentes. También tú, Madmén, serás cortada, espada irá tras ti.",
      "3": "Voz de clamor de Horonaim, destrucción y gran quebrantamiento!",
      "4": "Moab fué quebrantada; hicieron que se oyese el clamor de sus pequeños.",
      "5": "Porque á la subida de Luhith con lloro subirá el que llora; porque á la bajada de Horonaim los enemigos oyeron clamor de quebranto.",
      "6": "Huid, salvad vuestra vida, y sed como retama en el desierto.",
      "7": "Pues por cuanto confiaste en tus haciendas, en tus tesoros, tú también serás tomada: y Chêmos saldrá en cautiverio, los sacerdotes y sus príncipes juntamente.",
      "8": "Y vendrá destruidor á cada una de las ciudades, y ninguna ciudad escapará: arruinaráse también el valle, y será destruída la campiña, como ha dicho Jehová.",
      "9": "Dad alas á Moab, para que volando se vaya; pues serán desiertas sus ciudades hasta no quedar en ellas morador.",
      "10": "Maldito el que hiciere engañosamente la obra de Jehová, y maldito el que detuviere su cuchillo de la sangre.",
      "11": "Quieto estuvo Moab desde su mocedad, y sobre sus heces ha estado él reposado, y no fué trasegado de vaso en vaso, ni nunca fué en cautiverio: por tanto quedó su sabor en él, y su olor no se ha trocado.",
      "12": "Por eso, he aquí que vienen días, ha dicho Jehová, en que yo le enviaré trasportadores que lo harán trasportar; y vaciarán sus vasos, y romperán sus odres.",
      "13": "Y avergonzaráse Moab de Chêmos, á la manera que la casa de Israel se avergonzó de Beth-el, su confianza.",
      "14": "¿Cómo diréis: Somos valientes, y robustos hombres para la guerra?",
      "15": "Destruído fué Moab, y sus ciudades asoló, y sus escogidos mancebos descendieron al degolladero, ha dicho el Rey, cuyo nombre es Jehová de los ejércitos.",
      "16": "Cercano está el quebrantamiento de Moab para venir, y su mal se apresura mucho.",
      "17": "Compadeceos de él todos los que estáis alrededor suyo; y todos los que sabéis su nombre, decid: ¿Cómo se quebró la vara de fortaleza, el báculo de hermosura?",
      "18": "Desciende de la gloria, siéntate en seco, moradora hija de Dibón; porque el destruidor de Moab subió contra ti, disipó tus fortalezas.",
      "19": "Párate en el camino, y mira, oh moradora de Aroer: pregunta á la que va huyendo, y á la que escapó; dile: ¿Qué ha acontecido?",
      "20": "Avergonzóse Moab, porque fué quebrantado: aullad y clamad: denunciad en Arnón que Moab es destruído.",
      "21": "Y que vino juicio sobre la tierra de la campiña; sobre Holón, y sobre Jahzah, y sobre Mephaath,",
      "22": "Y sobre Dibón, y sobre Nebo, y sobre Beth-diblathaim,",
      "23": "Y sobre Chîriathaim, y sobre Beth-gamul, y sobre Beth-meon,",
      "24": "Y sobre Chêrioth, y sobre Bosra, y sobre todas las ciudades de tierra de Moab, las de lejos y las de cerca.",
      "25": "Cortado es el cuerno de Moab, y su brazo quebrantado, dice Jehová.",
      "26": "Embriagadlo, porque contra Jehová se engrandeció; y revuélquese Moab sobre su vómito, y sea también él por escarnio.",
      "27": "¿Y no te fué á ti Israel por escarnio, como si lo tomaran entre ladrones? porque desde que de él hablaste, tú te has movido.",
      "28": "Desamparad las ciudades, y habitad en peñascos, oh moradores de Moab; y sed como la paloma que hace nido detrás de la boca de la caverna.",
      "29": "Oído hemos la soberbia de Moab, que es muy soberbio: su hinchazón y su orgullo, y su altivez y la altanería de su corazón.",
      "30": "Yo conozco, dice Jehová, su cólera; mas no tendrá efecto: sus mentiras no han de aprovechar le.",
      "31": "Por tanto yo aullaré sobre Moab, y sobre todo Moab haré clamor, y sobre los hombres de Kir-heres gemiré.",
      "32": "Con lloro de Jazer lloraré por ti, oh vid de Sibma: tus sarmientos pasaron la mar, llegaron hasta la mar de Jazer: sobre tu agosto y sobre tu vendimia vino destruidor.",
      "33": "Y será cortada la alegría y el regocijo de los campos labrados, y de la tierra de Moab: y haré cesar el vino de los lagares: no pisarán con canción; la canción no será canción.",
      "34": "El clamor, desde Hesbón hasta Eleale; hasta Jaaz dieron su voz: desde Zoar hasta Horonaim, becerra de tres años: porque también las aguas de Nimrin serán destruídas.",
      "35": "Y haré cesar de Moab, dice Jehová, quien sacrifique en altar, y quien ofrezca sahumerio á sus dioses.",
      "36": "Por tanto, mi corazón resonará como flautas por causa de Moab, asimismo resonará mi corazón á modo de flautas por los hombres de Kir-heres: porque perecieron las riquezas que había hecho.",
      "37": "Porque en toda cabeza habrá calva, y toda barba será raída; sobre todas manos rasguños, y sacos sobre todos los lomos.",
      "38": "Sobre todas las techumbres de Moab y en sus calles, todo él será llanto; porque yo quebranté á Moab como á vaso que no agrada, dice Jehová.",
      "39": "Aullad: ­Cómo ha sido quebrantado! ­cómo volvió la cerviz Moab, y fué avergonzado! Y fué Moab en escarnio y en espanto á todos los que están en sus alrededores.",
      "40": "Porque así ha dicho Jehová: He aquí que como águila volará, y extenderá sus alas á Moab.",
      "41": "Tomadas son las ciudades, y tomadas son las fortalezas; y será aquel día el corazón de los valientes de Moab como el corazón de mujer en angustias.",
      "42": "Y Moab será destruído para dejar de ser pueblo: porque se engrandeció contra Jehová.",
      "43": "Miedo y hoyo y lazo sobre ti, oh morador de Moab, dice Jehová.",
      "44": "El que huyere del miedo, caerá en el hoyo; y el que saliere del hoyo, será preso del lazo: porque yo traeré sobre él, sobre Moab, año de su visitación, dice Jehová.",
      "45": "A la sombra de Hesbón se pararon los que huían de la fuerza; mas salió fuego de Hesbón, y llama de en medio de Sihón, y quemó el rincón de Moab, y la mollera de los hijos revoltosos.",
      "46": "Ay de ti, Moab! pereció el pueblo de Chêmos: porque tus hijos fueron presos para cautividad, y tus hijas para cautiverio.",
      "47": "Empero haré tornar el cautiverio de Moab en lo postrero de los tiempos, dice Jehová. Hasta aquí es el juicio de Moab."
    },
    "49": {
      "1": "DE los hijos de Ammón. Así ha dicho Jehová: ¿No tiene hijos Israel? ¿No tiene heredero? ¿Por qué tomó como por heredad el rey de ellos á Gad, y su pueblo habitó en sus ciudades?",
      "2": "Por tanto, he aquí vienen días, ha dicho Jehová, en que haré oir en Rabba de los hijos de Ammón clamor de guerra; y será puesta en montón de asolamiento, y sus ciudades serán puestas á fuego, é Israel tomará por heredad á los que los tomaron á ellos, ha dicho Jehová.",
      "3": "Aulla, oh Hesbón, porque destruída es Hai; clamad, hijas de Rabba, vestíos de sacos, endechad, y rodead por los vallados, porque el rey de ellos fué en cautiverio, sus sacerdotes y sus príncipes juntamente.",
      "4": "¿Por qué te glorías de los valles? Tu valle se deshizo, oh hija contumaz, la que confía en sus tesoros, la que dice: ¿Quién vendrá contra mí?",
      "5": "He aquí yo traigo sobre ti espanto, dice el Señor Jehová de los ejércitos, de todos tus alrededores; y seréis lanzados cada uno en derechura de su rostro, y no habrá quien recoja al errante.",
      "6": "Y después de esto haré tornar la cautividad de los hijos de Ammón, dice Jehová.",
      "7": "De Edom. Así ha dicho Jehová de los ejércitos: ¿No hay más sabiduría en Temán? ¿ha perecido el consejo en los sabios? ¿corrompióse su sabiduría?",
      "8": "Huid, volveos, escondeos en simas para estar, oh moradores de Dedán; porque el quebrantamiento de Esaú traeré sobre él, al tiempo que lo tengo de visitar.",
      "9": "Si vendimiadores vinieran contra ti, ¿no dejarán rebuscos? Si ladrones de noche, tomarán lo que hubieren menester.",
      "10": "Mas yo desnudaré á Esaú, descubriré sus escondrijos, y no podrá esconderse: será destruída su simiente, y sus hermanos, y sus vecinos; y no será.",
      "11": "Deja tus huérfanos, yo los criaré; y en mí se confiarán tus viudas.",
      "12": "Porque así ha dicho Jehová: He aquí que los que no estaban condenados á beber del cáliz, beberán ciertamente; ¿y serás tú absuelto del todo? No serás absuelto, sino que de cierto beberás.",
      "13": "Porque por mí he jurado, dice Jehová, que en asolamiento, en oprobio, en soledad, y en maldición, será Bosra; y todas su ciudades serán en asolamientos perpetuos.",
      "14": "La fama oí, que de Jehová había sido enviado mensajero á las gentes, diciendo: Juntaos, y venid contra ella, y levantaos á la batalla.",
      "15": "Porque he aquí que pequeño te he puesto entre las gentes, menospreciado entre los hombres.",
      "16": "Tu arrogancia te engañó, y la soberbia de tu corazón, tú que habitas en cavernas de peñas, que tienes la altura del monte: aunque alces como águila tu nido, de allí te haré descender, dice Jehová.",
      "17": "Y será Edom en asolamiento: todo aquel que pasare por ella se espantará, y silbará sobre todas sus plagas.",
      "18": "Como el trastornamiento de Sodoma y de Gomorra, y de sus ciudades vecinas, dice Jehová, no morará allí nadie, ni la habitará hijo de hombre.",
      "19": "He aquí que como león subirá de la hinchazón del Jordán contra la bella y robusta; porque muy pronto harélo correr de sobre ella, y al que fuere escogido la encargaré; porque ¿quién es semejante á mí? ¿y quién me emplazará? ¿y quién será aquel pastor que me podrá resistir?",
      "20": "Por tanto, oíd el consejo de Jehová, que ha acordado sobre Edom; y sus pensamientos, que ha resuelto sobre los moradores de Temán. Ciertamente los más pequeños del hato los arrastrarán, y destruirán sus moradas con ellos.",
      "21": "Del estruendo de la caída de ellos la tierra tembló, y el grito de su voz se oyó en el mar Bermejo.",
      "22": "He aquí que como águila subirá y volará, y extenderá sus alas sobre Bosra: y el corazón de los valientes de Edom será en aquel día como el corazón de mujer en angustias.",
      "23": "Acerca de Damasco. Confundióse Hamath, y Arphad, porque oyeron malas nuevas: derritiéronse en aguas de desmayo, no pueden sosegarse.",
      "24": "Desmayóse Damasco, volvióse para huir, y tomóle temblor: angustia y dolores le tomaron, como de mujer que está de parto.",
      "25": "Cómo dejaron á la ciudad de alabanza, ciudad de mi gozo!",
      "26": "Por tanto, sus mancebos caerán en sus plazas, y todos los hombres de guerra morirán en aquel día, ha dicho Jehová de los ejércitos.",
      "27": "Y haré encender fuego en el muro de Damasco, y consumirá las casas de Ben-hadad.",
      "28": "De Cedar y de los reinos de Hasor, los cuales hirió Nabucodonosor rey de Babilonia. Así ha dicho Jehová: Levantaos, subid contra Cedar, y destruid los hijos de oriente.",
      "29": "Sus tiendas y su ganados tomarán: sus cortinas, y todos sus vasos, y sus camellos, tomarán para sí; y llamarán contra ellos miedo alrededor.",
      "30": "Huid, trasponeos muy lejos, meteos en simas para estar, oh moradores de Hasor, dice Jehová; porque tomó consejo contra vosotros Nabucodonosor rey de Babilonia, y contra vosotros ha formado designio.",
      "31": "Levantaos, subid á gente pacífica, que vive confiadamente, dice Jehová, que ni tienen puertas ni cerrojos, que viven solitarios.",
      "32": "Y serán sus camellos por presa, y la multitud de sus ganados por despojo; y esparcirélos por todos vientos, echados hasta el postrer rincón; y de todos sus lados les traeré su ruina, dice Jehová.",
      "33": "Y Hasor será morada de chacales, soledad para siempre: ninguno morará allí, ni la habitará hijo de hombre.",
      "34": "Palabra de Jehová que fué á Jeremías profeta acerca de Elam, en el principio del reinado de Sedechîas rey de Judá, diciendo:",
      "35": "Así ha dicho Jehová de los ejércitos: He aquí que yo quiebro el arco de Elam, principio de su fortaleza.",
      "36": "Y traeré sobre Elam los cuatro vientos de los cuatro puntos del cielo, y aventarélos á todos estos vientos; ni habrá gente adonde no vengan extranjeros de Elam.",
      "37": "Y haré que Elam se intimide delante de sus enemigos, y delante de los que buscan su alma; y traeré sobre ellos mal, y el furor de mi enojo, dice Jehová; y enviaré en pos de ellos espada hasta que los acabe.",
      "38": "Y pondré mi silla en Elam, y destruiré de allí rey y príncipe, dice Jehová.",
      "39": "Mas acontecerá en lo postrero de los días, que haré tornar la cautividad de Elam, dice Jehová."
    },
    "50": {
      "1": "PALABRA que habló Jehová contra Babilonia, contra la tierra de los Caldeos, por mano de Jeremías profeta.",
      "2": "Denunciad en las gentes, y haced saber; levantad también bandera: publicad, y no encubráis: decid: Tomada es Babilonia, Bel es confundido, deshecho es Merodach; confundidas son sus esculturas, quebrados son sus ídolos.",
      "3": "Porque subió contra ella gente del aquilón, la cual pondrá su tierra en asolamiento, y no habrá ni hombre ni animal que en ella more: moviéronse, se fueron.",
      "4": "En aquellos días y en aquel tiempo, dice Jehová, vendrán los hijos de Israel, ellos y los hijos de Judá juntamente; é irán andando y llorando, y buscarán á Jehová su Dios.",
      "5": "Preguntarán por el camino de Sión, hacia donde volverán sus rostros, diciendo: Venid, y juntaos á Jehová con pacto eterno, que jamás se ponga en olvido.",
      "6": "Ovejas perdidas fueron mi pueblo: sus pastores las hicieron errar, por los montes las descarriaron: anduvieron de monte en collado, olvidáronse de sus majadas.",
      "7": "Todos los que los hallaban, los comían; y decían sus enemigos: No pecaremos, porque ellos pecaron á Jehová morada de justicia, á Jehová, esperanza de sus padres.",
      "8": "Huid de en medio de Babilonia, y salid de la tierra de los Caldeos, y sed como los mansos delante del ganado.",
      "9": "Porque he aquí que yo suscito y hago subir contra Babilonia reunión de grandes pueblos de la tierra del aquilón; y desde allí se aparejarán contra ella, y será tomada: sus flechas como de valiente diestro, que no se tornará en vano.",
      "10": "Y la Caldea será para presa: todos los que la saquearen, saldrán hartos, dice Jehová.",
      "11": "Porque os alegrasteis, porque os gozasteis destruyendo mi heredad, porque os henchisteis como becerra de renuevos, y relinchasteis como caballos;",
      "12": "Vuestra madre se avergonzó mucho, afrentóse la que os engendró; he aquí será la postrera de las gentes: desierto, sequedad, y páramo.",
      "13": "Por la ira de Jehová no será habitada, sino que asolada será toda ella; todo hombre que pasare por Babilonia se asombrará, y silbará sobre todas sus plagas.",
      "14": "Apercibíos contra Babilonia alrededor, todos los que entesáis arco; tirad contra ella, no escatiméis las saetas: porque pecó contra Jehová.",
      "15": "Gritad contra ella en derredor; dió su mano; caído han sus fundamentos, derribados son sus muros; porque venganza es de Jehová. Tomad venganza de ella; haced con ella como ella hizo.",
      "16": "Talad de Babilonia sembrador, y el que tiene hoz en tiempo de la siega: delante de la espada opresora cada uno volverá el rostro hacia su pueblo, cada uno huirá hacia su tierra.",
      "17": "Ganado descarriado es Israel; leones lo amontonaron: el rey de Asiria lo devoró el primero; este Nabucodonosor rey de Babilonia lo deshuesó el postrero.",
      "18": "Por tanto, así ha dicho Jehová de los ejércitos, Dios de Israel: He aquí que yo visito al rey de Babilonia y á su tierra como visité al rey de Asiria.",
      "19": "Y volveré á traer á Israel á su morada, y pacerá en el Carmelo y en Basán; y en el monte de Ephraim y de Galaad se hartará su alma.",
      "20": "En aquellos días y en aquel tiempo, dice Jehová, la maldad de Israel será buscada, y no parecerá; y los pecados de Judá, y no se hallarán: porque perdonaré á los que yo hubiere dejado.",
      "21": "Sube contra la tierra de Merathaim, contra ella, y contra los moradores de Pekod: destruye y mata en pos de ellos, dice Jehová, y haz conforme á todo lo que yo te he mandado.",
      "22": "Estruendo de guerra en la tierra, y quebrantamiento grande.",
      "23": "Cómo fué cortado y quebrado el martillo de toda la tierra! ­cómo se tornó Babilonia en desierto entre las gentes!",
      "24": "Púsete lazos, y aun fuiste tomada, oh Babilonia, y tú no lo supiste: fuiste hallada, y aun presa, porque provocaste á Jehová.",
      "25": "Abrió Jehová tu tesoro, y sacó los vasos de su furor: porque esta es obra de Jehová, Dios de los ejércitos, en la tierra de los Caldeos.",
      "26": "Venid contra ella desde el cabo de la tierra: abrid sus almacenes: hacedla montones, y destruidla: no le queden reliquias.",
      "27": "Matad todos sus novillos; vayan al matadero: ­ay de ellos! que venido es su día, el tiempo de su visitación.",
      "28": "Voz de los que huyen y escapan de la tierra de Babilonia, para dar las nuevas en Sión de la venganza de Jehová nuestro Dios, de la venganza de su templo.",
      "29": "Haced juntar sobre Babilonia flecheros, á todos los que entesan arco; asentad campo sobre ella alrededor; no escape de ella ninguno: pagadle según su obra; conforme á todo lo que ella hizo, haced con ella: porque contra Jehová se ensoberbeció, contra el Santo de Israel.",
      "30": "Por tanto sus mancebos caerán es sus plazas, y todos su hombres de guerra serán talados en aquel día, dice Jehová.",
      "31": "He aquí yo contra ti, oh soberbio, dice el Señor Jehová de los ejércitos: porque tu día es venido, el tiempo en que te visitaré.",
      "32": "Y el soberbio tropezará y caerá, y no tendrá quien lo levante: y encenderé fuego en sus ciudades, y quemaré todos sus alrededores.",
      "33": "Así ha dicho Jehová de los ejércitos: Oprimidos fueron los hijos de Israel y los hijos de Judá juntamente: y todos los que los tomaron cautivos, se los retuvieron; no los quisieron soltar.",
      "34": "El redentor de ellos es el Fuerte; Jehová de los ejércitos es su nombre: de cierto abogará la causa de ellos, para hacer quietar la tierra, y turbar los moradores de Babilonia.",
      "35": "Cuchillo sobre los Caldeos, dice Jehová, y sobre los moradores de Babilonia, y sobre sus príncipes, y sobre sus sabios.",
      "36": "Cuchillo sobre los adivinos, y se atontarán; cuchillo sobre sus valientes, y serán quebrantados.",
      "37": "Cuchillo sobre sus caballos, y sobre sus carros, y sobre todo el vulgo que está en medio de ella, y serán como mujeres: cuchillo sobre sus tesoros, y serán saqueados.",
      "38": "Sequedad sobre sus aguas, y secaránse: porque tierra es de esculturas, y en ídolos enloquecen.",
      "39": "Por tanto, allí morarán bestias monteses con lobos, morarán también en ella pollos de avestruz: y no más será poblada para siempre, ni se habitará de generación en generación.",
      "40": "Como en el trastornamiento de Dios á Sodoma y á Gomorra y á sus ciudades vecinas, dice Jehová, no morará allí hombre, ni hijo de hombre la habitará.",
      "41": "He aquí viene un pueblo del aquilón; y una nación grande, y muchos reyes se levantarán de los lados de la tierra.",
      "42": "Arco y lanza manejarán; serán crueles, y no tendrán compasión; su voz sonará como la mar, y montarán sobre caballos: apercibirse han como hombre á la pelea, contra ti, oh hija de Babilonia.",
      "43": "Oyó su fama el rey de Babilonia, y sus manos se descoyuntaron: angustia le tomó, dolor como de mujer de parto.",
      "44": "He aquí que como león subirá de la hinchazón del Jordán á la morada fuerte: porque muy pronto le haré correr de sobre ella, y al que fuere escogido la encargaré: porque ¿quién es semejante á mí? ¿y quién me emplazará? ¿ó quién será aquel pastor que me podrá resistir?",
      "45": "Por tanto, oid el consejo de Jehová, que ha acordado sobre Babilonia, y sus pensamientos que ha formado sobre la tierra de los Caldeos: Ciertamente los más pequeños del hato los arrastrarán, y destruirán sus moradas con ellos.",
      "46": "Del grito de la toma de Babilonia la tierra tembló, y el clamor se oyó entre las gentes."
    },
    "51": {
      "1": "ASI ha dicho Jehová: He aquí que yo levanto sobre Babilonia, y sobre sus moradores que se levantan contra mí, un viento destruidor.",
      "2": "Y enviaré á Babilonia aventadores que la avienten, y vaciarán su tierra; porque serán contra ella de todas partes en el día del mal.",
      "3": "Diré al flechero que entesa su arco, y al que se pone orgulloso con su loriga: No perdonéis á sus mancebos, destruid todo su ejército.",
      "4": "Y caerán muertos en la tierra de los Caldeos, y alanceados en sus calles.",
      "5": "Porque Israel y Judá no han enviudado de su Dios, Jehová de los ejércitos, aunque su tierra fué llena de pecado contra el Santo de Israel.",
      "6": "Huid de en medio de Babilonia, y librad cada uno su alma, porque no perezcáis á causa de su maldad: porque el tiempo es de venganza de Jehová; darále su pago.",
      "7": "Vaso de oro fué Babilonia en la mano de Jehová, que embriaga toda la tierra: de su vino bebieron las gentes; aturdiéronse por tanto las naciones.",
      "8": "En un momento cayó Babilonia, y despedazóse: aullad sobre ella; tomad bálsamo para su dolor, quizá sanará.",
      "9": "Curamos á Babilonia, y no ha sanado: dejadla, y vámonos cada uno á su tierra; porque llegado ha hasta el cielo su juicio, y alzádose hasta las nubes.",
      "10": "Jehová sacó á luz nuestras justicias: venid, y contemos en Sión la obra de Jehová nuestro Dios.",
      "11": "Limpiad las saetas, embrazad los escudos: despertado ha Jehová el espíritu de los reyes de Media; porque contra Babilonia es su pensamiento para destruirla; porque venganza es de Jehová, venganza de su templo.",
      "12": "Levantad bandera sobre los muros de Babilonia, reforzad la guardia, poned centinelas, disponed celadas; porque deliberó Jehová, y aun pondrá en efecto lo que ha dicho sobre los moradores de Babilonia.",
      "13": "La que moras entre muchas aguas, rica en tesoros, venido ha tu fin, la medida de tu codicia.",
      "14": "Jehová de los ejércitos juró por su vida, diciendo: Yo te llenaré de hombres como de langostas, y levantarán contra ti gritería.",
      "15": "El es el que hizo la tierra con su fortaleza, el que afirmó el mundo con su sabiduría, y extendió los cielos con inteligencia;",
      "16": "El que da con su voz muchedumbre de aguas del cielo, y hace subir las nubes de lo postrero de la tierra; él hace relámpagos con la lluvia, y saca el viento de sus tesoros.",
      "17": "Todo hombre se ha infatuado y es sin ciencia: avergüénzase todo artífice de la escultura, porque mentira es su vaciadizo, que no tiene espíritu.",
      "18": "Vanidad son, obra de irrisiones; en el tiempo de su visitación perecerán.",
      "19": "No es como ellos la parte de Jacob: porque él es el Formador de todo; é Israel es la vara de su heredad: Jehová de los ejércitos es su nombre.",
      "20": "Martillo me sois, y armas de guerra; y por medio de ti quebrantaré gentes, y por medio de ti desharé reinos;",
      "21": "Y por tu medio quebrantaré caballos y sus cabalgadores, y por medio de ti quebrantaré carros y los que en ellos suben;",
      "22": "Asimismo por tu medio quebrantaré hombres y mujeres, y por medio de ti quebrantaré viejos y mozos, y por tu medio quebrantaré mancebos y vírgenes:",
      "23": "También quebrantaré por medio de ti al pastor y á su manada: quebrantaré por tu medio á labradores y sus yuntas; y duques y príncipes quebrantaré por medio de ti.",
      "24": "Y pagaré á Babilonia y á todos los moradores de Caldea, todo el mal de ellos que hicieron en Sión delante de vuestros ojos, dice Jehová.",
      "25": "He aquí yo contra ti, oh monte destruidor, dice Jehová, que destruiste toda la tierra; y extenderé mi mano sobre ti, y te haré rodar de las peñas, y te tornaré monte quemado.",
      "26": "Y nadie tomará de ti piedra para esquina, ni piedra para cimiento; porque perpetuos asolamientos serás, ha dicho Jehová.",
      "27": "Alzad bandera en la tierra, tocad trompeta en las naciones, apercibid gentes contra ella; juntad contra ella los reinos de Ararat, de Minni, y de Aschênaz; señalad contra ella capitán, haced subir caballos como langostas erizadas.",
      "28": "Apercibid contra ella gentes; á reyes de Media, á sus capitanes, y á todos sus príncipes, y á toda la tierra de su señorío.",
      "29": "Y temblará la tierra, y afligiráse; porque confirmado es contra Babilonia todo el pensamiento de Jehová, para poner la tierra de Babilonia en soledad, y que no haya morador.",
      "30": "Los valientes de Babilonia dejaron de pelear, estuviéronse en sus fuertes: faltóles su fortaleza, tornáronse como mujeres: encendiéronse sus casas, quebráronse sus cerrojos.",
      "31": "Correo se encontrará con correo, mensajero se encontrará con mensajero, para noticiar al rey de Babilonia que su ciudad es tomada por todas partes:",
      "32": "Y los vados fueron tomados, y los carrizos fueron quemados á fuego, y consternáronse los hombres de guerra.",
      "33": "Porque así ha dicho Jehová de los ejércitos, Dios de Israel: La hija de Babilonia es como parva; tiempo es ya de trillarla: de aquí á poco le vendrá el tiempo de la siega.",
      "34": "Comióme, desmenuzóme Nabucodonosor rey de Babilonia; paróme como vaso vacío, tragóme como dragón, hinchió su vientre de mis delicadezas, y echóme.",
      "35": "Sobre Babilonia la violencia contra mí y mi carne, dirá la moradora de Sión; y mi sangre sobre los moradores de Caldea, dirá Jerusalem.",
      "36": "Por tanto, así ha dicho Jehová: He aquí que yo juzgo tu causa y haré tu venganza; y secaré su mar, y haré que quede seca su corriente.",
      "37": "Y será Babilonia para montones, morada de chacales, espanto y silbo, sin morador.",
      "38": "A una rugirán como leones; como cachorros de leones bramarán.",
      "39": "En su calor les pondré sus banquetes; y haréles que se embriaguen, para que se alegren, y duerman eterno sueño, y no despierten, dice Jehová.",
      "40": "Hacerlos he traer como corderos al matadero, como carneros con cabritos.",
      "41": "Cómo fué presa Sesach, y fué tomada la que era alabada por toda la tierra! ­Cómo fué Babilonia por espanto entre las gentes!",
      "42": "Subió la mar sobre Babilonia; de la multitud de sus ondas fué cubierta.",
      "43": "Sus ciudades fueron asoladas, la tierra seca y desierta, tierra que no morará en ella nadie, ni pasará por ella hijo de hombre.",
      "44": "Y visitaré á Bel en Babilonia, y sacaré de su boca lo que ha tragado: y no vendrán más á él gentes; y el muro de Babilonia caerá.",
      "45": "Salid de en medio de ella, pueblo mío, y salvad cada uno su vida de la ira del furor de Jehová.",
      "46": "Y porque no desmaye vuestro corazón, y temáis á causa de la fama que se oirá por la tierra, en un año vendrá la fama, y después en otro año el rumor, y la violencia en la tierra, y el enseñoreador sobre el que enseñorea.",
      "47": "Por tanto, he aquí vienen días que yo visitaré las esculturas de Babilonia, y toda su tierra será avergonzada, y todos sus muertos caerán en medio de ella.",
      "48": "Y los cielos y la tierra, y todo lo que está en ellos, darán alabanzas sobre Babilonia: porque del aquilón vendrán sobre ella destruidores, dice Jehová.",
      "49": "Pues que Babilonia fué causa que cayesen muertos de Israel, también de Babilonia caerán muertos de toda la tierra.",
      "50": "Los que escapasteis del cuchillo, andad, no os detengais; acordaos por muchos días de Jehová, y acordaos de Jerusalem.",
      "51": "Estamos avergonzados, porque oímos la afrenta: confusión cubrió nuestros rostros, porque vinieron extranjeros contra los santuarios de la casa de Jehová.",
      "52": "Por tanto, he aquí vienen días, dice Jehová, que yo visitaré sus esculturas, y en toda su tierra gemirán los heridos.",
      "53": "Si subiese Babilonia al cielo, y si fortaleciere en lo alto su fuerza, de mí vendrán á ella destruidores, dice Jehová.",
      "54": "Sonido de grito de Babilonia, y quebrantamiento grande de la tierra de los Caldeos!",
      "55": "Porque Jehová destruye á Babilonia, y quitará de ella el mucho estruendo; y bramarán sus ondas, como muchas aguas será el sonido de la voz de ellos:",
      "56": "Porque vino destruidor contra ella, contra Babilonia, y sus valientes fueron presos, el arco de ellos fué quebrado: porque Jehová, Dios de retribuciones, dará la paga.",
      "57": "Y embriagaré sus príncipes y sus sabios, sus capitanes y sus nobles y sus fuertes; y dormirán sueño eterno y no despertarán, dice el Rey, cuyo nombre es Jehová de los ejércitos.",
      "58": "Así ha dicho Jehová de los ejércitos: El muro ancho de Babilonia será derribado enteramente, y sus altas puertas serán quemadas á fuego; y en vano trabajarán pueblos y gentes en el fuego, y se cansarán.",
      "59": "Palabra que envió Jeremías profeta á Seraías hijo de Nerías, hijo de Maasías, cuando iba con Sedechîas rey de Judá á Babilonia, el cuarto año de su reinado. Y era Seraías el principal camarero.",
      "60": "Escribió pues Jeremías en un libro todo el mal que había de venir sobre Babilonia, todas las palabras que están escritas contra Babilonia.",
      "61": "Y dijo Jeremías á Seraías: Cuando llegares á Babilonia, y vieres y leyeres todas estas cosas,",
      "62": "Dirás: Oh Jehová, tú has dicho contra este lugar que lo habías de talar, hasta no quedar en él morador, ni hombre ni animal, sino que para siempre ha de ser asolado.",
      "63": "Y será que cuando acabares de leer este libro, le atarás una piedra, y lo echarás en medio del Eufrates:",
      "64": "Y dirás: Así será anegada Babilonia, y no se levantará del mal que yo traigo sobre ella; y serán rendidos. Hasta aquí son las palabras de Jeremías."
    },
    "52": {
      "1": "ERA Sedechîas de edad de veintiún años cuando comenzó á reinar, y reinó once años en Jerusalem. Su madre se llamaba Hamutal, hija de Jeremías, de Libna.",
      "2": "E hizo lo malo en los ojos de Jehová, conforme á todo lo que hizo Joacim.",
      "3": "Y á causa de la ira de Jehová contra Jerusalem y Judá, fué el llegar á echarlos de su presencia: y rebelóse Sedechîas contra el rey de Babilonia.",
      "4": "Aconteció por tanto á los nueve años de su reinado, en el mes décimo, á los diez días del mes, que vino Nabucodonosor rey de Babilonia, él y todo su ejército, contra Jerusalem, y contra ella asentaron campo, y de todas partes edificaron contra ella baluartes.",
      "5": "Y estuvo cercada la ciudad hasta el undécimo año del rey Sedechîas.",
      "6": "En el mes cuarto, á los nueve del mes, prevaleció el hambre en la ciudad, hasta no haber pan para el pueblo de la tierra.",
      "7": "Y fué entrada la ciudad, y todos los hombres de guerra huyeron, y saliéronse de la ciudad de noche por el camino de postigo de entre los dos muros, que había cerca del jardín del rey, y fuéronse por el camino del desierto, estando aún los Caldeos junto á la ciudad alrededor.",
      "8": "Y el ejército de los Caldeos siguió al rey, y alcanzaron á Sedechîas en los llanos de Jericó; y esparcióse de él todo su ejército.",
      "9": "Entonces prendieron al rey, e hiciéronle venir al rey de Babilonia, á Ribla en tierra de Hamath, donde pronunció contra él sentencia.",
      "10": "Y degolló el rey de Babilonia á los hijos de Sedechîas delante de sus ojos, y también degolló á todos los príncipes de Judá en Ribla.",
      "11": "A Sedechîas empero sacó los ojos, y le aprisionó con grillos, é hízolo el rey de Babilonia llevar á Babilonia; y púsolo en la casa de la cárcel hasta el día en que murió.",
      "12": "Y en el mes quinto, á los diez del mes, que era el año diecinueve del reinado de Nabucodonosor, rey de Babilonia, vino á Jerusalem Nabuzaradán, capitán de la guardia, que solía estar delante del rey de Babilonia.",
      "13": "Y quemó la casa de Jehová, y la casa del rey, y todas las casas de Jerusalem; y abrasó con fuego todo grande edificio.",
      "14": "Y todo el ejército de los Caldeos, que venía con el capitán de la guardia, destruyó todos los muros de Jerusalem en derredor.",
      "15": "E hizo trasportar Nabuzaradán, capitán de la guardia, los pobres del pueblo, y toda la otra gente vulgar que en la ciudad habían quedado, y los fugitivos que se habían huído al rey de Babilonia, y todo el resto de la multitud vulgar.",
      "16": "Mas de los pobres del país dejó Nabuzaradán, capitán de la guardia, para viñadores y labradores.",
      "17": "Y los Caldeos quebraron las columnas de bronce que estaban en la casa de Jehová, y las basas, y el mar de bronce que estaba en la casa de Jehová, y llevaron todo el metal á Babilonia.",
      "18": "Lleváronse también los calderos, y los badiles, y los salterios, y las bacías, y los cazos, y todos los vasos de metal con que se servían.",
      "19": "Y las copas, é incensarios, y tazones, y ollas, y candeleros, y escudillas, y tazas: lo que de oro de oro, y lo que de plata de plata, se llevó el capitán de la guardia.",
      "20": "Las dos columnas, un mar, y doce bueyes de bronce que estaban debajo de las basas, que había hecho el rey Salomón en la casa de Jehová: no se podía pesar el metal de todos estos vasos.",
      "21": "Cuanto á las columnas, la altura de la columna era de dieciocho codos, y un hilo de doce codos la rodeaba: y su grueso era de cuatro dedos, y hueca.",
      "22": "Y el capitel de bronce que había sobre ella, era de altura de cinco codos, con una red y granadas en el capitel alrededor, todo de bronce; y lo mismo era lo de la segunda columna con sus granadas.",
      "23": "Había noventa y seis granadas en cada orden: todas ellas eran ciento sobre la red alrededor.",
      "24": "Tomó también el capitán de la guardia á Seraías principal sacerdote, y á Sophonías segundo sacerdote, y tres guardas del atrio.",
      "25": "Y de la ciudad tomó un eunuco que era capitán sobre los hombres de guerra, y siete hombres de los continuos del rey, que se hallaron en al ciudad; y al principal secretario de la milicia, que revistaba el pueblo de la tierra para la guerra; y sesenta hombres del vulgo del país, que se hallaron dentro de la ciudad.",
      "26": "Tomólos pues Nabuzaradán, capitán de la guardia, y llevólos al rey de Babilonia á Ribla.",
      "27": "Y el rey de Babilonia los hirió, y los mató en Ribla en tierra de Hamath. Así fué Judá trasportado de su tierra.",
      "28": "Este es el pueblo que Nabucodonosor hizo trasportar: En el año séptimo, tres mil veintitrés Judíos:",
      "29": "En el año dieciocho hizo Nabudonosor, trasportar de Jerusalem ochocientas treinta y dos personas:",
      "30": "El año veintitrés de Nabucodonosor, trasportó Nabuzaradán capitán de la guardia, setecientas cuarenta y cinco personas de los Judíos: todas las personas fueron cuatro mil seiscientas.",
      "31": "Y acaeció que en el año treinta y siete de la cautividad de Joachîn rey de Judá, en el mes duodécimo, á los veinticinco del mes, Evil-merodach, rey de Babilonia, en el año primero de su reinado, alzó la cabeza de Joachîn rey de Judá y sacólo de la casa de la cárcel;",
      "32": "Y habló con él amigablemente, é hizo poner su silla sobre las sillas de los reyes que estaban con él en Babilonia.",
      "33": "Hízole mudar también los vestidos de su prisión, y comía pan delante de él siempre todos los días de su vida.",
      "34": "Y continuamente se le daba ración por el rey de Babilonia, cada cosa en su día por todos los de su vida, hasta el día de su muerte."
    }
  },
  "lamentations": {
    "1": {
      "1": "COMO está sentada sola la ciudad populosa! La grande entre las naciones se ha vuelto como viuda, La señora de provincias es hecha tributaria.",
      "2": "Amargamente llora en la noche, y sus lágrimas en sus mejillas; No tiene quien la consuele de todos sus amadores: Todos sus amigos le faltaron, volviéronsele enemigos.",
      "3": "Fuése Judá, a causa de la aflicción y de la grandeza de servidumbre; Ella moró entre las gentes, y no halló descanso: Todos sus perseguidores la alcanzaron entre estrechuras.",
      "4": "Las calzadas de Sión tienen luto, porque no hay quien venga á las solemnidades; Todas sus puertas están asoladas, sus sacerdotes gimen, Sus vírgenes afligidas, y ella tiene amargura.",
      "5": "Sus enemigos han sido hechos cabeza, sus aborrecedores fueron prosperados; Porque Jehová la afligió por la multitud de sus rebeliones: Sus niños fueron en cautividad delante del enemigo.",
      "6": "Fuése de la hija de Sión toda su hermosura: Sus príncipes fueron como ciervos que no hallan pasto, Y anduvieron sin fortaleza delante del perseguidor.",
      "7": "Jerusalem, cuando cayó su pueblo en mano del enemigo y no hubo quien le ayudase, Se acordó de los días de su aflicción, y de sus rebeliones, Y de todas sus cosas deseables que tuvo desde los tiempos antiguos: Miráronla los enemigos, y escarnecieron de sus sábados.",
      "8": "Pecado cometió Jerusalem; por lo cual ella ha sido removida: Todos los que la honraban la han menospreciado, porque vieron su vergüenza; Y ella suspira, y se vuelve atrás.",
      "9": "Sus inmundicias en sus faldas; no se acordó de su postrimería: Por tanto ella ha descendido maravillosamente, no tiene consolador. Mira, oh Jehová, mi aflicción, porque el enemigo se ha engrandecido.",
      "10": "Extendió su mano el enemigo á todas sus cosas preciosas; Y ella ha visto entrar en su santuario las gentes, De las cuales mandaste que no entrasen en tu congregación.",
      "11": "Todo su pueblo buscó su pan suspirando; Dieron por la comida todas sus cosas preciosas, para entretener la vida. Mira, oh Jehová, y ve que estoy abatida.",
      "12": "¿No os conmueve á cuantos pasáis por el camino? Mirad, y ved si hay dolor como mi dolor que me ha venido; Porque Jehová me ha angustiado en el día de la ira de su furor.",
      "13": "Desde lo alto envió fuego en mis huesos, el cual se enseñoreó: Ha extendido red a mis pies, tornóme atrás, Púsome asolada, y que siempre tenga dolor.",
      "14": "El yugo de mis rebeliones está ligado por su mano, Enlazadas han subido sobre mi cerviz: ha hecho caer mis fuerzas: Hame entregado el Señor en sus manos, contra quienes no podré levantarme.",
      "15": "El Señor ha hollado todos mis fuertes en medio de mí; Llamó contra mí compañía para quebrantar mis mancebos: Como lagar ha pisado el Señor á la virgen hija de Judá.",
      "16": "Por esta causa yo lloro; mis ojos, mis ojos fluyen aguas; Porque se alejó de mí consolador que dé reposo á mi alma: Mis hijos son destruídos, porque el enemigo prevaleció.",
      "17": "Sión extendió sus manos, no tiene quien la consuele; Jehová dió mandamiento contra Jacob, que sus enemigos lo cercasen: Jerusalem fué en abominación entre ellos.",
      "18": "Jehová es justo; que yo contra su boca me rebelé. Oid ahora, pueblos todos, y ved mi dolor: Mis vírgenes y mis mancebos fueron en cautiverio.",
      "19": "Dí voces á mis amadores, mas ellos me han engañado; Mis sacerdotes y mis ancianos en la ciudad perecieron, Buscando comida para sí con que entretener su vida.",
      "20": "Mira, oh Jehová, que estoy atribulada: mis entrañas rugen, Mi corazón está trastornado en medio de mí; porque me rebelé desaforadamente: De fuera deshijó el cuchillo, de dentro parece una muerte.",
      "21": "Oyeron que gemía, y no hay consolador para mí: Todos mis enemigos han oído mi mal, se han holgado de que tú lo hiciste. Harás venir el día que has anunciado, y serán como yo.",
      "22": "Entre delante de ti toda su maldad, Y haz con ellos como hiciste conmigo por todas mis rebeliones: Porque muchos son mis suspiros, y mi corazón está doloroso."
    },
    "2": {
      "1": "COMO oscureció el Señor en su furor a la hija de Sión! Derribó del cielo á la tierra la hermosura de Israel, Y no se acordó del estrado de sus pies en el día de su ira.",
      "2": "Destruyó el Señor, y no perdonó; Destruyó en su furor todas las tiendas de Jacob: Echó por tierra las fortalezas de la hija de Judá, Deslustró el reino y sus príncipes.",
      "3": "Cortó con el furor de su ira todo el cuerno de Israel; Hizo volver atrás su diestra delante del enemigo; Y encendióse en Jacob como llama de fuego que ha devorado en contorno.",
      "4": "Entesó su arco como enemigo, afirmó su mano derecha como adversario, Y mató toda cosa hermosa á la vista: En la tienda de la hija de Sión derramó como fuego su enojo.",
      "5": "Fué el Señor como enemigo, destruyó a Israel; Destruyó todos sus palacios, disipó sus fortalezas: Y multiplicó en la hija de Judá la tristeza y lamento.",
      "6": "Y quitó su tienda como de un huerto, Destruyó el lugar de su congregación: Jehová ha hecho olvidar en Sión solemnidades y sábados, Y ha desechado en el furor de su ira rey y sacerdote.",
      "7": "Desechó el Señor su altar, menospreció su santuario, Ha entregado en mano del enemigo los muros de sus palacios: Dieron grita en la casa de Jehová como en día de fiesta.",
      "8": "Jehová determinó destruir el muro de la hija de Sión; Extendió el cordel, no retrajo su mano de destruir: Hizo pues, se lamentara el antemuro y el muro; fueron destruídos juntamente.",
      "9": "Sus puertas fueron echadas por tierra, destruyó y quebrantó sus cerrojos: Su rey y sus príncipes están entre las gentes donde no hay ley; Sus profetas tampoco hallaron visión de Jehová.",
      "10": "Sentáronse en tierra, callaron los ancianos de la hija de Sión; Echaron polvo sobre sus cabezas, ciñéronse de saco; Las vírgenes de Jerusalem bajaron sus cabezas a tierra.",
      "11": "Mis ojos desfallecieron de lágrimas, rugieron mis entrañas, Mi hígado se derramó por tierra por el quebrantamiento de la hija de mi pueblo, Cuando desfallecía el niño y el que mamaba, en las plazas de la ciudad.",
      "12": "Decían a sus madres: ¿Dónde está el trigo y el vino? Desfallecían como heridos en las calles de la ciudad, Derramando sus almas en el regazo de sus madres.",
      "13": "¿Qué testigo te traeré, ó á quién te haré semejante, hija de Jerusalem? ¿A quién te compararé para consolarte, oh virgen hija de Sión? Porque grande es tu quebrantamiento como la mar: ¿quién te medicinará?",
      "14": "Tus profetas vieron para ti vanidad y locura; Y no descubrieron tu pecado para estorbar tu cautiverio, Sino que te predicaron vanas profecías y extravíos.",
      "15": "Todos los que pasaban por el camino, batieron las manos sobre ti; Silbaron, y movieron sus cabezas sobre la hija de Jerusalem, diciendo: ¿Es ésta la ciudad que decían de perfecta hermosura, el gozo de toda la tierra?",
      "16": "Todos tus enemigos abrieron sobre ti su boca, Silbaron, y rechinaron los dientes; dijeron: Devoremos: Cierto éste es el día que esperábamos; lo hemos hallado, vímoslo.",
      "17": "Jehová ha hecho lo que tenía determinado, Ha cumplido su palabra que él había mandado desde tiempo antiguo: Destruyó, y no perdonó; Y alegró sobre ti al enemigo, Y enalteció el cuerno de tus adversarios.",
      "18": "El corazón de ellos clamaba al Señor: Oh muro de la hija de Sión, echa lágrimas como un arroyo día y noche; No descanses, ni cesen las niñas de tus ojos.",
      "19": "Levántate, da voces en la noche, en el principio de las velas; Derrama como agua tu corazón ante la presencia del Señor; Alza tus manos á él por la vida de tus pequeñitos, Que desfallecen de hambre en las entradas de todas las calles.",
      "20": "Mira, oh Jehová, y considera á quién has hecho así. ¿Han de comer las mujeres su fruto, los pequeñitos de sus crías? ¿Han de ser muertos en el santuario del Señor el sacerdote y el profeta?",
      "21": "Niños y viejos yacían por tierra en las calles; Mis vírgenes y mis mancebos cayeron a cuchillo: Mataste en el día de tu furor, degollaste, no perdonaste.",
      "22": "Has llamado, como a día de solemnidad, mis temores de todas partes; Y en el día del furor de Jehová no hubo quien escapase ni quedase vivo: Los que crié y mantuve, mi enemigo los acabó"
    },
    "3": {
      "1": "YO soy el hombre que ha visto aflicción en la vara de su enojo.",
      "2": "Guióme y llevóme en tinieblas, mas no en luz.",
      "3": "Ciertamente contra mí volvió y revolvió su mano todo el día.",
      "4": "Hizo envejecer mi carne y mi piel; quebrantó mis huesos.",
      "5": "Edificó contra mí, y cercóme de tósigo y de trabajo.",
      "6": "Asentóme en oscuridades, como los ya muertos de mucho tiempo.",
      "7": "Cercóme por todos lados, y no puedo salir; agravó mis grillos.",
      "8": "Aun cuando clamé y dí voces, cerro los oídos a mi oración.",
      "9": "Cercó mis caminos con piedra tajada, torció mis senderos.",
      "10": "Como oso que acecha fué para mí, como león en escondrijos.",
      "11": "Torció mis caminos, y depedazóme; tornóme asolado.",
      "12": "Su arco entesó, y púsome como blanco a la saeta.",
      "13": "Hizo entrar en mis riñones las saetas de su aljaba.",
      "14": "Fuí escarnio á todo mi pueblo, canción de ellos todos los días.",
      "15": "Hartóme de amarguras, embriagóme de ajenjos.",
      "16": "Quebróme los dientes con cascajo, cubrióme de ceniza.",
      "17": "Y mi alma se alejó de la paz, olvidéme del bien.",
      "18": "Y dije: Pereció mi fortaleza, y mi esperanza de Jehová.",
      "19": "Acuérdate de mi aflicción y de mi abatimiento, del ajenjo y de la hiel.",
      "20": "Tendrálo aún en memoria mi alma, porque en mí está humillada.",
      "21": "Esto reduciré á mi corazón, por lo cual esperaré.",
      "22": "Es por la misericordia de Jehová que no somos consumidos, porque nunca decayeron sus misericordias.",
      "23": "Nuevas son cada mañana; grande es tu fidelidad.",
      "24": "Mi parte es Jehová, dijo mi alma; por tanto en él esperaré.",
      "25": "Bueno es Jehová á los que en él esperan, al alma que le buscare.",
      "26": "Bueno es esperar callando en la salud de Jehová.",
      "27": "Bueno es al hombre, si llevare el yugo desde su mocedad.",
      "28": "Sentaráse solo, y callará, porque lo llevó sobre sí.",
      "29": "Pondrá su boca en el polvo, por si quizá hay esperanza.",
      "30": "Dará la mejilla al que le hiriere; hartaráse de afrenta.",
      "31": "Porque el Señor no desechará para siempre:",
      "32": "Antes si afligiere, también se compadecerá según la multitud de sus misericordias.",
      "33": "Porque no aflige ni congoja de su corazón á los hijos de los hombres.",
      "34": "Desmenuzar bajo de sus pies todos los encarcelados de la tierra,",
      "35": "Hacer apartar el derecho del hombre ante la presencia del Altísimo,",
      "36": "Trastornar al hombre en su causa, el Señor no lo sabe.",
      "37": "¿Quién será aquel que diga, que vino algo que el Señor no mandó?",
      "38": "¿De la boca del Altísimo no saldrá malo y bueno?",
      "39": "¿Por qué murmura el hombre viviente, el hombre en su pecado?",
      "40": "Escudriñemos nuestros caminos, y busquemos, y volvámonos a Jehová.",
      "41": "Levantemos nuestros corazones con las manos a Dios en los cielos.",
      "42": "Nosotros nos hemos rebelado, y fuimos desleales; tú no perdonaste.",
      "43": "Desplegaste la ira, y nos perseguiste; mataste, no perdonaste.",
      "44": "Te cubriste de nube, porque no pasase la oración nuestra.",
      "45": "Raedura y abominación nos tornaste en medio de los pueblos.",
      "46": "Todos nuestros enemigos abrieron sobre nosotros su boca.",
      "47": "Temor y lazo fué para nosotros, asolamiento y quebrantamiento.",
      "48": "Ríos de aguas echan mis ojos, por el quebrantamiento de la hija de mi pueblo.",
      "49": "Mis ojos destilan, y no cesan, porque no hay alivio,",
      "50": "Hasta que Jehová mire y vea desde los cielos.",
      "51": "Mis ojos contristaron mi alma, por todas las hijas de mi ciudad.",
      "52": "Mis enemigos me dieron caza como á ave, sin por qué.",
      "53": "Ataron mi vida en mazmorra, pusieron piedra sobre mí.",
      "54": "Aguas de avenida vinieron sobre mi cabeza; yo dije: Muerto soy.",
      "55": "Invoqué tu nombre, oh Jehová, desde la cárcel profunda.",
      "56": "Oiste mi voz; no escondas tu oído á mi clamor, para mi respiro",
      "57": "Acercástete el día que te invoqué: dijiste: No temas.",
      "58": "Abogaste, Señor, la causa de mi alma; redimiste mi vida.",
      "59": "Tú has visto, oh Jehová, mi agravio; defiende mi causa.",
      "60": "Tú has visto toda su venganza; todos sus pensamientos contra mí.",
      "61": "Tú has oído el oprobio de ellos, oh Jehová, todas sus maquinaciones contra mí;",
      "62": "Los dichos de los que contra mí se levantaron, y su designio contra mí todo el día.",
      "63": "Su sentarse, y su levantarse mira: yo soy su canción.",
      "64": "Dales el pago, oh Jehová, según la obra de sus manos.",
      "65": "Dales ansia de corazón, tu maldición á ellos.",
      "66": "Persíguelos en tu furor, y quebrántalos de debajo de los cielos, oh Jehová."
    },
    "4": {
      "1": "COMO se ha oscurecido el oro! ­Cómo el buen oro se ha demudado! Las piedras del santuario están esparcidas por las encrucijadas de todas las calles.",
      "2": "Los hijos de Sión, preciados y estimados más que el oro puro, ­Cómo son tenidos por vasos de barro, obra de manos de alfarero!",
      "3": "Aun los monstruos marinos sacan la teta, dan de mamar a sus chiquitos: La hija de mi pueblo es cruel, como los avestruces en el desierto.",
      "4": "La lengua del niño de teta, de sed se pegó á su paladar: Los chiquitos pidieron pan, y no hubo quien se lo partiese.",
      "5": "Los que comían delicadamente, asolados fueron en las calles; Los que se criaron en carmesí, abrazaron los estercoleros.",
      "6": "Y aumentóse la iniquidad de la hija de mi pueblo más que el pecado de Sodoma, Que fué trastornada en un momento, y no asentaron sobre ella compañías.",
      "7": "Sus Nazareos fueron blancos más que la nieve, más lustrosos que la leche. Su compostura más rubicunda que los rubíes, más bellos que el zafiro:",
      "8": "Oscura más que la negrura es la forma de ellos; no los conocen por las calles: Su piel está pegada á sus huesos, seca como un palo.",
      "9": "Más dichosos fueron los muertos á cuchillo que los muertos del hambre; Porque éstos murieron poco á poco por falta de los frutos de la tierra.",
      "10": "Las manos de las mujeres piadosas cocieron á sus hijos; Fuéronles comida en el quebrantamiento de la hija de mi pueblo.",
      "11": "Cumplió Jehová su enojo, derramó el ardor de su ira; Y encendió fuego en Sión, que consumió sus fundamentos.",
      "12": "Nunca los reyes de la tierra, ni todos los que habitan en el mundo, Creyeron que el enemigo y el adversario entrara por las puertas de Jerusalem.",
      "13": "Es por los pecados de sus profetas, por las maldades de sus sacerdotes, Que derramaron en medio de ella la sangre de los justos.",
      "14": "Titubearon como ciegos en las calles, fueron contaminados en sangre, De modo que no pudiesen tocar á sus vestiduras.",
      "15": "Apartaos ­inmundos!, les gritaban, Apartaos, apartaos, no toquéis. Cuando huyeron y fueron dispersos, dijeron entre las gentes: Nunca más morarán aquí",
      "16": "La ira de Jehová los apartó, no los mirará más: No respetaron la faz de los sacerdotes, ni tuvieron compasión de los viejos.",
      "17": "Aun nos han desfallecido nuestros ojos tras nuestro vano socorro: En nuestra esperanza aguardamos gente que no puede salvar.",
      "18": "Cazaron nuestro pasos, que no anduviésemos por nuestras calles: Acercóse nuestro fin, cumpliéronse nuestros días; porque nuestro fin vino.",
      "19": "Ligeros fueron nuestros perseguidores más que las águilas del cielo: Sobre los montes nos persiguieron, en el desierto nos pusieron emboscada.",
      "20": "El resuello de nuestras narices, el ungido de Jehová, De quien habíamos dicho: A su sombra tendremos vida entre las gentes: fué preso en sus hoyos.",
      "21": "Gózate y alégrate, hija de Edom, la que habitas en tierra de Hus: Aun hasta ti pasará el cáliz; embriagarte has, y vomitarás.",
      "22": "Cumplido es tu castigo, oh hija de Sión: Nunca más te hará trasportar. Visitará tu iniquidad, oh hija de Edom; Descubrirá tus pecados."
    },
    "5": {
      "1": "ACUÉRDATE, oh Jehová, de lo que nos ha sucedido: Ve y mira nuestro oprobio.",
      "2": "Nuestra heredad se ha vuelto á extraños, Nuestras casas á forasteros.",
      "3": "Huérfanos somos sin padre, Nuestras madres como viudas.",
      "4": "Nuestra agua bebemos por dinero; Nuestra leña por precio compramos.",
      "5": "Persecución padecemos sobre nuestra cerviz: Nos cansamos, y no hay para nosotros reposo.",
      "6": "Al Egipcio y al Asirio dimos la mano, para saciarnos de pan.",
      "7": "Nuestros padres pecaron, y son muertos; Y nosotros llevamos sus castigos.",
      "8": "Siervos se enseñorearon de nosotros; No hubo quien de su mano nos librase.",
      "9": "Con peligro de nuestras vidas traíamos nuestro pan Delante del cuchillo del desierto.",
      "10": "Nuestra piel se ennegreció como un horno A causa del ardor del hambre.",
      "11": "Violaron á las mujeres en Sión, A las vírgenes en las ciudades de Judá.",
      "12": "A los príncipes colgaron por su mano; No respetaron el rostro de los viejos.",
      "13": "Llevaron los mozos á moler, Y los muchachos desfallecieron en la leña.",
      "14": "Los ancianos cesaron de la puerta, Los mancebos de sus canciones.",
      "15": "Cesó el gozo de nuestro corazón; Nuestro corro se tornó en luto.",
      "16": "Cayó la corona de nuestra cabeza: ­Ay ahora de nosotros! porque pecamos.",
      "17": "Por esto fué entristecido nuestro corazón, Por esto se entenebrecieron nuestro ojos:",
      "18": "Por el monte de Sión que está asolado; Zorras andan en él.",
      "19": "Mas tú, Jehová, permanecerás para siempre: Tu trono de generación en generación.",
      "20": "¿Por qué te olvidarás para siempre de nosotros, Y nos dejarás por largos días?",
      "21": "Vuélvenos, oh Jehová, á ti, y nos volveremos: Renueva nuestros días como al principio.",
      "22": "Porque repeliendo nos has desechado; Te has airado contra nosotros en gran manera."
    }
  },
  "ezekiel": {
    "1": {
      "1": "Y FUÉ que á los treinta años, en el mes cuarto, á cinco del mes, estando yo en medio de los trasportados junto al río de Chebar, los cielos se abrieron, y vi visiones de Dios.",
      "2": "A los cinco del mes, que fué en el quinto año de la transmigración del rey Joachîn,",
      "3": "Fué palabra de Jehová á Ezequiel sacerdote, hijo de Buzi, en la tierra de los Caldeos, junto al río de Chebar; fué allí sobre él la mano de Jehová.",
      "4": "Y miré, y he aquí un viento tempestuoso venía del aquilón, una gran nube, con un fuego envolvente, y en derredor suyo un resplandor, y en medio del fuego una cosa que parecía como de ámbar,",
      "5": "Y en medio de ella, figura de cuatro animales. Y este era su parecer; había en ellos semejanza de hombre.",
      "6": "Y cada uno tenía cuatro rostros, y cuatro alas.",
      "7": "Y los pies de ellos eran derechos, y la planta de sus pies como la planta de pie de becerro; y centelleaban á manera de bronce muy bruñido.",
      "8": "Y debajo de sus alas, á sus cuatro lados, tenían manos de hombre; y sus rostros y sus alas por los cuatro lados.",
      "9": "Con las alas se juntaban el uno al otro. No se volvían cuando andaban; cada uno caminaba en derecho de su rostro.",
      "10": "Y la figura de sus rostros era rostro de hombre; y rostro de león á la parte derecha en los cuatro; y á la izquierda rostro de buey en los cuatro; asimismo había en los cuatro rostro de águila.",
      "11": "Tales eran sus rostros; y tenían sus alas extendidas por encima, cada uno dos, las cuales se juntaban; y las otras dos cubrían sus cuerpos.",
      "12": "Y cada uno caminaba en derecho de su rostro: hacia donde el espíritu era que anduviesen, andaban; cuando andaban, no se volvían.",
      "13": "Cuanto á la semejanza de los animales, su parecer era como de carbones de fuego encendidos, como parecer de hachones encendidos: discurría entre los animales; y el fuego resplandecía, y del fuego salían relámpagos.",
      "14": "Y los animales corrían y tornaban á semejanza de relámpagos.",
      "15": "Y estando yo mirando los animales, he aquí una rueda en la tierra junto á los animales, á sus cuatro caras.",
      "16": "Y el parecer de las ruedas y su obra semejábase al color del topacio. Y las cuatro tenían una misma semejanza: su apariencia y su obra como rueda en medio de rueda.",
      "17": "Cuando andaban, se movían sobre sus cuatro costados: no se volvían cuando andaban.",
      "18": "Y sus cercos eran altos y espantosos, y llenos de ojos alrededor en las cuatro.",
      "19": "Y cuando los animales andaban, las ruedas andaban junto á ellos: y cuando los animales se levantaban de la tierra, las ruedas se levantaban.",
      "20": "Hacia donde el espíritu era que anduviesen, andaban; hacia donde era el espíritu que anduviesen, las ruedas también se levantaban tras ellos; porque el espíritu de los animales estaba en las ruedas.",
      "21": "Cuando ellos andaban, andaban ellas; y cuando ellos se paraban, se paraban ellas; asimismo cuando se levantaban de la tierra, las ruedas se levantaban tras ellos; porque el espíritu de los animales estaba en las ruedas.",
      "22": "Y sobre las cabezas de cada animal aparecía expansión á manera de cristal maravilloso, extendido encima sobre sus cabezas.",
      "23": "Y debajo de la expansión estaban las alas de ellos derechas la una á la otra; á cada uno dos, y otras dos con que se cubrían sus cuerpos.",
      "24": "Y oí el sonido de sus alas cuando andaban, como sonido de muchas aguas, como la voz del Omnipotente, como ruido de muchedumbre, como la voz de un ejército. Cuando se paraban, aflojaban sus alas.",
      "25": "Y cuando se paraban y aflojaban sus alas, oíase voz de arriba de la expansión que había sobre sus cabezas.",
      "26": "Y sobre la expansión que había sobre sus cabezas, veíase la figura de un trono y que parecía de piedra de zafiro; y sobre la figura del trono había una semejanza que parecía de hombre sentado sobre él.",
      "27": "Y vi apariencia como de ámbar, como apariencia de fuego dentro de ella en contorno, por el aspecto de sus lomos para arriba; y desde sus lomos para abajo, vi que parecía como fuego, y que tenía resplandor alrededor.",
      "28": "Cual parece el arco del cielo que está en las nubes el día que llueve, así era el parecer del resplandor alrededor. Esta fué la visión de la semejanza de la gloria de Jehová. Y luego que yo la hube visto, caí sobre mi rostro, y oí voz de uno que hablaba."
    },
    "2": {
      "1": "Y DIJOME: Hijo del hombre, está sobre tus pies, y hablaré contigo.",
      "2": "Y entró espíritu en mí luego que me habló, y afirmóme sobre mis pies, y oía al que me hablaba.",
      "3": "Y díjome: Hijo del hombre, yo te envío á los hijos de Israel, á gentes rebeldes que se rebelaron contra mí: ellos y sus padres se han rebelado contra mí hasta este mismo día.",
      "4": "Yo pues te envío á hijos de duro rostro y de empedernido corazón; y les dirás: Así ha dicho el Señor Jehová.",
      "5": "Acaso ellos escuchen; y si no escucharen, (porque son una rebelde familia,) siempre conocerán que hubo profeta entre ellos.",
      "6": "Y tú, hijo del hombre, no temas de ellos, ni tengas miedo de sus palabras, aunque te hallas entre zarzas y espinas, y tú moras con escorpiones: no tengas miedo de sus palabras, ni temas delante de ellos, porque son casa rebelde.",
      "7": "Les hablarás pues mis palabras, escuchen ó dejen de escuchar; porque son muy rebeldes.",
      "8": "Mas tú, hijo del hombre, oye lo que yo te hablo; no seas tú rebelde como la casa rebelde: abre tu boca, y come lo que yo te doy.",
      "9": "Y miré, y he aquí una mano me fué enviada, y en ella había un rollo de libro.",
      "10": "Y extendiólo delante de mí, y estaba escrito delante y detrás: y había escritas en él endechas, y lamentación, y ayes."
    },
    "3": {
      "1": "Y DIJOME: Hijo del hombre, come lo que hallares; come este rollo, y ve y habla á la casa de Israel.",
      "2": "Y abrí mi boca, é hízome comer aquel rollo.",
      "3": "Y díjome: Hijo del hombre, haz á tu vientre que coma, é hinche tus entrañas de este rollo que yo te doy. Y comílo, y fué en mi boca dulce como miel.",
      "4": "Díjome luego: Hijo del hombre, ve y entra á la casa de Israel, y habla á ellos con mis palabras.",
      "5": "Porque no eres enviado á pueblo de habla profunda ni de lengua difícil, sino á la casa de Israel.",
      "6": "No á muchos pueblos de profunda habla ni de lengua difícil, cuyas palabras no entiendas; y si á ellos te enviara, ellos te oyeran.",
      "7": "Mas la casa de Israel no te querrán oir, porque no me quieren oír á mí: porque toda la casa de Israel son tiesos de frente, y duros de corazón.",
      "8": "He aquí he hecho yo tu rostro fuerte contra los rostros de ellos, y tu frente fuerte contra su frente.",
      "9": "Como diamante, más fuerte que pedernal he hecho tu frente; no los temas, ni tengas miedo delante de ellos, porque es casa rebelde.",
      "10": "Y díjome: Hijo del hombre, toma en tu corazón todas mis palabras que yo te hablaré, y oye con tus oídos.",
      "11": "Y ve, y entra á los trasportados, á los hijos de tu pueblo, y les hablarás y les dirás: Así ha dicho el Señor Jehová; escuchen, ó dejen de escuchar.",
      "12": "Y levantóme el espíritu, y oí detrás de mí una voz de grande estruendo, que decía: Bendita sea la gloria de Jehová desde su lugar.",
      "13": "Oí también el sonido de las alas de los animales que se juntaban la una con la otra, y el sonido de las ruedas delante de ellos, y sonido de grande estruendo.",
      "14": "Levantóme pues el espíritu, y me tomó; y fuí en amargura, en la indignación de mi espíritu: mas la mano de Jehová era fuerte sobre mí.",
      "15": "Y vine á los trasportados en Telabib, que moraban junto al río de Chebar, y asenté donde ellos estaban asentados, y allí permanecí siete días atónito entre ellos.",
      "16": "Y aconteció que al cabo de los siete días fué á mí palabra de Jehová, diciendo:",
      "17": "Hijo del hombre, yo te he puesto por atalaya á la casa de Israel: oirás pues tú la palabra de mi boca, y amonestarlos has de mi parte.",
      "18": "Cuando yo dijere al impío: De cierto morirás: y tú no le amonestares, ni le hablares, para que el impío sea apercibido de su mal camino, á fin de que viva, el impío morirá por su maldad, mas su sangre demandaré de tu mano.",
      "19": "Y si tú amonestares al impío, y él no se convirtiere de su impiedad, y de su mal camino, él morirá por su maldad, y tú habrás librado tu alma.",
      "20": "Y cuando el justo se apartare de su justicia, é hiciere maldad, y pusiere yo tropiezo delante de él, él morirá, porque tú no le amonestaste; en su pecado morirá, y sus justicias que había hecho no vendrán en memoria; mas su sangre demandaré de tu mano.",
      "21": "Y si al justo amonestares para que el justo no peque, y no pecare, de cierto vivirá, porque fué amonestado; y tú habrás librado tu alma.",
      "22": "Y fué allí la mano de Jehová sobre mí, y díjome: Levántate, y sal al campo, y allí hablaré contigo.",
      "23": "Y levantéme, y salí al campo: y he aquí que allí estaba la gloria de Jehová, como la gloria que había visto junto al río de Chebar: y caí sobre mi rostro.",
      "24": "Entonces entró espíritu en mí, y afirmóme sobre mis pies, y hablóme, y díjome: Entra, y enciérrate dentro de tu casa.",
      "25": "Y tú, oh hijo del hombre, he aquí que pondrán sobre ti cuerdas, y con ellas te ligarán, y no saldrás entre ellos.",
      "26": "Y haré se pegue tu lengua á tu paladar, y estarás mudo, y no serás á ellos varón que reprende: porque son casa rebelde.",
      "27": "Mas cuando yo te hubiere hablado, abriré tu boca, y les dirás: Así ha dicho el Señor Jehová: El que oye, oiga; y el que cesa, cese: porque casa rebelde son."
    },
    "4": {
      "1": "Y TU, hijo del hombre, tómate un adobe, y ponlo delante de tí, y diseña sobre él la ciudad de Jerusalem:",
      "2": "Y pondrás contra ella cerco, y edificarás contra ella fortaleza, y sacarás contra ella baluarte, y asentarás delante de ella campo, y pondrás contra ella arietes alrededor.",
      "3": "Tómate también una plancha de hierro, y ponla en lugar de muro de hierro entre ti y la ciudad: afirmarás luego tu rostro contra ella, y será en lugar de cerco, y la sitiarás. Es señal á la casa de Israel.",
      "4": "Y tú dormirás sobre tu lado izquierdo, y pondrás sobre él la maldad de la casa de Israel: el número de los días que dormirás sobre él, llevarás sobre ti la maldad de ellos.",
      "5": "Yo te he dado los años de su maldad por el número de los días, trescientos y noventa días: y llevarás la maldad de la casa de Israel.",
      "6": "Y cumplidos estos, dormirás sobre tu lado derecho segunda vez, y llevarás la maldad de la casa de Judá cuarenta días: día por año, día por año te lo he dado.",
      "7": "Y al cerco de Jerusalem afirmarás tu rostro, y descubierto tu brazo, profetizarás contra ella.",
      "8": "Y he aquí he puesto sobre ti cuerdas, y no te tornarás del un tu lado al otro lado, hasta que hayas cumplido los días de tu cerco.",
      "9": "Y tú toma para ti trigo, y cebada, y habas, y lentejas, y mijo, y avena, y ponlo en una vasija, y hazte pan de ello el número de los días que durmieres sobre tu lado: trescientos y noventa días comerás de él.",
      "10": "Y la comida que has de comer será por peso de veinte siclos al día: de tiempo á tiempo lo comerás.",
      "11": "Y beberás el agua por medida, la sexta parte de un hin: de tiempo á tiempo beberás.",
      "12": "Y comerás pan de cebada cocido debajo de la ceniza; y lo cocerás á vista de ellos con los estiércoles que salen del hombre.",
      "13": "Y dijo Jehová: Así comerán los hijos de Israel su pan inmundo, entre las gentes á donde los lanzaré yo.",
      "14": "Y dije: ­Ah Señor Jehová! he aquí que mi alma no es inmunda, ni nunca desde mi mocedad hasta este tiempo comí cosa mortecina ni despedazada, ni nunca en mi boca entró carne inmunda.",
      "15": "Y respondióme: He aquí te doy estiércoles de bueyes en lugar de los estiércoles de hombre, y dispondrás tu pan con ellos.",
      "16": "Díjome luego: Hijo del hombre, he aquí quebrantaré el sostén del pan en Jerusalem, y comerán el pan por peso, y con angustia; y beberán el agua por medida, y con espanto.",
      "17": "Porque les faltará el pan y el agua, y se espantarán los unos con los otros, y se consumirán por su maldad."
    },
    "5": {
      "1": "Y TU, hijo del hombre, tómate un cuchillo agudo, una navaja de barbero toma, y hazla pasar sobre tu cabeza y tu barba: tómate después un peso de balanza, y reparte los pelos.",
      "2": "Una tercera parte quemarás con fuego en medio de la ciudad, cuando se cumplieren los días del cerco, y tomarás una tercera parte, y herirás con cuchillo alrededor de ella; y una tercera parte esparcirás al viento, y yo desenvainaré espada en pos de ellos.",
      "3": "Tomarás también de allí unos pocos por cuenta, y los atarás en el canto de tu ropa.",
      "4": "Y tomarás otra vez de ellos, y los echarás en mitad del fuego, y en el fuego los quemarás: de allí saldrá el fuego en toda la casa de Israel.",
      "5": "Así ha dicho el Señor Jehová: Esta es Jerusalem: púsela en medio de las gentes y de las tierras alrededor de ella.",
      "6": "Y ella mudó mis juicios y mis ordenanzas en impiedad más que las gentes, y más que las tierras que están alrededor de ella; porque desecharon mis juicios y mis mandamientos, y no anduvieron en ellos.",
      "7": "Por tanto, así ha dicho Jehová: ¿Por haberos multiplicado más que á las gentes que están alrededor de vosotros, no habéis andado en mis mandamientos, ni habéis guardado mis leyes? Ni aun según las leyes de las gentes que están alrededor de vosotros habéis hecho.",
      "8": "Así pues ha dicho el Señor Jehová: He aquí yo contra ti; si, yo, y haré juicios en medio de ti á los ojos de las naciones.",
      "9": "Y haré en ti lo que nunca hice, ni jamás haré cosa semejante, á causa de todas tus abominaciones.",
      "10": "Por eso los padres comerán á los hijos en medio de ti, y los hijos comerán á sus padres; y haré en ti juicios, y esparciré á todos vientos todo tu residuo.",
      "11": "Por tanto, vivo yo, dice el Señor Jehová, ciertamente por haber violado mi santuario con todas tus abominaciones, te quebrantaré yo también: mi ojo no perdonará, ni tampoco tendré yo misericordia.",
      "12": "Una tercera parte de ti morirá de pestilencia, y de hambre será consumida en medio de ti; y una tercera parte caerá á cuchillo alrededor de ti; y una tercera parte esparciré á todos los vientos, y tras ellos desenvainaré espada.",
      "13": "Y cumpliráse mi furor, y haré que repose en ellos mi enojo, y tomaré satisfacción: y sabrán que yo Jehová he hablado en mi celo, cuando habré cumplido en ellos mi enojo.",
      "14": "Y te tornaré en desierto y en oprobio entre las gentes que están alrededor de ti, á los ojos de todo transeunte.",
      "15": "Y serás oprobio, y escarnio, y escarmiento, y espanto á las gentes que están alrededor de ti, cuando yo hiciere en ti juicios en furor é indignación, y en reprensiones de ira. Yo Jehová he hablado.",
      "16": "Cuando arrojare yo sobre ellos las perniciosas saetas del hambre, que serán para destrucción, las cuales enviaré para destruiros, entonces aumentaré el hambre sobre vosotros, y quebrantaré entre vosotros el arrimo del pan.",
      "17": "Enviaré pues sobre vosotros hambre, y malas bestias que te destruyan; y pestilencia y sangre pasarán por ti; y meteré sobre ti cuchillo. Yo Jehová he hablado."
    },
    "6": {
      "1": "Y FUÉ á mí palabra de Jehová, diciendo:",
      "2": "Hijo del hombre, pon tu rostro hacia los montes de Israel, y profetiza contra ellos.",
      "3": "Y dirás: Montes de Israel, oid palabra del Señor Jehová: Así ha dicho el Señor Jehová á los montes y dicho el Señor Jehová á los montes y á los collados, á los arroyos y á los valles: He aquí que yo, yo haré venir sobre vosotros cuchillo, y destruiré vuestros altos.",
      "4": "Y vuestros altares serán asolados, y vuestras imágenes del sol serán quebradas: y haré que caigan vuestros muertos delante de vuestros ídolos.",
      "5": "Y pondré los cuerpos muertos de los hijos de Israel delante de sus ídolos; y vuestros huesos esparciré en derredor de vuestros altares.",
      "6": "En todas vuestras habitaciones las ciudades serán desiertas, y los altos serán asolados, para que sean asolados y se hagan desiertos vuestros altares; y quebrados serán vuestros ídolos, y cesarán; y vuestras imágenes del sol serán destruídas, y vuestras obras serán desechas.",
      "7": "Y los muertos caerán en medio de vosotros; y sabréis que soy Jehová.",
      "8": "Mas dejaré que haya de vosotros quien escape del cuchillo entre las gentes, cuando fuereis esparcidos por las tierras.",
      "9": "Y los que de vosotros escaparen, se acordarán de mí entre las gentes entre las cuales serán cautivos: porque yo me quebranté á causa de su corazón fornicario, que se apartó de mí, y á causa de sus ojos, que fornicaron tras sus ídolos: y se avergonzarán de sí mismos, á causa de los males que hicieron en todas sus abominaciones.",
      "10": "Y sabrán que yo soy Jehová: no en vano dije que les había de hacer este mal.",
      "11": "Así ha dicho el Señor Jehová: Hiere con tu mano, y huella con tu pie, y di: ­Ay de los males de la casa de Israel por todas las abominaciones! porque con cuchillo, y con hambre, y con pestilencia caerán.",
      "12": "El que estuviere lejos, morirá de pestilencia; y el que estuviere cerca caerá á cuchillo; y el que quedare, y fuere cercado, morirá de hambre: así cumpliré en ellos mi enojo.",
      "13": "Y sabréis que yo soy Jehová, cuando sus muertos estarán en medio de sus ídolos, en derredor de sus altares, en todo collado alto, y en todas las cumbres de los montes, y debajo de todo árbol sombrío, y debajo de toda encina espesa, lugares donde dieron olor suave á todos sus ídolos.",
      "14": "Y extenderé mi mano sobre ellos, y tornaré la tierra asolada y desierta, más que el desierto hacia Diblath, en todas sus habitaciones: y conocerán que yo soy Jehová."
    }
  }
};

