
	
export const bib_verses = {
  "numbers": {
    "25": {
      "1": "Y REPOSO Israel en Sittim, y el pueblo empezó á fornicar con las hijas de Moab:",
      "2": "Las cuales llamaron al pueblo á los sacrificios de sus dioses: y el pueblo comió, é inclinóse á sus dioses.",
      "3": "Y allegóse el pueblo á Baal-peor; y el furor de Jehová se encendió contra Israel.",
      "4": "Y Jehová dijo á Moisés: Toma todos los príncipes del pueblo, y ahórcalos á Jehová delante del sol; y la ira del furor de Jehová se apartará de Israel.",
      "5": "Entonces Moisés dijo á los jueces de Israel: Matad cada uno á aquellos de los suyos que se han allegado á Baal-peor.",
      "6": "Y he aquí un varón de los hijos de Israel vino y trajo una Madianita á sus hermanos, á ojos de Moisés y de toda la congregación de los hijos de Israel, llorando ellos á la puerta del tabernáculo del testimonio.",
      "7": "Y viólo Phinees, hijo de Eleazar, hijo de Aarón el sacerdote, y levantóse de en medio de la congregación, y tomó una lanza en su mano:",
      "8": "Y fué tras el varón de Israel á la tienda, y alanceólos á ambos, al varón de Israel, y á la mujer por su vientre. Y cesó la mortandad de los hijos de Israel.",
      "9": "Y murieron de aquella mortandad veinte y cuatro mil.",
      "10": "Entonces Jehová habló á Moisés, diciendo:",
      "11": "Phinees, hijo de Eleazar, hijo de Aarón el sacerdote, ha hecho tornar mi furor de los hijos de Israel, llevado de celo entre ellos: por lo cual yo no he consumido en mi celo á los hijos de Israel.",
      "12": "Por tanto di les: He aquí yo establezco mi pacto de paz con él;",
      "13": "Y tendrá él, y su simiente después de él, el pacto del sacerdocio perpetuo; por cuanto tuvo celo por su Dios, é hizo expiación por los hijos de Israel.",
      "14": "Y el nombre del varón muerto, que fué muerto con la Madianita, era Zimri hijo de Salu, jefe de una familia de la tribu de Simeón.",
      "15": "Y el nombre de la mujer Madianita muerta, era Cozbi, hija de Zur, príncipe de pueblos, padre de familia en Madián.",
      "16": "Y Jehová habló á Moisés, diciendo:",
      "17": "Hostilizaréis á los Madianitas, y los heriréis:",
      "18": "Por cuanto ellos os afligieron á vosotros con sus ardides, con que os han engañado en el negocio de Peor, y en el negocio de Cozbi, hija del príncipe de Madián, su hermana, la cual fué muerta el día de la mortandad por causa de Peor."
    },
    "26": {
      "1": "Y ACONTECIO después de la mortandad, que Jehová habló á Moisés, y á Eleazar hijo del sacerdote Aarón, diciendo:",
      "2": "Tomad la suma de toda la congregación de los hijos de Israel, de veinte años arriba, por las casas de sus padres, todos los que puedan salir á la guerra en Israel.",
      "3": "Y Moisés y Eleazar el sacerdote hablaron con ellos en los campos de Moab, junto al Jordán de Jericó, diciendo:",
      "4": "Contaréis el pueblo de veinte años arriba, como mandó Jehová á Moisés y á los hijos de Israel, que habían salido de tierra de Egipto.",
      "5": "Rubén primogénito de Israel: los hijos de Rubén: Hanoc, del cual era la familia de los Hanochîtas; de Phallú, la familia de los Phalluitas;",
      "6": "De Hesrón, la familia de los Hesronitas; de Carmi, la familia de los Carmitas.",
      "7": "Estas son las familias de los Rubenitas: y sus contados fueron cuarenta y tres mil setecientos y treinta.",
      "8": "Y los hijos de Phallú: Eliab.",
      "9": "Y los hijos de Eliab: Nemuel, y Dathán, y Abiram. Estos Dathán y Abiram fueron los del consejo de la congregación, que hicieron el motín contra Moisés y Aarón con la compañía de Coré, cuando se amotinaron contra Jehová.",
      "10": "Que la tierra abrió su boca y tragó á ellos y á Coré, cuando aquella compañía murió, cuando consumió el fuego doscientos y cincuenta varones, los cuales fueron por señal.",
      "11": "Mas los hijos de Coré no murieron.",
      "12": "Los hijos de Simeón por sus familias: de Nemuel, la familia de los Nemuelitas; de Jamín, la familia de los Jaminitas; de Jachîn, la familia de los Jachînitas;",
      "13": "De Zera, la familia de los Zeraitas; de Saul, la familia de los Saulitas.",
      "14": "Estas son las familias de los Simeonitas, veinte y dos mil y doscientos.",
      "15": "Los hijos de Gad por sus familias: de Zephón, la familia de los Zephonitas; de Aggi, la familia de los Aggitas; de Suni, la familia de los Sunitas;",
      "16": "De Ozni, la familia de los Oznitas; de Eri, la familia de los Eritas;",
      "17": "De Aroz, la familia de los Aroditas; de Areli, la familia de los Arelitas.",
      "18": "Estas son las familias de Gad, por sus contados, cuarenta mil y quinientos.",
      "19": "Los hijos de Judá: Er y Onán; y Er y Onán murieron en la tierra de Canaán.",
      "20": "Y fueron los hijos de Judá por sus familias: de Sela, la familia de los Selaitas; de Phares, la familia de los Pharesitas; de Zera, la familia de los Zeraitas.",
      "21": "Y fueron los hijos de Phares: de Hesrón, la familia de los Hesronitas; de Hamul, la familia de los Hamulitas.",
      "22": "Estas son las familias de Judá, por sus contados, setenta y seis mil y quinientos.",
      "23": "Los hijos de Issachâr por sus familias: de Thola, la familia de los Tholaitas; de Puá la familia de los Puanitas;",
      "24": "De Jasub, la familia de los Jasubitas; de Simron, la familia de los Simronitas.",
      "25": "Estas son las familias de Issachâr, por sus contados, sesenta y cuatro mil y trescientos.",
      "26": "Los hijos de Zabulón por sus familias: de Sered, la familia de los Sereditas; de Elón, la familia de los Elonitas; de Jalel, la familia de los Jalelitas.",
      "27": "Estas son las familias de los Zabulonitas, por sus contados, sesenta mil y quinientos.",
      "28": "Los hijos de José por sus familias: Manasés y Ephraim.",
      "29": "Los hijos de Manasés: de Machîr, la familia de los Machîritas; y Machîr engendró á Galaad; de Galaad, la familia de los Galaaditas.",
      "30": "Estos son los hijos de Galaad: de Jezer, la familia de los Jezeritas; de Helec, la familia de los Helecitas;",
      "31": "De Asriel, la familia de los Asrielitas: de Sechêm, la familia de los Sechêmitas;",
      "32": "De Semida, la familia de los Semidaitas; de Hepher, la familia de los Hepheritas.",
      "33": "Y Salphaad, hijo de Hepher, no tuvo hijos sino hijas: y los nombres de las hijas de Salphaad fueron Maala, y Noa, y Hogla, y Milca, y Tirsa.",
      "34": "Estas son las familias de Manasés; y sus contados, cincuenta y dos mil y setecientos.",
      "35": "Estos son los hijos de Ephraim por sus familias: de Suthala, la familia de los Suthalaitas; de Bechêr, la familia de los Bechêritas; de Tahan, la familia de los Tahanitas.",
      "36": "Y estos son los hijos de Suthala: de Herán, la familia de los Heranitas.",
      "37": "Estas son las familias de los hijos de Ephraim, por sus contados, treinta y dos mil y quinientos. Estos son los hijos de José por sus familias.",
      "38": "Los hijos de Benjamín por sus familias: de Bela, la familia de los Belaitas; de Asbel, la familia de los Asbelitas; de Achîram, la familia de los Achîramitas;",
      "39": "De Supham, la familia de los Suphamitas; de Hupham, la familia de los Huphamitas.",
      "40": "Y los hijos de Bela fueron Ard y Naamán: de Ard, la familia de los Arditas; de Naamán, la familia de los Naamanitas.",
      "41": "Estos son los hijos de Benjamín por sus familias; y sus contados, cuarenta y cinco mil y seiscientos.",
      "42": "Estos son los hijos de Dan por sus familias: de Suham, la familia de los Suhamitas. Estas son las familias de Dan por sus familias.",
      "43": "Todas las familias de los Suhamitas, por sus contados, sesenta y cuatro mil y cuatrocientos.",
      "44": "Los hijos de Aser por sus familias: de Imna, la familia de los Imnaitas; de Issui, la familia de los Issuitas; de Beria, la familia de los Beriaitas.",
      "45": "Los hijos de Beria: de Heber, la familia de los Heberitas; de Malchîel, la familia de los Malchîelitas.",
      "46": "Y el nombre de la hija de Aser fué Sera.",
      "47": "Estas son las familias de los hijos de Aser, por sus contados, cincuenta y tres mil y cuatrocientos.",
      "48": "Los hijos de Nephtalí por sus familias: de Jahzeel, la familia de los Jahzeelitas; de Guni, la familia de los Gunitas;",
      "49": "De Jeser, la familia de los Jeseritas; de Sillem, la familia de los Sillemitas.",
      "50": "Estas son las familias de Nephtalí por sus familias; y sus contados, cuarenta y cinco mil y cuatrocientos.",
      "51": "Estos son los contados de los hijos de Israel, seiscientos y un mil setecientos y treinta.",
      "52": "Y habló Jehová á Moisés, diciendo:",
      "53": "A estos se repartirá la tierra en heredad, por la cuenta de los nombres.",
      "54": "A los más darás mayor heredad, y á los menos menor; y á cada uno se le dará su heredad conforme á sus contados.",
      "55": "Empero la tierra será repartida por suerte; y por los nombres de las tribus de sus padres heredarán.",
      "56": "Conforme á la suerte será repartida su heredad entre el grande y el pequeño.",
      "57": "Y los contados de los Levitas por sus familias son estos: de Gersón, la familia de los Gersonitas; de Coath, la familia de los Coathitas; de Merari, la familia de los Meraritas.",
      "58": "Estas son las familias de los Levitas: la familia de los Libnitas, la familia de los Hebronitas, la familia de los Mahalitas, la familia de los Musitas, la familia de los Coritas. Y Coath engendró á Amram.",
      "59": "Y la mujer de Amram se llamó Jochâbed, hija de Leví, la cual nació á Leví en Egipto: ésta parió de Amram á Aarón y á Moisés, y á María su hermana.",
      "60": "Y á Aarón nacieron Nadab y Abiú, Eleazar é Ithamar.",
      "61": "Mas Nadab y Abiú murieron, cuando ofrecieron fuego extraño delante de Jehová.",
      "62": "Y los contados de los Levitas fueron veinte y tres mil, todos varones de un mes arriba: porque no fueron contados entre los hijos de Israel, por cuanto no les había de ser dada heredad entre los hijos de Israel.",
      "63": "Estos son los contados por Moisés y Eleazar el sacerdote, los cuales contaron los hijos de Israel en los campos de Moab, junto al Jordán de Jericó.",
      "64": "Y entre estos ninguno hubo de los contados por Moisés y Aarón el sacerdote, los cuales contaron á los hijos de Israel en el desierto de Sinaí.",
      "65": "Porque Jehová les dijo: Han de morir en el desierto: y no quedó varón de ellos, sino Caleb hijo de Jephone, y Josué hijo de Nun."
    },
    "27": {
      "1": "Y LAS hijas de Salphaad, hijo de Hepher, hijo de Galaad, hijo de Machîr, hijo de Manasés, de las familias de Manasés, hijo de José, los nombres de las cuales eran Maala, y Noa, y Hogla, y Milca, y Tirsa, llegaron;",
      "2": "Y presentáronse delante de Moisés, y delante del sacerdote Eleazar, y delante de los príncipes, y de toda la congregación, á la puerta del tabernáculo del testimonio, y dijeron:",
      "3": "Nuestro padre murió en el desierto, el cual no estuvo en la junta que se reunió contra Jehová en la compañía de Coré: sino que en su pecado murió, y no tuvo hijos.",
      "4": "¿Por qué será quitado el nombre de nuestro padre de entre su familia, por no haber tenido hijo? Danos heredad entre los hermanos de nuestro padre.",
      "5": "Y Moisés llevó su causa delante de Jehová.",
      "6": "Y Jehová respondió á Moisés, diciendo:",
      "7": "Bien dicen las hijas de Salphaad: has de darles posesión de heredad entre los hermanos de su padre; y traspasarás la heredad de su padre á ellas.",
      "8": "Y á los hijos de Israel hablarás, diciendo: Cuando alguno muriere sin hijos, traspasaréis su herencia á su hija:",
      "9": "Y si no tuviere hija, daréis su herencia á sus hermanos:",
      "10": "Y si no tuviere hermanos, daréis su herencia á los hermanos de su padre.",
      "11": "Y si su padre no tuviere hermanos, daréis su herencia á su pariente más cercano de su linaje, el cual la poseerá: y será á los hijos de Israel por estatuto de derecho, como Jehová mandó á Moisés.",
      "12": "Y Jehová dijo á Moisés: Sube á este monte Abarim, y verás la tierra que he dado á los hijos de Israel.",
      "13": "Y después que la habrás visto, tú también serás reunido á tus pueblos, como fué reunido tu hermano Aarón:",
      "14": "Pues fuisteis rebeldes á mi dicho en el desierto de Zin, en la rencilla de la congregación, para santificarme en las aguas á ojos de ellos. Estas son las aguas de la rencilla de Cades en el desierto de Zin.",
      "15": "Entonces respondió Moisés á Jehová, diciendo:",
      "16": "Ponga Jehová, Dios de los espíritus de toda carne, varón sobre la congregación,",
      "17": "Que salga delante de ellos, y que entre delante de ellos, que los saque y los introduzca; porque la congregación de Jehová no sea como ovejas sin pastor.",
      "18": "Y Jehová dijo á Moisés: Toma á Josué hijo de Nun, varón en el cual hay espíritu, y pondrás tu mano sobre él;",
      "19": "Y ponerlo has delante de Eleazar el sacerdote, y delante de toda la congregación; y le darás órdenes en presencia de ellos.",
      "20": "Y pondrás de tu dignidad sobre él, para que toda la congregación de los hijos de Israel le obedezcan.",
      "21": "Y él estará delante de Eleazar el sacerdote, y á él preguntará por el juicio del Urim delante de Jehová: por el dicho de él saldrán, y por el dicho de él entrarán, él, y todos los hijos de Israel con él, y toda la congregación.",
      "22": "Y Moisés hizo como Jehová le había mandado; que tomó á Josué, y le puso delante de Eleazar el sacerdote, y de toda la congregación:",
      "23": "Y puso sobre él sus manos, y dióle órdenes, como Jehová había mandado por mano de Moisés."
    },
    "28": {
      "1": "Y HABLO Jehová á Moisés, diciendo:",
      "2": "Manda á los hijos de Israel, y diles: Mi ofrenda, mi pan con mis ofrendas encendidas en olor á mí agradable, guardaréis, ofreciéndomelo á su tiempo.",
      "3": "Y les dirás: Esta es la ofrenda encendida que ofreceréis á Jehová: dos corderos sin tacha de un año, cada un día, será el holocausto continuo.",
      "4": "El un cordero ofrecerás por la mañana, y el otro cordero ofrecerás entre las dos tardes:",
      "5": "Y la décima de un epha de flor de harina, amasada con una cuarta de un hin de aceite molido, en presente.",
      "6": "Es holocausto continuo, que fué hecho en el monte de Sinaí en olor de suavidad, ofrenda encendida á Jehová.",
      "7": "Y su libación, la cuarta de un hin con cada cordero: derramarás libación de superior vino á Jehová en el santuario.",
      "8": "Y ofrecerás el segundo cordero entre las dos tardes: conforme á la ofrenda de la mañana, y conforme á su libación ofrecerás, ofrenda encendida en olor de suavidad á Jehová.",
      "9": "Mas el día del sábado dos corderos de un año sin defecto, y dos décimas de flor de harina amasada con aceite, por presente, con su libación:",
      "10": "Es el holocausto del sábado en cada sábado, además del holocausto continuo y su libación.",
      "11": "Y en los principios de vuestros meses ofreceréis en holocausto á Jehová dos becerros de la vacada, y un carnero, y siete corderos de un año sin defecto;",
      "12": "Y tres décimas de flor de harina amasada con aceite, por presente con cada becerro; y dos décimas de flor de harina amasada con aceite, por presente con cada carnero;",
      "13": "Y una décima de flor de harina amasada con aceite, en ofrenda por presente con cada cordero: holocausto de olor suave, ofrenda encendida á Jehová.",
      "14": "Y sus libaciones de vino, medio hin con cada becerro, y el tercio de un hin con cada carnero, y la cuarta de un hin con cada cordero. Este es el holocausto de cada mes por todos los meses del año.",
      "15": "Y un macho cabrío en expiación se ofrecerá á Jehová, además del holocausto continuo con su libación.",
      "16": "Mas en el mes primero, á los catorce del mes será la pascua de Jehová.",
      "17": "Y á los quince días de aqueste mes, la solemnidad: por siete días se comerán ázimos.",
      "18": "El primer día, santa convocación; ninguna obra servil haréis:",
      "19": "Y ofreceréis por ofrenda encendida en holocausto á Jehová dos becerros de la vacada, y un carnero, y siete corderos de un año: sin defecto los tomaréis:",
      "20": "Y su presente de harina amasada con aceite: tres décimas con cada becerro, y dos décimas con cada carnero ofreceréis;",
      "21": "Con cada uno de los siete corderos ofreceréis una décima;",
      "22": "Y un macho cabrío por expiación, para reconciliaros.",
      "23": "Esto ofreceréis además del holocausto de la mañana, que es el holocausto continuo.",
      "24": "Conforme á esto ofreceréis cada uno de los siete días, vianda y ofrenda encendida en olor de suavidad á Jehová; ofrecerse ha, además del holocausto continuo, con su libación.",
      "25": "Y el séptimo día tendréis santa convocación: ninguna obra servil haréis.",
      "26": "Además el día de las primicias, cuando ofreciereis presente nuevo á Jehová en vuestras semanas, tendréis santa convocación: ninguna obra servil haréis:",
      "27": "Y ofreceréis en holocausto, en olor de suavidad á Jehová, dos becerros de la vacada, un carnero, siete corderos de un año:",
      "28": "Y el presente de ellos, flor de harina amasada con aceite, tres décimas con cada becerro, dos décimas con cada carnero,",
      "29": "Con cada uno de los siete corderos una décima;",
      "30": "Un macho cabrío, para hacer expiación por vosotros.",
      "31": "Los ofreceréis, además del holocausto continuo con sus presentes, y sus libaciones: sin defecto los tomaréis."
    },
    "29": {
      "1": "Y EL séptimo mes, al primero del mes tendréis santa convocación: ninguna obra servil haréis; os será día de sonar las trompetas.",
      "2": "Y ofreceréis holocausto por olor de suavidad á Jehová, un becerro de la vacada, un carnero, siete corderos de un año sin defecto;",
      "3": "Y el presente de ellos, de flor de harina amasada con aceite, tres décimas con cada becerro, dos décimas con cada carnero,",
      "4": "Y con cada uno de los siete corderos, una décima;",
      "5": "Y un macho cabrío por expiación, para reconciliaros:",
      "6": "Además del holocausto del mes, y su presente, y el holocausto continuo y su presente, y sus libaciones, conforme á su ley, por ofrenda encendida á Jehová en olor de suavidad.",
      "7": "Y en el diez de este mes séptimo tendréis santa convocación, y afligiréis vuestras almas: ninguna obra haréis:",
      "8": "Y ofreceréis en holocausto á Jehová por olor de suavidad, un becerro de la vacada, un carnero, siete corderos de un año; sin defecto los tomaréis:",
      "9": "Y sus presentes, flor de harina amasada con aceite, tres décimas con cada becerro, dos décimas con cada carnero,",
      "10": "Y con cada uno de los siete corderos, una décima;",
      "11": "Un macho cabrío por expiación: además de la ofrenda de las expiaciones por el pecado, y del holocausto continuo, y de sus presentes, y de sus libaciones.",
      "12": "También á los quince días del mes séptimo tendréis santa convocación; ninguna obra servil haréis, y celebraréis solemnidad á Jehová por siete días;",
      "13": "Y ofreceréis en holocausto, en ofrenda encendida á Jehová en olor de suavidad, trece becerros de la vacada, dos carneros, catorce corderos de un año: han de ser sin defecto;",
      "14": "Y los presentes de ellos, de flor de harina amasada con aceite, tres décimas con cada uno de los trece becerros, dos décimas con cada uno de los dos carneros,",
      "15": "Y con cada uno de los catorce corderos, una décima;",
      "16": "Y un macho cabrío por expiación: además del holocausto continuo, su presente y su libación.",
      "17": "Y el segundo día, doce becerros de la vacada, dos carneros, catorce corderos de un año sin defecto;",
      "18": "Y sus presentes y sus libaciones con los becerros, con los carneros, y con los corderos, según el número de ellos, conforme á la ley;",
      "19": "Y un macho cabrío por expiación: además del holocausto continuo, y su presente y su libación.",
      "20": "Y el día tercero, once becerros, dos carneros, catorce corderos de un año sin defecto;",
      "21": "Y sus presentes y sus libaciones con los becerros, con los carneros, y con los corderos, según el número de ellos, conforme á la ley;",
      "22": "Y un macho cabrío por expiación: además del holocausto continuo, y su presente y su libación.",
      "23": "Y el cuarto día, diez becerros, dos carneros, catorce corderos de un año sin defecto;",
      "24": "Sus presentes y sus libaciones con los becerros, con los carneros, y con los corderos, según el número de ellos, conforme á la ley;",
      "25": "Y un macho cabrío por expiación: además del holocausto continuo, su presente y su libación.",
      "26": "Y el quinto día, nueve becerros, dos carneros, catorce corderos de un año sin defecto;",
      "27": "Y sus presentes y sus libaciones con los becerros, con los carneros, y con los corderos, según el número de ellos, conforme á la ley;",
      "28": "Y un macho cabrío por expiación: además del holocausto continuo, su presente y su libación.",
      "29": "Y el sexto día, ocho becerros, dos carneros, catorce corderos de un año sin defecto;",
      "30": "Y sus presentes y sus libaciones con los becerros, con los carneros, y con los corderos, según el número de ellos, conforme á la ley;",
      "31": "Y un macho cabrío por expiación: además del holocausto continuo, su presente y sus libaciones.",
      "32": "Y el séptimo día, siete becerros, dos carneros, catorce corderos de un año sin defecto;",
      "33": "Y sus presentes y sus libaciones con los becerros, con los carneros, y con los corderos, según el número de ellos, conforme á la ley;",
      "34": "Y un macho cabrío por expiación: además del holocausto continuo, con su presente y su libación.",
      "35": "El octavo día tendréis solemnidad: ninguna obra servil haréis:",
      "36": "Y ofreceréis en holocausto, en ofrenda encendida de olor suave á Jehová, un novillo, un carnero, siete corderos de un año sin defecto;",
      "37": "Sus presentes y sus libaciones con el novillo, con el carnero, y con los corderos, según el número de ellos, conforme á la ley;",
      "38": "Y un macho cabrío por expiación: además del holocausto continuo, con su presente y su libación.",
      "39": "Estas cosas ofreceréis á Jehová en vuestras solemnidades, además de vuestros votos, y de vuestras ofrendas libres, para vuestros holocaustos, y para vuestros presentes, y para vuestras libaciones y para vuestras paces.",
      "40": " Y MOISÉS dijo á los hijos de Israel, conforme á todo lo que Jehová le había mandado."
    },
    "30": {
      "1": " Y habló Moisés á los príncipes de las tribus de los hijos de Israel, diciendo: Esto es lo que Jehová ha mandado.",
      "2": " Cuando alguno hiciere voto á Jehová, ó hiciere juramento ligando su alma con obligación, no violará su palabra: hará conforme á todo lo que salió de su boca.",
      "3": " Mas la mujer, cuando hiciere voto á Jehová, y se ligare con obligación en casa de su padre, en su mocedad;",
      "4": " Si su padre oyere su voto, y la obligación con que ligó su alma, y su padre callare á ello, todos los votos de ella serán firmes, y toda obligación con que hubiere ligado su alma, firme será.",
      "5": " Mas si su padre le vedare el día que oyere todos sus votos y sus obligaciones, con que ella hubiere ligado su alma, no serán firmes; y Jehová la perdonará, por cuanto su padre le vedó.",
      "6": " Empero si fuére casada, é hiciere votos, o pronunciare de sus labios cosa con que obligue su alma;",
      "7": " Si su marido lo oyere, y cuando lo oyere callare á ello, los votos de ella serán firmes, y la obligación con que ligó su alma, firme será.",
      "8": " Pero si cuando su marido lo oyó, le vedó, entonces el voto que ella hizo, y lo que pronunció de sus labios con que ligó su alma, será nulo; y Jehová lo perdonará.",
      "9": " Mas todo voto de viuda, ó repudiada, con que ligare su alma, será firme.",
      "10": " Y si hubiere hecho voto en casa de su marido, y hubiere ligado su alma con obligación de juramento,",
      "11": " Si su marido oyó, y calló á ello, y no le vedó; entonces todos sus votos serán firmes, y toda obligación con que hubiere ligado su alma, firme será.",
      "12": " Mas si su marido los anuló el día que los oyó; todo lo que salió de sus labios cuanto á sus votos, y cuanto á la obligación de su alma, será nulo; su marido los anuló, y Jehová la perdonará.",
      "13": " Todo voto, ó todo juramento obligándose á afligir el alma, su marido lo confirmará, ó su marido lo anulará.",
      "14": " Empero si su marido callare á ello de día en día, entonces confirmó todos sus votos, y todas las obligaciones que están sobre ella: confirmólas, por cuanto calló á ello el día que lo oyó.",
      "15": " Mas si las anulare después de haberlas oido, entonces él llevará el pecado de ella.",
      "16": " Estas son las ordenanzas que Jehová mandó á Moisés entre el varón y su mujer, entre el padre y su hija, durante su mocedad en casa de su padre."
    },
    "31": {
      "1": "Y JEHOVA habló á Moisés, diciendo:",
      "2": "Haz la venganza de los hijos de Israel sobre los Madianitas; después serás recogido á tus pueblos.",
      "3": "Entonces Moisés habló al pueblo, diciendo: Armaos algunos de vosotros para la guerra, é irán contra Madián, y harán la venganza de Jehová en Madián.",
      "4": "Mil de cada tribu de todas las tribus de los hijos de Israel, enviaréis á la guerra.",
      "5": "Así fueron dados de los millares de Israel, mil por cada tribu, doce mil á punto de guerra.",
      "6": "Y Moisés los envió á la guerra: mil por cada tribu envió: y Phinees, hijo de Eleazar sacerdote, fué á la guerra con los santos instrumentos, con las trompetas en su mano para tocar.",
      "7": "Y pelearon contra Madián, como Jehová lo mandó á Moisés, y mataron á todo varón.",
      "8": "Mataron también, entre los muertos de ellos, á los reyes de Madián: Evi, y Recem, y Zur, y Hur, y Reba, cinco reyes de Madián; á Balaam también, hijo de Beor, mataron á cuchillo.",
      "9": "Y llevaron cautivas los hijos de Israel las mujeres de los Madianitas, y sus chiquitos y todas sus bestias, y todos sus ganados; y arrebataron toda su hacienda.",
      "10": "Y abrasaron con fuego todas sus ciudades, aldeas y castillos.",
      "11": "Y tomaron todo el despojo, y toda la presa, así de hombres como de bestias.",
      "12": "Y trajeron á Moisés, y á Eleazar el sacerdote, y á la congregación de los hijos de Israel, los cautivos y la presa y los despojos, al campo en los llanos de Moab, que están junto al Jordán de Jericó.",
      "13": "Y salieron Moisés y Eleazar el sacerdote, y todos los príncipes de la congregación, á recibirlos fuera del campo.",
      "14": "Y enojóse Moisés contra los capitanes del ejército, contra los tribunos y centuriones que volvían de la guerra;",
      "15": "Y díjoles Moisés: ¿Todas las mujeres habéis reservado?",
      "16": "He aquí ellas fueron á los hijos de Israel, por consejo de Balaam, para causar prevaricación contra Jehová en el negocio de Peor; por lo que hubo mortandad en la congregación de Jehová.",
      "17": "Matad pues ahora todos los varones entre los niños: matad también toda mujer que haya conocido varón carnalmente.",
      "18": "Y todas las niñas entre las mujeres, que no hayan conocido ayuntamiento de varón, os reservaréis vivas.",
      "19": "Y vosotros quedaos fuera del campo siete días: y todos los que hubieren matado persona, y cualquiera que hubiere tocado muerto, os purificaréis al tercero y al séptimo día, vosotros y vuestros cautivos.",
      "20": "Asimismo purificaréis todo vestido, y toda prenda de pieles, y toda obra de pelos de cabra, y todo vaso de madera.",
      "21": "Y Eleazar el sacerdote dijo á los hombres de guerra que venían de la guerra: Esta es la ordenanza de la ley que Jehová ha mandado á Moisés:",
      "22": "Ciertamente el oro, y la plata, metal, hierro, estaño, y plomo,",
      "23": "Todo lo que resiste el fuego, por fuego lo haréis pasar, y será limpio, bien que en las aguas de purificación habrá de purificarse: mas haréis pasar por agua todo lo que no aguanta el fuego.",
      "24": "Además lavaréis vuestros vestidos el séptimo día, y así seréis limpios; y después entraréis en el campo.",
      "25": "Y Jehová habló á Moisés, diciendo:",
      "26": "Toma la cuenta de la presa que se ha hecho, así de las personas como de las bestias, tú y el sacerdote Eleazar, y las cabezas de los padres de la congregación:",
      "27": "Y partirás por mitad la presa entre los que pelearon, los que salieron á la guerra, y toda la congregación.",
      "28": "Y apartarás para Jehová el tributo de los hombres de guerra, que salieron á la guerra: de quinientos uno, así de las personas como de los bueyes, de los asnos, y de las ovejas:",
      "29": "De la mitad de ellos lo tomarás; y darás á Eleazar el sacerdote la ofrenda de Jehová.",
      "30": "Y de la mitad perteneciente á los hijos de Israel tomarás uno de cincuenta, de las personas, de los bueyes, de los asnos, y de las ovejas, de todo animal; y los darás á los Levitas, que tienen la guarda del tabernáculo de Jehová.",
      "31": "E hicieron Moisés y Eleazar el sacerdote como Jehová mandó á Moisés.",
      "32": "Y fué la presa, el resto de la presa que tomaron los hombres de guerra, seiscientas y setenta y cinco mil ovejas,",
      "33": "Y setenta y dos mil bueyes,",
      "34": "Y setenta y un mil asnos;",
      "35": "Y en cuanto á personas, de mujeres que no habían conocido ayuntamiento de varón, en todas trenita y dos mil.",
      "36": "Y la mitad, la parte de los que habían salido á la guerra, fué el número de trescientas treinta y siete mil y quinientas ovejas.",
      "37": "Y el tributo para Jehová de la ovejas, fué seiscientas setenta y cinco.",
      "38": "Y de los bueyes, treinta y seis mil: y de ellos el tributo para Jehová, setenta y dos.",
      "39": "Y de los asnos, treinta mil y quinientos: y de ellos el tributo para Jehová, setenta y uno.",
      "40": "Y de las personas, diez y seis mil: y de ellas el tributo para Jehová, trteinta y dos personas.",
      "41": "Y dió Moisés el tributo, por elevada ofrenda á Jehová, á Eleazar el sacerdote, como Jehová lo mandó á Moisés.",
      "42": "Y de la mitad para los hijos de Israel, que apartó Moisés de los hombres que habían ido á la guerra;",
      "43": "(La mitad para la congregación fué: de las ovejas, trescientas treinta y siete mil y quinientas;",
      "44": "Y de los bueyes, treinta y seis mil;",
      "45": "Y de los asnos, treinta mil y quinientos;",
      "46": "Y de las personas, diez y seis mil:)",
      "47": "De la mitad, pues, para los hijos de Israel tomó Moisés uno de cada cincuenta, así de las personas como de los animales, y diólos á los Levitas, que tenían la guarda del tabernáculo de Jehová; como Jehová lo había mandado á Moisés.",
      "48": "Y llegaron á Moisés los jefes de los millares de aquel ejército, los tribunos y centuriones;",
      "49": "Y dijeron á Moisés: Tus siervos han tomado razón de los hombres de guerra que están en nuestro poder, y ninguno ha faltado de nosotros.",
      "50": "Por lo cual hemos ofrecido á Jehová ofrenda, cada uno de lo que ha hallado, vasos de oro, brazaletes, manillas, anillos, zarcillos, y cadenas, para hacer expiación por nuestras almas delante de Jehová.",
      "51": "Y Moisés y el sacerdote Eleazar recibieron el oro de ellos, alhajas, todas elaboradas.",
      "52": "Y todo el oro de la ofrenda que ofrecieron á Jehová de los tribunos y centuriones, fué diez y seis mil setecientos y cincuenta siclos.",
      "53": "Los hombres del ejército habían pillado cada uno para sí.",
      "54": "Recibieron, pues, Moisés y el sacerdote Eleazar, el oro de los tribunos y centuriones, y trajéronlo al tabernáculo del testimonio, por memoria de los hijos de Israel delante de Jehová."
    },
    "32": {
      "1": "Y LOS hijos de Rubén y los hijos de Gad tenían una muy grande muchedumbre de ganado; los cuales viendo la tierra de Jazer y de Galaad, parecióles el país lugar de ganado.",
      "2": "Y vinieron los hijos de Gad y los hijos de Rubén, y hablaron á Moisés, y á Eleazar el sacerdote, y á los príncipes de la congregación, diciendo:",
      "3": "Ataroth, y Dibón, y Jazer, y Nimra, y Hesbón, y Eleale, y Sabán, y Nebo, y Beón,",
      "4": "La tierra que Jehová hirió delante de la congregación de Israel, es tierra de ganado, y tus siervos tienen ganado.",
      "5": "Por tanto, dijeron, si hallamos gracia en tus ojos, dése esta tierra á tus siervos en heredad, y no nos hagas pasar el Jordán.",
      "6": "Y respondió Moisés á los hijos de Gad y á los hijos de Rubén: ¿Vendrán vuestros hermanos á la guerra, y vosotros os quedaréis aquí?",
      "7": "¿Y por qué prevenís el ánimo de los hijos de Israel, para que no pasen á la tierra que les ha dado Jehová?",
      "8": "Así hicieron vuestros padres, cuando los envié desde Cades-barnea para que viesen la tierra.",
      "9": "Que subieron hasta la arroyada de Escol, y después que vieron la tierra, preocuparon el ánimo de los hijos de Israel, para que no viniesen á la tierra que Jehová les había dado.",
      "10": "Y el furor de Jehová se encendió entonces, y juró diciendo:",
      "11": "Que no verán los varones que subieron de Egipto de veinte años arriba, la tierra por la cual juré á Abraham, Isaac, y Jacob, por cuanto no fueron perfectos en pos de mí;",
      "12": "Excepto Caleb, hijo de Jephone Cenezeo, y Josué hijo de Nun, que fueron perfectos en pos de Jehová.",
      "13": "Y el furor de Jehová se encendió en Israel, é hízolos andar errantes cuarenta años por el desierto, hasta que fué acabada toda aquella generación, que había hecho mal delante de Jehová.",
      "14": "Y he aquí vosotros habéis sucedido en lugar de vuestros padres, prole de hombres pecadores, para añadir aún á la ira de Jehová contra Israel.",
      "15": "Si os volviereis de en pos de él, él volverá otra vez á dejaros en el desierto, y destruiréis á todo este pueblo.",
      "16": "Entonces ellos se allegaron á él y dijeron: Edificaremos aquí majadas para nuestro ganado, y ciudades para nuestros niños;",
      "17": "Y nosotros nos armaremos, é iremos con diligencia delante de los hijos de Israel, hasta que los metamos en su lugar: y nuestros niños quedarán en ciudades fuertes á causa de los moradores del país.",
      "18": "No volveremos á nuestras casas hasta que los hijos de Israel posean cada uno su heredad.",
      "19": "Porque no tomaremos heredad con ellos al otro lado del Jordán ni adelante, por cuanto tendremos ya nuestra heredad de estotra parte del Jordán al oriente.",
      "20": "Entonces les respondió Moisés: Si lo hiciereis así, si os apercibiereis para ir delante de Jehová á la guerra,",
      "21": "Y pasareis todos vosotros armados el Jordán delante de Jehová, hasta que haya echado á sus enemigos de delante de sí,",
      "22": "Y sea el país sojuzgado delante de Jehová; luego volveréis, y seréis libres de culpa para con Jehová, y para con Israel; y esta tierra será vuestra en heredad delante de Jehová.",
      "23": "Mas si así no lo hiciereis, he aquí habréis pecado á Jehová; y sabed que os alcanzará vuestro pecado.",
      "24": "Edificaos ciudades para vuestros niños, y majadas para vuestras ovejas, y haced lo que ha salido de vuestra boca.",
      "25": "Y hablaron los hijos de Gad y los hijos de Rubén á Moisés, diciendo: Tus siervos harán como mi señor ha mandado.",
      "26": "Nuestros niños, nuestras mujeres, nuestros ganados, y todas nuestras bestias, estarán ahí en las ciudades de Galaad;",
      "27": "Y tus siervos, armados todos de guerra, pasarán delante de Jehová á la guerra, de la manera que mi señor dice.",
      "28": "Entonces los encomendó Moisés á Eleazar el sacerdote, y á Josué hijo de Nun, y á los príncipes de los padres de las tribus de los hijos de Israel.",
      "29": "Y díjoles Moisés: Si los hijos de Gad y los hijos de Rubén, pasaren con vosotros el Jordán, armados todos de guerra delante de Jehová, luego que el país fuere sojuzgado delante de vosotros, les daréis la tierra de Galaad en posesión:",
      "30": "Mas si no pasaren armados con vosotros, entonces tendrán posesión entre vosotros en la tierra de Canaán.",
      "31": "Y los hijos de Gad y los hijos de Rubén respondieron, diciendo: Haremos lo que Jehová ha dicho á tus siervos.",
      "32": "Nosotros pasaremos armados delante de Jehová á la tierra de Canaán, y la posesión de nuestra heredad será de esta parte del Jordán.",
      "33": "Así les dió Moisés á los hijos de Gad y á los hijos de Rubén, y á la media tribu de Manasés hijo de José, el reino de Sehón rey Amorrheo, y el reino de Og rey de Basán, la tierra con sus ciudades y términos, las ciudades del país alrededor.",
      "34": "Y los hijos de Gad edificaron á Dibón, y á Ataroth, y á Aroer,",
      "35": "Y á Atroth-sophan, y á Jazer, y á Jogbaa,",
      "36": "Y á Beth-nimra, y á Betharán: ciudades fuertes, y también majadas para ovejas.",
      "37": "Y los hijos de Rubén edificaron á Hesbón, y á Eleale, y á Kiriathaim,",
      "38": "Y á Nebo, y á Baal-meón, (mudados los nombres), y á Sibma: y pusieron nombres á las ciudades que edificaron.",
      "39": "Y los hijos de Machîr hijo de Manasés fueron á Galaad, y tomáronla, y echaron al Amorrheo que estaba en ella.",
      "40": "Y Moisés dió Galaad á Machîr hijo de Manasés, el cual habitó en ella.",
      "41": "También Jair hijo de Manasés fué y tomó sus aldeas, y púsoles por nombre Havoth-jair.",
      "42": "Asimismo Noba fué y tomó á Kenath y sus aldeas, y llamóle Noba, conforme á su nombre."
    },
    "33": {
      "1": "Estas son las estancias de los hijos de Israel, los cuales salieron de la tierra de Egipto por sus escuadrones, bajo la conducta de Moisés y Aarón.",
      "2": "Y Moisés escribió sus salidas conforme á sus jornadas por mandato de Jehová. Estas, pues, son sus estancias con arreglo á sus partidas.",
      "3": "De Rameses partieron en el mes primero, á los quince diás del mes primero: el segundo día de la pascua salieron los hijos de Israel con mano alta, á ojos de todos los Egipcios.",
      "4": "Estaban enterrando los Egipcios los que Jehová había muerto de ellos, á todo primogénito; habiendo Jehová hecho también juicios en sus dioses.",
      "5": "Partieron, pues, los hijos de Israel de Rameses, y asentaron campo en Succoth.",
      "6": "Y partiendo de Succoth, asentaron en Etham, que está al cabo del desierto.",
      "7": "Y partiendo de Etham, volvieron sobre Pi-hahiroth, que está delante de Baalsephon, y asentaron delante de Migdol.",
      "8": "Y partiendo de Pi-hahiroth, pasaron por medio de la mar al desierto, y anduvieron camino de tres días por el desierto de Etham, y asentaron en Mara.",
      "9": "Y partiendo de Mara, vinieron á Elim, donde había doce fuentes de aguas, y setenta palmeras; y asentaron allí.",
      "10": "Y partidos de Elim, asentaron junto al mar Bermejo.",
      "11": "Y partidos del mar Bermejo, asentaron en el desierto de Sin.",
      "12": "Y partidos del desierto de Sin, asentaron en Dophca.",
      "13": "Y partidos de Dophca, asentaron en Alús.",
      "14": "Y partidos de Alús, asentaron en Rephidim, donde el pueblo no tuvo aguas para beber.",
      "15": "Y partidos de Rephidim, asentaron en el desierto de Sinaí.",
      "16": "Y partidos del desierto de Sinaí, asentaron en fmfm Kibroth-hataava.",
      "17": "Y partidos de Kibroth-hataava, asentaron en Haseroth.",
      "18": "Y partidos de Haseroth, asentaron en Ritma.",
      "19": "Y partidos de Ritma, asentaron en Rimmón-peres.",
      "20": "Y partidos de Rimmón-peres, asentaron en Libna.",
      "21": "Y partidos de Libna, asentaron en Rissa.",
      "22": "Y partidos de Rissa, asentaron en Ceelatha,",
      "23": "Y partidos de Ceelatha, asentaron en el monte de Sepher.",
      "24": "Y partidos del monte de Sepher, asentaron en Harada.",
      "25": "Y partidos de Harada, asentaron en Maceloth.",
      "26": "Y partidos de Maceloth, asentaron en Tahath.",
      "27": "Y partidos de Tahath, asentaron en Tara.",
      "28": "Y partidos de Tara, asentaron en Mithca.",
      "29": "Y partidos de Mithca, asentaron en Hasmona.",
      "30": "Y partidos de Hasmona, asentaron en Moseroth.",
      "31": "Y partidos de Moseroth, asentaron en Bene-jaacán.",
      "32": "Y partidos de Bene-jaacán, asentaron en el monte de Gidgad.",
      "33": "Y partidos del monte de Gidgad, asentaron en Jotbatha.",
      "34": "Y partidos de Jotbatha, asentaron en Abrona.",
      "35": "Y partidos de Abrona, asentaron en Esion-geber.",
      "36": "Y partidos de Esion-geber, asentaron en el desierto de Zin, que es Cades.",
      "37": "Y partidos de Cades, asentaron en el monte de Hor, en la extremidad del país de Edom.",
      "38": "Y subió Aarón el sacerdote al monte de Hor, conforme al dicho de Jehová, y allí murió á los cuarenta años de la salida de los hijos de Israel de la tierra de Egipto, en el mes quinto, en el primero del mes.",
      "39": "Y era Aarón de edad de ciento y veinte y tres años, cuando murió en el monte de Hor.",
      "40": "Y el Cananeo, rey de Arad, que habitaba al mediodía en la tierra de Canaán, oyó como habían venido los hijos de Israel.",
      "41": "Y partidos del monte de Hor, asentaron en Salmona.",
      "42": "Y partidos de Salmona, asentaron en Phunón.",
      "43": "Y partidos de Phunón, asentaron en Oboth.",
      "44": "Y partidos de Oboth, asentaron en Ije-abarim; en el término de Moab.",
      "45": "Y partidos de Ije-abarim, asentaron en Dibón-gad.",
      "46": "Y partidos de Dibón-gad, asentaron en Almon-diblathaim.",
      "47": "Y partidos de Almon-diblathaim, asentaron en los montes de Abarim, delante de Nebo.",
      "48": "Y partidos de los montes de Abarim, asentaron en los campos de Moab, junto al Jordán de Jericó.",
      "49": "Finalmente asentaron junto al Jordán, desde Beth-jesimoth hasta Abel-sitim, en los campos de Moab.",
      "50": "Y habló Jehová á Moisés en los campos de Moab junto al Jordán de Jericó, diciendo:",
      "51": "Habla á los hijos de Israel, y diles: Cuando hubiereis pasado el Jordán á la tierra de Canaán,",
      "52": "Echaréis á todos los moradores del país de delante de vosotros, y destruiréis todas sus pinturas, y todas sus imágenes de fundición, y arruinaréis todos sus altos;",
      "53": "Y echaréis los moradores de la tierra, y habitaréis en ella; porque yo os la he dado para que la poseáis.",
      "54": "Y heredaréis la tierra por suertes por vuestras familias: á los muchos daréis mucho por su heredad, y á los pocos daréis menos por heredad suya: donde le saliere la suerte, allí la tendrá cada uno: por las tribus de vuestros padres heredaréis.",
      "55": "Y si no echareis los moradores del país de delante de vosotros, sucederá que los que dejareis de ellos serán por aguijones en vuestros ojos, y por espinas en vuestros costados, y afligiros han sobre la tierra en que vosotros habitareis.",
      "56": "Será además, que haré á vosotros como yo pensé hacerles á ellos."
    },
    "34": {
      "1": "Y JEHOVA habló á Moisés, diciendo:",
      "2": "Manda á los hijos de Israel, y diles: Cuando hubiereis entrado en la tierra de Canaán, es á saber, la tierra que os ha de caer en heredad, la tierra de Canaán según sus términos;",
      "3": "Tendréis el lado del mediodía desde el desierto de Zin hasta los términos de Edom; y os será el término del mediodía al extremo del mar salado hacia el oriente:",
      "4": "Y este término os irá rodeando desde el mediodía hasta la subida de Acrabbim, y pasará hasta Zin; y sus salidas serán del mediodía á Cades-barnea; y saldrá á Hasar-addar, y pasará hasta Asmón;",
      "5": "Y rodeará este término, desde Asmón hasta el torrente de Egipto, y sus remates serán al occidente.",
      "6": "Y el término occidental os será la gran mar: este término os será el término occidental.",
      "7": "Y el término del norte será este: desde la gran mar os señalaréis el monte de Hor;",
      "8": "Del monte de Hor señalaréis á la entrada de Hamath, y serán las salidas de aquel término á Sedad;",
      "9": "Y saldrá este término á Ziphón, y serán sus remates en Hasar-enán: este os será el término del norte.",
      "10": "Y por término al oriente os señalaréis desde Hasar-enán hasta Sepham;",
      "11": "Y bajará este término desde Sepham á Ribla, al oriente de Ain: y descenderá el término, y llegará á la costa de la mar de Cinnereth al oriente;",
      "12": "Después descenderá este término al Jordán, y serán sus salidas al mar Salado: esta será vuestra tierra: por sus términos alrededor.",
      "13": "Y mandó Moisés á los hijos de Israel, diciendo: Esta es la tierra que heredaréis por suerte, la cual mandó Jehová que diese á las nueve tribus, y á la media tribu:",
      "14": "Porque la tribu de los hijos de Rubén según las casas de sus padres, y la tribu de los hijos de Gad según las casas de sus padres, y la media tribu de Manasés, han tomado su herencia:",
      "15": "Dos tribus y media tomaron su heredad de esta parte del Jordán de Jericó al oriente, al nacimiento del sol.",
      "16": "Y habló Jehová á Moisés, diciendo:",
      "17": "Estos son los nombres de los varones que os aposesionarán la tierra: Eleazar el sacerdote, y Josué hijo de Nun.",
      "18": "Tomaréis también de cada tribu un príncipe, para dar la posesión de la tierra.",
      "19": "Y estos son los nombres de los varones: De la tribu de Judá, Caleb hijo de Jephone.",
      "20": "Y de la tribu de los hijos de Simeón, Samuel hijo de Ammiud.",
      "21": "De la tribu de Benjamín; Elidad hijo de Chislón.",
      "22": "Y de la tribu de los hijos de Dan, el príncipe Bucci hijo de Jogli.",
      "23": "De los hijos de José: de la tribu de los hijos de Manasés, el príncipe Haniel hijo de Ephod.",
      "24": "Y de la tribu de los hijos de Ephraim, el príncipe Chêmuel hijo de Siphtán.",
      "25": "Y de la tribu de los hijos de Zabulón, el príncipe Elisaphán hijo de Pharnach.",
      "26": "Y de la tribu de los hijos de Issachâr, el príncipe Paltiel hijo de Azan.",
      "27": "Y de la tribu de los hijos de Aser, el príncipe Ahiud hijo de Selomi.",
      "28": "Y de la tribu de los hijos de Nephtalí, el príncipe Pedael hijo de Ammiud.",
      "29": "Estos son á los que mandó Jehová que hiciesen la partición de la herencia á los hijos de Israel en la tierra de Canaán."
    },
    "35": {
      "1": "Y HABLO Jehová á Moisés en los campos de Moab, junto al Jordán de Jericó, diciendo:",
      "2": "Manda á los hijos de Israel, que den á los Levitas de la posesión de su heredad ciudades en que habiten: También daréis á los Levitas ejidos de esas ciudades alrededor de ellas.",
      "3": "Y tendrán ellos las ciudades para habitar, y los ejidos de ellas serán para sus animales, y para sus ganados, y para todas sus bestias.",
      "4": "Y los ejidos de las ciudades que daréis á los Levitas, serán mil codos alrededor, desde el muro de la ciudad para afuera.",
      "5": "Luego mediréis fuera de la ciudad á la parte del oriente dos mil codos, y á la parte del mediodía dos mil codos, y á la parte del occidente dos mil codos, y á la parte del norte dos mil codos, y la ciudad en medio: esto tendrán por los ejidos de las ciudades.",
      "6": "Y de las ciudades que daréis á los Levitas, seis ciudades serán de acogimiento, las cuales daréis para que el homicida se acoja allá: y además de éstas daréis cuarenta y dos ciudades.",
      "7": "Todas las ciudades que daréis á los Levitas serán cuarenta y ocho ciudades; ellas con sus ejidos.",
      "8": "Y las ciudades que diereis de la heredad de los hijos de Israel, del que mucho tomaréis mucho, y del que poco tomaréis poco: cada uno dará de sus ciudades á los Levitas según la posesión que heredará.",
      "9": "Y habló Jehová á Moisés, diciendo:",
      "10": "Habla á los hijos de Israel, y diles: Cuando hubiereis pasado el Jordán á la tierra de Canaán,",
      "11": "Os señalaréis ciudades, ciudades de acogimiento tendréis, donde huya el homicida que hiriere á alguno de muerte por yerro.",
      "12": "Y os serán aquellas ciudades por acogimiento del pariente, y no morirá el homicida hasta que esté á juicio delante de la congregación.",
      "13": "De las ciudades, pues, que daréis, tendréis seis ciudades de acogimiento.",
      "14": "Tres ciudades daréis de esta parte del Jordán, y tres ciudades daréis en la tierra de Canaán; las cuales serán ciudades de acogimiento.",
      "15": "Estas seis ciudades serán para acogimiento á los hijos de Israel, y al peregrino, y al que morare entre ellos, para que huya allá cualquiera que hiriere de muerte á otro por yerro.",
      "16": "Y si con instrumento de hierro lo hiriere y muriere, homicida es; el homicida morirá:",
      "17": "Y si con piedra de mano, de que pueda morir, lo hiriere, y muriere, homicida es; el homicida morirá.",
      "18": "Y si con instrumento de palo de mano, de que pueda morir, lo hiriere, y muriere, homicida es; el homicida morirá.",
      "19": "El pariente del muerto, él matará al homicida: cuando lo encontrare, él le matará.",
      "20": "Y si por odio lo empujó, ó echó sobre él alguna cosa por asechanzas, y muere;",
      "21": "O por enemistad lo hirió con su mano, y murió: el heridor morirá; es homicida; el pariente del muerto matará al homicida, cuando lo encontrare.",
      "22": "Mas si casualmente lo empujó sin enemistades, ó echó sobre él cualquier instrumento sin asechanzas,",
      "23": "O bien, sin verlo, hizo caer sobre él alguna piedra, de que pudo morir, y muriere, y él no era su enemigo, ni procuraba su mal;",
      "24": "Entonces la congregación juzgará entre el heridor y el pariente del muerto conforme á estas leyes:",
      "25": "Y la congregación librará al homicida de mano del pariente del muerto, y la congregación lo hará volver á su ciudad de acogimiento, á la cual se había acogido; y morará en ella hasta que muera el gran sacerdote, el cual fué ungido con el aceite santo.",
      "26": "Y si el homicida saliere fuera del término de su ciudad de refugio, á la cual se acogió,",
      "27": "Y el pariente del muerto le hayare fuera del término de la ciudad de su acogida, y el pariente del muerto al homicida matare, no se le culpará por ello:",
      "28": "Pues en su ciudad de refugio deberá aquél habitar hasta que muera el gran sacerdote: y después que muriere el gran sacerdote, el homicida volverá á la tierra de su posesión.",
      "29": "Y estas cosas os serán por ordenanza de derecho por vuestras edades, en todas vuestras habitaciones.",
      "30": "Cualquiera que hiriere á alguno, por dicho de testigos, morirá el homicida: mas un solo testigo no hará fé contra alguna persona para que muera.",
      "31": "Y no tomaréis precio por la vida del homicida; porque está condenado á muerte: mas indefectiblemente morirá.",
      "32": "Ni tampoco tomaréis precio del que huyó á su ciudad de refugio, para que vuelva á vivir en su tierra, hasta que muera el sacerdote.",
      "33": "Y no contaminaréis la tierra donde estuviereis: porque esta sangre amancillará la tierra: y la tierra no será expiada de la sangre que fué derramada en ella, sino por la sangre del que la derramó.",
      "34": "No contaminéis, pues, la tierra donde habitáis, en medio de la cual yo habito; porque yo Jehová habito en medio de los hijos de Israel."
    },
    "36": {
      "1": "Y LLEGARON los príncipes de los padres de la familia de Galaad, hijo de Machîr, hijo de Manasés, de las familias de los hijos de José; y hablaron delante de Moisés, y de los príncipes, cabezas de padres de los hijos de Israel,",
      "2": "Y dijeron: Jehová mandó á mi señor que por suerte diese la tierra á los hijos de Israel en posesión: también ha mandado Jehová á mi señor, que dé la posesión de Salphaad nuestro hermano á sus hijas;",
      "3": "Las cuales, si se casaren con algunos de los hijos de las otras tribus de los hijos de Israel, la herencia de ellas será así desfalcada de la herencia de nuestros padres, y será añadida á la herencia de la tribu á que serán unidas: y será quitada de la suerte de nuestra heredad.",
      "4": "Y cuando viniere el jubileo de los hijos de Israel, la heredad de ellas será añadida á la heredad de la tribu de sus maridos; y así la heredad de ellas será quitada de la heredad de la tribu de nuestros padres.",
      "5": "Entonces Moisés mandó á los hijos de Israel por dicho de Jehová, diciendo: La tribu de los hijos de José habla rectamente.",
      "6": "Esto es lo que ha mandado Jehová acerca de las hijas de Salphaad, diciendo: Cásense como á ellas les pluguiere, empero en la familia de la tribu de su padre se casarán;",
      "7": "Para que la heredad de los hijos de Israel no sea traspasada de tribu en tribu; porque cada uno de los hijos de Israel se allegará á la heredad de la tribu de sus padres.",
      "8": "Y cualquiera hija que poseyere heredad de las tribus de los hijos de Israel, con alguno de la familia de la tribu de su padre se casará, para que los hijos de Israel posean cada uno la heredad de sus padres.",
      "9": "Y no ande la heredad rodando de una tribu á otra: mas cada una de las tribus de los hijos de Israel se llegue á su heredad.",
      "10": "Como Jehová mandó á Moisés, así hicieron las hijas de Salphaad.",
      "11": "Y así Maala, y Tirsa, y Hogla, y Milchâ, y Noa, hijas de Salphaad, se casaron con hijos de sus tíos:",
      "12": "De la familia de los hijos de Manasés, hijo de José, fueron mujeres; y la heredad de ellas quedó en la tribu de la familia de su padre.",
      "13": "Estos son los mandamientos y los estatutos que mandó Jehová por mano de Moisés á los hijos de Israel en los campos de Moab, junto al Jordán de Jericó."
    }
  },
  "deuteronomy": {
    "1": {
      "1": "ESTAS son las palabras que habló Moisés á todo Israel de esta parte del Jordán en el desierto, en el llano delante del mar Bermejo, entre Parán, y Thopel, y Labán, y Haseroth, y Dizahab.",
      "2": "Once jornadas hay desde Horeb, camino del monte de Seir, hasta Cades-barnea.",
      "3": "Y fué, que á los cuarenta años, en el mes undécimo, al primero del mes, Moisés habló á los hijos de Israel conforme á todas las cosas que Jehová le había mandado acerca de ellos;",
      "4": "Después que hirió á Sehón rey de los Amorrheos, que habitaba en Hesbón, y á Og rey de Basán, que habitaba en Astarot en Edrei:",
      "5": "De esta parte del Jordán, en tierra de Moab, resolvió Moisés declarar esta ley, diciendo:",
      "6": "Jehová nuestro Dios nos habló en Horeb, diciendo: Harto habéis estado en este monte;",
      "7": "Volveos, partíos é id al monte del Amorrheo, y á todas sus comarcas, en el llano, en el monte, y en los valles, y al mediodía, y á la costa de la mar, á la tierra del Cananeo, y el Líbano, hasta el gran río, el río Eufrates.",
      "8": "Mirad, yo he dado la tierra en vuestra presencia; entrad y poseed la tierra que Jehová juró á vuestros padres Abraham, Isaac, y Jacob, que les daría á ellos y á su simiente después de ellos.",
      "9": "Y yo os hablé entonces, diciendo: Yo no puedo llevaros solo:",
      "10": "Jehová vuestro Dios os ha multiplicado, y he aquí sois hoy vosotros como las estrellas del cielo en multitud.",
      "11": "Jehová Dios de vuestros padres añada sobre vosotros como sois mil veces, y os bendiga, como os ha prometido!",
      "12": "¿Cómo llevaré yo solo vuestras molestias, vuestras cargas, y vuestros pleitos?",
      "13": "Dad me de entre vosotros, de vuestras tribus, varones sabios y entendidos y expertos, para que yo los ponga por vuestros jefes.",
      "14": "Y me respondisteis, y dijisteis: Bueno es hacer lo que has dicho.",
      "15": "Y tomé los principales de vuestras tribus, varones sabios y expertos, y púselos por jefes sobre vosotros, jefes de millares, y jefes de cientos, y jefes de cincuenta, y cabos de diez, y gobernadores á vuestras tribus.",
      "16": "Y entonces mandé á vuestros jueces, diciendo: Oid entre vuestros hermanos, y juzgad justamente entre el hombre y su hermano, y el que le es extranjero.",
      "17": "No tengáis respeto de personas en el juicio: así al pequeño como al grande oiréis: no tendréis temor de ninguno, porque el juicio es de Dios: y la causa que os fuere difícil, la traeréis á mí, y yo la oiré.",
      "18": "Os mandé, pues, en aquel tiempo todo lo que habíais de hacer.",
      "19": "Y partidos de Horeb, anduvimos todo aquel grande y terrible desierto que habéis visto, por el camino del monte del Amorrheo, como Jehová nuestro Dios nos lo mandó; y llegamos hasta Cades-barnea.",
      "20": "Entonces os dije: Llegado habéis al monte del Amorrheo, el cual Jehová nuestro Dios nos da.",
      "21": "Mira, Jehová tu Dios ha dado delante de ti la tierra: sube y posée la, como Jehová el Dios de tus padres te ha dicho; no temas ni desmayes.",
      "22": "Y llegasteis á mí todos vosotros, y dijisteis: Enviemos varones delante de nosotros, que nos reconozcan la tierra y nos traigan de vuelta razón del camino por donde hemos de subir, y de las ciudades adonde hemos de llegar.",
      "23": "Y el dicho me pareció bien: y tomé doce varones de vosotros, un varón por tribu:",
      "24": "Y se encaminaron, y subieron al monte, y llegaron hasta la arroyada de Escol, y reconocieron la tierra.",
      "25": "Y tomaron en sus manos del fruto del país, y nos lo trajeron, y diéronnos cuenta, y dijeron: Es buena la tierra que Jehová nuestro Dios nos da.",
      "26": "Empero no quisisteis subir, antes fuisteis rebeldes al dicho de Jehová vuestro Dios;",
      "27": "Y murmurasteis en vuestras tiendas, diciendo: Porque Jehová nos aborrecía, nos ha sacado de tierra de Egipto, para entregarnos en mano del Amorrheo para destruirnos.",
      "28": "¿A dónde subimos? Nuestros hermanos han hecho desfallecer nuestro corazón, diciendo: Este pueblo es mayor y más alto que nosotros, las ciudades grandes y muradas hasta el cielo; y también vimos allí hijos de gigantes.",
      "29": "Entonces os dije: No temáis, ni tengáis miedo de ellos.",
      "30": "Jehová vuestro Dios, el cual va delante de vosotros, él peleará por vosotros, conforme á todas las cosas que hizo por vosotros en Egipto delante de vuestros ojos;",
      "31": "Y en el desierto has visto que Jehová tu Dios te ha traído, como trae el hombre á su hijo, por todo el camino que habéis andado, hasta que habéis venido á este lugar.",
      "32": "Y aun con esto no creisteis en Jehová vuestro Dios,",
      "33": "El cual iba delante de vosotros por el camino, para reconoceros el lugar donde habíais de asentar el campo, con fuego de noche para mostraros el camino por donde aduvieseis, y con nube de día.",
      "34": "Y oyó Jehová la voz de vuestras palabras, y enojóse, y juró diciendo:",
      "35": "No verá hombre alguno de estos de esta mala generación, la buena tierra que juré había de dar á vuestros padres,",
      "36": "Excepto Caleb hijo de Jephone: él la verá, y á él le daré la tierra que pisó, y á sus hijos; porque cumplió en pos de Jehová.",
      "37": "Y también contra mí se airó Jehová por vosotros, diciendo: Tampoco tú entrarás allá:",
      "38": "Josué hijo de Nun, que está delante de ti, él entrará allá: anímale; porque él la hará heredar á Israel.",
      "39": "Y vuestros chiquitos, de los cuales dijisteis serán por presa, y vuestros hijos que no saben hoy bueno ni malo, ellos entrarán allá, y á ellos la daré, y ellos la heredarán.",
      "40": "Y vosotros volveos, y partíos al desierto camino del mar Bermejo.",
      "41": "Entonces respondisteis y me dijisteis: Pecado hemos contra Jehová; nosotros subiremos y pelearemos, conforme á todo lo que Jehová nuestro Dios nos ha mandado. Y os armasteis cada uno de sus armas de guerra, y os apercibisteis para subir al monte.",
      "42": "Y Jehová me dijo: Diles: No subáis, ni peleéis, pues no estoy entre vosotros; porque no seáis heridos delante de vuestros enemigos.",
      "43": "Y os hablé, y no disteis oído; antes fuisteis rebeldes al dicho de Jehová, y persistiendo con altivez, subisteis al monte.",
      "44": "Y salió el Amorrheo, que habitaba en aquel monte, á vuestro encuentro, y os persiguieron, como hacen las avispas, y os derrotaron en Seir, persiguiéndoos hasta Horma.",
      "45": "Y volvisteis, y llorasteis delante de Jehová; pero Jehová no escuchó vuestra voz, ni os prestó oído.",
      "46": "Y estuvisteis en Cades por muchos días, como en los días que habéis estado."
    },
    "2": {
      "1": "Y VOLVIMOS, y partímonos al desierto camino del mar Bermejo, como Jehová me había dicho; y rodeamos el monte de Seir por muchos días.",
      "2": "Y Jehová me habló, diciendo:",
      "3": "Harto habéis rodeado este monte; volveos al aquilón.",
      "4": "Y manda al pueblo, diciendo: Pasando vosotros por el término de vuestros hermanos los hijos de Esaú, que habitan en Seir, ellos tendrán miedo de vosotros; mas vosotros guardaos mucho:",
      "5": "No os metáis con ellos; que no os daré de su tierra ni aun la holladura de la planta de un pie; porque yo he dado por heredad á Esaú el monte de Seir.",
      "6": "Compraréis de ellos por dinero las viandas, y comeréis; y también compraréis de ellos el agua, y beberéis:",
      "7": "Pues Jehová tu Dios te ha bendecido en toda obra de tus manos: él sabe que andas por este gran desierto: estos cuarenta años Jehová tu Dios fué contigo; y ninguna cosa te ha faltado.",
      "8": "Y pasamos de nuestros hermanos los hijos de Esaú, que habitaban en Seir, por el camino de la llanura de Elath y de Esiongeber. Y volvimos, y pasamos camino del desierto de Moab.",
      "9": "Y Jehová me dijo: No molestes á Moab, ni te empeñes con ellos en guerra, que no te daré posesión de su tierra; porque yo he dado á Ar por heredad á los hijos de Lot.",
      "10": "(Los Emimeos habitaron en ella antes, pueblo grande, y numeroso, y alto como fhnumeroso, y alto como fh gigantes:",
      "11": "Por gigantes eran ellos también contados, como los Anaceos; y los Moabitas los llaman Emimeos.",
      "12": "Y en Seir habitaron antes los Horeos, á los cuales echaron los hijos de Esaú; y los destruyeron de delante de sí, y moraron en lugar de ellos; como hizo Israel en la tierra de su posesión que les dió Jehová.)",
      "13": "Levantaos ahora, y pasad el arroyo de Zered. Y pasamos el arroyo de Zered.",
      "14": "Y los días que anduvimos de Cades-barnea hasta que pasamos el arroyo de Zered, fueron treinta y ocho años; hasta que se acabó toda la generación de los hombres de guerra de en medio del campo, como Jehová les había jurado.",
      "15": "Y también la mano de Jehová fué sobre ellos para destruirlos de en medio del campo, hasta acabarlos.",
      "16": "Y aconteció que cuando se hubieron acabado de morir todos los hombres de guerra de entre el pueblo,",
      "17": "Jehová me habló, diciendo:",
      "18": "Tú pasarás hoy el término de Moab, á Ar,",
      "19": "Y te acercarás delante de los hijos de Ammón: no los molestes, ni te metas con ellos; porque no te tengo de dar posesión de la tierra de los hijos de Ammón; que á los hijos de Lot la he dado por heredad.",
      "20": "(Por tierra de gigantes fué también ella tenida: habitaron en ella gigantes en otro tiempo, á los cuales los Ammonitas llamaban Zomzommeos;",
      "21": "Pueblo grande, y numeroso, y alto, como los Anaceos; á los cuales Jehová destruyó de delante de los Ammonitas, quienes les sucedieron, y habitaron en su lugar:",
      "22": "Como hizo con los hijos de Esaú, que habitaban en Seir, de delante de los cuales destruyó á los Horeos; y ellos les sucedieron, y habitaron en su lugar hasta hoy.",
      "23": "Y á los Heveos que habitaban en Haserin hasta Gaza, los Caftoreos que salieron de Caftor los destruyeron, y habitaron en su lugar.)",
      "24": "Levantaos, partid, y pasad el arroyo de Arnón: he aquí he dado en tu mano á Sehón rey de Hesbón, Amorrheo, y á su tierra: comienza á tomar posesión, y empéñate con él en guerra.",
      "25": "Hoy comenzaré á poner tu miedo y tu espanto sobre los pueblos debajo de todo el cielo, los cuales oirán tu fama, y temblarán, y angustiarse han delante de ti.",
      "26": "Y envié mensajeros desde el desierto de Cademoth á Sehón rey de Hesbón, con palabras de paz, diciendo:",
      "27": "Pasaré por tu tierra por el camino: por el camino iré, sin apartarme á diestra ni á siniestra:",
      "28": "La comida me venderás por dinero y comeré: el agua también me darás por dinero, y beberé: solamente pasaré á pie;",
      "29": "Como lo hicieron conmigo los hijos de Esaú que habitaban en Seir, y los Moabitas que habitaban en Ar; hasta que pase el Jordán á la tierra que nos da Jehová nuestro Dios.",
      "30": "Mas Sehón rey de Hesbón no quiso que pasásemos por el territorio suyo; porque Jehová tu Dios había endurecido su espíritu, y obstinado su corazón para entregarlo en tu mano, como hoy.",
      "31": "Y díjome Jehová: He aquí yo he comenzado á dar delante de ti á Sehón y á su tierra; comienza á tomar posesión, para que heredes su tierra.",
      "32": "Y saliónos Sehón al encuentro, él y todo su pueblo, para pelear en Jaas.",
      "33": "Mas Jehová nuestro Dios lo entregó delante de nosotros; y herimos á él y á sus hijos, y á todo su pueblo.",
      "34": "Y tomamos entonces todas sus ciudades, y destruimos todas las ciudades, hombres, y mujeres, y niños; no dejamos ninguno:",
      "35": "Solamente tomamos para nosotros las bestias, y los despojos de las ciudades que habíamos tomado.",
      "36": "Desde Aroer, que está junto á la ribera del arroyo de Arnón, y la ciudad que está en el arroyo, hasta Galaad, no hubo ciudad que escapase de nosotros: todas las entregó Jehová nuestro Dios en nuestro poder.",
      "37": "Solamente á la tierra de los hijos de Ammón no llegaste, ni á todo lo que está á la orilla del arroyo de Jaboc ni á las ciudades del monte, ni á lugar alguno que Jehová nuestro Dios había prohibido."
    }
  }
};

