
	
export const bib_verses = {
  "jeremiah": {
    "6": {
      "1": "HUID, hijos de Benjamín, de en medio de Jerusalem, y tocad bocina en Tecoa, y alzad por señal humo sobre Beth-hacchêrem: porque del aquilón se ha visto mal, y quebrantamiento grande.",
      "2": "A mujer hermosa y delicada comparé á la hija de Sión.",
      "3": "A ella vendrán pastores y sus rebaños; junto á ella en derredor pondrán sus tiendas; cada uno apacentará á su parte.",
      "4": "Denunciad guerra contra ella: levantaos y subamos hacia el mediodía. ­Ay de nosotros! que va cayendo ya el día, que las sombras de la tarde se han extendido.",
      "5": "Levantaos, y subamos de noche, y destruyamos sus palacios.",
      "6": "Porque así dijo Jehová de los ejércitos: Cortad árboles, y extended baluarte junto á Jerusalem: esta es la ciudad que toda ella ha de ser visitada; violencia hay en medio de ella.",
      "7": "Como la fuente nunca cesa de manar sus aguas, así nunca cesa de manar su malicia; injusticia y robo se oye en ella; continuamente en mi presencia, enfermedad y herida.",
      "8": "Corrígete, Jerusalem, porque no se aparte mi alma de ti, porque no te torne desierta, tierra no habitada.",
      "9": "Así dijo Jehová de los ejércitos: Del todo rebuscarán como á vid el resto de Israel: torna tu mano como vendimiador á los cestos.",
      "10": "¿A quién tengo de hablar y amonestar, para que oigan? He aquí que sus orejas son incircuncisas, y no pueden escuchar; he aquí que la palabra de Jehová les es cosa vergonzosa, no la aman.",
      "11": "Por tanto estoy lleno de saña de Jehová, trabajado he por contenerme; derramaréla sobre los niños en la calle, y sobre la reunión de los jóvenes juntamente; porque el marido también será preso con la mujer, el viejo con el lleno de días.",
      "12": "Y sus casas serán traspasadas á otros, sus heredades y también sus mujeres; porque extenderé mi mano sobre los moradores de la tierra, dice Jehová.",
      "13": "Porque desde el más chico de ellos hasta el más grande de ellos, cada uno sigue la avaricia; y desde el profeta hasta el sacerdote, todos son engañadores.",
      "14": "Y curan el quebrantamiento de la hija de mi pueblo con liviandad, diciendo, Paz, paz; y no hay paz.",
      "15": "¿Hanse avergonzado de haber hecho abominación? No por cierto, no se han avergonzado, ni aun saben tener vergüenza: por tanto caerán entre los que caerán; caerán cuando los visitaré, dice Jehová.",
      "16": "Así dijo Jehová: Paraos en los caminos, y mirad, y preguntad por las sendas antiguas, cuál sea el buen camino, y andad por él, y hallaréis descanso para vuestra alma. Mas dijeron: No andaremos.",
      "17": "Desperté también sobre vosotros atalayas, que dijesen: Escuchad á la voz de la trompeta. Y dijeron ellos: No escucharemos.",
      "18": "Por tanto oid, gentes, y conoce, oh conjunto de ellas.",
      "19": "Oye, tierra. He aquí yo traigo mal sobre este pueblo, el fruto de sus pensamientos; porque no escucharon á mis palabras, y aborrecieron mi ley.",
      "20": "¿A qué viene para mí este incienso de Seba, y la buena caña olorosa de tierra lejana? Vuestros holocaustos no son á mi voluntad, ni vuestros sacrificios me dan gusto.",
      "21": "Por tanto Jehová dice esto: He aquí yo pongo á este pueblo tropiezos, y caerán en ellos los padres y los hijos juntamente, el vecino y su cercano perecerán.",
      "22": "Así ha dicho Jehová: He aquí que viene pueblo de tierra del aquilón, y gente grande se levantará de los cantones de la tierra.",
      "23": "Arco y escudo arrebatarán; crueles son, que no tendrán misericordia; sonará la voz de ellos como la mar, y montarán á caballo como hombres dispuestos para la guerra, contra ti, oh hija de Sión.",
      "24": "Su fama oimos, y nuestras manos se descoyuntaron; apoderóse de nosotros angustia, dolor como de mujer que pare.",
      "25": "No salgas al campo, ni andes por camino; porque espada de enemigo y temor hay por todas partes.",
      "26": "Hija de mi pueblo, cíñete de saco, y revuélcate en ceniza; hazte luto como por hijo único, llanto de amarguras: porque presto vendrá sobre nosotros el destruidor.",
      "27": "Por fortaleza te he puesto en mi pueblo, por torre: conocerás pues, y examinarás el camino de ellos.",
      "28": "Todos ellos príncipes rebeldes, andan con engaño; son cobre y hierro: todos ellos son corruptores.",
      "29": "Quemóse el fuelle, del fuego se ha consumido el plomo: por demás fundió el fundidor, pues los malos no son arrancados.",
      "30": "Plata desechada los llamarán, porque Jehová los desechó."
    },
    "7": {
      "1": "PALABRA que fué de Jehová á Jeremías, diciendo:",
      "2": "Ponte á la puerta de la casa de Jehová, y predica allí esta palabra, y di: Oid palabra de Jehová, todo Judá, los que entráis por estas puertas para adorar á Jehová.",
      "3": "Así ha dicho Jehová de los ejércitos, Dios de Israel: Mejorad vuestros caminos y vuestras obras, y os haré morar en este lugar.",
      "4": "No fiéis en palabras de mentira, diciendo: Templo de Jehová, templo de Jehová, templo de Jehová es éste.",
      "5": "Mas si mejorareis cumplidamente vuestros caminos y vuestras obras; si con exactitud hiciereis derecho entre el hombre y su prójimo,",
      "6": "Ni oprimiereis al peregrino, al huérfano, y á la viuda, ni en este lugar derramareis la sangre inocente, ni anduviereis en pos de dioses ajenos para mal vuestro;",
      "7": "Os haré morar en este lugar, en la tierra que dí á vuestros padres para siempre.",
      "8": "He aquí vosotros os confiáis en palabras de mentira, que no aprovechan.",
      "9": "¿Hurtando, matando, y adulterando, y jurando falso, é incensando á Baal, y andando tras dioses extraños que no conocisteis,",
      "10": "Vendréis y os pondréis delante de mí en esta casa sobre la cual es invocado mi nombre, y diréis: Librados somos: para hacer todas estas abominaciones?",
      "11": "¿Es cueva de ladrones delante de vuestros ojos esta casa, sobre la cual es invocado mi nombre? He aquí que también yo veo, dice Jehová.",
      "12": "Andad empero ahora á mi lugar que fué en Silo, donde hice que morase mi nombre al principio, y ved lo que le hice por la maldad de mi pueblo Israel.",
      "13": "Ahora pues, por cuanto habéis vosotros hecho todas estas obras, dice Jehová, y bien que os hablé, madrugando para hablar, no oísteis, y os llamé, y no respondisteis;",
      "14": "Haré también á esta casa sobre la cual es invocado mi nombre, en la que vosotros confiáis, y á este lugar que dí á vosotros y á vuestros padres, como hice á Silo:",
      "15": "Que os echaré de mi presencia como eché á todos vuestros hermanos, á toda la generación de Ephraim.",
      "16": "Tú pues, no ores por este pueblo, ni levantes por ellos clamor ni oración, ni me ruegues; porque no te oiré.",
      "17": "¿No ves lo que estos hacen en las ciudades de Judá y en las calles de Jerusalem?",
      "18": "Los hijos cogen la leña, y los padres encienden el fuego, y las mujeres amasan la masa, para hacer tortas á la reina del cielo y para hacer ofrendas á dioses ajenos, por provocarme á ira.",
      "19": "¿Provocaránme ellos á ira, dice Jehová, y no más bien obran ellos mismos para confusión de sus rostros?",
      "20": "Por tanto, así ha dicho el Señor Jehová: He aquí que mi furor y mi ira se derrama sobre este lugar, sobre los hombres, sobre los animales, sobre los árboles del campo, y sobre los frutos de la tierra; y encenderáse, y no se apagará.",
      "21": "Así ha dicho Jehová de los ejércitos, Dios de Israel: Añadid vuestros holocaustos sobre vuestros sacrificios, y comed carne.",
      "22": "Porque no hablé yo con vuestros padres, ni les mandé el día que los saqué de la tierra de Egipto, acerca de holocaustos y de víctimas:",
      "23": "Mas esto les mandé, diciendo: Escuchad mi voz, y seré á vosotros por Dios, y vosotros me seréis por pueblo; y andad en todo camino que os mandare, para que os vaya bien.",
      "24": "Y no oyeron ni inclinaron su oído; antes caminaron en sus consejos, en la dureza de su corazón malvado, y fueron hacia atrás y no hacia adelante,",
      "25": "Desde el día que vuestros padres salieron de la tierra de Egipto hasta hoy. Y os envié á todos los profetas mis siervos, cada día madrugando y enviándolos:",
      "26": "Mas no me oyeron ni inclinaron su oído; antes endurecieron su cerviz, é hicieron peor que sus padres.",
      "27": "Tú pues les dirás todas estas palabras, mas no te oirán; aun los llamarás, y no te responderán.",
      "28": "Les dirás por tanto: Esta es la gente que no escuchó la voz de Jehová su Dios, ni tomó corrección; perdióse la fe, y de la boca de ellos fué cortada.",
      "29": "Trasquila tu cabello, y arrójalo, y levanta llanto sobre las alturas; porque Jehová ha aborrecido y dejado la nación de su ira.",
      "30": "Porque los hijos de Judá han hecho lo malo ante mis ojos, dice Jehová; pusieron sus abominaciones en la casa sobre la cual mi nombre fué invocado, amancillándola.",
      "31": "Y han edificado los altos de Topheth, que es en el valle del hijo de Hinnom, para quemar al fuego sus hijos y sus hijas, cosa que yo no les mandé, ni subió en mi corazón.",
      "32": "Por tanto, he aquí vendrán días, ha dicho Jehová, que no se diga más, Topheth, ni valle del hijo de Hinnom, sino Valle de la Matanza; y serán enterrados en Topheth, por no haber lugar.",
      "33": "Y serán los cuerpos muertos de este pueblo para comida de las aves del cielo y de las bestias de la tierra; y no habrá quien las espante.",
      "34": "Y haré cesar de las ciudades de Judá, y de la calles de Jerusalem, voz de gozo y voz de alegría, voz de esposo y voz de esposa; porque la tierra será en desolación."
    },
    "8": {
      "1": "EN aquel tiempo, dice Jehová, sacarán los huesos de los reyes de Judá, y los huesos de sus príncipes, y los huesos de los sacerdotes, y los huesos de los profetas, y los huesos de los moradores de Jerusalem, fuera de sus sepulcros;",
      "2": "Y los esparcirán al sol, y á la luna, y á todo el ejército del cielo, á quien amaron, y á quienes sirvieron, y en pos de quienes anduvieron, y á quienes preguntaron, y á quienes se encorvaron. No serán recogidos, ni enterrados: serán por muladar sobre la haz de la tierra.",
      "3": "Y escogeráse la muerte antes que la vida por todo el resto que quedare de esta mala generación, en todos los lugares á donde los arrojaré yo á los que quedaren, dice Jehová de los ejércitos.",
      "4": "Les dirás asimismo: Así ha dicho Jehová: ¿El que cae, no se levanta? ¿el que se desvía, no torna á camino?",
      "5": "¿Por qué es este pueblo de Jerusalem rebelde con rebeldía perpetua? Abrazaron el engaño, no han querido volverse.",
      "6": "Escuché y oí; no hablan derecho, no hay hombre que se arrepienta de su mal, diciendo: ¿Qué he hecho? Cada cual se volvió á su carrera, como caballo que arremete con ímpetu á la batalla.",
      "7": "Aun la cigüeña en el cielo conoce su tiempo, y la tórtola y la grulla y la golondrina guardan el tiempo de su venida; mas mi pueblo no conoce el juicio de Jehová.",
      "8": "¿Cómo decís: Nosotros somos sabios, y la ley de Jehová es con nosotros? Ciertamente, he aquí que en vano se cortó la pluma, por demás fueron los escribas.",
      "9": "Los sabios se avergonzaron, espantáronse y fueron presos: he aquí que aborrecieron la palabra de Jehová; ¿y qué sabiduría tienen?",
      "10": "Por tanto daré á otros sus mujeres, y sus heredades á quien las posea: porque desde el chico hasta el grande cada uno sigue la avaricia, desde el profeta hasta el sacerdote todos hacen engaño.",
      "11": "Y curaron el quebrantamiento de la hija de mi pueblo con liviandad, diciendo: Paz, paz; y no hay paz.",
      "12": "¿Hanse avergonzado de haber hecho abominación? Por cierto no se han corrido de vergüenza, ni supieron avergonzarse; caerán por tanto entre los que cayeren, cuando los visitaré: caerán, dice Jehová.",
      "13": "Cortarélos de por junto, dice Jehová. No habrá uvas en la vid, ni higos en la higuera, y caeráse la hoja; y lo que les he dado pasará de ellos.",
      "14": "¿Sobre qué nos aseguramos? Juntaos, y entrémonos en las ciudades fuertes, y allí reposaremos: porque Jehová nuestro Dios nos ha hecho callar, y dádonos á beber bebida de hiel, porque pecamos contra Jehová.",
      "15": "Esperamos paz, y no hubo bien; día de cura, y he aquí turbación.",
      "16": "Desde Dan se oyó el bufido de sus caballos: del sonido de los relinchos de sus fuertes tembló toda la tierra; y vinieron y devoraron la tierra y su abundancia, ciudad y moradores de ella.",
      "17": "Porque he aquí que yo envío sobre vosotros serpientes, basiliscos, contra los cuales no hay encantamiento; y os morderán, dice Jehová.",
      "18": "A causa de mi fuerte dolor mi corazón desfallece en mí.",
      "19": "He aquí voz del clamor de la hija de mi pueblo, que viene de la tierra lejana: ¿No está Jehová en Sión? ¿no está en ella su Rey? ¿Por qué me hicieron airar con sus imágenes de talla, con vanidades ajenas?",
      "20": "Pasóse la siega, acabóse el verano, y nosotros no hemos sido salvos.",
      "21": "Quebrantado estoy por el quebrantamiento de la hija de mi pueblo; entenebrecido estoy, espanto me ha arrebatado.",
      "22": "¿No hay bálsamo en Galaad? ¿no hay allí médico? ¿Por qué pues no hubo medicina para la hija de mi pueblo?"
    },
    "9": {
      "1": "OH si mi cabeza se tornase aguas, y mis ojos fuentes de aguas, para que llore día y noche los muertos de la hija de mi pueblo!",
      "2": "Oh quién me diese en el desierto un mesón de caminantes, para que dejase mi pueblo, y de ellos me apartase! Porque todos ellos son adúlteros, congregación de prevaricadores.",
      "3": "E hicieron que su lengua, como su arco, tirase mentira; y no se fortalecieron por verdad en la tierra: porque de mal en mal procedieron, y me han desconocido, dice Jehová.",
      "4": "Guárdese cada uno de su compañero, ni en ningún hermano tenga confianza: porque todo hermano engaña con falacia, y todo compañero anda con falsedades.",
      "5": "Y cada uno engaña á su compañero, y no hablan verdad: enseñaron su lengua á hablar mentira, se ocupan de hacer perversamente.",
      "6": "Tu morada es en medio de engaño; de muy engañadores no quisieron conocerme, dice Jehová.",
      "7": "Por tanto, así ha dicho Jehová de los ejércitos: He aquí que yo los fundiré, y los ensayaré; porque ¿cómo he de hacer por la hija de mi pueblo?",
      "8": "Saeta afilada es la lengua de ellos; engaño habla; con su boca habla paz con su amigo, y dentro de sí pone sus asechanzas.",
      "9": "¿No los tengo de visitar sobre estas cosas? dice Jehová. ¿De tal gente no se vengará mi alma?",
      "10": "Sobre los montes levantaré lloro y lamentación, y llanto sobre las moradas del desierto; porque desolados fueron hasta no quedar quien pase, ni oyeron bramido de ganado: desde las aves del cielo y hasta las bestias de la tierra se trasportaron, y se fueron.",
      "11": "Y pondré á Jerusalem en montones, por moradas de culebras; y pondré las ciudades de Judá en asolamiento, que no quede morador.",
      "12": "¿Quién es varón sabio que entienda esto? ¿y á quién habló la boca de Jehová, para que pueda declararlo? ¿Por qué causa la tierra ha perecido, ha sido asolada como desierto, que no hay quien pase?",
      "13": "Y dijo Jehová: Porque dejaron mi ley, la cual dí delante de ellos, y no obedecieron á mi voz, ni caminaron conforme á ella;",
      "14": "Antes se fueron tras la imaginación de su corazón, y en pos de los Baales que les enseñaron sus padres:",
      "15": "Por tanto así ha dicho Jehová de los ejércitos, Dios de Israel: He aquí que á este pueblo yo les daré á comer ajenjos, y les daré á beber aguas de hiel.",
      "16": "Y los esparciré entre gentes que no conocieron ellos ni sus padres; y enviaré espada en pos de ellos, hasta que yo los acabe.",
      "17": "Así dice Jehová de los ejércitos: Considerad, y llamad plañideras que vengan; y enviad por las sabias que vengan:",
      "18": "Y dense prisa, y levanten llanto sobre nosotros, y córranse nuestros ojos en lágrimas, y nuestros párpados en aguas se destilen.",
      "19": "Porque voz de endecha fué oída de Sión: ­Cómo hemos sido destruídos! en gran manera hemos sido confundidos. ¿Por qué dejamos la tierra? ¿por qué nos han echado de sí nuestras moradas?",
      "20": "Oíd pues, oh mujeres, palabra de Jehová, y vuestro oído reciba la palabra de su boca; y enseñad endechas á vuestras hijas, y cada una á su amiga, lamentación.",
      "21": "Porque la muerte ha subido por nuestras ventanas, ha entrado en nuestros palacios; para talar los niños de las calles, los mancebos de las plazas.",
      "22": "Habla: Así ha dicho Jehová: Los cuerpos de los hombres muertos caerán como estiércol sobre la haz del campo, y como manojo tras el segador, que no hay quien lo recoja.",
      "23": "Así dijo Jehová: No se alabe el sabio en su sabiduría, ni en su valentía se alabe el valiente, ni el rico se alabe en sus riquezas.",
      "24": "Mas alábese en esto el que se hubiere de alabar: en entenderme y conocerme, que yo soy Jehová, que hago misericordia, juicio, y justicia en la tierra: porque estas cosas quiero, dice Jehová.",
      "25": "He aquí que vienen días, dice Jehová, y visitaré sobre todo circuncidado, y sobre todo incircunciso:",
      "26": "A Egipto, y á Judá, y á Edom, y á los hijos de Ammón y de Moab, y á todos los arrinconados en el postrer rincón, que moran en el desierto; porque todas las gentes tienen prepucio, y toda la casa de Israel tiene prepucio en el corazón."
    },
    "10": {
      "1": "OID la palabra que Jehová ha hablado sobre vosotros, oh casa de Israel.",
      "2": "Así dijo Jehová: No aprendáis el camino de las gentes, ni de las señales del cielo tengáis temor, aunque las gentes las teman.",
      "3": "Porque las ordenanzas de los pueblos son vanidad: porque leño del monte cortaron, obra de manos de artífice con azuela.",
      "4": "Con plata y oro lo engalanan; con clavos y martillo lo afirman, para que no se salga.",
      "5": "Como palma lo igualan, y no hablan; son llevados, porque no pueden andar. No tengáis temor de ellos; porque ni pueden hacer mal, ni para hacer bien tienen poder.",
      "6": "No hay semejante á tí, oh Jehová; grande tú, y grande tu nombre en fortaleza.",
      "7": "¿Quién no te temerá, oh Rey de las gentes? porque á tí compete ello; porque entre todos los sabios de las gentes, y en todos sus reinos, no hay semejante á ti.",
      "8": "Y todos se infatuarán, y entontecerán. Enseñanza de vanidades es el mismo leño.",
      "9": "Traerán plata extendida de Tarsis, y oro de Uphaz; obrará el artífice, y las manos del fundidor; vestiránlos de cárdeno y de púrpura: obra de peritos es todo.",
      "10": "Mas Jehová Dios es la verdad; él es Dios vivo y Rey eterno: á su ira tiembla la tierra, y las gentes no pueden sufrir su saña.",
      "11": "Les diréis así: Los dioses que no hicieron los cielos ni la tierra, perezcan de la tierra y de debajo de estos cielos.",
      "12": "El que hizo la tierra con su potencia, el que puso en orden el mundo con su saber, y extendió los cielos con su prudencia;",
      "13": "A su voz se da muchedumbre de aguas en el cielo, y hace subir las nubes de lo postrero de la tierra; hace los relámpagos con la lluvia, y saca el viento de sus depósitos.",
      "14": "Todo hombre se embrutece y le falta ciencia; avergüéncese de su vaciadizo todo fundidor: porque mentira es su obra de fundición, y no hay espíritu en ellos;",
      "15": "Vanidad son, obra de escarnios: en el tiempo de su visitación perecerán.",
      "16": "No es como ellos la suerte de Jacob: porque él es el Hacedor de todo, é Israel es la vara de su herencia: Jehová de los ejércitos es su nombre.",
      "17": "Recoge de las tierras tus mercaderías, la que moras en lugar fuerte.",
      "18": "Porque así ha dicho Jehová: He aquí que esta vez arrojaré con honda los moradores de la tierra, y he de afligirlos, para que lo hallen.",
      "19": "Ay de mí, por mi quebrantamiento! mi llaga es muy dolorosa. Yo empero dije: Ciertamente enfermedad mía es esta, y debo sufrirla.",
      "20": "Mi tienda es destruída, y todas mis cuerdas están rotas: mis hijos fueron sacados de mí, y perecieron: no hay ya más quien extienda mi tienda, ni quien levante mis cortinas.",
      "21": "Porque los pastores se infatuaron, y no buscaron á Jehová: por tanto no prosperaron, y todo su ganado se esparció.",
      "22": "He aquí que voz de fama viene, y alboroto grande de la tierra del aquilón, para tornar en soledad todas las ciudades de Judá, en morada de culebras.",
      "23": "Conozco, oh Jehová, que el hombre no es señor de su camino, ni del hombre que camina es ordenar sus pasos.",
      "24": "Castígame, oh Jehová, mas con juicio; no con tu furor, porque no me aniquiles.",
      "25": "Derrama tu enojo sobre las gentes que no te conocen, y sobre las naciones que no invocan tu nombre: porque se comieron á Jacob, y lo devoraron, y le han consumido, y asolado su morada."
    },
    "11": {
      "1": "PALABRA que fué de Jehová, á Jeremías, diciendo:",
      "2": "Oid las palabras de este pacto, y hablad á todo varón de Judá, y á todo morador de Jerusalem.",
      "3": "Y les dirás tú: Así dijo Jehová Dios de Israel: Maldito el varón que no obedeciere las palabras de este pacto,",
      "4": "El cual mandé á vuestros padres el día que los saqué de la tierra de Egipto, del horno de hierro, diciéndoles: Oid mi voz, y ejecutad aquéllas, conforme á todo lo que os mando, y me seréis por pueblo, y yo seré á vosotros por Dios;",
      "5": "Para que confirme el juramento que hice á vuestros padres, que les daría la tierra que corre leche y miel, como este día. Y respondí, y dije: Amén, oh Jehová.",
      "6": "Y Jehová me dijo: Pregona todas estas palabras en las ciudades de Judá y en las calles de Jerusalem, diciendo: Oid las palabras de este pacto, y ponedlas por obra.",
      "7": "Porque con eficacia protesté a vuestros padres el día que los hice subir de la tierra de Egipto hasta el día de hoy, madrugando y protestando, diciendo: Oid mi voz.",
      "8": "Mas no oyeron, ni inclinaron su oído, antes se fueron cada uno tras la imaginación de su corazón malvado: por tanto, traeré sobre ellos todas las palabras de este pacto, el cual mandé que cumpliesen, y no lo cumplieron.",
      "9": "Y díjome Jehová: Conjuración se ha hallado en los varones de Judá, y en los moradores de Jerusalem.",
      "10": "Hanse vuelto á las maldades de sus primeros padres, los cuales no quisieron escuchar mis palabras, antes se fueron tras dioses ajenos para servirles; la casa de Israel y la casa de Judá invalidaron mi pacto, el cual había yo concertado con sus padres.",
      "11": "Por tanto, así ha dicho Jehová: He aquí yo traigo sobre ellos mal del que no podrán salir; y clamarán á mi, y no los oiré.",
      "12": "E irán las ciudades de Judá y los moradores de Jerusalem, y clamarán á los dioses á quienes queman ellos inciensos, los cuales no los podrán salvar en el tiempo de su mal.",
      "13": "Porque según el número de tus ciudades fueron tus dioses, oh Judá; y según el número de tus calles, oh Jerusalem, pusisteis los altares de ignominia, altares para ofrecer sahumerios á Baal.",
      "14": "Tú pues, no ores por este pueblo, ni levantes por ellos clamor ni oración; porque yo no oiré el día que en su aflicción á mí clamaren.",
      "15": "¿Qué tiene mi amado en mi casa, habiendo hecho abominaciones muchas? Y las carnes santas pasarán de sobre tí, porque en tu maldad te gloriaste.",
      "16": "Oliva verde, hermosa en fruto y en parecer, llamó Jehová tu nombre. A la voz de gran palabra hizo encender fuego sobre ella, y quebraron sus ramas.",
      "17": "Pues Jehová de los ejércitos, que te plantó, ha pronunciado mal contra ti, á causa de la maldad de la casa de Israel y de la casa de Judá, que hicieron á sí mismos, provocándome á ira con incensar á Baal.",
      "18": "Y Jehová me lo hizo saber, y conocílo: entonces me hiciste ver sus obras.",
      "19": "Y yo como cordero inocente que llevan á degollar, pues no entendía que maquinaban contra mí designios, diciendo: Destruyamos el árbol con su fruto, y cortémoslo de la tierra de los vivientes, y no haya más memoria de su nombre.",
      "20": "Mas, oh Jehová de los ejércitos, que juzgas justicia, que sondas los riñones y el corazón, vea yo tu venganza de ellos: porque á ti he descubierto mi causa.",
      "21": "Por tanto, así ha dicho Jehová de los varones de Anathoth, que buscan tu alma, diciendo: No profetices en nombre de Jehová, y no morirás á nuestras manos:",
      "22": "Así pues ha dicho Jehová de los ejércitos: He aquí que yo los visito; los mancebos morirán á cuchillo; sus hijos y sus hijas morirán de hambre;",
      "23": "Y no quedará resto de ellos: porque yo traeré mal sobre los varones de Anathoth, año de su visitación."
    },
    "12": {
      "1": "JUSTO eres tú, oh Jehová, aunque yo contigo dispute: hablaré empero juicios contigo. ¿Por qué es prosperado el camino de los impíos, y tienen bien todos los que se portan deslealmente?",
      "2": "Plantástelos, y echaron raíces; progresaron, é hicieron fruto; cercano estás tú en sus bocas, mas lejos de sus riñones.",
      "3": "Tu empero, oh Jehová, me conoces; vísteme, y probaste mi corazón para contigo: arráncalos como á ovejas para el degolladero, y señálalos para el día de la matanza.",
      "4": "¿Hasta cuándo estará desierta la tierra, y marchita la hierba de todo el campo? Por la maldad de los que en ella moran, faltaron los ganados, y las aves; porque dijeron: No verá él nuestras postrimerías.",
      "5": "Si corriste con los de á pié, y te cansaron, ¿cómo contenderás con los caballos? Y si en la tierra de paz estabas quieto, ¿cómo harás en la hinchazón del Jordán?",
      "6": "Porque aun tus hermanos y la casa de tu padre, aun ellos se levantaron contra ti, aun ellos dieron voces en pos de ti. No los creas, cuando bien te hablaren.",
      "7": "He dejado mi casa, desamparé mi heredad, entregado he lo que amaba mi alma en manos de sus enemigos.",
      "8": "Fué para mí mi heredad como león en breña: contra mí dió su voz; por tanto la aborrecí.",
      "9": "¿Esme mi heredad ave de muchos colores? ¿no están contra ella aves en derredor? Venid, reuníos, vosotras todas las bestias del campo, venid á devorarla.",
      "10": "Muchos pastores han destruído mi viña, hollaron mi heredad, tornaron en desierto y soledad mi heredad preciosa.",
      "11": "Fué puesta en asolamiento, y lloró sobre mí, asolada: fué asolada toda la tierra, porque no hubo hombre que mirase.",
      "12": "Sobre todos los lugares altos del desierto vinieron disipadores: porque la espada de Jehová devorará desde el un extremo de la tierra hasta el otro extremo: no habrá paz para ninguna carne.",
      "13": "Sembraron trigo, y segarán espinas; tuvieron la heredad, mas no aprovecharon nada: se avergonzarán de vuestros frutos, á causa de la ardiente ira de Jehová.",
      "14": "Así dijo Jehová contra todos mis malos vecinos, que tocan la heredad que hice poseer á mi pueblo Israel: He aquí que yo los arrancaré de su tierra, y arrancaré de en medio de ellos la casa de Judá.",
      "15": "Y será que, después que los hubiere arrancado, tornaré y tendré misericordia de ellos, y harélos volver cada uno á su heredad, y cada cual á su tierra.",
      "16": "Y será que, si cuidadosamente aprendieren los caminos de mi pueblo, para jurar en mi nombre, diciendo, Vive Jehová, así como enseñaron á mi pueblo á jurar por Baal; ellos serán prosperados en medio de mi pueblo.",
      "17": "Mas si no oyeren, arrancaré á la tal gente, sacándola de raíz, y destruyendo, dice Jehová."
    },
    "13": {
      "1": "ASI me dijo Jehová: Ve, y cómprate un cinto de lino, y cíñelo sobre tus lomos, y no lo meterás en agua.",
      "2": "Y compré el cinto conforme á la palabra de Jehová, y púselo sobre mis lomos.",
      "3": "Y fué á mí segunda vez palabra de Jehová, diciendo:",
      "4": "Toma el cinto que compraste, que está sobre tus lomos, y levántate, y ve al Eufrates, y escóndelo allá en la concavidad de una peña.",
      "5": "Fuí pues, y escondílo junto al Eufrates, como Jehová me mandó.",
      "6": "Y sucedió que al cabo de muchos días me dijo Jehová: Levántate, y ve al Eufrates, y toma de allí el cinto que te mandé escondieses allá.",
      "7": "Entonces fuí al Eufrates, y cavé, y tomé el cinto del lugar donde lo había escondido; y he aquí que el cinto se había podrido; para ninguna cosa era bueno.",
      "8": "Y fué á mí palabra de Jehová, diciendo:",
      "9": "Así ha dicho Jehová: Así haré podrir la soberbia de Judá, y la mucha soberbia de Jerusalem,",
      "10": "A este pueblo malo, que no quieren oir mis palabras, que andan en las imaginaciones de su corazón, y se fueron en pos de dioses ajenos para servirles, y para encorvarse á ellos; y vendrá á ser como este cinto, que para ninguna cosa es bueno.",
      "11": "Porque como el cinto se junta á los lomos del hombre, así hice juntar á mí toda la casa de Israel y toda la casa de Judá, dice Jehová, para que me fuesen por pueblo y por fama, y por alabanza y por honra: empero no escucharon.",
      "12": "Les dirás pues esta palabra: Así ha dicho Jehová, Dios de Israel: Henchiráse de vino todo odre. Y ellos te dirán: ¿No sabemos que todo odre se henchirá de vino?",
      "13": "Entonces les has de decir: Así ha dicho Jehová: He aquí que yo lleno de embriaguez todos los moradores de esta tierra, y á los reyes de la estirpe de David que se sientan sobre su trono, y á los sacerdotes y profetas, y á todos los moradores de Jerusalem;",
      "14": "Y quebrantarélos el uno con el otro, los padres con los hijos juntamente, dice Jehová: no perdonaré, ni tendré piedad ni misericordia, para no destruirlos.",
      "15": "Escuchad y oid; no os elevéis: pues Jehová ha hablado.",
      "16": "Dad gloria á Jehová Dios vuestro, antes que haga venir tinieblas, y antes que vuestros pies tropiecen en montes de oscuridad, y esperéis luz, y os la torne sombra de muerte y tinieblas.",
      "17": "Mas si no oyereis esto, en secreto llorará mi alma á causa de vuestra soberbia; y llorando amargamente, se desharán mis ojos en lágrimas, porque el rebaño de Jehová fué cautivo.",
      "18": "Di al rey y á la reina: Humillaos, sentaos en tierra; porque la corona de vuestra gloria bajó de vuestras cabezas.",
      "19": "Las ciudades del mediodía fueron cerradas, y no hubo quien las abriese: toda Judá fué trasportada, trasportada fué toda ella.",
      "20": "Alzad vuestros ojos, y ved los que vienen del aquilón: ¿dónde está el rebaño que te fué dado, la grey de tu gloria?",
      "21": "¿Qué dirás cuando te visitará? porque tu los enseñaste á ser príncipes y cabeza sobre ti. ¿No te tomarán dolores como á mujer que pare?",
      "22": "Cuando dijeres en tu corazón: ¿Por qué me ha sobrevenido esto? Por la enormidad de tu maldad fueron descubiertas tus faldas, fueron desnudos tus calcañares.",
      "23": "¿Mudará el negro su pellejo, y el leopardo sus manchas? Así también podréis vosotros hacer bien, estando habituados á hacer mal.",
      "24": "Por tanto yo los esparciré, como tamo que pasa, al viento del desierto.",
      "25": "Esta es tu suerte, la porción de tus medidas de parte mía, dice Jehová; porque te olvidaste de mí, y confiaste en la mentira.",
      "26": "Yo pues descubriré también tus faldas delante de tu cara, y se manifestará tu ignominia.",
      "27": "Tus adulterios, tus relinchos, la maldad de tu fornicación sobre los collados: en el mismo campo vi tus abominaciones. ­Ay de ti, Jerusalem! ¿No serás al cabo limpia? ¿hasta cuándo todavía?"
    },
    "14": {
      "1": "PALABRA de Jehová que fué dada á Jeremías, con motivo de la sequía.",
      "2": "Enlutóse Judá, y sus puertas se despoblaron: oscureciéronse en tierra, y subió el clamor de Jerusalem.",
      "3": "Y los principales de ellos enviaron sus criados al agua: vinieron á las lagunas, y no hallaron agua: volviéronse con sus vasos vacíos; se avergonzaron, confundiéronse, y cubrieron sus cabezas.",
      "4": "Porque se resquebrajó la tierra á causa de no llover en el país; confusos los labradores, cubrieron sus cabezas.",
      "5": "Y aun las ciervas en los campos parían, y dejaban la cría, porque no había hierba.",
      "6": "Y los asnos monteses se ponían en los altos, aspiraban el viento como los chacales; sus ojos se ofuscaron, porque no había hierba.",
      "7": "Si nuestras iniquidades testifican contra nosotros, oh Jehová, haz por amor de tu nombre; porque nuestras rebeliones se han multiplicado, contra ti pecamos.",
      "8": "Oh esperanza de Israel, Guardador suyo en el tiempo de la aflicción, ¿por qué has de ser como peregrino en la tierra, y como caminante que se aparta para tener la noche?",
      "9": "¿Por qué has de ser como hombre atónito, y como valiente que no puede librar? tú empero estás entre nosotros, oh Jehová, y sobre nosotros es invocado tu nombre; no nos desampares.",
      "10": "Así ha dicho Jehová á este pueblo: Así amaron moverse, ni detuvieron sus pies: por tanto, Jehová no los tiene en voluntad; acordaráse ahora de la maldad de ellos, y visitará sus pecados.",
      "11": "Y díjome Jehová: No ruegues por este pueblo para bien.",
      "12": "Cuando ayunaren, yo no oiré su clamor, y cuando ofrecieren holocausto y ofrenda, no lo aceptaré; antes los consumiré con cuchillo, y con hambre, y con pestilencia.",
      "13": "Y yo dije: ­Ah! ah! Señor Jehová! he aquí que los profetas les dicen: No veréis cuchillo, ni habrá hambre en vosotros, sino que en este lugar os daré paz verdadera.",
      "14": "Díjome entonces Jehová: Falso profetizan los profetas en mi nombre: no los envié, ni les mandé, ni les hablé: visión mentirosa, y adivinación, y vanidad, y engaño de su corazón os profetizan.",
      "15": "Por tanto así ha dicho Jehová sobre los profetas que profetizan en mi nombre, los cuales yo no envié, y que dicen, Cuchillo ni hambre no habrá en esta tierra: Con cuchillo y con hambre serán consumidos esos profetas.",
      "16": "Y el pueblo á quien profetizan, echado será en las calles de Jerusalem por hambre y por espada; y no habrá quien los entierre, ellos, y sus mujeres, y sus hijos, y sus hijas; y sobre ellos derramaré su maldad.",
      "17": "Decirles has, pues, esta palabra: Córranse mis ojos en lágrimas noche y día, y no cesen; porque de gran quebrantamiento es quebrantada la virgen hija de mi pueblo, de plaga muy recia.",
      "18": "Si salgo al campo, he aquí muertos á cuchillo; y si me entro en la ciudad, he aquí enfermos de hambre: porque también el profeta como el sacerdote anduvieron rodeando en la tierra, y no conocieron.",
      "19": "¿Has desechado enteramente á Judá? ¿ha aborrecido tu alma á Sión? ¿Por qué nos hiciste herir sin que nos quede cura? Esperamos paz, y no hubo bien; tiempo de cura, y he aquí turbación.",
      "20": "Reconocemos, oh Jehová, nuestra impiedad, la iniquidad de nuestros padres: porque contra ti hemos pecado.",
      "21": "Por amor de tu nombre no nos deseches, ni trastornes el trono de tu gloria: acuérdate, no invalides tu pacto con nosotros.",
      "22": "¿Hay entre las vanidades de las gentes quien haga llover? ¿y darán los cielos lluvias? ¿No eres tú, Jehová, nuestro Dios? en ti pues esperamos; pues tú hiciste todas estas cosas."
    },
    "15": {
      "1": "Y DIJOME Jehová: Si Moisés y Samuel se pusieran delante de mí, mi voluntad no será con este pueblo: échalos de delante de mí, y salgan.",
      "2": "Y será que si te preguntaren: ¿A dónde saldremos? les dirás: Así ha dicho Jehová: El que á muerte, á muerte; y el que á cuchillo, á cuchillo; y el que á hambre, á hambre; y el que á cautividad, á cautividad.",
      "3": "Y enviaré sobre ellos cuatro géneros, dice Jehová: cuchillo para matar, y perros para despedazar, y aves del cielo y bestias de la tierra, para devorar y para disipar.",
      "4": "Y entregarélos á ser agitados por todos los reinos de la tierra, á causa de Manasés hijo de Ezechîas rey de Judá, por lo que hizo en Jerusalem.",
      "5": "Porque ¿quién tendrá compasión de ti, oh Jerusalem? ¿ó quién se entristecerá por tu causa? ¿ó quién ha de venir á preguntar por tu paz?",
      "6": "Tú me dejaste, dice Jehová, atrás te volviste: por tanto yo extenderé sobre ti mi mano, y te destruiré; estoy cansado de arrepentirme.",
      "7": "Y aventélos con aventador hasta las puertas de la tierra; desahijé, desbaraté mi pueblo; no se tornaron de sus caminos.",
      "8": "Sus viudas se multiplicaron más que la arena de la mar; traje contra ellos destruidor á medio día sobre la madre y los hijos; sobre la ciudad hice que de repente cayesen terrores.",
      "9": "Enflaquecióse la que parió siete; llenóse de dolor su alma; su sol se le puso siendo aún de día; fué avergonzada y llena de confusión: y lo que de ella quedare, entregarélo á cuchillo delante de sus enemigos, dice Jehová.",
      "10": "Ay de mí, madre mía, que me has engendrado hombre de contienda y hombre de discordia á toda la tierra! Nunca les dí á logro, ni lo tomé de ellos; y todos me maldicen.",
      "11": "Dijo Jehová: De cierto tus reliquias serán en bien; de cierto haré que el enemigo te salga á recibir en el tiempo trabajoso, y en el tiempo de angustia.",
      "12": "¿Quebrará el hierro al hierro de la parte de aquilón, y al bronce?",
      "13": "Tus riquezas y tus tesoros daré á saco sin ningún precio, por todos tus pecados, y en todos tus términos;",
      "14": "Y te haré pasar á tus enemigos en tierra que no conoces: porque fuego se ha encendido en mi furor, y arderá sobre vosotros.",
      "15": "Tú lo sabes, oh Jehová; acuérdate de mí, y visítame, y véngame de mis enemigos. No me tomes en la prolongación de tu enojo: sabes que por amor de ti sufro afrenta.",
      "16": "Halláronse tus palabras, y yo las comí; y tu palabra me fué por gozo y por alegría de mi corazón: porque tu nombre se invocó sobre mí, oh Jehová Dios de los ejércitos.",
      "17": "No me senté en compañia de burladores, ni me engreí á causa de tu profecía; sentéme solo, porque me llenaste de desabrimiento.",
      "18": "¿Por qué fué perpetuo mi dolor, y mi herida desahuciada no admitió cura? ¿Serás para mí como cosa ilusoria, como aguas que no son estables?",
      "19": "Por tanto así dijo Jehová: Si te convirtieres, yo te repondré, y delante de mí estarás; y si sacares lo precioso de lo vil, serás como mi boca. Conviértanse ellos á ti, y tú no te conviertas á ellos.",
      "20": "Y te daré para este pueblo por fuerte muro de bronce, y pelearán contra ti, y no te vencerán: porque yo estoy contigo para guardarte y para defenderte, dice Jehová.",
      "21": "Y librarte he de la mano de los malos, y te redimiré de la mano de los fuertes."
    },
    "16": {
      "1": "Y FUÉ á mí palabra de Jehová, diciendo:",
      "2": "No tomarás para ti mujer, ni tendrás hijos ni hijas en este lugar.",
      "3": "Porque así ha dicho Jehová acerca de los hijos y de las hijas que nacieren en este lugar, y de sus madres que los parieren, y de los padres que los engendraren en esta tierra.",
      "4": "De dolorosas enfermedades morirán; no serán plañidos ni enterrados: serán por muladar sobre la haz de la tierra: y con cuchillo y con hambre serán consumidos, y sus cuerpos serán para comida de las aves del cielo y de las bestias de la tierra.",
      "5": "Porque así ha dicho Jehová: No entres en casa de luto, ni vayas á lamentar, ni los consueles: porque yo he quitado mi paz de este pueblo, dice Jehová, mi misericordia y piedades.",
      "6": "Y morirán en esta tierra grandes y chicos: no se enterrarán, ni los plañirán, ni se arañarán, ni se mesarán por ellos;",
      "7": "Ni por ellos partirán pan por luto, para consolarlos de sus muertos; ni les darán á beber vaso de consolaciones por su padre ó por su madre.",
      "8": "Asimismo no entres en casa de convite, para sentarte con ellos á comer ó á beber.",
      "9": "Porque así ha dicho Jehová de los ejércitos, Dios de Israel: He aquí que yo haré cesar en este lugar, delante de vuestros ojos y en vuestros días, toda voz de gozo y toda voz de alegría, toda voz de esposo y toda voz de esposa.",
      "10": "Y acontecerá que cuando anunciares á este pueblo todas estas cosas, te dirán ellos: ¿Por qué habló Jehová sobre nosotros este mal tan grande? ¿y qué maldad es la nuestra, ó qué pecado es el nuestro, que cometiéramos contra Jehová nuestro Dios?",
      "11": "Entonces les dirás: Porque vuestros padres me dejaron, dice Jehová, y anduvieron en pos de dioses ajenos, y los sirvieron, y á ellos se encorvaron, y me dejaron á mí, y no guardaron mi ley;",
      "12": "Y vosotros habéis hecho peor que vuestros padres; porque he aquí que vosotros camináis cada uno tras la imaginación de su malvado corazón, no oyéndome á mí.",
      "13": "Por tanto, yo os haré echar de esta tierra á tierra que ni vosotros ni vuestros padres habéis conocido, y allá serviréis á dioses ajenos de día y de noche; porque no os mostraré clemencia.",
      "14": "Empero he aquí, vienen días, dice Jehová, que no se dirá más: Vive Jehová, que hizo subir á los hijos de Israel de tierra de Egipto;",
      "15": "Sino: Vive Jehová, que hizo subir á los hijos de Israel de la tierra del aquilón, y de todas las tierras á donde los había arrojado: y volverélos á su tierra, la cual dí á sus padres.",
      "16": "He aquí que yo envío muchos pescadores, dice Jehová, y los pescarán; y después enviaré muchos cazadores, y los cazarán de todo monte, y de todo collado, y de las cavernas de los peñascos.",
      "17": "Porque mis ojos están sobre todos sus caminos, los cuales no se me ocultaron, ni su maldad se esconde de la presencia de mis ojos.",
      "18": "Mas primero pagaré al doble su iniquidad y su pecado; porque contaminaron mi tierra con los cuerpos muertos de sus abominaciones, y de sus abominaciones llenaron mi heredad.",
      "19": "Oh Jehová, fortaleza mía, y fuerza mía, y refugio mío en el tiempo de la aflicción; á ti vendrán gentes desde los extremos de la tierra, y dirán: Ciertamente mentira poseyeron nuestros padres, vanidad, y no hay en ellos provecho.",
      "20": "¿Ha de hacer el hombre dioses para sí? mas ellos no son dioses.",
      "21": "Por tanto, he aquí, les enseñaré de esta vez, enseñarles he mi mano y mi fortaleza, y sabrán que mi nombre es Jehová."
    },
    "17": {
      "1": "EL pecado de Judá escrito está con cincel de hierro, y con punta de diamante: esculpido está en la tabla de su corazón, y en los lados de vuestros altares;",
      "2": "Cuando sus hijos se acuerdan de sus altares y de sus bosques, junto á los árboles verdes y en los collados altos.",
      "3": "Oh mi montaña! tu hacienda en el campo y todos tus tesoros daré á saco, por el pecado de tus altos en todos tus términos.",
      "4": "Y habrá en ti cesación de tu heredad, la cual yo te dí, y te haré servir á tus enemigos en tierra que no conociste; porque fuego habéis encendido en mi furor, para siempre arderá.",
      "5": "Así ha dicho Jehová: Maldito el varón que confía en el hombre, y pone carne por su brazo, y su corazón se aparta de Jehová.",
      "6": "Pues será como la retama en el desierto, y no verá cuando viniere el bien; sino que morará en las securas en el desierto, en tierra despoblada y deshabitada.",
      "7": "Bendito el varón que se fía en Jehová, y cuya confianza es Jehová.",
      "8": "Porque él será como el árbol plantado junto á las aguas, que junto á la corriente echará sus raices, y no verá cuando viniere el calor, sino que su hoja estará verde; y en el año de sequía no se fatigará, ni dejará de hacer fruto.",
      "9": "Engañoso es el corazón más que todas las cosas, y perverso; ¿quién lo conocerá?",
      "10": "Yo Jehová, que escudriño el corazón, que pruebo los riñones, para dar á cada uno según su camino, según el fruto de sus obras.",
      "11": "Como la perdiz que cubre lo que no puso, es el que allega riquezas, y no con justicia; en medio de sus días las dejará, y en su postrimería será insipiente.",
      "12": "Trono de gloria, excelso desde el principio, es el lugar de nuestro santuario.",
      "13": "Oh Jehová, esperanza de Israel! todos los que te dejan, serán avergonzados; y los que de mí se apartan, serán escritos en el polvo; porque dejaron la vena de aguas vivas, á Jehová.",
      "14": "Sáname, oh Jehová, y seré sano; sálvame, y seré salvo: porque tú eres mi alabanza.",
      "15": "He aquí que ellos me dicen: ¿Dónde está la palabra de Jehová? venga ahora.",
      "16": "Mas yo no me entrometí á ser pastor en pos de ti, ni deseé día de calamidad, tú lo sabes. Lo que de mi boca ha salido, fué en tu presencia.",
      "17": "No me seas tú por espanto: esperanza mía eres tú en el día malo.",
      "18": "Avergüéncense los que me persiguen, y no me avergüence yo; asómbrense ellos, y yo no me asombre: trae sobre ellos día malo, y quebrántalos con doble quebrantamiento.",
      "19": "Así me ha dicho Jehová: Ve, y ponte á la puerta de los hijos del pueblo, por la cual entran y salen los reyes de Judá, y á todas las puertas de Jerusalem,",
      "20": "Y diles: Oid la palabra de Jehová, reyes de Judá, y todo Judá, y todos los moradores de Jerusalem que entráis por esta puertas.",
      "21": "Así ha dicho Jehová: Guardaos por vuestras vidas, y no traigáis carga en el día del sábado, para meter por las puertas de Jerusalem;",
      "22": "Ni saquéis carga de vuestras casas en el día del sábado, ni hagáis obra alguna: mas santificad el día del sábado, como mandé á vuestros padres;",
      "23": "Mas ellos no oyeron, ni inclinaron su oído, antes endurecieron su cerviz, por no oir, ni recibir corrección.",
      "24": "Será empero, si vosotros me obedeciereis, dice Jehová, no metiendo carga por las puertas de esta ciudad en el día del sábado, sino que santificaréis el día del sábado, no haciendo en él ninguna obra;",
      "25": "Que entrarán por las puertas de esta ciudad, en carros y en caballos, los reyes y los príncipes que se sientan sobre el trono de David, ellos y sus príncipes, los varones de Judá, y los moradores de Jerusalem: y esta ciudad será habitada para siempre.",
      "26": "Y vendrán de las ciudades de Judá, y de los alrededores de Jerusalem, y de tierra de Benjamín, y de los campos, y del monte, y del austro, trayendo holocausto y sacrificio, y ofrenda é incienso, y trayendo sacrificio de alabanza á la casa de Jehová.",
      "27": "Mas si no me oyereis para santificar el día del sábado, y para no traer carga ni meterla por las puertas de Jerusalem en día de sábado, yo haré encender fuego en sus puertas, y consumirá los palacios de Jerusalem, y no se apagará."
    },
    "18": {
      "1": "LA palabra que fué á Jeremías de Jehová, diciendo:",
      "2": "Levántate, y vete á casa del alfarero, y allí te haré oir mis palabras.",
      "3": "Y descendí á casa del alfarero, y he aquí que él hacía obra sobre la rueda.",
      "4": "Y el vaso que él hacía de barro se quebró en la mano del alfarero; y tornó é hízolo otro vaso, según que al alfarero pareció mejor hacerlo.",
      "5": "Entonces fué á mí palabra de Jehová, diciendo:",
      "6": "¿No podré yo hacer de vosotros como este alfarero, oh casa de Israel, dice Jehová? He aquí que como el barro en la mano del alfarero, así sois vosotros en mi mano, oh casa de Israel.",
      "7": "En un instante hablaré contra gentes y contra reinos, para arrancar, y disipar, y destruir.",
      "8": "Empero si esas gentes se convirtieren de su maldad, de que habré hablado, yo me arrepentiré del mal que había pensado hacerles.",
      "9": "Y en un instante hablaré de la gente y del reino, para edificar y para plantar;",
      "10": "Pero si hiciere lo malo delante de mis ojos, no oyendo mi voz, arrepentiréme del bien que había determinado hacerle.",
      "11": "Ahora pues habla luego á todo hombre de Judá, y á los moradores de Jerusalem, diciendo: Así ha dicho Jehová: He aquí que yo dispongo mal contra vosotros, y trazo contra vosotros designios: conviértase ahora cada uno de su mal camino, y mejorad vuestros caminos y vuestras obras.",
      "12": "Y dijeron: Es por demás: porque en pos de nuestras imaginaciones hemos de ir, y hemos de hacer cada uno el pensamiento de su malvado corazón.",
      "13": "Por tanto, así dijo Jehová: Preguntad ahora á las gentes, quién tal haya oído. Gran fealdad ha hecho la virgen de Israel.",
      "14": "¿Faltará la nieve del Líbano de la piedra del campo? ¿faltarán las aguas frías que corren de lejanas tierras?",
      "15": "Porque mi pueblo me ha olvidado, incensando á la vanidad, y hácenles tropezar en sus caminos, en las sendas antiguas, para que caminen por sendas, por camino no hollado;",
      "16": "Para poner su tierra en desolación, y en silbos perpetuos; todo aquel que pasare por ella se maravillará, y meneará su cabeza.",
      "17": "Como viento solano los esparciré delante del enemigo; mostraréles las espaldas, y no el rostro, en el día de su perdición.",
      "18": "Y dijeron: Venid, y tracemos maquinaciones contra Jeremías; porque la ley no faltará del sacerdote, ni consejo del sabio, ni palabra del profeta. Venid é hirámoslo de lengua, y no miremos á todas sus palabras.",
      "19": "Oh Jehová, mira por mí, y oye la voz de los que contienden conmigo.",
      "20": "¿Dase mal por bien para que hayan cavado hoyo á mi alma? Acuérdate que me puse delante de ti para hablar bien por ellos, para apartar de ellos tu ira.",
      "21": "Por tanto, entrega sus hijos á hambre, y hazlos derramar por medio de la espada; y queden sus mujeres sin hijos, y viudas; y sus maridos sean puestos á muerte, y sus jóvenes heridos á cuchillo en la guerra.",
      "22": "Oigase clamor de sus casas, cuando trajeres sobre ellos ejército de repente: porque cavaron hoyo para prenderme, y á mis pies han escondido lazos.",
      "23": "Mas tú, oh Jehová, conoces todo su consejo contra mí para muerte; no perdones su maldad, ni borres su pecado de delante de tu rostro: y tropiecen delante de ti; haz así con ellos en el tiempo de tu furor."
    },
    "19": {
      "1": "ASI dijo Jehová: Ve, y compra una vasija de barro de alfarero, y lleva contigo de los ancianos del pueblo, y de los ancianos de los sacerdotes;",
      "2": "Y saldrás al valle del hijo de Hinnom, que está á la entrada de la puerta oriental, y publicarás allí las palabras que yo te hablaré.",
      "3": "Dirás pues: Oid palabra de Jehová, oh reyes de Judá, y moradores de Jerusalem. Así dice Jehová de los ejércitos, Dios de Israel: He aquí que yo traigo mal sobre este lugar, tal que quien lo oyere, le retiñan los oídos.",
      "4": "Porque me dejaron, y enajenaron este lugar, y ofrecieron en él perfumes á dioses ajenos, los cuales no habían ellos conocido, ni sus padres, ni los reyes de Judá; y llenaron este lugar de sangre de inocentes;",
      "5": "Y edificaron alto á Baal, para quemar con fuego sus hijos en holocaustos al mismo Baal; cosa que no les mandé, ni hablé, ni me vino al pensamiento.",
      "6": "Por tanto, he aquí vienen días, dice Jehová, que este lugar no se llamará más Topheth, ni Valle del hijo de Hinnom, sino Valle de la Matanza.",
      "7": "Y desvaneceré el consejo de Judá y de Jerusalem en este lugar; y haréles caer á cuchillo delante de sus enemigos, y en las manos de los que buscan sus almas; y daré sus cuerpos para comida de las aves del cielo y de las bestias de la tierra:",
      "8": "Y pondré á esta ciudad por espanto y silbo: todo aquel que pasare por ella se maravillará, y silbará sobre todas sus plagas.",
      "9": "Y haréles comer la carne de sus hijos y la carne de sus hijas; y cada uno comerá la carne de su amigo, en el cerco y en el apuro con que los estrecharán sus enemigos y los que buscan sus almas.",
      "10": "Y quebrarás la vasija ante los ojos de los varones que van contigo,",
      "11": "Y les dirás: Así ha dicho Jehová de los ejércitos: Así quebrantaré á este pueblo y á esta ciudad, como quien quiebra un vaso de barro, que no puede más restaurarse; y en Topheth se enterrarán, porque no habrá otro lugar para enterrar.",
      "12": "Así haré á este lugar, dice Jehová, y á sus moradores, poniendo esta ciudad como Topheth.",
      "13": "Y las casas de Jerusalem, y las casas de los reyes de Judá, serán como el lugar de Topheth inmundas, por todas las casas sobre cuyos tejados ofrecieron perfumes á todo el ejército del cielo, y vertieron libaciones á dioses ajenos.",
      "14": "Y volvió Jeremías de Topheth, á donde le envió Jehová á profetizar, y paróse en el atrio de la casa de Jehová, y dijo á todo el pueblo.",
      "15": "Así ha dicho Jehová de los ejércitos, Dios de Israel: He aquí yo traigo sobre esta ciudad y sobre todas sus villas todo el mal que hablé contra ella: porque han endurecido su cerviz, para no oir mis palabras."
    },
    "20": {
      "1": "Y PASHUR sacerdote, hijo de Immer, que presidía por príncipe en la casa de Jehová, oyó á Jeremías que profetizaba estas palabras.",
      "2": "E hirió Pashur á Jeremías profeta, y púsole en el cepo que estaba á la puerta de Benjamín en lo alto, la cual conducía á la casa de Jehová.",
      "3": "Y el día siguiente Pashur sacó á Jeremías del cepo. Díjole entonces Jeremías: Jehová no ha llamado tu nombre Pashur, sino Magormissabib.",
      "4": "Porque así ha dicho Jehová: He aquí yo te pondré en espanto á ti, y á todos los que bien te quieren, y caerán por el cuchillo de sus enemigos, y tus ojos lo verán: y á todo Judá entregaré en mano del rey de Babilonia, y los trasportará á Babilonia, y herirálos á cuchillo.",
      "5": "Entregaré asimismo toda la sustancia de esta ciudad, y todo su trabajo, y todas sus cosas preciosas; y daré todos los tesoros de los reyes de Judá en manos de sus enemigos, y los saquearán, y los tomarán, y llevaránlos á Babilonia.",
      "6": "Y tú, Pashur, y todos los moradores de tu casa iréis cautivos, y entrarás en Babilonia, y allí morirás, y serás allá enterrado, tu, y todos los que bien te quieren, á los cuales has profetizado con mentira.",
      "7": "Alucinásteme, oh Jehová, y hállome frustrado: más fuerte fuiste que yo, y vencísteme: cada día he sido escarnecido; cada cual se burla de mí.",
      "8": "Porque desde que hablo, doy voces, grito, Violencia y destrucción: porque la palabra de Jehová me ha sido para afrenta y escarnio cada día.",
      "9": "Y dije: No me acordaré más de él, ni hablaré más en su nombre: empero fué en mi corazón como un fuego ardiente metido en mis huesos, trabajé por sufrirlo, y no pude.",
      "10": "Porque oí la murmuración de muchos, temor de todas partes: Denunciad, y denunciaremos. Todos mis amigos miraban si claudicaría. Quizá se engañará, decían, y prevaleceremos contra él, y tomaremos de él nuestra venganza.",
      "11": "Mas Jehová está conmigo como poderoso gigante; por tanto los que me persiguen tropezarán, y no prevalecerán; serán avergonzados en gran manera, porque no prosperarán; tendrán perpetua confusión que jamás será olvidada.",
      "12": "Oh Jehová de los ejércitos, que sondas los justos, que ves los riñones y el corazón, vea yo tu venganza de ellos; porque á ti he descubierto mi causa.",
      "13": "Cantad á Jehová, load á Jehová: porque librado ha el alma del pobre de mano de los malignos.",
      "14": "Maldito el día en que nací: el día en que mi madre me parió no sea bendito.",
      "15": "Maldito el hombre que dió nuevas á mi padre, diciendo, Hijo varón te ha nacido, haciéndole alegrarse así mucho.",
      "16": "Y sea el tal hombre como las ciudades que asoló Jehová, y no se arrepintió: y oiga gritos de mañana, y voces al medio día;",
      "17": "Porque no me mató en el vientre, y mi madre me hubiera sido mi sepulcro, y su vientre concebimiento perpetuo.",
      "18": "¿Para qué salí del vientre? ¿para ver trabajo y dolor, y que mis días se gastasen en afrenta?"
    },
    "21": {
      "1": "PALABRA que fué á Jeremías de Jehová, cuando el rey Sedechîas envió á él á Pashur hijo de Malchîas, y á Sephanías sacerdote, hijo de Maasías, que le dijesen:",
      "2": "Pregunta ahora por nosotros á Jehová; porque Nabucodonosor rey de Babilonia hace guerra contra nosotros: quizá Jehová hará con nosotros según todas sus maravillas, y aquél se irá de sobre nosotros.",
      "3": "Y Jeremías les dijo: Diréis así á Sedechîas:",
      "4": "Así ha dicho Jehová Dios de Israel: He aquí yo vuelvo las armas de guerra que están en vuestras manos, y con que vosotros peleáis con el rey de Babilonia; y los Caldeos que os tienen cercados fuera de la muralla, yo los juntaré en medio de esta ciudad.",
      "5": "Y pelearé contra vosotros con mano alzada y con brazo fuerte, y con furor, y enojo, é ira grande:",
      "6": "Y heriré los moradores de esta ciudad; y los hombres y las bestias morirán de pestilencia grande.",
      "7": "Y después, así dice Jehová, entregaré á Sedechîas rey de Judá, y á sus criados, y al pueblo, y á los que quedaren en la ciudad de la pestilencia, y del cuchillo, y del hambre, en mano de Nabucodonosor rey de Babilonia, y en mano de sus enemigos, y en mano de los que buscan sus almas; y él los herirá á filo de espada; no los perdonará, ni los recibirá á merced, ni tendrá de ellos misericordia.",
      "8": "Y á este pueblo dirás: Así ha dicho Jehová: He aquí pongo delante de vosotros camino de vida y camino de muerte.",
      "9": "El que se quedare en esta ciudad, morirá á cuchillo, ó de hambre, ó pestilencia: mas el que saliere, y se pasare á los Caldeos que os tienen cercados, vivirá, y su vida le será por despojo.",
      "10": "Porque mi rostro he puesto contra esta ciudad para mal, y no para bien, dice Jehová: en mano del rey de Babilonia será entregada, y quemarála á fuego.",
      "11": "Y á la casa del rey de Judá dirás: Oid palabra de Jehová.",
      "12": "Casa de David, así dijo Jehová: Juzgad de mañana juicio, y librad al oprimido de mano del opresor; porque mi ira no salga como fuego, y se encienda, y no haya quien apague, por la maldad de vuestras obras.",
      "13": "He aquí yo contra ti, moradora del valle de la piedra de la llanura, dice Jehová: los que decís: ¿Quién subirá contra nosotros? ¿y quién entrará en nuestras moradas?",
      "14": "Yo os visitaré conforme al fruto de vuestras obras, dice Jehová, y haré encender fuego en su breña, y consumirá todo lo que está alrededor de ella."
    },
    "22": {
      "1": "ASI dijo Jehová: Desciende á la casa del rey de Judá, y habla allí esta palabra,",
      "2": "Y di: Oye palabra de Jehová, oh rey de Judá que estás sentado sobre el trono de David, tú, y tus criados, y tu pueblo que entran por estas puertas.",
      "3": "Así ha dicho Jehová: Haced juicio y justicia, y librad al oprimido de mano del opresor, y no engañéis, ni robéis al extranjero, ni al huérfano, ni á la viuda, ni derraméis sangre inocente en este lugar.",
      "4": "Porque si efectivamente hiciereis esta palabra, los reyes que en lugar de David se sientan sobre su trono, entrarán montados en carros y en caballos por las puertas de esta casa, ellos, y sus criados, y su pueblo.",
      "5": "Mas si no oyereis estas palabras, por mí he jurado, dice Jehová, que esta casa será desierta.",
      "6": "Porque así ha dicho Jehová sobre la casa del rey de Judá: Galaad eres tú para mí, y cabeza del Líbano: empero de cierto te pondré en soledad, y ciudades deshabitadas.",
      "7": "Y señalaré contra ti disipadores, cada uno con sus armas; y cortarán tus cedros escogidos, y los echarán en el fuego.",
      "8": "Y muchas gentes pasarán junto á esta ciudad, y dirán cada uno á su compañero: ¿Por qué lo hizo así Jehová con esta grande ciudad?",
      "9": "Y dirán: Porque dejaron el pacto de Jehová su Dios, y adoraron dioses ajenos, y les sirvieron.",
      "10": "No lloréis al muerto, ni de él os condolezcáis: llorad amargamente por el que va; porque no volverá jamás, ni verá la tierra donde nació.",
      "11": "Porque así ha dicho Jehová, de Sallum hijo de Josías, rey de Judá, que reina por Josías su padre, que salió de este lugar: No volverá acá más;",
      "12": "Antes morirá en el lugar adonde lo trasportaren, y no verá más esta tierra.",
      "13": "Ay del que edifica su casa y no en justicia, y sus salas y no en juicio, sirviéndose de su prójimo de balde, y no dándole el salario de su trabajo!",
      "14": "Que dice: Edificaré para mí casa espaciosa, y airosas salas; y le abre ventanas, y la cubre de cedro, y la pinta de bermellón.",
      "15": "¿Reinarás porque te cercas de cedro? ¿no comió y bebío tu padre, é hizo juicio y justicia, y entonces le fué bien?",
      "16": "El juzgó la causa del afligido y del menesteroso, y entonces estuvo bien. ¿No es esto conocerme á mí? dice Jehová.",
      "17": "Mas tus ojos y tu corazón no son sino á tu avaricia, y á derramar la sangre inocente, y á opresión, y á hacer agravio.",
      "18": "Por tanto así ha dicho Jehová, de Joacim hijo de Josías, rey de Judá: No lo llorarán, diciendo: ­Ay hermano mío! y ­ay hermana! ni lo lamentarán, diciendo: ­Ay señor! ­ay su grandeza!",
      "19": "En sepultura de asno será enterrado, arrastrándole y echándole fuera de las puertas de Jerusalem.",
      "20": "Sube al Líbano, y clama, y en Basán da tu voz, y grita hacia todas partes; porque todos tus enamorados son quebrantados.",
      "21": "Hete hablado en tus prosperidades; mas dijiste: No oiré. Este fué tu camino desde tu juventud, que nunca oiste mi voz.",
      "22": "A todos tus pastores pacerá el viento, y tus enamorados irán en cautiverio: entonces te avergonzarás y te confundirás á causa de toda tu malicia.",
      "23": "Habitaste en el Líbano, hiciste tu nido en los cedros: ­cómo gemirás cuando te vinieren dolores, dolor como de mujer que está de parto!",
      "24": "Vivo yo, dice Jehová, que si Conías hijo de Joacím rey de Judá fuese anillo en mi mano diestra, aun de allí te arrancaré;",
      "25": "Y te entregaré en mano de los que buscan tu alma, y en mano de aquellos cuya vista temes; sí, en mano de Nabucodonosor rey de Babilonia, y en mano de los Caldeos.",
      "26": "Y hacerte he trasportar, á ti, y á tu madre que te parió, á tierra ajena en que no nacisteis; y allá moriréis.",
      "27": "Y á la tierra á la cual levantan ellos su alma para tornar, allá no volverán.",
      "28": "¿Es este hombre Conías un ídolo vil quebrado? ¿es vaso con quien nadie se deleita? ¿Por qué fueron arrojados, él y su generación, y echados á tierra que no habían conocido?",
      "29": "Tierra, tierra, tierra! oye palabra de Jehová.",
      "30": "Así ha dicho Jehová: Escribid que será este hombre privado de generación, hombre á quien nada sucederá prósperamente en todos los días de su vida: porque ningún hombre de su simiente que se sentare sobre el trono de David, y que se enseñoreare sobre Judá, será jamás dichoso."
    },
    "23": {
      "1": "AY de los pastores que desperdician y derraman las ovejas de mi majada! dice Jehová.",
      "2": "Por tanto, así ha dicho Jehová Dios de Israel á los pastores que apacientan mi pueblo: Vosotros derramasteis mis ovejas, y las espantasteis, y no las habéis visitado: he aquí yo visito sobre vosotros la maldad de vuestras obras, dice Jehová.",
      "3": "Y yo recogeré el resto de mis ovejas de todas las tierras adonde las eché, y harélas volver á sus moradas; y crecerán, y se multiplicarán.",
      "4": "Y pondré sobre ellas pastores que las apacienten; y no temerán más, ni se asombrarán, ni serán menoscabadas, dice Jehová.",
      "5": "He aquí que vienen los días, dice Jehová, y despertaré á David renuevo justo, y reinará Rey, el cual será dichoso, y hará juicio y justicia en la tierra.",
      "6": "En sus días será salvo Judá, é Israel habitará confiado: y este será su nombre que le llamarán: JEHOVA, JUSTICIA NUESTRA.",
      "7": "Por tanto, he aquí que vienen días, dice Jehová, y no dirán más: Vive Jehová que hizo subir los hijos de Israel de la tierra de Egipto;",
      "8": "Sino: Vive Jehová que hizo subir y trajo la simiente de la casa de Israel de tierra del aquilón, y de todas las tierras adonde los había yo echado; y habitarán en su tierra.",
      "9": "A causa de los profetas mi corazón está quebrantado en medio de mí, todos mis huesos tiemblan; estuve como hombre borracho, y como hombre á quien dominó el vino, delante de Jehová y delante de las palabras de su santidad.",
      "10": "Porque la tierra está llena de adúlteros: porque á causa del juramento la tierra está desierta; las cabañas del desierto se secaron; la carrera de ellos fué mala, y su fortaleza no derecha.",
      "11": "Porque así el profeta como el sacerdote son fingidos: aun en mi casa hallé su maldad, dice Jehová.",
      "12": "Por tanto, como resbaladeros en oscuridad les será su camino: serán empujados, y caerán en él: porque yo traeré mal sobre ellos, año de su visitación, dice Jehová.",
      "13": "Y en los profetas de Samaria he visto desatinos: profetizaban en Baal, é hicieron errar á mi pueblo Israel.",
      "14": "Y en los profetas de Jerusalem he visto torpezas: cometían adulterios, y andaban en mentiras, y esforzaban las manos de los malos, para que ninguno se convirtiese de su malicia: fuéronme todos ellos como Sodoma, y sus moradores como Gomorra.",
      "15": "Por tanto, así ha dicho Jehová de los ejércitos contra aquellos profetas: He aquí que yo les hago comer ajenjos, y les haré beber aguas de hiel; porque de los profetas de Jerusalem salió la hipocresía sobre toda la tierra.",
      "16": "Así ha dicho Jehová de los ejércitos: No escuchéis las palabras de los profetas que os profetizan: os hacen desvanecer; hablan visión de su corazón, no de la boca de Jehová.",
      "17": "Dicen atrevidamente á los que me irritan: Jehová dijo: Paz tendréis; y á cualquiera que anda tras la imaginación de su corazón, dijeron: No vendrá mal sobre vosotros.",
      "18": "Porque ¿quién estuvo en el secreto de Jehová, y vió, y oyó su palabra? ¿quién estuvo atento á su palabra, y oyó?",
      "19": "He aquí que la tempestad de Jehová saldrá con furor; y la tempestad que está aparejada, caerá sobre la cabeza de los malos.",
      "20": "No se apartará el furor de Jehová, hasta tanto que haya hecho, y hasta tanto que haya cumplido los pensamientos de su corazón: en lo postrero de los días lo entenderéis cumplidamente.",
      "21": "No envié yo aquellos profetas, y ellos corrían: yo no les hablé, y ellos profetizaban.",
      "22": "Y si ellos hubieran estado en mi secreto, también hubieran hecho oir mis palabras á mi pueblo; y les hubieran hecho volver de su mal camino, y de la maldad de sus obras.",
      "23": "¿Soy yo Dios de poco acá, dice Jehová, y no Dios de mucho ha?",
      "24": "¿Ocultaráse alguno, dice Jehová, en escondrijos que yo no lo vea? ¿No hincho yo, dice Jehová, el cielo y la tierra?",
      "25": "Yo he oído lo que aquellos profetas dijeron, profetizando mentira en mi nombre, diciendo: Soñé, soñé.",
      "26": "¿Hasta cuándo será esto en el corazón de los profetas que profetizan mentira, y que profetizan el engaño de su corazón?",
      "27": "¿No piensan como hacen á mi pueblo olvidarse de mi nombre con sus sueños que cada uno cuenta á su compañero, al modo que sus padres se olvidaron de mi nombre por Baal?",
      "28": "El profeta con quien fuere sueño, cuente sueño; y el con quien fuere mi palabra, cuente mi palabra verdadera. ¿Qué tiene que ver la paja con el trigo? dice Jehová.",
      "29": "¿No es mi palabra como el fuego, dice Jehová, y como martillo que quebranta la piedra?",
      "30": "Por tanto, he aquí yo contra los profetas, dice Jehová, que hurtan mis palabras cada uno de su más cercano.",
      "31": "He aquí yo contra los profetas, dice Jehová, que endulzan sus lenguas, y dicen: El ha dicho.",
      "32": "He aquí yo contra los que profetizan sueños mentirosos, dice Jehová y contáronlos, é hicieron errar á mi pueblo con sus mentiras y con sus lisonjas, y yo no los envié, ni les mandé; y ningún provecho hicieron á este pueblo, dice Jehová.",
      "33": "Y cuando te preguntare este pueblo, ó el profeta, ó el sacerdote, diciendo: ¿Qué es la carga de Jehová? les dirás: ¿Qué carga? Os dejaré, ha dicho Jehová.",
      "34": "Y el profeta, y el sacerdote, ó el pueblo, que dijere: Carga de Jehová; yo enviaré castigo sobre tal hombre y sobre su casa.",
      "35": "Así diréis cada cual á su compañero, y cada cual á su hermano: ¿Qué ha respondido Jehová, y qué habló Jehová?",
      "36": "Y nunca más os vendrá á la memoria decir: Carga de Jehová: porque la palabra de cada uno le será por carga; pues pervertisteis las palabras del Dios viviente, de Jehová de los ejércitos, Dios nuestro.",
      "37": "Así dirás al profeta: ¿Qué te respondió Jehová, y qué habló Jehová?",
      "38": "Mas si dijereis: Carga de Jehová: por eso Jehová dice así: Porque dijisteis esta palabra, Carga de Jehová, habiendo enviado á deciros: No digáis, Carga de Jehová:",
      "39": "Por tanto, he aquí que yo os echaré en olvido, y os arrancaré de mi presencia, y á la ciudad que os dí á vosotros y á vuestros padres;",
      "40": "Y pondré sobre vosotros afrenta perpetua, y eterna confusión que nunca borrará el olvido."
    },
    "24": {
      "1": "MOSTROME Jehová, y he aquí dos cestas de higos puestas delante del templo de Jehová, después de haber trasportado Nabucodonosor rey de Babilonia á Jechônías hijo de Joacim, rey de Judá, y á los príncipes de Judá, y á los oficiales y herreros de Jerusalem, y haberlos llevado á Babilonia.",
      "2": "La una cesta tenía higos muy buenos, como brevas; y la otra cesta tenía higos muy malos, que no se podían comer de malos.",
      "3": "Y díjome Jehová: ¿Qué ves tú, Jeremías? Y dije: Higos, higos buenos, muy buenos; y malos, muy malos, que de malos no se pueden comer.",
      "4": "Y fué á mí palabra de Jehová, diciendo:",
      "5": "Así ha dicho Jehová Dios de Israel: Como á estos buenos higos, así conoceré la trasportación de Judá al cual eché de este lugar á tierra de Caldeos, para bien.",
      "6": "Porque pondré mis ojos sobre ellos para bien, y volverélos á esta tierra; y los edificaré, y no los destruiré: plantarélos, y no los arrancaré.",
      "7": "Y les daré corazón para que me conozcan, que yo soy Jehová: y me serán por pueblo, y yo les seré á ellos por Dios; porque se volverán á mí de todo su corazón.",
      "8": "Y como los malos higos, que de malos no se pueden comer, así, ha dicho Jehová, daré á Sedechîas rey de Judá, y á sus príncipes, y al resto de Jerusalem que quedaron en esta tierra, y que moran en la tierra de Egipto.",
      "9": "Y darélos por escarnio, por mal á todos los reinos de la tierra: por infamia, y por ejemplo, y por refrán, y por maldición á todos los lugares adonde yo los arrojaré.",
      "10": "Y enviaré sobre ellos espada, hambre, y pestilencia, hasta que sean acabados de sobre la tierra que les dí á ellos y á sus padres."
    },
    "25": {
      "1": "PALABRA que fué á Jeremías acerca de todo el pueblo de Judá en el año cuarto de Joacim hijo de Josías, rey de Judá, el cual es el año primero de Nabucodonosor rey de Babilonia;",
      "2": "La cual habló Jeremías profeta á todo el pueblo de Judá, y á todos los moradores de Jerusalem, diciendo:",
      "3": "Desde el año trece de Josías hijo de Amón, rey de Judá, hasta este día, que son veintitrés años, fué á mí palabra de Jehová, y os he hablado, madrugando y dando aviso; mas no oisteis.",
      "4": "Y envió Jehová á vosotros todos sus siervos los profetas, madrugando y enviándolos; mas no oisteis, ni inclinasteis vuestro oído para escuchar,",
      "5": "Cuando decían: Volveos ahora de vuestro mal camino y de la maldad de vuestras obras, y morad en la tierra que os dió Jehová, á vosotros y á vuestros padres para siempre;",
      "6": "Y no vayáis en pos de dioses ajenos, sirviéndoles y encorvándoos á ellos, ni me provoquéis á ira con la obra de vuestras manos; y no os haré mal.",
      "7": "Empero no me habéis oído, dice Jehová, para provocarme á ira con la obra de vuestras manos para mal vuestro.",
      "8": "Por tanto, así ha dicho Jehová de los ejércitos: Por cuanto no habéis oído mis palabras,",
      "9": "He aquí enviaré yo, y tomaré todos los linajes del aquilón, dice Jehová, y á Nabucodonosor rey de Babilonia, mi siervo, y traerélos contra esta tierra, y contra sus moradores, y contra todas estas naciones en derredor; y los destruiré, y pondrélos por escarnio, y por silbo, y en soledades perpetuas.",
      "10": "Y haré que perezca de entre ellos voz de gozo y voz de alegría, voz de desposado y voz de desposada, ruido de muelas, y luz de lámpara.",
      "11": "Y toda esta tierra será puesta en soledad, en espanto; y servirán estas gentes al rey de Babilonia setenta años.",
      "12": "Y será que, cuando fueren cumplidos los setenta años, visitaré sobre el rey de Babilonia y sobre aquella gente su maldad, ha dicho Jehová, y sobre la tierra de los Caldeos; y pondréla en desiertos para siempre.",
      "13": "Y traeré sobre aquella tierra todas mis palabras que he hablado contra ella, con todo lo que está escrito en este libro, profetizado por Jeremías contra todas gentes.",
      "14": "Porque se servirán también de ellos muchas gentes, y reyes grandes; y yo les pagaré conforme á sus hechos, y conforme á la obra de sus manos.",
      "15": "Porque así me dijo Jehová Dios de Israel: Toma de mi mano el vaso del vino de este furor, y da á beber de él á todas las gentes á las cuales yo te envío.",
      "16": "Y beberán, y temblarán, y enloquecerán delante del cuchillo que yo envío entre ellos.",
      "17": "Y tomé el vaso de la mano de Jehová, y dí de beber á todas las gentes á las cuales me envió Jehová:",
      "18": "A Jerusalem, á las ciudades de Judá, y á sus reyes, y á sus príncipes, para ponerlos en soledad, en escarnio, y en silbo, y en maldición, como este día;",
      "19": "A Faraón rey de Egipto, y á sus siervos, á sus príncipes, y á todo su pueblo;",
      "20": "Y á toda la mezcla de gente, y á todos los reyes de tierra de Hus, y á todos los reyes de tierra de Palestina, y á Ascalón, y Gaza, y Ecrón, y al residuo de Asdod;",
      "21": "A Edom, y Moab, y á los hijos de Ammón;",
      "22": "Y á todos los reyes de Tiro, y á todos los reyes de Sidón, y á los reyes de las islas que están de ese lado de la mar;",
      "23": "Y á Dedán, y Tema, y Buz, y á todos los que están al cabo del mundo;",
      "24": "Y á todos los reyes de Arabia, y á todos los reyes de pueblos mezclados que habitan en el desierto;",
      "25": "Y á todos los reyes de Zimri, y á todos los reyes de Elam, y á todos los reyes de Media;",
      "26": "Y á todos los reyes del aquilón, los de cerca y los de lejos, los unos con los otros; y á todos los reinos de la tierra que están sobre la haz de la tierra: y el rey de Sesach beberá después de ellos.",
      "27": "Les dirás, pues: Así ha dicho Jehová de los ejércitos, Dios de Israel: Bebed, y embriagaos, y vomitad, y caed, y no os levantéis delante del cuchillo que yo envío entre vosotros.",
      "28": "Y será que, si no quieren tomar el vaso de tu mano para beber, les dirás tú: Así ha dicho Jehová de los ejércitos: Habéis de beber.",
      "29": "Porque he aquí, que á la ciudad sobre la cual es invocado mi nombre yo comienzo á hacer mal; ¿y vosotros seréis absueltos? No seréis absueltos: porque espada traigo sobre todos los moradores de la tierra, dice Jehová de los ejércitos.",
      "30": "Tú pues, profetizarás á ellos todas estas palabras, y les dirás: Jehová bramará desde lo alto, y desde la morada de su santidad dará su voz: enfurecido bramará sobre su morada; canción de lagareros cantará contra todos los moradores de la tierra.",
      "31": "Llegó el estruendo hasta el cabo de la tierra; porque juicio de Jehová con las gentes: él es el Juez de toda carne; entregará los impíos á cuchillo, dice Jehová.",
      "32": "Así ha dicho Jehová de los ejércitos: He aquí que el mal sale de gente en gente, y grande tempestad se levantará de los fines de la tierra.",
      "33": "Y serán muertos de Jehová en aquel día desde el un cabo de la tierra hasta el otro cabo; no se endecharán, ni se recogerán, ni serán enterrados; como estiércol serán sobre la haz de la tierra.",
      "34": "Aullad, pastores, y clamad; y revolcaos en el polvo, mayorales del rebaño; porque cumplidos son vuestros días para ser vosotros degollados y esparcidos, y caeréis como vaso de codicia.",
      "35": "Y acabaráse la huída de los pastores, y el escape de los mayorales del rebaño.",
      "36": "Voz de la grita de los pastores, y aullido de los mayorales del rebaño! porque Jehová asoló sus majadas.",
      "37": "Y las majadas quietas serán taladas por el furor de la ira de Jehová.",
      "38": "Dejó cual leoncillo su guarida; pues asolada fué la tierra de ellos por la ira del opresor, y por el furor de su saña."
    },
    "26": {
      "1": "EN el principio del reinado de Joacim hijo de Josías, rey de Judá, fué esta palabra de Jehová, diciendo:",
      "2": "Así ha dicho Jehová: Ponte en el atrio de la casa de Jehová, y habla á todas las ciudades de Judá, que vienen para adorar en la casa de Jehová, todas las palabras que yo te mandé les hablases; no retengas palabra.",
      "3": "Quizá oirán, y se tornarán cada uno de su mal camino; y arrepentiréme yo del mal que pienso hacerles por la maldad de sus obras.",
      "4": "Les dirás pues: Así ha dicho Jehová: Si no me oyereis para andar en mi ley, la cual dí delante de vosotros,",
      "5": "Para atender á las palabras de mis siervos los profetas que yo os envío, madrugando en enviarlos, á los cuales no habéis oído;",
      "6": "Yo pondré esta casa como Silo, y daré esta ciudad en maldición á todas las gentes de la tierra.",
      "7": "Y los sacerdotes, los profetas, y todo el pueblo, oyeron á Jeremías hablar estas palabras en la casa de Jehová.",
      "8": "Y fué que, acabando de hablar Jeremías todo lo que Jehová le había mandado que hablase á todo el pueblo, los sacerdotes y los profetas y todo el pueblo le echaron mano, diciendo: De cierto morirás.",
      "9": "¿Por qué has profetizado en nombre de Jehová, diciendo: Esta casa será como Silo, y esta ciudad será asolada hasta no quedar morador? Y juntóse todo el pueblo contra Jeremías en la casa de Jehová.",
      "10": "Y los príncipes de Judá oyeron estas cosas, y subieron de casa del rey á la casa de Jehová; y sentáronse en la entrada de la puerta nueva de Jehová.",
      "11": "Entonces hablaron los sacerdotes y los profetas á los príncipes y á todo el pueblo, diciendo: En pena de muerte ha incurrido este hombre; porque profetizó contra esta ciudad, como vosotros habéis oído con vuestros oídos.",
      "12": "Y habló Jeremías á todos los príncipes y á todo el pueblo, diciendo: Jehová me envió á que profetizase contra esta casa y contra esta ciudad, todas las palabras que habéis oído.",
      "13": "Y ahora, mejorad vuestros caminos y vuestras obras, y oid la voz de Jehová vuestro Dios, y arrepentiráse Jehová del mal que ha hablado contra vosotros.",
      "14": "En lo que á mí toca, he aquí estoy en vuestras manos: haced de mí como mejor y más recto os pareciere.",
      "15": "Mas sabed de cierto que, si me matareis, sangre inocente echaréis sobre vosotros, y sobre esta ciudad, y sobre sus moradores: porque en verdad Jehová me envió á vosotros para que dijese todas estas palabras en vuestros oídos.",
      "16": "Y dijeron los príncipes y todo el pueblo á los sacerdotes y profetas. No ha incurrido este hombre en pena de muerte, porque en nombre de Jehová nuestro Dios nos ha hablado.",
      "17": "Entonces se levantaron ciertos de los ancianos de la tierra, y hablaron á toda la junta del pueblo, diciendo:",
      "18": "Miqueas de Morasti profetizó en tiempo de Ezechîas rey de Judá, diciendo: Así ha dicho Jehová de los ejércitos: Sión será arada como campo, y Jerusalem vendrá á ser montones, y el monte del templo en cumbres de bosque.",
      "19": "¿Matáronlo luego Ezechîas rey de Judá y todo Judá? ¿no temió á Jehová, y oró en presencia de Jehová, y Jehová se arrepintió del mal que había hablado contra ellos? ¿Haremos pues nosotros tan grande mal contra nuestras almas?",
      "20": "Hubo también un hombre que profetizaba en nombre de Jehová, Urías, hijo de Semaías de Chîriath-jearim, el cual profetizó contra esta ciudad y contra esta tierra, conforme á todas las palabras de Jeremías:",
      "21": "Y oyó sus palabras el rey Joacim, y todos sus grandes, y todos sus príncipes, y el rey procuró de matarle; lo cual entendiendo Urías, tuvo temor, y huyó, y metióse en Egipto:",
      "22": "Y el rey Joacim envió hombres á Egipto, á Elnathán hijo de Acbor, y otros hombres con él, á Egipto;",
      "23": "Los cuales sacaron á Urías de Egipto, y lo trajeron al rey Joacim, é hiriólo á cuchillo, y echó su cuerpo en los sepulcros del vulgo.",
      "24": "La mano empero de Ahicam hijo de Saphán era con Jeremías, porque no lo entregasen en las manos del pueblo para matarlo."
    }
  }
};

