
	
export const bib_verses = {
  "romans": {
    "9": {
      "1": "VERDAD digo en Cristo, no miento, dándome testimonio mi conciencia en el Espíritu Santo,",
      "2": "Que tengo gran tristeza y continuo dolor en mi corazón.",
      "3": "Porque deseara yo mismo ser apartado de Cristo por mis hermanos, los que son mis parientes según la carne;",
      "4": "Que son israelitas, de los cuales es la adopción, y la gloria, y el pacto, y la data de la ley, y el culto, y las promesas;",
      "5": "Cuyos son los padres, y de los cuales es Cristo según la carne, el cual es Dios sobre todas las cosas, bendito por los siglos. Amén.",
      "6": "No empero que la palabra de Dios haya faltado: porque no todos los que son de Israel son Israelitas;",
      "7": "Ni por ser simiente de Abraham, son todos hijos; mas: En Isaac te será llamada simiente.",
      "8": "Quiere decir: No los que son hijos de la carne, éstos son los hijos de Dios; mas los que son hijos de la promesa, son contados en la generación.",
      "9": "Porque la palabra de la promesa es esta: Como en este tiempo vendré, y tendrá Sara un hijo.",
      "10": "Y no sólo esto; mas también Rebeca concibiendo de uno, de Isaac nuestro padre,",
      "11": "(Porque no siendo aún nacidos, ni habiendo hecho aún ni bien ni mal, para que el propósito de Dios conforme á la elección, no por las obras sino por el que llama, permaneciese;)",
      "12": "Le fué dicho que el mayor serviría al menor.",
      "13": "Como está escrito: A Jacob amé, mas á Esaú aborrecí.",
      "14": "¿Pues qué diremos? ¿Que hay injusticia en Dios? En ninguna manera.",
      "15": "Mas á Moisés dice: Tendré misericordia del que tendré misericordia, y me compadeceré del que me compadeceré.",
      "16": "Así que no es del que quiere, ni del que corre, sino de Dios que tiene misericordia.",
      "17": "Porque la Escritura dice de Faraón: Que para esto mismo te he levantado, para mostrar en ti mi potencia, y que mi nombre sea anunciado por toda la tierra.",
      "18": "De manera que del que quiere tiene misericordia; y al que quiere, endurece.",
      "19": "Me dirás pues: ¿Por qué, pues, se enoja? porque ¿quién resistirá á su voluntad?",
      "20": "Mas antes, oh hombre, ¿quién eres tú, para que alterques con Dios? Dirá el vaso de barro al que le labró: ¿Por qué me has hecho tal?",
      "21": "¿O no tiene potestad el alfarero para hacer de la misma masa un vaso para honra, y otro para vergüenza?",
      "22": "¿Y qué, si Dios, queriendo mostrar la ira y hacer notoria su potencia, soportó con mucha mansedumbre los vasos de ira preparados para muerte,",
      "23": "Y para hacer notorias las riquezas de su gloria, mostrólas para con los vasos de misericordia que él ha preparado para gloria;",
      "24": "Los cuales también ha llamado, es á saber, á nosotros, no sólo de los Judíos, mas también de los Gentiles?",
      "25": "Como también en Oseas dice: Llamaré al que no era mi pueblo, pueblo mío; Y á la no amada, amada.",
      "26": "Y será, que en el lugar donde les fué dicho: Vosotros no sois pueblo mío: Allí serán llamados hijos del Dios viviente.",
      "27": "También Isaías clama tocante á Israel: Si fuere el número de los hijos de Israel como la arena de la mar, las reliquias serán salvas:",
      "28": "Porque palabra consumadora y abreviadora en justicia, porque palabra abreviada, hará el Señor sobre la tierra.",
      "29": "Y como antes dijo Isaías: Si el Señor de los ejércitos no nos hubiera dejado simiente, Como Sodoma habríamos venido á ser, y á Gomorra fuéramos semejantes.",
      "30": "¿Pues qué diremos? Que los Gentiles que no seguían justicia, han alcanzado la justicia, es á saber, la justicia que es por la fe;",
      "31": "Mas Israel que seguía la ley de justicia, no ha llegado á la ley de justicia.",
      "32": "¿Por qué? Porque la seguían no por fe, mas como por las obras de la ley: por lo cual tropezaron en la piedra de tropiezo,",
      "33": "Como está escrito: He aquí pongo en Sión piedra de tropiezo, y piedra de caída; Y aquel que creyere en ella, no será avergonzado."
    },
    "10": {
      "1": "HERMANOS, ciertamente la voluntad de mi corazón y mi oración á Dios sobre Israel, es para salud.",
      "2": "Porque yo les doy testimonio que tienen celo de Dios, mas no conforme á ciencia.",
      "3": "Porque ignorando la justicia de Dios, y procurando establecer la suya propia, no se han sujetado á la justicia de Dios.",
      "4": "Porque el fin de la ley es Cristo, para justicia á todo aquel que cree.",
      "5": "Porque Moisés describe la justicia que es por la ley: Que el hombre que hiciere estas cosas, vivirá por ellas.",
      "6": "Mas la justicia que es por la fe dice así: No digas en tu corazón: ¿Quién subirá al cielo? (esto es, para traer abajo á Cristo:)",
      "7": "O, ¿quién descenderá al abismo? (esto es, para volver á traer á Cristo de los muertos.)",
      "8": "Mas ¿qué dice? Cercana está la palabra, en tu boca y en tu corazón. Esta es la palabra de fe, la cual predicamos:",
      "9": "Que si confesares con tu boca al Señor Jesús, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo.",
      "10": "Porque con el corazón se cree para justicia; mas con la boca se hace confesión para salud.",
      "11": "Porque la Escritura dice: Todo aquel que en él creyere, no será avergonzado.",
      "12": "Porque no hay diferencia de Judío y de Griego: porque el mismo que es Señor de todos, rico es para con todos los que le invocan:",
      "13": "Porque todo aquel que invocare el nombre del Señor, será salvo.",
      "14": "¿Cómo, pues invocarán á aquel en el cual no han creído? ¿y cómo creerán á aquel de quien no han oído? ¿y cómo oirán sin haber quien les predique?",
      "15": "¿Y cómo predicarán si no fueren enviados? Como está escrito: ­Cuán hermosos son los pies de los que anuncian el evangelio de la paz, de los que anuncian el evangelio de los bienes!",
      "16": "Mas no todos obedecen al evangelio; pues Isaías dice: Señor, ¿quién ha creído á nuestro anuncio?",
      "17": "Luego la fe es por el oir; y el oir por la palabra de Dios.",
      "18": "Mas digo: ¿No han oído? Antes bien, Por toda la tierra ha salido la fama de ellos, Y hasta los cabos de la redondez de la tierra las palabras de ellos.",
      "19": "Mas digo: ¿No ha conocido esto Israel? Primeramente Moisés dice: Yo os provocaré á celos con gente que no es mía; Con gente insensata os provocaré á ira.",
      "20": "E Isaías determinadamente dice: Fuí hallado de los que no me buscaban; Manifestéme á los que no preguntaban por mí.",
      "21": "Mas acerca de Israel dice: Todo el día extendí mis manos á un pueblo rebelde y contradictor."
    },
    "11": {
      "1": "DIGO pues: ¿Ha desechado Dios á su pueblo? En ninguna manera. Porque también yo soy Israelita, de la simiente de Abraham, de la tribu de Benjamín.",
      "2": "No ha desechado Dios á su pueblo, al cual antes conoció. ¿O no sabéis qué dice de Elías la Escritura? cómo hablando con Dios contra Israel dice:",
      "3": "Señor, á tus profetas han muerto, y tus altares han derruído; y yo he quedado solo, y procuran matarme.",
      "4": "Mas ¿qué le dice la divina respuesta? He dejado para mí siete mil hombres, que no han doblado la rodilla delante de Baal.",
      "5": "Así también, aun en este tiempo han quedado reliquias por la elección de gracia.",
      "6": "Y si por gracia, luego no por las obras; de otra manera la gracia ya no es gracia. Y si por las obras, ya no es gracia; de otra manera la obra ya no es obra.",
      "7": "¿Qué pues? Lo que buscaba Israel aquello no ha alcanzado; mas la elección lo ha alcanzado: y los demás fueron endurecidos;",
      "8": "Como está escrito: Dióles Dios espíritu de remordimiento, ojos con que no vean, y oídos con que no oigan, hasta el día de hoy.",
      "9": "Y David dice: Séales vuelta su mesa en lazo, y en red, Y en tropezadero, y en paga:",
      "10": "Sus ojos sean obscurecidos para que no vean, Y agóbiales siempre el espinazo.",
      "11": "Digo pues: ¿Han tropezado para que cayesen? En ninguna manera; mas por el tropiezo de ellos vino la salud á los Gentiles, para que fuesen provocados á celos.",
      "12": "Y si la falta de ellos es la riqueza del mundo, y el menoscabo de ellos la riqueza de los Gentiles, ¿cuánto más el henchimiento de ellos?",
      "13": "Porque á vosotros hablo, Gentiles. Por cuanto pues, yo soy apóstol de los Gentiles, mi ministerio honro.",
      "14": "Por si en alguna manera provocase á celos á mi carne, e hiciese salvos á algunos de ellos.",
      "15": "Porque si el extrañamiento de ellos es la reconciliación del mundo, ¿qué será el recibimiento de ellos, sino vida de los muertos?",
      "16": "Y si el primer fruto es santo, también lo es el todo, y si la raíz es santa, también lo son las ramas.",
      "17": "Que si algunas de las ramas fueron quebradas, y tú, siendo acebuche, has sido ingerido en lugar de ellas, y has sido hecho participante de la raíz y de la grosura de la oliva;",
      "18": "No te jactes contra las ramas; y si te jactas, sabe que no sustentas tú á la raíz, sino la raíz á ti.",
      "19": "Pues las ramas, dirás, fueron quebradas para que yo fuese ingerido.",
      "20": "Bien: por su incredulidad fueron quebradas, mas tú por la fe estás en pie. No te ensoberbezcas, antes teme.",
      "21": "Que si Dios no perdonó á las ramas naturales, á ti tampoco no perdone.",
      "22": "Mira, pues, la bondad y la severidad de Dios: la severidad ciertamente en los que cayeron; mas la bondad para contigo, si permanecieres en la bondad; pues de otra manera tú también serás cortado.",
      "23": "Y aun ellos, si no permanecieren en incredulidad, serán ingeridos; que poderoso es Dios para volverlos á ingerir.",
      "24": "Porque si tú eres cortado del natural acebuche, y contra natura fuiste ingerido en la buena oliva, ¿cuánto más éstos, que son las ramas naturales, serán ingeridos en su oliva?",
      "25": "Porque no quiero, hermanos, que ignoréis este misterio, para que no seáis acerca de vosotros mismos arrogantes: que el endurecimiento en parte ha acontecido en Israel, hasta que haya entrado la plenitud de los Gentiles;",
      "26": "Y luego todo Israel será salvo; como está escrito: Vendrá de Sión el Libertador, Que quitará de Jacob la impiedad;",
      "27": "Y este es mi pacto con ellos, Cuando quitare su pecados.",
      "28": "Así que, cuanto al evangelio, son enemigos por causa de vosotros: mas cuanto á la elección, son muy amados por causa de los padres.",
      "29": "Porque sin arrepentimiento son las mercedes y la vocación de Dios.",
      "30": "Porque como también vosotros en algún tiempo no creísteis á Dios, mas ahora habéis alcanzado misericordia por la incredulidad de ellos;",
      "31": "Así también éstos ahora no ha creído, para que, por la misericordia para con vosotros, ellos también alcancen misericordia.",
      "32": "Porque Dios encerró á todos en incredulidad, para tener misericordia de todos.",
      "33": "Oh profundidad de las riquezas de la sabiduría y de la ciencia de Dios! ­Cuán incomprensibles son sus juicios, e inescrutables sus caminos!",
      "34": "Porque ¿quién entendió la mente del Señor? ¿ó quién fué su consejero?",
      "35": "¿O quién le dió á él primero, para que le sea pagado?",
      "36": "Porque de él, y por él, y en él, son todas las cosas. A él sea gloria por siglos. Amén."
    },
    "12": {
      "1": "ASI que, hermanos, os ruego por las misericordias de Dios, que presentéis vuestros cuerpos en sacrificio vivo, santo, agradable á Dios, que es vuestro racional culto.",
      "2": "Y no os conforméis á este siglo; mas reformaos por la renovación de vuestro entendimiento, para que experimentéis cuál sea la buena voluntad de Dios, agradable y perfecta.",
      "3": "Digo pues por la gracia que me es dada, á cada cual que está entre vosotros, que no tenga más alto concepto de sí que el que debe tener, sino que piense de sí con templanza, conforme á la medida de la fe que Dios repartió á cada uno.",
      "4": "Porque de la manera que en un cuerpo tenemos muchos miembros, empero todos los miembros no tienen la misma operación;",
      "5": "Así muchos somos un cuerpo en Cristo, mas todos miembros los unos de los otros.",
      "6": "De manera que, teniendo diferentes dones según la gracia que nos es dada, si el de profecía, úsese conforme á la medida de la fe;",
      "7": "si ministerio, en servir; ó el que enseña, en doctrina;",
      "8": "El que exhorta, en exhortar; el que reparte, hágalo en simplicidad; el que preside, con solicitud; el que hace misericordia, con alegría.",
      "9": "El amor sea sin fingimiento: aborreciendo lo malo, llegándoos á lo bueno;",
      "10": "Amándoos los unos á los otros con caridad fraternal; previniéndoos con honra los unos á los otros;",
      "11": "En el cuidado no perezosos; ardientes en espíritu; sirviendo al Señor;",
      "12": "Gozosos en la esperanza; sufridos en la tribulación; constantes en la oración;",
      "13": "Comunicando á las necesidades de los santos; siguiendo la hospitalidad.",
      "14": "Bendecid á los que os persiguen: bendecid y no maldigáis.",
      "15": "Gozaos con los que se gozan: llorad con los que lloran.",
      "16": "Unánimes entre vosotros: no altivos, mas acomodándoos á los humildes. No seáis sabios en vuestra opinión.",
      "17": "No paguéis á nadie mal por mal; procurad lo bueno delante de todos los hombres.",
      "18": "Si se puede hacer, cuanto está en vosotros, tened paz con todos los hombres.",
      "19": "No os venguéis vosotros mismos, amados míos; antes dad lugar á la ira; porque escrito está: Mía es la venganza: yo pagaré, dice el Señor.",
      "20": "Así que, si tu enemigo tuviere hambre, dale de comer; si tuviere sed, dale de beber: que haciendo esto, ascuas de fuego amontonas sobre su cabeza.",
      "21": "No seas vencido de lo malo; mas vence con el bien el mal."
    },
    "13": {
      "1": "TODA alma se someta á las potestades superiores; porque no hay potestad sino de Dios; y las que son, de Dios son ordenadas.",
      "2": "Asi que, el que se opone á la potestad, á la ordenación de Dios resiste: y los que resisten, ellos mismos ganan condenación para sí.",
      "3": "Porque los magistrados no son para temor al que bien hace, sino al malo. ¿Quieres pues no temer la potestad? haz lo bueno, y tendrás alabanza de ella;",
      "4": "Porque es ministro de Dios para tu bien. Mas si hicieres lo malo, teme: porque no en vano lleva el cuchillo; porque es ministro de Dios, vengador para castigo al que hace lo malo.",
      "5": "Por lo cual es necesario que le estéis sujetos, no solamente por la ira, mas aun por la conciencia.",
      "6": "Porque por esto pagáis también los tributos; porque son ministros de Dios que sirven á esto mismo.",
      "7": "Pagad á todos lo que debéis: al que tributo, tributo; al que pecho, pecho; al que temor, temor; al que honra, honra.",
      "8": "No debáis á nadie nada, sino amaros unos á otros; porque el que ama al prójimo, cumplió la ley.",
      "9": "Porque: No adulterarás; no matarás; no hurtarás; no dirás falso testimonio; no codiciarás: y si hay algún otro mandamiento, en esta sentencia se comprende sumariamente: Amarás á tu prójimo como á ti mismo.",
      "10": "La caridad no hace mal al prójimo: así que, el cumplimento de la ley es la caridad.",
      "11": "Y esto, conociendo el tiempo, que es ya hora de levantarnos del sueño; porque ahora nos está más cerca nuestra salud que cuando creímos.",
      "12": "La noche ha pasado, y ha llegado el día: echemos, pues, las obras de las tinieblas, y vistámonos las armas de luz,",
      "13": "Andemos como de día, honestamente: no en glotonerías y borracheras, no en lechos y disoluciones, no en pedencias y envidia:",
      "14": "Mas vestíos del Señor Jesucristo, y no hagáis caso de la carne en sus deseos."
    },
    "14": {
      "1": "RECIBID al flaco en la fe, pero no para contiendas de disputas.",
      "2": "Porque uno cree que se ha de comer de todas cosas: otro que es débil, come legumbres.",
      "3": "El que come, no menosprecie al que no come: y el que no come, no juzgue al que come; porque Dios le ha levantado.",
      "4": "¿Tú quién eres que juzgas al siervo ajeno? para su señor está en pie, ó cae: mas se afirmará; que poderoso es el Señor para afirmarle.",
      "5": "Uno hace diferencia entre día y día; otro juzga iguales todos los días. Cada uno esté asegurado en su ánimo.",
      "6": "El que hace caso del día, háce lo para el Señor: y el que no hace caso del día, no lo hace para el Señor. El que come, come para el Señor, porque da gracias á Dios; y el que no come, no come para el Señor, y da gracias á Dios.",
      "7": "Porque ninguno de nosotros vive para sí, y ninguno muere para sí.",
      "8": "Que si vivimos, para el Señor vivimos; y si morimos, para el Señor morimos. Así que, ó que vivamos, ó que muramos, del Señor somos.",
      "9": "Porque Cristo para esto murió, y resucitó, y volvió á vivir, para ser Señor así de los muertos como de los que viven.",
      "10": "Mas tú ¿por qué juzgas á tu hermano? ó tú también, ¿por qué menosprecias á tu hermano? porque todos hemos de estar ante el tribunal de Cristo.",
      "11": "Porque escrito está: Vivo yo, dice el Señor, que á mí se doblará toda rodilla, Y toda lengua confesará á Dios.",
      "12": "De manera que, cada uno de nosotros dará á Dios razón de sí.",
      "13": "Así que, no juzguemos más los unos de los otros: antes bien juzgad de no poner tropiezo ó escándalo al hermano.",
      "14": "Yo sé, y confío en el Señor Jesús, que de suyo nada hay inmundo: mas á aquel que piensa alguna cosa ser inmunda, para él es inmunda.",
      "15": "Empero si por causa de la comida tu hermano es contristado, ya no andas conforme á la caridad. No arruines con tu comida á aquél por el cual Cristo murió.",
      "16": "No sea pues blasfemado vuestro bien:",
      "17": "Que el reino de Dios no es comida ni bebida, sino justicia y paz y gozo por el Espíritu Santo.",
      "18": "Porque el que en esto sirve á Cristo, agrada á Dios, y es acepto á los hombres.",
      "19": "Así que, sigamos lo que hace á la paz, y á la edificación de los unos á los otros.",
      "20": "No destruyas la obra de Dios por causa de la comida. Todas las cosas á la verdad son limpias: mas malo es al hombre que come con escándalo.",
      "21": "Bueno es no comer carne, ni beber vino, ni nada en que tu hermano tropiece, ó se ofenda ó sea debilitado.",
      "22": "¿Tienes tú fe? Tenla para contigo delante de Dios. Bienaventurado el que no se condena á sí mismo con lo que aprueba.",
      "23": "Mas el que hace diferencia, si comiere, es condenado, porque no comió por fe: y todo lo que no es de fe, es pecado."
    },
    "15": {
      "1": "ASI que, los que somos más firmes debemos sobrellevar las flaquezas de los flacos, y no agradarnos á nosotros mismos.",
      "2": "Cada uno de nosotros agrade á su prójimo en bien, á edificación.",
      "3": "Porque Cristo no se agradó á sí mismo; antes bien, como está escrito: Los vituperios de los que te vituperan, cayeron sobre mí.",
      "4": "Porque las cosas que antes fueron escritas, para nuestra enseñanza fueron escritas; para que por la paciencia, y por la consolación de las Escrituras, tengamos esperanza.",
      "5": "Mas el Dios de la paciencia y de la consolación os dé que entre vosotros seáis unánimes según Cristo Jesús;",
      "6": "Para que concordes, á una boca glorifiquéis al Dios y Padre de nuestro Señor Jesucristo.",
      "7": "Por tanto, sobrellevaos los unos á los otros, como también Cristo nos sobrellevó, para gloria de Dios.",
      "8": "Digo, pues, que Cristo Jesús fué hecho ministro de la circuncisión por la verdad de Dios, para confirmar las promesas hechas á los padres,",
      "9": "Y para que los Gentiles glorifiquen á Dios por la misericordia; como está escrito: Por tanto yo te confesaré entre los Gentiles, Y cantaré á tu nombre.",
      "10": "Y otra vez dice: Alegraos, Gentiles, con su pueblo.",
      "11": "Y otra vez: Alabad al Señor todos los Gentiles, Y magnificadle, todos los pueblos.",
      "12": "Y otra vez, dice Isaías: Estará la raíz de Jessé, Y el que se levantará á regir los Gentiles: Los Gentiles esperarán en él.",
      "13": "Y el Dios de esperanza os llene de todo gozo y paz creyendo, para que abundéis en esperanza por la virtud del Espíritu Santo.",
      "14": "Empero cierto estoy yo de vosotros, hermanos míos, que aun vosotros mismos estáis llenos de bodad, llenos de todo conocimiento, de tal manera que podáis amonestaros los unos á los otros.",
      "15": "Mas os he escrito, hermanos, en parte resueltamente, como amonestádoos por la gracia que de Dios me es dada,",
      "16": "Para ser ministro de Jesucristo á los Gentiles, ministrando el evangelio de Dios, para que la ofrenda de los Gentiles sea agradable, santificada por el Espíritu Santo.",
      "17": "Tengo, pues, de qué gloriarme en Cristo Jesús en lo que mira á Dios.",
      "18": "Porque no osaría hablar alguna cosa que Cristo no haya hecho por mí para la obediencia de los Gentiles, con la palabra y con las obras,",
      "19": "Con potencia de milagros y prodigios, en virtud del Espíritu de Dios: de manera que desde Jerusalem, y por los alrededores hasta Ilírico, he llenado todo del evangelio de Cristo.",
      "20": "Y de esta manera me esforcé á predicar el evangelio, no donde antes Cristo fuese nombrado, por no edificar sobre ajeno fundamento:",
      "21": "Sino, como esta escrito: A los que no fué anunciado de él, verán: Y los que no oyeron, entenderán.",
      "22": "Por lo cual aun he sido impedido muchas veces de venir á vosotros.",
      "23": "Mas ahora no teniendo más lugar en estas regiones, y deseando ir á vosotros muchos años há,",
      "24": "Cuando partiere para España, iré á vosotros; porque espero que pasando os veré, y que seré llevado de vosotros allá, si empero antes hubiere gozado de vosotros.",
      "25": "Mas ahora parto para Jerusalem á ministrar á los santos.",
      "26": "Porque Macedonia y Acaya tuvieron por bien hacer una colecta para los pobres de los santos que están en Jerusalem.",
      "27": "Porque les pareció bueno, y son deudores á ellos: porque si los Gentiles han sido hechos participantes de sus bienes espirituales, deben también ellos servirles en los carnales.",
      "28": "Así que, cuando hubiere concluído esto, y les hubiere consignado este fruto, pasaré por vosotros á España.",
      "29": "Y sé que cuando llegue á vosotros, llegaré con abundancia de la bendición del evangelio de Cristo.",
      "30": "Ruégoos empero, hermanos, por el Señor nuestro Jesucristo, y por la caridad del Espíritu, que me ayudéis con oraciones por mí á Dios,",
      "31": "Que sea librado de los rebeldes que están en Judea, y que la ofrenda de mi servicio á los santos en Jerusalem sea acepta;",
      "32": "Para que con gozo llegue á vosotros por la voluntad de Dios, y que sea recreado juntamente con vosotros.",
      "33": "Y el Dios de paz sea con todos vosotros. Amén."
    },
    "16": {
      "1": "ENCOMIÉNDOOS empero á Febe nuestra hermana, la cual es diaconisa de la iglesia que está en Cencreas:",
      "2": "Que la recibáis en el Señor, como es digno á los santos, y que la ayudéis en cualquiera cosa en que os hubiere menester: porque ella ha ayudado á muchos, y á mí mismo.",
      "3": "Saludad á Priscila y Aquila, mis coadjutores en Cristo Jesús;",
      "4": "(Que pusieron sus cuellos por mi vida: á los cuales no doy gracias yo sólo, mas aun todas las iglesias de los Gentiles;)",
      "5": "Asimismo á la iglesia de su casa. Saludad á Epeneto, amado mío, que es las primicias de Acaya en Cristo.",
      "6": "Saludad á María, la cual ha trabajado mucho con vosotros.",
      "7": "Saludad á Andrónico y á Junia, mis parientes, y mis compañeros en la cautividad, los que son insignes entre los apóstoles; los cuales también fueron antes de mí en Cristo.",
      "8": "Saludad á Amplias, amado mío en el Señor.",
      "9": "Saludad á Urbano, nuestro ayudador en Cristo Jesús, y á Stachîs, amado mío.",
      "10": "Saludad á Apeles, probado en Cristo. Saludad á los que son de Aristóbulo.",
      "11": "Saludad á Herodión, mi pariente. Saludad á los que son de la casa de Narciso, los que están en el Señor.",
      "12": "Saludad á Trifena y á Trifosa, las cuales trabajan en el Señor. Saludad á Pérsida amada, la cual ha trabajado mucho en el Señor.",
      "13": "Saludad á Rufo, escogido en el Señor, y á su madre y mía.",
      "14": "Saludad á Asíncrito, y á Flegonte, á Hermas, á Patrobas, á Hermes, y á los hermanos que están con ellos.",
      "15": "Saludad á Filólogo y á Julia, á Nereo y á su hermana, y á Olimpas, y á todos los santos que están con ellos.",
      "16": "Saludaos los unos á los otros con ósculo santo. Os saludan todas las iglesias de Cristo.",
      "17": "Y os ruego hermanos, que miréis los que causan disensiones y escándalos contra la doctrina que vosotros habéis aprendido; y apartaos de ellos.",
      "18": "Porque los tales no sirven al Señor nuestro Jesucristo, sino á sus vientres; y con suaves palabras y bendiciones engañan los corazones de los simples.",
      "19": "Porque vuestra obediencia ha venido á ser notoria á todos; así que me gozo de vosotros; mas quiero que seáis sabios en el bien, y simples en el mal.",
      "20": "Y el Dios de paz quebrantará presto á Satanás debajo de vuestros pies. la gracia del Señor nuestro Jesucristo sea con vosotros.",
      "21": "Os saludan Timoteo, mi coadjutor, y Lucio y Jasón y Sosipater, mis parientes.",
      "22": "Yo Tercio, que escribí la epístola, os saludo en el Señor.",
      "23": "Salúdaos Gayo, mi huésped, y de toda la iglesia. Salúdaos Erasto, tesorero de la ciudad, y el hermano Cuarto.",
      "24": "La gracia del Señor nuestro Jesucristo sea con todos vosotros. Amén.",
      "25": "Y al que puede confirmaros según mi evangelio y la predicación de Jesucristo, segun la revelación del misterio encubierto desde tiempos eternos,",
      "26": "Mas manifestado ahora, y por las Escrituras de los profetas, según el mandamiento del Dios eterno, declarado á todas las gentes para que obedezcan á la fe;",
      "27": "Al sólo Dios sabio, sea gloria por Jesucristo para siempre. Amén. enviada por medio de Febe, diaconisa de la iglesia de Cencreas."
    }
  },
  "1_corinthians": {
    "1": {
      "1": "PABLO, llamado á ser apóstol de Jesucristo por la voluntad de Dios, y Sóstenes el hermano,",
      "2": "A la iglesia de Dios que está en Corinto, santificados en Cristo Jesús, llamados santos, y á todos los que invocan el nombre de nuestro Señor Jesucristo en cualquier lugar, Señor de ellos y nuestro:",
      "3": "Gracia y paz de Dios nuestro Padre, y del Señor Jesucristo.",
      "4": "Gracias doy á mi Dios siempre por vosotros, por la gracia de Dios que os es dada en Cristo Jesús;",
      "5": "Que en todas las cosas sois enriquecidos en él, en toda lengua y en toda ciencia;",
      "6": "Así como el testimonio de Cristo ha sido confirmado en vosotros:",
      "7": "De tal manera que nada os falte en ningún don, esperando la manifestación de nuestro Señor Jesucristo:",
      "8": "El cual también os confirmará hasta el fin, para que seáis sin falta en el día de nuestro Señor Jesucristo.",
      "9": "Fiel es Dios, por el cual sois llamados á la participación de su Hijo Jesucristo nuestro Señor.",
      "10": "Os ruego pues, hermanos, por el nombre de nuestro Señor Jesucristo, que habléis todos una misma cosa, y que no haya entre vosotros disensiones, antes seáis perfectamente unidos en una misma mente y en un mismo parecer.",
      "11": "Porque me ha sido declarado de vosotros, hermanos míos, por los que son de Cloé, que hay entre vosotros contiendas;",
      "12": "Quiero decir, que cada uno de vosotros dice: Yo cierto soy de Pablo; pues yo de Apolos; y yo de Cefas; y yo de Cristo.",
      "13": "¿Está dividido Cristo? ¿Fué crucificado Pablo por vosotros? ¿ó habéis sido bautizados en el nombre de Pablo?",
      "14": "Doy gracias á Dios, que á ninguno de vosotros he bautizado, sino á Crispo y á Gayo;",
      "15": "Para que ninguno diga que habéis sido bautizados en mi nombre.",
      "16": "Y también bauticé la familia de Estéfanas: mas no sé si he bautizado algún otro.",
      "17": "Porque no me envió Cristo á bautizar, sino á predicar el evangelio: no en sabiduría de palabras, porque no sea hecha vana la cruz de Cristo.",
      "18": "Porque la palabra de la cruz es locura á los que se pierden; mas á los que se salvan, es á saber, á nosotros, es potencia de Dios.",
      "19": "Porque está escrito: Destruiré la sabiduría de los sabios, Y desecharé la inteligencia de los entendidos.",
      "20": "¿Qué es del sabio? ¿qué del escriba? ¿qué del escudriñador de este siglo? ¿no ha enloquecido Dios la sabiduría del mundo?",
      "21": "Porque por no haber el mundo conocido en la sabiduría de Dios á Dios por sabiduría, agradó á Dios salvar á los creyentes por la locura de la predicación.",
      "22": "Porque los Judíos piden señales, y los Griegos buscan sabiduría:",
      "23": "Mas nosotros predicamos á Cristo crucificado, á los Judíos ciertamente tropezadero, y á los Gentiles locura;",
      "24": "Empero á los llamados, así Judíos como Griegos, Cristo potencia de Dios, y sabiduría de Dios.",
      "25": "Porque lo loco de Dios es más sabio que los hombres; y lo flaco de Dios es más fuerte que los hombres.",
      "26": "Porque mirad, hermanos, vuestra vocación, que no sois muchos sabios según la carne, no muchos poderosos, no muchos nobles;",
      "27": "Antes lo necio del mundo escogió Dios, para avergonzar á los sabios; y lo flaco del mundo escogió Dios, para avergonzar lo fuerte;",
      "28": "Y lo vil del mundo y lo menos preciado escogió Dios, y lo que no es, para deshacer lo que es:",
      "29": "Para que ninguna carne se jacte en su presencia.",
      "30": "Mas de él sois vosotros en Cristo Jesús, el cual nos ha sido hecho por Dios sabiduría, y justificación, y santificación, y redención:",
      "31": "Para que, como está escrito: El que se gloría, gloríese en el Señor."
    },
    "2": {
      "1": "ASI que, hermanos, cuando fuí á vosotros, no fuí con altivez de palabra, ó de sabiduría, á anunciaros el testimonio de Cristo.",
      "2": "Porque no me propuse saber algo entre vosotros, sino á Jesucristo, y á éste crucificado.",
      "3": "Y estuve yo con vosotros con flaqueza, y mucho temor y temblor;",
      "4": "Y ni mi palabra ni mi predicación fué con palabras persuasivas de humana sabiduría, mas con demostración del Espíritu y de poder;",
      "5": "Para que vuestra fe no esté fundada en sabiduría de hombres, mas en poder de Dios.",
      "6": "Empero hablamos sabiduría de Dios entre perfectos; y sabiduría, no de este siglo, ni de los príncipes de este siglo, que se deshacen:",
      "7": "Mas hablamos sabiduría de Dios en misterio, la sabiduría oculta, la cual Dios predestinó antes de los siglos para nuestra gloria:",
      "8": "La que ninguno de los príncipes de este siglo conoció; porque si la hubieran conocido, nunca hubieran crucificado al Señor de gloria:",
      "9": "Antes, como está escrito: Cosas que ojo no vió, ni oreja oyó, Ni han subido en corazón de hombre, Son las que ha Dios preparado para aquellos que le aman.",
      "10": "Empero Dios nos lo reveló á nosotros por el Espíritu: porque el Espíritu todo lo escudriña, aun lo profundo de Dios.",
      "11": "Porque ¿quién de los hombres sabe las cosas del hombre, sino el espíritu del hombre que está en él? Así tampoco nadie conoció las cosas de Dios, sino el Espíritu de Dios.",
      "12": "Y nosotros hemos recibido, no el espíritu del mundo, sino el Espíritu que es de Dios, para que conozcamos lo que Dios nos ha dado;",
      "13": "Lo cual también hablamos, no con doctas palabras de humana sabiduría, mas con doctrina del Espíritu, acomodando lo espiritual á lo espiritual.",
      "14": "Mas el hombre animal no percibe las cosas que son del Espíritu de Dios, porque le son locura: y no las puede entender, porque se han de examinar espiritualmente.",
      "15": "Empero el espiritual juzga todas las cosas; mas él no es juzgado de nadie.",
      "16": "Porque ¿quién conoció la mente del Señor? ¿quién le instruyó? Mas nosotros tenemos la mente de Cristo."
    },
    "3": {
      "1": "DE manera que yo, hermanos, no pude hablaros como á espirituales, sino como á carnales, como á niños en Cristo.",
      "2": "Os dí á beber leche, y no vianda: porque aun no podíais, ni aun podéis ahora;",
      "3": "Porque todavía sois carnales: pues habiendo entre vosotros celos, y contiendas, y disensiones, ¿no sois carnales, y andáis como hombres?",
      "4": "Porque diciendo el uno: Yo cierto soy de Pablo; y el otro: Yo de Apolos; ¿no sois carnales?",
      "5": "¿Qué pues es Pablo? ¿y qué es Apolos? Ministros por los cuales habéis creído; y eso según que á cada uno ha concedido el Señor.",
      "6": "Yo planté, Apolos regó: mas Dios ha dado el crecimiento.",
      "7": "Así que, ni el que planta es algo, ni el que riega; sino Dios, que da el crecimiento.",
      "8": "Y el que planta y el que riega son una misma cosa; aunque cada uno recibirá su recompensa conforme á su labor.",
      "9": "Porque nosotros, coadjutores somos de Dios; y vosotros labranza de Dios sois, edificio de Dios sois.",
      "10": "Conforme á la gracia de Dios que me ha sido dada, yo como perito arquitecto puse el fundamento, y otro edifica encima: empero cada uno vea cómo sobreedifica.",
      "11": "Porque nadie puede poner otro fundamento que el que está puesto, el cual es Jesucristo.",
      "12": "Y si alguno edificare sobre este fundamento oro, plata, piedras preciosas, madera, heno, hojarasca;",
      "13": "La obra de cada uno será manifestada: porque el día la declarará; porque por el fuego será manifestada; y la obra de cada uno cuál sea, el fuego hará la prueba.",
      "14": "Si permaneciere la obra de alguno que sobreedificó, recibirá recompensa.",
      "15": "Si la obra de alguno fuere quemada, será perdida: él empero será salvo, mas así como por fuego.",
      "16": "¿No sabéis que sois templo de Dios, y que el Espíritu de Dios mora en vosotros?",
      "17": "Si alguno violare el templo de Dios, Dios destruirá al tal: porque el templo de Dios, el cual sois vosotros, santo es.",
      "18": "Nadie se engañe á sí mismo: si alguno entre vosotros parece ser sabio en este siglo, hágase simple, para ser sabio.",
      "19": "Porque la sabiduría de esta mundo es necedad para con Dios; pues escrito está: El que prende á los sabios en la astucia de ellos.",
      "20": "Y otra vez: El Señor conoce los pensamientos de los sabios, que son vanos.",
      "21": "Así que, ninguno se gloríe en los hombres; porque todo es vuestro,",
      "22": "Sea Pablo, sea Apolos, sea Cefas, sea el mundo, sea la vida, sea la muerte, sea lo presente, sea los por venir; todo es vuestro;",
      "23": "Y vosotros de Cristo; y Cristo de Dios."
    },
    "4": {
      "1": "TÉNGANNOS los hombres por ministros de Cristo, y dispensadores de los misterios de Dios.",
      "2": "Mas ahora se requiere en los dispensadores, que cada uno sea hallado fiel.",
      "3": "Yo en muy poco tengo el ser juzgado de vosotros, ó de juicio humano; y ni aun yo me juzgo.",
      "4": "Porque aunque de nada tengo mala conciencia, no por eso soy justificado; mas el que me juzga, el Señor es.",
      "5": "Así que, no juzguéis nada antes de tiempo, hasta que venga el Señor, el cual también aclarará lo oculto de las tinieblas, y manifestará los intentos de los corazones: y entonces cada uno tendrá de Dios la alabanza.",
      "6": "Esto empero, hermanos, he pasado por ejemplo en mí y en Apolos por amor de vosotros; para que en nosotros aprendáis á no saber más de lo que está escrito, hinchándoos por causa de otro el uno contra el otro.",
      "7": "Porque ¿quién te distingue? ¿ó qué tienes que no hayas recibido? Y si lo recibiste, ¿de qué te glorías como si no hubieras recibido?",
      "8": "Ya estáis hartos, ya estáis ricos, sin nosotros reináis; y ojalá reinéis, para que nosotros reinemos también juntamente con vosotros.",
      "9": "Porque á lo que pienso, Dios nos ha mostrado á nosotros los apóstoles por los postreros, como á sentenciados á muerte: porque somos hechos espectáculo al mundo, y á los ángeles, y á los hombres.",
      "10": "Nosotros necios por amor de Cristo, y vosotros prudentes en Cristo; nosotros flacos, y vosotros fuertes; vosotros nobles, y nosotros viles.",
      "11": "Hasta esta hora hambreamos, y tenemos sed, y estamos desnudos, y somos heridos de golpes, y andamos vagabundos;",
      "12": "Y trabajamos, obrando con nuestras manos: nos maldicen, y bendecimos: padecemos persecución, y sufrimos:",
      "13": "Somos blasfemados, y rogamos: hemos venido á ser como la hez del mundo, el desecho de todos hasta ahora.",
      "14": "No escribo esto para avergonzaros: mas amonéstoos como á mis hijos amados.",
      "15": "Porque aunque tengáis diez mil ayos en Cristo, no tendréis muchos padres; que en Cristo Jesús yo os engendré por el evangelio.",
      "16": "Por tanto, os ruego que me imitéis.",
      "17": "Por lo cual os he enviado á Timoteo, que es mi hijo amado y fiel en el Señor, el cual os amonestará de mis caminos cuáles sean en Cristo, de la manera que enseño en todas partes en todas las iglesias.",
      "18": "Mas algunos están envanecidos, como si nunca hubiese yo de ir á vosotros.",
      "19": "Empero iré presto á vosotros, si el Señor quisiere; y entenderé, no las palabras de los que andan hinchados, sino la virtud.",
      "20": "Porque el reino de Dios no consiste en palabras, sino en virtud.",
      "21": "¿Qué queréis? ¿iré á vosotros con vara, ó con caridad y espíritu de mansedumbre?"
    },
    "5": {
      "1": "DE cierto se oye que hay entre vosotros fornicación, y tal fornicación cual ni aun se nombra entre los Gentiles; tanto que alguno tenga la mujer de su padre.",
      "2": "Y vosotros estáis hinchados, y no más bien tuvisteis duelo, para que fuese quitado de en medio de vosotros el que hizo tal obra.",
      "3": "Y ciertamente, como ausente con el cuerpo, mas presente en espíritu, ya como presente he juzgado al que esto así ha cometido:",
      "4": "En el nombre del Señor nuestro Jesucristo, juntados vosotros y mi espíritu, con la facultad de nuestro Señor Jesucristo,",
      "5": "El tal sea entregado á Satanás para muerte de la carne, porque el espíritu sea salvo en el día del Señor Jesús.",
      "6": "No es buena vuestra jactancia. ¿No sabéis que un poco de levadura leuda toda la masa?",
      "7": "Limpiad pues la vieja levadura, para que seáis nueva masa, como sois sin levadura: porque nuestra pascua, que es Cristo, fué sacrificada por nosotros.",
      "8": "Así que hagamos fiesta, no en la vieja levadura, ni en la levadura de malicia y de maldad, sino en ázimos de sinceridad y de verdad.",
      "9": "Os he escrito por carta, que no os envolváis con los fornicarios:",
      "10": "No absolutamente con los fornicarios de este mundo, ó con los avaros, ó con los ladrones, ó con los idólatras; pues en tal caso os sería menester salir del mundo.",
      "11": "Mas ahora os he escrito, que no os envolváis, es á saber, que si alguno llamándose hermano fuere fornicario, ó avaro, ó idólatra, ó maldiciente, ó borracho, ó ladrón, con el tal ni aun comáis.",
      "12": "Porque ¿qué me va á mí en juzgar á los que están fuera? ¿No juzgáis vosotros á los que están dentro?",
      "13": "Porque á los que están fuera, Dios juzgará: quitad pues á ese malo de entre vosotros."
    },
    "6": {
      "1": "¿OSA alguno de vosotros, teniendo algo con otro, ir á juicio delante de los injustos, y no delante de los santos?",
      "2": "¿O no sabéis que los santos han de juzgar al mundo? Y si el mundo ha de ser juzgado por vosotros, ¿sois indignos de juzgar cosas muy pequeñas?",
      "3": "¿O no sabéis que hemos de juzgar á los angeles? ¿cuánto más las cosas de este siglo?",
      "4": "Por tanto, si hubiereis de tener juicios de cosas de este siglo, poned para juzgar á los que son de menor estima en la iglesia.",
      "5": "Para avergonzaros lo digo. ¿Pues qué, no hay entre vosotros sabio, ni aun uno que pueda juzgar entre sus hermanos;",
      "6": "Sino que el hermano con el hermano pleitea en juicio, y esto ante los infieles?",
      "7": "Así que, por cierto es ya una falta en vosotros que tengáis pleitos entre vosotros mismos. ¿Por qué no sufrís antes la injuria? ¿por qué no sufrís antes ser defraudados?",
      "8": "Empero vosotros hacéis la injuria, y defraudáis, y esto á los hermanos.",
      "9": "¿No sabéis que los injustos no poseerán el reino de Dios? No erréis, que ni los fornicarios, ni los idólatras, ni los adúlteros, ni los afeminados, ni los que se echan con varones,",
      "10": "Ni los ladrones, ni los avaros, ni los borrachos, ni los maldicientes, ni los robadores, heredarán el reino de Dios.",
      "11": "Y esto erais algunos: mas ya sois lavados, mas ya sois santificados, mas ya sois justificados en el nombre del Señor Jesús, y por el Espíritu de nuestro Dios.",
      "12": "Todas las cosas me son lícitas, mas no todas convienen: todas las cosas me son lícitas, mas yo no me meteré debajo de potestad de nada.",
      "13": "Las viandas para el vientre, y el vientre para las viandas; empero y á él y á ellas deshará Dios. Mas el cuerpo no es para la fornicación, sino para el Señor; y el Señor para el cuerpo:",
      "14": "Y Dios que levantó al Señor, también á nosotros nos levantará con su poder.",
      "15": "¿No sabéis que vuestros cuerpos son miembros de Cristo? ¿Quitaré pues los miembros de Cristo, y los haré miembros de una ramera? Lejos sea.",
      "16": "¿O no sabéis que el que se junta con una ramera, es hecho con ella un cuerpo? porque serán, dice, los dos en una carne.",
      "17": "Empero el que se junta con el Señor, un espíritu es.",
      "18": "Huid la fornicación. Cualquier otro pecado que el hombre hiciere, fuera del cuerpo es; mas el que fornica, contra su propio cuerpo peca.",
      "19": "¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo, el cual está en vosotros, el cual tenéis de Dios, y que no sois vuestros?",
      "20": "Porque comprados sois por precio: glorificad pues á Dios en vuestro cuerpo y en vuestro espíritu, los cuales son de Dios."
    },
    "7": {
      "1": "CUANTO á las cosas de que me escribisteis, bien es al hombre no tocar mujer.",
      "2": "Mas á causa de las fornicaciones, cada uno tenga su mujer, y cada una tenga su marido.",
      "3": "El marido pague á la mujer la debida benevolencia; y asimismo la mujer al marido.",
      "4": "La mujer no tiene potestad de su propio cuerpo, sino el marido: é igualmente tampoco el marido tiene potestad de su propio cuerpo, sino la mujer.",
      "5": "No os defraudéis el uno al otro, á no ser por algún tiempo de mutuo consentimiento, para ocuparos en la oración: y volved á juntaros en uno, porque no os tiente Satanás á causa de vuestra incontinencia.",
      "6": "Mas esto digo por permisión, no por mandamiento.",
      "7": "Quisiera más bien que todos los hombres fuesen como yo: empero cada uno tiene su propio don de Dios; uno á la verdad así, y otro así.",
      "8": "Digo pues á los solteros y á las viudas, que bueno les es si se quedaren como yo.",
      "9": "Y si no tienen don de continencia, cásense; que mejor es casarse que quemarse.",
      "10": "Mas á los que están juntos en matrimonio, denuncio, no yo, sino el Señor: Que la mujer no se aparte del marido;",
      "11": "Y si se apartare, que se quede sin casar, ó reconcíliese con su marido; y que el marido no despida á su mujer.",
      "12": "Y á los demás yo digo, no el Señor: si algún hermano tiene mujer infiel, y ella consiente en habitar con él, no la despida.",
      "13": "Y la mujer que tiene marido infiel, y él consiente en habitar con ella, no lo deje.",
      "14": "Porque el marido infiel es santificado en la mujer, y la mujer infiel en el marido: pues de otra manera vuestros hijos serían inmundos; empero ahora son santos.",
      "15": "Pero si el infiel se aparta, apártese: que no es el hermano ó la hermana sujeto á servidumbre en semejante caso; antes á paz nos llamó Dios.",
      "16": "Porque ¿de dónde sabes, oh mujer, si quizá harás salva á tu marido? ¿ó de dónde sabes, oh marido, si quizá harás salvo á tu mujer?",
      "17": "Empero cada uno como el Señor le repartió, y como Dios llamó á cada uno, así ande: y así enseño en todas las iglesias.",
      "18": "¿Es llamado alguno circuncidado? quédese circunciso. ¿Es llamado alguno incircuncidado? que no se circuncide.",
      "19": "La circuncisión nada es, y la incircuncisión nada es; sino la observancia de las mandamientos de Dios.",
      "20": "Cada uno en la vocación en que fué llamado, en ella se quede.",
      "21": "¿Eres llamado siendo siervo? no se te dé cuidado; mas también si puedes hacerte libre, procúralo más.",
      "22": "Porque el que en el Señor es llamado siendo siervo, liberto es del Señor: asimismo también el que es llamado siendo libre, siervo es de Cristo.",
      "23": "Por precio sois comprados; no os hagáis siervos de los hombres.",
      "24": "Cada uno, hermanos, en lo que es llamado, en esto se quede para con Dios.",
      "25": "Empero de las vírgenes no tengo mandamiento del Señor; mas doy mi parecer, como quien ha alcanzado misericordia del Señor para ser fiel.",
      "26": "Tengo, pues, esto por bueno á causa de la necesidad que apremia, que bueno es al hombre estarse así.",
      "27": "¿Estás ligado á mujer? no procures soltarte. ¿Estáis suelto de mujer? no procures mujer.",
      "28": "Mas también si tomares mujer, no pecaste; y si la doncella se casare, no pecó: pero aflicción de carne tendrán los tales; mas yo os dejo.",
      "29": "Esto empero digo, hermanos, que el tiempo es corto: lo que resta es, que los que tienen mujeres sean como los que no las tienen,",
      "30": "Y los que lloran, como los que no lloran; y los que se huelgan, como los que no se huelgan; y los que compran, como los que no poseen;",
      "31": "Y los que usan de este mundo, como los que no usan: porque la apariencia de este mundo se pasa.",
      "32": "Quisiera, pues, que estuvieseis sin congoja. El soltero tiene cuidado de las cosas que son del Señor, cómo ha de agradar al Señor:",
      "33": "Empero el que se casó tiene cuidado de las cosas que son del mundo, cómo ha de agradar á su mujer.",
      "34": "Hay asimismo diferencia entre la casada y la doncella: la doncella tiene cuidado de las cosas del Señor, para ser santa así en el cuerpo como en el espíritu: mas la casada tiene cuidado de las cosas del mundo, cómo ha de agradar á su marido.",
      "35": "Esto empero digo para vuestro provecho; no para echaros lazo, sino para lo honesto y decente, y para que sin impedimento os lleguéis al Señor.",
      "36": "Mas, si á alguno parece cosa fea en su hija virgen, que pase ya de edad, y que así conviene que se haga, haga lo que quisiere, no peca; cásese.",
      "37": "Pero el que está firme en su corazón, y no tiene necesidad, sino que tiene libertad de su voluntad, y determinó en su corazón esto, el guardar su hija virgen, bien hace.",
      "38": "Así que, el que la da en casamiento, bien hace; y el que no la da en casamiento, hace mejor.",
      "39": "La mujer casada está atada á la ley, mientras vive su marido; mas si su marido muriere, libre es: cásese con quien quisiere, con tal que sea en el Señor.",
      "40": "Empero más venturosa será si se quedare así, según mi consejo; y pienso que también yo tengo Espíritu de Dios."
    },
    "8": {
      "1": "Y POR lo que hace á lo sacrificado á los ídolos, sabemos que todos tenemos ciencia. La ciencia hincha, mas la caridad edifica.",
      "2": "Y si alguno se imagina que sabe algo, aun no sabe nada como debe saber.",
      "3": "Mas si alguno ama á Dios, el tal es conocido de él.",
      "4": "Acerca, pues, de las viandas que son saacrificadas á los ídolos, sabemos que el ídolo nada es en el mundo, y que no hay más de un Dios.",
      "5": "Porque aunque haya algunos que se llamen dioses, ó en el cielo, ó en la tierra (como hay muchos dioses y muchos señores),",
      "6": "Nosotros empero no tenemos más de un Dios, el Padre, del cual son todas las cosas, y nosotros en él: y un Señor Jesucristo, por el cual son todas las cosas, y nosotros por él.",
      "7": "Mas no en todos hay esta ciencia: porque algunos con conciencia del ídolo hasta aquí, comen como sacrificado á ídolos; y su conciencia, siendo flaca, es contaminada.",
      "8": "Si bien la vianda no nos hace más aceptos á Dios: porque ni que comamos, seremos más ricos; ni que no comamos, seremos más pobres.",
      "9": "Mas mirad que esta vuestra libertad no sea tropezadero á los que son flacos.",
      "10": "Porque si te ve alguno, á ti que tienes ciencia, que estás sentado á la mesa en el lugar de los ídolos, ¿la conciencia de aquel que es flaco, no será adelantada á comer de lo sacrificado á los ídolos?",
      "11": "Y por tu ciencia se perderá el hermano flaco por el cual Cristo murió.",
      "12": "De esta manera, pues, pecando contra los hermanos, é hiriendo su flaca conciencia, contra Cristo pecáis.",
      "13": "Por lo cual, si la comida es á mi hermano ocasión de caer, jamás comeré carne por no escandalizar á mi hermano."
    },
    "9": {
      "1": "¿NO soy apóstol? ¿no soy libre? ¿no he visto á Jesús el Señor nuestro? ¿no sois vosotros mi obra en el Señor?",
      "2": "Si á los otros no soy apóstol, á vosotros ciertamente lo soy: porque el sello de mi apostolado sois vosotros en el Señor.",
      "3": "Esta es mi respuesta á los que me preguntan.",
      "4": "Qué, ¿no tenemos potestad de comer y de beber?",
      "5": "¿No tenemos potestad de traer con nosotros una hermana mujer también como los otros apóstoles, y los hermanos del Señor, y Cefas?",
      "6": "¿O sólo yo y Bernabé no tenemos potestad de no trabajar?",
      "7": "¿Quién jamás peleó á sus expensas? ¿quién planta viña, y no come de su fruto? ¿ó quién apacienta el ganado, y no come de la leche del ganado?",
      "8": "¿Digo esto según los hombres? ¿no dice esto también la ley?",
      "9": "Porque en la ley de Moisés está escrito: No pondrás bozal al buey que trilla. ¿Tiene Dios cuidado de los bueyes?",
      "10": "¿O dícelo enteramente por nosotros? Pues por nosotros está escrito: porque con esperanza ha de arar el que ara; y el que trilla, con esperanza de recibir el fruto.",
      "11": "Si nosotros os sembramos lo espiritual, ¿es gran cosa si segáremos lo vuestro carnal?",
      "12": "Si otros tienen en vosotros esta potestad, ¿no más bien nosotros? Mas no hemos usado de esta potestad: antes lo sufrimos todo, por no poner ningún obstáculo al evangelio de Cristo.",
      "13": "¿No sabéis que los que trabajan en el santuario, comen del santuario; y que los que sirven al altar, del altar participan?",
      "14": "Así también ordenó el Señor á los que anuncian el evangelio, que vivan del evangelio.",
      "15": "Mas yo de nada de esto me aproveché: ni tampoco he escrito esto para que se haga así conmigo; porque tengo por mejor morir, antes que nadie haga vana esta mi gloria.",
      "16": "Pues bien que anuncio el evangelio, no tengo por qué gloriarme porque me es impuesta necesidad; y ­ay de mí si no anunciare el evangelio!",
      "17": "Por lo cual, si lo hago de voluntad, premio tendré; mas si por fuerza, la dispensación me ha sido encargada.",
      "18": "¿Cuál, pues, es mi merced? Que predicando el evangelio, ponga el evangelio de Cristo de balde, para no usar mal de mi potestad en el evangelio.",
      "19": "Por lo cual, siendo libre para con todos, me he hecho siervo de todos por ganar á más.",
      "20": "Heme hecho á los Judíos como Judío, por ganar á los Judíos; á los que están sujetos á la ley (aunque yo no sea sujeto á la ley) como sujeto á la ley, por ganar á los que están sujetos á la ley;",
      "21": "A los que son sin ley, como si yo fuera sin ley, (no estando yo sin ley de Dios, mas en la ley de Cristo) por ganar á los que estaban sin ley.",
      "22": "Me he hecho á los flacos flaco, por ganar á los flacos: á todos me he hecho todo, para que de todo punto salve á algunos.",
      "23": "Y esto hago por causa del evangelio, por hacerme juntamente participante de él.",
      "24": "¿No sabéis que los que corren en el estadio, todos á la verdad corren, mas uno lleva el premio? Corred de tal manera que lo obtengáis.",
      "25": "Y todo aquel que lucha, de todo se abstiene: y ellos, á la verdad, para recibir una corona corruptible; mas nosotros, incorruptible.",
      "26": "Así que, yo de esta manera corro, no como á cosa incierta; de esta manera peleo, no como quien hiere el aire:",
      "27": "Antes hiero mi cuerpo, y lo pongo en servidumbre; no sea que, habiendo predicado á otros, yo mismo venga á ser reprobado."
    },
    "10": {
      "1": "PORQUE no quiero, hermanos, que ignoréis que nuestros padres todos estuvieron bajo la nube, y todos pasaron la mar;",
      "2": "Y todos en Moisés fueron bautizados en la nube y en la mar;",
      "3": "Y todos comieron la misma vianda espiritual;",
      "4": "Y todos bebieron la misma bebida espiritual; porque bebían de la piedra espiritual que los seguía, y la piedra era Cristo.",
      "5": "Mas de muchos de ellos no se agradó Dios; por lo cual fueron postrados en el desierto.",
      "6": "Empero estas cosas fueron en figura de nosotros, para que no codiciemos cosas malas, como ellos codiciaron.",
      "7": "Ni seáis honradores de ídolos, como algunos de ellos, según está escrito: Sentóse el pueblo á comer y á beber, y se levantaron á jugar.",
      "8": "Ni forniquemos, como algunos de ellos fornicaron, y cayeron en un día veinte y tres mil.",
      "9": "Ni tentemos á Cristo, como también algunos de ellos le tentaron, y perecieron por las serpientes.",
      "10": "Ni murmuréis, como algunos de ellos murmuraron, y perecieron por el destructor.",
      "11": "Y estas cosas les acontecieron en figura; y son escritas para nuestra admonición, en quienes los fines de los siglos han parado.",
      "12": "Así que, el que piensa estar firme, mire no caiga.",
      "13": "No os ha tomado tentación, sino humana: mas fiel es Dios, que no os dejará ser tentados más de lo que podeís llevar; antes dará también juntamente con la tentación la salida, para que podáis aguantar.",
      "14": "Por tanto, amados míos, huid de la idolatría.",
      "15": "Como á sabios hablo; juzgad vosotros lo que digo.",
      "16": "La copa de bendición que bendecimos, ¿no es la comunión de la sangre de Cristo? El pan que partimos, ¿no es la comunión del cuerpo de Cristo?",
      "17": "Porque un pan, es que muchos somos un cuerpo; pues todos participamos de aquel un pan.",
      "18": "Mirad á Israel según la carne: los que comen de los sacrificios ¿no son partícipes con el altar?",
      "19": "¿Qué pues digo? ¿Que el ídolo es algo? ¿ó que sea algo lo que es sacrificado á los ídolos?",
      "20": "Antes digo que lo que los Gentiles sacrifican, á los demonios lo sacrifican, y no á Dios: y no querría que vosotros fueseis partícipes con los demonios.",
      "21": "No podéis beber la copa del Señor, y la copa de los demonios: no podéis ser partícipes de la mesa del Señor, y de la mesa de los demonios.",
      "22": "¿O provocaremos á celo al Señor? ¿Somos más fuertes que él?",
      "23": "Todo me es lícito, mas no todo conviene: todo me es lícito, mas no todo edifica.",
      "24": "Ninguno busque su propio bien, sino el del otro.",
      "25": "De todo lo que se vende en la carnicería, comed, sin preguntar nada por causa de la conciencia;",
      "26": "Porque del Señor es la tierra y lo que la hinche.",
      "27": "Y si algún infiel os llama, y queréis ir, de todo lo que se os pone delante comed, sin preguntar nada por causa de la conciencia.",
      "28": "Mas si alguien os dijere: Esto fué sacrificado á los ídolos: no lo comáis, por causa de aquel que lo declaró, y por causa de la conciencia: porque del Señor es la tierra y lo que la hinche.",
      "29": "La conciencia, digo, no tuya, sino del otro. Pues ¿por qué ha de ser juzgada mi libertad por otra conciencia?",
      "30": "Y si yo con agradecimiento participo, ¿por qué he de ser blasfemado por lo que doy gracias?",
      "31": "Si pues coméis, ó bebéis, ó hacéis otra cosa, haced lo todo á gloria de Dios.",
      "32": "Sed sin ofensa á Judíos, y á Gentiles, y á la iglesia de Dios;",
      "33": "Como también yo en todas las cosas complazco á todos, no procurando mi propio beneficio, sino el de muchos, para que sean salvos."
    },
    "11": {
      "1": "SED imitadores de mí, así como yo de Cristo.",
      "2": "Y os alabo, hermanos, que en todo os acordáis de mi, y retenéis las instrucciones mías, de la manera que os enseñé.",
      "3": "Mas quiero que sepáis, que Cristo es la cabeza de todo varón; y el varón es la cabeza de la mujer; y Dios la cabeza de Cristo.",
      "4": "Todo varón que ora ó profetiza cubierta la cabeza, afrenta su cabeza.",
      "5": "Mas toda mujer que ora ó profetiza no cubierta su cabeza, afrenta su cabeza; porque lo mismo es que si se rayese.",
      "6": "Porque si la mujer no se cubre, trasquílese también: y si es deshonesto á la mujer trasquilarse ó raerse, cúbrase.",
      "7": "Porque el varón no ha de cubrir la cabeza, porque es imagen y gloria de Dios: mas la mujer es gloria del varón.",
      "8": "Porque el varón no es de la mujer, sino la mujer del varón.",
      "9": "Porque tampoco el varón fué criado por causa de la mujer, sino la mujer por causa del varón.",
      "10": "Por lo cual, la mujer debe tener señal de potestad sobre su cabeza, por causa de los ángeles.",
      "11": "Mas ni el varón sin la mujer, ni la mujer sin el varón, en el Señor.",
      "12": "Porque como la mujer es del varón, así también el varón es por la mujer: empero todo de Dios.",
      "13": "Juzgad vosotros mismos: ¿es honesto orar la mujer á Dios no cubierta?",
      "14": "La misma naturaleza ¿no os enseña que al hombre sea deshonesto criar cabello?",
      "15": "Por el contrario, á la mujer criar el cabello le es honroso; porque en lugar de velo le es dado el cabello.",
      "16": "Con todo eso, si alguno parece ser contencioso, nosotros no tenemos tal costumbre, ni las iglesias de Dios.",
      "17": "Esto empero os denuncio, que no alabo, que no por mejor sino por peor os juntáis.",
      "18": "Porque lo primero, cuando os juntáis en la iglesia, oigo que hay entre vosotros disensiones; y en parte lo creo.",
      "19": "Porque preciso es que haya entre vosotros aun herejías, para que los que son probados se manifiesten entre vosotros.",
      "20": "Cuando pues os juntáis en uno, esto no es comer la cena del Señor.",
      "21": "Porque cada uno toma antes para comer su propia cena; y el uno tiene hambre, y el otro está embriagado.",
      "22": "Pues qué, ¿no tenéis casas en que comáis y bebáis? ¿ó menospreciáis la iglesia de Dios, y avergonzáis á los que no tienen? ¿Qué os diré? ¿os alabaré? En esto no os alabo.",
      "23": "Porque yo recibí del Señor lo que también os he enseñado: Que el Señor Jesús, la noche que fué entregado, tomó pan;",
      "24": "Y habiendo dado gracias, lo partió, y dijo: Tomad, comed: esto es mi cuerpo que por vosotros es partido: haced esto en memoria de mí.",
      "25": "Asimismo tomó también la copa, después de haber cenado, diciendo: Esta copa es el nuevo pacto en mi sangre: haced esto todas las veces que bebiereis, en memoria de mí.",
      "26": "Porque todas las veces que comiereis este pan, y bebiereis esta copa, la muerte del Señor anunciáis hasta que venga.",
      "27": "De manera que, cualquiera que comiere este pan ó bebiere esta copa del Señor indignamente, será culpado del cuerpo y de la sangre del Señor.",
      "28": "Por tanto, pruébese cada uno á sí mismo, y coma así de aquel pan, y beba de aquella copa.",
      "29": "Porque el que come y bebe indignamente, juicio come y bebe para sí, no discerniendo el cuerpo del Señor.",
      "30": "Por lo cual hay muchos enfermos y debilitados entre vosotros; y muchos duermen.",
      "31": "Que si nos examinásemos á nosotros mismos, cierto no seríamos juzgados.",
      "32": "Mas siendo juzgados, somos castigados del Señor, para que no seamos condenados con el mundo.",
      "33": "Así, que, hermanos míos, cuando os juntáis á comer, esperaos unos á otros.",
      "34": "Si alguno tuviere hambre, coma en su casa, porque no os juntéis para juicio. Las demás cosas ordenaré cuando llegare."
    },
    "12": {
      "1": "Y ACERCA de los dones espirituales, no quiero, hermanos, que ignoréis.",
      "2": "Sabéis que cuando erais Gentiles, ibais, como erais llevados, a los ídolos mudos.",
      "3": "Por tanto os hago saber, que nadie que hable por Espíritu de Dios, llama anatema á Jesús; y nadie puede llamar á Jesús Señor, sino por Espíritu Santo.",
      "4": "Empero hay repartimiento de dones; mas el mismo Espíritu es.",
      "5": "Y hay repartimiento de ministerios; mas el mismo Señor es.",
      "6": "Y hay repartimiento de operaciones; mas el mismo Dios es el que obra todas las cosas en todos.",
      "7": "Empero á cada uno le es dada manifestación del Espíritu para provecho.",
      "8": "Porque á la verdad, á éste es dada por el Espíritu palabra de sabiduría; á otro, palabra de ciencia según el mismo Espíritu;",
      "9": "A otro, fe por el mismo Espíritu, y á otro, dones de sanidades por el mismo Espíritu;",
      "10": "A otro, operaciones de milagros, y á otro, profecía; y á otro, discreción de espíritus; y á otro, géneros de lenguas; y á otro, interpretación de lenguas.",
      "11": "Mas todas estas cosas obra uno y el mismo Espíritu, repartiendo particularmente á cada uno como quiere.",
      "12": "Porque de la manera que el cuerpo es uno, y tiene muchos miembros, empero todos los miembros del cuerpo, siendo muchos, son un cuerpo, así también Cristo.",
      "13": "Porque por un Espíritu somos todos bautizados en un cuerpo, ora Judíos ó Griegos, ora siervos ó libres; y todos hemos bebido de un mismo Espíritu.",
      "14": "Pues ni tampoco el cuerpo es un miembro, sino muchos.",
      "15": "Si dijere el pie: Porque no soy mano, no soy del cuerpo: ¿por eso no será del cuerpo?",
      "16": "Y si dijere la oreja: Porque no soy ojo, no soy del cuerpo: ¿por eso no será del cuerpo?",
      "17": "Si todo el cuerpo fuese ojo, ¿dónde estaría el oído? Si todo fuese oído, ¿dónde estaría el olfato?",
      "18": "Mas ahora Dios ha colocado los miembros cada uno de ellos en el cuerpo, como quiso.",
      "19": "Que si todos fueran un miembro, ¿dónde estuviera el cuerpo?",
      "20": "Mas ahora muchos miembros son á la verdad, empero un cuerpo.",
      "21": "Ni el ojo puede decir á la mano: No te he menester: ni asimismo la cabeza á los pies: No tengo necesidad de vosotros.",
      "22": "Antes, mucho más los miembros del cuerpo que parecen más flacos, son necesarios;",
      "23": "Y á aquellos del cuerpo que estimamos ser más viles, á éstos vestimos más honrosamente; y los que en nosotros son menos honestos, tienen más compostura.",
      "24": "Porque los que en nosotros son más honestos, no tienen necesidad: mas Dios ordenó el cuerpo, dando más abundante honor al que le faltaba;",
      "25": "Para que no haya desavenencia en el cuerpo, sino que los miembros todos se interesen los unos por los otros.",
      "26": "Por manera que si un miembro padece, todos los miembros á una se duelen; y si un miembro es honrado, todos los miembros á una se gozan.",
      "27": "Pues vosotros sois el cuerpo de Cristo, y miembros en parte.",
      "28": "Y á unos puso Dios en la iglesia, primeramente apóstoles, luego profetas, lo tercero doctores; luego facultades; luego dones de sanidades, ayudas, gobernaciones, géneros de lenguas.",
      "29": "¿Son todos apóstoles? ¿son todos profetas? ¿todos doctores? ¿todos facultades?",
      "30": "¿Tienen todos dones de sanidad? ¿hablan todos lenguas? ¿interpretan todos?",
      "31": "Empero procurad los mejores dones; mas aun yo os muestro un camino más excelente."
    }
  }
};

