
	
export const bib_verses = {
  "acts": {
    "8": {
      "1": "Y SAULO consentía en su muerte. Y en aquel día se hizo una grande persecución en la iglesia que estaba en Jerusalem; y todos fueron esparcidos por las tierras de Judea y de Samaria, salvo los apóstoles.",
      "2": "Y llevaron á enterrar á Esteban varones piadosos, é hicieron gran llanto sobre él.",
      "3": "Entonces Saulo asolaba la iglesia, entrando por las casas: y trayendo hombres y mujeres, los entregaba en la cárcel.",
      "4": "Mas los que fueron esparcidos, iban por todas partes anunciando la palabra.",
      "5": "Entonces Felipe, descendiendo á la ciudad de Samaria, les predicaba á Cristo.",
      "6": "Y las gentes escuchaban atentamente unánimes las cosas que decía Felipe, oyendo y viendo las señales que hacía.",
      "7": "Porque de muchos que tenían espíritus inmundos, salían éstos dando grandes voces; y muchos paralíticos y cojos eran sanados:",
      "8": "Así que había gran gozo en aquella ciudad.",
      "9": "Y había un hombre llamado Simón, el cual había sido antes mágico en aquella ciudad, y había engañado la gente de Samaria, diciéndose ser algún grande:",
      "10": "Al cual oían todos atentamente desde al más pequeño hasta el más grande, diciendo: Este es la gran virtud de Dios.",
      "11": "Y le estaban atentos, porque con sus artes mágicas los había embelesado mucho tiempo.",
      "12": "Mas cuando creyeron á Felipe, que anunciaba el evangelio del reino de Dios y el nombre de Jesucristo, se bautizaban hombres y mujeres.",
      "13": "El mismo Simón creyó también entonces, y bautizándose, se llegó á Felipe: y viendo los milagros y grandes maravillas que se hacían, estaba atónito.",
      "14": "Y los apóstoles que estaban en Jerusalem, habiendo oído que Samaria había recibido la palabra de Dios, les enviaron á Pedro y á Juan:",
      "15": "Los cuales venidos, oraron por ellos, para que recibiesen el Espíritu Santo;",
      "16": "(Porque aun no había descendido sobre ninguno de ellos, mas solamente eran bautizados en el nombre de Jesús.)",
      "17": "Entonces les impusieron las manos, y recibieron el Espíritu Santo.",
      "18": "Y como vió Simón que por la imposición de las manos de los apóstoles se daba el Espíritu Santo, les ofreció dinero,",
      "19": "Diciendo: Dadme también á mí esta potestad, que á cualquiera que pusiere las manos encima, reciba el Espíritu Santo.",
      "20": "Entonces Pedro le dijo: Tu dinero perezca contigo, que piensas que el don de Dios se gane por dinero.",
      "21": "No tienes tú parte ni suerte en este negocio; porque tu corazón no es recto delante de Dios.",
      "22": "Arrepiéntete pues de esta tu maldad, y ruega á Dios, si quizás te será perdonado el pensamiento de tu corazón.",
      "23": "Porque en hiel de amargura y en prisión de maldad veo que estás.",
      "24": "Respondiendo entonces Simón, dijo: Rogad vosotros por mí al Señor, que ninguna cosa de estas que habéis dicho, venga sobre mí.",
      "25": "Y ellos, habiendo testificado y hablado la palabra de Dios, se volvieron á Jerusalem, y en muchas tierras de los Samaritanos anunciaron el evangelio.",
      "26": "Empero el ángel de Señor habló á Felipe, diciendo: Levántate y ve hacia el mediodía, al camino que desciende de Jerusalem á Gaza, el cual es desierto.",
      "27": "Entonces él se levantó, y fué: y he aquí un Etiope, eunuco, gobernador de Candace, reina de los Etiopes, el cual era puesto sobre todos sus tesoros, y había venido á adorar á Jerusalem,",
      "28": "Se volvía sentado en su carro, y leyendo el profeta Isaías.",
      "29": "Y el Espíritu dijo á Felipe: Llégate, y júntate á este carro.",
      "30": "Y acudiendo Felipe, le oyó que leía el profeta Isaías, y dijo: Mas ¿entiendes lo que lees?",
      "31": "Y dijo: ¿Y cómo podré, si alguno no me enseñare? Y rogó á Felipe que subiese, y se sentase con él.",
      "32": "Y el lugar de la Escritura que leía, era éste: Como oveja á la muerte fué llevado; Y como cordero mudo delante del que le trasquila, Así no abrió su boca:",
      "33": "En su humillación su juicio fué quitado: Mas su generación, ¿quién la contará? Porque es quitada de la tierra su vida.",
      "34": "Y respondiendo el eunuco á Felipe, dijo: Ruégote ¿de quién el profeta dice esto? ¿de sí, ó de otro alguno?",
      "35": "Entonces Felipe, abriendo su boca, y comenzando desde esta escritura, le anunció el evangelio de Jesús.",
      "36": "Y yendo por el camino, llegaron á cierta agua; y dijo el eunuco: He aquí agua; ¿qué impide que yo sea bautizado?",
      "37": "Y Felipe dijo: Si crees de todo corazón, bien puedes. Y respondiendo, dijo: Creo que Jesucristo es el Hijo de Dios.",
      "38": "Y mandó parar el carro: y descendieron ambos al agua, Felipe y el eunuco; y bautizóle.",
      "39": "Y como subieron del agua, el Espíritu del Señor arrebató á Felipe; y no le vió más el eunuco, y se fué por su camino gozoso.",
      "40": "Felipe empero se halló en Azoto: y pasando, anunciaba el evangelio en todas las ciudades, hasta que llegó á Cesarea."
    },
    "9": {
      "1": "Y SAULO, respirando aún amenazas y muerte contra los discípulos del Señor, vino al príncipe de los sacerdotes,",
      "2": "Y demandó de él letras para Damasco á las sinagogas, para que si hallase algunos hombres ó mujeres de esta secta, los trajese presos á Jerusalem.",
      "3": "Y yendo por el camino, aconteció que llegando cerca de Damasco, súbitamente le cercó un resplandor de luz del cielo;",
      "4": "Y cayendo en tierra, oyó una voz que le decía: Saulo, Saulo, ¿por qué me persigues?",
      "5": "Y él dijo: ¿Quién eres, Señor? Y él dijo: Yo soy Jesús á quien tú persigues: dura cosa te es dar coses contra el aguijón.",
      "6": "El, temblando y temeroso, dijo: ¿Señor, qué quieres que haga? Y el Señor le dice: Levántate y entra en la ciudad, y se te dirá lo que te conviene hacer.",
      "7": "Y los hombres que iban con Saul, se pararon atónitos, oyendo á la verdad la voz, mas no viendo á nadie.",
      "8": "Entonces Saulo se levantó de tierra, y abriendo los ojos, no veía á nadie: así que, llevándole por la mano, metiéronle en Damasco;",
      "9": "Donde estuvo tres días sin ver, y no comió, ni bebió.",
      "10": "Había entonces un discípulo en Damasco llamado Ananías, al cual el Señor dijo en visión: Ananías. Y él respondió: Heme aquí, Señor.",
      "11": "Y el Señor le dijo: Levántate, y ve á la calle que se llama la Derecha, y busca en casa de Judas á uno llamado Saulo, de Tarso: porque he aquí, él ora;",
      "12": "Y ha visto en visión un varón llamado Ananías, que entra y le pone la mano encima, para que reciba la vista.",
      "13": "Entonces Ananías respondió: Señor, he oído á muchos acerca de este hombre, cuántos males ha hecho á tus santos en Jerusalem:",
      "14": "Y aun aquí tiene facultad de los príncipes de los sacerdotes de prender á todos los que invocan tu nombre.",
      "15": "Y le dijo el Señor: Ve: porque instrumento escogido me es éste, para que lleve mi nombre en presencia de los Gentiles, y de reyes, y de los hijos de Israel:",
      "16": "Porque yo le mostraré cuánto le sea menester que padezca por mi nombre.",
      "17": "Ananías entonces fué, y entró en la casa, y poniéndole las manos encima, dijo: Saulo hermano, el Señor Jesús, que te apareció en el camino por donde venías, me ha enviado para que recibas la vista y seas lleno de Espíritu Santo.",
      "18": "Y luego le cayeron de los ojos como escamas, y recibió al punto la vista: y levantándose, fué bautizado.",
      "19": "Y como comió, fué confortado. Y estuvo Saulo por algunos días con los discípulos que estaban en Damasco.",
      "20": "Y luego en las sinagogas predicaba á Cristo, diciendo que éste era el Hijo de Dios.",
      "21": "Y todos los que le oían estaban atónitos, y decían: ¿No es éste el que asolaba en Jerusalem á los que invocaban este nombre, y á eso vino acá, para llevarlos presos á los príncipes de los sacerdotes?",
      "22": "Empero Saulo mucho más se esforzaba, y confundía á los Judíos que moraban en Damasco, afirmando que éste es el Cristo.",
      "23": "Y como pasaron muchos días, los Judíos hicieron entre sí consejo de matarle;",
      "24": "Mas las asechanzas de ellos fueron entendidas de Saulo. Y ellos guardaban las puertas de día y de noche para matarle.",
      "25": "Entonces los discípulos, tomándole de noche, le bajaron por el muro en una espuerta.",
      "26": "Y como vino á Jerusalem, tentaba de juntarse con los discípulos; mas todos tenían miedo de él, no creyendo que era discípulo.",
      "27": "Entonces Bernabé, tomándole, lo trajo á los apóstoles, y contóles cómo había visto al Señor en el camino, y que le había hablado, y cómo en Damasco había hablado confiadamente en el nombre de Jesús.",
      "28": "Y entraba y salía con ellos en Jerusalem;",
      "29": "Y hablaba confiadamente en el nombre del Señor: y disputaba con los Griegos; mas ellos procuraban matarle.",
      "30": "Lo cual, como los hermanos entendieron, le acompañaron hasta Cesarea, y le enviaron á Tarso.",
      "31": "Las iglesias entonces tenían paz por toda Judea y Galilea y Samaria, y eran edificadas, andando en el temor del Señor; y con consuelo del Espíritu Santo eran multiplicadas.",
      "32": "Y aconteció que Pedro, andándolos á todos, vino también á los santos que habitaban en Lydda.",
      "33": "Y halló allí á uno que se llamaba Eneas, que hacía ocho años que estaba en cama, que era paralítico.",
      "34": "Y le dijo Pedro: Eneas, Jesucristo te sana; levántate, y hazte tu cama. Y luego se levantó.",
      "35": "Y viéronle todos los que habitaban en Lydda y en Sarona, los cuales se convirtieron al Señor.",
      "36": "Entonces en Joppe había una discípula llamada Tabita, que si lo declaras, quiere decir Dorcas. Esta era llena de buenas obras y de limosnas que hacía.",
      "37": "Y aconteció en aquellos días que enfermando, murió; á la cual, después de lavada, pusieron en una sala.",
      "38": "Y como Lydda estaba cerca de Joppe, los discípulos, oyendo que Pedro estaba allí, le enviaron dos hombres, rogándole: No te detengas en venir hasta nosotros.",
      "39": "Pedro entonces levantándose, fué con ellos: y llegado que hubo, le llevaron á la sala, donde le rodearon todas las viudas, llorando y mostrando las túnicas y los vestidos que Dorcas hacía cuando estaba con ellas.",
      "40": "Entonces echados fuera todos, Pedro puesto de rodillas, oró; y vuelto al cuerpo, dijo: Tabita, levántate. Y ella abrió los ojos, y viendo á Pedro, incorporóse.",
      "41": "Y él le dió la mano, y levantóla: entonces llamando á los santos y las viudas, la presentó viva.",
      "42": "Esto fué notorio por toda Joppe; y creyeron muchos en el Señor.",
      "43": "Y aconteció que se quedó muchos días en Joppe en casa de un cierto Simón, curtidor."
    },
    "10": {
      "1": "Y HABIA un varón en Cesarea llamado Cornelio, centurión de la compañía que se llamaba la Italiana,",
      "2": "Pío y temeroso de Dios con toda su casa, y que hacía muchas limosnas al pueblo, y oraba á Dios siempre.",
      "3": "Este vió en visión manifiestamente, como á la hora nona del día, que un ángel de Dios entraba á él, y le decía: Cornelio.",
      "4": "Y él, puestos en él los ojos, espantado, dijo: ¿Qué es, Señor? Y díjole: Tus oraciones y tus limosnas han subido en memoria á la presencia de Dios.",
      "5": "Envía pues ahora hombres á Joppe, y haz venir á un Simón, que tiene por sobrenombre Pedro.",
      "6": "Este posa en casa de un Simón, curtidor, que tiene su casa junto á la mar: él te dirá lo que te conviene hacer.",
      "7": "E ido el ángel que hablaba con Cornelio, llamó dos de sus criados, y un devoto soldado de los que le asistían;",
      "8": "A los cuales, después de habérselo contado todo, los envió á Joppe.",
      "9": "Y al día siguiente, yendo ellos su camino, y llegando cerca de la ciudad, Pedro subió á la azotea á orar, cerca de la hora de sexta;",
      "10": "Y aconteció que le vino una grande hambre, y quiso comer; pero mientras disponían, sobrevínole un éxtasis;",
      "11": "Y vió el cielo abierto, y que descendía un vaso, como un gran lienzo, que atado de los cuatro cabos era bajado á la tierra;",
      "12": "En el cual había de todos los animales cuadrúpedos de la tierra, y reptiles, y aves del cielo.",
      "13": "Y le vino una voz: Levántate, Pedro, mata y come.",
      "14": "Entonces Pedro dijo: Señor, no; porque ninguna cosa común é inmunda he comido jamás.",
      "15": "Y volvió la voz hacia él la segunda vez: Lo que Dios limpió, no lo llames tú común.",
      "16": "Y esto fué hecho por tres veces; y el vaso volvió á ser recogido en el cielo.",
      "17": "Y estando Pedro dudando dentro de sí qué sería la visión que había visto, he aquí, los hombres que habían sido enviados por Cornelio, que, preguntando por la casa de Simón, llegaron á la puerta.",
      "18": "Y llamando, preguntaron si un Simón que tenía por sobrenombre Pedro, posaba allí.",
      "19": "Y estando Pedro pensando en la visión, le dijo el Espíritu: He aquí, tres hombres te buscan.",
      "20": "Levántate, pues, y desciende, y no dudes ir con ellos; porque yo los he enviado.",
      "21": "Entonces Pedro, descendiendo á los hombres que eran enviados por Cornelio, dijo: He aquí, yo soy el que buscáis: ¿cuál es la causa por la que habéis venido?",
      "22": "Y ellos dijeron: Cornelio, el centurión, varón justo y temeroso de Dios, y que tiene testimonio de toda la nación de los Judíos, ha recibido respuesta por un santo ángel, de hacerte venir á su casa, y oir de ti palabras.",
      "23": "Entonces metiéndolos dentro, los hospedó. Y al día siguiente, levantándose, se fué con ellos; y le acompañaron algunos de los hermanos de Joppe.",
      "24": "Y al otro día entraron en Cesarea. Y Cornelio los estaba esperando, habiendo llamado á sus parientes y los amigos más familiares.",
      "25": "Y como Pedro entró, salió Cornelio á recibirle; y derribándose á sus pies, adoró.",
      "26": "Mas Pedro le levantó, diciendo: Levántate; yo mismo también soy hombre.",
      "27": "Y hablando con él, entró, y halló á muchos que se habían juntado.",
      "28": "Y les dijo: Vosotros sabéis que es abominable á un varón Judío juntarse ó llegarse á extranjero; mas me ha mostrado Dios que á ningún hombre llame común ó inmundo;",
      "29": "Por lo cual, llamado, he venido sin dudar. Así que pregunto: ¿por qué causa me habéis hecho venir?",
      "30": "Entonces Cornelio dijo: Cuatro días ha que á esta hora yo estaba ayuno; y á la hora de nona estando orando en mi casa, he aquí un varón se puso delante de mí en vestido resplandeciente.",
      "31": "Y dijo: Cornelio, tu oración es oída, y tus limosnas han venido en memoria en la presencia de Dios.",
      "32": "Envía pues á Joppe, y haz venir á un Simón, que tiene por sobrenombre Pedro; éste posa en casa de Simón, curtidor, junto á la mar; el cual venido, te hablará.",
      "33": "Así que, luego envié á ti; y tú has hecho bien en venir. Ahora pues, todos nosotros estamos aquí en la presencia de Dios, para oir todo lo que Dios te ha mandado.",
      "34": "Entonces Pedro, abriendo su boca, dijo: Por verdad hallo que Dios no hace acepción de personas;",
      "35": "Sino que de cualquiera nación que le teme y obra justicia, se agrada.",
      "36": "Envió palabra Dios á los hijos de Israel, anunciando la paz por Jesucristo; éste es el Señor de todos.",
      "37": "Vosotros sabéis lo que fué divulgado por toda Judea; comenzando desde Galilea después del bautismo que Juan predicó,",
      "38": "Cuanto á Jesús de Nazaret; cómo le ungió Dios de Espíritu Santo y de potencia; el cual anduvo haciendo bienes, y sanando á todos los oprimidos del diablo; porque Dios era con él.",
      "39": "Y nosotros somos testigos de todas las cosas que hizo en la tierra de Judea, y en Jerusalem; al cual mataron colgándole en un madero.",
      "40": "A éste levantó Dios al tercer día, é hizo que apareciese manifiesto,",
      "41": "No á todo el pueblo, sino á los testigos que Dios antes había ordenado, es á saber, á nosotros que comimos y bebimos con él, después que resucitó de los muertos.",
      "42": "Y nos mandó que predicásemos al pueblo, y testificásemos que él es el que Dios ha puesto por Juez de vivos y muertos.",
      "43": "A éste dan testimonio todos los profetas, de que todos los que en él creyeren, recibirán perdón de pecados por su nombre.",
      "44": "Estando aún hablando Pedro estas palabras, el Espíritu Santo cayó sobre todos los que oían el sermón.",
      "45": "Y se espantaron los fieles que eran de la circuncisión, que habían venido con Pedro, de que también sobre los Gentiles se derramase el don del Espíritu Santo.",
      "46": "Porque los oían que hablaban en lenguas, y que magnificaban á Dios.",
      "47": "Entonces respondió Pedro: ¿Puede alguno impedir el agua, para que no sean bautizados éstos que han recibido el Espíritu Santo también como nosotros?",
      "48": "Y les mandó bautizar en el nombre del Señor Jesús. Entonces le rogaron que se quedase por algunos días."
    },
    "11": {
      "1": "Y OYERON los apóstoles y los hermanos que estaban en Judea, que también los Gentiles habían recibido la palabra de Dios.",
      "2": "Y como Pedro subió á Jerusalem, contendían contra él los que eran de la circuncisión,",
      "3": "Diciendo: ¿Por qué has entrado á hombres incircuncisos, y has comido con ellos?",
      "4": "Entonces comenzando Pedro, les declaró por orden lo pasado, diciendo:",
      "5": "Estaba yo en la ciudad de Joppe orando, y vi en rapto de entendimiento una visión: un vaso, como un gran lienzo, que descendía, que por los cuatro cabos era abajado del cielo, y venía hasta mí.",
      "6": "En el cual como puse los ojos, consideré y vi animales terrestres de cuatro pies, y fieras, y reptiles, y aves del cielo.",
      "7": "Y oí una voz que me decía: Levántate, Pedro, mata y come.",
      "8": "Y dije: Señor, no; porque ninguna cosa común ó inmunda entró jamás en mi boca.",
      "9": "Entonces la voz me respondió del cielo segunda vez: Lo que Dios limpió, no lo llames tú común.",
      "10": "Y esto fué hecho por tres veces: y volvió todo á ser tomado arriba en el cielo.",
      "11": "Y he aquí, luego sobrevinieron tres hombres á la casa donde yo estaba, enviados á mí de Cesarea.",
      "12": "Y el Espíritu me dijo que fuese con ellos sin dudar. Y vinieron también conmigo estos seis hermanos, y entramos en casa de un varón,",
      "13": "El cual nos contó cómo había visto un ángel en su casa, que se paró, y le dijo: Envía á Joppe, y haz venir á un Simón que tiene por sobrenombre Pedro;",
      "14": "El cual te hablará palabras por las cuales serás salvo tu, y toda tu casa.",
      "15": "Y como comencé á hablar, cayó el Espíritu Santo sobre ellos también, como sobre nosotros al principio.",
      "16": "Entonces me acordé del dicho del Señor, como dijo: Juan ciertamente bautizó en agua; mas vosotros seréis bautizados en Espíritu Santo.",
      "17": "Así que, si Dios les dió el mismo don también como á nosotros que hemos creído en el Señor Jesucristo, ¿quién era yo que pudiese estorbar á Dios?",
      "18": "Entonces, oídas estas cosas, callaron, y glorificaron á Dios, diciendo: De manera que también á los Gentiles ha dado Dios arrepentimiento para vida.",
      "19": "Y los que habían sido esparcidos por causa de la tribulación que sobrevino en tiempo de Esteban, anduvieron hasta Fenicia, y Cipro, y Antioquía, no hablando á nadie la palabra, sino sólo á los Judíos.",
      "20": "Y de ellos había unos varones Ciprios y Cirenences, los cuales como entraron en Antioquía, hablaron á los Griegos, anunciando el evangelio del Señor Jesús.",
      "21": "Y la mano del Señor era con ellos: y creyendo, gran número se convirtió al Señor.",
      "22": "Y llegó la fama de estas cosas á oídos de la iglesia que estaba en Jerusalem: y enviaron á Bernabé que fuese hasta Antioquía.",
      "23": "El cual, como llegó, y vió la gracia de Dios, regocijóse; y exhortó á todos á que permaneciesen en el propósito del corazón en el Señor.",
      "24": "Porque era varón bueno, y lleno de Espíritu Santo y de fe: y mucha compañía fué agregada al Señor.",
      "25": "Después partió Bernabé á Tarso á buscar á Saulo; y hallado, le trajo á Antioquía.",
      "26": "Y conversaron todo un año allí con la iglesia, y enseñaron á mucha gente; y los discípulos fueron llamados Cristianos primeramente en Antioquía.",
      "27": "Y en aquellos días descendieron de Jerusalem profetas á Antioquía.",
      "28": "Y levantándose uno de ellos, llamado Agabo, daba á entender por Espíritu, que había de haber una grande hambre en toda la tierra habitada: la cual hubo en tiempo de Claudio.",
      "29": "Entonces los discípulos, cada uno conforme á lo que tenía, determinaron enviar subsidio á los hermanos que habitaban en Judea:",
      "30": "Lo cual asimismo hicieron, enviándolo á los ancianos por mano de Bernabé y de Saulo."
    },
    "12": {
      "1": "Y EN el mismo tiempo el rey Herodes echó mano á maltratar algunos de la iglesia.",
      "2": "Y mató á cuchillo á Jacobo, hermano de Juan.",
      "3": "Y viendo que había agradado á los Judíos, pasó adelante para prender también á Pedro. Eran entonces los días de los ázimos.",
      "4": "Y habiéndole preso, púsole en la cárcel, entregándole á cuatro cuaterniones de soldados que le guardasen; queriendo sacarle al pueblo después de la Pascua.",
      "5": "Así que, Pedro era guardado en la cárcel; y la iglesia hacía sin cesar oración á Dios por él.",
      "6": "Y cuando Herodes le había de sacar, aquella misma noche estaba Pedro durmiendo entre dos soldados, preso con dos cadenas, y los guardas delante de la puerta, que guardaban la cárcel.",
      "7": "Y he aquí, el ángel del Señor sobrevino, y una luz resplandeció en la cárcel; é hiriendo á Pedro en el lado, le despertó, diciendo: Levántate prestamente. Y las cadenas se le cayeron de las manos.",
      "8": "Y le dijo el ángel: Cíñete, y átate tus sandalias. Y lo hizo así. Y le dijo: Rodéate tu ropa, y sígueme.",
      "9": "Y saliendo, le seguía; y no sabía que era verdad lo que hacía el ángel, mas pensaba que veía visión.",
      "10": "Y como pasaron la primera y la segunda guardia, vinieron á la puerta de hierro que va á la ciudad, la cual se les abrió de suyo: y salidos, pasaron una calle; y luego el ángel se apartó de él.",
      "11": "Entonces Pedro, volviendo en sí, dijo: Ahora entiendo verdaderamente que el Señor ha enviado su ángel, y me ha librado de la mano de Herodes, y de todo el pueblo de los Judíos que me esperaba.",
      "12": "Y habiendo considerado esto, llegó á casa de María la madre de Juan, el que tenía por sobrenombre Marcos, donde muchos estaban juntos orando.",
      "13": "Y tocando Pedro á la puerta del patio, salió una muchacha, para escuchar, llamada Rhode:",
      "14": "La cual como conoció la voz de Pedro, de gozo no abrió el postigo, sino corriendo adentro, dió nueva de que Pedro estaba al postigo.",
      "15": "Y ellos le dijeron: Estás loca. Mas ella afirmaba que así era. Entonces ellos decían: Su ángel es.",
      "16": "Mas Pedro perseveraba en llamar: y cuando abrieron, viéronle, y se espantaron.",
      "17": "Mas él haciéndoles con la mano señal de que callasen, les contó cómo el Señor le había sacado de la cárcel. Y dijo: Haced saber esto á Jacobo y á los hermanos. Y salió, y partió á otro lugar.",
      "18": "Luego que fué de día, hubo no poco alboroto entre los soldados sobre qué se había hecho de Pedro.",
      "19": "Mas Herodes, como le buscó y no le halló, hecha inquisición de los guardas, los mandó llevar. Después descendiendo de Judea á Cesarea, se quedó allí.",
      "20": "Y Herodes estaba enojado contra los de Tiro y los de Sidón: mas ellos vinieron concordes á él, y sobornado Blasto, que era el camarero del rey, pedían paz; porque las tierras de ellos eran abastecidas por las del rey.",
      "21": "Y un día señalado, Herodes vestido de ropa real, se sentó en el tribunal, y arengóles.",
      "22": "Y el pueblo aclamaba: Voz de Dios, y no de hombre.",
      "23": "Y luego el ángel del Señor le hirió, por cuanto no dió la gloria á Dios; y espiró comido de gusanos.",
      "24": "Mas la palabra del Señor crecía y era multiplicada.",
      "25": "Y Bernabé y Saulo volvieron de Jerusalem cumplido su servicio, tomando también consigo á Juan, el que tenía por sobrenombre Marcos."
    },
    "13": {
      "1": "HABIA entonces en la iglesia que estaba en Antioquía, profetas y doctores: Bernabé, y Simón el que se llamaba Niger, y Lucio Cireneo, y Manahén, que había sido criado con Herodes el tetrarca, y Saulo.",
      "2": "Ministrando pues éstos al Señor, y ayunando, dijo el Espíritu Santo: Apartadme á Bernabé y á Saulo para la obra para la cual los he llamado.",
      "3": "Entonces habiendo ayunado y orado, y puesto las manos encima de ellos, despidiéronlos.",
      "4": "Y ellos, enviados así por el Espíritu Santo, descendieron á Seleucia: y de allí navegaron á Cipro.",
      "5": "Y llegados á Salamina, anunciaban la palabra de Dios en las sinagogas de los Judíos: y tenían también á Juan en el ministerio.",
      "6": "Y habiendo atravesado toda la isla hasta Papho, hallaron un hombre mago, falso profeta, Judío, llamado Bar jesús;",
      "7": "El cual estaba con el procónsul Sergio Paulo, varón prudente. Este, llamando á Bernabé y á Saulo, deseaba oír la palabra de Dios.",
      "8": "Mas les resistía Elimas el encantador (que así se interpreta su nombre), procurando apartar de la fe al procónsul.",
      "9": "Entonces Saulo, que también es Pablo, lleno del Espíritu Santo, poniendo en él los ojos,",
      "10": "Dijo: Oh, lleno de todo engaño y de toda maldad, hijo del diablo, enemigo de toda justicia, ¿no cesarás de trastornar los caminos rectos del Señor?",
      "11": "Ahora pues, he aquí la mano del Señor es contra ti, y serás ciego, que no veas el sol por tiempo. Y luego cayeron en él obscuridad y tinieblas; y andando alrededor, buscaba quién le condujese por la mano.",
      "12": "Entonces el procónsul, viendo lo que había sido hecho, creyó, maravillado de la doctrina del Señor.",
      "13": "Y partidos de Papho, Pablo y sus compañeros arribaron á Perge de Pamphylia: entonces Juan, apartándose de ellos, se volvió á Jerusalem.",
      "14": "Y ellos pasando de Perge, llegaron á Antioquía de Pisidia, y entrando en la sinagoga un día de sábado, sentáronse.",
      "15": "Y después de la lectura de la ley y de los profetas, los príncipes de la sinagoga enviaron á ellos, diciendo: Varones hermanos, si tenéis alguna palabra de exhortación para el pueblo, hablad.",
      "16": "Entonces Pablo, levantándose, hecha señal de silencio con la mano, dice: Varones Israelitas, y los que teméis á Dios, oid:",
      "17": "El Dios del pueblo de Israel escogió á nuestros padres, y ensalzó al pueblo, siendo ellos extranjeros en la tierra de Egipto, y con brazo levantado los sacó de ella.",
      "18": "Y por tiempo como de cuarenta años soportó sus costumbres en el desierto;",
      "19": "Y destruyendo siete naciones en la tierra de Canaán, les repartió por suerte la tierra de ellas.",
      "20": "Y después, como por cuatrocientos y cincuenta años, dió les jueces hasta el profeta Samuel.",
      "21": "Y entonces demandaron rey; y les dió Dios á Saúl, hijo de Cis, varón de la tribu de Benjamín, por cuarenta años.",
      "22": "Y quitado aquél, levantóles por rey á David, el que dió también testimonio, diciendo: He hallado á David, hijo de Jessé, varón conforme á mi corazón, el cual hará todo lo que yo quiero.",
      "23": "De la simiente de éste, Dios, conforme á la promesa, levantó á Jesús por Salvador á Israel;",
      "24": "Predicando Juan delante de la faz de su venida el bautismo de arrepentimiento á todo el pueblo de Israel.",
      "25": "Mas como Juan cumpliese su carrera, dijo: ¿Quién pensáis que soy? No soy yo él; mas he aquí, viene tras mí uno, cuyo calzado de los pies no soy digno de desatar.",
      "26": "Varones hermanos, hijos del linaje de Abraham, y los que entre vosotros temen á Dios, á vosotros es enviada la palabra de esta salud.",
      "27": "Porque los que habitaban en Jerusalem, y sus príncipes, no conociendo á éste, y las voces de los profetas que se leen todos los sábados, condenándo les, las cumplieron.",
      "28": "Y sin hallar en él causa de muerte, pidieron á Pilato que le matasen.",
      "29": "Y habiendo cumplido todas las cosas que de él estaban escritas, quitándolo del madero, lo pusieron en el sepulcro.",
      "30": "Mas Dios le levantó de los muertos.",
      "31": "Y él fué visto por muchos días de los que habían subido juntamente con él de Galilea á Jerusalem, los cuales son sus testigos al pueblo.",
      "32": "Y nosotros también os anunciamos el evangelio de aquella promesa que fué hecha á los padres,",
      "33": "La cual Dios ha cumplido á los hijos de ellos, á nosotros, resucitando á Jesús: como también en el salmo segundo está escrito: Mi hijo eres tú, yo te he engendrado hoy.",
      "34": "Y que le levantó de los muertos para nunca más volver á corrupción, así lo dijo: Os daré las misericordias fieles de David.",
      "35": "Por eso dice también en otro lugar: No permitirás que tu Santo vea corrupción.",
      "36": "Porque á la verdad David, habiendo servido en su edad á la voluntad de Dios, durmió, y fué juntado con sus padres, y vió corrupción.",
      "37": "Mas aquel que Dios levantó, no vió corrupción.",
      "38": "Séaos pues notorio, varones hermanos, que por éste os es anunciada remisión de pecados,",
      "39": "Y de todo lo que por la ley de Moisés no pudisteis ser justificados, en éste es justificado todo aquel que creyere.",
      "40": "Mirad, pues, que no venga sobre vosotros lo que está dicho en los profetas;",
      "41": "Mirad, oh menospreciadores, y entonteceos, y desvaneceos; Porque yo obro una obra en vuestros días, Obra que no creeréis, si alguien os la contare.",
      "42": "Y saliendo ellos de la sinagoga de los Judíos, los Gentiles les rogaron que el sábado siguiente les hablasen estas palabras.",
      "43": "Y despedida la congregación, muchos de los Judíos y de los religiosos prosélitos siguieron á Pablo y á Bernabé; los cuales hablándoles, les persuadían que permaneciesen en la gracia de Dios.",
      "44": "Y el sábado siguiente se juntó casi toda la ciudad á oir la palabra de Dios.",
      "45": "Mas los Judíos, visto el gentío, llenáronse de celo, y se oponían á lo que Pablo decía, contradiciendo y blasfemando.",
      "46": "Entonces Pablo y Bernabé, usando de libertad, dijeron: A vosotros á la verdad era menester que se os hablase la palabra de Dios; mas pues que la desecháis, y os juzgáis indignos de la vida eterna, he aquí, nos volvemos á los Gentiles.",
      "47": "Porque así nos ha mandado el Señor, diciendo: Te he puesto para luz de los Gentiles, Para que seas salud hasta lo postrero de la tierra.",
      "48": "Y los Gentiles oyendo esto, fueron gozosos, y glorificaban la palabra del Señor: y creyeron todos los que estaban ordenados para vida eterna.",
      "49": "Y la palabra del Señor era sembrada por toda aquella provincia.",
      "50": "Mas los Judíos concitaron mujeres pías y honestas, y á los principales de la ciudad, y levantaron persecución contra Pablo y Bernabé, y los echaron de sus términos.",
      "51": "Ellos entonces sacudiendo en ellos el polvo de sus pies, vinieron á Iconio.",
      "52": "Y los discípulos estaban llenos de gozo, y del Espíritu Santo."
    },
    "14": {
      "1": "Y ACONTECIO en Iconio, que entrados juntamente en la sinagoga de los Judíos, hablaron de tal manera, que creyó una grande multitud de Judíos, y asimismo de Griegos.",
      "2": "Mas los Judíos que fueron incrédulos, incitaron y corrompieron los ánimos de los Gentiles contra los hermanos.",
      "3": "Con todo eso se detuvieron allí mucho tiempo, confiados en el Señor, el cual daba testimonio á la palabra de su gracia, dando que señales y milagros fuesen hechos por las manos de ellos.",
      "4": "Mas el vulgo de la ciudad estaba dividido; y unos eran con los Judíos, y otros con los apóstoles.",
      "5": "Y haciendo ímpetu los Judíos y los Gentiles juntamente con sus príncipes, para afrentarlos y apedrearlos,",
      "6": "Habiéndolo entendido, huyeron á Listra y Derbe, ciudades de Licaonia, y por toda la tierra alrededor.",
      "7": "Y allí predicaban el evangelio.",
      "8": "Y un hombre de Listra, impotente de los pies, estaba sentado, cojo desde el vientre de su madre, que jamás había andado.",
      "9": "Este oyó hablar á Pablo; el cual, como puso los ojos en él, y vió que tenía fe para ser sano,",
      "10": "Dijo á gran voz: Levántate derecho sobre tus pies. Y saltó, y anduvo.",
      "11": "Entonces las gentes, visto lo que Pablo había hecho, alzaron la voz, diciendo en lengua licaónica: Dioses semejantes á hombres han descendido á nosotros.",
      "12": "Y á Bernabé llamaban Júpiter, y á Pablo, Mercurio, porque era el que llevaba la palabra.",
      "13": "Y el sacerdote de Júpiter, que estaba delante de la ciudad de ellos, trayendo toros y guirnaldas delante de las puertas, quería con el pueblo sacrificar.",
      "14": "Y como lo oyeron los apóstoles Bernabé y Pablo, rotas sus ropas, se lanzaron al gentío, dando voces,",
      "15": "Y diciendo: Varones, ¿por qué hacéis esto? Nosotros también somos hombres semejantes á vosotros, que os anunciamos que de estas vanidades os convirtáis al Dios vivo, que hizo el cielo y la tierra, y la mar, y todo lo que está en ellos:",
      "16": "El cual en las edades pasadas ha dejado á todas las gentes andar en sus caminos;",
      "17": "Si bien no se dejó á sí mismo sin testimonio, haciendo bien, dándonos lluvias del cielo y tiempos fructíferos, hinchiendo de mantenimiento y de alegría nuestros corazones.",
      "18": "Y diciendo estas cosas, apenas apaciguaron el pueblo, para que no les ofreciesen sacrificio.",
      "19": "Entonces sobrevinieron unos Judíos de Antioquía y de Iconio, que persuadieron á la multitud, y habiendo apedreado á Pablo, le sacaron fuera de la ciudad, pensando que estaba muerto.",
      "20": "Mas rodeándole los discípulos, se levantó y entró en la ciudad y un día después, partió con Bernabé á Derbe.",
      "21": "Y como hubieron anunciado el evangelio á aquella ciudad, y enseñado á muchos, volvieron á Listra, y á Iconio, y á Antioquía,",
      "22": "Confirmando los ánimos de los discípulos, exhortándoles á que permaneciesen en la fe, y que es menester que por muchas tribulaciones entremos en el reino de Dios.",
      "23": "Y habiéndoles constituído ancianos en cada una de las iglesias, y habiendo orado con ayunos, los encomendaron al Señor en el cual habían creído.",
      "24": "Y pasando por Pisidia vinieron á Pamphylia.",
      "25": "Y habiendo predicado la palabra en Perge, descendieron á Atalia;",
      "26": "Y de allí navegaron á Antioquía, donde habían sido encomendados á la gracia de Dios para la obra que habían acabado.",
      "27": "Y habiendo llegado, y reunido la iglesia, relataron cuán grandes cosas había Dios hecho con ellos, y cómo había abierto á los Gentiles la puerta de la fe.",
      "28": "Y se quedaron allí mucho tiempo con los discípulos."
    },
    "15": {
      "1": "ENTONCES algunos que venían de Judea enseñaban á los hermanos: Que si no os circuncidáis conforme al rito de Moisés, no podéis ser salvos.",
      "2": "Así que, suscitada una disensión y contienda no pequeña á Pablo y á Bernabé contra ellos, determinaron que subiesen Pablo y Bernabé á Jerusalem, y algunos otros de ellos, á los apóstoles y á los ancianos, sobre esta cuestión.",
      "3": "Ellos, pues, habiendo sido acompañados de la iglesia, pasaron por la Fenicia y Samaria, contando la conversión de los Gentiles; y daban gran gozo á todos los hermanos.",
      "4": "Y llegados á Jerusalem, fueron recibidos de la iglesia y de los apóstoles y de los ancianos: y refirieron todas las cosas que Dios había hecho con ellos.",
      "5": "Mas algunos de la secta de los Fariseos, que habían creído, se levantaron, diciendo: Que es menester circuncidarlos, y mandarles que guarden la ley de Moisés.",
      "6": "Y se juntaron los apóstoles y los ancianos para conocer de este negocio.",
      "7": "Y habiendo habido grande contienda, levantándose Pedro, les dijo: Varones hermanos, vosotros sabéis cómo ya hace algún tiempo que Dios escogió que los Gentiles oyesen por mi boca la palabra del evangelio, y creyesen.",
      "8": "Y Dios, que conoce los corazones, les dió testimonio, dándoles el Espíritu Santo también como á nosotros;",
      "9": "Y ninguna diferencia hizo entre nosotros y ellos, purificando con la fe sus corazones.",
      "10": "Ahora pues, ¿por qué tentáis á Dios, poniendo sobre la cerviz de los discípulos yugo, que ni nuestros padres ni nosotros hemos podido llevar?",
      "11": "Antes por la gracia del Señor Jesús creemos que seremos salvos, como también ellos.",
      "12": "Entonces toda la multitud calló, y oyeron á Bernabé y á Pablo, que contaban cuán grandes maravillas y señales Dios había hecho por ellos entre los Gentiles.",
      "13": "Y después que hubieron callado, Jacobo respondió, diciendo: Varones hermanos, oidme:",
      "14": "Simón ha contado cómo Dios primero visitó á los Gentiles, para tomar de ellos pueblo para su nombre;",
      "15": "Y con esto concuerdan las palabras de los profetas, como está escrito:",
      "16": "Después de esto volveré Y restauraré la habitación de David, que estaba caída; Y repararé sus ruinas, Y la volveré á levantar;",
      "17": "Para que el resto de los hombres busque al Señor, Y todos los Gentiles, sobre los cuales es llamado mi nombre, Dice el Señor, que hace todas estas cosas.",
      "18": "Conocidas son á Dios desde el siglo todas sus obras.",
      "19": "Por lo cual yo juzgo, que los que de los Gentiles se convierten á Dios, no han de ser inquietados;",
      "20": "Sino escribirles que se aparten de las contaminaciones de los ídolos, y de fornicación, y de ahogado, y de sangre.",
      "21": "Porque Moisés desde los tiempos antiguos tiene en cada ciudad quien le predique en las sinagogas, donde es leído cada sábado.",
      "22": "Entonces pareció bien á los apóstoles y á los ancianos, con toda la iglesia, elegir varones de ellos, y enviarlos á Antioquía con Pablo y Bernabé: á Judas que tenía por sobrenombre Barsabas, y á Silas, varones principales entre los hermanos;",
      "23": "Y escribir por mano de ellos: Los apóstoles y los ancianos y los hermanos, á los hermanos de los Gentiles que están en Antioquía, y en Siria, y en Cilicia, salud:",
      "24": "Por cuanto hemos oído que algunos que han salido de nosotros, os han inquietado con palabras, trastornando vuestras almas, mandando circuncidaros y guardar la ley, á los cuales no mandamos;",
      "25": "Nos ha parecido, congregados en uno, elegir varones, y enviarlos á vosotros con nuestros amados Bernabé y Pablo,",
      "26": "Hombres que han expuesto sus vidas por el nombre de nuestro Señor Jesucristo.",
      "27": "Así que, enviamos á Judas y á Silas, los cuales también por palabra os harán saber lo mismo.",
      "28": "Que ha parecido bien al Espíritu Santo, y á nosotros, no imponeros ninguna carga más que estas cosas necesarias:",
      "29": "Que os abstengáis de cosas sacrificadas á ídolos, y de sangre, y de ahogado, y de fornicación; de las cuales cosas si os guardareis, bien haréis. Pasadlo bien.",
      "30": "Ellos entonces enviados, descendieron á Antioquía; y juntando la multitud, dieron la carta.",
      "31": "La cual, como leyeron, fueron gozosos de la consolación.",
      "32": "Judas también y Silas, como ellos también eran profetas, consolaron y confirmaron á los hermanos con abundancia de palabra.",
      "33": "Y pasando allí algún tiempo, fueron enviados de los hermanos á los apóstoles en paz.",
      "34": "Mas á Silas pareció bien el quedarse allí.",
      "35": "Y Pablo y Bernabé se estaban en Antioquía, enseñando la palabra del Señor y anunciando el evangelio con otros muchos.",
      "36": "Y después de algunos días, Pablo dijo á Bernabé: Volvamos á visitar á los hermanos por todas las ciudades en las cuales hemos anunciado la palabra del Señor, cómo están.",
      "37": "Y Bernabé quería que tomasen consigo á Juan, el que tenía por sobrenombre Marcos;",
      "38": "Mas á Pablo no le parecía bien llevar consigo al que se había apartado de ellos desde Pamphylia, y no había ido con ellos á la obra.",
      "39": "Y hubo tal contención entre ellos, que se apartaron el uno del otro; y Bernabé tomando á Marcos, navegó á Cipro.",
      "40": "Y Pablo escogiendo á Silas, partió encomendado de los hermanos á la gracia del Señor.",
      "41": "Y anduvo la Siria y la Cilicia, confirmando á las iglesias."
    },
    "16": {
      "1": "DESPUÉS llegó á Derbe, y á Listra: y he aquí, estaba allí un discípulo llamado Timoteo, hijo de una mujer Judía fiel, mas de padre Griego.",
      "2": "De éste daban buen testimonio los hermanos que estaban en Listra y en Iconio.",
      "3": "Este quiso Pablo que fuese con él; y tomándole, le circuncidó por causa de los Judíos que estaban en aquellos lugares; porque todos sabían que su padre era Griego.",
      "4": "Y como pasaban por las ciudades, les daban que guardasen los decretos que habían sido determinados por los apóstoles y los ancianos que estaban en Jerusalem.",
      "5": "Así que, las iglesias eran confirmadas en fe, y eran aumentadas en número cada día.",
      "6": "Y pasando á Phrygia y la provincia de Galacia, les fué prohibido por el Espíritu Santo hablar la palabra en Asia.",
      "7": "Y como vinieron á Misia, tentaron de ir á Bithynia; mas el Espíritu no les dejó.",
      "8": "Y pasando á Misia, descendieron á Troas.",
      "9": "Y fué mostrada á Pablo de noche una visión: Un varón Macedonio se puso delante, rogándole, y diciendo: Pasa á Macedonia, y ayúdanos.",
      "10": "Y como vió la visión, luego procuramos partir á Macedonia, dando por cierto que Dios nos llamaba para que les anunciásemos el evangelio.",
      "11": "Partidos pues de Troas, vinimos camino derecho á Samotracia, y el día siguiente á Neápolis;",
      "12": "Y de allí á Filipos, que es la primera ciudad de la parte de Macedonia, y una colonia; y estuvimos en aquella ciudad algunos días.",
      "13": "Y un día de sábado salimos de la puerta junto al río, donde solía ser la oración; y sentándonos, hablamos á las mujeres que se habían juntado.",
      "14": "Entonces una mujer llamada Lidia, que vendía púrpura en la ciudad de Tiatira, temerosa de Dios, estaba oyendo; el corazón de la cual abrió el Señor para que estuviese atenta á lo que Pablo decía.",
      "15": "Y cuando fué bautizada, y su familia, nos rogó, diciendo: Si habéis juzgado que yo sea fiel al Señor, entrad en mi casa, y posad: y constriñónos.",
      "16": "Y aconteció, que yendo nosotros á la oración, una muchacha que tenía espíritu pitónico, nos salió al encuentro, la cual daba grande ganancia á sus amos adivinando.",
      "17": "Esta, siguiendo á Pablo y á nosotros, daba voces, diciendo: Estos hombres son siervos del Dios Alto, los cuales os anuncian el camino de salud.",
      "18": "Y esto hacía por muchos días; mas desagradando á Pablo, se volvió y dijo al espíritu: Te mando en el nombre de Jesucristo, que salgas de ella. Y salió en la misma hora.",
      "19": "Y viendo sus amos que había salido la esperanza de su ganancia, prendieron á Pablo y á Silas, y los trajeron al foro, al magistrado;",
      "20": "Y presentándolos á los magistrados, dijeron: Estos hombres, siendo Judíos, alborotan nuestra ciudad,",
      "21": "Y predican ritos, los cuales no nos es lícito recibir ni hacer, pues somos Romanos.",
      "22": "Y agolpóse el pueblo contra ellos: y los magistrados rompiéndoles sus ropas, les mandaron azotar con varas.",
      "23": "Y después que los hubieron herido de muchos azotes, los echaron en la cárcel, mandando al carcelero que los guardase con diligencia:",
      "24": "El cual, recibido este mandamiento, los metió en la cárcel de más adentro; y les apretó los pies en el cepo.",
      "25": "Mas á media noche, orando Pablo y Silas, cantaban himnos á Dios: y los que estaban presos los oían.",
      "26": "Entonces fué hecho de repente un gran terremoto, de tal manera que los cimientos de la cárcel se movían; y luego todas las puertas se abrieron, y las prisiones de todos soltaron.",
      "27": "Y despertado el carcelero, como vió abiertas las puertas de la cárcel, sacando la espada se quería matar, pensando que los presos se habían huído.",
      "28": "Mas Pablo clamó á gran voz, diciendo: No te hagas ningún mal; que todos estamos aquí.",
      "29": "El entonces pidiendo luz, entró dentro, y temblando, derribóse á los pies de Pablo y de Silas;",
      "30": "Y sacándolos fuera, le dice: Señores, ¿qué es menester que yo haga para ser salvo?",
      "31": "Y ellos dijeron: Cree en el Señor Jesucristo, y serás salvo tú, y tu casa.",
      "32": "Y le hablaron la palabra del Señor, y á todos los que estan en su casa.",
      "33": "Y tomándolos en aquella misma hora de la noche, les lavó los azotes; y se bautizó luego él, y todos los suyos.",
      "34": "Y llevándolos á su casa, les puso la mesa: y se gozó de que con toda su casa había creído á Dios.",
      "35": "Y como fué, día, los magistrados enviaron los alguaciles, diciendo: Deja ir á aquellos hombres.",
      "36": "Y el carcelero hizo saber estas palabras á Pablo: Los magistrados han enviado á decir que seás sueltos: así que ahora salid, é id en paz.",
      "37": "Entonces Pablo les dijo: Azotados públicamente sin ser condenados, siendo hombres Romanos, nos echaron en la cárcel; y ¿ahora nos echan encubiertamente? No, de cierto, sino vengan ellos y sáquennos.",
      "38": "Y los alguaciles volvieron á decir á los magistrados estas palabras: y tuvieron miedo, oído que eran Romanos.",
      "39": "Y viniendo, les rogaron; y sacándolos, les pidieron que se saliesen de la ciudad.",
      "40": "Entonces salidos de la cárcel, entraron en casa de Lidia; y habiendo visto á los hermanos, los consolaron, y se salieron."
    },
    "17": {
      "1": "Y PASANDO por Amphípolis y Apolonia, llegaron á Tesalónica, donde estaba la sinagoga de los Judíos.",
      "2": "Y Pablo, como acostumbraba, entró á ellos, y por tres sábados disputó con ellos de las Escrituras,",
      "3": "Declarando y proponiendo, que convenía que el Cristo padeciese, y resucitase de los muertos; y que Jesús, el cual yo os anuncio, decía él, éste era el Cristo.",
      "4": "Y algunos de ellos creyeron, y se juntaron con Pablo y con Silas; y de los Griegos religiosos grande multitud, y mujeres nobles no pocas.",
      "5": "Entonces los Judíos que eran incrédulos, teniendo celos, tomaron consigo á algunos ociosos, malos hombres, y juntando compañía, alborotaron la ciudad; y acometiendo á la casa de Jasón, procuraban sacarlos al pueblo.",
      "6": "Mas no hallándolos, trajeron á Jasón y á algunos hermanos á los gobernadores de la ciudad, dando voces: Estos que alborotan el mundo, también han venido acá;",
      "7": "A los cuales Jasón ha recibido; y todos estos hacen contra los decretos de César, diciendo que hay otro rey, Jesús.",
      "8": "Y alborotaron al pueblo y á los gobernadores de la ciudad, oyendo estas cosas.",
      "9": "Mas recibida satisfacción de Jasón y de los demás, los soltaron.",
      "10": "Entonces los hermanos, luego de noche, enviaron á Pablo y á Silas á Berea; los cuales habiendo llegado, entraron en la sinagoga de los Judíos.",
      "11": "Y fueron estós más nobles que los que estaban en Tesalónica, pues recibieron la palabra con toda solicitud, escudriñando cada día las Escrituras, si estas cosas eran así.",
      "12": "Así que creyeron muchos de ellos; y mujeres Griegas de distinción, y no pocos hombres.",
      "13": "Mas como entendieron los Judíos de Tesalónica que también en Berea era anunciada la palabra de Dios por Pablo, fueron, y también allí tumultuaron al pueblo.",
      "14": "Empero luego los hermanos enviaron á Pablo que fuese como á la mar; y Silas y Timoteo se quedaron allí.",
      "15": "Y los que habían tomado á cargo á Pablo, le llevaron hasta Atenas; y tomando encargo para Silas y Timoteo, que viniesen á él lo más presto que pudiesen, partieron.",
      "16": "Y esperándolos Pablo en Atenas, su espíritu se deshacía en él viendo la ciudad dada á idolatría.",
      "17": "Así que, disputaba en la sinagoga con los Judíos y religiosos; y en la plaza cada día con los que le ocurrían.",
      "18": "Y algunos filósofos de los Epicúreos y de los Estóicos, disputaban con él; y unos decían: ¿Qué quiere decir este palabrero? Y otros: Parece que es predicador de nuevos dioses: porque les predicaba á Jesús y la resurrección.",
      "19": "Y tomándole, le trajeron al Areópago, diciendo: ¿Podremos saber qué sea esta nueva doctrina que dices?",
      "20": "Porque pones en nuestros oídos unas nuevas cosas: queremos pues saber qué quiere ser esto.",
      "21": "(Entonces todos los Atenienses y los huéspedes extranjeros, en ningun otra cosa entendían, sino ó en decir ó en oir alguna cosa nueva.)",
      "22": "Estando pues Pablo en medio del Areópago, dijo: Varones Atenienses, en todo os veo como más superticiosos;",
      "23": "Porque pasando y mirando vuestros santuarios, hallé también un altar en el cual estaba esta inscripción: AL DIOS NO CONOCIDO. Aquél pues, que vosotros honráis sin conocerle, á éste os anuncio yo.",
      "24": "El Dios que hizo el mundo y todas las cosas que en él hay, éste, como sea Señor del cielo y de la tierra, no habita en templos hechos de manos,",
      "25": "Ni es honrado con manos de hombres, necesitado de algo; pues él da á todos vida, y respiración, y todas las cosas;",
      "26": "Y de una sangre ha hecho todo el linaje de los hombres, para que habitasen sobre toda la faz de la tierra; y les ha prefijado el orden de los tiempos, y los términos de los habitación de ellos;",
      "27": "Para que buscasen á Dios, si en alguna manera, palpando, le hallen; aunque cierto no está lejos de cada uno de nosotros:",
      "28": "Porque en él vivimos, y nos movemos, y somos; como también algunos de vuestros poetas dijeron: Porque linaje de éste somos también.",
      "29": "Siendo pues linaje de Dios, no hemos de estimar la Divinidad ser semejante á oro, ó á plata, ó á piedra, escultura de artificio ó de imaginación de hombres.",
      "30": "Empero Dios, habiendo disimulado los tiempos de esta ignorancia, ahora denuncia á todos los hombres en todos los lugares que se arrepientan:",
      "31": "Por cuanto ha establecido un día, en el cual ha de juzgar al mundo con justicia, por aquel varón al cual determinó; dando fe á todos con haberle levantado de los muertos.",
      "32": "Y así como oyeron de la resurrección de los muertos, unos se burlaban, y otros decían: Te oiremos acerca de esto otra vez.",
      "33": "Y así Pablo se salió de en medio de ellos.",
      "34": "Mas algunos creyeron, juntándose con él; entre los cuales también fué Dionisio el del Areópago, y una mujer llamada Dámaris, y otros con ellos."
    },
    "18": {
      "1": "PASADAS estas cosas, Pablo partió de Atenas, y vino á Corinto.",
      "2": "Y hallando á un Judío llamado Aquila, natural del Ponto, que hacía poco que había venido de Italia, y á Priscila su mujer, (porque Claudio había mandado que todos los Judíos saliesen de Roma) se vino á ellos;",
      "3": "Y porque era de su oficio, posó con ellos, y trabajaba; porque el oficio de ellos era hacer tiendas.",
      "4": "Y disputaba en la sinagoga todos los sábados, y persuadía á Judíos y á Griegos.",
      "5": "Y cuando Silas y Timoteo vinieron de Macedonia, Pablo estaba constreñido por la palabra, testificando á los Judíos que Jesús era el Cristo.",
      "6": "Mas contradiciendo y blasfemando ellos, les dijo: sacudiendo sus vestidos: Vuestra sangre sea sobre vuestra cabeza; yo, limpio; desde ahora me iré á los Gentiles.",
      "7": "Y partiendo de allí, entró en casa de uno llamado Justo, temeroso de Dios, la casa del cual estaba junto á la sinagoga.",
      "8": "Y Crispo, él prepósito de la sinagoga, creyó al Señor con toda su casa: y muchos de los Corintios oyendo creían, y eran bautizados.",
      "9": "Entonces él Señor dijo de noche en visión á Pablo: No temas, sino habla, y no calles:",
      "10": "Porque yo estoy contigo, y ninguno te podrá hacer mal; porque yo tengo mucho pueblo en esta ciudad.",
      "11": "Y se detuvo allí un año y seis meses, enseñándoles la palabra de Dios.",
      "12": "Y siendo Galión procónsul de Acaya, los Judíos se levantaron de común acuerdo contra Pablo, y le llevaron al tribunal,",
      "13": "Diciendo: Que éste persuade á los hombres á honrar á Dios contra la ley.",
      "14": "Y comenzando Pablo á abrir la boca, Galión dijo á los Judíos: Si fuera algún agravio ó algún crimen enorme, oh Judíos, conforme á derecho yo os tolerara:",
      "15": "Mas si son cuestiones de palabras, y de nombres, y de vuestra ley, vedlo vosotros; porque yo no quiero ser juez de estas cosas.",
      "16": "Y los echó del tribunal.",
      "17": "Entonces todos los Griegos tomando á Sóstenes, prepósito de la sinagoga, le herían delante del tribunal: y á Galión nada se le daba de ello.",
      "18": "Mas Pablo habiéndose detenido aún allí muchos días, después se despidió de los hermanos, y navegó á Siria, y con él Priscila y Aquila, habiéndose trasquilado la cabeza en Cencreas, porque tenía voto.",
      "19": "Y llegó á Efeso, y los dejó allí: y él entrando en la sinagoga, disputó con los Judíos,",
      "20": "Los cuales le rogaban que se quedase con ellos por más tiempo; mas no accedió.",
      "21": "Sino que se despidió de ellos, diciendo: Es menester que en todo caso tenga la fiesta que viene, en Jerusalem; mas otra vez volveré á vosotros, queriendo Dios. Y partió de Efeso.",
      "22": "Y habiendo arribado á Cesarea subió á Jerusalem; y después de saludar á la iglesia, descendió á Antioquía.",
      "23": "Y habiendo estado allí algún tiempo, partió, andando por orden la provincia de Galacia, y la Phrygia, confirmando á todos los discípulos.",
      "24": "Llegó entonces á Efeso un Judío, llamado Apolos, natural de Alejandría, varón elocuente, poderoso en las Escrituras.",
      "25": "Este era instruído en el camino del Señor; y ferviente de espíritu, hablaba y enseñaba diligentemente las cosas que son del Señor, enseñando solamente en el bautismo de Juan.",
      "26": "Y comenzó á hablar confiadamente en la sinagoga: al cual como oyeron Priscila y Aquila, le tomaron, y le declararon más particularmente el camino de Dios.",
      "27": "Y queriendo él pasar á Acaya, los hermanos exhortados, escribieron á los discípulos que le recibiesen; y venido él, aprovechó mucho por la gracia á los que habían creído:",
      "28": "Porque con gran vehemencia convencía públicamente á los Judíos, mostrando por las Escrituras que Jesús era el Cristo."
    },
    "19": {
      "1": "Y ACONTECIO que entre tanto que Apolos estaba en Corinto, Pablo, andadas las regiones superiores, vino á Efeso, y hallando ciertos discípulos,",
      "2": "Díjoles: ¿Habéis recibido el Espíritu Santo después que creísteis? Y ellos le dijeron: Antes ni aun hemos oído si hay Espíritu Santo.",
      "3": "Entonces dijo: ¿En qué pues sois bautizados? Y ellos dijeron: En el bautismo de Juan.",
      "4": "Y dijo Pablo: Juan bautizó con bautismo de arrepentimiento, diciendo al pueblo que creyesen en el que había de venir después de él, es á saber, en Jesús el Cristo.",
      "5": "Oído que hubieron esto, fueron bautizados en el nombre del Señor Jesús.",
      "6": "Y habiéndoles impuesto Pablo las manos, vino sobre ellos el Espíritu Santo; y hablaban en lenguas, y profetizaban.",
      "7": "Y eran en todos como unos doce hombres.",
      "8": "Y entrando él dentro de la sinagoga, hablaba libremente por espacio de tres meses, disputando y persuadiendo del reino de Dios.",
      "9": "Mas endureciéndose algunos y no creyendo, maldiciendo el Camino delante de la multitud, apartándose Pablo de ellos separó á los discípulos, disputando cada día en la escuela de un cierto Tyranno.",
      "10": "Y esto fué por espacio de dos años; de manera que todos los que habitaban en Asia, Judíos y Griegos, oyeron la palabra del Señor Jesús.",
      "11": "Y hacía Dios singulares maravillas por manos de Pablo:",
      "12": "De tal manera que aun se llevaban sobre los enfermos los sudarios y los pañuelos de su cuerpo, y las enfermedades se iban de ellos, y los malos espíritus salían de ellos.",
      "13": "Y algunos de los Judíos, exorcistas vagabundos, tentaron á invocar el nombre del Señor Jesús sobre los que tenían espíritus malos, diciendo: Os conjuro por Jesús, el que Pablo predica.",
      "14": "Y había siete hijos de un tal Sceva, Judío, príncipe de los sacerdotes, que hacían esto.",
      "15": "Y respondiendo el espíritu malo, dijo: A Jesús conozco y sé quién es Pablo: mas vosotros ¿quiénes sois?",
      "16": "Y el hombre en quien estaba el espíritu malo, saltando en ellos, y enseñoreándose de ellos, pudo más que ellos, de tal manera que huyeron de aquella casa desnudos y heridos.",
      "17": "Y esto fué notorio á todos, así Judíos como Griegos, los que habitaban en Efeso: y cayó temor sobre todos ellos, y era ensalzado el nombre del Señor Jesús.",
      "18": "Y muchos de los que habían creído, venían, confesando y dando cuenta de sus hechos.",
      "19": "Asimismo muchos de los que habían practicado vanas artes, trajeron los libros, y los quemaron delante de todos; y echada la cuenta del precio de ellos, hallaron ser cincuenta mil denarios.",
      "20": "Así crecía poderosamente la palabra del Señor, y prevalecía.",
      "21": "Y acabadas estas cosas, se propuso Pablo en espíritu partir á Jerusalem, después de andada Macedonia y Acaya, diciendo: Después que hubiere estado allá me será menester ver también á Roma.",
      "22": "Y enviando á Macedonia á dos de los que le ayudaban, Timoteo y Erasto, él se estuvo por algún tiempo en Asia.",
      "23": "Entonces hubo un alboroto no pequeño acerca del Camino.",
      "24": "Porque un platero llamado Demetrio, el cual hacía de plata templecillos de Diana, daba á los artífices no poca ganancia;",
      "25": "A los cuales, reunidos con los oficiales de semejante oficio, dijo: Varones, sabéis que de este oficio tenemos ganancia;",
      "26": "Y veis y oís que este Pablo, no solamente en Efeso, sino á muchas gentes de casi toda el Asia, ha apartado con persuasión, diciendo, que no son dioses los que se hacen con las manos.",
      "27": "Y no solamente hay peligro de que este negocio se nos vuelva en reproche, sino también que el templo de la gran diosa Diana sea estimado en nada, y comience á ser destruída su majestad, la cual honra toda el Asia y el mundo.",
      "28": "Oídas estas cosas, llenáronse de ira, y dieron alarido diciendo: ­Grande es Diana de los Efesios!",
      "29": "Y la ciudad se llenó de confusión; y unánimes se arrojaron al teatro, arrebatando á Gayo y á Aristarco, Macedonios, compañeros de Pablo.",
      "30": "Y queriendo Pablo salir al pueblo, los discípulos no le dejaron.",
      "31": "También algunos de los principales de Asia, que eran sus amigos, enviaron á él rogando que no se presentase en el teatro.",
      "32": "Y otros gritaban otra cosa; porque la concurrencia estaba confusa, y los más no sabían por qué se habían juntado.",
      "33": "Y sacaron de entre la multitud á Alejandro, empujándole los Judíos. Entonces Alejandro, pedido silencio con la mano, quería dar razón al pueblo.",
      "34": "Mas como conocieron que era Judío, fué hecha un voz de todos, que gritaron casi por dos horas: ­Grande es Diana de los Efesios!",
      "35": "Entonces el escribano, apaciguado que hubo la gente, dijo: Varones Efesios ¿y quién hay de los hombres que no sepa que la ciudad de los Efesios es honradora de la gran diosa Diana, y de la imagen venida de Júpiter?",
      "36": "Así que, pues esto no puede ser contradicho, conviene que os apacigüéis, y que nada hagáis temerariamente;",
      "37": "Pues habéis traído á estos hombres, sin ser sacrílegos ni blasfemadores de vuestra diosa.",
      "38": "Que si Demetrio y los oficiales que están con él tienen negocio con alguno, audiencias se hacen, y procónsules hay; acúsense los unos á los otros.",
      "39": "Y si demandáis alguna otra cosa, en legítima asamblea se pueda decidir.",
      "40": "Porque peligro hay de que seamos argüidos de sedición por hoy, no habiendo ninguna causa por la cual podamos dar razón de este concurso.",
      "41": "Y habiendo dicho esto, despidió la concurrencia."
    },
    "20": {
      "1": "Y DESPUÉS que cesó el alboroto, llamando Pablo á los discípulos habiéndoles exhortado y abrazado, se despidió, y partió para ir á Macedonia.",
      "2": "Y andado que hubo aquellas partes, y exhortádoles con abundancia de palabra, vino á Grecia.",
      "3": "Y después de haber estado allí tres meses, y habiendo de navegar á Siria, le fueron puestas asechanzas por los Judíos; y así tomó consejo de volverse por Macedonia.",
      "4": "Y le acompañaron hasta Asia Sopater Bereense, y los Tesalonicenses, Aristarco y Segundo; y Gayo de Derbe, y Timoteo; y de Asia, Tychîco y Trófimo.",
      "5": "Estos yendo delante, nos esperaron en Troas.",
      "6": "Y nosotros, pasados los días de los panes sin levadura, navegamos de Filipos y vinimos á ellos á Troas en cinco días, donde estuvimos siete días.",
      "7": "Y el día primero de la semana, juntos los discípulos á partir el pan, Pablo les enseñaba, habiendo de partir al día siguiente: y alargó el discurso hasta la media noche.",
      "8": "Y había muchas lámparas en el aposento alto donde estaban juntos.",
      "9": "Y un mancebo llamado Eutichô que estaba sentado en la ventana, tomado de un sueño profundo, como Pablo disputaba largamente, postrado del sueño cayó del tercer piso abajo, y fué alzado muerto.",
      "10": "Entonces descendió Pablo, y derribóse sobre él, y abrazándole, dijo: No os alborotéis, que su alma está en él.",
      "11": "Después subiendo, y partiendo el pan, y gustando, habló largamente hasta el alba, y así partió.",
      "12": "Y llevaron al mozo vivo, y fueron consolados no poco.",
      "13": "Y nosotros subiendo en el navío, navegamos á Assón, para recibir de allí á Pablo; pues así había determinado que debía él ir por tierra.",
      "14": "Y como se juntó con nosotros en Assón, tomándole vinimos á Mitilene.",
      "15": "Y navegamos de allí, al día siguiente llegamos delante de Chîo, y al otro día tomamos puerto en Samo: y habiendo reposado en Trogilio, al día siguiente llegamos á Mileto.",
      "16": "Porque Pablo se había propuesto pasar adelante de Efeso, por no deternerse en Asia: porque se apresuraba por hacer el día de Pentecostés, si le fuese posible, en Jerusalem.",
      "17": "Y enviando desde Mileto á Efeso, hizo llamar á los ancianos de la iglesia.",
      "18": "Y cuando vinieron á él, les dijo: Vosotros sabéis cómo, desde el primer día que entré en Asia, he estado con vosotros por todo el tiempo,",
      "19": "Sirviendo al Señor con toda humildad, y con muchas lágrimas, y tentaciones que me han venido por las asechanzas de los Judíos:",
      "20": "Cómo nada que fuese útil he rehuído de anunciaros y enseñaros, públicamente y por las casas,",
      "21": "Testificando á los Judíos y á los Gentiles arrepentimiento para con Dios, y la fe en nuestro Señor Jesucristo.",
      "22": "Y ahora, he aquí, ligado yo en espíritu, voy á Jerusalem, sin saber lo que allá me ha de acontecer:",
      "23": "Mas que el Espíritu Santo por todas las ciudades me da testimonio, diciendo que prisiones y tribulaciones me esperan.",
      "24": "Mas de ninguna cosa hago caso, ni estimo mi vida preciosa para mí mismo; solamente que acabe mi carrera con gozo, y el ministerio que recibí del Señor Jesús, para dar testimonio del evangelio de la gracia de Dios.",
      "25": "Y ahora, he aquí, yo sé que ninguno de todos vosotros, por quien he pasado predicando el reino de Dios, verá más mi rostro.",
      "26": "Por tanto, yo os protesto el día de hoy, que yo soy limpio de la sangre de todos:",
      "27": "Porque no he rehuído de anunciaros todo el consejo de Dios.",
      "28": "Por tanto mirad por vosotros y por todo el rebaño en que el Espíritu Santo os ha puesto por obispos, para apacentar la iglesia del Señor, la cual ganó por su sangre.",
      "29": "Porque yo sé que después de mi partida entrarán en medio de vosotros lobos rapaces, que no perdonarán al ganado;",
      "30": "Y de vosotros mismos se levantarán hombres que hablen cosas perversas, para llevar discípulos tras sí.",
      "31": "Por tanto, velad, acordándoos que por tres años de noche y de día, no he cesado de amonestar con lágrimas á cada uno.",
      "32": "Y ahora, hermanos, os encomiendo á Dios, y á la palabra de su gracia: el cual es poderoso para sobreedificar, y daros heredad con todos los santificados.",
      "33": "La plata, ó el oro, ó el vestido de nadie he codiciado.",
      "34": "Antes vosotros sabéis que para lo que me ha sido necesario, y á los que están conmigo, estas manos me han servido.",
      "35": "En todo os he enseñado que, trabajando así, es necesario sobrellevar á los enfermos, y tener presente las palabras del Señor Jesús, el cual dijo: Más bienaventurada cosa es dar que recibir.",
      "36": "Y como hubo dicho estas cosas, se puso de rodillas, y oró con todos ellos.",
      "37": "Entonces hubo un gran lloro de todos: y echándose en el cuello de Pablo, le besaban,",
      "38": "Doliéndose en gran manera por la palabra que dijo, que no habían de ver más su rostro. Y le acompañaron al navío."
    }
  }
};

